### ISSUE TITLE
Screen stops updating after YouTube videos enter fullscreen

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2406] opened 2016-10-29 04:24 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

All

---

#### Description:

On 2016-10-28 04:14, Manuel Amador (Rudd-O) wrote:
>> On Wednesday, October 26, 2016 at 5:15:53 PM UTC-4, jamie wrote:
>>> does not matter if I use fedora, debian or whonix ... whenever I press fullscreen on any youtube video the brower freezes..
>>>
>>> it also does not matter which browser I use firefox, chromium,...
>>> all of them freeze.
> 
> I can confirm this issue.  It's not that they freeze, they continue to
> run and you can see window updates when you resize the window, but it's
> simply that they stop updating after hitting that damn fullscreen
> button.

[Full thread](https://groups.google.com/d/topic/qubes-users/LkRUbPYg_eA/discussion)

---

#### Related issues:

Apparently not a duplicate of #1502

**Comment by marmarek** [comment] 2016-10-29 10:49
It looks exactly like a duplicate of #1502

**Closed by marmarek** 2016-10-29 10:49 UTC
Labels: bug, C: gui-virtualization, P: major
