### ISSUE TITLE
IPv6 routing between appvm and an IPv6-capable proxyvm

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2570] opened 2017-01-12 16:27 UTC
#### Qubes OS version 

( R3.2 ):

#### Affected TemplateVMs 

presumably all of them, tested debian 8, fedora-24

---

### Expected behavior: 

some kind of basic IPv6 forwarding to maybe finally occur between VMs to allow NATing of ipv6 from an appVM through a proxyvm with (confirmed) ipv6 capability

### Actual behavior:
no ipv6 connectivity for appvm

### Steps to reproduce the behavior:

Create proxyvm with VPN as per existing instructions. No additional firewall changes made.

Run browser inside proxyvm and use ipleak.net and ipv6-test.com/ to confirm that 
1) VPN is working correctly (for apps inside proxyvm)
2) that ipv6 is working through VPN (ipv6 working, the address displayed is one of VPN service's)
3) connect an app VM to the proxyvm (either directly or through an additional small firewall VM, results won't differ)
4) retry steps 1 and 2 in appvm
5) observe complete lack of IPv6 connectivity in appvm

### General notes:
I kind of understand why a privacy and security focused OS would treat ipv6 as cancer :)
But sooner rather than later ipv6 support will become vital.

"nattish-ing" ipv6 through a chain along the lines of 
[IPv6-needy-AppVM] -> [dedicated-mini-firewall-VM] -> [IPv6-capable-proxyvm] -> [IPv4-only-net-vm]
seems like a reasonable solution

---

**Comment by marmarek** [comment] 2017-01-12 16:42
This is duplicate of #718

**Closed by marmarek** 2017-01-12 16:42 UTC
