### ISSUE TITLE
R4.1.2-rc1 installation: Initial Setup screen shows Qubes 4.1.1 version number

### ISSUE THREAD

**Issue by eaon** [QubesOS/qubes-issues#8059] opened 2023-02-23 12:19 UTC
### Qubes OS release

R4.1.2-rc1

### Brief summary

![image](https://user-images.githubusercontent.com/201369/220903423-6194bbaa-b8be-4ea1-bea8-207a7ede58ec.png)

### Steps to reproduce

Reboot after installation, boot new system, see configuration screen 

### Expected behavior

Show 4.1.2 in the upper right corner :smile:

### Actual behavior

Shows 4.1.1 in the upper right corner

**Comment by andrewdavidwong** [comment] 2023-02-23 14:13
Duplicate of #8039

**Comment by andrewdavidwong** [comment] 2023-02-23 14:14
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-02-23 14:14 UTC
Labels: T: bug, P: default
