### ISSUE TITLE
Describe new widgets - tooltips?

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3509] opened 2018-01-30 15:33 UTC
#### Qubes OS version:

R4.0

---

There are two (and in the future maybe more) new widgets in tray by default:
 - domains widget
 - devices widget

Currently there is no information what those are, user need to guess based on available actions there.
Proposed solution: add a tooltip with short description (maybe just names listed above). Or maybe also a title to menus opened there?

**Comment by andrewdavidwong** [comment] 2018-01-31 01:41
Related to (and possible duplicate of) #2211.

**Comment by marmarta** [comment] 2018-02-20 19:00
It would seem that AppIndicators (the Gtk thingy we use for those widgets) don't support tooltips. I'll look into how much work would it be to convert the widgets into something with tooltips.

**Closed** 2018-12-06 13:11 UTC
Labels: C: manager/widget, P: minor, enhancement, ux
