### ISSUE TITLE
Opening a .mp3 in DisposableVM fails poorly

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1773] opened 2016-02-24 11:34 UTC
Upon trying to open an `.mp3` file in a DisposableVM, I experience the following error messages:

A modal dialogue shows:

```
qopen-in-vm: Fatal error: send file to dispVM (error type: Broken pipe)
```

And the Qubes notification window shows an item:

```
DVM savefile creation failed
```

Neither of these are user friendly, easy to understand, nor explain what steps a user can do to provide help. I _assume_ this error means that Qubes does not understand how to handle this mime type to the correct player securely through DVM, is that correct?

**Comment by marmarek** [comment] 2016-02-24 17:23
There is (almost) clear message in that case:
```
Unable to handle mimetype of the requested file (exit status: %d)
```

Those you've cited are something else. Not sure what really happened
there yet.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment] 2016-05-19 07:39
Possibly related to #1603, if there's a general problem with DispVM MIME type handlers.

**Comment by andrewdavidwong** [comment] 2016-12-23 09:40
It sounds like there just wasn't a suitable media player for the mp3 in the DispVM. What happens if you install one in the DVM template (or the template on which the DVM template is based), regenerate the DispVM, and try again?

**Comment by unman** [comment] 2019-07-10 14:56
@andrewdavidwong This is over 3 years old . It isn't due to a missing mime handler: as Marek pointed out, that's well handled, as I've just confirmed.

I found other reports of similar issues in 3.2rc1, attributable to errors in disposableVM creation process.

I think it is safe to close this.

**Comment by andrewdavidwong** [comment] 2019-07-11 00:28
Closing this for now due to the prolonged lack of activity. If you believe this is a mistake, or if anyone would like this issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-07-11 00:28 UTC
Labels: P: minor, T: bug, ux
