### ISSUE TITLE
R4.0-rc3 installer doesn't run on Macbook Pro 11,4 (Mid 2015 Retina)

### ISSUE THREAD

**Issue by andzaytsev** [QubesOS/qubes-issues#3427] opened 2017-12-24 03:22 UTC
#### Qubes OS version:

R4.0-rc3

#### Affected TemplateVMs: 

N/A

---

### Steps to reproduce the behavior:

I am trying to install the latest release of Qubes 4.0 (rc3) on my Macbook Pro Mid 2015 Retina (MacBook Pro 11,4) following the suggestions [here](https://www.qubes-os.org/doc/macbook-troubleshooting/#macbook-pro-retina-15-inch-mid-2015-macbookpro-115) (those are for 3.2, but I expected them to work on 4.0 as well).

First, I installed rEFInd 0.11.2 on my Mac using the Recovery mode. After that, I created a bootable Qubes USB-drive using Unetbootin and the latest iso from the website.

REFInd showed all the USB boot options correctly, so I chose EFI\BOOT\xen.efi from the USB-drive (I tried all the other options, but got the same result).

### Expected behavior:

I expected an installer to appear to proceed with the installation of the OS.

### Actual behavior:

Instead of the installer, I saw a lot of ACPI errors, following the prompt for the emergency console. It also said that /dev/root doesn't exist. I was able to copy the rdsosreport.txt (the boot log) onto my local partition and am attaching it here.

I believe the most relevant errors are the following:

```
[    0.000000] localhost kernel: ACPI BIOS Warning (bug): 32/64X length mismatch in FADT/Gpe0Block: 128/0 (20170531/tbfadt-603)


[    0.067254] localhost kernel: ACPI: [Firmware Bug]: BIOS _OSI(Linux) query ignored
[    0.067537] localhost kernel: ACPI Error: Needed type [Reference], found [Integer] ffff880464db0ca8 (20170531/exresop-103)
[    0.067537] localhost kernel: ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands for [OpcodeName unavailable] (20170531/dswexec-461)
[    0.067537] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU0._PDC, AE_AML_OPERAND_TYPE (20170531/psparse-550)`

[    0.229058] localhost kernel: pci 0000:00:01.0:   bridge window [mem 0xa0b00000-0xa0bfffff]
[    0.229068] localhost kernel: pci 0000:06:00.0: BAR 15: no space for [mem size 0x00200000 64bit pref]
[    0.229069] localhost kernel: pci 0000:06:00.0: BAR 15: failed to assign [mem size 0x00200000 64bit pref]
[    0.229070] localhost kernel: pci 0000:06:04.0: BAR 14: no space for [mem size 0x00200000]
[    0.229071] localhost kernel: pci 0000:06:04.0: BAR 14: failed to assign [mem size 0x00200000]


[    1.819719] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.819745] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU1._CST, AE_NOT_FOUND (20170531/psparse-550)
[    1.819843] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.819869] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU2._CST, AE_NOT_FOUND (20170531/psparse-550)
[    1.819947] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.819972] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU3._CST, AE_NOT_FOUND (20170531/psparse-550)
[    1.820098] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.820124] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU4._CST, AE_NOT_FOUND (20170531/psparse-550)
[    1.820228] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.820253] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU5._CST, AE_NOT_FOUND (20170531/psparse-550)
[    1.820339] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.820364] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU6._CST, AE_NOT_FOUND (20170531/psparse-550)
[    1.820463] localhost kernel: ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUND (20170531/psargs-364)
[    1.820488] localhost kernel: ACPI Error: Method parse/execution failed \_PR.CPU7._CST, AE_NOT_FOUND (20170531/psparse-550)`
```
[rdsosreport.txt](https://github.com/QubesOS/qubes-issues/files/1584582/rdsosreport.txt)

### General notes:

It seems I have the exact same machine referenced in the [Macbook Troubleshooting](https://www.qubes-os.org/doc/macbook-troubleshooting/#macbook-pro-retina-15-inch-mid-2015-macbookpro-115), so I'm wondering if this is a specific R4.0 issue. In addition, I believe other Linux distros can be installed on this machine, so this seems to be a Qubes-specific issue.

---

**Comment by matthazinski** [comment] 2017-12-27 05:17
I just installed 4.0-RC3 on a Macbook Pro 11,4 and didn't hit any major issues during the installer.

Lack of Unetbootin support is a known issue (#1415).

**Comment by andzaytsev** [comment] 2017-12-27 17:51
Interesting! What tool did you use to write the ISO to a USB drive?

**Comment by matthazinski** [comment] 2017-12-27 19:09
I just used dd:

`sudo dd if=Downloads/Qubes-R4.0-rc3-x86_64.iso of=/dev/rdisk2 bs=1m`

**Comment by ideologysec** [comment] 2017-12-29 18:46
Etcher (https://etcher.io) should also work, but definitely use dd or some other block copying device (Unetbootin is...strange).

**Comment by eduncan911** [comment] 2018-02-11 18:06
I've been trying to get Qubes installed on an MacBook Pro 11,3 15" Retina Nvidia 750M GPU for about a year myself.

Qubes' 4.0 rc4 installer actually works perfectly flashed to a USB3 stick.  Used  other `dd` and Etcher, and they both boot the installer just fine.  I prefer Etcher as it validates when done and has caught some bad flashes.

Under macOS, if not using Etcher: 

`sudo dd if=~/Downloads/Qubes-R4.0-rc34-x86_64.iso of=/dev/rdisk2 bs=1M`

(Note that I have the GNUTools utils loaded under brew and use only the GNU dd version)

I can get Qubes installed on both the internal SSD and an external M.2 SSD I have in an USB3 enclosure.

However, my problem is that the Anaconda installer does not create the proper `/EFI/Qubes/` entries, leaving them blank and empty.  Instead, it always boots to the dreaded `grub>` prompt.

For a few days I've been struggling to figure out the properties Xen + Fedora + EFI configuration to get it to load without success.  But not having a valid 4.0rc4 install anywhere means I can't create a rescue disk to even debug this.  

The only way I've been able to debug this is to:

* Install Qubes 4.0rc4 (either on SSD or external SSD)
* Do not exit installer: instead of clicking Finish, press Fun+Ctrl+Alt-F2 to get to the prompt.
* `chroot /mnt/sysimage` to get into the system and configure and test.
* Reboot and home it works!  Which, it never does yet...  Very time consuming.

There is also issue #3505 from a couple of days ago that looks to have bypassed Grub completely for EFI and just boot EFI directly - which is exactly what I'm after!

**Comment by marmarek** [comment] 2018-02-28 23:06
Thanks to @eduncan911 this should be fixed by QubesOS/qubes-installer-qubes-os#20. @andzaytsev  If you're brave enough, you can grab iso from https://openqa.qubes-os.org/tests/210/asset/iso/Qubes-DVD-x86_64-20180228.iso and try.

**Comment by eduncan911** [comment] 2018-12-01 20:35
@andrewdavidwong i think we can close this one as I've confirmed the installer works on mid-2014 Macbook Pro Retina and on a mid-2015 Macbook Pro Retina (which this issue was for).

Note: there's still some roadblocks to actually using Qubes on these devices, such as the eluding Broadcom drivers for the wifi and thunderbolt - the catch22.  But that's out of scope of this issue.

**Comment by andrewdavidwong** [comment] 2018-12-01 22:17
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-12-01 22:17 UTC
Labels: C: doc, C: installer, bug

**Comment by CODE33301** [comment] 2020-10-27 03:54
I have that ACPI Error.

![image](https://user-images.githubusercontent.com/46226136/97255170-f0e04780-1807-11eb-9162-e15eb212cb7d.jpeg)

I have an ASUS R540N Notebook PC. I don't understand why I'm getting this error.

**Comment by andrewdavidwong** [comment] 2020-10-28 02:34
> I have that ACPI Error.
> 
> [...]
> 
> I have an ASUS R540N Notebook PC. I don't understand why I'm getting this error.
> 
> I'm trying to install qubes is 4.0.3

Your error looks different from this one. Yours says `ACPI Error: No handler [...]` (or at least one of them does), whereas this one doesn't appear to say that. Searching this issue tracker for [`ACPI Error: No handler`](https://github.com/QubesOS/qubes-issues/issues?q=is%3Aissue+%22ACPI+Error%3A+No+handler%22) returns five other issues (but not this one). You might want to have a look at those instead.
