### ISSUE TITLE
Screenshot tool does not work when menus are open R4.0

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#3759] opened 2018-03-29 14:59 UTC
### Affected component(s): 
Dom0

---

### Steps to reproduce the behavior:

Open a menu, try to take a screenshot

### Expected behavior:

Screenshot dialogue opens

### Actual behavior:

Nothing happens

### General notes:

---

**Comment by esote** [comment] 2018-11-28 02:34
@JPL1 I just tested this and was not able to reproduce. In order to take a screenshot of an open menu in dom0 while also taking a screenshot, I added a 1 second delay and it correctly captured the screen. Do you still experience this? If so, does it also happen with other desktop environments? (if not, it's an XFCE bug)

**Comment by esote** [comment] 2018-12-18 23:53
@andrewdavidwong Due to lack of response (& cannot reproduce), should this issue be closed?

**Comment by unman** [comment] 2018-12-18 23:57
Unable to reproduce with KSnapshot

**Comment by andrewdavidwong** [comment] 2018-12-19 06:04
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-12-19 06:04 UTC
Labels: C: other, bug
