### ISSUE TITLE
Restored DisposableVMs halting immediately after start (intermittent issue)

### ISSUE THREAD

**Issue by tetrahedras** [QubesOS/qubes-issues#5143] opened 2019-07-06 14:27 UTC
**Qubes OS version**
Qubes release 4.0 (R4.0)
Latest updates installed.

**Affected component(s) or functionality**
DispVMs/DisposableVMs

**Brief summary**
A phenomenally annoying bug. After restoring Qubes from backup, DispVMs (sometimes, not always) refuse to start. I will click on the menu item "whonix-ws-14-dvm1" and the usual "dispXXX is starting" notification will come up. Then (simultaneously) there will be the notifications "dispXXX has started" and "dispXXX has halted."

Unfortunately the Xen console logs appear to end as soon as the VM halts -- `sudo xl console dispXXX` produces messages up until, but not including, the point where the VM halts. There is nothing in the console logs that I can see which suggests anything wrong!

I have also tried changing the DispVM to use a fresh `whonix-ws-14` template (including replacing the installed template with `qubes-dom0-update --action=reinstall`) but that did not solve the problem. Moreover, other restored DispVM templates based on e.g Fedora 29 exhibit the same behaviour,

Trying to start multiple instances of the DispVM in quick succession results in e.g one of three DispVM instances starting correctly, and I can in general just keep trying and trying a given DispVM until it finally goes.

Unfortunately, this workaround only seems to work for Whonix-WS based DispVMs. Fedora 29 based DispVMs halt on boot in all cases. For those templates, if I e.g launch a terminal from the menu, the template will proceed with boot all the way up until the terminal window appearing on screen. However, the terminal window will vanish almost as soon as it appears, and the template will halt immediately afterwards. Launching several in quick succession results in them all failing.

Finally, for some reason Whonix-WS images are occasionally very slow (Tor Browser locks up and lags) since the restore. 

**To Reproduce**
1. Select the Qubes Applications menu (top-left)
2. Click whonix-ws-14-dvm or another DispVM
3. Click Tor Browser (AnonDist)
4. Wait for DispVM to start, or not
5a. If Tor Browser launches successfully, keep working
5b. If the "dispXXXX is halting" notification is displayed, try again until Tor Browser launches

**Expected behavior**
Tor Browser (or another DispVM application) launches every time

**Actual behavior**
DispVM goes into "halting" mode instead of the application launching, approximately 2/3 of the time.

**Screenshots**
n/a

**Additional context**
Problem cropped up after restoring from backup

**Solutions you've tried**
Try rapid-fire opening the DispVM application 3 times in a row, resulting in 3 DispVMs starting up. Of these 3, one will usually open normally, the other 2 will halt/crash.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
n/a

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/3213
Very similar issue -- but it looks like that issue has already been fixed.

**Comment by marmarek** [comment] 2019-07-06 20:19
This looks similar to #5121. Check if `xl dmesg` contains message like `p2m_pod_demand_populate: Dom10 out of PoD memory!`

**Comment by tetrahedras** [comment] 2019-07-11 14:02
Indeed that error does appear in `xl dmesg`, and the [solution suggested in that issue](https://github.com/QubesOS/qubes-issues/issues/5121#issuecomment-506652055) resolves the problem for me:

> ok, so I increased the "initial memory" of the DispVM Template = whonix-ws-14-dvm to "1000M" (from, iirc, 400M), and I was successfully able to start torbrowser in a new whonix DispVM via the qvm-run command three times in a row!

**Comment by tetrahedras** [comment] 2019-07-11 14:09
Unfortunately increasing the initial memory does not resolve the issue with plain fedora-29 based templates halting at start. For those templates, the initial application (e.g terminal) window appears, but disappears as soon as it appears. I see no new messages in `xl dmesg` after trying to start such a template and having it halt/crash/catch fire.

**Comment by marmarek** [comment] 2019-07-11 14:16
Gnome terminal is incompatible with DisposableVM, see #2581. Try different application.

**Comment by tetrahedras** [comment] 2019-07-12 11:48
Ok, using XTerm instead of Gnome Terminal worked. Thanks!

**Comment by unman** [comment] 2019-07-12 12:26
@tetrahedras Are you happy to close this now?

**Comment by tetrahedras** [comment] 2019-07-12 15:54
Yes, you can close it.

**Closed** 2019-07-13 00:25 UTC
Labels: C: core, P: default, T: bug

**Comment by andrewdavidwong** [comment] 2019-07-13 00:26
Closing as a duplicate of #2581.
