### ISSUE TITLE
Focus / Popup bug prevents use of SweetHome

### ISSUE THREAD

**Issue by goulou** [QubesOS/qubes-issues#3386] opened 2017-12-10 11:41 UTC
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

debian-9 (stretch)

---

### Steps to reproduce the behavior:

-Install sweethome3D in vm or templatevm
-start it
-try to create a wall

### Expected behavior:

-a tooltip opens showing the size/orientation of the wall, and gets updated while you drag the mouse to create it
-once you release the mouse button, the wall gets created and the tooltip closed

### Actual behavior:

-the tooltip appears and closes immediately (even though you don't release the mouse button), wall editing is canceled, you cannot create the wall

### General notes:

This is certainly due to a focus problem between the main windows and the tooltip : the tooltip gains the focus, and the main window thinks the editing is cancelled. In the expected behaviour, the tooltip should appear in front of the window, but without gaining focus.

---

**Comment by andrewdavidwong** [comment] 2017-12-10 19:51
Does changing your window focus settings (in dom0) have any effect?

**Comment by goulou** [comment] 2017-12-10 21:20
Indeed, disabling the option "Automatically give focus to newly created windows" in Menu/System Tools/Window Manager/Focus did the trick!
I'm not sure what the default should be though, and if I should expect the default mode to work nevertheless : as far as I understand it, this option is a "user-experience option", not a bugfixing one... :-)
I let you close the bug if you think this "bugfix" is acceptable.

Goulou.

**Comment by andrewdavidwong** [comment] 2017-12-10 21:48
It sounds like the problem is specific to a small class of programs of which SweetHome is a member, so I'll close this as resolved.

As for the default window focus setting, that's driven primarily by balancing security concerns with user expectations, and we have other issues to address this, such as #3267.

**Closed by andrewdavidwong** 2017-12-10 21:48 UTC
Labels: bug, C: desktop-linux, UX
