### ISSUE TITLE
Change default (pre-installed) Fedora template flavor from GNOME to Xfce

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8435] opened 2023-08-18 11:11 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

I suggest doing this firstly to save space on users' disks, and secondly to avoid performance problems.

I had constantly too much cpu consumption when using some gnome app.

There were also many performance issues specifically with nautilus

### The value to a user, and who that user might be
Space saver and battery saver

**Comment by andrewdavidwong** [comment] 2023-08-18 12:49
I think @marmarek was already [thinking about doing this](https://forum.qubes-os.org/t/default-pre-installed-template-flavor-considering-change-from-gnome-to-xfce/20269), but I couldn't find an existing issue for it.

**Comment by Middenvaus** [comment] 2023-08-18 15:45
Let's then invite him to this issue and discuss this issue in more detail.

**Comment by DemiMarie** [comment] 2023-08-18 16:08
> I had constantly too much cpu consumption when using some gnome app.
> 
> There were also many performance issues specifically with nautilus

Yup, GTK4 is horrible for systems (like Qubes OS!) that use software rendering.

**Comment by Middenvaus** [comment] 2023-08-18 16:20
I myself have already disabled opengl and hardware acceleration wherever possible. Is it possible to set opengl settings globally for all qt applications?

**Comment by marmarek** [comment] 2023-08-18 18:02
Duplicate of https://github.com/QubesOS/qubes-issues/issues/8435

**Comment by DemiMarie** [comment] 2023-08-18 21:09
@marmarek did you get the issue number wrong?  An issue can’t be a duplicate of itself.

**Comment by Middenvaus** [comment] 2023-08-18 21:55
> Duplicate of #8435

you are very tired. time to give yourself a break

**Comment by andrewdavidwong** [comment] 2023-08-19 02:11
> Let's then invite him to this issue and discuss this issue in more detail.

I appreciate your enthusiasm, but please note that the issue tracker (qubes-issues) is not intended to serve as a discussion venue. Instead, we've created a designated [forum](https://forum.qubes-os.org/) for discussion and [support](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) In this case, the [existing forum thread](https://forum.qubes-os.org/t/default-pre-installed-template-flavor-considering-change-from-gnome-to-xfce/20269) would be a perfect place to discuss this. Thank you for your understanding!

**Comment by andrewdavidwong** [comment] 2023-08-19 02:13
@marmarek, did you mean to mark this as a duplicate of #7784? That's the closest issue I've been able to find.

**Comment by marmarek** [comment] 2023-08-19 09:12
> did you mean to mark this as a duplicate of #7784?

Ofc, wrong paste...

**Comment by andrewdavidwong** [comment] 2023-08-19 13:35
Duplicate of #7784

**Comment by andrewdavidwong** [comment] 2023-08-19 13:35
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-08-19 13:35 UTC
Labels: T: enhancement, C: Fedora, P: default, C: Fedora XFCE
