### ISSUE TITLE
Fresh Fedora 30 TemplateVM install gives "Failed to synchronize cache for repo 'fedora-modular'   

### ISSUE THREAD

**Issue by RenatoLopes771** [QubesOS/qubes-issues#5280] opened 2019-08-29 23:05 UTC
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
4.0

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
Using dnf on Fedora 30 Template VM

**Brief summary**
_A clear and concise summary of the bug._
Just installed the Fedora 30 Official Template VM and whenever I use a dnf-related command the command line gives me:
"Error: Failed to synchronize cache for repo 'fedora-modular'

**To Reproduce**
_Steps to reproduce the behavior:_
Use any dnf type of command on the Fedora 30 official Template VM

**Expected behavior**
_A clear and concise description of what you expected to happen._
Execution of the command

**Actual behavior**
_What actually happened (instead of what you expected to happen)._
The error described above

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._
None

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._
Qubes has a answer to this error on the FAQ that it relates to the Fedora, but it is an official VM. It shipped broken.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._
https://github.com/QubesOS/qubes-issues/issues/3737

**Comment by underlineGalaxy** [comment] 2019-08-29 23:06
Ok I pressed enter by accident, I'll fill in the details now.

**Comment by andrewdavidwong** [comment] 2019-08-30 21:27
Possible duplicate of #4973.

> Qubes has a answer to this error on the FAQ that it relates to the Fedora, but it is an official VM. It shipped broken.

I don't think that changes the answer:

https://www.qubes-os.org/faq/#i-keep-getting-failed-to-synchronize-cache-for-repo-errors-when-trying-to-update-my-fedora-templates

If it's due to a network problem or a problem with the Fedora update servers, then there is nothing broken that ships with Qubes. In that case, it's a problem with the external infrastructure with which your Fedora VM is attempting to communicate.

That's the general answer to "Failed to synchronize cache for repo" errors. I don't have enough information to determine if that's what's happening here. Best to try again a bit later or from a different connection. Are you using `sys-whonix` for updates? If you're willing to try updating via `sys-firewall` instead, that's worth trying.

**Comment by underlineGalaxy** [comment] 2019-08-30 22:02
@andrewdavidwong I have been using SYS firewall, but I will try whonix now.
Funny though, whonix broke my updates on Dom0 having to make me switch to SYS-firewall for that...

Also: I remember reading somewhere that it might have been because qubes is using the 'fedora-modular' repo, maybe a Dev could make a fedora30 templatevm using the standard repo instead to see if it works? The issue you mentioned was made 5 months ago and its unlikely that they would just not fix it for 5 months.

**Comment by Jeeppler** [comment] 2019-09-02 07:15
I had the same problem. I think it is related to the `tinyproxy` as described in #4973 or the update proxy mechanism. The reason being that TemplateVMs do not have network access through `sys-firewall`, instead they use the update proxy mechanism.

I had to make some changes to configuration files. I don't remember what I had to do on top of my hat. Maybe I can figure it out again.

**Comment by underlineGalaxy** [comment] 2019-09-03 21:24
@Jeeppler I would be really glad if you could guide me.

I can use my OS as a way for you to test it but honestly qubes 4.0 already ships with this broken thing so it's better if you download it and test on a vm

**Comment by Aporbel** [comment] 2019-09-04 10:26
Have same issue. Also this issue appear when updating whonix.

**Comment by andrewdavidwong** [comment] 2019-09-05 01:42
> Also this issue appear when updating whonix.

What do you mean? Whonix is Debian-based, so it would not use the fedora-modular repos.

**Comment by Aporbel** [comment] 2019-09-05 09:09
> > Also this issue appear when updating whonix.
> 
> What do you mean? Whonix is Debian-based, so it would not use the fedora-modular repos.

Issue with fedora-29 - solved. Maybe was trouble on fedora side. Whonix - he don't want update from qubes-manager gui, whonix-gw-14 ask for update, but he haven't network, Can I provide network him for update? Or it willn't secure? If not, how I can update whonix with secure method?

**Comment by andrewdavidwong** [comment] 2019-09-06 02:25
> Issue with fedora-29 - solved in my case. Maybe was troubles on fedora side.

Ok, that supports the possibility I mentioned above (https://github.com/QubesOS/qubes-issues/issues/5280#issuecomment-526755659).

> Whonix-gw-14 ask for update, but he haven't network, Can I provide network him for update? Or it willn't secure? If not, how I can update whonix with secure method?

Whonix templates can be updated normally through the Qubes Update widget. If that's not working for you, please consult the Whonix documentation or ask on the Whonix forums.

**Comment by Jeeppler** [comment] 2019-09-06 10:55
@andrewdavidwong do you know by chance, where I can find the Salt scripts for updating Whonix from 14 to 15?

**Comment by andrewdavidwong** [comment] 2019-09-07 06:34
> @andrewdavidwong do you know by chance, where I can find the Salt scripts for upgrading Whonix from 14 to 15?

I recommend following these instructions:

https://www.whonix.org/wiki/Upgrading_Whonix_14_to_Whonix_15

**Comment by Jeeppler** [comment] 2019-09-07 22:24
@andrewdavidwong thanks for pointing out the instructions. I already followed them and they work. That is not the issue. However, that was not my question. I actually want to see the source code for the Salt scripts. Just to verify it has nothing to do with the problems discussed in this issue.

**Comment by marmarek** [comment] 2019-09-07 22:51
@Jeeppler which upgrade process? The one linked by @andrewdavidwong does not use salt.

**Comment by Jeeppler** [comment] 2019-09-08 14:39
This is what I did:

0. Download Qubes OS 4
1. Install Qubes OS on new computer
2. Selected to install Fedora 29 and Debian 9 Template
3. Installed Fedora 30 template
4. Upgraded Whonix from 14 to 15 via Salt
5. Upgraded Debian Template from Debian 9 "Stretch" to Debian 10 "Buster"
6. Changed my sys-firewall to be based on Fedora 30 Template
7. Created new "fork" of Fedora 30 Template for applications (cloning the template)
8. Tried to upgrade the template Fedora 30 -> did not work, received same error as described in this issue -> refocused on other parts
9. Played around with USB, Networking and Wifi (sys-usb-net or better sys-net + sys-usb) -> was confused
*. Rebooted and changed several things, networking, usb, sys-firewall etc. -> happy that my system started working in the way I wanted it to work
n. Got the  Ferdora 30 Template updates to work -> no idea what I changed resolved the issue with the Fedora 30 Template

*Note: I did not use Tor to update Dom0 or any VMs, except for Whonix itself. Tor should not be the problem in this case.*

@marmarek I upgraded Whonix after installing the Fedora 30 Template (Step 3) and before doing something with the Fedora 30 Template (Step 6+). I just wanted to cross-check if the Whonix Salt scripts for upgrading Whonix manipulate any system configuration. Just, a random idea.

I did the Debian 9 to 10 upgrade manually in the Template VM. Therefore, I did not change any configuration files in Dom0.

**Comment by andrewdavidwong** [comment] 2019-09-08 21:36
> This is what I did:
> 
> 1. Download Qubes OS 4
> 2. Install Qubes OS on new computer
> 3. Selected to install Fedora 29 and Debian 9 Template
> 4. Installed Fedora 30 template
> 5. Upgraded Whonix from 14 to 15 via Salt
> 6. Upgraded Debian Template from Debian 9 "Stretch" to Debian 10 "Buster"
> 7. Changed my sys-firewall to be based on Fedora 30 Template
> 8. Created new "fork" of Fedora 30 Template for applications (cloning the template)
> 9. Tried to upgrade the template Fedora 30 -> did not work, received same error as described in this issue -> refocused on other parts
> 10. Played around with USB, Networking and Wifi (sys-usb-net or better sys-net + sys-usb) -> was confused
>     *. Rebooted and changed several things, networking, usb, sys-firewall etc. -> happy that my system started working in the way I wanted it to work
>     n. Got the  Ferdora 30 Template updates to work -> no idea what I changed resolved the issue with the Fedora 30 Template
> 
> _Note: I did not use Tor to update Dom0 or any VMs, except for Whonix itself. Tor should not be the problem in this case._
> 
> @marmarek I upgraded Whonix after installing the Fedora 30 Template (Step 3) and before doing something with the Fedora 30 Template (Step 6+). I just wanted to cross-check if the Whonix Salt scripts for upgrading Whonix manipulate any system configuration. Just, a random idea.
> 
> I did the Debian 9 to 10 upgrade manually in the Template VM. Therefore, I did not change any configuration files in Dom0.

Your questions are off-topic here. Please take them to qubes-users or the Whonix forums.

**Closed** 2023-08-05 09:21 UTC
Labels: T: bug, C: Fedora, P: default, eol-4.0
