### ISSUE TITLE
Qubes updater shows perpetual Fedora 32 updates available

### ISSUE THREAD

**Issue by tk-47** [QubesOS/qubes-issues#6276] opened 2020-12-11 21:46 UTC
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Qubes Updater

**Brief summary**

Qubes updater icon is perpetually showing an available update.  Once open, the updater perpetually shows a Fedora 32 update.  The update will run with no errors.  Green check mark shows. Click finish.  Updater icon persists and continues to show the Fedora 32 update available.  It does not matter how many times the update runs, it does not change. Issue has persisted for at least 4 days.

**How Reproducible**

Issue is persistent.

**To Reproduce**

1. click notification icon for updater
2. run fedora 32 update
3. repeat ...

**Expected behavior**

Expect fedora 32 to update and for the icon and update to disappear until next legitimate update is available.

**Actual behavior**

Updater never registers the update was completed.

**Screenshots**

![7C0F230F-F9EA-4515-A1A0-65892FCBA46F](https://user-images.githubusercontent.com/73854881/101959502-7448d300-3bd3-11eb-88d3-b5ddd1078d2c.jpg)

![DBC75A96-BE9D-46DB-B6F3-CA296CD1C47D](https://user-images.githubusercontent.com/73854881/101959138-bd4c5780-3bd2-11eb-91a2-3fa942e5c900.jpg)
![177B0F13-34E0-4AE2-A039-62BEADD19BA8(2)](https://user-images.githubusercontent.com/73854881/101959145-c1787500-3bd2-11eb-86bc-82903c1492d0.jpg)
![7B9D9908-809E-4B9B-A0F9-A1CB5C1C501B](https://user-images.githubusercontent.com/73854881/101959163-cc330a00-3bd2-11eb-9e8f-4f8d5024c06f.jpg)
![214C2564-000A-4C8B-B40A-14D49376AF14](https://user-images.githubusercontent.com/73854881/101959182-d35a1800-3bd2-11eb-9dd4-dea600bef337.jpg)

**Additional context**

**Solutions you've tried**

Have run the update many times over past 4 days.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

I looked extensively and did not see a similar open issue.  Apologies if this has been addressed.

**Comment by buck3tsec** [comment] 2020-12-12 04:15
I am experiencing this issue on Fedora 32 templates, but not Fedora 32 minimal templates. There appear to be some Qubes packages that depend upon older packages.

__Affected Qubes packages:__ pulseaudio-qubes and qubes-vm-recommended

```
Dependencies resolved.

 Problem 1: package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - cannot install both pulseaudio-14.0-1.fc32.x86_64 and pulseaudio-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-13.99.1-3.fc32.x86_64 and pulseaudio-14.0-1.fc32.x86_64
  - cannot install the best update candidate for package pulseaudio-qubes-4.0.31-1.fc32.x86_64
  - cannot install the best update candidate for package pulseaudio-13.99.1-4.fc32.x86_64
 Problem 2: package qubes-vm-recommended-4.0.7-1.fc32.noarch requires pulseaudio-qubes, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - package pulseaudio-13.99.1-4.fc32.x86_64 requires pulseaudio-libs(x86-64) = 13.99.1-4.fc32, but none of the providers can be installed
  - package pulseaudio-13.99.1-3.fc32.x86_64 requires pulseaudio-libs(x86-64) = 13.99.1-3.fc32, but none of the providers can be installed
  - cannot install both pulseaudio-libs-14.0-1.fc32.x86_64 and pulseaudio-libs-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-libs-13.99.1-3.fc32.x86_64 and pulseaudio-libs-14.0-1.fc32.x86_64
  - cannot install the best update candidate for package qubes-vm-recommended-4.0.7-1.fc32.noarch
  - cannot install the best update candidate for package pulseaudio-libs-13.99.1-4.fc32.x86_64
 Problem 3: problem with installed package pulseaudio-qubes-4.0.31-1.fc32.x86_64
  - package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - cannot install both pulseaudio-14.0-1.fc32.x86_64 and pulseaudio-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-13.99.1-3.fc32.x86_64 and pulseaudio-14.0-1.fc32.x86_64
  - package pulseaudio-module-bluetooth-14.0-1.fc32.x86_64 requires libpulsecore-14.0.so()(64bit), but none of the providers can be installed
  - package pulseaudio-module-bluetooth-14.0-1.fc32.x86_64 requires pulseaudio(x86-64) = 14.0-1.fc32, but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-bluetooth-13.99.1-4.fc32.x86_64
 Problem 4: problem with installed package qubes-vm-recommended-4.0.7-1.fc32.noarch
  - package qubes-vm-recommended-4.0.7-1.fc32.noarch requires pulseaudio-qubes, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.31-1.fc32.x86_64 requires pulseaudio = 13.99.1, but none of the providers can be installed
  - cannot install both pulseaudio-14.0-1.fc32.x86_64 and pulseaudio-13.99.1-4.fc32.x86_64
  - cannot install both pulseaudio-13.99.1-3.fc32.x86_64 and pulseaudio-14.0-1.fc32.x86_64
  - package pulseaudio-module-x11-14.0-1.fc32.x86_64 requires libpulsecore-14.0.so()(64bit), but none of the providers can be installed
  - package pulseaudio-module-x11-14.0-1.fc32.x86_64 requires pulseaudio(x86-64) = 14.0-1.fc32, but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-x11-13.99.1-4.fc32.x86_64
==============================================================================================================================================================================================================================================
 Package                                                                Architecture                                      Version                                                    Repository                                          Size
==============================================================================================================================================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 pulseaudio                                                             x86_64                                            13.99.1-3.fc32                                             fedora                                             1.0 M
 pulseaudio                                                             x86_64                                            14.0-1.fc32                                                updates                                            1.0 M
 pulseaudio-libs                                                        x86_64                                            13.99.1-3.fc32                                             fedora                                             707 k
 pulseaudio-libs                                                        x86_64                                            14.0-1.fc32                                                updates                                            690 k
Skipping packages with broken dependencies:
 pulseaudio-module-bluetooth                                            x86_64                                            14.0-1.fc32                                                updates                                             78 k
 pulseaudio-module-x11                                                  x86_64                                            14.0-1.fc32                                                updates                                             31 k

Transaction Summary
==============================================================================================================================================================================================================================================
Skip  6 Packages
```

```
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                            Architecture                                  Version                                                 Repository                                                     Size
==============================================================================================================================================================================================================================================
Upgrading:
 pulseaudio                                                         x86_64                                        14.0-1.fc32                                             updates                                                       1.0 M
 pulseaudio-libs                                                    x86_64                                        14.0-1.fc32                                             updates                                                       690 k
 pulseaudio-libs-glib2                                              x86_64                                        14.0-1.fc32                                             updates                                                        18 k
 pulseaudio-module-bluetooth                                        x86_64                                        14.0-1.fc32                                             updates                                                        78 k
 pulseaudio-module-x11                                              x86_64                                        14.0-1.fc32                                             updates                                                        31 k
 pulseaudio-utils                                                   x86_64                                        14.0-1.fc32                                             updates                                                        72 k
Removing dependent packages:
 pulseaudio-qubes                                                   x86_64                                        4.0.31-1.fc32                                           @qubes-vm-r4.0-current                                         41 k
 qubes-vm-recommended                                               noarch                                        4.0.7-1.fc32                                            @qubes-vm-r4.0-current                                          0  

Transaction Summary
==============================================================================================================================================================================================================================================
Upgrade  6 Packages
Remove   2 Packages

Total download size: 1.9 M
Is this ok [y/N]: N
Operation aborted.
```

**Comment by iamahuman** [comment] 2020-12-12 06:19
Although the direct cause of this issue appears to be #6234, it would be still helpful to **enhance** Qubes updater GUI to indicate when more recent packages are available _but_ cannot be installed due to dependency conflicts like this.

**Comment by straussmaus** [comment] 2020-12-12 07:51
I opened a similar ticket last month.  It was marked as not a Qubes bug but I think it is.  https://github.com/QubesOS/qubes-issues/issues/6204

@iamahuman 

> Although the direct cause of this issue appears to be #6234, it would be still helpful to enhance Qubes updater GUI to indicate when more recent packages are available but cannot be installed due to dependency conflicts like this.

Maybe but this misses an important discrete point.  The updater completes with a green check mark despite not actually doing the job.

**Comment by andrewdavidwong** [comment] 2020-12-12 13:55
Duplicate of #6234

**Comment by andrewdavidwong** [comment] 2020-12-12 13:55
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-12-12 13:55 UTC
Labels: P: default, T: bug

**Comment by andrewdavidwong** [comment] 2020-12-12 13:57
> Although the direct cause of this issue appears to be #6234, it would be still helpful to **enhance** Qubes updater GUI to indicate when more recent packages are available _but_ cannot be installed due to dependency conflicts like this.

Please open a separate enhancement issue.
 - https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing
 - https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-of-a-single-type

**Comment by tk-47** [comment] 2020-12-12 18:17
To confirm, running the following script will resolve this issue in the short term?

sudo yum update --enablerepo=qubes-vm-r4.0-current-testing

**Comment by buck3tsec** [comment] 2020-12-12 20:29
> Duplicate of #6234

Thank you for the response and commentary @andrewdavidwong, but this is not a duplicate of #6234; it just happens to be related this time, as any package conflict(s) would create this behavior. If this is duplicate of an existing issue, that issue would be #6204. Anyway, I'll take my additional commentary to #6279 where @tk-47 has opened an enhancement request.
