### ISSUE TITLE
ryzen 2700/rx 5700 xt based build frequently locks up, effectively unusable for extended periods of time.

### ISSUE THREAD

**Issue by hanetzer** [QubesOS/qubes-issues#6320] opened 2021-01-01 13:45 UTC
**Qubes OS version**

Qubes release 4.1 (R4.1)
Using because none of the current 'releases' will boot on my hardware.
Or at least they can't operate my gpu (Asrock RX 5700 XT).

**Affected component(s) or functionality**

Overall it 'works' but after some time it entirely locks up (not sure if its just the gui or if is a real system lock; trying to switch tty doesn't work)

**Brief summary**

I'm not 100% certain, but it seems to follow this progression:
Youtube & other videos being watched cease playing, but mouse moves
Mouse moves and I can switch virtual desktops (xfce and i3)
Mouse moves but I can't switch virtual desktops
Full lock.

**How Reproducible**

At least hourly once I get to the point of 'normally using' my computer.
Idling with 'nothing running' does not produce this error.

**To Reproduce**

1. boot (sys-net, sys-firewall and sys-whonix take a while after decryption, not sure if this is 'normal')
2. use the pc as you normally would (with additional qubes overhead)
3. get pissed when it freezes.
4. I think it may be running `personal: Firefox` that causes the lockup. the machine kept running with 'nothing' running on it overnight new years eve.

**Expected behavior**

A relatively normal experience using my fairly expensive computer.

**Actual behavior**

Lockups as described, requiring a hard reset with the reset button.

**Screenshots**

Once it freezes I can no longer screenshot (not that I know how to screenshot
under qubes yet, but you get the point. Would just be a still image of a frozen i3-based qubes desktop)

[Qubes-HCL-ASUS-System_Product_Name-20201231-071851.txt](https://github.com/QubesOS/qubes-issues/files/5758986/Qubes-HCL-ASUS-System_Product_Name-20201231-071851.txt)
^My HCL; the mainboard is an Asus ROG VII Hero (Wifi), and I'm booting from a 500gb samsung nvme drive with 64gb of DDR4 memory. I do not use the listed wifi adapter.

**Additional context**

I'm a fairly experienced linux user, my last major distros were arch and gentoo, so if you need more info just let me know what and maybe how to get it if its a bit more esoteric than 'normal' linux distributions. I just want to be able to use my pc properly.

**Solutions you've tried**

Updating to kernel-latest seems to have reduced the time required for a lockup, but this may just be a placebo.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

Lots of googling (I originally had an issue where libgcc_s.so corrupted in the fedora-32 templatevm which I fixed by reinstalling the template from the install media) and questions/complaints on irc.freenode.net/#qubes

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment] 2021-01-01 19:22
I noticed that you didn't put anything under "Related, non-duplicate issues," so I infer that you're not aware of #6055.

What exactly is the difference between these two issues?

Is this a duplicate of (or should it be combined with) #6055?

**Comment by 0spinboson** [comment] 2021-01-01 20:11
have you enabled the current-testing repo? & do you see entries like these in your kernel logs? https://github.com/QubesOS/qubes-issues/issues/6097#issuecomment-751618002

**Comment by crat0z** [comment] 2021-01-01 21:51
@andrewdavidwong this is not related to #6055 as I've had a r5 2600 CPU running totally fine with no special fixes and working as expected on 4.0, but with a different older Nvidia GPU. This sounds like #5416 #5670 related issues, might even be a duplicate.

**Comment by hanetzer** [comment] 2021-01-01 23:00
> I noticed that you didn't put anything under "Related, non-duplicate issues," so I infer that you're not aware of #6055.
> 
> What exactly is the difference between these two issues?
> 
> Is this a duplicate of (or should it be combined with) #6055?

Sorry, but I'm entirely new to the qubes ecosystem and don't know my head from my arse at the moment in that regard.
No, from the posted gif in the OP the system keeps running, just choppy. I have an entire lockup.



> have you enabled the current-testing repo? & do you see entries like these in your kernel logs? [#6097 (comment)](https://github.com/QubesOS/qubes-issues/issues/6097#issuecomment-751618002)

I don't believe I have enabled current-testing, and yes, I did see at least similar stuff in my kernel log (specifically CPU#N stuck for XXs!).



> @andrewdavidwong this is not related to #6055 as I've had a r5 2600 CPU running totally fine with no special fixes and working as expected on 4.0, but with a different older Nvidia GPU. This sounds like #5416 #5670 related issues, might even be a duplicate.

#5670 does look familiar; I did see swiotlb related messages in my kernel log at various times.

**Comment by hanetzer** [comment] 2021-01-01 23:33
Yeah its definitely something to do with firefox windows & tabs (yeah, I'm a taboholic) as a trigger condition. System ran fine for 10hr or so but when I opened firefox and restored my previous session had a whole lockup almost immediately.

> have you enabled the current-testing repo?

Just tried it, and since it updated quite a lot of software I believe the answer is 'no'. I'll reboot into that and see if it survives longer.

**Comment by hanetzer** [comment] 2021-01-02 01:44
After swapping my rx5700xt for an rx580 gpu I thought I was good, but shortly after expressing this belief on irc I had another hard lock.

**Comment by 0spinboson** [comment] 2021-01-02 07:56
hm. For me the issues are caused by something in Xen 4.14, but downgrading to xen 4.13.1-4 is non-trivial.

**Comment by 0spinboson** [comment] 2021-01-02 08:11
Recently had to revert myself after trying Xen 4.14.0-9. The files you need are these: https://we.tl/t-0vUbukJMWf
install from dom0 command line using e.g. dnf install ./*.rpm , but be sure to shutdown all qubes prior to downgrade.

**Comment by hanetzer** [comment] 2021-01-05 19:08
I reinstalled plain fedora; as interesting as qubes is I need to be able to work and it seems its not quite ready for my hardware. I'll tinker with it and see what can be done in the mean time but for now I don't have time for reboots every hour or more frequently.
`processor.max_cstate=5` seems to have helped some but I still got lockups.

**Comment by 0spinboson** [comment] 2021-01-10 11:58
https://github.com/QubesOS/qubes-issues/issues/6097#issuecomment-755379980 this may be worth trying for this issue too. (adding sched=credit to xen boot options).

**Comment by dylangerdaly** [comment] 2021-01-10 12:38
I recommend upgrading to Fedora 33 (TemplateVM), I'm noticing everything is much smoother (AMD 4000)

**Comment by 0spinboson** [comment] 2024-10-05 07:35
is this still an issue?

**Closed** 2024-12-07 13:50 UTC
Labels: T: bug, C: other, P: major, hardware support, needs diagnosis, affects-4.1, eol-4.1
