### ISSUE TITLE
Qubes 4.0.1 stuck on Reached target Basic System

### ISSUE THREAD

**Issue by knopperx** [QubesOS/qubes-issues#4857] opened 2019-03-03 22:39 UTC
### Qubes OS version:

R4.0.1

### Affected component(s) or functionality:

Qubes system boot

---

### Steps to reproduce the behavior:

* Install Qubes 4.0.1
* Use for weeks
* Run `sudo qubes-dom0-update` in dom0 terminal
* See that there are no available updates
* Reboot

### Expected or desired behavior:

Normal Qubes boot

### Actual behavior:

System stuck on Reached target Basic System

### General notes:

After letting boot timeout I enter dracut console. After running journalctl I get the following relevant warnings/errors:

Check of pool qubes_dom0/pool100 failed (status:!). Manual repair required!
Warning: dracut-initqueue timeout - starting timeout scripts
Warning: Could not boot.
Warning: /dev/mapper/qubes_dom0-root does not exist
Warning: /dev/qubes_dom0/root does not exist

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues/4479

**Comment by andrewdavidwong** [comment] 2019-03-04 06:36
Why do you believe that this is not a duplicate of #4479?

**Comment by knopperx** [comment] 2019-03-04 09:59
This affects Qubes 4.0.1 instead of Qubes 4. I apologize if this is a duplicate. Where can I go for help on at least mounting my VM's and backing up important files?

**Comment by andrewdavidwong** [comment] 2019-03-05 01:29
> This affects Qubes 4.0.1 instead of Qubes 4.

1. [Qubes 4.0.1 and Qubes 4 are the same thing.](https://www.qubes-os.org/doc/supported-versions/#note-on-point-releases)
2. [We generally don't have separate issues for the same issue affecting different versions.](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues)

> Where can I go for help on at least mounting my VM's and backing up important files?

The `qubes-users` [mailing list](https://www.qubes-os.org/support/).

**Comment by andrewdavidwong** [comment] 2019-03-05 01:29
Duplicate of #4479

**Closed by andrewdavidwong** 2019-03-05 01:29 UTC
Labels: C: other, bug

**Comment by notbyosmosis** [comment] 2020-01-03 15:04
Hello.  I was able to recover from this state a couple of months ago.  Details below:

#5160
