### ISSUE TITLE
Launching Tor Browser in anon-whonix AppVM results in torbrowser script bug

### ISSUE THREAD

**Issue by RooneyMcNibNug** [QubesOS/qubes-issues#4311] opened 2018-09-15 16:32 UTC
### Qubes OS version:

4.0

### Affected component(s): 

`anon-whonix` AppVM

---

### Steps to reproduce the behavior:

start `anon-whonix` > run Tor Browser (AnonDist)

### Expected behavior:

Tor Browser (AnonDist) opens successfully

### Actual behavior:

The following echoes:

```
[ERROR] [torbrowser] ###########################################################
## torbrowser script bug.
## No panic. Nothing is broken. Just some rare condition
## has been hit. Try again later. There is likely a
## solution for this problem. Please see the Whonix News,
## Whonix User Help Forum and Whonix Documentation.
## https://www.whonix.org/wiki/Tor_Browser
## Please report this bug!
##
## BASH_COMMAND: "$tb_browser_folder/Browser/start-tor-browser" --allow-remote "$@"
## exit_code: 255
##
## output: /usr/lib/msgcollector/msgcollector
## output_opts: --icon /usr/share/icons/anon-icon-pack/tbupdate.ico --parentpid 3054 --identifier torbrowser --parenttty /dev/pts/0 --whoami user
## progressbaridx: 
##
## Experts only:
## bash -x torbrowser
###########################################################
```

### General notes:

This only started happening recently, and I haven't made any alterations to this particular AppVM's settings. The issue is persistent on the AppVM after restart. Tor Browser is functioning properly on all other whonix VMs - including disposable ones.

Please let me know if I can produce any meaningful logs here.

---

**Comment by kvesel** [comment] 2018-09-20 06:42
I am also having this issue starting same time.

**Comment by kvesel** [comment] 2018-09-20 06:53
Perhaps this can help. I am trying start-tor-browser script with `set -o xtrace`

```
user@host:~/.tb/tor-browser/Browser$ ./start-tor-browser
+ complain_dialog_title='Tor Browser'
+ '[' x:0 = x ']'
+ '[' x/bin/bash = x ']'
+ unset SESSION_MANAGER
++ id -u
+ '[' 1000 -eq 0 ']'
+ grep -q '^flags\s*:.* sse2' /proc/cpuinfo
+ log_output=0
+ show_output=0
+ detach=0
+ show_usage=0
+ register_desktop_app=0
+ logfile=/dev/null
+ :
+ case "$1" in
+ break
+ '[' 0 -eq 1 -a 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ exec
+ exec

```

**Comment by RooneyMcNibNug** [comment] 2018-09-22 22:32
Yep, that fixed this for me as well @kvesel - thanks.

**Comment by kvesel** [comment] 2018-09-24 02:12
@RooneyMcNibNug what did you do? I only posted the xtrace output from the failed start script, not a solution.

**Comment by adrelanos** [comment] 2018-10-26 08:41
Could you start with debugging please? See:

https://www.whonix.org/wiki/Tor_Browser/Advanced_Users#Debugging

**Comment by RooneyMcNibNug** [comment] 2018-10-31 02:06
Sorry - I ended up upgrading to the latest version of Whonix on the machine - which fixed the issue - so I can no longer debug.. hopefully someone else can help.

**Comment by andrewdavidwong** [comment] 2018-10-31 05:37
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-10-31 05:37 UTC
Labels: C: Whonix, bug
