### ISSUE TITLE
Windows 7 HVM cannot capture keystrokes during login

### ISSUE THREAD

**Issue by locustnigi** [QubesOS/qubes-issues#1933] opened 2016-04-24 12:10 UTC
#### Qubes OS version (e.g., `R3.1`):
R3.1

#### Affected TemplateVMs
Windows 7 standalone with windows tools.

---

### Expected behavior:
i expect to insert password in login field with keyboard.

### Actual behavior:
keystrokes are sent to The windows immediately under the appvm login screen.
to log in you have to use the windows virtual keyboard and insert the password with the mouse. Afterwards everything works fine.

### Steps to reproduce the behavior:
Come to my computer 

### General notes:
It is a bummer, I leaked my psw into an irc channel -_-

---

**Comment by axon-qubes** [comment] 2016-04-24 14:41
When you say "appvm login screen" do you mean the screen to log in to Windows, or some other kind of login prompt or web page?

**Comment by axon-qubes** [comment] 2016-04-24 14:42
The window underneath the login screen is part of the same VM, correct?

**Comment by axon-qubes** [comment] 2016-04-24 14:45
This sounds like a duplicate of #738, but I thought that was fixed long ago...

CC @marmarek

**Comment by axon-qubes** [comment] 2016-04-24 14:48
Actually, after re-reading this issue, it seems like a simple case of not following [the recommendation to enable autologon](https://www.qubes-os.org/doc/windows-appvms/#tocAnchor-1-1-1).

**Comment by axon-qubes** [comment] 2016-04-27 08:30
@locustnigi: If you're willing to enable autologon in order to avoid this issue. If that doesn't work, then please feel free to re-open this issue.

**Closed by axon-qubes** 2016-04-27 08:30 UTC
Labels: question

**Comment by perkooo** [comment] 2016-05-20 15:54
Hi,
When you can't autologon (GPO AD), it would  be nice to have a solution to put ctrl + alt + del ! Thanks :)

**Comment by andrewdavidwong** [comment] 2016-05-20 22:35
If Qubes Windows Tools are installed, you can use `ctrl + alt + home`.

**Comment by perkooo** [comment] 2016-05-21 09:44
Yes, Qubes Windows Tools are installed but ctrl atl home is not working.
I have a french keyboard by the way (AZERTY, not a QWERTY) and still not working when I change keyboard from "FR" to "EN" (at windows login).
It might be the problem !

**Comment by andrewdavidwong** [comment] 2016-05-21 10:14
I understand. However, the appropriate issue for your comment is #1585. I see that you already commented there. We're currently working on it. If you want to include further information that could help us, please post it on that issue so that we can keep things organized.

**Comment by perkooo** [comment] 2016-05-21 10:17
Ok thanks. I will give you more informations on #1585 !
