### ISSUE TITLE
qvm-open-in-vm opens URLs in non-default browser

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1487] opened 2015-12-04 14:41 UTC
1. Set Thunderbird in `emailvm` to open links using this script:

        #!/bin/bash
        /bin/qvm-open-in-vm linkvm $1

2. The default browser in `linkvm` is Firefox. Clicking an email link in `emailvm` results in Firefox opening in `linkvm` and going to that URL, as expected.

3. Change the default browser in `linkvm` from Firefox to Google Chrome.

4. Restart `linkvm`.

5. Open another email link in `emailvm`. Unexpected result: link opens in Firefox again, not Chrome.

**Comment by v6ak** [comment] 2015-12-04 19:37
This seems to be caused by wrapping HTTP links to HTML. As a result, the links are opened by default browser for HTML, not for HTTP/HTTPS/whatever.

Some details are in  #1462.

**Comment by adrelanos** [comment] 2015-12-04 20:47
Sure this is a Qubes issue or linkvm operating system configuration issue? Configuration of the default browser is very difficult, because there are so many different places to configure this.

See, `The Default Browser on Linux Debacle`:
http://blog.codef00.com/2011/02/18/the-default-browser-on-linux-debacle/

There is a configuration package, that can set Tor Browser as default browser:
https://github.com/Whonix/tb-default-browser

It may be useful for reference.

**Comment by axon-qubes** [comment] 2015-12-05 00:44
> Sure this is a Qubes issue or linkvm operating system configuration issue? Configuration of the default browser is very difficult, because there are so many different places to configure this.

Indeed, it could be. But the "default browser" issue is something of a red herring. The idea is that it would constitute a good feature to let the user cause the link to open in the `linkvm` browser of choice (regardless of whether that browser is the default).

> There is a configuration package, that can set Tor Browser as default browser

Very useful; thank you.

**Comment by adrelanos** [comment] 2015-12-05 12:49
Axon:
> Indeed, it could be. But the "default browser" issue is something of
> a red herring. The idea is that it would constitute a good feature to
> let the user cause the link to open in the `linkvm` browser of choice
> (regardless of whether that browser is the default).

Okay. Didn't know that. That is one okay choice to implement this
feature. How is the linkvm browser setting currently configured?

**Comment by axon-qubes** [comment] 2015-12-05 22:40
Not sure, but @v6ak said above:
> This seems to be caused by wrapping HTTP links to HTML. As a result, the links are opened by default browser for HTML, not for HTTP/HTTPS/whatever.
> 
> Some details are in #1462.

**Comment by marmarek** [comment] 2015-12-11 16:23
I think the solution would be to create `qubes.OpenURL` service and call it for URLs instead of wrapping them in HTML file.

**Comment by axon-qubes** [comment] 2016-04-07 21:20
Is it just me, or has this problem already been fixed in R3.1?

**Comment by marmarek** [comment] 2016-04-07 21:47
Maybe some side effect. But `qubes.OpenURL` is not yet implemented. But that can be treated as duplicate of #1462

**Closed** 2016-05-18 01:00 UTC
Labels: bug, C: core, P: minor

**Comment by adrelanos** [comment] 2016-06-16 13:26
qubes.OpenURL will land in Qubes Q3.2?

**Comment by marmarek** [comment] 2016-06-16 14:01
On Thu, Jun 16, 2016 at 06:26:44AM -0700, Patrick Schleizer wrote:
> qubes.OpenURL will land in Qubes Q3.2?

Yes.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
