### ISSUE TITLE
Qubes XFCE documentation issues

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2143] opened 2016-07-02 17:21 UTC
* 1) `create ~/.config/menus/favorites.menu, example content:`. - Is this still still required? I skipped in after upgrading Qubes R3.1 KDE to Qubes R3.2 and then migrating to XFCE and did not notice any favorites menu.
 * 1) a) If that step is still required, how are users supposed to get the example file from their browser VM to dom0? This is something really difficult in Qubes and should be documented. And if manual reading and writing is suggested (how awful that would be) that should be pointed out. Either that and/or perhaps a link on how to do such copy and paste from VM to dom0.
* 2) Please document how to migrate from kde login manager to xfce login manager (lightdm).

**Comment by dumbl3d0re** [comment] 2016-07-03 09:12
Duplicate of #1923

**Comment by adrelanos** [comment] 2016-07-03 10:50
I guess this one is more detailed. But yes, these should be merged.

**Comment by andrewdavidwong** [comment] 2016-07-03 15:18
Merged: https://github.com/QubesOS/qubes-issues/issues/1923#issuecomment-230158543

**Closed by andrewdavidwong** 2016-07-03 15:18 UTC
Labels: C: doc, duplicate, P: major, task
