### ISSUE TITLE
Multiple Issues with Qubes R4.0 RC4

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3562] opened 2018-02-10 13:22 UTC
#### Qubes OS version:

Fresh install of 4.0 RC4

#### Affected TemplateVMs: 

N/A

---

### Steps to reproduce the behavior:

Shutdown Qube from Qubes Manager

### Expected behavior:

The Qube shutsdown

### Actual behavior:

An error is thrown referencing Line 178

### General notes:

---

#### Related issues:

Restarting Qube from Qubes Manager - Qube doesn't restart. You have to click on the Start button.

Happens with Fedora 26 AppVM: Going into Qubes Menu and clicking on an Application doesn't launch it.

**Comment by lunarthegrey** [comment] 2018-02-10 19:15
Issue already referenced here: https://github.com/QubesOS/qubes-issues/issues/3501

Patch was pushed, but doesn't look like package with the fix was built yet.

**Comment by andrewdavidwong** [comment] 2018-02-10 20:18
Duplicate of #3501

**Comment by andrewdavidwong** [comment] 2018-02-10 20:18
> Restarting Qube from Qubes Manager - Qube doesn't restart. You have to click on the Start button.

#2362

> Happens with Fedora 26 AppVM: Going into Qubes Menu and clicking on an Application doesn't launch it.

#3533

**Comment by andrewdavidwong** [comment] 2018-02-10 20:18
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-10 20:18 UTC
