### ISSUE TITLE
Qubes 4.0 Installation Failing

### ISSUE THREAD

**Issue by wekroma** [QubesOS/qubes-issues#4574] opened 2018-12-05 10:19 UTC
### Qubes OS version:

R(4.0) and (4.1)

### Affected component(s): 

Laptop, USB and DVD Player

---

### Steps to reproduce the behavior:

Use Qubes(4.0) ISO with rufus(3.3) using original set rules and dd mode. Plugging it in to the laptop and trying to boot from the USB.

### Expected behavior:

Booting up from Qubes(4.0) USB should lead to a successful installation.

### Actual behavior:

Xen boots up and then immediately goes to black screen. Cannot be interacted with at all.

### General notes:

*Looking into my laptop, I relised that there is no TPM chip on this laptop. I dont know if this impacts anything*
*Also I am using UEFI mode as Legacy mode is not applicable to this laptop*

Trying to straight up install from the USB results in Xen booting up, then goes immediately to black screen. No interaction is possible.

Tested with both Qubes(4.0) and (4.1) with rEFInd to boot to the USB is unsuccessful, this end with rEFInd attaching the USB as a removable disk then after awhile the timeout scripts start. Including trying to boot into Fallback boot loader mode also ending in a black screen, no interaction is possible. 

I have tried burning Qubes 4.0 on a DVD drive and booting it using rEFInd is somewhat successful. When the graphical interface shows up asking to set language a "Unsupported Hardware Detected" popup comes up. Says that "Missing features: xl call failed", I can still move forward with the installation and use this installation for daily use but I still prefer a clear system install with no errors.

---

### Related issues:

This open ticket is exactly what I'm getting with xl call failure popup.

Unsupported Hardware Detected: xl call failed #4034
https://github.com/QubesOS/qubes-issues/issues/4034#issue-335264546

**Comment by esote** [comment] 2018-12-05 14:14
1. By "Qubes (4.1)" do you mean 4.0.1?
2. If the other issue describes the exact error you get, then this would be a duplicate of #4034.

**Comment by andrewdavidwong** [comment] 2018-12-06 03:46
> I feel that this is an expansion to #4034 and I have experienced more problems that does not fit into #4034

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), the part of this report that's not covered by #4034 appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Closed by andrewdavidwong** 2018-12-06 03:46 UTC
