### ISSUE TITLE
disposable VMs don't have $HOME set

### ISSUE THREAD

**Issue by zander** [QubesOS/qubes-issues#3424] opened 2017-12-23 13:29 UTC
#### Qubes OS version:
4.0R3 with a self-build archlinux based disp-vm template.

### Steps to reproduce the behavior:

start an app that expects HOME to be there, for instance dolphin, or frankly almost any KDE apps.

they complain about not being able to find settings etc. Upon investigation $HOME is not set.

Even if you open a konsole and type 'cd' your bash will complain about same.

### Expected behavior:

A disposable VM should behave identical to an AppVM. Except that all it changes will be deleted on exit.

### Actual behavior:

The environment is not setup properly.

**Comment by marmarek** [comment] 2017-12-23 21:34
This is a duplicate of #3416 
But also take a look at #3012 , especially info about `qubes.StartApp` service.

**Closed by marmarek** 2017-12-23 21:34 UTC
Labels: bug, C: core, C: templates
