### ISSUE TITLE
No sound in debian buster (10)

### ISSUE THREAD

**Issue by subproc** [QubesOS/qubes-issues#3532] opened 2018-02-04 09:48 UTC
#### Qubes OS version:

R4.0

#### Affected TemplateVMs: 

debian 10 (buster)

---

### Steps to reproduce the behavior:

upgrade a debian 9 template to debian 10

### Expected behavior:

working sound

### Actual behavior:

there's no sound

### General notes:

i've switched to buster-testing repo in qubesR4.0 source list but with no luck 

#### Related issues:

it seems the pulseaudio issues like it there was in past template update, but using

user@debian-9:~$ sudo bash
root@debian-9:/home/user# cd /usr/lib/pulse-11.1/modules
root@debian-9:/usr/lib/pulse-11.1/modules# ln -s ../../pulse-10.0/modules/module-vchan-sink.so . 

doesn't do the trick

it needs something like in #3454

**Comment by marmarek** [comment] 2018-02-14 00:17
Try updating again, there should be updated package.

**Comment by subproc** [comment] 2018-02-17 11:03
thanks, tracking stable repo there's still no audio, but with testing repo it's working

**Comment by andrewdavidwong** [comment] 2018-02-18 00:10
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by techgeeknz** [comment] 2018-09-06 21:37
Sound is broken in Buster.  Is this related to the upgrade to pulseaudio 12.0?

**Comment by airelemental** [comment] 2018-09-07 01:16
Workaround: 
```
cd /usr/lib/pulse-12.0/modules
sudo ln -s ../../pulse-11.1/modules/module-vchan-sink.so .
```

**Closed** 2018-09-12 20:05 UTC
Labels: C: Debian, bug
