### ISSUE TITLE
Qubes Manager's "is template for DisposableVMs" corresponds to Qubes Settings "Allows Starting DisposableVMs from this qube"?

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5089] opened 2019-06-10 14:09 UTC
**Qubes OS version**
R4.01 current-testing

**Affected component(s) or functionality**
DVM-related properties in two places.

**Brief summary**
I was investigating default settings related to anti-leak protections...and noticed Qubes Manager and Qubes Settings have properties that are seem related but appear to be different, yet toggling one changes the other and vice versa.

**To Reproduce**
1. Open Qubes Manager.
2. Find a VM that has Yes in the "is template for DisposableVMs" column.
3. Right click and select Qubes Settings.
4. Navigate to second tab.
5. Note that "Allows Starting DisposableVMs from this qube" is checked.
6. Uncheck the checkbox.
7. Click OK.
8. The VM in Qubes Manager now has a blank in the "is template for DisposableVMs" column.
9. Right click and select Qubes Settings.
10. Navigate to second tab.
11. Note that "Allows Starting DisposableVMs from this qube" is unchecked.
12. Check the checkbox.
13. Click OK.
14. The VM in Qubes Manager now has a Yes in the "is template for DisposableVMs" column.

**Expected behavior**
Unsure.

**Actual behavior**
Confusion.

**Comment by andrewdavidwong** [comment] 2019-06-11 00:21
Sounds like there should be some explanatory tooltips here (#2211).

**Comment by andrewdavidwong** [comment] 2019-06-11 00:25
> Qubes Manager's "is template for DisposableVMs" corresponds to Qubes Settings "Allows Starting DisposableVMs from this qube"?

Pretty sure the answer is "yes." They're the same thing. When there is a "yes" in the "is template for DisposableVMs" column, this is just telling you that the "Allows Starting DisposableVMs from this qube" box is checked. Perhaps it's as simple as using the same phrase in both places so that it's clear that they're the same.

**Comment by deeplow** [comment] 2019-07-03 18:04
I can confirm the confusion. Just wasted a bunch of time debugging why it was opening every app in a dispVM. I think labeling `Allows Starting DisposableVMs from this qube` as `is template for DisposableVMs` would be less confusing @andrewdavidwong.

The natural language here also doesn't help. "Allows Starting DisposableVMs from this qube" can be interpreted as:
- that we can start disposableVMs from this qube (by running `qvm-open-in-dvm` inside the qube without getting the `request refused`;
- this qube serves as a template VM for disposableVMs - which is the correct meaning, according to @brendanhoar

**Comment by marmarta** [comment] 2019-07-07 20:26
I think this is duplicate of https://github.com/QubesOS/qubes-issues/issues/4935 ; there's also some discussion (and even some consensus) on terminology related to disposable VMs.

**Comment by andrewdavidwong** [comment] 2019-07-08 08:14
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-07-08 08:14 UTC
Labels: C: manager/widget, P: default, T: bug, ux
