### ISSUE TITLE
salt @debian: module 're' has no attribute 'RE.MULTILINE'

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#8784] opened 2023-12-21 10:43 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1, probably 4.2 too

### Brief summary
Attempting to apply `file.append` salt states to a fully updated `debian-12`  VM with a `debian-11` management VM results in the following errors:
```
       Comment: An exception occurred in this state: Traceback (most recent call last):
                  File "/var/tmp/.root_dd8a91_salt/pyall/salt/state.py", line 2171, in call
                    ret = self.states[cdata["full"]](
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader.py", line 2105, in wrapper
                    return f(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^
                  File "/var/tmp/.root_dd8a91_salt/pyall/salt/states/file.py", line 6301, in append
                    if __salt__["file.search"](
                       ^^^^^^^^^^^^^^^^^^^^^^^^
                  File "/var/tmp/.root_dd8a91_salt/pyall/salt/modules/file.py", line 3154, in search
                    return replace(
                           ^^^^^^^^
                  File "/var/tmp/.root_dd8a91_salt/pyall/salt/modules/file.py", line 2530, in replace
                    flags_num = _get_flags(flags)
                                ^^^^^^^^^^^^^^^^^
                  File "/var/tmp/.root_dd8a91_salt/pyall/salt/modules/file.py", line 1653, in _get_flags
                    _flag = getattr(re, str(flag).upper())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                AttributeError: module 're' has no attribute 'RE.MULTILINE'
```

### Steps to reproduce
1. Use a `debian-11` management DVM, e.g in an attempt to upgrade to `debian-12`.
2. Apply certain salt states with `file.append` to a `debian-12` VM.

### Expected behavior
Works.

### Actual behavior
Enjoy the above error.

### Related

#8154
#8285

### Likely root cause

#8285 was only fixed for Fedora.

### Side note

Applying the same states to a `debian-11` VM via a `debian-11` management DVM works just fine.

**Comment by unman** [comment] 2023-12-21 11:11
Duplicate of #7891?
This is upstream bug, fixed upstream, and backported to Qubes.
Is your debian-11 template also fully updated? I can use file.append
using a debian-11 mgmt qube with  no issue.

**Comment by 3hhh** [comment] 2023-12-21 11:15
On 12/21/23 12:11, unman wrote:
> Duplicate of #7891?
> This is upstream bug, fixed upstream, and backported to Qubes.
> Is your debian-11 template also fully updated? I can use file.append
> using a debian-11 mgmt qube with  no issue.

Yes, it is.

As I've said: This only happens when applied to a debian-12 VM, not between debian-11 VMs.

**Comment by unman** [comment] 2023-12-21 13:05
I dont think you did say it only applies with a debian-12 target. Thanks
for that.
I still think it's a duplicate #7891.

**Closed** 2023-12-21 20:36 UTC
Labels: T: bug, R: duplicate, P: default
