### ISSUE TITLE
Qube manager crashes when "run command in qube" tries to execute a non-existing command

### ISSUE THREAD

**Issue by deadc0de6** [QubesOS/qubes-issues#7483] opened 2022-05-02 11:48 UTC
### Qubes OS release

4.1

### Brief summary

Running a non-existing command in a qube using the qube manager will crash qube manager

### Steps to reproduce

run qube manager
```bash
$ qubes-qube-manager
```

right click on a qube, select *Run command in qube* and enter a non-existing command

### Expected behavior

At least same as qubes 4.0 (do nothing, show nothing) or better show a dialog with a helpful error.

### Actual behavior

Crash and coredump

**Comment by DemiMarie** [comment] 2022-05-02 18:54
Duplicate of #7278.

**Closed by DemiMarie** 2022-05-02 18:54 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2022-05-02 22:38
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
