### ISSUE TITLE
Template Update Errors

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#7463] opened 2022-04-22 21:15 UTC
Trying to update some Templates and getting error messages:

Fedora-33:

Failed to return clean data (Fedora-33)
AttributeError: _scope_id

Whonix (Whonix-ws/gw-15)

Release file for tor+https://deb.whonix.org/dists/buster/InRelease is expired. Updates for this repository will note be applied

Also getting an error when trying to update Tor Browser (to version 11.0.10)

curl_status_message (partial file. only part of the file was transferred)

and also a GPG signature download error:

can't check signature (no public key)

**Comment by DemiMarie** [comment] 2022-04-23 00:29
Both of those templates are end of life.  Please use `qvm-template` to install a supported version (Fedora 34 or 35, or Whonix 16).  Also, Whonix support for Qubes R4.0 has ended, so you will need to upgrade to R4.1 to continue using Whonix if you have not done so already.

**Comment by DemiMarie** [comment] 2022-04-23 00:31
Closing as “not an issue”: the reported behavior is not a bug, but a consequence of the templates having reached end of life.

**Closed by DemiMarie** 2022-04-23 00:31 UTC
Labels: T: bug, R: not an issue, P: default

**Comment by bluesteal** [comment] 2022-04-23 01:20
Is R4.1 stable? I tried does an in place upgrade and it completely broke my system. Can I use Whonix-16 without upgrading to R4.1?

**Comment by DemiMarie** [comment] 2022-04-23 02:12
R4.1 is stable, yes.  If an in-place upgrade fails it is best to back up your VMs and restore them on R4.1.

**Comment by bluesteal** [comment] 2022-04-23 02:17
I wasn't able to install R4.1 the first time I tried. Has there been any further development? Is it possible to do an in-place upgrade from Whonix-15 to Whonix-16? When attempting the steps in this article: https://www.whonix.org/wiki/Release_Upgrade_Whonix_15_to_Whonix_16 
 
there was an error message:
E: Unable to locate package release-upgrade

**Comment by andrewdavidwong** [comment] 2022-04-24 06:35
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
