### ISSUE TITLE
networking in proxyVM

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#2072] opened 2016-06-15 07:40 UTC
#### Qubes OS version (e.g., `R3.1`):

3.1 (testing repo enabled)
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora 23

---
### Expected behavior:

If I change one firewallVM's netVM the internal IP addresses and routing table are changing according to the new netVMs setting
### Actual behavior:

The default route not changing, remaining related to the first assigned netVM. Even after I change it's netVM.
### Steps to reproduce the behavior:
- Start a firewallVM assignet to a netVM
- change the netvm to another one
- check your routing table.
### General notes:

Environment:
I have separated netvms: WiFi, Ethernet
I have several firevallVMs each connected to one of the netvms

It was working as expected  before - but not sure which update has broke it.

---

**Comment by marmarek** [comment] 2016-06-15 08:20
Do you get any errors during the switch? Especially in firewallvm syslog.

**Comment by Zrubi** [comment] 2016-06-15 08:35
just checked dmesg before.. now I found one in syslog:

systemd-udevd[4279]: Process '/usr/lib/qubes/setup-ip' failed with exit code 1.

The sorroundings:


Jun 15 10:25:12 Home-VPN NetworkManager[509]: <warn>  (eth0): failed to find device 23 'eth0' with udev
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  (eth0): new Ethernet device (carrier: OFF, driver: 'vif', ifindex: 23)
Jun 15 10:25:12 Home-VPN systemd-udevd[4279]: Process '/usr/lib/qubes/setup-ip' failed with exit code 1.
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  (eth0): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  (eth0): link connected
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  (eth0): device state change: unavailable -> disconnected (reason 'none') [20 30 0]
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  Auto-activating connection 'VM uplink eth0'.
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  (eth0): Activation: starting connection 'VM uplink eth0' (de85f79b-8c3d-405f-a652-cb4c10b4f9ef)
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  (eth0): device state change: disconnected -> prepare (reason 'none') [30 40 0]
Jun 15 10:25:12 Home-VPN NetworkManager[509]: <info>  NetworkManager state is now CONNECTING

**Comment by marmarek** [comment] 2016-06-15 08:42
Ah, you have NetworkManager in that FirewallVM. Try restarting it - maybe it doesn't notice updated settings for eth0.

**Comment by Zrubi** [comment] 2016-06-15 08:48
You mean I should restart after every NetVM change?

I rebooted to see if it's solve this. And yes after reboot (maybe restarting the NM would be enough) it is working - but just until I change the netvm again...

**Comment by marmarek** [comment] 2016-06-15 09:10
Yes, restart (or better try reload) NetworkManager after NetVM change. If that help, will add this to the script to handle it automatically.

**Comment by Zrubi** [comment] 2016-06-15 09:50
reload not helps.
restart after the new netvm has no effect.

However I found out if I following this procedure:
- set the new netvm to none
- restart (reload not enough) NM
- set the new netvm

Then I got the proper routing.

**Comment by marmarek** [comment] 2016-06-15 09:56
Doesn't look like a good idea to do that automatically...
Maybe it's about when the configuration is modified. Take a look at [`/usr/lib/qubes/setup-ip`](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/setup-ip) and try stopping NM just before writing config and start just after.

**Comment by Zrubi** [comment] 2016-06-15 10:38
I found the solution (in the nmcli man page)

NetworkManager does not monitor changes to connection files by default. So you need to use this command in order to tell NetworkManager to re-read the connection profiles from disk when a change was made to them. However, the auto-loading feature can be enabled and then NetworkManager will reload connection files any time they change (monitor-connection-files=true in NetworkManager.conf(5)).

extending the main NM config with the parameter above solved this problem. :)

(However still not know when and where was changed about these)

**Comment by Zrubi** [comment] 2016-06-15 10:41
This error message is still there:
systemd-udevd[4279]: Process '/usr/lib/qubes/setup-ip' failed with exit code 1.

So it seems not related to this issue.

**Comment by marmarek** [comment] 2016-06-15 10:43
Maybe you didn't used NM before? Or maybe since this commit: https://github.com/QubesOS/qubes-core-agent-linux/commit/d23f3d8ddb6621987fb7cab599073b8be4b14a44

**Comment by unman** [comment] 2017-01-12 02:29
@marmarek 
I've tested this today and cant reproduce the error,  with NM running or not.
Everything works as expected.
Can we close this?

**Comment by andrewdavidwong** [comment] 2017-01-12 04:36
@Zrubi, are you still experiencing this issue?

**Comment by Zrubi** [comment] 2017-01-12 10:26
On 01/12/2017 05:36 AM, Andrew David Wong wrote:
> @Zrubi <https://github.com/Zrubi>, are you still experiencing this issue?
> 

I do not have any 3.1 instance, so I can't even test it.
This issue was not affect 3.2 - what I'm using on all of my Qubes boxes.


-- 
Zrubi

**Comment by andrewdavidwong** [comment] 2017-01-13 09:32
Ok, let's close this then.

**Closed by andrewdavidwong** 2017-01-13 09:32 UTC
Labels: bug, C: core, P: minor
