### ISSUE TITLE
USB Passthrough with RT2800USB does not work

### ISSUE THREAD

**Issue by QubesWirelessIssue** [QubesOS/qubes-issues#3778] opened 2018-04-02 19:52 UTC
### Qubes OS version:
Version 4

USB Pass through of RT2800USB chipset does not work.

### Affected component(s): 

Qubes4, with sys-usb qube involved, and a converted debian 9 -> kali qube.

---

### Steps to reproduce the behavior:

Plug in RT2800USB wireless adapter. Use USB Pass through to a qube. 

### Expected behavior:

I can use the RT2800USB wireless adapter in the target qube. 

### Actual behavior:

In the target qube, I get the below logs:

```
[ 3207.128956] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(0)
[ 3207.128981] vhci_hcd vhci_hcd.0: devid(65542) speed(3) speed_str(high-speed)
[ 3207.345085] usb 1-1: new high-speed USB device number 20 using vhci_hcd
[ 3207.461155] usb 1-1: SetAddress Request (20) to port 0
[ 3207.493446] usb 1-1: New USB device found, idVendor=148f, idProduct=3070
[ 3207.493481] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3207.493509] usb 1-1: Product: 802.11 n WLAN
[ 3207.493518] usb 1-1: Manufacturer: Ralink
[ 3207.493526] usb 1-1: SerialNumber: 1.0
[ 3208.391263] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3209.279250] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3210.167066] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3211.055282] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3211.055479] ieee80211 phy2: rt2x00usb_vendor_request: Error - Vendor Request 0x07 failed for offset 0x1000 with error -19
[ 3211.055638] ieee80211 phy2: rt2800_probe_rt: Error - Invalid RT chipset 0x0000, rev 0000 detected
[ 3211.055770] ieee80211 phy2: rt2x00lib_probe_dev: Error - Failed to allocate device
[ 3211.059753] usb 1-1: USB disconnect, device number 20
[ 3211.951092] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3212.839286] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3212.839394] usb usb1-port1: attempt power cycle
[ 3214.039259] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3214.927061] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 3214.927122] usb usb1-port1: unable to enumerate USB device
```

Suffice to say, the wireless card does not work.  

### General notes:

I also tried blacklisting the loading of rt2800usb kernel modules in the sys-usb qube, and verified that after restarting the sys-usb qube, it did not have the kernel modules loaded, nor where they loaded when I plugged the card in. After trying to enable pass through again, it failed with the above error messages.

---

**Comment by marmarek** [comment] 2018-04-02 19:59
What do you see from kernel in sys-usb?

**Comment by QubesWirelessIssue** [comment] 2018-04-02 23:20
Nothing that leads me to believe that there's a kernel related issue:

Apr 02 14:22:30 sys-usb audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 02 14:22:30 sys-usb kernel: audit: type=1131 audit(1522693350.271:95): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? re
Apr 02 14:22:31 sys-usb pulseaudio[1450]: source cork req state =2, now state=1
Apr 02 14:22:31 sys-usb pulseaudio[1450]: sink cork req state =2, now state=1
Apr 02 14:22:45 sys-usb kernel: usb 1-5: new high-speed USB device number 6 using xhci_hcd
Apr 02 14:22:45 sys-usb kernel: usb 1-5: New USB device found, idVendor=148f, idProduct=3070
Apr 02 14:22:45 sys-usb kernel: usb 1-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 02 14:22:45 sys-usb kernel: usb 1-5: Product: 802.11 n WLAN
Apr 02 14:22:45 sys-usb kernel: usb 1-5: Manufacturer: Ralink
Apr 02 14:22:45 sys-usb kernel: usb 1-5: SerialNumber: 1.0
Apr 02 14:22:45 sys-usb mtp-probe[2011]: checking bus 1, device 6: "/sys/devices/pci0000:00/0000:00:05.0/usb1/1-5"
Apr 02 14:22:45 sys-usb mtp-probe[2011]: bus: 1, device: 6 was not an MTP device
Apr 02 14:22:55 sys-usb systemd[1]: Started Update time from ClockVM.

**Comment by QubesWirelessIssue** [comment] 2018-04-03 21:17
For what it's worth, other people on qubes-user as well, without any suitable full solutions. 

https://groups.google.com/forum/#!searchin/qubes-users/%22maybe$20the$20usb$20cable%22%7Csort:date

I might have to see if I can assign a full USB controller or so.

**Comment by QubesWirelessIssue** [comment] 2018-04-05 00:09
After trying a fedora 26 target qube, I get the following dmesg output

```
[36918.440918] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(0)
[36918.440944] vhci_hcd vhci_hcd.0: devid(131078) speed(3) speed_str(high-speed)
[36918.657096] usb 1-1: new high-speed USB device number 3 using vhci_hcd
[36918.774180] usb 1-1: SetAddress Request (3) to port 0
[36918.806317] usb 1-1: New USB device found, idVendor=148f, idProduct=3070
[36918.806366] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[36918.806383] usb 1-1: Product: 802.11 n WLAN
[36918.806391] usb 1-1: Manufacturer: Ralink
[36918.806413] usb 1-1: SerialNumber: 1.0
[36919.735197] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36920.623159] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36921.511282] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36922.034405] audit: type=1123 audit(1522885146.570:531): pid=31543 uid=1000 auid=1000 ses=1 msg='cwd="/home/user" cmd="dmesg" terminal=pts/2 res=success'
[36922.034557] audit: type=1110 audit(1522885146.570:532): pid=31543 uid=0 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
[36922.035651] audit: type=1105 audit(1522885146.571:533): pid=31543 uid=0 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
[36922.399290] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36922.399505] ieee80211 phy0: rt2x00usb_vendor_request: Error - Vendor Request 0x07 failed for offset 0x1000 with error -19
[36922.399592] ieee80211 phy0: rt2800_probe_rt: Error - Invalid RT chipset 0x0000, rev 0000 detected
[36922.399670] ieee80211 phy0: rt2x00lib_probe_dev: Error - Failed to allocate device
[36922.400834] usbcore: registered new interface driver rt2800usb
[36922.401274] usb 1-1: USB disconnect, device number 3
[36923.295307] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36924.183100] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36924.183187] usb usb1-port1: attempt power cycle
[36925.383368] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36926.271287] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[36926.271427] usb usb1-port1: unable to enumerate USB device
```

However, it seems that the sys-usb says:

```
[24249.182018] usb 2-5: new high-speed USB device number 6 using xhci_hcd
[24249.328539] usb 2-5: New USB device found, idVendor=148f, idProduct=3070
[24249.328621] usb 2-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[24249.328702] usb 2-5: Product: 802.11 n WLAN
[24249.328744] usb 2-5: Manufacturer: Ralink
[24249.328786] usb 2-5: SerialNumber: 1.0
[24257.261140] usbcore: registered new device driver usbip-host
[24257.266368] usbip-host 2-5: usbip-host: register new device (bus 2 dev 6)
[24257.273079] usbip-host 2-5: stub up
```

After seeing the xhci_hcd (USB3) driver being used, I tried to find out if usbip supports USB3.. which leads me to https://www.spinics.net/lists/linux-usb/msg126277.html (which is old), but there's also https://www.systutorials.com/linux-kernels/51710/usbip-vhci-hcd-add-usb3-superspeed-support-linux-3-18-95/ which indicates it should be supported. That said, I wonder if it's possible to disable the USB3 support and just use USB2 kernel drivers. Let's see

**Comment by almapavi** [comment] 2019-03-19 21:39
I fixed (well was able to have the message removed) the issue by disabling usb dac-up in the bios.

**Comment by xaki23** [comment] 2019-06-10 14:43
this turns out to be not qubes specific, except outside of qubes most people wouldnt be using usbip.
the "cable is bad" happens also if you try to pass these interfaces between two plain fedora installs.
out of a dozen or so cabled and wireless usb network interfaces i tried only one worked:
`ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]`

what happens is the driver uploads firware or sets some deep cfg switches and wants to reset the device.

this reset event is handled by the virtual hub in the receiving vm, but not passed on to the giver:
https://github.com/torvalds/linux/blob/d1fdb6d8f6a4109a4263176c84b899076a5f8008/drivers/usb/usbip/vhci_hcd.c#L565

there is infrastructure for receiving remote resets on the other side:
https://github.com/torvalds/linux/blob/d1fdb6d8f6a4109a4263176c84b899076a5f8008/drivers/usb/usbip/stub_rx.c#L147

i have added code to make up a ctrlreq urb to trigger that codepath, but end up in some kind of usb state engine hell, so more filtering/tweaking or making up additional urbs may be required.

**Comment by andrewdavidwong** [comment] 2019-06-11 00:28
> this turns out to be not qubes specific, except outside of qubes most people wouldnt be using usbip.

Thanks for investigating, @xaki23. In that case, I'll close this as "not our bug." However, if anyone believes that this issue should still be open for some reason, please leave a comment explaining why, and we'll be happy to reopen it. Thank you.

**Comment by brendanhoar** [comment] 2019-06-11 00:51
I had issues with USB passthrough on a GL.INET USB150 microrouter (Driver=r8152
). I ended up just passing the entire USB 3.0 controller (PCI device) to sys-net instead.

B

**Comment by xaki23** [comment] 2019-07-09 21:52
> Thanks for investigating, @xaki23. In that case, I'll close this as "not our bug." However, if anyone believes that this issue should still be open for some reason, please leave a comment explaining why, and we'll be happy to reopen it. Thank you.

i dont like closing it as long as it is unfixed.
this problem applies to qubes users, and wont go away on its own.
and i have to admit ... i lost steam on this the moment i had an amazon product code for a dualband wifi dongle that worked.
realizing linux-usb doesnt have an issue tracker but a high volume mailing list didnt help either.

could we please keep this (and similar cases of not-our-bug) open even if only for gathering lore/workarounds?
(and i will try my luck on that mailinglist. yuck.)
(and please no one tell me a working _ethernet_ dongle for the moment ;)

**Comment by andrewdavidwong** [comment] 2019-07-10 08:12
> > Thanks for investigating, @xaki23. In that case, I'll close this as "not our bug." However, if anyone believes that this issue should still be open for some reason, please leave a comment explaining why, and we'll be happy to reopen it. Thank you.
> 
> i dont like closing it as long as it is unfixed.
> this problem applies to qubes users, and wont go away on its own.
> and i have to admit ... i lost steam on this the moment i had an amazon product code for a dualband wifi dongle that worked.
> realizing linux-usb doesnt have an issue tracker but a high volume mailing list didnt help either.
> 
> could we please keep this (and similar cases of not-our-bug) open even if only for gathering lore/workarounds?
> (and i will try my luck on that mailinglist. yuck.)
> (and please no one tell me a working _ethernet_ dongle for the moment ;)

I understand your concerns, but I don't think that reopening this issue would be an effective way to address them for the following reasons:

1. The purpose of this issue tracker is to help the developers make Qubes OS better. It is not intended to be a user help forum or a knowledge collection/transfer mechanism. We have other places for those distinct, important functions.

2. An issue being closed does not prevent people from commenting on it, so lore/workarounds can still be added as comments on this issue without reopening it.

3. An issue being open means that there is some work for a developer to do on it. If we start keeping issues open for other reasons, even when they are not actionable, then the issue tracker becomes less useful for developers. Every time they look at an open issue, they will have to guess whether there is really any action to be taken or not. They will have to read through the dozens of comments trying to figure out if it's a "real" issue or not. This increases cognitive load, saps motivation, and wastes valuable time that could be spent making Qubes OS better. We should instead keep the issue tracker organized and disciplined so it can effectively perform its specialized function and serve developers.

4. This bug report belongs in an upstream project's issue tracker. We can't have a bunch of other project's bug reports in our issue tracker just because they affect Qubes users. Likewise, we can't write and maintain the documentation for a bunch of upstream tools just because we use them. The Qubes OS project specializes in bringing these upstream tools together in a secure way. It's better for everyone if each project focuses on its own specialty.

Allow me to summarize:

> i dont like closing it as long as it is unfixed.

Agreed: Issues should remain open until fixed. However, this issue is in the wrong location (wrong project's issue tracker). It should be opened in the correct location, *then* remain open until fixed.

> this problem applies to qubes users, and wont go away on its own.

Agreed: This bug should be fixed. However, it should be fixed by the code's maintainers, not the Qubes devs, who are already buried under a mountain of over a thousand Qubes-specific issues.

> realizing linux-usb doesnt have an issue tracker but a high volume mailing list didnt help either.

IMHO, every software project should have an issue tracker. Maybe you can convince them to set one up?

> could we please keep this (and similar cases of not-our-bug) open even if only for gathering lore/workarounds?

Further summarizing:
 - Not necessary: lore/workarounds can still be gathered without reopening.
 - Not the right place: We have documentation and mailing lists for that.
 - Makes the issue tracker less useful for devs, which does more harm than good for the project and its users.

**Comment by marmarek** [comment] 2019-07-10 08:49
> > could we please keep this (and similar cases of not-our-bug) open even if only for gathering lore/workarounds?
> 
> Further summarizing:
> 
>     * Not necessary: lore/workarounds can still be gathered without reopening.
> 
>     * Not the right place: We have documentation and mailing lists for that.
> 
>     * Makes the issue tracker less useful for devs, which does more harm than good for the project and its users.

On the other hand, searching for closed issues also have its own issues. As @xaki23 said, it isn't "fixed". There is also another related case: when original issue is not fixed, but we apply some temporary workaround and the actual core issue is tracked in upstream issue tracker. In that case, there is still value in having an issue here (ideally with some automatic notification of upstream issue status changes, but github can't do that) - in many cases we want to remove suboptimal workaround when proper solution is there.
But qubes-issues repo may not be the best place for those cases. Lets keep only things _actionable_ for qubes developers in qubes-issues. Maybe we should have separate tracker (separate repository? wiki page?) for those other cases? Or maybe it isn't worth the effort, maybe some labels would be enough (even on closed issues)? Some of this comes from very limited set of issue states in github issues...

**Comment by andrewdavidwong** [comment] 2019-07-11 00:20
> On the other hand, searching for closed issues also have its own issues. As @xaki23 said, it isn't "fixed". 

This is what the `R:` resolution labels are for. We can tell that a closed issue with the `R: not our bug` label was closed not because it was fixed, but because it was determined to be not our bug (and similarly for the other `R:` labels).

> There is also another related case: when original issue is not fixed, but we apply some temporary workaround and the actual core issue is tracked in upstream issue tracker. In that case, there is still value in having an issue here (ideally with some automatic notification of upstream issue status changes, but github can't do that) - in many cases we want to remove suboptimal workaround when proper solution is there.

Yes, this is an important case. Ideally, the upstream fix would trigger the creation of a "remove suboptimal workaround" issue in our issue tracker. Perhaps that's not possible. The next best thing would be for us to receive a notification when the upstream fix happens so that we can manually create the "remove suboptimal workaround" issue ourselves.

Without either of these, keeping an issue open in our issue tracker would only help by accident: We stumble upon the issue some time later, realize that an upstream fix was patched in the meantime, and remember that we implemented a suboptimal workaround. But we can also stumble upon closed issues in this fashion. It's just that the open issues get more eye traffic.

> But qubes-issues repo may not be the best place for those cases. Lets keep only things _actionable_ for qubes developers in qubes-issues.

Agreed.

> Maybe we should have separate tracker (separate repository? wiki page?) for those other cases? Or maybe it isn't worth the effort, maybe some labels would be enough (even on closed issues)? Some of this comes from very limited set of issue states in github issues...

Yeah, I'm not sure what the best available solution is for those cases. As mentioned above, it would really be preferable to have the upstream action of patching a fix be the trigger, rather than us having to repeatedly check (i.e., a "push" rather than a "fetch" model).

**Comment by xaki23** [comment] 2019-07-27 19:42
my random poking around didnt result in anything that worked.

finally got around to at least report it to the (hopefully right) ML.
https://marc.info/?l=linux-usb&m=156423432111134

**Comment by k0l0ss** [comment] 2019-11-15 15:26
Is there any changes on this? Can't figure out a solution and all my laptop's usbs belong to same device, not an option to attach it to sys-net*.

Thanks

**Comment by andrewdavidwong** [comment] 2019-11-17 09:29
> Is there any changes on this? Can't figure out a solution and all my laptop's usbs belong to same device, not an option to attach it to sys-net*.

@k0l0ss, this issue was closed as "not our bug," since it is not Qubes-specific. You might want to check the link in the comment above yours for any updates from upstream.

**Comment by xaki23** [comment] 2019-11-17 12:58
there is not ever going to be any news about this upstream, much less a fix for this, unless someone from the qubes sides of things makes it happen.
the problem is (perceived as) a "wacky qubes specific usecase/problem".

(actualy i am not even sure who is "upstream" in this case. fedora? kernel?)

perhaps we should find an interested qubes user with some linux service contract who is willing to construct a (non-qubes) usecase and open a ticket?

**Comment by k0l0ss** [comment] 2019-11-17 13:24
Well, while I do understand this is not a bug of qubes but an upstream bug
with usbip, I do not share the idea of "not our bug" since it affects
directly the qubes sys-usb implementation. Every person plugging an
ethernet dongle 3.0 is going to face the issue and blame qubes for it.
I have checked upstream, someone in this post posted it, and I share the
opinion of xaki23, don't think this is ever going to be fixed due to low
use case out of qubes.
Btw, I've tried with Debian vm and same behaviour.
Usb 2.0 dongle worked just fine.

I wish I had the knowledge to dig into this problem. In fact if someone is
willing to help me into resolve this issue I'm happy with it.

My background is pure sysadmin/operations guy so.

Thanks again

**Comment by marmarek** [comment] 2019-11-17 13:42
> finally got around to at least report it to the (hopefully right) ML.
> https://marc.info/?l=linux-usb&m=156423432111134

Did you ever got _any_ response there or elsewhere? Public archives are silent about that :/

**Comment by chrischeu** [comment] 2019-11-17 22:42
Hello,

I currently figured out that the AXIS AX88179 USB 3.0 Gigabit NIC is working - you can successfully attach the USB NIC to anther VM. I will post the log messages tomrrow when getting back to my qubes machine.

I will also test some other WiFi USB adapters and post it, if there is any working one.

Chris

**Comment by xaki23** [comment] 2019-11-19 20:37
> Did you ever got _any_ response there or elsewhere? Public archives are silent about that :/

the public archives show you all the responses that ever happened. none.
i had another (un-qubes-related) kernel issue at the time, which initially got zero response too, but (since i had a worksforme-grade patch for it) i was following up on that one, and basicly it seems kernel mailinglists are for more or less fulltime kernel hackers only these days. 

> I currently figured out that the AXIS AX88179 USB 3.0 Gigabit NIC is working 

sadly, i can confirm this.

be super-careful when shopping for these (or the confirmed to be working rtl wifi ones) on amazon.
searching for a chipset does not mean the returned results actualy matched the searched-for string.
and even if you check the actual item description again and make sure it does mention the right chipset, you have a reasonable chance to end up with some straight chinesium. 

samples confirmed to be working:
usb-a simple dongle: https://www.amazon.de/gp/product/B07M91X2NW
usb-a with hub: https://www.amazon.de/gp/product/B00LLUEJFU
usb-c simple dongle: https://www.amazon.de/gp/product/B07M8GSLQB
usb-c with (fancy) hub: https://www.amazon.de/gp/product/B07GV6FKX5

**Comment by k0l0ss** [comment] 2019-11-23 19:23
Confirm UGREEN model: 50771
Also works.
Thanks Xaki23 for sharing

**Comment by spacejack13** [comment] 2019-11-27 20:14
Xaki23, are those models able to mount WiFi to user-specified qubes or are they only good for Ethernet? Because I have a WiFi dongle that I am unable to attach to any qube but when I re-install qubes 4 and select the configuration to allow the usb devices to be handled by sys-net, I am able to use the WiFi dongle as a source of internet for all the other cubes but I am still not unable to mount the device to any specified qube. I am not sure if this is the same issue that this thread is discussing as I am not a dev or anywhere close to that, just a privacy advocate and Linux hobbiest. I am trying to create a pen testing lab but can get the WiFi dongle to attach nor can I bring the dongle back up with the “ip link set <network device> up>” command and the ifconfig net-tools claims to be installed but I can’t seem to use them in any Debian based qubes so I’m at a stand still. I can get the dongle to work after reinstalling with the network/usb in one qube but that’s about all I can do. Do the devices you linked allow me to attach my WiFi dongle to specific qubes for lent testing?

**Comment by k0l0ss** [comment] 2019-11-27 20:58
Well it is probable the same issue but can't tell for sure without proper
log checking.
The fact that you can get it working passing the device entirely to the vm,
makes me think of the same problem.
I did went for the ethernet, but I am pretty sure this does happen to for
the WiFi modules.

**Comment by xaki23** [comment] 2019-12-02 18:05
WIFI samples confirmed to work, including monitor mode with airodump:

ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Driver=rtl8192cu, 480M
https://www.amazon.de/gp/product/B003MTTJOY
2.4 GHz only, very compact, 8eur, mainline driver

ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter
Driver=88XXau, 480M
https://www.amazon.de/gp/product/B074CV5JMP
2.4+5 GHz, compact, 10eur

https://www.amazon.de/gp/product/B074CVBRCB
not tried, but likely a 0bda:a811 with external antenna, 16eur

ID 0bda:0811 Realtek Semiconductor Corp. 802.11ac WLAN Adapter                 
Driver=88XXau, 480M
https://www.amazon.de/gp/product/B01CDUJHXK
2.4+5 GHz, external antenna

the 88XXau driver can be found here:
https://github.com/aircrack-ng/rtl8812au
crude but painless way to build a qubes-vm kernel rpm with it here
https://github.com/xaki23/qubes-linux-kernel/tree/wifi

beware of less than accurate product descriptions when procuring.
even the "chip description strings" returned by the devices may be wrong, go by usb IDs where possible.

**Comment by spacejack13** [comment] 2019-12-06 06:27
For clarity, these chipsets/dongles will be able to be attached to any specified vms from the sys-usb qube and allow the target vm to use the dongle as a source for internet? And they have been confirmed to be able to be set to down, changed to monitor mode and set back to up via ip commands? :
####
ip link set <interface> down
iwconfig <interface> mode monitor
ip link set <interface> up
####

For example, I have a Debian based katoolin vm and I want to attach the dongle and use it for monitoring and other aircrack-ng pentesting use cases. These dongle will work as intended with this set up or a similar one?

**Comment by xaki23** [comment] 2019-12-12 17:38
> https://www.amazon.de/gp/product/B074CVBRCB
> not tried, but likely a 0bda:a811 with external antenna, 16eur

by now confirmed to work as well 
ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter
Driver=88XXau, 480M





> For clarity, these chipsets/dongles will be able to be attached to any specified vms from the sys-usb qube and allow the target vm to use the dongle as a source for internet? And they have been confirmed to be able to be set to down, changed to monitor mode and set back to up via ip commands? :

yes. 
note you need the 88XXau driver not included in official kernels for most of these.

> For example, I have a Debian based katoolin vm and I want to attach the dongle and use it for monitoring and other aircrack-ng pentesting use cases. These dongle will work as intended with this set up or a similar one?

thats pretty much exactly my test-usecase. 

sudo iw dev wlan0 set type monitor
sudo airodump-ng -b abg -w test-wl0 wlan0

**Comment by dylangerdaly** [comment] 2020-01-15 23:31
Is there any update on this? I remember this being as issue years ago, recently picked up an RTL USB C to Ethernet Adapter and I'm getting the same error I was getting years ago.

I'll have to pick up the one that works.

**Comment by dylangerdaly** [comment] 2020-01-19 07:27
Can confirm the [UGREEN USB C Ethernet PN #50737](https://www.amazon.com.au/gp/product/B07M967CRD) works perfectly.
Can also confirm the [TP-Link Archer T3U AC1300 Mini USB AC Adapter](https://www.amazon.com.au/gp/product/B07M69276N/) works with [this driver](https://github.com/cilynx/rtl88x2bu)

**Comment by evadogstar** [comment] 2020-03-03 20:36
And I get the same issue :(

**Comment by xaki23** [comment] 2020-07-03 15:41
confirmed working: TP-Link T2U series
different sizes, all 2.4G+5G, Driver=rtl88XXau, 480M

ID 2357:011e TP-Link 802.11ac WLAN Adapter
https://www.amazon.de/gp/product/B07KRCW6LZ
very compact

ID 2357:011f TP-Link 802.11ac WLAN Adapter                    
https://www.amazon.de/gp/product/B00K11UIV4
small

ID 2357:0120 TP-Link 802.11ac WLAN Adapter
https://www.amazon.de/gp/product/B07P681N66
with external antenna

**Closed** 2023-08-05 09:23 UTC
Labels: C: other, P: default, eol-4.0

**Comment by SemanticBeeng** [comment] 2023-09-19 13:38
> Well, while I do understand this is not a bug of qubes but an upstream bug with usbip, I do not share the idea of "not our bug" since it affects directly the qubes sys-usb implementation. Every person plugging an ethernet dongle 3.0 is going to face the issue and blame qubes for 

Any chance this issue with "Ethernet over USB" is cased by same things?
https://groups.google.com/g/usbarmory/c/gZCBT_ldlrc/m/2QpnnhUJAwAJ

**Comment by DemiMarie** [comment] 2023-09-20 00:33
@SemanticBeeng I think this problem is a generic issue with USBIP.
