### ISSUE TITLE
Qubes 4.0 - Qube Manager: Memory Allocation Display?

### ISSUE THREAD

**Issue by pruflyos** [QubesOS/qubes-issues#3852] opened 2018-04-24 11:09 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Qube Manager

---

### General notes:

As far as I remember, Qubes 3.2 was displaying the current memory allocation of each VM in the last column of the *Qube Manager*. Is that  gone with 4.0? Is there  any other convenient tool to see  the total system memory and how much of that is allocated to each VM?

---

**Comment by andrewdavidwong** [comment] 2018-04-25 04:07
Duplicate of #3241

**Comment by andrewdavidwong** [comment] 2018-04-25 04:07
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-04-25 04:07 UTC
