### ISSUE TITLE
AEM 4.0.1 Communication failure, TPM 2.0, TCG Daemon

### ISSUE THREAD

**Issue by jonull101** [QubesOS/qubes-issues#4824] opened 2019-02-16 16:42 UTC
### Qubes OS version:
R4.0

### Affected component(s):
TPM && AEM || Tspi

---

### Steps to reproduce the behavior:
```#tpm_clear --force```

### Expected behavior:
# tpm_clear --force
TPM Successfully Cleared.

### Actual behavior:
```
#tpm_clear --force
Tspi_Context_Connect failed: 0x00003011 - layer=tsp, code =0011 (17), Communication failure

# cat /sys/class/tpm/tpm0/**pcrs**
```
Also i cannot find the file `**pcrs**` to verify kernel support for TPM:

### General notes:
cleared TPM in BIOS, still get the same error.

---

### Related issues:
```
systemctl status tcsd -l
* tcsd.service - TCG Core Services Daemon
 Loaded: lodaded (/usr/lib/systemd/system/tcsd.service; enabled; vendor preset: disabled)
 Drop-In: /usr/lib/systemd/system/tcsd.service.d
                |_anti-evil-maid-seal.conf, trousers-changer.conf
Active: failed (Result: exit-code) since ""date && time""
Process: 4383 ExecStartPre=/sbin/tcsd_changer_identify (code=exited, status=30)
Process: 4380 ExecStartPre=/sbin/tcsd_changer_migrate (code=exited, status=0/SUCCESS)

#dom0 systemd[1]: Starting TCG Core Services Daemon...
#dom0 tcsd_changer_migrate[4380]: tcsd_changer_migrate: already migrated
#dom0 tcsd_changer_identify[4383]: tcsd_changer_identify: identifying TPM
#dom0 tcsd[4387]: **TCSD TDDL[4387]: TrouSerS ioctl: (25) Inappropriate ioctl for device**
#dom0 tcsd[4387]: TCSD TDLL[4387]: TrouSerS Falling baack to Read/Write device support.
#dom0 systemd[1]: **tcsd.service: Control process exited, code=exited status=30**
#dom0 systemd[1]: **Failed to start TCG Core Services Daemon.**
#dom0 systemd[1]: **tcsd.service: Unit entered failed state.**
#dom0 systemd[1]: **tcsd.service: Failed with result 'exit-code'.**
```

**Comment by jonull101** [comment] 2019-02-19 16:33
@marmarek got any idea on this one? check out output below Related issues.

**Comment by jonull101** [comment] 2019-02-22 18:17
@rootkovska
@marmarek 
@rustybird
@mattmccuthen
@phagara

!!!!!

**Comment by strugee** [comment] 2019-02-22 20:36
TrouSerS does not support TPM 2.0, which is why you're getting this error. [Neither does Anti Evil Maid](https://github.com/QubesOS/qubes-antievilmaid/blob/master/anti-evil-maid/README).

**Comment by jonull101** [comment] 2019-02-22 21:44
Thanks! @strugee 

Is none working on the development of AEM to support TPM 2.0?
And is there any source-code for AEM to build on?
Why is none updating tpm-tools for TPM 2.0?
And the support on USB 3.0?
Support on the SSD cache?

**Comment by andrewdavidwong** [comment] 2019-02-23 02:26
Locking due to abuse.

**Comment by DemiMarie** [comment] 2021-12-24 14:07
Closing on the grounds that this isn’t a bug, but a (documented) limitation.

**Closed by DemiMarie** 2021-12-24 14:07 UTC
Labels: T: bug, C: other, P: default

**Comment by DemiMarie** [comment] 2021-12-24 14:09
Closing as duplicate of #6793 which is not locked.
