### ISSUE TITLE
Idea: Qubes-specific notification daemon

### ISSUE THREAD

**Issue by kisik21** [QubesOS/qubes-issues#3953] opened 2018-06-03 11:04 UTC
### Qubes OS version:

`Qubes release 3.2 (R3.2)`, actual for 4.0 too

### Affected component(s): 

dom0's GUI daemon, TemplateVMs, qrexec (used for implementation)

---

### Steps to reproduce the behavior:

```
qvm-run $anyvm 'notify-send "Notification 1"'
qvm-run $anothervm 'notify-send "Notification 2"'
```

### Expected behavior:

Notifications show like in any other Linux distribution, one under another.

### Actual behavior:

Notifications overlap each other, because qubes draw them instead of delegating this to dom0/hypothetical GUI domain that may be used in the future to run Xorg. Thanks to borders, it's impossible to confuse them, but it is still inconvenient.

### Proposal

I propose to implement Qubes-specific notification daemon in two parts working via qrexec as following:
1. In a qube: listen for notifications
2. In a qube: qrexec qubes.ShowNotification for each notification
3. In dom0: for each qubes.ShowNotification call show a dom0 notification with some indication of its source.
This can be easily implemented with a little Python and shell scripting (for dom0). How to indicate qube which emitted for notification is in need to be discussed. Drawing borders would be cool, but needs some sort of a custom notification daemon in dom0, which could probably look a lot more uglier than XFCE4's one (which is the default now).

---

### Related:
https://www.reddit.com/r/Qubes/comments/8o6vae/idea_qubesspecific_notification_daemon/ - original thread on /r/Qubes, author is yours truly.

**Comment by marmarek** [comment] 2018-06-04 00:38
Looks like a duplicate of #889

**Comment by andrewdavidwong** [comment] 2018-06-04 06:02
Duplicate of #889

**Comment by andrewdavidwong** [comment] 2018-06-04 06:02
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-06-04 06:02 UTC
Labels: C: desktop-linux, enhancement
