### ISSUE TITLE
Minimum specifications for Qubes OS 4.0

### ISSUE THREAD

**Issue by abis866i** [QubesOS/qubes-issues#3364] opened 2017-12-03 02:10 UTC
#### Qubes OS version: 4.0 RC3

I have a new computer that I have assembled and I wanted to have installed the Qubes OS 4. Here is what I have:
- CPU: I3 6100 3.7 GH, LGA1154
- Motherboard: MSI 7170 A PC Mate, Z170
- Memory: 32 GB DDR4 ballistic sport 2x16
I checked the requirements before I bought these parts and at least the CPU should have both VT-D, EPX, and VT-X.
I downloaded the Qubes OS 4 RC3 and tried to install but I got an error message: IOMMU/VT-D interrupts remapping is missing.
Can you help?
Thanks.

**Comment by andrewdavidwong** [comment] 2017-12-03 02:50
This issue appears to fall under one of two cases:

1. It may be a duplicate of #3208 (specifically, interrupt remapping not being properly detected, as explained in https://github.com/QubesOS/qubes-issues/issues/3208#issuecomment-339565279).
2. Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there.

If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, and your issue does not fall under either of these two cases, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Closed by andrewdavidwong** 2017-12-03 02:50 UTC
