### ISSUE TITLE
VM color change operation doesn't adjust the .desktop file icon

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1626] opened 2016-01-15 15:10 UTC
E.g. the file at: `.local/share/desktop-directories/fedora-23-ylw-vm.directory` would still have the old icon specified, e.g. `Icon=appvm-black`.

**Comment by marmarek** [comment] 2016-01-15 15:58
Duplicate of #1606

**Closed by marmarek** 2016-01-15 15:58 UTC
Labels: bug, C: desktop-linux, duplicate, P: minor
