### ISSUE TITLE
Qubes-Whonix Tor Connectivity and sdwdate Troubleshooting: "Qubes sys-net workaround"

### ISSUE THREAD

**Issue by quantitative-technologies** [QubesOS/qubes-issues#7563] opened 2022-06-13 20:12 UTC
### Qubes OS release (if applicable)

4.1

### Brief summary

I was unable to connect with Qubes-Whonix. Update was not working either. 

In the [Qubes-Whonix ™ Tor Connectivity and sdwdate Troubleshooting](https://www.whonix.org/wiki/Qubes/Troubleshooting) the `Qubes sys-net workaround` fixed this issue. It 

It says "Please report if this workaround helped.", which is why I created this issue.

**Comment by andrewdavidwong** [comment] 2022-06-14 17:16
FYI @adrelanos

**Comment by adrelanos** [comment] 2022-06-15 10:21
Thank you for the report.

That should not be the case.

Most likely not caused by Whonix. From the perspective of Whonix it doesn't matter if its connectivity is sys-firewall or sys-net.
(That doesn't mean sys-net is the solution because whatever firewalling is done in sys-firewall should be preserved.)

Qubes issue.

Could be an issue similar to this:
https://github.com/QubesOS/qubes-issues/issues/2141

Could you please update the `C:`? @andrewdavidwong

**Comment by andrewdavidwong** [comment] 2022-06-15 14:36
@adrelanos, could you provide a brief description of the problem? I've gathered from your comment that it likely has something to do with Qubes networking, but I still don't really understand what is going on here. Is it the case that a Whonix tool has checked for (and caught) some undesirable networking state in Qubes (and directed the user to report it here)? Is that why this isn't a Whonix issue even though it was reported by a Whonix tool in a Qubes-Whonix context?

**Comment by quantitative-technologies** [comment] 2022-06-15 18:02
> 



> Could you please update the `C:`? @andrewdavidwong

I assume that request was just for @andrewdavidwong (I don't know what `C:` is).

About my issue: It seems to be some intermittent issue with connecting to Tor. I am connected now with `sys-firewall` but just an hour ago I could not connect even with `sys-net`.

So it may have been a coincidence before, when I switched to `sys-net` and it seemed to solve my connection issue.

**Comment by andrewdavidwong** [comment] 2022-06-16 04:54
> I assume that request was just for @andrewdavidwong (I don't know what `C:` is).

Correct. He was simply referring to the [labels](https://www.qubes-os.org/doc/issue-tracking/#labels) on this issue.



> About my issue: It seems to be some intermittent issue with connecting to Tor. I am connected now with `sys-firewall` but just an hour ago I could not connect even with `sys-net`.
> 
> So it may have been a coincidence before, when I switched to `sys-net` and it seemed to solve my connection issue.

Ok. Since it may have just been a coincidence and things are working now, let's close this issue. If the problem recurs, feel free comment here with detailed information about the situation, and we can reopen it.

**Closed by andrewdavidwong** 2022-06-16 04:54 UTC
Labels: T: bug, P: default, needs diagnosis, C: networking

**Comment by adrelanos** [comment] 2022-06-16 06:49
The sys-firewall / sys-net change could be coincidental. Could also be just "normal" Tor connectivity issues.

> @adrelanos, could you provide a brief description of the problem?

User attempts to use networking with "a VM" (to make it more generic, unspecific to Whonix).

* sys-firewall: broken
* sys-net: functional

> I've gathered from your comment that it likely has something to do with Qubes networking,

Indeed.

> but I still don't really understand what is going on here.

Me neither.

> Is it the case that a Whonix tool has checked for (and caught) some undesirable networking state in Qubes (and directed the user to report it here)?

No. What happened: User wasn't able to connect with sys-firewall. Tried sys-net. Worked. That's weird indeed and worth reporting.

> Is that why this isn't a Whonix issue even though it was reported by a Whonix tool in a Qubes-Whonix context?

No tool involved. Manual user witness report.

**Comment by adrelanos** [comment] 2022-06-16 08:39
> So my first thought here is that there is a DNS problem in sys-firewall. That would explain what is happening.

I find that highly unlikely. Whonix doesn't require any functional upstream DNS server. It doesn't use any by default. On the contrary, there is actually a leak test, "Deactivate host DNS":
https://www.whonix.org/wiki/Dev/Leak_Tests#Deactivate_host_DNS

To make that a bit clearer what that would mean in context of Qubes, documented just now:
https://www.whonix.org/wiki/Dev/Leak_Tests#Deactivate_Qubes_DNS

Whonix-Gateway `/etc/resolv.conf`:
https://www.whonix.org/wiki/Whonix-Gateway_System_DNS#Whonix-Gateway_Default_System_DNS_Setting

More details on Whonix-Gateway DNS:
https://www.whonix.org/wiki/Whonix-Gateway_System_DNS
