### ISSUE TITLE
qubesosmamapaxpa.onion doesn't match qubes-os.org

### ISSUE THREAD

**Issue by D-3t66d58drph2j** [QubesOS/qubes-issues#2470] opened 2016-12-01 13:15 UTC
The contents of qubesosmamapaxpa.onion do not match qubes-os.org

Are there really two separate webservers running with two separate versions of the site or is there some kind of man-in-the-middle attack going on? Why don't qubesosmamapaxpa.onion and qubes-os.org point to the same webserver?

**Comment by andrewdavidwong** [comment] 2016-12-01 13:17
Duplicate of #1352. If you can help us out with that issue, we'd really appreciate it!

**Closed by andrewdavidwong** 2016-12-01 13:17 UTC
