### ISSUE TITLE
Display corruption on T450s

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#7894] opened 2022-11-19 12:30 UTC
### Qubes OS release

4.1.1

### Brief summary

Since quite some time I'm encountering graphical corruption on my thinkpad T450s - see pics below. This was definitely not present with 3.x but I don't remember if I got this just after migrating to 4.x (around Feb. this year) or if this happened after some updates.

I've looked at various graphics related issues (eg. #5377 where other issues are linked to) but none seem to be like what I encounter.
However using the `intel` driver rather than the default fb fixes the problem - but then I get very frequent hard freezes or impromptu reboots making the machine impossible to use for work (and unfortunately no way to get a decent oops trace).

pics (dusty screen duh!) - with corruption and without (after refresh):

![gui_glitch](https://user-images.githubusercontent.com/10845291/202849442-c6f64f7e-6e5d-4c3a-920e-6a576a448422.jpg)
![gui_OK](https://user-images.githubusercontent.com/10845291/202849439-65d3acce-0268-42e9-81e8-99d535ba45a2.jpg)

![xterm_glitch](https://user-images.githubusercontent.com/10845291/202849418-b03f71b7-19b5-40ad-bb83-db7f4907af98.jpg)
![xterm_ok](https://user-images.githubusercontent.com/10845291/202849419-ebfb3782-9ba4-4cdf-ac1e-6c67a3aa9b04.jpg)

Findings:

- dom0 windows aren't affected - only qubes' windows.
- the corruption/glitches disappear when the window refreshes, eg. after some time, or when switching workspaces, focusing to another window. ...
- some apps are less affected than others (for instance there's only a slight corruption in firefox when typing stuff, just before the cursor;  it's far worse with xterm).

And unscientific findings, as corruption is always present but to a various degree:

- it's bearable with the laptop on AC, docked, and using an external monitor (which is my setup nowadays 99% of the time - hence why I'm only reporting now - I've been really busy and took the lazy approach of thinking someone would find/fix that issue).
- it's far worse (like, 'really awful') when using the laptop undocked and on battery, making it next to impossible to type a few words in a terminal, let alone program a few lines of code (I have to type blindly/in advance and wait for a refresh - kinda like working with a 2400bps modem back in the day). NotE: I've disabled every power optimization I could find, without any improvement. I have to use another laptop without Qubes OS when I really need to be mobile and just need a browser.
- it's usually worse on the laptop's internal display
- it's somehow worse after undocking and re-docking the laptop ; it seems to be "better" after a clean power on cycle (eg. not after a suspend).

I've asked @andrewdavidwong as I remembered he had a T450s too but he doesn't encounter this problem ; it could be his laptop has a different gpu/revision (lspci on my laptop reports "Intel HD Graphics 5500 rev 09")

As a side note I encounter various issues that I hadn't with 3.x; no idea if they're related; eg. I don't count how many times I've lost some work on libreoffice after my work vm's windows disappear all of a sudden - with the vm still running but no way to launch anything graphical or "recover" the windows. And of course it always happens when I'm in a hurry so I didn't take the time to try to investigate this...

**Comment by jamke** [comment] 2022-11-19 15:13
The glitches on photos look similar to what I currently have on at LVM password prompt on Intel internal GPU.

Can you try adding `i915.enable_psr=0` to the list of kernel parameters.
Like it's described here: https://github.com/QubesOS/qubes-issues/issues/7380#issuecomment-1315081683
Or you can add this parameter without updating grub by simply pressing E button and modifying the kernel parameters during usual Qubes OS boot, but after reboot this will be forgotten.

**Comment by taradiddles** [comment] 2022-11-19 18:48
> Can you try adding `i915.enable_psr=0` to the list of kernel parameters.
> Like it's described here: [#7380 (comment)](https://github.com/QubesOS/qubes-issues/issues/7380#issuecomment-1315081683)

Thanks for the hint ; that's something I had already tried unfortunately :(

(side note - T450s were some of the first laptops with PSR when that feature was being developped on linux; there were quite a few issues back then - I actually helped debug some of them with a guy from Intel; AFAIK it's disabled by default for those gpus, at least on fedora, as various `/sys/...` files seem to confirm).

Re- issue #7380: I've just rebooted and interestingly luks prompt was also garbled - first time I notice that (maybe those are different issues with the same symptom).

**Comment by andrewdavidwong** [comment] 2022-11-19 23:42
> I've asked @andrewdavidwong as I remembered he had a T450s too but he doesn't encounter this problem ; it could be his laptop has a different gpu/revision (lspci on my laptop reports "Intel HD Graphics 5500 rev 09")

I seem to have the same IGP, but for some reason I haven't experienced this. Not sure if it matters, but I've updated to the latest BIOS and use only Debian-minimal-based VMs.

**Comment by taradiddles** [comment] 2022-11-20 08:26
> I seem to have the same IGP, but for some reason I haven't experienced this. Not sure if it matters, but I've updated to the latest BIOS and use only Debian-minimal-based VMs.

I also have the "latest" bios (1.37 / Aug 2019) ; one of the pics was signal-desktop in a debian minimal qube, the other was xterm in fedora minimal (+customizations) so the issue doesn't seem to be distro-dependent.
It's weird that you seem to have the exact same hardware yet you don't experience this; would it be too much to ask that you post the following ?
- `/etc/default/grub` (maybe removing any uuid info)
- `lscpi -v -s 00:02.0` (or the address reported by `lspci | grep -i vga` if it's not 00:02.0)
- `/var/log/Xorg.0.log` (there may be serial numbers in that file so if you're worried, `grep -i load /var/log/Xorg.0.log` ; this will show which driver you're using)

Anything showing that PSR is enabled? 

- `/sys/kernel/debug/dri/0/i915_params/enable_psr`
- `/sys/kernel/debug/dri/0/eDP-1/i915_psr_sink_status`
- `/sys/kernel/debug/dri/0/eDP-1/i915_psr_status`

Do you remember tweaking anything related to intel gfx (like from the [official guide](https://github.com/Qubes-Community/Contents/blob/master/docs/troubleshooting/intel-igfx-troubleshooting.md) or the [community one](https://github.com/Qubes-Community/Contents/blob/master/docs/troubleshooting/intel-igfx-troubleshooting.md)) ?

Have you upgraded from 3.x to 4.x, or did you do a "clean" 4.x install ?

Lastly, are you booting in legacy or in UEFI mode ? (I'm still on legacy as I forgot to switch to UEFI when installing 4.x)

Apologies for all those questions - I'm trying to understand what are the differences between your setup and mine, hopefully I'll find the cause (or at least a workaround).

Thanks !

**Comment by andrewdavidwong** [comment] 2022-11-21 03:39
Clean install, legacy boot, no tweaks.

```
$ cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_CMDLINE_LINUX="rd.luks.uuid=luks-***** rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap plymouth.ignore-serial-consoles i915.alpha_support=1 rd.driver.pre=btrfs rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
GRUB_THEME="/boot/grub2/themes/qubes/theme.txt"
GRUB_CMDLINE_XEN_DEFAULT="console=none dom0_mem=min:1024M dom0_mem=max:4096M ucode=scan smt=off gnttab_max_frames=2048 gnttab_max_maptrack_frames=4096"
GRUB_DISABLE_OS_PROBER="true"
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.qubes.hide_all_usb"
```

```
$ lspci -v -s 00:02.0
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 5036
	Flags: bus master, fast devsel, latency 0, IRQ 58
	Memory at f0000000 (64-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

```
Loading /usr/lib64/xorg/modules/drivers/modesetting_drv.so
Loading /usr/lib64/xorg/modules/drivers/fbdev_drv.so
Loading /usr/lib64/xorg/modules/drivers/vesa_drv.so
```

**Comment by andrewdavidwong** [comment] 2022-11-21 05:25
I think there's a BIOS setting for video RAM. Have you tried adjusting that?

**Comment by andrewdavidwong** [comment] 2022-11-22 11:22
Very strange, indeed! Sorry I couldn't be of more help. Have you considered replacing this laptop with a newer model that's still receiving microcode updates?

**Comment by taradiddles** [comment] 2022-11-22 14:26
> Sorry I couldn't be of more help

No problem - you've spent quite a bit of time comparing with your laptop - thanks.

> Have you considered replacing this laptop with a newer model that's still receiving microcode updates?

I did, but out of curiosity rather than necessity as I find it hard to justify replacing something that's still going strong, modulo this graphical issue (first for the environment, and second for my wallet). I'm addicted to trackpoints so that'd be either another thinkpad or select models from hp/dell. I looked at the T14/T14s gen 3 AMD but they were not available in Europe yet, + there wasn't any HCL report (well, someone has to be first but as I'm getting older I'm not interested in bleeding edge anymore - I just want something that works with minimal tweaking !).

I guess I'll have to wait until someone pays attention to this regression, as there are quite a few similar "graphical glitch/corruption/..." reports here and there, both for old and new hardware, and there weren't such problems with 3.x (and probably neither with 4.0)...

**Comment by brendanhoar** [comment] 2022-11-22 14:36
Grasping...noticing the asymmetrical ram on both...

It's possible the ram difference (size? type? Which mainland bank gets smallest/largest dimm?) might lead the gpu to utilize a slightly different memory map or timing arrangement, exposing a Xen/Linux bug?

B

**Comment by taradiddles** [comment] 2022-11-22 15:25
> It's possible the ram difference (size? type? Which mainland bank gets smallest/largest dimm?) might lead the gpu to utilize a slightly different memory map or timing arrangement, exposing a Xen/Linux bug?

Possibly... That issue is quite puzzling anyway: some (most?) people don't experience this issue, others experience it only with i3 but not with xfce, while for me xfce isn't OK; then, switching to xorg's `intel` driver seems to work for everybody, while I get frequent hard crashes ! I'm 99% percent sure it's not a hardware problem (well maintained laptop, running cool, almost always idling, ...).

fyi bank0 is soldered/4GB/Samsung, bank2 is replaceable/8GB/Hynix-Hyundai. I haven't upgraded the 2nd bank - the module installed from lenovo's factory.

Given that there was no issue with previous releases on the exact same hardware it would mean that something in the software stack has changed (XEN, kernel, fbdev, ...). It's my main laptop/computer so it would be hard to re-install older releases and find which update was the culprit :(

I'll try to limit the amount of memory available next time I reboot on this evening (I can't atm) - I'm not too keen on removing the 2nd bank physically yet - I'll try with xen's `availamem` first - but no idea from which bank the kernel will allocate memory (logically it should be bank0). Another option would be to try to remap memory and/or exclude some memory regions but I don't see how it's feasible with xen's boot options. Let me know if you have any idea !

**Comment by taradiddles** [comment] 2022-11-22 17:51
I've just tried the following things, without success (rebooting/testing between each step):
- `availmem=4000M` (then checked with `xl info` in dom0) with the assumption that this would exclude bank2
- reset bios to default settings
- set gfx memory to 512M (default is 256).

next thing I'll check is if I can "downclock" the ram and/or gfx and see what happens - if it's a timing issue I'd imagine there could be some effect (eg. different artifacts). That said if it was a timing issue I'd expect to have corruption in dom0 windows, which isn't the case. But then, if it isn't a timing issue then why doesn't @andrewdavidwong  have this issue...
It's also not dependent on the screen/panel (which I think is the only component we haven't compared with Andrew) since I encounter corruption on external monitors too.

Mystery ! :)

**Comment by DemiMarie** [comment] 2022-11-23 03:19
> I guess I'll have to wait until someone pays attention to this regression, as there are quite a few similar "graphical glitch/corruption/..." reports here and there, both for old and new hardware, and there weren't such problems with 3.x (and probably neither with 4.0)...

The problem is that I do not know how to fix this, and I suspect nobody else in the Qubes team knows either.  We aren’t graphics experts, and Qubes uses an old X server and old Mesa.

That said, I have one suggestion: @taradiddles would you be willing to try building and using a newer Mesa package for dom0?  If this makes the problem go away, then there is a chance that Qubes might be able to ship newer Mesa packages.

**Comment by taradiddles** [comment] 2022-11-23 07:34
> We aren’t graphics experts, and Qubes uses an old X server and old Mesa.

Don't worry (I realize that my wording - "until someone pays attention" - might have looked like I'm pushing someone to fix that issue - which is of course not the case).

> would you be willing to try building and using a newer Mesa package for dom0

Sure. I just tried but ran into the "dependency hell" typical of trying to backport newer stuff to older distributions. Building the newer mesa package (I used `mesa-22.2.3-1.fc37.src.rpm`) required newer versions of `libva`, then `libdrm`, and then`llvm` - I stopped recompiling/installing at the latter because llvm is a huge package and it'll take forever to compile on my machine now; but most importantly I don't think you'd ever want to repackage this for Qubes OS - that's simply too much maintainer work for an issue that not many people encounter (and for which there's a fix - switching to xorg's `intel` driver - although it doesn't work well for me).

I might give it a try though when I have a bit more time - just to see if it fixes my issue.

**Comment by DemiMarie** [comment] 2022-11-23 07:45
Good news is that R4.2 will have a newer dom0 (at least Fedora 37).  That said, I wonder if i3 is _not_ a compositing window manager.  That could explain why XFCE does not exhibit this behavior.

**Comment by andrewdavidwong** [comment] 2022-11-23 09:37
Have you checked whether you also experience this problem on bare-metal Fedora?

**Comment by taradiddles** [comment] 2022-11-23 10:14
> Have you checked whether you also experience this problem on bare-metal Fedora?

No (I avoid trying stuff on this laptop as it's my main work machine). I don't think there would be any graphic corruption since 1/ bare-metal Xorg Fedora uses the `intel` driver by default (IIRC), 2/ on Qubes OS dom0 is OK with the `fb` driver (only the vms' windows are garbled). I could test if I encounter crashes with the `intel` driver but on Qubes OS they're random and don't happen often enough to reliably test (eg. 1-3x a day); + I wouldn't be able to replicate my Qubes OS workflow/workload on a live distro.

Thinking of it, a test that more closely matches my Qubes OS' setup (/issue) would be to install f32 and xen, use `fb` and install a f36 vm guest to see if there's corruption; if so, do the same install/config with f37 as dom0 and check if the newer xen/mesa fix the issue. But that seems like a daunting and time consuming task !

That said it just occured to me that I could try to build a newer version of Xorg's `intel` driver and see if that fixes the crashes.

**Comment by marmarek** [comment] 2022-11-23 15:32
I can reproduce identical glitches with modesetting driver under xfce if I disable compositing. Enabling compositing back (in "Window Manager Tweaks", no xfwm restart necessary) immediately fixes the issue. I guess i3 doesn't use compositing and that's why it's affected.

Few more data points:
 - the issue seems to affect only VM windows, dom0 windows seems to be unaffected (maybe our gui-daemon misses some steps? or it's about caching attributes of our shared memory for GUI?)
 - the issue applies only to laptop's internal screen; windows placed on external (via DP) screen do not have the issue

**Comment by DemiMarie** [comment] 2022-11-23 15:42
Could we ship a compositing manager for use with i3?  In the future, could we switch to Xwayland + Sway?

**Comment by taradiddles** [comment] 2022-11-23 15:43
> I can reproduce identical glitches with modesetting driver under xfce if I disable compositing. Enabling compositing back (in "Window Manager Tweaks", no xfwm restart necessary)

Oh, that did it ! I thought forcing compositing with xfwm4's compositing=on would have overriden any other xfce setting (+ I had totally overlooked the setting in "Window Manager Tweaks" - oddly it reseted to "unchecked" after a logout/login but that's another issue). Enabling the option immediately removed the artifacts. @DemiMarie was [right](https://github.com/QubesOS/qubes-issues/issues/7894#issuecomment-1324663663).

> the issue seems to affect only VM windows, dom0 windows seems to be unaffected

Yes

> the issue applies only to laptop's internal screen; windows placed on external (via DP) screen do not have the issue

No - I get glitches on external displays too (DP), although with various "intensity" (the internal display always seem worse).

**Comment by andrewdavidwong** [comment] 2022-11-24 10:38
So, should this issue be closed as a duplicate or closed as resolved (or neither)?

**Comment by taradiddles** [comment] 2022-11-24 11:28
> So, should this issue be closed as a duplicate or closed as resolved (or neither)?

I'm not sure either.
In theory `fb` should work without compositing, so the issue isn't solved per se - but there's a workaround ("use compositing"). I don't know if it counts as "resolved" though. If you'd like I could change the title to add "[solved/workaround]" and close the issue with a comment that it's a duplicate of https://github.com/QubesOS/qubes-issues/issues/4782 and https://github.com/QubesOS/qubes-issues/issues/7507 ?

**Closed** 2022-11-24 14:36 UTC
Labels: T: bug, C: other, P: default, hardware support, needs diagnosis
