### ISSUE TITLE
Computer shuts down and restarts when put under stress

### ISSUE THREAD

**Issue by sucrecacao** [QubesOS/qubes-issues#7948] opened 2022-12-14 13:15 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

Qubes shutdown and restart when I have one qube doing an intense work ( compiling gcc ) and I start a browser in another qube ( I was able to reproduce ). The hardware is thinkpad 380 yoga

### Steps to reproduce

- install qubes 4.1.1 on lenovo L380 yoga
- open a qube terminal and run an intense work, like compiling gcc
- open a browser in a new qube

### Expected behavior

- Qubes still runs

### Actual behavior

- Computer shutdown and restart

**Comment by sucrecacao** [comment] 2022-12-14 22:01
Possibly related:
https://github.com/QubesOS/qubes-issues/issues/7785
https://github.com/QubesOS/qubes-issues/issues/7676

**Comment by sucrecacao** [comment] 2022-12-15 00:22
I rolled back to kernel version 5.10 and was not able to reproduce the issue: the system didn't crash on high stress. 

Closing now but might re-open if it happen again

**Comment by DemiMarie** [comment] 2022-12-15 00:28
Can you provide the contents of `/var/lib/systemd/pstore` after a crash?  On UEFI systems Qubes will save a stack trace and dmesg there if the dom0 kernel panics.

**Comment by andrewdavidwong** [comment] 2022-12-15 20:38
> I rolled back to kernel version 5.10 and was not able to reproduce the issue: the system didn't crash on high stress.
> 
> Closing now but might re-open if it happen again

Closing as "cannot reproduce" for now. If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by DemiMarie** [comment] 2022-12-15 23:51
> I rolled back to kernel version 5.10 and was not able to reproduce the issue: the system didn't crash on high stress.
> 
> Closing now but might re-open if it happen again

This is still a bug.  You should not need to roll back your kernel version.  Reopening.

**Comment by sucrecacao** [comment] 2022-12-22 03:43
@DemiMarie I'm back to the latest kernel version 

> Can you provide the contents of `/var/lib/systemd/pstore` after a crash? On UEFI systems Qubes will save a stack trace and dmesg there if the dom0 kernel panics.

How can I check if I'm UEFI? 
I have a dual boot install and I believe I used "legacy mode" or "both" during installation. Not sure if relevant

**Comment by DemiMarie** [comment] 2022-12-22 06:20
> @DemiMarie I'm back to the latest kernel version
> 
> > Can you provide the contents of `/var/lib/systemd/pstore` after a crash? On UEFI systems Qubes will save a stack trace and dmesg there if the dom0 kernel panics.
> 
> How can I check if I'm UEFI? I have a dual boot install and I believe I used "legacy mode" or "both" during installation. Not sure if relevant

If the directory is not empty, then that is sufficient.

**Comment by sucrecacao** [comment] 2023-01-17 12:54
@DemiMarie ,
I have a long period where the computer didn't crash at all, I just got two crashes. 

However `cat /var/lib/systemd/pstore` on dom0 returns a `No such file or directory` 

Any other files where I can find relevant information about the crashes ?

**Comment by DemiMarie** [comment] 2023-01-17 22:30
@marmarek any suggestions?

**Closed** 2024-12-07 14:25 UTC
Labels: T: bug, C: kernel, P: default, hardware support, affects-4.1, eol-4.1
