### ISSUE TITLE
Can unencrypt partition when load OS if contains rare characters

### ISSUE THREAD

**Issue by habemuscode** [QubesOS/qubes-issues#4560] opened 2018-11-30 19:42 UTC
### Qubes OS version:

Qubes-R4.0-x86_64

### Affected component(s): 

Instalation process

---

### Steps to reproduce the behavior:

When you select [in this image](https://i1.wp.com/www.helloitsliam.com/wp-content/uploads/2015/10/101715_1525_QubesOS5.png?ssl=1) the encrypt data, installation process request the passphrase for encrypt the partition.

I put in my passphrase a rare symbol (for more security passphrase) `#`. The process finish well but when i reboot the PC and request me to put the passphrase, dont accept `#` (i try to do wity `Alt Gr + 3` keys of the keyboard)

### Expected behavior:

If i can put that characters in passphrase, i need to be able to put after for unencrypt

### Actual behavior:

I cant put my passphrase when boot the OS

### General notes:

I read documentation but dont found nothing about this, sorry if is a mistake of me :S

---

**Comment by andrewdavidwong** [comment] 2018-12-01 01:49
Possible duplicate of #3352.

**Comment by habemuscode** [comment] 2018-12-01 16:39
Yes, It seems.

You can close now or after release if want 👍

**Closed** 2018-12-01 22:11 UTC
Labels: C: installer, bug
