### ISSUE TITLE
Debian cannot be updated. why?

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5346] opened 2019-09-26 13:07 UTC
I would like to update Debian 10 of QubesOS4.0.2, but I can't. I entered "sudo apt-get updated" in Debian Terminal and got an error.
"N: This must be accepted explicitly before updates for this repository can be applied.See apt-secure (8) manpage for details."
After that, when I entered "sudo apt-get install libreoffice" to install the software, the following message was displayed and I couldn't.
"E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"
How can these be solved?

**Comment by boklm** [comment] 2019-09-26 20:29
This is probably #5149.

**Comment by andrewdavidwong** [comment] 2019-09-26 21:41
Duplicate of #5149

**Comment by andrewdavidwong** [comment] 2019-09-26 21:42
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-09-26 21:42 UTC
