### ISSUE TITLE
sys-firewall: command failed with code: 1

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4665] opened 2018-12-28 09:47 UTC
### Qubes OS version:

R 4.0

### Affected component(s): 

sys-firewall , packages

---

### Steps to reproduce the behavior:

installed fedora-29 , and run update in dom0 

### Expected behavior:

to see clean update/upgrade. 

### Actual behavior:

Errors:

- Firewall with failed command
> sys-firewall: command failed with code: 1
- DNF downloading without installing packages
> DNF will only download packages for the transaction.

- Whats Happening:

````
[user@dom0 ~]$ sudo qubes-dom0-update
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
sys-firewall: command failed with code: 1
Fedora 25 - x86_64 - Updates                    915 kB/s |  24 MB     00:26    
Fedora 25 - x86_64                              1.5 MB/s |  50 MB     00:33    
Qubes Dom0 Repository (updates)                 215 kB/s | 7.7 MB     00:36    
determining the fastest mirror (8 hosts).. done.---  B/s |   0  B     --:-- ETA
Qubes Templates repository                      856  B/s |  10 kB     00:12    
Dependencies resolved.
================================================================================
 Package              Arch   Version                   Repository          Size
================================================================================
Reinstalling:
 anaconda-core        x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 1.5 M
 anaconda-gui         x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 386 k
 anaconda-tui         x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 186 k
 anaconda-widgets     x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 119 k
 python3-blivet       noarch 2:2.1.6-5.fc25            qubes-dom0-current 1.0 M
 python3-kickstart    noarch 1000:2.32-4.fc25          qubes-dom0-current 370 k
 qubes-anaconda-addon noarch 4.0.9-1.fc25              qubes-dom0-current  34 k
 xorg-x11-drv-ati     x86_64 18.0.1-1.fc25             qubes-dom0-current 168 k
 xorg-x11-drv-intel   x86_64 2.99.917-32.20171025.fc25 qubes-dom0-current 696 k

Transaction Summary
================================================================================

Total download size: 4.4 M
Installed size: 4.4 M
DNF will only download packages for the transaction.
Downloading Packages:
(1/9): anaconda-tui-25.20.9-14.fc25.x86_64.rpm  191 kB/s | 186 kB     00:00    
(2/9): anaconda-widgets-25.20.9-14.fc25.x86_64. 125 kB/s | 119 kB     00:00    
(3/9): anaconda-gui-25.20.9-14.fc25.x86_64.rpm  189 kB/s | 386 kB     00:02    
(4/9): python3-kickstart-2.32-4.fc25.noarch.rpm 589 kB/s | 370 kB     00:00    
(5/9): qubes-anaconda-addon-4.0.9-1.fc25.noarch 279 kB/s |  34 kB     00:00    
(6/9): xorg-x11-drv-ati-18.0.1-1.fc25.x86_64.rp 656 kB/s | 168 kB     00:00    
(7/9): xorg-x11-drv-intel-2.99.917-32.20171025. 361 kB/s | 696 kB     00:01    
(8/9): anaconda-core-25.20.9-14.fc25.x86_64.rpm 191 kB/s | 1.5 MB     00:07    
(9/9): python3-blivet-2.1.6-5.fc25.noarch.rpm   166 kB/s | 1.0 MB     00:06    
--------------------------------------------------------------------------------
Total                                           515 kB/s | 4.4 MB     00:08     
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Qubes OS Repository for Dom0                     36 MB/s |  37 kB     00:00    
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-dom0-security-testing
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
sys-firewall: command failed with code: 1
Qubes Dom0 Repository (security-testing)        176 kB/s | 1.5 MB     00:08    
Last metadata expiration check: 0:00:06 ago on Fri Dec 28 09:10:43 2018.
Dependencies resolved.
================================================================================
 Package              Arch   Version                   Repository          Size
================================================================================
Reinstalling:
 anaconda-core        x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 1.5 M
 anaconda-gui         x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 386 k
 anaconda-tui         x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 186 k
 anaconda-widgets     x86_64 1000:25.20.9-14.fc25      qubes-dom0-current 119 k
 python3-blivet       noarch 2:2.1.6-5.fc25            qubes-dom0-current 1.0 M
 python3-kickstart    noarch 1000:2.32-4.fc25          qubes-dom0-current 370 k
 qubes-anaconda-addon noarch 4.0.9-1.fc25              qubes-dom0-current  34 k
 xorg-x11-drv-ati     x86_64 18.0.1-1.fc25             qubes-dom0-current 168 k
 xorg-x11-drv-intel   x86_64 2.99.917-32.20171025.fc25 qubes-dom0-current 696 k

Transaction Summary
================================================================================

Total size: 4.4 M
Installed size: 4.4 M
DNF will only download packages for the transaction.
Downloading Packages:
[SKIPPED] anaconda-core-25.20.9-14.fc25.x86_64.rpm: Already downloaded         
[SKIPPED] anaconda-gui-25.20.9-14.fc25.x86_64.rpm: Already downloaded          
[SKIPPED] anaconda-tui-25.20.9-14.fc25.x86_64.rpm: Already downloaded          
[SKIPPED] anaconda-widgets-25.20.9-14.fc25.x86_64.rpm: Already downloaded      
[SKIPPED] python3-blivet-2.1.6-5.fc25.noarch.rpm: Already downloaded           
[SKIPPED] python3-kickstart-2.32-4.fc25.noarch.rpm: Already downloaded         
[SKIPPED] qubes-anaconda-addon-4.0.9-1.fc25.noarch.rpm: Already downloaded     
[SKIPPED] xorg-x11-drv-ati-18.0.1-1.fc25.x86_64.rpm: Already downloaded        
[SKIPPED] xorg-x11-drv-intel-2.99.917-32.20171025.fc25.x86_64.rpm: Already downloaded
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Qubes OS Repository for Dom0                     36 MB/s |  37 kB     00:00    
[user@dom0 ~]$
````

**Comment by marmarek** [comment] 2018-12-29 00:03
Duplicate of #4616

**Closed by marmarek** 2018-12-29 00:03 UTC
