### ISSUE TITLE
rpmfusion meta-packages should be published on ftp.qubes-os.org repos

### ISSUE THREAD

**Issue by andrewclausen** [QubesOS/qubes-issues#5951] opened 2020-07-14 18:58 UTC
Rpmfusion metadata (such as the signing keys) are included in the fedora 32 template, under the package rpmfusion-free-release-32-0.3.noarch.  I think is a great thing from a security point of view -- it removes the need to check the rpmfusion keys, which is hard to do properly.

However, upgrading a template VM (via running dnf inside the template VM) does not install this package.  I'm not sure why not.

One solution to this problem would be to publish the rpmfusion metadata rpms inside the Qubes rpm repositories, i.e. inside https://ftp.qubes-os.org/repo/yum/r4.0/current/vm/fc32/rpm

**Comment by andrewclausen** [comment] 2020-07-14 19:25
I suppose a bigger issue is: shouldn't all packages inside the template also be available in the qubes or fedora repositories?

**Comment by marmarek** [comment] 2020-07-14 19:27
This package is installed from rpmfusion repository, signed by their key. If you wish to update it (for example during template upgrade, or any other reason), simply enable rpmfusion repository.

**Comment by andrewclausen** [comment] 2020-07-14 19:46
But how can I check the signature if I don't have their key?  It's a bootstrapping problem.

**Comment by marmarek** [comment] 2020-07-14 21:06
You do have the key - installed with the (pre-installed) rpmfusion package. It includes also keys for future releases, so you can use that for verifying package from newer version too.

**Comment by marmarek** [comment] 2020-07-14 21:11
```
$ rpm -ql rpmfusion-free-release-30-0.3
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-29
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-29-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-30
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-30-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-31
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-31-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-latest
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-rawhide
/etc/yum.repos.d/rpmfusion-free-updates-testing.repo
/etc/yum.repos.d/rpmfusion-free-updates.repo
/etc/yum.repos.d/rpmfusion-free.repo
```
Newer rpmfusion-free-release contains even fedora-32 key, so you can skip 31:
```
$ rpm -ql rpmfusion-free-release-30-2
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-30
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-30-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-31
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-31-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32-primary
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-latest
/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-rawhide
/etc/yum.repos.d/rpmfusion-free-updates-testing.repo
/etc/yum.repos.d/rpmfusion-free-updates.repo
/etc/yum.repos.d/rpmfusion-free.repo
```

**Comment by andrewclausen** [comment] 2020-07-14 22:41
Unfortunately, I have none of these files or packages.  My hypothesis is that when I upgraded my fedora-31 template to fedora-32 with

> dnf --releasever=32 --best --allowerasing distro-sync

all of the files and packages you mentioned got erased.  Or at least, I have no other hypothesis for why I don't have them.  I do have some .rpmsave remnants, but that is all.

You were expecting the upgrade would not delete this files and packages?

I'm not sure how I might reproduce this situation.  The fedora-31 template has retired, so I can't install it easily.

Please note: I found a work-around (I downloaded the fedora-32 template rpm, and copied the relevant files out of it).  My motivation here is to make this work well for everyone.  There is no need to spend any time trying to give me any help.

**Comment by andrewdavidwong** [comment] 2020-07-15 09:00
It sounds like the original feature request ("rpmfusion meta-packages should be published on ftp.qubes-os.org repos") is considered unnecessary, since the required files are already included or available from appropriate places. However, it appears that going through this has unearthed a possible bug in which @andrewclausen's Fedora 32 template is missing keys that it should have. However, @andrewclausen has also said there's no need to help with the latter problem and that it's unclear how it could be reproduced. So, I'm going to close this as `not an issue`, since the original feature request has been deemed unnecessary, and it appears that there is nothing actionable left. If anyone feels that this issue should be reopened, please let us know.

**Closed by andrewdavidwong** 2020-07-15 09:00 UTC
Labels: P: default, T: enhancement

**Comment by andrewclausen** [comment] 2020-07-15 10:30
Thank you Andrew, but that isn't quite what I meant.  What I meant is: we ought to figure out why my rpmfusion package was uninstalled -- but for the benefit of others, not my own benefit.

I was wrong about the difficulties of installin old templates. I don't think it will be hard to reproduce after all.  I will try to reproduce it soon.

**Comment by andrewclausen** [comment] 2020-07-15 12:28
I have reproduced the problem now.  I installed the fedora-30 template (`qubes-dom0-update qubes-template-fedora-30`), and I issued this command from [the documentation](https://www.qubes-os.org/doc/template/fedora/upgrade/) to upgrade it:

```
sudo dnf --releasever=31 --best --allowerasing distro-sync
```

This command erases the rpmfusion packages:

```
...
Removing dependent packages:
rpmfusion-free-release           noarch 30-0.3                   @@commandline
                                                                          8.7 k
rpmfusion-nonfree-release        noarch 30-0.3                   @@commandline
                                                                           8.8 k
 
Transaction Summary
================================================================================
Install    49 Packages
Upgrade  1110 Packages
Remove      2 Packages

Total download size: 1.1 G
Is this ok [y/N]: 
```

It would be better if these packages were either upgraded, or at least preserved.

**Comment by fepitre** [comment] 2020-07-15 12:34
https://www.qubes-os.org/doc/template/fedora/upgrade/#fedora-30

**Comment by andrewclausen** [comment] 2020-07-15 12:39
Actually, I had enabled the rpmfusion repositories.  (That was the only other thing I did -- I did it to try to mimic what I had done in the past, to increase the chance of reproducing the problem.)

**Comment by fepitre** [comment] 2020-07-15 14:12
We are not going to provide RPM release packages in Qubes official repos as they are not Qubes components.

> Also, that release note is for upgrading **to** Fedora 30, not **from** Fedora 30.

Even if it's not upgrading ***to*** Fedora 30, I've just installed a fresh Fedora 30, enabled RPM fusion repos, and ran `dnf --releasever=32 distro-sync` it does upgrade RPM Fusion repo RPM and it does NOT remove them.

If something goes wrong with those meta-packages it's related to RPM Fusion not Qubes. Fedora 30 is EOL since May 26 so I doubt they would change anything is somthing is broken in their release packages.

**Comment by andrewclausen** [comment] 2020-07-15 18:15
@fepitre, thanks for trying this out.  I figured out the problem: I hadn't actually enabled the rpmfusion repo's.  I had used the command ``sudo dnf config-manager --enablerepo rpmfusion-free``, but apparently this doesn't do the job!  You have to do either ``sudo dnf config-manager --enable rpmfusion-free`` or ``sudo dnf config-manager --enablerepo rpmfusion-free --save``.  This design of ``dnf`` strikes me as unwise, but this is not the place to discuss that.

So it seems that for the rpmfusion metadata gets deleted during upgrades if both

1. the upgrade happens with the dnf option ``--allowerasing``, and
2. the rpmfusion repositories are disabled.

I don't think this is a result of broken packages -- it is the behaviour I would expect from the current arrangement of Fedora and Qubes not including the rpmfusion meta-package in their repositories.

I still think that Qubes Fedora templates ought to include the rpmfusion meta-package in its repository.  (In fact, I think Fedora ought to include it, and Qubes ought to inherit it.)  While it's true that it's not a Qubes or Fedora component, I don't see how this is relevant to the decision.  In principle, you might think there is a disadvantage of duplicating the package -- what if the rpmfusion metapackages published by Qubes and Rpmfusion get out of sync with each other?  But I don't think this would be a problem.  If Qubes only ever publishes rpmfusion metapackages that were previously publish by RpmFusion, then rpm versioning would take care of the rest.  Specifically, multiple versions of the metapackages would remain available for installation, but dnf would default to the most recent version.  This is how dnf handles multiple versions of kernel packages (see ``sudo dnf --showduplicates list kernel`` for details).  A corollary is that there is no need to regularly update the rpmfusion metapackage -- this would only be necessary when signing keys change.

Since there don't seem to be any important disadvantages (unless I am missing something), and there is a big security advantage (ensuring users have the signing keys whenever they need them, even after upgrades), it seems like an easy decision to me.

**Comment by andrewclausen** [comment] 2020-07-16 13:07
I asked upstream (on #fedora-devel) about this, and they were very helpful!  They told me:

1. The reason they don't distribute rpmfusion metadata is legal, especially software patents.  This is a relevant concern for Qubes too.

2. But they do distribute lots of signing keys inside the package distribution-gpg-keys, which is a big help.

Perhaps Qubes ought to advertise this package more?  (I can open a new issue with more specific proposals.)

**Comment by marmarek** [comment] 2020-07-16 13:11
On Thu, Jul 16, 2020 at 06:07:52AM -0700, Andrew Clausen wrote:
> 2. But they do distribute lots of signing keys inside the package distribution-gpg-keys, which is a big help.
> 
> Perhaps Qubes ought to advertise this package more?  (I can open a new issue with more specific proposals.)

Oh, I didn't know that package. Sounds useful indeed!

**Comment by andrewclausen** [comment] 2020-07-16 13:17
It just occurred to me that it would be helpful for the Qubes signing keys to go into that package too.  It would help safely bootstrap a Qubes installation.  Should I open a new issue?

**Comment by andrewdavidwong** [comment] 2020-07-16 13:30
It looks like this should remain closed as `not an issue` after all. If that's incorrect, please let me know.

The separate things that have been raised here are very different from the original bug report and therefore should be in separate issues.

**Comment by andrewclausen** [comment] 2020-07-16 13:44
Thanks @andrewdavidwong, I agree.

**Comment by andrewclausen** [comment] 2020-07-16 14:31
FYI: the Qubes signing keys have just been accepted upstream into the distribution-gpg-keys package.  (It might take a while to trickle down into the rpms...)
