### ISSUE TITLE
 qvm-usb a does not attach USB device

### ISSUE THREAD

**Issue by SubjectMatterExpert** [QubesOS/qubes-issues#3358] opened 2017-11-30 05:41 UTC
#### Qubes OS version:

4.0 RC3

#### Affected TemplateVMs: 

dom0
---

### Steps to reproduce the behavior:

1) plug in USB device
2) issue qvm-usb attach command in dom0, e.g.: 
    qvm-usb a personal sys-usb:2-5
3) Error Message: 
Device attach failed: /usr/lib/qubes/usb-import: line 37: [: sta: integer expression expected/usr/lib/qubes/usb-import: line51: printf: write error: Invalid argument

Note: the USB device is not attached to dom0 originally, but to sys-usb.

### Expected behavior:

USB device gets attached to target vm (e.g. to personal)

### Actual behavior:

1) Error message (see above)
2) USB device does not show up in the target vm (e.g. in personal)
3) USB device disappears from sys-usb

### General notes:

USB device gets attached to target vm (here: to personal)

---

#### Related issues:

May be related to issue: 
https://github.com/QubesOS/qubes-issues/issues/3343

**Comment by andrewdavidwong** [comment] 2017-11-30 05:45
This appears to be a duplicate of #2860. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-11-30 05:45 UTC

**Comment by adrelanos** [comment] 2017-11-30 11:39
> Device attach failed: /usr/lib/qubes/usb-import: line 37: [: sta: integer expression expected/usr

This is a harmless parsing bug. The protocol header reads "sta" first
before any other output. If "sta", the loop should `continue` (in bash
terms), i.e. go on with the next iteration.

Can you make head or tail of this and fix this please?

> /lib/qubes/usb-import: line51: printf: write error: Invalid argument

The rest I don't know.
