### ISSUE TITLE
qubes-builder: qubes-core-agent-passwordless-root is missing in qubuntu template

### ISSUE THREAD

**Issue by lgromanowski** [QubesOS/qubes-issues#6477] opened 2021-03-22 19:52 UTC
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

qubes-builder / qubuntu template

**Brief summary**

`qubes-core-agent-passwordless-root` is missing in `template_qubuntu/packages_qubes.list` or `template_qubuntu/packages_qubes_standard.list` (not sure which one is used in building focal-desktop template image). On unmodified files I cannot use sudo without password in focal-desktop template, after adding `qubes-core-agent-passwordless-root` to both packages_qubes*.list sudo works as expected (without a password).

**How Reproducible**

always

**To Reproduce**

1. build focal-desktop template
2. after installation run terminal inside focal-template
3. run a command with sudo, ie. sudo apt update

**Expected behavior**

sudo shouldn't ask for a password (like in fedora/debian templates)

**Actual behavior**

sudo asks for a users' password

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment] 2021-03-22 20:18
It is pulled in by [qubes-vm-recommended meta-package](https://github.com/QubesOS/qubes-meta-packages/blob/release4.0/debian/control#L50) . Did you get some errors when building the template?

**Comment by lgromanowski** [comment] 2021-03-22 20:23
I'll check the logs, but from what I saw on the console there were no errors - last lines were:
`-> Building template focal (logfile: build-logs/template-focal.log)...
--> Done.`
for both cases (with and without qubes-core-agent-passwordless-root added)

**Comment by unman** [comment] 2021-03-24 04:26
Duplicate of #6307
I'll check out why that resolution isn't being applied.

**Comment by andrewdavidwong** [comment] 2021-03-24 05:46
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-03-24 05:46 UTC
Labels: C: Debian/Ubuntu, C: builder, P: default, T: bug
