### ISSUE TITLE
qubes-vm-settings - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3191] opened 2017-10-19 12:21 UTC
#### Qubes OS version:

Qubes R4 with all Qubes testing repositories

#### Affected TemplateVMs: 

Dom0

---

### Steps to reproduce the behavior:

Install Qubes R4 with all Qubes testing repositories.

Enable Qubes community templates repository in /etc/yum.repos.d/qubes-templates.repo.

    sudo qubes-dom0-update qubes-template-whonix-gw qubes-template-whonix-ws

(Did last command because of https://github.com/QubesOS/qubes-issues/issues/3188.)

    sudo qubesctl state.sls qvm.sys-whonix
    sudo qubesctl state.sls qvm.sys-whonix
    sudo qubesctl state.highstate

    qvm-prefs --set sys-whonix netvm sys-firewall

    qubes-vm-settings anon-whonix

### Expected behavior:

Exit with return code `0` and no output.

### Actual behavior:

`Segmentation fault (core dumped)`

### General notes:

After running `qubes-vm-settings sys-whonix` - which worked without this issue - I no longer can reproduce this issue.

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/2157
https://github.com/QubesOS/qubes-issues/issues/2954

**Comment by marmarta** [comment] 2018-07-15 20:05
I cannot reproduce it with the steps above - I'd guess it was fixed in some update inbetween; I'm closing this ticket, unless of course someone stumbles upon the bug again.

**Closed by marmarta** 2018-07-15 20:05 UTC
Labels: C: core, P: major, bug
