### ISSUE TITLE
SSSD authselect profile is used, but SSSD is not installed

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8981] opened 2024-02-27 21:10 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 but I believe R4.1 was also affected

### Brief summary

Qubes OS uses the default “SSSD” authselect profile, but does not (and should not) install SSSD.  This results in the following log spam: `PAM adding faulty module: /usr/lib64/security/pam_sss.so`.

This can be fixed by using the “minimal” profile, which does not use SSSD.  This is not the default upstream because “minimal” doesn’t support smart cards, fingerprint readers, or LDAP, but Qubes VMs use none of these.

### Steps to reproduce

`sudo journalctl -b`

### Expected behavior

`PAM adding faulty module: /usr/lib64/security/pam_sss.so` doesn’t appear in the logs.

### Actual behavior

It does.

**Comment by marmarek** [comment] 2024-02-27 22:59
Duplicate of #8595

**Closed** 2024-02-27 23:00 UTC
Labels: T: bug, R: duplicate, C: Fedora, P: default, affects-4.1, affects-4.2

**Comment by DemiMarie** [comment] 2024-02-28 21:11
@marmarek I think this issue is about VMs, wheras #8595 is about dom0.
