### ISSUE TITLE
Add support for efi tweaks to qubes installer

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#7060] opened 2021-11-14 11:47 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

With the move to grub in Qubes OS 4.1.0, the system requires significantly less post-install fiddling to make it boot properly. Unfortunately we still have not reached a point yet where the installation _just works_. For example, some systems will never find `EFI/qubes/grub.efi` and only support `EFI/BOOT/BOOTX64.efi`. Every time a system update modifies `/boot/`, users have to do copy files and edit configs by hand, in order to apply these updates.

### The solution you'd like

The installer should provide an advanced menu where such settings can be specified. Idealy it detects and applies these workarounds automatically, e.g. by invoking `efibootmgr`. These workarounds should be reapplied on every system update which affects `/boot/`.

### The value to a user, and who that user might be

Installing Qubes OS should just work. Updating grub, xen or the kernel should _not_ require manual fiddling in the `/boot/` directory. Users should not have to write and maintain their own post-update shell scripts.

**Comment by fepitre** [comment] 2021-11-14 14:58
This is rather an upstream feature request for rhinstaller/anaconda.

**Comment by DemiMarie** [comment] 2021-11-14 15:48
> This is rather an upstream feature request for rhinstaller/anaconda.

Indeed, but it is still a valid feature request, and we should backport the implementation when one arrives upstream.  Marking as “not our bug” to indicate this.

**Comment by andrewdavidwong** [comment] 2021-11-14 21:41
> > This is rather an upstream feature request for rhinstaller/anaconda.
> 
> Indeed, but it is still a valid feature request, and we should backport the implementation when one arrives upstream. Marking as “not our bug” to indicate this.

This is not the best way to indicate that because (1) this is not a bug report but rather an enhancement request, so `not our bug` is technically inapplicable; and (2) an issue should not be closed when there's still some further action required on our end (both as a matter of good practice and simply because it's very likely to be forgotten).

Instead, our usual approach for this sort of case is to leave the issue open and apply the `waiting for upstream` label.

**Comment by AlxHnr** [comment] 2022-04-03 21:17
I just tried the installer again. Those issues are specific to my machine. My problem was that the boot order was locked in my bios, which prevented anaconda from doing its thing. Now everything works fine and I can install Qubes OS without any efi hacks! Feel free to close this issue.

**Closed** 2022-04-04 01:26 UTC
Labels: T: enhancement, C: installer, P: default, waiting for upstream

**Comment by noskb** [comment] 2023-04-20 04:40
It seems to me that `EFI/BOOT/BOOTX64.efi` should be created by default during installation as a fallback. On some firmware, such as MSI motherboards, boot entries such as `EFI/qubes/grubx64.efi` are deleted after reboot and are no longer bootable and must be manually configured by a user [0]. I recently installed Qubes OS on my MSI PRO Z790-P and still had to do that.

`EFI/BOOT/BOOTX64.efi` is an insurance for such cases as it is automatically detected by the firmware even if the boot entry is missing. Fedora and Ubuntu have it by default.

[0]
https://forum.qubes-os.org/t/6171
https://forum.qubes-os.org/t/8784
https://forum.qubes-os.org/t/16612
https://forum.qubes-os.org/t/17400
https://forum.qubes-os.org/t/17982

**Comment by andrewdavidwong** [comment] 2023-04-20 06:09
> It seems to me that `EFI/BOOT/BOOTX64.efi` should be created by default during installation as a fallback. On some firmware, such as MSI motherboards, boot entries such as `EFI/qubes/grubx64.efi` are deleted after reboot and are no longer bootable and must be manually configured by a user [0]. I recently installed Qubes OS on my MSI PRO Z790-P and still had to do that workaround.
> 
> `EFI/BOOT/BOOTX64.efi` can be an insurance for such cases as it is automatically detected by the firmware even if the boot entry is missing. Fedora and Ubuntu have it by default.

Although this issue and your request are closely related, they seem to me to be about fundamentally different things. This issue is about providing an interface for users to tweak or configure EFI settings, whereas your request is for `EFI/BOOT/BOOTX64.efi` to be created as a fallback without any user intervention. This is not my area of expertise, so I could be misunderstanding something, but the two requests seem different enough for yours to merit a separate issue.

**Comment by noskb** [comment] 2023-04-20 11:47
Indeed. Thank you for pointing that out.
