### ISSUE TITLE
Application Menu Shortcuts

### ISSUE THREAD

**Issue by f0xy** [QubesOS/qubes-issues#6180] opened 2020-11-03 06:15 UTC
**Qubes OS version**
Qubes 4.0

**Affected component(s) or functionality**

.config/menus/applications-merged/ menu items not deleted on qvm-remove

**Brief summary**
Menu shortcuts remain after deletion. 

**To Reproduce**

1. Remove Any VM or Template
2. Check .config/menus/applications-merged/ 

**Expected behavior**
Removal of menu items.

**Actual behavior**
Menu items remain

**Screenshots**
N/A

**Additional context**
N/A

**Solutions you've tried**
N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

**Comment by andrewdavidwong** [comment] 2020-11-03 06:33
Duplicate of #529

**Comment by andrewdavidwong** [comment] 2020-11-03 06:33
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-11-03 06:33 UTC
Labels: P: default, T: bug
