### ISSUE TITLE
Firefox switches mouse cursor properly while Google Chrome does not

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7409] opened 2022-04-02 06:27 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

R4.1 introduced a feature that cursor can change on appVM request.

This works for firefox but not for google chrome.

### Steps to reproduce

1. Start an appVM on R4.1 with firefox and google chrome both installed, be it a fedora or debian

2. Test the cursor feature on firefox and google chrome

### Expected behavior

Cursor changing feature works both.

### Actual behavior

Cursor changing feature only works in firefox.

**Comment by drewwiens** [comment] 2022-07-15 21:33
This is probably related to #7238 because Electron is Chromium based

**Comment by DemiMarie** [comment] 2022-07-16 03:14
@drewwiens @logoerthiner1 I am almost certain it is a duplicate.

**Comment by andrewdavidwong** [comment] 2022-07-16 03:54
> @drewwiens @logoerthiner1 I am almost certain it is a duplicate.

Closing as a duplicate of #7238, then.

------

To all:

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-07-16 03:54 UTC
Labels: R: duplicate, C: gui-virtualization, P: default
