### ISSUE TITLE
Add Qubes OS As OVA File For Virtual Machien For Testing/Tutorial/Fun

### ISSUE THREAD

**Issue by cheznewa** [QubesOS/qubes-issues#7311] opened 2022-02-27 04:27 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

[I Know This Issue But Here Is Different](https://github.com/QubesOS/qubes-issues/issues/5041)

### The problem you're addressing (if any)
Since The QubesOS 4, Im Tired The Message Say "Missing The IOMMU/VT-D" In VirtualBox So, I Required To Install On A Laptop But He Missing The IOMMU.

### The solution you'd like
In The Download Page, Is Possible To Add OVA Contain Preinstalled Qubes OS With VM Qubes Work, Inside VirtualBox, For Testing Before, Make A Tutorial, And Fun, After I Know Is Insecure, But It's Just For Testing Before, Make A Tutorial, And Fun And Those Who Whant Not Install It.

I Recommanded The OVA Disk Size Up To 256GB.

**Comment by andrewdavidwong** [comment] 2022-02-27 13:11
Duplicate of #5041 and #5954.

**Comment by andrewdavidwong** [comment] 2022-02-27 13:11
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-02-27 13:11 UTC
Labels: T: enhancement, P: default
