### ISSUE TITLE
boot error. Try to start VM already deleted

### ISSUE THREAD

**Issue by enricota66** [QubesOS/qubes-issues#4264] opened 2018-08-29 21:10 UTC
Hi everyone

### Qubes OS version:
Last version (4.0) dom0 updated

### Affected component(s): 

BOOT

---

### General notes:

boot log at:
/var/log/boot.log

"Failed to start Start Qubes VM my_VMname.
See systmctl status qubes-vm@my_VMname. service for details..

The problem is this VM "my_VMname" don't exist, no more, now is deleted...
I have try to make new one whit the same name and delete a second time.
But no solve.
Thanks a lot for your hard work.

---

**Comment by andrewdavidwong** [comment] 2018-08-30 04:57
Duplicate of #4014

**Comment by andrewdavidwong** [comment] 2018-08-30 04:58
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-30 04:58 UTC

**Comment by enricota66** [comment] 2018-08-30 14:45
Hi 
checked how to reproduce the behavior,  seems the same  of #4014.
thanks for your reply!
