### ISSUE TITLE
Domain '[whichever appVM]': qrexec not connected.

### ISSUE THREAD

**Issue by gameld** [QubesOS/qubes-issues#2667] opened 2017-03-04 15:31 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23

---

### Expected behavior:
No issues on startup of appVMs
### Actual behavior:
Often when starting appVMs, the dom0 manager will show the yellow warning triangle. When hovering over it, it says "Domain '[whichever appVM]: qrexec not connected"
### Steps to reproduce the behavior:
Inconsistent, but only happens when starting the appVMs
### General notes:
Usually goes away when restarting the appVM; sometimes takes 2 restarts.

Sometimes dom0 returns an error like:

```
Line: assert not vm.is_running()
func: start_vm
line.:1171
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
----
line: self.caller.start_vm(vm)
func: check_if_vm_has_shutdown
line no.:289
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py"
```

This error seems to occur when qrexec doesn't connect multiple times in a row.

**Comment by andrewdavidwong** [comment] 2017-03-05 09:18
Please check whether this is a duplicate of #2001.

**Comment by gameld** [comment] 2017-03-07 05:16
Hello,

It appears that this is related to that. I apologize. My searching the
bug reports didn't turn this up so I submitted a new one.

The only changes I have:

I was using the Fedora-23 templates.

I am using Qubes 3.2

I was not attempting to open multiple applications in a single appVM.
Doing this while opening Firefox in both the Personal and Work VMs at
the same time (e.g. after updating the template).

Thank you.

**Comment by andrewdavidwong** [comment] 2017-03-08 00:49
> I was not attempting to open multiple applications in a single appVM.
Doing this while opening Firefox in both the Personal and Work VMs at
the same time (e.g. after updating the template).

This sounds like it's not a duplicate of #2001, then.

**Comment by jpouellet** [comment] 2017-03-13 10:03
I can reproduce the error in case of opening two applications in the same AppVM with 100% reliability (this is a well-known behavior), and have never even once been able to reproduce the error in case of opening two applications in different AppVMs.

@gameld Can you please double-check this is indeed what you experienced, and whether or not it is reliable?

**Comment by andrewdavidwong** [comment] 2019-04-01 04:12
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Closed by andrewdavidwong** 2019-04-01 04:12 UTC
Labels: C: core, T: bug
