### ISSUE TITLE
Recurring dkms build and 'qubes-kernel-vm-support' apt error

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#5072] opened 2019-06-02 18:54 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
debian-10 template (upgraded from 9)

**Brief summary**
Whenever interacting with `apt` functions like install or remove, DKMS attempts a lengthy rebuild of a module and then reports an error.

So far this has been an annoying time-waster, but hasn't stopped apt from processing other packages.

**To Reproduce**
In a debian-10 template, `apt-get install` for any package will trigger it.

**Expected behavior**
The apt command completes without errors, or at least without errors unrelated to the non-kernel packages I'm trying to work with.

**Actual behavior**
After a lot of extra processing, a post-installation script error is reported for package `qubes-kernel-vm-support`.

**Additional context**
Output when I installed the mate-notification-daemon package:
```
$ sudo apt install mate-notification-daemon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mate-notification-daemon is already the newest version (1.20.2-1).
mate-notification-daemon set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-compiler-gcc-6-x86 linux-headers-4.9.0-8-amd64 linux-headers-4.9.0-8-common linux-image-4.9.0-8-amd64 linux-kbuild-4.9
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up qubes-kernel-vm-support (4.0.23+deb10u1) ...
update-initramfs: deferring update (trigger activated)
Removing old u2mfn-4.0.23 DKMS files...

-------- Uninstall Beginning --------
Module:  u2mfn
Version: 4.0.23
Kernel:  4.19.0-4-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

u2mfn.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.0-4-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.......

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  u2mfn
Version: 4.0.23
Kernel:  4.19.0-5-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

u2mfn.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.0-5-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 4.0.23
completely from the DKMS tree.
------------------------------
Done.
Loading new u2mfn-4.0.23 DKMS files...
dpkg: warning: version '4.19.43-1.pvops.qubes.x86_64' has bad syntax: invalid character in revision number
dpkg: warning: version '4.19.43-1.pvops.qubes.x86_64' has bad syntax: invalid character in revision number
dpkg: warning: version '4.19.43-1.pvops.qubes.x86_64' has bad syntax: invalid character in revision number
It is likely that 4.19.43-1.pvops.qubes.x86_64 belongs to a chroot's host
Building for 4.19.0-4-amd64, 4.19.0-5-amd64, 4.19.15-1.pvops.qubes.x86_64, 4.19.43-1.pvops.qubes.x86_64 and 4.9.0-8-amd64
Building initial module for 4.19.0-4-amd64
Done.

u2mfn.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-4-amd64/updates/dkms/

depmod......

DKMS: install completed.
Building initial module for 4.19.0-5-amd64
Done.

u2mfn.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-5-amd64/updates/dkms/

depmod....

DKMS: install completed.
Module build for kernel 4.19.15-1.pvops.qubes.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 4.19.43-1.pvops.qubes.x86_64
Error! Bad return status for module build on kernel: 4.19.43-1.pvops.qubes.x86_64 (x86_64)
Consult /var/lib/dkms/u2mfn/4.0.23/build/make.log for more information.
dpkg: error processing package qubes-kernel-vm-support (--configure):
 installed qubes-kernel-vm-support package post-installation script subprocess returned error exit status 10
Processing triggers for initramfs-tools (0.133) ...
update-initramfs: Generating /boot/initrd.img-4.19.0-5-amd64
cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries 
    nor crypto modules. If that's on purpose, you may want to uninstall the 
    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs 
    integration and avoid this warning.
I: The initramfs will attempt to resume from /dev/xvdc1
I: (UUID=9628f1f5-9a0b-4a5a-936d-9b9723382e8a)
I: Set the RESUME variable to override this.
Errors were encountered while processing:
 qubes-kernel-vm-support
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by marmarek** [comment] 2019-06-03 21:46
Duplicate of #4963

**Closed by marmarek** 2019-06-03 21:46 UTC
Labels: C: Debian/Ubuntu, P: default, T: bug
