### ISSUE TITLE
Cannot detach a persistently attached microphone

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6217] opened 2020-11-20 05:53 UTC
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

Microphone passthrough

**Brief summary**

A persistently attached microphone device cannot be detached.  I had to manually edit `qubes.xml` to fix the problem.

**How Reproducible**

Not sure.

**To Reproduce**

1. Run `qvm-device mic attach --persistent -- <VM name here> dom0:mic`
2. Run `qvm-device mic detach -- <VM name here> dom0:mic` 

**Expected behavior**

The detach succeeds

**Actual behavior**

The detach fails and I had to edit `qubes.xml` manually.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment] 2020-11-20 11:09
Duplicate of #4054

**Comment by andrewdavidwong** [comment] 2020-11-20 11:09
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-11-20 11:09 UTC
Labels: P: default, T: bug
