### ISSUE TITLE
Qubes systray pop-up is too short

### ISSUE THREAD

**Issue by tutaleedoo** [QubesOS/qubes-issues#3369] opened 2017-12-07 05:58 UTC
#### Qubes OS version:

Qubes release 4.0 (R4.0)

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behaviour:

1. Start 2 or more VMs
2. Left-click or right-click the Qubes icon in the systray

### Expected behaviour:

- As many VMs are displayed as possible (limited only by the height of the screen)
- The pop-up is scrollable only if the list of VMs cannot fit within the height of the screen

### Actual behaviour:

- The behaviour is inconsistent, but usually the pop-up is scrollable and only displays one or two items at a time

### General notes:

- It's difficult to work with the systray pop-up when only one or two items are displayed at a time
- Scrolling is done by mouseover, and it's very easy to scroll past items when the pop-up height is tiny

---

#### Related issues:

- Issue #2132

**Comment by tutaleedoo** [comment] 2017-12-07 07:23
To better illustrate my point, I've attached a screen shot
![systray](https://user-images.githubusercontent.com/34330122/33703320-dae1018a-dae4-11e7-81fc-28f97634c4af.png)

**Comment by andrewdavidwong** [comment] 2017-12-15 05:09
This appears to be a duplicate of #2970. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-15 05:09 UTC
Labels: C: qubes-manager, enhancement, UX
