### ISSUE TITLE
Qube settings does not start

### ISSUE THREAD

**Issue by ctr49** [QubesOS/qubes-issues#5208] opened 2019-07-30 21:51 UTC
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Qubes Settings

**Brief summary**
Cannot edit a Qube by using Qube settings.

**To Reproduce**

1. Open Qube Manager
2. Select Qube to edit (any, including global preferences)
3. Hit the "Qube Settings" button or right-click and select "Qube settings"
4. nothing happens.

- or

1. start "Qube settings" from within a Qube.

**Expected behavior**
A new window to change Qube settings appears.

**Actual behavior**
Nothing happens when started from Qube Manager. Error message when starting Qube settings directly.

**Screenshots**
![Screenshot_2019-07-30_23-35-55](https://user-images.githubusercontent.com/1297771/62167598-dfb63b80-b323-11e9-9e1a-30262fb4cb18.png)

**Additional context**
Details // console output (when starting Qube Manager from console):
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py", line 1025, in action_settings_triggered
    vm, self.qt_app, "basic")
  File "/usr/lib/python3.5/site-packages/qubesmanager/settings.py", line 174, in __init__
    self.__init_advanced_tab__()
  File "/usr/lib/python3.5/site-packages/qubesmanager/settings.py", line 707, in __init_advanced_tab__
    allow_default=True, allow_none=True)
  File "/usr/lib/python3.5/site-packages/qubesmanager/utils.py", line 136, in prepare_kernel_choice
    key=KernelVersion)
  File "/usr/lib/python3.5/site-packages/qubesmanager/utils.py", line 124, in __init__
    self.contents = [int(x) for x in re.compile(r'\D+').split(string)]
  File "/usr/lib/python3.5/site-packages/qubesmanager/utils.py", line 124, in <listcomp>
    self.contents = [int(x) for x in re.compile(r'\D+').split(string)]
ValueError: invalid literal for int() with base 10: ''
```

**Solutions you've tried**
Ran dom0-qubes-update, made sure using latest version of qubes-manager:
qubes-manager-4.0.36-1.fc25.noarch

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
n/a

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
there were recent updates in qubes-manager for similar issues which are apparently fixed though #4988 #5057

**Comment by marmarta** [comment] 2019-07-30 22:39
could you perhaps give us the contents of your `/var/lib/qubes/vm-kernels` (in dom0)? It seems like you have a very peculiar kernel.

**Comment by marmarta** [comment] 2019-07-31 00:17
nevermind, it has been found - a fix is incoming :) it was caused by a kernel name that ended in a letter.

**Closed** 2019-08-01 23:11 UTC
Labels: C: manager/widget, P: default, T: bug

**Comment by ctramnitz** [comment] 2019-08-25 15:41
Yes, there was a custom kernel that ended in a letter, thanks for the quick fix.
However, updating to current-testing also installed a new kernel which rendered my system unbootable (which is not trivial to recover using EFI boot).
But I can confirm, that the fix pushed here solves the initial problem.
