### ISSUE TITLE
huge memory consumption of `icon-sender` when running `electron`-based editors

### ISSUE THREAD

**Issue by bamalip** [QubesOS/qubes-issues#4725] opened 2019-01-16 11:59 UTC
### Affected component(s): 
`/usr/lib/qubes/icon-sender`

---
### Steps to reproduce the behavior:
* install any of `Atom Editor` or `Visual Studio Code` in TemplateVM
* run the editor in AppVM
* see the memory consumption
### Expected behavior: 
not such huge amount of memory needed
### Actual behavior: 
`ps aux | grep icon-sender` shows above `600MB`

---
### Related issues:
possibly is connected with #3653

**Comment by lunarthegrey** [comment] 2019-04-20 00:05
I can confirm this is an issue. It uses a huge amount of memory in a couple of my VMs (almost 700MB each). I haven't confirmed if this is due to using an Electron based application though. How would we go about testing this and getting the issue fixed?

**Comment by lunarthegrey** [comment] 2019-04-20 00:08
Looks like @marmarek wrote this based on the copyright in the file. Unfortunately I'm unfamiliar with Python development and debugging it. Any ideas?

**Comment by marmarek** [comment] 2019-04-20 13:07
The code live here: https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/window-icon-updater/icon-sender
`gc` python module is useful for debugging memory leaks, [here is an article about it](http://tech.labs.oliverwyman.com/blog/2008/11/14/tracing-python-memory-leaks/).

Looking at the code of icon-sender, I don't see anything obvious, so a deeper looks is needed.

**Comment by lunarthegrey** [comment] 2019-04-21 15:44
Thanks @marmarek I'll see if I can run `pdb` and import `gc`. I did an `strace` on the PID of `icon-sender` in one of my VMs and I can see it's constantly doing this and scrolling by very fast with some slight variation.

```
poll([{fd=4, events=POLLIN}], 1, -1)    = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\34\0\324\4\6\0 \2>\1\0\0\246=B\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=4, events=POLLIN}], 1, -1)    = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\34\0\324\4\6\0 \2>\1\0\0\317=B\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=4, events=POLLIN}], 1, -1)    = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\34\0\324\4\6\0 \2>\1\0\0\10>B\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
```

**Comment by lunarthegrey** [comment] 2019-04-21 16:01
I killed the running PID. I'm thinking that output I posted above is the leak or bug. I don't see anything like that on the new process now. I've got the debugger on the new one as well as an `strace`. I'll wait for the memory increase/leak to happen then provide some more output.

**Comment by lunarthegrey** [comment] 2019-04-22 17:43
So.. I might have it all wrong. It looks like it's supposed to be executed with `/usr/bin/qrexec-client-vm dom0 qubes.WindowIconUpdater /usr/lib/qubes/icon-sender`, not directly. When I do `pdb /usr/lib/qubes/icon-sender` or add `import pdb; pdb.set_trace()` directly in the file and run it I don't see that it's even being used for anything.

I'm not sure how to debug it if it needs to be executed from `qrexec-client-vm`. When I add `import pdb; pdb.set_trace()` in the file and try to run it I get this:

```
user@main:~$ /usr/bin/qrexec-client-vm dom0 qubes.WindowIconUpdater /usr/lib/qubes/icon-sender
Traceback (most recent call last):
  File "/usr/lib/qubes/icon-sender", line 30, in <module>
    import xcffib
  File "/usr/lib/qubes/icon-sender", line 30, in <module>
    import xcffib
  File "/usr/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.5/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Thoughts @marmarek?

**Comment by lunarthegrey** [comment] 2019-04-22 18:05
In my testing I can confirm when opening up an Electron based application the memory usage of `icon-sender` goes way up and stays up, even when the application gets closed.

**Comment by marmarek** [comment] 2019-04-22 20:13
Can you point at such application? I do have some (Signal for example) and doesn't see such problem.

**Comment by marmarek** [comment] 2019-04-22 20:14
As for tracing, you can start it directly without qrexec-client-vm, but it will produce a lot of data on stdout. It should be ok to redirect it to /dev/null.

**Comment by lunarthegrey** [comment] 2019-04-23 01:27
@marmarek I specifically tested with https://snapcraft.io/atom using `snapd`. Strangely, I started it directly but there wasn't much output. Might have been doing something wrong. My inexperience with `pdb` led to me not running it properly. I found out you have to press `c` to let it run, whereas I was just pressing `r`. Although, when I press `c` it runs but I cannot do anything in `pdb` while it's running.

```
(Pdb) c
^C
Program interrupted. (Use 'cont' to resume).
> /usr/lib/python3/dist-packages/xcffib/__init__.py(590)wait_for_event()
-> e = ffi.gc(e, lib.free)
(Pdb)
```

When it runs and I have `Atom` open the memory usage goes up very high right away.

**Comment by lunarthegrey** [comment] 2019-04-23 01:47
Excuse my ignorance... I was doing it all wrong.

```
(Pdb) import gc
(Pdb) gc.collect()
12
(Pdb) gc.collect()
0
(Pdb) import objgraph
(Pdb) objgraph.show_most_common_types(limit=20)
function                   2810
tuple                      1543
dict                       1470
weakref                    1049
wrapper_descriptor         1035
builtin_function_or_method 743
method_descriptor          727
type                       561
getset_descriptor          543
VISUALTYPE                 480
list                       349
set                        318
member_descriptor          298
WeakSet                    142
classmethod                128
module                     122
ModuleSpec                 120
property                   112
MovedAttribute             83
SourceFileLoader           80
```

**Comment by lunarthegrey** [comment] 2019-04-28 17:49
Realized something recently. The icon for Electron doesn't actually show up when I run the application. It shows in the menu but not my task bar. Perhaps it has trouble getting the icon and runs into some kind of bug?

**Comment by marmarek** [comment] 2019-05-02 14:09
Looks like Atom presents quite big icons - two of them, 1024x1024 each. This takes 8MB of input data.
Icon sender has hardcoded max size 128x128, so it explains why it doesn't show. But it does not explain why icon-sender takes so much RAM. Even if all those icons would be leaked, it's just 8MB, not 600MB.

**Comment by lunarthegrey** [comment] 2019-05-02 14:38
Nice find @marmarek, thanks. It is odd, here is how much memory icon-sender is using now in one of my VMs.

```
user@vm:~$ sudo pmap 1763 | grep total
 total           691760K
user@vm:~$ ps aux | grep 1763
user      1763  0.0 15.6 691760 628716 ?       S    May01   0:15 /usr/bin/python3 /usr/lib/qubes/icon-sender
```

The memory usage instantly shoots up when opening Atom. When it's closed it stays as well, maybe it's stuck in some kind of loop?

**Comment by marmarek** [comment] 2019-05-02 16:23
I've added a couple of prints and sleeps there and it jumps the moment the Atom's icon is retrieved. It is loaded in two parts and first load cause memory usage go up to ~180M, the second one - up to 600M.
This may be some interaction with xcffib library (used to retrieve window properties - icons in this case), maybe some of those objects require explicit release. Digging into this now.

**Comment by lunarthegrey** [comment] 2019-05-02 16:43
Thanks @marmarek you're much more suited in debugging this than I (have barely any experience with Python). Appreciate you looking into this, you'll end up saving me some RAM :)

**Comment by marmarek** [comment] 2019-05-03 02:48
found it!
Parsing a reply is responsible in [GetPropertyCookie.reply()](https://github.com/QubesOS/qubes-gui-agent-linux/blob/c8648596f08305086e5a45c2e4e5be90e01c030d/window-icon-updater/icon-sender#L89) call. Interally `xcffib` library uses [struct.unpack_from](https://github.com/QubesOS/qubes-gui-agent-linux/blob/c8648596f08305086e5a45c2e4e5be90e01c030d/window-icon-updater/icon-sender#L89), with quite long format (string of 4MB in this case). And apparently `struct.unpack_from` [isn't meant to be used on such large formats](https://github.com/QubesOS/qubes-gui-agent-linux/blob/c8648596f08305086e5a45c2e4e5be90e01c030d/window-icon-updater/icon-sender#L89). `struct.Struct` build from such format takes about 128MB, and _is cached internally forever_.
Since `struct` module is written in C, no Python tool to debug memory leaks helped here :(

Possible solutions:
1. Fix xcffib library to use more efficient formats (proper format repetition feature, instead of building very long format). `Struct` instance built this way takes only 120B, so even it will be cached, it isn't a problem.
2. Do not rely on xcffib to parse the response and do that in `icon-sender`, using `struct.Struct` (not cached) instead of `struct.unpack_from` (cached).

**Comment by marmarek** [comment] 2019-05-03 03:11
Upstream report: https://github.com/tych0/xcffib/issues/93

**Comment by lunarthegrey** [comment] 2019-05-03 13:29
Yay! I see you got your pull requests merged on upstream. Now would patching this in Qubes just be a matter of waiting for you to push the changes to the Qubes `python3-xcffib` RPM?

**Comment by marmarek** [comment] 2019-05-03 14:21
Something like this. But note that wherever possible we use distribution native python3-xcffib package - if exists. Which means, on Fedora the update may be available later.

**Comment by lunarthegrey** [comment] 2019-06-10 10:37
I can confirm the new version of python3-xcffib fixes the issue. I installed it from the Qubes stretch-testing repo and rebooted my VMs. Now when I open Atom I don't get 700MB of used memory from icon-sender! I believe this can be closed out, hopefully it'll hit stable soon so others who don't notice it fix the issue when they update.

Reference: https://github.com/QubesOS/updates-status/issues/1115

**Closed** 2019-06-11 00:18 UTC
Labels: C: other, P: default, T: bug
