### ISSUE TITLE
Nautilus often doesn't start the first (or second, or third) time

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2449] opened 2016-11-22 05:15 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-24 (possibly others)

---

### Expected behavior:

Nautilus starts the first time the shortcut is clicked in the app menu.

### Actual behavior:

Often (~70% of the time) it only starts on the second, third, or fourth try.

**Comment by andrewdavidwong** [comment] 2016-11-25 16:14
This also affects opening certain attachments in Thunderbird with the `thunderbird-qubes` extension. For example, if you double click on an attached .zip file, a new DispVM will start (and presumably the .zip file will be transferred to it), but no window from the new DispVM will open.

Usually it's Archive Manager, so maybe there's some dependency on Nautilus, or maybe this affects more than Nautilus.

**Comment by andrewdavidwong** [comment] 2016-12-08 09:59
@marmarek: Any idea what might be causing this? Any logs I should look at?

**Comment by 3n7r0p1** [comment] 2016-12-08 18:29
What does it say when you try to launch Nautilus from the terminal? Only Nautilus or other Gnome apps as well? I had a dbus-related issue in Whonix-12 that produced same symptoms, but for gnomish-apps across the board.

**Comment by andrewdavidwong** [comment] 2016-12-08 23:34
> What does it say when you try to launch Nautilus from the terminal?

Good idea:
```
$ nautilus

(nautilus:17938): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.

(nautilus:17938): Gtk-WARNING **: Theme parsing error: <broken file>:1:0: Failed to import: The resource at '/org/gnome/libgd/tagged-entry/default.css' does not exist

```

> Only Nautilus or other Gnome apps as well?

Seems to be only Nautilus and things that directly use Nautilus (e.g., Archive Manager).

**Comment by marmarek** [comment] 2016-12-09 00:12
Does it start after issuing those warnings?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 3n7r0p1** [comment] 2016-12-09 00:19
Sounded familiar. Related to these?

https://groups.google.com/d/msg/qubes-users/veefnCdXHhs/2A-5IqEQZFYJ
https://groups.google.com/d/msg/qubes-users/ki-m5el9yUQ/X99qrODEX4cJ
https://groups.google.com/d/msg/qubes-users/Vpw8VOPvUEU/_0a4ywPpBwAJ

I don't remember the solution though... dbus activatable = false? Or was that a bandaid?

**Comment by andrewdavidwong** [comment] 2016-12-09 00:37
> Does it start after issuing those warnings?

Yes, when started from the command-line, it starts after those warnings. (When started from the Application menu, though, it usually doesn't.)

**Comment by andrewdavidwong** [comment] 2017-03-01 09:50
Some anecdotal evidence: I've noticed that clicking the menu link twice in quick succession usually works, whereas waiting a few seconds between clicks does not.

Why this is *extremely* annoying and kills productivity:

Since I don't know whether a single click will work (because of this bug), my choice -- every time I need to open Nautilus in a Fedora VM (which is a lot) -- is between taking my chances (in which case I may ultimately have to navigate to and click the menu link 2+ times in the event that the first time doesn't work) or navigating to and clicking the link twice in quick succession (i.e., before I have a chance to find out whether the first click worked, in which case I have to navigate to the menu link twice). Either way means a *lot* of extra navigation and clicking through a *very* long menu.

I already have five groups of Xfce launchers, including 18 distinct Nautilus entries. This remains extremely problematic even *after* that degree of mitigation. I sometimes give up, open a dom0 terminal, and do `qvm-run <vm-name> nautilus` from the command-line, which is cumbersome but at least reliable.

**Comment by evadogstar** [comment] 2017-03-30 22:09
Maybe additional shortcut for nautilus like for terminal will be useful? 
https://github.com/QubesOS/qubes-issues/issues/2706 
I am also notices that `qvm-run VM nautilus` always start nautilus. It's application menu problem. Maybe lets add two utils to run terminal and to run nautilus by shortcuts?

**Comment by jpouellet** [comment] 2017-03-30 23:52
> It's application menu problem.

I'm inclined to believe the opposite.

>> Does it start after issuing those warnings?
> 
> Yes, when started from the command-line, it starts after those warnings. (When started from the Application menu, though, it usually doesn't.)

I have observed it still refusing to start after issuing the same warnings, also when started from the command line (both via qubes-desktop-run, and directly nautilus (with and without --gapplication-service)). Qubes seems not to be at fault. Looks more like a bug from something in the gnome/gtk/dbus/etc. world to me.

**Comment by jpouellet** [comment] 2017-03-30 23:56
Also, I've had cases where it happens repeatably 100% of the time (at least for the 50+ times in a row while I was investigating). Killing all nautilus processes would make it work (file manager window opens, no warnings) the first time afterwards, but would immediately go back to never working and always warning. Restarting the VM caused it to resume working each time.

**Comment by jpouellet** [comment] 2017-05-06 05:15
@evadogstar wrote:
> Maybe additional shortcut for nautilus like for terminal will be useful? #2706

Here: [qvm-filemanager](https://gist.github.com/jpouellet/bbf51888aee69a266f200f37963b8b87)

It is curious that the above linked script (essentially `qvm-run $vm 'exec nautilus --new-window --no-desktop </dev/null >/dev/null'`) has yet to fail to open Nautilus even when it reproducably fails consistently via the Qubes menu.

The thing which makes it work seems to be the inclusion of `--new-window` flag, also confirmed by trying to start nautilus from a terminal in the affected VM. I still haven't dug into source to determine root cause. In the mean time, `--new-window` appears to be a reliable workaround.

**Comment by jpouellet** [comment] 2017-05-06 05:24
Err sorry, the above is incorrect.

Desktop entry already passes this:
```
% grep Exec= /usr/share/applications/org.gnome.Nautilus.desktop 
Exec=nautilus --new-window %U
Exec=nautilus --new-window
```

Perhaps `--no-desktop` flag is differentiating factor? Idk. Needs more investigation.

**Comment by marmarek** [comment] 2017-05-06 09:21
`/usr/share/applications/org.gnome.Nautilus.desktop` have
`DBusActivatable=true` which affect how the application is started.
Especially, `Exec=` key is ignored in a such case:
https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by evadogstar** [comment] 2017-05-06 22:35
@jpouellet  Nice :) What shortcut you suggest for `qvm-filemanager`? Your `Ctrl+Enter` for `qvm-terminal` iis fine at 99% situations. 1% - the same shortcut used at pidgin for new line/send message and on some sites and other messengers.

**Comment by jpouellet** [comment] 2017-05-07 18:59
@evadogstar Currently Qubes+N, where "Qubes" is my modifier key reserved for exclusive use by all keyboard shortcuts

**Comment by jpouellet** [comment] 2017-05-07 19:01
FWIW I also use Qubes+Enter for new terminals. Ctrl+Enter conflicts with things like posting github comments ;)

In practice my "Qubes" modifier is the key to the left of my space bar, but people should feel free to use whatever they prefer. I intend to send patches for this unified Qubes modifier functionality when I get some more free time.

**Comment by evadogstar** [comment] 2017-05-09 12:21
@jpouellet 
`Qubes(win)+Enter` for new terminal - very good :) 
`Qubes+N` - for new nautilus? Why `N`? :)

**Comment by andrewdavidwong** [comment] 2018-06-17 19:01
This problem has recently gotten worse for some reason. Now, clicking a Nautilus shortcut N times will never open it. I have to launch it from the command line (I do it from dom0), at which point N Nautilus windows will open in the VM.

**Comment by marmarek** [comment] 2018-06-17 19:14
fedora-28 template? Qubes 3.2 or 4.0? Does opening other application (xterm?) also make N Nautilus windows open?

**Comment by andrewdavidwong** [comment] 2018-06-18 01:29
Fedora 28 on Qubes 3.2. 

> Does opening other application (xterm?) also make N Nautilus windows open?

No, just tried it. Launching xterm in the VM from dom0 resulted in an xterm window but no Nautilus windows. I then launched Nautilus in the VM from dom0 and only then got N Nautilus windows.

**Comment by tasket** [comment] 2018-07-02 17:09
To a lesser degree I'm experiencing this on R4.0, debian-9.

I've started to look at using the KDE apps instead, since they do not exhibit the same startup problems and have better feature sets anyway. On R4.0 however, the Dolphin menu integration exists only in Whonix.

**Comment by tonsimple** [comment] 2018-09-30 09:44
This _suddenly_ started affecting several of my VMs (2 debian based, 1 fedora based) on my R 3.2 "main workhorse" machine.

it appears to be worked around by starting Nautilus from terminal once... then it can be started to one's heart content from the main "start menu".

An annoying mystery.

**Comment by marmarek** [comment] 2019-03-20 03:43
I've looked into this more, and I think it's because how Gio library (the thing we we for parse desktop files and launch applications) handle dbus activation. It looks like it doesn't wait for the application launch call to complete ([g_dbus_connection_call call](https://gitlab.gnome.org/GNOME/glib/blob/2.58.2/gio/gdesktopappinfo.c#L2879-2881) is asynchronous, and its last arguments are completion callbacks - not provided here). There is also no notification when the call is complete. If the application start takes more time, it may not receive actual "Activate" call before `qubes-desktop-run` process terminates. Looks like Nautilus takes specifically long time, because it talks to (possibly starting it too) gnome virtual file system daemon (gvfsd). 
I've checked other high-level methods in Gio library but didn't found anything that would help here.
There are not much other libraries providing high level interface for both parsing desktop files and launching applications. For now (stable update), I'll replace call to high level gio API, with low level gio calls (according to [D-Bus Activation spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s08.html)), adding missing wait for the call to complete.
I've tested it briefly and without this change I could hit this bug in about 10% trials, but with this change, it works reliably for me.
For the next release, I'll replace it completely with simpler libraries - if the main reason for using (quite large) Gio library is void, it could be replaced with much smaller and simpler things (xdg python module for desktop files parsing, then pydbus for actual dbus calls). It will be much nicer than low level Gio calls, and possibly will be also faster.

While at it, I've found a heuristic that could be used for dbus-activable applications in DispVM (https://github.com/QubesOS/qubes-issues/issues/2449#issuecomment-262989349), to prevent shutting down such DispVM prematurely. The `qubes.StartApp` service (`qubes-desktop-run`) can wait for the activated name to disappear from D-Bus. This is still heuristic, as the specification does not mandate the name to remain visible after application is started, but in practice most D-Bus aware applications do. This works at least for Nautilus (with a little delay - nautilus process terminates and unregisters its name few seconds after closing its last window). Unfortunately, it does _not_ work for gnome-terminal - despite its desktop file name `org.gnome.Terminal.desktop`, it does not support D-Bus activation (there is no `DbusActivatable=true` in its desktop file, and also calling `org.freedesktop.Application.Activate` method does nothing, even though the method does exist).

**Closed** 2019-04-13 03:23 UTC
Labels: C: Fedora, P: major, T: bug, ux
