### ISSUE TITLE
qubes-sync-time.service fails to start on Arch Linux because of Python2/3 issue

### ISSUE THREAD

**Issue by fishilico** [QubesOS/qubes-issues#3872] opened 2018-05-01 19:59 UTC
### Qubes OS version:

R4.0, with Arch Linux template built by following instructions from https://www.qubes-os.org/doc/building-archlinux-template/

### Affected component(s): 

qubes-sync-time.service (qvm-sync-clock systemd service)

---

### Steps to reproduce the behavior:

* Create a Arch Linux TemplateVM and an AppVM on Qubes OS R4.0.
* Enumerate the services which failed to start (`systemctl | grep failed`). There is:

      * qubes-sync-time.service   loaded failed failed    Update time from ClockVM

* Try to start the service, it fails again.
* Start the program used by the service from a shell:
```
$ sudo /usr/bin/qvm-sync-clock
Traceback (most recent call last):
  File "/usr/lib/qubes/qubes-sync-clock", line 38, in <module>
    main()
  File "/usr/lib/qubes/qubes-sync-clock", line 35, in main
    stdout=subprocess.DEVNULL)
AttributeError: 'module' object has no attribute 'DEVNULL'
```

`subprocess.DEVNULL` only exists in Python 3, but `/usr/lib/qubes/qubes-sync-clock` starts with:
```py
#!/usr/bin/python2
```

The source code used python3 (https://github.com/QubesOS/qubes-core-agent-linux/blob/v4.0.26/qubes-rpc/qubes-sync-clock#L1) but the Arch Linux package replaces every Python shebang with Python 2 (https://github.com/QubesOS/qubes-core-agent-linux/blob/v4.0.26/archlinux/PKGBUILD#L48-L52):
```sh
    # Force running all scripts with python2
    sed 's:^#!/usr/bin/python.*:#!/usr/bin/python2:' -i misc/*
    sed 's:^#!/usr/bin/env python.*:#!/usr/bin/env python2:' -i misc/*
    sed 's:^#!/usr/bin/python.*:#!/usr/bin/python2:' -i qubes-rpc/*
    sed 's:^#!/usr/bin/env python.*:#!/usr/bin/env python2:' -i qubes-rpc/*
```

As `/usr/lib/qubes/qubes-sync-clock` is not compatible with Python 2, `/usr/bin/qvm-sync-clock` fails, and so does the service `qubes-sync-time.service`.

### Expected behavior:

qubes-sync-time.service works fine.

### Actual behavior:

qubes-sync-time.service fails to start, because it tries to run Python 3 code with Python 2.

### General notes:

There seems to be an ongoing effort to make Arch Linux packages use Python 3 Qubes libraries (e.g. https://github.com/QubesOS/qubes-core-qubesdb/commit/5efa37d1ffc24607630bde3679dcea1adc429632 ). This issue may be solved by ensuring every Python library used to interact with Qubes OS from an Arch Linux template is installed in its Python 3 version.

---

### Related issues:

I opened this issue because I have not found any issue related to migrating to Python 3.
It might be related to the more general "Archlinux template for QubesOS 4.0" issue, https://github.com/QubesOS/qubes-issues/issues/3185

**Comment by bxatnarf** [comment] 2019-01-22 14:57
This patch is what fixed the problem for me: https://github.com/QubesOS/qubes-core-admin/pull/250

**Comment by lubellier** [comment] 2020-09-27 21:55
I tested this issue on a fresh archlinux install, and the problem is solved. 

Details:
```bash
[user@test-qube-archlinux ~]$ systemctl status qubes-sync-time.service
● qubes-sync-time.service - Update time from ClockVM
     Loaded: loaded (/usr/lib/systemd/system/qubes-sync-time.service; static)
     Active: inactive (dead) since Sun 2020-09-27 23:43:15 CEST; 8min ago
TriggeredBy: ● qubes-sync-time.timer
    Process: 2009 ExecStart=/usr/bin/qvm-sync-clock (code=exited, status=0/SUCC>
   Main PID: 2009 (code=exited, status=0/SUCCESS)
```
```bash
[user@test-qube-archlinux ~]$ head -n1 /usr/lib/qubes/qubes-sync-clock 
#!/usr/bin/python3
```
```bash
[user@test-qube-archlinux ~]$ sudo /usr/bin/qvm-sync-clock
[user@test-qube-archlinux ~]$ echo $?
0
```

@andrewdavidwong  I suggest closing this issue

**Closed** 2020-09-27 22:12 UTC
Labels: C: Arch Linux, T: bug
