### ISSUE TITLE
Compile policy into an optimized state machine

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9361] opened 2024-07-18 21:09 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

qrexec policy evaluation uses a slow linear search in Python.

### The solution you'd like

Compile the policy into an optimized state machine that can evaluate policy in O(log N) time or better, where N is the number of rules in the policy.  Then use this optimized state machine to respond to queries.

Qrexec policy evaluation is a simpler version of ML pattern matching, for which highly efficient algorithms are known.

### The value to a user, and who that user might be

All users will benefit from faster qrexec calls.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment] 2024-07-18 21:17
Duplicate of #6266

**Closed** 2024-07-18 21:17 UTC
Labels: R: duplicate, T: enhancement, C: core, P: default
