### ISSUE TITLE
Graphical Installer: Wrong keyboard layout for Grub / LUKS

### ISSUE THREAD

**Issue by diffusae** [QubesOS/qubes-issues#3748] opened 2018-03-26 16:54 UTC
### Qubes OS version: 

R4.0rc5

### Affected component(s):  

Graphical Installer

---

### Steps to reproduce the behavior: 

If you use the graphical installer and change the keyboard layout (and not the system language).
The keyboard layout for LUKS passphrase will be set correctly, but nevertheless Grub uses the default keyboard layout after booting. 

### Expected behavior:

Should set the correct keyboard layout for Grub.

### Actual behavior: 

You could change the layout, but for the Grub installation it remains to US.

### General notes: 

It should be possible to change this afterwards.

---

### Related issues:

?

**Comment by andrewdavidwong** [comment] 2018-03-27 01:31
Duplicate of #3234

**Comment by andrewdavidwong** [comment] 2018-03-27 01:31
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-27 01:31 UTC
