### ISSUE TITLE
Tray app popup is too small, requiring scrolling to see all running Qubes

### ISSUE THREAD

**Issue by keepiru** [QubesOS/qubes-issues#3864] opened 2018-04-28 04:30 UTC
### Qubes OS version:
Qubes release 4.0 (R4.0)

### Affected component(s): 
qui.tray.domains

### Steps to reproduce the behavior:
Right click on XFCE panel
Panel
Panel preferences
Uncheck "lock panel"
Drag panel to the bottom of the screen
Click on the Qubes tray applet

### Expected behavior:
All of my running Qubes are visible.

### Actual behavior:
Seven qubes are visible.  The rest can be viewed by scrolling up and down.

**Comment by andrewdavidwong** [comment] 2018-04-28 18:33
Duplicate of #2970

**Comment by andrewdavidwong** [comment] 2018-04-28 18:34
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-04-28 18:34 UTC
