### ISSUE TITLE
qubes-dom0-update did not exclude installed template in fedora-29 sys-firewall

### ISSUE THREAD

**Issue by wynn1212** [QubesOS/qubes-issues#4584] opened 2018-12-07 13:06 UTC
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

sys-firewall, qubes-dom0-update

---

### Steps to reproduce the behavior:

sys-firewall is based on fedora-29
running `sudo qubes-dom0-update` in dom0 terminal.
When the templates is newer than the local one.

### Expected behavior:

Templates should not be upgrade.

### Actual behavior:

Templates will be upgrade when doing this procedure.

### General notes:

I did't try if this problem occurred in fedora-28 based sys-firewall (or not), because I already upgraded all App-VM to fedora-29 Template and deleted Fedora 28 Template.

---

### Related issues:

might related to #4477

**Comment by unman** [comment] 2018-12-07 14:33
Do you mean that `sudo qubes-dom0-update`updated the installed fedora-29 template package, and **only** that template package? 
There's code to stop it updating templates, unless the user explicitly overrides, and even then there's a warning.
I've just tried this and **no** template packages were updated, as expected.

What was the command line you used?

**Comment by marmarek** [comment] 2018-12-07 14:37
Fix already in master: https://github.com/QubesOS/qubes-core-admin-linux/commit/d7c23e1b7fdaf307138851ba24cd242ee81c4001, will be in qubes-core-dom0-linux 4.0.17.

>  I've just tried this and **no** template packages were updated, as expected.

This happens only on fedora-29 based updatevm (as @wynn1212 noted) and is caused by changed behavior of dnf 4.x (compared to dnf 2.x in fedora-28).

**Closed by marmarek** 2018-12-07 14:37 UTC
