### ISSUE TITLE
[Qubes VM Manager] Restarting a running AppVM throws AssertionError

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2505] opened 2016-12-08 20:34 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
* debian-8 (updated) ; and
* fedora-23 (updated)

AssertionError: This is most likely a bug in the Qubes Manager

```
line: assert not vm.is_running()
func: start_vm
line no: 1158
main.py
---
line: self.caller.start_vm(vm)
func: check_if_vm_has_shutdown
line: 288
main.py
```

Reproducible.

#### Remark:
Stop VM / Start VM sequence appears to work.

**Comment by andrewdavidwong** [comment] 2016-12-08 21:53
Duplicate of #2438.

**Closed by andrewdavidwong** 2016-12-08 21:53 UTC

**Comment by Wikinaut** [comment] 2016-12-08 21:55
Correct. sorry!
