### ISSUE TITLE
Add drag and drop func between AppVMs

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8430] opened 2023-08-17 20:25 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

In my fantasy, it looks like this: 2 explorer windows of different AppVMs are open and I have the opportunity to move a file from one open directory in AppVM to another directory open directory of another AppVM

### The solution you'd like
At this moment I don`t have any solution.

### The value to a user, and who that user might be
This function will be used by all users who will move files using the file manager

#### P.S
This is basically my first issue, so please treat the description with indulgence.
Ready to discuss your wish in more detail

**Comment by bzillacodes** [comment] 2023-08-18 02:12
This drastically increases dangers of sending files between appVM's.

The way I see it, the appVM's would theoretically need to know the active display/window positioning of the other qubes, or the file transfer proxied through the guiVM directly, both cases being unsafe.

**Comment by Middenvaus** [comment] 2023-08-18 09:57
this issue is on the verge of security and user experience. this function can be made optional and warn users about the consequences of using it

**Comment by andrewdavidwong** [comment] 2023-08-18 12:33
Duplicate of #6842

**Comment by andrewdavidwong** [comment] 2023-08-18 12:33
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-08-18 12:33 UTC
Labels: T: enhancement, P: default

**Comment by Middenvaus** [comment] 2023-08-18 16:29
yes, its duplicate
