### ISSUE TITLE
Fedora 28 update conflicts with Qubes packages

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#4053] opened 2018-07-04 18:53 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

fedora-28 template

---

### Steps to reproduce the behavior:

dnf update

### Expected behavior:

Package updates are installed, leaving Qubes packages intact.

### Actual behavior:

```
[user@fedora-28 ~]$ sudo dnf update --best
Last metadata expiration check: 0:07:53 ago on Wed 04 Jul 2018 01:52:23 PM EDT.
Error: 
 Problem: package salt-2018.3.2-1.fc28.noarch requires python-tornado < 5.0, but none of the providers can be installed
  - cannot install both python2-tornado-5.0.2-2.fc28.x86_64 and python2-tornado-4.5.2-2.fc28.x86_64
  - cannot install both python2-tornado-4.5.2-2.fc28.x86_64 and python2-tornado-5.0.2-2.fc28.x86_64
  - cannot install the best update candidate for package salt-2018.3.0-1.fc28.noarch
  - cannot install the best update candidate for package python2-tornado-4.5.2-2.fc28.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
```

### General notes:

This was triggered by a massive (and apparently careless) Fedora 28 update. Not sure why they would upgrade packages by a whole integer when their OS upgrade cycles are so short.

---

**Comment by andrewdavidwong** [comment] 2018-07-04 20:13
Duplicate of #3991

**Comment by andrewdavidwong** [comment] 2018-07-04 20:13
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-07-04 20:13 UTC
