### ISSUE TITLE
On some laptop models, the mute button mutes but does not unmute

### ISSUE THREAD

**Issue by ryannoblett** [QubesOS/qubes-issues#2550] opened 2017-01-02 02:42 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Issue is with dom0

---

### Expected behavior:
Pressing Mute mutes audio, pressing again unmutes audio
### Actual behavior:
Pressing Mute mutes audio, pressing again does nothing
### Steps to reproduce the behavior:
The issue can be seen with PulseAudio Volume Control open, on the Output Devices tab.
Press Mute, watch and hear output become muted, press mute again, see that it does not unmute the Speakers device and they remain silent.
### General notes:
I'm using a Lenovo Thinkpad X220. The microphone mute button does nothing at all, if that matters.

---

#### Related issues:
Split off from comments in:
https://github.com/QubesOS/qubes-issues/issues/2117

**Comment by unman** [comment] 2017-01-05 20:11
On a number of laptops that I have the mute button works as expected. (I don't have a Thinkpad X2220.) Other Lenovo models have been reported on the lists without this issue arising. 
Perhaps edit the title to make it more specific? 
What about asking for other experiences on the mailing list? 
(I'm assuming that it worked fine before Qubes.- have you tried testing with a live distro?)

**Comment by marmarek** [comment] 2017-01-05 23:58
Is it fresh R3.2 install, or upgraded from R3.1? 
Xfce have at least two volume widgets supported - in R3.2 we switched to
xfce4-pulseaudio-plugin exactly to fix this issue. But on upgraded
system the old one may still be in use.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by ryannoblett** [comment] 2017-01-07 14:57
@marmarek It is upgraded from R3.1. How can I tell which one I'm running and change it? My panel widget just says "Audio Mixer Plugin".

**Comment by marmarek** [comment] 2017-01-07 23:16
It's the old one. You need to install `xfce4-pulseaudio-plugin` package (using `qubes-dom0-update` tool), then remove this audio plugin and add the new one ("PulseAudio Panel Plugin").

**Comment by ryannoblett** [comment] 2017-01-21 21:35
Ok, I successfully installed `xfce4-pulseaudio-plugin` and changed the applet in the panel, but the behavior is still the same. I did reboot. Do I need to remove any packages to get rid of the old one?

**Comment by marmarek** [comment] 2017-01-21 21:38
Removing the old one from the panel should be enough.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by jpouellet** [comment] 2017-02-20 23:41
Duplicate of:
- https://github.com/QubesOS/qubes-issues/issues/2117
- https://github.com/QubesOS/qubes-issues/issues/2291
- https://github.com/QubesOS/qubes-issues/issues/2321
- https://groups.google.com/forum/#!msg/qubes-users/53TYf5GYkqY/ZU8i5v6JAwAJ

I ran into the same problem when I first started using Qubes, and tried to start this discussion as a result: https://groups.google.com/d/topic/qubes-users/dCctVsf15dE/discussion

In hindsight such a question probably belongs on qubes-devel.

**Comment by andrewdavidwong** [comment] 2017-02-21 22:10
@jpouellet Can you explain why you think this is a duplicate of all of those issues? That just seems patently false to me, but I could be missing something.

* This issue was intentionally branched off from #2117 precisely because it's distinct from #2117.
* #2291 looks like it could indeed be a duplicate, though.
* #2321 just looks like a different issue, which has been resolved, whereas this one (AFAIK) persists.

**Comment by jpouellet** [comment] 2017-02-22 13:58
@ryannoblett try removing xfce4-mixer and xfce4-volumed and see if it resolves your issue. This sounds exactly like the same thing I ran into a few months ago.

@andrewdavidwong It appears I did confuse issue originally reported in #2117 with [@0keh's comment](https://github.com/QubesOS/qubes-issues/issues/2117#issuecomment-250592447) describing a different behavior (which is the same as these issues) and claiming it was the same as the OP. This one appears indeed not a duplicate.

However, the issue here and in #2291 is the same xfce4-mixer + volumed not un-muting everywhere it needs to, for which the root cause and fix was identified in #2321, but in such a way that people simply doing qubes-dom0-update do not get the fix for. I had the same issue, did a qubes-dom0-update (which did not resolve it) and ended up debugging the issue myself only to discover these issues afterwards.

The resolution was to [replace xfce4-mixer & xfce4-volumed with xfce4-pulseaudio-plugin in the list of things installed in the installer](https://github.com/marmarek/qubes-installer-qubes-os/commit/4d1a47140278afeeda80fe6bfa8fe57fd7d754d5) and [put xfce4-pulseaudio-plugin in the default xfce4-panel](https://github.com/marmarek/qubes-desktop-linux-xfce4/commit/612e955ae98123e377424a827c65efe503248d30). However, patching the installer only affects new installs with a post-fix installer, as I noted in [a post to qubes-users](https://groups.google.com/d/topic/qubes-users/dCctVsf15dE/discussion), so this same already-fixed issue keeps getting brought back up.

I think the bigger issue is that the fix identified in #2321 does not propagate via qubes-dom0-update, and there is no good way that I am aware of to fix certain issues (those with installer fixes) without reinstalling or manually tracking the changes and modifying your local system, which I don't think normal users should be expected to do.

**Comment by andrewdavidwong** [comment] 2017-02-23 04:19
@jpouellet: In that case, I'm inclined to just close this as a duplicate of #2291, since, as you point out, there's not much we can do, unless you have another suggestion.

**Comment by jpouellet** [comment] 2017-02-23 05:50
I agree with closing as dupe. I think a discussion about better ways to update dom0 should eventually be had, because there *are* meaningful differences between an upgraded system and one installed from a more recent installer. While not a problem in itself, it leads to issues like this.

In particular, I think this is something to keep in mind when reevaluating the role of dom0 post GuiVM.

**Closed** 2017-02-24 05:05 UTC
Labels: bug, C: other, duplicate
