### ISSUE TITLE
Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#6878] opened 2021-09-07 17:15 UTC
### Qubes OS release

Qubes 4.0

### Brief summary

Journal showing error in qubes-debian (bullseye) not in normal/plain debian-xfce (bullseye).

### Steps to reproduce

- Open debian or whonix terminal (bullseye based)
- sudo journal -f (or from dom0 open xfce4-terminal in root mode)
- Error appear

### Expected behavior

Shouldnt show this error

### Actual behavior

```

root@host:~# journalctl -f
-- Journal begins at Mon 2021-08-23 09:23:24 UTC. --
Sep 07 15:39:41 host systemd[1]: Started Session c12 of user root.
Sep 07 15:39:41 host systemd[26562]: Condition check resulted in Sound Service being skipped.
Sep 07 15:39:41 host systemd[26562]: Started Foo User Unit.
Sep 07 15:39:41 host systemd[26562]: Reached target Main User Target.
Sep 07 15:39:41 host systemd[26562]: Startup finished in 210ms.
Sep 07 15:39:41 host systemd[26562]: usertest.service: Succeeded.
Sep 07 15:39:41 host qubes.VMShell-dom0[26608]: 
Sep 07 15:39:41 host qubes.VMShell-dom0[26608]: (xfce4-terminal:26609): dbind-WARNING **: 15:39:41.549: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Sep 07 15:39:41 host qubes.VMShell-dom0[26608]: Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
Sep 07 15:39:46 host qubes-gui[847]: WARNING handle_focus: Window 0x200005d data not initializedXGetWindowAttributes for 0x200005d failed in handle_crossing, ret=0x0

```

**Comment by unman** [comment] 2021-09-08 15:50
I suspect this isnt a Qubes problem, and you have missed part of the
"Steps to reproduce".

You've chosen to install xfce4-terminal - it's not shipped by default.
I suspect you havent installed Xfce and aren't running Xfce in the qube.
If you install a single Xfce application without the Xfce framework you
will see this *warning* (not an error).

**Comment by andrewdavidwong** [comment] 2021-09-08 23:20
Closing as "not an issue" (the reported behavior is not a bug or similarly for other issue types). If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2021-09-08 23:20 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, diagnosed

**Comment by TNTBOMBOM** [comment] 2021-11-20 17:32
> You've chosen to install xfce4-terminal - it's not shipped by default.

Isnt it coming by default with any xfce on any normal distro? 

whats your rational behind not installing it by default and differentiate the template from mainstream xfce-debian?

**Comment by pefu** [comment] 2021-12-07 08:00
I am currently still using Qubes-OS 4.0. I came here by a search for the term "SESSION_MANAGER", because I installed the xfce4-terminal package in a debian-11 and in a fedora-34 template qube. My motivation was to have a terminal emulator application which provides some of the features of gnome-terminal which are missing from xterm, but which is suitable as a terminal application for disposable qubes. The gnome-terminal program forks right away and is therefore not usable that way, because the disposable qube will shutdown again immediately after startup. 
I understand that the session manager running in my dom0 is not accessible by any xfce4-terminal application running in one of my qubes for security reasons.
@unman: I suspect that simply installing more parts of the xfce4-framework in such a template would not solve the problem of the not set $SESSION_MANAGER environment variable.
Unfortunately I have no idea how to avoid this annoying warning of xfce4-terminal when run from within any qube.

**Comment by marmarek** [comment] 2021-12-07 10:41
I don't think there is an easy way to get session manager running in a qube. We intentionally make in-qube system lightweight with disabled several services that are not needed outside of full standalone system.
Anyway, that's just a harmless message, xfce4-terminal works fine.

**Comment by ubuntupunk** [comment] 2024-10-11 18:22
Click on Qube icon, run terminal works fine. But if you wan to 'run terminal in qube' from the qube manager, a dsp opens and quits providing exact same error: Failed to connect to session manager: SESSION_MANAGER environment variable not defined.

**Comment by ThomasFreedman** [comment] 2024-10-21 16:58
I'm encountering this problem on R4.2.1. I have systemd services defined under /home/user/.config/systemd/user, can start them manually when logged in but they don't start at boot due to this SESSION error. The services are "loaded" and "enabled", with preset "enabled".

jpurnalctl -user -xe reports: "localhost qubes.StartApp+xfce4-terminal-dom0[892]: Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined"

And yes, I used "loginctl enable-linger" which should start those services at boot time. When I open a terminal to check they are not running.

**Comment by TNTBOMBOM** [comment] 2024-10-21 17:42
> We intentionally make in-qube system lightweight with disabled several services that are not needed outside of full standalone system.
> Anyway, that's just a harmless message, xfce4-terminal works fine.

I think this answer by marek looks enough to close the discussion about this message.

**Comment by ThomasFreedman** [comment] 2024-10-21 17:50
I thought that might be the case. Doesn't help when testing on a qubes system targeted elsewhere, but I understand the tradeoffs. Just thought I would mention my example. It's not just an xfce issue.

**Comment by TNTBOMBOM** [comment] 2024-10-21 17:56
> you might edit your comment to include a link to where marek said that.

Done.
