### ISSUE TITLE
Outdated article: XFCE installation in dom0

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#2325] opened 2016-09-16 05:21 UTC
The following article is outdated: [XFCE installation in dom0](https://www.qubes-os.org/doc/xfce/)
The article should mention XFCE is fully supported in Dom0 for Qubes R3+ and that XCFE is the standard desktop for Qubes R3.2.

**Comment by kulinacs** [comment] 2016-09-26 07:44
I do believe this is a duplicate of #1923

**Comment by andrewdavidwong** [comment] 2016-09-26 21:32
@kulinacs: Good catch. Thanks.

**Closed by andrewdavidwong** 2016-09-26 21:32 UTC
Labels: C: doc, duplicate, P: major
