### ISSUE TITLE
Dom0 should not have network drivers

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3799] opened 2018-04-08 19:18 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Dom0 kernel

---

### Steps to reproduce the behavior:

Run `find /lib/modules/4.14.18-1.pvops.qubes.x86_64/kernel/drivers/net`

### Expected behavior:

No output, or an error because that directory does not exist

### Actual behavior:

Many lines of output.

### General notes:

Dom0 should not have a network connection.  Therefore, it has no need for any of those drivers, and they increase attack surface in the event of a misconfiguration.

While these drivers must be built if we are to use common Dom0 and DomU kernels, we can delete them from the Dom0 kernel package.

Can these drivers be safely deleted?

---

### Related issues:

#2743

**Comment by marmarek** [comment] 2018-04-08 19:32
Duplicate of #3656

**Closed by marmarek** 2018-04-08 19:32 UTC
