### ISSUE TITLE
Critical error in Qube Manager after enabling "Allow full access for 5 mins"

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#8685] opened 2023-11-06 22:39 UTC
### Qubes OS release

R4.1 & R4.2  - much more prevalent in 4.2

### Brief summary

Enabling the "Allow full access for 5 mins" option results in a critical error the next time the qube's settings are opened within the five-minute window.

### Steps to reproduce

1. In the "Firewall rules" tab of a qube's Settings, select "Limit outgoing connections to..." and "Allow full access for 5 mins."
2. Press "OK."
3. Within the next five minutes, attempt to open the settings for that qube again.

### Expected behavior

Qube Settings opens normally.

### Actual behavior

![houston](https://github.com/QubesOS/qubes-issues/assets/19215444/d8ebc983-62e3-47b5-ab77-1d06747247ef)

Full log in that error window:
```
----
line: expire_time = model.temp_full_access_expire_time - \
func: set_fw_model
line no.: 1464
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: self.set_fw_model(model)
func: __init__
line no.: 192
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: window = window_class(qt_app, qubes_app)
func: run_synchronous
line no.: 558
file: /usr/lib/python3.11/site-packages/qubesmanager/utils.py
----
line: utils.run_synchronous(functools.partial(VMSettingsWindow, vm, args.tab))
func: main
line no.: 1540
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: sys.exit(load_entry_point('qubesmanager==4.2.8', 'console_scripts', 'qubes-vm-settings')())
func: <module>
line no.: 33
file: /usr/bin/qubes-vm-setting
```

**Comment by Eric678** [comment] 2023-11-07 02:07
Update: the problem with the immediate Houston popup when requesting settings rectifies itself eventually, probably when the timer expires.  Don't need to restart the qube.

**Comment by jaydn** [comment] 2024-02-11 12:27
I just experienced I think a variant of this on 4.2. In this case it was:

```
TypeError: unsupported operand type(s) for -: 'int' and 'str'
at line 33
of file /usr/bin/qubes-vm-settings.
```

I was able to workaround by commenting out the bottom 2 lines of func, opening Qube Manager, removing all firewall entries & disabling "allow full access". I could then uncomment the lines and all good.

Here is the more detailed information from the dom0 popup.
```
----
line: expire_time = model.temp_full_access_expire_time - \
func: set_fw_model
line no.: 1464
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: self.set_fw_model(model)
func: __init__
line no.: 192
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: window = window_class(qt_app, qubes_app)
func: run_synchronous
line no.: 558
file: /usr/lib/python3.11/site-packages/qubesmanager/utils.py
----
line: utils.run_synchronous(functools.partial(VMSettingsWindow, vm, args.tab))
func: main
line no.: 1540
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: sys.exit(load_entry_point('qubesmanager==4.2.8', 'console_scripts', 'qubes-vm-settings')())
func: <module>
line no.: 33
file: /usr/bin/qubes-vm-settings
```

**Comment by UndeadDevel** [comment] 2024-02-11 12:41
This seems like a duplicate of #8757 but that is supposed to be fixed now...

**Comment by Eric678** [comment] 2024-05-19 07:34
This issue is not yet fixed!  I only just caught up to date and checked.  Firewall tab in settings with "Limit outgoing connections.." set, and allow for 5 min ticked, then hit "OK" then this is the result of attempting to open the settings in that qube until the timer expires:
![houston](https://github.com/QubesOS/qubes-issues/assets/19215444/d8ebc983-62e3-47b5-ab77-1d06747247ef)

**Comment by UndeadDevel** [comment] 2024-05-19 12:36
> This issue is not yet fixed!

Can confirm and reproduce with the same method as @Eric678 and same result. Full log in that error window:
```
----
line: expire_time = model.temp_full_access_expire_time - \
func: set_fw_model
line no.: 1464
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: self.set_fw_model(model)
func: __init__
line no.: 192
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: window = window_class(qt_app, qubes_app)
func: run_synchronous
line no.: 558
file: /usr/lib/python3.11/site-packages/qubesmanager/utils.py
----
line: utils.run_synchronous(functools.partial(VMSettingsWindow, vm, args.tab))
func: main
line no.: 1540
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
----
line: sys.exit(load_entry_point('qubesmanager==4.2.8', 'console_scripts', 'qubes-vm-settings')())
func: <module>
line no.: 33
file: /usr/bin/qubes-vm-setting
```

**Comment by Eric678** [comment] 2024-05-20 02:02
Intentional!  Simply if the other issue is fixed then this must be different, so undo the dup!

**Comment by unman** [comment] 2024-05-20 12:36
Agreed - it's not a duplicate. The new error message should be noted in OP,
and this should be re-opened.

**Comment by Kungers** [comment] 2024-05-31 07:15
Encountered the same issue as the steps above (Tick Allow all for 5 Minutes). 
Qubes Release: 4.2.1 (R4.2)

**Closed** 2024-07-20 03:23 UTC
Labels: T: bug, C: manager/widget, P: default, needs diagnosis, affects-4.1, affects-4.2
