### ISSUE TITLE
Lots of 'failed to remove ioctl... luks' lines spamming on shutdown. Is it dangerous?

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2593] opened 2017-01-19 07:00 UTC
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Dom0
_(I think...)_

---

### Expected behavior:
Clean shutdown
### Actual behavior:
late in shutdown there is a pause and many (maybe hundreds!) of messages like :

device-mapper: remove ioctl on _[something I can't read because scrolls to fast but has word luks in it]_  failed [something] device or resource busy

After a while system still shutdowns

These messages sound scary.
Should I be worried ?

### Steps to reproduce the behavior:
1) shut down all VMs (so we're sure it's not a VM hanging)
2) run system for like five hours
3) trigger system shutdown from the GUI

### General notes:

Doesn't always happen.
Sometimes.
Usually if uptime > 5 hours.
Pointers as to how to find out what it is and how dangerous it is are very appreciated.

---

**Comment by andrewdavidwong** [comment] 2017-01-20 06:42
I see these too, and I'd also like to know. Any idea, @marmarek?

**Comment by pdinoto** [comment] 2017-02-02 16:07
I see these too, and seems to be related to shutdown when there was at least one machine with an attached block device.

In my case, dom0 root disk is on a SSD, and I have a 2nd LUKS volume at `/var/lib/qubes-add` which is a SHDD disk and added as a xen pool.

Will try to film the issue, as it happens quite frequently for me.

**Comment by marmarek** [comment] 2017-02-02 22:55
It's probably related to long system shutdown ( #1581 ), I guess VMs are not stopped and are still connected to those devices. I still haven't figured out why VMs are not stopped at this point...

**Comment by andrewdavidwong** [comment] 2017-02-03 04:38
@marmarek: I don't think that's what it is (at least not in my case), because I make sure to shut down all VMs before issuing a shutdown/reboot command in dom0.

**Comment by AndreasKieling** [comment] 2019-03-31 19:44
I have the same thing.
Even with all VMs off before shutdown.

**Comment by AndreasKieling** [comment] 2019-05-27 04:37
now it shutdowns properly after shutting all vms down beforehand.

**Comment by jpouellet** [comment] 2019-06-22 00:33
@andrewdavidwong I believe this issue is a duplicate of https://github.com/QubesOS/qubes-issues/issues/1581 (fixed by https://github.com/QubesOS/qubes-gui-daemon/pull/24/commits/a90544af2a6c2d42b0af1208bb63e177f15011ca) and can be closed.

**Comment by andrewdavidwong** [comment] 2019-06-22 09:40
Closing as a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #1581. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by jamke** [comment] 2021-01-03 19:21
I believe it's not duplicate.
I have this "remove ioctl" messages and also would want to know if it's dangerous? I have it in R4.0 and if it were a duplicate of #1581 it would be fixed by now.
Also #1581 has no "remove ioctl" text at all.

The messages are visible if one presses Home button during shutdown, to show console instead of Qubes logo.

I made a video of messages to see full text.
So, these messages are shown a lot of times, probably for each AppVM in the system:

```
device-mapper: remove ioctl on qubes_dom0-pool00-tpool failed: Device or resource busy.
Command failed
device-mapper: remove ioctl on qubes_dom0-pool00-tdata failed: Device or resource busy.
Command failed
device-mapper: remove ioctl on qubes_dom0-pool00-tmeta failed: Device or resource busy.
Command failed
device-mapper: remove ioctl on luks-{SOME-GUID} failed: Device or resource busy.
Command failed
```

And finally:
```
Powering off.
[{uptime}] reboot: Power down
```

**Comment by jamke** [comment] 2021-01-04 05:38
If you need any additional information on this issue - let me know. I have it every shutdown.
If somebody knows if it's dangerous or not - let me know too.

**Comment by DemiMarie** [comment] 2021-12-24 13:05
@jamke These messages are harmless.  @andrewdavidwong okay to close this?

**Comment by andrewdavidwong** [comment] 2021-12-25 09:25
> @jamke These messages are harmless. @andrewdavidwong okay to close this?

I would say there needs to be a decision about whether to do anything about this or not. The decision could be to do nothing, since the messages are harmless, or it could be to somehow hide or suppress the messages, since even if they're harmless, they degrade the user experience and cause users to be concerned.

**Comment by andrewdavidwong** [comment] 2021-12-25 09:27
Changed milestone back to 4.0, because I think this does affect 4.0, and our [policy](https://www.qubes-os.org/doc/issue-tracking/) for bug reports is to set the milestone to the earliest affected supported release.

**Comment by jamke** [comment] 2022-01-07 11:13
> @jamke These messages are harmless. @andrewdavidwong okay to close this?

@DemiMarie, why do you think they are harmless?
Can you share information what causes these remove ioctl failes in the first place?

**Comment by DemiMarie** [comment] 2022-01-07 20:53
I’m not sure, but I wonder if the problem is not all qubes being shut down properly.  Could/should `qvm-shutdown --all --wait` be called during shutdown?

**Comment by rustybird** [comment] 2022-01-07 21:25
> Could/should `qvm-shutdown --all --wait` be called during shutdown?

[It already is](https://github.com/QubesOS/qubes-core-admin/blob/v4.0.59/linux/systemd/qubes-core.service#L13), but somehow that's not as good as doing it manually before shutdown. Probably a weird tangle of implicit systemd orderings and timeouts

**Comment by DemiMarie** [comment] 2022-01-07 21:47
Timeouts seem likely to me.  I wonder if `xl shutdown -aFww` should be used instead; it waits until all VMs are dead.

**Comment by andrewdavidwong** [comment] 2022-01-08 21:24
> > Could/should `qvm-shutdown --all --wait` be called during shutdown?
> 
> [It already is](https://github.com/QubesOS/qubes-core-admin/blob/v4.0.59/linux/systemd/qubes-core.service#L13), but somehow that's not as good as doing it manually before shutdown. Probably a weird tangle of implicit systemd orderings and timeouts

This seems like it's been a recurring problem for years, but I don't know why. See, e.g.:

- https://github.com/QubesOS/qubes-issues/issues/1581#issuecomment-266266876
- https://github.com/QubesOS/qubes-issues/issues/1320
- https://github.com/QubesOS/qubes-issues/issues/1826

**Closed** 2023-08-05 09:32 UTC
Labels: T: bug, C: other, P: minor, ux, diagnosed, eol-4.0
