### ISSUE TITLE
Inconsistencies in appmenu commands between fc21 and fc23

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1634] opened 2016-01-15 15:45 UTC
Some apps, notably Terminal, have different commands embedded in their corresponding .desktop files on fc21 and fc23, resulting in the appmenus created for fc21-based AppVMs no longer working after switching over to the newer template. This might create an impression that VMs do not start, or something is broken. We should at the very least mention this somewhere in the docs/release notes? If this cannot be easily fixed, that is.

**Comment by marmarek** [comment] 2016-01-15 16:30
Duplicate of #1428
It is already documented in [template upgrade documentation](https://www.qubes-os.org/doc/fedora-template-upgrade-21/) (at the end)
There is also a too to ease fixing the issue (not merged yet): https://github.com/QubesOS/qubes-core-admin-linux/pull/4

Where else should it be documented?

**Closed** 2016-11-19 01:06 UTC
Labels: bug, C: desktop-linux, C: templates, duplicate, P: minor, UX
