### ISSUE TITLE
Use wheel group instead of qubes group

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4800] opened 2019-02-07 13:24 UTC
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s):

dom0/domU users/groups

---

### Steps to reproduce the behavior:

Look at `/etc/sudoers.d/qubes`

### Expected behavior:

The file contains something like

```
%wheel ALL=(ALL) NOPASSWD: ALL
```

### Actual behavior:

The file contains

```
%qubes ALL=(ALL) NOPASSWD: ALL
```

or 

```
user ALL=(ALL) NOPASSWD: ALL
```

### General notes:

QubesOS currently uses the `qubes` group to determine who can use QubesOS-specific features from within VMs, as well as who can use `sudo` to gain root privileges.  Instead, QubesOS should use the `wheel` group, which is traditionally used by \*nix systems to designate the group of trusted administrators who can escalate to root.  Most Linux distributions already allow users in group `wheel` to become `root`, so this just becomes a matter of allowing them to do so without supplying credentials.

---

**Comment by marmarek** [comment] 2019-02-07 14:19
If you mean disentangling "being able to use QubesOS-specific features" from "being able to use sudo", it may be more than just changing that group.
Anyway, this is already covered here: https://www.qubes-os.org/doc/vm-sudo/

**Comment by andrewdavidwong** [comment] 2019-02-08 01:20
> Anyway, this is already covered here: https://www.qubes-os.org/doc/vm-sudo/

Interpreting this to mean that the Qubes developers consider this to be working as intended.

Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2019-02-08 01:20 UTC
