### ISSUE TITLE
Improve error messaging for expired release files

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5455] opened 2019-11-09 23:52 UTC
**Qubes OS version**
4.0.x

**Affected component(s) or functionality**
`whonix-gw-14` updates

**Brief summary**
Updating `whonix-gw-14` failed due to expired release files

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to qubes manager
_2. Click on (right click) `whonix-gw-14` and choose "Update"
_3. See this error in the terminal:

```
E: Release file for tor+http://deb.dds6qkxxxx.onion/dists/stretc/InRelease is expired (invaled since 64d 5h 42min 19s).  Updates for this repository will not be applied.
E: Release file for http://deb.whonix.org/dists/stretch/InRelease is expired (invalid since 64d 5h 42min 21s). Updates for this repository will not be applied.
```

The actual Bug/Issue here is that there is no error message that indicates what I should do instead.
**Expected behavior**
_A clear and concise description of what you expected to happen._

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by andrewdavidwong** [comment] 2019-11-10 11:52
Duplicate of #3323

**Comment by andrewdavidwong** [comment] 2019-11-10 11:52
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue (#3323). If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

> The actual Bug/Issue here is that there is no error message that indicates what I should do instead.

Please see https://github.com/QubesOS/qubes-issues/issues/3323#issuecomment-529749572.

**Comment by straussmaus** [comment] 2019-11-17 06:50
@andrewdavidwong 

> Please see #3323 (comment).

Yes of course I did that before I even posted the Issue.  Again "The actual Bug/Issue here is that there is no error message that indicates what I should do instead."

It does not matter that there is a doc about this.  The Issue I am reporting is that there is no error message inside the update script that tells me to go to this place.  

Maybe this is an Issue you will not fix and there could be good reasons not to fix it.  But this is the issue.  The issue is not that there is not good doc on this (there is) and it is not that there is a problem with the whonix-14 template (there isn't) the Issue is that when I update the whonix-14 updater no message tells me the correct thing to do.  An error that says "Problem" but has no Solution is an Issue you might fix maybe not depends on the situation.

Anyway I would not worry for an old template but something to add to fiture templates if possible.

**Comment by andrewdavidwong** [comment] 2019-11-17 09:47
> @andrewdavidwong
> 
> > Please see #3323 (comment).
> 
> Yes of course I did that before I even posted the Issue.

There is no way I could know that, since you left the "Related, non-duplicate issues" field empty and didn't mention #3323 anywhere else in your issue. Many people report duplicates because they're not aware of other issues that exist.

> Again "The actual Bug/Issue here is that there is no error message that indicates what I should do instead."
> 
> It does not matter that there is a doc about this. The Issue I am reporting is that there is no error message inside the update script that tells me to go to this place.
> 
> Maybe this is an Issue you will not fix and there could be good reasons not to fix it. But this is the issue. The issue is not that there is not good doc on this (there is) and it is not that there is a problem with the whonix-14 template (there isn't) the Issue is that when I update the whonix-14 updater no message tells me the correct thing to do. An error that says "Problem" but has no Solution is an Issue you might fix maybe not depends on the situation.
> 
> Anyway I would not worry for an old template but something to add to fiture templates if possible.

Thank for clarifying the report.

**Comment by andrewdavidwong** [comment] 2019-11-17 09:48
FYI @adrelanos

**Comment by adrelanos** [comment] 2019-11-17 11:21
Not a Whonix specific issue.
Same would apply to any Debian template in Qubes which reaches end of life. Might equally apply for Fedora and other templates too.

**Comment by adrelanos** [comment] 2019-11-17 11:32
> is expired (invalid since 64d 5h 42min 21s).

Possibles:

* 1) a stale mirror attack
* 2) a downgrade attack
* 3) signatures forgotten to be refreshed by developers
* 4) end-of-life (EOL)

----

Error messages in case of 1), 2), 3) seem alright. I don't think these can be improved. (As there is no way to distinguish these at an implementation level.)

In case of 4) (EOL) the usability could be improved. There could be a final upgrade of some package inside the VM which indicates EOL. Some pacakge inside the VM could ship a file. For Whonix, `whonix-base-files` package or something could drop a file somewhere. Then some Qubes package could detected existence of this file and react accordingly.

A popup everything time VM starts?

Window title:

> This Template has reached end-of-life. (EOL)

Window text:

> See news: ...
>
> [ ] Do not show this message again.

(Window text needs to be thought through.)

Window buttons:

> OK

----

To implement such a popup... `/usr/lib/msgcollector/one-time-popup`. parameters:

* `status-file`
* `title`
* `message`

usage:

    /usr/lib/msgcollector/one-time-popup status-file title message

It's a standalone python3 script. Source code could be easily copied elsewhere if full `msgcollector` package installation is undesireable. All dependencies are available inside Debian.

* https://github.com/Whonix/msgcollector/blob/master/usr/lib/msgcollector/one-time-popup
* https://forums.whonix.org/t/do-not-show-this-message-again-generic-one-time-popup/8066

----

Otherwise also dom0 could have some mechanism which marks templates as EOL if declared so somewhere.

**Comment by marmarek** [comment] 2019-12-11 01:46
> Some pacakge inside the VM could ship a file. For Whonix, `whonix-base-files` package or something could drop a file somewhere. Then some Qubes package could detected existence of this file and react accordingly.

What about a final update shipping such popup on startup directly? There are already startup warnings in Whonix related to whonixcheck, so I think it could be added somewhere there.

Generally, this is related to https://github.com/QubesOS/qubes-issues/issues/3430

**Comment by adrelanos** [comment] 2019-12-21 18:11
Good idea.

**Comment by ninavizz** [comment] 2021-05-24 08:06
@adrelanos Any updates on this?

**Comment by adrelanos** [comment] 2021-05-26 08:43
Will do https://github.com/QubesOS/qubes-issues/issues/5455#issuecomment-564339872 when Whonix 15 deprecation happens. Created a reminder here just now:
https://forums.whonix.org/t/one-time-popup-notification-of-whonix-15-deprecation-once-whonix-16-was-released/11720

Not sure how tickets are best used. But since this issue was "forwarded to Whonix" or "forwarded to upstream" and not actionable at Qubes, I guess it could be closed. (But I don't have a strong opinion on that one. Works for me either way.)

For the Qubes specific actionable related part there is already #3430.

**Comment by andrewdavidwong** [comment] 2021-05-26 19:35
> Will do #5455 (comment) when Whonix 15 deprecation happens. Created a reminder here just now:
https://forums.whonix.org/t/one-time-popup-notification-of-whonix-15-deprecation-once-whonix-16-was-released/11720

Thanks!

> Not sure how tickets are best used. But since this issue was "forwarded to Whonix" or "forwarded to upstream" and not actionable at Qubes, I guess it could be closed. (But I don't have a strong opinion on that one. Works for me either way.)

Ok, closing. If something actionable on the Qubes side crops back up here, we can always reopen.

**Closed by andrewdavidwong** 2021-05-26 19:35 UTC
Labels: C: templates, P: default, T: enhancement, ux
