### ISSUE TITLE
Pulseaudio-utils package inclusion request for the QubesTV project

### ISSUE THREAD

**Issue by Aekez** [QubesOS/qubes-issues#3659] opened 2018-03-05 15:26 UTC
#### Qubes OS version:

Qubes 4 RC-5 or Qubes 4.1. 
Package currently not found on Qubes 4 RC-3.

#### Affected component(s): 

Missing dom0 package, pulseaudio-utils 
No further dependencies required.

---

### Steps to reproduce the behavior:

Execution of the pactl command for QubesTV sound control is not possible without the package.

### Expected behavior:

The command is very useful for QubesTV sound control, and other possible sound use-cases in Qubes, i.e. to mute sound with a  toggle single keybinded command.
'pactl set-sink-mute 0 toggle'

Other 'pactl' abilities include muting single predetermined Streaming VM's, while preserving or enabling the other streaming VM (multiple of streams, moving sound around with simply clicks). Currently I still need work on a the script to link the dynamic AppVM sound sink ID with a static symbolic link name (or something of the sorts), in order to make it work on individual AppVM's which keep getting new sink ID's. Once that is done, then pactl will be useful here too, as well as switching sound-card output.

In so far, pulseaudio-utils (pactl) is very useful as a sound control command, which is very straight forward and easy to use (and script), which makes it more easy to review the script too (keeping it as simple as possible).

### Actual behavior:

Execution of the pactl command for QubesTV sound control is not possible without the package.

### General notes:

- I've exhausted the search engine to find solutions, however I've not found a solution which also works in dom0 without installing a package, or introducing needless script complexity. The pactrl command is very handy, small and light, simple, and gives great sound control at the same time, which can be scripted and keybinded.

- I suspect at some point it will be ideal to move sound control away from dom0 as standard, however, it won't be standard any time soon, right? As such, this request is to have this  small package in dom0 until dom0 no longer controls sound by default.

- If putting the package in dom0 is undesired as a default inclusion, is it then possible to have a security evaluation of using this package in dom0? I suspect its safe, but having a second professional opinion would be valuable for the QubesTV project. Is this package safe to install in dom0? I.e. would it be fine to advice to run "sudo qubes-dom0-update pulseaudio-utils" in the QubesTV guide?

---

#### Related issues:

- In the near-term future, it is also speculated whether open source offline A.I.'s can be tied to QubesTV use-cases, in where linking the commands to voice control should hypothetically be straight forward once QubesTV working. This is a next step once QubesTV (based on simple scripts) is finished and working.  By then though, it would probably be desired to have default sound in an AppVM, rather than installing voice control A.I. in dom0. Are there currently any estimates on when AppVM sound control will become Qubes default?

**Comment by marmarek** [comment] 2018-03-05 19:44
> I.e. would it be fine to advice to run "sudo qubes-dom0-update pulseaudio-utils" in the QubesTV guide?

Yes, this is exactly what you should do. If you want, you can even add `-y` option to avoid confirmation prompt.

**Comment by Aekez** [comment] 2018-03-05 23:01
That's very good news, thanks a lot for the suggestion and confirmation! Having this package in dom0 definitely clears a major hurdle I have with putting together QubesTV, version 1.0.

Regarding the QubesTV project, I'll upload pieces of the guide/scripts over the couple of weeks as the exam period calms down a bit. The goal is to publish a Qubes doc page once I've put everything together, at that point I hope the quality will be sufficient to be worth sharing, but I will also openly welcome any found criticism or suggestions to improve it further. I'm planning to stick with it afterwards to keep working on ~ 1.x. version releases for further improvements, in order to improve quality and add extra features.

**Comment by andrewdavidwong** [comment] 2018-03-06 01:38
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-03-06 01:38 UTC
