### ISSUE TITLE
Error During Update

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#5779] opened 2020-04-19 07:22 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Update / Upgrade of fedora30 template

**Brief summary**
During the Upgrade in the  Verifying phase an Error occur

Error during downloading metadata for repository 'fedora':
- Curl error (6) Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist:
Curl error (6) Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

**To Reproduce**
Start update/upgrade of a fedora 30 template via Qube Manager or via dnf upgrade...

**Expected behavior**
no error occur

**Actual behavior**
error after verifying all packages

**Comment by andrewdavidwong** [comment] 2020-04-21 09:45
This appears to be a temporary network problem when attempting to connect to fedora update servers. Since this is not a bug, and not Qubes-specific, I'm closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2020-04-21 09:45 UTC
Labels: P: default, T: bug

**Comment by akkuladezeit** [comment] 2020-05-06 20:39
ok can be closed but im still confused:
why is there an connection at this late stage of the update?  Packages are already downloaded, installed and verifiied... ?

**Comment by andrewdavidwong** [comment] 2020-05-10 13:40
> ok can be closed but im still confused:
> why is there an connection at this late stage of the update? Packages are already downloaded, installed and verifiied... ?

It must be that there is some step involving downloading metadata at that point in the process. I think this is more of a dnf question than anything Qubes-specific.
