### ISSUE TITLE
DisposableVM logs not discarded in /var/log/qubes/guid.[dispxxx].log

### ISSUE THREAD

**Issue by Shic1983** [QubesOS/qubes-issues#6222] opened 2020-11-22 11:20 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
dom0

**Brief summary**
Disposable VM logs not discarded in /var/log/qubes/guid.[dispxxx].log

**Expected behavior**
After a disposable vm is close the log should be discarded, or at least rm disp* logs on reboot

**Actual behavior**
disposable vm logs are left to accumulate in /var/log/qubes/guid.[dispxxx].log

**Screenshots**
https://i.imgur.com/1STtB6Y.png

**Comment by unman** [comment] 2020-11-22 18:24
This is duplicate of  Section 1 item 9 of #4972

**Comment by andrewdavidwong** [comment] 2020-11-23 13:34
Duplicate of #4972

**Comment by andrewdavidwong** [comment] 2020-11-23 13:36
Actually, it looks like this particular topic was spun off into #5820 (see https://github.com/QubesOS/qubes-issues/issues/4972#issuecomment-484336804).

**Comment by andrewdavidwong** [comment] 2020-11-23 13:36
Duplicate of #5820

**Comment by andrewdavidwong** [comment] 2020-11-23 13:36
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-11-23 13:36 UTC
Labels: C: other, P: default, T: bug
