### ISSUE TITLE
Clearer Hardware compatiability list 

### ISSUE THREAD

**Issue by salgo** [QubesOS/qubes-issues#5405] opened 2019-10-21 16:52 UTC
**The problem you're addressing (if any)**
I'm a new user to Qubes. As I'm sure you can appreciate I want to try it out before it becomes my daily driver. To this end, I've been looking at the HCL and looking at eBay to find suitable items. This task is very much complicated by the fact that the items listed on there have varying levels of working and are testing against different versions.

**Describe the solution you'd like**
It seems to me that the best solution is a very simple JS application that allows you to filter by Qubes version and the various system features it supports. 

**Where is the value to a user, and who might that user be?**
If you lurk on reddit/Qubes as I've been doing you'll see a few people who have looked at the HCL found some kit, installed Qubes on it only to find that it doesn't work. This is not the best first experience for new users. 

**Describe alternatives you've considered**
A simpler alternative is to split the table into Qubes version (like the documentation elsewhere and is included in the guidelines elsewhere) and move the hardware that doesn't work into a different table title "known broken" or similar.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/hcl/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#3451 #1203 #53

I'm very happy to undertake this work if you think it is a good idea.

**Comment by andrewdavidwong** [comment] 2019-10-23 06:08
Duplicate of #3795

**Comment by andrewdavidwong** [comment] 2019-10-23 06:08
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-10-23 06:08 UTC
Labels: P: default, T: enhancement
