### ISSUE TITLE
Starting disposable VM from dmenu can start its template

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#7314] opened 2022-02-28 03:13 UTC
### Qubes OS release
4.1 (both upgraded from 4.0 and fresh install, affects two machines)

### Brief summary
Starting a new dispVM from i3/dmenu can randomly start either a new dispVM or its template. Repeated invocations eventually start a new dispVM.

### Steps to reproduce
From a QubesOS 4.1 install with i3 and dmenu:
1. Open dmenu
2. Type `dvm firefox` (assuming the dispVM template VM's name is `dvm`.
3. Watch either a new dispVM or the template start.

### Expected behavior
This should always start a new dispVM as it did in 4.0.

### Actual behavior
A new dispVM or the template will be started, seemingly at random. Additionally, dmenu displays two entries:
* dvm: firefox
* dvm: firefox (2)

**Comment by TheOne-Z** [comment] 2022-02-28 15:51
The directory where dmenu pulls those result is located at (dom0):  
`/home/user/.local/share/applications`

Example of an disposable template which has xterm in application menu: following .desktop files are created once you mark your app qube as a disposable template.
```
org.qubes-os.dispvm.test.xterm.desktop
org.qubes-os.qubes-vm-settings.test.desktop
org.qubes-os.vm.test.xterm.desktop
```
Dmenu is confused because both of those share the same name "xterm" in this case (`X-Qubes-AppName=xterm`).

The latter of those .desktop files (`org.qubes-os.vm.test.xterm.desktop`) can be deleted as a workaround if you do not plan to modify the disposable template (and it still can be modified by starting the disposable template from Qubes Manager and lauching a terminal in it).

**Comment by qtpies** [comment] 2022-03-03 18:30
Confirming this issue, and the workaround.

**Comment by dmoerner** [comment] 2022-03-04 12:52
I believe this is a dupe of https://github.com/QubesOS/qubes-issues/issues/7297

**Comment by andrewdavidwong** [comment] 2022-03-04 18:30
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-03-04 18:30 UTC
Labels: T: bug, C: desktop-linux-i3, P: default, needs diagnosis
