### ISSUE TITLE
QWT : Qubes Windows10 Tools - R4.1

### ISSUE THREAD

**Issue by b4b857f6ee** [QubesOS/qubes-issues#6289] opened 2020-12-16 21:46 UTC
**The problem you're addressing (if any)**
There is no QWT to fully integrate Windows 10 in QubesOS R4.1

**Describe the solution you'd like**
QWT like the previous QWT for Windows 7.

**Where is the value to a user, and who might that user be?**
Using Windows 10 like it was with the QWT in Windows 7

**Describe alternatives you've considered**
Nothing

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/3585

**Comment by b4b857f6ee** [comment] 2020-12-17 08:29
@andrewdavidwong I open a bountysource :) https://www.bountysource.com/issues/95242068-qwt-qubes-windows10-tools-r4-1

**Comment by iamahuman** [comment] 2020-12-19 04:11
Duplicate of #1861

**Comment by fepitre** [comment] 2020-12-19 09:01
This is not a duplicate but rather an extension. As there is a bounty on this at least the author needs properly update the bountysource depending on @andrewdavidwong refactor of both the issues.

**Comment by andrewdavidwong** [comment] 2020-12-21 14:53
Unless someone can explain why this isn't a duplicate of #1861, it does look like a duplicate to me.

If so, please update your bounty to point to #1861, @b4b857f6ee.

If not, please explain how the two issues are different, and we can reopen this one.

**Closed by andrewdavidwong** 2020-12-21 14:53 UTC
Labels: C: windows-tools, P: default, R: duplicate, T: enhancement, bounty

**Comment by fepitre** [comment] 2020-12-22 09:34
@andrewdavidwong It looks duplicate but the scope for #1861 is for Windows 8+. Here we don't even have any QWT built for R4.1. I've already made some tests and fixes for what should be done in our side as discussed in https://qubes-os.discourse.group/t/testing-windows-and-qwt-in-r4-1. My suggestion was to enlarge the scope of #1861 to have this one closed.

**Comment by andrewdavidwong** [comment] 2020-12-23 15:06
> It looks duplicate but the scope for #1861 is for Windows 8+

It looks to me like it already includes Windows 10.

> My suggestion was to enlarge the scope of #1861 to have this one closed.

That would be preferable, but how should it be further enlarged?

**Comment by fepitre** [comment] 2020-12-23 15:12
> > It looks duplicate but the scope for #1861 is for Windows 8+
> 
> It looks to me like it already includes Windows 10.

Yes but not Windows 7 for R4.1.

> > My suggestion was to enlarge the scope of #1861 to have this one closed.
> 
> That would be preferable, but how should it be further enlarged?

If #1861 is for Release 4.1, we need to add: `Support for Windows 7+` and in this case the scope of the issue itself includes the current one #6289. It's just for clarifying the goals for the ongoing work.

**Comment by andrewdavidwong** [comment] 2020-12-23 15:30
> > > It looks duplicate but the scope for #1861 is for Windows 8+
> > 
> > 
> > It looks to me like it already includes Windows 10.
> 
> Yes but not Windows 7 for R4.1.
> 
> > > My suggestion was to enlarge the scope of #1861 to have this one closed.
> > 
> > 
> > That would be preferable, but how should it be further enlarged?
> 
> If #1861 is for Release 4.1, we need to add: `Support for Windows 7+` and in this case the scope of the issue itself includes the current one #6289. It's just for clarifying the goals for the ongoing work.

Is it really a good idea for us to take on the task of supporting Windows 7 when even the *creator* of Windows 7 no longer supports it?

**Comment by DemiMarie** [comment] 2020-12-23 17:28
> Is it really a good idea for us to take on the task of supporting Windows 7 when even the _creator_ of Windows 7 no longer supports it?

Probably not.  In QubesOS, a Windows 7 VM can still be fairly secure if it has no network access and no files ever enter it from untrusted sources, but that doesn’t make using it a good idea.

**Comment by b4b857f6ee** [comment] 2021-01-29 11:10
Should i need to change something?

**Comment by b4b857f6ee** [comment] 2021-02-24 07:52
@andrewdavidwong Hello, can i recreate a bounty for https://github.com/QubesOS/qubes-issues/issues/1861 ?

**Comment by b4b857f6ee** [comment] 2021-02-24 07:58
ok i just send monay to https://www.bountysource.com/issues/32090963-qubes-windows-tools-support-for-windows-8-8-1-10****

**Comment by makeasnek** [comment] 2023-08-25 22:05
@b4b857f6ee unfortunately your money just went into a black hole

Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues
