### ISSUE TITLE
lock screen does not turn off backlight while active (nouveau/ThinkPad P52)

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#5000] opened 2019-04-26 09:07 UTC
**Qubes OS version**
R4.0, kernel-latest

**Affected component(s) or functionality**
X11

**Brief summary**
Activate the lock screen. The backlight stays on.

**To Reproduce**
See summary.

**Expected behavior**
While the screen is locked the backlight should be turned off.

**Actual behavior**
It glows eerily in the dark.

**Additional context**
Backlight control on Lenovo P52 with nouveau started working with kernel 5.0.7 BUT currently requires a modified xen.cfg enty:

kernel=vmlinuz-5.0.9-1.pvops.qubes.x86_64 [...] acpi_backlight=vendor acpi_osi="Linux" thinkpad-acpi.brightness_enable=1 nouveau.modeset=1 [...]

It seems that the currently used lockscreen is not up to the task and also cannot be configured to use alternative ways of controlling screen brightness.

**Solutions you've tried**
Installing Arch Linux helps tremendously.

Please consider replacing the component.

**Comment by red-avalanche** [comment] 2022-05-10 16:48
This seems like an old issue, but I am seeing it today so I'm not sure if it's been fixed.

**Qubes OS version**
xen_version: 4.14.4
Linux 5.10.104-3.fc32.qubes.x86_64

**Affected component(s) or functionality**
X11

**Brief summary**
Same as initial issue

**To Reproduce**
See summary.

**Expected behavior**
While the screen is locked the backlight should be turned off.

**Actual behavior**
It glows eerily in the dark.

**Additional context**
Desktop with Nvidia 1080Ti, Ryzen 3700 CPU, and Samsung Odyssey monitor over DisplayPort.

Solutions you've tried
I tried changing the settings in xen.cfg as in the original issue but it had no effect for me.

**Comment by DemiMarie** [comment] 2022-05-11 18:21
This is an XScreenSaver bug.  Not sure if it will be fixed, but it will go away if the GUI ever switches to Wayland.

**Comment by red-avalanche** [comment] 2022-06-30 23:39
I believe Qubes needs to provide a newer version of XScreenSaver (or dom0) to address this bug. Went to submit a bug report and found this on the bug reporting site:

> If you think you have found a bug, please let me know! The [Bugs](https://www.jwz.org/xscreensaver/bugs.html) page explains how to submit a useful bug report. But the _**very first thing you should do**_ is try the latest version to see if the bug is already fixed. _Particularly_ if you are not yet using version 6.

I tried upgrading by manually downloading the `.rpm` but encountered dependency hell with basic things like outdated `glibc`. From the xscreensaver package name (`xscreensaver-base-1:5.45-5.fc32.x86_64`) it looks like it's gathered from Fedora 32? Version 5.45 of XScreenSaver was released 8 Dec 2020 so it's quite old.

Reading the [change logs](https://www.jwz.org/xscreensaver/changelog.html) version 6.02 may help.
> X11: “Disable Screen Saver” was behaving like “Blank Screen Only”.

**Comment by DemiMarie** [comment] 2022-07-01 01:10
@marmarek any chance we can do that?

**Comment by unman** [comment] 2022-07-02 03:53
[quote]
@marmarek any chance we can do that?
[/quote]
FYI I had put in PR to create QScreensaver based on 6, but it isn't included
in 4.1

**Comment by red-avalanche** [comment] 2022-07-02 21:19
> FYI I had put in PR to create QScreensaver based on 6, but it isn't included in 4.1

If there is already a PR to update this could you post it here so we can review the necessary changes?

**Comment by marmarek** [comment] 2022-07-03 11:41
> Reading the [change logs](https://www.jwz.org/xscreensaver/changelog.html) version 6.02 may help.
> 
> > X11: “Disable Screen Saver” was behaving like “Blank Screen Only”.

I'm aware of all the improvements in 6.x, most of them are very exciting. But also, there is a massive regression (actually, related to backlight) that is a deal breaker. I tried to find some fix with the upstream for some time already, but for now found only really ugly workarounds that are not really appropriate for releasing...

**Comment by DemiMarie** [comment] 2022-07-03 18:37
> > Reading the [change logs](https://www.jwz.org/xscreensaver/changelog.html) version 6.02 may help.
> > > X11: “Disable Screen Saver” was behaving like “Blank Screen Only”.
> 
> I'm aware of all the improvements in 6.x, most of them are very exciting. But also, there is a massive regression (actually, related to backlight) that is a deal breaker. I tried to find some fix with the upstream for some time already, but for now found only really ugly workarounds that are not really appropriate for releasing...

What is the regression, and what are the workarounds?  Is an out-of-tree patch practical?

**Comment by red-avalanche** [comment] 2022-07-03 20:16
> I'm aware of all the improvements in 6.x, most of them are very exciting. But also, there is a massive regression (actually, related to backlight) that is a deal breaker. I tried to find some fix with the upstream for some time already, but for now found only really ugly workarounds that are not really appropriate for releasing...

I know it's not a minor version change, but if that's the case would it be worth switching to something else?

**Comment by DemiMarie** [comment] 2022-07-03 20:31
> > I'm aware of all the improvements in 6.x, most of them are very exciting. But also, there is a massive regression (actually, related to backlight) that is a deal breaker. I tried to find some fix with the upstream for some time already, but for now found only really ugly workarounds that are not really appropriate for releasing...
> 
> I know it's not a minor version change, but if that's the case would it be worth switching to something else?

The problem is that X11 has horrible support for screen lockers.  A screen locker must never ever ever crash, because if it does the screen is unlocked.  I have an [open merge request] that would (hopefully) solve the problem, by having the server terminate immediately if the screen locker exits.  The long-term solution is to switch to Wayland, but this is a massive amount of work.

**Comment by andrewdavidwong** [comment] 2023-04-07 22:53
Is this still a problem in 4.1?

**Comment by na--** [comment] 2023-04-08 06:30
Yes, it happens fairly often for me. FWIW, it happens on my laptop with an 11th gen Intel CPU (with disabled dGPU).

**Comment by andrewdavidwong** [comment] 2023-08-14 17:51
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of #3590 ([pointed out by fsflover](https://forum.qubes-os.org/t/xscreensaver-wont-switch-off-display/20349/2)). If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2023-08-14 17:51
Duplicate of #3590

**Closed by andrewdavidwong** 2023-08-14 17:51 UTC
Labels: T: bug, C: desktop-linux, P: minor, hardware support, needs diagnosis, affects-4.1
