### ISSUE TITLE
Fedora 35 The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7259] opened 2022-02-10 12:39 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Upgraded fedora 34 to 35, Got a warning message whenever i want to update fedora

### Steps to reproduce

Just used this command: 

`sudo dnf --releasever=35 distro-sync --best --allowerasing`

Btw everything seems to be working/functioning perfectly (according to my own usage)

### Expected behavior

fixing that warning message

### Actual behavior

```
[user@fedora-35 ~]$ sudo dnf --refresh upgrade && sudo dnf clean all 
/usr/lib/python3.10/site-packages/dnf-plugins/qubes-hooks.py:23: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion

Fedora 35 - x86_64                              1.8 MB/s |  79 MB     00:43    
Fedora 35 openh264 (From Cisco) - x86_64        1.2 kB/s | 2.5 kB     00:02    
Fedora 35 - x86_64 - Updates                    1.6 MB/s |  25 MB     00:16    
Qubes OS Repository for VM (updates-testing)     74 kB/s | 124 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
/usr/lib/python3.10/site-packages/dnf-plugins/qubes-hooks.py:23: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion

32 files removed
[user@fedora-35 ~]$ 
```

### Related

#6969

**Comment by marmarek** [comment] 2022-02-10 12:45
Duplicate of #7083

**Closed by marmarek** 2022-02-10 12:45 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2022-02-10 12:53
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
