### ISSUE TITLE
fedora-25-minimal is password locked

### ISSUE THREAD

**Issue by ohreally** [QubesOS/qubes-issues#3365] opened 2017-12-04 10:08 UTC
#### Qubes OS version:

R4.0-rc3

#### Affected TemplateVMs: 

fedora-25-minimal

---

### Steps to reproduce the behavior:

Install and clone fedora-25-minimal (following the docs at https://www.qubes-os.org/doc/templates/fedora-minimal/). Open VM Settings for the clone, and refresh the applications. Start XTerm.
Type 'su -' (following docs): system asks for root password.
Type 'sudo bash' (which is installed contrary to what the docs say): system asks for user password.
If there are default passwords for user and root, I have not been able to find them in the documentation.

For anyone running into this problem, open a dom0 terminal and type

`qvm-run -u root fedora-25-minimal-clone xterm`

(obviously replacing the name of my clone with the name of your clone). A root terminal will open where you can make all the changes you need (including [sudo config](https://www.qubes-os.org/doc/vm-sudo/)).

**Comment by andrewdavidwong** [comment] 2017-12-05 02:06
This appears to be a duplicate of #3157. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-05 02:06 UTC
