### ISSUE TITLE
iommu=no-gfx Xen kernel option causes coreboot laptops to not boot 4.0rc1

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#2994] opened 2017-08-08 15:26 UTC
Lenovo X220 with coreboot & SeaBios:
https://groups.google.com/forum/#!topic/qubes-users/jfQovXpzCq8

Lenovo T530 with coreboot & SeaBios:
https://groups.google.com/forum/#!topic/qubes-users/8dRA8hIpSgI

Removing the option fixed the issue for the T530.

**Comment by marmarek** [comment] 2017-08-08 15:29
Duplicate of #2953

**Closed by marmarek** 2017-08-08 15:29 UTC
Labels: duplicate

**Comment by DarkCoridor** [comment] 2017-09-05 08:22
@3hhh were you able to get the x220 working? Removing the `iommu=no-igfx` option does not work for me with my Coreboot + SeaBIOS + ME cleaned machine

**Comment by 3hhh** [comment] 2017-09-05 17:51
@DarkCoridor I don't know about the x220 (that was some other guy in the aforementioned thread), I only got a T530 working with Coreboot + SeaBIOS + ME cleaned + Qubes 4.0rc1.

**Comment by h01ger** [comment] 2017-09-25 11:47
so, removing iommu=no-gfx indeed makes the system boot. Which makes me wonder:
- I guess you added this for a reason, what's the downside of not using it?
- is this a bug in coreboot? or just a misconfigured coreboot?

**Comment by marmarek** [comment] 2017-09-25 18:46
See [here](https://github.com/QubesOS/qubes-issues/issues/2836#issuecomment-305780009) for the full story. There is also Xen bug (https://github.com/QubesOS/qubes-issues/issues/2841#issuecomment-318207737) resulting in Xen panic, triggered by this option. Both already fixed, but you need to download updates for that (which is hard on the system not starting at all...).
