### ISSUE TITLE
Kali 2 HVM - GUI broken

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#2761] opened 2017-04-19 00:13 UTC
Affected: Qubes OS version R3.2

GUI broken when creating a Kali 2 HVM with the latest Kali 2 iso

**Comment by andrewdavidwong** [comment] 2017-04-19 00:16
Can you be more specific? In what way is the GUI broken?

**Comment by Simon-Davies** [comment] 2017-04-19 00:21
See a picture of the gui here: https://s24.postimg.org/vra4obket/IMG_0491.jpg

The gui is cut to the bottom of the window and non functional

**Comment by andrewdavidwong** [comment] 2017-04-19 17:07
Duplicate of #1981.

**Comment by andrewdavidwong** [comment] 2017-04-20 17:08
Reopening this issue to track the problem @Simon-Davies and others have reported with Kali HVMs.

While the problem was previously being tracked in #1981, it turns out that several users prefer to use a Kali **template** rather than a Kali **HVM** in order to avoid this very problem.

**Comment by Jeeppler** [comment] 2017-04-20 19:28
@Simon-Davies could you please specify which version you used? I guess you used Kali 2016.2 ISO. The best would be to add a hash sum of your ISO in your initial bug report. This way it would be easier to reproduce your issue. Because if I have the hash sum of the ISO I can download the exact same ISO.

Furthermore, did you install Kali or do you just use the Live CD?

**Comment by Chilinot** [comment] 2017-04-21 10:41
This exact problem has been discussed and solved in the qubes-users mailing list. I had the same problem and solved it by reading a thread in said list. However, I can not remember nor find the thread at the moment.

But, if I remember correctly it had to do with a change in X11 when switching from Debian 8 to Debian 9.

**Comment by Simon-Davies** [comment] 2017-04-21 11:12
I used the latest Kali 2016.2 ISO downloaded as a torrent 2 days ago. I can get a hash sum if it's required.

I installed kali into the Kali HVM I created.

You here to the login screen and that is fine but as soon as you are I'm the OS you get the GUI issues where it's cut to the bottom of the screen.

**Comment by Chilinot** [comment] 2017-04-21 11:16
This is a known and solved issue. There should be a working Kali template in the repos IIRC.

If that is not an option, take a look at the issue and subissues/threads linked by @andrewdavidwong.

**Comment by Simon-Davies** [comment] 2017-04-21 11:20
I created a working Kali template upgrading Debian 8 to Debian 9 Stretch and installing Katoolin to create a customised Kali build.

This does not fix the fact that you can't run Kali in a HVM though.

**Comment by Chilinot** [comment] 2017-04-21 11:23
My bad, it didn't occur to me when I wrote my previous post that you would not be able to apply the solution when using a HVM.

**Comment by Simon-Davies** [comment] 2017-04-21 11:27
If you can't bring up the Terminal on the HVM how can you edit Xorg settings?

You are forced to use a Kali AppVM template instead. 

Having a working template is better than having no Kali though :)

**Comment by Simon-Davies** [comment] 2017-04-21 11:29
Could quves not detected the installation of kali or that it is booting and do the Xorg change automatically? Maybe a possibile fix

**Comment by Chilinot** [comment] 2017-04-21 11:31
I don't have a kali hvm at the moment so I cant test it myself. But are you able to access a virtual console by pressing Ctrl+Alt+F1 ?

**Comment by Simon-Davies** [comment] 2017-04-21 11:32
I'll give this a shot now :) Thanks Chilinot :)

**Comment by Simon-Davies** [comment] 2017-04-21 11:55
Unfortunately Ctrl Alt F1 doesn't work. I've removed the Xfce keyboard shortcuts so they don't interfere but had no luck.

Off topic: For the Windows HVM documentation if the user removes the Xfce keyboard shortcuts they can press Ctrl Alt Del to login to Windows and them disable the Ctrl Alt Del logon option.

The documentation days to use Ctrl Alt Home but on my Dell laptop this didn't work

**Comment by vikasbswami** [comment] 2017-05-02 12:28
Any updates about this isssu??

**Comment by Jeeppler** [comment] 2017-06-10 16:10
I was able to reproduce the issue with the latest Kali 2017.1:

~~~
$ sha256sum kali-linux-2017.1-amd64.iso 
49b1c5769b909220060dc4c0e11ae09d97a270a80d259e05773101df62e11e9d  kali-linux-2017.1-amd64.iso
~~~

Furthermore, I was able to fix the issue by enabling automatic login in in the Gdm3 configuration file after the installation of Kali.

#### Fix

Using the KaliLinux LiveCD is the easiest method to be able to enable automatic login, because the HVM cannot be access by using a `xl` or `virsh` console.

The following is assumed: 
- during the installation the username `user` was selected
- the name of the Kali Linux HVM is `kali-vm`
- the Kali Linux `.iso` file is in the `Download` directory of the `personal` VM

Enable automatic login in Gdm3 configuration file:

1. After installation, start `kali-vm` in Dom0 terminal with:

        dom0: qvm-start kali-vm --cdrom personal:/home/user/Downloads/kali-linux-<version>-amd64.iso

    for example:
        
        dom0: qvm-start kali-vm --cdrom personal:/home/user/Downloads/kali-linux-2017.1-amd64.iso

2. Select in boot menu `LiveCD`
3. Mount the root partition of the `kali-vm` installation in `kali-vm`

        kali-vm: sudo mount /dev/mapper/kali--vg-root /mnt/

4. Enable automatic login by uncommenting the following lines in `/mnt/etc/gdm3/daemon.conf`

        [daemon]
        # Enable automatic login
          # AutomaticLoginEnable = true
          # AutomaticLogin = user

   like this

        [daemon]
        # Enable automatic login
          AutomaticLoginEnable = true
          AutomaticLogin = user

5. Save the file and shutdown `kali-vm`
6. Start `kali-vm` **without** the Kali Linux CD attached: `qvm-start kali-vm`

**Comment by Jeeppler** [comment] 2017-06-17 09:03
I was able to reproduce the issue with the latest Kali 2017.1:

~~~
$ sha256sum kali-linux-2017.1-amd64.iso 
49b1c5769b909220060dc4c0e11ae09d97a270a80d259e05773101df62e11e9d  kali-linux-2017.1-amd64.iso
~~~

Furthermore, I was able to fix the issue by enabling automatic login in in the Gdm3 configuration file after the installation of Kali.

#### Fix

Using the KaliLinux LiveCD is the easiest method to be able to enable automatic login, because the HVM cannot be access by using a `xl` or `virsh` console.

The following is assumed: 
- during the installation the username `user` was selected
- the name of the Kali Linux HVM is `kali-vm`
- the Kali Linux `.iso` file is in the `Download` directory of the `personal` VM

Enable automatic login in Gdm3 configuration file:

1. After installation, start `kali-vm` in Dom0 terminal with:

        dom0: qvm-start kali-vm --cdrom personal:/home/user/Downloads/kali-linux-<version>-amd64.iso

    for example:
        
        dom0: qvm-start kali-vm --cdrom personal:/home/user/Downloads/kali-linux-2017.1-amd64.iso

2. Select in boot menu `LiveCD`
3. Mount the root partition of the `kali-vm` installation in `kali-vm`

        kali-vm: sudo mount /dev/mapper/kali--vg-root /mnt/

4. Enable automatic login by uncommenting the following lines in `/mnt/etc/gdm3/daemon.conf`

        [daemon]
        # Enable automatic login
          # AutomaticLoginEnable = true
          # AutomaticLogin = user

   like this

        [daemon]
        # Enable automatic login
          AutomaticLoginEnable = true
          AutomaticLogin = user

5. Save the file and shutdown `kali-vm`
6. Start `kali-vm` **without** the Kali Linux CD attached: `qvm-start kali-vm`

**Comment by z4ppy** [comment] 2017-06-18 13:14
Thanks you !!

You can also do it without livecd :
In dom0 : qvm-block -A vm_name dom0:/var/lib/qubes/appvms/kalivm/root.img
In vm_name : sudo mount -t ext4 /dev/xvdi1 /mnt/removable/
Enable automatic login as you did, in /mnt/removable/etc/gdm3/daemon.conf

**Comment by Jeeppler** [comment] 2017-07-04 21:46
@andrewdavidwong I think we can close this issue.

**Closed** 2017-07-05 05:24 UTC
Labels: bug, C: other, help wanted
