### ISSUE TITLE
Qubes Global Settings UI shows strange value for Default DisposableVM Template

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#6852] opened 2021-08-23 11:39 UTC
### Qubes OS release

introduced in R4.1.0 beta

### Brief summary

The `Qubes Global Settings` UI shows a strange value for `Default DisposableVM Template`.

### Steps to reproduce

start `Qubes Global Settings` UI in dom0

### Expected behavior

The value under the key `Default DisposableVM Template` shows the name of an existing template VM plus `(current)` string.

### Actual behavior

The value under the key `Default DisposableVM Template` shows `<object object at 0x710af8d90950> (current)` (yes, `object` is printed twice).

**Comment by unman** [comment] 2021-08-24 11:51
Duplicate of #6800

**Comment by andrewdavidwong** [comment] 2021-08-24 22:19
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-08-24 22:19 UTC
Labels: T: bug, C: manager/widget, P: default, needs diagnosis
