### ISSUE TITLE
Document paranoid (sandboxed) backup restore

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6708] opened 2021-06-17 00:27 UTC
**Qubes OS version (if applicable)**

R4.1

**Affected component(s) or functionality (if applicable)**

core-admin-client, core-admin

**Brief summary**

R4.1 brings fully developed sandboxed backup restore (initially described at https://www.qubes-os.org/news/2017/04/26/qubes-compromise-recovery/). We need to include both user documentation, and developer documentation (how it's done internally). 

**Additional context**

Pull requests linked to https://github.com/QubesOS/qubes-issues/issues/5310

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/backup-restore/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by UndeadDevel** [comment] 2023-09-03 22:13
Isn't this a duplicate of #2791 ?

**Comment by andrewdavidwong** [comment] 2023-09-04 02:39
> Isn't this a duplicate of #2791 ?

Indeed, looks like a duplicate.

**Comment by andrewdavidwong** [comment] 2023-09-04 02:40
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2023-09-04 02:40
Duplicate of #2791

**Closed by andrewdavidwong** 2023-09-04 02:40 UTC
Labels: C: doc, T: task, P: default
