### ISSUE TITLE
qrexec-client-vm doesn't work with the same VM as its target

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4583] opened 2018-12-07 08:03 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-qrexec

---

### Steps to reproduce the behavior:

1. Run e.g. `qrexec-client-vm current_qube_name qubes.InstallUpdatesGUI`
2. Type YES and hit enter to allow the default policy file to be created
3. Type `current_qube_name` in the dom0 policy box and hit enter

### Expected behavior:

The service is properly invoked.

### Actual behavior:

`qrexec-client-vm` hangs forever, even though the mention of pipes in https://www.qubes-os.org/doc/qrexec3/#qubes-rpc-internals seems to imply that it should work just fine.

### General notes:

Obviously you can also see this behavior with tools like `qvm-copy` when providing the source as the destination. I have also double-checked that services work properly from a _different_ VM. This issue only appears with one VM talking to itself.

---

**Comment by marmarek** [comment] 2018-12-07 13:06
This is duplicate of #951 
Indeed it could be better signaled at qrexec level.

**Closed by marmarek** 2018-12-07 13:06 UTC

**Comment by marmarek** [comment] 2018-12-08 21:30
BTW #1392 ...

**Comment by andrewdavidwong** [comment] 2018-12-09 01:59
> BTW #1392 ...

What about it?

**Comment by marmarek** [comment] 2018-12-09 02:31
This issue is result of low quality of qrexec documentation - something that #1392 is about. But to fix #1392, I really need to create proper qrexec protocol specification, not only description of selected specific cases.
