### ISSUE TITLE
Whonix-gw/ws and problems with qubes.UpdatesProxy

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#4307] opened 2018-09-13 16:14 UTC
### Actual behavior:
I have a Whonix template restored from a backup from Qubes R4. I have the latest Qubes OS R4. I have set whonix-gw / ws -> sys-whonix-s -> sys-firewall-s -> sys-net-s.

In /etc/qubes-rpc/policy/qubes.UpdatesProxy, I have a set of default values for ordinary templates, and among others
$tag:whonix-updatevm $default allow,target=sys-whonix-s
$tag:whonix-updatevm $anyvm deny

Anyway, when I try to update whonix-ws / gw, whonix shows me the information that qubes proxy is not set.
Maybe for the correct operation of whonix I need to edit some additional files?
In qvm-tags whonix-gw / ws, I have "whonix-updatevm".

For example in "sys-whonix-s" is internet.

### General notes:
I have a version of whonix 14

As a last resort, I will probably need to delete (https://www.whonix.org/wiki/Qubes/Uninstall) template whonix and reinstall (https://www.whonix.org/wiki/Qubes/Install) with the command "sudo qubesctl state .sls qvm.anon-whonix "

**Comment by andrewdavidwong** [comment] 2018-09-14 01:29
Duplicate of #4167

**Comment by andrewdavidwong** [comment] 2018-09-14 01:29
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-09-14 01:29 UTC

**Comment by toxub23** [comment] 2018-09-18 17:41
Of course, I closed that topic and did not open it again, I had to create a new one because I also added new information in "General notes"

**Comment by andrewdavidwong** [comment] 2018-09-19 07:13
> Of course, I closed that topic and did not open it again, I had to create a new one because I also added new information in "General notes"

You are not using the issue tracker correctly. Please see:

https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues

I've reopened #4167. Please add your new information there as a comment.
