### ISSUE TITLE
Expanding Horizons: The Benefits of AArch64 Compatibility for Qubes OS

### ISSUE THREAD

**Issue by alexandresantosal91** [QubesOS/qubes-issues#8545] opened 2023-09-22 13:31 UTC
Introduction

In recent years, machines with AArch64 architecture have gained prominence in the technological scene, thanks to their power and efficiency. However, an important gap has limited the adoption of Qubes OS in this hardware segment. This text explores the benefits of extending Qubes OS support to AArch64 machines, presenting the problem, the desired solution, and the added value for users.

The problem

Currently, Qubes OS does not natively support the AArch64 architecture, limiting its use to x86_64 systems. This excludes a growing segment of users who have powerful AArch64 hardware and want to enjoy the security and isolation benefits offered by Qubes OS.

The solution

The solution to this problem is clear and valuable: Qubes OS should expand its compatibility to include AArch64 systems, allowing owners of machines with this architecture to enjoy all the benefits that Qubes OS offers in terms of security and system isolation.

The Value for Users

The main beneficiaries of this compatibility expansion would be users who have AArch64 machines. They could install Qubes OS on their systems, taking advantage of advanced security and environment isolation, regardless of their hardware architecture.

This extended compatibility would also be useful for organizations and enterprises looking to adopt Qubes OS in infrastructures using AArch64 hardware. Additionally, AArch64 support would open doors to a more diverse community of developers and contributors, further expanding the potential for innovation and improvement of the system.

Conclusion

The addition of AArch64 support to Qubes OS represents a significant opportunity to expand its reach and provide advanced security to a growing group of users. By overcoming the current limitation, Qubes OS would become a more affordable and attractive choice for those who have AArch64-based hardware. This way, the system could continue to be a leader in the field of cybersecurity and maintain its reputation for offering a highly secure and isolated computing environment.

#QubesOS #AArch64#security #isolation #community

**Comment by andrewdavidwong** [comment] 2023-09-22 19:17
Duplicate of #7476

**Comment by andrewdavidwong** [comment] 2023-09-22 19:17
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-09-22 19:17 UTC
Labels: T: enhancement, P: default
