### ISSUE TITLE
qubes-core-agent-networking & -network-manager still depend on iptables

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8346] opened 2023-07-09 19:53 UTC
### Qubes OS release

4.2

### Brief summary

According to #5031 qubes should have no dependency on iptables(?), but `qubes-core-agent-networking` & `qubes-core-agent-network-manager` showing they are still calling iptables

```
root@debian:~# apt remove --purge iptable*
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'iptables' for glob 'iptable*'
Note, selecting 'iptables-netflow-dkms' for glob 'iptable*'
Note, selecting 'iptables-nftables-compat' for glob 'iptable*'
Note, selecting 'iptables-persistent' for glob 'iptable*'
Package 'iptables-nftables-compat' is not installed, so not removed
Package 'iptables-persistent' is not installed, so not removed
Package 'iptables-netflow-dkms' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  conntrack libayatana-appindicator3-1 libayatana-ido3-0.4-0
  libayatana-indicator3-7 libdbusmenu-glib4 libdbusmenu-gtk3-4 libgck-1-0
  libgcr-base-3-1 libip6tc2 libnetfilter-conntrack3 libnfnetlink0
  libnma-common libnma0 network-manager-gnome socat tinyproxy tinyproxy-bin
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  iptables* qubes-core-agent-network-manager* qubes-core-agent-networking*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 2,612 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
root@debian:~# 
```

**Comment by andrewdavidwong** [comment] 2023-07-10 11:30
Duplicate of #5031

**Comment by andrewdavidwong** [comment] 2023-07-10 11:30
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-07-10 11:30 UTC
Labels: T: bug, R: duplicate, P: default
