### ISSUE TITLE
New device attach menu in 4.2 is missing useful information about block devices

### ISSUE THREAD

**Issue by kord1e** [QubesOS/qubes-issues#9201] opened 2024-05-09 09:37 UTC
### The problem you're addressing (if any)

The menu where you can attach block devices and other devices to VMs doesn't show the block device identifier, e.g. sda, sdb, sde1, anymore. It only shows the device model, which is useless in many cases, and the volume label which is useful, but devices do not always have a label.

### The solution you'd like

In 4.1 it showed the identifier e.g. sda2, as well. 

### The value to a user, and who that user might be

Anyone who needs to attach many hard drives to VMs.

**Comment by UndeadDevel** [comment] 2024-05-09 10:01
Duplicate of #9164

**Closed** 2024-05-10 07:18 UTC
Labels: R: duplicate, T: enhancement, P: default
