### ISSUE TITLE
System freeze immediately after dom0 update to Xen 2001:4.14.5-5

### ISSUE THREAD

**Issue by SvenSemmler** [QubesOS/qubes-issues#7618] opened 2022-07-15 17:56 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1 (stable, no testing) ... updated every 1-2 days.

### Brief summary

My system froze immediately after dom0 update today. 

Packages updates: python3-xen, xen, xen-hypervisor, xen-libs, xen-licenses, xen-runtime. From 2001:4.14.5-4.fc32 to 2001:4.14.5-5.fc32 

Screenshot attached. While there are several members complaining about freezing issues with Qubes OS updates in general in the forum, my machine has been rock stable on R4.1. So this is unusal. After reboot there seem to be no issues. Not sure you can do anything about this or if it will hit more people... but I thought I should at least report it.

### Steps to reproduce

qvm-shutdown --all --wait
qvm-start sys-net sys-firewall sys-usb
sudo qubesctl --show-output state.sls update.qubes-dom0

... this is happening within a batch script. So I don't know if the last line above or the one that follows caused the freeze. The one that folllows is:

sudo qubesctl --show-output --skip-dom0 --templates --max-concurrency=1 state.sls update.qubes-vm

All templates are debian-11-minimal based, except one fedora-33 template.

### Expected behavior

qubesctl updates all templates

### Actual behavior

freeze 
![IMG_0045](https://user-images.githubusercontent.com/16354196/179283202-d36f35e9-c592-4df4-849c-29ece644fd53.jpg)

**Comment by andrewdavidwong** [comment] 2022-07-15 23:10
This certainly shouldn't happen with only stable (no testing) updates.

Looks like there was a typo in the version number in the title (major number was "15" instead of "14"), so I've fixed that.

I wanted to check to see if this update was the one associated with [QSB-083](https://www.qubes-os.org/news/2022/07/13/qsb-083/), but I see that QSB-083's Xen packages are version "4.14.5-**6**", whereas yours are "4.14.5-**5**". I'm not sure if that makes a difference, but do you have any newer updates available?

**Comment by SvenSemmler** [comment] 2022-07-16 04:02
Thanks for fixing the typo @adw. No, after this update I have no other updates pending in dom0 and as I wrote everything works fine after rebooting. The QSB related update would be in testing now, that's why I don't see it on stable.

Anyway, if no one else sees the same thing I think we can blame my hardware or specific configuration and move on. Some recent forum posts talk about freezing when updating as kind of a regular thing and I posted there that I do not see this. 20 minutes later I experienced this issue and kind of felt I should document it if only to separate it from the more general observation of others.

**Comment by DemiMarie** [comment] 2022-07-16 10:00
@SvenSemmler Do you have this problem with the testing updates?

**Comment by jevank** [comment] 2022-07-16 10:15
I have similar hang once while testing xen-4.14.5-5 on qvm-template downloading. My thoughts ware about memory problems with hardware.

**Comment by brendanhoar** [comment] 2022-07-16 10:22
I'm a bit confused. 

Based on the ticket title @SvenSemmler said freeze was immediately after dom0 Xen update, but when dom0's Xen component is updated, it isn't used until the next reboot.

So the freeze could not be caused by Xen, correct?

B

**Comment by SvenSemmler** [comment] 2022-07-16 19:52
> Do you have this problem with the testing updates?

I saw this once on an otherwise extremely stable machine (no issues at all since R4.1). My T430 is equivalent to a certified machine (NitroPad T430). I never use testing on it, only stable.

I have a second identical machine, that wasn't used / updated for ~ 1 month. Before I try to reproduce it on that machine, are there any specific things you would like me to do / prepare? On that machine I can also do experiments using testing or security-testing if you'd like.

> freeze was immediately after dom0 Xen update, but when dom0's Xen component is updated, it isn't used until the next reboot. So the freeze could not be caused by Xen, correct?

Good point. After the freeze I restarted the machine and restarted the batch script which first attempts dom0 updates and then template updates. This time it completed all updates without freeze. That's why I thought it wasn't the template updates, otherwise it should have frozen again -- right?

However, this kind of thing used to happen all the time with 5.4 kernel, which is why I stayed with 4.19 on R4.0. With R4.1 and the 5.10 kernel I haven't seen any issues until now.

So again: I have a second identical computer, also on stable that is off for about 1 month. I can just start it and run update and see what happens. I haven't done so yet, because there may be things you'd like me to do before trying this.

**Comment by SvenSemmler** [comment] 2022-07-18 23:18
Update: had another freeze today, this time when updating a template. So this might not be related to a dom0 update as pointed out by @brendanhoar. 

@andrewdavidwong from my point of view I'd prefer closing this issue for now as the description / observation is off the mark and potentially confusing. My system management qube is based on debian-11-minimal as are (most) of my other templates. I am currently downloading fedora-36 and will base the system management qube of it. 

Then depending on what happens I will create a new issue pointing either at salt-based updates in general or salt-based updates using debian-11-minimal in particular. I am sad to say that I appear to have joined the ranks of users observing general issues with updating but have the hope that it might have something to do with my custom templates. Hence the experiment with fedora-36.

Please advice how you want this to be handled (close & open new one or extending / correcting this issue description).

**Comment by andrewdavidwong** [comment] 2022-07-19 01:03
> @andrewdavidwong from my point of view I'd prefer closing this issue for now as the description / observation is off the mark and potentially confusing. My system management qube is based on debian-11-minimal as are (most) of my other templates. I am currently downloading fedora-36 and will base the system management qube of it.
> 
> Then depending on what happens I will create a new issue pointing either at salt-based updates in general or salt-based updates using debian-11-minimal in particular. I am sad to say that I appear to have joined the ranks of users observing general issues with updating but have the hope that it might have something to do with my custom templates. Hence the experiment with fedora-36.
> 
> Please advice how you want this to be handled (close & open new one or extending / correcting this issue description).

That sounds fine. Closing this one.

**Closed by andrewdavidwong** 2022-07-19 01:03 UTC
Labels: T: bug, C: Xen, P: default, hardware support, needs diagnosis
