### ISSUE TITLE
templates should have prefix "Template:" not "Domain:" in start menu 4.0-rc2

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#3252] opened 2017-10-28 19:46 UTC
#### Qubes OS version:

R4.0-rc2

---

### Steps to reproduce the behavior:

Look at the app/start menu in 4.0-rc2.

### Expected behavior:

a template like fedora 25 should be listed "Template: Fedora 25" in a separate section from the domains. This is how it is in 3.2.

### Actual behavior:

a template like fedora 25 is listed as "Domain: Fedora 25" and mixed together with app domains.

### Related issues
Having a "Service" category like in 3.2 may also make sense for ServiceVMs.

**Comment by andrewdavidwong** [comment] 2017-10-28 19:49
This appears to be a duplicate of #3107. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-10-28 19:49 UTC

**Comment by mfc** [comment] 2017-10-28 19:56
well that is focused on "Service:" which I mention in the related issues but I will contribute to the discussion there.

**Comment by andrewdavidwong** [comment] 2017-10-28 20:00
If you read the comments on that issue, you will see that @marmarek also asked about `Domain:` and `Template:`, so the issue topic is actually broader that its title might suggest.
