### ISSUE TITLE
GPG Dialog Squished

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5730] opened 2020-03-15 18:17 UTC
**Qubes OS version**
I don't know bcuz that CLI syntax below in a dom0 terminal gave me nothing. It's the customized install from FPF for the SecureDrop Workstation. :D
> _The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._ 

**Affected component(s) or functionality**
GPG question dialog

**Brief summary**
Hey guys! I know I discussed this with Marta, and I'd thought I'd filed an issue a while ago... but I cannot find any such issue. Anywho—I'm still seeing the below, as how the window loads by default... :((
 
![image](https://user-images.githubusercontent.com/8262612/76691070-f33cbb00-6603-11ea-9e4a-c950a1b7468e.png)

**Comment by marmarek** [comment] 2020-03-15 22:04
Duplicate of #5513

**Closed by marmarek** 2020-03-15 22:04 UTC
Labels: P: default, T: bug

**Comment by ninavizz** [comment] 2020-03-16 16:15
Apologies for the duplicate! I did try to find #5513 via search queries, and GitHub failed. I swear, I even executed a query with "squished" in it... and got nothing. 

Any ETA on the release of 4.1?
