### ISSUE TITLE
Qubes Manager - About still says Qubes 4.0 R4 after updating dom0 from current-testing

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3679] opened 2018-03-08 21:21 UTC
#### Qubes OS version:

Qubes 4.0

#### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

Update dom0 with the current-testing repository enabled.

Reboot system

Click on Qubes Manager - About 

Tells you the system is Qubes 4.0 R4 instead of Qubes 4.0 R5

### Expected behavior:

About reflects the latest Release candidate version number 

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-03-09 02:24
Duplicate of #3671

**Comment by andrewdavidwong** [comment] 2018-03-09 02:24
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-09 02:24 UTC
