### ISSUE TITLE
After upgrade to R4.0, unusable on Lenovo Thinkpad Edge E560

### ISSUE THREAD

**Issue by pierwill** [QubesOS/qubes-issues#4268] opened 2018-09-01 20:50 UTC
I used to run Qubes R3.2 on a Lenovo ThinkPad Edge E560 15.6" HD Screen, Intel Dual Core i5-6200U 2.3 GHz, 16GB RAM, 240GB Solid State Drive, W7P / W10P. 

I had no major problems at all. Qubes ran great.

After upgrading to R4.0, things became so slow that it was unusable. I re-installed multiple times, fiddling with BIOS settings. The OS installs successfully, but things chug along, stall, and quit as if the machine suddenly had 500MB of RAM instead of 16GB.

Just wanted to let the team know in case this information is useful at all. I can provide more info if needed.

**Comment by andrewdavidwong** [comment] 2018-09-01 20:59
Duplicate of #3639

**Comment by andrewdavidwong** [comment] 2018-09-01 20:59
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-09-01 20:59 UTC
