### ISSUE TITLE
Start failed: internal error: libxenlight failed to create new domain 'sys-net'

### ISSUE THREAD

**Issue by entruevz** [QubesOS/qubes-issues#5448] opened 2019-11-06 19:46 UTC
**Qubes OS version**
_4.0.1, 4.0.2-rc2._

**Affected component(s) or functionality**
_PCI / VM sys-net._

**Brief summary**
_The VM sys-net as well as sys-firewall and sys-whonix refuses to start, both at system startup and manually with Qubes Manager.._

**Actual behavior**
_The following message appears when I try to start the VM from Qubes manager: 
`Start failed: internal error: libxenlight failed to create new domain 'sys-net'`._

**Additional context**
_qvm-start told me to look at /var/log/libvirt/libxl/libxl-driver.log:
`libxl: libxl_device.c:1385:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/2/0 not ready
libxl: libxl_pci.c:1361:libxl__add_pcidevs: libxl_device_pci_add failed: -3
libxl: libxl_create.c:1512:domcreate_attach_devices: unable to add pci devices
libxl: libxl_device.c:1385:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/2/0 not ready
libxl: libxl_linux.c:155:libxl__loopdev_cleanup: unable to release device /dev/loop0: No such device or address
libxl: libxl_pci.c:1199:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0
libxl: libxl_device.c:1385:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/4/0 not ready
libxl: libxl_pci.c:1361:libxl__add_pcidevs: libxl_device_pci_add failed: -3
libxl: libxl_create.c:1512:domcreate_attach_devices: unable to add pci devices
libxl: libxl_pci.c:1199:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0
libxl: libxl_device.c:1385:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/4/0 not ready
libxl: libxl_linux.c:155:libxl__loopdev_cleanup: unable to release device /dev/loop0: No such device or address
libxl: libxl_device.c:1385:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/6/0 not ready
libxl: libxl_pci.c:1361:libxl__add_pcidevs: libxl_device_pci_add failed: -3
libxl: libxl_create.c:1512:domcreate_attach_devices: unable to add pci devices
libxl: libxl_device.c:1385:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/6/0 not ready
libxl: libxl_linux.c:155:libxl__loopdev_cleanup: unable to release device /dev/loop0: No such device or address`._

Laptop model and version: Librem 13 Version 4 (which is supposed to work with Qubes Os)
My wifi card model: 
`01:00.0 Network controller: Qualcomm Atheros AR9462 Wireless Network Adapter (rev 01)`
With the stable version it worked 1 time out of 4, if the vm did not start I would restart the machine and the vm may or may not start. (and so I could use NetworkManager). 
With the testing version it worked after installation but now even after about twenty restarts, sys-net refuses to launch.
 
**Solutions you've tried**
_I tried the stable and testing version..
I changed the fedora template to debian_

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_
https://github.com/QubesOS/qubes-issues/issues/3125 (VT-x is enabled..)
.

**Comment by marmarek** [comment] 2019-11-06 20:17
Duplicate of #5445

**Comment by marmarek** [comment] 2019-11-06 20:17
Specifically see there for a question for more logs.

**Closed by marmarek** 2019-11-06 20:17 UTC
Labels: P: default, T: bug

**Comment by entruevz** [comment] 2019-11-06 21:07
Strangely, after restarting my computer, sys-net started and I have access to the Internet.
After verification, 0000:00:14.0 and 0000:00:14.1 match my usb ports. The problem does not come from there because sys-usb starts without any problem

What can I provide you with as a log? I would really like to be able to use Qubes-Os every time I start my computer.

**Comment by entruevz** [comment] 2019-11-06 21:28
# lspci -v
`        01:00.0 Network controller: Qualcomm Atheros AR9462 Wireless Network Adapter (rev 01)
	Subsystem: Lite-On Communications Inc Device 0802
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d1200000 (64-bit, non-prefetchable) [size=512K]
	Expansion ROM at d1280000 [disabled] [size=64K]
	Capabilities: [40] Power Management version 2
	Capabilities: [50] MSI: Enable- Count=1/4 Maskable+ 64bit+
	Capabilities: [70] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Virtual Channel
	Capabilities: [160] Device Serial Number 00-00-00-00-00-00-00-00
	Kernel driver in use: pciback
	Kernel modules: ath9k`

# journalctl | grep 01:00.0
`Nov 06 18:18:45 dom0 kernel: pci 0000:01:00.0: [168c:0034] type 00 class 0x028000
Nov 06 18:18:45 dom0 kernel: pci 0000:01:00.0: reg 0x10: [mem 0xd1200000-0xd127ffff 64bit]
Nov 06 18:18:45 dom0 kernel: pci 0000:01:00.0: reg 0x30: [mem 0xd1280000-0xd128ffff pref]
Nov 06 18:18:45 dom0 kernel: pci 0000:01:00.0: supports D1 D2
Nov 06 18:18:45 dom0 kernel: pci 0000:01:00.0: PME# supported from D0 D1 D2 D3hot D3cold
Nov 06 18:18:45 dom0 kernel: pciback 0000:01:00.0: seizing device
Nov 06 18:20:08 dom0 kernel: xen_pciback: vpci: 0000:01:00.0: assign to virtual slot 0
Nov 06 18:20:08 dom0 kernel: pciback 0000:01:00.0: registering for 4
Nov 06 18:20:33 dom0 kernel: xen_pciback: vpci: 0000:01:00.0: assign to virtual slot 0
Nov 06 18:20:33 dom0 kernel: pciback 0000:01:00.0: registering for 6
Nov 06 18:20:58 dom0 kernel: xen_pciback: vpci: 0000:01:00.0: assign to virtual slot 0
Nov 06 18:20:58 dom0 kernel: pciback 0000:01:00.0: registering for 8
Nov 06 18:23:14 dom0 kernel: xen_pciback: vpci: 0000:01:00.0: assign to virtual slot 0
Nov 06 18:23:14 dom0 kernel: pciback 0000:01:00.0: registering for 10
Nov 06 18:24:15 dom0 kernel: xen_pciback: vpci: 0000:01:00.0: assign to virtual slot 0
Nov 06 18:24:15 dom0 kernel: pciback 0000:01:00.0: registering for 12
`

**Comment by entruevz** [comment] 2019-11-07 14:54
To be able to launch the sys-net vm, I had to disable all vms started at startup (including sys-net so sys-whonix, sys-firewall, and even sys-usb).
After unlocking my user session, I am able to run sys-net manually without getting this error message: "Domain sys-net has failed to start: internal error: libxenlight failed to create new domain 'sys-net".
Then simply create a script that launches the desired vms at startup.
I guarantee to provide the logs that may be necessary to understand and correct the problem.

**Comment by andrewdavidwong** [comment] 2019-11-08 04:17
@entruevz, this issue has been closed as a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #5443. Please comment on that issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by stman** [comment] 2021-08-20 15:30
Well, with a MacBookPro Retina 15" mid-2012 (Macbookpro 10,1 - with EFI ROM : MBP101.00EE.B0B) I have the exact same problem as you do, the same logs.

I can't detach the USB controller in PCI 0000:00:14.0 that handles the two external USB Ports of the MacBookPro (There are 3 USB controllers listed in the macbookpro motherboard) from dom0 to attach it to my `sys-usb` qube and be able to handle networking thanks to this.

This is really terrible and raging.

I saw the other topic #5445 and no solution was found.

If you have a way to correct this small error, because it must be a very simple misconfiguration somewhere, please let me know because it is raging not to be able to make Qubes-OS run on this damned macbookpro just for this.
