### ISSUE TITLE
color of icons in apps.icons/ isn't updated when changing vm label

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#1606] opened 2016-01-12 07:54 UTC
Minor issue: in R3.1rc, when changing a vm label (say, "banking" from green to yellow), the icons in /var/lib/qubes/appvms/banking/apps.icons/ aren't updated to the new color (confirmed by opening them in an image viewer, they're still green, so it's not a caching issue).
Consequence: anything that uses the apps' .desktop definitions still show the old label/color. For instance sub-entries of "Domain: banking" in xfce's menu are still green  (firefox, files, ...) (the "root" entry in the menu properly displays a yellow padlock though).

**Comment by axon-qubes** [comment] 2016-03-13 17:07
Is this a dupe of #751?

Anyway, confirmed on R3.1 stable. Steps to reproduce (same as past stable Qubes releases):

1. Create a green AppVM.
2. Change it to gray.
3. `qvm-sync-appmenus`, host reboot, etc.
4. Color of "menu" lock icon changed to gray, but all specific application icons in the menu are still green.

**Closed** 2016-04-19 21:27 UTC
Labels: bug, C: core, C: desktop-linux, P: minor

**Comment by marmarek** [comment] 2016-05-17 22:11
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.11-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/f44b268299957463172109081351d753f53c930b...58c3f2221fb55b4471192c6199c571c920035f97

**Comment by taradiddles** [comment] 2016-06-10 19:29
Sorry to write on a closed issue, I should have tested the rpm while it was in the testing repo...
Maybe I'm doing something wrong, but it looks like the issue isn't fully solved:
- create an orange vm ; /var/lib/qubes/appsvm/vmname/apps.icons/firefox.jpg is orange
- then change it to gray ; /var/lib/qubes/appsvm/vmname/apps.icons/firefox.jpg is still orange (same file/modification time as before).

but - running "add more shortcuts" from the menu, modifying a shortcut to have something changed and clicking OK, and the icons' color is then updated to gray.

**Comment by marmarek** [comment] 2016-07-25 11:05
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.12-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/f44b268299957463172109081351d753f53c930b...f5ad47b73fc0169fbeb51d1a96efc6d5ef5afc61
