### ISSUE TITLE
4.1.0-rc3: Guest "Windows10-HVM" window disappears in Fullscreen Mode

### ISSUE THREAD

**Issue by mero-ber** [QubesOS/qubes-issues#7156] opened 2021-12-26 12:32 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.0-rc3

### Brief summary
Guest "Windows10-HVM" window disappears when Fullscreen Mode is enabled.

### Steps to reproduce
- Installing Qubes 4.1.0-rc3 (HW: MinisForum HX90)
- Installing Windows 10 and updates
- Set the Windows screen resolution to DOM:Display resolution (1929x1200)
- Activate Fullscreen Mode or ALT-F11 on the Windows10 guest.

There are no Qubes Windows Tools installed.

guest-Win10-dm.log: 
...
[2021-12-26 10:42:57] qubes_gui: got unkonwn msg type 127, ignoring
[2021-12-26 10:43:02] qubes_gui: got unkonwn msg type 127, ignoring
[2021-12-26 10:43:02] qubes_gui: got unkonwn msg type 145, ignoring
[2021-12-26 10:43:02] BUG: qubes_gui: got unkown msg type 145, but not ignored earlier
[2021-12-26 10:43:02] br0: port 2(vif62.0-emu) entered disabled state
...

### Expected behavior
Guest OS in fullscreen mode

### Actual behavior
"Windows10-HVM" window disappears

Guest OS have running State

**Comment by fepitre** [comment] 2021-12-26 14:52
Duplicate of: https://github.com/QubesOS/qubes-issues/issues/7148

**Closed by fepitre** 2021-12-26 14:52 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2021-12-26 19:48
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
