### ISSUE TITLE
Firewall: temporary full network access does not expire at the end of specified period

### ISSUE THREAD

**Issue by tomaskrizek** [QubesOS/qubes-issues#2423] opened 2016-11-07 20:56 UTC
#### Qubes OS version (e.g., `R3.1`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
not applicable

---

### Expected behavior:
When a temporary full network access is configured for a given time in Firwall Rules for a VM in Qubes VM Manager, the firewall should be turned back on again after the time elapses.
### Actual behavior:
After the time elapses, the VM still has full network access until it is restarted.
### Steps to reproduce the behavior:

1. Check VM has no network access.
2. Configure `Allow full access` for 1 minute.
3. Verify VM can access network.
4. Wait for more than a minute.
5. Verify VM can still access network.

**Comment by unman** [comment] 2016-11-08 00:47
Duplicate of  #1173

**Closed** 2016-11-08 09:04 UTC
Labels: duplicate
