### ISSUE TITLE
qvm-device pci fails on non-ASCII PCI IDs

### ISSUE THREAD

**Issue by Galland** [QubesOS/qubes-issues#4229] opened 2018-08-21 00:31 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-admin / qvm-device 

---

### Steps to reproduce the behavior:

Stock Qubes 4.0 just installed and applied updates. I can't access devices for sys-usb.
I then open a Dom0 terminal and type:

```sudo qvm-device pci list sys-usb```

and get: "Got empty response from qubesd"
By looking at last entries on journalctl there is:

```
Aug 21 02:14:21 dom0 qubesd[1832]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.pci.Available' dest=b'dom0' arg=b'' len(untrusted_payload)=0
Aug 21 02:14:21 dom0 qubesd[1832]: Traceback (most recent call last):
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Aug 21 02:14:21 dom0 qubesd[1832]:     untrusted_payload=untrusted_payload)
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Aug 21 02:14:21 dom0 qubesd[1832]:     yield self  # This tells Task to wait for completion.
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Aug 21 02:14:21 dom0 qubesd[1832]:     future.result()
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Aug 21 02:14:21 dom0 qubesd[1832]:     raise self._exception
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Aug 21 02:14:21 dom0 qubesd[1832]:     result = coro.send(None)
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Aug 21 02:14:21 dom0 qubesd[1832]:     res = func(*args, **kw)
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1134, in vm_device_available
Aug 21 02:14:21 dom0 qubesd[1832]:     (('description', dev.description),)
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib/python3.5/site-packages/qubes/ext/pci.py", line 161, in description
Aug 21 02:14:21 dom0 qubesd[1832]:     hostdev_details.XMLDesc()))
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib/python3.5/site-packages/qubes/ext/pci.py", line 122, in _device_desc
Aug 21 02:14:21 dom0 qubesd[1832]:     devclass=pcidev_class(hostdev_xml),
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib/python3.5/site-packages/qubes/ext/pci.py", line 80, in pcidev_class
Aug 21 02:14:21 dom0 qubesd[1832]:     qubes.ext.pci.pci_classes = load_pci_classes()
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib/python3.5/site-packages/qubes/ext/pci.py", line 48, in load_pci_classes
Aug 21 02:14:21 dom0 qubesd[1832]:     for line in pciids.readlines():
Aug 21 02:14:21 dom0 qubesd[1832]:   File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
Aug 21 02:14:21 dom0 qubesd[1832]:     return codecs.ascii_decode(input, self.errors)[0]
Aug 21 02:14:21 dom0 qubesd[1832]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2243: ordinal not in range(128)
```

### General notes:

Looking into the pci.py I see the file that contains non-ASCII chars is /usr/share/hwdata/pci.ids

And looking for non ASCII chars with:
```grep --color='auto' -P -n "[\x80-\xFF]" /usr/share/hwdata/pci.ids```

I get:
```
2186:		1787 201c  HD 7970 IceQ X²
2247:		1787 2020  R9 290X IceQ X² Turbo
3021:		1002 0b12  Radeon X1800 GTO²
18997:		103c 1627  AR9380/HB112 802.11abgn 3×3 Wi-Fi Adapter
19004:		103c 1838  AR9485/HB125 802.11bgn 1×1 Wi-Fi Adapter
```

The culprit chars are the squares (2) symbols and the fake "x" ones.

---

**Comment by SaswatPadhi** [comment] 2021-06-21 02:29
Just stumbled upon this issue.

The fix appears to be working as intended. We can probably close this issue.

**Comment by andrewdavidwong** [comment] 2021-06-21 02:48
> Just stumbled upon this issue.
> 
> The fix appears to be working as intended. We can probably close this issue.

Thank you for the update. Closing as resolved. If anyone believes the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-06-21 02:48 UTC
Labels: C: core, T: bug
