### ISSUE TITLE
Qubes R4.0 windows tools seamless mode not working

### ISSUE THREAD

**Issue by michaljenicek** [QubesOS/qubes-issues#4656] opened 2018-12-24 15:03 UTC
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Qubes windows tools, seamless mode

---

### Steps to reproduce the behavior:

I followed the instructions for installing a [Windows VM](https://www.qubes-os.org/doc/windows-vm/#qubes-40---windows-vm-installation), I had it working without issues, then I followed the instructions for install [windows tools](https://github.com/QubesOS/qubes-issues/issues/3585) and installed those without issues as well. All the windows apps appear in the qubes menu, but I'm unable to start any app in the seamless mode.

I know for a fact, that the seamless mode is working, because one time a windows notification for the action center appeared in qubes, and after clicking that notification the action center opened in seamless mode. The problem is, I'm unable to start any application.

I'm having the similar problems as described [here](https://www.reddit.com/r/Qubes/comments/8drcz5/qubes_4_win7_seamless_mode_does_it_work/) and [here](https://groups.google.com/forum/#!topic/qubes-users/pPZlXuz4bNc).

I tried:

- starting apps from the qubes menu
- starting apps from the command line (e.g. qvm-run -a win7 explorer.exe)
- refreshing the applications list in qubes VM settings

When I attempt to start an app, the VM starts (green dot) but the app doesn't start.

### Expected behavior:

To start the app in a seamless mode.

### Actual behavior:

Nothing happens, only the VM starts if it hasn't started already.

### General notes:

I'm new to Qubes, but I already managed to get the seamless mode working in the past on my previous laptop in Qubes 3, I'd be grateful for any help.

---

### Related issues:

https://www.reddit.com/r/Qubes/comments/8drcz5/qubes_4_win7_seamless_mode_does_it_work/
https://groups.google.com/forum/#!topic/qubes-users/pPZlXuz4bNc

**Comment by andrewdavidwong** [comment] 2018-12-25 02:04
Duplicate of #3585

**Comment by andrewdavidwong** [comment] 2018-12-25 02:04
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-12-25 02:04 UTC
