### ISSUE TITLE
Qubes 4.1.1 intermittently fails to enter sleep correctly

### ISSUE THREAD

**Issue by tetrahedras** [QubesOS/qubes-issues#7910] opened 2022-11-24 16:53 UTC
### Qubes OS release
4.1.1.

### Brief summary
I am using an X230. When closing the lid, Qubes usually goes to sleep normally. Occasionally (20-40% of the time) it does not.

When it fails to enter sleep correctly:
- the display is black, but backlight is on
- the power LED is pulsing, indicating sleep mode
- the system is running at full power
- if the lid is left closed, the fans eventually start running at full power due to CPU heating
- opening the lid, nothing happens (the system does not show the Xscreensaver unlock dialog)
- the system is entirely unresponsive to keystrokes or mouse

In this case, the only resolution is forced shut down of the system (removing battery or long-press the power button until power off). If the laptop is not forcibly shut off, it will eventually run out of battery and die that way.

The behaviour could be (but may not necessarily be) related to:
1. the system going to sleep for a longer time
2. the physical laptop being moved around in my bag, triggering a wake from sleep if the lid switch is accidentally triggered, and then a sleep command again as the switch is reset by normal motion
I have not yet been able to rule out either of these.

This may be related to #7611 and #7340 and #6923, I am still investigating.

### Steps to reproduce
Carry the laptop during daily errands, putting it to sleep and waking it up repeatedly (?).

### Expected behavior
Laptop goes to sleep and wakes up normally

### Actual behavior
Laptop stays stuck in a mode somewhere between sleep and normal operation, consuming battery until the battery (and laptop) dies.

**Comment by tlaurion** [comment] 2022-11-26 16:49
Not using sleep a lot here, but I experienced this regression once in the last week myself.

Running on stable repo.

**Comment by andrewdavidwong** [comment] 2022-11-29 01:08
Is this a duplicate of #7904?

**Comment by isodude** [comment] 2022-12-03 13:43
> Is this a duplicate of #7904?

Don't think so, not an AMD system?
https://www.lenovo.com/se/sv/laptops/thinkpad/x-series/x230/?orgRef=https%253A%252F%252Fwww.google.se%252F

**Comment by isodude** [comment] 2022-12-03 14:10
There are a couple of simpme ways to pinpoint which part it's stuck in.

*Does FnLock work?*
If not that means the hardware is completely dead and linux is not running anymore.

*Indicator lamp is glowing steadliy when suspending*
Some part of the laptop is not responding to suspend properly, there should be some log about that

*Indicator lamp is in sleep state even though unsuspend is activated*
Probably when entering sleep it entered a failed state, it should be possible to do pm_debug to see what this state is. I guess that this also could mean that some component is not reacting when called to wake up. Usually related to specific laptop models which need quirks or components (like ssds) that need a firmware update.

*Black sceeen*
GPU drivers most likely failed to initialize the display, this far it could either be that just that port failed or that the drivers just bailed out. Sometimes suspending and unsuspending can take you put of the loop. Also using some kind of magic sysrq maybe to kill X11 to reset the gpu might work. But most likey GPU drivers are to blaim, which also means that you need to experiment with different linux-firmware releases, if those were upgraded.

*Gray screen, screen is activated but not reacting*
Here it's a couple of options, if no mouse pointer is showing the GPU was initialized but X was completely hanged. Maybe look at the x11-driver. If there's a mouse pointer but it can't be moved, there's early in X11 were the problem is, if the mouse is movable (and problaby just withing the login window) X11 should be fine (there's a great post about this I should dig up). It might be possible to actually type in the password here and get it to work. From what I can tell runnig with AccelMethod=None in xorg.conf can ease problems here since it's less code that should be handled. (Shaders etc.)

Sorry about the long post, we should probably start a wiki entry where this kind of diagnostic is better linked. There are loads of tips and tricks all from pm_debug to drm_debug and pci=nomsi etc. With intel there are some xen options that could make a difference.

*Potential quick fix*
I guess you can change the behavior as well, do not resume on lid open, and then suspend with click on the power button. I think you choose that in BIOS?

**Comment by isodude** [comment] 2022-12-03 14:17
https://linux-kernel.vger.kernel.narkive.com/ulG2HedP/git-pull-libata-fixes-for-v3-13-rc5

This is an old issue, it seems that there are some new bugs around this as well. But as an example, some component entered a deadlock. Removing the DVD drive made the problem go away.

**Comment by isodude** [comment] 2022-12-03 14:22
https://www.reddit.com/r/thinkpad/comments/a1mai6/how_to_fix_thinkpad_x230_fails_to_enter_sleep/

Wifi card seems like a nice culprit, since it could be quite random. Could even be just badly seated or something like that.

**Comment by isodude** [comment] 2022-12-03 14:26
> After about 4 times of disassembly, it finally booted. Changing the paste helped fix the shutdown problem, and interestingly, the sleeping problem too was fixed.

First time I read this but wow, how could thermal paste affect shutdown problems :(

**Comment by tetrahedras** [comment] 2022-12-05 19:30
@isodude: Thanks for that. Some observations:

- the power LED ring around the power button dims and gets brighter, so
   sleep mode is halfway there.

- indicator lamp is in sleep state even though unsuspend is activated:
   yes, this is what happens. How do we enable PM_DEBUG on Qubes?

- black screen/grey screen: yes, the screen is always dark, often with the
   backlight still on. (this is considered grey screen?) No mouse
   pointer, but there is normally no mouse pointer with
   xcreensaver/xlock.
  
- wifi card: could be. There is a related issue where the WiFi card
   fails to come up after sleep (#5508 and potentially #4658).

- thermal paste: seems unlikely since a recent software
   upgrade appears to have affected the behaviour.

**Comment by tetrahedras** [comment] 2022-12-05 19:34
On Mon, Nov 28, 2022 at 05:08:24PM -0800, Andrew David Wong wrote:
>Is this a duplicate of #7904?

I'm not sure yet. It looks very similar, but in my case it's not at all
deterministic (it does not happen every time, unlike #7904). This is
also an issue I have seen occasionally since I started using Qubes. What
happend after the last upgrade is it became much more frequent.

I have been experimenting with a potential workaround: shutting down all
VMs (`qvm-shutdown --wait --all`) before putting my laptop to sleep. So
far I have not had this issue occur, when I have done this.

Since this issue is stochastic/statistical in nature, it's impossible to
say for sure whether this fixes it. So far the sample size is also
relatively small (n=5 to 10).

**Comment by tetrahedras** [comment] 2022-12-17 19:24
This appears to have stopped happening for me. This is probably the
result of a recent kernel upgrade.

**Comment by andrewdavidwong** [comment] 2022-12-18 03:12
> This appears to have stopped happening for me. This is probably the
> result of a recent kernel upgrade.
> 


Closing this for now as it appears that the issue no longer affects any Qubes users. If anyone believes this is a mistake, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by brycepg** [comment] 2023-01-10 09:35
> https://linux-kernel.vger.kernel.narkive.com/ulG2HedP/git-pull-libata-fixes-for-v3-13-rc5
> 
> This is an old issue, it seems that there are some new bugs around this as well. But as an example, some component entered a deadlock. Removing the DVD drive made the problem go away.

Funny you mention removing the DVD drive. I used to have this issue. I have a HDD caddy in the DVD drive of my laptop now and I haven't encoutnered this issue in some time.

**Comment by tetrahedras** [comment] 2023-02-04 14:28
This has started cropping up again, for me. I don't think I've updated
dom0 in the last few days.

It does appear to be much more intermittent than it was before. However,
it has recently led to data loss:  I guess the file was not written
correctly when sleeping, and then was erased on reboot as the filesystem
went through the journal.

**Comment by nicolaipre** [comment] 2023-02-09 22:28
Is there a fix for this? I am experiencing the same exact same problems mentioned in the original post.

**Comment by cordygram** [comment] 2023-10-13 11:54
Same issue here. OS 4.14.6. HP x360 laptop. Won't wake from suspend and power button remains illuminated.  Happens every single time.  All updates applied.
Also, when laptop is locked screen goes black but remains backlit.

**Closed** 2024-12-07 14:28 UTC
Labels: T: bug, P: major, C: power management, affects-4.1, eol-4.1
