### ISSUE TITLE
qvm-start: no "--cdrom" option to specify location of windows iso

### ISSUE THREAD

**Issue by jakuoku** [QubesOS/qubes-issues#3055] opened 2017-08-28 14:57 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### Steps to reproduce the behavior: in Dom0, create windows standalone template qvm-create and then issue command to start template specifying location of installation iso:
sudo qvm-create win7 --class StandaloneVM --label=blue
sudo qvm-start win7 --cdrom=/path/to/windows/iso

### General notes:  It seems the version of the qvm-start command in qubes 4 rc1 does not have an option to specify the location of an iso. FYI, I have done this successfully in r3.2.

---

**Comment by marmarek** [comment] 2017-08-28 15:03
This is mostly a duplicate of #2951

**Comment by jakuoku** [comment] 2017-08-28 15:07
Sorry, I don't see how this is a duplicate.  This is specifically for specifying location of an installation image for windows.  The version of qvm-start does not have an option to specify that.  The suggested solution for #2951 does not seem applicable.

**Comment by marmarek** [comment] 2017-08-28 15:14
Ok, leave it open as a reminder to re-enable --cdrom option after fixing #2951

**Comment by jakuoku** [comment] 2017-08-28 16:00
much appreciated, thanks!  And thanks to the Qubes team for all the work that goes into this innovative distro!

**Closed** 2017-09-14 00:38 UTC
Labels: C: core, P: major
