### ISSUE TITLE
kernel trace "interrupt for port # not enabled" for allowed non-existent RPCs

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#9336] opened 2024-07-03 11:16 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes OS R4.2 Only

### Brief summary
Kernel traces an interrupt each time a non existent allowed RPC is called.

### Steps to reproduce
1. Create a permission for an RPC ` qubes.Interrupt *  AppVM1  AppVM2 allow`
2. from `AppVM1` call the allowed RPC `qrexec-client-vm AppVM2 qubes.Interrupt`
3. check system logs for `AppVM2` you will see an `interrupt for a non enabled port #XX`

### Expected behavior
No kernel warning issued if RPC doesn't exist then exit cleanly

### Actual behavior
Kernel issues a trace in target domain `AppVM2` each time the RPC is allowed to it.

**Comment by marmarek** [comment] 2024-07-03 11:23
Duplicate of https://github.com/QubesOS/qubes-issues/issues/8914 ? (already fixed, install updates)

**Closed** 2024-07-03 20:30 UTC
Labels: T: bug, R: duplicate, P: default
