### ISSUE TITLE
Upgrade Qubes tools to python 3.x 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#6861] opened 2021-08-28 02:04 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

python 2.x is no longer used/deprecated in debian bullseye 11

### Effected tools

- qubes-core-agent
- qubes-core-agent-networking 
- qubes-gui-agent
- qubes-vm-dependencies
- xen-utils-common

### Expected behavior

These tools no more depend on python 2.x 

### Actual behavior (debian)

```
user@host:~$ sudo apt remove --purge python2*
The following packages were automatically installed and are no longer required:
  conntrack cpp cpp-10 dconf-cli ethtool gir1.2-glib-2.0 imagemagick
  imagemagick-6-common imagemagick-6.q16 initscripts insserv
  keyboard-configuration libde265-0 libdrm-amdgpu1 libdrm-intel1
  libdrm-nouveau2 libdrm-radeon1 libedit2 libegl-mesa0 libegl1
  libfftw3-double3 libfontenc1 libgbm1 libgirepository-1.0-1 libgl1
  libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libheif1
  libisl23 libllvm11 liblqr-1-0 libmagickcore-6.q16-6 libmagickwand-6.q16-6
  libmpc3 libpciaccess0 libpython2-stdlib libpython2.7-minimal
  libpython2.7-stdlib libqubes-rpc-filecopy2 libqubesdb libsensors-config
  libsensors5 libvulkan1 libwayland-server0 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-sync1 libxcb-xfixes0
  libxfont2 libxkbfile1 libxmuu1 libxshmfence1 libxxf86vm1 libz3-4
  mesa-vulkan-drivers net-tools python3-cffi-backend python3-daemon
  python3-dbus python3-gi python3-lockfile python3-qubesdb python3-six
  python3-xcffib python3-xdg qubesdb qubesdb-vm startpar sysv-rc tinyproxy
  tinyproxy-bin x11-xkb-utils x11-xserver-utils xauth xdg-utils xenstore-utils
  xinit xserver-common xserver-xorg-core xserver-xorg-input-qubes
  xserver-xorg-video-dummyqbs
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  python2* python2-minimal* python2.7* python2.7-minimal* qubes-core-agent*
  qubes-core-agent-networking* qubes-gui-agent* qubes-vm-dependencies*
  xen-utils-common*
0 upgraded, 0 newly installed, 9 to remove and 0 not upgraded.
After this operation, 5,798 kB disk space will be freed.
Do you want to continue? [Y/n]
```

### Related Issues

#6287

**Comment by andrewdavidwong** [comment] 2021-08-28 22:34
@fepitre, is this a duplicate of #5297? #5297 is labeled `C: Fedora`, but this mentions Debian. Should #5297 be generalized?

**Comment by unman** [comment] 2021-08-29 02:24
The "Brief Summary" is completely wrong.
Debian supports both Python stacks - the LONG TERM goal is to move to
only one, but that's some way off.
Python 2.7 is available (and therefore *used* ) in Debian-11.

Of course, you may wish to see all packages moved to Python3 , but that's
a separate preexisting issue.

**Comment by TNTBOMBOM** [comment] 2021-08-29 12:12
> Python 2.7 is available (and therefore *used* ) in Debian-11.

Available in the packages of debian yes, But debian 11 installation doesnt ship any python2.x by default thus debian fresh 11 in qubes shouldnt do that as well. (minimizes the differences in packages between origin and qubes version)

**Comment by unman** [comment] 2021-08-29 14:32
On Sun, Aug 29, 2021 at 05:12:31AM -0700, TNT BOM BOM wrote:
> > Python 2.7 is available (and therefore *used* ) in Debian-11.
> 
> Available in the packages of debian yes, But debian 11 installation doesnt ship any python2.x by default thus debian fresh 11 in qubes shouldnt do that as well. (minimizes the differences in packages between origin and qubes version)
> 
> 

This is almost meaningless, since "by default" will depend on what
packages you have chosen to install.
If you install packages/programs that depend on python2 then it will be
pulled in.
That's the case here.

Of course, what you want is to transition everything to Python3.
Then this is a duplicate of existing issue.

**Comment by andrewdavidwong** [comment] 2021-08-29 19:16
> Then this is a duplicate of existing issue.

Just to confirm, of which existing issue is this a duplicate? #5297?

**Comment by unman** [comment] 2021-09-02 02:14
On Sun, Aug 29, 2021 at 12:16:46PM -0700, Andrew David Wong wrote:
> > Then this is a duplicate of existing issue.
> 
> Just to confirm, of which existing issue is this a duplicate? #5297?
> 

Yes.
Note that precisely the same issue arises in a fedora template: if one
attempts to remove python2, core qubes packages will be removed.

**Comment by andrewdavidwong** [comment] 2021-09-02 02:54
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-09-02 02:54 UTC
Labels: T: enhancement, C: core, P: default
