### ISSUE TITLE
qvm-open-in-dvm does not handle --help well

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#6882] opened 2021-09-09 11:02 UTC
### Qubes OS release
R4.1

### Brief summary

`qvm-open-in-dvm --help` causes the following:
 ```
~ $ qvm-open-in-dvm --help
# Here a dispVM starts and stops
qopen-in-vm: unrecognized option '--help'
EOF
```

### Expected behavior

Display help, don't start a disposable VM.

**Comment by andrewdavidwong** [comment] 2021-09-09 14:37
Duplicate of #6787

**Comment by andrewdavidwong** [comment] 2021-09-09 14:37
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-09-09 14:37 UTC
Labels: T: bug, P: default
