### ISSUE TITLE
apt-get error - E: Repository 'https://cdn-aws.deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5149] opened 2019-07-07 11:31 UTC
```
Reading package lists... Done                                                        
N: Repository 'https://cdn-aws.deb.debian.org/debian buster InRelease' changed its 'Version' value from '' to '10.0'
E: Repository 'https://cdn-aws.deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'https://cdn-aws.deb.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

Affects Debian buster and Whonix 15 templates.

Instructions for users (these work alike for any Debian buster and Whonix users):
https://forums.whonix.org/t/apt-get-error-e-repository-tor-https-cdn-aws-deb-debian-org-debian-security-buster-updates-inrelease-changed-its-suite-value-from-testing-to-stable/7704

Solution for upgrading through QVMM? Dunno.

This would likely be fixed in new template builds without code changes required.

**Comment by tasket** [comment] 2019-07-08 21:04
FWIW, I fixed this in one template by changing 'buster' to 'stable' in sources.list, performed one update, then changed sources.list back to 'buster'. But adrelanos' workaround is easier and probably more correct.

**Comment by unman** [comment] 2019-07-09 12:08
This really isn't a Qubes issue.

The "easier" way for end users updating manually is to use `apt` - that's what it's designed to do, get rid of the command line options.
A manual `apt update` will notice the change and prompt user to accept the change.

The only Qubes relevant part of this is the impact on the updater process, which reports success, but none the less fails. It should be possible to drop a config file in `/etc/apt/apt.conf.d` in an updated salt package, but that seems like overkill to me.

I'll add a note to the docs, and maybe the FAQ.

**Comment by andrewdavidwong** [comment] 2019-07-10 08:01
> The only Qubes relevant part of this is the impact on the updater process, which reports success, but none the less fails.

Shouldn't the Qubes updater be robust against this sort of thing, though?

**Comment by tasket** [comment] 2019-07-10 10:21
> Shouldn't the Qubes updater be robust against this sort of thing, though?

Yes, definitely. However, Qubes RPC uses `apt-get` as does my qubes-multi-update, so users are left with non-updating templates because of pre-release state in the template.

The template in testing is still from June, so I think the Qubes R4.2rc1 release could also have this problem.

The template should be rebuilt or at least updated and then re-issued.

**Comment by unman** [comment] 2019-07-10 14:34
> Shouldn't the Qubes updater be robust against this sort of thing, though?

No. It isn't a bug, and nor is it an error - neither in Debian nor in Qubes. It's a security mechanism.
We choose to use apt-secure for Debian templates. Apt-secure requires a user to manually accept changes in the repo status - my hope for a config file was misplaced.

>  The template should be rebuilt or at least updated and then re-issued.

Of course, there isn't a current template available as yet, only testing. And 4.2rc1 **does** have the testing template, so cant be updated without user intervention.

I've tried to rebuild, but the build server seems to be broken at the moment, which is why we dont have an updated template,( and some packages aren't being pushed from testing to current).
[@marmarek knows](https://github.com/QubesOS/updates-status/issues/566#issuecomment-509665789)

**Comment by h01ger** [comment] 2019-07-10 14:51
On Wed, Jul 10, 2019 at 07:34:47AM -0700, unman wrote:
> > Shouldn't the Qubes updater be robust against this sort of thing, though?
> No. It isn't a bug, and nor is it an error - neither in Debian nor in Qubes. It's a security mechanism.

no, it's a bug in Debian. luckily the workaround is easy, the easiest is
just to run 'apt update' and then resolve it manually as prompted.

see https://bugs.debian.org/931566 
'apt: Don't complain about suite changes (Acquire::AllowReleaseInfoChange::Suite should be "true")'


-- 
tschau,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by unman** [comment] 2019-07-10 15:07
@h01ger To be picky, that's a feature request isn't it?
The existing treatment is completely in line with the apt-secure documentation.

**Comment by h01ger** [comment] 2019-07-10 15:18
On Wed, Jul 10, 2019 at 08:07:24AM -0700, unman wrote:
> @h01ger To be picky, that's a feature request isn't it?
> The existing treatment is completely in line with the apt-secure documentation.

well, that's the maintainers view. the release team considers it a
serious bugs in buster they want to see fixed.


-- 
tschau,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

"... the premise [is] that privacy is about hiding a wrong. It's not.
 Privacy is an inherent human right, and a requirement for maintaining
 the human condition with dignity and respect." (Bruce Schneier)

**Comment by unman** [comment] 2019-07-10 15:25
I think we can agree that if Debian introduces that feature we'd incorporate it in to Qubes updater.
Until then, some advice to users.

**Comment by tasket** [comment] 2019-07-10 21:44
Regardless of how Debian devs feel about the severity of the bug, they have the luxury of saying "Well, you installed a pre-release version and have an extra step to get it functioning as a full release".

Qubes doesn't have that option, because it shouldn't be distributing templates that are in a pre-release state.... not unless they come from a testing repo. Qubes shouldn't be foisting an unnecessary transition from pre-release to release onto regular users.

**Comment by andrewdavidwong** [comment] 2019-07-11 00:33
Ok, so there's some disagreement about whether this is a Debian bug and therefore how we should handle it. @marmarek, I think we need a decision from you about how we'll proceed.

**Comment by adrelanos** [comment] 2019-07-11 05:55
Andrew David Wong:
>> The only Qubes relevant part of this is the impact on the updater process, which reports success, but none the less fails.
> 
> Shouldn't the Qubes updater be robust against this sort of thing, though?
> 

I wrote a parser for the "apt-get update" output since apt get has
unreliable exit codes (Debian bug report exists) but unlikely to be
actioned.

https://github.com/Whonix/security-misc/blob/master/usr/lib/security-misc/apt-get-wrapper

syntax:

/usr/lib/security-misc/apt-get-wrapper update <args>

**Comment by adrelanos** [comment] 2019-07-11 06:49
https://github.com/Whonix/security-misc/blob/master/usr/lib/security-misc/apt-get-wrapper of course is only part of the solution for an auxiliary bug. apt-get-wrapper can help to detect bugs such as these by parsing the output of apt-get update. That way the updater at least can notice something is wrong (due to non-zero exit code).

Related (since it ships `/usr/lib/security-misc/apt-get-wrapper`): `Package security-misc from Whonix to Qubes`
https://github.com/QubesOS/qubes-issues/issues/1885

**Comment by unman** [comment] 2019-07-11 11:43
> Qubes doesn't have that option, because it shouldn't be distributing templates that are in a pre-release state.... not unless they come from a testing repo. Qubes shouldn't be foisting an unnecessary transition from pre-release to release onto regular users.

We haven't done so - the only templates *are* in testing, or are part of a testing rc2.
Regardless of what Debian does, (and I dont favour our circumventing security mechanisms in Debian), the obvious solution for Qubes is to build and release a current Template *after* the underlying release. Which is what is going to happen in this case.

**Comment by adrelanos** [comment] 2019-07-11 18:15
Whonix template are affected by this but and these are now in stable,
although community stable repository. Not sure that counts.

Realistically though, I don't think users don't see much of a difference
between those and have the same expectations.

**Comment by marmarek** [comment] 2019-07-11 19:15
@adrelanos is right, we need to do something about it. Either handle this as a special case in update scripts, or add `apt: Don't complain about suite changes (Acquire::AllowReleaseInfoChange::Suite should be "true")` to apt config.

**Comment by unman** [comment] 2019-07-12 10:45
I dont think we should rush in to anything. I dont think we need a special case to handle *this* transition.

If Debian implement that feature request, then we use it. If they dont, or don't provide some other mechanism, then we should be extremely reluctant to circumvent the secure apt process, even at the cost of some user pain.

**Comment by h01ger** [comment] 2019-07-12 16:54
On Fri, Jul 12, 2019 at 03:45:12AM -0700, unman wrote:
> I dont think we need a special case to handle *this* transition.

I disagree.

> then we should be extremely reluctant to circumvent the secure apt process,
> even at the cost of some user pain.

this apt warning has nothing to do with security. it's just a pita
with no benefit.


-- 
tschau,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by unman** [comment] 2019-07-14 12:16
> this apt warning has nothing to do with security. it's just a pita with no benefit.

Thanks for that extremely detailed and cogent argument. I'm completely convinced.

**Comment by marmarek** [comment] 2019-07-14 16:35
It has a value to prevent compromised (or mitm-ed) mirror serving another repository instead. While replacing "testing" with "stable" shouldn't have bad effect on security, serving "unstable" definitely isn't good. So, in this particular case it is ok, but in generic case this mechanism has a value.
@h01ger is there an option allowing only "downgrade", but not "upgrade" of repository's release?

**Comment by julian-klode** [comment] 2019-07-15 15:15
> While replacing "testing" with "stable" shouldn't have bad effect on security, serving "unstable" definitely isn't good. 

That's causing a warning when you run update though, as the name you have in the sources.list ("testing") will not match the repo you get ("unstable"). I'm not convinced by that particular argument, as it seems to me that turning the warning into an error would solve that in a better way.

Anyway, we're working on it, and should get a better solution before the bullseye release :-)

> @h01ger is there an option allowing only "downgrade", but not "upgrade" of repository's release?

No, there are no semantics attached to the field values, so whether it says stable, testing, or meow; we don't care.

-- a friendly apt dev

**Comment by marmarek** [comment] 2019-07-17 04:26
I've created PR adding `apt-get update --allow-releaseinfo-change` call if any list file for buster still contains `Suite: testing`. It isn't ideal (that option doesn't specify what change exactly should be allowed), but I don't see a better option there.

The PR applies to salt file update, used by "qubes update" application. It doesn't apply to template update started from qubes-manager. Nor manual `apt-get update` calls.

**Comment by tasket** [comment] 2019-07-17 11:40
@marmarek I recommend against any permanent disabling of `apt` integrity checks.

AFAICT simply re-uploading an updated template would have fixed this issue, at least for the next two years until Debian 11 is released.

**Comment by marmarek** [comment] 2019-07-17 11:56
Updated debian-10 templates are already in testing repo. @adrelanos you may want to build new Whonix templates.

**Comment by marmarek** [comment] 2019-07-20 00:01
@adrelanos do you want some automatic update method (like PR I created above)? Or just template rebuild? debian-10 templates are still in testing and already rebuilt. Whonix 15 templates are in stable, so this is more visible to the users.

**Comment by adrelanos** [comment] 2019-07-20 00:33
Both ok for me. Debian/Qubes package updates are ok. No Whonix updates
yet. These are still being tested.

**Comment by marmarek** [comment] 2019-08-01 14:47
@adrelanos When would be a good time for new Whonix template builds?
I'd like to have https://github.com/Whonix/whonixsetup/commit/9c6ec0f503c1b381d0e7cd50e465eb491f58447e there, as it's require for automatic tests to work.

**Comment by adrelanos** [comment] 2019-08-02 03:04
That change is not yet in stable-proposed or testers repository since some not so well tested changes in other packages are still being worked on in the developers repository. I am good for development, but don't have a good grip on stable/release management / backporting / Q/A. Due to missing https://phabricator.whonix.org/T709 (or similar) it's hard to keep track on singular changes and/or moving packages though suites faster. Specifically also tb-updater should have stable upgrades faster often.

**Comment by adrelanos** [comment] 2019-09-06 13:49
@marmarek:

> @adrelanos When would be a good time for new Whonix template builds?

Now would be a good time.

Since https://github.com/QubesOS/qubes-issues/issues/4918#issuecomment-528861928 among other fixes and enhancements hit Whonix stable repository today.

**Comment by zaoqi** [comment] 2019-10-27 08:23
This issue was fixed

**Comment by andrewdavidwong** [comment] 2019-10-28 08:36
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-10-28 08:36 UTC
Labels: C: Debian/Ubuntu, C: Whonix, P: critical, T: bug
