### ISSUE TITLE
Possible bug with: qubes-gpg-client 

### ISSUE THREAD

**Issue by SeemsToHaveLotsOfProblems** [QubesOS/qubes-issues#4213] opened 2018-08-14 12:45 UTC
### Qubes OS version:

Qubes-4.0 - R4.0

### Affected component(s): 

Qubes gpg manager

---

### Steps to reproduce the behavior:

Trying to unencrypt or encrypt something
`qubes-gpg-client -u 'key name' file`
or
`qubes-gpg-client -se -u 'keyname' -r recipient  file`

### Expected behavior:

When the decrypt command is run it should unencrypt the file.

### Actual behavior:

`decryption failed: No secret key`

### General notes:

The secret key is there, and if I go into my gpg vm I can manipulate it, sign and encrypt, as well as decrypt. This issue only occurred in the last day or so, everything was working before that, so I don't know what caused it. I hope I was able to provide enough info to help.
**Update:** 2nd update was to fix a few spelling mistakes.
I seem to have figured out a bit more information. This bug only affects keys created within the gpg vm. If you import a secret key, the vm keyring itself will not recognize it as a secret key, but the command `qubes-gpg-client -se -u 'imported key' -r 'whoever' file` & `qubes-gpg-client -u 'Imported key' file` Will work.
The command `qubes-gpg-client -K` will not show the imported key, however that key works for encryption & decryption.

---

**Comment by unman** [comment] 2018-08-14 13:39
What Templates are you using?
Have you installed any updates recently?

When you run `qubes-gpg-client -k` and` qubes-gpg-client -K`,  do you get an access notification? 
Are you prompted to give access to your keys in gpg-vm?

**Comment by marmarek** [comment] 2018-08-30 14:18
On Tue, Aug 14, 2018 at 07:23:31AM -0700, SeemsToHaveLotsOfProblems wrote:
> I'm using fedora 26 & 28 templates, both up to date. I can run `qubes-gpg-client -k` just fine and see all my keys without issue. I do get prompted for the gpg-vm but it will not ask for a password as it tells me the secret key doesn't exist. I have not installed any updates since I began using gpg.

Do you use gpg or gpg2 in backend vm? split gpg use gpg2 and secret keys
needs to be imported into it (gpg2 should automatically convert them on
first use if you used gpg before).

**Comment by DemiMarie** [comment] 2022-02-15 05:08
@marmarek should this be closed as “not a bug” or “invalid”?

**Comment by andrewdavidwong** [comment] 2022-02-16 10:56
Since it has been so long since Marek's question with no response from anyone, we close this as it presumably no longer affects any users and may have been inadvertently fixed in the meantime. If any users are still affected, please leave a comment, and we'll be happy to reopen.

(P.S. @DemiMarie, `more info needed` is for when more info is needed from the issue reporter or other users rather than from devs. Unclear from your usage whether you intended this.)

**Closed by andrewdavidwong** 2022-02-16 10:56 UTC
Labels: T: bug, more info needed, C: split-gpg1
