### ISSUE TITLE
When I shutdown the debian-9 TemplateVM it removes all my USB devices from sys-usb

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4161] opened 2018-07-30 04:13 UTC
### Qubes OS version: 
R4.0

### Affected component(s): 
sys-usb

### Steps to reproduce the behavior: 
Shutdown Debian-9 template VM

### Expected behavior: 
My USB devices are not affected

### Actual behavior:
I get a notification that all my USB devices are disconnected, but at least some of them still work (e.g. my keyboard and mouse)

### General notes:
N/A

### Related issues:
Possibly related to:
- https://github.com/QubesOS/qubes-issues/issues/4160
- https://github.com/QubesOS/qubes-issues/issues/4159

**Comment by MartynasJanonis** [comment] 2018-07-30 11:01
Most likely duplicate of #4078

**Comment by e6lk7dqzm83p** [comment] 2018-07-30 13:58
Agreed, sorry I missed that.

**Comment by andrewdavidwong** [comment] 2018-07-31 00:32
Duplicate of #4078

**Comment by andrewdavidwong** [comment] 2018-07-31 00:32
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-07-31 00:32 UTC
