### ISSUE TITLE
Builder Qubes 4.1 error conflicting packages

### ISSUE THREAD

**Issue by adubois** [QubesOS/qubes-issues#5832] opened 2020-05-19 21:31 UTC
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qubes-builder - qubes-os-master.conf/qubes-os-r4.1.conf - make iso

**Brief summary**
make iso fails

**To Reproduce**
Create new builder-41 VM (fedora-31 template)
follow qubes-builder guide with default option for 4.1 (+ fc31 + buster)
make qubes: complete!
make iso: Error 1

**Expected behavior**
iso image created

**Actual behavior**
-> Building installer-qubes-os iso for fc31 (logfile: build-logs/installer-qubes-os-iso-fc31.log)...
--> build failed!
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 777, in resolve
    raise exc
dnf.exceptions.DepsolveError: 
 Problem 1: package fedora-release-31-4.noarch conflicts with system-release provided by qubes-release-4.1-0.24.noarch
  - package qubes-release-4.1-0.24.noarch obsoletes fedora-release provided by fedora-release-31-4.noarch
  - conflicting requests
 Problem 2: package qubes-artwork-4.1.4-2.fc31.noarch obsoletes fedora-logos provided by fedora-logos-30.0.2-3.fc31.x86_64
  - conflicting requests
make[1]: *** [Makefile:92: iso-installer-lorax] Error 1
make[1]: Leaving directory '/home/user/qubes-src/installer-qubes-os'
make: *** [Makefile:538: iso] Error 1

**Solutions you've tried**
Identified obsolete package in qubes-src/linux-template-builder/cache_fc31/base_rpms/defora-release-31-4.noarch.rpm but not the 2d one (logos)
Unsure how to resolve the problem. Going to look into fedora-31 template builder Makefile expecting to change behavior so built rpm match expected names/package key?... 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment] 2020-05-19 21:46
We're in the middle of switching R4.1 dom0 to Fedora 32. The exact issue you see is caused by it...
You can observe the progress here: https://github.com/QubesOS/qubes-issues/issues/5763, as you can see, most pull requests are already merged. I hope to have it finished this week, but until then you probably need pick branches in those PRs... Or simply wait until it's done (I recommend subscribing to notifications in #5763)

**Closed by marmarek** 2020-05-19 21:46 UTC
Labels: P: default, T: bug
