### ISSUE TITLE
archlinux template builder is incomplete (r4.1 : qubes-template-archlinux, qubes-template-archlinux-minimal) error: target not found: qubes-vm-repo

### ISSUE THREAD

**Issue by IDBEHOLDS** [QubesOS/qubes-issues#6351] opened 2021-01-19 12:22 UTC
**Qubes OS version**
4.1

**Affected component(s) or functionality**
qubes-builder, qubes-builder-archlinux (4.1, stable/current-testing repo)
builder based on fedora-33 template

**Brief summary**

vanilla archlinux template build cannot be finished

**How Reproducible**
100%

$ make vmm-xen-vm
$ make core-vchan-xen-vm
$ make core-qubesdb-vm
$ make linux-utils-vm
$ make core-agent-linux-vm
$ make gui-common-vm
$ make gui-agent-linux-vm
$ make app-linux-split-gpg-vm

make template

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

```
Building template: archlinux-minimal
-> Preparing instalation of archlinux template...
--> Archlinux 00_prepare.sh
  --> Downloading Archlinux bootstrap tarball (v)...
--2021-01-19 15:19:16--  https://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2021.01.01-x86_64.tar.gz
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.101.1, 2604:1380:2001:3900::1
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.101.1|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File 'cache_archlinux/archlinux-bootstrap-2021.01.01-x86_64.tar.gz' not modified on server. Omitting download.

--2021-01-19 15:19:17--  https://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2021.01.01-x86_64.tar.gz.sig
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.101.1, 2604:1380:2001:3900::1
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.101.1|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File 'cache_archlinux/archlinux-bootstrap-2021.01.01-x86_64.tar.gz.sig' not modified on server. Omitting download.

  --> Preparing GnuPG to verify tarball...
gpg: key 3348882F6AC6A4C2: "Pierre Schmitz (Arch Linux Master Key) <pierre@master-key.archlinux.org>" not changed
gpg: key 5184252D824B18E8: 1 signature not checked due to a missing key
gpg: key 5184252D824B18E8: "Thomas B�chler (Arch Linux Master Key) <thomas@master-key.archlinux.org>" not changed
gpg: key 7EFD567D4C7EA887: 1 signature not checked due to a missing key
gpg: key 7EFD567D4C7EA887: "Ionut Biru (Arch Linux Master Key) <ionut@master-key.archlinux.org>" not changed
gpg: key BA1DFB64FFF979E7: 4 signatures not checked due to missing keys
gpg: key BA1DFB64FFF979E7: "Allan McRae (Arch Linux Master Key) <allan@master-key.archlinux.org>" not changed
gpg: key A04F9397CDFD6BB0: 2 signatures not checked due to missing keys
gpg: key A04F9397CDFD6BB0: "Dan McGee (Arch Linux Master Key) <dan@master-key.archlinux.org>" not changed
gpg: key 7F2D434B9741E8AC: 9 signatures not checked due to missing keys
gpg: key 7F2D434B9741E8AC: "Pierre Schmitz <pierre@archlinux.de>" not changed
gpg: Total number processed: 6
gpg:              unchanged: 6
  --> Verifying tarball...
gpg: Signature made Fri Jan  1 12:23:57 2021 MSK
gpg:                using RSA key 4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC
gpg: Good signature from "Pierre Schmitz <pierre@archlinux.de>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 4AA4 767B BC9C 4B1D 18AE  28B7 7F2D 434B 9741 E8AC
  --> NB: Bootstrap tarball not newer than bootstrap directory, will use existing!
-> Image file already exists, assuming *update*...
--> Archlinux 01_install_core.sh
--> Archlinux prepare-chroot-base
  --> NB: INSTALLDIR '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' already appears to have an environment; will leave as-is!
  --> Unbinding INSTALLDIR...
umount: cache_archlinux/bootstrap/mnt: not mounted.
-> Installing package groups...
--> Archlinux 02_install_groups.sh
  --> Synchronize resolv.conf...
  --> Updating installed packages...
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
  --> Installing archlinux package groups...
    --> Selected packages: xorg xterm ethtool net-tools sudo wget diffutils
warning: xf86-video-vesa-2.5.0-1 is up to date -- skipping
warning: xorg-bdftopcf-1.1-2 is up to date -- skipping
warning: xorg-docs-1.7.1-3 is up to date -- skipping
warning: xorg-font-util-1.3.2-2 is up to date -- skipping
warning: xorg-fonts-100dpi-1.0.3-7 is up to date -- skipping
warning: xorg-fonts-75dpi-1.0.3-7 is up to date -- skipping
warning: xorg-fonts-encodings-1.0.5-2 is up to date -- skipping
warning: xorg-iceauth-1.0.8-2 is up to date -- skipping
warning: xorg-mkfontscale-1.2.1-2 is up to date -- skipping
warning: xorg-server-1.20.10-3 is up to date -- skipping
warning: xorg-server-common-1.20.10-3 is up to date -- skipping
warning: xorg-server-devel-1.20.10-3 is up to date -- skipping
warning: xorg-server-xephyr-1.20.10-3 is up to date -- skipping
warning: xorg-server-xnest-1.20.10-3 is up to date -- skipping
warning: xorg-server-xvfb-1.20.10-3 is up to date -- skipping
warning: xorg-sessreg-1.1.2-2 is up to date -- skipping
warning: xorg-setxkbmap-1.3.2-2 is up to date -- skipping
warning: xorg-smproxy-1.0.6-3 is up to date -- skipping
warning: xorg-x11perf-1.6.1-2 is up to date -- skipping
warning: xorg-xauth-1.1-2 is up to date -- skipping
warning: xorg-xbacklight-1.2.3-2 is up to date -- skipping
warning: xorg-xcmsdb-1.0.5-3 is up to date -- skipping
warning: xorg-xcursorgen-1.0.7-2 is up to date -- skipping
warning: xorg-xdpyinfo-1.3.2-4 is up to date -- skipping
warning: xorg-xdriinfo-1.0.6-2 is up to date -- skipping
warning: xorg-xev-1.2.4-1 is up to date -- skipping
warning: xorg-xgamma-1.0.6-3 is up to date -- skipping
warning: xorg-xhost-1.0.8-2 is up to date -- skipping
warning: xorg-xinput-1.6.3-2 is up to date -- skipping
warning: xorg-xkbcomp-1.4.4-1 is up to date -- skipping
warning: xorg-xkbevd-1.1.4-3 is up to date -- skipping
warning: xorg-xkbutils-1.0.4-4 is up to date -- skipping
warning: xorg-xkill-1.0.5-2 is up to date -- skipping
warning: xorg-xlsatoms-1.1.3-2 is up to date -- skipping
warning: xorg-xlsclients-1.1.4-2 is up to date -- skipping
warning: xorg-xmodmap-1.0.10-2 is up to date -- skipping
warning: xorg-xpr-1.0.5-2 is up to date -- skipping
warning: xorg-xprop-1.2.5-1 is up to date -- skipping
warning: xorg-xrandr-1.5.1-2 is up to date -- skipping
warning: xorg-xrdb-1.2.0-2 is up to date -- skipping
warning: xorg-xrefresh-1.0.6-2 is up to date -- skipping
warning: xorg-xset-1.2.4-2 is up to date -- skipping
warning: xorg-xsetroot-1.1.2-2 is up to date -- skipping
warning: xorg-xvinfo-1.1.4-2 is up to date -- skipping
warning: xorg-xwayland-1.20.0.r800.ge4a9f0bb4-1 is up to date -- skipping
warning: xorg-xwd-1.0.7-2 is up to date -- skipping
warning: xorg-xwininfo-1.1.5-2 is up to date -- skipping
warning: xorg-xwud-1.0.5-2 is up to date -- skipping
warning: xterm-363-1 is up to date -- skipping
warning: ethtool-1:5.10-1 is up to date -- skipping
warning: net-tools-1.60.20181103git-2 is up to date -- skipping
warning: sudo-1.9.4.p2-2 is up to date -- skipping
warning: wget-1.21.1-1 is up to date -- skipping
warning: diffutils-3.7-3 is up to date -- skipping
 there is nothing to do
-> Unmounting prepared_image...
--> Copying prepared_images/archlinux-minimal.img to qubeized_images/archlinux-minimal/root.img...
--> Mounting qubeized_images/archlinux-minimal/root.img
--> Archlinux 04_install_qubes.sh
  --> Enabling x86 repos...
  --> Updating Qubes custom repository...
==> Adding package 'pkgs/qubes-db-vm-4.1.10-5-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-gpg-split-2.0.50-1-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-libvchan-xen-4.1.7-2-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-core-4.1.22-15-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-gui-4.1.15-10-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-gui-common-4.1.1-1-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-kernel-support-4.1.13-10-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-keyring-4.1.22-15-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-networking-4.1.22-15-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-passwordless-root-4.1.22-15-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-pulseaudio-4.1.15-10-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-utils-4.1.13-10-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
==> Extracting qubes.db.tar.gz to a temporary location...
==> Extracting qubes.files.tar.gz to a temporary location...
==> Adding package 'pkgs/qubes-vm-xen-4.14.1-2-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'pkgs/qubes.db.tar.gz'
  --> Registering Qubes custom repository...
  --> Synchronize resolv.conf...
  --> Updating pacman sources...
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
downloading multilib.db...
downloading qubes.db...
:: Starting full system upgrade...
 there is nothing to do
  --> Checking available qubes packages (for debugging only)...
qubes/qubes-db-vm 4.1.10-5
    QubesDB libs and daemon service.
qubes/qubes-gpg-split 2.0.50-1
    The Qubes service for secure gpg seperation
qubes/qubes-libvchan-xen 4.1.7-2
    The Qubes core libraries for installation inside a Qubes Dom0 and VM.
qubes/qubes-vm-core 4.1.22-15
    The Qubes core files for installation inside a Qubes VM.
qubes/qubes-vm-gui 4.1.15-10
    The Qubes GUI Agent for AppVMs
qubes/qubes-vm-gui-common 4.1.1-1
    Common files for Qubes GUI - protocol headers.
qubes/qubes-vm-kernel-support 4.1.13-10
    Common Linux files for Qubes VM.
qubes/qubes-vm-keyring 4.1.22-15
    Qubes OS Binary Repository Activation package and Keyring
qubes/qubes-vm-networking 4.1.22-15
    Qubes OS tools allowing to use a Qubes VM as a NetVM/ProxyVM
qubes/qubes-vm-passwordless-root 4.1.22-15
    Qubes OS Passwordless root access from normal user
qubes/qubes-vm-pulseaudio 4.1.15-10
    Pulseaudio support for Qubes VM
qubes/qubes-vm-utils 4.1.13-10
    Common Linux files for Qubes VM.
qubes/qubes-vm-xen 4.14.1-2
    Xen is a virtual machine monitor
  --> Installing repository qubes package...
error: target not found: qubes-vm-repo
make[1]: *** [Makefile:66: rootimg-build] Error 1

```
```
[user@qubes-builder-archlinux qubes-builder]$ make template
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/vmm-xen/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/vmm-xen/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/vmm-xen/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/core-vchan-xen/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-vchan-xen/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/core-vchan-xen/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/core-qubesdb/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-qubesdb/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/core-qubesdb/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/core-qrexec/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-qrexec/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/core-qrexec/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
cat: qubes-src/core-qrexec/pkgs/vm-archlinux/archlinux.list: No such file or directory
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/linux-utils/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/linux-utils/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/linux-utils/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/core-agent-linux/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-agent-linux/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/core-agent-linux/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/gui-common/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/gui-common/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/gui-common/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/gui-agent-linux/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/gui-agent-linux/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/gui-agent-linux/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/app-linux-split-gpg/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/app-linux-split-gpg/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/app-linux-split-gpg/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/app-linux-usb-proxy/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/app-linux-usb-proxy/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/app-linux-usb-proxy/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
cat: qubes-src/app-linux-usb-proxy/pkgs/vm-archlinux/archlinux.list: No such file or directory
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs; \
for package in archlinux; do\
	pkgnames=`cat qubes-src/meta-packages/pkgs/vm-archlinux/$package.list`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/meta-packages/$pkgname /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ || exit 1;\
		ln -f qubes-src/meta-packages/$pkgname.sig /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/ 2>/dev/null;\
		if [ -n "" ]; then \
			echo $pkgname >> ""; \
		fi; \
	done; \
done
cat: qubes-src/meta-packages/pkgs/vm-archlinux/archlinux.list: No such file or directory
-> Building template archlinux (logfile: build-logs/template-archlinux.log)...
make: *** [Makefile:341: template-local-archlinux+minimal] Error 1

```

**Solutions you've tried**

```
[user@qubes-builder-archlinux qubes-builder]$ sudo chroot chroot-vm-archlinux
[root@qubes-builder-archlinux /]# pacman -S qubes-vm-repo
error: could not register 'qubes-r4.1-current' database (database already registered)
warning: qubes-vm-repo-4.1.11-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) qubes-vm-repo-4.1.11-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.00 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 qubes-vm-repo-4.1.11-1-x86_64                            9.1 KiB  0.00   B/s 00:00 [################################################] 100%
(1/1) checking keys in keyring                                                      [################################################] 100%
(1/1) checking package integrity                                                    [################################################] 100%
(1/1) loading package files                                                         [################################################] 100%
(1/1) checking for file conflicts                                                   [################################################] 100%
:: Processing package changes...
(1/1) reinstalling qubes-vm-repo                                                    [################################################] 100%
warning: directory permissions differ on /etc/
filesystem: 775  package: 755
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[root@qubes-builder-archlinux /]# exit

```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by IDBEHOLDS** [comment] 2021-01-23 09:47
@marmarek something strange here
`/home/user/qubes-builder/qubes-src/builder-archlinux/scripts/04_install_qubes.sh`

i comment part of scripts and install manually `qubes-vm-repo` `qubes-vm-dependencies` and `qubes-vm-recommended` from chroot

make template is finished (archlinux-minimal)

**Comment by icequbes1** [comment] 2021-01-24 18:15
```
make qubes-vm
make template
```

You don't need to manually build each *-vm package (because you are missing some) - the `qubes-vm` target does this for you.

**Comment by unman** [comment] 2021-06-12 12:20
@IDBEHOLDS @andrewdavidwong
It looks to me as if the problem lay in not building the right packages - as @icequbes1 says `make qubes-vm` works fine.
As such this issue should be closed.

There **is** an issue with the `xenstore-read` error, but that is a duplicate of #6324

**Closed** 2021-06-12 21:47 UTC
Labels: C: Arch Linux, C: builder, P: default, R: not an issue, T: bug, diagnosed
