### ISSUE TITLE
Mouse events occassionally sent to window behind popup window, instead of popup window itself

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#7702] opened 2022-08-19 16:05 UTC
### Qubes OS release
4.1.1

### Brief summary
Occasionally, I'll get a popup, e.g. from Google Calendar in Chromium, that does not respond to clicks. However, it is clear that Qubes is sending the click events to the window underneath the popup window, because things happen that would have happened if I had clicked at that place on the screen and the popup window had not been present.

### Steps to reproduce
I don't know how to reproduce this, it only happens occasionally.

### Expected behavior
When I click on a button in the popup window, it should behave as normal

### Actual behavior
Popup window stays there, and if there is something at the same place in the window behind it, the application will do what it would have done if I had been able to click there.

**Comment by unman** [comment] 2022-08-19 16:55
Is duplicate of #6253?

**Comment by DemiMarie** [comment] 2022-08-19 18:53
Yes, which is itself a duplicate of #3267.

This is a fundamentally hard problem because of the use of a nested X server.  The correct solution is to send events to windows directly, instead of relying on Xorg’s event routing.  This is probably not feasable for X11.  However, this is simply a non-issue under Wayland, since the Wayland agent _is_ the display server there.

**Closed by DemiMarie** 2022-08-19 18:53 UTC
Labels: T: bug, C: gui-virtualization, P: default

**Comment by andrewdavidwong** [comment] 2022-08-19 22:46
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
