### ISSUE TITLE
Qubes 4.0 after installation doesn't boot on ThinkPad X220 UEFI, hangs at Xen, can't read fonts

### ISSUE THREAD

**Issue by defendio** [QubesOS/qubes-issues#4263] opened 2018-08-29 10:34 UTC
### Qubes OS version:

4.0

### Affected component(s): 

Whole system.

---

### Steps to reproduce the behavior:

1. install qubes 4.0 at thinkpad x220 with uefi
2. try booting it
3. boot hangs with black screen before getting to kernel (can't see any penguins)
4. can't read screen as it's unreadable just like in https://github.com/QubesOS/qubes-issues/issues/2284

### Expected behavior:

That it boots.

### Actual behavior:

It doesn't boot.

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-08-30 04:53
Duplicate of #2284

**Comment by andrewdavidwong** [comment] 2018-08-30 04:53
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2018-08-30 04:53
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Closed by andrewdavidwong** 2018-08-30 04:53 UTC
