### ISSUE TITLE
Stuck booting, APIC driver x2apic_cluster

### ISSUE THREAD

**Issue by ehanoc** [QubesOS/qubes-issues#5903] opened 2020-06-23 12:53 UTC
**Qubes OS versions**
kernel 4.19.125
OS 4.0
Xen hypervisor 4.8.5-18.fc25

** Hardware **
Purism Librem v15

**Affected component(s) or functionality**
Unbootable

**Brief summary**
I've updated dom0, restarted, can't boot

**Solutions you've tried**
Works in recovery mode, but cant start any VMs

![20200623_134523](https://user-images.githubusercontent.com/1436105/85405808-d72cac00-b558-11ea-9dfe-cebcdbb406bd.jpg)

**Comment by ehanoc** [comment] 2020-06-24 06:51
I noticed that this happens when choosing booting with **Xen hypervisor, version 4.8.5-18.fc25**; but it works if choose the old version of **Xen hypervisor, version 4.8**

**Comment by ehanoc** [comment] 2020-06-26 07:45
**Xen hypervisor 4.8** **+** **kernel 4.19.107** works just fine. I can manually choose these through grub.  Something changed with either Xen's or Qubes Kernel new versions. It has been working fine for me for over a year with no problems

**Comment by byte255** [comment] 2020-07-06 00:00
I am having the same problem. Cannot boot with kernel 4.19.125 (default). When choosing kernel 4.19.107 in boot menu, it boots successfully.

**Comment by darwin** [comment] 2020-07-13 20:58
I'm likely having the same problem with Librem 13v2

**Comment by ratiocinator0** [comment] 2020-07-15 01:56
Librem15, same problem starting with mid-June dom0 update and dom0 update several days later did not fix it. What I discovered is that when there is blinking cursor in upper right, start pressing ESC key and sometimes alternating with ENTER key using an  irregular rhythm, it will usually boot and present LUKS prompt. kernel 4.19.107 with any hypervisor works normally for me.

**Comment by ehanoc** [comment] 2020-07-15 07:55
I think a normal setup of Qubes only keeps the last 3 kernel versions? This needs to be addressed or there's a chance with the next update to completely block the system for users? @andrewdavidwong

**Comment by andrewdavidwong** [comment] 2020-07-15 09:10
> I think a normal setup of Qubes only keeps the last 3 kernel versions? This needs to be addressed or there's a chance with the next update to completely block the system for users?

@marmarek, is there a workaround to allow users to keep a "known good" combination of Xen+kernel versions?

**Comment by ratiocinator0** [comment] 2020-07-17 00:32
As it turns out, another dom0 came out right after I posted previous comment. I figured that since I have the ESC workaround I'd give it a try, but this latest update still has the issue. However, instead of 107, my last entry is now 100 which works.

**Comment by ollieparanoid** [comment] 2020-08-04 06:44
I have the same problem on a Librem 13 with kernel 4.19.128 and 4.19.125: it gets stuck on a blinking cursor instead of displaying the LUKS prompt.

> What I discovered is that when there is blinking cursor in upper right, start pressing ESC key and sometimes alternating with ENTER key using an irregular rhythm, it will usually boot and present LUKS prompt.

I found that sometimes, very rarely (1 out of 10 tries or so), the problematic kernels boot too - without touching any keys. So I guess it's a race condition, unrelated to hammering keys.

Only when selecting 4.19.107 in GRUB, the laptop boots every time.

> I think a normal setup of Qubes only keeps the last 3 kernel versions? This needs to be addressed or there's a chance with the next update to completely block the system for users? @andrewdavidwong

This also worries me, the working kernel is the last one out of the three now... looks like the next kernel update will remove it.

Can we help with resolving this?

**Comment by ehanoc** [comment] 2020-08-04 11:13
@andrewdavidwong can we bump priority on this? The next update will block us. And in my case, i use the system for work. I cant update anymore until this is clearly fixed.

**Comment by marmarek** [comment] 2020-08-04 11:57
Can you try booting the problematic kernel, but with more verbose messages? Specifically edit the entry in grub menu and remove "quiet" and "rhgb" options (boot with ctrl+x from the edit entry screen).

**Comment by ollieparanoid** [comment] 2020-08-04 21:39
> Can you try booting the problematic kernel, but with more verbose messages? Specifically edit the entry in grub menu and remove "quiet" and "rhgb" options (boot with ctrl+x from the edit entry screen).

Sure. I edited the entry and removed both options from the kernel line, then booted with ctrl+x. Unfortunately, it does not show more output, it is still just a blinking cursor.

**Comment by ratiocinator0** [comment] 2020-08-07 01:16
@ehanoc - that's not my experience. Letting it boot by itself has never worked for me, even when leaving it alone far longer than my workaround which works most of the time, closer to 9 out of ten. Also, a few dom0 updates back, my last choice changed from 125 to 100, both of which work normally.

**Comment by ehanoc** [comment] 2020-08-10 08:28
> closer to 9 out of ten. Also, a few dom0 updates back, my last choice changed from 125 to 100, both of which work normally.

@ratiocinator0  You are correct actually. Maybe i didn't described it correctly. It never worked letting it boot by itself for me too. 

@marmarek i still just get the same output as in the screenshot i posted. Isn't this to do with Xen configuration? Can we disable x2apic_cluster? I think there's a flag for it

**Comment by sptankard** [comment] 2020-10-09 03:06
Any ideas on the root cause of this? My qubes system has been unbootable for a few months due to this. :( 

I made the mistake of trying to fix it without research and bricked all my kernel entries. (After the first kernel was bricked, i booted the remaining good entry and manually re-applied the updates, which bricked the remaining kernel(s).)

The ESC workaround does not seem to work for me.

I tried adding `x2apic=off`, plus a bunch of other flags, no luck.

Qubes live recovery is also stalling out on LUKS decrypt (infinite loop, "waiting for lvm auto-evaluation..."). I think this might be due to lvm pool being very full (unrelated to this bug).

Note: While experimenting with grub flags, I did notice `xen.cfg` file is empty. Not sure if that is how it should be, or if there is more than one `xen.cfg` (maybe for uefi/legacy). The grub entries all appear fine (fleshed out) when i edit them interactively.)

**Comment by ehanoc** [comment] 2020-10-10 20:48
The issue is marked as critical but has been stale for a while... Is Qubes still actively maintained?

**Comment by sptankard** [comment] 2020-10-11 02:05
I'm not sure of the criteria for 'critical'. I expect i'm probably the only individual with an unbootable system at this point. (I had to take additional, involved, complex steps in order to get to that point.) I expect this bug affects very few setups (hardware combos probably?) and most of those can still boot on older grub entries.

For others, i expect it will be more critical when Qubes releases the next Xen or kernel updates. That's when it might push other setups into unbootable state.

I'm just a user, but my impression is Qubes is still maintained. Plenty of commits and activity by the devs. They've always had a pretty barebones team, though.

**Comment by andrewdavidwong** [comment] 2020-10-11 04:06
> The issue is marked as critical but has been stale for a while... Is Qubes still actively maintained?

Indeed, it is! You can easily verify this by looking at the frequent activity across our GitHub repos, as well as our frequent [news](https://www.qubes-os.org/news/) posts. But perhaps your question is really why this issue hasn't been fixed yet even though it's marked "critical." That's a fair question. I can offer these thoughts:

You might be reading a bit too much into the issue labels. When I assign a label like "critical," it is my best effort to infer the appropriate priority given all information available at the time. It's an attempt to anticipate the judgment of the developers in order to save them some time and effort, but it is not an expression of their judgment. It's not a pronouncement or decree of how important something actually is. It's a way of me saying to the devs, "Given all the information I have, here is what my best prediction of what you think the priority of this issue will be." It's then up to the devs to decide whether and to what degree my prediction was accurate and change the label if appropriate (or ask me to change my methodology!).

The developers have a *ton* of work to do, even beyond the current critical issues (of which there are currently a dozen open besides this one).The reality is that we're a very small team with limited resources, and a reasonably secure OS is a huge undertaking, where it's important to do things right. The result is that things move more slowly than anyone would like. Sometimes, the pace may unacceptably slow for you. What are your options in that case? Well, since Qubes is open-source software, we're always happy to receive patches. You could [submit a patch](https://www.qubes-os.org/doc/source-code/#how-to-send-patches) for the thing you want fixed (or get someone else to do so). There are also many other ways to [contribute](https://www.qubes-os.org/doc/contributing/) besides writing code. What if the patch isn't accepted, or if you want more drastic changes? A further step would be to fork the project. However, that would be a huge undertaking, and unless you have a bigger team and more funding, you might find yourself in exactly the same situation, just on the other side of things. I think we all get frustrated with software from time to time, but at least in the case of open-source software like Qubes, it can help to remember that you're getting it completely for free (including any [support](https://www.qubes-os.org/support/) you receive through our discussion venues).

When time is truly of the essence, such as with [security](https://www.qubes-os.org/security/) issues, we make sure to respond quickly. For example, I think the relatively consistent speed with which we've issued [Qubes Security Bulletins](https://www.qubes-os.org/security/bulletins/) over the years is pretty good. This is not to say that other issues, such as this one, aren't important. They surely are, and the time it takes to fix them affects people in real ways. But, at the end of the day, there's a small number of human beings behind the scenes trying to do everything, and sometimes they have to take time out for human stuff like sleeping and maybe even the occasional vacation. If they don't do those things, then the risk is an unsustainable workload that leads to burn-out, and then we wouldn't have Qubes at all. :slightly_frowning_face:

**Comment by sptankard** [comment] 2020-10-11 06:54
Btw @ehanoc does your system still boot on older entries? If anyone has ideas on what the root cause is i'm willing to look into it. (Motivated since my system doesn't boot at all...)

At this point my next step is probably to read the recent commit logs for Xen and kernel and see what components got changes.

**Comment by ratiocinator0** [comment] 2020-10-12 20:48
I noticed a succession of **dom0** updates recently. Following these updates, what I noticed is that if I leave it alone and let it auto-boot it has worked. But if I manually choose the top choices that would have auto-booted, it locks up. Very curious.

**Comment by sptankard** [comment] 2020-10-13 04:29
@ratiocinator0, 
 
> ... Following these updates, what I noticed is that if I leave it alone and let it auto-boot it has worked. ...

I take it you mean, if you choose an older kernel entry, then hit enter and let it boot unattended from there, it works? I believe it was the same for me, before i (re)applied updates manually.

**Comment by sptankard** [comment] 2020-10-13 04:34
I noted quite a lot of the folks reporting this issue are using a Purism Librem. (I'm experiencing the bug on a Librem 13 v2.) I'm wondering if there's anyone experiencing this bug on a device that is NOT a Librem?

Note: for clarity, unlike some others here, my 4.19.107 kernel entry does NOT work.

I have three major grub entries. The first one is xen `4.8.5-18.fc25`, the second is `4.8.5-18.fc25.config`, and the third one is `4.8`.

On my system, none of these work. (When it first broke, 1 or 2 of them still worked and 1 or 2 of them didn't. That was before the reboot and manually re-applying dnf updates.)

4.8.5-18 and 4.8 both give simply a blinking cursor (no error messages). The ".config" one gives a grub error screen with `no multiboot header found` (after xen) followed by `you need to load the kernel first` twice (after linux, and after ramdisk).

My kernel versions (per grub menu) are 125, 107 and 94: 4.19.125-1, 4.19.107-1, 4.19.94-1

I found a few commits which look like they could have something to do with it. But none which really stand out to me.

These are the repos/branches i looked at:
https://github.com/QubesOS/qubes-linux-kernel/commits/stable-4.19
https://github.com/QubesOS/qubes-vmm-xen/commits/xen-4.8

Commits in no particular order...

This one has to do with "Apply TSX related fixes for Haswell/Broadwell CPUs". I believe my system, and several of the other folks on here (with Librem 13, 15) is affected by the TSX errata. Not sure how the fix could lead to not booting though.
https://github.com/QubesOS/qubes-vmm-xen/commit/1b204361e6b390a13c416f723f92abe1349d76a6

https://github.com/QubesOS/qubes-vmm-xen/commit/89e7e3325430d62986bd69fdd71929d69dd41161
https://github.com/QubesOS/qubes-vmm-xen/commit/55a8390b9b02f7fa4d7111666bf9b65d32c0ba46

This one has something to do with disabling vTPM. I know my system (Librem 13 v2) does NOT have a tpm in the hardware. Not sure if that could have anything to do with it.
https://github.com/QubesOS/qubes-vmm-xen/commit/875b8816da2986dfc8f68dcbda673ca327aed3f4

There's a cluster of kernel commits on Mar 7 which looks like they might possibly have something to do with this somehow. Maybe.

Particularly this one:
https://github.com/QubesOS/qubes-linux-kernel/commit/080c3ade5bcd7b7568d827b44e9ceb27df9ac595

Also, i'm no bash syntax expert but this seems like it has an extra " quote? (And shellcheck.net seems to agree.):
`@echo "verrel"          Echo version release"`

https://github.com/QubesOS/qubes-linux-kernel/commit/ca79d2d56fa464f6b7c23b856f891d11a17e5a57

**Comment by darwin** [comment] 2020-10-13 11:21
Just to add my observations. I have a Librem 13v2 with TPM in the hardware. I don't use it on daily basis so I update only once in 3 months or so. Last time I updated dom0 it was around July 13 which caused the machine to be unable to boot on next restart.

Here is my top-level GRUB boot menu (square brackets added by me):

```
[1] Xen hypervisor, version 4.8.5-18.fc25
[2] Xen hypervisor, version 4.8.5-18.fc25.config
[3] Xen hypervisor, version 4.8
```

The first item offers this submenu:
```
[1.1] Qubes, with Xen 4.8.5-18.fc25 and Linux 4.19.125-1.pvops.qubes.x86_64
[1.2] Qubes, with Xen 4.8.5-18.fc25 and Linux 4.19.107-1.pvops.qubes.x86_64
[1.3] Qubes, with Xen 4.8.5-18.fc25 and Linux 4.19.100-1.pvops.qubes.x86_64
```

The  second item offers this submenu:
```
[2.1] Qubes, with Xen 4.8.5-18.fc25.config and Linux 4.19.125-1.pvops.qubes.x86_64
[2.2] Qubes, with Xen 4.8.5-18.fc25.config and Linux 4.19.107-1.pvops.qubes.x86_64
[2.3] Qubes, with Xen 4.8.5-18.fc25.config and Linux 4.19.100-1.pvops.qubes.x86_64
```

The third item offers this submenu:
```
[3.1] Qubes, with Xen 4.8 and Linux 4.19.125-1.pvops.qubes.x86_64
[3.2] Qubes, with Xen 4.8 and Linux 4.19.107-1.pvops.qubes.x86_64
[3.3] Qubes, with Xen 4.8 and Linux 4.19.100-1.pvops.qubes.x86_64
```

Today I just tried to run all nine options and here are my observations:
a) 1.1 and 3.1 do not boot, I just see blinking cursor in the top left corner
b) 1.2, 1.3, 3.2 and 3.3 do boot as expected
c) 2.1, 2.2 and 2.3 do not boot with an error `no multiboot header found`, same as described @sptankard

I'm willing to do further testing if you can give me further instructions how to diagnose the situation. Thanks.

**Comment by darwin** [comment] 2020-10-13 14:43
@marmarek thanks,
1. all three initramfs files have good sizes
2. edited the broken entry as suggested, and I'm seeing very similar output to @ehanoc's screenshot, last line where it got stuck says `(XEN) Switched to APIC driver x2apic_cluster.`

**Comment by sptankard** [comment] 2020-10-13 19:12
It works! Thank you so much. I can now boot. (Tried 4.8.5-18 with 4.19.125.)

This is my main machine so life without it has been pretty difficult.

**Comment by ollieparanoid** [comment] 2020-10-20 07:55
I can confirm that the `loglvl=all` workaround makes the 4.19.128 kernel boot reliably on my Librem 13. I've verified it 6 times.

Thanks to everyone in this thread!

**Comment by ehanoc** [comment] 2020-10-20 08:27
4.8.5-18.fc25 + 4.19.125-1; 

I don't see **console=none** in the **multiboot** command.
But I haven't made any updates since i stumbled in to this, so maybe the new entries have such option.

Can a fix be included in a future release and flagged here? 

Also, why would a log level fix it? Is this a timing thing that just so happens that for now it works but it's not a long lasting solution?

**Comment by darwin** [comment] 2020-10-21 13:41
Today I was brave enough to update dom0. 

I'm happy to confirm that `loglvl=all` workaround works on my Librem 13v2 with: 4.8.5-23.fc25 + 4.19.147-1

btw. if you don't have `console=none` only add `loglvl=all` somewhere into multiboot line.

**Comment by ehanoc** [comment] 2020-10-21 14:16
Is there a way to safe the changes? I tried a few times and i need to add the loglvl=all everytime.

**Comment by marmarek** [comment] 2020-10-27 01:10
You can edit /etc/default/grub, then regenerate grub config with `grub2-mkconfig -o /boot/grub2/grub.cfg`

**Comment by byte255** [comment] 2020-10-31 06:21
@darwin your solution worked for me, thank you so much!

**Comment by andrewdavidwong** [comment] 2020-10-31 22:45
Is anyone still affected by this issue?

**Comment by darwin** [comment] 2020-11-01 00:10
AFAICT currently there is no solution to this issue. Only a workaround.

My theory is that the workaround currently happens to work because it slightly changes timing/order of boot instuctions and the real issue does not get triggered. Nothing I would like to rely on. 

Please keep this issue open until someone figures out the real cause and a possible solution.

**Comment by ollieparanoid** [comment] 2020-11-02 13:11
@andrewdavidwong: at least 4 people are still affected, judging by "thumbs up" above.

@marmarek's workaround works perfectly for me. But I also think that this is a timing issue, so nothing to rely on.

**Comment by darwin** [comment] 2021-06-30 18:25
Just reporting that the problem went away on my Librem 13v2.

Currently running `4.8.5-34.fc25 + 5.4.120-1.fc25.qubes.x86_64`

🤞

**Comment by DemiMarie** [comment] 2021-09-03 18:48
Is this fixed?

**Comment by DemiMarie** [comment] 2021-10-13 21:27
Closing as fixed.

**Closed by DemiMarie** 2021-10-13 21:27 UTC
Labels: T: bug, C: kernel, C: Xen, P: critical, hardware support, needs diagnosis
