### ISSUE TITLE
Failing to build ubuntu template - 4.0rc2

### ISSUE THREAD

**Issue by digital-nomad17** [QubesOS/qubes-issues#3310] opened 2017-11-14 23:21 UTC
#### Qubes OS version:

4.0rc2

#### Affected TemplateVMs: 

xenial(16) ubuntu template

---

### Steps to reproduce the behavior:

Followed the guide for building templates with 3.2 - https://www.qubes-os.org/doc/building-archlinux-template/. Only selected ubuntu(xenial) template to build. 

### Expected behavior:

To build qube-os iso which includes the template. 

### Actual behavior:

It fails with the following error:

```
-> Building gui-agent-linux (debian) for xenial vm (logfile: build-logs/gui-agent-linux-vm-xenial.log)
--> build failed!
install -m 0644 -D window-icon-updater/qubes-icon-sender.desktop \
	/home/user/qubes-src/gui-agent-linux/debian/tmp/etc/xdg/autostart/qubes-icon-sender.desktop
install -D -m 0644 appvm-scripts/usr/lib/sysctl.d/30-qubes-gui-agent.conf \
	/home/user/qubes-src/gui-agent-linux/debian/tmp/usr/lib/sysctl.d/30-qubes-gui-agent.conf
install -D -m 0644 appvm-scripts/usr/lib/modules-load.d/qubes-gui.conf \
	/home/user/qubes-src/gui-agent-linux/debian/tmp/usr/lib/modules-load.d/qubes-gui.conf
install -d /home/user/qubes-src/gui-agent-linux/debian/tmp/var/log/qubes
install -D appvm-scripts/etc/X11/xinit/xinitrc.d/qubes-keymap.sh \
	/home/user/qubes-src/gui-agent-linux/debian/tmp/etc/X11/Xsession.d/90qubes-keymap
install -d /home/user/qubes-src/gui-agent-linux/debian/tmp/etc/X11/Xsession.d
install appvm-scripts/etc/X11/Xsession.d/* /home/user/qubes-src/gui-agent-linux/debian/tmp/etc/X11/Xsession.d/
install -d /home/user/qubes-src/gui-agent-linux/debian/tmp/etc/xdg
install -m 0644 appvm-scripts/etc/xdg-debian/* /home/user/qubes-src/gui-agent-linux/debian/tmp/etc/xdg
install -m 0644 -D appvm-scripts/qubes-gui-agent.service \
	/home/user/qubes-src/gui-agent-linux/debian/tmp//lib/systemd/system/qubes-gui-agent.service
make[2]: Leaving directory '/home/user/qubes-src/gui-agent-linux'
make[1]: Leaving directory '/home/user/qubes-src/gui-agent-linux'
   debian/rules override_dh_install
make[1]: Entering directory '/home/user/qubes-src/gui-agent-linux'
dh_install --fail-missing
dh_install: qubes-gui-agent missing files: etc/xdg/Trolltech.conf
dh_install: missing files, aborting
debian/rules:24: recipe for target 'override_dh_install' failed
make[1]: *** [override_dh_install] Error 2
make[1]: Leaving directory '/home/user/qubes-src/gui-agent-linux'
debian/rules:12: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
/home/user/QubeDev/qubes-builder/qubes-src/builder-debian/Makefile.qubuntu:200: recipe for target 'dist-package' failed
make[2]: *** [dist-package] Error 2
Makefile.generic:156: recipe for target 'packages' failed
make[1]: *** [packages] Error 1
Makefile:212: recipe for target 'gui-agent-linux-vm' failed
make: *** [gui-agent-linux-vm] Error 1

```

### General notes:

---

**Comment by andrewdavidwong** [comment] 2017-11-15 02:24
This appears to be a duplicate of #3308. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-11-15 02:24 UTC
