### ISSUE TITLE
"Error starting VM: Cannot execute qrexec-daemon!"

### ISSUE THREAD

**Issue by stone212** [QubesOS/qubes-issues#3099] opened 2017-09-18 02:50 UTC
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs 

No template affected.  Relevant VM is based on Debian 9 template.

---

### Expected behavior:

When I start a VM, it should start. ")

### Actual behavior:

I receive the error "Error starting VM: Cannot execute qrexec-daemon!"  This happens regardless of how I start the VM, when in my session I start the VM, and persists after a reboot.

### Steps to reproduce the behavior:

Just try to open the affected VM.

### General notes:

1 - I do not have any reason to think this is connected to my other similar issue.  It might be but I don't see a connection, since that problem has gone away.  

2 - The affected VM was working fine yesterday and it is one that I use often.

3 - Debian 9 upgrade was successfull.  Other VMs using it are running.

4 - QUESTION: is there a way to recover data from this VM if I can't start it?
---

#### Related issues:

I don't actually know that this is related but it might be:

https://github.com/QubesOS/qubes-issues/issues/2882

**Comment by andrewdavidwong** [comment] 2017-09-18 03:45
> I do not have any reason to think this is connected to my other similar issue. It might be but I don't see a connection, since that problem has gone away.

Can you be more specific about why you think this isn't a duplicate of #2882? If that problem has gone away, can we close #2882?

**Comment by stone212** [comment] 2017-09-24 22:33
> Can you be more specific about why you think this isn't a duplicate of #2882?

I didn't say that I think it isn't a duplicate.  I said I have no reason to think that it is.

> If that problem has gone away, can we close #2882?

I hope that you do not.  That would not be a very good way of handling bugs.  If we haven't figured out what caused the problem, the fact that it went away is not a solution but a second mystery.  Maybe it was a recent update to dom0 that fixed it?  Maybe something else?  Is this scheduled to be worked on?  Do you need more information from me?  

I am still waiting for assistance on another bug report (unrelated so won't link) and you seemed to want to close that also, I think.  Is the goal to close tickets or to solve problems?

**Comment by andrewdavidwong** [comment] 2017-09-29 02:55
>> Can you be more specific about why you think this isn't a duplicate of #2882?
>>
> I didn't say that I think it isn't a duplicate. I said I have no reason to think that it is.

I didn't say that you *said* that you think it isn't a duplicate. I asked why you *think* it isn't a duplicate. :)

(If you didn't think it wasn't a duplicate in a case like this, it would be standard to add comments to the existing issue rather than file a new one. But it's not a big deal. My question was just a way of requesting more information, not an accusation or anything.)

> It happens at a different time to only one VM under a different set of circumstances.

These sound like reasons to think that it isn't a duplicate. :)

>> If that problem has gone away, can we close #2882?
>>
> I hope that you do not. That would not be a very good way of handling bugs.

Actually, closing issues for bugs that can't be reproduced is, in many cases, exactly the right thing to do.

> If we haven't figured out what caused the problem, the fact that it went away is not a solution but a second mystery. Maybe it was a recent update to dom0 that fixed it? Maybe something else? Maybe it will return as mysteriously as it arrived and left?

I agree, but it may not be an *actionable* mystery if it can't be reproduced. We may all agree that no solution has been found while also agreeing that we presently have no cost-effective means of discovering one. (Closing the issue wouldn't preventing it from being reopened if such a means were to become available in the future.)

> Is this scheduled to be worked on?

Yes, but only in the sense that all of our outstanding issues are scheduled to be worked on. We have many more open issues than we have person-hours to devote to them, so we cannot guarantee that the issue will be worked on according to a specific time line.

> Do you need more information from me?

Thank you for asking. Not at the moment. Anyone who needs more information will post a comment requesting it.

**Closed** 2019-04-01 04:16 UTC
Labels: C: core, T: bug

**Comment by andrewdavidwong** [comment] 2019-04-01 04:19
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
