### ISSUE TITLE
Arch Linux template build fails due to missing requirements

### ISSUE THREAD

**Issue by fisiognomico** [QubesOS/qubes-issues#6196] opened 2020-11-11 16:29 UTC
**Qubes OS version**
Qubes Release 4.0

**Affected component(s) or functionality**
Arch Linux Template

**Brief summary**
Building the template breaks in qubes 4.0 during the `make template` step. 

**How Reproducible**
It seems to persist even after a complete project cleanup.

**To Reproduce**

Steps to reproduce:
1. On a fresh building qube, follow each step on the [Building Archlinux template guide](https://www.qubes-os.org/doc/building-archlinux-template/) until step 7.
2. On step 7, before `make qubes-vm`, consider to fix the Pulseaudio issue in `gui-agent-linux` :
 * `cd qubes-src/gui-agent-linux/pulse`
 * `ln -s pulsecore-13.99.2 pulsecore-13.99.3`
In order to fix, as proposed, #6172 . In this way `make qubes-vm` should complete successfully.
3. On step 8, `make template`.

**Expected behavior**
1) To complete the make process without errors
2) To find the expected script and rpm file in `./qubes-src/linux-template-builder/rpm/`

**Actual behavior**
On step 8, `make template`, during the [qubes-builder-archlinux](https://github.com/QubesOS/qubes-builder-archlinux/)'s  scripts execution phase, in particular during `04_install_qubes.sh` execution, the make process breaks with the error

>   --> Installing mandatory qubes packages...
> error: target not found: qubes-vm-dependencies
> trap -- '' SIGFPE
> trap -- '' SIGXFSZ
> make[1]: *** [Makefile:66: rootimg-build] Error 1

from `build-logs/template-archlinux.log`

**Screenshots**

from `build-logs/template-archlinux.log`

> --> Archlinux 04_install_qubes.sh
[CUT]
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
> downloading multilib.db...
> downloading qubes.db...
>   --> Checking available qubes packages (for debugging only)...
> qubes/qubes-db-vm 4.0.15-5
>     QubesDB libs and daemon service.
> qubes/qubes-gpg-split 2.0.48-1
>     The Qubes service for secure gpg seperation
> qubes/qubes-libvchan-xen 4.0.8-2
>     The Qubes core libraries for installation inside a Qubes Dom0 and VM.
> qubes/qubes-usb-proxy 1.0.29-1
>     The Qubes service for proxying USB devices
> qubes/qubes-vm-core 4.0.58-15
>     The Qubes core files for installation inside a Qubes VM.
> qubes/qubes-vm-gui 4.0.31-10
>     The Qubes GUI Agent for AppVMs
> qubes/qubes-vm-gui-common 4.0.2-1
>     Common files for Qubes GUI - protocol headers.
> qubes/qubes-vm-kernel-support 4.0.31-10
>     Common Linux files for Qubes VM.
> qubes/qubes-vm-keyring 4.0.58-15
>     Qubes OS Binary Repository Activation package and Keyring
> qubes/qubes-vm-networking 4.0.58-15
>     Qubes OS tools allowing to use a Qubes VM as a NetVM/ProxyVM
> qubes/qubes-vm-pulseaudio 4.0.31-10
>     Pulseaudio support for Qubes VM
> qubes/qubes-vm-utils 4.0.31-10
>     Common Linux files for Qubes VM.
> qubes/qubes-vm-xen 4.8.5-25
>     Xen is a virtual machine monitor
>   --> Installing mandatory qubes packages...
> error: target not found: qubes-vm-dependencies
> trap -- '' SIGFPE
> trap -- '' SIGXFSZ
> make[1]: *** [Makefile:66: rootimg-build] Error 1

**Additional context**
I am a newbie to the Qubes world, so there might be a naive solution.

**Solutions you've tried**
Comment out the offending lines in `04_install_qubes.sh` where `qubes-vm-dependencies` is installed through the update proxy, but the problem seems to persist when trying to install other packages next up.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/building-archlinux-template/
https://www.qubes-os.org/doc/building-non-fedora-template/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#6172 
#6028 
#5929

**Comment by marmarek** [comment] 2020-11-11 17:21
Duplicate of #6172

**Closed by marmarek** 2020-11-11 17:21 UTC
Labels: P: default, T: bug
