### ISSUE TITLE
Nautilus stuck at "loading" in Fedora 37

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7921] opened 2022-11-30 12:26 UTC
## Observation

openQA test in scenario qubesos-4.1-templates-x86_64-system_tests_gui_interactive@64bit fails in
[gui_filecopy](https://openqa.qubes-os.org/tests/54646/modules/gui_filecopy/steps/12)

Files (nautilus) in fedora-37 opens up, but doesn't show any files, only "Loading" info in right bottom corner.

After clicking around for some times, the content finally showed up, but then after switching directory back and forth went back to "loading".

## Reproducible

Fails since (at least) Build [2022113002-4.1-fedora-37](https://openqa.qubes-os.org/tests/54576)

## Expected result

Last good: [2022111622-4.1-fedora-37](https://openqa.qubes-os.org/tests/53979) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=templates&machine=64bit&test=system_tests_gui_interactive&version=4.1)

Related to #7807

**Comment by marmarek** [comment] 2022-11-30 12:51
I see quite a few dbus errors when looking for `org.freedesktop.portal.*` services. Installing `xdg-desktop-portal-gtk` made them go away, but did _not_ fixed nautilus.

**Comment by noskb** [comment] 2022-11-30 13:52
Perhaps it can be fixed by calling an external command asynchronously?

**Comment by marmarek** [comment] 2022-11-30 13:55
Which command? The copy to vm isn't involved here yet, it's at nautilus startup.

**Comment by noskb** [comment] 2022-11-30 13:59
Ah, I thought `subprocess.call` caused nautilus stucks.

**Comment by meithecatte** [comment] 2023-01-08 18:32
Is that a typical xen-based qubes being ran in KVM, with nested virtualization, or is it using Qubes's hypervisor abstraction layer.

**Comment by DemiMarie** [comment] 2023-01-08 22:12
> Is that a typical xen-based qubes being ran in KVM, with nested virtualization, or is it using Qubes's hypervisor abstraction layer.

The former.  I wonder if some sort of timeout is being hit.

**Comment by marmarek** [comment] 2023-01-09 00:09
Could be, but I'd expect any kind of error message in that case...

**Comment by meithecatte** [comment] 2023-01-17 19:57
I traced this back to a callback registered through `vfs_file_call_when_ready`, which later *does* gets marked as satisfied in `call_ready_callbacks`, but when the code attempts to schedule it to actually get called "at idle", something goes wrong and it doesn't get called. I'll debug this further.

**Comment by meithecatte** [comment] 2023-01-19 02:30
Notably, the conditional *does* get entered, so the issue is that the GLib event loop somehow doesn't get to execute this callback. This is either because there are higher-priority things occupying the event loop, or because the event loop itself gets stuck somehow.

I am not sure how to go about debugging what's happening within the event loop.

**Comment by meithecatte** [comment] 2023-01-19 02:34
On the off chance the event loop is actually multi-threaded, I tried assigning 2 VCPUs to the domain I was testing this with (as opposed to the 1 VCPU it was running with before). This caused the bug to reproduce much less often – it went from reproducing almost 100% of the time, to the directory actually getting loaded within about 3 tries.

**Comment by marmarek** [comment] 2023-01-19 03:00
> On the off chance the event loop is actually multi-threaded, I tried assigning 2 VCPUs to the domain I was testing this with (as opposed to the 1 VCPU it was running with before). This caused the bug to reproduce much less often – it went from reproducing almost 100% of the time, to the directory actually getting loaded within about 3 tries.

That sounds like an explanation why it's hard to reproduce outside of openQA - normally there are 2 vcpus by default. That said, I can not reproduce it locally even when assigning only 1 vcpu. But that could be also about CPU speed (the one within nested virt is rather slow).

**Comment by marmarek** [comment] 2023-01-27 04:24
Summary of @meithecatte debugging: it isn't "something stuck causing content not loading and thus stuck at 'loading' message". It's "the rendering of the loading message causing content not loading"!
So, I'm joining GTK haters club.

In fact, disabling the spinning makes Nautilus immediately load the content:
![RecApp-2023-01-26-23:20:04](https://user-images.githubusercontent.com/726704/215008923-ba9bec1e-6544-4e72-9bcd-5b38dec61f30.gif)

**Comment by marmarek** [comment] 2023-01-27 05:47
Reported upstream: https://gitlab.gnome.org/GNOME/nautilus/-/issues/2814

**Comment by rustybird** [comment] 2023-01-30 23:11
`GDK_DEBUG=gl-disable` (that's G**D**K, not G**T**K) seems to make GTK 4 based programs like Nautilus less excruciatingly slow

**Comment by DemiMarie** [comment] 2023-01-30 23:21
I am not surprised.  GTK4 is designed assuming that GPU acceleration will be available, and uses OpenGL for rendering even if no GPU is present.

**Comment by rustybird** [comment] 2023-01-30 23:42
Maybe Qubes should ship a bunch of configuration files for common toolkits and programs to disable this kind of indirection? (Another example: `vo=x11` in `/etc/mpv/mpv.conf`)

**Comment by DemiMarie** [comment] 2023-01-30 23:47
The problem is that the alternate backend (Cairo) is not fully functional (it does not implement 3D transformations) and so enforcing its use will cause some programs to not render correctly.

**Comment by GWeck** [comment] 2023-02-18 10:12
Nautilus still hangs when opening an SMB share on some other (Windows) VM.

**Comment by DemiMarie** [comment] 2023-02-19 02:26
@GWeck Please open a separate bug.

**Comment by swamba** [comment] 2023-04-21 12:41
This does not completely fix the issue. This still happens when you open a new tab.

As I understand it then the fix involved removing the spinner from the popup in the lower right corner that says "Loading" while the app reads in the directory. Well that spinner also appears when you open a new tab and lo and behold, the tab is frozen. Only way to get back to a working Nautilus is to close that tab with ctrl-w or right click on the tab and select close.

**Comment by marmarek** [comment] 2023-04-25 01:12
> This does not completely fix the issue. This still happens when you open a new tab.

Which version of qubes-gui-agent package do you have there? The 4.1.29 or newer has alternative fix that should handle that spinner too.

**Comment by marmarek** [comment] 2023-05-15 13:41
> What is the status of getting qubes-gui-agent 4.1.29 or newer into the current repo?

Just to be clear: does this version fix the issue for you?

**Comment by marmarek** [comment] 2023-05-15 14:33
Thanks. I'll migrate it to the "current" repo today.

**Comment by ckaspro** [comment] 2023-06-28 04:09
I would like to re/open this issue again - context:
The issue occurs as per initial description, but upon opening a new tab. "killing" the spinner (as per Marks comment https://github.com/QubesOS/qubes-issues/issues/7921 ) either on the bottom- right, or left next to the text in the new tab opens the content ok.
Workaround is to simply open a new window, instead a new tab.

System:
- Qubes: r4.2
- Template: fedora-37

**Comment by ckaspro** [comment] 2023-07-03 02:56
If I see this correct, this resolved the issue - thank you! :)

FYI, on the fedora-38 template which just came out, the issue is not visible, either!

**Comment by andrewdavidwong** [comment] 2023-07-04 08:38
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Closed by andrewdavidwong** 2023-07-04 08:38 UTC
Labels: T: bug, C: Fedora, P: default, r4.1-buster-stable, r4.1-bullseye-stable, r4.1-dom0-stable, needs diagnosis, r4.1-bookworm-stable, r4.1-fc36-stable, r4.2-host-cur-test, r4.1-fc37-stable, r4.2-vm-centos-stream8-stable, r4.2-vm-bullseye-stable, r4.2-vm-fc36-stable, r4.2-vm-fc37-stable, r4.2-vm-bookworm-stable, r4.2-vm-fc38-cur-test, r4.1-fc38-cur-test
