### ISSUE TITLE
monitor layout change regression in 4.0-rc2

### ISSUE THREAD

**Issue by o-** [QubesOS/qubes-issues#3253] opened 2017-10-29 14:30 UTC
#### Qubes OS version:

4.0-rc2

#### Affected TemplateVMs: 

all

---

### Steps to reproduce the behavior:

Start i3 with the default configuration from qubes-i3 package. Change layout (e.g. add an external monitor) with xrandr.

### Expected behavior:

All appvms get notified of the layout change.

### Actual behavior:

The clickable area in all running appvms is not updated (only the area of the previous virtual screen are clickable). Rebooting the appvm updates the layout.

### General notes:

I had this issue in older releases and was able to resolve it with `qubes-monitor-layout-notify`. Unfortunately this script was removed in https://github.com/QubesOS/qubes-gui-daemon/commit/25aa33c by @woju . I was not able to find this service in core-admin, as the commit message suggests. Grepping for relevant strings only surfaces a layout-notify event in the gui daemon, but I can't find the actual implementation.

Also it seems, that the gui-daemon-repo still has a references to the removed script in https://github.com/QubesOS/qubes-gui-daemon/blob/cf7cdd09fb425bd37fc6b58cd19222729bb125df/screen-layout-handler/qubes-screen-layout-watches.desktop .

Since I did not find the replacement mechanism, I was not able to debug the issue. If you can point me to it I am happy to investigate further.

--

**Comment by marmarek** [comment] 2017-10-29 16:48
Try `qvm-start-gui --notify-monitor-layout`

**Comment by o-** [comment] 2017-10-30 08:29
@marmarek that works

**Comment by o-** [comment] 2017-10-30 10:04
So what is the expected behavior? Should the notify be triggered automatically, or does the WM have to watch it?

In the second case I could create a PR against qubes-desktop-linux-i3, since I have some other qubes 4.0 changes for it.

**Comment by tasket** [comment] 2017-10-31 11:30
BTW, I have experienced this with Xfce.

**Comment by GAhlekzis** [comment] 2017-11-24 09:33
I experience this in 3.2 with i3wm at the moment. Never had this before and now it happens rather often.

The funny thing is, that it mostly happens with one of my few debian vms. I don't think I ever noticed it with another vm.

**Comment by DTMW2** [comment] 2018-07-23 14:08
This bug is still active (at least in my system: Thinkpad X1C 5th, Qubes 4 with newest updates installed in both dom0, fedora and debian). Duplicate bug-report: #4052

**Comment by bertrandlec** [comment] 2018-08-03 17:23
I have the same issue with a fresh install of R4.0 on Lenovo T580 with an external screen. However, qvm-start-gui --notify-monitor-layout does not work for me.

**Comment by o-** [comment] 2018-08-06 08:27
The issue in this bug seemed like the `qvm-start-gui --notify-monitor-layout` event was not triggered, when the layout changed. This got fixed at some point, at least for me it started to work properly.

There is a new bug, which was reported in #3984, where calling `qvm-start-gui --notify-monitor-layout` does not help.

We should probably close at least one of those two reports.

**Comment by andrewdavidwong** [comment] 2018-08-07 03:27
> There is a new bug, which was reported in #3984, where calling `qvm-start-gui --notify-monitor-layout` does not help.
> 
> We should probably close at least one of those two reports.

Why, exactly?

@bertrandlec just reported that `qvm-start-gui --notify-monitor-layout` didn't work for him/her for this issue either. Or do you think that @bertrandlec is actually experiencing #3984 instead of this issue? Or are you suggesting that these two issues are actually duplicates?

**Comment by v6ak** [comment] 2018-08-07 06:31
I have briefly looked at #3984 and it looks like the same issue.

In order to have layout changes working properly, one needs:

1. When some layout change is performed (monitor added/removed/rotated/moved/resized/…), it should trigger layout change notification.
2. Layout change notification works well.

This looks like both have `qvm-start-gui --notify-monitor-layout` not working, so step 2 does not work well. We cannot tell if step 1 works well.

In Q3.2, I remember several factors that can break layout change notification. Some of them may also apply for Q4:

* Some VM is paused. (Notification often works well for VMs notified before this one, but they break for the paused VM and all VMs that would be notified after the paused VM.)
* Some VM has a broken qrexec connection. (Similar case to paused VM.)
* Some VM is starting/stopping. (Similar case to paused VM.)
* Sometimes, it breaks with no apparent reason, but a subsequent call succeeds. I call it explicitly from autorotate script (it automatically rotates screen and some pointing input devices according to accelerometers) and it seems to lower the failure rate, but it still sometimes fails anyway, not sure why.
-- 
Sent from my fruity BlackBerry device with K-9 Mail. Please excuse my brevity.

**Comment by o-** [comment] 2018-08-07 06:52
@andrewdavidwong
> Or do you think that @bertrandlec is actually experiencing #3984 instead of this issue?

yes, sorry for not being clear. This bug was about VMs not being notified about layout change. I think this bug got fixed (maybe even accidentally), without ever being closed. But I can't be sure, because currently, even if VMs get notified, the layout is not updated.

Currently, what @bertrandlec and myself are observing is, that even if we manually execute the notify command, running VMs do not get an up-to-date monitor area. Which seems to be  what #3984 describes.

**Comment by andrewdavidwong** [comment] 2018-08-08 00:26
Closing #3984 as a duplicate of this issue. If you believe that #3984 is not really a duplicate, please leave a comment on #3984 briefly explaining why. We'll be happy to take another look and, if appropriate, reopen that issue. Thank you.

**Comment by o-** [comment] 2018-08-08 09:15
Current status on 4.0 all updates applied:

When I change the monitor layout, or when I call `qvm-start-gui --notify-monitor-layout`, the gui-demon *does* notify the VMs, but with wrong parameters.

In the guid.vm.log I see (in fact several per layout change) entries like:
`reloading X server parameters...`

On the app vm `qubes-set-monitor-layout` gets called. The problem seems to be, that the app VM does see the second monitor as disconnected.

As a concrete example, my xrandr (shortened, since I have to type it)
```
Screen 0: minimum 320 x 200, xurrent 4480 x 1600, maximum 8192 x 8192
eDP-i connected primary 1920x1080+0+520 (normal left inverted right x axis y axis) 309mm x 174mm
  ...
PD-1 disconnections
...
DP-2 connected 2560x1600+1920+0 (normal left inverted right x axis y axis) 641mm x 401mm
  ...
```

Tthen the configuration that the app vm receives is:
`--output DUMMY0 --mode QB1920x1080 --pos 0x520 --set WIDTH_MM 325 --set HEIGHT_MM 182 --output DUMMY1 --mode QB2560x1600 --pos 1920x0`

If I apply this one, I get
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  186
  Current serial number in output stream:  187
```

The culprit seems to be the `--pos 1920x0`, if I remove that (or pass `0x0`), then it works.


For reference, this is what an app vm with broken display shows:
```
Screen 0: minimum 64 x 64, current 1920 x 1080, maximum 32767 x 32767
DUMMY0 connected primary 1920x1080+0+0 325mm x 182mm
   QB1920x1080   46.10*+
DUMMY1 disconnected
   QB2560x1600   59.99  
```
if I remove the `pos` argument, then it shows:
```
Screen 0: minimum 64 x 64, current 2560 x 1600, maximum 32767 x 32767
DUMMY0 connected primary 1920x1080+0+0 325mm x 182mm
   QB1920x1080   46.10*+
DUMMY1 connected 2560x1600+0+0 0mm x 0mm
   QB1920x1080   46.10 +
   QB2560x1600   59.99* 
```
This is what a freshly started vm shows:
```
Screen 0: minimum 64 x 64, current 4480 x 1600, maximum 32767 x 32767
DUMMY0 connected primary 1920x1080+0+520 325mm x 182mm
   QB4480x1600   31.17 +
   QB1920x1080   59.96* 
DUMMY1 connected 2560x1600+1920+0 0mm x 0mm
   QB4480x1600   31.17 +
   QB2560x1600   59.99* 
```

My guess is that the dummy display driver has some bug calculating the overall screen size.

**Comment by o-** [comment] 2018-08-08 09:29
Btw. I just noticed that there might be in fact be two issues here:

1. gui-demon does not send `--pos 0x520` for DUMMY0
2. display driver does not accept `--pos 1920x0` for DUMMY1

On the other hand, is the `pos` even necessary?
When I experiment with different translations, it seems like the translation in the app vm does not matter at all, and app VMs with different screen positions, draw the windows in the same place (as dictated by dom0).

**Comment by v6ak** [comment] 2018-08-08 10:08
AFAIU, pos is needed in order to know the clickable area. Without pos, I guess both pos would be 0x0, meaning those areas are seen as overlapping. This is usually the case of screen mirroring, but it is not what you want for two separate screens.

Window position is determined by dom0, and the actual window position can be outside of the domU's virtual screen area. The “only” drawback for most of the situation is reduced clickable area.

On August 8, 2018 11:29:27 AM GMT+02:00, its me <notifications@github.com> wrote:
>Btw. I just noticed that there might be in fact be two issues here:
>
>1. gui-demon does not send `--pos 0x520` for DUMMY0
>2. display driver does not accept `--pos 1920x0` for DUMMY1
>
>On the other hand, is the `pos` even necessary?
>When I experiment with different translations, it seems like the
>translation in the app vm does not matter at all, and app VMs with
>different screen positions, draw the windows in the same place (as
>dictated by dom0).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/3253#issuecomment-411345405

-- 
Sent from my fruity BlackBerry device with K-9 Mail. Please excuse my brevity.

**Comment by phagara** [comment] 2018-08-28 15:12
I'm having the same issue. Using i3wm, the monitor layout is broken in domUs (as described in https://github.com/QubesOS/qubes-issues/issues/3253#issuecomment-411341716 ) and I'm unable to use mouse on any domU window when it's located on other than the first screen.

Has anyone found a workaround for this? It makes multi-monitor setups pretty much unusable.

**Comment by bertrandlec** [comment] 2018-08-28 21:58
Just an update on the subject: since when I confirmed the issue, I could not reproduce it. I absolutely do not know what I could have done to correct it!!! Maybe, it's a way to disconnect the screen that lead to this problem, I don't know. I'll still monitor this and if i get new information of a better characterization, I will come back :)

Bertrand

**Comment by phagara** [comment] 2018-08-29 09:47
Update: it appears having 2 FHD monitors (laptop screen + external) side-by-side or stacked works just fine. The issue manifests itself only when you specify --pos different than 1920x0 or 0x1080. Even if layout applies without errors in domUs, parts of the screen will be unclickable.

**Comment by DTMW2** [comment] 2018-09-06 10:08
I think during time/updates the problem got even worse (or is just bad at all):

When I start a VM with 4K monitor attached everything is fine, when I detach that monitor and VM windows switch back to my Full HD main screen everything is fine.

When I re-attach the 4K monitor all VMs continue to only detect mouse input in the upper left "full HD corner" of that monitor.

**Comment by v6ak** [comment] 2018-09-06 11:39
When you detach the screen, there is not so much what can go immediately wrong in your setup. Probably either of those will happen:

a. Your remaining screen will match. This is likely when your old screen was at the right side or on the bottom. The VM would also see the old screen, but this would have not much an effect. Clickable area will not be affected. Some apps (e.g., notifications, slideshows and some other full-screen apps) might try to use the non-existant screen. However, dom0 GUId AFAIK does not allow showing anything outside of screen, so the content would be probably moved to the only real screen. It could cause some issues, however, especially when the screens have a different density or when they have a different resolution.
b. Your remaining screen will be considered as a part of the old screen by the AppVM. I would expect this if the disconnected screen was on left side or on top. Again, clickable area is not affected. Some full-screen apps might have similar issues. Issues related to different screen density are more likely there.

If the detached screen was a smaller one, it could however cause some non-clickable areas.

**Comment by marmarek** [comment] 2018-09-14 00:44
The formula is here: https://github.com/QubesOS/qubes-gui-agent-linux/blob/198077e2d9b5cb95a286df6d3274df99dc869c62/appvm-scripts/usrbin/qubes-run-xorg#L39-L41

As seen in the comment, margin for dynamic allocation is large enough for (only) one FHD monitor. Maybe that margin should be increased?

**Comment by lvh** [comment] 2019-01-23 16:46
FWIW I no longer have a  /etc/X11/xorg-qubes.conf file in dom0 on current 4.x.

**Comment by rollick** [comment] 2019-02-17 14:12
I was having a related issue when connecting a QHD monitor to a laptop *after* the VM was running. My workaround is to add the following in the /rw/config/rc.local file in each VM:

    qubesdb-write /qubes-gui-videoram-min 33301

I got 33301 by starting the VM after the QHD monitor was connected and checking VideoRam in /etc/X11/xorg-qubes.conf.

/qubes-gui-videoram-min is used here when creating the xorg config:

https://github.com/QubesOS/qubes-gui-agent-linux/blob/000561482ab5e80853eac8ca8c3b47ded0051c11/appvm-scripts/usrbin/qubes-run-xorg#L41

I am not sure if it is possible to persist a qubesdb-write call because then it wouldn't be necessary to always call it via rc.local.

**Comment by marmarek** [comment] 2019-02-17 18:27
See https://www.qubes-os.org/doc/gui-configuration/

**Comment by rollick** [comment] 2019-02-19 09:52
> See https://www.qubes-os.org/doc/gui-configuration/

Thanks!

**Comment by o-** [comment] 2019-02-19 17:01
> See https://www.qubes-os.org/doc/gui-configuration/

doesn't seem to change anything here. Do I need to reboot dom0?

**Comment by marmarek** [comment] 2019-03-10 01:16
@o- only affected VMs (which may mean all of them...).

**Comment by o-** [comment] 2019-03-11 10:15
@marmarek 

it still does not work here. The bug as I initially reported it still persists. Every time I attach my external monitor I have to restart all vm's which I started when the monitor wasn't attached.

xrandr reports a screen size of `4480x1600`, as per the wiki suggestion I set `gui-videoram-min` to 2800 (I also tried much larger values, for testing).

This is the xrandr line I am using:
```
xrandr --output eDP-1 --mode 1920x1080 --pos 0x320 --rotate normal --output DP-2 --primary --mode 2560x1600 --pos 1920x0 --rotate normal
```

**Comment by marmarek** [comment] 2019-03-11 10:43
Just to confirm, have you executed
```
qvm-features dom0 gui-videoram-min $(($WIDTH * $HEIGHT * 4 / 1024))
qvm-features dom0 gui-videoram-overhead 0
```
with values calculated as described on https://www.qubes-os.org/doc/gui-configuration/ ?

**Comment by marmarek** [comment] 2019-03-11 10:53
Also, what version of qubes-core-dom0 in dom0 do you have and qubes-gui-agent in VMs?

**Comment by marmarek** [comment] 2019-03-11 11:21
28000 looks like a correct value. See what you get in X server log inside VM (`/var/log/Xorg.0.log` or `~/.local/share/xorg/Xorg.0.log`).

**Comment by o-** [comment] 2019-03-11 15:17
thanks for the pointers!

> (I also tried much larger values, for testing)

I guess this part I only did in my imagination (or the situation somehow changed since I last looked into it).

After some more thorough testing I observed the following. With the setting to 28000 I get:

```
DUMMYQBS(0): Unable to set up a virtual screen size of 4480x1600 with 28000 Kb of video memory available.  Please increase the video memory size.
```

If I increase by 1 to 28001 it works (and no msgs in xorg.0.log).

so I guess either the implementation or the documentation has an off by 1 error.

> Also, what version of qubes-core-dom0 in dom0 do you have 

4.0.38

> and qubes-gui-agent in VMs?

4.0.20

**Comment by marmarek** [comment] 2019-03-11 16:14
Yes, it is off by one error!

**Closed** 2019-03-20 21:43 UTC
Labels: C: desktop-linux, C: gui-virtualization, P: major, bug

**Comment by Zrubi** [comment] 2019-04-26 11:55
I still have this issue even after updated qubes-gui-agent (4.0.23)
it means Qubes is unusable with external monitor in practice, which is a huge regression :(

However, not sure what to check/debug to create more useful report about this issue.

**Comment by marmarek** [comment] 2019-04-26 11:58
Have you set `gui-videoram-min`? See https://www.qubes-os.org/doc/gui-configuration/

**Comment by Zrubi** [comment] 2019-04-26 12:03
Ohh, yeah. I misset that step.

Now I can confirm that missing step fix this issue :)

**Comment by runephilosof** [comment] 2019-12-18 13:57
> On the app vm `qubes-set-monitor-layout` gets called. But the xrandr command fails to get applied. The dummy driver seems to not correctly handle `--pos` arguments.

I can't find the log file where @o- found this in.
What logs do I need to check?
