### ISSUE TITLE
Building Debian Template with qubes-builder fails

### ISSUE THREAD

**Issue by Marduk218** [QubesOS/qubes-issues#4778] opened 2019-01-29 03:55 UTC
### Qubes OS version:
R4.0

### Affected component(s):
qubes-builder on fedora-29
building debian-9 and debian-9-minimal templates

---

### Steps to reproduce the behavior:
1. clone and verify qubes-builder
2. run qubes-builder/setup.sh
3. import keys
4. select builder-debian
5. select stretch+minimal, unselect all other templates
6. `make install-deps && make get-sources && make qubes-vm && make template`

### Expected behavior:
`make template` succeeds, producing an debian-9-minimal rpm

### Actual behavior:
`make template` fails with following error message in the template-stretch.log:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qubes-vm-dependencies : Depends: qubes-gui-agent but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100
```

### General notes:
The error occurs too, when building the standard, non-minimal stretch template.
Same result, when building is performed in a fedora-28 VM.
Full [template-stretch.log](https://github.com/QubesOS/qubes-issues/files/2805969/template-stretch.log) is attached.

---

### Related issues:
none that I'm aware of.

**Comment by marmarek** [comment] 2019-01-29 16:53
Have you seen any errors while gui-agent was built? You can also verify if it's built with `make check-release-status` - it should output "built, not released" for gui-agent-linux.

**Comment by unman** [comment] 2019-01-29 23:36
@Marduk218  I followed all your steps on a newly installed Fedora-29, and built the template without issue. Also the templates have been built recently using the automated build system.

(The particular error does looks familiar to me: I think a broken dependency in qubes-gui-agent? But that was fixed some time ago.)
If you check as Marek suggests, and all looks well, then you  can either set DEBUG and VERBOSE values, and run `make template` again, or chroot in to the template and try to install the package manually.

Either way you should be able to identify *why* qubes-gui-agent will not be installed.

**Comment by unman** [comment] 2019-02-19 12:38
@Marduk218  Were you able to identify the issue that prevented you from building the template?

**Comment by unman** [comment] 2019-03-06 00:27
@andrewdavidwong In the absence of any response from @Marduk218 , and since the build succeeds, I suggest this be closed.

**Comment by andrewdavidwong** [comment] 2019-03-06 01:57
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by andrewdavidwong** [comment] 2019-10-26 23:19
Reopening due to #5419

**Comment by andrewdavidwong** [comment] 2019-10-29 05:24
@unman [pointed out](https://github.com/QubesOS/qubes-issues/issues/5419#issuecomment-546983660) that #5419 is not actually a duplicate of this issue and that neither issue should be open. Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), they do not appear to be suitable for `qubes-issues`. We ask that everyone with this type of problem post to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Closed by andrewdavidwong** 2019-10-29 05:24 UTC
Labels: C: Debian/Ubuntu, C: builder, P: default, T: bug
