### ISSUE TITLE
`dispvm_netvm` cannot be set to 'none' with `qvm-prefs`

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1295] opened 2015-10-08 00:59 UTC
```
[user@dom0 ~]$ qvm-prefs -l untrusted
[...]
dispvm_netvm       : sys-firewall
[...]
[user@dom0 ~]$ qvm-prefs -s untrusted dispvm_netvm none
[user@dom0 ~]$ qvm-prefs -l untrusted
[...]
dispvm_netvm       : sys-firewall
[...]
[user@dom0 ~]$ qvm-prefs -s untrusted dispvm_netvm
Missing netvm name argument!
Possible values:
1) default (the same as VM own netvm)
2) none
3) <vmname>
[user@dom0 ~]$ qvm-prefs -s untrusted dispvm_netvm 2
A VM with the name 'None' does not exist in the system.
[user@dom0 ~]$
```

**Comment by marmarek** [comment] 2015-10-08 01:02
Duplicate of #1272

**Closed by marmarek** 2015-10-08 01:02 UTC
