### ISSUE TITLE
R3.2 Fedora 28 qubes-firewall service fails Another app is currently holding the xtables lock

### ISSUE THREAD

**Issue by dmfreemon** [QubesOS/qubes-issues#4250] opened 2018-08-26 17:11 UTC
### Qubes OS version:

R3.2
Fedora 28 Template based VMs

### Affected component(s): 

qubes-firewall service
when using:
/rw/config/qubes-firewall-user-script

---

### Steps to reproduce the behavior:

After upgrading guest VMs to use F28 template, service qubes-firewall (somewhat non-deterministically, but almost always - after starting a AppVM dependent on the ProxyVM in question) fails with:

Aug 26 10:07:50 sys-vpn systemd[1]: Started Qubes firewall updater.
Aug 26 10:12:09 sys-vpn qubes-firewall[777]: /qubes-iptables
Aug 26 10:12:09 sys-vpn qubes-firewall[777]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Aug 26 10:12:09 sys-vpn systemd[1]: qubes-firewall.service: Main process exited, code=exited, status=4/NOPERMISSION
Aug 26 10:12:09 sys-vpn systemd[1]: qubes-firewall.service: Failed with result 'exit-code'.

### Expected behavior:

The qubes-firewall service does not crash, and that the iptables rules are correctly updated.

### Actual behavior:

The qubes-firewall service crashes, and the iptables rules are not correctly updated.

### General notes:

I found the "workaround" to be to include the "-w" option on all iptables commands in qubes-firewall-user-script.

I put the word workaround in quotes as I think this is probably not a qubes problem per se, and that using the '-w' option is probably the right thing to do anyway.

I create this issue here for three reasons:
(a) The Qubes documentation does not discuss the need to use the wait option.  https://www.qubes-os.org/doc/firewall.  It probably should.
(b) Other Qubes users will almost certainly encounter this problem, and this post may be of some value to them.
(c) In the event this might also affect R4 (I have not looked). 

---

**Comment by andrewdavidwong** [comment] 2018-08-26 18:36
Duplicate of #3939

**Comment by andrewdavidwong** [comment] 2018-08-26 18:36
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-26 18:36 UTC

**Comment by dmfreemon** [comment] 2018-08-26 18:56
I did see that, but I didn't consider it to be a duplicate for these reasons:

* different versions (R3.2 vs R4)
* different system service involved (qubes-iptables vs qubes-firewall)
* different files involved (during my investigation, some of the files involved this (this) issue do not exist in R4 branch of the repos)
* the fix for R4 (#3939) does not fix (this) issue 

My system is fully up-to-date, as will be others running R3.2, and yet, this issue currently remains an issue regardless of the state of the R4 fix.

**Comment by andrewdavidwong** [comment] 2018-08-26 20:58
> different versions (R3.2 vs R4)

When a bug affects both versions, we have one issue covering both versions.

> different system service involved (qubes-iptables vs qubes-firewall)

If it's the same underlying cause, there should be a single issue. Unless you know for certain that that's not the case here, there is a presumption that it is, and I think we should let the devs decide if it's not.

> different files involved (during my investigation, some of the files involved this (this) issue do not exist in R4 branch of the repos)

It seems like the devs just forgot to fix it for the 3.2.

> the fix for R4 (#3939) does not fix (this) issue

Did you attempt to apply the 4.0 fix to 3.2 somehow? Given your point above about different files, it might be more involved than that, but it should still be covered by #3939.
