### ISSUE TITLE
Fedora-28 template update hangs

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#4599] opened 2018-12-11 11:08 UTC
### Qubes OS version:

R3.2

### Affected component(s): 

Fedora-28 template

---

### Steps to reproduce the behavior:

Starting an update of the template VM for Fedora-28 via the Qubes manager or via the command dnf upgrade starts the upgrade, but after downloading the relevant files, the update process starts, runs for some time, and then stops at various points, e.g. when updating vim-common. If the VM is killed and the update is restarted, it starts at the point where it was interrupted, but the interrupted package does not seen to get updated.

### Expected behavior:

The update should run till the end.

### Actual behavior:

After several restarts, most of the template is updated but not everything. Qubes Manager still shows that there are updates for the template, but these cannot be installed, as the updated process claims that there is nothing to do.

### General notes:

Sometimes, starting the update via "dnf upgrade --best --allowerasing" gets around the problem for some packages, but most of the time not.

---

**Comment by marmarek** [comment] 2018-12-11 22:22
Look similar to #4466
Can you check the process list in that template when it hangs?

**Comment by GWeck** [comment] 2018-12-12 16:13
I tried to check, using a newly created template, and it updated flawlessly.
Maybe the template I used previously, dated 21.10.2018, was faulty, and the fault has meanwhile been repaired.
Probably it is best to close this issue now, as it is no longer reproducible. Thanks anyway!

**Comment by andrewdavidwong** [comment] 2018-12-13 02:30
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-12-13 02:30 UTC
Labels: C: Fedora, bug
