### ISSUE TITLE
BTRFS external mechanical USB HD mounts in AppVm with "SSD" option

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#4862] opened 2019-03-07 14:51 UTC
### Qubes OS version:

R4.0 (4.01)

### Affected component(s) or functionality:

When an external USB Hard Disk (mechanical) containg a BTRFS partition is connected to an AppVm and auto-mounted (i.e. using the file manager), its BTRFS partition gets mounted with the "ssd" option.

This is wrong, and annoying because the BTRFS filesystem does'nt behave the same (i.e. for keeping metadata copies and avoiding - or not - to fragment files) when working with a mechanical device or a SSD.

---

### Steps to reproduce the behavior:

Connect an external USB hard disk containg a BTRFS partition. Allocate it to an AppVm. Open it with the file manager.

Open a terminal and check with the "mount" command that the disk has ben mounted as a SSD.

### Expected or desired behavior:

The system should be able to identify whether the disk is mechanical or an SSD.

### Actual behavior:

The system always identifies the disk as an SSD.

### General notes:

BTRFS mount determines whether or not a disk is an SSD by checking if /sys/devices/.../block/xvd<something>/queue/rotational is either 0 or 1.

HDs should have "1" and SSDs should have "0".

The ways Qubes works seems to have the kernel think that the device is never "rotational" : always 0

---

**Comment by marmarek** [comment] 2019-03-07 19:17
Looks like a missing feature of Xen block device drivers (xen-blkback + xen-blkfront).
Actually, looks like Linux kernel treat all paravirtual devices a SSD by design: https://github.com/torvalds/linux/commit/88e740f1654bf28565edd528a060695c1f2b5ad7

**Comment by andrewdavidwong** [comment] 2019-03-08 02:02
> Actually, looks like Linux kernel treat all paravirtual devices a SSD by design: [torvalds/linux@88e740f](https://github.com/torvalds/linux/commit/88e740f1654bf28565edd528a060695c1f2b5ad7)

Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2019-03-08 02:02 UTC
