### ISSUE TITLE
double terminals shortcuts with one right click

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1670] opened 2016-01-21 20:40 UTC
- when u click "right click" inside whonix files (anywhere) it will show up two terminals:- 

(zoom in if u cant c it clearly)

https://forums.whonix.org/uploads/default/original/1X/6a279c239566a374fbf51c01911b63b8d63b25c0.png

**Comment by adrelanos** [comment] 2016-01-22 00:08
Cross linking them:
https://forums.whonix.org/t/two-terminals-shortcuts-with-one-right-click-whonix-specific

**Comment by adrelanos** [comment] 2016-01-23 13:35
Another screenshot by @TNTBOMBOM.
https://cloud.githubusercontent.com/assets/11895339/12508683/5ab8a914-c0f5-11e5-978e-ace13c9fffd7.png

Is this the same underlying issue?

Does this still require analysis or do you already have a guess what is causing this?

**Comment by TNTBOMBOM** [comment] 2016-01-23 13:41
yeah i think it is because of:- 

> "Tor Browser"

first one:-

qubes-desktop-run /usr/share/applications/anondist-torbrowser.desktop

second one:-

qubes-desktop-run /usr/share/applications/janondisttorbrowser.desktop

**Comment by marmarek** [comment] 2016-01-23 17:20
> "Tor Browser"

Both are owned by `tb-starter` package. And actually `anondist-torbrowser.desktop` is a symlink to `janondisttorbrowser.desktop`. What is the purpose of that @adrelanos ? Some legacy stuff?
There is a github issue reference in https://github.com/Whonix/tb-starter/commit/037c90bf19896ad8503b74345a6678de01c34b2e but it returns 404...

**Comment by adrelanos** [comment] 2016-01-23 20:46
Marek Marczykowski-Górecki:
>> "Tor Browser"
> 
> Both are owned by `tb-starter` package. And actually `anondist-torbrowser.desktop` is a symlink to `janondisttorbrowser.desktop`. What is the purpose of that @adrelanos ? Some legacy stuff?

Yes. Legacy. But I have to and will break it in Whonix 13.

> There is a github issue reference in https://github.com/Whonix/tb-starter/commit/037c90bf19896ad8503b74345a6678de01c34b2e but it returns 404...

That whole ticket got lost for truly mysterious reasons that baffle me.

The ticket included a good comment on explaining this mess. Related to
mime-open and mime priority as per file system order.
`anondist-torbrowser.desktop` is the better name, but
`janondisttorbrowser.desktop` actually worked.

**Comment by marmarek** [comment] 2016-01-23 23:10
> The ticket included a good comment on explaining this mess. Related to mime-open and mime priority as per file system order. `anondist-torbrowser.desktop` is the better name, but `janondisttorbrowser.desktop` actually worked.

Similar to #1621 ? Just changing the name doesn't directly affect filesystem order, maybe just a coincidence, but really fragile.

**Comment by adrelanos** [comment] 2016-01-24 17:49
Yes. (But I didn't see any other options - in this case no custom
handler was deciding to use mime-open or otherwise - I wanted to set the
default straight for any arbitrary application invoking it.)

**Comment by unman** [comment] 2016-05-17 13:31
This is whonix specific, if indeed it is still open.
Can someone remove Debian label, and update to Whonix

**Comment by adrelanos** [comment] 2016-05-17 16:22
The double Tor Browser nautilus right click menu entry ( https://cloud.githubusercontent.com/assets/11895339/12508683/5ab8a914-c0f5-11e5-978e-ace13c9fffd7.png ) is fixed in Whonix 13.

The double open in konsole nautilus right click menu entry ( https://forums.whonix.org/uploads/default/original/1X/6a279c239566a374fbf51c01911b63b8d63b25c0.png ) is still happening in Whonix. But in nautilus only. And as of Whonix 13, nautilus is not installed by default. (related: #1781) So as of Whonix 13, this bug is of minor importance.

The cause for this bug is having the three packages konsole, nautilus and nautilus-open-terminal installed by default in Qubes-Whonix. It will be fixed in Whonix 14. (related: #1781)

**Comment by adrelanos** [comment] 2016-05-17 16:27
Please close this one. @andrewdavidwong

**Closed** 2016-05-17 23:59 UTC
Labels: bug, C: templates, C: Whonix, P: minor, UX
