### ISSUE TITLE
qvm-features-request DeprecationWarning

### ISSUE THREAD

**Issue by f0xy** [QubesOS/qubes-issues#5795] opened 2020-05-04 17:07 UTC
**Qubes OS version**
Qubes release 4.0 (R4.0) / templates-itl-testing/qubes-template-fedora-32

**Affected component(s) or functionality**
qvm-features-request

**Brief summary**
/usr/bin/qvm-features-request:72: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

**To Reproduce**
dnf update

**Expected behavior**
Deprecation Warning

**Actual behavior**
If no packages are available to update / No error

**Screenshots**
N/A

**Additional context**
N/A

**Solutions you've tried**
dnf clear all

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

**Comment by neowutran** [comment] 2020-05-04 18:28
Duplicate of https://github.com/QubesOS/qubes-issues/issues/5658

**Comment by andrewdavidwong** [comment] 2020-05-10 02:07
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-05-10 02:07 UTC
Labels: P: default, T: bug
