### ISSUE TITLE
Salt-based updates fail on Debian and Whonix templates when using a Debian-based mgmt VM

### ISSUE THREAD

**Issue by airelemental** [QubesOS/qubes-issues#6642] opened 2021-05-26 19:18 UTC
**Qubes OS version**
R4.0 with latest updates applied

**Affected component(s) or functionality**
qubes-update-gui
qubesctl

**Brief summary**
`qubes-update-gui` and `qubesctl` fail to update debian-10 and whonix-15 templates, with obscure error.

**How Reproducible**
Always

**To Reproduce**
1. use `qubes-update-gui` to upgrade any debian or whonix template

OR

1. `sudo qubesctl --skip-dom0 --targets=debian-10-test --show-output state.sls update.qubes-vm`
 
**Expected behavior**

green check mark

**Actual behavior**
red cross
debian-10-test: ERROR (exception list index out of range)

**A workaround**
disp-mgmt console says:
~~~
user@disp-mgmt-debian-10-test:~$ sudo .journalctl -b | grep -i salt
May 26 11:27:07 disp-mgmt-debian-10-test qrexec-agent[504]: executed user:QUBESRPC qubes.SaltLinuxVM dom0 pid 584
May 26 11:27:07 disp-mgmt-debian-10-test sudo[585]:     user : TTY=unknown ; PWD=/home/user ; USER=root ; COMMAND=/etc/qubes-rpc/qubes.SaltLinuxVM
May 26 11:27:07 disp-mgmt-debian-10-test qubes.SaltLinuxVM-dom0[593]: sed: can't read /usr/lib/python3*/site-packages/salt/utils/jinja.py: No such file or directory
~~~

In disp-mgmt VM's /etc/qubes-rpc/qubes.SaltLinuxVM, there is a sed at the bottom that runs on jinga.py inside site-packages which doesn't exist in debian-10 and whonix-ws-15.

There's a dist-packages/ though, and if I replace "site-packages" by "dist-packages" in the sed, the upgrade seems to work.

Thanks to oush9 on qubes:matrix.org for troubleshooting help.

**Comment by andrewdavidwong** [comment] 2021-05-26 20:14
A Fedora-based `mgmt` VM can manage both Fedora and Debian VMs, but a Debian-based `mgmt` VM can manage only other Debian VMs, not Fedora VMs. Could this be your problem?

**Comment by DemiMarie** [comment] 2021-05-26 21:03
> This applies to 4.0, but I think it's already fixed in 4.1. @DemiMarie, can you confirm, and you can you provide the number for that issue?

Honestly I am not sure.

**Comment by airelemental** [comment] 2021-05-26 21:06
I use pnly debian VMs for everything.

Maybe that is why it hasn't been reported before - most people use fedora-based mgmt VM, which might have site-packages instead of dist-packages.

**Comment by DemiMarie** [comment] 2021-05-26 21:09
> > A Fedora-based mgmt VM can manage both Fedora and Debian VMs, but a Debian-based mgmt VM can manage only other Debian VMs, not Fedora VMs. Could this be your problem?
> 
> I use debian-based VMs for everything...
> 
> Maybe that is why it hasn't been reported before - most people use fedora-based mgmt VM, which might have site-packages instead of dist-packages.

That would certainly do it!  I will fix this.

**Comment by DemiMarie** [comment] 2021-05-26 21:12
> > This applies to 4.0, but I think it's already fixed in 4.1. @DemiMarie, can you confirm, and you can you provide the number for that issue?
> 
> Honestly I am not sure.

To elaborate: the problem is that Fedora has a newer version of Python, which is incompatible with the older version of Salt in Debian.  Fixing this would likely require that Qubes OS either ship its own version of Salt (overriding the distribution package), or that each non-minimal TemplateVM package provide a ManagementVM based on that TemplateVM (which is what I recommend).

**Comment by andrewdavidwong** [comment] 2021-05-26 21:19
> > > This applies to 4.0, but I think it's already fixed in 4.1. @DemiMarie, can you confirm, and you can you provide the number for that issue?
> > 
> > 
> > Honestly I am not sure.
> 
> To elaborate: the problem is that Fedora has a newer version of Python, which is incompatible with the older version of Salt in Debian. Fixing this would likely require that Qubes OS either ship its own version of Salt (overriding the distribution package), or that each non-minimal TemplateVM package provide a ManagementVM based on that TemplateVM (which is what I recommend).

Can you confirm whether this is fixed in 4.1? (I thought I recall hearing that from you, but now I'm not sure.)

If so, then the question is what, if anything, to do about it in 4.0. One option is just to document the fact that a Fedora TemplateVM should be used for the `mgmt` VM in 4.0. @marmarek, thoughts?

**Comment by unman** [comment] 2021-05-27 12:25
On Wed, May 26, 2021 at 02:19:19PM -0700, Andrew David Wong wrote:
> > > > This applies to 4.0, but I think it's already fixed in 4.1. @DemiMarie, can you confirm, and you can you provide the number for that issue?
> > > 
> > > 
> > > Honestly I am not sure.
> > 
> > To elaborate: the problem is that Fedora has a newer version of Python, which is incompatible with the older version of Salt in Debian. Fixing this would likely require that Qubes OS either ship its own version of Salt (overriding the distribution package), or that each non-minimal TemplateVM package provide a ManagementVM based on that TemplateVM (which is what I recommend).
> 
> Can you confirm whether this is fixed in 4.1? (I thought I recall hearing that from you, but now I'm not sure.)
> 
> If so, then the question is what, if anything, to do about it in 4.0. One option is just to document the fact that a Fedora TemplateVM should be used for the `mgmt` VM in 4.0. @marmarek, thoughts?
> 

It's worth pointing out that airelemental neglected a crucial fact -
that they are using update-candidates.
So the system has worked well - something in testing has been found to
be wrong, and is now being fixed. It has no impact on the main release.

Two things:
1. There should be some way of flagging these cases - so that reporters and
other users know they relate to "testing".
2. There should be more testing *before* updated packages are pushed to
testing. At present, it seems restricted to "does it build". ( I
often find that changes break Ubuntu, and older Debian.)
I know this is difficult with a small team: it isn't impossible.

**Comment by andrewdavidwong** [comment] 2021-05-27 13:19
> It's worth pointing out that airelemental neglected a crucial fact - that they are using update-candidates.
> [...]
> 1. There should be some way of flagging these cases - so that reporters and other users know they relate to "testing".

That's why the very first field in the issue template is "Qubes OS version."

In this case, @airelemental wrote:

> **Qubes OS version**
> R4.0 with latest updates applied

Was this a lie?

**Comment by unman** [comment] 2021-05-27 13:37
On Thu, May 27, 2021 at 06:19:36AM -0700, Andrew David Wong wrote:
> > It's worth pointing out that airelemental neglected a crucial fact - that they are using update-candidates.
> > [...]
> > 1. There should be some way of flagging these cases - so that reporters and other users know they relate to "testing".
> 
> That's why the very first field in the issue template is "Qubes OS version."
> 
> In this case, @airelemental wrote:
> 
> > **Qubes OS version**
> > R4.0 with latest updates applied
> 
> Was this a lie?
> 

Certainly not a lie - misleading.
It would depend on whether you interpret "latest" as "latest updates"
or "latest candidates for updates". These are different things.

Flagging such issues would enable devs to block package transition to
"updates": otherwise *many* users would encounter the problem.

**Comment by brendanhoar** [comment] 2021-05-27 14:12
Personally I do try to remember to indicate that I am using the testing repo when filling out a QubesOS bug report. Perhaps a reference to that can be added to the template in the first section for QubesOS version, e.g. "If using testing, security-testing or other non-default repos, please indicate which one(s) here as well."

**Comment by unman** [comment] 2021-05-27 15:30
On Thu, May 27, 2021 at 07:12:20AM -0700, Brendan Hoar wrote:
> Personally I do try to remember to indicate that I am using the testing repo when filling out a QubesOS bug report. Perhaps a reference to that can be added to the template in the first section for QubesOS version, e.g. "If using testing, security-testing or other non-default repos, please indicate which one(s) here as well."
> 

Yes, this would be good, although many users wont remember after they
have enabled those repositories.
Having a Label for Testing/Proposed_update would, I think, be useful,
since there is some immediacy required in dealing with those issues.

**Comment by andrewdavidwong** [comment] 2021-05-28 04:25
> Personally I do try to remember to indicate that I am using the testing repo when filling out a QubesOS bug report. Perhaps a reference to that can be added to the template in the first section for QubesOS version, e.g. "If using testing, security-testing or other non-default repos, please indicate which one(s) here as well." and then Andrew can tag accordingly.

Thanks for the feedback. I've updated the bug report issue template to add sections regarding testing: https://github.com/QubesOS/qubes-issues/commit/0ee2cc378e576cd2ea249c1a148337a99d3431ae. Hopefully this helps.

> Flagging such issues would enable devs to block package transition to "updates": otherwise *many* users would encounter the problem.

We actually already have a procedure in place for [providing feedback on packages in testing via the `updates-status` repo](https://www.qubes-os.org/doc/testing/#providing-feedback). I wasn't sure exactly how best to integrate this into the bug report issue template, but I figure we want to avoid a situation in which someone reports a bug here without indicating anything in `updates-status` or without linking together to their bug report here with their comment in `updates-status`, so I added an extra section specifically for this. (CC @marmarek)

> Having a Label for Testing/Proposed_update would, I think, be useful, since there is some immediacy required in dealing with those issues.

Unsure what label text would be most perspicuous here. `testing` is likely to be misused for things like writing unit tests and other work related to automated testing. Since we already have the `updates-status` repo, we could use that same name for this label, but people who don't know about `updates-status` might not make that connection. `updates-testing` might be confusing, given that we already have `C: updates`. It could be misinterpreted as testing the update system itself, but I suppose this is unlikely and the least of three evils. I'll go with this for now.

**Comment by unman** [comment] 2021-05-28 12:51
On Thu, May 27, 2021 at 09:25:22PM -0700, Andrew David Wong wrote:
> > Personally I do try to remember to indicate that I am using the testing repo when filling out a QubesOS bug report. Perhaps a reference to that can be added to the template in the first section for QubesOS version, e.g. "If using testing, security-testing or other non-default repos, please indicate which one(s) here as well." and then Andrew can tag accordingly.
> 
> Thanks for the feedback. I've updated the bug report issue template to add sections regarding testing: https://github.com/QubesOS/qubes-issues/commit/0ee2cc378e576cd2ea249c1a148337a99d3431ae. Hopefully this helps.
> 
> > Flagging such issues would enable devs to block package transition to "updates": otherwise *many* users would encounter the problem.
> 
> We actually already have a procedure in place for [providing feedback on packages in testing via the `updates-status` repo](https://www.qubes-os.org/doc/testing/#providing-feedback). I wasn't sure exactly how best to integrate this into the bug report issue template, but I figure we want to avoid a situation in which someone reports a bug here without indicating anything in `updates-status` or without linking together to their bug report here with their comment in `updates-status`, so I added an extra section specifically for this. (CC @marmarek)
> 
> > Having a Label for Testing/Proposed_update would, I think, be useful, since there is some immediacy required in dealing with those issues.
> 
> Unsure what label text would be most perspicuous here. `testing` is likely to be misused for things like writing unit tests and other work related to automated testing. Since we already have the `updates-status` repo, we could use that same name for this label, but people who don't know about `updates-status` might not make that connection. `updates-testing` might be confusing, given that we already have `C: updates`. It could be misinterpreted as testing the update system itself, but I suppose this is unlikely and the least of three evils. I'll go with this for now.
> 

If I knew how to give a thumbs up, I would do so.

**Comment by ThomasWaldmann** [comment] 2021-05-31 17:25
I also ran into this and worked around it by:

Menu -> System Tools -> Qubes Template Manager

default-mgmt-dvm: switched to fedora (had debian there)

**Comment by andrewdavidwong** [comment] 2021-05-31 22:55
@ThomasWaldmann wrote:
> I also ran into this

Are you also on 4.0 with testing repos enabled? If so, which ones? (@airelemental, I would also like to ask these same questions of you.)

@unman wrote:
> something in testing has been found to be wrong, and is now being fixed. It has no impact on the main release.

To clarify, by "main release" you mean "stable release (4.0) without any testing repos enabled"?

@DemiMarie wrote:
> Fixing this would likely require that Qubes OS either ship its own version of Salt (overriding the distribution package), or that each non-minimal TemplateVM package provide a ManagementVM based on that TemplateVM (which is what I recommend).

To be clear, you're saying that one of these fixes would likely be required for fixing this in 4.0, right?

Regarding your second/recommended proposal, I foresee a few challenges:
- Users of minimal templates still wouldn't get the fix. (Does this just get documented and considered acceptable per the health warning?)
- It wouldn't be obvious to users why a ManagementVM is being created when installing a template.
- Users might remove the automatically-created ManagementVMs, not realizing that they're needed or why.
- This would only solve the problem for new RPM-installed templates, not for existing templates. (Unless that's okay because only installations with certain testing repos enabled are affected?)

**Comment by unman** [comment] 2021-06-01 12:00
On Mon, May 31, 2021 at 03:55:14PM -0700, Andrew David Wong wrote:
> @ThomasWaldmann wrote:
> > I also ran into this
> 
> Are you also on 4.0 with testing repos enabled? If so, which ones? ***@***.***, I would also like to ask these same questions of you.)

The problem only arises if you install the package currenlt in testing.
> 
> @unman wrote:
> > something in testing has been found to be wrong, and is now being fixed. It has no impact on the main release.
> 
> To clarify, by "main release" you mean "stable release (4.0) without any testing repos enabled"?

Yes.

> 
> @DemiMarie wrote:
> > Fixing this would likely require that Qubes OS either ship its own version of Salt (overriding the distribution package), or that each non-minimal TemplateVM package provide a ManagementVM based on that TemplateVM (which is what I recommend).

This is a misunderstanding.
Even if Debian shipped the latest release of Salt, it would still be
broken by the patch.
The patch uses `site-packages` whereas Debian uses `dist-packages`, and
that call to sed isn't protected.

**Comment by ThomasWaldmann** [comment] 2021-06-01 16:28
@andrewdavidwong how exactly can I check whether i use testing repos?

**Comment by andrewdavidwong** [comment] 2021-06-01 18:10
> @andrewdavidwong how exactly can I check whether i use testing repos?

You would check in `/etc/yum.repos.d/`. But don't worry about it. Unman already answered the question. And if you never enabled testing repos, they wouldn't be enabled.

**Comment by ThomasWaldmann** [comment] 2021-06-01 18:50
I don't have testing repos enabled.

**Comment by andrewdavidwong** [comment] 2021-06-01 19:39
> The problem only arises if you install the package currenlt in testing.

> I don't have testing repos enabled.

@unman, this sounds like a contradiction to me, but maybe I'm missing something?

**Comment by airelemental** [comment] 2021-06-02 01:19
> Are you also on 4.0 with testing repos enabled? If so, which ones? (@airelemental, I would also like to ask these same questions of you.)

My apologies, I should have mentioned I have qubes-dom0-current-testing enabled.

**Comment by unman** [comment] 2021-06-02 12:53
On Tue, Jun 01, 2021 at 12:39:52PM -0700, Andrew David Wong wrote:
> > The problem only arises if you install the package currenlt in testing.
> 
> > I don't have testing repos enabled.
> 
> @unman, this sounds like a contradiction to me, but maybe I'm missing something?
> 

Since the Debian bug was introduced in
qubes-mgmt-salt-vm-connector-4.0.25-1 and that package is only available
in the updates candidates repository, the testing repo must be enabled.

**Comment by andrewdavidwong** [comment] 2021-06-02 17:43
> Since the Debian bug was introduced in qubes-mgmt-salt-vm-connector-4.0.25-1 and that package is only available in the updates candidates repository, the testing repo must be enabled.

Hm. The mystery continues. I wonder if there may actually be two distinct bugs at work here, then.

Actually, it sounds like testing repo (`current-testing`?) must be enabled in the **Debian TemplateVM**, not dom0 or anywhere else. Is that right?

@ThomasWaldmann, can you confirm that you also have never had `current-testing` enabled in any of your Debian TemplateVMs?

**Comment by airelemental** [comment] 2021-06-02 21:06
> Actually, it sounds like testing repo (`current-testing`?) must be enabled in the **Debian TemplateVM**, not dom0 or anywhere else. Is that right?

Wierd - I have a system where qubes-mgmt-salt-vm-connector-4.0.25-1 is installed in the debian-10 template (so its qubes.SaltLinuxVM tries to patch site-packages) even though the vm-buster-testing repo is disabled in the template's /etc/apt/sources.list.d/qubes-r4.list

**Comment by unman** [comment] 2021-06-03 11:44
On Wed, Jun 02, 2021 at 02:07:11PM -0700, airelemental wrote:
> > Actually, it sounds like testing repo (`current-testing`?) must be enabled in the **Debian TemplateVM**, not dom0 or anywhere else. Is that right?
> 
> Wierd - I have a system where qubes-mgmt-salt-vm-connector-4.0.25-1 is installed in the debian-10 template (so its qubes.SaltLinuxVM tries to patch site-packages) even though the vm-buster-testing repo is disabled in the template's /etc/apt/sources.list.d/qubes-r4.list
> 

Strange indeed - I checked as soon as you raised the issue and it was
not in current. No more is it now.
Can you check the apt logs in the template and report back. You should
be able to trace the install.

**Comment by marmarek** [comment] 2021-06-03 12:17
It was uploaded to the current repo shortly before this issue was opened: https://github.com/QubesOS/updates-status/issues/2434#issuecomment-847430103

**Comment by unman** [comment] 2021-06-03 12:39
On Thu, Jun 03, 2021 at 05:17:54AM -0700, Marek Marczykowski-G??recki wrote:
> It was uploaded to the current repo shortly before this issue was opened: https://github.com/QubesOS/updates-status/issues/2434#issuecomment-847430103
> 

That *is* weird, because I only found it in testing, not in current. I
should explicitly prune my cache.

**Comment by SvenSemmler** [comment] 2021-06-07 17:05
Looking for confirmation that I have to set this to fedora and there is no point in checking back as long as I run R4.0.x -- correct?

**Comment by DemiMarie** [comment] 2021-06-07 19:13
> Looking for confirmation that I have to set this to fedora and there is no point in checking back as long as I run R4.0.x -- correct?

No, this is a bug and *will* be fixed.

**Comment by 3hhh** [comment] 2021-06-21 09:40
I hit into this one in 4.0 stable repos as well.

**Comment by unman** [comment] 2021-06-21 10:14
On Mon, Jun 21, 2021 at 02:40:51AM -0700, 3hhh wrote:
> I hit into this one in 4.0 stable repos as well.
> 

As Marek said, it had moved in to current repos, so has the capacity to
impact everyone.

**Closed** 2021-06-23 01:21 UTC
Labels: C: Debian/Ubuntu, C: Whonix, C: mgmt, C: updates, P: default, T: bug, diagnosed

**Comment by ben-grande** [comment] 2025-02-26 19:35
Please reopen. Fedora 40 management qube to Debian 12:

> calling 'state.apply utils.tools.xfce'...
> Failed to apply salt#60003 workaround: sed: can't read /usr/lib/python3*/site-packages/salt/utils/jinja.py: No such file or directory|sed: can't read /usr/lib/python3*/site-packages/salt/client/ssh/state.py: No such file or directory

```
# dnf list installed salt* qubes-mgmt*
Installed Packages
qubes-mgmt-salt-vm-connector.noarch           4.2.2-1.fc40             @qubes-vm-r4.2-current
salt.noarch                                   3007.1-1.fc40            @qubes-vm-r4.2-current
salt-ssh.noarch                               3007.1-1.fc40            @qubes-vm-r4.2-current
```

**Comment by ben-grande** [comment] 2025-02-27 08:47
I seem to have made an error, I changed templates and this fixed, I messed up my templates... can be closed, sorry.

**Comment by unman** [comment] 2025-02-27 13:20
There IS a bug that I have been meaning to post, but not this one.
The default Debian template installed with 4.2 is not able to salt
Fedora templates correctly, but works fine against Debian templates.

Do you want to keep this open (and amend it) or should be a separate
issue raised?

**Comment by ben-grande** [comment] 2025-02-27 13:47
> There IS a bug that I have been meaning to post, but not this one. The default Debian template installed with 4.2 is not able to salt Fedora templates correctly, but works fine against Debian templates.

See:

- https://github.com/QubesOS/qubes-issues/issues/9328

**Comment by unman** [comment] 2025-02-27 14:57
On Thu, Feb 27, 2025 at 05:47:34AM -0800, ben-grande wrote:
> ben-grande left a comment (QubesOS/qubes-issues#6642)
> 
> > There IS a bug that I have been meaning to post, but not this one. The default Debian template installed with 4.2 is not able to salt Fedora templates correctly, but works fine against Debian templates.
> 
> See:
> 
> - https://github.com/QubesOS/qubes-issues/issues/9328

cheers
