### ISSUE TITLE
Resolution does not match physical screen

### ISSUE THREAD

**Issue by alinazzal** [QubesOS/qubes-issues#4796] opened 2019-02-07 02:50 UTC
### Qubes OS version:

4.0.1

### Affected component(s):

I just downloaded the latest qubes 4.0.1 on my surface pro 6 and the entire desktop and every application I run is soo tiny, it’s hard to read anything. Not only that, but toolbar buttons such as minimize and close are very very small. How can I apply settings so that not only dom0 but all others such as fedora get the same display settings?

---

### General notes:

---

**Comment by andrewdavidwong** [comment] 2019-02-07 02:54
Duplicate of #1951

**Comment by andrewdavidwong** [comment] 2019-02-07 02:54
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by alinazzal** [comment] 2019-02-07 03:17
The thing is, when changing the resolution the screen ends up flattening down from top and bottom. It doesn’t end up taking the full length up and down of my screen.

**Closed** 2023-08-05 09:19 UTC
Labels: T: bug, C: other, P: default, eol-4.0
