### ISSUE TITLE
[R4.0] "qvm-create -p netvm= somevm" creates VM with default netvm

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2330] opened 2016-09-21 16:08 UTC
#### Qubes OS version (e.g., `R3.1`):

R4.0

---
### Expected behavior:

`netvm` should be none.
### Actual behavior:

`netvm` is set to default value
### Steps to reproduce the behavior:

`qvm-create -p netvm= somevm`
### General notes:

---

**Comment by woju** [comment] 2017-09-06 23:42
Could not reproduce, this works as advertised.
Closing.

**Closed by woju** 2017-09-06 23:42 UTC
Labels: bug, C: core, P: minor
