### ISSUE TITLE
Graphical Installer: Qubes System (last installation step)

### ISSUE THREAD

**Issue by diffusae** [QubesOS/qubes-issues#3749] opened 2018-03-26 17:07 UTC
### Qubes OS version: 

R4.0rc5

### Affected component(s):  

Graphical Installer

---

### Steps to reproduce the behavior: 

If you finish the installation after booting, you could choose to configure the VMs. That takes a while. If you accidentally hit the "Qubes System button", you have to run through the menu. Sometimes this ends up in a faulty installation.

### Expected behavior:

There should be a way to escape from the screen, so you don't have to run it twice.

### Actual behavior: 

You can't escape from that screen until you click "Done". Than the configuration of the VMs starts again. Sometimes it ends up with an error message and some of the VMs aren't setup correctly.

### General notes: 

The system is booting correctly. Once I had the issue, that whonix VMs aren't setup.

---

### Related issues:

?

**Comment by andrewdavidwong** [comment] 2018-03-27 01:33
Duplicate of #2433

**Comment by andrewdavidwong** [comment] 2018-03-27 01:33
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-27 01:33 UTC
