### ISSUE TITLE
Qubes Global Settings doesn't support None for default_dispvm, changes it to something else

### ISSUE THREAD

**Issue by airelemental** [QubesOS/qubes-issues#4114] opened 2018-07-20 23:23 UTC
### Qubes OS version:

R4.0 current-testing
R4.0 current

### Affected component(s): 

Qubes Global Settings

---

### Steps to reproduce the behavior:

1. Set global default dispvm to None: `qubes-prefs default_dispvm ''`
2. System Tools > Qubes Global Settings
3. click okay

### Expected behavior:

No change to global default_dispvm.

### Actual behavior:

global default_dispvm changes to some VM.

### General notes:

If you set the default_dispvm to None and you create an offline VM, one day you may find it gets easy clearnet web access through its dispvm, since you opened the global settings to change something and clicked Okay.

---

**Comment by marmarek** [comment] 2018-07-20 23:33
Looks like a duplicate of #4114 (same problem for a different property). Check updated [qubes-manager package](https://github.com/QubesOS/updates-status/issues/600)

**Comment by airelemental** [comment] 2018-07-21 00:15
but this issue is #4114?

**Comment by marmarek** [comment] 2018-07-21 00:19
#4043

**Comment by airelemental** [comment] 2018-07-21 02:43
The issue with default_dispvm stilll occurs in qubes-manager-4.0.19.

**Closed** 2018-07-23 23:45 UTC
Labels: C: qubes-manager, bug
