### ISSUE TITLE
qubes-dom0-update - synchronize cache problem

### ISSUE THREAD

**Issue by hast0011** [QubesOS/qubes-issues#5167] opened 2019-07-14 18:07 UTC
**Qubes OS version**
Qubes R4.0

**Affected component(s) or functionality**
The update via sudo qubes-dom0-update

**Brief summary**
The update command throws error messages about "Failed to synchronize cache for qubes-dom0-current" and qubes-templates-itl.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to console
_2. Start update
_3. Wait a view seconds..
_4. See error_

**Expected behavior**
The packages to be updated are listed and can be installed with "y"

**Actual behavior**

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Updates on templates run as expected

**Comment by RooneyMcNibNug** [comment] 2019-07-14 21:21
Can confirm this is currently happening on a fresh 4.0.1 install:

```
[rooney@dom0 yum.repos.d]$ sudo qubes-dom0-update --clean
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
22 files removed
Fedora 25 - x86_64 - Updates                    597 kB/s |  24 MB     00:40    
Fedora 25 - x86_64                              698 kB/s |  50 MB     01:13    
Qubes Dom0 Repository (updates)                 163  B/s | 3.8 kB     00:23    
determining the fastest mirror (15 hosts).. done.--  B/s |   0  B     --:-- ETA
Qubes Templates repository                      126  B/s | 3.0 kB     00:24    
Failed to synchronize cache for repo 'qubes-dom0-current', ignoring this repo.
Failed to synchronize cache for repo 'qubes-templates-itl', ignoring this repo.
Last metadata expiration check: 0:00:25 ago on Sun Jul 14 16:12:46 2019.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
No updates available
[rooney@dom0 yum.repos.d]$
```

Editing ```/etc/yum.repos.d/qubes-dom0.repo``` in ```dom0``` to hard-code in the version number in place of ```r$releasever``` per previous recommendations (https://groups.google.com/d/msg/qubes-users/K7zAP4LXcN4/U-09iYILAwAJ ) is not solving the issue.

**Comment by marmarek** [comment] 2019-07-14 22:53
Check now, should be better.

**Comment by RooneyMcNibNug** [comment] 2019-07-15 02:10
Yep, working for me now - thanks for that.

**Comment by andrewdavidwong** [comment] 2019-07-15 02:15
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-07-15 02:15 UTC
Labels: C: infrastructure, P: default, T: bug

**Comment by hast0011** [comment] 2019-07-15 05:09
It works for me now. Thank you.
