### ISSUE TITLE
volume export on file pools fails in 4.0 ("dirty")

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6523] opened 2021-04-13 09:11 UTC
### Qubes OS version:
4.0

### Affected component(s) or functionality:
qubes-core-admin 4.0.58

---

### Steps to reproduce the behavior:
`qvm-clone debian-10 debian-10-test`

### Expected or desired behavior:
Clone is created.

### Actual behavior:
Clone is not created.

Message: `file pool cannot export dirty volumes.`

### General notes:

[is_dirty](https://github.com/QubesOS/qubes-core-admin/blob/fe66e3db56b3db67f24693d574bae117ac41e677/qubes/storage/file.py#L215) checks for `-cow` files, which are **always** there (hexdump shows they are only zeroes).

It's likely because stop() calls [commit](https://github.com/QubesOS/qubes-core-admin/blob/fe66e3db56b3db67f24693d574bae117ac41e677/qubes/storage/file.py#L343), which [creates empty sparse files](https://github.com/QubesOS/qubes-core-admin/blob/fe66e3db56b3db67f24693d574bae117ac41e677/qubes/storage/file.py#L266).

Workaround is to delete the `*-cow.img` files.

This affects at least qubes-core-admin 4.0.58 and was also reported on [qubes-users](https://groups.google.com/g/qubes-users/c/Tiz3d36RCdE).

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

-

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

-

**Comment by rustybird** [comment] 2021-04-13 09:47
Duplicate of QubesOS/qubes-issues#6371

The [bugfix](https://github.com/QubesOS/qubes-core-admin/commit/05eb051) is in R4.1, but it hasn't been backported to R4.0 yet.

**Comment by 3hhh** [comment] 2021-04-13 17:38
Then either this once can be closed and #6371 re-opened or this one can be kept open until it's backported.

**Comment by andrewdavidwong** [comment] 2021-04-15 09:39
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2021-04-15 09:39 UTC
Labels: R: duplicate
