### ISSUE TITLE
If .bashrc has error, AppVM starting hangs after Waiting for qubes-session

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#2356] opened 2016-10-02 06:08 UTC
#### Qubes OS version (e.g., `R3.1`):
R3.1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23

---

### Expected behavior:
If I try to `source` a nonexistent file in my `.bashrc` inside a VM, the VM should still start.

### Actual behavior:
`qvm-start vmname` hangs after `Waiting for qubes-session...` and no applications can be started.

### Steps to reproduce the behavior:
1. Inside an AppVM terminal: `echo "source /non/existent/file" >>~/.bashrc`
2. restart AppVM

### General notes:
This means `.bashrc` prints to stderr - maybe some brittle code is looking for something on stderr and not expecting that?

**Comment by unman** [comment] 2016-10-03 22:18
@greenrd I wonder how you are starting the qube: from the menu?
I think that the qube does start: can you check with `qvm-ls`

Also, try `qvm-run qube xterm` - you should see a terminal open with bash error.
Most other commands seem to work as expected when run with `qvm-run -a`. Can you confirm?

**Comment by unman** [comment] 2016-10-08 00:19
@greenrd @andrewdavidwong 
I simply can't reproduce this issue.
I've tried on both 3.1 and 3.2, with various templates, and don't encounter this problem. The reported case of fedora-23 on (clean) 3.1 works for me. The qube starts fine. 
Terminal started with `qvm-run -a` starts the qube, and the terminal opens showing a bash error message as expected.
Can any one else confirm?

**Comment by andrewdavidwong** [comment] 2016-10-09 01:16
I, too, am unable to reproduce this. Closing.

**Closed by andrewdavidwong** 2016-10-09 01:16 UTC
Labels: bug, C: core
