### ISSUE TITLE
Firefox scrolling the wrong window

### ISSUE THREAD

**Issue by tumbletree** [QubesOS/qubes-issues#5912] opened 2020-06-28 13:32 UTC
**Qubes OS version**
4

**Affected component(s) or functionality**
firefox

**Brief summary**
two firefox windows overlapping. Scrolling on top one did not move the page, but moved a page on the window behind. Clicked several times on page, no change. Clicking around between qubes, and it broke the 'spell', ie working properly now.

**To Reproduce**
Open Several firefox windows open, each with many tabs (so, ~4 w. x 10 tabs)
open another window (on top), load a page. Move mouse for scroll.

**Expected behavior**
active page should move with mouse.

**Actual behavior**
a different page moved with mouse.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
I query if there are new issues with firefox on Fedora-31 (I have noticed freezing), but don't know if that's firefox, fedora, my old machine (x230) or something else.

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by iamahuman** [comment] 2020-06-29 06:07
Duplicate of #1455 and #3267.

**Comment by andrewdavidwong** [comment] 2020-06-30 11:46
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-06-30 11:46 UTC
Labels: P: default, T: bug
