### ISSUE TITLE
Cannot launch installed Progressive Web Apps (PWAs) via app menu

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8967] opened 2024-02-25 01:58 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

If I install a Progressive Web App (such as GitHub) and try to launch the resulting `.desktop` file, `qubes.StartApp` crashes:

```
Traceback (most recent call last):
  File "/etc/qubes-rpc/qubes.StartApp", line 39, in <module>
    main(sys.argv)
  File "/etc/qubes-rpc/qubes.StartApp", line 15, in main
    if qubes_db.read('/qubes-service/app-dispvm.' + arg) is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qubesdb.Error: (0, 'Error')
```

The argument is `chrome-mjoklplbddabcmpepnokjaffbmgbkkgg`.

### Steps to reproduce

See above.

### Expected behavior

Works

### Actual behavior

Fails

**Comment by marmarek** [comment] 2024-02-25 02:12
Duplicate of https://github.com/QubesOS/qubes-issues/issues/7421

**Closed by marmarek** 2024-02-25 02:12 UTC
Labels: T: bug, P: default
