### ISSUE TITLE
dgplug.org has expired SSL certificate effecting templates download

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7072] opened 2021-11-17 13:10 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

Trying to install fedora-34

### Steps to reproduce

try install new template fedora 34 from dom0:

```
[user@dom0 ~]$ sudo qubes-dom0-update qubes-template-fedora-34
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
warning: Converting database from bdb to sqlite backend
Fedora 25 - x86_64                              6.3 kB/s | 5.1 kB     00:00    
Fedora 25 - x86_64 - Updates                    7.5 kB/s | 4.8 kB     00:00    
Qubes Dom0 Repository (updates)                 5.6 kB/s | 2.7 kB     00:00    
Qubes Templates repository                      6.8 kB/s | 2.7 kB     00:00    
Dependencies resolved.
================================================================================
 Package                  Arch   Version              Repository           Size
================================================================================
Installing:
 qubes-template-fedora-34 noarch 4.0.6-202110020209   qubes-templates-itl 1.6 G

Transaction Summary
================================================================================
Install  1 Package

Total download size: 1.6 G
Installed size: 4.6 G
DNF will only download packages for the transaction.
Downloading Packages:
[MIRROR] qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://mirrors.dgplug.org/qubes/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm [SSL certificate problem: certificate has expired]
--------------------------------------------------------------------------------
Total                                           5.5 MB/s | 1.6 GB     04:59     
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Qubes OS Repository for Dom0                                                          25 MB/s |  26 kB     00:00    
Dependencies resolved.
=====================================================================================================================
 Package                            Arch             Version                       Repository                   Size
=====================================================================================================================
Installing:
 qubes-template-fedora-34           noarch           4.0.6-202110020209            qubes-dom0-cached           1.6 G

Transaction Summary
=====================================================================================================================
Install  1 Package

Total size: 1.6 G
Installed size: 0  
Is this ok [y/N]: 
```

### Expected behavior

should go smoothly and securely

### Actual behavior

https://mirrors.dgplug.org which qubes rely on for downloading new templates seem to be neglecting their server security, and ssl one of the obvious things to look for...

**Comment by marmarek** [comment] 2021-11-17 18:35
While it's indeed unfortunate that the mirror have old certificate, please note this does not impact updates security in any way. First of all, a mirror to which connection failed (and expired cert does fail the connection) is ignored and the package is downloaded from another one. But even if that wouldn't be the case, the update is protected via package signature (and recently update metadata is signed too).

**Comment by andrewdavidwong** [comment] 2021-11-19 06:52
As Marek pointed out, this should not affect Qubes OS functionality or security in any way, since any bad mirror is just ignored (and a different one is used instead), and regardless, mirrors are never trusted for security in any way (which includes not trusting their certificates in any way). It sounds like you received a mere informational message that had no real impact, which means that everything is working as intended.

Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2021-11-19 06:52 UTC
Labels: T: bug, P: default

**Comment by DemiMarie** [comment] 2021-11-19 16:52
> > the update is protected via package signature
> 
> Dont depend on GPG signature, Very wrong to depend on that only, TLS sadly nowadays highly important and its not optional e.g: (I know its already certified with TLS but its just expired, But still its mandatory to be working properly)

Not an issue either ― the metadata is delivered over TLS and the hash of the template is checked.

**Comment by andrewdavidwong** [comment] 2021-11-20 09:01
Keep in mind also that we have no control over third party mirrors. We can't fix SSL/TLS on a domain that doesn't belong to us.
