### ISSUE TITLE
Error message says too much, disappears too easily, can't be recalled.

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#7221] opened 2022-01-21 12:19 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

Edited lightly for detail, (after validation from DemiMarie).

### Qubes OS release

4.1

### Brief summary
 An error message encountered as I attempted to connect my Android device to a qube popped up. But it was packed with information, including at least one https address, then faded out in ~10 seconds. 

EDIT - confounded by the need to keep a cursor on the error message to keep it alive.

### Steps to reproduce

1. connect phone/device by USB
2. use Qubes Devices to attach to target AppVM
3. encounter pop-up error with lots of text, filepaths and a https address
4. attempt to click or copy web address / other information 
5. move mouse off error message (by mistake, out of necessity) 

### Expected behavior
Either or both:
- error message stays around and is dismissed on click.
- error message is "bite size" but informative.

It would also help if, should web addresses or filepaths be provided, they were copiable. Don't know if this is possible.

Also, a list of last 5 or 10 error messages (and where they came from) could be useful. Perhaps launched from an icon in system tray, something like a clipboard manager. (Forgive me if something like this exists). May be what [6634](https://github.com/QubesOS/qubes-issues/issues/6634) is talking about, but the form is different. 

### Actual behavior

error message fades out when cursor moves off text box. Information cannot be read and retained.

**Comment by DemiMarie** [comment] 2022-01-21 14:44
This is actually a legitimate UX (user experience) problem!  @ninavizz thoughts?

**Comment by andrewdavidwong** [comment] 2022-01-22 19:40
Duplicate of #7113 and/or #889.

**Comment by andrewdavidwong** [comment] 2022-01-22 19:41
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2022-01-22 19:41 UTC
Labels: T: bug, R: duplicate, P: default
