### ISSUE TITLE
[Contribution] qubes-network-server

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#6246] opened 2020-12-01 13:14 UTC
**The problem you're addressing (if any)**

Tracking networking changes in Qubes OS is difficult from the perspective of maintaining Qubes network server.  Every time there is a minor (not micro, minor) release, Qubes network server breaks, because Qubes network server needs to "un-do" or modify certain protection mechanisms that were added since the past release.

**Describe the solution you'd like**

Qubes network server ought to be integrated into Qubes OS proper.

**Where is the value to a user, and who might that user be?**

Users who need to selectively expose VMs to their local network should be happy.

**Additional context**

https://github.com/Rudd-O/qubes-network-server

I am willing to offer funding for this task.  I cannot, however, contribute code changes for reasons I am not able to articulate here.

**Comment by andrewdavidwong** [comment] 2020-12-01 22:58
Duplicate of #5088

**Comment by andrewdavidwong** [comment] 2020-12-01 22:58
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-12-01 22:58 UTC
Labels: C: other, P: default, S: under review, T: enhancement
