### ISSUE TITLE
PCI Device Doesn't exist

### ISSUE THREAD

**Issue by Oregano1963** [QubesOS/qubes-issues#9520] opened 2024-10-20 04:32 UTC
### Qubes OS release

Latest 4.2.3 downloaded a few hours ago from the website.

### Brief summary

Upon downloading it, it got the following error. I redownloaded it twice and got the same error at the same time towards the end of the initialization. When trying to use a vm, it gives the same error as below
![Untitled](https://github.com/user-attachments/assets/d6de0585-5089-4dab-97bd-7d2e42f23e18)

### Steps to reproduce
Download QubesOS and download it. Wait until after it downloads, start it up, and after the scripts are done running, it'll come up with this error.

### Expected behavior
Regulat installation and usage

### Actual behavior
Screen goes black after clicking off the warning and goes to the password screen, It then returns a similar error regarding sysnet when trying to access a VM.

CPU: 7800x3d
Externals, monitor, mouse, usb, keyboard 
If other information should be provided, do ask.

**Comment by marmarek** [comment] 2024-10-20 20:26
Can you show output of `qvm-pci` command in dom0?

**Comment by Oregano1963** [comment] 2024-10-20 21:20
> Can you show output of `qvm-pci` command in dom0?

Here's the qvm-pci 
![IMG_E3243](https://github.com/user-attachments/assets/78685676-6cb0-48cd-9fbe-93da05ebfc64)


Also, when entering, I have to confirm my mouse (by hitting enter a few times). Is that normal and how do I make it not ask to confirm my mouse everytime? 
![IMG_E3242](https://github.com/user-attachments/assets/48c54807-bf7e-43ba-8bd5-9ac037c89f00)

**Comment by marmarek** [comment] 2024-10-20 21:37
and what about `qvm-pci ls sys-net`?



> I have to confirm my mouse (by hitting enter a few times). Is that normal and how do I make it not ask to confirm my mouse everytime?

There is a setting for that in "qubes global config"

**Comment by Eric678** [comment] 2024-10-20 23:01
I noticed this in 4.2.3 install and mentioned it in #8322  - the wrong PCI device numbers retrieved initially (new to 4.2.3) - one can probably rescue that system by using the qubes.skip_autostart facility and taking the bad device numbers out of sys_net (& sys_usb) and replacing with the correct ones in settings.

**Comment by Oregano1963** [comment] 2024-10-20 23:22
Here's the qvm-pci ls sys-net result:
![IMG_E3244](https://github.com/user-attachments/assets/58a56569-fd11-45b6-b4f3-38be2db896e9)

**Comment by marmarek** [comment] 2024-10-20 23:26
I'm not quite sure why in your case, but the ethernet controller changed its BDF. Go to sys-net's settings, remove the unknown device and add the correct ethernet controller.

Anyway, this looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/7792

**Comment by Oregano1963** [comment] 2024-10-21 00:05
> I noticed this in 4.2.3 install and mentioned it in #8322 - the wrong PCI device numbers retrieved initially (new to 4.2.3) - one can probably rescue that system by using the qubes.skip_autostart facility and taking the bad device numbers out of sys_net (& sys_usb) and replacing with the correct ones in settings.

How do I use the autostart facility/take the device out of sysnet and add the right one??

**Comment by Eric678** [comment] 2024-10-21 00:51
Sorry, as Marek said, you are actually running, so you can just go into  settings/devices in sys_net and you will see one of the assigned devices says device does not exist or something similar. Move that one to the left, and find the correct one and move it over to the right.

**Closed** 2024-10-21 05:14 UTC
Labels: T: bug, R: duplicate, P: default
