### ISSUE TITLE
4.0.1-rc2 Qubes Updater fails to find updates to whonix templates after running WhonixCheck in either whonix-gw-14 or whonix-ws-14 reports that packages can be updated

### ISSUE THREAD

**Issue by jrsmiley** [QubesOS/qubes-issues#4651] opened 2018-12-22 23:22 UTC
### Qubes OS version:

4.0.1-rc2

### Affected component(s): 

Qubes Updater

---

### Steps to reproduce the behavior:

select Q -> Template whonix-gw/ws-14 -> whonix-gw/ws 14 : WhonixCheck
Wait for it to complete
Both report  that apt-get reports that packages can be updated
We know for certain that at least one package can be updated after running any of the whonix-ws 14-based VMs or dvms and running the Tor browser, which indicates that a new version is available and then installing and running the new version.  Want to apply to Templates so that this is not necessary.

Tried applying updates two ways:
1. Qubes Updater, selecting both the ws and gw. Updater reports no updates available.
2. Select Konsole from shortcuts from either template and running `sudo apt-get-update-plus dist-upgrade`

### Expected behavior:

Either method applies updates

### Actual behavior:

Qubes Updater does not find any updates to apply.
Running the update manually in the Konsole finds and installs updates.

### General notes:

Found that although dist-upgrade did install new package versions, the Tor Browser was not among them.  I think this is expected behavior since there is a separate shortcut for running the browser updater.  Using this allows install of an updated Tor browser (8.0.4 or 8.5a6).  Chose 8.0.4 since that is the most recent GA version.

Also note that re-running WhonixCheck after the manual update reports that everything is up to date as one would expect.

---

**Comment by jrsmiley** [comment] 2018-12-22 23:45
Verified that vms and dvms based on ws template now start with the current browser after applying the update to the template using the browser update shortcut.

**Comment by marmarek** [comment] 2018-12-23 00:06
Duplicate of #4650

**Closed by marmarek** 2018-12-23 00:06 UTC
