### ISSUE TITLE
Feature Request: More Colors Please

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3847] opened 2018-04-23 08:26 UTC
In the Qubes Manager, it would be nice if there were more colors to choose from when coloring the Qubes.  Even better if we could have an HTML color picker that also saves the most recent, or favorites.

**Comment by andrewdavidwong** [comment] 2018-04-24 00:25
Duplicate of #2523

**Comment by andrewdavidwong** [comment] 2018-04-24 00:26
This appears to be a duplicate of #2523 (but also see #2646). If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2018-04-25 04:27 UTC
Labels: duplicate
