### ISSUE TITLE
start Display manager before Qubes

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5594] opened 2020-01-22 02:43 UTC
**The problem you're addressing (if any)**
I need to wait for sys-usb, sys-net, sys-firewall to start before I can login and start other qube

**Describe the solution you'd like**
start Display manager before Qubes

**Where is the value to a user, and who might that user be?**
Reduce startup time

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by brendanhoar** [comment] 2020-01-22 16:58
A manual workaround that I use: configure a USB VM, but disable autostart for sys-usb, sys-net and sys-firewall.

If network-requiring VMs are to be used, sys-net and sys-firewall will auto-start. 

If USB access is needed, I'll start it manually. 

Since I opted to set up a sys-usb VM, even though I disabled autostart, my system boots quickly and the rd.qubes.hide_all_usb kernel option is used  With that option enabled dom0 is blind to all the USB devices so devices shouldn't be parsed even with sys-usb not running. See: https://github.com/QubesOS/qubes-issues/issues/2172

**Comment by rustybird** [comment] 2020-01-22 18:33
Duplicate of #3149

**Comment by andrewdavidwong** [comment] 2020-01-23 09:44
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-01-23 09:44 UTC
Labels: P: default, T: enhancement
