### ISSUE TITLE
KDE bugs after updated and crash system.

### ISSUE THREAD

**Issue by Aporbel** [QubesOS/qubes-issues#5475] opened 2019-11-20 23:11 UTC
My deepest apologises for this non-structure issue. I write from phone.

**** system 
qubes rc.4.0
4.19.82.1

after `sudo-dom0-update ` KDE began to lagging, flicking(like artifacts with videocard) and unresponse on click and etc. Before all was fine.
Next step: I tried to rollbacking(deleted with qubes docs)  to previous version and tried install with another repo, all of this was unsuccessful. Next I did `yum delete group 'KDE'` but this command crash many things in system not only things according KDE, ofc I have xfce, but my lightDM was crashed also. After this I logining  throught command line and started xfce and figured out that I can't download/update any packets. Now, I thinking about backup, could someone to say, it will be safety to recovery dom0 from backup and possible? Because I have a lot of important information on my qubes.

**Comment by Aporbel** [comment] 2019-11-20 23:15
and for future... how I can update system without some packet? about performance: i7-7700HQ, nvidia 1050, dell xps 15.

**Comment by Aporbel** [comment] 2019-11-21 15:09
Tried restore dom0 from backup but it's restored only user folders, I meant that it will be full backup like in other OS with restoring Os parameters.

**Comment by andrewdavidwong** [comment] 2019-11-22 08:57
> Tried restore dom0 from backup but it's restored only user folders, I meant that it will be full backup like in other OS with restoring Os parameters.

We have an open issue about this: #1635

**Comment by Aporbel** [comment] 2019-11-22 13:05
andrewdavidwong, sorry, but I saw that topic does not have any solutions or information which could help, it seems that not possible to recovery any VM as far as VM backup includes only user files eachs? For example, I would like to transfer from 1 pc to another pc my VMs, but it seems that I will recieve only user folders. It's look very terrible. I guessed that it will be restore system like timeshift in Linux Mint, or like timecapsule MacOs or alike Microsoft backup or something like this. Because it is work like a compress crypto container(winrar+dm crypt), but no one capability to restore none VM system. Similarly, it is mean that we will not have possibility to direct transfer our VMs  because if we do simple copying it will not work in new system because too many dependencies( like UUID each vm, etc). So, finally that down on me, if I broke my dom0(when I did "sudo yum delete group 'KDE'") and does not have a ways to resolve this. Can you say me one? If I understood right, when I transfer my Qubes throught qubes-backup to new system will get only users file without qube like VM?

**Comment by andrewdavidwong** [comment] 2019-11-24 08:29
> andrewdavidwong, sorry, but I saw that topic does not have any solutions or information which could help, it seems that not possible to recovery any VM as far as VM backup includes only user files eachs? For example, I would like to transfer from 1 pc to another pc my VMs, but it seems that I will recieve only user folders. It's look very terrible. I guessed that it will be restore system like timeshift in Linux Mint, or like timecapsule MacOs or alike Microsoft backup or something like this. Because it is work like a compress crypto container(winrar+dm crypt), but no one capability to restore none VM system. Similarly, it is mean that we will not have possibility to direct transfer our VMs because if we do simple copying it will not work in new system because too many dependencies( like UUID each vm, etc). So, finally that down on me, if I broke my dom0(when I did "sudo yum delete group 'KDE'") and does not have a ways to resolve this.

Sorry, I don't really understand what you're asking. I'll try to make a few clarifying statements to see if it helps:

* Generally, all of your important data (which I'll call "user data") should be in the home directories of your VMs.
* All the user data in a VM is included in a Qubes backup, as long as that VM is selected for backup.
* All user data is recoverable from a Qubes backup without any Qubes-specific tools.
* As discussed in #1635, several dom0 settings are not currently included in Qubes backups. We wish to improve this.

Does this help?

**Comment by Aporbel** [comment] 2020-05-24 18:20
Solved. I had reinstalled OS and restored from back up my qubes.

**Comment by andrewdavidwong** [comment] 2020-05-25 17:46
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-05-25 17:46 UTC
Labels: C: desktop-linux-kde, P: default, T: bug
