### ISSUE TITLE
Use fastestmirror attribute in qubes-dom0-update

### ISSUE THREAD

**Issue by LEXUGE** [QubesOS/qubes-issues#5017] opened 2019-05-03 02:02 UTC
**The problem you're addressing (if any)**
I added `fastestmirror=True` in `/etc/dnf/dnf.conf`. But `qubes-dom0-update` did nothing.

**Describe the solution you'd like**
`qubes-dom0-update` behaves like `dnf` on this attribute.

**Where is the value to a user, and who might that user be?**
This could help user to use the fastest mirror automatically without hardcode the files in `/etc/yum.repo.d`.
Users in some countries which has slow internet access to the default mirror. (such as China).

**Describe alternatives you've considered**
None

**Additional context**
None

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/downloads/
https://www.qubes-os.org/downloads/mirrors/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by marmarek** [comment] 2019-05-03 02:42
This is already done for Qubes 4.1:
https://github.com/QubesOS/qubes-core-admin-linux/commit/fb1c28477471e312805ce26568767ff6ed0fdab3
https://github.com/QubesOS/qubes-core-agent-linux/commit/10399e8ab36bb53660efa22653ea00cf7716c938
(basically send dnf.conf too, not only legacy yum.conf)

In the meantime, you can add this option to individual repositories, it should work then.

**Comment by LEXUGE** [comment] 2019-05-03 02:45
> This is already done for Qubes 4.1:
> [QubesOS/qubes-core-admin-linux@fb1c284](https://github.com/QubesOS/qubes-core-admin-linux/commit/fb1c28477471e312805ce26568767ff6ed0fdab3)
> [QubesOS/qubes-core-agent-linux@10399e8](https://github.com/QubesOS/qubes-core-agent-linux/commit/10399e8ab36bb53660efa22653ea00cf7716c938)
> (basically send dnf.conf too, not only legacy yum.conf)
> 
> In the meantime, you can add this option to individual repositories, it should work then.

What did you mean by adding this option to individual repositories?
How to? thank you.

**Comment by marmarek** [comment] 2019-05-03 02:49
In `/etc/yum.repos.d` - relevant `.repo` files. This option is valid in both global and per-repository context.

**Comment by marmarek** [comment] 2019-05-03 02:50
Oh, you can also call `qubes-dom0-update --setopt=fastestmirror=True`, but that would be less convenient (you'd need to use that option every time).

**Comment by LEXUGE** [comment] 2019-05-03 03:09
> Oh, you can also call `qubes-dom0-update --setopt=fastestmirror=True`, but that would be less convenient (you'd need to use that option every time).

I can accept that. Thank you

**Comment by andrewdavidwong** [comment] 2019-05-03 03:13
> This is already done for Qubes 4.1:
> [...]
> I can accept that. Thank you

Closing this as resolved. If you believe the issue is not yet resolved, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-05-03 03:13 UTC
Labels: C: other, P: default, T: enhancement
