### ISSUE TITLE
Document how to build a single component downloading dependencies from yum.qubes-os.org

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1820] opened 2016-03-08 10:11 UTC
https://groups.google.com/d/msgid/qubes-devel/904d80f2-4a4d-4072-a488-48da8086c4ad%40googlegroups.com

> 1) After fetching sources and building deps, making gui-daemon without 
> having built anything else fails.
> 
> Error: No Package found for qubes-core-libs
> Error: No Package found for qubes-core-libs-devel >= 1.6.1
> Error: No Package found for qubes-gui-common-devel
> Error: No Package found for qubes-libvchan-xen-devel
> Makefile.fedora:91: recipe for target 'dist-build-dep' failed

Reported by @jgriffiths

**Comment by iamahuman** [comment] 2021-02-07 13:43
Duplicate of #4788

**Comment by andrewdavidwong** [comment] 2021-02-08 11:22
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-02-08 11:22 UTC
Labels: C: builder, C: doc, P: minor, T: task, help wanted
