### ISSUE TITLE
Device widget not showing attached devices. 

### ISSUE THREAD

**Issue by yubiguel** [QubesOS/qubes-issues#4878] opened 2019-03-12 11:50 UTC
### Qubes OS version:
Qubes release 4.0 (R4.0)

### Affected component(s) or functionality:
Qubes Devices Widget (qui-devices)

---

### Steps to reproduce the behavior:
Insert USB device such as a yubikey or usb stick. Attach the device using the device widget. Check if attached device shows bold in the device widget. In some cases it will not show as attached (bold) even though it is attached (qvm-usb or qvm-block showing it is attached). In other cases it will show attached, if it shows attached, try to detach the device using the widget manager, this will fail to detach and the only way to detach the device is through command line (qvm-usb or qvm-block)

### Expected or desired behavior:
Devices that are attached to vm's should show on the device Widget as attached. Additionally when a device is shown as attached it should be possible to detach it by clicking again on the device in the widget device manager.

### Actual behavior:

After last update, when inserting any USB device (yubikey or usb stick) the device widget does not show that the device is attached to the VM even though it is. Additionally, you cannot detach the device from the VM anymore using the device widget as it thinks it has nothing attached. When doing qvm-usb or qvm-block on dom0 the devices show correctly attached. 

When a device does show as attached in the widget it will not show detached if you click on it on the device widget. If you completely remove the usb from the computer, the device manager will still show it attached.  This creates many problems when trying to attach detach and reattach devices to other vm's. Using qvm-usb and qvm-block works fine as an alternative for the time being.

### General notes:

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/usb/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
https://github.com/QubesOS/qubes-issues/issues/3525

**Comment by brendanhoar** [comment] 2019-03-12 14:54
This may be a more succinctly written (thanks!) duplicate of #4849, in which I believe I noted the git change IDs that might be leading to this.

**Comment by yubiguel** [comment] 2019-03-12 15:11
oh wow yes I missed that one completely seems like the same issue indeed.

**Comment by Eric678** [comment] 2019-03-12 20:50
Yes I commented on this elsewhere as well. The latest update wrapped the code and stopped it updating. You can kill the process (/usr/bin/python3 /usr/bin/qui-devices) before you want to use it to get the old functionality back.

**Comment by andrewdavidwong** [comment] 2019-03-13 00:58
Duplicate of #4849

**Comment by andrewdavidwong** [comment] 2019-03-13 00:58
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-03-13 00:58 UTC
