### ISSUE TITLE
domains widget disappears on reboot

### ISSUE THREAD

**Issue by PsychicCat** [QubesOS/qubes-issues#3059] opened 2017-08-29 02:40 UTC
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
I would expect to see the Qubes Domains Widget in the taskbar.

### Actual behavior
After rebooting the machine, the domains widget has not appeared after the initial install.

### General notes:

---

**Comment by marmarta** [comment] 2018-07-15 19:59
I cannot reproduce this - has it persisted through updates? Is it still occurring now?

**Comment by marmarta** [comment] 2018-09-11 15:11
I'm going to close this, as I cannot reproduce this and there's been no further activity. If it continues to happen, please reopen.

**Closed by marmarta** 2018-09-11 15:11 UTC
Labels: C: qubes-manager, bug
