### ISSUE TITLE
Qubes installer should warn the user about performance problems on HDDs

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4284] opened 2018-09-07 02:39 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes installer

---

### Steps to reproduce the behavior:

Install onto an HDD, or a mixture of an SSD and an HDD

### Expected behavior:

The installar promps the user, warning that performance will be poor unless Qubes is installed entirely to SSDs, with the default being for the user to go back and fix their partitioning

### Actual behavior:

No warnings, but performance is atrocious (VMs taking several minutes to start).

### General notes:

This bit me.  For several months, I had an extremely slow system.

Also, I hope I am not spamming the issue tracker too much :)

---

**Comment by unman** [comment] 2018-09-07 11:29
> No warnings, but performance is atrocious (VMs taking several minutes to start).

Not my experience using HDD: e.g on underpowered x230 with 8Gb RAM, average start time is less than 20 secs with window in 25s. Not hugely different from all SDD with 64G, and certainly not orders of magnitude different.
I suspect you were facing a local issue.

**Comment by andrewdavidwong** [comment] 2018-09-08 01:13
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-09-08 01:13 UTC
Labels: C: installer, enhancement
