### ISSUE TITLE
Archlinux template fails to build

### ISSUE THREAD

**Issue by JoranHonig** [QubesOS/qubes-issues#2578] opened 2017-01-14 20:24 UTC
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
archlinux

---
### Steps to reproduce the behavior:
Follow the qubes guide to create an arch template.

Use the fixes described in issue #2565, https://github.com/QubesOS/qubes-issues/issues/2565#issuecomment-271483484
Change qubes-builder/qubes-src/gui-agent-linux/archlinux/PKGBUILD to not depend on xorg-server<1.19.0 since this makes the build fail.

### General notes:
template build log:  [template-archlinux.log.zip](https://github.com/QubesOS/qubes-issues/files/706194/template-archlinux.log.zip)
output of make template: [template.txt](https://github.com/QubesOS/qubes-issues/files/706196/template.txt)

---

#### Related issues:
https://github.com/QubesOS/qubes-issues/issues/2565

**Comment by andrewdavidwong** [comment] 2017-01-14 22:19
Like #2565, this is a duplicate of #2557. I can't tell from your description whether you're failing to build the Arch Linux template, or whether you're providing a solution. if you think #2557 should be reopened, please comment there.

**Closed by andrewdavidwong** 2017-01-14 22:19 UTC

**Comment by JoranHonig** [comment] 2017-01-14 23:34
#2557 fails on make qubes-vm, whereas I cant get make template to work. The log and output of this command are in the issue description. 
Sorry for not stating this clearly enough.

**Comment by andrewdavidwong** [comment] 2017-01-15 11:47
So, are you saying that this is actually different issue from #2557? Or are you just trying to get help? If you're just trying to get help, please send a message to the qubes-users mailing list. You can read more about our mailing lists here: https://www.qubes-os.org/mailing-lists/

If you think #2557 is still a problem and should be reopened, then please post your relevant report as a comment there, and I will reopen it.

**Comment by JoranHonig** [comment] 2017-01-15 12:34
Yes I think this is a different issue from #2557.

To be clear, I'm in the following situation.
 - Installed clean Qubes 3.2
 - Followed the guide to build an arch template [link](https://www.qubes-os.org/doc/templates/archlinux/)
 This at first failed on the same things as #2557(in make qubes-vm)
After having used the fix described in the issue converstion for #2557, it failed again because it could match the dependency xorg-server<1.19.0.
After having changed it to also allow higher versions ( this might cause problems later on ), make qubes-vm finishes successfully.
 - I then run make template, which results in the logs and output described in my first post.

Since I used a clean install and the default guide, and this is unreported and or undefined behavior I believe this should be an issue. However, if the mailing list is a better place deal with this problem, I'll be happy to ask my question there.

**Comment by andrewdavidwong** [comment] 2017-01-15 12:58
Ok, then this is still the same fundamental issue as #2557. The fundamental issue is that the Arch Linux template fails to build. It's the same issue across all three tickets. It's simply that you got further along in the process (thanks to the work done in #2557). So, you should be posting all of this in #2557, which I will now reopen.
