### ISSUE TITLE
Bad Error Messaging Deleting Fedora 32 Template

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6473] opened 2021-03-20 05:06 UTC
**Qubes OS version**
4.03

**Affected component(s) or functionality**
Fedora 32 Template

**Brief summary**
Can not delete Fedora 32 template using Qubes Manager.

**How Reproducible**
100%

**To Reproduce**

1. Install Fedora 32 template on command line using https://www.qubes-os.org/news/2020/06/30/fedora-32-templates-available/
2. Delete Fedora 32 template by right-click and delete
3. VM installed by package manager: fedora-32

**Expected behavior**

Either:

1. qube should delete like all qubes

2. "Delete" option should not be available, but instead "delete template"

3. Error message should be useful, as in: tell me what I should do to delete this.

**Actual behavior**

It just barks at me and gives no pointer to make progress.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

I feel like I reported this on an older Fedora template but I could not find that report.

**Comment by DemiMarie** [comment] 2021-03-20 06:45
“VM installed by package manager“ is indeed a bad error message.  The fix is to run `dnf remove qubes-template-fedora-32` instead, but the error message should at least suggest doing that.  It would be even better if this was done automatically, at least if i does not cause dependency problems.

**Comment by andrewdavidwong** [comment] 2021-03-20 22:13
Duplicate of #5509

**Comment by andrewdavidwong** [comment] 2021-03-20 22:15
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2021-03-20 22:15
Please search existing issues before opening new ones -- at least your own!

**Closed** 2021-03-20 22:16 UTC
Labels: P: default, R: duplicate, T: bug
