### ISSUE TITLE
Builder requires libgcc_s.so.1

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#3707] opened 2018-03-17 07:14 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

builder

---

### Steps to reproduce the behavior:

`make clean`
`make clean-chroot`
Attempt to `make qubes` with standard selections

### Expected behavior:

Shiny new ISO

### Actual behavior:

`Error: package gcc-6.4.1-1.qubes1.fc25.x86_64 requires libgcc_s.so.1, but none of the providers can be installed`

### General notes:

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3650 ?

**Comment by awokd** [comment] 2018-03-17 07:17
Only log is `gcc-dom0-fc25.log`, attaching.
[gcc-dom0-fc25.log](https://github.com/QubesOS/qubes-issues/files/1821363/gcc-dom0-fc25.log)

**Comment by awokd** [comment] 2018-03-17 07:43
Looks like https://github.com/marmarek/qubes-vmm-xen/commit/b79f692a2da10856f01c68eefbecbf5b1bcf8820 is intended to address it.

**Comment by marmarek** [comment] 2018-03-17 12:19
There is gcc-6.4.1-1.qubes2.fc25 which have this problem resolved.
Also, this is a duplicate of https://github.com/QubesOS/qubes-issues/issues/3650

**Closed by marmarek** 2018-03-17 12:19 UTC

**Comment by awokd** [comment] 2018-03-17 12:41
Had that linked as a related issue but the problem myself and a couple others on the mailing list are running into is that the standard `make clean` is not sufficient to get qubes-builder back in working order.
Will report over on the linked issue instead of this one once the gcc build finishes...
