### ISSUE TITLE
qubesdb-read /qubes-ip -> Failed connect to local daemon

### ISSUE THREAD

**Issue by oiefbajweiufhjm** [QubesOS/qubes-issues#5379] opened 2019-10-08 17:01 UTC
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
sys-whonix

**Brief summary**
Fresh install. sys-whonix displays an error dialog showing that the whonix-firewall failed to start for some reason.

**To Reproduce**
_Steps to reproduce the behavior:_
Start Qubes

**Expected behavior**
No error from sys-whonix

**Actual behavior**
Error from sys-whonix saying the whonix-firewall could not start

**Screenshots**
```
ERROR: whonix_firewall failed to load! 

The whonix_firewall failed to load for some reason. This could be due to the firewall being mis-configured or race-condition. Try restarting the VM to see if this error persists. 

Failure file /var/run/anon-firewall/failed.status exists! 

output of systemctl status whonix-firewall: 

######################################## 
● whonix-firewall.service - Whonix firewall loader
Loaded: loaded (/lib/systemd/system/whonix-firewall.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Tue 2019-10-08 16:27:16 UTC; 57s ago
Docs: https://www.whonix.org/wiki/Whonix_Firewall
Process: 396 ExecStart=/usr/lib/whonix-firewall/enable-firewall (code=exited, status=1/FAILURE)
Main PID: 396 (code=exited, status=1/FAILURE) 
######################################## 

To see this for yourself... 
1. Open a terminal. (dom0 -> Start Menu -> ServiceVM: -> Terminal) 
2. Run. 
systemctl status whonix-firewall

2. Also see. 
sudo journalctl -u whonix-firewall | cat

3. Try to manually start Whonix firewall. 
sudo whonix_firewall
If you know what you are doing, feel free to disable this check. Create a file /etc/whonix.d/50_whonixcheck_user.conf and add: 
whonixcheck_skip_functions+=" check_whonix_firewall_systemd_status "
```

```
user@host:~$ sudo journalctl -u whonix-firewall | cat
-- Logs begin at Tue 2019-10-08 16:27:16 UTC, end at Tue 2019-10-08 17:02:29 UTC. --
Oct 08 16:29:35 host systemd[1]: Starting Whonix firewall loader...
Oct 08 16:29:35 host enable-firewall[396]: OK: Loading Whonix firewall...
Oct 08 16:29:35 host enable-firewall[396]: OK: Skipping firewall mode detection since already set to 'full'.
Oct 08 16:29:35 host enable-firewall[396]: OK: (Full torified network access allowed.)
Oct 08 16:29:35 host enable-firewall[396]: OK: TOR_USER: 112
Oct 08 16:29:35 host enable-firewall[396]: OK: CLEARNET_USER: 106
Oct 08 16:29:35 host enable-firewall[396]: OK: USER_USER: 1000
Oct 08 16:29:35 host enable-firewall[396]: OK: ROOT_USER: 0
Oct 08 16:29:35 host enable-firewall[396]: OK: TUNNEL_USER: 107
Oct 08 16:29:35 host enable-firewall[396]: OK: SDWDATE_USER: 110
Oct 08 16:29:35 host enable-firewall[396]: OK: WHONIXCHECK_USER: 109
Oct 08 16:29:35 host enable-firewall[396]: OK: NO_NAT_USERS:  106 107 112
Oct 08 16:29:35 host enable-firewall[396]: Failed connect to local daemon
Oct 08 16:27:16 host systemd[1]: whonix-firewall.service: Main process exited, code=exited, status=1/FAILURE
Oct 08 16:27:16 host systemd[1]: Failed to start Whonix firewall loader.
Oct 08 16:27:16 host systemd[1]: whonix-firewall.service: Unit entered failed state.
Oct 08 16:27:16 host systemd[1]: whonix-firewall.service: Failed with result 'exit-code'.
```
```
user@host:~$ systemctl status qubes-db.service                                                                                                                                                                                 
● qubes-db.service - Qubes DB agent
   Loaded: loaded (/lib/systemd/system/qubes-db.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Tue 2019-10-08 17:28:24 UTC; 7s ago
  Process: 3620 ExecStart=/usr/sbin/qubesdb-daemon 0 (code=killed, signal=SEGV)
  Process: 3617 ExecStartPre=/bin/mkdir -p /var/run/qubes (code=exited, status=0/SUCCESS)
 Main PID: 3620 (code=killed, signal=SEGV)

Oct 08 17:28:24 host systemd[1]: Starting Qubes DB agent...
Oct 08 17:28:24 host systemd[1]: qubes-db.service: Main process exited, code=killed, status=11/SEGV
Oct 08 17:28:24 host systemd[1]: Failed to start Qubes DB agent.
Oct 08 17:28:24 host systemd[1]: qubes-db.service: Unit entered failed state.
Oct 08 17:28:24 host systemd[1]: qubes-db.service: Failed with result 'signal'.
```

**Additional context**
This is a brand new installation
Dom0 was updated successfully
I am also unable to update fedora-29 for some reason. Either using the GUI updater or running the update command manually will result in : 
`
Updating fedora-29
Error on updating fedora-29
Failed to synchronize cache for repo fedora-modular
`

**Solutions you've tried**
2. Try to launch `enable-firewall` manually -> `Failed connect to local daemon`
3. Running manually: `qubesdb-read /qubes-ip` ->  `Failed connect to local daemon`
4. Restarting the machine
5. `sudo qubes-dom0-update --action=upgrade qubes-template-debian9`
6. `sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-gw-14`
7. `sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-ws-14`

**Related doc**
https://github.com/QubesOS/qubes-issues/issues/4603

**Comment by adrelanos** [comment] 2019-10-28 14:58
Not a Whonix issue. Whonix is a symptom here, not the cause.

> 3. Running manually: qubesdb-read /qubes-ip -> Failed connect to local daemon

This is the underlying Qubes issue which needs to be debugged which however I cannot help with.

> qubes-template-whonix-gw-14

Outdated. Deprecated. Use Whonix 15.

**Comment by andrewdavidwong** [comment] 2019-10-29 05:27
> Not a Whonix issue. Whonix is a symptom here, not the cause.
> 
> > 1. Running manually: qubesdb-read /qubes-ip -> Failed connect to local daemon
> 
> This is the underlying Qubes issue which needs to be debugged which however I cannot help with.
> 

Thank you for the clarification.

> > qubes-template-whonix-gw-14
> 
> Outdated. Deprecated. Use Whonix 15.

I'm closing this because Whonix 14 is no longer supported. If the problem recurs with Whonix 15 (or a different type of VM), please leave a comment, and we can reopen this issue.

**Closed** 2019-10-29 05:28 UTC
Labels: C: core, P: default, T: bug
