### ISSUE TITLE
Enable Pointer/Hand cursor state affordance changes on clickable areas

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6596] opened 2021-05-11 01:48 UTC
**The problem you're addressing (if any)**
On my Qubes 4.0 machine, the arrow is not able to dynamically change from an arrow to an i-bar to a hand-pointer affordance, when over a clickable area, in any web browser or client app. Debian, Fedora, nada. When developing the SecureDrop Workstation client, the team also hit a wall enabling that to work in the client app (QT) as it's not supported in Qubes in any way.

This is a major usability issue and also factors into accessibility. 

While this is not an attribute of  many x-code (native Apple) apps, it is for many other cross-platform client applications. It is also expected behavior in web browsers, and many websites are developed without hover states, these days, assuming that is a capability.

**Describe the solution you'd like**
Do the things with the codes to enable app clients that support this functionality, to display cursor changes to the user. Likewise, would be lovely to have any desktop widgets do the same. Not sure if this is built-in to Gnome and the solution would just be to migrate XFCE over to Gnome asap, or if it'd have to be built in to XFCE... or if this is a focus-steal mitigation, GUI VM, or some other security something that would fly over my head.

**Where is the value to a user, and who might that user be?**
Affordances matter. :)
https://usabilitypost.com/2009/10/26/mouse-cursor-affordance/

**Describe alternatives you've considered**
Tears. As a UX contributor to a client app specifically for Qubes, yes, I can spec out hover states to somewhat overcome this... but I suspect I'm literally the only designer designing exclusively for Qubes, so this is a workaround that should be short lived. It also remains awkward that as a hybrid Qubes/Mac user, when I oscillate between the two environments, I get cursor affordances on one machine... but not the other. FPF developers on Ubuntu and Debian machines have expressed similar dual-machine confusion with this.

**Comment by DemiMarie** [comment] 2021-05-11 03:00
The underlying problem is that the cursor is drawn in dom0, but dom0 has no idea where buttons, etc are.  Having the GUI domain know about this information is a no-no as it exposes way too much attack surface, so this will need to be implemented via a domU→dom0 GUI message.

Looking at https://xcb.freedesktop.org/tutorial/mousecursors, we can support cursors that are predefined by the X server, but application-defined cursors will likely never be supported.  I am not sure how this is handled by Wayland, but we will be switching from X to Wayland in R4.2.

**Comment by marmarek** [comment] 2021-05-11 03:05
Duplicate of https://github.com/QubesOS/qubes-issues/issues/1551
And it is already implemented in R4.1 :)

**Closed by marmarek** 2021-05-11 03:05 UTC
Labels: P: default, T: enhancement

**Comment by ninavizz** [comment] 2021-05-11 07:13
THAT'S why I couldn't find it!! TY @DemiMarie for the helpful context, and @marmarek for allthethings! :)

**Comment by ubuntupunk** [comment] 2025-05-18 07:10
Been struggling with periodic issues to do with cursor not being able to grab certain ui components in the vm. Will for example stop being able to move firefox, can select the bar, but then not any file dropdown in xfce terminal etc. Is resolved by logging out, or rebooting the vm.
