### ISSUE TITLE
Whonix Tor Browser's NoScript is occasionally disabled(unrestrictive)

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5102] opened 2019-06-17 17:31 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Whonix 14 Tor Browser

**Brief summary**
Sometimes the NoScript included in the Tor Browser is set to allow everything. Opening it and clicking reset fixes the issue.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Start a Whonix 14 DVM with Tor Browser

**Expected behavior**
Scripts on most sites are blocked by default

**Actual behavior**
Every once in a while - everything is allowed, same as if NoScript is not installed.

**Solutions you've tried**
Opening NoScript settings and doing Reset fixes the problem albeit temporarily. You can't know when it will happen again when opening a Whonix disposable VM.

**Notes**
Not sure if this is the correct place to report this. Sorry if I am mistaken to post it here.

**Comment by adrelanos** [comment] 2019-06-20 13:04
For reference:
https://forums.whonix.org/t/tor-browser-in-whonix-blocks-javascript-only-when-started-for-the-first-time-and-in-dispvms/6843

**Comment by iprid23** [comment] 2019-07-05 10:26
@adrelanos
Does this imply that the expected behaviour is for NoScript to not block the scripts? Or so it says in the Whonix issue?

If so, how is this behaviour controlled? I'd prefer to have it block all scripts by default on every Disposable VM start.

Also, is there a bug filled for the disappearence of the NoScript button in the browser menu bar?
It's really annoying have it drag it from Customizations each time you use a Disposable VM.

Regards

**Comment by adrelanos** [comment] 2019-07-05 11:18
Generally:

- https://www.whonix.org/wiki/Free_Support_Principle
-
https://www.whonix.org/wiki/Reporting_Bugs#Linux_User_Experience_versus_Commercial_Operating_Systems

iprid23:
> @adrelanos
> Does this imply that the expected behaviour is for NoScript to not block the scripts?


Defaults are up to The Tor Project. See also:

https://www.whonix.org/wiki/Tor_Browser#NoScript

> Or so it says in the Whonix issue?


If there was one it should now be fixed in Whonix 15 and with later
upgrades this will be further solidified. See tb-updater git commit history.

> If so, how is this behaviour controlled? I'd prefer to have it block all scripts by default on every Disposable VM start.


Tor Browser by The Tor Project does not provide an environment variable
or documentation on how to enable blocking of all scripts upon start of
Tor Browser. Neither a ticket against Tor Project exists.

See also:

https://www.whonix.org/wiki/Tor_Browser#Tor_Browser_Bundle_versus_Whonix_Tor_Browser

https://www.whonix.org/wiki/Tor_Browser#Tor_Browser_Functionality_on_Different_Platforms

> Also, is there a bug filled for the disappearence of the NoScript button in the browser menu bar?


Decision by Tor Project.

> It's really annoying have it drag it from Customizations each time you use a Disposable VM.


Customizations discouraged by Tor Project, documented here:

https://www.whonix.org/wiki/Tor_Browser#NoScript_Custom_Setting_Persistence

**Comment by marmarek** [comment] 2019-07-05 16:16
> Defaults are up to The Tor Project. See also: https://www.whonix.org/wiki/Tor_Browser#NoScript

Clarification: as explained in [this section](https://www.whonix.org/wiki/Tor_Browser#Security_vs_Usability_Trade-off), The Tor Project decided to disable NoScript by default and Whonix intentionally honor this choice. This means it works as intended.

**Closed by marmarek** 2019-07-05 16:16 UTC
Labels: C: Whonix, P: default, T: bug
