### ISSUE TITLE
StandaloneVM and TemplateVM do not boot from iso

### ISSUE THREAD

**Issue by 9ca4it** [QubesOS/qubes-issues#3402] opened 2017-12-15 21:11 UTC
#### Qubes OS version:

4.0rc3

#### Affected TemplateVMs: 

standalone (eg: kali, windows, etc)

---

### Steps to reproduce the behavior:

qvm-create --class StandaloneVM -l blue kali
qvm-start kali cdrom=vmname:/home/Downloads/kali.iso

### Expected behavior:

vmname launches and boots from iso

### Actual behavior:

if the iso is not in dom0, it is met with an empty response from qubesd
if the iso is in dom0, the vm launches and then crashes after "Probing EDD"

### General notes:

---

**Comment by andrewdavidwong** [comment] 2017-12-16 05:07
This appears to be a duplicate of #3282. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-16 05:07 UTC

**Comment by 9ca4it** [comment] 2017-12-16 13:35
if I set the kernel to '', it has the error "libxenlight failed to create new domain 'kali'"

which seems to be #3339, where there doesn't seem to be a solution for that either
