### ISSUE TITLE
qubes-hcl-report ambigious redirect no report creation

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#2087] opened 2016-06-20 00:54 UTC
#### Qubes OS version (e.g., `R3.1`):
Qubes OS R3.1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0 fedora 20

---

### Expected behavior:
file creation

### Actual behavior:
error: ambiguous redirect

### Steps to reproduce the behavior:

use the `qubes-hcl-report` in the CLI of Qubes R3.1 (fedora 20).

~~~
qubes-hcl-report 
qubes-hcl-report -s
~~~
![qubes-hcl-report-file-error](https://cloud.githubusercontent.com/assets/2007739/16180898/7b6f54b4-3657-11e6-8608-2c6bce691dca.png)
![qubes-hcl-report-s-file-error](https://cloud.githubusercontent.com/assets/2007739/16180899/7b6f89b6-3657-11e6-9b76-ad0f09db6cea.png)

**Comment by marmarek** [comment] 2016-06-20 01:16
Duplicate of #1994

**Closed by marmarek** 2016-06-20 01:16 UTC
Labels: duplicate

**Comment by Jeeppler** [comment] 2016-06-20 02:26
@marmarek I was not sure if this is a duplication. Thanks for the clarification.
