### ISSUE TITLE
qui-domains and qui-devices should run under systemd user services

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4585] opened 2018-12-07 13:21 UTC
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

dom0 GUI

---

### Steps to reproduce the behavior:

Try to restart `qui-domains` and/or `qui-devices`.

### Expected behavior:

There is an easy and documented way to do this.

### Actual behavior:

No such method.

### General notes:

Running `qui-devices` and `qui-domains` as systemd user units would solve this problem.  They can be started by `xfce` using `systemctl --user`.

The same argument applies to `qui-disk-space`, but I have never had to restart it.

---

**Comment by marmarek** [comment] 2018-12-07 14:07
Duplicate of #4397 

That said, we've considered it in the past and the issue is that systemd user session is not bound to GUI session - if may be started way before X server. Also, systemd session is not terminated when X session is terminated (for the same reason), so if we'd use `systemd --user` only for automatic restart when the process exit, we'd need to handle that too (avoid trying to start qui-domains over and over when X session is not available). 
It's possible that those issues are easier to solve than using another mechanism for automatic widget restarts...

**Closed by marmarek** 2018-12-07 14:07 UTC
