### ISSUE TITLE
Archlinux template fails to build

### ISSUE THREAD

**Issue by hThoreau** [QubesOS/qubes-issues#2565] opened 2017-01-09 16:20 UTC
## Qubes OS version R3.2
Fedora-23 Standalone appVM, building Archlinux

---

## Expected behavior:
Running `make template` succeeds.

## Actual behavior:
```
[user@archlinux qubes-builder]$ make template
mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/vmm-xen/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/vmm-xen/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/core-vchan-xen/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-vchan-xen/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/core-qubesdb/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-qubesdb/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/linux-utils/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/linux-utils/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/core-agent-linux/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/core-agent-linux/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/gui-common/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/gui-common/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/gui-agent-linux/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/gui-agent-linux/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
	pkgnames=`cat qubes-src/app-linux-split-gpg/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
	for pkgname in $pkgnames; do\
		ln -f qubes-src/app-linux-split-gpg/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
	done;\
done;\

-> Building template archlinux (logfile: build-logs/template-archlinux.log)...
Makefile:297: recipe for target 'template-local-archlinux' failed
make: *** [template-local-archlinux] Error 1

```

1. Follow instructions provided in the documentation (https://www.qubes-os.org/doc/templates/archlinux/);
2. Execute fix described here (https://github.com/QubesOS/qubes-issues/issues/2557) when `make qubes-vm` fails;
3. Retry `make qubes-vm`
4. `make template`

## General notes:
I've also attached the log that was returned to me bellow. 
[template-archlinux.txt](https://github.com/QubesOS/qubes-issues/files/694361/template-archlinux.txt)

I'm a Graphic Designer by trade, I'm as familiar to CLI as my grandma is to GUI, meaning, I couldn't code even if my life depended on it. XD I'm more than grateful for any aid provided, but please, try to didatic with me.

Thanks in advance.

**Comment by hThoreau** [comment] 2017-01-09 18:04
I would like to add the log that was returned to me.
[template-archlinux.txt](https://github.com/QubesOS/qubes-issues/files/694271/template-archlinux.txt)

**Comment by unman** [comment] 2017-01-09 18:30
On Mon, Jan 09, 2017 at 08:20:59AM -0800, hThoreau wrote:
> ## Qubes OS version R3.2
> Fedora-23 VM, building Archlinux
> 
> 
> ---
> 
> ## Expected behavior:
> Running `make template` succeeds.
> 
> ## Actual behavior:
> ```
> [user@archlinux qubes-builder]$ make template
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/vmm-xen/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/vmm-xen/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/core-vchan-xen/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/core-vchan-xen/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/core-qubesdb/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/core-qubesdb/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/linux-utils/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/linux-utils/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/core-agent-linux/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/core-agent-linux/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/gui-common/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/gui-common/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/gui-agent-linux/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/gui-agent-linux/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> mkdir -p /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
> for arch_build_dir in archlinux; do\
> 	pkgnames=`cat qubes-src/app-linux-split-gpg/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
> 	for pkgname in $pkgnames; do\
> 		ln -f qubes-src/app-linux-split-gpg/pkgs/$pkgname-*.pkg.tar.xz /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
> 	done;\
> done;\
> 
> ln: failed to access ‘qubes-src/app-linux-split-gpg/pkgs/qubes-split-*.pkg.tar.xz’: No such file or directory
> /home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:156: recipe for target 'update-repo' failed
> make[1]: *** [update-repo] Error 1
> Makefile:297: recipe for target 'template-local-archlinux' failed
> make: *** [template-local-archlinux] Error 1
> ```
> Steps to reproduce the behavior:
> 
> 1. Follow instructions provided in the documentation (https://www.qubes-os.org/doc/templates/archlinux/);
> 2. Execute fix described here (https://github.com/QubesOS/qubes-issues/issues/2557) when make qubes-vm fails;
> 3. build the following components (`make core-agent-linux-vm`, `make gui-common-vm` and `make gui-agent-linux-vm` individually).
> 4. $ make template
> 
> ## General notes:
> I'm a Graphic Designer by trade, I'm as familiar to CLI as my grandma is to GUI, meaning, I couldn't code even if my life depended on it. XD I'm more than grateful for any aid provided, but please, try to didatic with me.
> 
> Thanks in advance.
> 

It seems you have not built app-linux-split-gpg?
Try 'make app-linux-split-gpg-vm'
Then 'make template'

**Comment by hThoreau** [comment] 2017-01-09 19:02
I've got the following message:
`[user@archlinux qubes-builder]$ make app-linux-split-gpg-vm
Currently installed dependencies:
git-2.5.5-1.fc23.x86_64
rpmdevtools-8.9-1.fc23.noarch
rpm-build-4.13.0-0.rc1.13.fc23.x86_64
createrepo-0.10.3-3.fc21.noarch
debootstrap-1.0.87-1.fc23.noarch
dpkg-dev-1.17.27-1.fc23.noarch
python-sh-1.11-1.fc23.noarch
dialog-1.3-4.20160424.fc23.x86_64
--> Archlinux dist-prepare-chroot (makefile):
  --> Checking mounting of dev/proc/sys on build chroot...
    --> sudo mount --bind /dev/pts /home/user/qubes-builder/chroot-archlinux/dev/pts;
  --> Synchronize resolv.conf, in case it changed since last run...
cp: cannot stat ‘/etc/resolv.conf’: No such file or directory
/home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:65: recipe for target 'dist-prepare-chroot' failed
make[1]: *** [dist-prepare-chroot] Error 1
Makefile:209: recipe for target 'app-linux-split-gpg-vm' failed
make: *** [app-linux-split-gpg-vm] Error 1
`

**Comment by cryptix** [comment] 2017-01-09 19:52
Hey @hThoreau!

I just completed the steps in the documentation and got a working rpm-file to install the template, create one and boot it.

I first hit step 2 (the missing init) myself. Did you use rdhammond workaround or the one marmarek linked to?

**Comment by hThoreau** [comment] 2017-01-09 20:21
By "rdhammond workaround" you refer to this [post](https://github.com/QubesOS/qubes-issues/issues/2560), am I correct? In that case, yes, I've used it. By "the one marmarek linked to, you refer to this [piece of code](https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/7/commits/80b2d0b64988cc9b67fb38bd6eeedab76b20ba49)? I've already found that correction performed in the qubes-builder files.

**Comment by hThoreau** [comment] 2017-01-09 21:52
@cryptix 
I'll try following the thread you've linked, and as soon as I'm finished I'll discuss my results here. Thanks! As for the umount, you think an open text editor might have caused that?

**Comment by hThoreau** [comment] 2017-01-09 22:03
@cryptix
Where did you get the "init" from? As for the umount, you think an open text editor might have caused that?

**Comment by cryptix** [comment] 2017-01-09 22:03
Okay, just make sure `make qubes-vm` works without many modifications. I only had to add the `init` to the `PKGBUILD`, nothing else.

> As for the umount, you think an open text editor might have caused that?

Text editor: unlikely, they usually only hold files open while they save or read files.

What I meant in general is this :

* open your terminal (like gnome-terminal)
* insert a usb key and mount it or network share.
* go into that location `cd /media/usbkey/...`
* try to unmount the usb drive (it will result in a `target is busy` error)

This is pretty arcane phenomena and can be hard to catch.

In this special case the system should know how to cleanly unmount, I think.

**Comment by hThoreau** [comment] 2017-01-10 04:27
Thank you @cryptix,
I manage to build the template! I performed the following substitutions in order to do so:

Change
```
> # FIXME: do a source code move vm-systemd/*.sh to init/
> # since those scripts are shared between sysvinit and systemd.
> install -m 0755 init/*.sh vm-systemd/*.sh $(DESTDIR)$(LIBDIR)/qubes/init/
> install -m 0644 init/functions $(DESTDIR)$(LIBDIR)/qubes/init/
```
for
```
# FIXME: do a source code move vm-systemd/*.sh to init/
# since those scripts are shared between sysvinit and systemd.
install -m 0755 /home/user/qubes-src/core-agent-linux/init/*.sh vm-systemd/*.sh $(DESTDIR)$(LIBDIR)/qubes/init/
install -m 0644 /home/user/qubes-src/core-agent-linux/init/functions $(DESTDIR)$(LIBDIR)/qubes/init/
```
in the document
`/qubes-builder/qubes-src/core-agent-linux/Makefile`

I've also changed the first line of the document
`/qubes-builder/qubes-src/app-linux-split-gpg/doc/Makefile`
to
`PANDOC=/bin/true `

Finally, [I've did what you suggested](https://github.com/QubesOS/qubes-core-agent-linux/pull/32/commits/d1faba7d03380711ed15cb9a0465ee477e283cc9), so maybe those first two modifications where just overkill. XD

Now I'm stuck in the next set (yay!) getting denied permission to transfer the template to the dom0. I've to figure that one now...

**Comment by cryptix** [comment] 2017-01-10 05:02
Nice that you got the template!!

> bash: install-templates.sh  Permission denied

Hm.. yea. that script seemed unnecessary to me.

Try to fetch the .rpm from the `noarch` directory (like explained in [copy to dom0](https://www.qubes-os.org/doc/copy-from-dom0/)) and then run `sudo dnf install xxx.rpm` and delete it afterwards. That's everything the script does, notice that only the `dnf install` needs sudo.

hope that helps.

**Comment by hThoreau** [comment] 2017-01-10 05:33
It seems that the code suggested in the guide follows the same structure from the one in link you've passed. Though I might be messing up in the syntax... Anyway, the following piece of code didn't return me an error message, though there was any confirmation of success and I can't seem to find the file:
```
sudo qvm-run --pass-io archlinux 'cat /home/user/qubes-builder/qubes-src/linux-template-builder/rpm/noarch/qubes-template-archlinux-3.0.6-201701100134.noarch.rpm' > qubes-tempalte-archlinux--33.0.6-201701100134.noarch.rpm
```

**Comment by andrewdavidwong** [comment] 2017-01-10 10:24
I'm glad you've able to help each other and make progress on this on your own. :)

For issue tracking purposes, this is obviously a duplicate of #2557 (as I'm sure you know, having cited that issue yourself), so I'm marking and closing it as a duplicate for organizational purposes. But please feel free, of course, to finish your discussion here, if it's helping. (In the future, you may find the MLs more appropriate as a medium for this type of exchange.)

**Closed by andrewdavidwong** 2017-01-10 10:24 UTC
Labels: duplicate
