### ISSUE TITLE
Split-GPG is incompatible with Tor Birdy

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1024] opened 2015-06-04 00:36 UTC
Attempting to use Split-GPG and Tor Birdy at the same time results in no GPG notifications in Thunderbird at all when viewing signed or encrypted messages.

**Comment by qjoo** [comment] 2015-06-04 17:03
see also:
https://groups.google.com/d/msg/qubes-users/64Pk_1U9FMU/-uj8qZ7787sJ
https://trac.torproject.org/projects/tor/ticket/14025

**Comment by mfc** [comment] 2016-02-19 17:00
also: https://trac.torproject.org/projects/tor/ticket/16935

**Comment by marmarek** [comment] 2016-02-29 01:40
Since there is no much interest from Tor developers, maybe we can simply ignore --keyserver-options in qubes-gpg-client-wrapper? This might have some negative impact if GPG VM is not really offline, but that would be misuse of gpg-split anyway.

cc @adrelanos

**Comment by adrelanos** [comment] 2016-02-29 09:49
Marek Marczykowski-Górecki:
> Since there is no much interest from Tor developers, maybe we can simply ignore --keyserver-options in qubes-gpg-client-wrapper?

That would be good enough as workaround given current resources, I suppose.

[ The clean solution would be to run the keyserver fetches in the mail
VM since that is supposed to be online. And the
encrypt/decrypt/sign/verify inside the gpg VM. All automagically. So it
does not matter how other applications handle it. ]

**Comment by marmarek** [comment] 2016-02-29 10:30
Can you look at linked patch, with your bash-expert hat on?

**Comment by adrelanos** [comment] 2016-02-29 14:57
Probably would cause issues. I am referring to of the most famous bash
hackers. We need a mix of http://mywiki.wooledge.org/WrapperScript and
http://mywiki.wooledge.org/BashFAQ/035.

I can come up with some pseudo code to filter out that command line
parameter.

**Comment by adrelanos** [comment] 2016-02-29 15:24
The problem with `args=` is, that it can mess up quotes, double quotes and what not. The following has a problem but would be more canonical.

```
#!/bin/bash

while true; do
    case $1 in
        --keyserver-options)       # Takes an option argument, ensuring it has been specified.
            if [ -n "$2" ]; then
                shift
            else
                shift 2
            fi
            ;;
        *)               # Default case: If no more options then break out of the loop.
            break
    esac

    shift
done

# Rest of the program here.
# If there are input files (for example) that follow the options, they
# will remain in the "$@" positional parameters.

exec qubes-gpg-client "$@"
```

The problem is, that is only filters out `--keyserver-options` if it is the first command line parameter. Not if it is somewhere in the middle of the parameters.

**Comment by adrelanos** [comment] 2016-02-29 15:26
From http://wiki.bash-hackers.org/scripting/posparams please see chapter `Filter unwanted options with a wrapper script` seems better.

**Comment by adrelanos** [comment] 2016-02-29 15:35
Based on above, the following is similar to what you came up originally. Pseudo code.

```
#!/bin/bash

options=()  # the buffer array for the parameters
eoo=0       # end of options reached

while [[ $1 ]]
do
    if ! ((eoo)); then
	case "$1" in
          --keyserver-options)
            shift 2
            ;;
	  -[^-]*a*|-a?*)
	      options+=("${1//a}")
	      shift
	      ;;
	  --)
	      eoo=1
	      options+=("$1")
	      shift
	      ;;
	  *)
	      options+=("$1")
	      shift
	      ;;
	esac
    else
	options+=("$1")

	# Another (worse) way of doing the same thing:
	# options=("${options[@]}" "$1")
	shift
    fi
done

exec qubes-gpg-client "${options[@]}"
```
Can you make head or tail of it? Otherwise I could also a pull request. Obviously useful to run the test suite over it to see if this does not break something but I guess it should work.

**Comment by marmarek** [comment] 2016-02-29 19:50
> Can you make head or tail of it?

Yes, thanks. Will improve the current patch.

> Obviously useful to run the test suite over it

That's one reason why I've finally implemented #1368 - in the current shape it pass also on whonix-ws based AppVM. It's doing simple send + receive email.

**Comment by marmarek** [comment] 2016-02-29 20:55
Pushed updated version

**Comment by adrelanos** [comment] 2016-02-29 21:43
Looks good.

**Comment by marmarek** [comment] 2016-02-29 23:16
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-02-29 23:16
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-02-29 23:34
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-02-29 23:34
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-02-29 23:34
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-02-29 23:34
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-02-29 23:34
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.18-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:27
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:27
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:27
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:27
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.18-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:32
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/R3.1-rc1...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:32
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-07 03:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 01:32
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 01:32
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 01:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 01:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.18-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by axon-qubes** [comment] 2016-03-13 09:04
I'm afraid this still doesn't appear to be working.

I've tried testing with a `whonix-ws`-based AppVM (with TorBirdy enabled), where the GPG backend domain is based on `fedora-23` with the latest `qubes-gpg-split-2.0.18-1.fc23` package.

* Opening a PGP-signed email does not interact with GPG at all. It just shows the signature as plain text (for in-line signed messages).
* Attempting to send a PGP-signed email results in: `Enigmail Alert: Send operation aborted. Error - encryption command failed`
* Running `qubes-gpg-client` from the command line in the `whonix-ws`-based AppVM works as before. For example, passing `-K` still lists private keys in the backed domain.

**Comment by marmarek** [comment] 2016-03-13 10:17
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 10:17
The fix is in frontend package, so you need to update package in whonix-ws. As you can see, package for Debian is still in testing repo (just pushed to stable for R3.1)

**Comment by marmarek** [comment] 2016-03-13 10:17
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 10:17
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by axon-qubes** [comment] 2016-03-13 13:55
Maybe it's just a problem with my key, but it keeps popping up a pinentry box (in the backend domain) to enter a passphrase for the key, even though the key has no passphrase. If I just hit enter, it fails to decrypt messages, claiming that no secret key is available.

**Comment by axon-qubes** [comment] 2016-03-13 16:23
I did some further testing, making sure to use a full key with no passphrase in the backend. The pinentry popup still occurs on encryption/decryption attempts, so I'm pretty certain it's not just a problem with my key. (Verifying signed emails works fine now, though.) I also don't think it's a general GPG bug, since the same thing still does not happen with non-TorBirdy Thunderbird.

**Comment by marmarek** [comment] 2016-03-13 21:32
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 21:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 21:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc22` has been pushed to the `r3.0` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 21:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.18-1.fc23` has been pushed to the `r3.0` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 21:33
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.18-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 21:34
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-13 21:35
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.18-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/6bae7f17704bf2eadc797a76e054410a47746d41...0899887f787b2f411c057ef22363f904c0cc4bbb

**Comment by marmarek** [comment] 2016-03-14 01:02
If the pinentry pops up in the backend domain, this is some different problem. This ticket is the one where the command doesn't even reach backend domain. Please open new one, and check enigmail logs for exact gpg command line.

**Closed by marmarek** 2016-03-14 01:02 UTC
Labels: C: other, r3.0-fc20-stable, r3.0-fc21-stable, r3.0-dom0-stable, r3.0-wheezy-stable, r3.0-jessie-stable, r3.1-dom0-stable, r3.1-fc21-stable, r3.1-fc22-stable, r3.1-fc23-stable, r3.0-fc22-stable, r3.0-fc23-stable, r3.1-jessie-stable, r3.1-wheezy-stable, r3.1-stretch-stable

**Comment by axon-qubes** [comment] 2016-03-14 07:05
Ah, I figured out the problem. `gpg2` keeps secret keys on a separate keyring from `gpg`. I had removed the passphrase using `gpg`, but since Split-GPG uses `gpg2`, I had to do it again.
