### ISSUE TITLE
Login screen: External USB mouse/keyboard not working

### ISSUE THREAD

**Issue by john-999** [QubesOS/qubes-issues#5833] opened 2020-05-20 06:47 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
External USB mouse/keyboard availability (at login screen)

**Brief summary**
Upon booting up, I cannot enter the login credentials because the external USB mouse/keyboard is not available (mouse pointer does not move, keystrokes are not registered). The notebook's integrated trackpad and keyboard do however still work.

**To Reproduce**
1. Push power button
2. Enter the password to unlock disk encryption (at this point, the external USB keyboard works)
3. At the Qubes user session login prompt, trying to move mouse pointer the via external USB mouse or moving the mouse pointer via the integrated trackpad (working) and then trying to type the user session password via the external USB keyboard fails.

**Expected behavior**
Entering the Qubes user session credentials via external USB mouse/keyboard should always work.

**Actual behavior**
Entering the Qubes user session credentials via external USB mouse/keyboard fails approximately 2 times out of 3.

**Solutions you've tried**
Rebooting 1-3 times has always resulted to success.
When the same issue had been happening in the past, it was temporarily solved by unplugging the USB receiver and plugging it in again, but this workaround does not work anymore, suggesting that the issue is now a different one (a guess: the qube "sys-usb" could not boot up correctly).

**Comment by xaki23** [comment] 2020-05-20 08:18
>  (a guess: the qube "sys-usb" could not boot up correctly).

check /var/log/xen/console/guest-sys-usb.log for any hints about why it is not starting (correctly).

for a more active approach, disable sys-usb autostart.
this way your usb stays connected to dom0 and you can log in, set up some debugging (like tailing the sys-usb console log), and then try to start sys-usb.

**Comment by john-999** [comment] 2020-05-20 08:41
> check /var/log/xen/console/guest-sys-usb.log for any hints about why it is not starting (correctly).

I know how to view that log, but I don't have the knowledge to understand it (I'm just a very high level end user).

> for a more active approach, disable sys-usb autostart.
> this way your usb stays connected to dom0 and you can log in, set up some debugging (like tailing the sys-usb console log), and then try to start sys-usb.

Same thing here - I don't have the knowledge to debug something like this.

**Comment by unman** [comment] 2020-05-20 13:01
You'd probably get better help at the mailing-list, to be honest.
The first thing I would do is to test the device(s) using a live distro - if you have access to anther machine, download a Live version of Fedora/Debian/anything, and then test the USB with that.

Once you have confirmed that the physical device(s) work, then you can turn to Qubes.
The fact that this worked in the past, and now works intermittently, is strange. Can you point to any changes you made? Any updates installed etc?
What is the hardware you are working with?
What boot method are you using?

As you'll see, at the moment this is a support problem, not a Qubes issue. In the course of debugging your problem we may identify a Qubes issue, or we may not. Honesty, better dealt with at the mailing list. Raise it over there.

**Comment by john-999** [comment] 2020-05-20 15:02
For the record:

> Once you have confirmed that the physical device(s) work
Everything works correctly.

> Can you point to any changes you made? Any updates installed etc?
I haven't made any changes to Qubes itself. The updates installed are simply the ones that come by default/automatically.

> What is the hardware you are working with?
Notebook: Dell Inspiron 17 5000 Series 5770
USB mouse/keyboard: Microsoft "Sculpt Ergonomic Desktop" (https://www.microsoft.com/accessories/en-us/products/keyboards/sculpt-ergonomic-desktop/l5v-00001)

> What boot method are you using?
Also just the default/standard method (but with disk encryption).

**Comment by andrewdavidwong** [comment] 2020-05-22 10:07
Unman is probably right you being more likely to receive help from the `qubes-users` [mailing list](https://www.qubes-os.org/support/). However, I'll leave this open for now in case it turns out to be a USB proxy bug.

**Comment by john-999** [comment] 2020-08-07 09:23
When the USB keyboard/mouse doesn't work (as described), I can still log in using the notebook's keyboard and trackpad.

I noticed that, after logging in like this, the "sys-usb" Qube had actually failed to start (so I have to start it manually and then, everything works normally).

I have no clue why it failed to start. But if somebody can tell me what info you need to find out, let me know.

**Comment by xaki23** [comment] 2023-04-07 13:25
> Has there been any progress on this since this has been reported almost 3 years ago? I searched the `qubes-users` mailing list archive but couldn't find a post that describes this issue.

not sure what "issue" is there?
if you install with usb kbd, you dont get a sys-usb, so usb kbd will work as usual.
could you be a bit more specific what your "huge issue" is?

**Comment by unman** [comment] 2023-04-07 13:26
I think you are right to say that this only happens in specific cases.

If Qubes detects USB devices on installation then the system *should* be
configured to allow for use of peripherals during LUKS entry before
sys-usb starts.
This covers most installations, which is why you see few complaints.

It would be helpful if you could detail the steps you took at
installation, and any specific details of your hardware.

**Comment by unman** [comment] 2023-04-08 10:37
Do you have a sys-usb qube?

**Comment by xaki23** [comment] 2023-04-08 10:51
if you rely on USB HID, set up a USB VM, have that VM set to autostart, and it fails to start ... then yes, you wont have working USB HID.

disable autostart to boot with working hid, then disable autostart on the usb vm, and debug why it isnt starting.

https://www.qubes-os.org/doc/autostart-troubleshooting/

**Comment by xaki23** [comment] 2023-04-08 11:36
once you have sys-usb autostart disabled (either by the skip_autostart option or on a per-vm basis), you should get a working boot. (which makes it so much easier to debug what the problem might be)

how to proceed from there to debug sys-usb not starting ... depends.
first i would check the logs for it in /var/log/xen/console/ ... 
if that is inconclusive, i would try to start sys-usb from the commandline (qvm-start sys-usb) to see if that generates any error message. 
also doublecheck the right pci device is assigned to the VM.

**Comment by SlinkyGopher** [comment] 2023-06-23 02:30
I just got this problem after changing my motherboard. The rest of the device stays the same. No USB device works after decrypting the LUKS partition.

In the top right bar, I can also see an unfamiliar "XF" icon. Help is much appreciated. Everything was working fine until I changed the motherboard.

**Closed** 2024-12-07 14:18 UTC
Labels: T: bug, P: default, hardware support, C: usb proxy, affects-4.1, eol-4.1
