### ISSUE TITLE
dom0 updates failing when whonix-ws-16-dvm used as updatevm

### ISSUE THREAD

**Issue by no-usernames-left** [QubesOS/qubes-issues#8667] opened 2023-10-29 12:43 UTC
### Qubes OS release

4.1.2

### Brief summary

When `whonix-ws-16-dvm` is used as updatevm, updates fail with mention of a missing script.

### Steps to reproduce

In `dom0`:
1. `sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=reinstall qubes-template-whonix-ws-16` to revert back to a version of the template which should be known-good (`qubes-template-whonix-ws-16-0:4.0.6-202302011525`). To avoid complicating things, do not update the template until you have finished reproducing the issue.
2. `qubes-prefs updatevm whonix-ws-16-dvm`
3. `sudo qubes-dom0-update`

### Expected behavior

works

### Actual behavior

An Xterm pops open:
```
sh: 1: /usr/lib/qubes/qubes-download-dom0-updates.sh: not found
Fetching updates failed with code 127; press Enter to exit
```

**Comment by andrewdavidwong** [comment] 2023-10-29 21:02
@marmarek wrote in https://github.com/QubesOS/qubes-issues/issues/8482#issuecomment-1784115823:
> I don't think Whonix Workstation is supposed to be used as updatevm, AFAIR Whonix Gateway (sys-whonix) should work in that role if you want to use Whonix.

That sounds right to me. This probably should not be expected to work in the first place. Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-10-29 21:02 UTC
Labels: T: bug, C: Whonix, P: default, needs diagnosis, C: updates, affects-4.1
