### ISSUE TITLE
Hardware manager GUI does not update appropriately

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4392] opened 2018-10-15 20:11 UTC
### Qubes OS version:

4.14

### Affected component(s): 

Hardware manager GUI

---

### Steps to reproduce the behavior:

Hard to tell: I'm unable to have new AppVMs and DVMs detected and old ones removed from the list of VMs that I can attache hardware to.

### Expected behavior:

When a new AppVM/DVM is started, it shows up as an option to attach hardware to in the GUI.

When an AppVM/DVM is closed, it no longer shows up as an option to attach hardware to in the GUI.

### Actual behavior:

When a new AppVM/DVM is started, it often does not show up as an option to attach hardware to in the GUI.

When an AppVM/DVM is closed, it may still show up as an option to attach hardware to in the GUI.

### General notes:

---

**Comment by marmarek** [comment] 2018-10-15 20:17
I think this is a duplicate of https://github.com/QubesOS/qubes-issues/issues/4060 (even if you don't get exact the same message). [The fix](https://github.com/QubesOS/updates-status/issues/741) is already in [current-testing repository](https://www.qubes-os.org/doc/testing/).

**Closed by marmarek** 2018-10-15 20:17 UTC
