### ISSUE TITLE
Request: storage alerts for dom0 and domUs

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#4404] opened 2018-10-18 15:05 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Storage subsystems.
System stability.

---

### Steps to reproduce the behavior:

Run out of storage on a volume or pool in dom0 or a domU.

### Expected behavior:

User would be alerted before this happens and can take action to avoid bad and sometimes irreversible  outcomes.

### Actual behavior:

User is surprised when entire system or a particular VM fails to work correctly and/or becomes corrupted and unusable.

### General notes:

It may be useful to alert the user of storage issues before the (generally bad) effects of running out of storage occur. Probably best with configurable thresholds, e.g.: "predefined % remaining" or perhaps "total remaining storage". Monitoring could be broken down into two or three categories, all reported via a new widget (or updates to an existing one):

1. Alerts for dom0 via widget: monitor dom0 volumes as well as any pools that Qubes utilizes for VM volume storage.

2. Alerts for domU via widget utilizing Qubes Linux/windows tools: reported via RPC by the VM. Probably most critical for Linux and non-fullscreen Windows.

3. Alerts for domU via widget **without** Qubes tools support: **optional** delayed-reporting scan after shutdown by temporarily attaching the VM's volumes to a newly-run dvm and performing a filesystem scan for mountable filesystems, then reported via RPC. Widget would be reporting on RPC data from dvm, but knows the original domU it was checking. **OK, this one is probably a pipe dream. Probably best to create a script to do suggestion number 3.**

---

**Comment by andrewdavidwong** [comment] 2018-10-19 01:32
Duplicate of #1872

**Comment by andrewdavidwong** [comment] 2018-10-19 01:32
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-10-19 01:32 UTC
