### ISSUE TITLE
slowness of "any" operation

### ISSUE THREAD

**Issue by nailgao** [QubesOS/qubes-issues#4128] opened 2018-07-23 01:42 UTC
### Qubes OS version:

4.0.

### Affected component(s): 

any application, any process run on desktop

---

### Steps to reproduce the behavior:

use your desktop for at least half an hour. 
have a number of VMs open, ideally as many as your hardware memory allows you to. 
have various applications running; maybe several browser windows, file managers, editors etc..  

### Expected behavior:

you move back and forth between applications, and smoothly proceed with whatever you are doing.

### Actual behavior:

after you are past the first 10-15 minutes of your desktop session, it begins to take "long" to run any operation (mostly starting/running applications).
and after yet another while, it  may take AGES to do so. 
depending on at which timepoint of your desktop session you do it, the application opens in anywhere from 5 minutes to 15 minutes (and longer!). and this when you have a total of around 10 windows (or less) open on desktop. 
so far this happens when you want to start an application from qubes menu on the panel, or else with firefox tabs, like in the issue #4120 that I posted. 
yet there have been moments when no click on any spot of the desktop was responsive for long minutes, too.

### General notes:

---

### Related issues:

INTERESTING PHENOMENON: 
have Qubes developers added any fixes for this problem in the most recent fedora -27 update? 
after I updated fedora template today, my last two sessions, particularly my last session,  unlike the previous ones severely affected by desktop freezes, have been considerably more pleasant in terms of speed and seamless procession between and within apps.

**Comment by andrewdavidwong** [comment] 2018-07-23 02:22
Possible duplicate of #3639.

**Comment by nailgao** [comment] 2018-07-23 11:19
just thought adding a detail may be relevant:
during the aforementioned long delays of operations, i.e. of launching applications, it doesn't help to click again and again on the respective application in the menu. though it sometimes gets started in the 5th or 10th click, this state makes it seem to me like it is unrelated to whether I click on it again or not.

**Comment by manasb** [comment] 2018-07-23 13:56
Not sure if this is related but since upgrading to R4.0, my `whonix-gw` and `whonix-ws` take an extremely long period of time before successfully launching any program - in this period of time disk is constantly accessed.

Launching `whonix-ws` and checking on `top` with the use of `sudo xl console whonix-ws` in `dom0` shows the `kswapd0` process consuming 100% CPU for a number of minutes before gradually reducing CPU usage to around 20% but not completely stopping. This `kswapd` problem was noticable on R3.2 but only sometimes and that too randomly - I did not have a reliable way of reproducing that behavior. Now, however, I am seeing this behavior everytime I start up my `whonix-ws` or `whonix-gw` TemplateVMs.

**Comment by t4777sd** [comment] 2018-07-24 00:40
This sounds dumb, but are you sure each VM has enough memory and no where in the system is swapping?

**Comment by manasb** [comment] 2018-07-24 08:52
Checking with `free` shows over 1 GB of "available" RAM, so a shortage of RAM doesn't seem to be the cause in my case.

**Comment by nailgao** [comment] 2018-07-26 11:02
@manasb, why do you NOT, if you are not sure -as you say- create a new issue for your problem?

don't you see that you break the communication flow of the issue that I created?

what attitude is this?

if it is too much work for you to fill in a new issue, maybe you should turn to other OSes that you will not have to do that!

**Comment by nailgao** [comment] 2018-07-26 11:04
@andrewdavidwong can you please -if technically possible- remove the latter posts that is not related to my issue?
if everyone posted under everyone else's issue, what kind of place would this platform become?

**Comment by nailgao** [comment] 2018-07-26 11:09
also in connection with the issue #4120, the problem persists.

anon-whonix turned instantly unclickable while there were 2 tabs open.
other open apps such as the file manager and disk utility were not affected.

with these "instant freeze" problems of the desktop and in particular the browsers, **qubes presents itself no more suitable for daily use**. can you please solve these ASAP?

**Comment by andrewdavidwong** [comment] 2018-07-27 00:58
@nailgao:
> why do you NOT, if you are not sure -as you say- create a new issue for your problem?
> 
> don't you see that you break the communication flow of the issue that I created?
> 
> what attitude is this?
> 
> if it is too much work for you to fill in a new issue, maybe you should turn to other OSes that you will not have to do that!

> can you please -if technically possible- remove the latter posts that is not related to my issue? or ask the respective dude to delete and publish his issue elsewhere?
> if everyone posted own issue under everyone else's issue, what kind of place would this platform become?

It doesn't look like @manasb was (intentionally or unintentionally) issue-jacking. Rather, it looks like @manasb commented here because he had reason to believe that he might be having the same problem, which is understandable, given how broad this issue is. This is appropriate conduct, so his comments will not be deleted. Please don't lash out at others like this. Doing so runs contrary to the spirit of our [Code of Conduct](https://www.qubes-os.org/code-of-conduct/).

**Comment by andrewdavidwong** [comment] 2018-08-11 00:37
@nailgao:
> see it from my side. I am waiting for a reply, feedback, solution to my posted issue. 

You seem to be under the mistaken impression that there's anyone here who owes you those things. [No one owes you a reply. No one here is responsible for solving your problems for you.](https://www.qubes-os.org/support/#discussion-list-guidelines)

> now it is buried way back in the communication. think of it this way; what if I have something to add more? someone else has been talking on my issue page on something completely different (from my issue, no matter how related it may be in some "broad" sense), and then I will tally my updates at the end of his talk? a hodgepodge of communication? do you really defend this??!

It's not "your" issue. You can't file an issue, then exclude other users from commenting on it. That's simply not how this works.

As I explained above, his comments were on-topic and appropriate for this issue.

> again, when I -and I only, not someone else- added related topics to my own issue which at least could be grouped under the name "Qubes Manager", you asked me to post them separately, and I did that.

That's because you reported multiple things that were clearly separate problems in a single issue. That's completely orthogonal to whether the reporters are multiple people or the same person; either way, separate problems should be filed as separate issues.

> this degrades the quality of my post, the way I can follow it and communicate with you on it.

No, it doesn't. Your reaction to it, on the other hand, certainly does.

> this is "very" unfair, not to speak of the fact that the issues posted by me, for which I spend time and I do that gladly, remain unsolved and unresponded. and right now I still have the same problem that I posted a month ago. on top of that I am dealing with this.

You should seriously reconsider the way you're approaching this whole thing. This is a free and open-source project. You're paying nothing for any of this, and nothing was promised to you. Your sense of entitlement is not only entirely unjustified but also proving to be quite unconducive to the achivement of your goals.

> a month ago I posted a number of issues, almost 10. why should I post any issue if you will allow this to happen on my issue page?

Please feel free to stop at any time.

> I repeat my request to move the issue elsewhere.

Request denied.

**Closed** 2023-08-05 09:17 UTC
Labels: T: bug, C: other, eol-4.0
