### ISSUE TITLE
qubes-repo-contrib: ERROR: could not verify one or more packages

### ISSUE THREAD

**Issue by juodumas** [QubesOS/qubes-issues#6139] opened 2020-10-21 23:15 UTC
**Qubes OS version**

Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**

qubes-repo-contrib on dom0 (`qubes-repo-contrib-4.0.7-1.fc25.noarch`)

**Brief summary**

Cannot install package from qubes contrib repository.

**To Reproduce**

```
$ sudo qubes-dom0-update qubes-repo-contrib
$ sudo qubes-dom0-update --enablerepo=qubes-contrib-dom0-r4.0-current-testing qvm-screenshot-tool
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
--> Running transaction check
---> Package qvm-screenshot-tool.x86_64 0:0.7-0.fc25 will be installed
--> Finished Dependency Resolution
qvm-screenshot-tool-0.7-0.fc25.x86_64.rpm                   |  18 kB  00:00     
ERROR: could not verify /var/lib/qubes/dom0-updates/packages/qvm-screenshot-tool-0.7-0.fc25.x86_64.rpm
ERROR: could not verify one or more packages
```

**Solutions you've tried**

Tried adding `--clean` to `qubes-dom0-update`.
Also checked the UpdateVM - I see that the RPM is downloaded and then immediately deleted. Note: the UpdateVM is running Debian 10.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/installing-contributed-packages/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/5842 sounds similar, but looks like his issue has been fixed with `sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora`. In my case the contrib key seems to be already imported: 
```
dom0 ~>>rpm -qi gpg-pubkey-d0941e87-5d8c9210
Name        : gpg-pubkey
Version     : d0941e87
Release     : 5d8c9210
Architecture: (none)
Install Date: Thu 22 Oct 2020 01:31:00 AM EEST
Group       : Public Keys
Size        : 0
License     : pubkey
Signature   : (none)
Source RPM  : (none)
Build Date  : Thu 26 Sep 2019 01:25:20 PM EEST
Build Host  : localhost
Relocations : (not relocatable)
Packager    : Qubes OS Contrib Release 4 Signing Key
Summary     : gpg(Qubes OS Contrib Release 4 Signing Key)
Description :
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: rpm-4.13.0.2 (NSS-3)

<...>
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by andrewdavidwong** [comment] 2020-10-22 00:12
Duplicate of #6124

**Comment by andrewdavidwong** [comment] 2020-10-22 00:12
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-10-22 00:12 UTC
Labels: P: default, T: bug
