### ISSUE TITLE
provide GUI mechanism (Qubes Manager, Settings, etc) for USB passthrough 

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2328] opened 2016-09-20 22:01 UTC
I couldn't find a ticket tracking this. The options available to the user in [attaching a single USB device to a qube (USB passthrough)](https://www.qubes-os.org/doc/usb/#tocAnchor-1-1-5)  should be available to the user through a GUI, with appropriate warning. This is especially important for webcam passthrough, which has previously been seen a blocker for user adoption.

**Comment by boring-stuff** [comment] 2017-02-20 09:19
Anything against me starting on this? 
I know it's a minor issue, but it might be one of the few tasks I might use to learn GUI programming (with Gtk) and Qubes at the same time. Code would be shared with/taken from #910 as well.

**Comment by andrewdavidwong** [comment] 2017-02-20 09:50
Thanks, @boring-stuff! I can see no problem with you starting on it. @marmarek?

**Comment by marmarek** [comment] 2017-02-20 12:07
This is somehow a duplicate of #2132 - where the same widget will be used to assign any type of device (block, usb etc). See here:
https://github.com/QubesOS/qubes-issues/issues/2132#issuecomment-255106656
@kalkin what is the current status of it?

**Comment by mfc** [comment] 2017-04-06 00:52
this is not a duplicate of #2132. just as the Qubes VM Manager has `Attach/Detach audio-input to the VM`, this would create an `Attach/Detach webcam to the VM` entry. this is continually listed as one of the remaining [usability / adoption challenges](https://micahflee.com/2014/04/dual-booting-qubes-and-ubuntu-with-encrypted-disks/) for Qubes. 

I don't think waiting for Release 4.0 and the new Decomposed Qubes Manager is realistic for this, I think this should be added to Release 3.2 update milestone.

**Comment by mfc** [comment] 2017-04-20 20:17
hey @boring-stuff you still have some time for this? it is actually quite an important issue for new users and would help a lot with user retention of less technical users. R3.2 is going to be around for a while (supported for a year after R4.0 is released) and it would be really good to have this be part of it.

**Comment by jpouellet** [comment] 2019-06-22 05:32
@andrewdavidwong I believe this can be closed since the generic devices widget does now exist, no?

**Comment by andrewdavidwong** [comment] 2019-06-22 09:42
> @andrewdavidwong I believe this can be closed since the generic devices widget does now exist, no?

Yes, it appears so. Thanks!

**Closed by andrewdavidwong** 2019-06-22 09:42 UTC
Labels: C: manager/widget, P: major, T: enhancement, help wanted, ux
