### ISSUE TITLE
Fedora 29 based disposable VMs force close when launched with certain applications

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5016] opened 2019-05-02 21:22 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Fedora 29 based DisposableVMs

**Brief summary**
When trying to start a disposable VM from a Fedora 29 based Qube marked as Disposable VM,
the VM will automatically close if started with certain applications. For example trying to start a Fedora 29 based Disposable VM with Terminal will start the VM, show the terminal for a brief second and then close it.

**To Reproduce**
1. Create a template based qube based on Fedora 29
2. Mark the create qube as a disposable vm
3. From the Start Menu(XFCE Launcher applet), try to create a new instance of the Disposable VM by selecting Terminal

**Expected behavior**
You should have a running Disposable VM with a Terminal window.

**Actual behavior**
The Disposable VM is started, the Terminal window is shown for a brief period and then it's automatically closed and the VM is also closed and destroyed.

**Additional context**
This bug also occurs with Text editor. However it does not occur with Calculator.
Also I could not reproduce this problem with Whonix.

**Comment by andrewdavidwong** [comment] 2019-05-03 00:23
Possible duplicate of #3878, #2581, or one of many similar issues about this.

**Comment by marmarek** [comment] 2023-05-07 01:34
> Possible duplicate of #3878, #2581, or one of many similar issues about this.

Yes, it does look like a duplicate, and the GNOME Terminal case is already fixed.

**Closed by marmarek** 2023-05-07 01:34 UTC
Labels: T: bug, C: Fedora, P: default

**Comment by andrewdavidwong** [comment] 2023-05-07 22:42
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
