### ISSUE TITLE
Qubes should warn user if there is not enough disk space to restore an archive properly.

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6277] opened 2020-12-11 22:55 UTC
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**
Restored qubes

**Brief summary**
When an archive is a large percentage (ex 95%) of disk capacity, restore is not reliable.

This is a special case of https://github.com/QubesOS/qubes-issues/issues/6236

**How Reproducible**

Unknown

**To Reproduce**

1. Backup qubes into compressed archive
2. Restore qubes on a system where disk capacity is slightly larger (within 5%) of archive
3. See successful restore (!)
4. Later, be surprised when opening a qube to receive this error:

`qrexec-daemon startup failed: Connection to the VM failed`

Note that other errors may be possible from this bug, I guess?

**Expected behavior**

The restore program should warn the user that there is not enough disk space, and definitely should not say that the restore was successful.

**Actual behavior**

The restore is said to be successful, which could make someone delete the original and/or the archive before using all qubes in the restored system.

**Additional context**

This is a special case of https://github.com/QubesOS/qubes-issues/issues/6236

**Solutions you've tried**

Tested in https://github.com/QubesOS/qubes-issues/issues/6236

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/6236

**Comment by andrewdavidwong** [comment] 2020-12-12 13:31
Duplicate of #4791

**Comment by andrewdavidwong** [comment] 2020-12-12 13:31
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-12-12 13:31 UTC
Labels: P: default, T: bug
