### ISSUE TITLE
PV mode VMs fail to start: `sigchld_parent_handler: Connection to the VM failed`

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#8337] opened 2023-07-08 09:55 UTC
### Qubes OS release

4.1

### Brief summary

Starting _some_ AppVMs that so far worked now fail to start.

### Steps to reproduce

The last thing I did was update dom0 2 days ago:

NOTE that in the below list I already downgraded the three qrexec packages. They were initially upgraded to version 4.1.22. But downgrading didn't help.

```
[user@dom0 ~]$ rpm -qa --last | head
qubes-core-qrexec-libs-4.1.18-1.fc32.x86_64   Sat 08 Jul 2023 11:28:38 AM CEST
qubes-core-qrexec-dom0-4.1.18-1.fc32.x86_64   Sat 08 Jul 2023 11:27:41 AM CEST
qubes-core-qrexec-4.1.18-1.fc32.x86_64        Sat 08 Jul 2023 11:27:41 AM CEST
qubes-mgmt-salt-dom0-update-4.1.11-1.fc32.noarch Thu 06 Jul 2023 05:59:04 PM CEST
qubes-core-admin-client-4.1.31-1.fc32.noarch  Thu 06 Jul 2023 05:59:04 PM CEST
kernel-6.1.35-1.qubes.fc32.x86_64             Thu 06 Jul 2023 05:59:04 PM CEST
kernel-qubes-vm-6.1.35-1.qubes.fc32.x86_64    Thu 06 Jul 2023 05:58:47 PM CEST
kernel-devel-6.1.35-1.qubes.fc32.x86_64       Thu 06 Jul 2023 05:58:47 PM CEST
python3-qubesadmin-4.1.31-1.fc32.noarch       Thu 06 Jul 2023 05:58:43 PM CEST
qubes-core-dom0-4.1.31-1.fc32.noarch          Thu 06 Jul 2023 05:58:42 PM CEST
```
My only explanation is that updates introduced the behavior, because prior to July 6th everything worked fine.

### Expected behavior

I expect the AppVMs to start properly.

### Actual behavior

Error popup nearly immediately after starting an AppVM:

`Qube <qubename> has failed to start: qrexec-daemon startup failed: <date> qrexec-daemon[14252]: qrexec-daemon.c:307:init: Waiting for VM's qrexec-daemon.c:-135:sigchld_parent_handler: Connection to the VM failed`

This happens for some AppVMs, not for all.

Googling for sigchld_parent_handler does only return 3 results, one being #7624. I looked at the failing AppVMs and their mode was set to **PV**.

Switching the mode to **PVH** did resolve the issue!

The AppVMs that were not affected were already set to PVH mode. But those failing AppVMs in PV mode were in this mode for ages. So something (in my view) clearly changed with the latest updates.

**Comment by marmarek** [comment] 2023-07-08 12:20
First of all, PV mode should be avoided for security reasons (see the warning in the settings). That said, it should also still be functional.

Can you check console log of an AppVM that failed to start? You can find it in /var/log/xen/console/guest-VMNAME.log (with actual name instead of VMNAME). You can access it also via right-click menu in Qube Manager, where you have an option to copy it to the clipboard.

**Comment by heinrich-ulbricht** [comment] 2023-07-08 15:32
@marmarek Thanks for the heads-up.

The log has nothing, besides the message that I opened the log.

Two failed startups in PV mode and two times opened the log gives:

```
[2023-07-08 17:24:51] Logfile Opened
[2023-07-08 17:27:25] Logfile Opened
```

The AppVM reliably fails in PV mode and reliably starts in PVH mode.

**Comment by DemiMarie** [comment] 2023-07-08 17:30
Duplicate of #7935.

**Closed by DemiMarie** 2023-07-08 17:30 UTC
Labels: T: bug, C: core, P: default, needs diagnosis

**Comment by heinrich-ulbricht** [comment] 2023-07-08 19:09
I see. So the kernel update probably triggered this. Thanks for the update.

**Comment by andrewdavidwong** [comment] 2023-07-08 22:59
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
