### ISSUE TITLE
Clock sync qube fails to initialize properly "Qube sys-clock has failed to start: Cannot connect to qrexec agent for 60 seconds"

### ISSUE THREAD

**Issue by kord1e** [QubesOS/qubes-issues#7806] opened 2022-10-03 19:46 UTC
### Qubes OS release
4.1.1

### Brief summary
Clock sync qube randomly fails to initialize properly.

### Steps to reproduce
Set up a separate disposable VM for clock syncing, and configure it as the clock cube in the qubes global settings

### Expected behavior
The clock qube should start and work normally

### Actual behavior
The clock qube used to work well.
After installing dom0 updates a few weeks ago (first time since Mar 2022 maybe), the clock qube quite often throws an error like this, then shuts down, restarts and may throw the error again:

"Qube sys-clock has failed to start: Cannot connect to qrexec agent for 60 seconds. See /var/log/xen/console/guest-sys-clock.log for details"

The log file is quite long. I can try to provide more information if needed, but  I'm not sure what to look for.

**Comment by kord1e** [comment] 2023-02-09 16:41
Looks like this may have been a configuration issue...?

I increased the amount of memory given to the clock qube, and now it seems to start correctly. Now it is 256 MB (768 MB max), I don't remember what it was but maybe 128 MB (256 max).  So was this caused by not enough memory?

**Comment by andrewdavidwong** [comment] 2023-02-10 05:22
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-02-10 05:22 UTC
Labels: T: bug, C: other, P: default, diagnosed
