### ISSUE TITLE
fedora-27 drop-down menu displays unreal list of "selected apps"

### ISSUE THREAD

**Issue by nailgao** [QubesOS/qubes-issues#4123] opened 2018-07-22 11:09 UTC
### Qubes OS version:

4.0.

### Affected component(s): 

fedora-27 VM

---

### Steps to reproduce the behavior:

replace fedora-26 with fedora-27 following the procedure outlined in the respective Qubes doc.
go to Qubes on panel and hover over to fedora-27. 
View apps list of this VM.

### Expected behavior:

you only see displayed whatever apps you've selected from among the installed fedora-27 apps in Qubes Manager. 
And, as it is familiar from 3.2., if you haven't selected any yet, only "Files" or maybe "Terminal" should have been already appearing in the list by default.

### Actual behavior:

"All" installed apps of fedora-27 VM are displayed, when in reality no app is yet "selected" via "Applications" tab of Qubes Manager, whereas under this tab, the selected apps list is empty!

### General notes:

---

**Comment by esote** [comment] 2018-07-22 19:29
It's not difficult to fix this. I believe it also happens when you clone a VM (but haven't verified).

To fix it, from the Applications chooser, select any application and "Ok". You should see that it now only shows that application, instead of them all.

**Comment by nailgao** [comment] 2018-07-22 19:44
@esote  thank you for your hint, that fixed the list. 
of course, the fix should only have circumvented any possible underlying reason for the strange behaviour.

**Comment by andrewdavidwong** [comment] 2018-07-22 20:45
Duplicate of #3929

**Comment by andrewdavidwong** [comment] 2018-07-22 20:45
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-07-22 20:45 UTC
