### ISSUE TITLE
keystrokes "lost" from browser

### ISSUE THREAD

**Issue by tumbletree** [QubesOS/qubes-issues#5918] opened 2020-06-30 01:35 UTC
**Qubes OS version**
4

**Affected component(s) or functionality**
Windows focus (again)

**Brief summary**
Top window registered mouse movements, but not keyboard input. Switched window, tried again, all good again.

**To Reproduce**
Return to firefox after overnight suspend, select text field and try to type.

**Expected behavior**
accept text input

**Actual behavior**
nothing. Mouse move, text could be highlighted and addressbar selected, but nothing typed. I could not **find** another window/application that was accepting my text, but I really don't know. (n.b. I was looking only in the current workspace). Effect lasted ~60s, at a guess. 

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
I have an output of dmesg, if required.

This is the third or forth time I've encountered an attention-stealing issue. This is the second report (below), for different and more concerning behavior: "what has happened to my keystrokes"? (Nothing of any importance in this case). 

I will note also that 
	a) this has only happened after fedora-31 template upgrade
	b) a freeze, again, when opening up gedit to write this report.

This seems very reminiscent of issues reported earlier (duplicates on #5912), but they were from 2015 and 2017. Since this is keystroke data, and seems only triggered since fedora-31, surely this warrants a fix?

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5912

**Comment by andrewdavidwong** [comment] 2020-06-30 12:03
Possible duplicate of #3267 (as you acknowledge).

> Return to firefox after overnight suspend, select text field and try to type.

Does it only affect Firefox? I noticed your other issue (#5912) also only mentioned Firefox.

> a freeze, again, when opening up gedit to write this report.

Freezing sounds like a separate problem that should be reported in a separate issue.

**Comment by tumbletree** [comment] 2020-07-01 04:39
FIrefox is the principle app I use lately. Just haven't had the chance to notice it on anything else.

If the freeze happens again today, I'll submit a separate report.

**Closed** 2023-08-05 09:27 UTC
Labels: T: bug, C: gui-virtualization, P: default, needs diagnosis, eol-4.0
