### ISSUE TITLE
Qubes-builder ./setup fails - ANSIColor - curses.tparm argument 1 must be a string, not None

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#4484] opened 2018-11-07 03:26 UTC
### Qubes OS version:

R4, R3.2

### Affected component(s): 

qubes-builder

---

### Steps to reproduce the behavior:

vm depending on fedora-26 or fedora-29, in which dependencies have been installed following https://www.qubes-os.org/doc/qubes-r3-building/

launching ./setup results in:
```
Traceback (most recent call last):
  File "./setup", line 1919, in <module>
    install_deps()
  File "./setup", line 144, in install_deps
    ansi = ANSIColor()
  File "/home/user/qubes-builder/libs/ansi.py", line 17, in __init__
    self['black']     = curses.tparm(curses.tigetstr('setaf'), 0)
TypeError: tparm() argument 1 must be string, not None
```

### General notes:

---

**Comment by unman** [comment] 2018-11-07 23:53
@tlaurion I've taken clean ITL templates, installed the dependencies from that page, and cant reproduce this error, in either fedora-26 or fedora-28, using both xterm and gnome-terminal. (I haven't tested in fedora-29.)
Had you made any other changes to the template prior to running setup? What sort of terminal are you running?

**Comment by tlaurion** [comment] 2018-11-08 03:34
`sudo xl console virtualmachine` from dom0

**Comment by unman** [comment] 2018-11-08 10:58
@tlaurion Good grief.
I assume you are using a login shell to user.
`export TERM=xterm-256color`  will get you sorted.

**Comment by unman** [comment] 2018-11-15 11:47
@andrewdavidwong This is such a non standard route to building, that I would expect anyone using it to be able to trouble shoot it for themselves.
We can't add documentation to cover every possible approach that users may take, particularly one that isn't documented. If you really want this added to the docs I will, but where will that end?

**Comment by andrewdavidwong** [comment] 2018-11-16 02:37
> This is such a non standard route to building, that I would expect anyone using it to be able to trouble shoot it for themselves.
> We can't add documentation to cover every possible approach that users may take, particularly one that isn't documented. If you really want this added to the docs I will, but where will that end?

Didn't realize it was that non-standard. In that case, closing.

**Closed by andrewdavidwong** 2018-11-16 02:37 UTC
Labels: C: builder, C: doc, help wanted, task
