### ISSUE TITLE
sys-usb and sys-net hang on R4.0rc4 after closing the lid

### ISSUE THREAD

**Issue by stuart12** [QubesOS/qubes-issues#3645] opened 2018-03-01 18:26 UTC
#### Qubes OS version:

4.0 (R4.0) (rc4)

#### Affected component(s): 

sys-usb (and often sys-net)

---

### Steps to reproduce the behavior:

Close the lid with a USB mouse active.

### Expected behavior:
My USB mouse works after opening the lid.

### Actual behavior:

The sys-usb qube no longer responds and my USB mouse up longer works. When I try to open a Terminal in the sys-usb qube nothing happens and unplugging and replugging my mouse does not get it working again.

`qvm-shutdown sys-usb ` does not kill the qube. When I look at the list of qubes in the GUI there is a spinning wheel next to sys-usb. `qvm-kill sys-usb` followed by `qvm-start sys-usb` gets my USB mouse working again.

### General notes:

I have also seen sys-net hang the same way.  I needed to kill it (after killing all the network qubes) to get my network working again.

I have a Dell Latitude 7480. Qubes 3.2 did not install (I found myself at the text installer which had problems with LVM).

---

#### Related issues:

Please document how to copy text from Dom0 with R4.

**Comment by marmarek** [comment] 2018-03-01 18:37
Does the same happens if you suspend the system from the menu?
What kernel version do you have in sys-net and sys-usb? There was similar issue with 4.14.13-2 and older.

**Comment by stuart12** [comment] 2018-03-01 18:51
```[user@sys-usb ~]$ uname -r
4.14.13-2.pvops.qubes.x86_64```

```[user@sys-net ~]$ uname -r
4.14.13-2.pvops.qubes.x86_64```

**Comment by stuart12** [comment] 2018-03-01 19:03
This time, using the `Suspend` command from the menu hung `sys-net` but didn't hang `sys-usb`.  I had to kill and restart `sys-net` and then restart all the Qubes using `sys-net` to get everything working again.
```
[user@sys-usb ~]$ uname -r
4.14.13-2.pvops.qubes.x86_64
```
```
[user@sys-net ~]$ uname -r
4.14.13-2.pvops.qubes.x86_64
```

**Comment by marmarek** [comment] 2018-03-01 19:12
> 4.14.13-2.pvops.qubes.x86_64

Ok, this is definitely the problem. Install updates in dom0, you should get kernel-qubes-vm 4.14.13-3 or newer.

**Comment by stuart12** [comment] 2018-03-02 13:17
I have upgraded. I'll update the ticket with info on whether I see any more hangs.  ```
[user@sys-net ~]$ uname -r
4.14.13-3.pvops.qubes.x86_64
```
```
[user@sys-net ~]$ uname -r
4.14.13-3.pvops.qubes.x86_64
```

**Comment by lunarthegrey** [comment] 2018-03-02 21:15
Curious to check this one, will have to try when I get home.

**Comment by stuart12** [comment] 2018-03-07 15:51
I haven't seen any more total network hangs but I have lost the touchpad.

**Comment by unman** [comment] 2018-03-08 17:55
R4.0rc5 -I dont see this problem.
sys-net picks up again (if you're foolish enough to leave it active), sys-usb is fine, and touchpad works well.
Works for me.

**Comment by andrewdavidwong** [comment] 2018-03-09 02:16
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-03-09 02:16 UTC
Labels: C: kernel, bug
