### ISSUE TITLE
usb widget design and performance

### ISSUE THREAD

**Issue by nailgao** [QubesOS/qubes-issues#4129] opened 2018-07-23 02:08 UTC
### Qubes OS version:

4.0.

### Affected component(s): 

usb widget on the desktop panel
usb devices connected to VMs

---

### Steps to reproduce the behavior:

insert a usb device.
connect it to a VM via usb widget.
remove the device via latter.

### Expected behavior:

connection/disconnection of the device is clearly displayed, easy to handle, without freezes.

### Actual behavior:

as I added to the issue #4116, the temporary freezes prevalent in other parts of the desktop occur here, too, during the connection and removal of usb devices to/from VMs. 

### General notes:

the usb problem #4127 that was in Qubes Manager of 3.2. persists, though to a less severe extent in my case.
yet Qubes Manager in 3.2. never froze during the referred operations of device connection and removal.

---

### Related issues:

the GUI:

if the connected device contains a number of partitions, you need to scroll down the list. And even if not, you still need to do that because the block device is shown at the bottom of the list which in turn is shown at the bottom of the screen, hence it is not so correct to say "shown" because it goes often -almost always- off-screen. And the list is comprised of densely packed rows written in thin fonts on a grey background with minimal window margins.
I don't see why this miniscule "usb widget" has come about to replace the beautiful, nicely outlined, most useful Qubes Manager, which was by no means "unnecessary" or "bulky" or whatever.
(here I am referring to what I've heard about the initial plans to skip Qubes Manager altogether) 

Qubes Manager's usb operations are moved to a miniature, badly done (from a GUI point of view) window with the same drop-down function. Just...why? I am not in command of, if any, security-related aspects of this change, but else where is the change for the better here?

**Comment by andrewdavidwong** [comment] 2018-07-23 02:32
This issue is too convoluted and tries to cover too many disparate topics (both bug reports and feature requests). Each issue must be about **a single, actionable thing** that is distinct from (i.e., neither a duplicate of subsumed by) another extant issue.

**Closed by andrewdavidwong** 2018-07-23 02:32 UTC

**Comment by andrewdavidwong** [comment] 2018-07-23 03:09
For more information, please see the following guidelines (just updated):

https://www.qubes-os.org/doc/reporting-bugs/#qubes-issues-guidelines
