### ISSUE TITLE
"Tags" for VMs

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6555] opened 2021-04-23 11:31 UTC
**The problem you're addressing (if any)**
dom0 shell scripts should be able to differentiate between different kinds of VMs (e.g. secret ones vs not secret ones, etc.)

**Describe the solution you'd like**
Add to Qube Manager the ability to add/edit/delete "tags" for VMs: strings or string pairs to supply extra information about a VM.

Example: `dangerous`=`1`.

There should be an easy way to enumerate all VMs having (or not having) a certain tag (or tag combination).

**Where is the value to a user, and who might that user be?**
I want to use it for solving #6552 for me (please reopen that issue by the way!)

Any advanced sysadmin may benefit.

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by unman** [comment] 2021-04-23 13:20
Tags are already available, using `qvm-tags`.
Instead of spamming GitHub do some research.

If you wanted to have the `tag` character exposed in Qube Manager, you
would have seen that there is **already** existing work in hand on
revising the Manager, and your comment could have been added there.

**Comment by vporton** [comment] 2021-04-23 13:23
> Tags are already available, using `qvm-tags`. Instead of spamming GitHub do some research. If you wanted to have the `tag` character exposed in Qube Manager, you would have seen that there is **already** existing work in hand on revising the Manager, and your comment could have been added there.

I was clear that I do want it in Qube Manager. How to add my comment there? I thought this repo is the right place for such feature requests. Why isn't it?

**Comment by fepitre** [comment] 2021-04-23 15:43
> I was clear that I do want it in Qube Manager.

Please do it.

**Comment by andrewdavidwong** [comment] 2021-04-23 19:15
Duplicate of #2949

**Comment by andrewdavidwong** [comment] 2021-04-23 19:16
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2021-04-23 19:16 UTC
Labels: P: default, R: duplicate, T: enhancement
