### ISSUE TITLE
Significant performance reduction after R3.2 -> R4.0 upgrade

### ISSUE THREAD

**Issue by kravietz** [QubesOS/qubes-issues#3803] opened 2018-04-08 20:12 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

All applications, most notably Chrome, Firefox

---

### Steps to reproduce the behavior:

After R3.2 -> R4.0 upgrade the performance of all GUI apps was significantly reduced. This is most visible with Chrome and Firefox, but applies to any GUI application.

### Expected behavior:

In R3.2 applications were responding immediately with no visible delay. I installed R4.0 over fully upgraded R3.2 just a few days ago. Unfortunately I'm unable to provide benchmarks for R3.2 as it's my primary working computer and downgrade is not feasible.

### Actual behavior:

Responsiveness of the applications dropped dramatically to a point where you actually wait for a fraction of second for application to respond to a mouse click etc. Video playback is practically impossible, they are being displayed frame-by-frame, like a slow GIF animation.

### General notes:

Kernel messages attached

[dmesg.txt](https://github.com/QubesOS/qubes-issues/files/1887848/dmesg.txt)

---

**Comment by andrewdavidwong** [comment] 2018-04-08 20:47
Duplicate of #3639

**Comment by andrewdavidwong** [comment] 2018-04-08 20:48
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-04-08 20:48 UTC
