### ISSUE TITLE
wrong resolution during boot

### ISSUE THREAD

**Issue by cryptix** [QubesOS/qubes-issues#2284] opened 2016-08-31 17:26 UTC
#### Qubes OS version

R3.1 and R3.2-rc3

---
### Expected behavior:

Readable boot messages.
### Actual behavior:

The text is readable in the bootloader menu and for a second when the `XEN EFI LOADER...` does its thing.. than it switches to this:
![share](https://cloud.githubusercontent.com/assets/111202/18139130/5c21311c-6fb0-11e6-8127-10189b9410e2.jpg)
### Steps to reproduce the behavior:

Use a Lenovo [x220](http://www.thinkwiki.org/wiki/Category:X220) and try to boot one of the .iso's. I tried the verbose mode and various kernel flags like `nomodeset`, `vga=ask` and other fixed values for resolutions that should work but none of them seem to take effect.

(_edit:_ system info link to thinkwiki.org)

**Comment by cryptix** [comment] 2016-09-12 11:29
I will test if this also happens through the external monitor connection later this week.

Any other ideas?

**Comment by alorgill** [comment] 2016-10-29 22:45
Issue persists on my X220 Qubes version 3.2

**Comment by cryptix** [comment] 2017-01-07 13:35
#1771 makes me think that some people are able to use qubes on their x2**?

I wasn't able to get into the installer yet. Also tried on a friends x220, same problem. We also tried attaching an external monitor over VGA. Same problem.

**Comment by cryptix** [comment] 2017-01-08 20:56
I just tried 3.2 and now it works for me...

**Comment by andrewdavidwong** [comment] 2017-01-09 04:25
Thanks, @cryptix. Is it still occurring for you, @alorgill?

**Comment by DrWhax** [comment] 2017-01-13 16:28
I had this same issue on an x201, which was related to VT-d, which wasn't playing nicely with the installer. Disabling VT-d for the installer and after installation re-enabling VT-d worked fine for me.

**Comment by jaja654** [comment] 2017-03-10 21:30
I also had the same issue on a ThinkPad T410 with Qubes 3.2, and good news, there is a solution!

After hours of duckduckgo-ing I found out that indeed, if I turn off VT-d in the BIOS, I can see the installer. But having that security feature is a must, so don't do that, instead simply add `iommu=no-igfx` to the end of your XEN boot command line in GRUB. Again, not the linux kernel command line, but the XEN command line. This turns off iommu only for the graphic card, but that's not a  big deal, it is connected to the trusted dom0 anyway. (Or that's what I read.)

So in the GRUB menu press `e` or `<tab>` while the counter goes down, you are now in edit mode. Go down to the XEN command line, `module  /xen-something.gz  blabla console=none blabla` and add `iommu=no-igfx` to the end (separated by a `<space>`). It should be a couple lines above the kernel line `(module /vmlinuz blabla)`. Press `<control>-x` to boot.

After install you have to add this to GRUB permanently. From dom0 terminal:
run `sudo nano /etc/default/grub`
add `iommu=no-igfx` into the GRUB_CMDLINE_XEN_DEFAULT="..." statement (between the " marks).
run `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`
Reboot to check.

Perhaps this info could be added to some official Qubes install documentation, seems to be a common problem with the intel graphics solution of the era. (Still very usable machines with VT-x, VT-d, TPM, TXT, ...)

**Comment by jaja654** [comment] 2017-03-10 21:32
Also for future reference my VGA from lspci:
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
 and it is an "Intel Corporation 5 Series/3400 Series Chipset".

**Comment by andrewdavidwong** [comment] 2017-03-11 01:27
> Perhaps this info could be added to some official Qubes install documentation

Please feel free to submit a PR.

**Comment by jaja654** [comment] 2017-03-11 18:59
Will do, once I figure out how to get it working with anti evil maid.
Booting with tboot I get a different kind of graphic glitch, vertical lines. Pressing esc to go to text console works however, so I see the secret unsealing works. Too bad it messes up graphics.

**Comment by defendio** [comment] 2018-08-28 19:28
I am experiencing exactly same issue with 4.0 and ThinkPad X220.

**Comment by andrewdavidwong** [comment] 2020-09-02 16:37
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by andrewdavidwong** [comment] 2020-09-02 16:38
Moving to 4.0 milestone based on most recent report.

**Comment by andrewdavidwong** [comment] 2020-09-02 16:38
@ofendio, are you still affected by this?

**Comment by ofendio** [comment] 2020-09-03 07:41
Hi, it's not current anymore.

**Comment by andrewdavidwong** [comment] 2020-09-03 23:54
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-09-03 23:54 UTC
Labels: C: other, P: default, T: bug, hardware support, needs-diagnosis
