### ISSUE TITLE
qvm-usb return invalid speed when sys-usb lacks qubes-usb-proxy

### ISSUE THREAD

**Issue by pietrushnic** [QubesOS/qubes-issues#3335] opened 2017-11-24 22:32 UTC
#### Qubes OS version:
R4.0-rc2

#### Affected TemplateVMs: 
dom0, sys-usb

---

### Steps to reproduce the behavior:

Make sure that `qubes-usb-proxy` is not installed in `sys-usb` and run below command in `dom0`

```
qvm-usb a <appvm> <usb-device>
```

### Expected behavior:

Information about missing `qubes-usb-proxy` package or other message with true reason of failure.

### Actual behavior:

Confusing message:

```
Device attach failed: invalid speed received
```

### General notes:

I believe that salt states shall verify if required package is installed on `sys-usb`.

I thought that there is something wrong with support for my device and I was prepared to debug that by my own, but there is no documentation how to approach that. Digging Python scripts with so many levels of abstraction was also not pleasure. `--verbose` option didn't helped in that way. I believe there should be some note in documentation how to approach debugging of USB related problems. Or maybe I missing something and there is some debugging documentation out there ?

---

**Comment by andrewdavidwong** [comment] 2017-11-25 01:11
This appears to be a duplicate of #3026. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-11-25 01:11 UTC
