### ISSUE TITLE
Qubes Manager blocks the UI while it is starting or stopping a VM

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4283] opened 2018-09-07 02:35 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes manager

---

### Steps to reproduce the behavior:

Start or stop a VM from Qubes Manager

### Expected behavior:

qubes-manager remains responsive while the VM is starting

### Actual behavior:

qubes-manager becomes unresponsive while the VM is starting

### General notes:

---

**Comment by marmarta** [comment] 2018-09-10 15:43
Are you sure this is also the case with the current testing repositories? Because I'm having trouble reproducing this bug (the manager is responsive while start/shutdown are happening, although it's true that there's a hiccup of about a second when start is pressed (which is a bug, definitely)).

**Comment by esote** [comment] 2018-09-11 16:30
Also \related: the Qubes domain widget freezes when shutting down VMs from the widget itself. I haven't tested in current-testing.

**Comment by donob4n** [comment] 2018-10-16 20:51
Hi,

I am working on a rewrite for fixing this and other things. Basically switching "threading.Threads" to "QThreads" and using emit(SIGNAL) for notify errors. So we can remove the ThreadMonitor stuff and the 'lag cause':

```
while not t_monitor.is_finished():
            self.qt_app.processEvents()
            time.sleep(0.2)
```

Please let me know if this could cause some conflict or problem.

**Comment by donob4n** [comment] 2018-10-17 12:07
Well, although my idea about switching to QThreads and using signals/slots could help, I discovered that is not the root of the problem.

The problem is that some Qubes API methods are blocked when some VM is starting or stopping. e.g. I tested vm.is_running(), on normal state it only takes  like 2ms for return, but if you start or stop a VM (with or without the manager), it can delay 3, 4 or even more seconds.

So the solution is to avoid calling this kind of functions from the main GUI thread.

With the QtThreads I am thinking on two options:
1) Create a new thread for any new huge task, like current way but without waiting them to finish. It will emit a 'show_error' signal (maybe other name?) in case of error. 
2) Create a single WorkerThread with slots connected to signals for huge tasks. The main thread just emits a signal when needed and lets the worker to process it. 

What do you think @marmarek @marmarta ?

**Comment by marmarek** [comment] 2018-10-17 12:28
The blocking during start/stop applies to any VM property/method access, not only is_running(). The more appropriate thing would be fix that instead of working around it everywhere. This is caused by how LVM is handled - right now those operations are synchronous. The storage API provide elegant method to make them non-blocking, but LVM implementation doesn't use it right now... @rustybird already [implemented this for btrfs](https://github.com/QubesOS/qubes-core-admin/pull/231), I need to do the same for LVM.

But there are still methods that will take time by design, for example start(). Those are already handled in separate thread, but switching to QThread may make the code cleaner. I think the first option is better for this purpose.

**Comment by donob4n** [comment] 2018-10-17 13:56
Yes, improving API seems the best option.

@marmarek 
> switching to QThread may make the code cleaner. I think the first option is better for this purpose.

There are some problems with the option 1. It needs to have a reference to all running QThread objects or the garbage collector calls  __del__(), which calls self.wait() and blocks the main thread until the thread finishes.

Since the user could click 'start' two (or more) times in a row, we can't just have a member like self.startThread (the second click will cause the deletion of the older instance and a blocking call to wait()), so it needs an array or list which also needs to be periodically reviewed for freeing finished threads.

I think the option 2 will provide same user experience with a simpler and easier to maintain code. Only a class with some methods connected to some signals.

**Comment by marmarek** [comment] 2018-10-17 14:11
But then you can't start two qubes simultaneously, no? What about list of threads in option 1? And to waste of memory, there could be a function that remove already finished threads (I assume it's easy to check if thread finished) before starting new one.

**Comment by donob4n** [comment] 2018-10-17 14:30
> But then you can't start two qubes simultaneously, no?

You could click start on all VM's you want but the emitted signals will be queued and processed sequentially.

For tasks like start/stop (which really takes few seconds in qubes manager) I think it should be nice because the GUI will run smooth and I don't think there is too much difference between starting all vm's at same time or adding a few seconds delay between them.

For other huge tasks like cloning, deleting or adding domains, maybe is not a good option.

>  What about list of threads in option 1? And to waste of memory, there could be a function that remove already finished threads (I assume it's easy to check if thread finished) before starting new one.

I think that there is a signal emited when a thread finishes so freeing their resources should be trivial also. So yes, the option 1 is probably better... :)

**Comment by andrewdavidwong** [comment] 2018-12-19 05:56
@donob4n: Please confirm the version of `qubes-core-dom0` you're using.

**Comment by donob4n** [comment] 2018-12-19 09:44
It is 'qubes-core-dom0-4.0.37-1.fc25' @andrewdavidwong

**Comment by marmarta** [comment] 2019-05-12 19:08
This should have been fixed by assorted fixes for QThreads; I cannot reproduce the issue with current qube manager.

**Closed by marmarta** 2019-05-12 19:08 UTC
Labels: C: manager/widget, T: enhancement, r4.0-dom0-stable, ux
