### ISSUE TITLE
Cannot shut down a qube in startup_timeout

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7116] opened 2021-12-11 11:41 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1, but R4.0 was also affected last I checked.

### Brief summary

A qube cannot be shut down via the Qubes tools until either it is fully started or its startup_timeout expires.

### Steps to reproduce

Misconfigure a qube so that it never finishes starting, and assign a long startup_timeout.

### Expected behavior

The qube can be shut down during the startup_timeout using the normal Qubes tools, without having to restart qubesd or resort to `xl` or `virsh`.

### Actual behavior

The normal Qubes tools do not allow the qube to be shut down during the startup_timeout.  The qube can still be shut down manually via `xl` or `virsh` commands in dom0.  If qubesd is restarted, the normal qubes tools can shut down the qube, even if its startup_timeout still has not elapsed.

**Comment by marmarek** [comment] 2022-03-02 11:37
Duplicate of https://github.com/QubesOS/qubes-issues/issues/6322

**Closed by marmarek** 2022-03-02 11:37 UTC
Labels: T: bug, C: core, P: default, needs diagnosis

**Comment by andrewdavidwong** [comment] 2022-03-02 14:50
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
