### ISSUE TITLE
I get an error when I try to update with dom0 in Qubes.

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5394] opened 2019-10-16 01:11 UTC
I get a mysterious error when I try to update with dom0 of QubesOS. How can I solve it?
qubes-dom0-update
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
error: could not delete old database at /var/lib/qubes/dom0-updates/home/user/.rpmdbold.4070
https://mirrors.phx.ms/qubes/repo/yum/r4.0/current/dom0/fc25/repodata/repomd.xml: [Errno 14] curl#7 - "Couldn't connect"
Trying other mirror.
https://mirror.linux.pizza/qubes-os.org/repo/yum/r4.0/templates-itl/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
No new updates available
No updates available

**Comment by andrewdavidwong** [comment] 2019-10-16 03:01
Duplicate of #5282

**Comment by andrewdavidwong** [comment] 2019-10-16 03:01
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-10-16 03:01 UTC
Labels: P: default, T: bug
