### ISSUE TITLE
Dom0 "update available" icon appears even when no updates are available

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2086] opened 2016-06-19 20:40 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

N/A

---
### Expected behavior:

If no new updates is available for Dom0 the "update(s) available" icon is hidden.
### Actual behavior:

Dom0's "update(s) available" icon is always visible, regardless if updates is available or not.
### Steps to reproduce the behavior:
1. Update dom0.
2. Notice the icon doesn't become hidden, even if rebooting the computer.

**Comment by andrewdavidwong** [comment] 2016-06-20 17:56
Sounds like a regression of #1511.

@marmarek, in cases such as this, do you want a new issue opened, or the old issue re-opened?

**Comment by timcollinsal1** [comment] 2016-06-27 13:34
I know this is minor but wanted to expand  - this is definitely reproduced on my machine. I was able to run the -sudo qubes-dom0-update in terminal and found various updates (the above mentioned issue stated "whether there are updates or not") but also might request some update or clarity in documentation for updates in general on DOC's. I attempted the sudo qubes-dom0-update --enablerepo=qubes-dom0-update-testing/security-testing and received the following error 
 
"Cannot retrieve repository metadata (repomd.xl) for repository: fedora. Please verify its path and try again"

I'm sure it prob me not doing something right (new to Linux in general) but was curious if this was just an 3.2r1 issue or not. As an aside, will there be a text editor added to dom0 for the recommended adjustment on the DOC page for software updates which advise's you can update default repo in etc/yum..etc.? Again, maybe "New to Linux" issue but I am not yet comfortable editing text via console, would prefer small utility or something like Kwrite?

**Comment by timcollinsal1** [comment] 2016-06-27 13:47
Update - The first update I ran in Console did not install or update everything to newest version's - I re-ran the -sudo qubes-dom0-update again and found 8 more "mesa" files still needing update/install. After install/cleanup/verify the "Update" Icon disappeared. 

Also the GUI update icon in Qubes Manager seems to insist that there ARE no new updates but the icon remains - unsure if this is just an recognition issue or maybe something to do with it running through Whonix's sys-whonix GW.

**Comment by andrewdavidwong** [comment] 2016-06-27 17:52
> "Cannot retrieve repository metadata (repomd.xl) for repository: fedora. Please verify its path and try again"

You're downloading updates via Tor, correct? I think this can be caused by "bad" exit nodes. I find it helps to request a new circuit (or simply wait until a new one is automatically selected, which occurs every ten minutes), then retry the update.

> As an aside, will there be a text editor added to dom0 for the recommended adjustment on the DOC page for software updates which advise's you can update default repo in etc/yum..etc.? Again, maybe "New to Linux" issue but I am not yet comfortable editing text via console, would prefer small utility or something like Kwrite?

There are a lot of tutorials on the web regarding basic Vi(m) usage. You're also free to install whichever graphical text editor you like in dom0 (but note that the usual warnings about installing and running programs in dom0 still apply).

> Also the GUI update icon in Qubes Manager seems to insist that there ARE no new updates but the icon remains - unsure if this is just an recognition issue or maybe something to do with it running through Whonix's sys-whonix GW.

Did you make a typo here? (There is no icon to indicate that there are no new updates available. Rather, there is an icon that is supposed to indicate the availability of new updates, and the absence of that icon is supposed to indicate that there are no new updates available.)

**Comment by timcollinsal1** [comment] 2016-06-27 20:57
Apologies yes, the Icon in Qubes Manager showing updates are available is
visible, but after using the update button (down arrow) a GUI notice says
that all updates are installed but the icon remains (hence the icon
showing).

The icon did not dissappear until I ran the update through the console
update command line. I had to run it three times total in console before
the GUI update available icon in Qubes Manager dissappeared.

**Comment by andrewdavidwong** [comment] 2016-10-17 06:42
Note: Some users (myself included) have a false dom0 update notification only occasionally (~2 times/week), not all the time.

For example:

[On 2016-10-16 23:35, Alex wrote:](https://groups.google.com/d/msgid/qubes-users/ec09e17a-6a59-8c2f-bfb7-795f69244560%40gmx.com)
> Hi everyone,
> in the last months I've been getting a lot (say, twice a week?) of
> notifications of dom0 updates available which turn out to be false. I run
> $ sudo qubes-dom0-update
> but it tells me that there are no updates available.
> 
> I can't really recall exactly when this started, nor can I connect the
> beginning of this with any specific events. I did some manual RPM
> installations in dom0, related to Xorg and some Radeon drivers, which
> have been ultimately undone; I don't know if this may have affected the
> situation.
> 
> I believe I remember that it's the firewallVM that does the actual
> update check for dom0, so I ask: is there anything that needs to be
> synchronized? My firewallVM is based off Fedora 24 (not the default
> template, but the old Fd-23 manually updated to 24), and dom0 has Fedora
> 23 (Qubes is R3.2).
> 
> If you have any other ideas for further debug (like "please check these
> two files they should match" or "make sure this command returns zero")
> let me know.. I know nothing about yum/dnf/rpm as a system.
>

**Comment by andrewdavidwong** [comment] 2016-11-26 11:50
Since upgrading to 3.2, I've noticed false dom0 update notifications occurring much more frequently (once every couple of hours).

**Comment by marmarek** [comment] 2016-12-04 21:31
Found it: `dnf` have slightly different output, especially print on stdout a line `Last metadata expiration check: 1:44:39 ago on Sun Dec  4 20:46:00 2016.` which is confused with available update.

**Comment by dmoerner** [comment] 2016-12-10 15:19
Great to hear you figured out the problem; I now get these notifications once a day. Would it be possible to push this fix to Qubes 3.2?

Now every single update we get to dom0 will come from you (rather than Fedora upstream) and should really be important. We don't want users to ignore them because this feature doesn't work reliably.

**Comment by dmoerner** [comment] 2016-12-19 23:58
Hi, was going to write a patch to just fix this, but then I found that this bug was actually already fixed in git, but the wrong commit was referenced (Should be #2086, not #2096) 

https://github.com/marmarek/qubes-core-agent-linux/commit/a9e7f91ca653ae4d474727844160a1567a094435

**Comment by marmarek** [comment] 2016-12-20 00:24
Ups, indeed. Anyway, as you can see in #2096, the fix is already in testing repository.

**Comment by andrewdavidwong** [comment] 2017-03-06 11:11
@marmarek: It appears that the fix has already moved from testing to stable. (At any rate, the problem is no longer exhibited on my stable system.) Should this be closed?

Note that the fix may have caused the opposite problem: #2677.

**Closed** 2017-03-07 21:44 UTC
Labels: bug, C: qubes-manager, P: major

**Comment by speedtester** [comment] 2019-07-18 15:59
Hello,

I'm having the same problem with my new debian-10 qube: "Qubes Update" icon appears in tray with: "Updates are available." message, and down arrow icon appears also in qube manager.
However both update methods ends with no updates available.

Please advise.
