### ISSUE TITLE
"Close lid to encrypt" encrypt LUKS key during hibernate

### ISSUE THREAD

**Issue by besendorf** [QubesOS/qubes-issues#5756] opened 2020-04-04 06:38 UTC
**The problem you're addressing (if any)**
As most people use Laptops as their primary devices (excluding smartphones) and batterys have gotten better and power consumption lower, most have transition to very rarely shuting their laptops down and instead use sleep or hibernate mode which leaves the encryption keys in RAM in plaintext.

**Describe the solution you'd like**
Clear the key from RAM during suspend. There have been a few attempts to implement this for various distributions. But it was always not working 100% because of race conditions when suspending. Since Linux 5.6 however there is is a kernel patch by this project:
https://fosdem.org/2020/schedule/event/dip_close_lid_encrypt/ 

**Where is the value to a user, and who might that user be?**
This would greatly benefit the secruity of encryption harddrives on qubes os and protect activists, journalists from espacially state surveilance.

**Describe alternatives you've considered**
On the design side: The only alternative for users is to always shut down their devices when they stop using them.
On the implementatin side: Here are 2 other projects that tried to implement this:
https://github.com/guns/go-luks-suspend
https://github.com/vianney/arch-luks-suspend

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
The repo of the project I mentioned:
https://salsa.debian.org/mejo/cryptsetup-suspend
The patch that was submitted to the kernel: https://lkml.org/lkml/2020/1/16/310

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
-

**Comment by andrewdavidwong** [comment] 2020-04-04 23:14
Duplicate of #2890

**Comment by andrewdavidwong** [comment] 2020-04-04 23:14
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-04-04 23:14 UTC
Labels: P: default, T: enhancement

**Comment by ncorbuk** [comment] 2023-03-01 22:05
cant you use edit laptop close lid settings from suspend/sleep to shutdown/hybernate? that way disk is encrypted when laptop lid closes? no data/keys in ram?

**Comment by brendanhoar** [comment] 2023-03-01 22:28
Xen does not support hibernate.

**Comment by andrewdavidwong** [comment] 2023-03-02 00:17
Please note that the issue tracker (qubes-issues) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by ncorbuk** [comment] 2023-03-04 21:06
> Xen does not support hibernate.

ah okay my bad, thanks.
