### ISSUE TITLE
Glitched screen with artifacts in sys-gui-gpu.

### ISSUE THREAD

**Issue by Arna13** [QubesOS/qubes-issues#7432] opened 2022-04-10 20:28 UTC
### Qubes OS release

Latest Qubes 4.1 (R4.1)
uname: "Linux dom0 5.10.104-3.fc32.qubes.x86_64"

### Brief summary

`sys-gui-gpu` doesnt work correctly, the screen shows graphical glitches, flicker, a green-ish tone and a weird aspect ratio (Image attached). I also get different graphical artifacts in `sys-gui` very similar to the video in #7424.

![PXL_20220410_220859431](https://user-images.githubusercontent.com/51060310/162638258-f31659ea-90ed-4d45-9d9b-e6f4195ec013.jpg)

My system is a Lenovo Thinkpad T430 with an Intel Core i5-3320M with Intel HD Graphics 4000 and 8GB of RAM.
I am running Heads in my BIOS ROM chip, which uses coreboot's [libgfxinit](https://github.com/coreboot/libgfxinit) to initialize the igpu.
I have tried using Coreboot with SeaBIOS and libgfxinit as well as SeaBIOS with VGA initialization providing a videobios.rom. In any case the result is the same.
I have not tried to use vendor's BIOS ROM, and I would like to avoid doing so if possible.

As a side note, I never got to dump my vgabios from linux as I always get an I/O error, I had to extract it from vendor firmware to use it with SeaBIOS in my tests.

### Steps to reproduce

Install Qubes 4.1
Run "sudo qubes-dom0-update" (also tried without updating on a fresh install)
Create `sys-gui-gpu` as shown [here](https://www.qubes-os.org/doc/guivm-configuration/)
Run "qvm-start sys-gui-gpu" in a terminal after rebooting.

### Expected behavior

The screen shows fine, with no artifacts or tearing and the display's right aspect ratio and colors.

### Actual behavior

When the vm loads, screen shows a green tone, graphical glitches and tearing with artifacts. The video is smooth though.

**Comment by ben-grande** [comment] 2024-07-17 09:27
Duplicate of https://github.com/QubesOS/qubes-issues/issues/7424

**Comment by Arna13** [comment] 2024-07-17 10:43
#7424 is about sys-gui and this issue is about sys-gui-gpu, but I'm happy to merge this issue with #7424 if you feel it's appropriate.

**Comment by ben-grande** [comment] 2024-07-17 11:54
With your response, I believe it is the same cause but I cannot assert it and mark as duplicate.

**Closed** 2024-12-07 14:37 UTC
Labels: T: bug, C: gui-domain, P: default, hardware support, affects-4.1, eol-4.1
