### ISSUE TITLE
DNS `10.139.1.1` and `10.139.1.2` not work  in Qubes R4.0

### ISSUE THREAD

**Issue by Retia-Adolf** [QubesOS/qubes-issues#4472] opened 2018-11-04 11:02 UTC
### Qubes OS version: 

`R4.0`

### Affected component(s): 

DNS settings as shown in AppVM's `/etc/resolv.conf` file:
```
nameserver 10.139.1.1
nameserver 10.139.1.2
```
except in `sys-net`, which shows the same as I set by NetworkManager.
And for compare, in AdminVM `dom0` this file contains nothing.

---

### Steps to reproduce the behavior:

I'm not very sure... Haven't seen any other report same with me with Qubes R4.0, but I think I haven't touch anything deeply...

<details>
1. Downloaded `Qubes-R4.0-x86_64.iso` via torrent, verified integrity via DIGEST file.

2. a. Wrote iso to my sdcard SD1 (128GB) using Rufus.
   b. A mess.. Fresh installed on a SurfaceBook to SD2 (64GB), checked options to:
   　• Allocate spare space to existed partition
   　• Use `sys-whonix` as default netvm and updateVM
   c. Read SD2 and wrote to SD3 (128GB) both using Rufus.
   　(in case more space are needed)
   　(I had wrote iso to SD3 before, but can not get it booted, so gave up and formatted)
   　(however, it does boot for an already installed Qubes OS, as below)

3. Successfully get Qubes OS booted from SD3.

4. A mess.. of other issues just existed here by unknown: Hard power off several times because can not shutdown correctly, it will auto restart or remain powered on with lighted black screen; Network disconnects after suspend, and can not connect again until reboot; `sys-net` vm sometimes hangs on booting, sometimes succeeds but retains a black blank terminal window there can't close; BTW I can't find any shortcut in Application menu excepts default one "Qube settings", nor in settings>Applications tab; 
and, when opening settings>Firewall rules tab, it prompts:

>"The 'work' qube is network connected to 'sys-firewall', which does not
support firewall!
You may edit the 'work' qube firewall rules, but these will not take any
effect until you connect it to a working Firewall qube." 

  fixed by command found at [this thread](https://groups.google.com/d/msg/qubes-users/i08ZSoQLPUQ/mg89XMh6AQAJ):
   ```
   qvm-features fedora-26 qubes-firewall 1
   ```
  But my situation is different from the thread's OP.
  I have not done anything except I stated above. These issues are existed "as is"...

5. A mess.. process to finally found the real problem: I thought it was problems with tor at the first, maybe it was blocked or I misconfigured it. I found later the built-in Whonix is the old release 13, not support meeklite, so deleted both its appvm and templates as per [guide](https://www.whonix.org/wiki/Qubes/Uninstall), and changed default netvm and updateVM to `sys-firewall`.
</details>

#### Environment:
SurfaceBook: i7-6600U, 16GB RAM
```
[user@sys-net ~]$ lspci | grep -i eth
00:05.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
```
Set IP manually cause DHCP of my modem&router is broken.
```
Security: WPA2 Personal
IPv4 Method: Manual
Address: 192.168.1.39
Netmask: 255.255.255.0 (/24)
Gateway: 192.168.1.1
DNS Servers: 1.1.1.1, 199.91.73.222, 192.168.1.1
IPv6 Method: Link-Local Only
```
Kernel: `4.14.18-1`, updated to `4.14.74-1` later.

### Expected behavior:

Well, accesses not in `dom0`, and update accesses in `dom0` should both work.

### Actual behavior:

Well, *accesses queried domain names and not in sys-net* are both not work, except that partial accesses by `qubes-dom0-update` via `sys-net` but NOT `sys-firewall` are work.

```
[user@sys-net ~]$ ping 8.8.8.8
[output omitted]
[user@sys-net ~]$ ping www.qubes-os.org
[output omitted]
```

```
[user@sys-firewall ~]$ ping 8.8.8.8
[output omitted]
[user@sys-firewall ~]$ ping www.qubes-os.org
ping: www.qubes-os.org: Name or service not known
```

```
@dom0 ~]$ sudo qubes-dom0-update
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Failed to synchronize cache for repo 'Updates', disabling.
Failed to synchronize cache for repo 'fedora', disabling.
Failed to synchronize cache for repo 'qubes-dom0-current', disabling.
Failed to synchronize cache for repo 'qubes-templates-itl', disabling.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
```
When changed UpdateVM to `sys-net`, partially succeeds; changed back it still fails:

[dom0_update.txt](https://github.com/QubesOS/qubes-issues/files/2545705/dom0_update.txt)

No matter using sys-firewall or sys-net as netvm for fedora-26-dvm:
```
[user@fedora-26-dvm ~]$ ping www.qubes-os.org
ping: www.qubes-os.org: Name or service not known
```

Run firefox in fedora-26-dvm, try to browse `www.qubes-os.org` or `www.wikipedia.org`, shows:
> We can't connect to the server at www.qubes-os.org

etc.

Run firefox in fedora-26-dvm, try to enter IP addresses directly to browse:
```
185.199.111.153 # for qubes-os.org
198.35.26.96    # for wikipedia.org
192.30.253.112  # for github.com
13.35.20.81     # for developer.mozilla.org
```
Can't load any actual content, but does received error page or redirect to domain (for github) from remote server.

### General notes:

---

**Comment by Retia-Adolf** [comment] 2018-11-04 12:53
@unman emmm.. I mean I can't update `dom0` when UpdateVM is set to `sys-firewall`, `qubes-dom0-update` fails. I can update `dom0` when UpdateVM is set to `sys-net`, but `qubes-dom0-update` still prints some errors like "`Curl error (6): Couldn't resolve host name`". Please see [dom0_update.txt](https://github.com/QubesOS/qubes-issues/files/2545705/dom0_update.txt).

And I get similar errors in `fedora-26-dvm` this disposable VM too (it's not template). In this disposable VM, ping a Internet domain name returns error "`Name or service not known`"; and Firefox reports "`We can't connect to the server at www.qubes-os.org`", while manually enter the IP I can get a 404 page sent by github server. Thus, I think I have encountered a problem, that DNS not working for me for some reason, so when programs request to resolve a name they can't get responses.

**Comment by marmarek** [comment] 2018-11-04 13:11
Your problems with `qubes-firewall` feature not set and missing menu entries suggests the initial setup didn't completed successfully. So, first of all I'd try to fix that:
```
qvm-run -p --service fedora-26 qubes.PostInstall
```

This should regenerate missing menu entries, set `qubes-firewall` and other features etc. After that, restart all the VMs.

**Comment by Retia-Adolf** [comment] 2018-11-09 03:30
@marmarek thanks for reply. Tried it, no luck, it prompts:
```
connect: No such file or directory
```

then I shutdown `sys-firewall`, `sys-net`, `fedora-26` one by one and start them likewise. But nothing different than before.

And then I tried restarting Qubes OS and ran the same command again, got same result. This time I did not bother with VMs, tried restarting physical machine directly, still no luck.

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/34053927/48241600-88f08680-e3cf-11e8-8770-17f6af468c1c.png)

</details>

Should I just try reinstalling Qubes OS?

**Comment by marmarek** [comment] 2018-11-09 09:31
Try wait a little (a minute) after starting fedora-26 and only then call this qvm-run. If it still doesn't help, then indeed reinstalling may be the easiest thing to do (I assume you don't have much data there yet).

**Comment by DemiMarie** [comment] 2021-12-20 23:57
Is this still a problem, or should it be closed as “cannot reproduce”?

**Comment by andrewdavidwong** [comment] 2021-12-21 04:51
Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-12-21 04:51 UTC
Labels: T: bug, C: other

**Comment by mcku** [comment] 2022-04-13 04:21
I have faced the same symptoms some time after migrating to a new laptop. As the old laptop was still available it was possible to compare with a working configuration. 
For some reason, on the new laptop's default template, /etc/resolv.conf was symlinked to a systemd path.  
But on the old laptop it was an empty file.

Removing the symlink and placing an empty resolv.conf file solved my issue. 
I am still unsure what caused this. Because it worked fine quite some time until I played with networking qubes on the new laptop.

**Comment by DemiMarie** [comment] 2022-04-13 04:29
> I have faced the same symptoms some time after migrating to a new laptop. As the old laptop was still available it was possible to compare with a working configuration. For some reason, on the new laptop's default template, /etc/resolv.conf was symlinked to a systemd path. But on the old laptop it was an empty file.
> 
> Removing the symlink and placing an empty resolv.conf file solved my issue. I am still unsure what caused this. Because it worked fine quite some time until I played with networking qubes on the new laptop.

That’s #7429.
