### ISSUE TITLE
Initial setup fail if disk using 4Kn sector size with lvm+thin pool

### ISSUE THREAD

**Issue by 51lieal** [QubesOS/qubes-issues#7398] opened 2022-03-31 14:30 UTC
### Qubes OS release

4.1

### Brief summary

- Qubes automatically use 4Kn sector size if the lbaf is already 4K.
- After install I need to configure everything manually, from install templates, to add vm pool.
- BTRFS install works out of the box.

### Steps to reproduce

- Using manual partition with configuration like this : 

```
gdisk /dev/nvme0n1

1. +600MiB
2. +1GiB
3. the rest of remaining space.

cryptsetup -c aes-xts-plain64 -h sha512 -s 512 --sector-size 4096 luksFormat /dev/nvme0n1p3
cryptsetup luksOpen /dev/nvme0n1p3 luks
pvcreate /dev/mapper/luks
vgcreate qubes_dom0 /dev/mapper/luks
lvcreate -n swap -L 32G qubes_dom0 
lvcreate -T -L 40G qubes_dom0/root-pool
lvcreate -T -l 95%FREE qubes_dom0/vm-pool
lvs (to check your vm-pool size)
lvcreate -V40G -T qubes_dom0/root-pool -n root
lvcreate -V800G -T qubes_dom0/vm-pool -n vm ( around 800gb i forgot)
mkfs.xfs /dev/qubes_dom0/vm 
```

Configure partition : 

```
600 MiB > reformat > EFI partition > /boot/efi > update
1 GiB > reformat > xfs > /boot > update
40 GiB > reformat > xfs > / > update
(swap) > reformat > swap > update
and leaving vm-pool untouched
```

### Expected behavior

Initial setup should work

### Actual behavior

- Initial setup fail.
- VM-pool is not automatically added.

### Solutions you've tried

- Skip Initial setup.
- Install Templates located in /var/lib/qubes/template-package (i forget the path, should be around /var/lib/qubes).
- Use salt to configure everthing.
- Qubes already to be used.

### Additional context

- I cannot install default template located in above path to vm-pool, but creating an AppVM / DispVM based on varlibqubes pool which TemplateVM reside to vm pool is fine.
- Building a 4Kn templates using qubes-builder cannot be installed in varlibqubes, Installed to vm-pool is fine, creating an AppVM / DispVM to both pool is fine too.

**Comment by 51lieal** [comment] 2022-05-20 06:31
I think the problem is around kernel support / qubes storage driver, here's my another test.

-- btrfs 512
# /var/log/xen/console/guest-bullseye-minimal.log
[2022-05-20 09:05:30] Waiting for /dev/xvda* devices...
[2022-05-20 09:05:30] Qubes: Doing R/W setup for TemplateVM...
[2022-05-20 09:05:30] [    2.852297]  xvdc: xvdc1 xvdc3
[2022-05-20 09:05:30] Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
[2022-05-20 09:05:30] no label, UUID=0b3ffcfd-55c2-4330-88cd-b32eed24e15a
[2022-05-20 09:05:30] Qubes: done.
[2022-05-20 09:05:30] [    2.866559] BTRFS: device fsid ae9d67c9-8e58-4616-b2be-39f4638ee359 devid 1 transid 49 /dev/xvda3 scanned by mount (197)
[2022-05-20 09:05:30] [    2.866760] BTRFS info (device xvda3): flagging fs with big metadata feature
[2022-05-20 09:05:30] [    2.866784] BTRFS info (device xvda3): using free space tree
[2022-05-20 09:05:30] [    2.866794] BTRFS info (device xvda3): has skinny extents
[2022-05-20 09:05:30] [    2.872753] BTRFS info (device xvda3): enabling ssd optimizations
[2022-05-20 09:05:30] Waiting for /dev/xvdd device...
[2022-05-20 09:05:30] [    2.875342] /dev/xvdd: Can't open blockdev
[2022-05-20 09:05:30] [    2.875453] EXT4-fs (xvdd): mounting ext3 file system using the ext4 subsystem
[2022-05-20 09:05:30] [    2.879403] EXT4-fs (xvdd): mounted filesystem with ordered data mode. Quota mode: none.
[2022-05-20 09:05:30] mount: /tmp/modules: WARNING: device write-protected, mounted read-only.
[2022-05-20 09:05:30] mount: /sysroot/lib/modules: mount point does not exist.
[2022-05-20 09:05:30] [    2.903313] BTRFS info (device xvda3): using free space tree
[2022-05-20 09:05:30] switch_root: cannot access /sbin/init: No such file or directory
[2022-05-20 09:05:30] switch_root: failed to execute /sbin/init: No such file or directory
[2022-05-20 09:05:30] [    2.907091] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00

-- btrfs 4kn 
# /var/log/xen/console/guest-bullseye-minimal.log
[2022-05-20 09:21:18] Waiting for /dev/xvda* devices...
[2022-05-20 09:21:18] Qubes: Doing R/W setup for TemplateVM...
[2022-05-20 09:21:18] [    2.830061]  xvdc: xvdc1 xvdc3
[2022-05-20 09:21:18] Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
[2022-05-20 09:21:18] no label, UUID=1f0a2ede-a793-43d1-92e4-92c806d8eada
[2022-05-20 09:21:18] Qubes: done.
[2022-05-20 09:21:18] mount: /sysroot: wrong fs type, bad option, bad superblock on /dev/xvda, missing codepage or helper program, or other error.
[2022-05-20 09:21:18] Waiting for /dev/xvdd device...
[2022-05-20 09:21:18] [    2.853361] /dev/xvdd: Can't open blockdev
[2022-05-20 09:21:18] [    2.853516] EXT4-fs (xvdd): mounting ext3 file system using the ext4 subsystem
[2022-05-20 09:21:18] [    2.854866] EXT4-fs (xvdd): mounted filesystem with ordered data mode. Quota mode: none.
[2022-05-20 09:21:18] mount: /tmp/modules: WARNING: device write-protected, mounted read-only.
[2022-05-20 09:21:18] mount: /sysroot/lib/modules: mount point does not exist.
[2022-05-20 09:21:18] mount: /sysroot: mount point not mounted or bad option.
[2022-05-20 09:21:18] switch_root: failed to mount moving /sysroot to /: Invalid argument
[2022-05-20 09:21:18] switch_root: failed. Sorry.
[2022-05-20 09:21:18] [    2.869358] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100

-- xfs 4kn
# /var/log/xen/console/guest-bullseye-minimal.log
fail log same as btrfs 4k

-- xfs 512
[2022-05-20 11:01:53] Waiting for /dev/xvda* devices...
[2022-05-20 11:01:53] Qubes: Doing R/W setup for TemplateVM...
[2022-05-20 11:01:53] [    4.251647]  xvdc: xvdc1 xvdc3
[2022-05-20 11:01:53] Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
[2022-05-20 11:01:53] no label, UUID=4988e98b-6f3e-41b5-afbe-9a4358f5799b
[2022-05-20 11:01:53] Qubes: done.
[2022-05-20 11:01:54] mount: /sysroot: unknown filesystem type 'xfs'.
[2022-05-20 11:01:54] Waiting for /dev/xvdd device...
[2022-05-20 11:01:54] [    4.279990] /dev/xvdd: Can't open blockdev
[2022-05-20 11:01:54] [    4.280098] EXT4-fs (xvdd): mounting ext3 file system using the ext4 subsystem
[2022-05-20 11:01:54] [    4.280843] EXT4-fs (xvdd): mounted filesystem with ordered data mode. Quota mode: none.
[2022-05-20 11:01:54] mount: /tmp/modules: WARNING: device write-protected, mounted read-only.
[2022-05-20 11:01:54] mount: /sysroot/lib/modules: mount point does not exist.
[2022-05-20 11:01:54] mount: /sysroot: mount point not mounted or bad option.
[2022-05-20 11:01:54] switch_root: failed to mount moving /sysroot to /: Invalid argument
[2022-05-20 11:01:54] switch_root: failed. Sorry.
[2022-05-20 11:01:54] [    4.289281] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100

-- ext4 4kn
# /var/log/xen/console/guest-bullseye-minimal.log
fail log same as btrfs 4k

-- All fs and sector size have this fail log.
# /var/log/qubes/qrexec.bullseye-minimal.log
domain dead
qrexec-daemon[11831]: qrexec-daemon.c:340:init: cannot connect to qrexec agent: No such file or directory

-- ext4 512
doesn't have any problem.


A workround for 4k drive to work if using xfs / btrfs / ext4 4kn template format is to install template in secondary storage which use lvm_thin driver rather than file-reflink.

**Comment by DemiMarie** [comment] 2022-05-20 14:07
Looks like the sector size in dom0 does not get propagated to the VMs.

**Comment by marmarek** [comment] 2022-05-20 15:02
This is a tricky issue. All the filesystem images (and partition tables) needs to be adjusted. Currently we ship all the templates the same - with 512 sector size. This is an issue not only for fresh installation, but also later, if you clone/migrate VMs between storage pools. Maybe we could have some magic in initramfs that will adjust the filesystem on boot, but in general case this is a good solution (takes time on VM startup, in some cases it may be even impossible to do).

**Comment by brendanhoar** [comment] 2022-05-20 15:38
> This is a tricky issue. 

It would be interesting to survey how other Linux-based VM environments, which support templating or host-migration, have handled this problem during the transition to 4Kn hardware (other than forcing 512e mode).

B

**Comment by 51lieal** [comment] 2022-05-20 17:42
> All the filesystem images (and partition tables) needs to be adjusted. Currently we ship all the templates the same - with 512 sector size.

I might be wrong, but in above example, all fs and partition tables has been adjusted to 4k as you can see here.

![image](https://user-images.githubusercontent.com/19891105/169582746-7f28e476-2b34-49c5-af39-2d924fb700b1.png)

**Comment by edwintorok** [comment] 2023-08-07 17:43
I think I've run into the same problem (`/dev/xvdd: Can't open blockdev`) trying out Qubes 4.2.0-RC1, I have 4K sector sizes on my NVME drive:
```
# nvme list
/dev/nvme0n1          /dev/ng0n1            20068229000128554D0C Force MP600                              0x1          1.00  TB /   1.00  TB      4 KiB +  0 B   EGFM11.3

# nvme id-ns -H /dev/nvme0n1
LBA Format  0 : Metadata Size: 0   bytes - Data Size: 512 bytes - Relative Performance: 0x2 Good 
LBA Format  1 : Metadata Size: 0   bytes - Data Size: 4096 bytes - Relative Performance: 0x1 Better (in use)
```

Perhaps this should be detected/warned by the installer?

The problem is worse on 4.2.0-RC1: if you enable the use of `sys-usb` (which is the default): `sys-usb` will fail to boot (like all the other VMs), and that causes an immediate host reboot, making it difficult to debug what is wrong (turning off the creation of `sys-usb` avoids the immediate host reboot and allows to collect logs).

I'm going to try the reverse of https://www.bjonnh.net/article/20210721_nvme4k/ and switch the drive back to 512 mode and report back.

**Comment by edwintorok** [comment] 2023-08-07 20:36
Confirmed the *workaround* that reformatting the NVME drive with 512 byte sectors works, here are the commands that I used (this will obviously ERASE all the data on the drive, so it won't work if the drive is to be shared with another existing OS):
```
sudo nvme id-ns -H /dev/nvme0n1
sudo nvme format --lbaf=0 /dev/disk/by-id/nvme-Force_MP600_20068229000128554D0C
```

(this only works on NVME devices, I don't think there is an equivalent for 4Kn HDD devices)

**Comment by DemiMarie** [comment] 2023-08-07 23:52
Which filesystems care about underlying sector size and which do not?

**Comment by marmarek** [comment] 2023-08-13 00:20
This looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/4974

**Comment by andrewdavidwong** [comment] 2023-08-13 13:20
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-08-13 13:20 UTC
Labels: T: bug, C: installer, P: default, needs diagnosis, C: storage, affects-4.1
