### ISSUE TITLE
libvirtError: internal error: libxenlight failed to create domain (when installing Windows Tools)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2096] opened 2016-06-20 19:03 UTC
[Micah Lee wrote](https://groups.google.com/d/msg/qubes-users/ML2TKnZ4PxE/1SMjGgE2BwAJ):
> I think I'm running into this same problem. I'm running Qubes R3.2 RC1. 
> I have an HVM called win7 with Windows 7 installed. Here's the error I 
get when I try to install windows tools: 

```
[m@dom0 ~]$ qvm-start win7 --install-windows-tools 
--> Loading the VM (type = HVM)... 
Traceback (most recent call last): 
  File "/usr/bin/qvm-start", line 131, in <module> 
    main() 
  File "/usr/bin/qvm-start", line 115, in main 
    xid = vm.start(verbose=options.verbose, 
preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, 
notify_function=tray_notify_generic if options.tray else None) 
  File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", 
line 326, in start 
    return super(QubesHVm, self).start(*args, **kwargs) 
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", 
line 1963, in start 
    self.libvirt_domain.createWithFlags(libvirt.VIR_DOMAIN_START_PAUSED) 
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1059, in 
createWithFlags 
    if ret == -1: raise libvirtError ('virDomainCreateWithFlags() 
failed', dom=self) 
libvirt.libvirtError: internal error: libxenlight failed to create new 
domain 'win7' 
```

**Comment by marmarek** [comment] 2016-06-20 19:14
Looks like a duplicate of #1977

**Closed by marmarek** 2016-06-20 19:14 UTC
Labels: bug, C: windows tools, duplicate

**Comment by marmarek** [comment] 2016-12-12 21:42
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.15-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/938d184ef484170b4a1e3e2a4634c54cf684772c...fb8c356216f693eca09665dd03219e83c7bd1c03

**Comment by marmarek** [comment] 2016-12-12 21:42
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.15-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/938d184ef484170b4a1e3e2a4634c54cf684772c...fb8c356216f693eca09665dd03219e83c7bd1c03

**Comment by marmarek** [comment] 2016-12-12 21:43
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.15-1.fc25` has been pushed to the `r3.2` testing repository for the Fedora `fc25` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/938d184ef484170b4a1e3e2a4634c54cf684772c...fb8c356216f693eca09665dd03219e83c7bd1c03
