### ISSUE TITLE
Nvidia driver installation on Qubes 4 fails (kernel building)

### ISSUE THREAD

**Issue by keeponhacking** [QubesOS/qubes-issues#4614] opened 2018-12-15 17:56 UTC
I am using Qubes 4
GPU: Nvidia GTV 970

I read few guides on how to install proprietary nvidia drivers for my GTX 970 and here is what happened.

What is the guide i found:

1. dom0:   qubes-dom0-update install gcc devel-kernel ksmod linux-headers
2. appvm:  download NVIDIA-Linux-375.20-install.run (any appvm)
3. dom0:   qvm-run --pass-io <APPVM> 'cat /PATH/TO/NVIDIA.run' > NVIDIA.run
4. dom0:   ./NVIDIA.run --ui=none --no-x-check --keep --extract-only
5: dom0:   cd NVIDIA-*/kernel/;  IGNORE_XEN_PRESENCE=y CC="gcc -DNV_VMAP_4_PRESENT -DNV_SIGNAL_STRUCT_RLIM" make module;
6: dom0:   cp nvidia.ko /lib/modules/4.4.31-11.pvops.qubes.x86_64/extra/.
7: dom0:   depmod -a; modinfo nvidia (all working will show up fine)
8: dom0:   EDIT GRUB or EFI; add rd.driver.blacklist=nouveau

After running 
5: dom0:   cd NVIDIA-*/kernel/;  IGNORE_XEN_PRESENCE=y CC="gcc -DNV_VMAP_4_PRESENT -DNV_SIGNAL_STRUCT_RLIM" make module;

I get this error:

```
[barandu@dom0 kernel]$ sudo cd NVIDIA-*/kernel; IGNORE_XEN_PRESENCE=y CC="gcc -DNV_VMAP_4_PRESENT -DNV_SIGNAL_STRUCT_RLIM" make module;
/bin/cd: line 2: cd: NVIDIA-*/kernel: No such file or directory
make "CC=gcc -DNV_VMAP_4_PRESENT -DNV_SIGNAL_STRUCT_RLIM" KBUILD_OUTPUT=/lib/modules/4.14.74-1.pvops.qubes.x86_64/build KBUILD_VERBOSE= -C /lib/modules/4.14.74-1.pvops.qubes.x86_64/source M=/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel ARCH=x86_64 NV_KERNEL_SOURCES=/lib/modules/4.14.74-1.pvops.qubes.x86_64/source NV_KERNEL_OUTPUT=/lib/modules/4.14.74-1.pvops.qubes.x86_64/build NV_KERNEL_MODULES="nvidia nvidia-uvm nvidia-modeset nvidia-drm" INSTALL_MOD_DIR=kernel/drivers/video modules
make[1]: Entering directory '/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64'
make[2]: Entering directory '/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64'
  LD [M]  /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia.o
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-frontend.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-instance.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-acpi.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-chrdev.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-cray.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-dma.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-gvi.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-i2c.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-mempool.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-mmap.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-p2p.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-pat.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-procfs.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-usermap.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-vm.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-vtophys.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/os-interface.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/os-mlock.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/os-pci.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/os-registry.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/os-usermap.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-modeset-interface.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-pci-table.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-kthread-q.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv-kthread-q-selftest.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nv_uvm_interface.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/ebridge_linux.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/ibmnpu_linux.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nvlink_linux.o: No such file or directory
ld: cannot find /home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia/nvlink_pci.o: No such file or directory
/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64/scripts/Makefile.build:574: recipe for target '/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia.o' failed
make[3]: *** [/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia.o] Error 1
/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64/Makefile:1527: recipe for target '_module_/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel' failed
make[2]: *** [_module_/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64'
Makefile:146: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64'
Makefile:81: recipe for target 'modules' failed
make: *** [modules] Error 2
[baransu@dom0 kernel]$ /usr/src/kernels/4.14.74-1.pvops.qubes.x86_64/scripts/Makefile.build:574: recipe for target '/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia.o' failed
bash: /usr/src/kernels/4.14.74-1.pvops.qubes.x86_64/scripts/Makefile.build:574:: No such file or directory
[baransu@dom0 kernel]$ make[3]: *** [/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel/nvidia.o] Error 1
bash: make[3]:: command not found
[baransu@dom0 kernel]$ /usr/src/kernels/4.14.74-1.pvops.qubes.x86_64/Makefile:1527: recipe for target '_module_/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel' failed
bash: /usr/src/kernels/4.14.74-1.pvops.qubes.x86_64/Makefile:1527:: No such file or directory
[baransu@dom0 kernel]$ make[2]: *** [_module_/home/baransu/NVIDIA-Linux-x86_64-375.20/kernel] Error 2
bash: make[2]:: command not found
[baransu@dom0 kernel]$ make[2]: Leaving directory '/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64'
bash: make[2]:: command not found
[baransu@dom0 kernel]$ Makefile:146: recipe for target 'sub-make' failed
bash: Makefile:146:: command not found
[baransu@dom0 kernel]$ make[1]: *** [sub-make] Error 2
bash: make[1]:: command not found
[baransu@dom0 kernel]$ make[1]: Leaving directory '/usr/src/kernels/4.14.74-1.pvops.qubes.x86_64'
bash: make[1]:: command not found
[baransu@dom0 kernel]$ Makefile:81: recipe for target 'modules' failed
bash: Makefile:81:: command not found
[baransu@dom0 kernel]$ make: *** [modules] Error 2
bash: make:: command not found
```

The second thing i'm wondering is that I don't have /etc/default/grub file
Where do i have to add the nouveau blacklist? Would echo "blacklist nouveau" >> /etc/modprobe.d/blacklist.conf work?

Best regards

**Comment by andrewdavidwong** [comment] 2018-12-15 18:16
Duplicate of #4610

**Comment by andrewdavidwong** [comment] 2018-12-15 18:16
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-12-15 18:16 UTC
