### ISSUE TITLE
 Enabling Community Templates in Qubes 4.2 via Global Config Editor strange error

### ISSUE THREAD

**Issue by britl37** [QubesOS/qubes-issues#8349] opened 2023-07-10 19:23 UTC
### Qubes OS release
R4.2

### Brief summary
When attempting to enable Community templates or Official Testing Templates via the Global Config Editor gui in Qubes R4.2, I am receiving this strange error: “dom0 Could not save changes… The following error occured: can only concatenate str (Not “NoneType”) to str”

Screenshot: https://imgur.com/C1ZNZSN

### Steps to reproduce
1. Open Qubes Global Config Editor via Settings menu or Qubes Manager GUI
2. Go to Updates tab
3. Scroll to the bottom and check the box to enable Community Templates or Official Testing Templates
4. Press Apply or OK
5. Error message comes up

### Expected behavior
Changes should save normally and Community Templates or Official Testing Templates should be enabled.

### Actual behavior
Changes do not save and Community Templates or even Official Testing Templates can not be enabled via the Qubes Global Config GUI.

**Comment by marmarek** [comment] 2023-07-10 20:50
This looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/8152. Can you install [updates from current-testing](https://www.qubes-os.org/doc/how-to-install-software-in-dom0/#testing-repositories) repository and re-check?

**Comment by britl37** [comment] 2023-07-10 21:34
> This looks like a duplicate of #8152. Can you install [updates from current-testing](https://www.qubes-os.org/doc/how-to-install-software-in-dom0/#testing-repositories) repository and re-check?

I updated and rebooted, still getting the same thing.

**Comment by britl37** [comment] 2023-07-11 00:11
Looking at this further, it seems changing any setting on the "Updates" tab in Qubes Global Config gui produces the same error. I was able to enable the template repos I wanted through dom0 terminal and the changes reflect in global config gui, but I still can't change anything in there.

**Comment by britl37** [comment] 2023-07-11 00:12
accidental close

**Comment by marmarta** [comment] 2023-07-11 12:43
do you have gui-vm set up?

**Closed** 2023-07-16 02:53 UTC
Labels: T: bug, C: core, C: desktop-linux, C: manager/widget, P: default, diagnosed, pr submitted

**Comment by britl37** [comment] 2023-07-21 19:51
thank you for fixing this and i apologize for not being of more help. i didn’t realize this github account was linked to an older email address. i’ve been on qubes since R3 and still love it! the progress is amazing and i have so much respect for all of you devs.
