### ISSUE TITLE
[Dom0] Error at first boot

### ISSUE THREAD

**Issue by wocsigint** [QubesOS/qubes-issues#2981] opened 2017-08-06 06:53 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): Dom0

---

### Actual behavior: here is the error message :
```
['/usr/bin/qvm-start', 'sys-firewall'] failed:
stdout: ""
stderr : "Start failed: invalid argument cuold not find capabilities for arch=x86_64
```

### General notes:
I run Qubes as a VM (VMware).

---

**Comment by andrewdavidwong** [comment] 2017-08-06 16:48
> I run Qubes as a VM (VMware).

Since this is [not officially supported](https://www.qubes-os.org/doc/user-faq/#can-i-install-qubes-in-a-virtual-machine-eg-on-vmware), it's possible that this issue will be a `wontfix`.

**Comment by marmarek** [comment] 2017-08-06 17:34
Specifically, the error is caused by missing VT-x. Not sure if VMware support VT-x emulation, but anyway this is unsupported configuration.

**Closed by marmarek** 2017-08-06 17:34 UTC
Labels: bug, C: other
