### ISSUE TITLE
debian-based VMs' keyboard layout not corresponding to dom0

### ISSUE THREAD

**Issue by aurora-of-earth** [QubesOS/qubes-issues#4582] opened 2018-12-07 07:25 UTC
### Actual behavior: keyboard layout remains the same

As I see the fedora-based VMs don't have this problem.
Probably you've included something in the qubes' rpm repos that isn't available(by default) in debian repos.

**Comment by marmarek** [comment] 2018-12-07 13:09
Duplicate of #4489

**Closed by marmarek** 2018-12-07 13:09 UTC
