### ISSUE TITLE
For newbie

### ISSUE THREAD

**Issue by NantaNakamoto** [QubesOS/qubes-issues#2035] opened 2016-05-26 07:17 UTC
1) I launched Firefox and lost a lot of memory. 
2) I installed extensions and themes and set up the browser but the next launch all the settings have been lost.

**Comment by dumbl3d0re** [comment] 2016-05-26 08:53
I assume that you started Firefox in the `DisposableVM`? It's supposed to "reset" after you have closed down firefox, i.e. it's a feature and not a bug.

But I think that we can do it more clear. I don't know if we already have an issue for that. Asking @nrgaway.

**Comment by unman** [comment] 2016-05-26 15:55
@NantaNakamoto  Lack of response makes it difficult to deal with this.
If it is a DisposableVM, the guide in the [docs](https://www.qubes-os.org/doc/dispvm/) is good. Look particularly at the section on customisation. Also this has been covered in detail on the mailing lists. Look there.

If it's not a disposableVM, please explain what sort of qube you were using, and exactly what you did to launch firefox and set up the browser

**Comment by andrewdavidwong** [comment] 2016-05-27 03:26
> 1) I launched Firefox and lost a lot of memory.

What do you mean "lost"?

You're probably just seeing `qmemman` dynamically redistribute the total system memory across the currently running VMs (including dom0). This is normal, expected behavior.

> 2) I installed extensions and themes and set up the browser but the next launch all the settings have been lost.

You probably opened Firefox in a DispVM, as others mentioned.

> But I think that we can do it more clear. I don't know if we already have an issue for that.

If you think that the DispVM docs need to be clarified, please submit a pull request (preferred) or file a separate issue for that.

-----

I'm closing this since it isn't actually a bug report, feature request, or anything else appropriate to `qubes-issues`. It's a set of questions more appropriate for `qubes-users` (or, ideally, answered by reading the [docs](https://www.qubes-os.org/doc/) and the [users' FAQ](https://www.qubes-os.org/doc/user-faq/)).

**Closed by andrewdavidwong** 2016-05-27 03:26 UTC
