### ISSUE TITLE
Backup restore should not touch appmenus

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1627] opened 2016-01-15 15:13 UTC
... or else we end up in a mess, especially when user decided to backup and restore only some of their VMs. So, I propose to exclude the `.local/share/applications` and `.local/share/desktop-directories` from either backup or restore. Possibly other directories also, such as under `.kde/`?

**Comment by marmarek** [comment] 2016-01-15 16:00
This is duplicate of #1106

**Closed by marmarek** 2016-01-15 16:00 UTC
Labels: bug, C: core, C: desktop-linux, duplicate, P: minor
