### ISSUE TITLE
Can't boot anything anymore from usb after installing rc3 once!

### ISSUE THREAD

**Issue by NinjaTurtle007** [QubesOS/qubes-issues#3356] opened 2017-11-29 21:50 UTC
#### Qubes OS version:

4 rc3

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

install rc3 from scratch, full disk encryption

### Actual behavior:
This is related to https://github.com/QubesOS/qubes-issues/issues/3340#issuecomment-347838835
but since we kinda drifter to what could be another issue and this is CRITICAL I took the liberty to start a new issue.

In short. After installing RC3 once and messing it up (tried to shutdown sys-net, it didn't so I killed it) it wouldn't start so I decided to reinstall it from scratch.
Well I can no longer boot anything from a flash drive!
I tried 
legacy boot, 
disable secure boot, 
wipe the bios keys
dding the iso to another flash drive
dding rc2 and booting it
even making bootable ubuntu 17.10 usb drive

Well none of them boots anymore!
It's kinda like I can't use that system anymore!
Current OS is bricked and I can't install new one.

No idea what could be causing this at this point.

It's a new high end system, z270MB, M.2 SSD, i7 7700, 16GB ram
all new and fresh components, not that it's that relevant but really have no idea what might be preventing it from booting from any usb drive

rc2 and rc3 boots are stuck at this screen:
https://imgur.com/a/64dzJ

Ubuntu boot is stuck at the ubuntu logo with the loading dots beneath it.

### General notes:

---

**Comment by Nesos-ita** [comment] 2017-11-30 19:00
Some questions:
-can you access bios (for example by pressing F2/del/typing "fwsetup" in grub/whatever/using reboot in bios option)?
-have you wiped the hdd? i'm interested about ESP (efi system partition, usually a fa32 partition about 100/500MB) if you haven't deleted this DON'T delete it.
-is there some os installed in the hdd? if yes does it boot (also if it crash/BSOD or whatever but it's boot process starts?)
from what i understood you have on the hdd a broken qubes installation (does it boot and crash/freeze? or it is not even found)
you mention ubuntu stucked, also that is booted from hdd?
-pc model?

>No idea what could be causing this at this point.

same here, i spent the last month unbricking friend pc for a similar issue (not caused by Qubes). and fixed it yesterday.
he had ubuntu and wanted to reinstall windows so he wiped the hdd; well this BRICKED the pc, from that moment it started saying "nothing to boot, insert something bootable"; pressing enter(ok) showed the firmware boot menu: ubuntu/grub, and selecting one or other or pressing esc led to the same "nothing to boot message".
-internal hdd didn't work
-external usb/cd didn't work
-couldn't access bios
had to desolder bios chip dump it with spi flash programmer, extract the GPT GUID he wanted to boot and could boot ubuntu after installing it from other pc and changing the guid; still couldn't access bios or changing efivars. at the grub menu pressing esc and typing exit led to the firmware boot menu, selecting grub again and exiting again showed the "usb flash" boot option previously not visible but still whatever you chose it still bot ubuntu.
fixed again with spi flash programmer by unprotecting the spi flash bios memory.
it was fully write protected (protect bits were all 0 so nothing protected but CMP=complement was 1 thus fully protected).
i hope you will not have to tryharder like me.
i can only think a firmware bug no idea...

**Comment by NinjaTurtle007** [comment] 2017-11-30 21:15
**Some answers:**
- I can access bios just fine with del or f2
- I havent touched the hdd with any external tools, when I was still able to start an installation I was reclaiming all the space, by deleting the partitions and installing clean (that in the qubes installer)
- there wasn't, but today I was finally able to install Ubuntu. Funny thing, Ubuntu didnt want to install either at first. I unplugged the PC from the power for 5-10 mins and then it started just fine. But I don't see how this could have changed anything. However, I still can't boot qubes.

- the broken qubes install wasn't starting because i messed up sys-net and it was failing to fully load because of it. I dont have it anymore, installed ubuntu clean over it.

- ubuntu was booted from one of the flash drives I used for qubes (i tried qubes with 2 different usb drives, to excluse bad thumb drive)


- Oh boy, i cant imagine how and OS could damage the bios chip. First thing I hear of something like that :(


- Well I have functional Ubuntu 17.10 install now, so ill be trying your suggestions at the end.

Thank you so much for that long and detailed answer, I was really banging my head against the door before that. Now at least I have stuff to try! Even that is a progress in my situation, lol! :)

**Comment by NinjaTurtle007** [comment] 2017-11-30 21:56
The grub> exit thing showed the boot menu (test and install qubes, install qubes) but selecting any option just returns to the same screen.
After selecting install 10 times it actually went to this screen again https://imgur.com/a/64dzJ
but stucks on it forever like before when booting from the USB directly.


Im updating the bios as I write this. Man love those new bioses, I just selected update over the internet and it downloads it from the bios directly.

It's stuck on downloading it for 20 mins now though, hope that is normal :)
Will update.

**Comment by NinjaTurtle007** [comment] 2017-12-01 10:42
Well the bios update is stuck and downloading and I left it overnight.
So will fight that issue today.

**Comment by Nesos-ita** [comment] 2017-12-01 18:56
Updating the bios is a good idea, doing it over the internet i don't think so...
On my pc (asus) i have used the thing included in the bios (called "ez flash") basically you browse for the file on usb key and click it.

Since you can access bios and you had success installing ubuntu i think that pc is not bricked.
to avoid interferences from past installations and partitions you could try to wipe the hdd before install:
`dd if=/dev/zero of=/dev/sdX bs=1M count=1`
this will wipe the first mb of hdd so it will delete the partition table and grub.
please make a dd copy of the partition table and esp (efi system partition) before trying this, better to have a copy of the whole disk.

I think that this issue can be closed now. 
the fact that you can't install qubes is a duplicate of 
"Pane is dead" error when attempting to install 4.0-rc3": https://github.com/QubesOS/qubes-issues/issues/3340

**Comment by andrewdavidwong** [comment] 2017-12-02 06:16
This appears to be a duplicate of #3340. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-02 06:16 UTC
Labels: bug, C: installer

**Comment by NinjaTurtle007** [comment] 2017-12-02 11:42
@Nesos-ita Do I dd wipe it by entering into grub> upon boot?

**Comment by Nesos-ita** [comment] 2017-12-05 12:16
you have to do it from a live linux, for example from ubuntu installer usb, click try ubuntu and do it from terminal.
if you have problems try search in internet for a solution.

**Comment by NinjaTurtle007** [comment] 2017-12-08 08:20
Updating the bios worked and I successfully installed rc3 again.
Note, updating the bios reset all settings, so that might have helped as well.
