### ISSUE TITLE
`notify-send` in dom0 bash script fails with GDBus.Error

### ISSUE THREAD

**Issue by kennethrrosen** [QubesOS/qubes-issues#8608] opened 2023-10-13 18:43 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.0-rc3 & 4.2.0-rc4

### Brief summary

When running a bash script in dom0, `notify-send` in a variety of ways yields an error. When using the command as a standalone in the terminal emulator, the command functions as it should.

```
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

The daemon appears to be running, since the `notify-send` command works in the terminal and `ps aux | grep notify` shows active daemon. But `usr/share/dbus-1/services/` does not (no longer?) contains a file named `org.freedesktop.Notifications.service`.

The directory contains:
```
[@dom0 services]$ ls 

 ca.desrt.dconf.service
 org.freedesktop.Tracker3.Miner.Files.service
 dbus-qubes-app-menu.service
 org.freedesktop.Tracker3.Miner.RSS.service org.a11y.Bus.service
 org.freedesktop.Tracker3.Writeback.service
 org.freedesktop.impl.portal.desktop.gtk.service
 org.gtk.GLib.PACRunner.service
 org.freedesktop.impl.portal.PermissionStore.service
 org.gtk.vfs.Daemon.service
 org.freedesktop.portal.Desktop.service
 org.gtk.vfs.Metadata.service
 org.freedesktop.portal.Documents.service
 org.gtk.vfs.UDisks2VolumeMonitor.service org.freedesktop.portal.Tracker.service
 org.xfce.FileManager.service org.freedesktop.systemd1.service
 org.xfce.Thunar.FileManager1.service
 org.freedesktop.Tracker3.Miner.Extract.service
 org.xfce.Thunar.service
 org.freedesktop.Tracker3.Miner.Files.Control.service
 org.xfce.Xfconf.service

```

### Steps to reproduce

Use `notify-send` as user or root in dom0 bash script, such as:

```
sudo notify-send -u critical -t 3900 "messagehed" "messagebody"
notify-send -u critical -t 3900 "messagehed" "messagebody"
```

### Expected behavior

Error from bash script, which worked in 4.1, does not occur and notification is sent. 

### Actual behavior

Error from bash script occurs; notification is not sent.

**Comment by marmarek** [comment] 2023-10-13 19:00
I don't think it's a bug, it looks to be related to how you call the script. Note that notify-send needs access to user's session (and especially DBUS_SESSION_BUS_ADDRESS variable that is set on desktop environment startup). In practice, most use systemd to start dbus, and it uses predictible address, so you can simply set it in your script.

**Comment by andrewdavidwong** [comment] 2023-10-13 19:16
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-10-13 19:16 UTC
Labels: T: bug, C: desktop-linux, P: default, needs diagnosis, regression, affects-4.2
