### ISSUE TITLE
Label change not reflected in updated Manager

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4622] opened 2018-12-16 15:16 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

Change label colour of qube.

### Expected behavior:

Change will be reflected in Manager

### Actual behavior:

Label colour does not change in Manager, although Settings confirms change has been made.

### General notes:

---

### Related issues:

Closed #3675

**Comment by andrewdavidwong** [comment] 2018-12-17 01:08
Duplicate of #3675

**Comment by andrewdavidwong** [comment] 2018-12-17 01:08
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-12-17 01:08 UTC
