### ISSUE TITLE
Qube Manager refuses to produce Debian-10 standalone qube; makes Fed-30 qube

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5545] opened 2019-12-29 16:38 UTC
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Qubes Manager

**Brief summary**
Went to create a standalone qube of Debian 10 for a VPN qube. Instead, got a standalone qube of Fedora 30. Twice.

**To Reproduce**
Follow dialouge box to create a new qube (launched from icon). 
In dropdown box for type > 'Standalone...'
in dropdown box for Template > 'debian-10'

Also, named it, selected 'provides network'.

**Expected behavior**
produce a debian-10 standalone qube.

**Actual behavior**
I got a fedora-30 standalone qube.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Glitchy behavior of Qube Manager observed in the past:
-renamed/clone qubes subsituting another qube's firewall rules
-jumbled lines across column entries (e.g. Qube-one suddenly listing with qube-2's template or disk usage. Whole table affected.
-sudden disappearance or radical resorting of line entry for a qube just edited.

**Solutions you've tried**
Going to learn to do by commandline.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by MondayPeople** [comment] 2019-12-30 11:15
18 hours later, getting correct response. (No restart performed, but network connectivity was disrupted for many hours - haven't done anything else). 

Have to include possibility of operator error (it was very late).

**Comment by andrewdavidwong** [comment] 2019-12-30 13:35
> 18 hours later, getting correct response. (No restart performed, but network connectivity was disrupted for many hours - haven't done anything else).
> 
> Have to include possibility of operator error (it was very late).

Closing this for now as "cannot reproduce." If you believe this is a misunderstanding, or if you subsequently find that you can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by MondayPeople** [comment] 2019-12-31 09:01
Please re-open.

1. Just reproduced it, as above. This time, tried creating a deb-9 standalone.

2. Went to repeat it to confirm, but this time it reverted to correct action.

Further notes:
-errors were incurred at different times of day, but each after hours in 'Suspend' mode.
-I query the stability of whatever drives the graphics for Qube Manager. I suspect the dropdown menu isn't actually passing on the selection, or isn't displaying the real selection. The display of the main panel has not infrequently been unstable - rows breaking, mis-alignment of 'name' and the rest of the row (i.e. AppVM-1 jumped down to align with the entry for AppVM-2, for e.g.). Its definitely been glitchy.

**Comment by marmarta** [comment] 2020-01-08 18:10
As far as glitchiness of Qube Manager goes, it should be improved in 4.1, when we go to Qt5 (instead of Qt4 in 4.0).
I have problems reproducing this issue. A question (may this will help?) - do you mean creating a VM from a create new vm window opened before a suspend? Or is it just after a suspend, with a newly opened Create New VM? Also, what is the exact version of qubes-manager package you have? ( `rpm -qa qubes-manager` in dom0).

**Comment by MondayPeople** [comment] 2020-01-09 08:25
Just after a suspend, pretty much the first work task I began: 
Qubes Manager > "Create a new qube" > then the dialogue box to define its attributes.

Version:
qubes-manager-4.0.40-1.fc25.noarch

(Haven't tried it again, busy with other things.)

**Comment by MondayPeople** [comment] 2020-01-09 08:27
Also, thanks for info re QT version.

**Comment by MondayPeople** [comment] 2020-01-09 11:39
Re glitchiness in Qube Manager:

just cloned a couple of qubes in succession. Noticed that 'split highlight effect' between the original qube's "name" cell and the clone's other attributes to the left of the "name" column is systematic. So I guess that's by design? Kind of see the logic in it, but... Will a new Qt version address that?

However, when I changed the NetVM settings on the cloned qube, *something* re-sorted (I; perhaps listing by NetVM?) and I was left with "untrusted" vm - a qube I hadn't touched - listed right above the clone's entry; the two lines displayed a checkerboard pattern, with "untrusted" cell, then 'clone' cell, then "untrusted"... etc. I really don't understand this.

I took a photo on my phone, but I need to crop it and I cannot figure out how to do that in Qubes this evening.

**Comment by MondayPeople** [comment] 2020-01-11 14:01
Hoping this picture comes through. This is an example of the flakiness I'm referring to you (just to prove its real!) I _think_ I had just cloned the shopping vm. I had done _nothing_ with "untrusted".

Just makes no sense to me. But, I take your point about a new QT version.

https://preview.redd.it/hikmw210m5a41.jpg?width=3461&format=pjpg&auto=webp&s=fd64eae8c3ee9061576c2286792e30bfb21092f6

**Comment by marmarta** [comment] 2020-01-11 14:07
Yeah, this is a bug that was there for a long time (due to among others Qt hating huge tables with a passion) - I really hope improvements in the Qt5 version will help (apart from new Qt version there are also some smaller fixes in Qubes4.1). In my own tests it helped, at least.

**Comment by MondayPeople** [comment] 2020-01-13 01:31
Okay, thanks for this.

**Closed** 2023-08-05 09:24 UTC
Labels: T: bug, C: manager/widget, P: default, eol-4.0
