### ISSUE TITLE
Installer fails to create paratitions on Samsung T3 portable SSD

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2097] opened 2016-06-20 19:56 UTC
Thread: https://groups.google.com/d/topic/qubes-users/zVFjCSUk6KE/discussion

Cory Nelson:
> I'm trying to install Qubes 3.1 to a 512GB Samsung T3 (external USB 
3.1 SSD with UAS). May have identified an incompatibility. 
> 
> Qubes errors out while creating partitions. Not the UI to reclaim or 
manually partition, but the step afterward when you finally start the 
install. 
> 
> I've run a full test of the drive verifying no bad blocks and even 
installed Ubuntu on it to ensure it's in working order. I then tried 
to install Qubes to a 64GB thumb drive  on the same PC and it worked 
fine there.

almightylaxz:
> I am also having problems installing Qubes R3.1 to the Samsung T3 External SSD 500GB. Using a pgp and hash verified iso that passes the media verification test. Running on a Intel Core i5-4570 @ 3.20GHz.
> 
> The install fails on the "creating swap" step with an "unknown error". devices.py line 788 is at the top of the error.
> 
> Also, manual partitioning doesn't work. Trying to create the "/" or "/boot" parition results in the error "cannot create aligned partition" or something. Clicking the "automatically create partitions" link in the partition page gives an error along the lines of "the root / partition does not exist" and "the boot partition does not exist".
> 
> I have tried switching the external SSD from a 3.0 port to a 2.0 port to avail. 
> 
> Update:
> 
> I tried the text installation by pressing ctrl+alt+f2 and typing 'anaconda'. The results were as follows:
> 
> Progress
> Setting up the installation environment
> .
> Creating disklabel on /dev/sdc
> .
> Creating efi on /dev/sdc1
> .
> Creating ext4 on /dev/sdc2
> .
> Creating luks on /dev/sdc3
> 
> (anaconda:1277): Gdk-ERROR **: error: XDG_RUNTIME_DIR not set in the environment.
> 
> Trace/breakpoint trap
> 
> (It then goes back to the shell)
>

**Comment by AlmightyLaxz** [comment] 2016-06-21 05:13
I have found a temporary workaround.

Requirements:
Another usb or harddrive of 32gb (qubes system requirement)
Qubes installer or another *nix system

1. Install normally onto a USB or harddrive

2. Use the qubes installer (ctrl+alt+f2) or another *nix system to dd the installed OS to the Samsung T3 Portable SSD
Use lsblk -f to find the appropriate drive letters.

Example: dd if=/dev/sdc of=/dev/sdd bs=1M
/dev/sdc being the installed OS, /dev/sdd being the portable SSD.

I haven't tested the copy extensively, but it's able to boot and run VMs normally.

**Comment by marmarek** [comment] 2016-07-13 00:45
I think this is duplicate of #2099 - fixed in R3.2

**Closed by marmarek** 2016-07-13 00:45 UTC
Labels: bug, C: installer, duplicate
