### ISSUE TITLE
R4.0.x current-testing Xen updates running -> xenstored crashing (was -> pacat-simple-vc 100% cpu)

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5991] opened 2020-08-09 14:29 UTC
**Qubes OS version**
R4.0.x current-testing

**Affected component(s) or functionality**
qubes-dom0-update
Received and installed Xen-* updates this morning after a few days of not updating.

**Brief summary**
Noticed that xentop stopped working (just blank screen when invoked) after Xen upgrades before reboot. Ran top and then noticed three pacat-simple-vc processes each taking 99% CPU. I was able to kill -9 them to regain CPU usage.

**To Reproduce**
As above.

Will update ticket after reboot, but assuming system will act normal.

**Comment by marmarek** [comment] 2020-08-09 14:49
Is that all before post-update reboot? The only change in this update is in the hypervisor part, so it should not affect anything before reboot. Was the Xen packages the only update?

For reference: https://github.com/QubesOS/updates-status/issues/1971

**Comment by brendanhoar** [comment] 2020-08-09 15:22
All before reboot.

The qubes-dom0-update never completed. 

Xl list and xentop stopped working. 

Xl shutdown failed. Any VMs i shutdown remained on the Qubes widget menu (probably because backend xl/libvirt tooling stopped working).

Performed in dom0 sudo shutdown -h now after 30 minutes, still had to hard shutdown after another 10 minutes as remaining volumes could not be dismounted (no limit timeout on luks for example).

Any logs I should pull?

**Comment by marmarek** [comment] 2020-08-09 15:37
Perhaps you have run out of disk space? `journalctl` and/or `dmesg` from dom0 would be useful.

**Comment by brendanhoar** [comment] 2020-08-09 15:57
After a couple of reboots df in dom0 shows all mounted volumes < 10% other than boot at 45%.

I check lvs regularly for data%/metadata% and I’m clear there as well.

Let me go over the journalctl man page to see if I can find the dmesg equivalent from that session.

B

**Comment by brendanhoar** [comment] 2020-08-09 16:04
Everything looks normal until xenstored[2904]: segfault at b50c98 ip 00000000004062b0 sp 00007ffffafd1350 error 6 in xenstored[400000+14000] and then another line Code: bb ff ff 83

**Comment by marmarek** [comment] 2020-08-09 16:32
`xenstored` segv sounds pretty bad. Can you collect stacktrace from `coredumpctl info`?

**Comment by brendanhoar** [comment] 2020-08-09 16:44
Output of command and lz4 file available. Where do you want them?

**Comment by marmarek** [comment] 2020-08-09 16:50
output you can paste here (perhaps after `<details>` tag). As for lz4, lets see if it will be necessary - if so, you can it my email to me (note, it does contain information about your system like running VMs etc).

**Comment by brendanhoar** [comment] 2020-08-09 16:53
```
           PID: 2904 (xenstored)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-08-09 10:13:29 EDT (2h 27min ago)
  Command Line: /usr/sbin/xenstored --pid-file /var/run/xen/xenstored.pid
    Executable: /usr/sbin/xenstored
 Control Group: /system.slice/xenstored.service
          Unit: xenstored.service
         Slice: system.slice
       Boot ID: 4f42518e80c84dcc89f25e01ad4d5ce3
    Machine ID: 85c4e970558042fcb86db1c001de7cd2
      Hostname: dom0
      Coredump: /var/lib/systemd/coredump/core.xenstored.0.4f42518e80c84dcc89f25e01ad4d5ce3.2904.1596982409000000000000.lz4
       Message: Process 2904 (xenstored) of user 0 dumped core.
                
                Stack trace of thread 2904:
                #0  0x00000000004062b0 handle_event (xenstored)
                #1  0x0000000000402a45 main (xenstored)
                #2  0x00007a4532d2f431 __libc_start_main (libc.so.6)
                #3  0x0000000000402cda _start (xenstored)
```

**Comment by marmarek** [comment] 2020-08-09 16:57
Is that reproducible? I mean, does it happen after (yet another) reboot too?

**Comment by brendanhoar** [comment] 2020-08-09 16:58
Nope, just during the qubes-dom0-update process hang.

**Comment by marmarek** [comment] 2020-08-09 17:04
Found it, seems to be a bug fixed in a newer version already: https://github.com/xen-project/xen/commit/bb2a34fd
Let me backport the fix.

**Comment by brendanhoar** [comment] 2020-08-09 17:05
You're so fast! Thanks!!! :)

**Closed** 2020-08-09 22:11 UTC
Labels: P: default, T: bug
