### ISSUE TITLE
Current application freezes when another (from the same VM) tries to assume focus

### ISSUE THREAD

**Issue by shunju** [QubesOS/qubes-issues#3582] opened 2018-02-13 20:50 UTC
#### Qubes OS version:
R4.0-rc4, possibly other versions as well

#### Affected TemplateVMs: 
debian-9

Probably also other Debian- and Fedora-based templates. However, I did not test with Fedora, because I am not familiar enough with Fedora to install Sublime Text within a reasonable timeframe.

---

### Steps to reproduce the behavior:
Open a LaTeX file in Sublime Text 3 (build 3143 with Package Manager and LaTeXTools installed), open a minimal LaTeX file (e.g. https://gist.github.com/Michael0x2a/e46e12a66b7dc604db5e ), build with pdfLaTeX (press Ctrl+B).

### Expected behavior:
LaTeX file is compiled to PDF, opened in PDF Viewer at the location of the output PDF (roughly) corresponding to the current text cursor position in the editor, focus (optionally) jumps back to Sublime Text. When switching back to the PDF viewer and PDF is scrollable.

### Actual behavior:
LaTeX file is compiled to PDF and opened in PDF Viewer.

evince:
The PDF is opened in evince and can be interacted with until the "sync" message is issued from Sublime Text (i.e. Sublime Text indicates to the PDF viewer which position of the document to jump to). Shortly after the "sync" message is issued (default: 0.5ms delay), Sublime Text tries to assume focus. Due to the nature of Qubes GUI/VM separation, focus remains with the PDF viewer. The PDF viewer freezes and cannot be interacted with, even though the window is active. Clicking on the viewer acts as though clicking on whatever window is below (or the dom0 desktop if no window is below), keyboard input goes to the window that was active before switching to the PDF Viewer. The situation remains like this even when clicking on the Desktop or another window (e.g. Firefox) and returning to the PDF viewer. When jumping back to the PDF viewer, clicks still "go through" the window and keyboard input goes to the last active application (e.g. Firefox). The window frame of the PDF viewer works as expected (window can be resized, moved etc. and resizes content to fit).

okular:
PDF viewer does not open at all. I did not investigate further as to why this is the case.

### General notes:
The bug stated in its current form requires very special circumstances. However, since the same setup does not cause any problems when using plain Debian (instead of running in a Debian-based Qubes VM), I am pretty sure it is related to how Qubes GUI works in some way. It should be possible to generalize a bit and apply to other cases where one program assumes focus and thereby renders another one inoperable.

Quick attempts at reproducing this with other LaTeX editors failed. To my surprise (I remembered differently), I found that TexMaker doesn’t use syncing for external viewers and everything works fine with the embedded viewer. I presume the issue has something to do this the interaction of two different applications running in the same VM.

### Workaround:
In LaTeXTools.sublime-settings, I set keep_focus_delay to 2147483.647 (a little over 35 minutes), effectively preventing Sublime Text from re-assuming focus. Setting it to any higher value than this apparently results in overflow (2147483.647 equals 2^31-1 microseconds) and the freezing issue re-appears.

---

#### Related issues:
Possibly related to #2571.
Probably not related to #1502 and #2177.

**Comment by andrewdavidwong** [comment] 2018-02-14 05:00
Duplicate of #3267

**Comment by andrewdavidwong** [comment] 2018-02-14 05:00
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-14 05:00 UTC
