### ISSUE TITLE
SD card readers are assigned to dom0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4235] opened 2018-08-21 20:36 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Dom0 kernel

---

### Steps to reproduce the behavior:

Look at the dom0 device list and see the SD card reader, along with the block devices on the SD card.

### Expected behavior:

SD card block devices are not assigned to dom0.

### Actual behavior:

SD card block devices are assigned to dom0.

### General notes:

This is a bug for the same reason that Qubes does not (by default) attach USB devices to dom0.

---

### Related issues:

#3802, #2454, #1743

**Comment by andrewdavidwong** [comment] 2018-08-22 04:05
Duplicate of #2454

**Comment by andrewdavidwong** [comment] 2018-08-22 04:05
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-22 04:05 UTC
Labels: R: duplicate
