### ISSUE TITLE
Update to Xfce 4.14

### ISSUE THREAD

**Issue by BawdyAnarchist** [QubesOS/qubes-issues#5330] opened 2019-09-19 05:15 UTC
**Problem:**  Display Issues in dom0 Xfce 4.12 for 4K monitors.

**Description:** I run a Purism 15v4, a 15" 4K monitor with 288 DPI.  Icon, text, and panel do not size or scale well at full screen resolution, even when forcing DPI to true size, and tinkering with all available Window Manager and Appearance settings.  

**Possible Solution:**  The new release of Xfce 4.14 is rumored to have made much progress in the past few years regarding high resolution/DPI monitor. I am *hoping/guessing* that integrating into dom0 could help, since it appears to be the DE causing the odd scaling issues.

**Cui Bono:**  If indeed Xfce 4.14, released in August 2019 solves these issues, it would be nice for Purism laptop users, and anyone with a 4k HiDPI monitor.

**Alternatives** Sometimes I drop my screen resolution, especially if I'm having problems with video playback at fullscreen. I also tried switching to KDE, but it seemed to consume a lot more system resources, and occasionally would freeze.

This is my first post on Github.  Qubes user since 2017.  Just starting to become active in open source communities.  Can't thank you all enough for giving the world such a unique and secure operating system!!

**Comment by esote** [comment] 2019-09-19 19:44
Welcome!

> 14.4

Note that it's 4.14, not 14.4

>  The new release of Xfce 14.4 is rumored to have made much progress in the past few years regarding high resolution/DPI monitor.

Not just rumours: specifically from 4.14's [release notes](https://xfce.org/download/changelogs/4.14)

- HiDPI: Adjust default theme with scale
- HiDPI: Fix menu alignment with scaled UI
- HiDPI: Fix monitor geometry with scaled UI (Bug #14566)
- HiDPI: Fix size increment with scaled UI
- HiDPI: Fix tabwin placement with scaled UI (Bug #14931)
- HiDPI: Use GTK3 scaling attributes for window titles

---

@marmarek @andrewdavidwong I wonder if 4.14 has updates to xfce-screensaver related to #3898?

**Comment by marmarek** [comment] 2019-09-19 19:46
Updating Xfce within R4.0 may be too intrusive change for a _stable_ release. But it's definitely an option for R4.1. Very desirable one.

**Comment by BawdyAnarchist** [comment] 2019-09-19 22:50
> Note that it's 4.14, not 14.4
Thanks, edited.  Glad to see it's on the radar for 4.1!

**Comment by ahimta** [comment] 2019-11-03 23:05
Would definitely be awesome to finally have HiDPI support for XFCE:yum::yum::yum:.

Unfortunately, there doesn't seem to be a way to have HiDPI in XFCE 4.12:sweat_smile:. XFCE 4.12's HiDPI = using larger fonts (font DPI) + using larger icons + using larger panels + using larger titlebar:cry:.

I personally would like it to land as an R4.0 update but think, for many reasons, it's best to stick to 4.12 for R4.0 and 4.14 for R4.1:nerd_face:.

**Comment by 0spinboson** [comment] 2020-02-20 20:39
this seems to me to work fine in Qubes 4.1, so I'd say this could be closed? :)

**Comment by andrewdavidwong** [comment] 2020-02-21 09:41
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-02-21 09:41 UTC
Labels: C: desktop-linux-xfce4, P: major, T: enhancement, release notes
