### ISSUE TITLE
website navigation: change "getting started" -> "get started"

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1868] opened 2016-03-22 23:10 UTC
Same meaning, shorter and more to the point. Also helpful since it's the only two-word navigation and it looks bad on smaller screens (not sure how much shortening it will help).

**Comment by axon-qubes** [comment] 2016-03-22 23:35
Duplicate of #1841.

**Closed by axon-qubes** 2016-03-22 23:35 UTC
Labels: duplicate, UX

**Comment by axon-qubes** [comment] 2016-03-22 23:53
(FWIW, just shortening "Getting Started" to "Get Started" doesn't fix the overhang issue anyway.)

![8](https://cloud.githubusercontent.com/assets/10417133/13971503/aa27e6a0-f088-11e5-8e5d-16eade7f273c.png)
