### ISSUE TITLE
fedora-28 template does not include tar program, causing qubes-dom0-update to fail

### ISSUE THREAD

**Issue by shvenkat** [QubesOS/qubes-issues#4142] opened 2018-07-25 03:36 UTC
### Qubes OS version:
R3.2

### Affected component(s):
`qubes-dom0-update`

---

### Steps to reproduce the behavior:
1. Update to Fedora 28 template.
2. In dom0: `sudo qubes-dom0-update --clean`.

### Expected behavior:
dom0 is updated.

### Actual behavior:

    sh: tar: command not found
    Can not read configuration: /var/lib/qubes/dom0-updates/etc/yum.conf , ignoring
    Unable to detect release version (use `--releasever` to specify release version)
    Can not read configuration: /var/lib/qubes/dom0-updates/etc/yum.conf , ignoring
    0 files removed
    Checking for dom0 updates...
    Can not read configuration: /var/lib/qubes/dom0-updates/etc/yum.conf , ignoring
    Unable to detect release version (use `--releasever` to specify release version)
    Can not read configuration: /var/lib/qubes/dom0-updates/etc/yum.conf , ignoring
    Error: There are no enabled repos.

**Comment by andrewdavidwong** [comment] 2018-07-25 04:20
Duplicate of #4032

**Comment by andrewdavidwong** [comment] 2018-07-25 04:20
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-07-25 04:20 UTC
