### ISSUE TITLE
Qubes Devices widget silently fails to attach dom0:mic / USB webcam / block device

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#5131] opened 2019-06-28 22:55 UTC
**Qubes OS version**
R.4.0.1

**Affected component(s) or functionality**
Qubes Devices widget

**Brief summary**
Attaching the dom0:mic or USB device or block device to a qube via the Qubes devices widget doesn't do anything.  Once a qube has had a dom0:mic/USB device/block device attached to it via the commandline, the Qubes devices widget appears to work as expected for that qube.

**To Reproduce**
Create a new qube, start it, and attempt to attach mic/usb device/block device using the GUI Qubes devices widget.

**Expected behavior**
User should be able to use the Qubes devices widget to attach dom0:mic or USB device (e.g. webcam) or block device to a qube.

**Actual behavior**
Hovering over the device then selecting `+ my-videoconference-qube' doesn't do anything. 

**Additional context**
1. Attaching from the commandline appears to correctly update the Qubes devices widget (showing the relevant devices attached to the correct qubes). 
2. not sure if relevant or whether even a bug, but no `*Attaching device*` or `*Detaching device*` desktop notifications appear when using the commandline.

**Solutions you've tried**
Once the user has attached a dom0:mic/USB device/block device *to a specific qube* using the commandline (e.g.from a dom0 terminal `qvm-devices mic a` or `qvm-usb a` or `qvm-block a`) the Qubes devices widget appears to work correctly from then on.  This survives a restart of the qube (not sure about a restart of the system, I'm not able to test that at the moment).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment] 2019-06-29 00:46
Looks like a duplicate https://github.com/QubesOS/qubes-issues/issues/4999
A fix is already available in current-testing repository: https://github.com/QubesOS/updates-status/issues/1177

**Comment by marmarek** [comment] 2019-06-29 00:47
Duplicate of #4999

**Closed by marmarek** 2019-06-29 00:47 UTC
Labels: P: default, T: bug
