### ISSUE TITLE
qvm-copy-to-vm unexpressive error message if argument are inverted

### ISSUE THREAD

**Issue by Mayeu** [QubesOS/qubes-issues#3086] opened 2017-09-08 07:58 UTC
#### Qubes OS version (e.g., `R3.2`):

R4-rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Not sure if applicable, but all my test happened in AppVM using fedora-25

---

### Expected behavior:

When running `qvm-copy-to-vm` with the wrong argument, eg. `qvm-copy-to-vm $file $toVM` instead of `qvm-copy-to-vm $toVM $file`, the tool should error out saying something like:
```
Error: no file or directory named $toVM found
usage: qvm-copy-to-vm [--without-progess] dest_vmname file [file...]
```

### Actual behavior:

The only error showned is:
```
Request refused
```

The result is that you end-up digging into your policy to understand why on earth you can't send something from this VM when the policy clearly state `$any $any ask` :)

### Steps to reproduce the behavior:

1. Invert the argument in `qvm-copy-to-vm`

**Comment by cartman4** [comment] 2018-03-15 17:35
I cant copy or move any files to other VMs since the last update (tried current-testing which seams to be RC-5 now and a the dom0-current repo of RC-4) i only get `Request refused` message when trying from terminal or nothing happens if i try it using the GUI

**Comment by unman** [comment] 2018-03-15 17:42
On Thu, Mar 15, 2018 at 10:35:05AM -0700, cartman4 wrote:
> I cant copy or move any files to other VMs since the last update (tried current-testing which seams to be RC-5 now and a the dom0-current repo of RC-4) i only get `Request refused` message when trying from terminal or nothing happens if i try it using the GUI
> 

Have a look at the policy file in /etc/qubes-rpc/policy and make sure
that the qube you are using is covered there.

**Comment by CrsiX** [comment] 2021-04-07 21:42
I think this issue can be closed.

When I use e.g. `qvm-copy-to-vm [existing file] [existing domain]` I get a pop-up window stating: `qfile-dom0-agent: stat [existing domain] (error type: No such file or directory)`
Additionally, in the console window, the response is `qvm-run: error: no such domain: '[existing file]'` and the exact usage string for the `qvm-copy-to-vm` tool.

In the rare case that the file name equals the domain name, the command works as expected and copies such a file to the targeted domain.

Tested on Qubes 4.0.4.

**Comment by andrewdavidwong** [comment] 2021-04-08 10:47
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-04-08 10:47 UTC
Labels: C: core, P: default, T: bug
