### ISSUE TITLE
DVD image doesn't fit on a DVD

### ISSUE THREAD

**Issue by aerth** [QubesOS/qubes-issues#1568] opened 2015-12-31 07:33 UTC
Just tried with [Qubes-R3.1-rc1-x86_64-DVD.iso](https://www.qubes-os.org/downloads/#qubes-release-31-release-candidate)

Because it is not the stable release? Why is DVD in the iso name? its a usb image? Thanks

**Comment by marmarek** [comment] 2016-01-03 21:21
This is one of problems mentioned in release notes:
https://www.qubes-os.org/doc/releases/3.1/release-notes/

Not yet decided what we want to do about this. The problem is mainly because of total four templates:
 - Fedora 23
 - Debian 8
 - Whonix-gateway
 - Whonix-workstation

So, basically four full systems (plus dom0)...

**Comment by aerth** [comment] 2016-01-05 03:59
Okay I read the release notes since posting. Thank you for a great thing!

Maybe just rename the .iso according to the medium it should be placed on. One of the FAQ when downloading *any* OS is ```which .iso should I download?```. 

I'm going to close this, as it is mentioned in release notes.

**Comment by axon-qubes** [comment] 2016-04-13 00:37
IMHO, this should be reopened until a firm decision is made.

I am in favor of making the installation image fit on a (single-layer) DVD. One technical solution is to create a "net-based" installation like Fedora (and many other distros) do, where necessary files are downloaded on-the-fly as part of the installation process.

In the case of Qubes, perhaps a similar option is to exclude certain templates from the image, then ask the user during the installation process (or on first startup after installation) whether the user wants those excluded templates. If so, download and install them.

**Comment by axon-qubes** [comment] 2016-04-13 01:08
#1507 is possibly a duplicate of this issue.

(Why would #1507 of this and not the other way around? Because #1507 is much more specific and focuses on only one possible way of making the total image smaller. IIUC, making the Fedora template smaller is not the only way to make the total Qubes installation image smaller. See previous comment.)

**Comment by rootkovska** [comment] 2016-06-29 09:11
Is this gonna be still the problem after we remove all the KDE from the installation ISO? cc @marmarek

**Comment by marmarek** [comment] 2016-06-29 09:29
Currently image is about 100MB bigger than DVD, so I hope it will fit
after dropping KDE :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment] 2016-07-31 11:01
Yes, it fits.

**Closed by marmarek** 2016-07-31 11:01 UTC
Labels: P: major

**Comment by R030t1** [comment] 2020-03-26 18:59
This is relevant again

**Comment by marmarek** [comment] 2020-03-26 19:42
We no longer target single-layer DVD medium, see https://www.qubes-os.org/doc/installation-guide/#copying-the-iso-onto-the-installation-medium
You can use dual-layer DVD, or simply USB stick large enough.
