### ISSUE TITLE
VirtualBox video driver not found in R3.2

### ISSUE THREAD

**Issue by egberts** [QubesOS/qubes-issues#2347] opened 2016-09-29 23:31 UTC
#### Inside a VIrtualBox 5.1.6

---

### Expected behavior:
Anaconda Graphical installer appears

### Actual behavior:
Anaconda installer appears in text-mode.

### Steps to reproduce the behavior:
Fresh install a Qubes 3.2 x86_64
inside VirtualBox 5.1.6
with 128MB video,
2 CPU,
32 GB storage
 
### General notes:
I noticed that other issue regarding inability to install in Anaconda text-mode due to lack of password prompt for its required LUKS support.
<img width="956" alt="qube" src="https://cloud.githubusercontent.com/assets/10352354/18975846/200e2400-867b-11e6-9060-03406dae5df1.png">

---

**Comment by egberts** [comment] 2016-09-29 23:32
This problem occurs before #1161

**Comment by andrewdavidwong** [comment] 2016-09-30 09:47
Effective duplicate of #1340. We don't support installing Qubes OS inside a VM:
https://www.qubes-os.org/doc/user-faq/#can-i-install-qubes-in-a-virtual-machine-eg-on-vmware

**Closed by andrewdavidwong** 2016-09-30 09:47 UTC
