### ISSUE TITLE
Qubes Manager - sometimes does not reflect changes in some qube properties

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5587] opened 2020-01-19 03:30 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes Manager

**To Reproduce**
change color
change type to DispVM

**Expected behavior**
reflect change

**Actual behavior**
sometimes No change

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/3675

**Comment by andrewdavidwong** [comment] 2020-01-19 22:22
Duplicate of #3675

**Comment by andrewdavidwong** [comment] 2020-01-19 22:22
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-01-19 22:22 UTC
Labels: P: default, T: bug
