### ISSUE TITLE
AppVMs based on Debian (7 & 8) templates fail to open application windows

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1027] opened 2015-06-11 15:43 UTC
see mention in email thread:
https://groups.google.com/d/msgid/qubes-users/5578070E.7080801%40gmail.com

> It sounds like it is related to a problem some of us are having in
> Debian 8: The same org.gnome.SessionManager error when trying to run
> nautilus, and the window may not appear (especially if you run it from
> the launcher menu).
> 
> However, if you run nautilus from terminal it should start the gnome
> SessionManager service before opening the window. So if you keep a
> nautilus window open while testing gnome-keyring functions you may find
> that it works. 

I can verify this issue, and have encountered this with both Debian 7 and Debian 8 templates. For Debian 8-based AppVMs, even the terminal will not appear when chosen, rendering Debian 8-based AppVMs unusable.

**Comment by marmarek** [comment] 2015-06-11 16:12
R2 or R3?
In case of R3 check packages in testing repository (uncomment
appropriate line in /etc/apt/sources.list.d/qubes-r3.list).

You should be able to start xterm if gnome-terminal is not working.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment] 2015-06-11 16:19
R3, great thanks for the heads-up.

**Comment by faern** [comment] 2015-07-08 14:20
If the issue is that you can't open gnome-terminal but xterm works fine, it's probably a locale problem. Try starting xterm and from there start gnome-terminal. If it's complaining about locales run this in your debian-8 template:

    $ sudo dpkg-reconfigure locales

Find and select ```en_US.UTF-8``` or whatever you want to use, on the next screen use the same locale as default. After this you should be able to run applications directly.

**Comment by marmarek** [comment] 2015-07-23 20:21
Duplicate of #1033

**Closed by marmarek** 2015-07-23 20:21 UTC
Labels: bug, C: core, C: Debian, duplicate
