### ISSUE TITLE
Dom0 update error: problem with installed package xorg-x11-drv-intel, nothing provides libXss.so.1()(64bit)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6428] opened 2021-02-25 21:57 UTC
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

dom0 update

**Brief summary**

Package error when attempting to update dom0.

**How Reproducible**

100%

**To Reproduce**

`sudo qubes-dom0-update`

**Expected behavior**

Normal dom0 update.

**Actual behavior**

```
$ sudo qubes-dom0-update
Using sys-update as UpdateVM to download updates for Dom0; this may take some time...
Qubes Dom0 Repository (updates)                 213 kB/s | 1.0 MB     00:04    
Qubes Dom0 Repository (security-testing)        459 kB/s | 2.9 MB     00:06    
determining the fastest mirror (15 hosts).. done..8 kB/s | 2.7 kB     00:00 ETA
Qubes Templates repository                      770  B/s | 6.2 kB     00:08    
Error: 
 Problem: problem with installed package xorg-x11-drv-intel-2.99.917-32.20171025.fc25.x86_64
  - cannot install the best update candidate for package xorg-x11-drv-intel-2.99.917-32.20171025.fc25.x86_64
  - nothing provides libXss.so.1()(64bit) needed by xorg-x11-drv-intel-2.99.917-49.20210126.fc25.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Solutions you've tried**

None. Unsure if using '--skip-broken' is a good idea in this case.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by marmarek** [comment] 2021-02-25 22:04
Duplicate of #6380

**Closed by marmarek** 2021-02-25 22:04 UTC
Labels: C: updates, P: default, T: bug, needs-diagnosis
