### ISSUE TITLE
Persistent qrexec policy daemon

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3868] opened 2018-04-29 20:59 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-admin

---

### Steps to reproduce the behavior:

1. Run `qvm-ls`
2. Note the time it takes

### Expected behavior:

`qvm-ls` is fast

### Actual behavior:

`qvm-ls` is slow

### General notes:

The problem seems to be that every qrexec call starts a new Python process.  I propose that this be replaced by a persistent daemon.  The daemon will listen on a Unix domain socket and maintain an in-memory cache of all qrexec policy files.  `inotify` will be used to notify the daemon when these change.  Additionally, whenever the machine is awake, the daemon will reload its configuration every minute or so, to ensure that it stays up-to-date.

---

**Comment by marmarek** [comment] 2018-04-29 22:43
Do you mean `qvm-ls` in dom0 or in some VM (with appropriate permissons for qrexec calls)? In case of dom0, it already use local socket and qrexec policy is not involved at all. But in case of VM, your diagnosis is correct.

Generally:
 - the idea you propose is good (with slightly different details about updating the info), this is what we plan to implement when time allows
 - this is a duplicate of https://github.com/QubesOS/qubes-issues/issues/3293#issuecomment-353750084, lets move the discussion there

**Closed by marmarek** 2018-04-29 22:43 UTC

**Comment by andrewdavidwong** [comment] 2018-04-30 03:11
Duplicate of #3293

**Comment by DemiMarie** [comment] 2018-04-30 17:25
I actually have the problem when making the calls from dom0.  They are
still slow.

**Comment by marmarek** [comment] 2018-04-30 17:30
Ok, but in case of dom0, qrexec policy is not involved at all.
