### ISSUE TITLE
Booting stuck at efi loader

### ISSUE THREAD

**Issue by NinjaTurtle007** [QubesOS/qubes-issues#3346] opened 2017-11-28 17:46 UTC
#### Qubes OS version:

4 rc3 

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:
1. make bootable usb drive
2. boot it

### Expected behavior:
to load the installer

### Actual behavior:

[https://imgur.com/a/KJg2f](url)

### General notes:

I've installed the very same way qubes 4 rc2 several times and rc3 once. 
However, the second time I tried to install rc3 from the same usb drive on the same computer it's indifinitely stuck at the screen linked above.

I tried another flash drive, remaking the iso on this one and nothing. It just doesn't want to boot it anymore.
Everything else is the same

---

**Comment by zander** [comment] 2017-11-28 22:37
I never managed to get past the grub screen on R2 using EFI. Unly when turning on the legacy boot in my bios did it boot. Same for the actual installed qubes OS afterwards.

Can you say if the USB pen boots after changing your bios to boot it as a legacy pen?

ps. Maybe someone can edit the bugreport, the url got its title and link reversed.

**Comment by zander** [comment] 2017-11-28 22:39
May be a duplicate of #3340

**Comment by andrewdavidwong** [comment] 2017-11-29 04:52
This appears to be a duplicate of #3340. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-11-29 04:52 UTC
