### ISSUE TITLE
Building Xenial 

### ISSUE THREAD

**Issue by lededje** [QubesOS/qubes-issues#4944] opened 2019-04-02 21:47 UTC
R4.0

Qubes-builder

**Brief summary**
When making Xenial build complains of missing release files:

```
Reading package lists...
W: The repository 'https://deb.qubes-os.org/r4.0/vm xenial Release' does not have a Release file.
E: Failed to fetch https://deb.qubes-os.org/r4.0/vm/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100
```

**To Reproduce**
In a fedora-29 image:
```
sudo dnf install git createrepo rpm-build make wget rpmdevtools dialog rpm-sign gnupg dpkg-dev debootstrap python2-sh perl-Digest-MD5 perl-Digest-SHA
wget https://keys.qubes-os.org/keys/qubes-master-signing-key.asc
gpg --import qubes-master-signing-key.asc 
gpg --edit-key 36879494
fpr
trust
5
y
q
wget https://keys.qubes-os.org/keys/qubes-developers-keys.asc
gpg --import qubes-developers-keys.asc
git clone git://github.com/QubesOS/qubes-builder.git
cd qubes-builder
git tag -v `git describe`
mkdir -p keyrings/git
./setup
Yes
Yes
4.0
Stable
Yes
Select builder-fedora and builder-debian
Yes
Select only xenial
make install-deps
make get-sources
make qubes-vm
```

**Expected behavior**
An Ubuntu image to be built

**Actual behavior**
An error thrown (see above)

**Screenshots**
N/A

**Additional context**
N/A

**Solutions you've tried**
Looking through makefiles, but they are alien to me.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/templates/ubuntu/
https://www.qubes-os.org/doc/qubes-builder/
https://www.qubes-os.org/doc/qubes-r3-building/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

**Comment by marmarek** [comment] 2019-04-02 22:11
Duplicate of #4907

**Closed by marmarek** 2019-04-02 22:11 UTC
Labels: P: default, T: bug
