### ISSUE TITLE
Keyboard input goes to incorrect window

### ISSUE THREAD

**Issue by homotopycolimit** [QubesOS/qubes-issues#4089] opened 2018-07-16 14:47 UTC
### Qubes OS version:
4.0

### Affected component(s): 

I believe it is the window manager.

---

### Steps to reproduce the behavior:

I have been using the cinelerra video editor. Specifically cinelerra-5.1-debian9-20180630.x86_64-static.txz from https://cinelerra-cv.org/five/tars/.

The first strange thing I noticed is that when I have the program running and I have another window in front of it (even if the window in front has focus) sometimes the commands are sent to cinelerra instead.

I have since learned that this bug also goes across workspaces. For example I found myself unable to fill in the bug report in this browser (on workspace 1) until I closed cinelerra on workspace 2. The 'K' in the title of this report was sent to cinelerra.

This behaviour has been erratic and hard to pin down but it is consistently happening.
I do not know what is causing it, nor where to look. For me it is a nuisance, but it could point to a more serious issue. After all, input should never be redirected to the wrong window.

### General notes:

I apologise that I do not have more specific instructions. As I said, the behaviour seems somewhat erratic - or maybe I just haven't figured out the triggers.

---

**Comment by andrewdavidwong** [comment] 2018-07-17 00:12
Duplicate of #3267

**Comment by andrewdavidwong** [comment] 2018-07-17 00:12
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-07-17 00:12 UTC
