### ISSUE TITLE
fedora-26-minimal not working as either sys-net or sys-firewall

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#3443] opened 2018-01-03 21:24 UTC
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

fedora-26-minimal

---

### Steps to reproduce the behavior:

1. install fedora-26-minimal template from dom0 terminal: `sudo qubes-dom0-update qubes-template-fedora-26-minimal `
2. clone fedora-26-minimal to f26-min-net from dom0 terminal: `qvm-clone fedora-26-minimal f26-min-net`
3. install packages needed to make a suitable netVM template (following [instructions for fedora-25-minimal](https://www.qubes-os.org/doc/templates/fedora-minimal/)): `sudo dnf install NetworkManager network-manager-applet dbus-x11 dejavu-sans-fonts tinyproxy notification-daemon gnome-keyring`
4. set sys-net template to f26-min-net
5. set sys-firewall template to fedora-26-minimal
6. restart sys-net and sys-firewall 

### Expected behavior:

we connect to the Internet!

### Actual behavior:

* if **either** sys-net or sys-firewall (see below for tested combinations) uses fedora-26-minimal or f26-min-net, sys-net appears to make an Internet connection (tray icon) but no appVMs (nor `qubes-dom0-update`, nor sys-whonix) can connect to the Internet)

### General notes:

* this is on a desktop system (ethernet only) so NetworkManager-wifi and wireless-tools were omitted
* fedora-26 (not minimal) works as sys-net and sys-firewall

sys-net | sys-firewall | web (appVM) | dom0-updates  | WhonixCheck
--------- | -------------- | ----------------- | ------------------ | -----------------
f26-min-net   |    fedora-26-minimal   |    NO           |       NO        |       NO
f25-min-net  |     fedora-25-minimal   |    **yes!**     |   **yes!**    |     **yes!**
f26-min-net  |     fedora-25-minimal  |     NO          |      NO         |        NO
f25-min-net   |    fedora-26-minimal |      NO           |     yes (?)       |        NO
fedora-26     |    fedora-26               |      **yes!**      |      **yes!**      |         **yes!**
fedora-26    |     fedora-26-minimal    |   NO            |       yes (?)         |             NO
f26-min-net   |    fedora-26            |        NO            |        NO                |            NO

---

#### Related issues:

#3429

**Comment by mossy-nw** [comment] 2018-01-04 05:15
thanks, andrewdavidwong, for pointing to this comment by rusty bird who indicates manual install of iptables package might be needed for the fresh templates -- https://groups.google.com/forum/#!topic/qubes-users/pD4KV9hOYhQ/discussion -- I will test to see if this works and post back here.

**Comment by mossy-nw** [comment] 2018-01-04 07:29
manually installing iptables to both the sys-net and sys-firewall templateVMs fixes the issue:
`$ sudo dnf install iptables` 

thanks, David for digging up the relevant qubes-users threads!

**Comment by andrewdavidwong** [comment] 2018-01-05 04:08
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-01-05 04:08 UTC
Labels: bug, C: Fedora

**Comment by evilaliv3** [comment] 2019-06-23 14:18
@andrewdavidwong : I accidentally upgraded my default from  fedora 29  to fedora-28 minimal and only now discovered that it do not contain the relevant packages for running net. This took me in a stuck situation where I cannot use the system. Is there any easy solution for this situation? Thank you!
