### ISSUE TITLE
video/audio syncing lag 

### ISSUE THREAD

**Issue by vieladams** [QubesOS/qubes-issues#4640] opened 2018-12-20 02:50 UTC
### Qubes OS version:

Qubes release 4.0  (R4.0)

### Affected component(s): 

dom0

---

### Steps to reproduce the behavior:

* open any video player or mp3 player
* watch youtube videos
* Browser websites 

### Expected behavior:

using the videos normally and using mp3 player without causing the whole system to lag 

### Actual behavior:

using any video/mp3 player cause the system to have a heavy lag, and even using a browser to surf websites normally can cause the system to be slower and watching youtube or any videos online is impossible without lagging even with 240p quality 

### General notes:

device information :
System:    
Host: dom0 Kernel: 4.14.74-1.pvops.qubes.x86_64 x86_64 bits: 64 Desktop: i3 4.16
Distro: Qubes release 4.0 (R4.0)

Machine:   
Device: laptop System: Dell product: Inspiron 5558 
UEFI [Legacy]: Dell v: A01 date: 02/09/2015

CPU:       
Dual core Intel Core i5-5200U (-MCP-) cache: 3072 KB
clock speeds: max: 2194 MHz 1: 2194 MHz 2: 2194 MHz

Graphics:  
Card-1: Intel HD Graphics 5500
Card-2: NVIDIA GK208M [GeForce 920M]
Display Server: x11 (X.org 1.19.3 ) drivers: nouveau,intel (unloaded: modesetting,fbdev,vesa)
Resolution: 1366x768@60.00hz
OpenGL: renderer: N/A version: N/A

---

### Attachments 
[Xorg.0.log](https://github.com/QubesOS/qubes-issues/files/2697220/Xorg.0.log)

**Comment by DemiMarie** [comment] 2018-12-20 20:48
Which VM is this in?

**Comment by vieladams** [comment] 2018-12-21 00:21
the VM that i was using based on fedora-28 templates
I have tested it out in different using different templates and their AppVm like debian-9, whonix-14 and i had the same results

**Comment by andrewdavidwong** [comment] 2018-12-21 00:48
Duplicate of #3622

**Comment by andrewdavidwong** [comment] 2018-12-21 00:48
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-12-21 00:48 UTC
