### ISSUE TITLE
PDF converter does not work in 4.0

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4184] opened 2018-08-05 11:23 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

qubes.PdfConvert

---

### Steps to reproduce the behavior:
Attempt to convert untrusted PDF

### Expected behavior:

Converts to trusted PDF

### Actual behavior:

Fails with Request refused

### General notes:

Both Debian and Fedora templates affected.
Relevant policy seems to be set fine.

---

**Comment by andrewdavidwong** [comment] 2018-08-05 21:15
Duplicate of #3818

**Comment by andrewdavidwong** [comment] 2018-08-05 21:15
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-05 21:15 UTC
