### ISSUE TITLE
Thunderbird doesn't see thunderbird-qubes plugin anymore

### ISSUE THREAD

**Issue by mycase** [QubesOS/qubes-issues#5355] opened 2019-09-28 17:08 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes Thunderbird plugin

**Brief summary**
While using thunderbird, menu options relating to the qubes ("Send to VM", etc) thunderbird are not displayed.

**To Reproduce**
_Steps to reproduce the behavior:_

_1. Make sure packages are still there:_
[user@mail30 ~]$ rpm -qa | grep -i thunderbird
thunderbird-enigmail-2.0.8-3.fc30.noarch
thunderbird-68.1.0-1.fc30.x86_64
thunderbird-qubes-1.2.13-1.fc30.noarch
_2. In thunderbird, right mouse-click on attached document: A menu appears._

**Expected behavior**
_The Send-to-VM option is usually displayed in the context menu._

**Actual behavior**
_No such option is now visible._

**Screenshots**

**Additional context**
_Similar issue with the enigmail plugin: Thunderbird doesn't recognise gpg mail._

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_"Not all extensions will be supported in Thunderbird 68", https://www.ghacks.net/2019/05/21/not-all-extensions-will-be-supported-in-thunderbird-68/ ._

**Comment by marmarek** [comment] 2019-09-28 17:58
Duplicate of #5318

**Closed by marmarek** 2019-09-28 17:58 UTC
Labels: P: default, T: bug
