### ISSUE TITLE
VMs show as needing upgrade after upgrade

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3883] opened 2018-05-06 02:54 UTC
### Qubes OS version:

4.0

### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

In the Qubes Manager you see a down arrow and you upgrade the VM.  You refresh the Qubes Manager list and the arrow is still there.

### Expected behavior:

After you upgrade the VM, the arrow should disappear.  Absolutely it should disappear after refreshing the Qubes Manager

### Actual behavior:

The arrow does not disappear sometimes.  If there is a pattern to when it works and when it doesn't I don't know it.

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-05-06 06:32
Duplicate of #2009

**Comment by andrewdavidwong** [comment] 2018-05-06 06:32
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-05-06 06:32 UTC
