### ISSUE TITLE
Require encryption password regularly

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6553] opened 2021-04-23 08:35 UTC
**The problem you're addressing (if any)**
If the computer is not turned off, it has disk decryption information in memory and that could potentially be stolen from RAM by advanced electronic means.

Turning it off often is not convenient for the user as it increased the system resume time.

**Describe the solution you'd like**
Unmount the LUKS disk regularly (pausing normal operations of the system) and ask for the encryption password again to resume normal operations.

**Where is the value to a user, and who might that user be?**
Anyone with secrets costly or dangerous enough for an attacker to pay for reading the RAM without turning it off.

**Describe alternatives you've considered**
Turn it off often.

Process sensitive data in memory without ever deciphering.  (I don't remember a cryptographic term, but the theorem that that's possible (I think, in the assumption that P!=NP) does exist) processing data in memory without deciphering even temporarily (so the data remains ciphered even in CPU registers). This solution seems inefficient and any ciphers that allow processing without deciphering are less "secure" (I don't know the details) than usual ciphers. But this second solution may be the most secure (but that doesn't matter much for desktop systems where secret data could be seen on the screen during the work, anyway).

**Additional context**
It pauses the OS and user processes (including security updates). So it should be done only for some of partions, these including sensitive data. In turn this requires enhancing the basic security model: have a secret (LUKS) and non-secret partitions rather just a LUKS partition.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment] 2021-04-23 08:45
Duplicate of #2890

**Comment by andrewdavidwong** [comment] 2021-04-23 08:45
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2021-04-23 08:46
@vporton, please thoroughly search the existing issues before opening any new ones.

**Closed by andrewdavidwong** 2021-04-23 08:46 UTC
Labels: P: default, T: enhancement
