### ISSUE TITLE
USB devices do not work after suspend unless sys-usb is restarted

### ISSUE THREAD

**Issue by ekaflaer** [QubesOS/qubes-issues#4520] opened 2018-11-18 14:42 UTC
### Qubes OS version:
4.0

### Affected component(s): 
USB

---

### Steps to reproduce the behavior:
1. Start Qubes-OS
2. Attach USB Stick
3. Check if it shows up 
4. Remove USB Stick
5. Suspend
6. Resume
7. Add USB Stick again
8. Check if it shows up

### Expected behavior:

USB stick connection is shown in the notification and it is possible to attach the device to a VM.

### Actual behavior:

The USB stick connection only works directly after start. After the suspend it is not shown anymore.

### General notes:

Restarting the sys-usb vm fixes the issue until the next vm. So there is a work around but it is not nice. The issue did not appear in Qubes OS 3.2 or at least somwhere around this time.
It happened to me all the time with version 4.

Let me know how to debug it further or if you need any additional information.

**Comment by andrewdavidwong** [comment] 2018-11-18 23:04
Duplicate of #4042

**Comment by andrewdavidwong** [comment] 2018-11-18 23:04
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-11-18 23:04 UTC
