### ISSUE TITLE
USB Not Working

### ISSUE THREAD

**Issue by NicWow** [QubesOS/qubes-issues#3950] opened 2018-06-01 18:19 UTC
### Qubes OS version:

This picture should explain itself:

![usbnotworkingscreenshot](https://user-images.githubusercontent.com/26805521/40856644-72fccdae-658d-11e8-8550-e3184d984103.png)

But basically, I need to add some files to USB and it just won't connect. Can some plz help me?
Thanks in advance!

Edit: Screenshot doesn't seem to work either but basically I attached the USB to my AppVM "Firefox" and if i open folders in other locations it doesn't appear.The AppVM's template is Fedora26.

Edit2: I also made a reddit thread because I coudn't figure out how to download apps and have some error messages you can view them here: https://www.reddit.com/r/Qubes/comments/8nf2t6/how_to_download_3rd_part_apps/ and here https://www.reddit.com/r/Qubes/comments/8noffo/how_to_delete_apps_and_files_in_qubes_os/

### Affected component(s): 

---

### General notes:

---

**Comment by NicWow** [comment] 2018-06-02 00:45
I think I got it working. When I plug in the USB 2 instances show up one appears as "sys-net:sda - USB_2.0_FD ()" the other one is "sys-net:sda1 - USB_2.0_FD (MY-USB)" "MY-USB" was what I named the USB and was the one I attached. The other one removes when I attached one to a Qube. "sys-net:sda - USB_2.0_FD ()" shows up in "other locations" as My-USB while the other one doesn't work. 
Although I believe this is solved this is still a bit of an issue as it is very hard for the user to figure out how to add USBs.

**Comment by andrewdavidwong** [comment] 2018-06-02 06:10
> Although I believe this is solved this is still a bit of an issue as it is very hard for the user to figure out how to add USBs.

This should be addressed here:

https://www.qubes-os.org/doc/usb/

If you believe something is missing, please provide specifics.

Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-06-02 06:10 UTC
