### ISSUE TITLE
Backport Xen 4.9 Fixes for TSX on Haswell/Broadwell Intel CPUs

### ISSUE THREAD

**Issue by elliotkillick** [QubesOS/qubes-issues#5848] opened 2020-05-25 19:01 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Xen hypervisor

**Brief summary**
The current version of Xen used in Qubes is 4.8. This version lacks important TSX fixes for Intel CPUs based on the Haswell and Broadwell microarchitectures resulting in potential domain instability.

See this thread on the xen-devel mailing list for all the info:
https://lists.xenproject.org/archives/html/xen-devel/2020-05/msg01235.html

Looking back historically on my `hypervisor.log` files, this has been causing domains to unexpectedly crash on me for some time now, although it only ever seems to happen with HVMs.

**To Reproduce**
Please see the mailing list thread.

**Expected behavior**
Xen should not be put into an unstable state causing `domain_crash()` to be called.

**Actual behavior**
The domain may be forced to crash.

**Additional context**
Andrew offered to point out a set of minimum backports to make this work. So should this be deemed worthy of a backport, it should be a fairly straightforward process.

**Comment by marmarek** [comment] 2020-05-26 22:12
I've identified those two (commit ids from stable-4.9 branch):
xen-project/xen@d6e9f8d4f35d938417f9dc2ea50f6e8004e26725 x86/vmx: fix vmentry failure with TSX bits in LBR
xen-project/xen@1b0029cf6d07f2bd49ac57022274c903472af820 x86/vmx: Fix vmentry failure because of invalid LER on Broadwell

@andyhhp

**Comment by andyhhp** [comment] 2020-05-26 22:24
I was going to put you together some backports including the subsequent bugfixes to those two.

**Comment by andyhhp** [comment] 2020-05-27 23:54
Right, https://xenbits.xen.org/gitweb/?p=people/andrewcoop/xen.git;a=shortlog;h=refs/heads/qubes-4.8-tsx-vmentry top 4 patches.  Alternatively https://github.com/andyhhp/xen/compare/staging-4.8...andyhhp:qubes-4.8-tsx-vmentry which github seems to be happier with.

One substantially complicating factor is that one of the intermediate bugfixes was backported as an XSA prerequisite, and implemented differently.

As for testing, there is a dedicated unit test for this problem, available https://xenbits.xen.org/docs/xtf/test-lbr-tsx-vmentry.html but you'll need Haswell/Broadwell hardware for the errata precondition.

This does not include https://lore.kernel.org/xen-devel/c43b9d43-2e37-d2a8-ba32-dd06062a05e2@suse.com/ which is a bugfix to the Broadwell side affected model list, as it hasn't been committed yet (awaiting a VT-x ack).

**Comment by andyhhp** [comment] 2020-05-28 10:42
Good news.  The Broadwell fix has been committed.  I've refreshed the branch andyhhp/xen@staging-4.8...andyhhp:qubes-4.8-tsx-vmentry, now 5 patches.

**Comment by marmarek** [comment] 2020-05-28 13:13
Thanks! I can confirm the test fails before applying the patches and succeed with them. I'll upload the update to current-testing shortly.

**Closed** 2020-05-28 14:18 UTC
Labels: P: default, T: bug
