### ISSUE TITLE
Notification when out of storage per qube

### ISSUE THREAD

**Issue by bakeromso** [QubesOS/qubes-issues#7090] opened 2021-11-27 16:26 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

I was trying to copy something from one VM to another, when I got the error
```
qfile-unpacker: Fatal error: Error chdir to /home/user/QubesIncoming/[AppVM] (error type: No such file or directory)
```

I tried to create the folder manually in the destination qube, but only then I figured out that there was no storage left in the destination qube. This case, the problem was identified rather quickly, but I can imagine other cases where it might not be quickly evident that the root cause is the lack of storage in a qube.

### The solution you'd like
Any way that the user is notified when storage is running out per qube, either for the system storage or the user storage. This could be as a notification through the "Qubes Disk Space Monitor" tool, which I think might be the easiest to implement. An alternative would be to change error messages that are given to the user to incorporate the heads up that the storage space has (also) run out.

**Comment by marmarek** [comment] 2021-11-27 22:19
Duplicate of https://github.com/QubesOS/qubes-issues/issues/1053

**Comment by marmarek** [comment] 2021-11-27 22:20
This feature is already present in Qubes 4.1.

**Closed by marmarek** 2021-11-27 22:19 UTC
Labels: T: enhancement, P: default

**Comment by bakeromso** [comment] 2021-11-28 08:17
> This feature is already present in Qubes 4.1.

I don't understand. I'm on 4.1, so must I have missed such notification?

**Comment by marmarek** [comment] 2021-11-28 13:16
Yes, similar to running out of space in dom0 (or rather, individual storage pool). You can also click on the disk space widget to see warnings.
