### ISSUE TITLE
Appmenu entries for named DispVMs try to create a DispVM based on a DispVM

### ISSUE THREAD

**Issue by theperelomov** [QubesOS/qubes-issues#6683] opened 2021-06-09 09:51 UTC
**Qubes OS version**

R4.1 weekly builds

**Affected component(s) or functionality**

XTerm

**To Reproduce**

1.  Open Xfce appmenu
2.  Click Disposable: sys-firewall/sys-net
3.  Click XTerm

**Expected behavior**

I see XTerm

**Actual behavior**

I didn`t see XTerm

**Additional context**

From journalctl
```
Jun 09 12:43:43 dom0 qubesd[2882]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.CreateDisposable' dest=b'sys-firewall' arg=b'' len(untrusted_payload)=0
Jun 09 12:43:43 dom0 qubesd[2882]: Traceback (most recent call last):
Jun 09 12:43:43 dom0 qubesd[2882]:   File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 286, in respond
Jun 09 12:43:43 dom0 qubesd[2882]:     response = yield from self.mgmt.execute(
Jun 09 12:43:43 dom0 qubesd[2882]:   File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1192, in create_disposable
Jun 09 12:43:43 dom0 qubesd[2882]:     dispvm = yield from qubes.vm.dispvm.DispVM.from_appvm(dispvm_template)
Jun 09 12:43:43 dom0 qubesd[2882]:   File "/usr/lib/python3.8/site-packages/qubes/vm/dispvm.py", line 204, in from_appvm
Jun 09 12:43:43 dom0 qubesd[2882]:     if not appvm.template_for_dispvms:
Jun 09 12:43:43 dom0 qubesd[2882]: AttributeError: 'DispVM' object has no attribute 'template_for_dispvms'
```
**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

didn't see

**Comment by theperelomov** [comment] 2021-06-09 09:58
UPD: Not only XTerm, any app didn`t launch from menu (except qube settings)     

`qvm-run sys-firewall xterm` - work

**Comment by DemiMarie** [comment] 2021-06-09 17:44
There are two bugs here:

- The generated appmenus should not be trying to use a DispVM as a DispVM template.
- qubesd should provide a better error message.

More generally, *any* “Got empty response from qubesd” is a bug in qubesd, except perhaps for out-of-memory exceptions.  I will file a separate issue for that.

**Comment by EncryptedGiraffe** [comment] 2021-06-09 21:52
Perhaps related to this: https://github.com/QubesOS/qubes-issues/issues/4636?

**Comment by ninavizz** [comment] 2021-06-10 02:23
Related to #6634. @DemiMarie if you're tackling this, pls let me know—happy to work with  ya to come up with a clearer error message for failure scenarios.

**Comment by DemiMarie** [comment] 2021-06-10 05:38
> Perhaps related to this: #4636?

It is indeed, good catch!  I will mark this one as a duplicate, since #4636 already has a diagnosis.

Duplicate of #4636.

**Closed by DemiMarie** 2021-06-10 05:38 UTC
Labels: C: core, C: desktop-linux, P: major, T: bug, diagnosed

**Comment by DemiMarie** [comment] 2021-06-10 05:54
Duplicate of #4636
