### ISSUE TITLE
Firefox freezes when pressing F11 for maximizing the window

### ISSUE THREAD

**Issue by atlhaua** [QubesOS/qubes-issues#2177] opened 2016-07-15 17:30 UTC
Qubes OS version  `R3.1`
Affected TemplateVMs `fedora-23` and Debian8
Actual behavior:
Firefox freezes when pressing F11 for maximizing the window. If you move the focus to a different window and then come back to firefox, you can see it has taken in the last keystroke or click you did before switching the focus but then it freezes again. It seems as if the window is not been refreshed with the latest actions despite them happening in the background. Therefore it is not actually "freezing" but rather not refreshing.
This does not happen if you maximize the window by dragging it to the top edge of the screen.

I am using a TP300 Transformer FlipBook. Intel Core i3-4030U with VT-d and 4GB of memory.
Everything else I have tested works fine.

**Comment by andrewdavidwong** [comment] 2016-07-15 18:47
I can reproduce this.

**Comment by marmarek** [comment] 2016-07-15 20:34
Duplicate of #1502

**Closed by marmarek** 2016-07-15 20:34 UTC
Labels: bug, C: gui-virtualization, duplicate
