### ISSUE TITLE
Updater Stuck at 100% (updating whonix-ws)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#8288] opened 2023-06-22 16:39 UTC
### Qubes OS release
4.2-rc1

### Brief summary
The updater is stuck at 100% on the whonix-ws. So I’m not sure if it’s a whonix bug or an updater one. It kind of feels like an updater one just because a faulty template should be handled gracefully by the updater.

![40cd128e1e267a4afbfb4e4e0ff20570e05bc7ba](https://github.com/QubesOS/qubes-issues/assets/47065258/a77b76a0-32d7-4c2e-ac0d-7aaffef5605d)

### Steps to reproduce
Freshly installed Qubes 4.2 rc1, update the system

### Expected behavior
Updater gets to 100% and finishes the update (not hanging)

### Actual behavior

Updater gets stuck at 100%.

**Comment by marmarek** [comment] 2023-06-22 16:46
Duplicate of https://github.com/QubesOS/qubes-issues/issues/8163

**Closed by marmarek** 2023-06-22 16:46 UTC
Labels: T: bug, P: default

**Comment by deeplow** [comment] 2023-06-23 05:23
Whoops. I had not found that one. Thanks!

**Comment by andrewdavidwong** [comment] 2023-06-23 07:17
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
