### ISSUE TITLE
4.0.1-rc2 Qubes Updater indicates updates available after fresh install, but running the updater completes before sys-whonix is started and Tor connection is configured and established

### ISSUE THREAD

**Issue by jrsmiley** [QubesOS/qubes-issues#4649] opened 2018-12-22 22:51 UTC
### Qubes OS version:

4.0.1-rc2

### Affected component(s): 

Updater

---

### Steps to reproduce the behavior:

Hover mouse over gear icon at top right shows "Updates are available"
Left click the gear and select "Launch Updater"
fedora-29 shows that updates are available
Select Next
Open details window

### Expected behavior:

Shows updates being downloaded and installed

### Actual behavior:

Updater shows "SKIP (nothing to do)"
sys-whonix dialog window pops up asking how to connect to Tor
select Direct
sys-whonix connects to Tor but updater has already finished 

### General notes:

System was configured to use sys-whonix for template updates
Updater should wait until there sys-whonix is started and connected to Tor

---

**Comment by jrsmiley** [comment] 2018-12-22 22:55
Looking for a way to apply labels / tags to the issues I create.  Not finding any.  Not sure if this is intended or not.  Could save Andrew some time if I could apply these myself.

**Comment by marmarek** [comment] 2018-12-23 00:05
Duplicate of #4650

**Comment by jrsmiley** [comment] 2018-12-26 03:43
Not a duplicate. This issue relates to the updated not waiting for Whonix-gw to establish a Tor connection before looking for updates.  As it is now, the updater completes before the connection is made.

**Comment by jrsmiley** [comment] 2018-12-26 04:11
I will state explicitly what has only been implied until now. This system is configured so that all template updates come through Whonix. The updater must wait for Whonix-gw to connect to Tor, but does not.

**Comment by andrewdavidwong** [comment] 2018-12-26 21:06
> Looking for a way to apply labels / tags to the issues I create. Not finding any. Not sure if this is intended or not. Could save Andrew some time if I could apply these myself.

This is very much intentional. Considering that any anonymous person on the internet can create an issue here, allowing everyone to apply their own labels would be an unmitigated disaster. The time spent cleaning up mislabeling would easily outstrip the time currently spent labeling. (And if we didn't clean them up, labels would be effectively useless. We would just have to start ignoring them.)

**Comment by marmarek** [comment] 2019-01-20 14:14
@adrelanos what is the best way to wait for tor connecting to the network, i.e. for the network (providing) being fully operational? On "normal" system it would be `network-online.target` or `NetworkManager-wait-online.service`, but I think it wouldn't work directly on Whonix, and probably not even on non-Whonix Qubes VMs...
Ideally we'd like a qrexec service that waits for the network being fully operational (regardless of being that a Tor, VPN, or clearnet).

**Comment by adrelanos** [comment] 2019-01-20 15:54
Yes, would be very nice if the updater would wait for connectivity and communicate that. Next step would be helping out sorting out connectivity issues but that looks far fetched.

Marek Marczykowski-Górecki:

> On "normal" system it would be `network-online.target` or `NetworkManager-wait-online.service`
That wouldn't even work on directly to clearnet connected VM. Not even in NetVM. Not even on plain non-Qubes Debian. systemd manual last time I looked mentioned it's not for that. I am not aware of any connectivity check tools. We might have to invent it.

sys-net might use `nm-online`.

Otherwise check if network interface is online. And then... Actual connectivity check.

But how to check actual connectivity? We don't develop for a private script. We develop for Qubes OS. So we shouldn't hardcode "curl google.com". Things to think about: privacy; what if the destination server is offline (use multiple?); and censorship risk.

> Ideally we'd like a qrexec service that waits for the network being fully operational (regardless of being that a Tor, VPN, or clearnet).

Yes. A connectivity test qrexec call. Would be very useful.

Each VM capable only of asking their NetVM. If it's a middle (chained) NetVM, it should check if itself is ready and then ask its NetVM.

The code could have a plugin so that specific NetVMs. Just a program/script that would run before; and after. exit 0 on success or non-zero on non-connectivity. (Whonix could provide such a plugin.)

> what is the best way to wait for tor connecting to the network, i.e. for the network (providing) being fully operational?

Tor control protocol command `status/circuit-established` returning `1`.

python example: https://github.com/Whonix/anon-shared-helper-scripts/blob/master/usr/lib/anon-shared-helper-scripts/tor_circuit_established_check.py

( other related code: https://github.com/Whonix/anon-shared-helper-scripts/tree/master/usr/lib/anon-shared-helper-scripts )

The Whonix connectivity check plugin could run before, and check if `status/circuit-established` returns `1` and if so `exit 0`. This is because a connectivity check is pointless if `status/circuit-established` does not return `1`. An answer to `status/circuit-established` is fast but an actual connectivity test is slow. No way to distinguish slow Tor vs no connectivity.

**Closed** 2023-08-05 09:19 UTC
Labels: T: bug, C: other, P: default, eol-4.0
