### ISSUE TITLE
Screen does not lock on Purism Librem 15 with vmlinuz-4.14 if the right-click-menu is open

### ISSUE THREAD

**Issue by Zombie-Fairy** [QubesOS/qubes-issues#6046] opened 2020-09-11 17:33 UTC
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Very minor effect, very low impact, but it could potentially affect security.

I checked for "screen" "lock" for this and found nothing. 
I am on Purism Librem 15 with Qubes, Dom0, vmlinuz-4.14 and occasionally found (while the post lady came and I rushed to the door) that the screen lock did not activate after time elaped. That was, when the menu (Librem Menu button) that is the right click menu was open on dom0.
Without that menu open, the screen locks as it should
I reproduced and verified - it's reproducable! Even after reboot.

---

### Steps to reproduce the behavior:

Set screen lock to a short span of time, open menu, wait for time elapse ... 
Try again, when menu is not open, wait till screen locks. Ready

### Expected or desired behavior:

That the screen locks as it should, even if what-ever-it-is is open.

### Actual behavior:

see above

### General notes:

---

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

searched the internet for it and found ... this: 
https://bugs.launchpad.net/ubuntu/+source/gnome-screensaver/+bug/49579

searched github for it and found nothing

**Comment by andrewdavidwong** [comment] 2020-09-12 01:16
Duplicate of #3898

**Comment by andrewdavidwong** [comment] 2020-09-12 01:16
Thank you for trying to search beforehand. This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-09-12 01:16 UTC

**Comment by Zombie-Fairy** [comment] 2020-09-12 07:42
Andrew, thanks and sorry ... no clue as to why I did not notice it as a dup. 
As I find it helpful in many ways, to know, that this seems to be more of a general issue, I'll add the Ubuntu-link to #3898.
