### ISSUE TITLE
Install Issue 3.1-rc2: XDG_RUNTIME_DIR not set

### ISSUE THREAD

**Issue by cobrin** [QubesOS/qubes-issues#1623] opened 2016-01-14 13:55 UTC
Whilst instaling 3.1-rc2 in to VirtualBox, I selected Xfce option, when the installation started, after "`Creating luks on /dev/sda2`", I got the following error

`(anaconda:958): Gdk-ERROR **: error: XDG_RUNTIME_DIR not set in the environment.`

/tmp/syslog contained the following line

`13:32:12,420 INFO kernel:[   621.543330] traps: anaconda[1120] trap int3 ip:7fc90c234e9 sp:7fc8ed3428e0 error:0`

**Comment by axon-qubes** [comment] 2016-04-06 10:28
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by andrewdavidwong** [comment] 2016-06-27 19:37
Reopening because we have another user report about this.

[Drew White wrote](https://groups.google.com/d/msgid/qubes-users/b23aa3ea-e7ab-4333-8846-a34015ad3dc6%40googlegroups.com):
> Text based install
> 
> In the installer, when I don't get the LUKS bug, and it doesn't work right, 
> I get the following error....
> 
> It creates "luks" on /dev/sda2, even though I have not selected LUKS, nor 
> set a password for it.
> then it comes up with...
> ```
> (anaconda:957): Gdk-ERROR **: error: XDG_RUNTIME_DIR not set in the 
> environment.
> 
> 
> Pane is dead
> ```
> 
> There is no graphical interface, it's text based...

**Comment by marmarek** [comment] 2017-09-04 00:44
Duplicate of #1161

**Closed by marmarek** 2017-09-04 00:44 UTC
Labels: C: installer
