### ISSUE TITLE
"Whoops. A critical error has occured. This is most likely a bug in Qubes Manager." libvirt.py 3964

### ISSUE THREAD

**Issue by qjoo** [QubesOS/qubes-issues#1759] opened 2016-02-18 15:33 UTC
Hi,

this happened on R3.0, qubes-manager v3.0.13-1
(out of the blue)

```
----
line: if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
func: lookupByName
line no.: 3964
file: /usr/lib64/python2.7/site-packages/libvirt.py
----
line: self._libvirt_domain = vmm.libvirt_conn.lookupByName(self.name)
func: libvirt_domain
line no.: 740
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: if self.libvirt_domain.isActive():
func: is_running
line no.: 892
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: if not vm.is_running():
func: block_list_vm
line no.: 241
file: /usr/lib64/python2.7/site-packages/qubes/qubesutils.py
----
line: devices_list.update(block_list_vm(vm, system_disks))
func: block_list
line no.: 324
file: /usr/lib64/python2.7/site-packages/qubes/qubesutils.py
----
line: blk = qubesutils.block_list(self.qvm_collection)
func: update
line no.: 81
file: /usr/lib64/python2.7/site-packages/qubesmanager/block.py
----
line: self.update()
func: check_for_updates
line no.: 67
file: /usr/lib64/python2.7/site-packages/qubesmanager/block.py
----
line: res, msg = self.blk_manager.check_for_updates()
func: update_block_devices
line no.: 820
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
----
line: update_devs = self.update_block_devices() or out_of_schedule
func: update_table
line no.: 692
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

**Comment by marmarek** [comment] 2016-02-18 16:01
Duplicate of #1537. Not yet backported to R3.0

**Closed by marmarek** 2016-02-18 16:01 UTC
Labels: duplicate
