### ISSUE TITLE
xdg-open does not work in debian-8 template

### ISSUE THREAD

**Issue by waiting-for-dev** [QubesOS/qubes-issues#2065] opened 2016-06-13 07:49 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-8

---
### Expected behavior:

`xdg-open` to work out of the box
### Actual behavior:

```
xdg-open http://github.com
/usr/bin/xdg-open: 491: /usr/bin/xdg-open: gnome-open: not found
```
### Steps to reproduce the behavior:

Just run:

```
xdg-open http://github.com
```
### General notes:

This doesn't happen in `fedora-23` template.

I tried:

```
xdg-settings set default-web-browser iceweasel.desktop
xdg-mime default iceweasel.desktop x-scheme-handler/http
xdg-mime default iceweasel.desktop x-scheme-handler/https
```

without success. But, anyway, `xdg-open` should work OOTB.

Thanks!

---
#### Related issues:
- https://github.com/QubesOS/qubes-issues/issues/1781

**Comment by adrelanos** [comment] 2016-06-15 13:43
user support:

to fix this in meanwhile, install libgnome2-bin.

sudo apt-get install libgnome2-bin

development discussion:

Since we have environment variable GNOME_DESKTOP_SESSION_ID set,
xdg-open will set DE=gnome.

Rather than trying to understand and fix xdg-open, I suggest to install
libgnome2-bin by default (contains gnome-open).

Make libgnome2-bin a dependency of qubes-gui-agent-linux. Should I
create a pull request?

**Comment by marmarek** [comment] 2016-06-15 14:19
Actually we [set `DE=generic`](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes-open#L10) exactly for this reason.

**Comment by marmarek** [comment] 2016-06-15 14:21
Using `gnome-open` breaks DispVM (because `gnome-open` doesn't wait for file viewer/editor being closed).

**Comment by unman** [comment] 2016-06-15 22:33
On Wed, Jun 15, 2016 at 06:43:46AM -0700, Patrick Schleizer wrote:
> user support:
> 
> to fix this in meanwhile, install libgnome2-bin.
> 
> sudo apt-get install libgnome2-bin
> 
> development discussion:
> 
> Since we have environment variable GNOME_DESKTOP_SESSION_ID set,
> xdg-open will set DE=gnome.
> 
> Rather than trying to understand and fix xdg-open, I suggest to install
> libgnome2-bin by default (contains gnome-open).
> 
> Make libgnome2-bin a dependency of qubes-gui-agent-linux. Should I
> create a pull request?
> 
> 
If I remember this pulls in a vast amount of gnome stuff.

**Comment by adrelanos** [comment] 2016-06-16 10:46
At first it sounded like a bug worth being reported against gnome-open. I cannot find out how to report a bug against gnome-open. However, old bug reports against gnome-open make this seem futile.

https://bugzilla.gnome.org/buglist.cgi?short_desc=gnome-open&query_format=advanced&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=NEEDINFO&short_desc_type=substring

According to Debian file search for gnome-open, seems like gnome-open is a gnome2 thing only and not available in gnome3?

https://packages.debian.org/search?searchon=contents&keywords=gnome-open&mode=path&suite=unstable&arch=any

-----

Then what about perhaps setting `DE=generic` as global environment variable rather than just setting it in qubes-open?

**Comment by marmarek** [comment] 2016-06-16 11:38
Maybe it's rather a bug in `xdg-open` to call `gnome-open` if it isn't installed? I'm not sure about `DE=generic` globally - it may break something else or have other unexpected results.

**Comment by adrelanos** [comment] 2016-06-20 20:27
I am not sure upstream would accept a bug report and/or patch with
if/else /usr/bin/gnome-open code included. This issue probably applies
to Qubes only. Is caused by Qubes setting the GNOME_DESKTOP_SESSION_ID
environment variable.

[1]
https://github.com/marmarek/qubes-gui-agent-linux/blob/master/appvm-scripts/etc/X11/Xsession.d/20qt-gnome-desktop-session-id

In /usr/bin/xdg-open it gets triggered by the following line.

elif [ x"$GNOME_DESKTOP_SESSION_ID" != x"" ]; then DE=gnome

Upstream might ask, why do you have the GNOME_DESKTOP_SESSION_ID
environment variable set if you are not using gnome?

The workaround...
unset GNOME_DESKTOP_SESSION_ID xdg-open ...
...is functional.

Can the goal 'Prevents QT from displaying ugly QT theme' [1] be reached
some other way than setting the GNOME_DESKTOP_SESSION_ID environment
variable.

**Comment by marmarek** [comment] 2016-06-20 20:43
> Can the goal 'Prevents QT from displaying ugly QT theme' [1] be reached
> some other way than setting the GNOME_DESKTOP_SESSION_ID environment
> variable.

No idea, but if someone would find a way, I'd love to unset `GNOME_DESKTOP_SESSION_ID`.

This is the commit which introduced the change:
https://github.com/marmarek/qubes-gui-agent-linux/commit/524fb4528166279827861391cb738488248e9c38

**Comment by adrelanos** [comment] 2016-06-23 11:33
@h01ger @nrgaway

**Comment by adrelanos** [comment] 2016-11-23 14:48
A reasonable feature request against upstream `/usr/bin/xdg-open` could be:
`do not overwrite environment variable DE if it is already set`

The patch `/usr/bin/xdg-open` would be trivial.

Now:

```
detectDE

if [ x"$DE" = x"" ]; then
    DE=generic
fi
```

Suggested:

```
if [ x"$DE" = x"" ]; then
    detectDE
fi

if [ x"$DE" = x"" ]; then
    DE=generic
fi
```

What do you think?

**Comment by marmarek** [comment] 2016-11-23 19:44
Makes sense.

**Comment by adrelanos** [comment] 2016-11-26 23:52
`do not overwrite environment variable DE if it is already set`:
https://bugs.freedesktop.org/show_bug.cgi?id=98866

**Comment by rdieter** [comment] 2016-11-28 15:04
Is there any reasons you cannot set/use the (standardized) XDG_CURRENT_DESKTOP instead (of DE) ?

**Comment by marmarek** [comment] 2016-11-28 15:09
I think the only reason is: didn't know about its existence.

**Comment by adrelanos** [comment] 2016-11-28 15:28
Rex Dieter:
> Is there any reasons you cannot set/use the (standardized) XDG_CURRENT_DESKTOP instead (of DE) ?
> 

Setting XDG_CURRENT_DESKTOP=generic alone does not work. The bash xtrace
shows, DE will still be set to gnome.

Setting both XDG_CURRENT_DESKTOP=generic and DE=generic however works.
So no patch from upstream required.

**Comment by marmarek** [comment] 2016-11-28 15:35
Try `XDG_CURRENT_DESKTOP=X-generic`.

**Comment by adrelanos** [comment] 2016-11-28 22:13
Thank you @rdieter [xdg-open upstream] for joining this discussion!

Update: Upstream rejected my previous suggestion and that's fine.

Marek Marczykowski-Górecki:
> Try `XDG_CURRENT_DESKTOP=X-generic`.

Doesn't work.

Variable XDG_CURRENT_DESKTOP isn't tested for either 'generic' or 'X-generic' so I wouldn't know how that possibly could work as of now.

Still need to set DE=generic as well as XDG_CURRENT_DESKTOP=generic.

It makes sense to me because in /usr/bin/xdg-open 'sh' function 'detectDE' the following...

```
if [ x"$DE" = x"" ]; then
   ...
   DE=kde;
   ...
```

... is outside this previous 'if'.

```
if [ -n "${XDG_CURRENT_DESKTOP}" ]; then
```

Even though upstream considers variable DE an internal variable, for Qubes purpose in meanwhile as workaround setting DE=generic as well as XDG_CURRENT_DESKTOP=generic should do.

The clean fix for xdg-open as far as I see through this would be a minimal patch for if 'XDG_CURRENT_DESKTOP = 'generic' then it should also set 'DE=generic'. What do you think, @rdieter?

**Comment by marmarek** [comment] 2016-11-28 23:23
Typo in my message - there should be `X-Generic`.

**Comment by adrelanos** [comment] 2016-11-28 23:34
Same result.
`XDG_CURRENT_DESKTOP=X-Generic sh -x /usr/bin/xdg-open some-file` results in using `gnome-open`.

`DE=generic XDG_CURRENT_DESKTOP=generic sh -x /usr/bin/xdg-open some-file` results in using `mine-open`.

**Comment by marmarek** [comment] 2016-11-28 23:46
Hmm, it should. See [detectDE fuction](https://cgit.freedesktop.org/xdg/xdg-utils/tree/scripts/xdg-utils-common.in?id=ef8a58be4049697bb6347c3c5b8fff4d2b2deb86#n252)
```
detectDE()
{
    # see https://bugs.freedesktop.org/show_bug.cgi?id=34164
    unset GREP_OPTIONS

    if [ -n "${XDG_CURRENT_DESKTOP}" ]; then
      case "${XDG_CURRENT_DESKTOP}" in
(...)
         X-Generic)
           DE=generic
           ;;
      esac
    fi
```

Maybe Debian have outdated xdg-utils package?

**Comment by adrelanos** [comment] 2016-11-29 00:31
Yes. jessie version does not support `X-Generic`. stretch version does.

So looks like upstream already implemented a nice solution `XDG_CURRENT_DESKTOP="X-Generic"` that works for Qubes long term then.

For jessie based Qubes, I suggest:

```
# Can be removed once depending on Debian stretch or above.
DE=generic

XDG_CURRENT_DESKTOP=X-Generic
```

(Then we can just remove `DE=generic` later with very low priority.)

**Comment by esote** [comment] 2018-11-28 21:39
@adrelanos @marmarek Is this still an issue? I'm not familiar with Debian's development flow, but maybe changes from stretch (as mentioned by adrelanos) have filtered down to jessie.

**Comment by adrelanos** [comment] 2018-11-29 07:12
Still an issue with debian-9 template.

----

With `libgnome2-bin` package installed, in AppVM:

    xdg-open http://github.com

uses `gnome-open` which doesn't wait until execution is finished. Bad.

Also we probably shouldn't use Gnome anything (`gnome-open`) since VMs aren't based on Gnome?

----

Without `libgnome2-bin` installed, in AppVM

    xdg-open http://github.com

uses `gvfs-open` (from package `gvfs-bin`) which doesn't wait until execution is finished. Bad.

----

Without package `libgnome2-bin` and without `gvfs-bin` installed, in AppVM

    xdg-open http://github.com

uses xdg-open's `open_generic_xdg_x_scheme_handler` function.

-----

These packages are not installed by default in Qubes.

----

    XDG_CURRENT_DESKTOP=X-Generic xdg-open http://github.com

uses always uses xdg-open's `open_generic_xdg_x_scheme_handler` function consistently.

Works also well in DispVM.

    qvm-run --pass-io --dispvm=debian-dvm "bash -x xdg-open https://github.com"

I suggest

* we remove legacy `export DE=generic` from [qubes-open](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes-open#L10),
* and set `export XDG_CURRENT_DESKTOP=X-Generic` globally.

What do you think?

**Comment by unman** [comment] 2018-11-30 01:09
Still an issue with Debian-8, (although doesn't seem to be in Debian-9 for me.), so that last option won't fly.

**Comment by adrelanos** [comment] 2018-11-30 11:44
Indeed, `export XDG_CURRENT_DESKTOP=X-Generic` shouldn't be set globally in debian-8. Only in debian-9 (and above). Thanks, didn't have that on my radar.

Is it possible to make changes in Qubes packages only affecting Debian releases equal or greater than 9?

Inability to do so would make development difficult. Not a secret that I am not a big fan of carrying around oldstable versions support. Lot effort for little to zero popularity? I'd not release new Qubes packages for debian-8 in order to not break them. Only debian-9 and above. Otherwise too many targets required to test / too much development effort, imo.

**Comment by marmarta** [comment] 2021-09-08 22:43
Closing because debian 8 is long not supported.

**Closed by marmarta** 2021-09-08 22:43 UTC
Labels: T: enhancement, P: minor, C: Debian/Ubuntu

**Comment by andrewdavidwong** [comment] 2021-09-08 23:29
> Closing because debian 8 is long not supported.

Looks like this was reclassified from a bug to an enhancement, so the title should probably have been updated to something like "Support xdg-open in Debian qubes."

Still a "won't do"?

**Comment by unman** [comment] 2021-09-09 14:00
On Wed, Sep 08, 2021 at 04:29:41PM -0700, Andrew David Wong wrote:
> > Closing because debian 8 is long not supported.
> 
> Looks like this was reclassified from a bug to an enhancement, so the title should probably have been updated to something like "Support xdg-open in Debian qubes."
> 
> Still a "won't do"?
> 

Yes
