### ISSUE TITLE
GUI is not updated if new USB device is plugged/unplugged/attached

### ISSUE THREAD

**Issue by abbluiz** [QubesOS/qubes-issues#4900] opened 2019-03-20 19:54 UTC
### Qubes OS version:

R4.0 with current-testing repo enabled

### Affected component(s) or functionality:

Qubes Devices, sys-usb GUI

---

### Steps to reproduce the behavior:

I open the USB tray and attach a device to a qube; I plug/unplug an USB device to/from my computer

### Expected or desired behavior:

If I attach a device, it should display an option to detach it and if I plug/unplug a device to/from my computer, the list should be updated

### Actual behavior:

The tray is not updated if I plug or remove another USB device, and if I attach an available device to a qube, there is no way to detach it through the tray because the GUI is not updated. I would have to do so by typing `qvm-block detach` command

### General notes:

---

**Comment by andrewdavidwong** [comment] 2019-03-21 05:30
Duplicate of #4849

**Comment by andrewdavidwong** [comment] 2019-03-21 05:31
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-03-21 05:31 UTC
