### ISSUE TITLE
Absurd hotkey to pause all VMs (including sys-usb?) without confirmation

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#4700] opened 2019-01-10 07:33 UTC
### Qubes OS version:

4.0.1

### Affected component(s): 

UI / hotkeys

---

### Steps to reproduce the behavior:

1. Press an (unpublisised?) hotkey that pauses all VMs (is it ctrl-shift-P?)
2. System is now dead - cannot be unpaused (keyboard and mouse are dead - could this be because sys-usb is one of the VMs that has been paused?)
3. Cold restart computer
4. Attempt to recreate the work lost

### Expected behavior:

0. There should not be a hotkey that has such a drastic effect on an easily-pressed key combo
1. If pressed, there should be confirmation sought from user (an “are you sure?” is not too much to expect before killing your entire PC)
2. sys-usb should not be stopped if usb keyboard/mouse is in use

If that can’t be done, the hotkey needs to go because it is a “cure” that is worse than any problem.

**Comment by 0spinboson** [comment] 2019-01-10 09:22
Yeah, I've run into this once or twice myself. Luckily I still have a backup ps2 keyboard attached, but it's pretty silly that this shortcut exists.

**Comment by unman** [comment] 2019-01-10 11:56
Is this an Xfce thing? On KDE it has an effect dependent on application:  opening a new firefox window; in terminal it opens the print screen function, etc etc. Otherwise it doesn't seem to be set to any default action.

**Comment by andrewdavidwong** [comment] 2019-01-10 13:10
Duplicate of #4101

**Comment by andrewdavidwong** [comment] 2019-01-10 13:11
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by daniel-ayers** [comment] 2019-01-10 18:38
This is not a duplicate of #4101, which has been closed and implemented (and which I read prior to opening this issue). I did see that notification AFTER I pressed the secret hotkey and it did say I could unpause my VMs.

However it was impossible to do that because none of my (USB) input methods (mouse and keyboard) were functional. I can only speculate that was because sys-usb was also paused.

Closing this ignores the issues I have raised, which are:

- Poor choice of hotkey

- Requirement for confirmation before action is taken

- As a minimum, don’t pause critical system VMs (sys-usb) that in many configurations will be necessary to unpause.

The latter problem needs to be fixed as a priority, as it helps nobody to have a paused system that cannot be unpaused.  If at least one of the other problems was also addressed that would be a good step forward.

**Comment by tasket** [comment] 2019-02-06 19:47
I get the feeling this feature was added without a sober examination of the associated use cases + defaults.

IMO the best approach would be to remove the hotkey and let users set one manually if its really needed.

**Comment by marmarek** [comment] 2019-02-06 19:53
This is exactly what the above PR does. Would you like to help with testing it @tasket ?

**Comment by tasket** [comment] 2019-02-06 20:15
It should be someone else as I'm using KDE and I don't see a similar setting in this environment.

**Comment by daniel-ayers** [comment] 2019-02-07 03:56
@marmarek I am happy to help in any way I can, if that is of any use - complaints should always come with offers of help, etc. :)

**Closed** 2019-02-15 00:45 UTC
Labels: C: core, bug, ux

**Comment by imme-emosol** [comment] 2019-02-22 09:23
Another (better?) option would be to add "--exclude sys-usb" to the shortcut's command.

**Comment by marmarek** [comment] 2019-02-22 12:35
If we're going to reintroduce this hotkey, then yes. But the conflict with existing applications still needs another solution - choosing different keys.

**Comment by daniel-ayers** [comment] 2019-02-22 20:50
The first question should be is this "solution" required at all?  Is there a genuine case for it?  If there have been lots of reports of people being affected by a GUI DOS, I haven't seen them.

If a solution to some GUI DOS problem is warranted (which I doubt is the case) then the solution needs to be designed in a way that doesn't cause problems that are worse than the problem it is supposed to solve (remembering that the GUI DOS problem does not appear to be a major issue for the community, therefore the allowable risk of side-effects from the solution should be very low).

If the solution is reintroduced it has exactly zero value to a user who does not know it exists and/or does not know what the hotkey is.  Such a user could never activate it even if they experienced a GUI DOS.  (I suggest that most users would fit in that category the way it was originally implemented).  

This function can never, by default, be assigned to a hotkey that is likely to clash with other applications and/or be accidentally tripped (CTRL-SHIFT-P was an extraordinarily bad choice).

Given these considerations the only sensible way I can see of reintroducing the function is to default it to OFF with no hotkey assigned.  If a user wants that capability they can activate it and assign a hotkey that they know and suits their application.  This would ensure the user knows the hotkey and can actually use the function if it is needed.
