### ISSUE TITLE
fedora-xfce template has Run Terminal option missing

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#8361] opened 2023-07-15 06:05 UTC
### The problem you're addressing (if any)
fedora-38-xfce and fedora-38-minimal templates have no option to run a terminal by default.
(maybe someone can check if this is the default for debian/-minimal too)

Qubes Settings -> Applications:
- Application missing in template! (gpk-update-viewer.desktop)
- Application missing in template! (org.gnome.Software.desktop)
- Application missing in template! (org.gnome.Terminal.desktop)

### The value to a user, and who that user might be
For better user experience the default options should be available here too (terminal, file browser, ...)

**Comment by TNTBOMBOM** [comment] 2023-07-15 11:56
Known issue, your ticket already duplicate of #8318 and #8328 (even closed already: #7245 and 6805)

**Comment by andrewdavidwong** [comment] 2023-07-15 23:28
Duplicate of #8318

**Comment by andrewdavidwong** [comment] 2023-07-15 23:28
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-07-15 23:28 UTC
Labels: T: enhancement, P: default
