### ISSUE TITLE
Reflect new keyboard layout in dom0 to open AppVM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#919] opened 2015-03-08 17:22 UTC
**Reported by alex svc on 7 Nov 2014 18:14 UTC**
If the user selects a new keyboard layout (e.g. via hotkey) in dom0 kde, the setting is not reflected in the open AppVM (nor in the newly started VMs) - happens with fedora-20-x86 templateVM

Migrated-From: https://wiki.qubes-os.org/ticket/919

**Comment by andrewdavidwong** [comment] 2016-08-29 05:09
Closing as duplicate of #1396. (Technically, #1396 is a duplicate of this, since this is older, but #1396 has a lot of relevant discussion already, and this has none.)

**Closed by andrewdavidwong** 2016-08-29 05:09 UTC
Labels: bug, C: desktop-linux, duplicate, P: major
