### ISSUE TITLE
Meaningfully backup dom0 with Qubes Backup

### ISSUE THREAD

**Issue by marmot1791** [QubesOS/qubes-issues#5608] opened 2020-01-29 16:40 UTC
**The problem you're addressing (if any)**
Qubes Backup does not meaningfully backup dom0. The backup only includes the user's home directory which should contain effectively nothing. The parts of dom0 that may have actually been customized like the Qubes-RPC policy in /etc or the Salt configurations are not backed up.

**Describe the solution you'd like**
Initially, better documentation to the end user that dom0 is not backed up in a meaningful way.
Then, actual backups of useful dom0 configuration files.

**Where is the value to a user, and who might that user be?**
Most end users expect to be able to go from a fresh install + recent backup back to their prior state. Qubes Backup implies that promise by capturing all Qubes and offering to backup dom0, but does not keep that implied promise by storing dom0 data.

The Qubes documentation mentions changes to the dom0 configuration in several places, these changes should be preserved after a restore so they do not need to be manually recreated.

**Describe alternatives you've considered**
One alternative might be to version and or backup the dom0 configuration directly into the user's dom0 home directory so that the existing backup system need not be modified at all.

Another alternative might be to modify the backup implementation to capture more of dom0, but perhaps not all of dom0.

**Questions for others**
What configuration data in dom0 should be backed up? /etc? /srv?
What is the impact of restoring dom0 configuration data across versions of Qubes - both minor and major versions? Even if we're just advising users how to restore configuration data and not restoring it automatically, what advice should we give them?

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Backup and restore documentation: https://www.qubes-os.org/doc/backup-restore/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
restore process UX issues: https://github.com/QubesOS/qubes-issues/issues/4946
backup VM list improvements: https://github.com/QubesOS/qubes-issues/issues/4712

**Comment by andrewdavidwong** [comment] 2020-01-30 07:31
Duplicate of #1635

**Comment by andrewdavidwong** [comment] 2020-01-30 07:32
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-01-30 07:32 UTC
Labels: P: default, T: enhancement
