### ISSUE TITLE
Disposable sys-net: `failure adding connection: error writing to file /etc/NetworkManager/system-connections/<SSID>.nmconnection.MJP691: Permission denied`

### ISSUE THREAD

**Issue by SvenSemmler** [QubesOS/qubes-issues#8445] opened 2023-08-24 04:43 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2-rc1

### Brief summary

Selected the option to make sys-net disposable in the installer. First attempt to connect to Wi-Fi produces error message.

### Steps to reproduce

Install R4.2-rc1

-> using BTRFS file system (not likely related to this issue)
-> timezone America/Chicago (not likely related to this issue)
-> default template: fedora-38 (template for default-dvm, which in turn is template for sys-net)
-> deselect anything Whonix (not likely related to this issue)
-> deselect creating of default qubes (work, private, untrusted etc)

At first start attempt to connect to Wi-Fi.

### Expected behavior

Dialog box asking for password.

### Actual behavior

Connection failure
Failed to add/activate connection
failure adding connection: error writing to file /etc/NetworkManager/system-connections/Schlabber.nmconnection.MJP691: Permission denied

(Schlabber is the SSID of the Wi-Fi network)

### What I tired

I then deleted sys-net and recreated a ProxyVM based on fedora-38 named sys-net. This one worked right away.

qubes-prefs clockvm ''
qvm-prefs sys-firewall netvm ''
qvm-remove sys-net
qvm-create --template fedora-38 --label red sys-net
qvm-prefs sys-net virt_mode hvm
qvm-prefs sys-net netvm ''
qvm-prefs sys-net provides_network true
qubes-prefs clockvm sys-net
qvm-prefs sys-firewall netvm sys-net

**Comment by marmarek** [comment] 2023-08-24 08:29
Do you have updates from current-testing installed? This looks like https://github.com/QubesOS/qubes-issues/issues/8242 which should be fixed in qubes-core-agent 4.2.19

**Comment by SvenSemmler** [comment] 2023-08-24 13:32
This was straight of the R4.2-rc1 install media and after the installer finished. I was trying to connect to the Wi-Fi in order to update.

**Comment by andrewdavidwong** [comment] 2023-08-25 21:02
> This looks like https://github.com/QubesOS/qubes-issues/issues/8242

Just noticed that #8242 does indeed report the exact same error message, and someone just commented on that issues saying that a recent testing ISO is still affecting, so I just reopened it.

-----

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2023-08-25 21:02
Duplicate of #8242

**Closed by andrewdavidwong** 2023-08-25 21:02 UTC
Labels: T: bug, P: default, needs diagnosis, C: networking, affects-4.2
