### ISSUE TITLE
AppVMs do not detect resolution change

### ISSUE THREAD

**Issue by Geblaat** [QubesOS/qubes-issues#7799] opened 2022-10-01 08:58 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary

When an external monitor with higher resolution that built-in laptop screen is connected, and it is set to only use external monitor, only the left and upper part of the screen are clickable inside an AppVM. The clickable part seems to be exactly the same as the resolution of the built-in laptop screen(1280x800). E.g. in this case, when using the external monitor, from left to right, the clickable area is in the first 1280 pixels horizontally starting from the left and the first 800 pixels vertically starting from the upper part of the screen.
Clicking on the colored border window does work correctly on the whole screen, but clicking inside the window does not work correctly, so it seems that the AppVM itself does not detect the resolution properly.

### Steps to reproduce

Connect laptop to external screen with higher resolution
Choose to use only the external display
Start any application inside an AppVM that is already running
Try to click in the window area on the right and bottom, the part where the 'extra resolution' was 'added' to the virtual screen.

### Expected behavior

Works as expected, extra area is clickable

### Actual behavior

Extra area is not clickable, when clicking in the extra area, it behaves as if the user is clicking on the 'border' of the old resolution and the 'added part' from the new resolution. 
A reboot of running AppVM's is necessary to fix the behaviour.

**Comment by andrewdavidwong** [comment] 2022-10-02 02:37
Possible duplicate of #6268?

**Comment by Geblaat** [comment] 2022-10-02 14:12
> Possible duplicate of #6268?
> 
> I know that your setup uses only the external monitor while #6268 describes a dual-monitor setup, but the unexpected behavior sounds similar, so perhaps the cause is the same?

It may be. The reporter of #6268 states that it happens when using HDMI but not on VGA. I'm using Displayport instead of HDMI, but when I try VGA instead, it also does not happen.

**Comment by DemiMarie** [comment] 2023-10-17 16:11
Marking as https://github.com/QubesOS/qubes-issues/labels/fixed-by-wayland because with Wayland this would be the responsibility of the compositor.

**Comment by marmarek** [comment] 2023-10-17 16:26
> Marking as [ fixed-by-wayland](https://github.com/QubesOS/qubes-issues/labels/fixed-by-wayland) because with Wayland this would be the responsibility of the compositor.

The fact that wayland should implement this feature _too_, isn't relevant for X11 variant.

**Closed** 2024-12-07 14:28 UTC
Labels: T: bug, C: desktop-linux, C: gui-virtualization, ux, P: default, affects-4.1, eol-4.1
