### ISSUE TITLE
VPN documentation needs update on iptables rules

### ISSUE THREAD

**Issue by erikw** [QubesOS/qubes-issues#3888] opened 2018-05-09 21:51 UTC
...

**Comment by tasket** [comment] 2018-05-15 11:46
The OUTPUT rule you're adding makes pinging in the proxyVM possible, but at the (slight) expense of network isolation. One of the goals of the VPN solution is to prevent VPN VM tools from inadvertently accessing the net via the tunnel.

I would ask @adrelanos if such a rule is compatible with his criteria for isolation.

OTOH, it may be better to advise switching OUTPUT chain to `ACCEPT` for ping and traceroute tests. And testing from an appVM should probably be emphasized after the point where firewall rules are added (which is already the case in the proposed update).

Note that in the qubes-tunnel code (which the doc update is based on) firewall script will react to how the service name is specified. It will be possible for the user to turn off OUTPUT restrictions for testing by changing the Qubes service from `qubes-tunnel-openvpn` to a more generic form i.e. 'qubes-tunnel'. This will allow testing connectivity more freely from within the proxyVM.

**Comment by erikw** [comment] 2018-05-15 16:06
# Clarification
The whole idea of the solution currently online at https://www.qubes-os.org/doc/vpn/ is that only programs running under gid "qvpn" is allowed by iptables OUTPUT, and that the only program in the VPN VM that is supposed to be run under this gid is openvpn.

So in my example, ping from within the vpn using gid qvpn was just an example. *openvpn does not work* either without my suggested added rule.

It did work in qubes v3, but not in qubes v4. In v4 it seems like my suggested rule is needed for openvpn to be able to connect out to net-vm.

**Comment by tasket** [comment] 2019-06-07 22:37
I should point out that the main security idea of the VPN doc is embodied by the rules added to the FORWARD chain, definitely not OUTPUT.

The latter is a tertiary safeguard for circumstances where the user is experimenting inside the proxy VM; it doesn't contribute to the anti-leak properties wrt downstream VMs. Further, its specific to ICMP packets only, and only those packets originating from within the proxy VM. So the severity of the issue is low, and people have been using scripts with these rules (including the vpn doc and Qubes-vpn-support) with R4 for a long time now.

Note there may be a bug in newer Linux versions in how they emulate iptables rules, causing the ICMP blockage; or it may be in the new Qubes stack.

@andrewdavidwong You may want to close this issue, as the VPN doc already states a workaround as the normal procedure: Test the connection before adding scripts. Pinging from a downstream VM is recommended and avoids the issue, or you can effectively disable the OUTPUT restriction as suggested above.

**Comment by andrewdavidwong** [comment] 2019-06-08 03:41
> @andrewdavidwong You may want to close this issue, as the VPN doc already states a workaround as the normal procedure: Test the connection before adding scripts. Pinging from a downstream VM is recommended and avoids the issue, or you can effectively disable the OUTPUT restriction as suggested above.

Many docs, including this VPN doc, have recently transitioned to external documentation, so that's another reason to close this issue. Opening further issues to improve these docs is welcome in [Qubes Community](https://github.com/Qubes-Community).

**Closed by andrewdavidwong** 2019-06-08 03:41 UTC
Labels: C: doc
