### ISSUE TITLE
XScreenSaver turns into the screen for no reason (doesn't ask for login and doesn't lock the screen).

### ISSUE THREAD

**Issue by e5f3c2ea895af0f27667** [QubesOS/qubes-issues#2538] opened 2016-12-25 18:33 UTC
#### Qubes OS version: `R3.2`.

---

Also reported by another user:

> I wonder why #QubesOs lately always shows the xscreensaver lock screen when something is in fullscreen. Doesn't lock the screen, though
>
> Only happens after the system has run for a few days. Really disturbing to have the screen blank every few seconds

> https://twitter.com/SunTsu/status/811890918601138176

**Comment by andrewdavidwong** [comment] 2016-12-27 00:14
Description is vague, but this sounds like a duplicate of #2399.

**Closed by andrewdavidwong** 2016-12-27 00:14 UTC

**Comment by e5f3c2ea895af0f27667** [comment] 2016-12-27 08:06
@andrewdavidwong  Yes, that's exactly the issue I was experiencing.
