### ISSUE TITLE
KDE Plasma system tray does not show icons

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2400] opened 2016-10-27 06:06 UTC
Latest packages 3.2.

Systray icons like Kopete just show as windows that take up a quarter of the screen.

NetworkManager applet icon appears as floating window instead of appearing in systray.

Do not know what's up.

**Comment by andrewdavidwong** [comment] 2016-10-27 06:58
Duplicate of #2242 / #2268

**Closed by andrewdavidwong** 2016-10-27 06:58 UTC
