### ISSUE TITLE
Qubes 3.2 doesn't build default ubuntu template

### ISSUE THREAD

**Issue by arisAlexis** [QubesOS/qubes-issues#3598] opened 2018-02-17 16:33 UTC
#### Qubes OS version:

 3.2

#### Affected TemplateVMs: Ubuntu Trusty

---

### Steps to reproduce the behavior:

Following the default Archlinux Qubes Wiki:

clone Fedora 23 VM  
git clone the repo  

./setup fails with python2-sh dependency and resolved with editing Makefile, builder.conf and setup itself.  

make install deps works OK  
make qubes-vm fails with:  

> there is a problem with python2 because in fedora 23 there is no such
> package. I had to manually edit and put python-sh in Makefile,
> builder.conf and setup script. After that everything seems to be working
> fine but it crashes during make qubes-vm with this message:
>
> ln -s ../../bin/qrexec-client-vm
> /home/user/qubes-src/core-agent-linux/debian/tmp/usr/lib/qubes/qrexec_cli
> ent_vm install qrexec-fork-server
> /home/user/qubes-src/core-agent-linux/debian/tmp/usr/bin
> install qubes-rpc-multiplexer
> /home/user/qubes-src/core-agent-linux/debian/tmp/usr/lib/qubes
> make[2]: Leaving directory `/home/user/qubes-src/core-agent-linux/qrexec'
> make[1]: Leaving directory `/home/user/qubes-src/core-agent-linux'
> dh_install cp: cannot stat
> 'debian/tmp/lib/systemd/system/netfilter-persistent.service.d/30_qubes.co
> nf': No such file or directory
> dh_install: cp -a
> debian/tmp/lib/systemd/system/netfilter-persistent.service.d/30_qubes.con
> f
> debian/qubes-core-agent//lib/systemd/system/netfilter-persistent.service.
> d/ returned exit code 1 make: *** [binary] Error 2
> dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit
> status 2
> /home/user/qubes-builder/qubes-src/builder-debian/Makefile.qubuntu:200:
> recipe for target 'dist-package' failed make[2]: *** [dist-package] Error
> 2
> Makefile.generic:156: recipe for target 'packages' failed
> make[1]: *** [packages] Error 1
> Makefile:212: recipe for target 'core-agent-linux-vm' failed

### Expected behavior:

 build a default ubuntu image

### Actual behavior:

fails with error

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-02-18 00:13
Duplicate of #3308

**Comment by andrewdavidwong** [comment] 2018-02-18 00:13
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-18 00:13 UTC
Labels: C: Debian, bug
