### ISSUE TITLE
Qubes appVMs/StandaloneVMs fast speed for youtube playback

### ISSUE THREAD

**Issue by Nurmagoz** [QubesOS/qubes-issues#1698] opened 2016-01-26 18:01 UTC
one of the strangest thing im getting atm , all my appVMs r blazing with its speed which it cant be useable for streaming videos.

for e.g:- 

youtube videos moving in very high speed in which the connection speed can catch the speed of the video processing so no forward stream.

1------3-----8----10 loading 12------15----18---loading...etc (time in seconds)

also tried to run an audio player inside debian , i cant hear anything and the minutes line is rushing. 

i dunno how to reproduce this , or how can i give a useful info to work on. 

do u have commands , logs , ...etc i can check and report them back here ?

btw, all the rest r the same even appVMs from fedora-23 = youtube videos cant play normally 

only an OLD whonix-WS-appVM & also some old appVMs which r based on fedora 21 the youtube (or any video online) inside them is working good = dont ask me why it just weird i know.

**Comment by TNTBOMBOM** [comment] 2016-01-27 10:23
UPDATE

not just the appVMs & even the standaloneVMs

and i think something has changed in the last fidora-23 update which poisoned the entire qubes OS with this bug.

hope u participate in helping here urgently guys.

**Comment by TNTBOMBOM** [comment] 2016-01-28 13:30
UPDATE 

any new whonix-WS , is also infected with this bug. cant watch anything inside the TBB

cross linking

https://forums.whonix.org/t/streaming-videos-inside-the-tbb-not-possible-whonix-qubes-specific/2018

**Comment by TNTBOMBOM** [comment] 2016-01-30 13:00
![printscreen1111111111111111111111](https://cloud.githubusercontent.com/assets/11895339/12695809/fd7ab0aa-c750-11e5-8777-23014cd50d7a.png)


^^^^ this one ppl what do u call it ? 

when i run any video i cant watch because the red dot (as u c it in the pic) Moving very fast and jumping through seconds from 0 to 3 to 8 to ...etc. 

so streaming any video inside Qubes = impossible

@marmarek  how can i help u with this to get more info ?

**Comment by marmarek** [comment] 2016-01-31 22:04
Does it happen also with other video players, or just youtube in TBB? How about normal Firefox/Iceweasel? It is running using HTML5, or flash player (try switching to HTML5 if using flash)?

**Comment by adrelanos** [comment] 2016-01-31 23:19
I can confirm, that I also experienced this issue in past. Not enough
information to write a bug report, but hth... Already in R3.0 iirc.
Could be hardware dependent.

The approximate(!) steps to reproduce would be:

Start a browser in AppVM A.
Start a youtube video in AppVM A.
Change dom0 sound settings if you have multiple sound cards and outputs.
Close the browser in AppVM A.
Start a new browser in the [same] in AppVM A.
Now the video might be played super fast.

I could only restore to normal after reboot. AppVM restart did not help.
IIRC

**Comment by TNTBOMBOM** [comment] 2016-02-01 00:59
> Does it happen also with other video players, or just youtube in TBB? How about normal Firefox/Iceweasel? It is running using HTML5, or flash player (try switching to HTML5 if using flash)?

as i have mentioned already above and as patrick also said = in all of VMs. firefox or iceweasel or TBB , whonix or not ..etc

**Comment by Jeeppler** [comment] 2016-02-01 06:06
Have you tried to delete your AppVM and create a new one?

**Comment by TNTBOMBOM** [comment] 2016-02-01 13:13
yep i did. and again its not just the appVMs even standealoneVMs (which they r based on fedora-23 or debian-jessie or whonnix-ws/gw templates).

**Comment by TNTBOMBOM** [comment] 2016-02-02 22:37
all my appVMs/standaloneVMs r infected witha same speed problem , except one appVMs which is an old whonix-WS. ( i have created new one based on the current template , but it is infected witha same problem).

so a useful thing to do for this issue:- 

how can we extract some useful information which may help us from the old WS which is not infected and compare it with an infected WS ? good commands for this i dont really know, but how about u guys ? 

*WS = workstation or whonix-workstation.

**Comment by marmarek** [comment] 2016-02-02 22:48
Check pulseaudio settings in that VM. First of all, check if `module-vchan-sink` is loaded: `pactl list modules`, also listing `sinks` may be useful. Some video players (not sure if youtube is one of them) synchronize playing speed to audio, so if there is something wrong with audio, it would affect playing speed.
Another idea is system clock - does the time in VM is correct?

**Comment by TNTBOMBOM** [comment] 2016-02-03 22:14
well ahm i said good commands to type not good places to check in. 

so in WS how to do this checkism with commands?

**Comment by marmarek** [comment] 2016-02-04 00:03
Execute `pactl list modules` in WS and search for `module-vchan-sink`. If itsn't there, that may be a source of the problem. If you have the module in place, to the same with `pactl list sinks`.
As for system clock - simply check `date` output - does it match the current time (more or less)?

**Comment by TNTBOMBOM** [comment] 2016-02-04 00:39
found the error , its `module-vchan-sink` (Usage counter: 0)

purple = WS **not** infected 
orange = WS infected 
green = debian infected

![modules11111111111111111111111111111](https://cloud.githubusercontent.com/assets/11895339/12801763/22d2ff72-cad7-11e5-8e9e-f3bc0bc1bb1a.png)

Fedora-23 appvm = infected

![modules2](https://cloud.githubusercontent.com/assets/11895339/12801813/81db6c66-cad7-11e5-811a-2b0ac9ebf294.png)

`pactl list sinks `= good no difference 

`date` = good no deference

**Comment by marmarek** [comment] 2016-02-04 00:46
Usage counter should be "0", **when idle**. But should be "1" (or greater) when playing. You can also check vchan sink state - it should be "RUNNING" when playing. BTW How many sinks you have - there should only one.

**Comment by TNTBOMBOM** [comment] 2016-02-04 01:02
> Usage counter should be "0", when idle. But should be "1" (or greater) when playing. You can also check vchan sink state - it should be "RUNNING" when playing.

well then they r all the same  (damn thought we got this issue).

> BTW How many sinks you have - there should only one.

u mean this command:- 

> user@host:~$ pactl list sinks
Sink #0
	State: RUNNING
	Name: vchan_output
	Description: Qubes VCHAN sink
	Driver: module-vchan-sink.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 4
	Mute: no
	Volume: front-left: 81920 / 125% / 5.81 dB,   front-right: 81920 / 125% / 5.81 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: vchan_output.monitor
	Latency: 0 usec, configured 46439 usec
	Flags: DECIBEL_VOLUME LATENCY 
	Properties:
		device.string = "vchan_output"
		device.description = "Qubes VCHAN sink"
		device.icon_name = "audio-card"
	Formats:
		pcm

so i think these commands they look like all having the same results , do u have more ?

**Comment by marmarek** [comment] 2016-02-04 01:27
The same - only one. It must be something else...

**Comment by TNTBOMBOM** [comment] 2016-02-04 01:37
hmm well here is a pic of `pactl list sinks` from 
- Purple = WS-appvm **not** infected
- Orange = WS-appvm infected 
- Blue = Fedora-23 appvm  infecte

![modules33333333333333333333333](https://cloud.githubusercontent.com/assets/11895339/12803097/ce6644e0-cadf-11e5-8c25-4a54089d2add.png)

**Comment by marmarek** [comment] 2016-02-04 02:29
Check how that looks during some video playing

**Comment by TNTBOMBOM** [comment] 2016-02-04 03:05
- Purple = WS-appvm not infected
- Orange = WS-appvm infected
- Blue = Fedora-23 appvm infected
- Green = debian-standaloneVM infected

![modules4444444444444444444444444](https://cloud.githubusercontent.com/assets/11895339/12804524/ee3e9dd8-caeb-11e5-8f8d-2f9cd51fed3c.png)

**Comment by adrelanos** [comment] 2016-05-10 19:28
I am also experienced this bug.

It happened to me while I tried to get sound to work over (intel audio) hdmi. In `pavucontrol` Conflagration I have set to `Digital Stereo (HDMI 2) Output`. (The others were marked as `(Unplugged)`.) Then it started.

After setting it to `Digital Surround 5.1 (HDMI 2) Output` the video speedup bug stopped and HDMI sound worked. Seems reproducible. Although switching back and forth broke HDMI sound again.

Any more debug output required for this?

**Comment by marmarek** [comment] 2016-05-10 19:33
Take a look at `pactl list` and compare output between working and not working settings.

**Comment by adrelanos** [comment] 2016-05-14 01:43
`pactl list` outputs...

* [analog_stero_duplex_audio_without_audio_lag.txt](https://github.com/QubesOS/qubes-issues/files/264292/analog_stero_duplex_audio_without_audio_lag.txt) - working state, but analog audio only (notebook speakers or 3.5 out)
* [hdmi_audio_with_audio_lag.txt](https://github.com/QubesOS/qubes-issues/files/264293/hdmi_audio_with_audio_lag.txt) - actually, it did not fully work. Audio is ~ 3 seconds too late.
* [hdmi_audio_with_video_super_speedup.txt](https://github.com/QubesOS/qubes-issues/files/264294/hdmi_audio_with_video_super_speedup.txt) - Reproduced that state where videos run super fast.

`diff hdmi_audio_with_audio_lag.txt hdmi_audio_with_video_super_speedup.txt`
``` 
40c40
<       Usage counter: 1
---
>       Usage counter: 4
227c227,320
< Sink Input #40
---
> Sink Input #42
>       Driver: protocol-native.c
>       Owner Module: 6
>       Client: 40
>       Sink: 0
>       Sample Specification: float32le 2ch 44100Hz
>       Channel Map: front-left,front-right
>       Format: pcm, format.sample_format = "\"float32le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
>       Corked: yes
>       Mute: no
>       Volume: front-left: 81920 / 125% / 5.81 dB,   front-right: 81920 / 125% / 5.81 dB
>               balance 0.00
>       Buffer Latency: 100000 usec
>       Sink Latency: 0 usec
>       Resample method: copy
>       Properties:
>               media.name = "AudioStream"
>               application.name = "CubebUtils"
>               native-protocol.peer = "UNIX socket client"
>               native-protocol.version = "29"
>               application.process.id = "5617"
>               application.process.user = "user"
>               application.process.host = "social"
>               application.process.binary = "iceweasel"
>               window.x11.display = ":0"
>               application.language = "en_US.UTF-8"
>               application.process.machine_id = "360b0ab67e13483195c906dbc0c08d2f"
>               application.process.session_id = "c1"
>               application.icon_name = "iceweasel"
>               module-stream-restore.id = "sink-input-by-application-name:CubebUtils"
> 
> Sink Input #43
>       Driver: protocol-native.c
>       Owner Module: 6
>       Client: 40
>       Sink: 0
>       Sample Specification: float32le 2ch 44100Hz
>       Channel Map: front-left,front-right
>       Format: pcm, format.sample_format = "\"float32le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
>       Corked: yes
>       Mute: no
>       Volume: front-left: 81920 / 125% / 5.81 dB,   front-right: 81920 / 125% / 5.81 dB
>               balance 0.00
>       Buffer Latency: 82585 usec
>       Sink Latency: 0 usec
>       Resample method: copy
>       Properties:
>               media.name = "AudioStream"
>               application.name = "CubebUtils"
>               native-protocol.peer = "UNIX socket client"
>               native-protocol.version = "29"
>               application.process.id = "5617"
>               application.process.user = "user"
>               application.process.host = "social"
>               application.process.binary = "iceweasel"
>               window.x11.display = ":0"
>               application.language = "en_US.UTF-8"
>               application.process.machine_id = "360b0ab67e13483195c906dbc0c08d2f"
>               application.process.session_id = "c1"
>               application.icon_name = "iceweasel"
>               module-stream-restore.id = "sink-input-by-application-name:CubebUtils"
> 
> Sink Input #45
>       Driver: protocol-native.c
>       Owner Module: 6
>       Client: 40
>       Sink: 0
>       Sample Specification: float32le 2ch 44100Hz
>       Channel Map: front-left,front-right
>       Format: pcm, format.sample_format = "\"float32le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
>       Corked: yes
>       Mute: no
>       Volume: front-left: 81920 / 125% / 5.81 dB,   front-right: 81920 / 125% / 5.81 dB
>               balance 0.00
>       Buffer Latency: 100000 usec
>       Sink Latency: 0 usec
>       Resample method: copy
>       Properties:
>               media.name = "AudioStream"
>               application.name = "CubebUtils"
>               native-protocol.peer = "UNIX socket client"
>               native-protocol.version = "29"
>               application.process.id = "5617"
>               application.process.user = "user"
>               application.process.host = "social"
>               application.process.binary = "iceweasel"
>               window.x11.display = ":0"
>               application.language = "en_US.UTF-8"
>               application.process.machine_id = "360b0ab67e13483195c906dbc0c08d2f"
>               application.process.session_id = "c1"
>               application.icon_name = "iceweasel"
>               module-stream-restore.id = "sink-input-by-application-name:CubebUtils"
> 
> Sink Input #46
299c392
< Client #42
---
> Client #45
306c399
<               application.process.id = "5728"
---
>               application.process.id = "5850"
```

**Comment by marmarek** [comment] 2016-05-14 19:12
I meant `pactl list` in dom0...

**Comment by adrelanos** [comment] 2016-05-14 21:00
I needed to install pulseaudio-utils beforehand.

```
sudo qubes-dom0-update pulseaudio-utils
```

-----

* [dom0_analog_stereo_duplex_without_audio_lag.txt](https://github.com/QubesOS/qubes-issues/files/264691/dom0_analog_stereo_duplex_without_audio_lag.txt) - During a state were analog audio worked.
* [dom0_hdmi_audio_with_lag_probably.txt](https://github.com/QubesOS/qubes-issues/files/264692/dom0_hdmi_audio_with_lag_probably.txt) - (I would probably have to reboot to make audio actually work again. But this was the setting were audio lagged.)
* [dom0_hdmi_audio_with_video_too_fast.txt](https://github.com/QubesOS/qubes-issues/files/264693/dom0_hdmi_audio_with_video_too_fast.txt) - Video too fast. Always reproducible with that setting.
* [dom0_analog_stereo_duplex_same_setting_with_lag.txt](https://github.com/QubesOS/qubes-issues/files/264694/dom0_analog_stereo_duplex_same_setting_with_lag.txt) - Reset to analog audio but now also with lag. Would probably have to reboot to fix at least that one.

**Comment by marmarek** [comment] 2016-05-15 10:11
Interesting - you have "combine" module enabled. Even more interesting - in cases "with lag" there is no real sound card sink present.
Try disabling "combine" - either unload the module with `pactl unload-module module-combine-sink`, or disable it in `paprefs` GUI tool.

**Comment by adrelanos** [comment] 2016-05-15 20:17
Disabled it using paprefs. Fortunately, I do personally not require simultaneous hdmi and analog audio. This helped, no more video super speedup, but still audio lag over hdmi.

* [dom0_analog_audio_duplex_all_fine.txt](https://github.com/QubesOS/qubes-issues/files/265218/dom0_analog_audio_duplex_all_fine.txt)
* [dom0_hdmi_audio_one_sec_lag.txt](https://github.com/QubesOS/qubes-issues/files/265217/dom0_hdmi_audio_one_sec_lag.txt)
* [dom0_hdmi_no_video_speedup_but_audio_decync.txt](https://github.com/QubesOS/qubes-issues/files/265219/dom0_hdmi_no_video_speedup_but_audio_decync.txt)

**Comment by TNTBOMBOM** [comment] 2016-12-16 20:55
good thing @adrelanos figured it out , actually just turning on/off the built-in audio is giving direct effect on the speed inside the virtual machine.

OFF = normal , ON = hyper-speed . 

this problem still exist in Qubes 3.2 fresh installation

**Comment by andrewdavidwong** [comment] 2019-04-01 04:09
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by TNTBOMBOM** [comment] 2022-02-07 11:44
This issue is back again with qubes 4.1, This is a video showing whats going: 

https://user-images.githubusercontent.com/11895339/152781573-64f8498b-8805-4174-818e-f20027dbf398.mp4

This is happening in debian 11, fedora 34

- Semi/Half-Solution 

I have upgraded debian to 12 and found out that the video is working with proper speed, But due to this issue #6986 pulseaudio-qubes wont work and by this the solution for video is resolved but for audio not yet.

**Comment by TNTBOMBOM** [comment] 2022-02-07 17:06
Found a work around: 

- My current Qubes setup is:

PC has no internal Audio connectivity, Connected to TV by HDMI which from it i can watch and listen.

This is what causes the issue listed above.

To resolve it: 

Bring outside headphone/set connect it to your PC, Go to qubes pulseaudio turn OFF the HDMI from the configuration and keep only the connected headphone/set.

Magic! = videos going to work with proper speed

Note: This is not considered solution, New users will suffer and very few will look into a ticket since 2016

**Closed** 2024-12-07 14:23 UTC
Labels: T: bug, P: default, hardware support, C: audio, affects-4.1, eol-4.1

**Comment by Nurmagoz** [comment] 2024-12-07 18:24
fixed?
