### ISSUE TITLE
GUI CLI integration "--restart" does not force restarts

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#9032] opened 2024-03-12 09:06 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
Calling the GUI updater from the CLI with the `--restart` parameter doesn't force the restart of affected app qubes.

### Steps to reproduce
1. `qubes-update-gui --restart`
2. Confirm that no qubes are restarted automatically
3. If any update failed, confirm that exit code is still zero

### Expected behavior
Update-affected app qubes would restart automatically without any user interaction. Either that or appear pre-selected, just waiting for the user to click "next" (but not editable).
After any failure, the exit code would be non-zero.

This is the same behavior as the CLI counterpart `qubes-vm-update --restart` in the sense that it does force the restart of app qubes. (although the restart does happen regardless of whether or not there were updates,  but that's another issue https://github.com/QubesOS/qubes-issues/issues/9031).

### Actual behavior
`--restart` option doesn't does not force the app qubes to be restarted.

**Comment by unman** [comment] 2024-03-12 13:19
Is this duplicate of #9024 ?

**Comment by unman** [comment] 2024-03-12 13:35
Isnt this exacty the behavior you would expect to see given that
--restart doesnt work in the GUI?

**Comment by unman** [comment] 2024-03-12 14:13
Not being a user of the GUI I dont know how you would know this.
But if you can see that the GUI launches without that option being
selected, you are right, this is probably a separate issue. But the
solution may be the same.

**Closed as completed** 2024-06-28 16:10 UTC
Labels: C: Qubes GUI tools, P: default, diagnosed, pr submitted, C: updates, affects-4.2
