### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qubes-appmenus-qubes-start.desktop'

### ISSUE THREAD

**Issue by michaljenicek** [QubesOS/qubes-issues#4684] opened 2019-01-04 21:08 UTC
### Qubes OS version:

I have problems starting windows 7 apps in seamless mode. When I start the app, it only starts the VM but doesn't start the app itself.

When I run the command qvm-sync-appmenus, I get error: `FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qubes-appmenus-qubes-start.desktop'`.

I tried `sudo touch /usr/share/qubes-appmenus/qubes-start.desktop` as suggested [here](https://qubes-os.info/index.php?t=msg&goto=922&), which makes the command qvm-sync-appmenus go without error and it propagates the apps into the menu, but when I try to run the apps, nothing happens anyway.

I tried running the apps from the terminal as well with `qvm-run` as described on the website, but that doesn't work either.

### Affected component(s): 

---

### Steps to reproduce the behavior:

I followed instructions on the [website](https://www.qubes-os.org/doc/windows-vm/) and installed windows 7 without problems and I installed the qubes windows tools as described in this thread without problems as well.

### Expected behavior:

Open windows 7 apps in seamless mode.

### Actual behavior:

Apps don't open.

### General notes:

---

**Comment by andrewdavidwong** [comment] 2019-01-05 03:03
Possible duplicate of #3311.

**Comment by michaljenicek** [comment] 2019-04-26 21:12
Would anyone be able to help me please? I still haven't been able to resolve my issue.

I'm 100 % sure that my seamless mode is working in windows (viz screenshots below).

The problem is that I'm unable to run any apps either from the terminal, nor from the app menu. All the apps show correctly in the menu, but when I click on them, nothing happens.

![Screenshot_2019-04-26_20-43-52](https://user-images.githubusercontent.com/21178057/56836777-bccd4480-6867-11e9-9b4e-a0c9cd17c187.png)

![Screenshot_2019-04-26_20-55-47](https://user-images.githubusercontent.com/21178057/56836797-cbb3f700-6867-11e9-8142-0d262a6640ea.png)

When I try to run the qvm-sync-appmenus command, I get the error described above.

**Comment by elliotkillick** [comment] 2019-12-08 22:10
I fixed this by copying one of the `qubes-start.desktop` file I already had in Dom0 at `~/.local/share/qubes-appmenus/<ANY QUBE>/apps.templates` to `/usr/share/qubes-appmenus`

Note: This doesn't just affect Windows qubes, it affects any HVM in general, such as sys-net.

Contents of my `qubes-start.desktop` file:

```
[Desktop Entry]
Version=1.0
Type=Application
Exec=qvm-start --quiet %VMNAME%
Icon=%XDGICON%
Terminal=false
Name=%VMNAME%: Start
GenericName=%VMNAME%: Start
StartupNotify=false
Categories=System;X-Qubes-VM;
```

**Comment by elliotkillick** [comment] 2020-01-01 07:04
I tried the same solution referenced in the duplicate issue and that also worked. It was simpler than what I did so that is the solution I'm using now.

The file just doesn't seem to exist on Qubes R4 (stable, up-to-date) meaning the fix is easy.

**Comment by elliotkillick** [comment] 2020-05-13 00:54
This issue doesn't seem to exist for me anymore. I deleted the `qubes-start.desktop` file I placed in `/usr/share/qubes-appmenus` and no longer receive an error when syncing appmenus with an HVM.

I think this issue can be closed now.

**Closed** 2020-05-13 09:56 UTC
Labels: C: windows-vm, P: default, T: bug, help wanted
