### ISSUE TITLE
new qubes-update-gui widget reports fedora-29 updates even though none available 

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#4593] opened 2018-12-09 23:22 UTC
### Qubes OS version:

R4.0.1_rc1 (testing?)

### Affected component(s): 

"Sunshine" `qubes-update-gui` notification icon in recent R4.0.1_rc1 (testing?) dom0 update.  

---

### Steps to reproduce the behavior:

Manually update fedora-29 template, derived templates, and standalone AppVMs based on fedora-29 or derivatives, or run the updates via the prompt after clicking the "Sunshine" icon.   

### Expected behavior:

Either the templates or standalone AppVMs should install updates for templates when `updates available` is indicated and/or the `qubes-update-gui` sunshine widget should not falsely report available updates.

### Actual behavior:

Clicking `next` in the `qubes-update-gui` widget (with all `(updates available)` templates/standalone VMs selected) then clicking the `Details` dropdown reports `SKIP (nothing to do)` for each template.  `qubes-update-gui` widget afterward remains unchanged (all updates still recommended).

### General notes:

---

### Related issues:

#4592 -- seems very likely related to the error message upon updating fedora-29 templates.

**Comment by noseshimself** [comment] 2018-12-09 23:49
Happens on 4.0, too.

**Comment by andrewdavidwong** [comment] 2018-12-10 06:35
Related (possible duplicate of): #2009.

**Comment by mossy-nw** [comment] 2018-12-11 23:23
update: with #4592 resolved (by running `sudo dnf update --enablerepo=qubes-vm-r4.0-current-testing`) this issue is now limited to the sunshine icon appearing with `Qubes Update` `Updates are available` when hovering over the icon.

**Comment by GammaSQ** [comment] 2018-12-17 13:51
I still see the tick for `fedora-29 (updates available)` entry. Just updated and rebooted, dnf reports no updates available.

**Closed** 2018-12-18 03:13 UTC
Labels: C: manager/widget, bug
