### ISSUE TITLE
Consider a built-in notification mechanism for QSBs, etc.

### ISSUE THREAD

**Issue by HW42** [QubesOS/qubes-issues#5321] opened 2019-09-16 23:55 UTC
When writing #5320, I remembered that this isn't the first time that I think it might be useful to have some notification channel built-in.

What I have in mind is basically `qubes-announce` but integrated by default. I.e, the user should be notified about important news like QSBs, in cases like QSB #46 some pre-warning (like don't update your Debian templates until we have published the QSB with instructions), maybe EOL.

This might have a feature to automatically check if the patched packages are installed.

Implementing this correctly is more tricky than it might look at first. The tricky points are proper freshness guarantees (an attacker should not be able to withhold notifications) and not introducing much new attack surface with the additional update mechanism. So the "Consider" in the title is intentional. It might be not worth the effort.

**Comment by andrewdavidwong** [comment] 2019-09-17 03:24
Duplicate of #3430

**Comment by andrewdavidwong** [comment] 2019-09-17 03:25
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-09-17 03:25 UTC
Labels: P: default, T: enhancement
