### ISSUE TITLE
Qubes Shutdown Restarts System

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#3687] opened 2018-03-09 21:28 UTC
### Qubes OS version:

R 4.0-RC4

### Affected component(s): 

Qubes System Tray "Log Out" Menu

---

### Steps to reproduce the behavior:

Goto System Tray->Log Out-> Shutdown

### Expected behavior:

Systems shuts down, computer switches off

### Actual behavior:

System shuts down and restarts - same as pressing restart button

### General notes:

---

**Comment by unman** [comment] 2018-03-09 22:16
? Works for me.
What hardware do you have?
Can you upgrade to rc5 and see if problem persists.

**Comment by no2342** [comment] 2018-03-10 16:02
I tried on two different machines now. On a Lenovo V110-15IKB with i5 8GB RAM with RC5 it works as expected although a lot of ioctl errors occur on shutdown sequence.
On my HP EliteBook 850 i7 16GB RAM with RC 4 there're also lots of ioctl errors but it ends in a kernel panic that may cause the restart. On my real old and still active R2 this never happened ;)

If I find the time I will update to RC5 and document the error list and we'll see...

**Comment by no2342** [comment] 2018-04-11 10:03
Eventually I switched to Release 4.0 and the problem persists. I receive a kernel panic at the end of each shutdown followed by a restart attempt. The system has a new installation with all current available updates. Maybe the problem are ioctl issues with my Windows HVM disks?

**Comment by esote** [comment] 2018-11-28 02:20
@andrewdavidwong The user who reported this issue has deleted their account, and so cannot give feedback if this was fixed from future updates (kernel, Xen, etc.). Should it be closed?

**Comment by andrewdavidwong** [comment] 2018-11-28 05:37
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by philipthatcher** [comment] 2020-07-10 08:53
"Qubes Shutdown Restarts System".  I'm having this occur daily, so very reproducible.  I'm using Qubes OS release 4.0.  Is there a log file I can examine and post that'll assist this investigation?

**Closed** 2023-08-05 09:24 UTC
Labels: T: bug, C: other, P: default, needs diagnosis, eol-4.0
