### ISSUE TITLE
Xfce4's panel's "System Tools"and other menu-options disappear

### ISSUE THREAD

**Issue by Stifflersmum** [QubesOS/qubes-issues#3640] opened 2018-02-28 16:11 UTC
#### Qubes OS version:
 
 
Qubes 4.0-Rc-4.

#### Affected component(s): 

Xfce4 in dom0

---

### Steps to reproduce the behavior:

Im unsure what exactly triggers this bug, it seems definitely to be related to the command 

"qvm-snc-appmenus .." , however, it only appears sometimes, and as far as i can tell, only with debian based templates so far?

### Expected behavior:

The option sytem tools,Terminal etc are listed within the xfce menu.

### Actual behavior:

Only appvms/templates are listed

### General notes:

-Logut does not solve the problem temporarily, like in the past/with 3.2.
-very annoying for people not used to a Terminal.

I wasnt able to find a workaround for this so far, for any hints id be gratefull

---

**Comment by andrewdavidwong** [comment] 2018-03-01 04:27
Duplicate of #3294

**Comment by andrewdavidwong** [comment] 2018-03-01 04:27
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-01 04:27 UTC
