### ISSUE TITLE
Debian fails to boot using in VM kernel 6.1 in PVH mode

### ISSUE THREAD

**Issue by 1cho1ce** [QubesOS/qubes-issues#8235] opened 2023-05-28 10:09 UTC
### Qubes OS release

R4.2

### Brief summary

Default debian-11 template boots successfully with in VM kernel 5.10 in PVH mode but fails with kernel 6.1 from bullseye-backports.
Fedora-37 boots successfully with in VM kernel 6.2 in PVH mode.

### Steps to reproduce

1. Install `grub2-xen-pvh` in dom0:
`sudo qubes-dom0-update grub2-xen-pvh`
2. Clone debian-11 template and install packages:
`sudo apt install linux-image-amd64 linux-headers-amd64 grub2 qubes-kernel-vm-support`
3. Install grub:
`sudo grub-install /dev/xvda`
4. Shutdown template.
5. Open template Qube settings and set kernel to `pvgrub2-pvh`.
6. Start the template.
7. See that it starts successfully with kernel 5.10.
8. Install kernel 6.1 from backports:
`sudo apt -t bullseye-backports install linux-image-amd64 linux-headers-amd64`
9. Restart the template.
10. See that template fails to boot.

### Expected behavior

Debian-11 template with kernel 6.1 boots successfully.

### Actual behavior

Debian-11 template with kernel 6.1 fails boot.

Related logs:
`/var/log/xen/console/guest-debian-11-test.log`

Successful boot with kernel 5.10:
```
[2023-05-28 10:04:20] Logfile Opened
[2023-05-28 10:04:20] .[30m.[47mWelcome to GRUB!
[2023-05-28 10:04:20] 
[2023-05-28 10:04:20] .[37m.[40m.[37m.[40m.[37m.[40m.[3;34H      [ grub-xen.cfg  424B  100%  14.79KiB/s ].[3;1Herror: no such device: /boot/xen/pvboot-x86_64.elf.
[2023-05-28 10:04:21] Reading (xen/xvda,gpt3/boot/grub/grub.cfg
[2023-05-28 10:04:21] .[H.[J.[1;1Herror: file `/boot/grub/fonts/unicode.pf2' not found.
[2023-05-28 10:04:21] error: no suitable video mode found.
[2023-05-28 10:04:21] .[3;34H      [ grub.cfg  10.11KiB  100%  29.22KiB/s ].[3;1H.[H.[J.[1;1H  Booting `Debian GNU/Linux'
[2023-05-28 10:04:21] 
[2023-05-28 10:04:21] Loading Linux 5.10.0-23-amd64 ...
[2023-05-28 10:04:21] .[4;24H      [ vmlinuz-5.10.0-23-am  6.71MiB  100%  9.90MiB/s ].[4;1HLoading initial ramdisk ...
[2023-05-28 10:04:22] .[5;22H      [ initrd.img-5.10.0-23  41.44MiB  100%  32.53MiB/s ].[5;1H[    0.000000] Xen Platform PCI: unrecognised magic value
[2023-05-28 10:04:23] [    0.084137] ACPI: No IOAPIC entries present
[2023-05-28 10:04:23] [    0.133312] PCI: Fatal: No config space access function found
[2023-05-28 10:04:23] [    0.205234] ACPI: SCI (ACPI GSI 9) not registered
[2023-05-28 10:04:23] [    0.206373] ACPI Error: No handler or method for GPE 00, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:23] [    0.206391] ACPI Error: No handler or method for GPE 01, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:23] [    0.206414] ACPI Error: No handler or method for GPE 03, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:23] [    0.206429] ACPI Error: No handler or method for GPE 04, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:23] [    0.206444] ACPI Error: No handler or method for GPE 05, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:23] [    0.206460] ACPI Error: No handler or method for GPE 06, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:23] [    0.206475] ACPI Error: No handler or method for GPE 07, disabling event (20200925/evgpe-839)
[2023-05-28 10:04:29] Setting up swapspace version 1, size = 1073737728 bytes
[2023-05-28 10:04:29] UUID=a4a99611-17f0-4672-9979-1e12bfa64089
[2023-05-28 10:04:29] /dev/xvda3: clean, 127663/1299984 files, 1268494/5190656 blocks
[2023-05-28 10:04:31] 
[2023-05-28 10:04:31] Debian GNU/Linux 11 debian-11-test hvc0
[2023-05-28 10:04:31] 
[2023-05-28 10:04:31] debian-11-test login: 
```

Failed boot with kernel 6.1:
```
[2023-05-28 09:49:25] Logfile Opened
[2023-05-28 09:49:25] .[30m.[47mWelcome to GRUB!
[2023-05-28 09:49:25] 
[2023-05-28 09:49:25] .[37m.[40m.[37m.[40m.[37m.[40m.[3;34H      [ grub-xen.cfg  424B  100%  13.80KiB/s ].[3;1Herror: no such device: /boot/xen/pvboot-x86_64.elf.
[2023-05-28 09:49:25] Reading (xen/xvda,gpt3/boot/grub/grub.cfg
[2023-05-28 09:49:25] .[H.[J.[1;1Herror: file `/boot/grub/fonts/unicode.pf2' not found.
[2023-05-28 09:49:25] error: no suitable video mode found.
[2023-05-28 09:49:25] .[3;34H      [ grub.cfg  20.88KiB  100%  57.37KiB/s ].[3;1H.[H.[J.[1;1H  Booting `Debian GNU/Linux'
[2023-05-28 09:49:25] 
[2023-05-28 09:49:25] Loading Linux 6.1.0-0.deb11.7-amd64 ...
[2023-05-28 09:49:25] .[4;24H      [ vmlinuz-6.1.0-0.deb1  7.53MiB  100%  9.62MiB/s ].[4;1HLoading initial ramdisk ...
[2023-05-28 09:49:26] .[5;22H      [ initrd.img-6.1.0-0.d  56.97MiB  100%  32.44MiB/s ].[5;1H[    0.000000] platform_pci_unplug: Xen Platform PCI: unrecognised magic value
[2023-05-28 09:49:27] [    0.087078] ACPI: No IOAPIC entries present
[2023-05-28 09:49:27] [    0.130572] PCI: Fatal: No config space access function found
[2023-05-28 09:49:27] [    0.149815] ACPI: OSL: SCI (ACPI GSI 9) not registered
[2023-05-28 09:49:27] [    0.152550] ACPI Error: No handler or method for GPE 00, disabling event (20220331/evgpe-839)
[2023-05-28 09:49:27] [    0.152569] ACPI Error: No handler or method for GPE 01, disabling event (20220331/evgpe-839)
[2023-05-28 09:49:27] [    0.152589] ACPI Error: No handler or method for GPE 03, disabling event (20220331/evgpe-839)
[2023-05-28 09:49:27] [    0.152605] ACPI Error: No handler or method for GPE 04, disabling event (20220331/evgpe-839)
[2023-05-28 09:49:27] [    0.152620] ACPI Error: No handler or method for GPE 05, disabling event (20220331/evgpe-839)
[2023-05-28 09:49:27] [    0.152635] ACPI Error: No handler or method for GPE 06, disabling event (20220331/evgpe-839)
[2023-05-28 09:49:27] [    0.152651] ACPI Error: No handler or method for GPE 07, disabling event (20220331/evgpe-839)
```

**Comment by 1cho1ce** [comment] 2023-05-28 10:21
I forgot to update the grub after the kernel install with:
`sudo update-grub`
It works with kernel 6.1 as well.

**Comment by 1cho1ce** [comment] 2023-05-28 11:21
I spoke too soon, I've messed with qube setting at the same time that I've updated the grub.
The debian-11 with kernel 6.1 works if I change the initial or max memory or VCPUs settings with memory balancing enabled.
I couldn't find out precise pattern that will make it boot successfully.
More initial memory will let me boot successfully. More assigned VPCUs require more memory to boot.
For initial mem - 578, max mem - 5780, VCPU - 14 (and with any more ram) debian boots successfully but fails with less init ram. But it'll boot successfully if I set initial mem to 577 and max mem to 5650 with 14 VCPUs. And also it'll boot with 577 init mem, 5770 max mem and 13 VCPUs.

**Comment by marmarek** [comment] 2023-05-28 11:32
And where the "bug" exactly is? Yes, more vcpus require more RAM to account them, that's normal thing.

**Comment by 1cho1ce** [comment] 2023-05-28 12:16
I see a problem with how much RAM debian need to boot with different kernels:
debian-11 with dom0 kernel 6.3 boots with 1 VCPU and 248 MB init RAM.
debian-11 with in VM kernel 5.10 boots with 1 VCPU and 338 MB init RAM.
debian-11 with in VM kernel 6.1 boots with 1 VCPU and 553 MB init RAM.
As compared to fedora:
fedora-37 with dom0 kernel 6.3 boots with 1 VCPU and 248 MB init RAM.
fedora-37 with in VM kernel 6.2 boots with 1 VCPU and 341 MB init RAM.

**Comment by marmarek** [comment] 2023-05-28 12:24
So, your issue seems to be that Debian's kernel requires more ram too boot, right? That's nothing specific to qubes, maybe they choose to include more features built-in by default or something like this. You may want to ask in Debian channels about that, but I guess that's just the matter of their choice, not really a bug. In any case, it doesn't seems to be a _qubes bug_, so it doesn't belong to qubes-issues. Closing.

**Closed by marmarek** 2023-05-28 12:24 UTC
Labels: T: bug, P: default

**Comment by 1cho1ce** [comment] 2023-05-28 12:53
I've tested this in KVM and there is no such problem.
debian-11-xfce using kernel 5.10 without swap can boot and login without crash with 442 MB
debian-11-xfce using kernel 6.1 without swap can boot and login without crash with 446 MB
So it's not requiring additional 215 MB to boot with newer kernel compared to Qubes.
Maybe it's a Xen bug, but I can't test it on bare Xen.

**Comment by andrewdavidwong** [comment] 2023-05-28 13:07
This issue was closed as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug, or it is not a bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
