### ISSUE TITLE
Qubes R4.1 can't install KDE.

### ISSUE THREAD

**Issue by hackerncoder** [QubesOS/qubes-issues#6202] opened 2020-11-15 22:35 UTC
**Qubes OS version**

R4.1 with current-testing enabled

**Affected component(s) or functionality**

qubes-dom0-update

**Brief summary**

When using qubes-dom0-update to install KDE Plasma, I get errors about missing group packages and then it can't install.

**How Reproducible**

Whenever I try to install kde plasma, even with a completely fresh install.

**To Reproduce**

Use `qubes-dom0-update @kde-desktop-qubes`

**Expected behavior**

Qubes should install KDE Plasma

**Actual behavior**

I get errors about group packages missing.

**Screenshots**

N/A

**Additional context**

[user@dom0 ~]$ sudo qubes-dom0-update @kde-desktop-qubes
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Fedora 32 - x86_64 - Updates                    7.3 MB/s |  27 MB     00:03    
Fedora 32 - x86_64                               15 MB/s |  70 MB     00:04    
Qubes Dom0 Repository (updates)                 1.9 MB/s | 1.1 MB     00:00    
determining the fastest mirror (15 hosts).. done.--  B/s |   0  B     --:-- ETA
Qubes Templates repository                      1.7 kB/s | 1.6 kB     00:00    
No match for group package "kdepasswd"
No match for group package "qubes-kde-dom0"
No match for group package "xsettings-kde"
No match for group package "plasma-workspace-drkonqi"
No match for group package "kcm-gtk"
No match for group package "phonon-backend-gstreamer"
No match for group package "ksnapshot"
Dependencies resolved.

*Truncated*  

Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Qubes OS Repository for Dom0                                 3.0 MB/s | 3.0 kB     00:00    
Qubes OS Repository for Dom0                                  86 MB/s | 567 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Sun 15 Nov 2020 23:08:02 CET.
Module or Group 'kde-desktop-qubes' is not available.
Error: Nothing to do.
[user@dom0 ~]$ 

**Solutions you've tried**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

qubes-os.org/doc/kde

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by andrewdavidwong** [comment] 2020-11-16 05:38
Duplicate of #2921

**Comment by andrewdavidwong** [comment] 2020-11-16 05:38
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-11-16 05:38 UTC
Labels: P: default, T: bug
