### ISSUE TITLE
Experimental upgrade procedures fails on Debian-based TemplateVMs

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2224] opened 2016-08-02 23:17 UTC
#### Qubes OS version (e.g., `R3.1`):

`R3.1`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`debian-8`

---

[On 2016-08-02 04:19, hedron@[...].com wrote:](https://groups.google.com/d/msgid/qubes-users/KO6kF0M--3-0%40tutanota.com)
> Summary of Problem: During a fresh installation of Qubes R3.1, all restored
> Debian TemplateVMs crash during the apt-get dist-upgrade and can no longer be
> restarted.
> 
> Details: My preferred Qubes upgrade method is to do a fresh install to a new
> disk and backup/restore AppVMs and TemplateVMs from the previous version.
> This has highlighted two problems (the minor one first):
> 
> 1. The documentation at
> https://www.qubes-os.org/doc/releases/3.1/release-notes/#upgrading details
> two upgrade methods: [quote]The easiest and safest way to upgrade to Qubes
> R3.1 is to install it fromscratch and use qubes backup and restore tools
> formigrating of all of the user VMs. Users of Qubes R3.0 can upgrade using
> experimentalprocedure.[/quote]
> 
> 
> 
> I can find no reference in the fresh-installation instructions for upgrading
> the TemplateVMs, which only seems to be mentioned in the "experimental
> method" section. Perhaps the term "experimental" is no longer appropriate
> and, if so, should ideally be dropped.
> 
> 2. After a fresh installation of R3.1, I restored all AppVMs, HVMs and
> TemplateVMs (from R3.0) to the new system, I upgraded the Fedora TemplateVMs
> without problem using the "experimental" procedure but ALL 3 of my
> Debian-based TemplateVMs crash during the apt-get dist-upgrade step, leaving
> the VMs in an unusable state (cannot be restarted).
> 
> Since this is consistent across all three of my Debian-based TemplateVMs
> (debian-8, debian-8-nonfree and debian-8-sandbox) it seems likely to be a
> bug. Right now, I've restored all three from backup and they are still usable
> in R3.0 form but some things (eg VM Manager Update) no longer work.
> 
> Is this a known problem? Is there a solution or workaround?
>

**Comment by unman** [comment] 2016-10-08 00:33
@andrewdavidwong 
I've been unable to reproduce this.
The 3.0/3.1 upgrade path worked fine for me. Just to check, I've tried on a clean install of 3.1 and used Debian templates from the 3.0 installer, Jessie and an old wheezy template. Both updated properly to a stable Jessie 3.1.
I suggest closing this.

**Closed** 2016-10-09 01:17 UTC
Labels: bug, C: Debian

**Comment by marmarek** [comment] 2017-11-21 12:12
> The package qubes-core-dom0-4.0.14-1.fc25 has been pushed to the r4.0 testing repository for dom0.

Wrong ticket number...
