### ISSUE TITLE
Whonix-gw will not respond after update

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#4443] opened 2018-10-27 09:51 UTC
### Qubes OS version:
R4.0
### Affected component(s): 
Whonix-gw template vm

### Steps to reproduce the behavior:
Update dom0, update and upgrade whonix-gw, try to launch terminal from Dom0 or from the UI

### Expected behavior
Konsole launches

### Actual behavior:
VM starts but apps don't run

### General notes:
After updating dom0 and then upgrading whonix-gw I can no longer run any apps (eg konsole, dolphin) on whonix-gw. It starts but is unresponsive. I haven't tested whonix-ws yet.

**Comment by andrewdavidwong** [comment] 2018-10-27 23:06
Do you know which packages were updated and their version numbers?

**Comment by JPL1** [comment] 2018-10-28 15:05
No, I hadn't updated for about three weeks though, and I haven't added any packages to the default template if that's any help

**Comment by andrewdavidwong** [comment] 2018-10-28 21:13
> No, I hadn't updated for about three weeks though, and I haven't added any packages to the default template if that's any help

If it would be useful for whoever works on this issue (@adrelanos?), perhaps you could [check your update history](https://askubuntu.com/questions/14328/where-can-i-look-up-my-update-history) and provide the packages and version numbers here.

**Comment by adrelanos** [comment] 2018-10-30 09:04
Do we have Qubes general "VM does not boot" debugging instructions somewhere?

No updates from Whonix side that may be causing this as far as I can think off. This would be more like a dom0 and/or qubes-core-agent-linux issue where Debian should be equally effected.

Let me try to help. Few commands that may help to debug this.

    qvm-shutdown sys-whonix

(Just to make sure it is gone.)

    qvm-kill sys-whonix

Start.

    qvm-start sys-whonix

Any qrexec errors?

Start konsole from dom0 terminal.

    qvm-run --pass-io sys-whonix konsole

See what xl console is showing us.

    sudo xl console sys-whonix

Type `user` <enter> to login.

    sudo systemctl --failed list-units

.

    whonixcheck

**Comment by dephekt** [comment] 2018-11-03 07:48
> This would be more like a dom0 and/or qubes-core-agent-linux issue where Debian should be equally effected.

I can update dom0 and the template VMs for debian-9 and fedora-26, restart the app VMs, then can still run whonix check and get Tor connectivity, despite getting a warning that I need to upgrade. It's immediately after upgrading the `whonix-gw` and `whonix-ws` template VMs and restarting `sys-whonix` where Whonix functionality is lost.

To reproduce, after a fresh install of Qubes R4, via Qube Manager, I upgrade `dom0` and the `debian-9`, `fedora-26` template VMs and restart dependent app VMs. I do a whonix check and everything is working still.

Then I upgrade `whonix-gw` template VM. After the upgrade, I shut down the template VM and restart `sys-whonix` and after it comes back up, I'm no longer able to get Konsole or whonix check to respond.

> Do you know which packages were updated and their version numbers?

@andrewdavidwong Indeed. There are 125 upgraded, 5 newly installed, 2 to remove:

```
user@host:~$ sudo apt list --upgradable
Listing... Done                                                                                                
base-files/oldstable 8+deb8u11 amd64 [upgradable from: 8+deb8u10]                                              
bind9-host/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]                        
ca-certificates/oldstable 20141019+deb8u4 all [upgradable from: 20141019+deb8u3]                                   
curl/oldstable 7.38.0-4+deb8u12 amd64 [upgradable from: 7.38.0-4+deb8u10]                                                   
dnsutils/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]                                   
file/oldstable 1:5.22+15-2+deb8u4 amd64 [upgradable from: 1:5.22+15-2+deb8u3]                                               
fuse/oldstable 2.9.3-15+deb8u3 amd64 [upgradable from: 2.9.3-15+deb8u2]                                                                       
gnupg/oldstable,oldstable 1.4.18-7+deb8u5 amd64 [upgradable from: 1.4.18-7+deb8u4]                                                            
gnupg-agent/oldstable,oldstable 2.0.26-6+deb8u2 amd64 [upgradable from: 2.0.26-6+deb8u1]                                                      
gnupg2/oldstable,oldstable 2.0.26-6+deb8u2 amd64 [upgradable from: 2.0.26-6+deb8u1]                                                              
gpgv/oldstable,oldstable 1.4.18-7+deb8u5 amd64 [upgradable from: 1.4.18-7+deb8u4]                                                                    
imagemagick/oldstable 8:6.8.9.9-5+deb8u14 amd64 [upgradable from: 8:6.8.9.9-5+deb8u11]                                                               
imagemagick-6.q16/oldstable 8:6.8.9.9-5+deb8u14 amd64 [upgradable from: 8:6.8.9.9-5+deb8u11]                                                            
imagemagick-common/oldstable 8:6.8.9.9-5+deb8u14 all [upgradable from: 8:6.8.9.9-5+deb8u11]                                                                
libbind9-90/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]                                                                   
libcups2/oldstable 1.7.5-11+deb8u4 amd64 [upgradable from: 1.7.5-11+deb8u2]                                                                                                     
libcupsimage2/oldstable 1.7.5-11+deb8u4 amd64 [upgradable from: 1.7.5-11+deb8u2]                                                                                                
libcurl3/oldstable 7.38.0-4+deb8u12 amd64 [upgradable from: 7.38.0-4+deb8u10]                                                                                                   
libcurl3-gnutls/oldstable 7.38.0-4+deb8u12 amd64 [upgradable from: 7.38.0-4+deb8u10]
libdns-export100/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libdns100/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libexiv2-13/oldstable 0.24-4.1+deb8u2 amd64 [upgradable from: 0.24-4.1]
libfaad2/oldstable 2.7-8+deb8u1 amd64 [upgradable from: 2.7-8]
libfuse2/oldstable 2.9.3-15+deb8u3 amd64 [upgradable from: 2.9.3-15+deb8u2]
libgcrypt20/oldstable 1.6.3-2+deb8u5 amd64 [upgradable from: 1.6.3-2+deb8u4]
libgnutls-deb0-28/oldstable 3.3.30-0+deb8u1 amd64 [upgradable from: 3.3.8-6+deb8u7]
libgnutls-openssl27/oldstable 3.3.30-0+deb8u1 amd64 [upgradable from: 3.3.8-6+deb8u7]
libgs9/oldstable 9.06~dfsg-2+deb8u11 amd64 [upgradable from: 9.06~dfsg-2+deb8u6]
libgs9-common/oldstable 9.06~dfsg-2+deb8u11 all [upgradable from: 9.06~dfsg-2+deb8u6]
libidn11/oldstable 1.29-1+deb8u3 amd64 [upgradable from: 1.29-1+deb8u2]
libirs-export91/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libisc-export95/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libisc95/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libisccc90/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libisccfg-export90/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libisccfg90/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
liblcms2-2/oldstable 2.6-3+deb8u2 amd64 [upgradable from: 2.6-3+deb8u1]
libldap-2.4-2/oldstable 2.4.40+dfsg-1+deb8u4 amd64 [upgradable from: 2.4.40+dfsg-1+deb8u3]
liblwres90/oldstable 1:9.9.5.dfsg-9+deb8u16 amd64 [upgradable from: 1:9.9.5.dfsg-9+deb8u15]
libmad0/oldstable,oldstable 0.15.1b-8+deb8u1 amd64 [upgradable from: 0.15.1b-8]
libmagic1/oldstable 1:5.22+15-2+deb8u4 amd64 [upgradable from: 1:5.22+15-2+deb8u3]
libmagickcore-6.q16-2/oldstable 8:6.8.9.9-5+deb8u14 amd64 [upgradable from: 8:6.8.9.9-5+deb8u11]
libmagickwand-6.q16-2/oldstable 8:6.8.9.9-5+deb8u14 amd64 [upgradable from: 8:6.8.9.9-5+deb8u11]
libmp3lame0/oldstable 3.99.5+repack1-7+deb8u2 amd64 [upgradable from: 3.99.5+repack1-7+deb8u1]
libncurses5/oldstable 5.9+20140913-1+deb8u3 amd64 [upgradable from: 5.9+20140913-1+deb8u2]
libncursesw5/oldstable 5.9+20140913-1+deb8u3 amd64 [upgradable from: 5.9+20140913-1+deb8u2]
libokularcore5/oldstable 4:4.14.2-2+deb8u1 amd64 [upgradable from: 4:4.14.2-2]
libpolkit-agent-1-0/oldstable 0.105-15~deb8u3 amd64 [upgradable from: 0.105-15~deb8u2]
libpolkit-backend-1-0/oldstable 0.105-15~deb8u3 amd64 [upgradable from: 0.105-15~deb8u2]
libpolkit-gobject-1-0/oldstable 0.105-15~deb8u3 amd64 [upgradable from: 0.105-15~deb8u2]
libpoppler-qt4-4/oldstable 0.26.5-2+deb8u5 amd64 [upgradable from: 0.26.5-2+deb8u3]
libpoppler46/oldstable 0.26.5-2+deb8u5 amd64 [upgradable from: 0.26.5-2+deb8u3]
libprocps3/oldstable,oldstable 2:3.3.9-9+deb8u1 amd64 [upgradable from: 2:3.3.9-9]
libpython2.7/oldstable 2.7.9-2+deb8u2 amd64 [upgradable from: 2.7.9-2+deb8u1]
libpython2.7-minimal/oldstable 2.7.9-2+deb8u2 amd64 [upgradable from: 2.7.9-2+deb8u1]
libpython2.7-stdlib/oldstable 2.7.9-2+deb8u2 amd64 [upgradable from: 2.7.9-2+deb8u1]
libpython3.4-minimal/oldstable 3.4.2-1+deb8u1 amd64 [upgradable from: 3.4.2-1]
libpython3.4-stdlib/oldstable 3.4.2-1+deb8u1 amd64 [upgradable from: 3.4.2-1]
libqrexec-utils2/unknown 4.0.21+deb8u1 amd64 [upgradable from: 4.0.17+deb8u1]
libqubes-rpc-filecopy2/unknown 4.0.21+deb8u1 amd64 [upgradable from: 4.0.17+deb8u1]
libqubesdb/unknown 4.0.10-1+deb8u1 amd64 [upgradable from: 4.0.5-1+deb8u1]
libruby2.1/oldstable 2.1.5-2+deb8u6 amd64 [upgradable from: 2.1.5-2+deb8u3]
libsdl-image1.2/oldstable,oldstable 1.2.12-5+deb8u1 amd64 [upgradable from: 1.2.12-5+b5]
libsmbclient/oldstable 2:4.2.14+dfsg-0+deb8u10 amd64 [upgradable from: 2:4.2.14+dfsg-0+deb8u9]
libsoup-gnome2.4-1/oldstable 2.48.0-1+deb8u2 amd64 [upgradable from: 2.48.0-1+deb8u1]
libsoup2.4-1/oldstable 2.48.0-1+deb8u2 amd64 [upgradable from: 2.48.0-1+deb8u1]
libssh-gcrypt-4/oldstable 0.6.3-4+deb8u3 amd64 [upgradable from: 0.6.3-4+deb8u2]
libssl1.0.0/oldstable 1.0.1t-1+deb8u9 amd64 [upgradable from: 1.0.1t-1+deb8u7]
libtag1-vanilla/oldstable 1.9.1-2.1+deb8u1 amd64 [upgradable from: 1.9.1-2.1]
libtag1c2a/oldstable 1.9.1-2.1+deb8u1 amd64 [upgradable from: 1.9.1-2.1]
libtiff5/oldstable 4.0.3-12.3+deb8u7 amd64 [upgradable from: 4.0.3-12.3+deb8u5]
libtinfo5/oldstable 5.9+20140913-1+deb8u3 amd64 [upgradable from: 5.9+20140913-1+deb8u2]
libvchan-xen/unknown 4.0.5-1+deb8u1 amd64 [upgradable from: 4.0.1-1+deb8u1]
libvncclient0/oldstable,oldstable 0.9.9+dfsg2-6.1+deb8u3 amd64 [upgradable from: 0.9.9+dfsg2-6.1+deb8u2]
libwbclient0/oldstable 2:4.2.14+dfsg-0+deb8u10 amd64 [upgradable from: 2:4.2.14+dfsg-0+deb8u9]
libx11-6/oldstable 2:1.6.2-3+deb8u2 amd64 [upgradable from: 2:1.6.2-3+deb8u1]
libx11-data/oldstable 2:1.6.2-3+deb8u2 all [upgradable from: 2:1.6.2-3+deb8u1]
libx11-xcb1/oldstable 2:1.6.2-3+deb8u2 amd64 [upgradable from: 2:1.6.2-3+deb8u1]
libxcursor1/oldstable 1:1.1.14-1+deb8u2 amd64 [upgradable from: 1:1.1.14-1+deb8u1]
libxen-4.8/unknown 2001:4.8.4-3+deb8u1 amd64 [upgradable from: 2001:4.8.3-4+deb8u1]
libxen-lowlevel1.0/unknown 2001:4.8.4-3+deb8u1 amd64 [upgradable from: 2001:4.8.3-4+deb8u1]
libxenstore3.0/unknown 2001:4.8.4-3+deb8u1 amd64 [upgradable from: 2001:4.8.3-4+deb8u1]
libxml2/oldstable 2.9.1+dfsg1-5+deb8u7 amd64 [upgradable from: 2.9.1+dfsg1-5+deb8u6]
libxml2-utils/oldstable 2.9.1+dfsg1-5+deb8u7 amd64 [upgradable from: 2.9.1+dfsg1-5+deb8u6]
linux-base/oldstable 4.5~deb8u1 all [upgradable from: 3.5]
linux-image-amd64/oldstable 3.16+63+deb8u3 amd64 [upgradable from: 3.16+63+deb8u1]
linux-libc-dev/oldstable 3.16.59-1 amd64 [upgradable from: 3.16.51-3+deb8u1]
ncurses-base/oldstable 5.9+20140913-1+deb8u3 all [upgradable from: 5.9+20140913-1+deb8u2]
ncurses-bin/oldstable 5.9+20140913-1+deb8u3 amd64 [upgradable from: 5.9+20140913-1+deb8u2]
ncurses-term/oldstable 5.9+20140913-1+deb8u3 all [upgradable from: 5.9+20140913-1+deb8u2]
okular/oldstable 4:4.14.2-2+deb8u1 amd64 [upgradable from: 4:4.14.2-2]
openssl/oldstable 1.0.1t-1+deb8u9 amd64 [upgradable from: 1.0.1t-1+deb8u7]
patch/oldstable 2.7.5-1+deb8u1 amd64 [upgradable from: 2.7.5-1]
perl/oldstable,oldstable 5.20.2-3+deb8u11 amd64 [upgradable from: 5.20.2-3+deb8u9]
perl-base/oldstable,oldstable 5.20.2-3+deb8u11 amd64 [upgradable from: 5.20.2-3+deb8u9]
perl-modules/oldstable,oldstable 5.20.2-3+deb8u11 all [upgradable from: 5.20.2-3+deb8u9]
policykit-1/oldstable 0.105-15~deb8u3 amd64 [upgradable from: 0.105-15~deb8u2]
procps/oldstable,oldstable 2:3.3.9-9+deb8u1 amd64 [upgradable from: 2:3.3.9-9]
python-libxml2/oldstable 2.9.1+dfsg1-5+deb8u7 amd64 [upgradable from: 2.9.1+dfsg1-5+deb8u6]
python-qubesdb/unknown 4.0.10-1+deb8u1 amd64 [upgradable from: 4.0.5-1+deb8u1]
python2.7/oldstable 2.7.9-2+deb8u2 amd64 [upgradable from: 2.7.9-2+deb8u1]
python2.7-minimal/oldstable 2.7.9-2+deb8u2 amd64 [upgradable from: 2.7.9-2+deb8u1]
python3.4/oldstable 3.4.2-1+deb8u1 amd64 [upgradable from: 3.4.2-1]
python3.4-minimal/oldstable 3.4.2-1+deb8u1 amd64 [upgradable from: 3.4.2-1]
qubes-core-agent/unknown 4.0.37-1+deb8u1 amd64 [upgradable from: 4.0.24-1+deb8u1]
qubes-core-agent-dom0-updates/unknown 4.0.37-1+deb8u1 amd64 [upgradable from: 4.0.24-1+deb8u1]
qubes-core-agent-networking/unknown 4.0.37-1+deb8u1 amd64 [upgradable from: 4.0.24-1+deb8u1]
qubes-core-agent-passwordless-root/unknown 4.0.37-1+deb8u1 amd64 [upgradable from: 4.0.24-1+deb8u1]
qubes-core-agent-qrexec/unknown 4.0.37-1+deb8u1 amd64 [upgradable from: 4.0.24-1+deb8u1]
qubes-gui-agent/unknown 4.0.17-1+deb8u1 amd64 [upgradable from: 4.0.9-1+deb8u1]
qubes-kernel-vm-support/unknown 4.0.21+deb8u1 amd64 [upgradable from: 4.0.17+deb8u1]
qubes-utils/unknown 4.0.21+deb8u1 amd64 [upgradable from: 4.0.17+deb8u1]
qubes-vm-dependencies/unknown 4.0.3-1+deb8u1 amd64 [upgradable from: 4.0.0-1+deb8u1]
qubesdb/unknown 4.0.10-1+deb8u1 amd64 [upgradable from: 4.0.5-1+deb8u1]
qubesdb-vm/unknown 4.0.10-1+deb8u1 amd64 [upgradable from: 4.0.5-1+deb8u1]
ruby2.1/oldstable 2.1.5-2+deb8u6 amd64 [upgradable from: 2.1.5-2+deb8u3]
ruby2.1-dev/oldstable 2.1.5-2+deb8u6 amd64 [upgradable from: 2.1.5-2+deb8u3]
samba-libs/oldstable 2:4.2.14+dfsg-0+deb8u10 amd64 [upgradable from: 2:4.2.14+dfsg-0+deb8u9]
tzdata/oldstable 2018g-0+deb8u1 all [upgradable from: 2017c-0+deb8u1]
wget/oldstable,oldstable 1.16-1+deb8u5 amd64 [upgradable from: 1.16-1+deb8u4]
whonixcheck/unknown 3:4.6.5.2-1 all [upgradable from: 3:4.6.5-1]
xdg-utils/oldstable,oldstable 1.1.0~rc1+git20111210-7.4+deb8u1 all [upgradable from: 1.1.0~rc1+git20111210-7.4]
xen-utils-common/unknown 2001:4.8.4-3+deb8u1 all [upgradable from: 2001:4.8.3-4+deb8u1]
xenstore-utils/unknown 2001:4.8.4-3+deb8u1 amd64 [upgradable from: 2001:4.8.3-4+deb8u1]
xserver-xorg-input-qubes/unknown 4.0.17-1+deb8u1 amd64 [upgradable from: 4.0.9-1+deb8u1]
xserver-xorg-video-dummyqbs/unknown 4.0.17-1+deb8u1 amd64 [upgradable from: 4.0.9-1+deb8u1]
zsh/oldstable 5.0.7-5+b1 amd64 [upgradable from: 5.0.7-5]
```

This is the output of `apt dist-upgrade`:

```
user@host:~$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... The following packages were automatically installed and are no longer required:
  gcr gnome-keyring libgck-1-0 libgcr-3-common libgcr-base-3-1 libgcr-ui-3-1 libuuid-perl p11-kit p11-kit-modules python-xpyb xserver-xorg-input-qubes
  xserver-xorg-video-dummyqbs
Use 'apt-get autoremove' to remove them.
Done
The following packages will be REMOVED:
  qubes-gui-agent qubes-vm-dependencies
The following NEW packages will be installed:
  dconf-cli firmware-linux-free irqbalance libnuma1 linux-image-3.16.0-7-amd64
The following packages will be upgraded:
  base-files bind9-host ca-certificates curl dnsutils file fuse gnupg gnupg-agent gnupg2 gpgv imagemagick imagemagick-6.q16 imagemagick-common libbind9-90 libcups2
  libcupsimage2 libcurl3 libcurl3-gnutls libdns-export100 libdns100 libexiv2-13 libfaad2 libfuse2 libgcrypt20 libgnutls-deb0-28 libgnutls-openssl27 libgs9 libgs9-common
  libidn11 libirs-export91 libisc-export95 libisc95 libisccc90 libisccfg-export90 libisccfg90 liblcms2-2 libldap-2.4-2 liblwres90 libmad0 libmagic1 libmagickcore-6.q16-2
  libmagickwand-6.q16-2 libmp3lame0 libncurses5 libncursesw5 libokularcore5 libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0 libpoppler-qt4-4 libpoppler46
  libprocps3 libpython2.7 libpython2.7-minimal libpython2.7-stdlib libpython3.4-minimal libpython3.4-stdlib libqrexec-utils2 libqubes-rpc-filecopy2 libqubesdb libruby2.1
  libsdl-image1.2 libsmbclient libsoup-gnome2.4-1 libsoup2.4-1 libssh-gcrypt-4 libssl1.0.0 libtag1-vanilla libtag1c2a libtiff5 libtinfo5 libvchan-xen libvncclient0
  libwbclient0 libx11-6 libx11-data libx11-xcb1 libxcursor1 libxen-4.8 libxen-lowlevel1.0 libxenstore3.0 libxml2 libxml2-utils linux-base linux-image-amd64 linux-libc-dev
  ncurses-base ncurses-bin ncurses-term okular openssl patch perl perl-base perl-modules policykit-1 procps python-libxml2 python-qubesdb python2.7 python2.7-minimal python3.4
  python3.4-minimal qubes-core-agent qubes-core-agent-dom0-updates qubes-core-agent-networking qubes-core-agent-passwordless-root qubes-core-agent-qrexec
  qubes-kernel-vm-support qubes-utils qubesdb qubesdb-vm ruby2.1 ruby2.1-dev samba-libs tzdata wget whonixcheck xdg-utils xen-utils-common xenstore-utils
  xserver-xorg-input-qubes xserver-xorg-video-dummyqbs zsh
125 upgraded, 5 newly installed, 2 to remove and 0 not upgraded.
Need to get 91.0 MB of archives.
After this operation, 167 MB of additional disk space will be used.
```

I'll provide the requested info from `qvm-start` and `qvm-run` invoked from a shell and will list failed systemd units in a separate comment.

**Comment by adrelanos** [comment] 2018-11-03 08:04
Dan Snider:
> The following packages will be REMOVED:
>   qubes-gui-agent qubes-vm-dependencies

These shouldn't be removed. No gui agent, no gui.

Can you please try login:

qvm-start whonix-gw
qvm-start sys-whonix

(Let's hope it's only gui that it's not working. Then sys-whonix should
still be starting and functional.)

sudo xl console whonix-gw

Then try re-install:

sudo apt-get install qubes-gui-agent

sudo apt-get install qubes-vm-dependencies

Wondering what might be the package conflict here.


Alternatively, since Whonix 13 is deprecated anyhow, this is tedious to
debug. Get Whonix 14 instead:

https://www.whonix.org/wiki/Qubes/Install

Or perhaps even better help us testing newer Whonix 14 testers-only
templates:

(these already come with all recent package upgrades since original
Whonix 14 release)

https://forums.whonix.org/t/qubes-whonix-14-templatevms-4-0-1-20181101-for-qubes-r4-testers-wanted/6240

https://www.whonix.org/wiki/Qubes/Install/Testing

**Comment by adrelanos** [comment] 2018-11-03 08:49
Dan Snider:
>> sudo apt-get install qubes-gui-agent
> 
> ```
> The following packages have unmet dependencies:
>  qubes-gui-agent : Depends: python3-xcffib but it is not going to be installed
> ```
> 
> qubes-vm-dependencies is depending on qubes-gui-agent

sudo apt-get install python3-xcffib

And so forth. Until we see the culprit.

>> Does Qubes installer come with Whonix 14
> 
> Not that was immediately apparent. The version of whonix that I'm using was installed and configured by the post-install step using the most recent release version of Qubes R4 downloaded earlier today from qubes-os.org: https://mirrors.edge.kernel.org/qubes/iso/Qubes-R4.0-x86_64.iso. From running dnf info qubes-template-whonix-gw I get:
> 
> Version: 4.0.0
> Release: 201803270426
> 
> And that's the only package available for whonix-gw out of the box.
> 

I'd hope we'd get a Qubes R4 image with Whonix 14. Much better for
usability.

More so if/after
https://forums.whonix.org/t/qubes-whonix-14-templatevms-4-0-1-20181101-for-qubes-r4-testers-wanted/6240
was blessed stable.

**Comment by dephekt** [comment] 2018-11-03 08:54
You didn't see my edits above because email, but the culprit is:

`python3-xcffib : Depends: python3-cffi-backend-api-9729 but it is not installable`

**Comment by dephekt** [comment] 2018-11-03 09:06
I removed the Whonix 13 app VMs and nuked the templates with `sudo dnf remove qubes-template-whonix*`, then ran `sudo qubesctl state.sls qvm.anon-whonix` which got me updated Whonix 14 templates and app VMs configured and everything works great now.

**Comment by marmarek** [comment] 2018-11-03 12:37
> sudo apt-get install python3-xcffib

On jessie this require enabling jessie-backports.

> I'd hope we'd get a Qubes R4 image with Whonix 14. Much better for usability.

There is 4.0.1-rc1pre2, hopefully will become 4.0.1-rc1 today/tomorrow:
https://openqa.qubes-os.org/tests/overview?distri=qubesos&version=4.0&build=4.0.1-rc1pre2&groupid=1 (choose any test and go to the download tab)

**Comment by JPL1** [comment] 2018-11-04 17:20
I guess it's not worth looking into this any further til the next update then.

**Comment by adrelanos** [comment] 2018-11-07 02:40
`qubes-gui-daemon` `rpm_spec/gui-dom0.spec.in` contains `Requires:   python3-xcffib`.

So I guess this is a `qubes-gui-daemon` bug which was recently introduced?

So in theory bug might be retitled as `qubes-gui-daemon dependency on python3-xcffib breaks Debian jessie and Whonix 13 apt-get upgrades and VM gui`.

Another maybe option (earlier, I guess now it's too late) would be to stop supplying upgrades for Qubes Debian jessie templates earlier.

Personally however, I'd not put any development effort into this and I'd say `wontfix`, "Qubes no longer supports Debian jessie / Whonix 13 and recommends using Debian stretch / Whonix 14 instead".

**Comment by andrewdavidwong** [comment] 2018-11-07 02:49
> Personally however, I'd not put any development effort into this and I'd say wontfix, "Qubes no longer supports Debian jessie / Whonix 13 and recommends using Debian stretch / Whonix 14 instead".

@marmarek's call. Whonix 13 has reached EOL, but Debian Jessie is still on LTS until 2020-06-30.

**Comment by marmarek** [comment] 2018-11-12 19:55
Yes, we do need to fix this, as Jessie is still in LTS. There is no way to enable jessie-backports in time automatically (when apt upgrade/dist-upgrade is run, it's already too late). One alternative is supplying required package(s) using qubes repositories (for jessie). This appears to be python3-xcffib and python3-cffi. I'm going this way.

**Comment by marmarek** [comment] 2018-11-14 00:49
python3-xcffib was already in our repositories for jessie. Now uploaded python3-cffi too: https://github.com/QubesOS/updates-status/issues/785
No need to enable jessie-backports anymore.

For anyone running into this problem, it should be enough to re-install `qubes-vm-dependencies` as described in https://github.com/QubesOS/qubes-issues/issues/4443#issuecomment-435568982

**Closed by marmarek** 2018-11-14 00:49 UTC
Labels: C: core, bug
