### ISSUE TITLE
Display artifacts in sys-gui

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7424] opened 2022-04-05 12:46 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
sys-gui environment shows extreme (especially on desktop) cluttering on some machines.
Cluttering fades out significantly when using other machines inside the sys-gui environment

https://user-images.githubusercontent.com/62772396/161761596-475ec913-7f7f-4a9d-ad92-c3dbc52d6cfd.mp4

### The solution you'd like
sys-gui with no to little cluttering in render

### The value to a user, and who that user might be
Reasonably usable desktop.

Note: I have QubesOS installed on two different machines with Intel Graphics 630 & RTX 2070. It runs fine on RTX2070.

**Comment by DemiMarie** [comment] 2022-04-05 20:05
Does the problem go away if you use sys-gui-gpu?

**Comment by ZYousef** [comment] 2022-04-06 11:52
@DemiMarie I tried using sys-gui-gpu , however, after attaching the gpu to sys-gui-gpu `sudo qubesctl state.sls qvm.sys-gui-gpu-attach-gpu`; the PC just keeps restarting.
The PC uses Intel Xeon E3-1200 v3/4th integrated Graphics Controller

**Comment by Arna13** [comment] 2022-04-07 16:53
I have the same problem on an i5-3320M, but with a bit less artifacts on screen with sys-gui. 
On the other hand, sys-gui-gpu works but the image looks wide (overflows the screen, right half is not visible) and green-ish tone with lots of artifacts, but the video looks smooth fairly enough. To me it looks like screen sync problems, but I dont really have much idea.

@ZYousef you might want to try to blacklist i915 and launch the vm without screen to get sys-gui-gpu working, I believe you need i915 stopped to detach and reattach an intel gpu.

**Comment by ZYousef** [comment] 2022-04-10 03:20
@Arna13 Thanks, that's exactly what I did, honestly sys-gui-gpu works like a charm! However, it's not as stable as sys-gui sometimes it won't start, still trying to figure out why.

**Comment by Arna13** [comment] 2022-04-10 08:35
@ZYousef That's great to hear, I'll try to use sys-gui-gpu on a fresh install and if I cant get it to work I'll open an issue.

**Comment by Geblaat** [comment] 2022-06-02 09:03
I'm seeing the same thing, though a little less extreme than in OP video. Disabling display compositing in window manager tweaks did not work. I can't get sys-gui-gpu set up so can't comment on whether that's better.

**Comment by dylangerdaly** [comment] 2022-06-22 03:59
I'm hitting the _exact_ same issue, I'm assuming this is fixed via switching to sys-gui? Does anyone know if there's another solution?

**Comment by DemiMarie** [comment] 2022-06-22 15:16
> I assume the actifacting comes from the fact dom0 doesn't have the correct GPU firmware, I can see it's failing to load/find the firmware for i915.

That would certainly explain it.  @marmarek any chance of getting newer firmware in dom0?

**Comment by marmarek** [comment] 2022-06-22 23:53
To clarify the above - you can get newer by just installing updates, no need for manual build: install standard updates to get 20211216, install [current-testing updates](https://www.qubes-os.org/doc/how-to-install-software-in-dom0/#testing-repositories) to get 20220610.

**Comment by dylangerdaly** [comment] 2022-06-23 00:15
Thank you for that Marek, I installed the update and can see the GPU Firmware being correctly loaded however I appear to still be getting the artifacting.

I'm not sure what the issue is or what the difference is between sys-gui-gpu and dom0

**Comment by brendanhoar** [comment] 2022-06-24 21:12
> To clarify the above - you can get newer by just installing updates, no need for manual build: install standard updates to get 20211216, install current-testing updates to get 20220610.

Hmm, I wonder if old firmware might be a factor in other issues such as the older lenovo sound problems?

B

**Comment by DemiMarie** [comment] 2022-06-24 22:16
It probably is.

**Comment by dylangerdaly** [comment] 2022-10-11 08:23
I didn't realize this was something you could do easily, am I able to update this myself? I have qubes-builder setup

-------- Original Message --------

**Closed** 2024-12-07 14:04 UTC
Labels: T: bug, C: Xen, C: gui-domain, P: default, hardware support, affects-4.1, eol-4.1
