### ISSUE TITLE
Crash when selecting directory in Backup Qubes: "QubesVMError: Cannot start Dom0 fake domain!"

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4205] opened 2018-08-11 15:56 UTC
(Edit: pressed "Submit" accidentally, sorry...)

### Qubes OS version:

Qubes R4.0

### Affected component(s):

Qubes Backup

---

### Steps to reproduce the behavior:

1. Install Qubes R4.0 with the default settings
2. Open the "Backup Qubes" application from the menu
3. Select any set of Qubes to backup
4. Click on the little "..." button next to the text box for the backup location

### Expected behavior:

A file dialog or something? I'm assuming that's what's supposed to be here.

### Actual behavior:

A "Houston, we have a problem..." popup box appears, saying it's most likely a bug in Qubes Global Settings application. The given error message is:

    QubesVMError: Cannot start Dom0 fake domain! at line 102 of file base.py.

### General notes:

This issue also affects the "Restore Backup" application, with the exact same button and error message.

**Comment by andrewdavidwong** [comment] 2018-08-11 17:15
Duplicate of #3701

**Comment by andrewdavidwong** [comment] 2018-08-11 17:15
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-11 17:15 UTC
