### ISSUE TITLE
qvm-move fails, deletes origin file anyway

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#8516] opened 2023-09-15 03:38 UTC
### Qubes OS release
R4.1.2

### Brief summary - Steps to reproduce
qvm-move file.tar
qfile-agent: Fatal error: chdir to (null) (error type: No such file or directory)
EOF

File is not moved and is deleted by qvm-move.

### Expected behavior
On qvm-move failure: file is not deleted

### Actual behavior
On qvm-move failure: file is deleted

**Comment by johnnyboy-3** [comment] 2023-09-15 03:41
I just noticed the file is rather big, >2GB

**Comment by jamke** [comment] 2023-09-15 04:57
> qvm-move file.tar

Is it a real file name? If not, does the file have something in the name? Like spaces, something like ~!@#$%^&*()_-=+, slashes, some uncommon unicode characters?

Is it reproducible for you?

@andrewdavidwong probably this one is should be major or even critical as in includes user's data loss.

**Comment by rustybird** [comment] 2023-09-15 13:17
I can reproduce it, see below.

> the source file is in ~/Qubes-Incoming/qube-name/

This is the crucial part. File size isn't relevant, except for the timing of steps 4 and 5:

1. Create VMs named vmA, vmB,  and vmC. (Actually vmA can be the same as vmC.)
2. `[user@vmA ~] truncate -s 1500M file`
3. `[user@vmA ~] qvm-copy file`
4. Select vmB as the `qubes.Filecopy` destination, and **while the copy is in progress**:
5. `[user@vmB ~] cd ~/QubesIncoming/vmA`
6. Wait for the copy to finish, then:
7. `[user@vmB ~/QubesIncoming/vmA] qvm-move file`
8. Select vmC as the `qubes.Filecopy` destination.

The file copy from vmB to vmC instantly fails with the error message mentioned in the bug report, and `file` is removed in vmB.

It works flawlessly if I run `cd .` in vmB before step 7, so the issue appears to be related to the temporary bind mount set up at `~/QubesIncoming/vmA` by the first file copy operation. And then there's a second bug that causes `qrexec-client-vm` in `qvm-move` to exit with status 0, resulting in the source file being deleted.

> probably this one is should be major or even critical as it includes user's data loss.

+1

**Comment by andrewdavidwong** [comment] 2023-09-15 13:47
It hasn't been mentioned whether this affects 4.2. Can we assume it does?

This is somewhat reminiscent of #7905, which also involved `qvm-move` deleting (without successfully copying) the source file.

**Comment by rustybird** [comment] 2023-09-15 15:13
> It hasn't been mentioned whether this affects 4.2. Can we assume it does?

Very likely :(

> This is somewhat reminiscent of #7905, which also involved `qvm-move` deleting (without successfully copying) the source file.

Spot on. The previous issue addressed the specific bug but not what looks to me like two failing safeties that would have prevented data loss here too. This now looks like a combination of

0.  Specifically for this new bug: Whatever is going on with the `qfile-agent` + stale bind mount as working directory constellation
1. `qrexec-client-vm target_vm program_ident local_program` wrongly succeeds if the `program_ident` RPC (in this case, `qubes.Filecopy`) succeeds, even if `local_program` (in this case, `qfile-agent`) fails
2. `qubes.Filecopy` wrongly succeeds on a zero-length input stream, i.e. if the sender side hung up before sending anything

**Comment by rustybird** [comment] 2023-09-16 00:36
> 0. Specifically for this new bug: Whatever is going on with the `qfile-agent` + stale bind mount as working directory constellation

When `qvm-move` (or `qvm-copy`, or their GUI equivalents) is given a relative path argument, [`qfile-agent`](https://github.com/QubesOS/qubes-core-agent-linux/blob/v4.2.21/qubes-rpc/qfile-agent.c) will first convert it to an absolute path by prepending the result of `getcwd()` and a slash. It doesn't properly check for `getcwd()` failure (which I think happens in this constellation because we're in a working directory that's part of a subtree - the temporary bind mount from the first file copy - which has already been lazily detached from the file hierarchy). But more importantly, converting the relative path to an absolute path is just wrong conceptually, and it can lead to sending the wrong file! For example:

    $ mkdir ~/dir
    $ echo old > ~/dir/file
    $ cd ~/dir
    $ sudo mount -t tmpfs tmpfs ~/dir
    $ echo new > ~/dir/file
    $ cat ~/dir/file
    new
    $ cat file
    old
    $ qvm-copy file  # this will copy ~/dir/file instead (with content "new")

**Comment by jamke** [comment] 2023-09-16 05:10
Is it somehow related? #5950

**Comment by rustybird** [comment] 2023-09-16 10:35
@jamke No with this bug (here) the bind mount is not being mounted/unmounted multiple times.

Root cause is the conversion from relative to absolute paths on a textual level. It should be possible to avoid doing that: Instead of preserving the working directory as a string obtained from `getcwd()`, let's open a dirfd for `"."`. Then before processing each argument, `fchdir()` back to that dirfd so that relative arguments can be used directly.

**Comment by DemiMarie** [comment] 2023-09-16 20:05
> * Shared with the previous issue: `qrexec-client-vm target_vm program_ident local_program` wrongly succeeds if merely the `program_ident` RPC (in this case, `qubes.Filecopy`) succeeds, even if `local_program` (in this case, `qfile-agent`) fails

This was already fixed in R4.2 by QubesOS/qubes-core-qrexec@f14c3ba655822ce41c3adcbea824c59d610bd3e0, but that commit didn’t get backported to R4.1.  I filed https://github.com/QubesOS/qubes-core-qrexec/pull/126 for the backport.

**Comment by rustybird** [comment] 2023-09-18 11:15
PipelineRetry

**Comment by jamke** [comment] 2023-10-26 16:42
Recently I had this situation with data loss. When copying **failed** for some reason, but `qvm-move` **still deleted my files**.
It happened to me on R4.1. Should the problem be considered solved for R4.1, too?

**Comment by andrewdavidwong** [comment] 2023-10-26 20:48
> Recently I had this situation with data loss. When copying **failed** for some reason, but `qvm-move` **still deleted my files**. It happened to me on R4.1. Should the problem be considered solved for R4.1, too?

I'm not sure, but I do see that @qubesos-bot posted https://github.com/QubesOS/qubes-issues/issues/8516#issuecomment-1751905301 above about 4.1 and added some 4.1 labels. Not sure whether there are more 4.1 updates still to come for this, though.

**Comment by rustybird** [comment] 2023-10-29 11:04
@jamke Do you remember any details?

The R4.1 backport of Demi's general fix was [stabilized on 2023-09-26](https://github.com/QubesOS/updates-status/issues/4061#issuecomment-1734698359). If your sender side had the core-qrexec 4.1.23+ packages, theoretically that should have prevented data loss - assuming that `qfile-agent` *correctly terminated unsuccessfully* on error.

There's also a new belts-and-suspenders [early EOF check](https://github.com/QubesOS/qubes-linux-utils/pull/105) to prevent data loss even on *wrongly successful exit*, but that one hasn't been cherry-picked for R4.1 yet.

**Comment by jamke** [comment] 2023-10-29 15:42
@rustybird thank you for this information. Unfortunately, I have no major details, I was in a hurry and did not analyzed the situation properly, and later I forgot to return to this problem. I think it was a permission issue (maybe the owner was different, like what can be done with `chown`). It was 2 non-empty directories, and I used dolphin right-click service (which calls `qvm-move`), that what I remember.

About the version, it is possible, that it was older, because the sender qube used an outdated template.
I will look for such cases more attentively in the future and report if it ever happens again.

**Comment by DemiMarie** [comment] 2023-10-30 20:29
https://github.com/QubesOS/qubes-linux-utils/commit/3ee55169dbc5b9f455ae3a6c2a1dcfc9e7903786 needs to be backported to R4.1.  Reopening, but removing https://github.com/QubesOS/qubes-issues/labels/affects-4.2 so that this is no longer considered a release blocker for R4.2.

**Comment by andrewdavidwong** [comment] 2023-10-30 22:35
> [QubesOS/qubes-linux-utils@3ee5516](https://github.com/QubesOS/qubes-linux-utils/commit/3ee55169dbc5b9f455ae3a6c2a1dcfc9e7903786) needs to be backported to R4.1. Reopening, but removing https://github.com/QubesOS/qubes-issues/labels/affects-4.2 so that this is no longer considered a release blocker for R4.2.

That's not how it works. `affects-4.2` just means that the bug affects 4.2. It's not the case that every issue with `P: blocker`+`affects-4.2` will block release. That's what the milestone is for. Only issues on the milestone block release. If it's true that this affects 4.2, then `affects-4.2` should remain. Maybe what you're looking for is `backport pending`.

**Comment by andrewdavidwong** [comment] 2023-10-30 22:57
(Removing it from the 4.2 milestone is also adittedly bad, but I don't see another option right now. Will discuss this separately and figure out a better system.)

**Comment by andrewdavidwong** [comment] 2023-10-30 23:12
Thanks to @marmarek for clarifying: `backport pending` is intended to be for closed issues. Will clarify this in the label description and re-close this issue now.

**Closed by andrewdavidwong** 2023-10-30 23:12 UTC
Labels: T: bug, C: core, P: blocker, r4.1-buster-cur-test, r4.1-bullseye-cur-test, diagnosed, pr submitted, backport pending, r4.1-bookworm-cur-test, r4.1-fc37-cur-test, r4.2-vm-centos-stream8-stable, r4.2-vm-bullseye-stable, r4.2-vm-fc37-stable, r4.2-vm-bookworm-stable, r4.1-fc38-cur-test, r4.2-host-stable, r4.2-vm-fc38-stable, affects-4.1, affects-4.2, r4.2-vm-fc39-stable
