### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#911] opened 2015-03-08 17:22 UTC
**Reported by anonymous on 29 Oct 2014 14:20 UTC**
I love Qubes-OS! And plan on donating more. Though the current theme is boring & ugly. A sleek looking dark black theme would be great for both the dmo0 and VM templates as a default or at least as a choice. Thanks.

Migrated-From: https://wiki.qubes-os.org/ticket/911

**Comment by bnvk** [comment] 2015-11-24 19:19
I'm definitely in favour of this dark option existing and have kind of configured my KDE to this end at present. I'll take this into account further down the line!

**Comment by Jeeppler** [comment] 2016-05-11 03:13
Hello, 

I like the dark option too. I have been able to change most of Qubes OS 3.1 KDE 4 to use a dark theme. The only thing I did was playing around with the KDE settings.

The first image shows a Qubes Manager in Black and the Desktop theme is also dark:
![qubes-black-3](https://cloud.githubusercontent.com/assets/2007739/15168854/d2be4bac-16fa-11e6-9266-e999509045fb.png)

The menu is dark as well, which works perfectly fine:
![qubes-black-2](https://cloud.githubusercontent.com/assets/2007739/15168839/b3ec866c-16fa-11e6-8080-7d678f166d4f.png)

The only problem with the Qubes Manager are the graphs. The problem is here the text color. The text color of the graphs should always bee black on white background:
![qubes-black-4](https://cloud.githubusercontent.com/assets/2007739/15168841/b3ee99de-16fa-11e6-924c-3aed060eb68a.png)

Only the close, resize and minimize buttons of the Plastik for Qubes theme does not work well together with the Oxygen application window theme:
![qubes-black-5](https://cloud.githubusercontent.com/assets/2007739/15168840/b3ee9cae-16fa-11e6-94aa-f3c2de800236.png)

Besides the two minor issues buttons for the black theme and the graphs in the Qubes Manager everything works perfectly fine. Let's see what happens if we would have KDE 5 with the breeze theme.

**Comment by Jeeppler** [comment] 2016-05-11 03:24
Setting the VM's to a black theme requires gnome-tweak-tools to enable the GTK dark theme for gnome:

![vm-black](https://cloud.githubusercontent.com/assets/2007739/15169106/57448948-16fd-11e6-8213-53ca1941b244.png)

Only Firefox has a problem with the gnome-dark theme and HTML forms. The dark theme makes forms unreadable. This is only a minor issue and requires to overwrite Firefox CSS default stylesheet. 

Installing the following plugin: [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/) and in the plugin a GTK dark theme, helps to overwrite the default Firefox CSS, so that everything works correctly.

**Comment by andrewdavidwong** [comment] 2016-05-11 03:54
I use the same dark themes, too. If you don't want to install Stylish to fix Firefox, you can just add this line to `/rw/config/rc.local`:

```
sed -i.bak "s/Exec=firefox %u/Exec=bash -c 'GTK_THEME=Adwaita:light firefox %u'/g" /usr/share/applications/firefox.desktop
```

**Comment by Jeeppler** [comment] 2016-05-28 15:22
So, what should be done to mark this issue as resolved?

**Comment by marmarek** [comment] 2016-05-29 22:14
@andrewdavidwong do you think it qualifies for a documentation page?

**Comment by andrewdavidwong** [comment] 2016-05-30 05:58
Sure, there can be a doc page about this. However, I think the OP had in mind something "built-in":

> A sleek looking dark black theme would be great for both the dmo0 and VM templates **as a default or at least as a choice**.

**Comment by andrewdavidwong** [comment] 2016-05-30 05:59
@Jeeppler, since you've already done a lot of good work on this (incl. screenshots), would you be interested in writing the doc page and submitting it as a PR?

**Comment by Jeeppler** [comment] 2016-05-30 07:09
I mean Qubes Debian and especially Fedora Images could include Gnome-Tweak-Tool, to set GTK Desktops to "GTK Dark Theme". Qubes OS Dom0 could be tested with Light and Dark Theme. 

It would be maybe a good idea to let the user choose during the installation process if he want's to have a light or dark theme for Dom0 (+DomU's).

**Comment by Jeeppler** [comment] 2016-05-30 07:10
@andrewdavidwong Yes, I am interested in writing a doc page and submitting it as a PR.

**Comment by andrewdavidwong** [comment] 2016-05-30 10:18
Thank you! :)

**Comment by andrewdavidwong** [comment] 2016-06-09 22:47
@marmarek: Does this issue actually have two parts: doc page and integrated theme option? Or are we closing that after the doc page gets written? (Or splitting into two issues, etc.)

**Comment by Jeeppler** [comment] 2016-06-16 00:05
I created a pull request in qubes-doc and qubes-attachment for the documentation.

**Comment by ttasket** [comment] 2016-06-16 20:39
How did I miss this one? I like dark themes.

I'll submit my fix for the CPU/disk meter bars that works with both bright and dark...

domU gnome: Enable dark theme without tweaktool...
```
mkdir -p .config/gtk-3.0
echo "[Settings]" >.config/gtk-3.0/settings.ini
echo "gtk-application-prefer-dark-theme=1" >>.config/gtk-3.0/settings.ini
```
You may still have to tell gnome-terminal to 'yes really use the dark theme' in its prefs. But the other apps should conform.

domU KDE: Don't have one yet. I have a couple vms with KDE apps that need  it.

Mozilla apps: I've been using a combination of the DeepDark theme and (for Firefox) a page-coloring extension such as "Blank Your Monitor" and "Color Transform". BYM works well with DeepDark if you turn off "Form enhancement" so that location bar, etc. doesn't turn bright. DeepDark on Tbird isn't as thorough so I had to tweak it.

**Comment by Jeeppler** [comment] 2016-06-16 21:09
I use `Black Dark by rtodorovsky` as black theme for Firefox. 

domU KDE -> should be the same as for Dom0 KDE.

**Comment by ttasket** [comment] 2016-07-01 11:41
I've entered a simple and good-looking fix for the CPU/mem meters. Just change `white` to `transparent` and `0` to `1` where indicated...

```
@@ -398,11 +398,11 @@ def __init__(self, min, max, format, update_func, vm, load, hue=210, parent = No
                                     "QProgressBar:horizontal{" +\
                                         "border: 1px solid hsv({0}, 100, 250);".format(hue) +\
                                         "border-radius: 4px;\
-                                        background: white;\
+                                        background: transparent;\
                                         text-align: center;\
                                     }\
                                     QProgressBar::chunk:horizontal {\
-                                        background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5, " +\
+                                        background: qlineargradient(x1: 1, y1: 0.5, x2: 1, y2: 0.5, " +\
                                         "stop: 0 hsv({0}, 170, 207),".format(hue) +
                                         " stop: 1 white); \
                                     }"
```
https://github.com/QubesOS/qubes-manager/compare/master...ttasket:patch-1

![snapshot2](https://cloud.githubusercontent.com/assets/14337937/16520592/1286f176-3f5f-11e6-9b00-064374757dc6.png)

**Comment by ttasket** [comment] 2016-07-01 11:51
FYI, I didn't show the actual "graphs" along with the "meters" shown above. The graphs also look correct with this fix.

Since KDE5 includes nice dark palettes, it would be nice to have this in the 3.2 release.

**Comment by andrewdavidwong** [comment] 2016-07-02 02:22
> Since KDE5 includes nice dark palettes, it would be nice to have this in the 3.2 release.

Would that only work for users who manually install KDE in R3.2? I imagine most users will switch to XFCE, since that'll be the new default.

**Comment by ttasket** [comment] 2016-07-02 03:22
Qubes Manager is a Qt application, so that depends on whether users can control Qt color scheme from XFCE. I think the meter rendering should corrected in either case.

**Comment by Jeeppler** [comment] 2016-07-12 03:24
XFCE comes with dark themes by default, but there are not really usable. This is at least my experience when I was testing it on Q R3.1. I think the changes will have a good effect for both platforms.

**Comment by Jeeppler** [comment] 2016-07-26 20:58
@andrewdavidwong this Qubes Issue should have multiple related issues which can be fixed separately. I would recommend something to split this in documentation: Dom0 (KDE, XCFE dark theme), VM dark theme and development tasks. So, each task could be solved separately. Otherwise this taks will be here for ever.

**Comment by andrewdavidwong** [comment] 2016-07-26 22:00
@Jeeppler: Yes, I was waiting for an answer from @marmarek to my [question above](https://github.com/QubesOS/qubes-issues/issues/911#issuecomment-225049460) about that. 

However, the more I think about it, the less clear it is to me that we need any further issues on this. Thanks to you, we already have extensive documentation on how to implement dark themes in KDE and XFCE in dom0 and in various VMs. The biggest problem is/was the Qubes VM Manager, which is going away soon anyway. So, what is actually left to do? The only possibility that comes to mind is a built-in option for enabling a global dark theme, as I [mentioned](https://github.com/QubesOS/qubes-issues/issues/911#issuecomment-222417003) above, but this would be a significant undertaking. It would have to be a community contribution.

So, as I see it, we're left with two options: call this issue done and close it now, or leave it open as a "help wanted" task for implemented the built-in global dark theme option. @marmarek, what do you think?

**Comment by marmarek** [comment] 2016-07-26 22:23
I think it is unrealistic to have built-in global option, that would be huge task (involving both dom0 and VMs). So this may be closed.

**Closed** 2016-07-26 22:56 UTC
Labels: C: other, C: doc, P: major, ux

**Comment by Jeeppler** [comment] 2016-07-26 23:12
@marmarek I don't think there is a need to have a built-in global option. The only thing I would like to see is that you select a dark and a bright default theme for XCFE during the development phase of R3.2 and R4. This could be done by community members. You could open another issue for that, like: "R3.2 or R4 XCFE black default theme" and make sure that it is documented how to use/configure the theme. @marmarek, @andrewdavidwong, @bnvk  What do you think about that?

**Comment by andrewdavidwong** [comment] 2016-07-27 21:00
@Jeeppler: Are you suggesting that a dark theme should be pre-selected as the default when Qubes OS is installed? I'm not so sure that's a good idea. As much as I personally love dark themes, I think we should recognize that many users don't like them, and there's a reason why almost every user-facing default theme is light.

**Comment by Jeeppler** [comment] 2016-07-27 21:32
No, not as default, but for those who want to select a dark theme their should be one installed which works 100% with Qubes OS. One dark theme which is tested and a Qubes OS recommendation.

You are right, light themes are often the default, but if you want to switch to a dark theme it looks horrible and you have to configure a lot of options to make it work. This should not be the case. People who want to switch they should have one working dark theme. 

For example right now the Qubes VM Manager looks horrible with dark themes under XCFE.

**Comment by andrewdavidwong** [comment] 2016-07-27 21:40
Sounds good. I've created #2204 to track that.

**Comment by Jeeppler** [comment] 2016-07-27 21:42
@andrewdavidwong yes, that is what I meant.
