### ISSUE TITLE
No audio in CentOS 7

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#5558] opened 2020-01-05 11:03 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
- Centos 7 tempates (`qubes-template-centos-7` and `qubes-template-centos-7-minimal`)
- Audio (`pulseaudio-qubes`?)

**Steps To Reproduce**
_1._ Install `qubes-template-centos-7`
_2._ Create an AppVM / DispVM based on `centos-7`
_3._ Launch any audio-playing application in the new AppVM / DispVM

or

_1._ Install `qubes-template-centos-7-minimal`
_2._ Install `pulseaudio-qubes` within the new `centos-7-minimal` TemplateVM
_3._ Create an AppVM / DispVM based on `centos-7-minimal`
_4._ Launch any audio-playing application in the new AppVM / DispVM

**Expected behavior**
Audio output works and the AppVM shows up in dom0's audio mixer

**Actual behavior**
No audio output and AppVM does not appear in dom0's audio mixer

**Comment by fepitre** [comment] 2020-01-05 16:15
After first investigations, it's a duplicate of https://github.com/QubesOS/qubes-issues/issues/5126.

**Closed by fepitre** 2020-01-05 16:15 UTC
Labels: P: default, T: bug
