### ISSUE TITLE
Qubes Devices Widget broken after Dom0 kernel updates

### ISSUE THREAD

**Issue by TangoBravo14** [QubesOS/qubes-issues#4883] opened 2019-03-13 19:20 UTC
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s) or functionality:
Qubes Devices Widget

---

### Steps to reproduce the behavior:

New install. Applied critical apt updates to debian-9 and whonix templates.   Applied updates as available from qubes updater.  Last group that updated dom0 applied and device widget stopped working properly after

### Expected or desired behavior:

Expect normal operation of device widget.  Change entries as items are inserted and removed, indicate when items are attached to domain, and allow you to eject items.

### Actual behavior:
Devices only show if they were present at boot in device widget.  Updates to status or removal are no longer tracked.  Able to attach to a domain but no indication and unable to eject, the widget continues to attempt to attach on subsequent clicks even though it is already attached.

### General notes:
After applying the following kernel upgrades as prompted by the system on a new install, Devices Widget no longer operates properly.  Before the update, full expected functionality existed.  Afterwards, devices are only populated and removed if they are connected on initial boot.  Plugging in a new device does create a pop up notification but the corresponding entry in the Devices Widget is not populated.  Selecting to attach a device to a domain will work but the device does not become bolded and the + never changes to the eject icon.  Clicking on the domain a second time continues to try and attach the device which errors as it is already attached. 

Full operation still available by qvm-usb commands.

Reinstalled three times.  Confirmed the error started after the completion of the below dom0 updates being applied.
```
--------------
Updating dom0

local:
    ----------
    kernel:
        ----------
        new:
            1000:4.14.103-1.pvops.qubes,1000:4.14.74-1.pvops.qubes
        old:
            1000:4.14.74-1.pvops.qubes
    kernel-qubes-vm:
        ----------
        new:
            1000:4.14.103-1.pvops.qubes,1000:4.14.74-1.pvops.qubes
        old:
            1000:4.14.74-1.pvops.qubes
    python2-qubesimgconverter:
        ----------
        new:
            4.0.23-1.fc25
        old:
            4.0.22-1.fc25
    python3-qubesimgconverter:
        ----------
        new:
            4.0.23-1.fc25
        old:
            4.0.22-1.fc25
    qubes-core-dom0:
        ----------
        new:
            4.0.39-1.fc25
        old:
            4.0.37-1.fc25
    qubes-desktop-linux-manager:
        ----------
        new:
            4.0.15-1.fc25
        old:
            4.0.13-1.fc25
    qubes-manager:
        ----------
        new:
            4.0.28-1.fc25
        old:
            4.0.26-1.fc25
    qubes-mgmt-salt:
        ----------
        new:
            4.0.15-1.fc25
        old:
            4.0.14-1.fc25
    qubes-mgmt-salt-admin-tools:
        ----------
        new:
            4.0.15-1.fc25
        old:
            4.0.14-1.fc25
    qubes-mgmt-salt-config:
        ----------
        new:
            4.0.15-1.fc25
        old:
            4.0.14-1.fc25
    qubes-mgmt-salt-dom0:
        ----------
        new:
            4.0.15-1.fc25
        old:
            4.0.14-1.fc25
    qubes-mgmt-salt-dom0-update:
        ----------
        new:
            4.0.6-1.fc25
        old:
            4.0.4-1.fc25
    qubes-utils:
        ----------
        new:
            4.0.23-1.fc25
        old:
            4.0.22-1.fc25
    qubes-utils-libs:
        ----------
        new:
            4.0.23-1.fc25
        old:
            4.0.22-1.fc25
    xfce4-settings-qubes:
        ----------
        new:
            4.0.3-1.fc25
        old:
            4.0.2-1.fc25
------------------------------
```

---

**Comment by yubiguel** [comment] 2019-03-13 21:22
Yes, this seems to be a duplicate of #4849 . I also submitted another one closed (due to being a duplicate) #4878  with a similar explanation.

**Comment by andrewdavidwong** [comment] 2019-03-14 00:04
Duplicate of #4849

**Comment by andrewdavidwong** [comment] 2019-03-14 00:05
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-03-14 00:05 UTC
