### ISSUE TITLE
Selecting updates over tor for templates and dom0 during install only gets applied to dom0, not templates as well

### ISSUE THREAD

**Issue by swimik** [QubesOS/qubes-issues#6143] opened 2020-10-23 02:26 UTC
**Qubes OS version**
Qubes 4.0.3

**Affected component(s) or functionality**
During installation final setup. The option for all updates for dom0 and TemplateVMs to occur over Tor is given to the user.

**Brief summary**
If you select the option to have all updates for Templates and dom0 over Tor the installer will ensure the global settings for dom0 updates occur over sys-whonix. However, TemplateVM updates occur over sys-net. If you check /etc/qubes-rpc/policy/qubes.UpdatesProxy the option for TemplateVMs over sys-whonix is commented out and instead those updates are going over sys-net.

**To Reproduce**

1. Install Qubes 4.0.3
2. Select the option to force dom0 and TemplateVM updates to be over sys-whonix
3. Check /etc/qubes-rpc/policy/qubes.UpdatesProxy to see that the option to force updates over sys-whonix.

**Expected behavior**
Selecting the option to have updates for dom0 and TemplateVMs over Tor should ensure updates do indeed occur over Tor

**Actual behavior**
Updates for dom0 are changed in Global Settings are changed to update over sys-whonix, and updates do indeed occur over sys-whonix. Updates for TemplateVMs continue to occur over sys-net, as seen in /etc/qubes-rpc/policy/qubes.UpdatesProxy, and do occur over clearnet.

**Comment by marmarek** [comment] 2020-10-23 10:19
Can you post exact `/etc/qubes-rpc/policy/qubes.UpdatesProxy` you've got? Including the very first line.

**Comment by icequbes1** [comment] 2020-10-23 16:38
Not the OP; only trying to help test. But I could not reproduce this on a fresh install of Qubes 4.0.3 without doing any further updates.

The qubes.UpdatesProxy properly contained the sys-whonix target policy as the first line:

```
$ head /tmp/q4install/root/etc/qubes-rpc/policy/qubes.UpdatesProxy 
$type:TemplateVM $default allow,target=sys-whonix
## Note that policy parsing stops at the first match,
## so adding anything below "$anyvm $anyvm action" line will have no effect

## Please use a single # to start your custom comments

# Upgrade all TemplateVMs through sys-whonix.
#$type:TemplateVM $default allow,target=sys-whonix

# Upgrade Whonix TemplateVMs through sys-whonix.
```

qubesctl states during install as indicated in the journal:

```
$ journalctl --file /tmp/q4install/root/var/log/journal/9bb6221c1fd543b4ab40ee679ad341a2/system.journal|grep qubesctl

Running... qubesctl saltutil.clear_cache
Running... qubesctl saltutil.sync_all
Running... qubesctl top.enable qvm.sys-net
Running... qubesctl top.enable qvm.sys-firewall
Running... qubesctl top.enable qvm.default-dispvm
Running... qubesctl top.enable qvm.sys-whonix
Running... qubesctl top.enable qvm.anon-whonix
Running... qubesctl top.enable qvm.updates-via-whonix
Running... qubesctl --all state.highstate
Running... qubesctl top.disable qvm.sys-net
Running... qubesctl top.disable qvm.sys-firewall
Running... qubesctl top.disable qvm.default-dispvm
Running... qubesctl top.disable qvm.sys-whonix
Running... qubesctl top.disable qvm.anon-whonix
Running... qubesctl top.disable qvm.updates-via-whonix
```

If the OP's first line in qubes.UpdatesProxy does not contain the sys-whonix target, I wonder if it is getting overwritten by further actions. I did not perform any updates after initial install. qubes-core-dom0 owns the qubes.UpdatesProxy file.

**Comment by unman** [comment] 2020-10-23 23:55
On Fri, Oct 23, 2020 at 09:39:07AM -0700, icequbes1 wrote:
> Not the OP; only trying to help test. But I could not reproduce this on a fresh install of Qubes 4.0.3 without doing any further updates.
> 
> The qubes.UpdatesProxy properly contained the sys-whonix target policy as the first line:
> 
> ```
> $ head /tmp/q4install/root/etc/qubes-rpc/policy/qubes.UpdatesProxy 
> $type:TemplateVM $default allow,target=sys-whonix
> ## Note that policy parsing stops at the first match,
> ## so adding anything below "$anyvm $anyvm action" line will have no effect
> 
> ## Please use a single # to start your custom comments
> 
> # Upgrade all TemplateVMs through sys-whonix.
> #$type:TemplateVM $default allow,target=sys-whonix
> 
> # Upgrade Whonix TemplateVMs through sys-whonix.
> ```
> 
> qubesctl states during install as indicated in the journal:
> 
> ```
> $ journalctl --file /tmp/q4install/root/var/log/journal/9bb6221c1fd543b4ab40ee679ad341a2/system.journal|grep qubesctl
> 
> Running... qubesctl saltutil.clear_cache
> Running... qubesctl saltutil.sync_all
> Running... qubesctl top.enable qvm.sys-net
> Running... qubesctl top.enable qvm.sys-firewall
> Running... qubesctl top.enable qvm.default-dispvm
> Running... qubesctl top.enable qvm.sys-whonix
> Running... qubesctl top.enable qvm.anon-whonix
> Running... qubesctl top.enable qvm.updates-via-whonix
> Running... qubesctl --all state.highstate
> Running... qubesctl top.disable qvm.sys-net
> Running... qubesctl top.disable qvm.sys-firewall
> Running... qubesctl top.disable qvm.default-dispvm
> Running... qubesctl top.disable qvm.sys-whonix
> Running... qubesctl top.disable qvm.anon-whonix
> Running... qubesctl top.disable qvm.updates-via-whonix
> ```
> 
> If the OP's first line in qubes.UpdatesProxy does not contain the sys-whonix target, I wonder if it is getting overwritten by further actions. I did not perform any updates after initial install. qubes-core-dom0 owns the qubes.UpdatesProxy file.
> 

I've not been able to reproduce this either, and I've been trying since
it was first suggested.
Since it seems *extremely* unlikely that this is a bug that has affected
EVERY install in the past without any one noticing, I wonder if it is
linkable to some peculiarity in the set-up.
Some information about hardware might be of use?

**Comment by swimik** [comment] 2020-10-24 14:16
Sorry for the delay. Thanks everyone for helping. I cant get my initial symptoms to repeat I may have not seen anything at all, I did not catch that `$type:TemplateVM $default allow,target=sys-whonix`  was just printed at the top of the file, and instead saw it commented out at `# Upgrade all TemplateVMs through sys-whonix. #$type:TemplateVM $default allow,target=sys-whonix`, while `# Default rule for all TemplateVMs - direct the connection to sys-net
$type:TemplateVM $default allow,target=sys-net` was uncommented.

When I first brought up the problem I could do updates with sys-whonix not running on a TemplateVM and it would start sys-whonix up for a dom0 update if it was not running. 

Hardware wise it was a Dell 7470 and an amd FX 8350, 970a-ud3b mobo, approved ram for this mobo, 2 sata ssds, 1 pcie nvme, radeon mobility 5400 series cheap gpu.

Here is the /etc/qubes-rpc/policy/qubes.UpdatesProxy
`$type:TemplateVM $default allow,target=sys-whonix`
`## Note that policy parsing stops at the first match,`
`## so adding anything below "$anyvm $anyvm action" line will have no effect`

`## Please use a single # to start your custom comments`

`# Upgrade all TemplateVMs through sys-whonix.`
`#$type:TemplateVM $default allow,target=sys-whonix`

`# Upgrade Whonix TemplateVMs through sys-whonix.`
`$tag:TemplateVM $default allow,target=sys-whonix`

`# Deny Whonix Template VMs using UpdatesProxy of any other VM.`
`$tag:whonix-updatevm $anyvm deny`

`# Default rule for all TemplateVMs - direct the connection to sys-net`
`$type:TemplateVM $default allow,target=sys-net`

`$anyvm $anyvm deny`

I guess its probable I configured the install and did not notice.

**Comment by andrewdavidwong** [comment] 2020-10-24 21:23
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-10-24 21:23 UTC
Labels: C: installer, P: default, T: bug, more-info-needed, needs-diagnosis
