### ISSUE TITLE
Make sys-usb a DispVM by default

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5542] opened 2019-12-28 13:18 UTC
**Describe the solution you'd like**
Make sys-usb a DispVM by default

**Where is the value to a user, and who might that user be?**
Reduce the possibility of sys-usb being compromised and avoid storing unnecessary temporary files of sys-usb

**Comment by andrewdavidwong** [comment] 2019-12-30 13:25
Duplicate of #3704

**Comment by andrewdavidwong** [comment] 2019-12-30 13:25
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-12-30 13:25 UTC
Labels: P: default, T: enhancement
