### ISSUE TITLE
debian-9 not working due to Xorg.wrap being present and missing dbus-launch

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3229] opened 2017-10-27 14:46 UTC
#### Qubes OS version:
R4.0-rc2

#### Affected TemplateVMs: 
debian-9

### Steps to reproduce the behavior:
1. Install debian-9 template and try to open its terminal using the menu entry

### Expected behavior:
It opens.

### Actual behavior:
It doesn't open.

### General notes:
The main problem is that Xorg does not start due to the presence of Xorg.wrap setuid wrapper, which refuses to work. Deleting it solves that problem.

A second issue is that dbus-launch is missing because the dbus-x11 package is not installed.

**Comment by andrewdavidwong** [comment] 2017-11-09 00:47
@qubesuser, do you think this is a duplicate of #2909?

**Comment by marmarek** [comment] 2017-11-09 01:17
Also, what version of the template you've tried? Because exactly this issue was fixed in `qubes-template-debian-9-4.0.0-201711030329.noarch.rpm`.

**Closed** 2017-11-18 22:49 UTC
Labels: bug, C: Debian
