### ISSUE TITLE
Templates can't be updated via GUI Package Updater / Apper

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1197] opened 2015-09-21 12:26 UTC
I'm creating this issue to track the progress of fixing this issue. 

*current functionality*: a user cannot update TemplateVMs using the GUI Package Updater because the Package Updater reports that there are no updates available even when there are

*expected functionality*: Package Updater reports the updates available and can attempt to update those packages

There is a [related issue on the Whonix bug tracker](https://phabricator.whonix.org/T373) but it has quickly expanded beyond the issue at hand into more general discussions about the security & practices of update managers.

Package Updater works for other distros (however poorly), we want that same level of crappy functionality in Qubes. The longer term discussion about finding/building a better updater can still happen, but it is not related to this issue.

**Comment by marmarek** [comment] 2015-09-21 12:51
This seems to be a duplicate of #982

**Comment by marmarek** [comment] 2015-09-21 12:52
BTW there is also related issue for dom0: #968

**Comment by mfc** [comment] 2015-09-21 12:58
ah beautiful I knew there had to already be issues that more directly referenced this issue. I saw the dom0 issue but it again seemed to die upon being referenced to the mostly-unrelated Phabricator ticket.

Sounds like you have work-around for it. Calling the terminal is fine, from the user perspective it is mostly equivalent as they just click a button in the menu and something (ugly) pops up that asks if they want to update.

**Comment by mfc** [comment] 2015-09-21 23:01
I asked on #982 as well, but do you think it'd be possible to test the workaround and see if it works, and potentially implement for R3.0? It would be really unfortunate to have a reduction in usability comparing R3.0 to R2.0.

**Closed** 2015-10-08 23:01 UTC
Labels: bug, C: templates, P: major
