### ISSUE TITLE
Networks VMs are restarting themselves without valid reason

### ISSUE THREAD

**Issue by skaven-gear** [QubesOS/qubes-issues#5930] opened 2020-07-03 23:01 UTC
**Qubes OS version**
`R4.0`

**Affected component(s) or functionality**
qvm-prefs
qvm-shutdown

**Brief summary**
Sometimes I cut off and shutdown all the networks VMs from my AppVms;
but then, if I close and reopen the lid of my laptop or shutdown one of the AppVms, all the networks VMs restart.

**To Reproduce**
1  `qvm-prefs anon-whonix netvm none`
2 start an anon-whonix
3 shutdown sys-whonix, sys-firewall and sys-net
4 shutdown anon-whonix

**Expected behavior**
Networks VMs should restart only a VM which really need them is asking for it.

**Actual behavior**
Networks VMs may restart when it's inappropriate.

**Comment by marmarek** [comment] 2020-07-03 23:32
This is probably caused by some Whonix-related qrexec service call from anon-whonix. Take a look at `journalctl` in dom0 - look for entries with `qrexec` process.

@adrelanos how anon-whonix decides whether to do those calls (if that's the reason) and where to target them?

**Comment by adrelanos** [comment] 2020-07-05 18:13
https://www.whonix.org/wiki/Sdwdate-gui#Qubes-Whonix_-_Unexpected_Autostart_of_sys-whonix for now user support reply is:

> Follow instructions [multiple Qubes-Whonix ™ Whonix-Workstation ™](https://www.whonix.org/wiki/Multiple_Whonix-Workstation#Qubes-Whonix_.E2.84.A2).

----

Duplicate of https://github.com/QubesOS/qubes-issues/issues/5253?

related:
https://groups.google.com/forum/#!topic/qubes-devel/DEQNltD2_kc

ticket:
[whonix.SdwdateStatus service starts VMs that were killed](https://phabricator.whonix.org/T930)

Help welcome.

> @adrelanos how anon-whonix decides whether to do those calls (if that's the reason) and where to target them?

sdwdate writes to `/run/sdwdate/status` and what results in "nothing" except a "consumer" (sdwdate-gui-qubes watcher) does something with it.

Workstations sdwdate-gui-qubes watcher watches `/run/sdwdate/status` for changes.

When changes where noticed it will run qrexec-client-vm with default target sys-whonix, configurable through foder /etc/sdwdate-gui.d/ or folder /usr/local/etc/sdwdate-gui.d/.

related source file:
https://gitlab.com/whonix/sdwdate-gui/-/blob/master/usr/lib/python3/dist-packages/sdwdate_gui/sdwdate_watcher.py

If we had feature https://github.com/QubesOS/qubes-issues/issues/5253 then fixing most issues would be a lot simpler. But still corner cases probably. (Killing sys-whonix and shutdown for anon-whonix would still restart sys-whonix.)

https://phabricator.whonix.org/T930 looks more sophisticated but also a lot harder to implement for me. (But probably no corner cases.)

**Comment by andrewdavidwong** [comment] 2020-07-07 10:59
> https://www.whonix.org/wiki/Sdwdate-gui#Qubes-Whonix_-_Unexpected_Autostart_of_sys-whonix for now user support reply is:
> 
> > Follow instructions [multiple Qubes-Whonix ™ Whonix-Workstation ™](https://www.whonix.org/wiki/Multiple_Whonix-Workstation#Qubes-Whonix_.E2.84.A2).
> 

@skaven-gear, does this resolve the issue for you?

**Comment by skaven-gear** [comment] 2020-07-21 10:27
> This is probably caused by some Whonix-related qrexec service call from anon-whonix. Take a look at `journalctl` in dom0 - look for entries with `qrexec` process.
This is what I find at the moment where sys-whoix is resurrecting. (set is the name of the AppVM)

`Jul 21 12:14:31 dom0 qrexec[20858]: whonix.NewStatus+set_shutdown: set -> sys-whonix: allowed to sys-whonix`
`Jul 21 12:14:31 dom0 qubesd[3137]: Starting sys-whonix`


> > https://www.whonix.org/wiki/Sdwdate-gui#Qubes-Whonix_-_Unexpected_Autostart_of_sys-whonix for now user support reply is:
> > > Follow instructions [multiple Qubes-Whonix ™ Whonix-Workstation ™](https://www.whonix.org/wiki/Multiple_Whonix-Workstation#Qubes-Whonix_.E2.84.A2).

The first one alone doesn't solve it for me;
I am not sure to understand what is expected with the second here? remove "gateway=sys-whonix" or change it to a false value?

**Comment by adrelanos** [comment] 2020-07-21 13:14
> remove "gateway=sys-whonix"


No removal required.

> remove "gateway=sys-whonix" 


replace sys-whonix2 with the name of the VM of the other Whonix-Gateway.

replace sys-whonix with the name of the VM of the other Whonix-Gateway.

gateway=name-of-other-whonix-gateway

(all 3 sentences = same meaning)

> or change it to a false value?


No false value.

**Comment by skaven-gear** [comment] 2020-07-22 13:52
So I added in /etc/sdwdate-gui.d/50_user.conf
'disable=true'
in both whonix-ws-15 and whonix-gw-15 TemplatesVMs
with root rights.

I added in /usr/local/etc/sdwdate-gui.d/50_user.conf
'gateway=sys-whonix'
in the AppVM
with root rights.
(I didn't understand why, i didn't try to change the gateway and this setting is already defined in 
/etc/sdwdate-gui.d/30_default.conf;
but nonetheless did it.)

Then I reproduced the 4 steps of the first post; 
for the same result.

**Comment by adrelanos** [comment] 2020-07-22 16:06
> So I added in /etc/sdwdate-gui.d/50_user.conf
> `disable=true`
> in both whonix-ws-15 and whonix-gw-15 TemplatesVMs
> with root rights.

Confirmed. I've applied a fix.

https://github.com/Whonix/sdwdate-gui/commit/d585273ccce59a093bd5cd01e95dd85490ce99a0

Now in stable-proposed-updates. Will flow to stable as per usual.

> I added in /usr/local/etc/sdwdate-gui.d/50_user.conf
> `gateway=sys-whonix`
> in the AppVM

Not needed.

> with root rights.

This file cannot be edited without root rights.

> (I didn't understand why, i didn't try to change the gateway and this setting is already defined in
> /etc/sdwdate-gui.d/30_default.conf;
> but nonetheless did it.)

/etc/sdwdate-gui.d/30_default.conf vs /etc/sdwdate-gui.d/50_user.conf explained here:

https://www.whonix.org/wiki/Configuration_Files

----

Fixed, can be closed.

**Comment by skaven-gear** [comment] 2020-07-22 16:40
Nice; thanks for the hints.

**Comment by andrewdavidwong** [comment] 2020-07-24 17:26
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-07-24 17:26 UTC
Labels: C: Whonix, P: default, T: bug, diagnosed
