### ISSUE TITLE
Xscreensaver not unlocked when using yubikey

### ISSUE THREAD

**Issue by Wh1teR4bb1t** [QubesOS/qubes-issues#8903] opened 2024-01-30 10:57 UTC
### Qubes OS release
4.2 only

### Brief summary
When setup password + yubikey authentication, lightdm and tty login works fine. However, xscreensaver seems to not recognize the yubikey. It immediately fails with incorrect password without making the yubikey blink.

### Steps to reproduce

Setup the [yubikey authentication from the official doc](https://www.qubes-os.org/doc/yubikey/).

- Having a yubikey configured with a HMAC-SHA1 challenge-response
- In sys-usb "root" template (fedora-38-xfce in my case), install ykpers : `sudo dnf install ykpers`
- In dom0, install qubes-yubikey-dom0: `sudo qubes-dom0-update qubes-yubikey-dom0`
- Input manually the AES key into /etc/qubes/yk-keys/yk-secret-key.hex in dom0.
- get a SHA1 hash of password:
    - In dom0: `read -r password`
    - In dom0: `echo -n "$password" | openssl dgst -sha1 | cut -f2 -d ' '`
    - put the resulting hash into /etc/qubes/yk-keys/yk-login-pass-hashed.hex
- Adding the directive `auth include yubikey` as first effective directive in the following files (dom0):
    - /etc/pam.d/xscreensaver
    - /etc/pam.d/login
    - /etc/pam.d/lightdm
- Edit /etc/pam.d/yubikey (dom0) ard remove the directive `default=ignore`
- (Optional) Test you can successfully login with the yubikey on tty and lightdm

### Expected behavior
Having the yubikey blink and being able to unlock the screen when screen locked.

### Actual behavior
No blinking and access denied, even with the right password. I have to login through tty and kill xscreensaver.

### Other infos
```
[user@dom0]$ xscreensaver --version
xscreensaver 6.08-1.fc37 (19-Nov-2023), by Jamie Zawinski
```

**Comment by DemiMarie** [comment] 2024-01-30 20:57
Could this be because xscreensaver drops supplementary groups?

**Comment by marmarek** [comment] 2024-01-30 21:23
Yes, that's exactly why. And the fix is part of https://github.com/QubesOS/qubes-app-yubikey/pull/22

**Comment by marmarek** [comment] 2024-01-30 21:45
Duplicate of #8859

**Closed by marmarek** 2024-01-30 21:45 UTC
Labels: T: bug, P: default
