### ISSUE TITLE
Qubes-global-config is not able to launch

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [QubesOS/qubes-issues#8251] opened 2023-06-09 13:21 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.0 rc1

### Brief summary

If no VM available with name sys-net, then qubes-global-config not able to launch

### Steps to reproduce

remove VM named sys-net and try to open qubes-global-config. It fails to launch.

### Expected behavior

qubes-config able to launch with custom net vms

### Actual behavior

No launching when sys-net not available.

**Comment by Asterium01** [comment] 2023-06-09 17:09
I encountered the same behavior after removing sys-net. In fact, during my experiments I encountered many errors in qubes-global-config that occur for different reasons. Maybe you can reproduce them in the same way when you change the system default value of qubes to none(net qube, clock qube, etc) , sometimes this does not happen and qubes-global-config returns default values or crashes. Also I could not remove default-dvm, it was written that it is still attached to some qube, but it is not.

**Comment by andrewdavidwong** [comment] 2023-06-09 23:47
Duplicate of #8238

**Comment by andrewdavidwong** [comment] 2023-06-09 23:47
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by marmarek** [comment] 2023-06-18 13:24
The sys-net case is actually separate (but similar) issue, reopening.

**Closed** 2023-06-26 14:46 UTC
Labels: T: bug, C: manager/widget, P: default, needs diagnosis
