### ISSUE TITLE
Not starting Dom0 after updates with 4.9.56-21.pvops.qubes.x86_64

### ISSUE THREAD

**Issue by loadcorp** [QubesOS/qubes-issues#3625] opened 2018-02-23 20:22 UTC
#### Qubes OS version:
R3.2

#### Affected TemplateVMs:
Dom0

---

### Steps to reproduce the behavior:
1. Install Qubes 3.2.
2. Update all (from Dom0 to all VM).

### Expected behavior:
Normal loading like older kernel.

### Actual behavior:
Not loading the kernel version 4.9.56-21.pvops.qubes.x86_64.

### General notes:
After updating I have 2 options in Grub Boot Menu:
1. Qubes, with Xen 4.6.6 and Linux 4.4.14-11.pvops.qubes.x86_64
2. Qubes, with Xen 4.6.6 and Linux 4.9.56-21.pvops.qubes.x86_64

First one working like before updates, but second just rebooting computer.

**Comment by tonsimple** [comment] 2018-02-24 12:37
Do you happen to have an Intel video card by any chance?

https://github.com/QubesOS/qubes-issues/issues/3165

**Comment by loadcorp** [comment] 2018-02-24 19:14
@tonsimple Yes, I have the Intel integrated video card in motherboard.

You wan't to tell me that I must to try with discrete video card? Is it will resolve the problem? Or is there another solution to the problem?

**Comment by andrewdavidwong** [comment] 2018-02-25 06:32
Duplicate of #3165

**Comment by andrewdavidwong** [comment] 2018-02-25 06:32
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-25 06:32 UTC
