### ISSUE TITLE
qvm-backup-restore --verify-only interrupts network to running qubes

### ISSUE THREAD

**Issue by SvenSemmler** [QubesOS/qubes-issues#7827] opened 2022-10-19 18:02 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1 (up-to-date, no testing)

### Brief summary

I do `qvm-backup-restore --verify-only` every morning and when I do some of my network connected qubes loose network connection. It is easily restored by setting `netvm` to none and then back to what it was before.

### Steps to reproduce

Use `qvm-backup-restore --verify-only` while having other network connected qubes running. 

### Expected behavior

Running a simulated (`--verify-only`) restore should have no impact on the network connectivity of running qubes. 

### Actual behavior

Most (but not all) network connected qubes loose network connectivity (`netvm` property is still set correctly). Which ones is somewhat random.

**Comment by marmarek** [comment] 2022-11-11 17:31
Possibly a duplicate of https://github.com/QubesOS/qubes-issues/issues/6497 (to be verified)

**Comment by marmarek** [comment] 2022-12-06 15:21
In this case, IMO better focus on #6497, and leave this one alone until more reliable reproduction steps are found.

**Comment by andrewdavidwong** [comment] 2023-08-30 20:53
Since it has been a long time, and no reliable way to reproduce this issue has been reported, I'm closing this issue as "cannot reproduce." If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2023-08-30 20:53 UTC
Labels: T: bug, C: core, P: minor, more info needed, needs diagnosis, affects-4.1
