### ISSUE TITLE
Enigmail 2.0 update breaks qubes-gpg-split #2

### ISSUE THREAD

**Issue by thewildcat** [QubesOS/qubes-issues#3807] opened 2018-04-09 11:48 UTC
### Qubes OS version:

R3.2, fedora 26, testing repos enabled

### Affected component(s): 

qubes-gpg-split

---

### Steps to reproduce the behavior:

Use Enigmail 2.0 (on Thunderbird 52.7.0 x64) with qubes-gpg-split
As already stated in https://github.com/QubesOS/qubes-issues/issues/3750#issuecomment-377339725 it also uses the --sender email@address.tld so this has to be addressed as well.

### Expected behavior:

The thunderbird message plane should show the decrypted message and support the --sender parameter.

### Actual behavior:

qubes-gpg-client: unrecognized option '--sender'

### General notes:

Temporary fix:
`
--sender)
shift 2
;;
`

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3750

**Comment by andrewdavidwong** [comment] 2018-04-09 23:58
Duplicate of #3750

**Comment by andrewdavidwong** [comment] 2018-04-09 23:59
@thewildcat, you don't explain how this is distinct from #3750. In fact, your report seems to confirm that this is a duplicate of #3750. If it's not, please explain.

**Closed by andrewdavidwong** 2018-04-09 23:59 UTC

**Comment by marmarek** [comment] 2018-04-20 11:31
> But there is another new parameter "--sender" which was not addressed by the fix of #3750

It is, in version 2.0.30.
