### ISSUE TITLE
DomU windows causing Intel GFX acceleration to fail (heavy screen artifacts after VT switch)

### ISSUE THREAD

**Issue by qwrd** [QubesOS/qubes-issues#5460] opened 2019-11-13 10:18 UTC
**Qubes OS version**
R4.0 (4.0.2-rc2)

**Affected component(s) or functionality**
Desktop rendering, graphics

**Brief summary**
After switching to a terminal with **CRTL+ALT+F2** and back to desktop with **CRTL+ALT+F1**, the desktop will no longer render properly.

**To Reproduce**
I'm using an Asus Zenbook UX410UA
1. Perform a default Qubes R4.0 installation on it
2. Boot the system to desktop (xfce), optionally update dom0
3. Open some windows on the desktop from different domains
4. Press CTRL+ALT+F2 to switch to a VT
5. Press CTRL+ALT+F1 to switch back to desktop
6. Desktop rendering is now screwed

**Expected behavior**
The system should be able to seamlessly switch between VT's and desktop without any adverse effects.

**Actual behavior**
When the system boots to xfce desktop everything works as intended. The problem only appears after switching to another VT and back to desktop by using the CRTL+ALT+X (X = F2, F3, etc) and CRTL+ALT+F1 shortcuts. Afterwards there will be rendering issues on the desktop. Some windows like the dom0 terminal will become transparent or partially opaque, system tray icons will disappear (become invisible), desktop shortcuts will have no text, other windows may have invisible buttons and other controls, etc. The problem is most evident when using the Window Manager settings (Start => System tools => Window Manager => Style => Theme) to switch window border styles as the entire windows become messed up.

None of this happens without VT switching. None of this seem to happen when there are no windows open or there are only windows from dom0 present on the desktop. The problem fixes itself after a reboot or relog.

**Screenshots**
After switch: https://imgur.com/a/kCeutlJ
After style change: https://imgur.com/a/jyLqssj

**Additional context**
I found some similar bugs in the issue tracker, but I'm unsure how much they relate due to the fact that other people had discrete graphics cards (nvidia) while my machine has **Intel HD Graphics 620** and that alone. There were also 3-rd party window managers in use (i.e. i3) while I'm using the default unmodified XFCE desktop that comes with Qubes R4.0-rc2. I have not tested any external monitors.

A sample Xorg log was captured with the given timeline: https://pastebin.com/gQnSNpi5
74s - The system booted into desktop
161s - I switched to CTRL+ALT+F2
207s - I switched to desktop CTRL+ALT+F1
253s - Logout

This issue did not happen in Debian Buster LXQt Live nor in Ubuntu Mate 19.10 Live. Meanwhile I found a working solution (see solution 2) and according to the command "xrandr --listproviders" both ubuntu and debian reported "name:modesetting" while qubes reported "name:Intel" in dom0. I am unsure whether it is an ideal solution, but it seems to be working, and I will be testing in in some more programs to see how it handles.

**Solutions you've tried**
1) Upgraded dom0 kernel from 4.19.81-1 to 5.3.7-1 - no dice

2) This seems to fix the problem:
https://groups.google.com/forum/#!msg/qubes-users/0W3BXvKV1Ow/N-SMsWyRHgAJ

**Relevant documentation you've consulted**
https://www.qubes-os.org/doc/software-update-dom0/
https://www.qubes-os.org/doc/newer-hardware-troubleshooting/
https://www.qubes-os.org/doc/testing/

**Related, non-duplicate issues**
https://github.com/QubesOS/qubes-issues/issues/5377
https://github.com/QubesOS/qubes-issues/issues/4943

**Comment by marmarek** [comment] 2019-11-13 13:22
I'm not sure if the problem is the same, but the solution is:
https://github.com/QubesOS/qubes-issues/issues/5244

**Comment by qwrd** [comment] 2019-11-14 12:34
Interesting.

I'm not sure that's the same issue though, but it appears you might be at least partially correct as I did not notice the high CPU usage initially. Whatever this is it must be a symptom of another problem, and apparently this single line in Xorg.0.log is the culprit. 
> [   857.565] (EE) intel(0): Failed to submit rendering commands (Bad address), disabling acceleration.

I did a fresh R4.0.2-rc2 install and updated dom0 and fedora template. Upon first booting Qubes everything works fine. Then I tested some stuff and everything seemed to work e.g. glxgears on dom0 were spinning, window border styles worked fine, VT switching worked, cpu use was normal, etc. Everything was fine until that one line appeared in Xorg.0.log. Afterwards the glxgears suddenly stopped spinning, and after switching VT's it appears X switches to software rendering which apparently causes the screwed screen artifacts all over the place. Oddly though, the glxgears started spinning again, but with high CPU usage. A quick relog returns the state to a working condition.

**Now, I did some tests and I found out that the culprit line seems to appear whenever I first open a window from another non-dom0 domain. Either that or shortly after dragging the window around the screen a bit.**

Upgrading the dom0 kernel to kernel-latest (5.3.7-1.pvops.qubes.x86_64 in current) doesn't seem to do anything, and the xen.conf already has the "iommu=no-igfx" option present in all kernels. According to that post you linked someone apparently used the intel driver with various options to troubleshoot. I tried playing with the individual lines a bit in /etc/X11/xorg.conf.d/20-intel.conf and here are the observations.

```
Section "device"
    Identifier "intel"
    Driver "intel"
    # Option "DRI" "2"
    # Option "AccelMethod" "uxa"
EndSection
```

While using the DRI option ("false", "1", "2") has no visible effect, setting AccelMethod to uxa does "solve" the problem. The desktop appears to be working (the glxgears keep spinning, there are no errors when opening windows from other domains, VT switching works fine, window border styles work fine, etc), but there is one new major hassle: the window dragging with a mouse is incredibly slow. I haven't tested any video playback yet.

However, using the following options instead appears to produce fully functional desktop:
```
Section "device"
    Identifier "intel"
    Driver "modesetting"
    Option "AccelMethod" "glamor"
EndSection
```

**Useful resources:**
https://wiki.archlinux.org/index.php/Intel_graphics
https://jlk.fjfi.cvut.cz/arch/manpages/man/intel.4

**Comment by brendanhoar** [comment] 2019-11-17 00:18
Also want to mention something extracted from the email thread, that restarting X can help:
~~~
sudo systemctl restart lightdm
~~~
...should recover all of your domU windows. There are two side effects, however:

o Any disposable VMs from before X was restarted may not automatically exit when their primary window is closed.

o If you had any dom0 windows, those will be gone (e.g. running a script orchestrating other VMs).

B
Brendan

**Comment by marmarek** [comment] 2019-11-17 00:24
> There are two side effects, however:

There is a third one: audio from VMs stop working. To fix that, you need to reload `module-vchan-sink` in pulseaudio: `pactl unload-module module-vchan-sink; pactl load-module module-vchan-sink` - in every VM.

**Comment by brendanhoar** [comment] 2019-11-17 00:39
Is that noted as a defect for 4.1? :P

**Comment by marmarek** [comment] 2019-11-17 14:19
It is now: https://github.com/QubesOS/qubes-issues/issues/5470

**Comment by qwrd** [comment] 2019-11-17 21:51
So that's what happened to my audio!

I was testing Youtube video playback in one of the qubes while poking around with different X11 settings. At one point there was no sound to be heard from the qube running Firefox. Upon opening the volume control I noticed all other host qubes disappeared from the output list. The volume sliders however did return after a reboot.

I am curious about something. I think my microphone is part of the webcam. I went to the input/recording tab of the volume control and I noticed that all noise indicators from every qube responded to sound when the mic was only supposed to be attached to the personal qube.

Why is this?

**Comment by qwrd** [comment] 2020-03-24 07:21
Hey, just dropping by to say that this issue no longer appears to be present in Qubes 4.1 Build20200310-4.1 (default installation).

**Comment by iamahuman** [comment] 2020-06-27 14:50
Should this issue remain open, and if so what other things shall be done?

**Comment by andrewdavidwong** [comment] 2020-06-30 11:32
> Hey, just dropping by to say that this issue no longer appears to be present in Qubes 4.1 Build20200310-4.1 (default installation).

It sounds like this has been fixed, so I'm closing this issue as resolved. If anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-06-30 11:32 UTC
Labels: C: other, P: default, T: bug

**Comment by BehindTheBrain** [comment] 2021-01-23 00:28
Just confirming #6356 does seem to be an instance of this problem with a different effect.
