### ISSUE TITLE
USB External Drive does not want to attach to AppVM unless..

### ISSUE THREAD

**Issue by stopthisbruh68** [QubesOS/qubes-issues#5194] opened 2019-07-26 14:50 UTC
**Qubes OS version**
_R4.0_

**Affected component(s) or functionality**
_Idk? I am affected by this ??_

**Brief summary**
_This is not fully tested but will explain anyways. So if you boot up the system, start Vault, for example. Play around in the computer and then decide to plug in your External Drive and attach it to Vault. Then it will not attach anything, nothing happens when you try to attach it. You have to restart Vault once and then attach it to Vault._

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Boot up your computer_
_2. Start Vault or any other AppVM_
_3. Plug in USB external drive and try to attach it to Vault_
_4. It will not attach until Vault is restarted_

**Expected behavior**
_Start Vault. Plug in external drive, attach it and it works_

**Actual behavior**
_Start Vault. Plug in external drive, attach it and it wont attach. Restart Vault. Now it will attach_

**Solutions you've tried**
_None_

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by brendanhoar** [comment] 2019-07-26 15:17
This is fixed in the current testing repo, maybe even in current.

Have you updated via:

sudo qubes-dom0-update

?

Brendan

**Comment by andrewdavidwong** [comment] 2019-07-27 00:14
Duplicate of #4999

**Comment by andrewdavidwong** [comment] 2019-07-27 00:14
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-07-27 00:14 UTC
Labels: P: default, T: bug
