### ISSUE TITLE
Qubes Domains: "Open File Manager" button similar to "Run Terminal"

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#5170] opened 2019-07-15 01:51 UTC
**The problem you're addressing (if any)**

It could be easier to open the file manager in a qube.

**Describe the solution you'd like**

In the Qubes Domains widget, we have a "Run Terminal" button for each running qube. I suggest also having an "Open File Manager" button.

**Where is the value to a user, and who might that user be?**

This would make it easier to open the file manager in a qube, especially in a DisposableVM that doesn't have an Applications menu entry.

**Describe alternatives you've considered**

I usually just do `qvm-run` in a dom0 terminal.

**Additional context**

(None)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#2132, #4398

**Comment by zS3mNH2** [comment] 2019-07-15 04:56
Would be awesome. Especially if it opened the default file manager for that qube and not a specific one (like nautilus)

**Comment by marmarek** [comment] 2019-07-15 11:06
> Especially if it opened the default file manager for that qube and not a specific one

Yes, that's definitely a good idea. Does anyone know if there is something like "default file manager" in Linux, or we need to invent it? `xdg-settings` knows only default web browser...
Maybe a handler for `inode/directory` mime type? This is what `xdg-open $HOME` would do.

**Comment by iprid23** [comment] 2019-07-15 20:41
Agreed it's a nice idea. 
Also how about having the Change keyboard layout there too?
It's really annoying to change your keyboard layout in a DispVM right now.

**Comment by andrewdavidwong** [comment] 2019-07-16 01:12
> Also how about having the Change keyboard layout there too?

Not sure if that use case is common enough to merit adding another button to the list.

**Comment by airelemental** [comment] 2019-07-16 05:39
I thought the domains widget would only* have actions that pertain to **running** domains. What's wrong with having the file manager be another entry in the application menu? After all, sometimes you want to open the file manager for a domain that is not running.

* Then again, it already contains the Open terminal and Settings actions.

**Comment by unman** [comment] 2019-07-16 12:56
> Maybe the handler for inode/directory mime type? This is what xdg-open $HOME would do.

I think this is right, although not infallible.
What about minimal or custom templates where there is no file manager? The button would fail silently, I think.

**Comment by zS3mNH2** [comment] 2019-07-17 01:55
@iprid23 and @unman posts show that this is a pretty big usability issue. I think adding a folder menu on the widget is just putting a bandaid over a real usability sore spot and does not solve the underlying issue and that issue is that people need to use disposable VMs for more than 1 application at a time. I think there is a better a solution.

I think DisposableVM apps should go in the normal application menu. Since DisposableVMs are based off of another VM qubes already knows what application entries are vaild for it (the same as whatever it is based off of) without any extra work, so it can just copy that VMs app entries and place it in the menu.

**Advantages of Putting DispVMs in Application Menu**

1. It is discoverable. There shouldn't be two places to open applications when one will suffice. Many people probably don't even use the widget. But everyone uses the application menu. I think it is preferable to keep the widget mostly about "shutdown / shutoff" and to keep the application menu for well... launching applications.

2. It solves every use-case, not just a subset. With this solution both @unman and @iprid23 and every other use-case is solved. The elegance of the solution is better I think

3. Disposable VMs are largely not useful for 95% of use-cases because they are one-app. Most workflows require multiple applications to complete a task within a VM. And, in these situations DisposableVMs fail unless people start a terminal and launch multiple apps and stop using the application menu (very anti-user and not intuitive). _Using disposable VMs should be as easy to use as any other VM._ That will promote their use.

There are many ways to do the applicaton menu entries for the disposable VM. For example, have a menu item named "Active Disposable VMs" and put each VM name under the heading along with each desktop file under that.

However, I personally think disposable VM menu re-arrangment like the following would be best. The basic format is a special menu "Disposable VMs". Under this menu will be the Disposable VM templates types (whonix, etc). Under this menu is a "Start New VM" menu that is sorted on top. Clicking an app icon in this menu will start a NEW disposable VM.

Under the same hierarchy as this will be a list of disposable VMs that belong to that template along with every application associated with that disposable VM.

Disposable VMs
----Whonix Based VM
--------#Start New VM (this is always on the top and starts a new VM)
------------Application \#1
------------Application \#2
--------DispVM \#5334 (this is an actively running VM. Will disappear when VM shuts down)
------------Application \#1
------------Application \#2
--------DispVM \#6837 (this is an actively running VM. Will disappear when VM shuts down)
------------Application \#1
------------Application \#2
----VPN Based VM
.....
-----Another VPN
........

**Comment by marmarek** [comment] 2019-07-17 02:30
Technically adding running DisposableVMs to the menu is not a problem. But doing so will easily lead to another usability issue: DisposableVM by design is destroyed as soon as the application running there is closed. If you start another application there and then close the initial one, DisposableVM will be destroyed, potentially destroying the data you had open in another application. Changing DisposableVM mechanism to destroy it only when last application there is closed also isn't such a good idea, because it could lead to the opposite problem: closing an application and expecting the VM to be destroyed, but in fact it will stay there, because some other application (on another desktop? minimized?) is still running.

As for the proposed menu layout, it looks nice on paper, but multi level menus are hard to navigate. Anyway I like the idea of putting "New" word somewhere in the menu entry for creating new DisposableVM. So, instead of "Disposable: whonix-ws-15-dvm" it could be "New Disposable: whonix-ws-15-dvm". It would be also logical to keep that DisposableVM Template (whonix-ws-15-dvm) somewhere visible, next to dispXXXX names. But that's getting offtopic now.

**Comment by zS3mNH2** [comment] 2019-07-17 05:27
I was thinking with my idea that the disposable VM would not be destroyed until shutdown of the VM (not automatically). Since shutdowns are so easy now with the widget I think it makes sense. I at least hope that this is one day an option of the disposable VMs. It also keeps it consistent with the other UI the system (no other VM launched via the application window auto-shutdowns, so why would DispVMs be different? Persistence is unrelated to auto-shutdown, so that connection is non-intuitive).

For me, there are two-types of disposable VMs and I think context is important:

1) The type that launch when a user is in thunderbird and they click "View PDF in disposable VM". That type of VM it makes sense to shutdown automatically when the app shuts down.

2) The DisposableVM that is started manually in the application menu. I do not think most users expect this to shutdown automatically on them. I know I did not and when it did it was really unpleasant. After all, every other VM started via the app menu does not shutdown automatically, so why would the DispVMs? That is my experience as a user.

Considering I manually started the VM the same way as every other VM in the system which I control the shutdown it makes sense that those VMs would be controlled by me too. I look at those VMs as more like Tails. When a user wants to do a set related tasks in a non-persistant manner, then they use such a VM.

If auto-shutdown is a non-negotiable feature of the DispsoableVM, then I think it might be useful to have a simple NonPersitantVM that is like a normal VM in every way except nothing is persisted to disk.

All the stuff about dynamic menus, etc, really only makes sense for this type of VM. If the user is confined to one app per disposableVM for practical purposes (what is usable), then there isn't really a reason to expose a method for them to launch more than one app.

> As for the proposed menu layout, it looks nice on paper, but multi level menus are hard to navigate. 

What about the other layout I recommended:

Active DisposableVMs
-----VM Name
----------Application #1

This is one menu-level less than the one proposed in the previous message. I think that at a minimum the dynamic menus have to go under their own sub-menu. The reason is so that the top-level menu stays consistent and does not become a distraction. Much of mouse movement is muscle memory based, so if the top-level menu was changing around a lot based on the number of running Disposable VMs, then I think it would be a worse trade off than shoving them all under their own sub-menu as per-above for usability.

**Comment by airelemental** [comment] 2019-07-17 18:45
>     2\. The DisposableVM that is started manually in the application menu. I do not think most users expect this to shutdown automatically on them. I know I did not and when it did it was really unpleasant. After all, every other VM started via the app menu does not shutdown automatically, so why would the DispVMs? That is my experience as a user.

This style of DisposableVM are already implemented (persist until shutdown, permanent app menu entry) but must be created using CLI (no GUI): https://groups.google.com/d/msg/qubes-users/LB9f9OSWCzM/Grsk5VDjCQAJ

**Comment by andrewdavidwong** [comment] 2019-07-19 03:25
Please try to keep your comments on-topic. We already have a lot of other issues that deal with forensics-related topics: #4972, #4488, #4408, #3504, #1293, #904.

The scope of this issue is clearly much narrower.

**Closed** 2020-05-25 01:29 UTC
Labels: C: manager/widget, P: default, T: enhancement, ux
