### ISSUE TITLE
Colored padlock icon for all newly started applications of AppVM after some use of the system.

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#6653] opened 2021-05-30 10:42 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Icons in dom0 (xfce4-panel), related backend scripts.

**Brief summary**
At some point icons logic of Qubes OS breaks for running AppVM (one or several) and all icons of newly starting applications of this AppVM start to look as colored padlocks.
All windows of this AppVM that were opened before the problem occurs have proper icons. Only newly opened windows have padlocks.

**How Reproducible**
Once a day, maybe once in several days.

**To Reproduce**
Work as usual, mount loop devices, maybe.
I have not found the exact way or reason why icons backend breaks. Ask for logs if needed.

**Expected behavior**
Icons on xfce4-panel depend on the application running.

**Actual behavior**
All newly started windows of AppVM have generic icons - colored padlocks.

**Additional context**
The issue #6292 is a different 100% reproducible issue, somehow connected to the icon size.

**Solutions you've tried**
Rebooting the AppVM helps.
Don't know how to fix it without shutdown.

**Comment by jamke** [comment] 2021-05-30 10:57
Hmm, maybe it's a duplicate of #1495?
#1495 is 6 years old and is not about R4 but R3.1 or even earlier versions. And have no proper report template.

If it's the same issue that exists for 6+ years, please close my ticked as duplicated and change "minor" to something higher if possible. Because it's a basic function of Qubes OS that does not work properly for so many years.

**Comment by andrewdavidwong** [comment] 2021-05-30 23:17
> Hmm, maybe it's a duplicate of #1495?

Ok, closing as a duplicate of #1495.

> #1495 is 6 years old and is not about R4 but R3.1 or even earlier versions.

Age is irrelevant, as is the original reported affected release, as long as it still affects a stable release. Updating milestone to R4.0.

> And have no proper report template.

There was no template back then. :slightly_smiling_face:
 
> If it's the same issue that exists for 6+ years, please close my ticked as duplicated and change "minor" to something higher if possible. Because it's a basic function of Qubes OS that does not work properly for so many years.

Done.

**Closed by andrewdavidwong** 2021-05-30 23:17 UTC
Labels: P: default, T: bug
