### ISSUE TITLE
qubesctl: 'state.cls' is not available. DOM0 configuration failed, not continuing (Whonix)

### ISSUE THREAD

**Issue by phabricator0** [QubesOS/qubes-issues#5154] opened 2019-07-08 07:27 UTC
**Qubes OS version**

R4.0 
(current repo without current-testing/unstable repos enabled)

**Affected component(s) or functionality**

salt?

**Brief summary**
```
sudo qubesctl state.cls qvm.anon-whonix
'state.cls' is not available.
DOM0 configuration failed, not continuing
```

**To Reproduce**

Starting with a R4.0 and whonix 14 installed:

_Steps to reproduce the behavior:_

all commands are issued in dom0:

```
sudo qubes-dom0-update --action=install qubes-template-whonix-gw-15 qubes-template-whonix-ws-15
sudo rpm -e qubes-template-whonix-gw-14-4.0.1-201811040215
sudo rpm -e qubes-template-whonix-ws-14-4.0.1-201811040215
```
reboot
```
sudo qubesctl state.cls qvm.anon-whonix
'state.cls' is not available.
DOM0 configuration failed, not continuing
```

**Expected behavior**

no error output

**Actual behavior**

```
'state.cls' is not available.
DOM0 configuration failed, not continuing
```

**Additional context**

Whonix developer says this is a Qubes issue
https://forums.whonix.org/t/whonix-15-state-cls-is-not-available/7705/4

**Solutions you've tried**

reboot
replaced '14' with '15' in 
`/srv/formulas/base/virtual-machines-formula/qvm/whonix.jinja`

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.whonix.org/wiki/Qubes/Install#Footnotes

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by hexagonrecursion** [comment] 2019-07-08 07:54
There is a typo in the whonix documentation. It should be [`state.sls`](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.sls). There is no such thing as `state.cls` in salt.

**Comment by adrelanos** [comment] 2019-07-08 08:21
This is now fixed.

https://www.whonix.org/w/index.php?title=Qubes%2FInstall&type=revision&diff=49181&oldid=49132

However might not solve the user error since that quote was in the footnote/troubleshooting section. The original command `sudo qubesctl state.sls qvm.anon-whonix` from chapter `Download Whonix ™ Templates and Configure sys-whonix and anon-whonix` was always correct.

**Comment by andrewdavidwong** [comment] 2019-07-08 08:22
> This is now fixed.

Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-07-08 08:22 UTC
Labels: C: Whonix, C: doc, P: default, T: bug
