### ISSUE TITLE
Network Manager icon superimposes several states

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4701] opened 2019-01-10 16:55 UTC
### Affected component(s): Networkmanager icon

On my new system, the Networkmanager icon looks like this: ![screenshot_2019-01-10_17-30-22](https://user-images.githubusercontent.com/4425677/50983613-bb198400-14f7-11e9-8b4c-438f7b07844e.png)

To me, it seems like Networkmanager gets stuck with several state-icons. This is especially obvious in transient states (e.g. while connecting).

This is just a minor UX-issue, everything works as expected.

**Comment by lunarthegrey** [comment] 2019-01-12 05:43
Can confirm this. It's happening to me as well.

Only happens when using the fedora-29 template.

**Comment by ThomasWaldmann** [comment] 2019-01-21 22:47
NM looks same (distorted) for me.

I also have seen another effect, maybe same root cause?

The tray icon of the "vorta" (borgbackup gui) qt app at first looks ok.
Then you right-click on it to open its tray menu and the icon gets distorted (like upper and lower halves swapped in position). Does not go away when closing menu again.
But i gets fix again when switching to another (text mode) VT and back to qubes Xorg display.

**Comment by m-v-b** [comment] 2019-03-31 18:53
Hello,

After researching this issue online, I found that this is a known issue in GTK that is documented in the ArchLinux distribution's wiki [here](https://wiki.archlinux.org/index.php/NetworkManager#nm-applet_tray_icons_display_wrongly).

Accordingly, here is the bug report for GTK: [GTK bug 1280](https://gitlab.gnome.org/GNOME/gtk/issues/1280)

And here is the commit that fixes the issue: [commit](https://gitlab.gnome.org/GNOME/gtk/commit/e3a1593a0984cc0156ec1892a46af8f256a64878)

I was able to work around this issue by recompiling GTK 3.24.3 with `mock` and installing it into my Fedora 29-based template VM.

According to [Fedora's `koji` page for GTK3](https://koji.fedoraproject.org/koji/packageinfo?packageID=10393), Fedora 29 is currently stuck with GTK 3.24.1, meaning that the bug has not been resolved in Fedora 29 yet.

I hope that this information helps someone!

**Comment by andrewdavidwong** [comment] 2019-03-31 19:07
> Hello,
> 
> After researching this issue online, I found that this is a known issue in GTK that is documented in the ArchLinux distribution's wiki [here](https://wiki.archlinux.org/index.php/NetworkManager#nm-applet_tray_icons_display_wrongly).
> 
> Accordingly, here is the bug report for GTK: [GTK bug 1280](https://gitlab.gnome.org/GNOME/gtk/issues/1280)
> 
> And here is the commit that fixes the issue: [commit](https://gitlab.gnome.org/GNOME/gtk/commit/e3a1593a0984cc0156ec1892a46af8f256a64878)
> 
> I was able to work around this issue by recompiling GTK 3.24.3 with `mock` and installing it into my Fedora 29-based template VM.
> 
> According to [Fedora's `koji` page for GTK3](https://koji.fedoraproject.org/koji/packageinfo?packageID=10393), Fedora 29 is currently stuck with GTK 3.24.1, meaning that the bug has not been resolved in Fedora 29 yet.
> 
> I hope that this information helps someone!

Thank you for this information. Closing as "not our bug." If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2019-03-31 19:07 UTC
Labels: C: desktop-linux, P: major, T: bug, ux

**Comment by GammaSQ** [comment] 2019-07-24 08:18
Though this is correctly not a qubes-specific bug, would it be possible to host a newer GTK-version in the qubes-repos? Totally out of my depth on how much work would be necessary to compile a newer GTK-version for fedora-29 templates and weather it would be worth it.
