### ISSUE TITLE
Whiskey Lake CPU support and xen version

### ISSUE THREAD

**Issue by alpha-and-omega** [QubesOS/qubes-issues#5267] opened 2019-08-22 23:01 UTC
Hello! I am new to Qubes OS, and after ~10 attempts I managed to successfully install Qubes-R4.0.2-rc1 on a brand new (1 month since release) laptop "Lenovo Thinkpad X1 Yoga (4th gen)" with Whiskey Lake CPU Core i7-8565U onboard.

Everything started to work smoothly, except one small bug which destroyed all my efforts: before suspend laptop eats 4-5Watts, after suspend it starts eating 13Watts. For some reason system starts eating much more power after wake up from suspend.

To solve this tiny problem I tried every small thing:
1) updated qubeos kernel/tools to testing / unstable - fail
2) installed debian with same (even older) kernel, works - not kernel problem
3) learnt that xen has own power management tool - xenpm. Tried to debug the problem and failed, the only difference pre/post suspend is "Avg freq" which rises from 200000 to 400000.
4) installed free xenserver (XCP-ng) to check if it works and found interesting difference - "xenpm get-cpufreq-para" presented much more info about CPU to me than in qubes os. xenserver's xenpm shows all 8 cpu cores, but Qubeos's xenpm shows only 2 cores info. Xenserver's version of xen: 4.11. Qubes xen: 4.8...
5) Xenserver does not support dom0 suspend, so I was unable to check if it increases power consumption after wake up from suspend. Before suspend it eats 5W too, same as Qubes.

Now, I think problem is in QubesOs's xen, It just fails to recognize my CPU corectly, this is an assumption and I can't test it.

**Describe the solution you'd like**
I would like to test Qubes-OS with xen-4.12. Is it possible to build https://github.com/QubesOS/qubes-vmm-xen/tree/xen-4.12 and use it right now ?

**Where is the value to a user, and who might that user be?**
I will value this a lot, and I am the user ;) and obviuosly all x1 carbon 7th and yoga 4th users too, and probably all Whiskey Lake CPU users too ...

**Comment by andrewdavidwong** [comment] 2019-08-23 11:35
Duplicate of #5210

**Comment by andrewdavidwong** [comment] 2019-08-23 11:35
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-08-23 11:35 UTC
Labels: P: default, T: enhancement

**Comment by dmoerner** [comment] 2019-09-24 16:37
@alpha-and-omega Did you have any trouble getting suspend working with Whiskey Lake? I have a Dell Latitude 7400, and I was able to install after disabling Secure Boot and Intel RST in the bios, but I am unable to resume from suspend with either kernel 4.19 or 5.2 (in kernel-latest).

**Comment by alpha-and-omega** [comment] 2019-09-24 16:52
@dmoerner, I had no problem with resume.
