### ISSUE TITLE
Update all screenshots on website and in documentation

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5838] opened 2020-05-22 18:34 UTC
_child within #5676_

## Problem
Updating the padlocks with Qute Qube icons in the UI for Qubes, will significantly-enough change how new and prospective users are able to build their understanding of Qubes through screenshots on the website and in documentation.

## Solution
Most of the screenshots are pretty old, anyway... so just before the Qute-Qube icons go live, I'm proposing the majority of today's screenshots be replaced with new screenshots.
- All screens on the website; especially the intro/overview parts
- All screens of Qube Manager
- All Devices Widget screens
- QVM-Copy UI
- All menu screens
- Any other components that show multiple listings of Qubes, with icons.

Also, a new page should be added to the documentation to clearly distinguish the icon schema—eg, "This is a `Template-VM` icon, this is a `Service VM` icon, this is a `disp-VM` icon, this is an `App-VM` icon."

**Comment by vrushti-mody** [comment] 2020-06-02 10:00
I would like to work on this issue

**Comment by andrewdavidwong** [comment] 2020-06-04 12:31
> I would like to work on this issue

Thank you! It sounds like there will not be anything to work on until the the UIs are available for new screenshots to be taken. I'm sure an update will be posted here when that happens.

**Comment by fepitre** [comment] 2020-06-04 12:48
Just a little reminder that I remade and added some newer images here: https://github.com/fepitre/qubes-diagrams/tree/newversion for a talk in December. There is source code and PNG that originally Joanna forgot to push. In case that could help.

**Comment by hackerncoder** [comment] 2020-10-22 15:12
Hi.
I was also thinking about updating the images on the website,.
I have 4.1 installed on my computer and am ready to take the pictures, however I would like to know about whether there will be changes in the UI so that I should wait.

**Comment by fepitre** [comment] 2020-10-22 17:13
Yes thank you that would help. Generally default UI will not change that much. I can propose you to write a little list of what exactly you want to update then we can confirm you. That's for you to not lose your time. Also, for your information, current content included in `qubes-doc` is located at `https://github.com/QubesOS/qubes-attachment`.

**Comment by hackerncoder** [comment] 2020-10-22 18:16
I was thinking about going at it like this:

```P1:
https://www.qubes-os.org/intro/
https://www.qubes-os.org/screenshots/

P2:
https://www.qubes-os.org/doc/getting-started/
https://www.qubes-os.org/doc/disposablevm/
https://www.qubes-os.org/doc/split-gpg/

P3:
https://www.qubes-os.org/doc/managing-appvm-shortcuts/
https://www.qubes-os.org/doc/firewall/
https://www.qubes-os.org/doc/resize-disk-image/```

**Comment by fepitre** [comment] 2020-10-22 18:22
Yes that would be great for every item you listed. Thank you very much for that.

**Comment by hackerncoder** [comment] 2020-10-22 20:21
I was thinking, how should I name them?

The current ones have something like this `r<release-number><beta, rc or minor version>-<description of image>`

Should I just do r4.1-<description of image>?

**Comment by fepitre** [comment] 2020-10-22 20:27
Yes prefix `r4.1-` is fine.

**Comment by hackerncoder** [comment] 2020-10-22 20:31
P1 should be done and is uploaded, I might need to stop for today so will continue with the rest tomorrow and however many days it will take.
https://github.com/hackerncoder/qubes-attachment

**Comment by fepitre** [comment] 2020-10-22 20:32
Sure thank you again for doing this! That helps a lot.

**Comment by andrewdavidwong** [comment] 2020-10-24 10:20
Thanks for doing this, @hackerncoder. However, we should wait on using 4.1 images as the live default images in docs until 4.1 is a stable release.

**Comment by hackerncoder** [comment] 2020-10-24 18:09
No need to thank me, I love doing this.

Not a bad idea (I do object since 4.1 looks a lot like 4.0.3, but ok). However I just wanted to know what "stable" is. All the way to release? Not RC or beta?

**Comment by andrewdavidwong** [comment] 2020-10-24 21:22
> Not a bad idea (I do object since 4.1 looks a lot like 4.0.3, but ok).

If there are cases where it looks exactly the same, then those images can go live now, but we want to avoid a situation where the documentation does not match the latest stable release, because then it's less useful for users.

> However I just wanted to know what "stable" is. All the way to release? Not RC or beta?

Correct.

**Comment by hackerncoder** [comment] 2020-10-24 22:05
Depending on how much exactly means to you, maybe 1 or 2 will be ready to go live.

Because we have switched to Nina's cube (#5657) in 4.1, which I don't believe to be in 4.0.3, then none showing Qube Manager, Program Menu or just even the desktop (qube management icon in notification area) can go live.

**Comment by andrewdavidwong** [comment] 2020-10-25 12:03
> I just saw your announcement on reddit where can I find information about it

I'm afraid there's no other information yet, but we'll publish an announcement when there is.

> and more importantly for this task: will the cube design be backported?

@marmarta, do you know the answer to this?

> I also have a problem because that I have no or little images of the current desktop to compare against.

I think that's the problem this issue was intended to solve. :slightly_frowning_face: On the bright side, thanks to your work, there will be 4.1 images to compare against whenever they need to be updated again after that. :slightly_smiling_face:

**Comment by hackerncoder** [comment] 2020-10-25 16:24
> I'm afraid there's no other information yet, but we'll publish an announcement when there is.

Great!

> I think that's the problem this issue was intended to solve. 

It seems so.

> there will be 4.1 images to compare against whenever they need to be updated again after that. 

I hope that it won't be 2 or 3 releases before that happens.

&nbsp;

And as you can see, I have uploaded all (except the split-gpg which I have neglected because I need a split-gpg setup) and made a pull request to add them to qubes-attachment.

A pull request for qubes-doc to change to those images is in the works.  
I just need to know what to do with images that reference Windows integration using QWT and Nalu's Customized KDE images

**Comment by andrewdavidwong** [comment] 2020-10-25 21:24
> And as you can see, I have uploaded all (except the split-gpg which I have neglected because I need a split-gpg setup) and made a pull request to add them to qubes-attachment.

Merged. Thank you!

> I just need to know what to do with images that reference Windows integration using QWT and Nalu's Customized KDE images

Sorry, I don't understand. Could you be a bit more specific about what you mean by "what to do with [them]"? For example, is it that you can't take 4.1 screenshots of those things because they're not available to you?

**Comment by hackerncoder** [comment] 2020-10-26 08:25
I have read that QWT doesn't work with Win10 and the qubes 4 so I can't remake the seamless windows integration screenshots. I could run windows as a regular HVM if you wanted me to, otherwise I would just remove the screenshots.

And I find Nalu's images to be too much work, again, if you want me to recreate them, I am willing to, otherwise I would just remove them.

(Talking about Screenshots: https://www.qubes-os.org/screenshots/)

**Comment by andrewdavidwong** [comment] 2020-10-28 00:58
> I have read that QWT doesn't work with Win10 and qubes 4, so I can't remake the [seamless Windows integration screenshots](https://www.qubes-os.org/attachment/wiki/QubesScreenshots/r2b3-windows-seamless-1.png). I could run windows as a regular HVM if you wanted me to, otherwise I would just remove the screenshots.

@GWeck and @deeplow, I know that you just overhauled this documentation. Can you say whether these images are still being used or are out-of-date?

> And I find [Nalu's images](https://www.qubes-os.org/attachment/wiki/QubesScreenshots/r3rc1-nalu-desktop-1.png) (showing KDE customized a lot) to be too much work. If you want me to recreate them, I am willing to, otherwise I would just remove them.
> 
> (Talking about Screenshots: https://www.qubes-os.org/screenshots/) 

Agreed.

**Comment by GWeck** [comment] 2020-10-28 10:42
For the current state of QWT under R4.1, see my tests at [https://qubes-os.discourse.group/t/testing-windows-and-qwt-in-r4-1/1143](https://qubes-os.discourse.group/t/testing-windows-and-qwt-in-r4-1/1143). In short: QWT does not really run on R4.1, and so far I have not been able to get seamless mode with Windows 7. For Windows 10, seamless mode is unlikely to be available soon, if at all, not even in R4.0.3.

For R4.0.3 and Windows 7, the existing screeshots are still appropriate, in my opinion. For R4.0.3 and Windows 10, a screenshot showing the system in non-seamless mode might be good, showing that Qubes supports this combination.

Screenshots for Windows 7 and 10 as HVM without QWT in R4.1 are possible; here's a simple example:

![Bildschirmfoto_2020-10-28_11-29-43](https://user-images.githubusercontent.com/22047384/97425205-12c5f100-1912-11eb-9bb6-2a402c8a4663.png)

**Comment by hackerncoder** [comment] 2020-10-28 12:47
>  If there are cases where it looks exactly the same, then those images can go live now, but we want to avoid a situation where the documentation does not match the latest stable release, because then it's less useful for users.

Uh.. @andrewdavidwong, the images have changed.  
See:  
https://www.qubes-os.org/screenshots/

**Comment by andrewdavidwong** [comment] 2020-10-29 05:55
> > If there are cases where it looks exactly the same, then those images can go live now, but we want to avoid a situation where the documentation does not match the latest stable release, because then it's less useful for users.
> 
> Uh.. @andrewdavidwong, the images have changed. Was this supposed to happen?
> See: https://www.qubes-os.org/screenshots/

Isn't this from your PR (https://github.com/QubesOS/qubes-doc/pull/1065), which I just merged yesterday?

After reviewing that PR, I thought it consisted only of images that you selected as being close enough to 4.0 that they were okay to go live now. Perhaps I misunderstood. Did you intend for that PR to be held until 4.1 went live?

**Comment by hackerncoder** [comment] 2020-10-29 09:36
> consisted only of images that you selected as being close enough to 4.0

No.

> Did you intend for that PR to be held until 4.1 went live?

Yes, I probably should have made that clear

> These new screenshots seemed closer to 4.0 than the old ones (just from the opposite direction), so I figured it was still an improvement, even if they don't exactly match 4.0.

That was why I said:

> Depending on how much exactly means to you

But yes, they are closer to what we have now. For the most part it should be fine. 

> P.S. -- Here's a real life example of future release screenshots being confusing for users (even when explained): #6135 (comment)

I see. With my very images. (P.s. the old images are still there. https://www.qubes-os.org/attachment/wiki/GettingStarted/q40_widgets.png, most of the time you just have to remove `r4.1-` to get the old one)

> P.S.S. -- I see that your new screenshots are a hit on the subreddit, so perhaps it's a net gain to have them up a bit early. slightly_smiling_face

They definitely are.

**Comment by hackerncoder** [comment] 2020-10-29 10:55
https://github.com/QubesOS/qubes-attachment/pull/37. 

I really should check through more things before pushing.

**Comment by ninavizz** [comment] 2021-02-07 06:46
HI folks! I'm looking at things on the Qubes website, and just noticed that many of the screenshots on it now are not of the current version of Qubes, but of a test build of 4.1. 

FWIW, it's likely to be very confusing for new users, to see images that do not match what they've downloaded. It may even cause nervousness around safety. 

Likewise, it's also probably best not to take screenshots of a build, until it is in its final days of testing and is close to being deployed. 

It feels like it'd be a good thing to establish in the project's Release playbook, that all website and documentation screenshots get updated with each new release—and to assign a point-person to perhaps own that? Otherwise, we can end-up in the situation things are at right now, where we're chasing-down what is the most recent and where all images need to go. 

Perhaps as a first step towards that, maybe an inventory of all images across the docs and the website should happen, so that when a release happens someone can very easily just work-down a list to make updates?

The above said: @hackerncoder I appreciate your effort so very much, to update the website—thank you!! Pls don't take the above as an admonishment. Only concerned about folks being confused... and wanting what's on the website and in the docs, to accurately reflect what folks download and install. 

Any chance we could get some `4.0` screenshots up, with the current `time-sync` icons in the Tray? To my knowledge, those are the only things updated in the UI after the initial deploy of `4.0` was pushed.

**Comment by deeplow** [comment] 2021-02-07 07:27
Maybe some images could be grabbed [from the automated testing](https://github.com/marmarek/openqa-tests-qubesos/tree/master/needles)?

I guess that could make sense as those will have to be updated anyways with new releases.

**Comment by hackerncoder** [comment] 2021-02-07 14:51
> FWIW, it's likely to be very confusing for new users, to see images that do not match what they've downloaded. It may even cause nervousness around safety.

Yep we saw that just after it was updated, see Andrews comment above.

It's at least closer in looks than the old screenshots (Real world example of old screenshots: https://old.reddit.com/r/Qubes/comments/lbhxxy/memory_and_cpu_utilization_in_qube_manager/)

> Likewise, it's also probably best not to take screenshots of a build, until it is in its final days of testing and is close to being deployed.

I asked about it.

> It feels like it'd be a good thing to establish in the project's Release playbook, that all website and documentation screenshots get updated with each new release—and to assign a point-person to perhaps own that? Otherwise, we can end-up in the situation things are at right now, where we're chasing-down what is the most recent and where all images need to go

Definitely. If we need a person to do something like that I volunteer.

> Perhaps as a first step towards that, maybe an inventory of all images across the docs and the website should happen, so that when a release happens someone can very easily just work-down a list to make updates?

Again a definitely, I hunted down many of the images, but it might not be all.

> The above said: @hackerncoder I appreciate your effort so very much, to update the website—thank you!! Pls don't take the above as an admonishment. Only concerned about folks being confused... and wanting what's on the website and in the docs, to accurately reflect what folks download and install.

I don't. I that's also what I want, exactly why I updated them. Personally I think having r4.1 images that look more like r4.0 is better than the old r3.x or r2 or even sometimes (I think) r1 (see the above mentioned example of old images being a problem), of course too new and we have problems (see Andrews comment), so it *has* to be exactly the newest stable release.

> Any chance we could get some 4.0 screenshots up, with the current time-sync icons in the Tray? To my knowledge, those are the only things updated in the UI after the initial deploy of 4.0 was pushed.

I was thinking of reinstalling Qubes anyways, so sure.

> Maybe some images could be grabbed from the automated testing?
>  
> I guess that could make sense as those will have to be updated anyways with new releases.

That might be an idea. Of course, the current images are staged (at least the once I took, I staged them to look like the old images)

**Comment by hackerncoder** [comment] 2021-02-09 20:12
So, I just want to be clear, are there any restrictions on what I can put into a screenshot? I was going to use `"Just Because It's Gay?": Transgressive Design un Queer Coming of Age Visual Novels` for a random PDF, but then I thought: "Oh god, politics, can I, or should I even put that In?"

**Comment by DemiMarie** [comment] 2021-02-09 20:16
IIRC, it needs to be something you have the right to redistribute.  I am not a lawyer, though.

**Comment by hackerncoder** [comment] 2021-02-09 20:29
You're right. That is something to look out for.

**Comment by andrewdavidwong** [comment] 2021-02-10 13:14
> So, I just want to be clear, are there any restrictions on what I can put into a screenshot? I was going to use `"Just Because It's Gay?": Transgressive Design in Queer Coming of Age Visual Novels` for a random PDF, but then I thought: "Oh god, politics, can I, or should I even put that In?"

For Qubes screenshots on the official website, we won't be using anything political, controversial, edgy, etc. It's just not the place for it, and it risks opening up a can of worms that we frankly don't have the time to deal with.

**Comment by ninavizz** [comment] 2021-02-15 23:55
WRT PDFs used... per @DemiMarie and @andrewdavidwong I'd recommend something that has no copyright AND is entirely un-controversial... so, a PDF of something in the public realm. If someone wants to be ultra-contrarian, the lyrics to "Happy Birthday" would be funny, but I'd suggest something like Pentagon Papers archives or the schematics for an old piece of technology (not a cotton gin) with an expired patent; Penicillin, maybe? 

@hackerncoder I do usability stuff for a living. The screenshots are too different for new users. It's my strong preference that they be rolled-back to reflect an over-abundance of colored padlocks everywhere, but with the updated `time-sync` widget. So, yes, total padlocks-overload 

Also, I am not super technical, and care deeply about making Qubes more usable to less technical at-risk users... so please bear with me as I will occasionally use imprecise language such as "Whonix globe-blob icon thing in Tray" to describe UI tidbits. :)

**Comment by hackerncoder** [comment] 2021-02-16 00:09
Just gotta pull myself to-get and get those images renamed and a PR created. There are definetly some of them I would redo now that I am looking at them. I should look into backups, they might make it easier to reinstall. I replaced many things with custom written stuff so that copyright wasn't an issue. 

Yep. That's why I am willing to reinstall Qubes to take images.

I also care about making stuff usable to less technical users, and just helping with Qubes in general, the reason we are having a conversation right now. No problem with the language.

**Comment by hackerncoder** [comment] 2021-02-16 01:46
Done!

https://github.com/QubesOS/qubes-doc/pull/1114

https://github.com/QubesOS/qubes-attachment/pull/40

**Comment by andrewdavidwong** [comment] 2021-02-16 09:00
> WRT PDFs used... per @DemiMarie and @andrewdavidwong I'd recommend something that has no copyright AND is entirely un-controversial... so, a PDF of something in the public realm. If someone wants to be ultra-contrarian, the lyrics to "Happy Birthday" would be funny, but I'd suggest something like Pentagon Papers archives or the schematics for an old piece of technology (not a cotton gin) with an expired patent; Penicillin, maybe?

Just lorem ipsum type stuff is fine for this. No need to get extra fancy.

**Comment by hackerncoder** [comment] 2021-02-17 01:05
How would image text be done? Some of the images have copyright (CC) that needs to be stated.

**Comment by ninavizz** [comment] 2021-02-17 02:48
"Image Text." Example? Not trying to be difficult... just, also been playing "dodge the copyrights!" for a few too many dang years. 

TY again @hackerncoder for the re-do on these. Yay to teamwork for helping less technical users. :)

**Comment by hackerncoder** [comment] 2021-02-17 02:51
Example: I need to state that an image used in r4.0-xfce-three-domains-at-work.png is licensed under CC-BY. Somewhere/somehow I need to do that on the Qubes website (I think, IANAL).

**Comment by hackerncoder** [comment] 2021-02-17 03:06
Mock-up:

![Screenshot_2021-02-17_04-04-53](https://user-images.githubusercontent.com/14183017/108150704-04703080-70cd-11eb-8409-f3acbd8a29a4.png)

**Comment by marmarek** [comment] 2021-02-17 03:16
Will it work to add a text file (`COPYRIGHT`?) to the qubes-attachment repo with that info? It isn't exactly on the website, but is closer to where the actual image is stored - which is also public.

**Comment by hackerncoder** [comment] 2021-02-17 03:17
Sure I guess.

**Comment by marmarek** [comment] 2021-02-17 04:14
Top level like you did is fine. But there needs to be a list what applies to which file.

**Comment by andrewdavidwong** [comment] 2021-02-17 19:15
Could also just replace it with a non-copyrighted image.

**Comment by hackerncoder** [comment] 2021-02-17 19:40
I will try to next time.

**Comment by andrewdavidwong** [comment] 2021-04-23 04:29
Is this issue done? @hackerncoder @ninavizz

**Comment by hackerncoder** [comment] 2021-04-23 21:05
Pretty much. The majority of the screenshots (I found, there may be more) are now updated to 4.0 (https://github.com/QubesOS/qubes-issues/issues/5838#issuecomment-714671635).

**Closed** 2021-04-23 23:07 UTC
Labels: C: doc, C: website, P: default, T: enhancement
