### ISSUE TITLE
Attaching device through devices widget does nothing, while qvm-usb works

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4999] opened 2019-04-25 20:17 UTC
I'm experiencing a strange issue during testing, at times attaching a device (yubikey) does nothing at all. The device does not get attached. Although the device does show in the list it simply does not get attached to the vm. The only solution is to kill qui-devices which then restarts itself and then its possible to attach again, or to attach the device via command line (qvm-usb)

_Originally posted by @yubiguel in https://github.com/QubesOS/qubes-issues/issues/4849#issuecomment-486752685_

**Comment by marmarek** [comment] 2019-04-25 20:22
I've seen similar thing few days ago too.
Strangely, I didn't seen any message in logs (journalctl, `.xsession-errors`) - simply nothing have happened.

**Comment by marmarta** [comment] 2019-05-03 12:46
what do you mean by "does show in the list it simply does not get attached to the vm"? does it:
- appear in the list as not attached (what happens if you try to attach it?)
- appear in the list as attached (what happens if you try to detach it?)

**Comment by noonker** [comment] 2019-05-06 15:31
I have the same issue. It appears that qui-devices isn't updating the state of the dropdown. 
1. From qui-devices attach a device to a domain
2. A notification will let you know that the device has been attached (and a lsusb will confirm that it has) 
3. The qui-devices dropdown will not update it's state  (still shows as not attached)
4. Run `killall qui-devices` and it will restart showing the correct state of a usb devices.

Starting `qui-devices` from a terminal in dom0 and repeating the above steps yields this error:
`(qui-devices:10849): GLib-GIO-CRITICAL **: g_application_send_notification: assertion '!g_application_get_is_remote (application)' failed`

**Comment by yubiguel** [comment] 2019-05-09 15:12
> what do you mean by "does show in the list it simply does not get attached to the vm"? does it:
> 
> * appear in the list as not attached (what happens if you try to attach it?)
> * appear in the list as attached (what happens if you try to detach it?)

Sorry for the late reply. What I mean is that when you click on the tray icon you will see the usb device listed there as not attached (appears in the list) but when you try to attach the device to a vm it does not get attached. (nothing happens). By killing qui-devices in dom0 you can now re-attach. This is happening to me constantly.

**Comment by holiman** [comment] 2019-06-11 11:04
> What I mean is that when you click on the tray icon you will see the usb device listed there as not attached (appears in the list) but when you try to attach the device to a vm it does not get attached. (nothing happens)

I can confirm the exact same thing happening. I recently upgraded all templates to Fedora-29. After `killall qui-devices` I can attach and something actually happens (I get a notification that it was attached)

**Comment by marmarek** [comment] 2019-06-21 17:13
Found it! The exception and some debug prints:
```
Jun 21 19:09:50 dom0 widget-wrapper[14518]: toggle dev <qui.tray.devices.Device object at 0x77abdb340c50> vm disp1323 attached False
Jun 21 19:09:50 dom0 widget-wrapper[14518]: attach_item called for <qui.tray.devices.VM object at 0x77abdb329cf8>
Jun 21 19:09:50 dom0 widget-wrapper[14518]: detach_item called
Jun 21 19:09:50 dom0 widget-wrapper[14518]: detach_item success
Jun 21 19:09:50 dom0 widget-wrapper[14518]: detach_successful = True
Jun 21 19:09:50 dom0 widget-wrapper[14518]: attach_item exception: TypeError('A logger name must be a string',)
Jun 21 19:09:50 dom0 widget-wrapper[14518]: Traceback (most recent call last):
Jun 21 19:09:50 dom0 widget-wrapper[14518]:   File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 77, in attach_item
Jun 21 19:09:50 dom0 widget-wrapper[14518]:     vm_to_attach = self.qapp.domains[menu_item.vm]
Jun 21 19:09:50 dom0 widget-wrapper[14518]:   File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 90, in __getitem__
Jun 21 19:09:50 dom0 widget-wrapper[14518]:     return self.get_blind(item)
Jun 21 19:09:50 dom0 widget-wrapper[14518]:   File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 105, in get_blind
Jun 21 19:09:50 dom0 widget-wrapper[14518]:     self._vm_objects[item] = cls(self.app, item, klass=klass)
Jun 21 19:09:50 dom0 widget-wrapper[14518]:   File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 59, in __init__
Jun 21 19:09:50 dom0 widget-wrapper[14518]:     self.log = logging.getLogger(name)
Jun 21 19:09:50 dom0 widget-wrapper[14518]:   File "/usr/lib64/python3.5/logging/__init__.py", line 1787, in getLogger
Jun 21 19:09:50 dom0 widget-wrapper[14518]:     return Logger.manager.getLogger(name)
Jun 21 19:09:50 dom0 widget-wrapper[14518]:   File "/usr/lib64/python3.5/logging/__init__.py", line 1151, in getLogger
Jun 21 19:09:50 dom0 widget-wrapper[14518]:     raise TypeError('A logger name must be a string')
Jun 21 19:09:50 dom0 widget-wrapper[14518]: TypeError: A logger name must be a string
```
The key thing: `self.qapp.domains[menu_item.vm]`, with `menu_item.vm` being `qui.tray.devices.VM` object instead of string (VM name).

**Comment by marmarta** [comment] 2019-08-08 14:15
Looks like this is fixed in testing (judging from comments here and there) - I'm closing this issue, if it reemerges please reopen.

**Comment by 4NobleTruths** [comment] 2020-10-11 08:29
This is definitely not fixed with SD cards. I'm not sure I could even list all the possible permutations of failed in this.
Some of them are:

- Showing the device unattached to a VM, but then giving a black popup error that it's already attached, when  the VM clearly shows it's not.
- Showing the same SD card being attached to two different VMs at the same time, when it's attached to none in reality.
- Showing the SD card in one VM as being attached to another VM, when sys-usb has attached it to none in reality.

And killing qui-devices doesn't fix it either. Neither does restarting one or more VMs involved and sys-usb, plugging and replugging... It just works sometimes, almost as if something eventually times out.

This is with sys-usb based on Fedora 32 XFCE and Debian 10.

**Closed** 2023-08-05 09:25 UTC
Labels: T: bug, C: manager/widget, P: default, needs diagnosis, eol-4.0
