### ISSUE TITLE
Gray-colored appvms have green-colored application items

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3521] opened 2018-02-02 23:34 UTC
#### Qubes OS version:

4.0rc4

---

### Steps to reproduce the behavior:

1. Change VM color to gray.
2. Go to Qubes app menu entry for that VM

### Expected behavior:

Submenu items are gray.

### Actual behavior:

Submenu items are green.

### General notes:

I only see this mis-coloring with gray.

---

#### Related issues:

Please also add more colors - brown, pink, aquamarine, ...

**Comment by andrewdavidwong** [comment] 2018-02-03 03:50
This appears to be a duplicate of #3471. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-03 03:50 UTC
