### ISSUE TITLE
[R4.0] Display in portrait mode causes mouse click glitches / freezes on login

### ISSUE THREAD

**Issue by Brandl** [QubesOS/qubes-issues#4271] opened 2018-09-03 10:15 UTC
### Qubes OS version:
R4.0

### Affected component(s): 

VMs / Graphics?

---

### Steps to reproduce the behavior:

Connect two displays, rotate one via the "[dom0] Display" utility

### Expected behavior:

I can click anywhere in a VM Window (like "[untrusted] Firefox").

### Actual behavior:

Clicks on *all* screens are only registered in the upper third of VM applications. dom0 are working fine though.
Also some times the actual click position differs from the mouse point position.
I have also observed, that while logging in the system freezes on login, but stops to as soon as I disconnect the display in vertical orientation.

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-09-03 19:44
Probable duplicate of #3253

**Closed** 2023-08-05 09:17 UTC
Labels: T: bug, C: gui-virtualization, eol-4.0
