### ISSUE TITLE
Dashes disappear when copying between vm

### ISSUE THREAD

**Issue by frozentime345** [QubesOS/qubes-issues#4739] opened 2019-01-19 05:11 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Copying text between vms 

---

### Steps to reproduce the behavior:

Whenever I copy "7/1 - 1/1,

- 06" to another vm the dashes disappear. I'm copying from LibreOffice to another LibreOffice.

### Expected behavior: 

Dashes still exist after copy

### Actual behavior:

Dashes disappear

### General notes:

---

**Comment by andrewdavidwong** [comment] 2019-01-19 23:21
I can confirm that **en dashes** and **em dashes** are not copied via the inter-VM clipboard. **Hyphens** are fine.

Strangely, we already have another issue (#2845) reporting that em dashes are _corrupted_ (rather than absent) when copied via the inter-VM clipboard.

**Comment by jamke** [comment] 2020-10-12 13:29
I also have this issue. Probably everybody does. 

Text copying s very basic-level stuff, so it's very expected to work fine. How can one promote this issue to be diagnosed and solved faster? More than a year passed and still text copying is not working right between domains.

**Comment by andrewdavidwong** [comment] 2020-10-13 02:47
> I also have this issue. Probably everybody does.
> 
> Text copying s very basic-level stuff, so it's very expected to work fine. How can one promote this issue to be diagnosed and solved faster? More than a year passed and still text copying is not working right between domains.

I've raised the issue priority. Unfortunately, the dev team has a *ton* of work to do relative to their size, including many open issues that are just as important as this one (and many even more critical). Unless you are willing to [submit patches](https://www.qubes-os.org/doc/source-code/#how-to-send-patches) or get another contributor to do so, I'm afraid there is not much you can do except find workarounds and continue to wait patiently.

**Comment by marmarek** [comment] 2020-12-03 03:39
This actually is a duplicate of #2845

**Comment by marmarek** [comment] 2020-12-03 03:39
Duplicate of #2845

**Closed by marmarek** 2020-12-03 03:39 UTC
Labels: C: core, P: major, T: bug, needs-diagnosis
