### ISSUE TITLE
Any qrexec call from DispVM to opener VM kills DispVM

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#4273] opened 2018-09-04 15:32 UTC
### Qubes OS version:
R4.0, latest current-testing (but it's not a new problem)

---
### Steps to reproduce the behavior:
1. Open a terminal in any VM (called "sourcevm" in this example)
2. In that terminal, run  `qvm-run-vm --dispvm '/usr/lib/qubes/qrexec-client-vm \$default qubes.Filecopy </dev/null; echo sleeping supposedly forever; sleep inf'`
3. In the dom0 permission / VM selection dialog that pops up, choose sourcevm and confirm.

### Expected behavior:
The `qvm-run-vm` command should block forever (because of the `sleep inf` at the end).

### Actual behavior:
The `qvm-run-vm` command finishes a few seconds after showing the "sleeping supposedly forever" message, because the DispVM is killed for some reason.

Last line in /var/log/qubes/qrexec.dispNNNN.log says `libvchan_is_eof`.

### General notes:
If any other VM than sourcevm is chosen the dom0 dialog, everything works as expected (i.e. the DispVM is not killed).

**Comment by marmarek** [comment] 2018-09-04 15:53
Duplicate of #3318

**Closed by marmarek** 2018-09-04 15:53 UTC
