### ISSUE TITLE
"ERROR: Failed to perform backup: error in addproc" around 75% complete

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#1588] opened 2016-01-06 10:54 UTC
Every time I attempt to do an encrypted backup I end up with an error around 75% complete. The error states:

```
ERROR: Failed to perform backup: error in addproc
```

As stated in the title, I am running RC3.1 and I have updated dom0 using `current testing`. Tell any other information you need.

**Comment by marmarek** [comment] 2016-01-06 12:41
Duplicate of #1515

**Comment by Rudd-O** [comment] 2016-06-10 11:26
Backup just failed for me right as it was doing the second-to-last VM (I checked with lsof, the root.img of that second-to-last VM was open).  Sure enough, error with addproc.

There are three dangling symlinks in /root, a few in /var/lib/qubes/<the kernels directory>, and three dangling symlinks in my home directory.  None of these should have been cause for the backup to fail, because when I performed a backup of *only* Dom0, that worked fine.

I am so pissed right now.  I had left the backup running overnight, it had backed up 400 GB of data, and then it craps out, leaving me with a corrupted file that cannot be used, and a machine I cannot move because the very thing that was supposed to protect its data from theft -- you guessed it, the backup -- simply cannot be completed.

Also today I discover that the backup doesn't even work for the VMs that were in fact successfully backed up!  So, in this sense, the backup tool is inferior to even a simple tar cvzf | openssl enc.  Not to mention slower.

But I guess the thing that pisses me off the most, is that the backup tool EATS THE EXCEPTION.  It shows me no error message whatsoever, just says "error in addproc".   I could fix the issue if I had seen the exception, but as it is, after 400 GB of backing stuff up, to get such a cryptic error, I mean this is probably only slightly marginally better than just crapping out without any error message.  WTH is addproc?  Error in addproc?  What error!  Well, I can't know because the code won't tell me, and I do not have another eight hours to reproduce the issue at this point.

I think I will stop using the backup tool altogether, and start using some other method to back up data.

qubes-core-dom0-3.1.16-1.fc20.x86_64

**Comment by andrewdavidwong** [comment] 2016-06-12 14:05
@Rudd-O: Sorry to hear about your backup troubles. FWIW, I too have noticed that `qvm-backup` tends to fail on "large" backups. Not sure if this is the same issue, and I don't know what exactly the cause is, but my personal workaround has just been to back up smaller sets of VMs (rather than trying to back up all of my VMs at once).

**Comment by marmarek** [comment] 2016-06-12 14:08
@Rudd-O do you have a lot of small VMs, or few big ones? Do you have any VM larger than 100GB?

**Comment by Rudd-O** [comment] 2016-06-12 17:53
Yes, one of my VMs is literally 115 GB.  I do have dozens of small VMs though.

**Comment by marmarek** [comment] 2016-06-12 18:13
> Yes, one of my VMs is literally 115 GB. I do have dozens of small VMs though.

Do you use compression?

I'll check that. Backup file format have archive split into 100MB files, and named with 3-digits sequential number. In theory having more than 1000 files (which is 100GB) should be handled by simply using 4-digits there, but maybe it doesn't work for some reason.

**Comment by Rudd-O** [comment] 2016-06-12 18:32
On 06/12/2016 06:13 PM, Marek Marczykowski-Górecki wrote:
>
>     Yes, one of my VMs is literally 115 GB. I do have dozens of small
>     VMs though.
>
> Do you use compression?
>
> I'll check that. Backup file format have archive split into 100MB
> files, and named with 3-digits sequential number. In theory having
> more than 1000 files (which is 100GB) should be handled by simply
> using 4-digits there, but maybe it doesn't work for some reason.
>

No compression.

Perhaps the 1000 files limit is something I hit.  But I have no way of
knowing, and I see no way how that could have happened, since the
(unhelpful) "error in addproc" happened at the very end, way after that
big VM had been backed up.

Honestly, the backup tool should be replaced by something like
Duplicity.  They get it right, they do *incremental* backups, they do
*encryption*, and they do arbitrary targets, so it would be extremely
easy to accommodate backing up to another VM, or even to damn S3 if we
wanted to.  Ideally, the way I would see that working is:

1.  Take snapshot of file system containing VMs.  Mount the snapshot
somewhere, read-only.

2.  Execute duplicity pointing it to the read-only VM data source, and
the target storage destination (VM or local mountpoint)

3.  Destroy snapshot.

This would also allow for backup of VMs that are running, so no need to
shut down VMs during backup.

I highly recommend we research replacing qvm-backup with Duplicity.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by andrewdavidwong** [comment] 2016-06-12 18:48
We already have an issue open for considering incremental backup support (#858). Please post your comment there so that we can keep distinct issues and discussions organized.

Note that we also had someone ask about Duplicity here: https://github.com/QubesOS/qubes-issues/issues/971#issuecomment-198133151

My response was here: https://github.com/QubesOS/qubes-issues/issues/971#issuecomment-198441965

**Comment by StevenLColeman42** [comment] 2016-08-08 14:50
I just had this same problem. First I had my 3.0 fc23 template go south and all vms refused to run, so I upgraded to 3.2 and restored my 3.0 VM's into the new system. Since I lost a few things during the transition I wanted to be sure to do a backup of the new 3.2 system before doing much configuration other than getting up to date on patches.

When I did the first backup it failed with the same error, after searching for a solution I found this thread and checked my link files. I found two corrupted links which I fixed and my backups completed just now. What was in common between the two links is that they were both vm-template icon.png files, and both had an invalid path where one started with vm1//usr/share/... and the other vm8/vm8//usr/share/... but the remainder of the path was otherwise correct. Once I pointed these correctly the backup worked like a charm. Something obviously corrupted these two links in a similar manor but exactly when that happened I do not know. I'm still in recovery mode so I can not spend too much time on this right now but I thought this commonality between the two broken links might give you a clue.

**Comment by Rudd-O** [comment] 2016-08-12 13:36
I got a functioning version of a Duplicity backend for a Qubes VM, which works well with the latest Duplicity 0.7.x present in Fedora 23.  Place the following file `qubesvmbackend.py` along the other backends in the Duplicity site-packages backends directory, then try `duplicity full /source/dir qubesvm://yourbackupvm/path/to/directory/inside/vm` and report back.

```
# -*- Mode:Python; indent-tabs-mode:nil; tab-width:4 -*-
#
# This file is NOT part of duplicity.  It is an extension to Duplicity
# that allows the Qubes OS dom0 to back up to a Qubes OS VM.
#
# Duplicity is free software, and so is this file.  This file is
# under the same license as the one distributed by Duplicity.

import io
import os
import pipes
import subprocess

import duplicity.backend
from duplicity import log, progress
from duplicity.errors import *

BLOCKSIZE = 1048576  # for doing file transfers by chunk
MAX_LIST_SIZE = 10485760  # limited to 10 MB directory listings to avoid problems


class QubesVMBackend(duplicity.backend.Backend):
    """This backend accesses files stored on a Qubes OS VM.  It is intended to
    work as a backed within a Qubes OS dom0 (TCB) for the purposes of using
    Duplicity to back up to a VM.  No special tools are required other than
    this backend file itself installed to your Duplicity backends directory.

    Missing directories on the remote (VM) side will NOT be created.  It is
    an error to try and back up to a VM when the target directory does
    not already exist.

    module URL: qubesvm://vmname/path/to/backup/directory
    """
    def __init__(self, parsed_url):
        properly_parsed_url = parsed_url
        duplicity.backend.Backend.__init__(self, properly_parsed_url)
        if properly_parsed_url.path:
            self.remote_dir = properly_parsed_url.path
        else:
            self.remote_dir = '.'
        self.hostname = properly_parsed_url.hostname

    def _validate_remote_filename(self, op, remote_filename):
        if os.path.sep in remote_filename or "\0" in remote_filename:
            raise BackendException(
                ("Qubes VM %s failed: path separators "
                 "or nulls in destination file name %s") % (
                     op, remote_filename))

    def _dd(self, iff=None, off=None):
        cmd = ["dd", "status=none", "bs=%s" % BLOCKSIZE]
        if iff:
            cmd.append("if=%s" % iff)
        if off:
            cmd.append("of=%s" % off)
        return cmd

    def _execute_qvmrun(self, cmd, stdin, stdout, bufsize=MAX_LIST_SIZE):
        subcmd = " ".join(pipes.quote(s) for s in cmd)
        cmd = ["qvm-run", "--pass-io", "--", self.hostname, subcmd]
        return subprocess.Popen(
            cmd,
            stdin=stdin,
            stdout=stdout,
            close_fds=True
        )

    def _put(self, source_path, remote_filename):
        """Transfers a single file to the remote side."""
        self._validate_remote_filename("put", remote_filename)
        file_size = os.path.getsize(source_path.name)
        rempath = os.path.join(self.remote_dir, remote_filename)
        cmd = self._dd(off=rempath)
        progress.report_transfer(0, file_size)
        try:
            p = self._execute_qvmrun(cmd,
                                     stdin=subprocess.PIPE,
                                     stdout=open(os.devnull),
                                     bufsize=0)
        except Exception, e:
            raise BackendException(
                "Qubes VM put of %s (as %s) failed: (%s) %s" % (
                    source_path.name, remote_filename, type(e), e))
        buffer = bytearray(BLOCKSIZE)
        fobject = open(source_path.name, "rb")
        try:
            read_bytes = 0
            while True:
                b = fobject.readinto(buffer)
                if not b:
                    break
                read_bytes = read_bytes + b
                p.stdin.write(memoryview(buffer)[:b])
                progress.report_transfer(read_bytes, file_size)
        except Exception, e:
            p.kill()
            raise BackendException(
                "Qubes VM put of %s (as %s) failed: (%s) %s" % (
                    source_path.name, remote_filename, type(e), e))
        finally:
            p.stdin.close()
            fobject.close()
        progress.report_transfer(file_size, file_size)
        err = p.wait()
        if err != 0:
            raise BackendException(
                ("Qubes VM put of %s (as %s) failed: writing the "
                 "destination path exited with nonzero status %s") % (
                     source_path.name, remote_filename, err))

    def _get(self, remote_filename, local_path):
        """Retrieves a single file from the remote side."""
        self._validate_remote_filename("get", remote_filename)
        rempath = os.path.join(self.remote_dir, remote_filename)
        cmd = self._dd(iff=rempath)
        fobject = open(local_path.name, "wb")
        try:
            p = self._execute_qvmrun(cmd,
                                     stdin=open(os.devnull),
                                     stdout=fobject,
                                     bufsize=0)
        except Exception, e:
            raise BackendException(
                "Qubes VM get of %s (as %s) failed: (%s) %s" % (
                    remote_filename.name, local_path, type(e), e))
        finally:
            fobject.close()
        err = p.wait()
        if err != 0:
            raise BackendException(
                ("Qubes VM get of %s (as %s) failed: writing the "
                 "destination path exited with nonzero status %s") % (
                     remote_filename.name, local_path, err))

    def _list(self):
        """Lists the contents of the one duplicity dir on the remote side."""
        cmd = ["find", self.remote_dir, "-maxdepth", "1", "-print0"]
        try:
            p = self._execute_qvmrun(cmd,
                                     stdin=open(os.devnull, "rb"),
                                     stdout=subprocess.PIPE)
        except Exception, e:
            raise BackendException(
                "Qubes VM list of %s failed: %s" % (self.remote_dir, e))
        data = p.stdout.read(MAX_LIST_SIZE)
        p.stdout.close()
        err = p.wait()
        if err != 0:
            raise BackendException(
                ("Qubes VM list of %s failed: list command finished "
                "with nonzero status %s" % (self.remote_dir, err)))
        if not data:
            raise BackendException(
                ("Qubes VM list of %s failed: list command returned "
                "empty" % (self.remote_dir,)))
        filename_list = data.split("\0")
        if filename_list[0] != self.remote_dir:
            raise BackendException(
                ("Qubes VM list of %s failed: list command returned a "
                "filename_list for a path different from the remote folder") % (
                    self.remote_dir,))
        filename_list.pop(0)
        if filename_list[-1]:
            raise BackendException(
                ("Qubes VM list of %s failed: list command returned "
                "wrongly-terminated data or listing was too long") % (
                    self.remote_dir,))
        filename_list.pop()
        filename_list = [ p[len(self.remote_dir) + 1:] for p in filename_list ]
        if any(os.path.sep in p for p in filename_list):
            raise BackendException(
                ("Qubes VM list of %s failed: list command returned "
                "a path separator in the listing") % (
                    self.remote_dir,))
        return filename_list

    def _delete_list(self, filename_list):
        """Deletes all files in the list on the remote side."""
        if any(os.path.sep in p or "\0" in p for p in filename_list):
            raise BackendException(
                ("Qubes VM delete of files in %s failed: delete "
                 "command asked to delete a file with a path separator "
                 "or a null character in the listing") % (
                     self.remote_dir,))
        pathlist = [os.path.join(self.remote_dir, p) for p in filename_list]
        cmd = "set -e\n" + "\n".join("rm -f -- " + pipes.quote(p) for p in pathlist)
        try:
            p = self._execute_qvmrun(['bash'],
                                     stdin=subprocess.PIPE,
                                     stdout=open(os.devnull, "wb"))
            p.stdin.write(cmd)
            p.stdin.close()
        except Exception, e:
            raise BackendException(
                "Qubes VM delete of files in %s (%s) failed: %s" % (
                    self.remote_dir, cmd, e))
        err = p.wait()
        if err != 0:
            raise BackendException(
                ("Qubes VM delete of files in %s failed: delete "
                 "command finished with nonzero status %s") % (
                     self.remote_dir, err))

duplicity.backend.register_backend("qubesvm", QubesVMBackend)
duplicity.backend.uses_netloc.extend(['qubesvm'])
```

Enjoy!

**Comment by Rudd-O** [comment] 2016-08-12 13:44
Excellent news!  I have decided to track the development of that Duplicity component in its own repository:

https://github.com/Rudd-O/duplicity-qubes

Enjoy!

**Comment by cyrinux** [comment] 2016-09-04 13:39
Same problem here. With one big qube and other lighter

**Comment by jmitchell** [comment] 2016-09-29 21:33
I did a fresh install of the newly released v3.2 and bumped into this without creating new VMs nor modifying any of the default VMs. Backing up a couple VMs at a time works, but when I tried shutting down and backing up all VMs in the same batch it failed with the same "addproc" error. Failure correlates with the size of the backup.

Are there any recommended diagnostics I should try? Running a large backup takes a while, so I'm not eager to fumble in the dark too much.

**Comment by maxbane** [comment] 2016-10-09 16:16
I believe I'm encountering the same issue. Running 3.1, with dom0 fully updated as of 2016-10-09. In preparation for upgrading to 3.2, I've been attempting to backup my AppVMs, but most attempts encounter the "error in addproc" error and abort early. This happens even on quite small backups, e.g., if I select a few small VMs totalling 500MB. It's not fully deterministic, though, as I can sometimes successfully make very small backups, e.g., 120MB.

Obviously this is a bit of an impediment to upgrading to 3.2... I suppose I can manually backup the files I care about within each AppVM.

**Comment by marmarek** [comment] 2016-10-09 22:26
Try running backup from command line (`qvm-backup`), with --debug
option.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by DavidVorick** [comment] 2016-10-27 09:22
Getting the same issue.

"-> Backing up files: 55%...tar: david/backups/qubes-2016-10-27-T004735: file changed as we read it
-> Backing up files: 55%...Wait_backup_feedback returned: addproc
 ERROR: Failed to perform backup: error in addproc"

**Comment by DavidVorick** [comment] 2016-10-27 11:23
A repeat job saving to /backups in dom0 yielded the same failure.

**Comment by marmarek** [comment] 2016-10-27 15:47
Ah, your destination directory is dom0 user home, right? When you make
full backup, it by default include that directory, so the backup archive
itself... Select other destination.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment] 2016-10-27 18:53
> A repeat job saving to /backups in dom0 yielded the same failure.

And what error did you get then?

**Comment by DavidVorick** [comment] 2016-10-28 00:39
Sorry, I just mis-typed the command. When I backed up to somewhere other than the dom0 user home, I did not run into problems. My mistake.

I think the right way to handle this issue is to serve a warning if the user selects a destination in the dom0 home. Maybe check that the destination isn't conflicting in any other ways as well, but I'm guessing this would cover 95% of the cases where people run into this error.

**Comment by jpouellet** [comment] 2017-09-10 03:25
I'm 100% sure I triggered this without including the backup dest in backups. The real problem does not seem related to backup target.

This is pretty annoying to try to trace down since I need to wait through like an hour of backups to trigger it. :(

**Comment by jpouellet** [comment] 2017-09-10 04:18
Appears that anything which causes tar to exit with non-zero status will cause this. In my case the root cause was existence of files with chmod 000 rights in my dom0 home dir while trying to back up dom0, causing tar to fail.

Such situations should never be possible in normal use of Qubes: "thou shalt not muck about with dom0" - especially once we have adminvm/guivm separation. I think we should close this as WONTFIX, and instead open bugs against anything in the future which is found to create unreadable files in the locations which Qubes tries to back up (not aware of any - my case and the others in this thread appear to all be user error).

**Comment by jpouellet** [comment] 2017-09-10 04:24
In case anyone cares... (from an R3.2 machine)

Before (with unreadable files in dom0 ~):
```
[user@dom0 ~]$ qvm-backup --debug -d sys-usb-trusted /run/media/user/ext/backups/dom0 dom0
------------------+--------------+--------------+
               VM |         type |         size |
------------------+--------------+--------------+
             Dom0 |    User home |     71.9 MiB |
------------------+--------------+--------------+
      Total size: |                    72.0 MiB |
------------------+--------------+--------------+
VMs not selected for backup:
[...]

NOTE: VM sys-usb-trusted will be excluded because it is the backup destination.
Do you want to proceed? [y/N] y
Please enter the passphrase that will be used to encrypt and verify the backup: 
Enter again for verification: 
-> Backing up files: 0%...Working in /tmp/backup_CK8ZS3
Creating pipe in: /tmp/backup_CK8ZS3/backup_pipe
Will backup: [{u'path': '/var/lib/qubes/qubes.xml', u'subdir': u'', u'size': 90112}, {u'path': '/home/user', u'subdir': u'dom0-home/', u'size': 75427840}]
Backing up {u'path': '/var/lib/qubes/qubes.xml', u'subdir': u'', u'size': 90112}
Using temporary location: /tmp/backup_CK8ZS3/qubes.xml
tar -Pc --sparse -f /tmp/backup_CK8ZS3/backup_pipe -C /var/lib/qubes --dereference --xform s:^qubes.xml:\0: qubes.xml
Started sending thread
Moving to temporary dir /tmp/backup_CK8ZS3
Sending file backup-header
Removing file backup-header
Sending file backup-header.hmac
Removing file backup-header.hmac
-> Backing up files: 0%...Wait_backup_feedback returned: 
Sending file qubes.xml.000
HMAC proc return code: 0
Writing hmac to /tmp/backup_CK8ZS3/qubes.xml.000.hmac
Finished tar sparse with exit code 0
Backing up {u'path': '/home/user', u'subdir': u'dom0-home/', u'size': 75427840}
Using temporary location: /tmp/backup_CK8ZS3/dom0-home/user
tar -Pc --sparse -f /tmp/backup_CK8ZS3/backup_pipe -C /home --xform s:^user:dom0-home/\0: user
Removing file qubes.xml.000
Sending file qubes.xml.000.hmac
Removing file qubes.xml.000.hmac
-> Backing up files: 75%...tar: user/etc/shadow: Cannot open: Permission denied
-> Backing up files: 86%...tar: user/etc/gshadow: Cannot open: Permission denied
-> Backing up files: 87%...tar: user/etc/gshadow-: Cannot open: Permission denied
-> Backing up files: 87%...tar: user/etc/shadow-: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
-> Backing up files: 88%...Wait_backup_feedback returned: addproc
 ERROR: Failed to perform backup: error in addproc
```

After (without unreadable files):
```
[user@dom0 ~]$ qvm-backup --debug -d sys-usb-trusted /run/media/user/ext/backups/dom0 dom0
------------------+--------------+--------------+
               VM |         type |         size |
------------------+--------------+--------------+
             Dom0 |    User home |     71.9 MiB |
------------------+--------------+--------------+
      Total size: |                    72.0 MiB |
------------------+--------------+--------------+
VMs not selected for backup:
[...]

NOTE: VM sys-usb-trusted will be excluded because it is the backup destination.
Do you want to proceed? [y/N] y
Please enter the passphrase that will be used to encrypt and verify the backup: 
Enter again for verification: 
-> Backing up files: 0%...Working in /tmp/backup_weSJEn
Creating pipe in: /tmp/backup_weSJEn/backup_pipe
Will backup: [{u'path': '/var/lib/qubes/qubes.xml', u'subdir': u'', u'size': 90112}, {u'path': '/home/user', u'subdir': u'dom0-home/', u'size': 75427840}]
Backing up {u'path': '/var/lib/qubes/qubes.xml', u'subdir': u'', u'size': 90112}
Using temporary location: /tmp/backup_weSJEn/qubes.xml
tar -Pc --sparse -f /tmp/backup_weSJEn/backup_pipe -C /var/lib/qubes --dereference --xform s:^qubes.xml:\0: qubes.xml
Started sending thread
Moving to temporary dir /tmp/backup_weSJEn
Sending file backup-header
Removing file backup-header
Sending file backup-header.hmac
Removing file backup-header.hmac
-> Backing up files: 0%...Wait_backup_feedback returned: 
Sending file qubes.xml.000
HMAC proc return code: 0
Writing hmac to /tmp/backup_weSJEn/qubes.xml.000.hmac
Finished tar sparse with exit code 0
Backing up {u'path': '/home/user', u'subdir': u'dom0-home/', u'size': 75427840}
Using temporary location: /tmp/backup_weSJEn/dom0-home/user
tar -Pc --sparse -f /tmp/backup_weSJEn/backup_pipe -C /home --xform s:^user:dom0-home/\0: user
Removing file qubes.xml.000
Sending file qubes.xml.000.hmac
Removing file qubes.xml.000.hmac
-> Backing up files: 88%...Wait_backup_feedback returned: 
Sending file dom0-home/user.000
HMAC proc return code: 0
Writing hmac to /tmp/backup_weSJEn/dom0-home/user.000.hmac
Finished tar sparse with exit code 0
Removing file dom0-home/user.000
Sending file dom0-home/user.000.hmac
Removing file dom0-home/user.000.hmac
Finished sending thread
VMProc1 proc return code: None
Sparse1 proc return code: 0

-> Backup completed.
```

**Comment by jpouellet** [comment] 2017-09-10 04:28
And for those who follow who've somehow ended up with a file causing this issue and don't want to wait through backups in debug mode to figure out which and where, try:
```
[user@dom0 ~]$ find /home/* /var/lib/qubes '!' -readable '!' -type l
```

**Comment by qubenix** [comment] 2018-03-29 02:32
I'm sorry this has lingered open. I think it should be safe to close now as I haven't had backup errors in nearly a year.

**Comment by andrewdavidwong** [comment] 2018-06-13 02:33
[On 2018-06-12 03:12, [...] wrote:](https://groups.google.com/d/msgid/qubes-users/1264feaa-2134-84a9-0876-12458992adba%40riseup.net)
> Hi,
> 
> when trying to perform a backup of my VMs I get this error after about 75%
> 
> "ERROR: Failed to perform backup: error in addproc" 
> 
> This is reproducible everytime. Which means I can no longer backup my VMs.
> 
> I'm using R3.2.
> 
> I found this error on the bugtracker but it was on R3.1 and is marked as closed:
> 
> https://github.com/QubesOS/qubes-issues/issues/1588
> 
> 
> Anyone else observing this and know of a workaround?
> 
> thanks!
> 

Reopening.

**Comment by andrewdavidwong** [comment] 2018-06-14 02:51
[On 2018-06-13 02:45, [...] wrote:](https://groups.google.com/d/msgid/qubes-users/da5e0768-c6c2-962b-13f7-070451e6c6e3%40riseup.net)
> thanks!
> 
> I got it to work - backup done without failure.
> 
> Here is what I did:
> 
> 'qvm-ls' was showing warnings about corrupt files for specific VMs.
> 
> Since these where old VMs that I deleted already in qubes manager I deleted them again with
> 
> qvm-remove --just-db <name>
> 
> Then I performed a backup. I'm not entirely sure if that was the problem since I deleted some more
> VMs but it sound reasonable. 
> 
> If this was indeed the root-cause:
> Maybe qvm-backup could check if there are any warnings in qvm-ls output before proceeding?
> 

CC: @marmarek

**Comment by andrewdavidwong** [comment] 2020-09-02 16:36
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Closed by andrewdavidwong** 2020-09-02 16:36 UTC
Labels: C: core, P: major, T: bug
