### ISSUE TITLE
NetworkManager applet sometimes fails to start automatically on firstboot

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#2537] opened 2016-12-25 06:02 UTC
#### Qubes OS version (e.g., `R3.2`):

R3.2

### Expected behavior:

First thing one wants after installing Qubes OS is internet access (if only to read some more docs).

Usually there is either a icon in some toolbar with a already running network-manager applet (or similar tool) or some menu entry to start some wifi configuration tool.

### Actual behavior:

With Qubes OS, there is no obvious / intuitive way:

- no running / no visible nm applet
- the xfce running in dom0 offers a network connection setup tool in the menu, but when trying to use it to add a wifi connection everything is greyed out there, leading the fresh qubes user in the wrong direction of thinking this is a permissions issue (like having to get root / admin first) - but I guess rather that tool should not be there at all as network stuff works via sys-net VM.
- the sys-net VM menu entries also have no tool to configure a new connection, but one can add the menu entry for it manually (that's what I did in the end and could add / configure my WiFi).

### Steps to reproduce the behavior:

Fresh Qubes OS 3.2 install on a Thinkpad X230.

**Comment by andrewdavidwong** [comment] 2016-12-25 09:38
The NetworkManager applet *should* start and run in the system tray by default. It sounds like you might have a hardware compatibility issue with your Wi-Fi adapter (missing drivers?).

-----

This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by ThomasWaldmann** [comment] 2016-12-25 16:11
Well, "should", but it did not.

I don't think I have a hardware compat issue, the X230 is known-good (see qubes hw compat list) and the intel iwl6205 "n" is also not known as problematic (and works flawlessly after I did what I described above). It also "just works" with a lot of other current linuxes.

Also, this is not a "question", I was just reporting what happened.

You didn't address the issue of the useless / misleading xfce connection setup tool menu entry.

So, please reopen, this issue is not solved.

**Comment by andrewdavidwong** [comment] 2016-12-25 17:50
> Well, "should", but it did not.

I mean it normally does. So, if it does not for you, then this is a special case, not a common bug. Usually that means a hardware compatibility issue, which we refer to qubes-users.

> I don't think I have a hardware compat issue, the X230 is known-good (see qubes hw compat list) and the intel iwl6205 "n" is also not known as problematic (and works flawlessly after I did what I described above). It also "just works" with a lot of other current linuxes.

Indeed, it's surprising that this would happen on an X230.

> Also, this is not a "question", I was just reporting what happened.

I know, but that's a saved reply. When you deal with the volume of issues of this kind that we get, it's more efficient to use saved replies.

> You didn't address the issue of the useless / misleading xfce connection setup tool menu entry.

Dom0 has no network access by design, so that tool shouldn't be used at all. (There are many tools in dom0 that shouldn't be used; this is just one of them.)

> So, please reopen, this issue is not solved.

Very well.

**Comment by andrewdavidwong** [comment] 2016-12-25 18:00
So, what happens if you try to start NetworkManager manually in sys-net?

**Comment by andrewdavidwong** [comment] 2016-12-25 18:06
> the sys-net VM menu entries also have no tool to configure a new connection, but one can add the menu entry for it manually (that's what I did in the end and could add / configure my WiFi).

Ah, so you got it working. The problem is just that the nm-applet didn't appear automatically on first boot, right? In that case, this is a duplicate of #2293. (If it's not, let me know.)

**Closed by andrewdavidwong** 2016-12-25 18:06 UTC
Labels: C: other, UX
