### ISSUE TITLE
Changing settings in qubes-manager GUI - ERROR: TypeError('items(self, QMimeData): not enough arguments',)

### ISSUE THREAD

**Issue by bugluv** [QubesOS/qubes-issues#4959] opened 2019-04-07 10:45 UTC
When changing settings in qube-manager GUI the following error occurs:

ERROR: TypeError('items(self, QMimeData): not enough arguments',)

-   Adding applications to an AppVM with the qubes-manager GUI works despite the error (after      closing error popup and pressing 'apply and 'ok' on the qubes-manager GUI).

-   Attaching pci devices with the qubes-manager GUI fails to attach pci device (but works from commandline).

Same error on different hardware.

**Comment by marmarek** [comment] 2019-04-07 23:19
Please use qubes-issues repository for bug reports, not updates-status.

**Comment by marmarek** [comment] 2019-04-07 23:19
Duplicate of #4951

**Closed by marmarek** 2019-04-07 23:19 UTC
