### ISSUE TITLE
xflock4 doesn't automatically lock screen if dom0 has applications widget open

### ISSUE THREAD

**Issue by bzillacodes** [QubesOS/qubes-issues#8391] opened 2023-08-04 13:22 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.2

### Brief summary
When opening the Applications menu in dom0, and leaving it open, regardless of no keyboard/mouse movement, for a state of 30+ minutes, xlock4 doesn't lock the screen after the default 10 minute inactivity timer.

Continues to lock screen fine if the Applications menu widget is not left open. Haven't encountered any other xfce widgets causing this, but at the same time I haven't tested the state of leaving any other widgets open. But just a heads up to help avoid certain scenarios where device could be left open to maid attacks.

### Steps to reproduce
Leave dom0 with the Applications menu open (by accident in my case). The automatic xflock4 inactivity timer doesn't kick in after the default set 10 minutes.

### Expected behavior
If there is no mouse/keyboard movement, xflock4 should initiate the automatic screen lock, regardless of which applications/widgets are taking priority and keeping the screen awake.

### Actual behavior
As observed, the applications menu in dom0 caused xflock4 to not automatically lock after the 10 minutes of keyboard/mouse inactivity.

Sent from Github Mobile.

**Comment by DemiMarie** [comment] 2023-08-04 16:02
I believe the only possible fix is to switch to Wayland in the GUI qube, which means using KDE instead of XFCE or finding a way to make rootful XWayland work with XFCE.

**Comment by andrewdavidwong** [comment] 2023-08-05 08:21
Duplicate of #3898

**Comment by andrewdavidwong** [comment] 2023-08-05 08:21
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-08-05 08:21 UTC
Labels: T: bug, P: default
