### ISSUE TITLE
qubes-builder fails looking for pungi rpm

### ISSUE THREAD

**Issue by barryfx** [QubesOS/qubes-issues#5682] opened 2020-02-22 18:17 UTC
### Qubes OS version:
Release R4.0

### Affected component(s) or functionality:

qubes-builder

---

### Steps to reproduce the behavior:
build the qubes-builder following the instructions found here  https://www.qubes-os.org/doc/qubes-builder/ .  Received the following error doing 'make get-sources':

--> Downloading additional sources for linux-scrypt...
--> Verifying the sources...
--> Downloading additional sources for installer-qubes-os...
--> Verifying the sources...
--> Downloading additional sources for pykickstart...
--> Verifying the sources...
--> Downloading additional sources for blivet...
--> Verifying the sources...
--> Downloading additional sources for lorax...
--> Verifying the sources...
--> Downloading additional sources for pungi...
Cannot find source RPM: pungi-4.1.41-3.fc31.src.rpm
make[1]: *** [Makefile:21: pungi-4.1.41.tar.bz2.UNTRUSTED] Error 1
make: *** [Makefile:205: pungi.get-sources-extra] Error 2

### Expected or desired behavior:
make should succeed

### Actual behavior:
make failed looking for pungi-4.1.41-3.fc31.src.rpm

### General notes:
Building on an attached SATA hard drive in a Fedora 29 HVM.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/qubes-builder/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
none

**Comment by unman** [comment] 2020-02-23 00:23
I'm afraid you are using an unsupported version of Fedora - [29 is eol ](https://www.mail-archive.com/qubes-users@googlegroups.com/msg31252.html)
Yes, I *know* the docs say to use 29, but they are out of date and I will fix that now. Try it with a Fedora 30 template for your build machine.

**Comment by fepitre** [comment] 2020-02-23 08:58
Have a look to the branch in this PR https://github.com/QubesOS/qubes-pungi/pull/4 for using Qubes mirror for source.

**Comment by andrewdavidwong** [comment] 2020-02-23 10:41
Is this resolved by using Fedora 30 as @unman suggested?

**Comment by fepitre** [comment] 2020-02-23 10:50
> Is this resolved by using Fedora 30 as @unman suggested?

No I think it's unrelated. I think @unman is talking about building Qubes under Fedora 29 but this is still possible (I'm still doing it). Once again, I'm strongly guessing It's related to the current problem of keeping sync with Fedora updates provided RPMs. We are switching to distfiles mirror/upstream project mirror for that now (this is why I notified about the PR).

**Comment by unman** [comment] 2020-02-23 14:44
>   >Is this resolved by using Fedora 30 as @unman suggested?

> No I think it's unrelated. 

To be clear, I didn't *suggest* the issue would be resolved by switching to Fedora30, I *asked* if it was.

**Comment by barryfx** [comment] 2020-02-23 18:54
The change provided by fepitre worked.  Thank you.  Once the final resolution is in place this issue can be closed.

**Comment by unman** [comment] 2020-02-24 11:34
> > > Is this resolved by using Fedora 30 as @unman suggested?

> >  No I think it's unrelated.

> To be clear, I didn't *suggest* the issue would be resolved by switching to Fedora30, I *asked* if it was.

And it isn't. @fepitre solution is required

**Comment by barryfx** [comment] 2020-02-24 12:52
I used a fedora 30 vm and it failed with the same error.  I then tried the
new pungi Makefile and it worked.

**Comment by andrewdavidwong** [comment] 2020-02-24 14:08
> > > Is this resolved by using Fedora 30 as @unman suggested?
> 
> > No I think it's unrelated.
> 
> To be clear, I didn't _suggest_ the issue would be resolved by switching to Fedora30, I _asked_ if it was.

Well, I didn't say that you suggested that the issue would be resolved by switching to Fedora 30. I only said that you suggested trying Fedora 30. _I_ was the one asking whether the issue would be resolved by following your suggestion to try Fedora 30.

FWIW, I don't see where you asked anything.

**Comment by arno01** [comment] 2020-02-27 12:56
> Currently we are on thinking how to properly update and provide components sources.

How about to use the upstream link, e.g. https://pagure.io/releases/pungi/pungi-4.1.41.tar.bz2 and then use http://ftp.qubes-os.org/distfiles/ if the upstream fails?

```
[user@build pungi]$ grep -i Source0 pungi.spec.in 
Source0:        https://pagure.io/releases/%{name}/%{name}-%{version}.tar.bz2
```

**Comment by marmarek** [comment] 2020-02-27 13:21
The issue is that upstream tarball miss some files (at least translations) and require downloading them build-time. For (I hope) obvious reasons, we don't want the build process to download extra files on its own. The simplest solution is to extract tarball from Fedora's src.rpm, which has those extra sources already included.

**Comment by arno01** [comment] 2020-02-27 16:53
> The issue is that upstream tarball miss some files (at least translations) and require downloading them build-time.

Hum, am I missing something or...
That would mean that the upstream tarball would render in a different hash, which isn't the case:

```
[user@build pungi]$ wget -c https://pagure.io/releases/pungi/pungi-4.1.41.tar.bz2
[user@build pungi]$ sha512sum pungi-4.1.41.tar.bz2
d2f1263c209f3f2a1e95571fdd6a1327852e480339d64a03b3b985bd235ebac05b63538ce3d8518a7174a25a8b2210007d0490aa1d07d092fe5d49cb40c9fd83  pungi-4.1.41.tar.bz2
[user@build pungi]$ cat pungi-4.1.41.tar.bz2.sha512
d2f1263c209f3f2a1e95571fdd6a1327852e480339d64a03b3b985bd235ebac05b63538ce3d8518a7174a25a8b2210007d0490aa1d07d092fe5d49cb40c9fd83
```

**Comment by marmarek** [comment] 2020-02-27 17:07
Oh, pungi fixed their tarballs in the meantime, thanks for checking. Yes, in that case, definitely downloading directly from the upstream makes more sense.

**Comment by fepitre** [comment] 2020-02-27 17:35
I updated pungi distfiles mirror.

**Closed** 2020-02-29 15:48 UTC
Labels: C: builder, P: default, T: bug
