### ISSUE TITLE
No qubes kde settings package anymore

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2662] opened 2017-03-03 11:45 UTC
My window borders are no longer colored within KDE in a new Q3.2 install.

**Comment by marmarek** [comment] 2017-03-03 19:18
Duplicate of #2663 (it works when you install `plasma-breeze-qubes`, which is included in that instruction).

**Closed by marmarek** 2017-03-03 19:18 UTC

**Comment by andrewdavidwong** [comment] 2017-03-03 23:28
@marmarek: I can't find (literal `ctrl`+`F`) any mention of `plasma-breeze-qubes` in #2663 or https://www.qubes-os.org/doc/kde/.

**Comment by marmarek** [comment] 2017-03-03 23:53
> @marmarek: I can't find (literal ctrl+F) any mention of plasma-breeze-qubes in #2663 or https://www.qubes-os.org/doc/kde/.

It's part of "kde-desktop-qubes" group.

**Comment by Rudd-O** [comment] 2017-03-04 23:26
Kay.  I will add that to my recipe.  It's a bummer tho.  It used to be a different package back then in the R2 world.  Sorry.

On March 4, 2017 12:53:10 AM GMT+01:00, "Marek Marczykowski-Górecki" <notifications@github.com> wrote:
>> @marmarek: I can't find (literal ctrl+F) any mention of
>plasma-breeze-qubes in #2663 or https://www.qubes-os.org/doc/kde/.
>
>It's part of "kde-desktop-qubes" group.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/2662#issuecomment-284103023

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marmarek** [comment] 2017-03-05 00:43
On Sat, Mar 04, 2017 at 03:26:12PM -0800, Rudd-O wrote:
> Kay.  I will add that to my recipe.  It's a bummer tho.  It used to be a different package back then in the R2 world.  Sorry.

Better use group name instead of explicit packages - it will be
future-proof.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Rudd-O** [comment] 2017-03-05 18:50
On March 5, 2017 1:44:00 AM GMT+01:00, "Marek Marczykowski-Górecki" <notifications@github.com> wrote:
>On Sat, Mar 04, 2017 at 03:26:12PM -0800, Rudd-O wrote:
>> Kay.  I will add that to my recipe.  It's a bummer tho.  It used to
>be a different package back then in the R2 world.  Sorry.
>
>Better use group name instead of explicit packages - it will be
>future-proof.

You are quite correct, and yet, group name doesn't work in Ansible.  Tragic.

When's the next meetup?  I want to get one of the new T-shirts that don't have the typo :-D

(I got the V1 shirt!  So awesome!  CCC was wonderful!)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rudd-O** [comment] 2017-03-06 13:21
The borders are still not colored even after installin plasma breeze qubes.  Donno what's up.

**Comment by Rudd-O** [comment] 2017-03-06 13:22
The borders are still not colored even after installin plasma breeze qubes.  Donno what's up.     I had to manually run qubes-generate-color-palette.

**Comment by marmarek** [comment] 2017-03-06 13:31
It should be started automatically from `/etc/xdg/autostart/qubes-generate-color-palette.desktop` (at user login). Do you have this file? Maybe there is something wrong with it?

**Comment by Rudd-O** [comment] 2017-03-06 13:31
I never logged in again.  Just reran kwin.  Fixed by running it by hand.
