### ISSUE TITLE
Windows 10 support in QWT

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3643] opened 2018-02-28 22:06 UTC
#### Qubes OS version:

R4.0

#### Affected component(s): 

QWT

---

### General notes:

This is a feature request, but Windows 7 may become unsupported in the near future, in which case this will become mandatory for anyone who wishes to run a version of Windows in an AppVM and not immediately get hacked.

---

**Comment by andrewdavidwong** [comment] 2018-03-01 04:44
Duplicate of #1861

**Comment by andrewdavidwong** [comment] 2018-03-01 04:44
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-01 04:44 UTC
