### ISSUE TITLE
Clock does not synchronize

### ISSUE THREAD

**Issue by sergeyfrolov** [QubesOS/qubes-issues#4989] opened 2019-04-20 22:36 UTC
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
sys-net clock sync

**Brief summary**
Clock does not synchronize.
`systemd-timesyncd.service` requires `/var/run/qubes-service/clocksync` to be present in `sys-net`, but it is absent, therefore service will not start.

I don't think I had done anything specific or time-related to trigger this bug.

**Expected behavior**
Clock syncs

**Actual behavior**
Clock doesn't sync. Clock is incorrect both in dom0 and sys-net

**Solutions you've tried**
After creating `/var/run/qubes-service/clocksync`, restarting the services in sys-net, and running `qvm-sync-clock` in dom0, I got it working.

**Comment by unman** [comment] 2019-04-21 00:32
On Sat, Apr 20, 2019 at 03:36:10PM -0700, sergeyfrolov wrote:
> **Qubes OS version**
> Qubes release 4.0 (R4.0)
> 
> **Affected component(s) or functionality**
> sys-net clock sync
> 
> **Brief summary**
> Clock does not synchronize.
> `systemd-timesyncd.service` requires `/var/run/qubes-service/clocksync` to be present in `sys-net`, but it is absent, therefore service will not start.
> 
> I don't think I had done anything specific or time-related to trigger this bug.
> 
> **Expected behavior**
> Clock syncs
> 
> **Actual behavior**
> Clock doesn't sync. Clock is incorrect both in dom0 and sys-net
> 
> **Solutions you've tried**
> After creating `/var/run/qubes-service/clocksync`, restarting the services in sys-net, and running `qvm-sync-clock` in dom0, I got it working.
> 

What template are you using for sys-net?

**Comment by sergeyfrolov** [comment] 2019-04-21 00:59
> What template are you using for sys-net?
fedora 29

**Comment by andrewdavidwong** [comment] 2019-04-21 01:42
Possible duplicate of #4939.

**Comment by marmarek** [comment] 2019-11-30 04:21
Duplicate of #4939

**Closed by marmarek** 2019-11-30 04:21 UTC
Labels: C: other, P: default, T: bug
