### ISSUE TITLE
QubesNoSuchPropertyError by qvm-ls

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3350] opened 2017-11-29 18:48 UTC
#### Qubes OS version:
4.0rc2

#### Affected TemplateVMs: 
debian-8

### Steps to reproduce the behavior:

1. `qvm-ls` in dom0

1. `sudo journalctl -b0` in dom0

### Expected behavior:

`qvm-ls` calls don't clutter the log.

### Actual behavior:

Lots of entries such as
`Nov 29 19:27:52 dom0 qubesd[1865]: QubesNoSuchPropertyError("Invalid property 'netvm' of dom0",) while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'dom0' arg=b'netvm' len(untrusted_payload)=0
Nov 29 19:27:52 dom0 qubesd[1865]: QubesNoSuchPropertyError("Invalid property 'ip' of dom0",) while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'dom0' arg=b'ip' len(untrusted_payload)=0`

or

`Nov 29 19:27:52 dom0 qubesd[1865]: QubesNoSuchPropertyError("Invalid property 'template' of StandaloneVM",) while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'StandaloneVM' arg=b'template' len(untrusted_payload)=0`

Apparently some unchecked calls for non-existing VM properties lead to log entries.

### General notes:
If it's not qvm-ls, please let me know. I just noticed that the rate of logs increased when I called qvm-ls. This noise consumes ~70% of my current log.

**Comment by marmarek** [comment] 2017-12-22 21:53
Duplicate of #3238 (already fixed)

**Closed by marmarek** 2017-12-22 21:53 UTC
Labels: bug, C: core
