### ISSUE TITLE
Slow X start as it waits for autostart VMs

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3149] opened 2017-10-06 09:10 UTC
#### Qubes OS version (e.g., `R3.2`):
3.2, 4.0rc1

#### Description
Somewhat since 2.x the boot process is significantly slowed down as all VMs flagged to autostart (at least sys-net & sys-firewall) are required to start before the X server is started.

This is inconvenient for the following reasons:

- Users may want to use a VM first which doesn't require networking.
- If an error occurs during the startup of one of the autostart VMs, the user waited in vain.
- Startup of further VMs the user might want to start during his current session is delayed further.

**Comment by marmarek** [comment] 2017-10-06 10:19
In 3.2 this is required to avoid various races between GUI startup, X
start and VM startup. In 4.0 theoretically it shouldn't be needed. But
it still may be useful feature: when you log in, your system is fully
operational.

If you don't want to wait, disable autostart of those VMs. They will be
started when required (application launch) anyway.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 3hhh** [comment] 2017-10-06 22:46
> In 3.2 this is required to avoid various races between GUI startup, X
start and VM startup. In 4.0 theoretically it shouldn't be needed. But
it still may be useful feature: when you log in, your system is fully
operational.

That's the only plus and it doesn't even hold if some error occurred (in 3.2 50% of the time my sys-net was not started, in 4.0rc1 in 20% of boots sys-firewall or sys-net fails to start).

I'd even say the login time (the 5s the user needs to type his password to pass the dm login) could e.g. be used to startup VMs.

> If you don't want to wait, disable autostart of those VMs. They will be
started when required (application launch) anyway.

Yes, I know I can do it all for myself.

However from a bigger perspective I think that the default settings of an OS should have performance in mind as long as security is not compromised. Every user notices the time it takes for his OS to boot until X is started (whatever happens afterwards tends to be noticed less). If you can reduce this by 40-50%, that's something many people will see as an improvement.

**Comment by 3hhh** [comment] 2017-10-12 06:49
Ok, so I did some tests to get more concrete numbers:

#### Methodology

- test system: Lenovo T530, i5 3rd Gen, 16 GB RAM, SSD, Qubes 4.0rc1
- 4 VMs in autostart: sys-usb, sys-net, sys-firewall, sys-vpn (proxy to sys-firewall)
- "X time" := time measured right after the luks password was typed in and until the X server showed up (in my case until awesome was started)
- "VM time" := time the aforementioned VMs required to start when the Qubes autostart feature was not used (I started a script from my awesome rc.lua which took the time & started the VMs instead)
- WM logon was set to autologin, i.e. no time was used to type in any password
- each test scenario was measured two times
- "chain loading" := sys-net, sys-firewall and sys-vpn were started one after another, sys-usb in parallel
- "parallel loading" := sys-net, sys-firewall, sys-vpn and sys-usb were all started in parallel

#### Measurements
##### Qubes Default Boot

X time: 43s, 44s

##### Manual autostart, chain loading

X time: 7s, 7s
VM time: 47s, 48s

##### Manual autostart, parallel loading

X time: 7s, 7s
VM time: 47s, 47s

#### Conclusions

- The Qubes default boot seems to be faster by ~10s for the test system if measured in total. Some small parts of this may be caused by my bad implementation (awesome & the VMs could be started in parallel, 4 times using `qvm-start --skip-if-running` seems to take ~2s if the VMs are running/nothing has to be done).
- Seeing X in 7s rather than 44s can be an improvement for some users (being able to start further VMs & use dom0).
- Having a fully functional system in 44s might be preferred by other users.
- Errors during VM startup will further increase the Qubes Default boot time (I think the default timeout is at 90s per VM or so, i.e. booting will then take 90s+).
- Boot time for both scenarios could be improved by starting the VMs during the WM password prompt (was disabled during the tests).
- Chain loading has no advantage over parallel loading even though it seems more clever at first sight to keep the dependencies in mind.

Unfortunately this still leaves the topic controversial, but should help make both positions more easy to understand.

**Comment by 3hhh** [comment] 2017-10-20 08:33
Side note: VMs were running in hvm mode except for sys-usb. With pv mode everything is significantly faster.

**Comment by 3hhh** [comment] 2018-02-26 17:50
I recently stumbled across an article in one of the biggest German IT magazines [1] in the context of an ORWL test [2] and it said:

`Qubes OS boots very slowly; it takes 45s until you see the login screen.`
(translated from German)

Pretty much my point. ;-)

[1] c't 20/2017, p. 64
[2] https://orwl.org/

**Comment by marmarek** [comment] 2018-02-26 20:02
There is one thing you can try: start VMs in parallel with X and password prompt. Create `/etc/systemd/system/qubes-vm@.service.d/order.conf` with:
```
[Unit]
Before=
```

In 3.2 this would break VM's GUI, but in 4.0 it should be safe(r).
This should give at least an impression of faster system startup.

**Comment by rustybird** [comment] 2018-02-26 23:04
> There is one thing you can try: start VMs in parallel with X and password prompt. Create `/etc/systemd/system/qubes-vm@.service.d/order.conf` with:
> 
>     [Unit]
>     Before=

I recently attempted this on R4.0 rc4, but systemd can't reset orderings via a drop-in. Only new ones can be added - see `systemctl show --property=Before qubes-vm@whatever.service`.

Anyway, patching `qubes-vm@.service` to remove `Before=systemd-user-sessions.service` caused the Network Manager tray icon for sys-net to be missing on most startups, until I manually started the GUI daemon.

**Comment by donob4n** [comment] 2018-02-28 18:10
Maybe an easy solution for 3.2 could be that autostarting VMs wait for X instead the opposite.

It will take more total time but the user experience will boost if you get the password prompt or your desktop (I use autologin since there is already a luks passphrase for booting) in ~7 seconds instead 40...

**Comment by 3hhh** [comment] 2018-02-28 19:15
> Maybe an easy solution for 3.2 could be that autostarting VMs wait for X instead the opposite.

Yes, that's an option if you use autologin anyway.

Othe than that if one wants to use the password typing time, I see the following options for applications that require X:

1. in such VMs: Start applications using something such as `wait until X available; [application start]`.

1. in dom0: Use the X desktop files to run `qvm-run [VM] [application]` as these are only executed after X startup anyway.

For nm-applet in particular there's also a cli available that doesn't need X. But then of course you're losing that handy tray app...

**Comment by 3hhh** [comment] 2018-02-28 19:20
@donob4n One of the reasons I don't like autologin atm: If your X server crashes with a screen lock on, it'll automatically restart and you may end up with an unlocked machine unless you have some clever screen locker checking for a crash during each X server startup...

**Comment by marmarek** [comment] 2018-02-28 20:21
> Maybe an easy solution for 3.2 could be that autostarting VMs wait for X instead the opposite.

You can simply disable "autostart" option, then add own session startup command (in Xfce go to Settings Manager -> Session and Startup) like `qvm-start some-vm` or even `qvm-run -a some-vm some-app`.

**Comment by donob4n** [comment] 2018-03-01 19:50
@3hhh 

> One of the reasons I don't like autologin atm: If your X server crashes with a screen lock on, it'll automatically restart and you may end up with an unlocked machine unless you have some clever screen locker checking for a crash during each X server startup...

Good to know, thanks.

@marmarek 

> You can simply disable "autostart" option, then add own session startup command (in Xfce go to Settings Manager -> Session and Startup) like qvm-start some-vm or even qvm-run -a some-vm some-app.

After some play with systemd and got GUI problems, I finally used this way and it works fine.

 I will test on 4.0. The boot experience is really better and if it doesn't have problems should be default behavior right?

**Comment by 3hhh** [comment] 2018-03-27 10:27
Same request: https://groups.google.com/forum/#!topic/qubes-users/6QNAPDeMp5A

**Comment by rustybird** [comment] 2019-05-05 13:32
For a couple of months now, I've been running Qubes with `Before=systemd-user-sessions.service` removed from dom0 [/usr/lib/systemd/system/qubes-vm@.service](https://github.com/QubesOS/qubes-core-admin/blob/master/linux/systemd/qubes-vm%40.service), and haven't encountered any problems since QubesOS/qubes-core-admin#229 and QubesOS/qubes-linux-utils#37 were merged. It really does wonders for the perceived startup speed.

The only caveat I can think of would be for `qubes.InputKeyboard` (and `qubes.InputMouse`) RPC users, presumably their keyboard (and mouse) are then unresponsive until sys-usb has started. To avoid this regression (for the keyboard anyway - not sure what to do about the mouse), [`usb-keyboard.sls`](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/usb-keyboard.sls) could create a `/usr/lib/systemd/system/qubes-vm@sys-usb.service.d/before-login.conf` drop-in, containing the ordering that was removed from `qubes-vm@.service`:

```
[Unit]
Before=systemd-user-sessions.service
```

**Comment by marmarek** [comment] 2019-05-06 00:50
I think it's safer to create that file in all the cases (together with sys-usb). Even if that would be about just mouse, it will be very confusing if it will not work from the beginning.
Other use cases may be affected too - for example 2FA with Yubikey or such.

**Comment by brendanhoar** [comment] 2019-05-06 11:01
I mostly remedied it the old-fashioned way: disable autostart for all VMs except for sys-usb.  One could argue that should be the default anyway.

**Comment by rustybird** [comment] 2019-05-07 15:32
@marmarek:
> I think it's safer to create that file in all the cases (together with sys-usb).

Sounds reasonable. And if the drop-in is written into the `/usr/lib/systemd/` hierarchy, people who do want to login _before_ sys-usb startup will be able to mask the drop-in file in the equivalent `/etc/systemd/` directory. 

[`sys-usb.sls`](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/sys-usb.sls) can prioritize sys-usb startup with another drop-in file (in `qubes-vm@.service.d/` somewhere):

```
[Unit]
After=qubes-vm@sys-usb.service
```

This combo of systemd unit templates, drop-ins, and orderings seems to work fine. Unsurprisingly, it  logs a warning: `systemd[1]: qubes-vm@sys-usb.service: Dependency After=qubes-vm@sys-usb.service dropped`

@brendanhoar:
> I mostly remedied it the old-fashioned way: disable autostart for all VMs except for sys-usb. One could argue that should be the default anyway.

Depends on the use case... To keep some online data in sync, I autostart a couple of VMs but not sys-usb.

**Comment by brendanhoar** [comment] 2019-05-07 17:30
@rustybird 
> @brendanhoar:
> 
> > I mostly remedied it the old-fashioned way: disable autostart for all VMs except for sys-usb. One could argue that should be the default anyway.
> 
> Depends on the use case... To keep some online data in sync, I autostart a couple of VMs but not sys-usb.

Valid point. Thanks.
Brendan

**Closed** 2021-05-13 18:25 UTC
Labels: C: other, P: default, T: enhancement, ux
