### ISSUE TITLE
Changing NetVM in a running AppVM causes errors

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1391] opened 2015-11-08 00:34 UTC
I'm not sure if the behavior of `Changing the NetVM of an AppVM that is running` is not supposed to be allowed, but it seems to save the change. However, the change does not seem to have the desired effect nor persist in the VM Manager. Upon stopping the AppVM and trying to redo the change, I get the following `dom0` window:

```
ERROR: Basic Tab: 36
```

**Comment by axon-qubes** [comment] 2015-11-08 00:46
Possible duplicate of #975.

**Closed** 2016-01-07 00:10 UTC
Labels: bug, duplicate
