### ISSUE TITLE
Linux to Windows file copy same name

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#1976] opened 2016-05-10 16:08 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

- *inux VM's
- Windows VM's

---

### Expected behavior: 

Renaming of the second file to filename-copy.extension

### Actual behavior: 

File exists error -> copy process aborts

### Steps to reproduce the behavior: 

Copy first Document.pdf to Windows VM and then copy document.pdf or the other way around.

### General notes:

Windows does not make a difference between lower case and upper case file names. For example document.pdf and Document.pdf is the same file under Windows. 
In Linux on the other hand document.pdf and Document.pdf are two different files.

It would be nice if the qubes-copy-to-vm tools could handle this transparently and rename the second file if the copy target VM is a Windows VM to filename-copy.extension. For example rename document.pdf to document-copy.pdf, if Document.pdf is already in the folder.

---

**Comment by andrewdavidwong** [comment] 2016-05-10 19:49
Duplicate of #1772.

**Closed by andrewdavidwong** 2016-05-10 19:49 UTC
Labels: duplicate

**Comment by Jeeppler** [comment] 2016-05-10 19:57
@andrewdavidwong: this is not the same as #1772 this is a Linux -> Windows issues. Windows does not differentiate between upper and lower case letters in file names and Linux does. This means even if document.pdf and Document.pdf are two different files on a Linux VM. Windows will complain. 

#1772 handles another more general use case if files already exist, but there are not a duplicate.

**Comment by marmarek** [comment] 2016-05-10 20:06
From Windows point of view, the issue is the same.

**Comment by andrewdavidwong** [comment] 2016-05-10 20:15
@Jeeppler: It's not a duplicate in the sense that they describe precisely the same issue, but it's a duplicate in the sense that any good solution to #1772 should also solve this issue. There's no reason to implement a Windows-specific solution to this problem when a more general solution for all VM types will work just as well (or better).

**Comment by Jeeppler** [comment] 2016-05-10 20:16
@andrewdavidwong that is true
