### ISSUE TITLE
sys-gui-vnc: can't update qubes from it

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#9301] opened 2024-06-13 12:14 UTC
### Qubes OS release

4.2.1

### Brief summary

I'm using sys-gui-vnc as a guivm, I have a systray icon indicating there are updates for qubes, but the updater GUI fails to start.

As a fallback, `qubesctl` command can't be used to trigger the updates in templates.

### Steps to reproduce

Setup sys-gui-vnc, run `qubes-gui-update` from it.

### Expected behavior

the GUI shows up and I can update the qubes.

### Actual behavior

The program fails to start as user or as root

```
[user@sys-gui-vnc Desktop]$ qubes-update-gui 
Traceback (most recent call last):
  File "/usr/bin/qubes-update-gui", line 33, in <module>
    sys.exit(load_entry_point('qui==0.1', 'gui_scripts', 'qubes-update-gui')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 313, in main
    app = QubesUpdater(qapp, cliargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 48, in __init__
    log_handler = logging.FileHandler(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/logging/__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib64/python3.12/logging/__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/log/qubes/qui.updater.log'
```

as root

```
[user@sys-gui-vnc Desktop]$ sudo qubes-update-gui 
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 60, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 169, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 100, in populate_vm_list
    self.list_store.append_vm(vm, state)
  File "/usr/lib/python3.12/site-packages/qui/updater/utils.py", line 279, in append_vm
    qube_row = self.row_type(self.list_store_raw, vm, state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 252, in __init__
    updates_available = bool(vm.features.get('updates-available', False))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/features.py", line 74, in get
    return self[item]
           ~~~~^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/features.py", line 54, in __getitem__
    return self.vm.qubesd_call(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/base.py", line 76, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/app.py", line 910, in qubesd_call
    raise qubesadmin.exc.QubesDaemonAccessError(
qubesadmin.exc.QubesDaemonAccessError: Service call error: Request refused

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 60, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 169, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 100, in populate_vm_list
    self.list_store.append_vm(vm, state)
  File "/usr/lib/python3.12/site-packages/qui/updater/utils.py", line 279, in append_vm
    qube_row = self.row_type(self.list_store_raw, vm, state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 252, in __init__
    updates_available = bool(vm.features.get('updates-available', False))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/features.py", line 74, in get
    return self[item]
           ~~~~^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/features.py", line 54, in __getitem__
    return self.vm.qubesd_call(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/base.py", line 76, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qubesadmin/app.py", line 910, in qubesd_call
    raise qubesadmin.exc.QubesDaemonAccessError(
qubesadmin.exc.QubesDaemonAccessError: Service call error: Request refused
```

**Comment by rapenne-s** [comment] 2024-06-13 12:21
After adding the following lines in dom0 `/etc/qubes/policy.d/50-gui-sys-gui-vnc.policy`

```
admin.vm.feature.Get        +os-eol sys-gui-vnc             dom0                             allow
admin.vm.feature.Get        +template-name sys-gui-vnc             dom0                             allow
admin.vm.feature.Get        +updates-available sys-gui-vnc             dom0                             allow
admin.vm.feature.Get        +last-updates-check sys-gui-vnc             dom0                             allow
admin.vm.feature.Get        +last-update sys-gui-vnc             dom0                             allow
```

I get the following error

```
[user@sys-gui-vnc Desktop]$ sudo qubes-update-gui 
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 60, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 169, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 106, in populate_vm_list
    self.refresh_update_list(settings.update_if_stale)
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 119, in refresh_update_list
    to_update = self._get_stale_qubes(cmd)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 209, in _get_stale_qubes
    output = subprocess.check_output(cmd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qubes-vm-update'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 60, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.12/site-packages/qui/updater/updater.py", line 169, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 106, in populate_vm_list
    self.refresh_update_list(settings.update_if_stale)
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 119, in refresh_update_list
    to_update = self._get_stale_qubes(cmd)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qui/updater/intro_page.py", line 209, in _get_stale_qubes
    output = subprocess.check_output(cmd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qubes-vm-update'
```

**Comment by rapenne-s** [comment] 2024-06-13 12:30
Actually, having sys-gui-vnc breaks updates done through dom0. I did not change anything to the system since I've setup sys-gui-vnc.

all my fedora templates (I'm only using fedora) fail to update with this error

```
Updating fedora-39-xfce
Install requirements
Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Proxy CONNECT aborted]
Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Proxy CONNECT aborted]
```

**Comment by marmarek** [comment] 2024-06-13 12:45
> Actually, having sys-gui-vnc breaks updates done through dom0

Can you check updates proxy logs? Could it be #9299 ?

**Comment by marmarek** [comment] 2024-06-13 12:47
As for the original issue: duplicate of #8934

**Closed** 2024-06-13 12:47 UTC
Labels: T: bug, R: duplicate, P: default

**Comment by rapenne-s** [comment] 2024-06-13 13:06
> > Actually, having sys-gui-vnc breaks updates done through dom0
> 
> Can you check updates proxy logs? Could it be #9299 ?

it was 9299 indeed, bad timing :grin:
