### ISSUE TITLE
Debian bullseye templates have very low entropy available / low quality of entropy?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#6939] opened 2021-10-06 10:46 UTC
Qubes (R4.0) Debian bullseye templates have very low entropy available.

    cat /proc/sys/kernel/random/entropy_avail
> 516

    cat /dev/random 

Just shows 1 line and is then blocking.

```
��m�������7�ΌM�&�=�At��:�֓�KS>�
```

It might also lead to low quality of entropy according to https://github.com/QubesOS/qubes-issues/issues/673? That could be potentially disastrous - think crypto currency wallet seed generation, (OpenPGP) key generation and so forth if applications are using `/dev/urandom`? Which many applications do due to widespread view "just use /dev/urandom", see [/dev/random vs /dev/urandom](https://www.whonix.org/wiki/Dev/Entropy#.2Fdev.2Frandom_vs._.2Fdev.2Furandom]).

haveged is installed by Qubes default but seems to have no effect.

Installing jitterentropy-rngd makes it faster but I am not sure that is a full solution to the issue.

>sudo apt install jitterentropy-rngd

    cat /proc/sys/kernel/random/entropy_avail
>1920

To avoid this happening in future, I suggest Qubes test suite to check if the value in <code>/proc/sys/kernel/random/entropy_avail</code> is high enough.

Qubes-Whonix / Kicksecure: has jitterentropy-rngd installed by default and systemcheck checks <code>/proc/sys/kernel/random/entropy_avail</code>.

Non-duplicates, related:

* https://github.com/QubesOS/qubes-issues/issues/673 (more fundamental considerations)
* https://github.com/QubesOS/qubes-issues/issues/4169 (one possible solution but might as well just be band-aid and obfuscate any underlying issue here, if any)

**Comment by DemiMarie** [comment] 2021-10-06 11:55
> Qubes (R4.0) Debian bullseye templates have very low entropy available.
> 
> ```
> cat /proc/sys/kernel/random/entropy_avail
> ```
> 
> > 516

516 bits is more than adequate.  Entropy is not a consumable resource; the kernel’s CSPRNG will produce high quality random bits forever after initial seeding.  The only exception is if someone manages to read kernel memory, but then there are worse problems to deal with.

@marmarek am I missing something or is this working as intended?

**Comment by adrelanos** [comment] 2021-10-06 12:15
Trying to generate a gpg / ssh test key now...

**Comment by 3hhh** [comment] 2021-10-06 15:37
Hm I get ~2 MB/s with `haveged` on debian-10. So maybe this is a `haveged` configuration issue on debian-11?

**Comment by marmarek** [comment] 2021-10-06 15:40
The issue seems to be specific to R4.0. I just tried on fresh debian-11 on R4.1 and it took between 1-2s. Also, `/proc/sys/kernel/random/entropy_avail` shows values over 3k.
`haveged` is running in this case correctly.

But, on R4.0 `haveged` systemd unit is broken, due to a workaround for a bug from Debian stretch times. I'll backport https://github.com/QubesOS/qubes-core-agent-linux/commit/30f6c496bc5bef2d2bbebcee597378f96aad5342 to R4.0.

**Comment by marmarek** [comment] 2021-11-11 23:30
Fixed in https://github.com/QubesOS/qubes-core-agent-linux/commit/6735b2e936740e270236ed737082a4781f5e3e5f

**Closed by marmarek** 2021-11-11 23:30 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, diagnosed
