### ISSUE TITLE
32 files that are cleaned but never cleaned (Fedora-Templates) - Files for Eternity

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7540] opened 2022-06-01 23:23 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Cleaning packages after upgrades is good behavior to keep your distro clean from unnecessary files.

### Steps to reproduce

- Download fedora 35 template (34 affected as well)
- Open terminal and run: 

`sudo dnf --refresh upgrade && sudo dnf clean all`

### Expected behavior

after cleaning files there should be 0 files exist for cleaning

### Actual behavior

```
[user@fedora-35 ~]$ sudo dnf --refresh upgrade && sudo dnf clean all
Fedora 35 - x86_64                              3.5 MB/s |  79 MB     00:22    
Fedora 35 openh264 (From Cisco) - x86_64        726  B/s | 2.5 kB     00:03    
Fedora 35 - x86_64 - Updates                    2.5 MB/s |  30 MB     00:11    
Qubes OS Repository for VM (updates)             62 kB/s | 161 kB     00:02    
Last metadata expiration check: 0:00:01 ago on Wed Jun  1 23:12:57 2022.
Dependencies resolved.
Nothing to do.
Complete!
32 files removed
[user@fedora-35 ~]$ sudo dnf --refresh upgrade && sudo dnf clean all
Fedora 35 - x86_64                              3.2 MB/s |  79 MB     00:24    
Fedora 35 openh264 (From Cisco) - x86_64        655  B/s | 2.5 kB     00:03    
Fedora 35 - x86_64 - Updates                    1.9 MB/s |  30 MB     00:16    
Qubes OS Repository for VM (updates)             66 kB/s | 161 kB     00:02    
Dependencies resolved.
Nothing to do.
Complete!
32 files removed
[user@fedora-35 ~]$ 
```

**Comment by DemiMarie** [comment] 2022-06-02 00:45
DNF deliberately keeps these files as a cache, to avoid having to uselessly redownload metadata.  Qubes bypasses this cache during upgrades, but it is still very useful during installation and search commands.

Closing as “not a bug” (the reported behavior is not a bug).

**Closed by DemiMarie** 2022-06-02 00:45 UTC
Labels: T: bug, R: not an issue, P: default
