### ISSUE TITLE
Qubes update can fail silently

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#4815] opened 2019-02-13 12:24 UTC
### Qubes OS version

R4.0

### Affected component(s):

Qubes Update (Gui)

---

### Steps to reproduce the behavior:

Likely an update with network disconnected will reproduce it.

### Expected behavior:

Failure it marked by red cross.

### Actual behavior:

The failure is silently ignored, I see green tick.

![screenshot_2019-02-13_12-41-14](https://user-images.githubusercontent.com/184015/52711635-913dfc00-2f92-11e9-8a7c-e9c73c63e743.png)

**Comment by andrewdavidwong** [comment] 2019-02-14 04:34
Duplicate of #4674

**Comment by andrewdavidwong** [comment] 2019-02-14 04:35
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-02-14 04:35 UTC

**Comment by v6ak** [comment] 2019-02-14 07:56
You are right. I have (unsuccessfully) tried to find an existing issue. Sorry for the duplicate.
