### ISSUE TITLE
Random black screen or black boxes on the screen

### ISSUE THREAD

**Issue by lightyagamipotatochip** [QubesOS/qubes-issues#5990] opened 2020-08-08 22:32 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Screen, Display, Xfce?

**Brief summary**
I'm getting random screen issues when for an unknown reason the whole screen goes black or is almost filled with black boxes.

**To Reproduce**
I have no consistent way of reproducing this. Sometimes it fails around a time in the day. Sometimes it fails when I open in Firefox the AWS console. Sometimes it fails when I'm working on IntelliJ IDEA. Most of the time it happens when I'm using the same VMs. It is like the lock screen tries to show on top but it fails. I have no idea what is causing it.

**Expected behavior**
The screen never goes totally black or shows black boxes.

**Actual behavior**
The screen goes totally black or shows black boxes randomly.

**Screenshots**
![img1](https://user-images.githubusercontent.com/69404033/89720736-0726f600-d9c5-11ea-9fb0-344abd352ea8.jpg)
![img2](https://user-images.githubusercontent.com/69404033/89720739-17d76c00-d9c5-11ea-8496-f92c2dd022a1.jpg)

**Additional context**
* I have a NVIDIA card
* I installed the kernel-latest package to better support the video card
* I have a 4K monitor

**Solutions you've tried**
To fix this I move between workspaces and click the windows below the black boxes and little by little the boxes disapear.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I don't know where to start

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by ejose19** [comment] 2020-08-12 00:06
Pretty sure this is fixed by going to Window Manager Tweaks -> Compositor and unchecking "Enable display compositing"

**Comment by lightyagamipotatochip** [comment] 2020-09-14 22:13
I reinstalled the OS but this time without the kernel-latest package and it happened again.

@PROTechThor I did that and the display has been working properly since then.
I don't understand a lot about Linux desktop environments but to me it doesn't seem like a fix but more like a workaround. What is the reasoning behind using Xfce?

Thanks for the help.

**Comment by ejose19** [comment] 2020-09-14 23:54
@lightyagamipotatochip it **is** a workaround, this issue has been reported previously (#4514, #2399) but no solution has been found yet. However you're not missing much disabling the display compositing.

**Comment by andrewdavidwong** [comment] 2020-09-15 04:50
> this issue has been reported previously (#4514, #2399) but no solution has been found yet.

Are you suggesting these are all duplicates? The reporter of #4514 said that he doesn't think it's a duplicate of #2399.

**Comment by ejose19** [comment] 2020-09-15 14:41
@andrewdavidwong #4514 is mentioning alt+tab redraws the screen, which is basically #2399. I've suffered from this on the past before disabling display compositing and know to recognize this issue.

**Closed** 2023-08-05 09:25 UTC
Labels: T: bug, C: desktop-linux, P: default, hardware support, needs diagnosis, eol-4.0
