### ISSUE TITLE
domU template tinyproxy traffic not routing though sys-firewall

### ISSUE THREAD

**Issue by bzillacodes** [QubesOS/qubes-issues#8384] opened 2023-08-01 11:21 UTC
### Qubes OS release
R4.1.2

### Brief summary
dnf/apt traffic seems to route directly from sys-net to the template when updating/installing packages.

Whereas the automatic update checks appear to route through sys-firewall like intended.

## Steps to reproduce
After a fresh install with updates not chosen to go through sys-whonix:

Opened gnome system monitor in sys-{net, firewall} (default fedora-37) to monitor resource IO ->

Network IO is seen going though as sys-net > sys-firewall > [automatic update check], after it occurs and the notification appears to update ->

Open qubes-update-gui and update the qube, the network IO is only seen getting routed through sys-net and doesn't pass through sys-firewall.

### Expected behavior
Non-whonix domU templates should route their dnf/apt tinyproxy traffic thorugh sys-firewall rather than accessing packages/updates through sys-net directly.

### Actual behavior
Updates and package installs can successfully pass through from sys-net to domU non-whonix templates. Which can further be confirmed by shutting down sys-firewall and attempting template updates and package installs.

**Comment by bzillacodes** [comment] 2023-08-01 16:33
Closest related issue: UpdateVM for templates always defaults to sys-net [#3118](https://github.com/QubesOS/qubes-issues/issues/3118) which does provide insights to configuring the desired proxyVM per domain, incase anyone else was looking.

I'd assume many users would figure that dnf/apt traffic gets routed through sys-firewall. I figured this was the case until I had templates update/install packages successfully without sys-firewall booted.

I think from a secure approach for standard users, R4.2 should implement a sys-update qube of some sort to separate network traffic from sys-firewall. Since many users are likely to be sloppy with network attached qubes that are connected to sys-firewall by default. It doesn't seem safe to keep sys-firewall as both the standard dom0-update-qube and network qube.

**Comment by andrewdavidwong** [comment] 2023-08-02 02:13
> Whereas the automatic update checks appear to route through sys-firewall **like intended**.

No, non-Whonix template updates going through sys-net by default is intentional. You can easily prove this to yourself simply by viewing `/etc/qubes/policy.d/90-default.policy` in dom0 and seeing that the Qubes devs intentionally wrote these lines:

```
# Default rule for all TemplateVMs - direct the connection to sys-net
qubes.UpdatesProxy      *   @type:TemplateVM        @default    allow target=sys-net
```

You can also see the same thing in the source code here on GitHub:

https://github.com/QubesOS/qubes-core-admin/blob/00ac303627c2e935e6635dd5709385c7d82fb5d4/qubes-rpc-policy/90-default.policy#L73-L74

-----

Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-08-02 02:13 UTC
Labels: T: bug, P: default

**Comment by bzillacodes** [comment] 2023-08-02 03:48
I now understand how the qubes-rpc policies work by default with templateVM updates, I just don't understand why. I agree that it is not a bug as it is intended by the configuration files stated above. But I figured after reading how HVM qubes with pci connected devices cannot be considered secure, hence why users are urged to connect network qubes with a (sys-net -> sys-firewall -> [net-qube]) network architecture, and control all firewall rules through the proxyVM.

So maybe I should've investigated my concern further and made a feature request instead.

Maybe the qubes-global-settings should have an option to control the updateVM for non-whonix templates, similar to how the updateVM for dom0 can be chosen.

Should I continue the thread here with a feature request or open a new issue altogether @andrewdavidwong ?

**Comment by andrewdavidwong** [comment] 2023-08-02 09:09
> I now understand how the qubes-rpc policies work by default with templateVM updates, I just don't understand why.

The best place to ask questions about developer design decisions is probably on the [qubes-devel mailing list](https://www.qubes-os.org/support/#qubes-devel).

> But I figured after reading how HVM qubes with pci connected devices cannot be considered secure, hence why users are urged to connect network qubes with a (sys-net -> sys-firewall -> [net-qube]) network architecture, and control all firewall rules through the proxyVM.

I don't know much about that topic, but if you read that from some non-official source, then I'd take it with a grain of salt.

> Should I continue the thread here with a feature request or open a new issue altogether @andrewdavidwong ?

I think, at this point, I think it would be simpler and cleaner to open a new issue.
