### ISSUE TITLE
No audio vm packages in Debian-based templates

### ISSUE THREAD

**Issue by a-barinov** [QubesOS/qubes-issues#7033] opened 2021-11-02 21:11 UTC
### Qubes OS release
4.1-rc1

### Brief summary
No packages for audio vm creation (qubes-audio-daemon, is anything else needed?) available in Debian-based templates. These packages are available in Fedora-based templates.

### Steps to reproduce
Try 'apt-get install qubes-audio-daemon' or go to http://deb.qubes-os.org/r4.1/vm/pool/main/ 

### Expected behavior
qubes-audio-daemon package available for Debian

### Actual behavior
qubes-audio-daemon does not exist in Debian

**Comment by marmarek** [comment] 2021-11-02 23:37
It seems to be "just" inconsistent naming: there is `qubes-gui-daemon-pulseaudio`.

**Comment by andrewdavidwong** [comment] 2021-11-03 05:07
> It seems to be "just" inconsistent naming: there is `qubes-gui-daemon-pulseaudio`.

Is this considered `not an issue`, then, or something to be changed?

**Comment by unman** [comment] 2021-11-03 14:13
On Tue, Nov 02, 2021 at 10:07:30PM -0700, Andrew David Wong wrote:
> > It seems to be "just" inconsistent naming: there is `qubes-gui-daemon-pulseaudio`.
> 
> Is this considered `not an issue`, then, or something to be changed?
> 

We already have an issue for inconsistent Debian naming - #6094 - I
suggest you generalise that (which you raised), and close this with
reference to it.
I'm in the process of updating those package names, so this should be
addressed soon.

**Comment by andrewdavidwong** [comment] 2021-11-05 01:02
> On Tue, Nov 02, 2021 at 10:07:30PM -0700, Andrew David Wong wrote: > It seems to be "just" inconsistent naming: there is `qubes-gui-daemon-pulseaudio`. Is this considered `not an issue`, then, or something to be changed?
> We already have an issue for inconsistent Debian naming - #6094 - I suggest you generalise that (which you raised), and close this with reference to it. I'm in the process of updating those package names, so this should be addressed soon.

Sounds good. Closing as a duplicate of #6094.

**Closed by andrewdavidwong** 2021-11-05 01:02 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, diagnosed
