### ISSUE TITLE
Qubes 4.0 Updated, no vms are starting

### ISSUE THREAD

**Issue by linuxcomputer** [QubesOS/qubes-issues#3314] opened 2017-11-16 23:52 UTC
#### Qubes OS version:
Qubes release 4.0 (R4.0)

#### Affected TemplateVMs:
All the VMs

#### Steps to reproduce the behavior:
Update the system using this command:
sudo qubes-dom0-update
It was working after that, but when i reboot the machine, none of the VMs are starting.

#### Expected behavior:
Update the system and vms should work after a reboot

#### Actual behavior:
None of the VMs are starting after update

#### General notes:
Already tried starting them manually and still not working but i got this message:
COMMAND: qvm-start vault
RESULT:  volume qubes_dom0/vm-fedora-25-root missing
And aso
COMMAND: qvm-start debian-8
RESULT: volume qubes_dom0/vm-debian-8-private missing
What can i do? I got important things on my vms.

**Comment by linuxcomputer** [comment] 2017-11-17 00:08
Did
sudo lvs
Results:
vm-debian-8-private-snap
vm-debian-8-private-tmp

**Comment by marmarek** [comment] 2017-11-17 00:15
Did your system crashed during debian-8 shutdown?
Anyway try this:
```
sudo lvrename qubes_dom0 vm-debian-8-private-tmp vm-debian-8-private
```
Try similar thing with fedora-25-root (look for fedora-25-root-tmp).

Then, lets try to find the root cause. Search `sudo journalctl -u qubesd` for things about fedora-25-root (and debian-8-private).

**Comment by Aekez** [comment] 2017-11-21 14:07
I just encountered this same problem today, at least it looks alike, with some slight differences. 

My qvm-run instead rapport a missing directory. Journalctl seem to give the details below.

How to reproduce (from today's update, was fully updated yesterday). Ran 
qubes-dom0-update --enablerepo=qubes-dom0-current-testing

From what I can tell, or guess, it's probably the Qubes  admin update that broke things, and it looks like it too?when running 
Sudo journalctl -u qubesd --boot
As you suggested. 

Unfortunately I can't post the entire output before I get near another trustworthy computer which I can transfer the log to his USB in dom0. I'll provide this in half a day if it a still needed. 

Here is what it tells me in rough cheery picking from the log, in order. All events happen inn the same second, to the same activity. For example starting sys-net.  

- Starting sys-net
-A fee likes if proper working code it seems.
- FileNotFoundError: [Error 2] No such file or directory. 
- During handling of the above exception, another exception occurred: 
- Traceback (most recent call last): 
- Some 10-12 give or take python code that gives no errors. Until; 
- File "/usr/lib/python3.5/site-packages/qubes/vm/qubesvm.pv", line 1257, in requested memory raise IOError('Failed to connect to qmemman: {!s}' .format(e))
- OSError: Failed to connect tool qmemman: [Error 2] No such file or directory.
- End of log event for sys-net start-up.

The first error, appears to be to the working line reference before it, /var/run/qubes/qmemman.sock") 

Issues: 
How to prevent it from happening? 
How to fix it, once it happens? 


I'll post the full detailed log in half a day from now, if the above is not sufficient to find out what's wrong. 

Much appreciated,
Aekez

**Comment by marmarek** [comment] 2017-11-21 16:15
This looks rather like #3324

**Comment by Aekez** [comment] 2017-11-21 17:26
Thanks mamare,, your solution in that thread worked instantly. I was able to start all the VMs without any trouble after typing in 
sudo systemctl start qubes-qmemman.service

What did not work was:
- I tried the restarting approach a few times as well, but this approach did not work in my case. I tried 5 restarts. 
- Also the solution of typing in the command, does not stick after a fresh boot. But it's still a big improvement, now I can use my system, albeit by having to type in the command at every boot first.

**Comment by Aekez** [comment] 2017-11-21 17:37
Of course! I have to use enable instead of just start, my, I feel stupid for something to obvious. Albeit in also really exhausted, might explain it. Well.. Now it works automatically too. 

I apologize for typo in your name, was not meant as disrespect.

**Comment by jpouellet** [comment] 2019-06-24 22:56
@andrewdavidwong I think this issue should be closed since the relevant code has changed a lot since the time it was opened (see: https://github.com/QubesOS/qubes-core-admin/pull/203). I used to see this issue occasionally, but it's been fine for the past ~year.

**Comment by andrewdavidwong** [comment] 2019-06-25 05:22
> @andrewdavidwong I think this issue should be closed since the relevant code has changed a lot since the time it was opened (see: [QubesOS/qubes-core-admin#203](https://github.com/QubesOS/qubes-core-admin/pull/203)). I used to see this issue occasionally, but it's been fine for the past ~year.

Closing. If anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-06-25 05:22 UTC
Labels: C: other, T: bug
