### ISSUE TITLE
Better handle unusual technical error messages

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1823] opened 2016-03-09 14:22 UTC
I just encountered a strange Dom0 error. I am uncertain what triggered this error or how it affected the Qubes VM Manager, as it seemed to be running just fine. 

```
Houston, we have a problem...

AttributeError: 'module' object has no attribute 'VIR_INTERNAL_ERROR'

This is mostly a bug in the Qubes Manager

----
line: elif e.get_error_code() == libvirt.VIR_INTERNAL_ERROR:
func: is_running
line no.: 935
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: if not vm.is_running():
func: measure_cpu_usage
line no.: 234
file: /usr/lib64/python2.7/site-packages/qubes/qubes.py
----
line: self.last_measure_time)
func: update_table
line no.: 768
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

I have no idea what this message meant. Regarding messages of this nature, perhaps we should handle them in the one of the following ways:

1. Offer a way to report this message to Qubes (if useful)
2. A simple notification like `Something small went wrong`
3. Or suppress them entirely from the end user

**Comment by andrewdavidwong** [comment] 2016-05-19 09:54
Duplicate of #1300.

**Closed by andrewdavidwong** 2016-05-19 09:54 UTC
Labels: C: qubes-manager, duplicate, UX
