### ISSUE TITLE
Updater: Selecting options in a certain order leaves "Next" button grayed out, but the same options in a different order works

### ISSUE THREAD

**Issue by kord1e** [QubesOS/qubes-issues#8063] opened 2023-02-25 09:19 UTC
### Qubes OS release
4.1

Updater doesn't let you to proceed if you tick the options in wrong order. How to reproduce:

1) Open updater
2) Un-tick all qubes that have updates available (in my case there's always Fedora 36 see above)
3) Click "Enable updates for qubes without known available updates"
4) Tick a qube that doesn't seem to have updates available (or dom0)

What happens - the "next" button stays grey and you can't proceed.

This also happens if you do the steps in order: 1, 3, 2, 4
But it does not happen if you do it in order: 1, 3, 4, 2 !

**Comment by andrewdavidwong** [comment] 2023-02-25 21:16
Hello, and welcome to the Qubes issue tracker! Thank you for taking the time to open an issue. However, [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing). I'm going to modify this issue accordingly.

> Problem 1: Updater shows that Fedora 36 template has updates available all the time. Even when it was just updated. Somehow it got stuck like this.

This sounds like a *possible* duplicate of #6279, so I'll modify this issue so that it's solely about what you labeled "Problem 2" (which doesn't appear to be similar to any existing issues of which I'm aware).

**Comment by marmarta** [comment] 2023-03-14 14:59
I think this is obsolete in terms of https://github.com/QubesOS/qubes-desktop-linux-manager/pull/139 - the new updater window should not have this problem at all (and I've tested the current version of that PR and indeed it has it not).

**Closed by marmarta** 2023-03-14 14:59 UTC
Labels: T: bug, C: manager/widget, P: default, needs diagnosis, C: updates
