### ISSUE TITLE
Fix locale in fedora-*-minimal

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2435] opened 2016-11-14 07:45 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-24-minimal

---

When updating the fedora-24-minimal template, there are warnings of this type:

    /etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory

(Repeated for `LC_COLLATE`, `LC_MESSAGES`, `LC_NUMERIC`, and `LC_TIME`.)

And after the update is finished:

    Failed to set locale, defaulting to C

**Comment by rustybird** [comment] 2016-11-14 11:44
This can be fixed by installing the `glibc-langpack-en` package, or alternatively by running `localectl set-locale LANG=C`

**Comment by jpouellet** [comment] 2016-11-15 05:59
Yeah, I noticed this too.

```
% strace -o trace man man > /dev/null
man: can't set the locale; make sure $LC_* and $LANG are correct
% grep locale trace                  
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/locale/en_US.UTF-8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en_US.utf8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en_US/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en.UTF-8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en.utf8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
write(2, "can't set the locale; make sure "..., 59) = 59
open("/usr/lib/locale/en_US.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en_US.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en_US/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Changing /etc/locale.conf from `LANG=en_US.UTF-8` to `LANG=C` also seems to work.

**Comment by jpouellet** [comment] 2016-11-22 02:48
@marmarek what do you think the appropriate path forward is here?

I propose installing `glibc-langpack-en` for fedora24 and only setting `LANG=C` for -minimal.

**Comment by marmarek** [comment] 2016-11-22 02:56
Seems like a good idea.

**Comment by marmarek** [comment] 2016-11-22 03:11
Hmm, looking [the commit setting locale](https://github.com/QubesOS/qubes-core-agent-linux/commit/0ccd2c9a98d8f5fa33a91cf8dd534aa24e266671), it is done for gnome-terminal. Here are more details: https://github.com/QubesOS/qubes-issues/issues/1033
But I've just checked and gnome-terminal seems to run just fine with either `LANG=C` or `LANG=`. So, maybe setting default locale isn't needed at all anymore?

On the other hand - changing this right now (as a stable update) isn't the best idea... So this would be (if at all) for Qubes 4.0. And for now LANG=C just for minimal template.

**Comment by jpouellet** [comment] 2016-11-22 03:52
Not the best idea because why? A desire to avoid churn for everybody for minimal benefit? Or some other reason?

**Comment by marmarek** [comment] 2016-11-22 04:04
Risk of regression or other unwanted side effects - like the one with gnome-terminal mentioned above.

**Comment by jpouellet** [comment] 2016-11-22 04:26
Makes sense.

Sounds to me like that's an argument for just installing glibc-langpack-en instead of trying to switch to LANG=C? Or just leave this unresolved?

**Comment by marmarek** [comment] 2016-11-22 04:30
How many packages are pulled in by `glibc-langpack-en` on minimal template? If not many (for example just one), that's ok.

**Comment by jpouellet** [comment] 2016-11-22 06:14
Deps are small:
```
$ rpm -qR glibc-langpack-en
glibc = 2.23.1-11.fc24
glibc-common = 2.23.1-11.fc24
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

Install log on clean fedora-24-minimal [here](https://gist.githubusercontent.com/anonymous/64ce5d11cefa6dc19401b11604152b6c/raw/db7a9f002384876c93ed0dc48dbff498b111afd6/glibc-langpack-en-install-log.txt).

**Comment by andrewdavidwong** [comment] 2016-11-22 10:10
> I propose installing `glibc-langpack-en` for fedora24

Why? Is there a problem on `fedora-24`? I only noticed it on `fedora-24-minimal`.

> only setting `LANG=C` for -minimal

This seems preferable to installing any additional packages, especially in the minimal template. More packages, larger attack surface, right?

**Comment by marmarek** [comment] 2016-11-22 11:43
> Why? Is there a problem on fedora-24? I only noticed it on fedora-24-minimal.

Indeed non-minimal template have `glibc-all-langpacks` installed.

> This seems preferable to installing any additional packages, especially in the minimal template. More packages, larger attack surface, right?

I don't think `glibc-langpack-en` enlarge attack surface in any way (unless it would pull in some other package that would do so) - it doesn't expose any additional interface - package brings in only some data (translations), not code. IMO the only concern here for minimal template is its size, but the package is relatively small (275k compressed, about 4MB uncompressed).

**Comment by andrewdavidwong** [comment] 2016-11-22 12:02
> I don't think glibc-langpack-en enlarge attack surface in any way (unless it would pull in some other package that would do so) - it doesn't expose any additional interface - package brings in only some data (translations), not code.

But the attack surface isn't just the code; it also includes the package maintainer(s), their signing keys, development machines, etc., any/all of which could be compromised, right? (In any case, I agree that this one package doesn't make much of a difference, but *ceteris paribus*, it seems preferable to adhere to principles.)

**Comment by jpouellet** [comment] 2016-11-22 13:23
While I agree that simply having utf8 errno value -> string conversions and such should be totally fine, safe utf8 handling in general is quite difficult, and if using the `C` locale would cause programs to handle input as ASCII and bypass utf8 handling code paths, then perhaps there is something to be said for that.

For example, my IRC client displays all unicode characters as `\u1234` instead of the actual character, and this did in practice save me from some font rendering bug on OS X a while back (the details of which have been lost to memory).

- https://websec.github.io/unicode-security-guide/
- http://www.unicode.org/reports/tr36/
- http://www.unicode.org/reports/tr39/
- http://seriot.ch/resources/talks_papers/i_love_unicode_softshake.pdf
- http://seriot.ch/resources/talks_papers/20141106_asfws_unicode_hacks.pdf
- https://www.schneier.com/crypto-gram/archives/2000/0715.html#9

> Unicode is just too complex to ever be secure. -- Bruce Schneier

**Comment by marmarek** [comment] 2016-11-26 01:29
Updated template uploaded to the repository.

**Comment by 3n7r0p1** [comment] 2016-12-15 23:02
> Hmm, looking the commit setting locale, it is done for gnome-terminal. Here are more details: #1033
But I've just checked and gnome-terminal seems to run just fine with either LANG=C or LANG=. So, maybe setting default locale isn't needed at all anymore?

Not sure what I'm doing differently but gnome-terminal does not run for me in fedora-24-minimal with `LANG=C`. Installing `glibc-langpack-en`, followed by `localectl set-locale LANG=en_US.utf8` solves the issue. If `glibc-langpack-en` is left out for space considerations, perhaps a note could be added to fedora-24-minimal documentation?

Also, not to play favorites, maybe uninstall `glibc-langpack-zu` (South African isiZulu) from the default template?  :-P

```
$ localectl list-locales
C.utf8
zu_ZA
zu_ZA.utf8
```

**Comment by andrewdavidwong** [comment] 2016-12-22 07:21
> Also, not to play favorites, maybe uninstall glibc-langpack-zu (South African isiZulu) from the default template? :-P

```
$ sudo dnf remove glibc-langpack-zu
Dependencies resolved.
Error: The operation would result in removing the following protected packages: dnf, systemd.
```

Odd.

**Comment by 3n7r0p1** [comment] 2016-12-22 07:51
Ah, now it makes sense. I didn't get that error because I installed `glibc-lanpack-en` **before** removing zu. It must be that one langpack is required and that's why zu was not removed from the template in the first place.

**Comment by andrewdavidwong** [comment] 2016-12-22 08:01
Yes, you're right. After installing `glibc-lanpack-en`, I was able to remove `glibc-langpack-zu`. Since we have to have one installed anyway by default, it might as well be `glibc-lanpack-en`. What do you think @marmarek?

**Comment by marmarek** [comment] 2016-12-22 10:24
Makes sense. Interesting why `glibc-langpack-zu` is chosen by default...

**Comment by andrewdavidwong** [comment] 2017-08-06 17:19
This is also a problem on `fedora-25-minimal`.

**Comment by Polygonbugs** [comment] 2018-02-14 03:10
This also applied to fedora-26-minimal.

**Closed** 2018-07-13 23:36 UTC
Labels: C: Fedora, P: minor, bug
