### ISSUE TITLE
HVM crashes when installing any VM it seems to load the black screen then closes i have tried Kali cent windows same thing

### ISSUE THREAD

**Issue by Maestrocpl** [QubesOS/qubes-issues#4066] opened 2018-07-10 03:34 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Tryinng to create new HVMs example Kali Cent os Windows

---

### Expected behavior:

Complete installation

### Actual behavior:

Installing any vm doesnt work i get a black screen and it disapears 

### General notes:

Can seem to install any VMs in qubes

---

**Comment by marmarek** [comment] 2018-07-10 03:46
Try setting `memory` equal to `maxmem` (in GUI it's named "initial memory" and "Max memory", in advanced tab).

**Comment by Maestrocpl** [comment] 2018-07-10 03:51
I tried using 4gb ram same

**Comment by andrewdavidwong** [comment] 2018-07-10 04:04
Please provide the exact steps required to reproduce this behavior.

**Comment by Maestrocpl** [comment] 2018-07-10 16:10
Hi Andrew
rebooted and tried again the Ram fix solved it
deeply appreciate all your assistance and prompt response you guys rock
Thanks

**Comment by andrewdavidwong** [comment] 2018-07-10 23:45
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-07-10 23:45 UTC
Labels: C: core, bug
