### ISSUE TITLE
Whonixcheck fails but Passthrough is not blocked

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4827] opened 2019-02-17 07:18 UTC
### Qubes OS version:

R4.0

### Affected component(s):

sys-whonix

---

### Steps to reproduce the behavior:

Create a TCP/IP VPN based VM with sys-whonix as gateway.

Create another VM that uses the TCP/IP VPN as gateway.

Start this VM, seeing that the VPN VM and sys-whonix start automatically

Receive network on this workstation VM.

A moment later receive an error from whonixcheck on sys-whonix that it did not connect.

### Expected behavior:

If whonix is not connected with Tor then the VPN and any VMs connected to the VPN should not get network.

### Actual behavior:

The connected VMs do get network.

### General notes:

Can you recommend some way to check connectivity step by step?  The VPN VM does not have network on it's command line because it is a VPN VM.

---

**Comment by straussmaus** [comment] 2019-02-27 04:01
As I encounter this more I am starting to think that one possibility is intermittent network.  So the reason whonixcheck fails is because *by that time* the network is down and by the time I switch back it is back up.  I am not certain this is true.  It is only one possibility.  Really this Issue is solved by providing a method to disable tor and test for passthrough connectivity.

**Comment by tasket** [comment] 2019-03-05 20:45
@straussmaus Whether or not intermittency is the issue, you should be able to use various tools like `iptables` and `wireshark` to see if vpn traffic is being routed over Tor. Just look at your vpn log for the connection ip address, and compare to the traffic you see downstream; they should not match and the downstream addresses you see can also be matched to what Tor reports in sys-whonix.

**Comment by straussmaus** [comment] 2019-03-23 07:35
@tasket I am happy to test more but can you explain in a little more detail?  For example you say "Just look at your vpn log for the connection ip address" but doesn't this mean look at the VPN server logs?  I do not own the server.  The VPN client logs won't help will they?  Actually I have to enable these bc the default config from provider does not have logging.  But I can do that.

**Comment by adrelanos** [comment] 2019-08-30 09:56
> test for passthrough connectivity.

Not sure this is what you were asking for... To connect to clearnet from Whonix-Gateway (`sys-whonix`) is possible. See:

https://www.whonix.org/wiki/Dev/Test#Curl_Clearnet_Connectivity_Test_from_Whonix-Gateway

> Really this Issue is solved by providing a method to disable tor

Again not sure what you are asking for but `How to UnWhonix ™ - restore clearnet networking` is documented here:
https://www.whonix.org/wiki/Dev/Test#How_to_UnWhonix_.E2.84.A2_-_restore_clearnet_networking

----

As for leak testing, see:

* https://www.whonix.org/wiki/Corridor
* https://github.com/rustybird/corridor
* https://www.whonix.org/wiki/Dev/Leak_Tests

**Comment by straussmaus** [comment] 2019-11-10 00:21
@adrelanos 

What I'm asking for is that any traffic routed through sys-whonix should not go through unless it's going through Tor!  Otherwise all security is lost and a very dangerous situation (with no warnings) is possible!

**Comment by straussmaus** [comment] 2019-11-10 00:25
@adrelanos You understand those leak tests you linked to are not useful in this situation right?

**Comment by adrelanos** [comment] 2019-11-10 06:42
> What I'm asking for is that any traffic routed through sys-whonix should not go through unless it's going through Tor.

This is the case. To check that, these leak tests can be helpful. Among other possible tests anyone could think off. Nobody has demonstrated a way in which any VM behind sys-whonix could figure out its own, external, internet service provider assigned IP address. [1]

If that was the case, the issue would be server enough and then there would be no need to mix the subject with any VPN stuff.

> You understand those leak tests you linked to are not useful in this situation right?

The corridor leak test would catch any clearnet leak. That is because traffic first passes through sys-whonix. Next it passes through corridor. Eventually it passes through another VM (probably sys-firewall/sys-net).

----

[1] Well, that is without compromising sys-whonix by disabling its firewall and enabling IP forwarding and whatnot to morph it into a clearnet proxyvm.

**Comment by straussmaus** [comment] 2019-11-17 06:54
@adrelanos 

> This is the case. To check that, these leak tests can be helpful.

Good and my tests made me think this is true but it's good to hear from you.

So the real problem is the indicators are bad.  I can connect to a Qube that gets net through a NetVM that gets net through sys-whonix.  I am browsing a web page in this Qube even though whonixcheck in sys-whonix says Tor is not connected.  Panic ensues.

Because of this I think the Issue must stay open.  You can say it is working, but messaging must reflect the true state of things right?

**Comment by adrelanos** [comment] 2019-11-17 11:43
Messages by whonixcheck are only valid at the time of the notification. An improved version where this isn't the case is not on the horizon.

Please post any notification messages you are seeing and find confusing. Then perhaps suggest a better wording.

**Comment by straussmaus** [comment] 2020-01-12 10:12
@adrelanos 

> Please post any notification messages you are seeing and find confusing. Then perhaps suggest a better wording.

If I am remembering, there was no error message.

**Comment by adrelanos** [comment] 2020-01-12 10:57
I don't think this ticket is actionable at this time. If I understand this right, it boils down to a confusing error message which can no longer be provided. I suggest to close this ticket until a better bug description can be provided.

> A moment later receive an error from whonixcheck on sys-whonix that it did not connect.

"did not connect" does not imply "will allow connections over clearnet".

Please be more specific and post complete error messages. A self-made summary is easily misunderstood.

After clearing up some misconceptions here, if this is still an open issue, please try to reproduce this and comment with an updated bug report using the [usual template](https://github.com/QubesOS/qubes-issues/issues/new?assignees=&labels=P%3A+default%2C+T%3A+bug&template=bug-report.md&title=).

**Comment by andrewdavidwong** [comment] 2020-01-13 10:59
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-01-13 10:59 UTC
Labels: C: Whonix, P: default, T: bug
