### ISSUE TITLE
Persian language special characters won't be transferred in Qubes copy / paste

### ISSUE THREAD

**Issue by Khoramyar** [QubesOS/qubes-issues#5914] opened 2020-06-29 11:56 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Copy / paste between Qubes

**Brief summary**
5 Persian language special characters ( ک ) ( گ ) ( چ ) ( پ ) ( ژ )  won't be transferred using Qubes copy / paste between Qubes.

**To Reproduce**
_Steps to reproduce the behavior:_

_1. Copy a Persian language text containing any 4 special characters of  ( ک ) ( گ ) ( چ ) ( پ ) ( ژ )  and paste it in another Qube. non of these characters gets transferred to the target Qube.

_2. For instance, copy and paste these sample words: ( کلمه - گل - پارسی - ژاله - گچبری - چراغ ) and you get ( لمه - ل - ارسی - اله - بری - راغ )

_3. It happens between all VMs, template doesn't make a difference, if it's Fedora, Debian, etc.

**Expected behavior**

_A clear and concise description of what you expected to happen._

The exact text should be transferred to the other Qube.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

These characters wont be transferred using Qubes copy / past between Qubes: ( ک ) ( گ ) ( چ ) ( پ ) ( ژ ) 

**Additional context**
_Add any other context about the problem here._

This should also effect Arabic, as one of these characters are shared with Arabic language: ( ک )

**Comment by iamahuman** [comment] 2020-06-30 01:37
After pasting (Ctrl-Shift-V), the following method works:

 - `xclip -sel clip -o -target STRING`

The following methods don't work (the characters disappear):

 - `xclip -sel clip -o -target UTF8_STRING`
 - `xclip -sel clip -o -target COMPOUND_TEXT`
 - `xclip -sel clip -o`
 - `xsel -bo`
 - Pasting into gedit
 - Pasting into Firefox

**Comment by iamahuman** [comment] 2020-06-30 12:13
If anything, this issue is strictly the responsibility of Qubes GUI Agent. The likely relevant part:

https://github.com/QubesOS/qubes-gui-agent-linux/blob/9a2dcb0d5361e6f15c96478d5f0f2786e03a29b6/gui-agent/vmside.c#L1019-L1073

**Comment by iamahuman** [comment] 2020-06-30 13:10
We shall ditch Xlib locale functions and stick to [INCR](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#incr_properties) like what xclip does. Should probably also solve #5781.

**Comment by iamahuman** [comment] 2020-12-05 23:10
Fixed by  QubesOS/qubes-gui-agent-linux#117 (related issue: #2845)

---

https://github.com/QubesOS/qubes-issues/issues/2845#issuecomment-739111587:

> **Automated announcement from [builder-github](https://github.com/QubesOS/qubes-builder-github)**
> 
> The package `qubes-gui-agent_4.0.32-1` has been pushed to the `r4.0` testing repository for the Debian template.
> To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `buster-testing` (or appropriate equivalent for your template version), then use the standard update command:
> 
> ```
> sudo apt-get update && sudo apt-get dist-upgrade
> ```
> 
> [Changes included in this update](https://github.com/QubesOS/qubes-gui-agent-linux/compare/23b453badbb731de486b3e4364ae52d5917e9fa6...8317c6cd54d4a5fa22f1e2ea37c5048da45bb092)

---

https://github.com/QubesOS/qubes-issues/issues/2845#issuecomment-739111844:

> **Automated announcement from [builder-github](https://github.com/QubesOS/qubes-builder-github)**
> 
> The package `gui-agent-linux` has been pushed to the `r4.0` testing repository for the CentOS `centos8` template.
> To test this update, please install it with the following command:
> 
> ```
> sudo yum update --enablerepo=qubes-vm-r4.0-current-testing
> ```
> 
> [Changes included in this update](https://github.com/QubesOS/qubes-gui-agent-linux/compare/23b453badbb731de486b3e4364ae52d5917e9fa6...8317c6cd54d4a5fa22f1e2ea37c5048da45bb092)

---

https://github.com/QubesOS/qubes-issues/issues/2845#issuecomment-739112311:

> **Automated announcement from [builder-github](https://github.com/QubesOS/qubes-builder-github)**
> 
> The component `gui-agent-linux` (including package `pulseaudio-qubes-4.0.32-1.fc32`) has been pushed to the `r4.0` testing repository for the Fedora template.
> To test this update, please install it with the following command:
> 
> ```
> sudo yum update --enablerepo=qubes-vm-r4.0-current-testing
> ```
> 
> [Changes included in this update](https://github.com/QubesOS/qubes-gui-agent-linux/compare/23b453badbb731de486b3e4364ae52d5917e9fa6...8317c6cd54d4a5fa22f1e2ea37c5048da45bb092)

**Comment by andrewdavidwong** [comment] 2020-12-06 21:02
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed** 2020-12-06 21:02 UTC
Labels: C: gui-virtualization, P: default, T: bug, localization, needs-diagnosis, ux
