### ISSUE TITLE
VPN over Tor via Proxy-VM will not connect

### ISSUE THREAD

**Issue by rudolfocode** [QubesOS/qubes-issues#7261] opened 2022-02-10 15:24 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1, all packages up to date.

### Brief summary
created proxy-VM using this [guide](https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/vpn.md) the vpn works fine without tor. However after selecting sys-whonix as its netvm, link is up notification displayed as normal, but openvpn shows "attempting to establish TCP connection with [AF_inet] (ip address removed) :443 [nonblock]" and then eventually times out.

ip neigh shows
ip address removed dev eth   FAILED
10.137.0.11 dev eth0 lladdr fe:ff:ff:ff:ff:ff STALE

### Steps to reproduce
use above guide to set up proxy VM as VPN gateway configured to use TCP and port 443, set netvm for PROXY-VM gateway to sys-whonix and try to connect to anything

### Expected behavior
VPN over TOR connection

### Actual behavior
link is up notification displayed as normal, but openvpn shows "attempting to establish TCP connection with [AF_inet] (removed ip address) :443 [nonblock]" and then eventually times out.

ip neigh shows
(ip address removed) dev eth   FAILED
10.137.0.11 dev eth0 lladdr fe:ff:ff:ff:ff:ff STALE

**Comment by adrelanos** [comment] 2022-02-10 19:38
The VPN provider might be blocking connections coming from the Tor network? Try a different VPN provider?

Otherwise this could be difficult to resolve. [Generic Bug Reproduction](https://www.whonix.org/wiki/Reporting_Bugs#Generic_Bug_Reproduction) might be required.

See also:
https://www.whonix.org/wiki/Tunnels/Introduction

Quite likely I won't be able to help any further than this.

**Comment by rudolfocode** [comment] 2022-02-10 20:22
Already tried a different provider, same result. I also don't seem to be the only one with this issue, see [here](https://forum.qubes-os.org/t/user-tor-vpn-internet-4-1-broken/6900/7)

I'm certainly not adversed to research but I think I have gone as far as I can after reading and rereading the documentation for qubes and whonix, reading qubes forum and bringing it up on said forum.  I even dug up what I think is your response to a hacky fix for this issue, on qubes-forum from almost 3 months ago 

> Don’t use IP forwarding inside Whonix-Gateway. It’s a milestone that IP forwarding isn’t required and immensely reduces the risk of IP leaks. Elaborated here: [Security Overview](https://www.whonix.org/wiki/Dev/Technical_Introduction#Security_Overview), [With more technical terms ](https://www.whonix.org/wiki/Dev/Technical_Introduction#With_more_technical_terms).

[source](https://forum.qubes-os.org/t/user-tor-vpn-internet-4-1-broken/6900/8?u=learningqubes)

This seems to be specifically connected to Qubes 4.1 somehow. Although I'm new to qubes and it's unusual network topology, I'm reasonably comptent with linux and the CLI, do you or anyone else @marmarek ? have any suggestions of where to start so we can begin diagnosing this?

Thank you for your help so far

**Comment by DemiMarie** [comment] 2022-02-10 23:34
@rudolfocode does your VPN use TCP or UDP?  Last I checked Tor can only handle TCP traffic.  Most VPNs use UDP by default because it provides superior performance.

**Comment by rudolfocode** [comment] 2022-02-10 23:43
It's configured for TCP port 443, I've followed all the guides to the the letter, I honestly don't think its a flub on my part, others are having the same issue too.

**Comment by andrewdavidwong** [comment] 2022-02-11 03:20
Wait, is this a duplicate of #7123?

**Comment by adrelanos** [comment] 2022-02-11 10:03
> 4.1, all packages up to date.

How do you know that?

* https://github.com/QubesOS/qubes-issues/issues/7254

Did you check package versions as per https://github.com/QubesOS/qubes-issues/issues/7123#issuecomment-1033096257?

**Comment by rudolfocode** [comment] 2022-02-11 14:24
@andrewdavidwong I don't think so, that issue was apparently fixed? Also on closer inspection the result of ip neigh is different for me and [workaround](https://github.com/QubesOS/qubes-issues/issues/7123#issue-1081148021) mentioned by @unknown-ter also does not work, consequently this must be a different but perhaps somehow related bug.

@adrelanos I once again reinstalled the latest Qubes 4.1 yesterday and did recieve updates and installed them fully then rebooted multiple times checking for further updates by “Enable updates for qubes without known available updates,” which returned nothing.

running rpm -q qubes-core-agent in fedora 34 returns:

 qubes-core-agent-4.1.31-1.fc34.x86_64

running dpkg -l qubes-core-agent in debian 11 returns:

  Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version                      Architecture   Description
+++-==========-=============-========-==============-===================
ii  qubes-core-agent    4.1.31-1+deb11u1    amd64          qubes core agent

and then is repeated again verbatim underneath

Note: After booting my machine today I randomly had updates available for fedora 34 and debian 11 which I installed but issue still occurs even after making fresh proxy-vm (which connects fine outside Tor).

**Comment by crat0z** [comment] 2022-02-13 19:46
Hey, just decided to try this out. 
![2022-02-13_14-30](https://user-images.githubusercontent.com/11581854/153771643-a327fa57-583d-497f-92ae-7a2a980b89ef.png)

![2022-02-13_14-27](https://user-images.githubusercontent.com/11581854/153771648-cb92dae4-ef25-4738-80c4-d7c24858c4ae.png)

core-agent is `qubes-core-agent/unknown,unknown,now 4.1.31-1+deb11u1 amd64 [installed,automatic]` in both sys-whonix and sys-tor-vpn, so it indeed seems to be not working as expected. Quite a strange situation. Does it really have to do with proxy ARP or is it something Qubes does?

**Comment by rudolfocode** [comment] 2022-02-13 21:09
@crat0z Nice work, thanks for reproducing the issue and your efforts troubleshooting more comprehensively than I'd be able to.

I hope someone can get to the bottom of it, as this is functionality I need and the reason I built a machine for specifically for heads.

**Comment by crat0z** [comment] 2022-02-13 22:00
I'm not familiar with the Linux source code at all, but perhaps [this](https://github.com/torvalds/linux/blob/754e0b0e35608ed5206d6a67a791563c631cec07/net/ipv4/arp.c#L838) is why?

**Comment by crat0z** [comment] 2022-02-14 00:00
If you are just using openvpn configs like `openvpn --config config.ovpn` etc, you can instead do `openvpn --socks-proxy $(qubesdb-read /qubes-gateway) 9050 --config config.ovpn`. However, after you close the connection, openvpn will leave your routing table in a weird state, which can be fixed with `sudo ip route add $(qubesdb-read /qubes-gateway) dev eth0 scope host onlink`. Some commercial VPN services only offer apps though, in which case maybe you could use proxychains. I'm sure some have SOCKS support in apps too though

**Comment by rudolfocode** [comment] 2022-02-14 09:40
@crat0z Once again I honestly and wholeheartedly appreciate you effort, but I'm really not at a stage where I can deep dive the linux source code. As for your other solutions, I get the gist and I'm not adversed to research, so I'm sure I could implement what you have mentioned given enough time but I don't really want to risk misconfiguring something and actually worsening my security, which I'm sure is easy to do with a custom option. 

I'm just completely at a loss as for why this functionality 'just worked' in Qubes 4, (sources [1](https://forum.qubes-os.org/t/qubes-vpn-support-error-cannot-resolve-host-address/5869/11?u=learningqubes) [2](https://forum.qubes-os.org/t/user-tor-vpn-internet-4-1-broken/6900?u=learningqubes) [3](https://forum.qubes-os.org/t/networking-broken-in-4-1-default-templates/7092?u=learningqubes) and is now mysteriously lost in 4.1.

Source 3 above has ludicrously had to; 

> copy TemplateVM’s over from Qubes 4.0.

-     Hop on Qubes 4.0, download a fresh TemplateVM of Fedora 33, 34, Debian 10, 11.

-     Run all the standard updates on that template.

-     Make a backup of it to a USB or wherever.

-     Import them into Qubes 4.1

-     Can run standard updates once again if you wish.

-     Set those restored VM’s as your primary networking VM’s for all your VPN’s or other services which you are having network      issues - and voila, issues resolved.

I mean come on, updated software is not supposed to lose functionality from a previous version unless by intention right? 

I know everyones busy dealing with a 100K things I couldn't even begin to entertain but this is pretty galling considering I just spent six months researching and building a machine prepping with heads to run qubes in this config only for it to lose that functionality mysteriously with the next iteration of the OS.

I don't mean to sound rude and if I come accross that way I apologise, I honestly have the deepest respect for the Qubes Developers and their clear committment to this awesome project.

**Comment by ew0k** [comment] 2022-03-30 06:05
I am experiencing the same issue fresh 4.1 install latest updates - and yes i verified latest version qubes core agent

the arp workaround fixes it

**Comment by marmarek** [comment] 2022-03-30 15:35
What the routing table looks like in the in the not working proxy vm? Can you paste `ip r` output?

**Comment by Anondoe** [comment] 2022-04-06 18:15
Greetings Friends, I've been been reporting this same issue and trying to diagnose it as best I can myself until I just recently was pointed to this Qubes Issue by a friend on the forums here:
https://forum.qubes-os.org/t/networking-broken-in-4-1-default-templates/7092

The ARP command that has been mentioned in this issue does indeed also temporarily fix the VPN communications if used inside the ProxyVM that the VPN is running in, however, it doesn't fix *other* networking issues that are related to this entire problem. Namely, direct inter-qube communication via `socat`.

If one of you could suggest a different ARP command that might fix that for me I will try it and report back here. Full details are in the Qubes thread linked above, there's A LOT of info in that thread, you can skip most of it and just check out the last 3 posts.

In particular the most recent post (#10) that I created today which talks about inter-qube communication and not being able to use a Trezor hardware device in Qubes, which works perfectly fine when using 4.0 based templates.

In post (#6) I also included a few text files which lists differences in packages between 4.0 & 4.1 templates.

Hopefully some of this info is useful in troubleshooting this problem. Let me know if there's any further suggestions or things you'd like me to try (including any arp commands for the socat)

**Comment by crat0z** [comment] 2022-04-18 02:42
Here is before connecting to VPN:
```
user@sys-tor-vpn:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:5e:6c:00 brd ff:ff:ff:ff:ff:ff
    inet 10.137.0.56/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd09:24ef:4179::a89:38/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe5e:6c00/64 scope link 
       valid_lft forever preferred_lft forever
```
```
user@sys-tor-vpn:~$ ip r
default via 10.137.0.6 dev eth0 onlink 
10.137.0.6 dev eth0 scope host onlink
```
```
user@sys-tor-vpn:~$ ip neigh
10.137.0.6 dev eth0 lladdr fe:ff:ff:ff:ff:ff REACHABLE
```
Here is after, with `net.ipv4.ip_forward=0` in sys-whonix:
```
user@sys-tor-vpn:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:5e:6c:00 brd ff:ff:ff:ff:ff:ff
    inet 10.137.0.56/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd09:24ef:4179::a89:38/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe5e:6c00/64 scope link 
       valid_lft forever preferred_lft forever
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.240.22.225 peer 10.240.22.226/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::68a9:66d8:bffc:f873/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```
```
user@sys-tor-vpn:~$ ip r
0.0.0.0/1 via 10.240.22.226 dev tun0 
default via 10.137.0.6 dev eth0 onlink 
10.137.0.6 dev eth0 scope host onlink 
10.240.22.226 dev tun0 proto kernel scope link src 10.240.22.225 
128.0.0.0/1 via 10.240.22.226 dev tun0 
219.100.37.113 via 10.137.0.6 dev eth0 
```
```
user@sys-tor-vpn:~$ ip neigh
219.100.37.113 dev eth0  INCOMPLETE
10.137.0.6 dev eth0 lladdr fe:ff:ff:ff:ff:ff REACHABLE
```
and with `net.ipv4.ip_forward=1` in sys-whonix, which "fixes" the issue
```
user@sys-tor-vpn:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:5e:6c:00 brd ff:ff:ff:ff:ff:ff
    inet 10.137.0.56/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd09:24ef:4179::a89:38/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe5e:6c00/64 scope link 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.240.35.25 peer 10.240.35.26/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::a5f8:70c9:2843:8ba6/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```
```
user@sys-tor-vpn:~$ ip r
0.0.0.0/1 via 10.240.35.26 dev tun0 
default via 10.137.0.6 dev eth0 onlink 
10.137.0.6 dev eth0 scope host onlink 
10.240.35.26 dev tun0 proto kernel scope link src 10.240.35.25 
128.0.0.0/1 via 10.240.35.26 dev tun0 
219.100.37.113 via 10.137.0.6 dev eth0 
```
```
user@sys-tor-vpn:~$ ip neigh
219.100.37.113 dev eth0 lladdr fe:ff:ff:ff:ff:ff REACHABLE
10.137.0.6 dev eth0 lladdr fe:ff:ff:ff:ff:ff REACHABLE
```

**Comment by DemiMarie** [comment] 2022-04-18 12:50
@marmarek @fepitre is there any chance that we can fix these problems once and for all by switching to point-to-point inter-VM links and/or moving ARP and NDP handling to userspace?  Yes, this breaks certain advanced configurations (such as bridging), so it would need to be optional.  However, it _fixes_ other problems (such as this one) for good.
.
@crat0z I think I see the problem: the last route (`219.100.37.113 via 10.137.0.6 dev eth0`) might need to be an `onlink` route.

**Comment by crat0z** [comment] 2022-04-18 17:52
Yes, that works. As far as I can tell, openvpn does not check for onlink and there is no way to specify it either. However, if you are using openvpn from the command line, you can edit your config file and add something like this:
```
route-up '/rw/config/fix-route.sh'
```
Create a file at `/rw/config/fix-route.sh` with
```
#!/bin/sh

/sbin/ip route change $trusted_ip via $(qubesdb-read /qubes-gateway) dev eth0 onlink
```
and make the script executable with `chmod +x /rw/config/fix-route.sh`. This will replace the route with identical route plus `onlink` set.

**Comment by tetrahedras** [comment] 2022-06-04 20:10
Here's the script I added to my qtunnel.conf (Qubes-tunnel) or vpn-client.conf (Qubes-vpn-support). It's assumed to be in /rw/config/qtunnel/. If using Qubes-vpn-support, it should be in /rw/config/vpn/ and the route-up entry should be changed accordingly.

```
# cat fix-arp.sh 
#!/bin/bash

# Should be called from openvpn.conf with
#	route-up '/rw/config/qtunnel/fix-arp.sh'

sleep 10
IP_NEIGH=`ip neigh`
IP_ADDR=`ip neigh | grep INCOMPLETE | cut -d " " -f 1`
echo $IP_ADDR
if [ "$IP_ADDR" = "" ];
then
	echo "No incomplete ARP entry in $IP_NEIGH"
	exit 1
fi
arp -s ${IP_ADDR} -i eth0 fe:ff:ff:ff:ff:ff
```

**Comment by Enteee** [comment] 2022-07-05 21:19
As @andrewdavidwong already stated I also think this might be a duplicate of #7123 .

**Comment by adrelanos** [comment] 2022-09-11 14:43
Can someone confirm or deny that this has been fixed?

**Comment by adrelanos** [comment] 2022-09-13 11:46
If this is a duplicate (which I am not sure about) then there's a PR that fixed it but packages might be unavailable for some reason.

@adrelanos
> Seems like fix by @DemiMarie (thanks!) [QubesOS/qubes-core-agent-linux#384](https://github.com/QubesOS/qubes-core-agent-linux/pull/384) didn't land in any packages yet?
> 
> I am wondering why there aren't any notifications by Qubes bot that packages were built and upload to Qubes repository?

Do you think this is a duplciate? @DemiMarie

**Comment by DemiMarie** [comment] 2022-09-14 10:44
@adrelanos Yup, this is a duplicate.  Closing.

**Comment by andrewdavidwong** [comment] 2022-09-14 11:17
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-09-14 11:17 UTC
Labels: T: bug, R: duplicate, P: default, diagnosed, C: networking
