### ISSUE TITLE
installing qemu in fedora-29 template clone

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#4805] opened 2019-02-08 22:52 UTC
### Qubes OS version:
R4.0

### Affected component(s):
qemu, xen-qubes-vm, xen-libs

Installing qemu depends on xen-qubes-vm-2001:4.8.4-7.fc29.x86_64 which requires xen-libs = 2001:4.8.4-7.fc29 while xen-libs-4.11.0-7.fc29.x86_64 is installed.

Forcing `sudo dnf --allowerase qemu` downgrades to an unbootable xen-qubes-vm-2001:4.8.4-7.fc29.x86_64 based template.

---

### Steps to reproduce the behavior:
```
sudo dnf install qemu
sudo dnf install --allowerase qemu
```

### Expected behavior:
install a functioning qemu vm usable for testing

### Actual behavior:
forcing `--allowerase` downgrades to  unbootable qube based on this template. Template doesn't boot either.

### General notes:
```
  - package qemu-2:3.0.0-3.fc29.x86_64 requires qemu-user = 2:3.0.0-3.fc29, but none of the providers can be installed
  - package qemu-user-2:3.0.0-3.fc29.x86_64 requires qemu-common = 2:3.0.0-3.fc29, but none of the providers can be installed
  - package qemu-common-2:3.0.0-3.fc29.x86_64 requires libxenctrl.so.4.11()(64bit), but none of the providers can be installed
  - package qemu-common-2:3.0.0-3.fc29.x86_64 requires libxenguest.so.4.11()(64bit), but none of the providers can be installed
  - package qemu-common-2:3.0.0-3.fc29.x86_64 requires libxentoolcore.so.1()(64bit), but none of the providers can be installed
  - package qemu-common-2:3.0.0-3.fc29.x86_64 requires libxendevicemodel.so.1()(64bit), but none of the providers can be installed
  - package xen-qubes-vm-2001:4.8.4-7.fc29.x86_64 requires xen-libs = 2001:4.8.4-7.fc29, but none of the providers can be installed
  - cannot install both xen-libs-2001:4.8.4-7.fc29.x86_64 and xen-libs-4.11.1-1.fc29.x86_64
  - cannot install both xen-libs-2001:4.8.4-7.fc29.x86_64 and xen-libs-4.11.0-7.fc29.x86_64
  - package xen-qubes-vm-2001:4.8.4-8.fc29.x86_64 requires xen-libs = 2001:4.8.4-8.fc29, but none of the providers can be installed
  - cannot install both xen-libs-2001:4.8.4-8.fc29.x86_64 and xen-libs-4.11.1-1.fc29.x86_64
  - cannot install both xen-libs-2001:4.8.4-8.fc29.x86_64 and xen-libs-4.11.0-7.fc29.x86_64
  - cannot install both xen-libs-4.11.1-1.fc29.x86_64 and xen-libs-2001:4.8.4-8.fc29.x86_64
  - cannot install both xen-libs-4.11.0-7.fc29.x86_64 and xen-libs-2001:4.8.4-8.fc29.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
```

---

**Comment by marmarek** [comment] 2019-02-09 00:09
This is duplicate of #3945 . Will be fixed in Qubes R4.1, unfortunately no easy way to safely apply the fix for R4.0 (requires recompiling all the packages with Fedora's xen-libs and not screwing any dependency in the process).

**Closed by marmarek** 2019-02-09 00:09 UTC
