### ISSUE TITLE
Imported VMs to 4.0 have corresponding "disp" VMx

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3846] opened 2018-04-23 08:23 UTC
### Qubes OS version:
4.0

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

Import a VM from 3.2 to 4.0.

### Expected behavior:

The VM and only the VM will arrive in Qubes 4.0

### Actual behavior:

The VM arrives.  So does another VM called "disp-<VM-name>".  

### General notes:

Why?  Can I delete this?  Why was it created in the first place?

**Comment by marmarek** [comment] 2019-02-18 22:46
This is not a duplicate of #3273. That one was about error while removing VMs, this one is about creating disp-* VMs in the first place.

Those `disp-*` VMs are created intentionally, to preserve configuration semantic of R3.2. In R3.2 disposable VM inherited netvm from the calling VM (or its `dispvm_netvm` property). In R4.0 this has changed and no settings are directly inherited. Instead, it's possible to create separate DVM templates for different set of settings. This is what backup restore tool does.

More details in proposed doc change: https://github.com/QubesOS/qubes-doc/pull/793

**Closed** 2019-02-19 06:05 UTC
Labels: C: doc, task
