### ISSUE TITLE
After installation of windows tools, Windows HVM (and HVM-template)'s window vanishes after booting

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#1550] opened 2015-12-27 11:40 UTC
Qubes OS 3.1RC1
Windows 7 Pro
qubes-windows-tools.x86_64 3.0.4-1
on a Lenovo W540 (HiDPI)

```
qvm-create Windows-7-Template  --hvm-template --label blue
qvm-start Windows-7-Template --cdrom=/Storage/Boot-Media/Windows7.iso
    --> first round of setup
qvm-start Windows-7-Template
    --> second round
qvm-start Windows-7-Template
    --> third round, account "admin" (but not "user"!) created
qvm-start Windows-7-Template --install-windows-tools
    --> of course had to redo it because I'm always forgetting the code signature
qvm-start Windows-7-Template --install-windows-tools
    --> install the tools
qvm-start Windows-7-Template
```

After the initial Windows boot screen the window just vanishes (as in "The Hunting of the Snark" "softly and suddenly vanish away and never be met with, again").
The logs are mostly empty, only `guid.Windows-7-Template.log` contains

```
Icon size: 128x128
Created 0x5600003(0x0) parent 0x0(0xffffffff) ovr=0 x/y 0/0 w/h 2880/1620
```

qvm-prefs isn't like I expect it to after installation of the tools:

```
[user@dom0 Windows-7-Template]$ qvm-prefs Windows-7-Template
name               : Windows-7-Template
label              : blue
type               : TemplateHVM
netvm              : sys-firewall
dispvm_netvm       : sys-firewall (default)
updateable         : True
autostart          : False
installed_by_rpm   : False
include_in_backups : True
last_backup        : None
dir                : /var/lib/qubes/vm-templates/Windows-7-Template
config             : /var/lib/qubes/vm-templates/Windows-7-Template/Windows-7-Template.conf
pcidevs            : []
pci_strictreset    : True
root_img           : /var/lib/qubes/vm-templates/Windows-7-Template/root.img
root_cow_img       : <bound method QubesTemplateHVm.rootcow_img of <QubesTemplateHVm at 0x26a85d0 qid=15 name='Windows-7-Template'>>
root_volatile_img  : /var/lib/qubes/vm-templates/Windows-7-Template/volatile.img
private_img        : /var/lib/qubes/vm-templates/Windows-7-Template/private.img
vcpus              : 4
memory             : 4096
maxmem             : 4096
MAC                : 00:16:3E:5E:6C:0F (auto)
debug              : off
default_user       : user
qrexec_installed   : False
qrexec_timeout     : 60
guiagent_installed : False
seamless_gui_mode  : False
drive              : None
timezone           : localtime
internal           : False
```

Any ideas?

Achim

**Comment by nrgaway** [comment] 2015-12-27 13:12
Did you try turning on debug mode?  I always do so I can see what's going on.  After installing tools, the system will prep to move user directory and requires two restarts I think.

**Comment by noseshimself** [comment] 2015-12-27 20:41
I was lacking the patience right now; the machine takes about 10 seconds to boot the point where it is turning off the boot logo display and the window is vanishing; turning on debugging is giving me full CPU load for 60 minutes (now; I have to get a train in an hour and will shut down if nothing is happening) and the same Windows boot logo without any indications that anything might change.

**Comment by axon-qubes** [comment] 2016-04-20 21:22
I can confirm this on Qubes R3.1. Steps I took to reproduce:

1. Installed Windows 7 x64 from original ISO as HVM template.
2. Restarted the HVM template. Confirmed that that Windows started up correctly and apps were usable.
3. Installed `qubes-windows-tools.x86_64 0:3.0.4-1` according to documentation.
4. After installing from the virtual disc inside the Windows HVM template, attempted to restart the VM to continue the rest of the installation procedure. However, on restarting, the VM no longer showed any GUI (possibly related to #1896).
5. Shut it down, then tried starting it again with `--debug`. It hung on the Windows startup screen.
6. (Tried this multiple times with the same result.)

Result: Windows HVM template will not fully start after Qubes Windows Tools have been installed.

**Comment by axon-qubes** [comment] 2016-04-20 21:27
@noseshimself: What was the resolution (total host screen resolution, not domU resolution) of the system on which you experienced this bug? If it was a "high" resolution, then I suspect that #1896 is actually a duplicate of this issue.

**Comment by axon-qubes** [comment] 2016-04-20 21:35
[Further testing](https://github.com/QubesOS/qubes-issues/issues/1896#issuecomment-212614062) reveals that the Windows VM is, in fact, starting (as evidenced by the interactivity of the passed-io shell), but that no GUI is visible (whether for individual apps or the whole desktop, seamless or otherwise) after the very early startup screen (which appears only when the VM is started with `--debug` and *appears* to freeze mid-startup).

**Comment by omeg** [comment] 2016-08-10 16:01
Most likely a case similar to #1896 which is now fixed.

**Closed by omeg** 2016-08-10 16:01 UTC
Labels: bug, C: windows tools, P: major
