### ISSUE TITLE
`man qrexec-client-vm` shows html

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7407] opened 2022-04-01 20:13 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
`man qrexec-client-vm` shows html

### Steps to reproduce
`man qrexec-client-vm`

### Expected behavior
manpage is shown.

### Actual behavior
garbled html output is shown.

**Comment by unman** [comment] 2022-08-24 15:38
Duplicate of #7041

**Comment by andrewdavidwong** [comment] 2022-08-25 01:05
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2022-08-25 01:05 UTC
Labels: T: bug, C: core, C: doc, P: default
