### ISSUE TITLE
Traffic flows through sys-whonix before whonixcheck passes

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6467] opened 2021-03-18 00:57 UTC
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**
sys-whonix

**Brief summary**
When sys-whonix starts, traffic can flow through it from attached Qube even before the lock icon has turned solid, and before whonixcheck passes

**How Reproducible**
100% but that is misleading.  This can happen 100% of the time.  But also, sometimes whonixcheck passes immediately so this isn't relevant.

**To Reproduce**

1. Start a Qube that uses sys-whonix.
2. Start traffic - VPN, web browsing, tor browser automatic updates, etc.
3. Notice that traffic flows, even if the lock icon is not solid for sys-whonix, and even if whonixcheck does not pass.

**Expected behavior**
Traffic should be restricted until Tor is considered ready, which is indicated by the lock icon being solid and whonixcheck passing (otherwise what is the purpose of the lock icon turning solid?)

**Actual behavior**
Traffic flows, but whonixcheck fails and the lock icon is not solid.

**Additional context**
It seems that whonixcheck is not passing due to swdate.

**Solutions you've tried**
It's not a user-solveable problem.  Either it is safe for traffic to flow before swdate is ready, in which case the lock icon should be solid even in that state.  Or the lock icon is correctly indicating "not ready" when it is not solid, in which case traffic should be restricted through sys-whonix until sys-whonix is ready.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None found.

**Comment by adrelanos** [comment] 2021-09-21 13:50
The implementation isn't finished. Duplicate of https://phabricator.whonix.org/T533.

**Comment by andrewdavidwong** [comment] 2021-09-22 00:58
Closing as "not our bug" (the Qubes OS Project does not develop or maintain the software that is causing this bug). If you believe this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

[FAQ: Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)

**Closed by andrewdavidwong** 2021-09-22 00:58 UTC
Labels: T: bug, C: Whonix, P: default, diagnosed

**Comment by straussmaus** [comment] 2021-10-15 02:18
I understand about upstream bugs.  But the bug/issue is not that whonix does not successfully complete whonixcheck, it is that traffic flows through the whonix qube before it is ready.

So maybe this is actually a feature request?  Such as:

Qubes should not default to allowing traffic through a NetVM with outstanding issues that are as big as https://phabricator.whonix.org/T533.

I can see an argument for allowing this as is, but do you see the argument that if the underlying VM is not verified by Qubes as OK, then maybe Qubes should not default to using it, particularly for the most private traffic (dispVMs)?

I'm saying maybe.  This is a design-philosophy issue at this point, so out of scope for me, but I will be happy to test or brainstorm if this moves anywhere.

**Comment by adrelanos** [comment] 2021-10-15 16:49
> I understand about upstream bugs. But the bug/issue is not that whonix does not successfully complete whonixcheck, it is that traffic flows through the whonix qube before it is ready.
> 
> So maybe this is actually a feature request? Such as:
> 
> Qubes should not default to allowing traffic through a NetVM with outstanding issues that are as big as https://phabricator.whonix.org/T533.

Yes, it's a feature request.

> I can see an argument for allowing this as is, but do you see the argument that if the underlying VM is not verified by Qubes as OK, then maybe Qubes should not default to using it, particularly for the most private traffic (dispVMs)?

It is OK but it's not perfect. There's no better solution available. Without this feature-in-progress, maybe you wouldn't know about the imperfection.

> I'm saying maybe. This is a design-philosophy issue at this point, so out of scope for me, but I will be happy to test or brainstorm if this moves anywhere.

https://www.whonix.org/wiki/Network_Time_Synchronization#Block_Networking_until_sdwdate_Finishes

**Comment by andrewdavidwong** [comment] 2021-10-16 20:59
> particularly for the most private traffic (dispVMs)?

It's a common misconception that disposables are supposed to be inherently more private than other qube types. That's not true unless they're Whonix disposables.

https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes
