### ISSUE TITLE
Submodule breaks page source links

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1357] opened 2015-10-25 03:54 UTC
I've created links to view and edit the source of every page using the "doc" layout. These links work beautifully for pages which reside in the primary `qubesos.github.io` repo, but they fail for all pages which reside in submodules (e.g., `qubes-doc`).

Current working examples:
- https://www.qubes-os.org/
- https://www.qubes-os.org/downloads/
- https://www.qubes-os.org/en/news/

Current broken examples:
- https://www.qubes-os.org/en/doc/
- https://www.qubes-os.org/en/doc/getting-started/
- https://www.qubes-os.org/en/doc/system-requirements/

(Look in the upper right-hand corner for the "Source" and "Edit" links.)

**Comment by axon-qubes** [comment] 2015-10-25 03:58
Options:

1. Create separate layouts for the pages in `qubesos.github.io` and the pages in submodules, and have the submodule layout use `page.relative_path` instead of `page.path`. But we'd still need a way to grab the correct `repository_url`.

2. Move the pages in `qubesos.github.io` to `qubes-doc`, and continue to use one layout (the "doc" layout) for everything, then make the other changes stated in 1.

**Comment by axon-qubes** [comment] 2015-10-25 04:37
Duplicate of #1307.

**Closed by axon-qubes** 2015-10-25 04:37 UTC
Labels: R: duplicate, C: website
