### ISSUE TITLE
Debian template doesn't have qubes-gpg-client-wrapper

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1149] opened 2015-08-26 16:38 UTC
Users are currently unable to set up splitGPG in the Debian 8 template. I feel like this should be functionality implemented prior to a template being accepted as a template. (Whonix template does have it.)

>  /usr/bin/qubes-gpg-client-wrapper

If it is in a different location then that needs to be addressed in the documentation.

**Comment by marmarek** [comment] 2015-09-02 00:56
Duplicate of #1140

**Closed by marmarek** 2015-09-02 00:56 UTC
