### ISSUE TITLE
attaching usb device to windows7 hvm fails

### ISSUE THREAD

**Issue by Luisames** [QubesOS/qubes-issues#3670] opened 2018-03-08 12:56 UTC
**Qubes OS version:**
- Qubes release 4.0 (R4.0-rc4)
- Kernel 4.14.18-1

**Affected component(s):** 
- Windows7 StandaloneVM

**Steps to reproduce the behavior:**
- I typed in dom0:
qvm-usb
      -> sys-usb:2-1      SanDisk_Ultra_4C530001281110110004
qvm-usb attach _windowsVM_ sys-usb:2-1

**Expected behavior:**
- usb device gets attached to windows7 hvm

**Actual behavior:**
- Error: Device attach failed

**General notes:**
- I also tried to attach the usb device to the windows7 hvm like this (but even this fails):
qvm-pci list sys-usb
        -> BACKEND:DEVID    dom0:00_14.0     
        -> DESCRIPTION:    USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller     
        -> USED BY:    sys-usb (no-strict-reset=true)
qvm-pci attach --persistent --option permissive=true --option no-strict-reset=true _windowsVM_ dom0:00_14.0

**Related issues:**
#3455

**Comment by andrewdavidwong** [comment] 2018-03-09 02:09
Duplicate of #1783

**Comment by andrewdavidwong** [comment] 2018-03-09 02:09
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-09 02:09 UTC
