### ISSUE TITLE
qui-devices does not update when VMs are created or destroyed

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4366] opened 2018-10-03 15:29 UTC
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

`qui-devices`

---

### Steps to reproduce the behavior:

Create and destroy VMs, especially DispVMs

### Expected behavior:

`qui-devices` updates its widget as domains are created or destroyed.

### Actual behavior:

`qui-devices` often does not do this.

### General notes:

---

**Comment by marmarek** [comment] 2018-10-03 15:46
What version do you have? Should be fixed with https://github.com/QubesOS/updates-status/issues/562

**Comment by DemiMarie** [comment] 2018-10-03 16:09
I get `qubes-desktop-linux-manager-4.0.10-1.fc25.noarch`

**Comment by DemiMarie** [comment] 2018-10-03 16:13
```
$ sudo qubes-dom0-update --enablerepo=qubes-dom0-security-testing --refresh
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Last metadata expiration check: 0:00:00 ago on Wed Oct  3 12:07:26 2018.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
Qubes OS Repository for Dom0                       34 MB/s |  35 kb    00:00
```

**Comment by DemiMarie** [comment] 2018-10-03 17:06
@marmarek

**Comment by marmarek** [comment] 2018-10-03 17:41
All the errors here are about devices widget, not domains (fix for that is already in master branch).
Just an idea - have you restarted qui-domains after installing the update (logout, system restart or such)? If not check if that helps - kill the `qui-domains` or `python3 -mqui.tray.domains` process, and start `qui-domains` again.

**Comment by DemiMarie** [comment] 2018-10-03 17:46
@marmarek Actually, my problem was the device widget.  My mention of the domains widget was a typo.

**Comment by marmarek** [comment] 2018-10-03 18:05
In that case, this is a duplicate of https://github.com/QubesOS/qubes-issues/issues/4289, the update will land in current-testing today.

**Closed** 2018-10-04 05:16 UTC
