### ISSUE TITLE
Whonix workstation can not reach whonix gateway. Gateway works.

### ISSUE THREAD

**Issue by damko** [QubesOS/qubes-issues#5349] opened 2019-09-27 12:57 UTC
**Qubes OS version**  R4.0
**Affected component(s) or functionality** whonix-workstation and/or whonix-gateway and/or dom0

**Brief summary**
After a dom0 upgrade my whonix workstation(s) can not reach anymore the gateway. I can't be 100% sure that the update is to be blamed but everything points in that direction so far. The gateway can connect to Tor and can ping out (8.8.8.8)

**To Reproduce**
No clue how to reproduce this.

**Expected behavior**
whonix-workstation should be able to connect to whonix-gateway and therefore to Tor network

**Additional context**

Both the whonix gw and ws 15 are updated to the latest version. 

I kept my old gw and ws 14 and they were both working until I moved to 15 a few weeks ago. I configured both my appVm (`sys-whonix` and `u-man-who`) to use version 14 templates. The behavior is exactly the same, the workstation can't reach the gateway. 
I also had another gateway AppVm and some other workstation AppVm which were all working until yesterday. They all have the same behavior.
_**It seems like dom0 is preventing the workstation to route through the gateway. Probably an rpc issue but I have no clue on how to diagnose this.**_

**dom0 update**
These are the packages (stable repo) involved in the update:

```
Transaction ID : 39
Begin time     : Thu Sep 26 16:32:41 2019
Begin rpmdb    : 1075:1647893eda5ead08d9d059d2ba1701bcc0a1ad7b
End time       :            16:37:28 2019 (287 seconds)
End rpmdb      : 1085:b2d829427f84eedd94ef55655ea19fa48845c0d3
User           :  <user>
Return-Code    : Success
Command Line   : --exclude=qubes-template-debian-9-minimal,qubes-template-whonix-gw-15,qubes-template-debian-10-minimal,qubes-template-whonix-ws,qubes-template-fedora-26,qubes-template-whonix-gw,qubes-template-whonix-ws-15,qubes-template-whonix-ws-14,qubes-template-whonix-gw-14,qubes-template-debian-9 upgrade
Transaction performed with:
    Installed     dnf-1.1.10-6.fc25.noarch   @anaconda/rawhide
    Installed     rpm-4.13.0.2-1.fc25.x86_64 @anaconda/rawhide
Packages Altered:
    Upgraded python3-qubesdb-4.0.10-1.fc25.x86_64              @qubes-dom0-cached
    Upgrade                  4.0.11-1.fc25.x86_64              @qubes-dom0-cached
    Upgraded qubes-db-4.0.10-1.fc25.x86_64                     @qubes-dom0-cached
    Upgrade           4.0.11-1.fc25.x86_64                     @qubes-dom0-cached
    Upgraded qubes-db-dom0-4.0.10-1.fc25.x86_64                @qubes-dom0-cached
    Upgrade                4.0.11-1.fc25.x86_64                @qubes-dom0-cached
    Upgraded qubes-db-libs-4.0.10-1.fc25.x86_64                @qubes-dom0-cached
    Upgrade                4.0.11-1.fc25.x86_64                @qubes-dom0-cached
    Upgraded qubes-manager-4.0.36-1.fc25.noarch                @qubes-dom0-cached
    Upgrade                4.0.39-1.fc25.noarch                @qubes-dom0-cached
    Erase    kernel-1000:4.14.67-1.pvops.qubes.x86_64          @qubes-dom0-cached
    Install  kernel-1000:4.19.71-1.pvops.qubes.x86_64          @qubes-dom0-cached
    Erase    kernel-qubes-vm-1000:4.14.67-1.pvops.qubes.x86_64 @qubes-dom0-cached
    Install  kernel-qubes-vm-1000:4.19.71-1.pvops.qubes.x86_64 @qubes-dom0-cached
Scriptlet output:
   1 please wait... ..................................................................................................................................................................................................................................................................................................................................................
   2 Generating grub configuration file ...
   3 Found theme: /boot/grub2/themes/system/theme.txt
   4 Found linux image: /boot/vmlinuz-4.19.71-1.pvops.qubes.x86_64
   5 Found linux image: /boot/vmlinuz-4.19.15-1.pvops.qubes.x86_64
   6 Found initrd image: /boot/initramfs-4.19.15-1.pvops.qubes.x86_64.img
   7 Found linux image: /boot/vmlinuz-4.14.74-1.pvops.qubes.x86_64
   8 Found initrd image: /boot/initramfs-4.14.74-1.pvops.qubes.x86_64.img
   9 Found linux image: /boot/vmlinuz-4.14.67-1.pvops.qubes.x86_64
  10 Found linux image: /boot/vmlinuz-4.19.71-1.pvops.qubes.x86_64
  11 Found linux image: /boot/vmlinuz-4.19.15-1.pvops.qubes.x86_64
  12 Found initrd image: /boot/initramfs-4.19.15-1.pvops.qubes.x86_64.img
  13 Found linux image: /boot/vmlinuz-4.14.74-1.pvops.qubes.x86_64
  14 Found initrd image: /boot/initramfs-4.14.74-1.pvops.qubes.x86_64.img
  15 Found linux image: /boot/vmlinuz-4.14.67-1.pvops.qubes.x86_64
  16 Found linux image: /boot/vmlinuz-4.19.71-1.pvops.qubes.x86_64
  17 Found linux image: /boot/vmlinuz-4.19.15-1.pvops.qubes.x86_64
  18 Found initrd image: /boot/initramfs-4.19.15-1.pvops.qubes.x86_64.img
  19 Found linux image: /boot/vmlinuz-4.14.74-1.pvops.qubes.x86_64
  20 Found initrd image: /boot/initramfs-4.14.74-1.pvops.qubes.x86_64.img
  21 Found linux image: /boot/vmlinuz-4.14.67-1.pvops.qubes.x86_64
  22 done
  23 Generating grub configuration file ...
  24 Found theme: /boot/grub2/themes/system/theme.txt
  25 Found linux image: /boot/vmlinuz-4.19.71-1.pvops.qubes.x86_64
  26 Found initrd image: /boot/initramfs-4.19.71-1.pvops.qubes.x86_64.img
  27 Found linux image: /boot/vmlinuz-4.19.15-1.pvops.qubes.x86_64
  28 Found initrd image: /boot/initramfs-4.19.15-1.pvops.qubes.x86_64.img
  29 Found linux image: /boot/vmlinuz-4.14.74-1.pvops.qubes.x86_64
  30 Found initrd image: /boot/initramfs-4.14.74-1.pvops.qubes.x86_64.img
  31 Found linux image: /boot/vmlinuz-4.19.71-1.pvops.qubes.x86_64
  32 Found initrd image: /boot/initramfs-4.19.71-1.pvops.qubes.x86_64.img
  33 Found linux image: /boot/vmlinuz-4.19.15-1.pvops.qubes.x86_64
  34 Found initrd image: /boot/initramfs-4.19.15-1.pvops.qubes.x86_64.img
  35 Found linux image: /boot/vmlinuz-4.14.74-1.pvops.qubes.x86_64
  36 Found initrd image: /boot/initramfs-4.14.74-1.pvops.qubes.x86_64.img
  37 Found linux image: /boot/vmlinuz-4.19.71-1.pvops.qubes.x86_64
  38 Found initrd image: /boot/initramfs-4.19.71-1.pvops.qubes.x86_64.img
  39 Found linux image: /boot/vmlinuz-4.19.15-1.pvops.qubes.x86_64
  40 Found initrd image: /boot/initramfs-4.19.15-1.pvops.qubes.x86_64.img
  41 Found linux image: /boot/vmlinuz-4.14.74-1.pvops.qubes.x86_64
  42 Found initrd image: /boot/initramfs-4.14.74-1.pvops.qubes.x86_64.img
  43 done
```

**dom0 /etc/qubes-rpc/policy/qubes.UpdatesProxy** 
```
## Note that policy parsing stops at the first match,
## so adding anything below "$anyvm $anyvm action" line will have no effect
## Please use a single # to start your custom comments

# Upgrade Whonix TemplateVMs through sys-whonix.
$tag:whonix-updatevm $default allow,target=sys-whonix

# Deny Whonix TemplateVMs using UpdatesProxy of any other VM.
$tag:whonix-updatevm $anyvm deny

# Upgrade all StandaloneVm tagged as standaloneVM through sys-net
$tag:standaloneVM $default allow,target=sys-net

# Deny StandaloneVMs tagged as standaloneVM using UpdatesProxy of any other VM.
$tag:standaloneVM $anyvm deny

# Default rule for all TemplateVMs - direct the connection to sys-net
$type:TemplateVM $default allow,target=sys-net
$type:TemplateVM $anyvm deny

$anyvm $anyvm deny


```
**whonix-ws whonixcheck output**
```
[INFO] [whonixcheck] u-man-who | Whonix-Workstation | whonix-ws-15 TemplateBased AppVM | Fri 27 Sep 12:10:34 UTC 2019
[ERROR] [whonixcheck] Tor Connection Result:
Tor's Control Port could not be reached!

Troubleshooting:
- Confirm that Whonix-Gateway is running.
- Run whonixcheck on Whonix-Gateway and confirm success.

- Rerun whonixcheck here in this Whonix-Workstation.

(Technical information:)
(tor_circuit_established_check_exit_code: 277)
(tor_bootstrap_timeout_type: )
(tor_bootstrap_status: )
(check_socks_port_open_test: 28)
(Tor Circuit: not established)
```

**qvm-prefs u-man-who** (whonix-workstation)
```
autostart             D  False
backup_timestamp      -  1566508100
debug                 D  False
default_dispvm        -  whonix-ws-15-dvm
default_user          D  user
gateway               D  
gateway6              D  
include_in_backups    D  True
installed_by_rpm      D  False
ip                    D  10.137.0.34
ip6                   D  fd09:24ef:4179::a89:22
kernel                D  4.19.74-1
kernelopts            D  nopat
klass                 D  AppVM
label                 -  orange
mac                   D  00:16:3e:5e:6c:00
management_dispvm     D  default-mgmt-dvm
maxmem                -  6000
memory                -  600
name                  -  u-man-who
netvm                 -  sys-whonix
provides_network      -  False
qid                   -  34
qrexec_timeout        D  60
shutdown_timeout      D  60
start_time            D  1569585999.11
stubdom_mem           U
stubdom_xid           D  -1
template              -  whonix-ws-15
template_for_dispvms  D  False
updateable            D  False
uuid                  -  0b15ef5a-4c90-4fd0-8a33-cf62111f0c13
vcpus                 D  2
virt_mode             D  pvh
visible_gateway       D  10.137.0.10
visible_gateway6      D  fd09:24ef:4179::a89:a
visible_ip            D  10.137.0.34
visible_ip6           D  fd09:24ef:4179::a89:22
visible_netmask       D  255.255.255.255
xid                   D  14
```
**sys-whonix whonixcheck output**
```
[INFO] [whonixcheck] sys-whonix | Whonix-Gateway | whonix-gw-15 TemplateBased ProxyVM | Fri 27 Sep 2019 12:17:35 PM UTC
[INFO] [whonixcheck] Connected to Tor.
[INFO] [whonixcheck] Whonix APT Repository: Enabled.
When the Whonix team releases BUSTER updates,
they will be AUTOMATICALLY installed (when you run apt-get dist-upgrade)
along with updated packages from the Debian team. Please
read https://www.whonix.org/wiki/Trust to understand the risk.
If you want to change this, use:
    sudo whonix_repository
[INFO] [whonixcheck] Debian Package Update Check: Checking for software updates via apt-get... ( Documentation: https://www.whonix.org/wiki/Update )
[INFO] [whonixcheck] Debian Package Update Check Result: No updates found via apt-get.
[INFO] [whonixcheck] Please donate!
   See: https://www.whonix.org/wiki/Donate
```

**qvm-prefs sys-whonix**
```
autostart             -  False
backup_timestamp      -  1566508100
debug                 D  False
default_dispvm        -  None
default_user          D  user
gateway               D  10.137.0.10
gateway6              D  fd09:24ef:4179::a89:a
include_in_backups    D  True
installed_by_rpm      D  False
ip                    D  10.137.0.10
ip6                   D  fd09:24ef:4179::a89:a
kernel                D  4.19.74-1
kernelopts            D  nopat
klass                 D  AppVM
label                 -  purple
mac                   D  00:16:3e:5e:6c:00
management_dispvm     D  default-mgmt-dvm
maxmem                -  2560
memory                -  256
name                  -  sys-whonix
netvm                 -  sys-net
provides_network      -  True
qid                   -  10
qrexec_timeout        D  60
shutdown_timeout      D  60
start_time            D  1569585989.26
stubdom_mem           U
stubdom_xid           D  -1
template              -  whonix-gw-15
template_for_dispvms  D  False
updateable            D  False
uuid                  -  cdc4cde4-243a-4daf-a5c5-876f51c0e240
vcpus                 D  2
virt_mode             D  pvh
visible_gateway       D  10.137.0.5
visible_gateway6      D  fd09:24ef:4179::a89:5
visible_ip            D  10.137.0.10
visible_ip6           D  fd09:24ef:4179::a89:a
visible_netmask       D  255.255.255.255
xid                   D  13
```

**qvm-features sys-whonix**
```
qubesmanager.maxmem_value   4000
service.cups                
check-updates               1
service.qubes-update-check  1
```
**qvm-service sys-whonix**
```
cups                           off
qubes-update-check  on
```

**tags**
```
> qvm-tags sys-whonix
anon-gateway
created-by-dom0
whonix-updatevm

> qvm-tags u-man-who
anon-vm
created-by-dom0
```

**RPC policies**
```
root@dom0:/etc/qubes-rpc/policy
> cat whonix.SdwdateStatus
$tag:anon-gateway $tag:anon-vm allow
$anyvm $anyvm deny

> cat whonix.NewStatus
$tag:anon-vm $tag:anon-gateway allow
$anyvm $anyvm deny
```

**errors in u-man-who syslog**
```
Sep 27 12:12:01 host systemd[1]: qubes-updates-proxy-forwarder@15-127.0.0.1:8082-127.0.0.1:33440.service: Failed with result 'exit-code'.
Sep 27 12:12:01 host systemd[1]: Started Forward connection to updates proxy over Qubes RPC (127.0.0.1:33442).
Sep 27 12:12:01 host systemd[1]: qubes-updates-proxy-forwarder@16-127.0.0.1:8082-127.0.0.1:33442.service: Main process exited, code=exited, status=126/n/a
Sep 27 12:12:01 host systemd[1]: qubes-updates-proxy-forwarder@16-127.0.0.1:8082-127.0.0.1:33442.service: Failed with result 'exit-code'.
Sep 27 12:12:01 host systemd[1]: Started Forward connection to updates proxy over Qubes RPC (127.0.0.1:33444).
Sep 27 12:12:01 host systemd[1]: qubes-updates-proxy-forwarder@17-127.0.0.1:8082-127.0.0.1:33444.service: Main process exited, code=exited, status=126/n/a
Sep 27 12:12:01 host systemd[1]: qubes-updates-proxy-forwarder@17-127.0.0.1:8082-127.0.0.1:33444.service: Failed with result 'exit-code'.
Sep 27 12:12:01 host systemd[1]: Started Forward connection to updates proxy over Qubes RPC (127.0.0.1:33446).
Sep 27 12:12:02 host systemd[1]: qubes-updates-proxy-forwarder@18-127.0.0.1:8082-127.0.0.1:33446.service: Main process exited, code=exited, status=126/n/a
Sep 27 12:12:02 host systemd[1]: qubes-updates-proxy-forwarder@18-127.0.0.1:8082-127.0.0.1:33446.service: Failed with result 'exit-code'.
Sep 27 12:12:02 host systemd[1]: Started Forward connection to updates proxy over Qubes RPC (127.0.0.1:33448).
Sep 27 12:12:02 host systemd[1]: qubes-updates-proxy-forwarder@19-127.0.0.1:8082-127.0.0.1:33448.service: Main process exited, code=exited, status=126/n/a
Sep 27 12:12:02 host systemd[1]: qubes-updates-proxy-forwarder@19-127.0.0.1:8082-127.0.0.1:33448.service: Failed with result 'exit-code'.
Sep 27 12:12:05 host systemd[1]: qubes-update-check.service: Succeeded.
Sep 27 12:12:05 host systemd[1]: Started Qubes check for VM updates and notify dom0.
Sep 27 12:12:11 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
Sep 27 12:12:32 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out

<many repeated lines like this>

Sep 27 12:21:12 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
Sep 27 12:21:32 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
Sep 27 12:21:53 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
Sep 27 12:22:01 host systemd[1]: Starting Cleanup of Temporary Directories...
Sep 27 12:22:01 host systemd-tmpfiles[6085]: [/usr/lib/tmpfiles.d/openvpn.conf:3] Duplicate line for path "/run/openvpn", ignoring.
Sep 27 12:22:01 host systemd-tmpfiles[6085]: [/usr/lib/tmpfiles.d/qubes-core-agent-linux.conf:1] Line references path below legacy directory /var/run/, updating /var/run/tinyproxy-updates → /run/tinyproxy-updates; please update the tmpfiles.d/ drop-in file accordingly.
Sep 27 12:22:01 host systemd-tmpfiles[6085]: [/etc/tmpfiles.d/qubes-gpg-split.conf:1] Line references path below legacy directory /var/run/, updating /var/run/qubes-gpg-split → /run/qubes-gpg-split; please update the tmpfiles.d/ drop-in file accordingly.
Sep 27 12:22:01 host systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Sep 27 12:22:01 host systemd[1]: Started Cleanup of Temporary Directories.
Sep 27 12:22:09 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
Sep 27 12:22:30 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
Sep 27 12:22:50 host systemd-socket-proxyd[1596]: Failed to connect to remote host: Connection timed out
```

**Solutions you've tried**
In an act of desperation I upgraded dom0 to testing repo. It wasn't smart and didn't change anything (beside the fact that now I'm running testing packages ... )

**Comment by damko** [comment] 2019-09-27 13:00
I just noticed this bit in sys-whonix syslog
```
Sep 27 12:52:53 host qubes.StartApp+debian-xterm-dom0: xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
Sep 27 12:53:32 host Tor[880]: Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
Sep 27 12:53:32 host Tor[880]: New control connection opened.
Sep 27 12:53:32 host Tor[880]: New control connection opened.
Sep 27 12:55:17 host systemd[1]: Starting Qubes check for VM updates and notify dom0...
Sep 27 12:55:28 host systemd[1]: qubes-update-check.service: Succeeded.
Sep 27 12:55:28 host systemd[1]: Started Qubes check for VM updates and notify dom0.
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: offline type_if=vif XENBUS_PATH=backend/vif/19/0
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: ifdown vif19.0 failed
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: ip route del 10.137.0.34 dev vif19.0 metric 32733 failed
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: ip route del fd09:24ef:4179::a89:22 dev vif19.0 metric 32733 failed
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: ip6tables-restore --noflush failed
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: ip addr del 10.137.0.10/32 dev vif19.0 failed
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: ip addr del fd09:24ef:4179::a89:a/128 dev vif19.0 failed
Sep 27 12:57:44 host root: /etc/xen/scripts/vif-route-qubes: Successful vif-route-qubes offline for vif19.0.
Sep 27 12:58:10 host systemd-udevd[4651]: Using default interface naming scheme 'v240'.
Sep 27 12:58:10 host root: /etc/xen/scripts/vif-route-qubes: online type_if=vif XENBUS_PATH=backend/vif/20/0
Sep 27 12:58:11 host root: /etc/xen/scripts/vif-route-qubes: Writing backend/vif/20/0/hotplug-error /etc/xen/scripts/vif-route-qubes failed; error detected. backend/vif/20/0/hotplug-status error to xenstore.
Sep 27 12:58:11 host root: /etc/xen/scripts/vif-route-qubes: /etc/xen/scripts/vif-route-qubes failed; error detected.
Sep 27 12:58:20 host kernel: [  483.887266] vif vif-20-0 vif20.0: Guest Rx ready

But it shows only several minutes after sys-whonix is up and running.

```

**Comment by marmarek** [comment] 2019-09-27 13:11
Duplicate of #5110

**Closed by marmarek** 2019-09-27 13:11 UTC
Labels: P: default, T: bug
