### ISSUE TITLE
Qube description field in the Qube Manager (or some sort of description string)

### ISSUE THREAD

**Issue by HerzogM** [QubesOS/qubes-issues#8546] opened 2023-09-22 14:20 UTC
Maybe this is silly, but I keep finding myself wanting to have a textbox in a qube’s settings to make remarks, comments or a description for that qube. Things I want to remember for that qube, a description for how this qube is intended to be used, warnings, hints etc.
The name field for the qube is not sufficient for this purpose and it would result in too long qube names if I made the name too verbose. So maybe the devs can consider giving the settings a textarea for this purpose?

User balko added the following:
"Nice idea, I would suggest to make it more general:
To allow adding some description string to any qube via qvm-prefs or something like that. And Qubes Manager can show it. Qubes widgets can also show it, too, e.g. as tooltips."

**Comment by unman** [comment] 2023-09-22 15:43
I'm almost 100% sure that this has been suggested before, but cant seem
to find an existing issue.
It's far from silly, and very desirable.

**Comment by andrewdavidwong** [comment] 2023-09-22 19:26
This is basically the front-end issue corresponding to #6572, and it is arguably a more general version of #6560.

**Comment by andrewdavidwong** [comment] 2023-09-22 19:31
Ah, this appears to be an exact duplicate of #899.

**Comment by andrewdavidwong** [comment] 2023-09-22 19:31
Duplicate of #899

**Comment by andrewdavidwong** [comment] 2023-09-22 19:31
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-09-22 19:31 UTC
Labels: T: enhancement, C: manager/widget, P: default
