### ISSUE TITLE
NetworkManager forgets connections upon reboot of NetVM

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2719] opened 2017-03-20 17:40 UTC
R3.2, updated Fedora 24 template.

NetworkManager is saving Wi-Fi connections to `/etc/sysconfig/network-scripts`.

Predictably, these get lost when the machine powers off.

What's going on?

**Comment by andrewdavidwong** [comment] 2017-03-21 02:18
Duplicate of #2584.

**Closed by andrewdavidwong** 2017-03-21 02:18 UTC
