### ISSUE TITLE
Make it easy for people to learn about qubes-users ML

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2152] opened 2016-07-04 11:05 UTC
I still keep getting emails from people asking questions about Qubes which they should really send to qubes-users. Make the links to the qubes-users somehow more visible. E.g. something like:

"Have a question or comment about Qubes OS?" and then once clicked, this would redirect to the qubes-users immediately.

**Comment by andrewdavidwong** [comment] 2016-07-04 11:39
It might be better to redirect them to [our mailing lists page](https://www.qubes-os.org/mailing-lists/) rather than directly to qubes-users. (Otherwise, it's even more likely that people will fail to follow the ML rules.)

**Comment by andrewdavidwong** [comment] 2016-07-04 11:43
We also want people to read the FAQ and docs to find the answers to easy questions before asking them on the MLs. So, perhaps we should send them to the [help](https://www.qubes-os.org/help/) page first?

**Comment by andrewdavidwong** [comment] 2016-07-04 11:44
The thing is, all of these pages/resources are clearly linked from every page on the website. It's just that most people don't pay attention (or don't care).

**Comment by evadogstar** [comment] 2016-07-04 14:34
https://www.qubes-os.org/team/
On this page need to place block **above** "Team" paragraph about what people must do if they need help

**Comment by rootkovska** [comment] 2016-07-04 16:04
I think most people are very adept at ignoring regular text at websites. So, what we need, IMHO, it a *button* :) A button labeled "Do you have a question?" or something.

**Comment by adrelanos** [comment] 2016-07-04 17:03
Joanna Rutkowska:
> I think most people are very adept at ignoring regular text at websites. So, what we need, IMHO, it a *button* :) A button labeled "Do you have a question?" or something.

Yes.

And some people are do not like mailing lists, never used them before,
forums, etc. and just are looking for an e-mail address for a quick
message. Or think they are special, require non-public communication or
whatnot.

If you want to avoid getting mails by these kind of people and answering
them with "please no private mails, use the proper support place as per
out help page: link", perhaps have e-mail addresses more protected.

joanna@<click here to find out the rest of the e-mail address> :)

That page would have 2 or 3 sentences and "@qubes-os.org" would be
somewhere in the middle of explaining the only acceptable reason for
private mails.

**Comment by evadogstar** [comment] 2016-07-04 17:10
Additional buttons is the good idea. But in such case we are already have the big "help" link at the top. Some users get attention not on "Help" link, but on "Team" link. Maybe they ignore help link, because they have a habit to search for "Forum" link to get help and they know that "Help" link on common websites always drive to some high volume of documentation printed with small text.  Maybe some of them are stupid :)

Anyway, they come to "Team" page, they see your email first on this page and you know what they do :) So, I suggest to add suggested button on the top of "Team" page. And maybe move team link from the header to the bottom of the page to get less random traffic on it. 

 https://i.imgur.com/kTsxX6Y.png``
![2016-07-04-195305](https://cloud.githubusercontent.com/assets/20259395/16566905/6993054e-4221-11e6-9ba0-7de23ebc5d75.png)

**Comment by andrewdavidwong** [comment] 2016-07-05 02:06
What do you think, @bnvk?

**Comment by rootkovska** [comment] 2016-07-05 07:38
Ok, a few additional thoughts:
1. I think it's confusing we actually have 4 help-like categories: Tour, Get Started Docs, and Help. IMHO at least Get Started should be renamed "Download", and Help should be somehow combined into the Docs (and we should make the "I have a questioin" button somewhere there).

2. I think the Team is somehow important, given the security sensitiveness of the project (i.e. many people will make some reputation calculating decision based on which human beings are behind a project). But I think we should perhaps not display email addresses there.

**Comment by marmarek** [comment] 2016-07-05 08:03
On Tue, Jul 05, 2016 at 12:38:08AM -0700, Joanna Rutkowska wrote:
> Ok, a few additional thoughts:
> 1. I think it's confusing we actually have 4 help-like categories: Tour, Get Started Docs, and Help. IMHO at least Get Started should be renamed "Download", 

+1
Also make the actual "Download" option more exposed - especially move it
before Live USB (which is not maintained currently).

> and Help should be somehow combined into the Docs (and we should make the "I have a questioin" button somewhere there).

-1

IMO "Help" is ok - short and on the topic. But that landing page IMO
should be somehow simplified - currently there are six buttons, and
"mailing lists" is the third one. I think it should have just 3 main
sections:
1. "Documentation" or "Resources" (with buttons for: documentation and FAQ)
2. "Ask" - with link to mailing list and maybe other places (stack
exchange? irc?)
3. Report bug - just like the current one

Also "Mailing Lists" should be named with "Join" - because IMO it
discourage from just asking questions there (looks like some bigger
thing than just "ask question"). Also we may consider linking to gmane
(instead of? in addition to google), if sending messages through it is
reliable.

> 2. I think the Team is somehow important, given the security sensitiveness of the project (i.e. many people will make some reputation calculating decision based on which human beings are behind a project). But I think we should perhaps not display email addresses there.

-1

It will make exactly this reputation calculation harder. In theory
there is key fingerprint, but in practice for not-so-critical assessment
it's just easier to filter on email address (and probably check
signatures later).
Current layout is good - the biggest information is key fingerprint,
email address is somehow small button.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment] 2016-07-05 09:27
> I think it's confusing we actually have 4 help-like categories: Tour, Get Started Docs, and Help. IMHO at least Get Started should be renamed "Download", and Help should be somehow combined into the Docs (and we should make the "I have a questioin" button somewhere there).

Agreed. (This part is pretty much a duplicate of #1841.)

**Comment by bnvk** [comment] 2016-07-07 08:02
> I think most people are very adept at ignoring regular text at websites.

Yes. @rootkovska mention of a big button is right on the mark, reworking the [mailing lists page](https://www.qubes-os.org/mailing-lists/) a bit should help.

A lot of the comments in this thread are about the overall information architecture of the whole site, which as @andrewdavidwong says is in #1841 and also factors in to #1833 in anycase, working on on this now!

**Comment by andrewdavidwong** [comment] 2016-10-15 22:22
We've already removed @rootkovska's email address from the Team page, and we can do the same for anyone else who doesn't want their email address visible there.

**Closed by andrewdavidwong** 2016-10-15 22:22 UTC
Labels: C: website, enhancement, P: minor, UX
