### ISSUE TITLE
Qubes Devices widget list becomes extremely tiny

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4738] opened 2019-01-19 02:32 UTC
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Qubes Devices notification area widget

---

### Steps to reproduce the behavior:

Use the system normally.

### Expected behavior:

After clicking on the Qubes Devices widget, a normal-sized menu opens listing the devices.

### Actual behavior:

After clicking on the Qubes Devices widget, an extremely short (but normal width) menu opens. Most of the menu is taken up by the up and down scroll buttons, and only a comically small ~5px tall area is left for the actual list of devices. :slightly_smiling_face:

### General notes:

 - When I click the up and down scroll buttons, the actual list of devices seems fine, but my "window" is too small to read the text or really interact with it. 
 - At first, the menu was normal-sized. This only happened after using the system over the course of a couple of days (without rebooting and without installing any dom0 updates).

---

**Comment by marmarek** [comment] 2019-01-19 08:18
Looks like a duplicate of #2970 - even though that issue is about domains widget, the cause seems to be the same.

**Closed** 2019-01-19 23:12 UTC
Labels: C: manager/widget, bug
