### ISSUE TITLE
Add password/additional encryption to qubes as an additional layer

### ISSUE THREAD

**Issue by blatchard** [QubesOS/qubes-issues#6766] opened 2021-07-06 13:57 UTC
### The problem you're addressing (if any)
Simply put, as an example, in whonix, you can set the workstation as encrypted requiring a password to just start that vm. After you have already logged into your probably already encrypted system.

We do not have this option in qubes, you log in and can start all qubes, regardless. it could potentially go in settings.

### Describe the solution you'd like
An option to provide an virtualbox encrypted drive style before even being able to start a qube up on qubes as the user sees it fit. Would be excellent. Vault maybe another example of a qube people like to use this with.

### Where is the value to a user, and who might that user be?
You have qubes unencrypted and open, you are persuaded to open something from a particular qube, you don't know the password....  double encryption also, a dummy password would also be great (delete all)

### Describe any alternative solutions you've considered
none

### Potentially related issues
None found.

**Comment by andrewdavidwong** [comment] 2021-07-06 14:15
Duplicate of #1293

**Comment by andrewdavidwong** [comment] 2021-07-06 14:15
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-07-06 14:15 UTC
Labels: P: default, T: enhancement
