### ISSUE TITLE
Qubes 3.1 lock screen leaks private information

### ISSUE THREAD

**Issue by talex5** [QubesOS/qubes-issues#1572] opened 2016-01-03 18:49 UTC
Sorry for the bad photo, but I think you can see the lock screen is revealing parts of my desktop:

![login](https://cloud.githubusercontent.com/assets/554131/12080164/5d483208-b24a-11e5-811a-6366f9e4abf7.jpg)

I've had other occasions where it has shown larger areas, e.g. emails, though normally it's just random-looking noise.

This started after upgrading to 3.1. Qubes 3.0 used to fill in the bits of the screen it wasn't using in black.

**Comment by cfcs** [comment] 2016-01-04 02:43
Here we go again,

previous discussion of the subject: https://github.com/QubesOS/qubes-issues/issues/963

[kind of related]: https://github.com/QubesOS/qubes-issues/issues/888

**Comment by marmarek** [comment] 2016-01-04 13:52
Duplicate of  #963

**Closed by marmarek** 2016-01-04 13:52 UTC
Labels: duplicate
