### ISSUE TITLE
"Terminal" does not work in debian-9-dvm: it crashes after start. "XTerm" does work.

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#3878] opened 2018-05-05 01:25 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

**Terminal** is part of the default set of applications, but when following the instructions of https://www.qubes-os.org/doc/dispvm-customization/ , **Terminal** crashes immediately after start in an debian-9-dvm. 

**XTerm** works.

---

### General notes:

---

**Comment by awokd** [comment] 2018-05-09 11:28
@Wikinaut Which section of that document are you following? And if you are running "terminal", try "gnome-terminal" instead.

**Comment by Wikinaut** [comment] 2018-05-09 12:47
@awokd I followed this section https://www.qubes-os.org/doc/dispvm-customization/#creating-new-disposable-vm-base-appvm and installed a debian-9-dvm.

The "Terminal" I mean is one of the four standard applications (Firefox, Terminal, Qube Settings and one more) which are installed and reachable via the App control icon (right click in the Qubes Menu in the upper left corner of Qubes-QS onto the debian-9-dvm machine icon).

**Comment by jimtahu** [comment] 2018-05-09 23:46
I am seeing this as well, with both fedora-26-dvm and debian-9-dvm: gnome-terminal shortcut only starts the vm briefly and immediately closes, the xterm shortcut works as expected (new dvm and xterm running).

Running gnome-terminal in the resulting xterm works fine. Notably though, it seems the immediate invocation returns immediately, and closing the xterm shutsdown the vm (killing the gnome-terminal).

I am suspecting gnome-terminal returning immediately is tricking the disposable vm into thinking it should shutdown.

**Comment by techgeeknz** [comment] 2018-05-10 01:56
In order to mitigate this issue in future Qubes releases, I recommend replacing `nautilus` with `thunar` and `gnome-terminal` with either one of `lxterminal` or `xfce4-terminal`.

Each one of these software packages are capable but lightweight replacements for their Gnome counterparts (thunar even supports GVFS); and, more importantly, work well with DVMs.

**Comment by andrewdavidwong** [comment] 2018-05-10 04:33
@jimtahu:
> I am seeing this as well, with both fedora-26-dvm and debian-9-dvm: gnome-terminal shortcut only starts the vm briefly and immediately closes, the xterm shortcut works as expected (new dvm and xterm running).
> 
> Running gnome-terminal in the resulting xterm works fine. Notably though, it seems the immediate invocation returns immediately, and closing the xterm shutsdown the vm (killing the gnome-terminal).
> 
> I am suspecting gnome-terminal returning immediately is tricking the disposable vm into thinking it should shutdown.

#2581 is the issue for this.

---

@Wikinaut:
> I followed this section https://www.qubes-os.org/doc/dispvm-customization/#creating-new-disposable-vm-base-appvm and installed a debian-9-dvm.
> 
> The "Terminal" I mean is one of the four standard applications (Firefox, Terminal, Qube Settings and one more) which are installed and reachable via the App control icon (right click in the Qubes Menu in the upper left corner of Qubes-QS onto the debian-9-dvm machine icon).

If the DispVM menu is using `gnome-terminal` instead of `xterm` by default, that sounds like an unintended regression (see https://github.com/QubesOS/qubes-issues/issues/2581#issuecomment-272666933). Please file a separate issue for this.

We'll keep the current issue about the documentation, which should be updated to direct users to use `xterm` instead of `gnome-terminal` for the reasons explained in the comments on #2581.

---

@techgeeknz:
> In order to mitigate this issue in future Qubes releases, I recommend replacing `nautilus` with `thunar` and `gnome-terminal` with either one of `lxterminal` or `xfce4-terminal`.

We'd prefer not to resort to this, if it can be avoided:
https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

**Comment by bigdx** [comment] 2018-10-25 07:53
Same problem with fedora-28-dvm. "Files" (Nautilus) has this issue too ...

If thats a known issue, why no warning/hint in the docs about DVM at https://www.qubes-os.org/doc/dispvm/? Specially if the "attitude" not allows to modify the template in first place! Would have saved me "some" time ;-)

**Comment by andrewdavidwong** [comment] 2018-10-26 01:55
> If thats a known issue, why no warning/hint in the docs about DVM at https://www.qubes-os.org/doc/dispvm/? Specially if the "attitude" not allows to modify the template in first place! Would have saved me "some" time ;-)
> 
> Edit: Sorry, it's mentioned, but somewhere down under "Adding programs to Disposable VM Application Menu". You wont look there if you not intend to add programs ...

The documentation is a community effort. Please help us improve it by submitting a pull request:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by marmarek** [comment] 2022-11-23 01:55
Since https://github.com/QubesOS/qubes-issues/issues/2581 is fixed, this issue isn't applicable anymore either.

**Closed by marmarek** 2022-11-23 01:55 UTC
Labels: C: doc
