### ISSUE TITLE
Cannot qubes-dom0-update after qubes-dom0-update

### ISSUE THREAD

**Issue by ohreally** [QubesOS/qubes-issues#3463] opened 2018-01-14 21:50 UTC
#### Qubes OS version:

R4.0rc3

#### Affected TemplateVMs: 

None (dom0 issue).

---

### Steps to reproduce the behavior:

qubes-dom0-update

### Expected behavior:

Stuff works.

### Actual behavior:

`# qubes-dom0-update`
`Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...`
`http://yum.qubes-os.org/r%24releasever/current/dom0/fc25/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"`
`Trying other mirror.`
`Error: Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current. Please verify its path and try again`

Instead of replacing `$releasever` in the repo URL with the release version, the $ in the config file is URL encoded.
Hardcoding `r4.0` instead of `r$releasever` in both /etc/yum.repos.d/qubes-dom0.repo and /etc/yum.repos.d/qubes-templates.repo allows me to run `qubes-dom0-update` again.

### General notes:

After running `qubes-dom0-update` a first time, I ran `qubes-dom0-update` a second time, to see if the problems I encountered were solved in the days between the first update and the reboot following it. The problem described occurred with the second run.

**Comment by marmarek** [comment] 2018-01-18 02:33
This looks to be related to `sys-whonix` as UpdateVM.

**Comment by marmarek** [comment] 2018-01-18 02:41
Is whonix-gw template up to date? Is it fresh install, or template
restored from a backup (migrated from R3.2)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by ohreally** [comment] 2018-01-18 16:29
This is a fresh install (24-12-2017), and I have not yet updated the whonix templates.

**Comment by adrelanos** [comment] 2019-01-27 06:35
Not related to Whonix. Happened to me using fedora-29 based UpdateVM over clearnet as well. Could see this issue clearly when using `sudo qubes-dom0-update -v`.

> Hardcoding r4.0 instead of r$releasever in both /etc/yum.repos.d/qubes-dom0.repo and /etc/yum.repos.d/qubes-templates.repo allows me to run qubes-dom0-update again.

Confirmed.

**Comment by marmarek** [comment] 2019-08-26 21:21
Duplicate of #4477

**Closed by marmarek** 2019-08-26 21:21 UTC
Labels: C: core, T: bug
