### ISSUE TITLE
Fedora: "grubby fatal error: unable to find suitable template" / "grubby: doing this would leave no kernel entries. Not writing out new config."

### ISSUE THREAD

**Issue by Polygonbugs** [QubesOS/qubes-issues#4074] opened 2018-07-13 05:54 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

grubby, kernel(?)

---

### Steps to reproduce the behavior:

1. Install grubby via upgrading template. `sudo dnf upgrade -y`.
2. While installing grubby itself also makes error messages.
3. Updating template after installing grubby makes continuous error messages.

### Expected behavior:

It shouldn't give any error message.

### Actual behavior:

It gives following error messages.
```
grubby fatal error: unable to find a suitable template
grubby: doing this would leave no kernel entries. Not writing out new config.
warning: file /lib/modules/4.16.14-300.fc28.x86_64/updates: remove failed: No such file or directory
```

### Additional Information

Here is more verbose information.
```
 Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: grub2-common-1:2.02-38.fc28.noarch                     1/1 
  Upgrading        : grub2-common-1:2.02-38.fc28.noarch                    1/74 
  Installing       : libkcapi-1.1.1-1.fc28.x86_64                          2/74 
  Installing       : libkcapi-hmaccalc-1.1.1-1.fc28.x86_64                 3/74 
  Upgrading        : dracut-048-1.fc28.x86_64                              4/74 
  Installing       : kernel-core-4.17.4-200.fc28.x86_64                    5/74 
  Running scriptlet: kernel-core-4.17.4-200.fc28.x86_64                    5/74 
  Upgrading        : grub2-tools-minimal-1:2.02-38.fc28.x86_64             6/74 
  Upgrading        : openblas-0.3.1-1.fc28.x86_64                          7/74 
  Running scriptlet: openblas-0.3.1-1.fc28.x86_64                          7/74 
  Upgrading        : mesa-libglapi-18.0.5-3.fc28.x86_64                    8/74 
  Running scriptlet: mesa-libglapi-18.0.5-3.fc28.x86_64                    8/74 
  Upgrading        : libattr-2.4.48-1.fc28.x86_64                          9/74 
  Upgrading        : libacl-2.2.53-1.fc28.x86_64                          10/74 
  Upgrading        : grub2-tools-extra-1:2.02-38.fc28.x86_64              11/74 
  Installing       : kernel-modules-4.17.4-200.fc28.x86_64                12/74 
  Running scriptlet: kernel-modules-4.17.4-200.fc28.x86_64                12/74 
  Running scriptlet: grub2-tools-1:2.02-38.fc28.x86_64                    13/74 
  Upgrading        : grub2-tools-1:2.02-38.fc28.x86_64                    13/74 
  Running scriptlet: grub2-tools-1:2.02-38.fc28.x86_64                    13/74 
  Upgrading        : grub2-pc-modules-1:2.02-38.fc28.noarch               14/74 
  Upgrading        : perl-Module-CoreList-1:5.20180626-1.fc28.noarch      15/74 
  Running scriptlet: openssh-7.7p1-5.fc28.x86_64                          16/74 
  Upgrading        : openssh-7.7p1-5.fc28.x86_64                          16/74 
  Upgrading        : mesa-libgbm-18.0.5-3.fc28.x86_64                     17/74 
  Running scriptlet: mesa-libgbm-18.0.5-3.fc28.x86_64                     17/74 
  Upgrading        : mesa-libEGL-18.0.5-3.fc28.x86_64                     18/74 
  Upgrading        : openssh-clients-7.7p1-5.fc28.x86_64                  19/74 
  Upgrading        : perl-Module-CoreList-tools-1:5.20180626-1.fc28.noa   20/74 
  Upgrading        : grub2-pc-1:2.02-38.fc28.x86_64                       21/74 
  Installing       : kernel-4.17.4-200.fc28.x86_64                        22/74 
  Upgrading        : acl-2.2.53-1.fc28.x86_64                             23/74 
  Upgrading        : vim-minimal-2:8.1.119-2.fc28.x86_64                  24/74 
  Upgrading        : mesa-libGL-18.0.5-3.fc28.x86_64                      25/74 
  Installing       : openblas-serial-0.3.1-1.fc28.x86_64                  26/74 
  Upgrading        : openblas-threads-0.3.1-1.fc28.x86_64                 27/74 
  Running scriptlet: openblas-threads-0.3.1-1.fc28.x86_64                 27/74 
  Installing       : grub2-tools-efi-1:2.02-38.fc28.x86_64                28/74 
  Upgrading        : perl-File-Temp-0.230.600-1.fc28.noarch               29/74 
  Upgrading        : perl-Devel-Size-0.82-1.fc28.x86_64                   30/74 
  Upgrading        : pcre2-10.31-5.fc28.x86_64                            31/74 
  Upgrading        : openldap-2.4.46-2.fc28.x86_64                        32/74 
  Upgrading        : libzstd-1.3.5-1.fc28.x86_64                          33/74 
  Upgrading        : libjpeg-turbo-1.5.3-6.fc28.x86_64                    34/74 
  Upgrading        : kernel-headers-4.17.4-200.fc28.x86_64                35/74 
  Upgrading        : hwdata-0.313-1.fc28.noarch                           36/74 
  Upgrading        : hunspell-en-US-0.20140811.1-12.fc28.noarch           37/74 
  Upgrading        : gdisk-1.0.4-1.fc28.x86_64                            38/74 
  Installing       : kernel-devel-4.17.4-200.fc28.x86_64                  39/74 
  Running scriptlet: kernel-devel-4.17.4-200.fc28.x86_64                  39/74 
  Cleanup          : grub2-pc-1:2.02-34.fc28.x86_64                       40/74 
  Cleanup          : acl-2.2.52-20.fc28.x86_64                            41/74 
  Erasing          : kernel-4.16.14-300.fc28.x86_64                       42/74 
  Cleanup          : perl-Module-CoreList-tools-1:5.20180420-1.fc28.noa   43/74 
  Cleanup          : grub2-pc-modules-1:2.02-34.fc28.noarch               44/74 
  Cleanup          : perl-Module-CoreList-1:5.20180420-1.fc28.noarch      45/74 
  Erasing          : kernel-devel-4.16.14-300.fc28.x86_64                 46/74 
  Cleanup          : perl-File-Temp-0.230.400-396.fc28.noarch             47/74 
  Cleanup          : kernel-headers-4.17.3-200.fc28.x86_64                48/74 
  Cleanup          : hwdata-0.312-1.fc28.noarch                           49/74 
  Cleanup          : hunspell-en-US-0.20140811.1-11.fc28.noarch           50/74 
  Running scriptlet: grub2-tools-1:2.02-34.fc28.x86_64                    51/74 
  Cleanup          : grub2-tools-1:2.02-34.fc28.x86_64                    51/74 
  Cleanup          : grub2-tools-extra-1:2.02-34.fc28.x86_64              52/74 
  Cleanup          : vim-minimal-2:8.1.119-1.fc28.x86_64                  53/74 
  Cleanup          : libacl-2.2.52-20.fc28.x86_64                         54/74 
  Cleanup          : mesa-libGL-18.0.5-2.fc28.x86_64                      55/74 
  Cleanup          : mesa-libEGL-18.0.5-2.fc28.x86_64                     56/74 
  Cleanup          : grub2-tools-minimal-1:2.02-34.fc28.x86_64            57/74 
  Erasing          : kernel-modules-4.16.14-300.fc28.x86_64               58/74 
  Running scriptlet: kernel-modules-4.16.14-300.fc28.x86_64               58/74 
  Running scriptlet: kernel-core-4.16.14-300.fc28.x86_64                  59/74 
**grubby fatal error: unable to find a suitable template
grubby: doing this would leave no kernel entries. Not writing out new config.**
  Erasing          : kernel-core-4.16.14-300.fc28.x86_64                  59/74 
**warning: file /lib/modules/4.16.14-300.fc28.x86_64/updates: remove failed: No such file or directory**
  Cleanup          : openssh-clients-7.7p1-4.fc28.x86_64                  60/74 
  Cleanup          : grub2-common-1:2.02-34.fc28.noarch                   61/74 
  Cleanup          : openssh-7.7p1-4.fc28.x86_64                          62/74 
  Cleanup          : dracut-047-8.git20180305.fc28.x86_64                 63/74 
  Cleanup          : mesa-libgbm-18.0.5-2.fc28.x86_64                     64/74 
  Running scriptlet: mesa-libgbm-18.0.5-2.fc28.x86_64                     64/74 
  Cleanup          : mesa-libglapi-18.0.5-2.fc28.x86_64                   65/74 
  Running scriptlet: mesa-libglapi-18.0.5-2.fc28.x86_64                   65/74 
  Cleanup          : libattr-2.4.47-23.fc28.x86_64                        66/74 
  Cleanup          : perl-Devel-Size-0.81-2.fc28.x86_64                   67/74 
  Cleanup          : pcre2-10.31-4.fc28.x86_64                            68/74 
  Cleanup          : openldap-2.4.46-1.fc28.x86_64                        69/74 
  Cleanup          : openblas-threads-0.3.0-1.fc28.x86_64                 70/74 
  Running scriptlet: openblas-threads-0.3.0-1.fc28.x86_64                 70/74 
  Cleanup          : openblas-0.3.0-1.fc28.x86_64                         71/74 
  Running scriptlet: openblas-0.3.0-1.fc28.x86_64                         71/74 
  Cleanup          : libzstd-1.3.4-1.fc28.x86_64                          72/74 
  Cleanup          : libjpeg-turbo-1.5.3-5.fc28.x86_64                    73/74 
  Cleanup          : gdisk-1.0.3-6.fc28.x86_64                            74/74 
  Running scriptlet: kernel-core-4.17.4-200.fc28.x86_64                   74/74 
**grubby fatal error: unable to find a suitable template
grubby fatal error: unable to find a suitable template
grubby: doing this would leave no kernel entries. Not writing out new config.**
  Running scriptlet: gdisk-1.0.3-6.fc28.x86_64                            74/74 
```

**Comment by Aekez** [comment] 2018-07-13 16:21
Two clues here make me curious, you mention the use of -y, and also grubby is currently included in the "dnf autoremove". Did you by any chance run -y on autoremove? or force the update/upgrade?


```
Last metadata expiration check: 0:05:42 ago on Fri Jul 13 18:08:58 2018.
Dependencies resolved.
================================================================================
 Package               Arch         Version                Repository      Size
================================================================================
Removing:
 gnupg                 x86_64       1.4.23-1.fc28          @updates       5.4 M
 grub2-tools-efi       x86_64       1:2.02-38.fc28         @updates       1.9 M
 grubby                x86_64       8.40-11.fc28           @fedora        123 k
 libusb                x86_64       1:0.1.5-12.fc28        @fedora         67 k

Transaction Summary
================================================================================
Remove  4 Packages

Freed space: 7.5 M
Is this ok [y/N]:
```

Could you try make a new copy of the minimal template, and try without autoremoval or force replacing updates?

**Comment by Polygonbugs** [comment] 2018-07-14 11:35
No, still I can see grubby fatal error on first update when issuing [bash-4.4]# "dnf update -y && dnf clean all" from fresh fedora-28-minimal.

**Comment by marmarek** [comment] 2018-07-15 00:06
Can you simply remove grubby? As seen above `dnf autoremove` would do that (which means it isn't required by anything installed). The grubby+grub2 idea is utterly broken, it tries to edit grub2.cfg file, which is a generated file and changes there would be overridden anyway. It isn't needed to install a kernel, nor configure grub (grub comes with its own configuration generator - grub2-mkconfig).

**Comment by Polygonbugs** [comment] 2018-07-15 06:54
@Aekez 
Here are answer of your questions 1),2),3)
(1)

```
[user@dom0 ~ ]$ rpm -qa qubes-template-fedora-28-minimal
qubes-template-fedora-28-minimal-4.0.0-2018052112212.noarch
```
I think we are using identical version of fedora-28-minimal.

(2)

```
[user@fedora-28-minimal-clone-1 ~]$ rpm -qa grubby
grubby-8.40-11.fc28.x86_64
```
Same as well

(3)
Sorry, I don't understand what is difference between two commands, `qvm-run -u root fedora-28-minimal "xterm -e 'sudo dnf update --refresh'"` and `qvm-run -u root fedora-28-minimal "xterm -e 'sudo dnf upgrade'"`. Also I don't understand the difference between adding `sudo` next to the commands vs commands issued by root account.

---
@marmarek ,
Grubby successfully removed (as well as grub2-tools-efi) by `autoremove` command. Let's see if next update give error messages

**Comment by Aekez** [comment] 2018-07-15 08:45
> Grubby successfully removed (as well as grub2-tools-efi) by autoremove command. Let's see if next update give error messages

Marek seem to have nailed it, so that definitely sounds like a plan. It might only happen the next time you get a kernel update though? So it'll probably be whenever fedora puts out a new kernel version. 

<br /> 

> Sorry, I don't understand what is difference between two commands, qvm-run -u root fedora-28-minimal "xterm -e 'sudo dnf update --refresh'" and qvm-run -u root fedora-28-minimal "xterm -e 'sudo dnf upgrade'". Also I don't understand the difference between adding sudo next to the commands vs commands issued by root account.

I'm more than happy to help answer and discuss this as I also find it interesting and I'm happy to help too, but it might go off-topic here. If you would like to discuss running these commands, i.e. in a shell or even a more advanced bash script to make updating easier, then your more than welcome to open an issue over at Qubes Community Collaboration (QCC) https://github.com/Qubes-Community/Contents/issues I'll continue the discussion with you there if you choose to open an issue.

So if you got everyday user questions the Qubes-user mailing list is best https://groups.google.com/forum/#!forum/qubes-users, but if you got questions or suggestions related to scripts, code or Qubes docs, which doesn't fit the official QubesOS GitHub development focus, then you can always open an issue to discuss it over at QCC which is more focused on the minor things and user experiences, with docs and code (typically scripts) :)

**Comment by Polygonbugs** [comment] 2018-07-19 05:03
Now I can't find any issue after removing grubby. Kernel update (though actually not needed) doesn't give error message.

**Comment by mvermaes** [comment] 2018-11-12 02:49
I've seen this error when doing the last few kernel updates to a standard Fedora 28 template (`qubes-template-fedora-28-4.0.0-201805232345`) as well. I haven't tried uninstalling grubby yet, but I assume it would resolve the issue.

**Comment by heinrich-ulbricht** [comment] 2018-12-16 21:02
Got the grubby error in the normal Fedora 28 template as well. Doing a `sudo dnf autoremove` before `sudo dnf update` did the trick (it removed grubby).

**Comment by marmarek** [comment] 2019-02-06 16:37
Upstream discussion about dropping grubby: https://bugzilla.redhat.com/show_bug.cgi?id=1287854
It goes back to 2015 and regardless of all the arguments over all those years, the maintainer(?) seems to be not convinced.

I see two ways of removing `grubby`:
 - in template builder scripts - it will avoid installing it in new templates, but will not help those who have  templates already installed (including templates on Qubes 4.0.1 installation image...)
 - by adding `Conflicts: grubby` to one of meta-packages (probably `qubes-vm-recommended`) - this should remove grubby also from existing templates, but there is a risk of breaking some, if there is a package really depending on `grubby` (according to `dnf repoquery --whatrequires grubby` there two: `autotest-framework` and `xorg-x11-drv-nvidia`, by default none of them is installed)

I think it's still better to go with the first option, but can be convinced otherwise.

**Comment by andrewdavidwong** [comment] 2019-04-14 19:56
I and other users are still seeing this, e.g.:

https://groups.google.com/d/msgid/qubes-users/LcSOm2v--3-1%40tutanota.com

**Comment by marmarek** [comment] 2019-04-15 00:40
This is fixed in template builder, so all templates built after Feb 6 do not have this issue anymore. But those build before (including those in 4.0.1) still have grubby installed.
While I'd like grubby to disappear, or never existed in the first place, it is a standard Fedora package and forcibly removing it (using one or another method) may lead to removing other packages depending on it (if user installed any of them). In default Fedora repositories I see only one such package: autotest-framework. But users are free to use other repositories too.
If there is any safe way to remove the package, it may be a good idea to add it to [update formula](https://github.com/QubesOS/qubes-mgmt-salt-dom0-update/blob/master/update/qubes-vm.sls). Safe, as in: do not remove if anything else depends on it.

**Comment by andrewdavidwong** [comment] 2019-04-15 06:56
> If there is any safe way to remove the package, it may be a good idea to add it to update formula. Safe, as in: do not remove if anything else depends on it.

Yes, that would be great. I tried removing it from a Fedora 29 TemplateVM, but it got automatically reinstalled a couple days later. If special instructions are required to uninstall it, perhaps we should document them.

**Comment by marmarek** [comment] 2019-04-16 00:19
I have alternative, rather hacky, idea: provide dummy `grubby` package in our repositories, with higher version number (or even high epoch). This will get rid of broken by design grubby scripts, while at the same time, should not prevent installation of packages referencing it. It still may break any package that actively use grubby, but since grubby is broken anyway, it should not be worse.

If someone have a better idea, please step in.

Otherwise, @fepitre could prepare such package and test it (especially, if it automatically replace real grubby)? In practice, I think it should be differently named package (`grubby-dummy`?) with `Provices: grubby`, `Obsoletes: grubby` (possibly pointing as some versions). This way, it will still be possible to exclude this dummy package, if someone really needs real grubby for any reason.

**Closed** 2019-04-21 21:27 UTC
Labels: C: Fedora, P: major, T: bug
