### ISSUE TITLE
xfce - keyboard and mouse input passed to wrong window 

### ISSUE THREAD

**Issue by cobordism** [QubesOS/qubes-issues#6253] opened 2020-12-03 16:52 UTC
**Qubes OS version**
`R4.0`

**Affected component(s) or functionality**
xfce window manager, I presume

**Brief summary**
just one example: 
When I click a link in one app (A) that opens a tab in another (browser) app (B), the mouse and keyboard input are messed up. Window A will remain in front and in focus but keyboard input will (mostly) go to B. Mouse input will go to B on those parts of A that overlap with B and otherwise they will go to A. This can get extremely confusing, and especially with drag-and-drop, dropping content on a background window can be very undesirable.
This happens in several scenarios where one window opens another, or passes input to another but I have not been able to ascertain all the exact circumstances that trigger this.

**How Reproducible**
Have the two open windows for A and B overlap. Click on a link in A (this can be thunderbird, discord, a chat app ...) so that it opens in the browser B (firefox, brave ...). 
Scroll your mouse wheel in app A. If the mouse position overlaps B, the content in B will scroll, if the mouse does not overlap B, then A will scroll.
Type some letters and note that they get sent to the background app. Press Alt+space and see that it gets processed by the foreground window.

**Expected behavior**
I expect all mouse and keyboard input to be directed to the one active window in front.

**Actual behavior**
a mixture - mouse input is mapped to one of two windows depending on position. 
foreground window retains focus, but background window takes keyboard and some mouse input.

For example, typing letters get passed to background window, but pressing keys like alt+space opens WM menu of foreground window.

**Additional context**
in case it is relevant: usb mouse via sys-usb qube

**Solutions you've tried**
window manager tweaks and settings.
Window manager options like "Automatically give focus to newly created windows" or "activate focus stealing prevention" have no effect.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I searched for 'xfce' issues in this repo, I searched for focus stealing, 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

perhaps this is related or duplicate? I cannot tell - it's for Qubes 3.2. Apologies if duplicate.
https://github.com/QubesOS/qubes-issues/issues/3267

**Comment by iamahuman** [comment] 2020-12-03 18:28
Duplicate of #3267 -- it has indeed been reported against R3.2, but its milestone has been updated to R4.0.

**Comment by cobordism** [comment] 2020-12-03 19:45
Thanks. Do you know if there is some workaround? I constantly trip over this issue.

**Comment by iamahuman** [comment] 2020-12-04 03:43
Thanks for the report. You can click on the title bar instead.

**Comment by andrewdavidwong** [comment] 2020-12-04 06:25
Duplicate of #3267

**Comment by andrewdavidwong** [comment] 2020-12-04 06:25
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-12-04 06:25 UTC
Labels: P: default, T: bug

**Comment by cobordism** [comment] 2020-12-04 09:42
"You can click on the title bar instead."
Instead of what? clicking on a URL? that doesn't make sense.

It is possible to break back out of this errant behaviour by switching windows or perhaps clicking the title bar, but usually, by the time you realise that you're in this position, the damage is already done. 

You're not going to click on the title bar of every window every time you want to interact with the app.

Is this an xfce problem? Is it a workaround to switch window managers? Or is the bug deeper down?

**Comment by iamahuman** [comment] 2020-12-04 10:29
> "You can click on the title bar instead."
> Instead of what? clicking on a URL? that doesn't make sense.

I completely understand, but it's currently the best known workaround that works in all cases. That or using <kbd><kbd>Alt</kbd>-<kbd>Tab</kbd></kbd>.

> 
> It is possible to break back out of this errant behaviour by switching windows or perhaps clicking the title bar, but usually, by the time you realise that you're in this position, the damage is already done.

You're right.

> 
> You're not going to click on the title bar of every window every time you want to interact with the app.

We shouldn't.

> 
> Is this an xfce problem? Is it a workaround to switch window managers? Or is the bug deeper down?

This is the Qubes GUI agent's problem. Dom0 windows (e.g. Qubes Manager, Applications Menu, dom0 terminal, d0m file manager, etc) are unaffected.

**Comment by iamahuman** [comment] 2020-12-04 10:37
Also, this only happens between windows from the same VM. Windows from different VMs do not get focus intermixed.
