### ISSUE TITLE
Can`t increase font size in debian or kali template using xfce4-appearance-settings

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8433] opened 2023-08-18 10:53 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

I tried to change the font size not only with xfce4-appearance-settings, but also with gsettings. None of this helped.

Only the following solution helped:
edit /etc/X11/Xresources/x11-common and add the line "Xft.dpi: 105" to the end of file. Need reboot of the AppVM for applying changes.

My guess is that this is due to the missing gnome daemon, but I tried to install it along with the following packages:
"gnome-settings-daemon" and "gnome-tweaks"

I was unable to do this due to broken dependencies of the entire template. Dependencies in kali and debian templates are already broken right after installing these very templates

### Steps to reproduce
Try to increase fonts with xfce4-appearance-settings or gsettings

### Expected behavior

You can't change font sizes

**Comment by Middenvaus** [comment] 2023-08-18 10:54
I will write the following details as I remember what else happened at the time of this breakdown.

**Comment by andrewdavidwong** [comment] 2023-08-18 12:39
Possible duplicate of #1951 and/or #7881.

**Comment by Middenvaus** [comment] 2023-08-18 16:12
No, I have a standard resolution screen of 1920x1080 and this is also not a duplicate of those issues

**Closed** 2024-12-07 14:26 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, C: Kali, affects-4.1, eol-4.1
