### ISSUE TITLE
Qubes Updater: Make "Details" view live (not display output after update is done)

### ISSUE THREAD

**Issue by sjvudp** [QubesOS/qubes-issues#7778] opened 2022-09-18 19:39 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Using Qubes Updater is offering a quite boring view, even when having selected "Details":
You see _no_ output until after update is complete (or ended otherwise). Then you see the collected output all at once.
Sometimes with a slow network connection it can take several minutes until you see something.

### The solution you'd like
I'd like to see output when it was created, i.e.: A "live" view.

### The value to a user, and who that user might be
See what's actually going on while updating.

**Comment by marmarek** [comment] 2022-09-18 22:10
With the current updater technology, it isn't possible.
But R4.2 will ship with new updater backend (#7443 ) and it will include at the very least a progress bar showing actual progress.

**Comment by andrewdavidwong** [comment] 2022-09-18 22:56
> With the current updater technology, it isn't possible. But R4.2 will ship with new updater backend (#7443 ) and it will include at the very least a progress bar showing actual progress.

Closing as a duplicate of #7443.

-----

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-09-18 22:56 UTC
Labels: T: enhancement, P: default
