### ISSUE TITLE
Qube Manager: Houston error, steps to reproduce

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4022] opened 2018-06-19 20:48 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Qube Manger

---

### Steps to reproduce the behavior:

Open: http://porteus-kiosk.org/download.html

Download: Porteus Kiosk 4.7.0 (Default version) as Porteus-Kiosk-4.7.0-x86_64.iso

Open Qube Manager, Menu `Qube`, Select `Create new qube`.

Note: `[Dom0] Create new qube` popup displays.
- Name and label: `<custom>-kiosk-dvm`
- Type: `Standalone qube not based on a template`
- `[X]` launch settings after creation
Press `OK`.

Note: `[Dom0] Settings: <custom>-kiosk-dvm` popup displays.
Tab `Basic`
- `[X]` Start qube automatically on boot
Tab `Advanced`
- Initial memory: `1000 MB`
- `[ ]` Include in memory balancing
- Mode: `default (PVH)`
Press `Apply` then in Tab `Advanced` press `Boot qube from CDROM`.

Note: `[Dom0] Boot <custom>-kiosk-dvm from device` popup displays.
- `(X) from file in qube`
Select the qube you used to download the iso.
Press `...` then select the file `Porteus-Kiosk-4.7.0-x86_64.iso`.
Press `OK`

Note: Nothing happens.

In Qube Manager, right click `<custom>-kiosk-dvm`, select `Qube Settings`.

Note `[Dom0] Houston, we have a problem...` popup displays.
```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.
at line 871
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.
```

[Hide Details...] [OK]

```
----
line: 'Got empty response from qubesd. See journalctl in dom0 for '
func: _parse_qubesd_response
line no.: 81
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: return self._parse_qubesd_response(return_data)
func: qubesd_call
line no.: 483
file: /usr/lib/python3.5/site-packages/qubesadmin/app.py
----
line: payload_stream)
func: qubesd_call
line no.: 68
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: self.vm.name, 'admin.vm.feature.Get', item).decode('utf-8')
func: __getitem__
line no.: 55
file: /usr/lib/python3.5/site-packages/qubesadmin/features.py
----
line: return self[item]
func: get
line no.: 74
file: /usr/lib/python3.5/site-packages/qubesadmin/features.py
----
line: and not vm.features.get('internal', False))
func: _filter_internal
line no.: 31
file: /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: choice_list = list(choice_list)
func: prepare_choice
line no.: 74
file: /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: *args, **kwargs)
func: prepare_vm_choice
line no.: 137
file: /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: allow_default=True, allow_none=True)
func: __init_basic_tab__
line no.: 327
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: self.__init_basic_tab__()
func: __init__
line no.: 89
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: vm, self.qt_app, "basic")
func: action_settings_triggered
line no.: 871
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

**Comment by marmarta** [comment] 2018-07-16 17:00
That error looks like the VM does not exist - I've tried to reproduce the steps, and everything up to the error happens the same on the two systems I've tested it on; while the VM does not boot (I'd guess there's a problem with virtualization and that ISO..? ), Qube Settings and so on work normally. Has it occurred again? If you do encounter it again, it would be very helpful if you could check what is the output of `qvm-prefs <this-vms-name>`.

**Comment by RefinedSoftwareLLC** [comment] 2018-07-17 18:35
I re-followed these steps and couldn't reproduce the same error. But after following these steps I pressed the [Dom0] Qube Manager's "Refresh" button and got this popup error:

`[Dom0] Houston, we have a problem...`
`Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

RuntimeError: wrapped C/C++ object of type VmNameItem has been deleted
at line 888
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

----
line: self.vms_in_table[selected_qid].name_widget)
func: fill_table
line no.: 437
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.fill_table()
func: update_table
line no.: 465
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.update_table()
func: action_refresh_list_triggered
line no.: 888
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py`

**Comment by RefinedSoftwareLLC** [comment] 2018-07-17 18:58
```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

RuntimeError: wrapped C/C++ object of type VmStatusIcon has been deleted
at line 525
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

----
line: self.setPixmap(icon_pixmap)
func: set_on_icon
line no.: 184
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.set_on_icon()
func: update
line no.: 169
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.on_icon.update()
func: update_vm_state
line no.: 258
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.info_widget.update_vm_state(self.vm)
func: update
line no.: 139
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.vms_in_table[vm.qid].update()
func: update_single_row
line no.: 404
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.update_single_row(vm)
func: table_selection_changed
line no.: 525
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

**Comment by RefinedSoftwareLLC** [comment] 2018-07-17 19:01
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

RuntimeError: wrapped C/C++ object of type VmStatusIcon has been deleted
at line 873
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

----
line: self.setPixmap(icon_pixmap)
func: set_on_icon
line no.: 184
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.set_on_icon()
func: update
line no.: 169
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.on_icon.update()
func: update_vm_state
line no.: 258
file: /usr/lib/python3.5/site-packages/qubesmanager/table_widgets.py
----
line: self.info_widget.update_vm_state(self.vm)
func: update
line no.: 139
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.vms_in_table[vm.qid].update()
func: update_single_row
line no.: 404
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.update_single_row(vm)
func: action_settings_triggered
line no.: 873
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

**Comment by RefinedSoftwareLLC** [comment] 2018-07-17 19:03
```
[admin@dom0 ~]$ qvm-prefs del2-kiosk-dvm
autostart           -  True
backup_timestamp    U
debug               D  False
default_dispvm      D  whonix-ws-dvm2
default_user        D  user
gateway             D  
gateway6            D  
include_in_backups  D  True
installed_by_rpm    D  False
ip                  D  10.137.0.26
ip6                 D  
kernel              D  4.14.41-1
kernelopts          D  nopat
klass               D  StandaloneVM
label               -  red
mac                 D  00:16:3E:5E:6C:00
maxmem              D  4000
memory              -  1000
name                -  del2-kiosk-dvm
netvm               D  sys-whonix
provides_network    -  False
qid                 -  26
qrexec_timeout      D  60
start_time          D  
stubdom_mem         U
stubdom_xid         D  -1
updateable          D  True
uuid                -  eb636c60-2993-4227-bc98-ab98c9d97521
vcpus               D  2
virt_mode           D  pvh
visible_gateway     D  10.137.0.8
visible_gateway6    D  
visible_ip          D  10.137.0.26
visible_ip6         D  
visible_netmask     D  255.255.255.255
xid                 D  87
```

**Comment by RefinedSoftwareLLC** [comment] 2018-07-17 19:12
Okay, the qube isn't running (per the qube menu next to clock) but Qube Manager is showing state as yellow. In Qube Manager, if I right click and select `Qube Settings`, then press `Cancel` The `at line 873` error is consistently re-displaying.
The qube still isn't running and Qube Manager is still showing state as yellow. I am pressing Refresh button (two green arrows going in circle), Now the `at line 525` error displayed. Now the `at line 873` error is no longer happening if I open `Qube Settings` then `Cancel`.

**Comment by torjunkie** [comment] 2018-07-28 10:39
Platform: Qubes R4

VM: Qubes-Whonix 13 anon-whonix AppVM

Application: Qubes Manager

Action: Attempt to view logs of the AppVM.

Expectation: Logs displayed.

Actual Event:

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

UnsupportOperation: can't do nonzero end-relative seeks at line 1159 of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

Details:

line: log.seek(-LOG_DISPLAY_SIZE, os.SEEK_END)
func:__init_log_text__
line no.:59
file: /usr/lib/python3.5/site-packages/qubesmanager/log_dialog.py

line: self.__init_log_text__()
func:__init__
line no.:50
file: /usr/lib/python3.5/site-packages/qubesmanager/log_dialog.py

line: log_dlg = log_dialog.LogDialog(self.qt_app, log)
func: show_log
line no.: 1159
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

**Comment by marmarta** [comment] 2018-08-05 20:47
@RefinedSoftwareLLC it seems you don't have the 'testing-current' version of qubes manager - in the current version, there's no 'refresh' button. The bug you are writing about now should be fixed in that version - it's an artifact of the old way of making the manager react to VM events.

**Comment by marmarta** [comment] 2018-08-05 20:50
@torjunkie likewise, this error should be fixed by the current testing version of qubes-manager (it's this: https://github.com/QubesOS/qubes-manager/commit/4933c6b58009da48970185f9abc429a1eb792ff3 commit).

**Closed by marmarta** 2018-08-05 20:50 UTC
Labels: C: qubes-manager, bug

**Comment by vladionescu** [comment] 2018-11-30 20:14
@marmarta I'm having trouble figuring out when the refresh button was removed and what the rationale was, sorry to ask here, this is the best option I found.

**Comment by marmarta** [comment] 2018-11-30 20:23
> @marmarta I'm having trouble figuring out when the refresh button was removed and what the rationale was, sorry to ask here, this is the best option I found.

@vladionescu , it was removed because it should now work by itself, without having to force refreshes - like it was in old qubes manager.
