### ISSUE TITLE
Qubes Domains widget missing some qubes and displaying in wrong place

### ISSUE THREAD

**Issue by tzwcfq** [QubesOS/qubes-issues#7520] opened 2022-05-21 06:01 UTC
### Qubes OS release
Qubes R4.1 current-testing

### Brief summary
At some point I've noticed that some of my qubes were missing from `Qubes Domains` widget and my disposable qube was displayed at the bottom of `Qubes Domains` widget menu below `Open Qube Manager` when it should be on top below`dom0` entry.
Missing qubes are `vault` and `win7` and both of them should be right above `Open Qube Manager` entry in `Qubes Domains` widget.
When I've shutdown these qubes and opened them again they were displayed in Qubes Domains widget and were in right order.
I've attached image of how it looked:
![gui-bug](https://user-images.githubusercontent.com/104582924/169637967-a044f0cc-e123-4e5c-94b8-427e34a044cc.png)

### Steps to reproduce
Not sure how it was triggered.
Maybe it was because of resume from suspend but I couldn't reproduce it.

### Expected behavior
Qubes Domains widget show all running qubes and they are in right order.

### Actual behavior
Qubes Domains widget don't show some running qubes and some of them are in wrong order.

**Comment by DemiMarie** [comment] 2022-05-21 15:28
This is probably at least partly a core-admin-client bug.

**Comment by marmarek** [comment] 2022-05-21 15:32
Can you check qubes-core-admin-client version? 4.1.23 fixed similar issue.
Anyway, this sounds like a duplicate of https://github.com/QubesOS/qubes-issues/issues/7362

**Comment by tzwcfq** [comment] 2022-05-21 17:15
> Can you check qubes-core-admin-client version? 4.1.23 fixed similar issue.

```
$ dnf list | grep qubes-core-admin-client
qubes-core-admin-client.noarch               4.1.23-1.fc32                    @qubes-dom0-cached
```

**Comment by DemiMarie** [comment] 2022-05-21 18:19
Probably a missing cache invalidation (something like QubesOS/qubes-manager#320 but for the widget)

**Comment by tzwcfq** [comment] 2022-05-22 06:58
I had the same issue again and I didn't enter suspend after boot so it's not related to resume from suspend.
Now sys-whonix went missing and disposable qube went to the bottom again.
![gui-bug2](https://user-images.githubusercontent.com/104582924/169682973-b891f2db-8472-46c0-b766-245b5efe88c2.png)

**Comment by tzwcfq** [comment] 2022-05-22 07:20
This really seems to be a duplicate of https://github.com/QubesOS/qubes-issues/issues/7362.
I can trigger this issue at every time at boot if I quickly start 2 more VMs after login aside from 4 VMs that are configured for autostart at boot.

**Closed** 2022-05-22 07:24 UTC
Labels: T: bug, C: core, C: manager/widget, P: default, needs diagnosis, updates testing
