### ISSUE TITLE
Problems with restore backup

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#3216] opened 2017-10-26 08:04 UTC
#### Affected TemplateVMs: 

---

### General notes:

---

#### Related issues:

Hi, from a long time I used Qubes OS R3.2. But I wanted install version
R4.0-rc2. I maked backup with encryption and save it on my second partition.
After this I installed Qubes OS R4.0 with encrypt my Qubes partition.
After this I run Qubes R4.0 and run command qubes-backup-restore (all this
is on photo) and I tryed restore my VM but I saw problems. But when I
click menu I see all my restored VM.
All is on photos and in log file.
Immediately after installation of Qubes OS R4.0 I run update dom0 , even
fedora template and even debiant template I upgraded. After all upgrades I
tried restore backup.

https://imgur.com/a/TZKd9  (photos)
https://0bin.net/paste/Y5heHwSf+y0bNUaE#B2Aj5nWAs6gnL4nPS4Lol0MHWjo8B8F3kALQpsbstFc
  (log)

It is link to my post on Google Group:
https://groups.google.com/forum/m/#!topic/qubes-users/4jWs4X08urc

**Comment by na--** [comment] 2017-10-26 11:34
Can you try running `qvm-backup-restore` with the `--verify-only` flag? I had some issues with restoring 3.2 backups, but in my case I think the errors were due to my disk getting full.

**Comment by toxub23** [comment] 2017-10-26 20:19
I don't know bu

**Comment by toxub23** [comment] 2017-10-26 20:23
I don't know but administrator of Qubes OS IRC channel said that is problem with python packages. And I believe him.

**Comment by andrewdavidwong** [comment] 2017-10-27 00:42
@marmarek, is this a duplicate of #3167?

**Comment by toxub23** [comment] 2017-10-29 21:27
No.

**Closed** 2023-08-05 09:15 UTC
Labels: T: bug, C: core, eol-4.0
