### ISSUE TITLE
qubesctl state.sls qvm.anon-whonix [ERROR   ] Command ['dnf', '--quiet', 'clean', 'expire-cache', '--disablerepo=*', '--enablerepo=qubes-templates-community-testing'] failed with return code: 1

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4154] opened 2018-07-27 11:37 UTC
### Qubes OS version:
R3.2

### Affected component(s): 
dom0

---

### Steps to reproduce the behavior:
Requires https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/14#issuecomment-408376428

    sudo qubesctl state.sls qvm.anon-whonix

### Expected behavior:

No such error.

### Actual behavior:

```
[user@dom0 ~]$ sudo qubesctl state.sls qvm.anon-whonix
[ERROR   ] Command ['dnf', '--quiet', 'clean', 'expire-cache', '--disablerepo=*', '--enablerepo=qubes-templates-community-testing'] failed with return code: 1                                                                                                                
[ERROR   ] output: Error: Unknown repo: 'qubes-templates-community-testing'
```

```

root     16360  0.0  0.2 228980  6412 pts/18   S+   18:11   0:00 sudo qubesctl state.sls qvm.anon-whonix
root     16361  0.1  1.8 523220 51100 pts/18   S+   18:11   0:00 /usr/bin/python /bin/qubesctl state.sls qvm.anon-whonix
root     16366  1.9  2.9 633456 81880 pts/18   S+   18:11   0:05 /usr/bin/python /bin/qubesctl --dom0-only state.sls qvm.anon-whonix
root     16555  0.0  0.0   9636  2624 pts/18   S+   18:11   0:00 /bin/bash /bin/qubes-dom0-update -y --best --allowerasing --disablerepo=* --enablerepo=qubes-templates-community-testing --clean qubes-template-whonix-ws-14
root     16583  0.0  1.2 332408 33812 pts/18   S+   18:11   0:00 /usr/bin/python2 /bin/qvm-run --nogui --pass-io sys-firewall script --quiet --return --command '/usr/lib/qubes/qubes-download-dom0-updates.sh --doit --nogui --exclude=qubes-template-fedora-25,qubes-template-whonix-gw,qubes-template-whonix-ws,qubes-template-fedora-26, -y --best --allowerasing --disablerepo=* --enablerepo=qubes-templates-community-testing --clean qubes-template-whonix-ws-14' /dev/null
root     16586  0.0  0.1  54108  3012 pts/18   SL+  18:11   0:00 /usr/lib/qubes/qrexec-client -d sys-firewall user:script --quiet --return --command '/usr/lib/qubes/qubes-download-dom0-updates.sh --doit --nogui --exclude=qubes-template-fedora-25,qubes-template-whonix-gw,qubes-template-whonix-ws,qubes-template-fedora-26, -y --best --allowerasing --disablerepo=* --enablerepo=qubes-templates-community-testing --clean qubes-template-whonix-ws-14' /dev/null
root     16588  0.0  0.0      0     0 ?        I    18:11   0:00 [kworker/u16:1]
user     16596  0.0  0.1 122696  5132 pts/5    Ss   18:12   0:00 /bin/bash
root     16645  0.0  0.0      0     0 ?        I    18:14   0:00 [kworker/2:2]
user     16661  0.0  0.1 157760  3884 pts/5    R+   18:16   0:00 ps aux
```

### General notes:

I expect this to be a usability issues. Users are likely to abort after reading this error.

---

### Related issues:

https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/14

**Comment by marmarek** [comment] 2018-07-27 12:20
Oh, it looks like we already have an issue for this: #3188
That was about R4, so the only thing to do is to backport the fix to R3.2.

**Comment by andrewdavidwong** [comment] 2018-07-28 04:33
Not closing this as a duplicate of #3188 since it has already been referenced in a commit message.

**Closed** 2018-10-07 21:11 UTC
Labels: C: Whonix, C: mgmt, bug, duplicate, r3.2-dom0-stable
