### ISSUE TITLE
Qubes VM widget displays incorrect states, prevents user from shuting down VMs

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3937] opened 2018-05-29 08:11 UTC
For about half of active qubes I see the "starting up" notifications (spinning circles) that won't go away forever. The context menu then allows only killing the VM, rather than cleanly shutting down.

**Comment by marmarek** [comment] 2018-05-29 10:17
Duplicate of #3660

**Comment by rootkovska** [comment] 2018-07-11 10:47
With latest updates installed in dom0 (from current), this problem still persists.

**Comment by marmarek** [comment] 2018-07-11 11:18
This is still a duplicate of #3660 - see status there (the fix is in current-testing).

**Closed by marmarek** 2018-07-11 11:18 UTC
Labels: P: critical, UX, bug, duplicate
