### ISSUE TITLE
Qubes Attachments is incompatible with Thunderbird 78.5.0

### ISSUE THREAD

**Issue by tk-47** [QubesOS/qubes-issues#6240] opened 2020-11-28 23:05 UTC
**Qubes OS version**

Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**

The Qubes Attachments default-add on in Thunderbird 78.5.0 is inoperable.

**Brief summary**

Qubes Attachments (disabled)
Qubes actions for attachments like "Open in DVM" or "Send to VM"
Qubes Attachments is incompatible with Thunderbird 78.5.0.
Author
Marek Marczykowski@Invisible Things Lab
Version
2.0.5
Last Updated
November 18, 2020
Homepage
http://www.qubes-os.org/

**How Reproducible**

**To Reproduce**

1. Open Thunderbird (78,5,0)
2. Settings
3. Add-ons

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Qubes extension will break in Thunderbird 78 #5861
https://github.com/QubesOS/qubes-issues/issues/5861

**Comment by DemiMarie** [comment] 2020-11-29 00:57
Duplicate of #5861.  The short version is that this is a known problem, but fixing it in a maintainable way will likely require collaboration with Mozilla.

**Closed by DemiMarie** 2020-11-29 00:57 UTC
Labels: P: default, R: duplicate, T: bug
