### ISSUE TITLE
updated fedora29 TVM to just released version 30, and can not dnf upgrade the TVM

### ISSUE THREAD

**Issue by bidelakbari** [QubesOS/qubes-issues#5025] opened 2019-05-07 15:15 UTC
My Qubes version is 4.0.1

I don't know whether I had to wait for fedora 30 upgrade or not but I followed this page in user documentation section: "Upgrading the Fedora 27 Template to Fedora 28" and upgraded my fedora TVM. (changing old values with new one of course)

everything is working as expected but I can not upgrade the newly created template. 
I get this error: <code>failed to synchronize cache for repo 'fedora-modular'</code>

one thing: when I use the updater GUI [Dom0] Qubes Updater, a TVM pops up with the name "disp-mgmt-fedora-30" and when update errors, it disappears again

I googled the issue and came across issue #3557 [](https://github.com/QubesOS/qubes-issues/issues/3557) and the output of <code>journalctl --boot | grep qubes-updates-proxy</code> has some errors indeed:

<pre>
qubes-updates-proxy.service: failed at step EXEC spawning /usr/sbin/tinyproxy: No such file or directory
</pre>

any thoughts?

**Comment by marmarek** [comment] 2019-05-07 15:39
> qubes-updates-proxy.service: failed at step EXEC spawning /usr/sbin/tinyproxy: No such file or directory

It's this: #4973 
The fix is already in current-testing. To install it, switch whatever you use as updates proxy (sys-net by default) back to previous template.

**Comment by marmarek** [comment] 2019-05-07 15:40
Duplicate of #4973

**Closed by marmarek** 2019-05-07 15:39 UTC
Labels: P: default, T: bug
