### ISSUE TITLE
Provide full gpu support including opengl

### ISSUE THREAD

**Issue by student-sx** [QubesOS/qubes-issues#1942] opened 2016-05-03 11:47 UTC
I would like to use qubes os as my production system but I need for work full graphics support with opengl features. 

So I ask for a feature request to make is possible to enable full gpu support in an appvm. 

For my case I need it on a laptop with optimus (i.e. an internal intel card and a discrete nvidia card; in my case Quadro K2000M) and I want the gpu to be fully available in an fedora based appvm.

It would be sufficient for me to assign the nvidia card just to one domain.

**Comment by marmarek** [comment] 2016-05-03 12:06
Looks like a duplicate of #1659

**Closed by marmarek** 2016-05-03 12:06 UTC
Labels: duplicate
