### ISSUE TITLE
Edit in VM not working

### ISSUE THREAD

**Issue by DOEResearch** [QubesOS/qubes-issues#5036] opened 2019-05-13 21:05 UTC
### Qubes OS version:

4.0 (R4.0)
Windows tools 4.0.1-3

### Affected component(s) or functionality:

"Edit in VM" Windows "SendTo" shortcut
"Edit in dispVM" Windows "SendTo" shortcut

---

### Steps to reproduce the behavior:

In windows 7, Right-click a document or file > SendTo > Edit in VM
In windows 7, Right-click a document or file > SendTo > Edit in dispVM

### Expected or desired behavior:

File opens in another VM (windows, linux)

### Actual behavior:

Command prompt window appears then disappears. Receiving VM/dispVM appears to start, however the file does not open.

### General notes:

It appears STDIN is not sending over the file name/content.

---

**Comment by andrewdavidwong** [comment] 2019-05-14 05:12
Possible duplicate of #3585.

**Comment by tomc797** [comment] 2019-05-18 05:29
I believe I've addressed the problem in pull request https://github.com/QubesOS/qubes-core-agent-windows/pull/1

Previously qrexec-wrapper would deadlock as it did not handle EOF correctly.

**Closed** 2023-08-05 09:20 UTC
Labels: T: bug, help wanted, C: windows-tools, P: default, eol-4.0
