### ISSUE TITLE
Issue with File Transfer with Emojis

### ISSUE THREAD

**Issue by vzvva** [QubesOS/qubes-issues#9567] opened 2024-11-09 21:48 UTC
Hi,

In Fedora 39 with the Xfce desktop environment and Thunar file manager, I can't send files with emojis. When I use the "Copy to other Qube" and "Move to other Qube" buttons, I receive the following error:

`qfile-agent: Fatal error: File copy: "Unknown error -84; Last file: Korn - Requiem (2022) Mp3 320kbps [PMEDIA] ______" (error type: Unknown error -84)`

A screenshot of the filename is attached.
`Korn - Requiem (2022) Mp3 320kbps [PMEDIA] ⭐️`

When I use the following commands, I get the same error:

```
/usr/bin/qvm-copy
/usr/bin/qvm-move
```

This bug seems to be related to issue #9506.

![Screenshot_2024-11-09_12-28-36](https://github.com/user-attachments/assets/62e29f12-c7b9-41da-aa33-5685f575fe57)

**Comment by DemiMarie** [comment] 2024-11-09 21:59
I think this is a duplicate of #9506 which is fixed in the testing repository.

**Comment by vzvva** [comment] 2024-11-09 22:06
I upgraded Fedora 39 to the testing repository using the following command:
`sudo dnf update --enablerepo=qubes-vm-r4.2-current-testing`
#9506 is fixed, but this new bug has appeared."

**Comment by DemiMarie** [comment] 2024-11-09 22:32
Did you upgrade your destination qube?

**Comment by vzvva** [comment] 2024-11-09 22:41
I checked now, and both AppVMs are using the same template, which has been updated to the testing repository. Files with emojis are causing errors.

**Comment by vzvva** [comment] 2024-11-09 22:51
Sorry, one point: the folder has this issue.
You can reproduce it like this:

```
mkdir  "Korn - Requiem (2022) Mp3 320kbps [PMEDIA] ⭐️"
qvm-copy Korn\ -\ Requiem\ \(2022\)\ Mp3\ 320kbps\ \[PMEDIA\]\ ⭐️
```

`qfile-agent: Fatal error: File copy: "Unknown error -84; Last file: Korn - Requiem (2022) Mp3 320kbps [PMEDIA] ______" (error type: Unknown error -84)
`

**Closed** 2024-11-15 14:49 UTC
Labels: T: bug, C: core, P: default, diagnosed, pr submitted, affects-4.2
