### ISSUE TITLE
Debian 9: libxen (libxenlight) has wrong SONAME for debian packages

### ISSUE THREAD

**Issue by cshoredaniel** [QubesOS/qubes-issues#3944] opened 2018-06-01 01:17 UTC
### Qubes OS version:

VERSION="4.0 (R4.0)"

### Affected component(s): 

Debian 9 templates and vm's with non-qubes packages which depend on libxenlight (from libxen)

---

### Steps to reproduce the behavior:

1. Install a package which depends on libxenlight (e.g. guestfish) and which doesn't exist in the qubes repository, but only in debian.
2. Run the program (e.g. `guestfish -h`)

### Expected behavior:

1. Program should run (in this case displaying help message).

### Actual behavior:

Get an error message such as:
```
guestfish: error while loading shared libraries: libxenlight-4.8.so: cannot open shared object file: No such file or directory
```

### General notes:

1. In debian packages for the same library with different SOVERSION are supported by appending `-X.Y` to the library name: e.g. `libxenlight-4.8.so.4.8.1` etc.
2. What's actually the case for Qubes repo: `dpkg -S libxen*|grep light`
```
libxen-dev: /usr/lib/x86_64-linux-gnu/libxenlight.a
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenlight.so.4.8.1.0
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenlight.so.4.8.1
libxen-dev: /usr/lib/x86_64-linux-gnu/libxenlight.so
``` 

---

### Related issues:

Fedora 28 SOVERSION is newer than Qubes repos for Fedora 28 for libxenlight (bug to be created), so qemu can't be installed in Fedora 28 template

**Comment by unman** [comment] 2018-09-01 02:14
It seems to me that the Qubes naming convention for these shared libraries is entirely in accord with Debian policy, and the Xen package isn't. (I think General note 1 is just wrong.)
That said, it seems obvious that we should follow the convention followed by the Debian package. I'm somewhat reluctant to make the change in a version. @marmarek What do you think? Change it now or update at the next major version change ?(4.10?)

**Comment by cshoredaniel** [comment] 2018-09-01 09:01
@unman It's not done for evry package in Debian only ones where there is considered a compelling reason to keep multiple library versions side-by-side (which is relatively rare).  Usually in situations like the libusb 1.0 vs 0.1 or gstreamer transition.

I'm not terribly worried about seeing it before 4.10 so don't rush on my account (not thinking that it's a huge issue for a lot of people).

**Comment by owenh000** [comment] 2018-09-02 02:16
>not thinking that it's a huge issue for a lot of people

I would really like to see a fix for this, because it breaks qemu also:

```
$ qemu-system-x86_64
qemu-system-x86_64: error while loading shared libraries: libxenctrl-4.8.so: cannot open shared object file: No such file or directory
```

**Comment by marmarek** [comment] 2018-09-02 02:45
@HW42 do you remember why exactly changing soname to 4.8.1 was needed? If that's only about API used by qubes tools, manual package dependencies (Requires/Conflicts) should be enough instead.

**Comment by HW42** [comment] 2018-09-02 03:04
Because `patch-stubdom-linux-0004.patch`, `patch-stubdom-linux-config-qubes-gui.patch` and `patch-stubdom-linux-config-stubdom-mem.patch` are changing the ABI (Not sure that I did not forget a patch). So everything which uses the `libxl_domain_build_info` struct needs to be updated (most importantly libvirt). This should all be dom0 only.

It should be possible to cover this with manual dependencies but you need to keep this in mind if you see strange failures, since such ABI incompatibilities can have weird effects.

**Comment by daniel-ayers** [comment] 2018-09-26 05:57
Today I need to copy some files from a qcow2 image and it can't be done in either fedora-28 or debian-9 based VMs because in both distros the xen related packages are broken in different ways.

libguestfs-tools depends on libxen-4.8 (via libvirt0).  A qubes version of that is installed in the template.  That package should provide the following files:

```
$ apt-file list libxen-4.8
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxencall-4.8.so.1
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxencall-4.8.so.1.0
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenctrl-4.8.so
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenevtchn-4.8.so.1
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenevtchn-4.8.so.1.0
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenforeignmemory-4.8.so.1
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenforeignmemory-4.8.so.1.0
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxengnttab-4.8.so.1
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxengnttab-4.8.so.1.1
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenguest-4.8.so
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxenlight-4.8.so
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxentoollog-4.8.so.1
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxentoollog-4.8.so.1.0
libxen-4.8: /usr/lib/x86_64-linux-gnu/libxlutil-4.8.so
libxen-4.8: /usr/share/bug/libxen-4.8/control
libxen-4.8: /usr/share/doc/libxen-4.8/changelog.Debian.gz
libxen-4.8: /usr/share/doc/libxen-4.8/changelog.gz
libxen-4.8: /usr/share/doc/libxen-4.8/copyright
```

It doesn't.

```
$ apt-file list libxen-4.8 | awk -F: '{print $2}' | tr -d ' ' | xargs file
/usr/lib/x86_64-linux-gnu/libxencall-4.8.so.1:            cannot open `/usr/lib/x86_64-linux-gnu/libxencall-4.8.so.1' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxencall-4.8.so.1.0:          cannot open `/usr/lib/x86_64-linux-gnu/libxencall-4.8.so.1.0' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenctrl-4.8.so:              cannot open `/usr/lib/x86_64-linux-gnu/libxenctrl-4.8.so' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenevtchn-4.8.so.1:          cannot open `/usr/lib/x86_64-linux-gnu/libxenevtchn-4.8.so.1' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenevtchn-4.8.so.1.0:        cannot open `/usr/lib/x86_64-linux-gnu/libxenevtchn-4.8.so.1.0' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenforeignmemory-4.8.so.1:   cannot open `/usr/lib/x86_64-linux-gnu/libxenforeignmemory-4.8.so.1' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenforeignmemory-4.8.so.1.0: cannot open `/usr/lib/x86_64-linux-gnu/libxenforeignmemory-4.8.so.1.0' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxengnttab-4.8.so.1:          cannot open `/usr/lib/x86_64-linux-gnu/libxengnttab-4.8.so.1' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxengnttab-4.8.so.1.1:        cannot open `/usr/lib/x86_64-linux-gnu/libxengnttab-4.8.so.1.1' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenguest-4.8.so:             cannot open `/usr/lib/x86_64-linux-gnu/libxenguest-4.8.so' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxenlight-4.8.so:             cannot open `/usr/lib/x86_64-linux-gnu/libxenlight-4.8.so' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxentoollog-4.8.so.1:         cannot open `/usr/lib/x86_64-linux-gnu/libxentoollog-4.8.so.1' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxentoollog-4.8.so.1.0:       cannot open `/usr/lib/x86_64-linux-gnu/libxentoollog-4.8.so.1.0' (No such file or directory)
/usr/lib/x86_64-linux-gnu/libxlutil-4.8.so:               cannot open `/usr/lib/x86_64-linux-gnu/libxlutil-4.8.so' (No such file or directory)
/usr/share/bug/libxen-4.8/control:                        cannot open `/usr/share/bug/libxen-4.8/control' (No such file or directory)
/usr/share/doc/libxen-4.8/changelog.Debian.gz:            gzip compressed data, max compression, from Unix
/usr/share/doc/libxen-4.8/changelog.gz:                   gzip compressed data, max compression, from Unix
/usr/share/doc/libxen-4.8/copyright:                      ASCII text
```

At the risk of stating the obvious, a "debian" template that includes packages that don't provide the files that the rest of the debian packages expect that package to provide isn't a great deal of use.

**Comment by 99ninetynine** [comment] 2018-10-04 13:56
Qemu works only on bionic template for me.

fedora 28 

`[user@coding test]$ sudo dnf install qemu
Last metadata expiration check: 5:32:48 ago on Thu 04 Oct 2018 11:20:12 AM MSK.
Error: 
 Problem: package qemu-system-xtensa-core-2:2.11.1-2.fc28.x86_64 requires libxenctrl.so.4.10()(64bit), but none of the providers can be installed
  - cannot install both xen-libs-2001:4.8.3-7.fc28.x86_64 and xen-libs-4.10.1-6.fc28.x86_64
  - cannot install both xen-libs-2001:4.8.3-7.fc28.x86_64 and xen-libs-4.10.0-8.fc28.x86_64
  - package xen-qubes-vm-2001:4.8.3-7.fc28.x86_64 requires libxenctrl.so.4.8()(64bit), but none of the providers can be installed
  - problem with installed package xen-qubes-vm-2001:4.8.4-2.fc28.x86_64
  - package xen-qubes-vm-2001:4.8.3-8.fc28.x86_64 requires xen-libs = 2001:4.8.3-8.fc28, but none of the providers can be installed
  - cannot install both xen-libs-2001:4.8.3-8.fc28.x86_64 and xen-libs-4.10.1-6.fc28.x86_64
  - cannot install both xen-libs-2001:4.8.3-8.fc28.x86_64 and xen-libs-4.10.0-8.fc28.x86_64
  - package qemu-system-xtensa-2:2.11.1-2.fc28.x86_64 requires qemu-system-xtensa-core = 2:2.11.1-2.fc28, but none of the providers can be installed
  - package qemu-2:2.11.1-2.fc28.x86_64 requires qemu-system-xtensa = 2:2.11.1-2.fc28, but none of the providers can be installed
  - conflicting requests
  - package qemu-2:2.11.2-4.fc28.x86_64 requires qemu-system-xtensa = 2:2.11.2-4.fc28, but none of the providers can be installed
  - package qemu-system-xtensa-2:2.11.2-4.fc28.x86_64 requires qemu-system-xtensa-core = 2:2.11.2-4.fc28, but none of the providers can be installed
  - package qemu-system-xtensa-core-2:2.11.2-4.fc28.x86_64 requires libxenctrl.so.4.10()(64bit), but none of the providers can be installed
  - package xen-qubes-vm-2001:4.8.4-1.fc28.x86_64 requires xen-libs = 2001:4.8.4-1.fc28, but none of the providers can be installed
  - cannot install both xen-libs-2001:4.8.4-1.fc28.x86_64 and xen-libs-4.10.1-6.fc28.x86_64
  - cannot install both xen-libs-2001:4.8.4-1.fc28.x86_64 and xen-libs-4.10.0-8.fc28.x86_64
  - package xen-qubes-vm-2001:4.8.4-2.fc28.x86_64 requires xen-libs = 2001:4.8.4-2.fc28, but none of the providers can be installed
  - cannot install both xen-libs-2001:4.8.4-2.fc28.x86_64 and xen-libs-4.10.1-6.fc28.x86_64
  - cannot install both xen-libs-2001:4.8.4-2.fc28.x86_64 and xen-libs-4.10.0-8.fc28.x86_64
  - cannot install both xen-libs-4.10.1-6.fc28.x86_64 and xen-libs-2001:4.8.4-2.fc28.x86_64
  - cannot install both xen-libs-4.10.0-8.fc28.x86_64 and xen-libs-2001:4.8.4-2.fc28.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
`
debian 9

`user@flash-builder:~$ qemu-system-x86_64 
qemu-system-x86_64: error while loading shared libraries: libxenctrl-4.8.so: cannot open shared object file: No such file or directory
`

**Closed** 2018-10-08 12:10 UTC
Labels: C: Debian, bug

**Comment by daniel-ayers** [comment] 2018-10-08 21:42
Thank you for working on this @marmarek - really helps those of us who need to run/develop virtualization related stuff.  Hopefully the Fedora equivalent issue can be addressed also https://github.com/QubesOS/qubes-issues/issues/3945.

**Comment by andrewdavidwong** [comment] 2018-10-23 23:55
> add please fedora 29 affected from

This is covered by #3945.

**Comment by kchr** [comment] 2018-10-27 11:09
Confirmed to work fine for Debian stretch templates.
