### ISSUE TITLE
usb attach failure

### ISSUE THREAD

**Issue by loftlifter31** [QubesOS/qubes-issues#9605] opened 2024-11-25 19:56 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.3

### Brief summary
Trying to pass a usb device (phone) to an app qube results in a pop up error that qubesd passed an empty response and this in the journalctl log.

Nov 25 14:23:36 dom0 qrexec-policy-daemon[2365]: qrexec: qubes.USB+4-3: phone-admin -> sys-usb: allowed to sys-usb
Nov 25 14:23:41 dom0 qubesd[2361]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.usb.Attach' dest=b'phone-admin' arg=b'sys-usb+4-3' len(untrusted_payload)=0
Nov 25 14:23:41 dom0 qubesd[2361]: Traceback (most recent call last):
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 634, in on_device_attach_usb
Nov 25 14:23:41 dom0 qubesd[2361]:     await vm.run_service_for_stdio('qubes.USBAttach',
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1596, in run_service_for_stdio
Nov 25 14:23:41 dom0 qubesd[2361]:     raise subprocess.CalledProcessError(p.returncode,
Nov 25 14:23:41 dom0 qubesd[2361]: subprocess.CalledProcessError: Command 'qubes.USBAttach' returned non-zero exit status 1.
Nov 25 14:23:41 dom0 qubesd[2361]: During handling of the above exception, another exception occurred:
Nov 25 14:23:41 dom0 qubesd[2361]: Traceback (most recent call last):
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubes/api/__init__.py", line 297, in respond
Nov 25 14:23:41 dom0 qubesd[2361]:     response = await self.mgmt.execute(
Nov 25 14:23:41 dom0 qubesd[2361]:         
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubes/api/admin.py", line 1306, in vm_device_attach
Nov 25 14:23:41 dom0 qubesd[2361]:     await self.dest.devices[devclass].attach(assignment)
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 251, in attach
Nov 25 14:23:41 dom0 qubesd[2361]:     await self._vm.fire_event_async('device-pre-attach:' + self._bus,
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 234, in fire_event_async
Nov 25 14:23:41 dom0 qubesd[2361]:     effect = task.result()
Nov 25 14:23:41 dom0 qubesd[2361]:              ^^^^^^^^^^^^^
Nov 25 14:23:41 dom0 qubesd[2361]:   File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 648, in on_device_attach_usb
Nov 25 14:23:41 dom0 qubesd[2361]:     sanitized_stderr = santizied_stderr[:-2] + "."
Nov 25 14:23:41 dom0 qubesd[2361]:                        ^^^^^^^^^^^^^^^^

### Steps to reproduce

1. connect usb device
2. attach usb device to app qube

### Expected behavior

device attaches

### Actual behavior

doesn't attach, generates error above

**Comment by marmarek** [comment] 2024-11-25 21:13
duplicate of https://github.com/QubesOS/qubes-issues/issues/9545

**Closed** 2024-11-25 21:13 UTC
Labels: T: bug, R: duplicate, P: default

**Comment by loftlifter31** [comment] 2024-11-25 22:04
This is not a duplicate. There is a bug in the error handler which was referenced in the issue you linked to, and that does show up here as well because it affects everyone on 4.2, but there is another error beyond that. See the first 15 lines of the error log I posted above.

**Comment by marmarek** [comment] 2024-11-25 22:18
Then please try with the fixed package (it's in current-testing repo) and see what happens.

**Comment by loftlifter31** [comment] 2024-12-04 19:29
Ok. I get a new error now. "Device attach failed /usr/lib/qubes/usb-import line 94: echo: write error: Inavlid argument
This is a toast notification. I don't see anything in journalctl. This error happens when I try to attach an android phone with  adb over usb enabled.
