### ISSUE TITLE
"Files" file manager fails to start

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#2863] opened 2017-06-22 07:16 UTC
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Fedora 23, Fedora 24, and also upgraded to Fedora 25

---

### Expected behavior:

When clicking on "FIles" for the file manager in the start menu, the file manager should start.

### Actual behavior:

Quite often, the file manager will NOT start on the first attempt - whether or not the VM is already running, or is started at this occasion.

No error message, just "nothing happens".

Most of the times, the file manager will start properly on the 2dn attempt (but I've sometimes seen it fail twice and start at the 3rd attempt).

### Steps to reproduce the behavior:

Start "Files" from the start menu, in any VM.

### General notes:

Same issue noticed on 3 different machinesj separate Qubes 3.2 installs, and in all Fedora AppVMs

No other application shows this behaviour. Only "Files".

---

**Comment by andrewdavidwong** [comment] 2017-06-23 02:35
Duplicate of #2449.

**Closed by andrewdavidwong** 2017-06-23 02:35 UTC
