### ISSUE TITLE
Microphone cannot be attached to AppVM using device manager menu

### ISSUE THREAD

**Issue by tetrahedras** [QubesOS/qubes-issues#5293] opened 2019-09-04 12:21 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Device manager widget menu

**Brief summary**
Attaching mic to an AppVM (debian or fedora) using the device manager menu bar widget does not work, detaching works

**To Reproduce**
1. click the device manager menu widget
2. select microphone
3. choose a VM
4. verify audio is not being passed to VM and the microphone has not been attached (it is not shown as attached in the drop-down menu)

**Expected behavior**
Menu attaches microphone

**Actual behavior**
Nothing happens when you try to attach

**Additional context**
Menu can detach microphone if you attach it with command-line tools

**Solutions you've tried**
`qvm-device mic attach myvm dom0:mic` works

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/external-audio/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4637

**Comment by marmarek** [comment] 2019-09-04 13:51
What version of `qubes-desktop-linux-manager` package do you have in dom0 (check with `rpm -q`)? [Similar issue](https://github.com/QubesOS/qubes-issues/issues/4999) was fixed not long ago, [the update](https://github.com/QubesOS/updates-status/issues/1177) is still in [testing repository](https://www.qubes-os.org/doc/testing/)

**Comment by tetrahedras** [comment] 2019-09-08 05:30
qubes-desktop-linux-manager-4.0.18-1.fc25.noarch

Looks like I managed to miss #4999 when I searched for related issues...

**Comment by andrewdavidwong** [comment] 2019-11-03 09:35
I am unable to reproduce this with `qubes-desktop-linux-manager-4.0.22-1.fc25.noarch`. @tetrahedras (or anyone), are you still able to reproduce this problem with that version or later?

**Comment by andrewdavidwong** [comment] 2019-11-03 09:37
Also related: #4718

**Comment by tetrahedras** [comment] 2019-11-05 03:42
It's fixed now for me.

**Comment by andrewdavidwong** [comment] 2019-11-06 04:47
> It's fixed now for me.

Glad to hear it! In that case, I'm closing this as resolved. If anyone believes the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-11-06 04:47 UTC
Labels: C: manager/widget, P: default, T: bug
