### ISSUE TITLE
Qubes-4.2.202308081030-x86_64 doesn't boot from ISO (Heads)

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#8443] opened 2023-08-23 04:49 UTC
@marmarek : Testing Qubes-4.2.202308081030-x86_64: stays stuck at boot where iso is verified against sig, both with latest kernel (6.4.7-1) and normal kernel option from grub menu 
Last dmesg message is : `loop0: detected capacity change from 0 to 12611036`. 
After a long wait:
![signal-2023-08-23-003825](https://github.com/QubesOS/updates-status/assets/827570/d24d7f6a-a850-4305-a59b-6df4e9a3c272)

For which inst.repo= is passed:
![signal-2023-08-23-004456](https://github.com/QubesOS/updates-status/assets/827570/a1b96e75-e02c-46b0-a3ca-9c8eccd7e0dd)

It finally landed on recovery shell. Here is the rdosreport.txt:
[rdsosreport.txt](https://github.com/QubesOS/qubes-issues/files/12415256/rdsosreport.txt)

So not sure what cause that regression @marmarek.

Qubes 4.2.202305060901 boots installer fine in both latest kernel (6.2.?) and normal kernel.

> Originally posted under https://github.com/QubesOS/updates-status/issues/3940#issuecomment-1689242487
> cross-posting at  https://forum.qubes-os.org/t/qubes-os-4-2-signed-weekly-builds/16929/50?u=insurgo

**Comment by marmarek** [comment] 2023-08-23 09:22
Duplicate of https://github.com/QubesOS/qubes-issues/issues/8422

**Closed by marmarek** 2023-08-23 09:22 UTC
Labels: T: bug, C: installer, P: default, needs diagnosis, affects-4.2

**Comment by andrewdavidwong** [comment] 2023-08-23 09:50
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
