### ISSUE TITLE
Unversioned dependency of pulseaudio-qubes Debian package on pulseaudio

### ISSUE THREAD

**Issue by a-barinov** [QubesOS/qubes-issues#4201] opened 2018-08-10 08:36 UTC
### Qubes OS version:

4.0

### Affected component(s): 

pulseaudio-qubes

---

### Steps to reproduce the behavior:

Upgrade Debian qube to unstable

### Expected behavior:

Either working sound in upgraded qube or suggested removal of pulseaudio-qubes

### Actual behavior:

No sound in upgraded qube due to mismatched ABI of qubes pulseaudio plugin (v10) and upgraded pulseaudio (v11) 

### General notes:

Debian package of pulsaudio-qubes has unversioned dependency on pulseaudio while in fact the plugin provided by this package depends on ABI v10 and does not work with ABI v11. This leads to no sound from qubes which are updated to Debian 10 or unstable. To fix the problem pulsaudio-qubes shoud depend on pulseaudio < 11.

---

**Comment by andrewdavidwong** [comment] 2018-08-11 00:45
Duplicate of #3454

**Comment by andrewdavidwong** [comment] 2018-08-11 00:45
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-11 00:45 UTC
