### ISSUE TITLE
Qube Manager 4.0 start error

### ISSUE THREAD

**Issue by erasmo52** [QubesOS/qubes-issues#4481] opened 2018-11-06 17:24 UTC
### Qubes OS version:

Qubes OS version: 4.0
I updated the dom0 last 26 Oct and today I started the system again all seem to work fine and there is no further updates for dom0, but I am unable to start the Qube Manager.
When I try to start it I receive the following error:

[Qube_Manager_Error.txt](https://github.com/QubesOS/qubes-issues/files/2554358/Qube_Manager_Error.txt)

I tried to restart some few times the system, but I received always the same error.
Hope to receive some feedback to fix it.
Thanks everybody
Erasmo

### Affected component(s): 

---

### General notes:

---

**Comment by TNTBOMBOM** [comment] 2018-11-06 19:08
not good to upload .txt while you can post it here: 

````
{
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

Error: g-dbus-error-quark: 
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: 
The name org.qubes.DomainManager1 was not provided by any .service files (2)
at line 9
of file /usr/bin/qubes-qube-manager.

Details:
----
line: 0, timeout_to_glib(timeout), None)
func: get
line no.: 47
file: /usr/lib/python3.5/site-packages/pydbus/proxy.py
----
line: manager = self.bus.get("org.qubes.DomainManager1")
func: __init__
line no.: 391
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: manager_window = VmManagerWindow(qt_app, qubes_app)
func: main
line no.: 1332
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: load_entry_point('qubesmanager==4.0.19', 'console_scripts', 'qubes-qube-manager')()
func: <module>
line no.: 9
file: /usr/bin/qubes-qube-manager
}
````

**Comment by erasmo52** [comment] 2018-11-08 08:08
Well, only this morning I could try the "donob4n" suggestions.
1) my  qubes-manager version is 4.0.19-1 fc25.
2) I am using only stable repository and I have onionized all dom0 repositories and I update dom0 over sys-whonix.
3) if I try to run: sudo qubes-dom0-update --refresh, I receive the following message: 
Command line error: no such option: --refresh
Usage: "yumdownloader [options] package1 [package2] [package..]
Command line error: no such option: --refresh
4) if I try to run sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing, I receive the following message: 
Error: Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current-testing. Please verify its path and try again
Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current-testing. Please verify its path and try again

Then here we are.
Thanks for your attention

**Comment by donob4n** [comment] 2018-11-08 09:00
> Well, only this morning I could try the "donob4n" suggestions.
> 
>     1. my  qubes-manager version is 4.0.19-1 fc25.
It seems the last stable version so probably you have some problem with Qubes dbus.
> 
>     2. I am using only stable repository and I have onionized all dom0 repositories and I update dom0 over sys-whonix.
> 
>     3. if I try to run: sudo qubes-dom0-update --refresh, I receive the following message:
>        Command line error: no such option: --refresh
>        Usage: "yumdownloader [options] package1 [package2] [package..]
>        Command line error: no such option: --refresh

This happens because you are using a debian-based updateVM. But it won't help since you seem already using the latest stable version.
 
>     4. if I try to run sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing, I receive the following message:
>        Error: Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current-testing. Please verify its path and try again
>        Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current-testing. Please verify its path and try again
> 

Probably also related with sys-whonix as updateVM. Check how enabling testing repository if you want to install current version without dbus.

**Comment by erasmo52** [comment] 2018-11-08 10:48
Finally:
1) I changed the updatevm to sys-firewall and 'sudo qubes-dom0-update --refresh' and 'sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing' didn't worked anyway
2) I also de-onionized repositories and the two above commands worked fine and after upgrade of some software also the qubes-manager worked fine again. But it means that the onionize of all dom0 repositories and the update of dom0 over sys-whonix is incompatible with  the two  'sudo qubes-dom0-update --refresh' and 'sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing' commands? Is this a bug? Or it is normal? And if it is a normal behavior, maybe it would be precised in the "https://www.whonix.org/wiki/Onionizing_Repositories" instructions.
3) After all that I reverted my settings to the onionized all dom0 repositories and I update dom0 over sys-whonix and I got for both commands the same errors that I already signaled. And also the simple 'sudo qubes-dom0-update' now give me the same error as if I was updating from the testing repository.
Voila!

**Comment by donob4n** [comment] 2018-11-08 11:19
> Finally:
>     2. I also de-onionized repositories and the two above commands worked fine and after upgrade of some software also the qubes-manager worked fine again. But it means that the onionize of all dom0 repositories and the update of dom0 over sys-whonix is incompatible with  the two  'sudo qubes-dom0-update --refresh' and 'sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing' commands? Is this a bug? Or it is normal? And if it is a normal behavior, maybe it would be precised in the "https://www.whonix.org/wiki/Onionizing_Repositories" instructions.

Default sys-firewall is based on Fedora so it uses a real  yum, I think that whonix/debian based uses some kind of proxy for download the packages which does not support all commands.
 
>     3. After all that I reverted my settings to the onionized all dom0 repositories and I update dom0 over sys-whonix and I got for both commands the same errors that I already signaled. And also the simple 'sudo qubes-dom0-update' now give me the same error as if I was updating from the testing repository.
>        Voila!

**Comment by unman** [comment] 2018-11-08 13:46
It seems that the original issue could be closed.
The root cause seems to have been using sys-whonix as updateVM for onionized repositories, although it *may* be that those repositories weren't properly synced with the main Qubes repositories.

@erasmo52  Can you either retitle this issue, or better (imo) close it.
It might be an idea to open a new issue for the update errors.  If details of the versions loaded prior to the succesful update that would be incredibly helpful. (You may be able to garner this from the update logs.) In the absence of those I'm not sure what benefit there would be in opening an issue.

@andrewdavidwong What do you think?

**Comment by donob4n** [comment] 2018-11-08 14:16
@unman He was using the latest stable version of qubes-manager. It seems that something was/is broken with his qubes/dbus. Since he updated to current-testing he is avoiding the dbus problem.

I personally run testing version and I can't catch dbus events with 'dbus-monitor' (months ago I could), maybe qubes-dbus was disabled or removed?

**Comment by unman** [comment] 2018-11-08 14:30
@donob4n I know that. But the fact that updating from the non Tor Qubes repos fixed the problem suggests that some _other_ package was at fault, and we know nothing about what versions of other packages were installed, nor what "after upgrade of some software" means. That's why I asked if that information could be provided.

**Comment by erasmo52** [comment] 2018-11-08 14:49
OK, I don't know if open a new issue could be a good idea because the actual malfunction is the consequence of the past actions.
To take stock of the situation: I changed the updatevm to sys-firewall, I de-onionized repositories (qubes-dom0.repo and qubes-templates.repo); after that I successfully upgraded the dom0.
This upgrade solved the original problem (qubes-manager error).
After this upgrade, I re-onionized the dom0 repositories and I set again the updatevm to sys-whonix.
I run 'sudo qubes-dom0-update' (which originally - before the testing upgrade - was working fine) and I receive this error:
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Error: Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current. Please verify its path and try again
... some yumdownloader usage help ...
find: '/var/lib/qubes/dom0-updates/var/cache/yum': No such file or directory
No packages downloaded
Last thing I verified in the qubes-dom0.repo and qubes-templates.repo and the testing repositories are disabled.
Now you can judge what to do with that issue. There is always the alternative to completely disable the repository onionize and upgrade via default sys-firewall  updatevm, but imo it is not a good solution. All that was working fine until the last dom0 stable upgrade.
Best regards and thanks for your time

**Comment by andrewdavidwong** [comment] 2018-11-09 06:11
> After this upgrade, I re-onionized the dom0 repositories and I set again the updatevm to sys-whonix.
> I run 'sudo qubes-dom0-update' (which originally - before the testing upgrade - was working fine) and I receive this error:
> Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
> Error: Cannot retrieve repository metadata (repomd.xml) for repository: qubes-dom0-current. Please verify its path and try again
> ... some yumdownloader usage help ...
> find: '/var/lib/qubes/dom0-updates/var/cache/yum': No such file or directory
> No packages downloaded

Looks like this has already been reported in #3463.

**Comment by andrewdavidwong** [comment] 2018-11-09 06:11
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-11-09 06:11 UTC
Labels: C: manager/widget, bug

**Comment by andrewdavidwong** [comment] 2018-11-10 03:43
@erasmo52, you [wrote](https://github.com/QubesOS/qubes-issues/issues/4481#issuecomment-437019252):
> This upgrade solved the original problem (qubes-manager error).

Since the original problem reported in this issue has been solved, this issue has been closed as "resolved."

> but the problems I related and synthesized in my last comments are always present. The solution reported in #3463 (hardcoding r4.0 instead of r$releasever in both /etc/yum.repos.d/qubes-dom0.repo and /etc/yum.repos.d/qubes-templates.repo) changed nothing to the behavior of update process.

Those are different problems than the one that this issue is about. Therefore, they belong in a different issue. If #3463 doesn't cover them, file a new issue.
