### ISSUE TITLE
Launching application from menu in a AppVM do not work 

### ISSUE THREAD

**Issue by pdinoto** [QubesOS/qubes-issues#3826] opened 2018-04-15 20:55 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

`dom0`  GUI

---

### Steps to reproduce the behavior:

Restore a R3.2 AppVM qube into a stock R4.0 system, and then select any of the AppVM applications on the Xfce menu (except for "<qube-name> Qube Settings" menu item, obviously)

### Expected behavior:

The AppVM is started if it was not already running. Once the AppVM has booted the requested application is launched in that qube.

### Actual behavior:

The AppVM is launched if it was not already running, but then nothing happens.
If the AppVM was running, nothing happens.

### General notes:

The same application can be launched by using `dom0` command line, like:

    dom0$ qvm-run <appvm-qube-name> <application>

It does not seem related to the type of launched application.
Only common denominator is that this happens on restored from backup qubes.
ServiceVMs applications launch fine.
Application from newly created qubes also launch fine.

Editing the AppVM exposed applications on the Qube Settings dialog, "Application" tab does not fix the issue.

---

**Comment by marmarek** [comment] 2018-04-15 21:00
Is is TemplateBasedVM or StandaloneVM? Is is on template also restored, or fresh one from Qubes 4.0?  Is the template version the same as was on R3.2?

**Comment by pdinoto** [comment] 2018-04-21 00:07
Well, it seems that this issue was solved by an update in `qubes-*` debian packages in the `debian-9` template.

Also, the templates I migrated started to work properly when the qubes repository on them was changed to `.../r4.0/...`, which I did not realize :man_facepalming: 

Unless this happens to others, I thing we should close this one.

**Comment by andrewdavidwong** [comment] 2018-04-21 19:32
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-04-21 19:32 UTC
Labels: C: desktop-linux-xfce4, bug
