### ISSUE TITLE
VM not starting after installing plasma KDE

### ISSUE THREAD

**Issue by TheBubblePopped** [QubesOS/qubes-issues#3630] opened 2018-02-25 14:51 UTC
#### Qubes OS version:
 4.0-rc4 

#### Affected component(s): 
Everything
(VMs Domains)

---

### Steps to reproduce the behavior:
Installing qubes, install plasma after it = VM not starting. 

### Expected behavior:
Vm should start f.e. firefox.

### Actual behavior:
Nothing happens

### General notes:

Tried to format 5 times to reproduce the error it was always the same

---

**Comment by marmarek** [comment] 2018-02-25 22:46
I think this is a duplicate of #3147. If you reboot after KDE installation (assuming you've followed this instruction: https://www.qubes-os.org/doc/kde/) it should be fine.

**Closed by marmarek** 2018-02-25 22:46 UTC

**Comment by TheBubblePopped** [comment] 2018-02-26 11:16
The story gets even sader. You just baited me to reinstall it and now i face the same problem as before
