### ISSUE TITLE
Update error “failed to return clean data”

### ISSUE THREAD

**Issue by selltic** [QubesOS/qubes-issues#7040] opened 2021-11-06 05:32 UTC
I use Qubes OS 4.0.4 and whonix-16

Whenever I try to update Whonix via the qubes updater, I get an error (below). I’ve been getting this error since I installed qubes about a week ago, and I haven’t had a problem on any other qube so I assume it’s a Whonix issue. Running “sudo apt-get update” then “sudo apt-get upgrade” works fine in a standalone VM based on whonix, but it also gives the same error using the qubes updater gui tool.

I’m using whonix workstation 16.

Here’s the error copied from the updater tool:
Updating whonix-ws-16

`Error on updating whonix-ws-16: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=whonix-ws-16', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20
whonix-ws-16:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/var/tmp/.root_dd8a91_salt/salt-call", line 27, in <module>
              salt_call()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py", line 445, in salt_call
              client.run()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py", line 48, in run
              caller = salt.cli.caller.Caller.factory(self.config)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 64, in factory
              return ZeroMQCaller(opts, **kwargs)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 329, in __init__
              super(ZeroMQCaller, self).__init__(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 89, in __init__
              self.minion = salt.minion.SMinion(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/minion.py", line 912, in __init__
              opts["grains"] = salt.loader.grains(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader.py", line 825, in grains
              ret = funcs[key]()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/grains/core.py", line 2384, in ip_fqdn
              ret["ipv6"] = salt.utils.network.ip_addrs6(include_loopback=True)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py", line 1353, in ip_addrs6
              return _ip_addrs(interface, include_loopback, interface_data, "inet6")
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py", line 1333, in _ip_addrs
              ret.add(addr)
            File "/usr/lib/python3.9/ipaddress.py", line 1920, in __hash__
              return hash((self._ip, self._scope_id))
          AttributeError: _scope_id
      stdout:`

**Comment by marmarek** [comment] 2021-11-06 10:25
Select newer template for `default-mgmt-dvm` (fedora-33 or newer, or debian-11)

**Comment by selltic** [comment] 2021-11-06 21:27
> Select newer template for `default-mgmt-dvm` (fedora-33 or newer, or debian-11)

Thanks. This worked for me. 
Please, tell me. Now I have updated the Fedora template VM from version 32 to version 33. Do I need to change the Template in my other virtual machines? For example, sys-net and sys-firewall. Should I change the template in them from Fedora 32 to Fedor 33? Or can they continue to work for Fedor 32? 
Will the sys-firewall continue to perform its functions if I update its Template from Fedora 32 to Fedora 33?

Thanks for the answer

**Comment by unman** [comment] 2021-11-07 01:12
On Sat, Nov 06, 2021 at 02:28:04PM -0700, selltic wrote:
> > Select newer template for `default-mgmt-dvm` (fedora-33 or newer, or debian-11)
> 
> Thanks. This worked for me. 
> Please, tell me. Now I have updated the Fedora template VM from version 32 to version 33. Do I need to change the Template in my other virtual machines? For example, sys-net and sys-firewall. Should I change the template in them from Fedora 32 to Fedor 33? Or can they continue to work for Fedor 32? 
> Will the sys-firewall continue to perform its functions if I update its Template from Fedora 32 to Fedora 33?
> 
> Thanks for the answer
> 

Fedora 32 has reached end of life:
https://www.qubes-os.org/news/2021/05/25/fedora-32-eol/

So you are advised to use the template manager to switch all your qubes
that use 32 to 33.
The firewall (and all other qubes) should continue to work as expected.

**Comment by selltic** [comment] 2021-11-07 17:59
> On Sat, Nov 06, 2021 at 02:28:04PM -0700, selltic wrote: > Select newer template for `default-mgmt-dvm` (fedora-33 or newer, or debian-11) Thanks. This worked for me. Please, tell me. Now I have updated the Fedora template VM from version 32 to version 33. Do I need to change the Template in my other virtual machines? For example, sys-net and sys-firewall. Should I change the template in them from Fedora 32 to Fedor 33? Or can they continue to work for Fedor 32? Will the sys-firewall continue to perform its functions if I update its Template from Fedora 32 to Fedora 33? Thanks for the answer
> Fedora 32 has reached end of life: https://www.qubes-os.org/news/2021/05/25/fedora-32-eol/ So you are advised to use the template manager to switch all your qubes that use 32 to 33. The firewall (and all other qubes) should continue to work as expected.

Thank for answer.
Please, tell is there a need to update debian from version 10 to version 11 through the test repository? Can I safely continue to use debian 10 for my cubes until debian 11 appears in the main release?

**Comment by andrewdavidwong** [comment] 2021-11-08 04:51
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2021-11-08 04:51 UTC
Labels: T: bug, P: default, diagnosed, C: updates

**Comment by andrewdavidwong** [comment] 2021-11-08 04:53
> Please, tell is there a need to update debian from version 10 to version 11 through the test repository? Can I safely continue to use debian 10 for my qubes until debian 11 appears in the main release?

Please take these sorts of questions to the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/).
