### ISSUE TITLE
Connect Display Dialogues pop up in App Qubes

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#8689] opened 2023-11-07 07:47 UTC
### Qubes OS release
4.2-rc4

### Brief summary
When I connect an external display (via USB-c -- not sure if that matters) the "Display" applications pops up in most app qubes. If I were to guess, this is something to do with the move to XFCE in templates. Something that was done in the gnome ones but didn't migrate to the XFCE templates.

![display](https://github.com/QubesOS/qubes-issues/assets/47065258/9fd180ba-7a36-4b49-8dfe-588d86ec37eb)

### Steps to reproduce
1. connect device to external display
2. see results

### Expected behavior
Only the admin qube shows the "Display" application and all other qubes mirror the setting silently.

### Actual behavior
Many of the other qubes show the "Display" application

**Comment by deeplow** [comment] 2023-11-07 09:19
This happens on fedora-xfce templates, but I haven't tested on any other once. I apparently can't reproduce it now, so I guess I'll test on the next restart.

**Comment by deeplow** [comment] 2023-11-15 07:51
> I apparently can't reproduce it now, so I guess I'll test on the next restart.

I can now confirm that this happens once per computer restart, after I connect to the display. After that first time, it never happens again until a reboot.

**Comment by marmarek** [comment] 2024-03-28 22:05
Duplicate of #8756

**Closed** 2024-03-28 22:05 UTC
Labels: T: bug, R: duplicate, C: templates, P: default, needs diagnosis, affects-4.2
