### ISSUE TITLE
passive popups sent from VMs look weird

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1267] opened 2015-10-04 13:09 UTC
Currently if Debian [or Fedora] VMs dispatch passive popups... Examples:

* `kdialog --passivepopup test`
* `notify-send test`

These look weird.

Feature Request:
Integrate them with Qubes Manager. Show these popups like the usual `starting vm-name` alike popups as dispatched as usual by Qubes VM Manager.

Security Considerations:

* Would that be secure?
* If not, how else this could be designed to stay user friendly?

This is important for Qubes-Whonix usability. However, it looks like a general Qubes issue. Unspecific to Whonix.

-----

Background:

At the Tor summer dev meeting, I discussed with @bnvk, that in future the only popups by Whonix should be the following.

* 1.: `starting sys-whonix` (dispatched as usual by Qubes VM Manager)
* 2.: `sys-whonix started` (dispatched as usual by Qubes VM Manager)
* 3.: `Tor bootstrap in progress.` (dispatched by sys-whonix whonixcheck)
* 4.: `Tor bootstrap done.` (dispatched by sys-whonix whonixcheck)

@bnvk, @mfc agreed, that those should use the same notification mechanism as Qubes uses.

**Comment by qubesuser** [comment] 2015-10-04 13:46
Regarding Whonix in particular, it might be a good idea in general to only popup messages in case there is a problem, as opposed to the current behavior of having both whonixcheck and timesync popup dialogs unconditionally.

**Comment by marmarek** [comment] 2015-10-04 15:05
This seems to be a duplicate of #889. There is even a prototype of such service.

**Closed by marmarek** 2015-10-04 15:05 UTC
