### ISSUE TITLE
Whonix-ws-dvm starts without torbrowser enabled R4.0 rc5

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#3740] opened 2018-03-25 08:01 UTC
### Qubes OS version

R4.0 rc5

### Affected component(s): 

Whonix-ws-dvm

---

### Steps to reproduce the behavior:

menu | disposable: whonix-ws-dvm | select whonix-ws-dvmTorbrowser (Anon dist)

### Expected behavior:

dvm opens, Torbrowser starts

### Actual behavior:

Popup:

> Tor Browser is currently not installed. 
> (Folder /home/user/.tb/tor-browser does not exist.)
> Start Tor Browser Updater (by Whonix Developers)?

### General notes:

Shouldn't TB be installed by default?

---

**Comment by andrewdavidwong** [comment] 2018-03-25 17:50
CC @adrelanos

**Comment by unman** [comment] 2018-03-25 19:58
@JPL1  This isn't my experience. 
Tor Browser opens in a disposableVM as one would expect.
I'm writing now on a clean install from the latest iso and TBB works just fine.
I wonder if it depends on how you get to rc5 - was your's a clean install or an upgrade?

If you also are working from the latest iso, can you check in Whonix-WS to see what is there, and then try regenerating the  Whonix-ws-dvm again?

**Comment by JPL1** [comment] 2018-03-25 22:49
It's an upgrade from rc4. If I try to start torbrowser from the terminal in Whonix-ws I get the same message.

**Comment by andrewdavidwong** [comment] 2018-03-26 02:26
I've experienced the same issue on 3.2. Creating a new VM based on `whonix-ws` resulted in a VM that did not have Tor Browser installed.

**Comment by marmarek** [comment] 2018-03-30 22:43
Can anyone confirm this on fresh 4.0 install? I cannot reproduce it anymore.

**Comment by mirrorway** [comment] 2018-03-30 23:07
I thought this was the correct behavior. The TorBrowser app is located in ~/.tb, which is downloaded by running Tor Browser Downloader once in each new whonix-ws-based VM.

**Comment by andrewdavidwong** [comment] 2018-03-31 23:13
Note that the label and milestone changes are part of a general issue tracker organization sweep. They're not an indication that we've received new information about this issue. We still invite users to confirm this on a fresh 4.0 installation. If no one confirms it, this issue will likely be closed as "cannot reproduce."

**Comment by awokd** [comment] 2018-04-02 08:20
> Can anyone confirm this on fresh 4.0 install?

I have experienced similar behaviour when accidentally trying to launch Torbrowser directly from the `whonix-ws-dvm` template instead of the `disposable: whonix-ws-dvm` menu item, but everything works as expected on a fresh 4.0 install.

**Comment by adrelanos** [comment] 2018-04-14 10:58
This is how it should work:
https://www.whonix.org/wiki/Tor_Browser/Advanced_Users#tb-updater_in_Qubes_TemplateVM

So yes, should be installed by default.

Tracking here:
https://phabricator.whonix.org/T789

**Comment by adrelanos** [comment] 2018-08-07 18:18
Works for me in Whonix 14 / Qubes R4.0.

Close please.

**Closed** 2018-08-08 00:43 UTC
Labels: C: Whonix, UX, bug
