### ISSUE TITLE
Unable to change the kernel in fedora-25 template

### ISSUE THREAD

**Issue by pietrushnic** [QubesOS/qubes-issues#3183] opened 2017-10-18 01:02 UTC
#### Qubes OS version:

`R4.0`

#### Affected TemplateVMs: 

`fedora-25`

---

### Steps to reproduce the behavior:

I'm trying to follow [this documentation](https://www.qubes-os.org/doc/managing-vm-kernel/) section Installing kernel in Fedora VM.

I was able to install 4.13.5-100 kernel. Unfortunately I'm not able to boot it using properties.

### Expected behavior:

I should be able to change VM kernel.

### Actual behavior:

Trying `pvgrub2` gives ability to set but do not detect file:

```
[pietrushnic@dom0 src]$ qvm-start fedora-25
Missing file: /var/lib/qubes/vm-kernels/pvgrub2/modules.img
```

Trying existing build kernel `4.13.5-100`:

```
[pietrushnic@dom0 src]$ qvm-prefs -s fedora-25 kernel 4.13.5-100
Traceback (most recent call last):
  File "/usr/bin/qvm-prefs", line 9, in <module>
    load_entry_point('qubesadmin==4.0.7', 'console_scripts', 'qvm-prefs')()
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_prefs.py", line 140, in main
    return process_actions(parser, args, target)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_prefs.py", line 116, in process_actions
    setattr(target, args.property, args.value)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 239, in __setattr__
    str(value).encode('utf-8'))
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 69, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 481, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 103, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesPropertyValueError: Kernel '4.13.5-100' not installed
```

Same thing when I try full directory name `4.13.5-100.fc25.x86_64`

I realized that missing file may mean content of `dom0`, but after copying all files from `fedora-25` to `dom0` I still was not able to boot:

```
[pietrushnic@dom0 src]$ qvm-start fedora-25
Start failed: internal error: libxenlight failed to create new domain 'fedora-25'
```

What is correct way of buidling and reaplcing kernel ?

### General notes:

This is result of my continue fight to fix Intel 8260 which hangs after S3. What I would like to try are different ucode files.

---

**Comment by marmarek** [comment] 2017-10-18 08:18
Set kernel to empty value ("(none)" if doing via GUI).
This is a duplicate of #3136

**Closed by marmarek** 2017-10-18 08:18 UTC
Labels: bug, C: Fedora, C: kernel
