### ISSUE TITLE
LibreOffice slow in Debian 10, perhaps

### ISSUE THREAD

**Issue by kramse** [QubesOS/qubes-issues#5600] opened 2020-01-26 11:49 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
LibreOffice in Debian 10 VM

**Brief summary**
After upgrade the LibreOffice was found to be very slow and almost unusable. Browsing in a small document of only a few pages would be choppy, and a lot of waiting to get the cursor back.

Tried multiple setting, but ended up finding the Uncheck Tools/Options/Libre Office/View/Use hardware acceleration - which made a huge difference.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Run LibreOffice on Debian 9
2. Upgrade Debian 9 to Debian 10
3. Run LibreOffice, browse document
4. If slow it will immediately be recognizable

**Expected behavior**
I expected LibreOffice to run as normally, on Debian 9. Been using Qubes for multiple years, and dont remember same problem in previous upgrades, neither from Qubes R3 to R4 or Debian upgrades

**Actual behavior**
Very slow browsing and editing in LibreOffice

**Screenshots**
No screenshot would help.

**Additional context**
Also added this a a proposed change for doc:
https://github.com/QubesOS/qubes-doc/pull/929

**Solutions you've tried**
Tried other setting which made no difference. "Cacheing" in LibreOffice changed over the years.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Googled LibreOffice slow etc.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none.

**Comment by andrewdavidwong** [comment] 2020-01-26 13:50
Do you experience this only in Debian VMs, or also in Fedora (or other OS) VMs?

**Comment by unman** [comment] 2020-01-26 15:45
On Sun, Jan 26, 2020 at 05:50:34AM -0800, Andrew David Wong wrote:
> Do you experience this only in Debian VMs, or also in Fedora (or other OS) VMs?
> 

I use LibreOffice in Debian-10 and dont see this.
Does it arise because of 9-10 upgrade path?

**Comment by kramse** [comment] 2020-01-27 07:28
> Do you experience this only in Debian VMs, or also in Fedora (or other OS) VMs?

Tried adding Fedora-30 standalone, dnf install libreoffice, copied same document to VM, did not experience long pauses while browsing/working.
Note this is running LibreOffice 6.2 - where the Debian was running 6.1 :
libreoffice-writer                    1:6.1.5-3+deb10u5 

Fedora-30:
libreoffice-writer-6.2.8.2-2.fc30.x86_64

**Comment by unman** [comment] 2020-01-27 11:39
On Sun, Jan 26, 2020 at 11:28:37PM -0800, Henrik Kramsh??j wrote:
> > Do you experience this only in Debian VMs, or also in Fedora (or other OS) VMs?
> 
> Tried adding Fedora-30 standalone, dnf install libreoffice, copied same document to VM, did not experience long pauses while browsing/working.
> Note this is running LibreOffice 6.2 - where the Debian was running 6.1 :
> libreoffice-writer                    1:6.1.5-3+deb10u5 
> 
> Fedora-30:
> libreoffice-writer-6.2.8.2-2.fc30.x86_64
> 
Can you test on a clean debian-10 rather than an upgrade?

**Comment by unman** [comment] 2020-02-09 16:26
@kramse Any chance of an update? Did you do anything to the template or your LibreOffice setup?

I have to say that I installed LibreOffice to a Debian 9 template. Performed an update, tested: dist-upgrade, and every thing worked fine. ( I mean I could scroll through, and edit, a 900 page document without any issues.)
This is on an i5 with 16GB RAM, and many other qubes open, so hardly a power house.

At the moment this is a "Can't reproduce".

**Comment by andrewdavidwong** [comment] 2020-02-11 12:56
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-02-11 12:56 UTC
Labels: C: Debian/Ubuntu, P: default, T: bug
