### ISSUE TITLE
Storage configuration errors in text-based installer

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2113] opened 2016-06-25 01:27 UTC
[On 2016-06-24 03:11, Drew White wrote](https://groups.google.com/d/msgid/qubes-users/5434d02b-830b-451d-9032-8e9c2e76414c%40googlegroups.com):
> Text based install.
> This issue has not been fixed since I reported it in Qubes 2.0 installer.
> 
> 
> INSTALLATION DESTINATION
> 
> (LVM, LVM Thin Partitioning)
> ERROR AS FOLLOWS..

```
storage configuration failed: autopart failed:
Encryption requested for LUKS device sda2 but no encryption key specified 
for this device.
```

> (Standard, Btrfs Partitioning)

```
storage configuration failed: autopart failed:
Encryption requested for LUKS device sda2 but no encryption key specified 
for this device.
Encryption requested for LUKS device sda3 but no encryption key specified 
for this device.
```

**Comment by marmarek** [comment] 2016-06-25 10:47
Duplicate of https://github.com/QubesOS/qubes-issues/issues/1161
And unlikely to be fixed in the near future (unless upstream will fix it). What we can do, is to disable text installation option, but it's still useful when using automated install (kickstart based), which was described on mailing list, for example here: https://groups.google.com/d/msg/qubes-users/MHNnq9202jg/k0yXR1i2KwAJ

**Closed by marmarek** 2016-06-25 10:47 UTC
Labels: bug, C: installer, duplicate

**Comment by bot2600** [comment] 2016-10-15 06:20
So what is the path here? X fails to start for me and it doesn't recognize my network card so it drops me to the text install where I run into this error.

**Comment by bot2600** [comment] 2016-10-15 06:22
Ah, sorry, just read the link.

**Comment by vovcacik** [comment] 2017-10-09 13:54
Don't overthink this. Kickstart is not the first thing to try.

1) Qubes [does not support][1] your dedicated GPU. If you got Intel CPU just replug your HDMI cable to motherboard.
2) Your BIOS may let you choose between integrated and dedicated GPU.
3) Try different hardware, maybe you got some old notebook around.
...
10) Kickstart

[1]: https://www.qubes-os.org/doc/system-requirements/

**Comment by ct-ferozakbar** [comment] 2017-10-25 10:11
does it have gui installer?

**Comment by MDGrey33** [comment] 2018-06-17 06:32
In my case its a macbook, and I'm trying qubes on virtual before I erase everything I got to install it as my main OS.
I tried 4.0 on install it only reboots and now the same issue mentioned above with 3.2...
I'll give the unattended install a try first 
https://groups.google.com/forum/#!msg/qubes-users/-9qRHSkwfy8/CCx08nnTVEAJ
