### ISSUE TITLE
Cannot attach usb camera to a custom dispvm 

### ISSUE THREAD

**Issue by kototama** [QubesOS/qubes-issues#3575] opened 2018-02-12 12:23 UTC
#### Qubes OS version:
4RC3, updated

#### Affected TemplateVMs: 
Custom DVM based on debian-9. Debian-9 template has qubes-usb-proxy installed.

---

### Steps to reproduce the behavior:

`qvm-usb attach  disp667 sys-usb:1-8`

### Expected behavior:

Camera get attached.

### Actual behavior:

Got error:
```

Device attach failed: /usr/lib/qubes/usb-import: 33: /usr/lib/qubes/usb-import: cannot open /sys/devices/platform/vhci_hcd/status: No such fileNo unused port found!/usr/lib/qubes/usb-import: 51: /usr/lib/qubes/usb-import: cannot create /sys/devices/platform/vhci_hcd/attach: Directory nonexistent

```

### General notes:

It works with the Fedora DVM  

---

**Comment by marmarek** [comment] 2018-02-12 13:20
Duplicate of #3456 
Apparently package is stuck in testing: https://github.com/QubesOS/updates-status/issues/378
Will push to stable in a moment.

**Closed by marmarek** 2018-02-12 13:20 UTC
