### ISSUE TITLE
New app menu does not appear on KDE

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8172] opened 2023-05-04 18:36 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

If I use KDE instead of XFCE, the new app menu does not appear when I click on the application launcher at the bottom left.

### Steps to reproduce

See above.

### Expected behavior

New app menu launches.

### Actual behavior

Exception related to missing or invalid QML file.

**Comment by marmarek** [comment] 2023-05-04 21:35
Duplicate of https://github.com/QubesOS/qubes-issues/issues/8159

**Closed by marmarek** 2023-05-04 21:35 UTC
Labels: T: bug, C: desktop-linux-kde, P: default, C: app menu

**Comment by andrewdavidwong** [comment] 2023-05-05 16:34
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
