### ISSUE TITLE
mouseclicks are received not at all or at the wrong position

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#5689] opened 2020-02-24 13:02 UTC
**Qubes OS version**

R4.0 but this also happened with 3.2

**Affected component(s) or functionality**

ui applications like terminals or webbrowsers mostly, but actually any application can be affected. strangely its also not happening in all running VMs.

**Brief summary**

clicking on elements doesnt work or clicks on the wrong location:

sometimes trying to mark text in a terminal marks no texts at all or marks text at a different location.
similarily, sometimes trying to click links (or other ui elements like buttons) results in nothing or the wrong area being clicked

**To Reproduce**
_Steps to reproduce the behavior:_

it just sometimes happens, its very strange. today even a reboot didnt fix things :(

it's also unclear to me whether this is an i3 issue or...?

**Comment by h01ger** [comment] 2020-02-24 14:47
hi, 

some additional info from irc today:

<pre>
[14:31] <       kohi> | h01ger: i have seen something like that with display layout changes.
[14:32] < h01ger> i did change the display layout after login
[14:36] < h01ger> kohi: fascinating. my laptop has a full hd display, but right now i'm using my 4k monitor (and have the problem). now, when i switch to full hd resolution its gone and back when i switch back 
                  to 4k
[14:37] <       kohi> | h01ger: try restarting a VM while the 4k is enabled.
[14:37] <       kohi> | h01ger: vms allocate a virtual X screen the size of the dom0 layout at start time.
[14:37] < kohi> _shrinking_ the used layout while they run may work, increasing it leads to all kinds of funnies.
[14:38] < h01ger> kohi: hmpf
[14:38] < h01ger> kohi: mind if i quote you in #5689?
[14:39] <       kohi> | h01ger: as in, when i plug myself into the google-presentation-hdmi at work, i need to start whatever vms i want to present from after plugging + configuring display. :/
[14:39] <       kohi> | h01ger: no, go ahead, but i am pretty sure there is at least one forever-ticket on this open already and there are workarounds like pre-allocating the vidbuffer
[14:40] < h01ger> kohi: yes, i seem to recall having heard about this workaround too. i'd like to use it..
</pre>

and indeed, switching to full HD resolution works as a crude workaround.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by marmarek** [comment] 2020-02-24 20:52
I'm almost sure you need this: https://www.qubes-os.org/doc/gui-configuration/

**Comment by ioleo** [comment] 2020-07-02 09:14
@marmarek Had the same issue (after plugging external display with already running qube) and this has fixed it for me. Thanks.

**Comment by andrewdavidwong** [comment] 2020-07-04 12:35
> I'm almost sure you need this: https://www.qubes-os.org/doc/gui-configuration/
>
>> Had the same issue (after plugging external display with already running qube) and this has fixed it for me. Thanks.

@h01ger, did this also work for you?

**Comment by h01ger** [comment] 2020-07-04 14:39
On Sat, Jul 04, 2020 at 05:35:33AM -0700, Andrew David Wong wrote:
> > I'm almost sure you need this: https://www.qubes-os.org/doc/gui-configuration/
> @h01ger, did this also work for you?

yes.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by andrewdavidwong** [comment] 2020-07-07 10:39
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-07-07 10:39 UTC
Labels: C: gui-virtualization, P: default, T: bug
