### ISSUE TITLE
Python error in journalctl when extending volume

### ISSUE THREAD

**Issue by cliff19** [QubesOS/qubes-issues#5301] opened 2019-09-07 19:00 UTC
**Qubes OS version**
R4.0
**Affected component(s) or functionality**
Extending the storage space of a VM
**Brief summary**
When attempting to resize a built-in VM(personal, untrusted etc) on the command line, a "Got empty response from qubesd. See journalctl in dom0 for details"(see below).
Possibly related:
In the GUI, all of the affected VMs will say "*Cannot be changed while qube is running" next to the storage. The VMs are not running, I have tried rebooting.
**To Reproduce**
_Steps to reproduce the behavior:_
1. Reboot
2. Try to resize a built-in VM
(Exact command I ran was,`qvm-volume extend personal:root 50g`. My machine has that plus alot more storage available)
**Expected behavior**
VM storage extends
**Actual behavior**
_What actually happened (instead of what you expected to happen)._
Nothing except python error in journalctl.
[Here is the error](pastebin.com/wFBneqtm)

**Additional context**
This is a fresh install, haven't done anything.

**Solutions you've tried**
None, editing the python scripts myself without a green flag seems like a bad idea

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I have found no relevant information online

**Comment by marmarek** [comment] 2019-09-07 19:39
Duplicate of #5219

**Closed by marmarek** 2019-09-07 19:39 UTC
Labels: P: default, T: bug

**Comment by cliff19** [comment] 2019-09-07 20:20
> Duplicate of #5219

No it isn't. That issue specificially says "Resizing a currently-running DispVM's private volume results in stack traces like the following from qubesd". This is happening on VMs that are not running.

**Comment by marmarek** [comment] 2019-09-07 20:23
Reproduction steps may be different, but the cause seems to be the same.
