### ISSUE TITLE
Language switcher stopped working in new templates

### ISSUE THREAD

**Issue by gangamstyle** [QubesOS/qubes-issues#7903] opened 2022-11-23 10:56 UTC
### Qubes OS release
4.1.1

### Brief summary
Language switcher (Ctrl+Shift, Alt+shift) works in dom0, but stopped working inside VM's after Debian 11 template reinstall (reinstall is required to fix other bug: https://github.com/QubesOS/qubes-issues/issues/7865).

Old Debian 11 template had this file responsible for language switching:
```
/etc/X11/Xsession.d/90qubes-keymap
```
New template lacks it.
Copying this file into a new template helped to solve the problem, but not completely. Language switcher now works for some time, then stops working again, I think this happens after suspend/resume.

Fedora 35 minimal template is affected too.

**Comment by gangamstyle** [comment] 2023-10-06 15:16
This bug is pain in ass, I am still struggling with it even after reinstalling debian template. Since noone can fix it, can you guys tell me how to auto-run /etc/X11/Xsession.d/90qubes-keymap in all running guests after each dom0's suspend-to-ram ?
After every suspend keyboard language switcher stops working.

**Comment by gangamstyle** [comment] 2023-10-06 15:28
Same problem here https://github.com/QubesOS/qubes-issues/issues/1396

**Comment by andrewdavidwong** [comment] 2023-10-07 00:41
> Same problem here #1396

Just to confirm, are you saying that this issue is a duplicate of #1396?

**Closed** 2024-12-07 14:28 UTC
Labels: T: bug, C: templates, localization, P: default, affects-4.1, eol-4.1
