### ISSUE TITLE
Debian: Pre-install wider array of NIC/Wifi drivers

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#5123] opened 2019-06-26 16:54 UTC
**Qubes OS version**
R4.0.1
R4.0.2

**Affected component(s) or functionality**
debian-9 templates
debian-10 templates

**Brief summary**
Many users cannot easily utilize a full set of Debian VMs after Qubes installation due to missing NIC firmware. Abortive attempts to switch sys-net and sys-usb to Debian templates are made before giving up or having to troubleshoot the situation.

For example, the `firmware-iwlwifi` package is required for use with a large proportion of PC systems – which have Intel NICs – but its omission from the initial template installation means that a high percentage of users (probably most) trying to control their hardware with Debian will experience a loss of network access.

Qubes should accommodate the users' initial intention to use Debian templates for basic tasks by having all or most NIC driver packages pre-installed.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

https://github.com/QubesOS/qubes-issues/issues/1919#issuecomment-304050179

**Comment by marmarek** [comment] 2019-06-26 17:30
Feel free to open a PR to qubes-builder-debian, likely [this file](https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/packages_buster_standard.list).

**Comment by tasket** [comment] 2019-06-27 18:10
@unman 
Do you have a preference or opinion about adding these packages to the default Debian configuration?

```
firmware-ath9k-htc
firmware-atheros
firmware-b43-installer
firmware-brcm80211
firmware-intelwimax
firmware-iwlwifi
firmware-ralink
firmware-realtek
```
I picked these as obvious choices to improve Debian templates' initial NIC support.

**Comment by unman** [comment] 2019-07-01 12:51
For my live systems I use these:

```
atmel-firmware 
firmware-atheros 
firmware-brcm80211 
firmware-ipw2x00 
firmware-iwlwifi 
firmware-misc-nonfree 
firmware-realtek 
firmware-zd1211
```
We could do union or intersection.

I suspect this is a variant of [the note on default preferences](https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default).

TBH it doesn't matter either way - since a system ships with fedora defaults, a user has to decide to switch to Debian templates, and has the opportunity to install whatever firmware is needed using the default set-up. This is an improvement on a stock Debian install where none of these are installed, and that option isn't available. (That's why there is a prompt to make the drivers available during installation.)

**Comment by tasket** [comment] 2019-07-08 18:09
As a side OT note:

I didn't know that `emacs` was included specifically by Qubes. The way its added is problematic because the default file type association for text ends up being emacs instead of the more accessible `gedit`. Its a UX pitfall in the Debian templates.

**Comment by tasket** [comment] 2019-07-08 18:47
@unman Added a union of the two lists and posted a PR [here.](https://github.com/QubesOS/qubes-builder-debian/pull/34)

**Comment by tasket** [comment] 2019-07-08 18:56
I should add: Some of these packages have a license acceptance prompt. Don't know if that's a problem for the builder scripts.

**Comment by adrelanos** [comment] 2019-07-08 19:41
This will break the build since some firmware will ask license related debconf questions which make the build interactive (requiring keyboard input). Not even `DEBIAN_FRONTEND="noninteractive"` or [`apt-get-noninteractive`](https://github.com/Whonix/usability-misc/blob/master/usr/bin/apt-get-noninteractive) can beat that. I've run into this issue before and here is the solution.

```
## https://git-tails.immerda.ch/tails/tree/config/chroot_local-preseed/firmware
echo b43-fwcutter b43-fwcutter/cut_firmware boolean true | debconf-set-selections
echo firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true | debconf-set-selections
echo firmware-iwlwifi firmware-iwlwifi/license/accepted boolean true | debconf-set-selections
echo firmware-ralink firmware-ralink/license/accepted boolean true | debconf-set-selections
```

**Comment by unman** [comment] 2019-07-29 14:59
I think we should offer this as a separate target, rather than incorporate in to standard template.
That way it's still possible to build a "free" debian10 , and keep build options open, allowing e.g.minimal+firmware.
I use this approach and it's fine.
PR on it's way.

We also need to add an alias in configs, so "buster" builds buster+standard+firmware.

**Comment by tasket** [comment] 2019-07-29 15:28
Are the current debian templates really libre? I thought the av codecs, for example, included parts that aren't.

**Comment by unman** [comment] 2019-08-01 13:50
Minimal is clean. It's only the standard template that has non-free and it's all firmware - we could consider moving those packages too in to a firmware target.
Of course, neither Qubes nor Debian will be [endorsed by FSF](https://www.qubes-os.org/faq/#will-qubes-seek-to-get-certified-under-the-gnu-free-system-distribution-guidelines-gnu-fsdg)

**Comment by adrelanos** [comment] 2019-08-03 05:03
https://github.com/Whonix/anon-meta-packages/blob/master/debian/control

```
Package: firmware-nonfreedom
Architecture: all
Pre-Depends: whonix-legacy
Depends: ${misc:Depends},
 firmware-amd-graphics,
 firmware-atheros,
 firmware-b43-installer,
 firmware-b43legacy-installer,
 firmware-brcm80211,
 firmware-intel-sound,
 firmware-ipw2x00,
 firmware-iwlwifi,
 firmware-libertas,
 firmware-linux,
 firmware-linux-free,
 firmware-linux-nonfree,
 firmware-misc-nonfree,
 firmware-realtek,
 firmware-ti-connectivity,
 firmware-zd1211,
Description: Recommended packages for hosts with nonfreedom hardware design
 A metapackage, which includes nonfree firmware useful for hosts with
 nonfreedom hardware design.
 .
 These are not useful in Qubes, since this would be up to Qubes.
 .
Safe to remove, if you know what you are doing.
```

**Comment by unman** [comment] 2019-10-20 01:12
@tasket  After the merge of https://github.com/QubesOS/qubes-builder-debian/pull/35 this could be closed. The libre issue is separate.

**Comment by andrewdavidwong** [comment] 2019-10-20 07:25
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-10-20 07:25 UTC
Labels: C: Debian/Ubuntu, P: default, T: enhancement, help wanted
