### ISSUE TITLE
Blocking a qubes RPC can result in the screen being filled with notifications

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#5965] opened 2020-07-25 05:30 UTC
**Qubes OS version**
4.1
**Affected component(s) or functionality**
Qubes RPC notifications
**Brief summary**
When a policy which will be retried is denied, the screen will fill with notifications. A malicious VM could use this as a cheap GUI DOS. 

**To Reproduce**
1. Block Qubes U2F proxy in RPC policy. 
2. Navigate to a website which requests U2F. 
3. Watch the screen fill up with policy violation notifications. 

**Expected behavior**
Notifications should be rate-limited to avoid overwhelming the rest of the system. 

**Actual behavior**
Screen filled with notifications.

**Comment by andrewdavidwong** [comment] 2020-07-27 01:43
This sounds closely related to #5856. Perhaps #5856 should be generalized to subsume this?

CC: @ninavizz

**Comment by JarrahG** [comment] 2020-07-27 09:01
I think you're right in that the solution to #5856 should be extended to solve this problem. However, it sounds like that issue is talking about a user being repeatedly prompted for permission, while the issue here is that the current passive pop-up notification extends across the entire screen when there are multiple.

**Comment by andrewdavidwong** [comment] 2020-07-28 20:29
> I think you're right in that the solution to #5856 should be extended to solve this problem. However, it sounds like that issue is talking about a user being repeatedly prompted for permission,

No, there are also just notifications (not prompts), and part of the problem is that the user gets spammed by a large number of them.

> while the issue here is that the current passive pop-up notification extends across the entire screen when there are multiple.

The main problem is notification spam. It sounds like fundamentally the same problem.

Even if there were the same number of notification pop-ups in the same spot (not extending across the screen), it would still be bad UX to have so many notifications repeatedly popping up. Not very useful to the user and a rather unpleasant experience.

**Comment by JarrahG** [comment] 2020-07-29 11:34
> The main problem is notification spam. It sounds like fundamentally the same problem.

I must have mis-read that. Seems like this issue should be closed as a
duplicate.

**Comment by andrewdavidwong** [comment] 2020-07-30 20:23
I've generalized #5856 to be about notification spam in general so that it encompasses this issue.

Now closing as a duplicate of #5856.

**Comment by strugee** [comment] 2020-07-30 22:29
@andrewdavidwong looks like you didn't actually hit "Close" by mistake?

**Closed** 2020-07-31 09:20 UTC
Labels: C: core, P: default, R: duplicate, T: bug, ux

**Comment by andrewdavidwong** [comment] 2020-08-01 19:14
Yep, hit the wrong button. Thanks for closing, Jarrah.
