### ISSUE TITLE
Qubes Update broke after 21 May 2024 dom0 update

### ISSUE THREAD

**Issue by ryrona2** [QubesOS/qubes-issues#9253] opened 2024-05-22 05:08 UTC
### Qubes OS release

Qubes R4.2.1 (with only Debian templates, no Fedora templates, and with sys-whonix as update gateway for both dom0 and qubes)

### Brief summary

After updating dom0 on 21 May 2024, Qubes Update GUI application stopped working. It won't even start if clicking on the app menu item for it, and a stack trace is shown if running "sudo qubes-update-gui" in dom0 terminal.

This issue does not just affect me, multiple other Qubes OS users are experiencing this since yesterday.

https://forum.qubes-os.org/t/dom0-update-qubes-update-no-longer-available/26546

### Steps to reproduce

1. Install the latest dom0 updates.
2. Click app menu, cogwheel, Qubes Tools, Qubes Update. Nothing happens, no new window is opened at all.
3. Click app menu, cogwheel, Other, Xfce Terminal.
4. Type "sudo qubes-update-gui", and the below stack trace will show immediately and nothing more happens.

Rebooting does not help.

### Expected behavior

Starting Qubes Update GUI from the app menu or from dom0 terminal should work fine.

### Actual behavior

Qubes Update GUI fails to start with this stack trace:

```
[me@dom0 ~]$ sudo qubes-update-gui
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 58, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 155, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 106, in populate_vm_list
    self.refresh_update_list(settings.update_if_stale)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 122, in refresh_update_list
    in output.decode().split("\n", maxsplit=1)[0]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 58, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 155, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 106, in populate_vm_list
    self.refresh_update_list(settings.update_if_stale)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 122, in refresh_update_list
    in output.decode().split("\n", maxsplit=1)[0]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by PeterLacknase** [comment] 2024-05-22 06:30
Same over here. (Though "automatic" updates for VMs still work.)

**Comment by unman** [comment] 2024-05-22 10:40
Updating with testing repositories enabled:
1. Update GUI starts normally from tray icon
2. From menu, splash screen appears with grey contents.
3. "sudo qubes-update-gui" works normallydd

I have not tested after reboot.

**Comment by marmarek** [comment] 2024-05-22 10:51
Duplicate of https://github.com/QubesOS/qubes-issues/issues/9203

**Closed** 2024-05-22 10:52 UTC
Labels: T: bug, R: duplicate, P: default
