### ISSUE TITLE
qubes-gui error: libvchan_is_eof

### ISSUE THREAD

**Issue by sagonwulf** [QubesOS/qubes-issues#6365] opened 2021-01-26 09:42 UTC
**Qubes OS version**

Qubes release 4.1 (R4.1)

**Affected component(s) or functionality**

Telegram desktop for linux latest version 2.5.1

**Brief summary**

After the 2 latest dom0 Updates telegram desktop doesn’t work anymore.
It worked before with no issues.

VM ist debian-10 standalone, also tried fedora-32 and debian-11

To rule out VM relates issues, I tried a clone of the debian-10 VM that
was made before VM Updates were applied. Still doesn’t work with this
unmodified VM.

When telegram ist started, it blriefly shows the GUI, and then
terminates.
After that, no GUI program in the VM works anymore, but the VM is still
alive and able to show the console.

There is an error message in ther VM log:

`qubes-gui[571]: libvchan_is_eof`

**How Reproducible**

the bug occurs every time Telegram Desktop is started

**To Reproduce**

1. create a clean VM from template debian-10
2. download Telegram Desktop to this VM
3. start a terminal in the VM 
4. start the Telegram application

**Expected behavior**

when calling the Telegram program from a terminal in a VM, the application starts

**Actual behavior**

when calling the Telegram program from a terminal in a VM, the application briefly shows and the terminal window closes.
After that, no GUI program can be launched in this VM.
But the VM is still alive, as the console can be connected.

**Screenshots**

**Additional context**

The cause of the problem seems to have been introduced in one of the last dom0 updates

**Solutions you've tried**

different VM OS (debian-10, debian-11, fedora-32)
different VM root system (via template, standalone)
different VM virtualization (PVH, HVM)
diffenent qubes kernel (5.4.88, 5.8.16)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment] 2021-01-26 11:14
Check GUI daemon logs for that VM (`/var/log/qubes/guid.<vmname>.log`). If there is no relate message, then maybe look for `qubes-guid` process crash in `journalctl` (in dom0 still).

**Comment by blockomat2100** [comment] 2021-01-26 19:16
I am suffering a similar bug. However, the GUI only crashes when applications have a sys tray icon.

/var/log/qubes/guid.vault.log:

```
Icon size: 128x128
ErrorHandler: BadAccess (attempt to access private resource denied)
Major opcode: 130 (MIT-SHM)
Minor opcode: 1 (X_ShmAttach)
ResourceID: 0x1800007
Failed serial number: 2628
Current serial number: 2629
XShmAttach failed for window 0x4400207(remote 0x1200056)
ErrorHandler: BadValue (integer parameter out of range for operation)
Major opcode: 12 (X_ConfigureWindow)
Value: 0x0
Failed serial number: 2654
Current serial number: 2657
```
(Maybe #5519 is related?)

I can "workaround" the issue (for at least vault VM with keepassxc) by removing `.config/keepassxc`. If you run keepassxc and set systray icon, the VM GUI instantly crashes. If you play music in such a crashing VM (before crash), you are still able to here the music, just the GUI is not available anymore.

**Comment by sagonwulf** [comment] 2021-01-27 06:21
Upon start of Telegram the following messages appear:

**/var/log/qubes/guid.t2.log**

```
ErrorHandler: BadValue (integer parameter out of range for operation)
                 Major opcode: 12 (X_ConfigureWindow)
                 Value:        0x0
                 Failed serial number:  1926
                 Current serial number: 1929

```

**dom0 jourrnalctl:**

```
Jan 27 06:46:55 dom0 qmemman.daemon.algo[2194]: balance_when_enough_memory(xen_free_memory=17125010, total_mem_pref=4222445977.6, total_available_memory=11083043254.4)
Jan 27 06:46:55 dom0 qmemman.daemon.algo[2194]: left_memory=1744815664 acceptors_count=4
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '0' act=4294967296 pref=1667910451.2 last_target=4294967296
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '5' act=2140649331 pref=458443980.8 last_target=2140649331
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '6' act=2470259883 pref=548198809.6 last_target=2470259883
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '7' act=2324246476 pref=567277568.0 last_target=2324246476
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '8' act=4058241236 pref=980615168.0 last_target=4058241236
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: xenfree=69553810 memset_reqs=[('5', 2095870112), ('6', 2420887372), ('8', 3986739395), ('0', 4294967296), ('7', 2489974750)]
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 5 to 2095870112
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 6 to 2420887372
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 8 to 3986739395
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 0 to 4294967296
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 7 to 2489974750
Jan 27 06:46:55 dom0 qmemman.daemon.algo[2194]: balance_when_enough_memory(xen_free_memory=17047569, total_mem_pref=4268004966.4, total_available_memory=11037481527.599998)
Jan 27 06:46:55 dom0 qmemman.daemon.algo[2194]: left_memory=1680342691 acceptors_count=4
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '0' act=4294967296 pref=1667910451.2 last_target=4294967296
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '5' act=2095870112 pref=458443980.8 last_target=2095870112
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '6' act=2420887372 pref=548198809.6 last_target=2420887372
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '7' act=2489974750 pref=612836556.8000001 last_target=2489974750
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '8' act=3986739395 pref=980615168.0 last_target=3986739395
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: xenfree=69476369 memset_reqs=[('5', 2062046864), ('6', 2383594657), ('8', 3932731653), ('0', 4294967296), ('7', 2615160192)]
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 5 to 2062046864
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 6 to 2383594657
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 8 to 3932731653
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 0 to 4294967296
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 7 to 2615160192
Jan 27 06:46:55 dom0 qmemman.daemon.algo[2194]: balance_when_enough_memory(xen_free_memory=16986308, total_mem_pref=4309762048.0, total_available_memory=10995724922.0)
Jan 27 06:46:55 dom0 qmemman.daemon.algo[2194]: left_memory=1622448378 acceptors_count=4
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '0' act=4294967296 pref=1667910451.2 last_target=4294967296
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '5' act=2062046864 pref=458443980.8 last_target=2062046864
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '6' act=2383594657 pref=548198809.6 last_target=2383594657
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '7' act=2615160192 pref=654593638.4 last_target=2615160192
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: dom '8' act=3932731653 pref=980615168.0 last_target=3932731653
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: stat: xenfree=69415108 memset_reqs=[('5', 2031674855), ('6', 2350107196), ('8', 3884234724), ('0', 4294967296), ('7', 2727574960)]
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 5 to 2031674855
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 6 to 2350107196
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 8 to 3884234724
Jan 27 06:46:55 dom0 qmemman.systemstate[2194]: mem-set domain 0 to 4294967296
Jan 27 06:46:56 dom0 qmemman.systemstate[2194]: mem-set domain 7 to 2727574960
Jan 27 06:46:58 dom0 qmemman.daemon.algo[2194]: balance_when_enough_memory(xen_free_memory=16928384, total_mem_pref=4358702284.8, total_available_memory=10946785130.2)
Jan 27 06:46:58 dom0 qmemman.daemon.algo[2194]: left_memory=1556006817 acceptors_count=4
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: stat: dom '0' act=4294967296 pref=1667910451.2 last_target=4294967296
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: stat: dom '5' act=2031674855 pref=458443980.8 last_target=2031674855
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: stat: dom '6' act=2350107196 pref=548198809.6 last_target=2350107196
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: stat: dom '7' act=2727574960 pref=703533875.2 last_target=2727574960
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: stat: dom '8' act=3884234724 pref=980615168.0 last_target=3884234724
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: stat: xenfree=69357184 memset_reqs=[('5', 1996818863), ('6', 2311675802), ('8', 3828577934), ('0', 4294967296), ('7', 2856586020)]
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: mem-set domain 5 to 1996818863
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: mem-set domain 6 to 2311675802
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: mem-set domain 8 to 3828577934
Jan 27 06:46:58 dom0 qmemman.systemstate[2194]: mem-set domain 0 to 4294967296
Jan 27 06:46:59 dom0 qmemman.systemstate[2194]: mem-set domain 7 to 2856586020
Jan 27 06:47:00 dom0 qrexec-policy-daemon[2824]: qrexec: qubes.NotifyUpdates+: t2 -> @adminvm: allowed to dom0
Jan 27 06:47:00 dom0 qmemman.daemon.algo[2194]: balance_when_enough_memory(xen_free_memory=16860960, total_mem_pref=4406343270.4, total_available_memory=10899143604.599998)
Jan 27 06:47:00 dom0 qmemman.daemon.algo[2194]: left_memory=1658062470 acceptors_count=4

````

**Comment by donob4n** [comment] 2021-01-28 22:58
I checked but can't reproduce. It seems working on both debian/fedora templates and xfce/kde dekstops.

**Comment by 0spinboson** [comment] 2021-01-28 23:07
yeah telegram also works fine for me, but this libvchan eof thing is a real issue that shouldn't happen.

**Comment by andrewdavidwong** [comment] 2021-01-29 01:03
> yeah telegram also works fine for me, but this libvchan eof thing is a real issue that shouldn't happen.

Updated issue title accordingly.

**Comment by blockomat2100** [comment] 2021-01-29 05:19
I am not sure if my problem is still related to this bug, because I can not find a libvchan_is_eof error in the console logs of my crashing VMs (the error appears in some vm logs, but not in the logs of the crashing ones). 
The rest of the description matches my problem. I can reproduce the problem for Telegram on all of my VMs, too.
If I run `tail -f /var/log/qubes/guid.guitest.log` and run telegram, the "BadValue" error appears right after the gui crashes.

**Comment by sagonwulf** [comment] 2021-02-02 14:24
I updated the debian VM and now I have:

```
user@t2:$ uname -a
Linux t2 5.4.67-1.qubes.x86_64 #1 SMP Thu Oct 1 03:31:59 CEST 2020 x86_64 GNU/Linux
user@t2:$ cat /etc/debian_version 
bullseye/sid
```
Telegram still doesn't work.
This messages are logged inside the VM (journalctl) upon start fo Telegram:

```
Feb 02 14:21:06 t2 qubes-gui[479]: XGetWindowAttributes for 0x1200005 failed in handle_create, ret=0x0
Feb 02 14:21:07 t2 dbus-daemon[756]: [session uid=1000 pid=756] Activating via systemd: service name='org.freedesktop.Tracker1' unit='tracker-store.service' requested by ':1.2' (uid=1000 pid=724 comm="/usr/libexec/tracker-miner-fs ")
Feb 02 14:21:07 t2 systemd[691]: Starting Tracker metadata database store and lookup manager...
Feb 02 14:21:07 t2 dbus-daemon[756]: [session uid=1000 pid=756] Successfully activated service 'org.freedesktop.Tracker1'
Feb 02 14:21:07 t2 systemd[691]: Started Tracker metadata database store and lookup manager.
Feb 02 14:21:07 t2 dbus-daemon[756]: [session uid=1000 pid=756] Activating via systemd: service name='org.freedesktop.Tracker1.Miner.Extract' unit='tracker-extract.service' requested by ':1.2' (uid=1000 pid=724 comm="/usr/libexec/tracker-miner-fs ")
Feb 02 14:21:07 t2 systemd[691]: Starting Tracker metadata extractor...
Feb 02 14:21:07 t2 tracker-extract[1099]: Set scheduler policy to SCHED_IDLE
Feb 02 14:21:07 t2 tracker-extract[1099]: Setting priority nice level to 19
Feb 02 14:21:07 t2 dbus-daemon[756]: [session uid=1000 pid=756] Activating service name='org.freedesktop.Notifications' requested by ':1.25' (uid=1000 pid=1078 comm="/home/user/QubesIncoming/signal/Telegram/Telegram ")
Feb 02 14:21:07 t2 dbus-daemon[756]: [session uid=1000 pid=756] Successfully activated service 'org.freedesktop.Notifications'
Feb 02 14:21:07 t2 qubes-gui[479]: libvchan_is_eof
Feb 02 14:21:08 t2 dbus-daemon[756]: [session uid=1000 pid=756] Successfully activated service 'org.freedesktop.Tracker1.Miner.Extract'
Feb 02 14:21:08 t2 systemd[691]: Started Tracker metadata extractor.
Feb 02 14:21:08 t2 dbus-daemon[756]: [session uid=1000 pid=756] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.28' (uid=1000 pid=1099 comm="/usr/libexec/tracker-extract ")
Feb 02 14:21:08 t2 systemd[691]: Starting Virtual filesystem metadata service...
Feb 02 14:21:08 t2 dbus-daemon[756]: [session uid=1000 pid=756] Successfully activated service 'org.gtk.vfs.Metadata'
Feb 02 14:21:08 t2 systemd[691]: Started Virtual filesystem metadata service.
Feb 02 14:21:18 t2 systemd[691]: tracker-extract.service: Succeeded.
```
How can I discover what's the diference between systems where Telegram runs and my system?

**Comment by sagonwulf** [comment] 2021-02-08 06:58
The same error occurs when starting **Teamviewer** in a debian 10.8 VM:

VM journalctl:

**`
Feb 08 07:47:17 teams qubes-gui[558]: libvchan_is_eof
`**


dom0 /var/log/qubes/guid.teams.log:

```
ErrorHandler: BadValue (integer parameter out of range for operation)
                 Major opcode: 12 (X_ConfigureWindow)
                 Value:        0x0
                 Failed serial number:  3149
                 Current serial number: 3152

```

dom0 journalctl:
```

Feb 08 07:47:13 dom0 qmemman.daemon.algo[2195]: balance_when_enough_memory(xen_free_memory=16962986, total_mem_pref=4568999936.0, total_available_memory=10735975402.0)
Feb 08 07:47:13 dom0 qmemman.daemon.algo[2195]: left_memory=1706731221 acceptors_count=3
Feb 08 07:47:18 dom0 qmemman.daemon.algo[2195]: balance_when_enough_memory(xen_free_memory=16962986, total_mem_pref=4517248204.8, total_available_memory=10787727133.2)
Feb 08 07:47:18 dom0 qmemman.daemon.algo[2195]: left_memory=1823541446 acceptors_count=3
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: stat: dom '0' act=4294967296 pref=1740152012.8 last_target=4294967296
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: stat: dom '5' act=2107438660 pref=460376883.2 last_target=2107438660
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: stat: dom '14' act=2427502181 pref=555105075.2 last_target=2427502181
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: stat: dom '16' act=4194304000 pref=1306711244.8 last_target=4194304000
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: stat: dom '17' act=2263800215 pref=454902988.8 last_target=2263800215
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: stat: xenfree=69391786 memset_reqs=[('17', 2146963582), ('0', 4294967296), ('5', 2165491242), ('14', 2486120697), ('16', 4194304000)]
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: mem-set domain 17 to 2146963582
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: mem-set domain 0 to 4294967296
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: mem-set domain 5 to 2165491242
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: mem-set domain 14 to 2486120697
Feb 08 07:47:18 dom0 qmemman.systemstate[2195]: mem-set domain 16 to 4194304000

```

**Comment by blockomat2100** [comment] 2021-02-10 08:47
I was able to get my GUI back after a crash using `qvm-start-gui -v --all` in dom0. Maybe this works for you, too.

**Comment by blockomat2100** [comment] 2021-02-10 08:52
In most cases, I was able to get my GUI back after a crash using `qvm-start-gui -v --all` in dom0. Maybe this works for you, too.
I did not yet figure out why it does not work everytime.

**Comment by sagonwulf** [comment] 2021-02-11 10:37
This was a very good tip, thank you. `qvm-start-gui -v <VM>` works as well.

Now I think it is probable that the GUI daemon in dom0 has an issue.

**Comment by blockomat2100** [comment] 2021-02-11 19:18
I just downgraded `qubes-gui-daemon` to `4.1.10` in dom0, which seems to not suffer this bug. At least for now no GUI crashes.

The package can be downloaded at https://yum.qubes-os.org and copied to dom0 using the official docs. 

A bit more user-friendly workaround.

**Comment by sagonwulf** [comment] 2021-02-12 10:17
great! Thank you!

**Comment by marmarek** [comment] 2021-02-12 17:38
> ErrorHandler: BadValue (integer parameter out of range for operation)
> Major opcode: 12 (X_ConfigureWindow)
> Value: 0x0
> Failed serial number: 2654
> Current serial number: 2657

I wonder if this can be related to https://github.com/QubesOS/qubes-gui-daemon/pull/56, specifically the part that avoids covering panels. XConfigureWindow(3) says "The width and  height  members  are used to set the inside size of the window, not including the border, and must be nonzero, or a BadValue error results.", perhaps some corner case results in 0-size request.

@sagonwulf can you enable "debug" property (named "run in debug mode" in qube settings) on some affected qube and restart it? This should give more details in `/var/log/qubes/guid.<vmname>.log`.

**Comment by blockomat2100** [comment] 2021-02-14 11:52
It seems that the GUI is not crashing if I use the default panel location (top). I normally have my panel at the bottom of the screen. With the latest gui-daemon the GUI crashes, if the panel is not located at the top.

**Comment by marmarek** [comment] 2021-02-14 12:02
This even more makes me suspect the above linked PR is responsible. Can you get the debug log using the procedure I described above?

**Comment by blockomat2100** [comment] 2021-02-14 12:07
The logs with debug mode enabled:

[guid.vault.log](https://github.com/QubesOS/qubes-issues/files/5977657/guid.vault.log)

**Comment by marmarek** [comment] 2021-02-14 12:21
That's it!
```
force_on_screen(from handle_map) returns 1 (reason 4): window 0x4400201, xy 1694 1049, wh 22 22, work area 1920 1049 borderwidth 0
XMoveResizeWindow local 0x4400201 remote 0x1200006, xy 0 0 (vm_window is 1694 1049) wh 22 0
ErrorHandler: BadValue (integer parameter out of range for operation)
                 Major opcode: 12 (X_ConfigureWindow)
                 Value:        0x0
                 Failed serial number:  1621
                 Current serial number: 1624
```
"wh 22 0" - the "0" should not be there.
In fact, this window looks like a tray icon which should be excluded from this "work area" enforcement completely.

**Comment by sagonwulf** [comment] 2021-02-15 06:48
Attached the guid log in debug mode.

[guid.telegram.log](https://github.com/QubesOS/qubes-issues/files/5979887/guid.telegram.log)

I also have the panel at the bottom of the screen. 
When I put the panel at the top, Telegram starts with no issue.

**Comment by na--** [comment] 2021-05-26 16:51
VLC and keepassxc consistently fail in this way for me, forcing me to use `qvm-start-gui` multiple times per day. Strangely, VLC fails both in Fedora and in Arch VMs, while the exact same version of `keepassxc` works in Fedora and fails in Arch... :man_shrugging: 

[guid.test.log](https://github.com/QubesOS/qubes-issues/files/6548404/guid.test.log)

Another strange thing is that I ran `qvm-features test gui-override-redirect-protection false`, which, if I understand things correctly and if https://github.com/QubesOS/qubes-issues/issues/6365#issuecomment-778338140 was the culprit, should have silenced the problem, but it didn't change anything :confused:

**Comment by na--** [comment] 2021-06-21 04:02
After the latest dom0 update (with `qubes*testing` repos enabled, but without updating TemplateVMs), this issue seems to have been fixed :tada: I don't see anything referenced here, but maybe some of the commits in https://github.com/QubesOS/updates-status/issues/2514 fixed it? :man_shrugging:

**Comment by andrewdavidwong** [comment] 2021-06-21 05:52
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-06-21 05:52 UTC
Labels: C: gui-virtualization, P: default, T: bug, needs diagnosis
