### ISSUE TITLE
kernel-devel needs tools/objtool/objtool to compile out-of-tree kernel modules

### ISSUE THREAD

**Issue by cregnec** [QubesOS/qubes-issues#3835] opened 2018-04-20 11:44 UTC
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

kernel-devel

---

### Steps to reproduce the behavior:

dom0 kernel version is 4.14.18-1.pvops.qubes

Install kernel-devel
`sudo qubes-dom0-udpate kernel-devel`

Boot the fedora-26 template vm with the same kernel

Install qubes-kernel-vm-support
`sudo dnf install qubes-kernel-vm-support`

```
[user@fedora-26 ~]$ sudo dkms status
u2mfn, 4.0.17: added
```
Build the module
`sudo dkms build -m u2mfn -v 4.0.17`

### Expected behavior:

Successful building of the module.

### Actual behavior:

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j2 KERNELRELEASE=4.14.18-1.pvops.qubes.x86_64 -C /lib/modules/4.14.18-1.pvops.qubes.x86_64/build M=/var/lib/dkms/u2mfn/4.0.17/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.18-1.pvops.qubes.x86_64 (x86_64)

DKMS make.log for u2mfn-4.0.17 for kernel 4.14.18-1.pvops.qubes.x86_64 (x86_64)
Fri Apr 20 13:21:39 CEST 2018
make: Entering directory '/usr/lib/modules/4.14.18-1.pvops.qubes.x86_64/build'
make[1]: *** No rule to make target 'tools/objtool/objtool', needed by '/var/lib/dkms/u2mfn/4.0.17/build/u2mfn.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  AR      /var/lib/dkms/u2mfn/4.0.17/build/built-in.o
make: *** [Makefile:1507: _module_/var/lib/dkms/u2mfn/4.0.17/build] Error 2
make: Leaving directory '/usr/lib/modules/4.14.18-1.pvops.qubes.x86_64/build'

### General notes:

Similar bugs have been spotted on other distributions.
The reason is that "objtool needs to be included to sucessfully
build all out-of-tree kernel modules, when kernel code include metadata
are generated by this tool (for example when CONFIG_STACK_VALIDATION /
CONFIG_UNWINDER_ORC enabled - ORC is enabled by default in 4.14.9+)."

details can be found in the following link from Debian bug report.

---

### Related issues:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833500

**Comment by marmarek** [comment] 2018-04-20 12:10
First of all, kernel provided from dom0 already have u2mfn module, you don't need compile it. I know there is automatic dkms service trying to build this module at VM startup. But we've disabled it recently (https://github.com/QubesOS/qubes-core-agent-linux/commit/76649d875b8248a22c9b561254cfbce677bfc3fc),  exactly for this reason - it's going to be part of the nearest update.
But I'm going to assume you use u2mfn just as an example, because in fact it apply to any out of tree module.
Unfortunately, adding objtool isn't enough to build out of tree kernel module, when using kernel provided from dom0. See #2844 for details. The easiest way to use out of tree modules is to use [kernel installed in the VM](https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm). 

@andrewdavidwong I think we should deprecate support of out of tree modules if using kernel from dom0. Kernel installed in VM works sufficiently ok for HVM (where such modules have the most use cases - drivers for PCI devices). We can't remove it completely yet, because of missing PVH support...
Where should we put such information? We have a page with supported versions, but not specific features.

**Comment by HW42** [comment] 2018-05-02 17:29
> I think we should deprecate support of out of tree modules if using kernel from dom0. Kernel installed in VM works sufficiently ok for HVM (where such modules have the most use cases - drivers for PCI devices). We can't remove it completely yet, because of missing PVH support...

Not convinced if deprecating it at this point is a good idea. If you look at the last Linux versions we always had some patches which fixed important issues. So by using distro kernels people will have it much easier to build OOT modules but then need to track Xen related kernel fixes.

Of corse I try to always push fixes we track down to stable and 4.17 hopefully will look better (didn't tried the rc yet for new regressions) so this should get better, but not convinced that it's good enough yet.

I will have a look if I see an easy fix for the build problems.

**Comment by vladimir-lu** [comment] 2018-05-30 20:47
Would it not be sufficient to allow the kernel from dom0 to be installed in a TemplateVM so that you can build modules for it? That would require a separate package though.

It also doesn't help currently that dom0 is based on a different fedora release than the new templates. I understand that using HVM would have a higher memory requirement (perhaps this is incorrect) so for things like VPN (wireguard) I would like to avoid it.

**Comment by homotopycolimit** [comment] 2018-06-28 11:44
@vladimir-lu I'm stuck in a similar place. I was wondering if you could expand on your previous comment? How does this work?
I have been trying for several day to build a kernel module (v4l2loopback) and I'd like to use the qubes kernel instead of the fedora or debian distribution kernel.

**Comment by marmarek** [comment] 2019-06-05 23:35
This is fixed with https://github.com/QubesOS/qubes-linux-kernel/commit/0a7a0dff2f6465a9a6e939d1e9f24b39790f2c89

**Closed by marmarek** 2019-06-05 23:35 UTC
Labels: C: doc, T: task
