### ISSUE TITLE
Software update with gnome-software in TemplateVM not working

### ISSUE THREAD

**Issue by umbratic** [QubesOS/qubes-issues#3815] opened 2018-04-13 12:29 UTC
### Qubes OS version:

4.0

### Affected component(s): 

gnome-software, TemplateVM

---

### Steps to reproduce the behavior:

Start _Software_ (gnome-software 3.24.3) from the menu in _Template: fedora-26_

### Expected behavior:

- _gnome-software_ is not able to connect to repositories.
- Adding or updating software packages not possible

### Actual behavior:

Cannot connect to repositories. Various error messages:
 - Unable to contact "Fedora Project PkgDb" [admin.fedoraproject.org]
 - Unable to download updates from "GNOME Shell extensions" [extensions.gnome.org]
 - Unable to download firmware updates from "Linux Vendor Firmware project" [s2.amazonaws.com]
 - Unable to download updates from "Open Desktop Review Server" [odrs.gnome.org]
 -  Oops, something has gone wrong. Please contact your software vendor. NetworkManager needs to be running

### General notes:

- Update using _dnf_ and _update qube_ from menu works perfectly.
- gnome-software worked fine im Qubes R 3.2
- I believe gnome-soft does not respect new mechanism with qrexec-based updates proxy

---

**Comment by marmarek** [comment] 2018-04-13 13:05
I've stumbled on this recently too. Not so short investigation left me with an impression that gnome-software is too tightly integrated with GNOME (too many assumptions about the environment) to work in Qubes VM. Unfortunately.

Details:
 - first, it's about setting HTTP proxy in PackageKit (it's architecture doesn't allow it to use the one already set in `/etc/dnf/dnf.conf`); previously it was set in [PackageKit.conf](https://github.com/QubesOS/qubes-core-agent-linux/commit/c2596a04359a7c0c7859680544cc4b18342dce7c#diff-c862aa1dbd6dd9c6f255c2c12bcea6b7), but PackageKit maintainers decided to [drop support for that setting](https://github.com/hughsie/PackageKit/commit/3afcfcd62ab979f493aee19e25344c559d199c82)
 - now, the only supported method is setting http proxy using d-bus API, by each client (which IMHO is even more "kinda crazy"); for `pkcon` command using environment `http_proxy` and such variables kind of works (even if `all_proxy` is set, one need to set `http_proxy` anyway...); but gnome-software ignores them
 - the only way for setting a proxy for gnome-software, is setting it globally in gnome network settings; two problems here: 1) we don't populate those settings at all (and also don't run NetworkManager in a template); 2) setting a proxy globally would defeat the main purpose of having it at all - giving network access _only_ to package manager
 - there are also (minor) problems related to network access detection - some parts of this puzzle like to conclude lack of network access when the system have only loopback interface and don't even bother to use provided proxy (which is running on this loopback interface)...

I haven't yet analyzed what is the best way to fix this, if at all.

**Comment by techgeeknz** [comment] 2018-05-10 02:53
@marmarek With all due respect, I think all GNOME software is too tightly integrated with GNOME to be useful outside that environment.  It seems to me we would resolve a lot of issues by piecewise-replacement of core GNOME software packages (starting with `gnome-software`, `nautilus`, and `gnome-terminal`) with equivalent software packages from XFCE or LXDE (such as `thunar`, `lxterminal` and `xfce4-terminal`.

Perhaps `yum extender` (for Fedora-based templates) or `synaptic` (for Debian-based templates) would be viable alternatives to `gnome-software`?

**Comment by andrewdavidwong** [comment] 2023-07-13 16:39
I think this should be closed as "won't fix" in favor of the much broader #6310. (Technically, it looks like #6310 is a duplicate of this, but I didn't catch that at the time it was filed years ago. At this point, I think it makes more sense to keep #6310 open (in an exception to our usual precedence rule about duplicates).)

Closing as "won't fix." (Please see #6310 instead.) If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-07-13 16:39 UTC
Labels: T: bug, C: Fedora
