### ISSUE TITLE
user statistics graph has offset labels

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3841] opened 2018-04-22 17:42 UTC
### Qubes OS version:

N/A

### Affected component(s): 

https://www.qubes-os.org/statistics/

---

### Expected behavior:

Labels are aligned with bars.

### Actual behavior:

Labels are off by 1.

### General notes:

As a result the last bar appears to be associated with a full last month, not the partial current month,
so makes people think Qubes usage fell off a cliff:
https://www.reddit.com/r/Qubes/comments/8ckvt5/why_has_qubes_dropped_down_in_users/

---

**Comment by woju** [comment] 2018-04-24 19:12
This is fixed in generator now and will kick in this night at around 05:15 UTC.

I kept every third label and had the window to be always 3 years, because current issue is caused by the fix to a previous one (#1711 reopen) and any solution without constraining the Y axis would certainly break in the future. There would be several months from now that will feature blank space to the left of the graph that will get pushed out eventually.

This is how it would look like for present data:

![image](https://user-images.githubusercontent.com/1550337/39208590-bb8c06d6-4803-11e8-8fee-980cde0b9f8d.png)

**Comment by woju** [comment] 2018-04-24 19:31
Current month is not a problem and I think it was already discussed. The problem is lack of contrast between red and purple.

**Comment by woju** [comment] 2018-04-24 19:41
OK, so here is new version, and it's at least readable:

![image](https://user-images.githubusercontent.com/1550337/39210132-17104946-4808-11e8-809b-a8a2edfd5d96.png)

**Comment by marmarek** [comment] 2018-04-24 20:00
> Current month is not a problem and I think it was already discussed. The problem is lack of contrast between red and purple.

Yes, those are independent issues.

**Comment by woju** [comment] 2018-04-25 09:09
The fix is now live so closing.

**Comment by rootkovska** [comment] 2018-04-28 09:01
Can we make the chart less ugly? Thank you!

**Comment by rootkovska** [comment] 2018-05-07 08:59
To elaborate more:
 1. reintroduce gaps between the bars (perhaps without outlines though)
 2. Either change to the more fine-grained pattern for the Tor areas, or -- better yet -- use shading (i.e. darker color). The current, sparse, pattern looks really bad.

**Comment by woju** [comment] 2018-05-09 12:42
1. The problem with gaps between bars is that they were fine when the bars were widely apart, but after some time passed, they became uneven, which was uglier than with continuous graph. So I'd like to leave it as is.

2. That's doable, but I'd have to to get those colours from somewhere. Some time ago Brennan got something resembling a colour palette for Qubes (https://www.qubes-os.org/doc/style-guide/#colors) and the colours in the graph are from there for consistency with the rest of the webpage (sans red, because for some reason it doesn't mix with other colours). But this palette lacks different shades for the same hue.
I can drop the palette and get some other colour set (maybe [Tango](http://tango.freedesktop.org/Tango_Icon_Theme_Guidelines#Color_Palette)? we already use it for VM labels).

**Comment by woju** [comment] 2018-05-09 13:47
![image](https://user-images.githubusercontent.com/1550337/39818074-46beb760-53a0-11e8-86fc-3ef8e8ba3db6.png)

**Comment by woju** [comment] 2018-05-11 19:14
I think actionable points are done. Closing.

**Closed by woju** 2018-05-11 19:14 UTC
Labels: C: website, P: major, bug
