### ISSUE TITLE
One click should not be able to trigger two GUI items in VM Manager

### ISSUE THREAD

**Issue by gutsle** [QubesOS/qubes-issues#1911] opened 2016-04-15 23:44 UTC
#### Qubes OS version (e.g., `R3.1`):

Qubes release 3.1 (R3.1)
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

VM Manager
### Expected behavior:

Right-clicking on a VM and then releasing should only open the context menu.
### Actual behavior:

The context menu opens on mouse-down and mouse-up activates menu items in case any are under the mouse.
### Steps to reproduce the behavior:

see above
### General notes:

I understand that sometimes activation on mouse-up and sometimes on mouse-down is common. The mixture seems weird however.
Since right-click + short hold seems to trigger an menu-close on mouse-up this looks like an artifact of trying to serve mixed use cases.

I think the intended behavior might have been: 
1. user clicks and holds -> he can trigger menu items by mouse-up on them or just close the menu by mouse-up outside of it
2. user clicks and releases immediately -> menu stays open allows left clicking on menu items to trigger them

The way it stands I can click and release immediately and if I do this while moving the mouse slightly to the right I will end up with the VM settings open instead of the menu.

I am using xfce. Maybe this is only an xfce problem.
##

**Comment by axon-qubes** [comment] 2016-04-27 08:35
> I am using xfce. Maybe this is only an xfce problem.

I can reproduce this in KDE.

**Comment by andrewdavidwong** [comment] 2016-05-02 15:06
Actually, I've noticed that this behavior is not specific to Qubes Manager. In KDE, for example, try right clicking on the title bar of any window, then hovering your cursor through the menu options to move that window to a different virtual desktop, then release the the right mouse button. The window will move to the other virtual desktop, even though you've only clicked (and held) once.

**Comment by gutsle** [comment] 2016-05-03 21:12
Just to clarify, there are timings involved. Doing this in general might make sense it only becomes a problem if a normal click (clicking and releasing immediately without holding) is interpreted as click-hold-release and causes two clicks.

**Comment by andrewdavidwong** [comment] 2016-05-04 05:35
Can you confirm that the double-right-click timing is *faster* in Qubes Manager than elsewhere in dom0? If it's the same speed everywhere, then perhaps adjusting your system-wide double-click-timing setting is the solution here?

**Comment by unman** [comment] 2017-01-12 02:37
@andrewdavidwong 
Will you close this? I see no advantage in keeping it open, since (as you pointed out) the behaviour is not Qubes specific, and can be ameliorated by changing the mouse timing settings.
What would another resolution look like?

**Comment by andrewdavidwong** [comment] 2017-01-12 04:59
@unman: I think that either this issue or a related one should remain open on UX grounds. I've actually been thinking about this issue a lot lately because I've noticed that things *frequently* happen in Qubes Manager (and *only* in Qubes Manager) that I do not intend as a result of this issue (or perhaps related ones). For example, I *very* often find myself opening the Firewall settings tab of a VM when I intended only to open the right-click context menu for that VM. Sometimes, I even find that a VM is set to be autostarted, for example, when I never consciously enabled that setting, probably as the result of a stray click when trying to do something else. I do not experience such a high mousing/click error rate with other GUI programs I frequently use (file managers, web browsers, etc.). **In general, this makes Qubes Manager feel particularly fragile and error-prone.**

A few thoughts:

* I don't think changing mouse timing settings is the answer. Accidentally opening the Firewall settings tab, for example, occurs with only a single right-click if there's even the slightest mouse movement to the right while right-clicking. (Besides, I've become accustomed to this approximate double-click speed after decades of use across OSes, and I'd be unwilling to change it in order to accommodate the quirkiness of a single program. I suspect the same holds for most users.)

* It could be that there's something unorthodox with the way Qubes Manager is designed. (Maybe the context menu doesn't have enough pixel padding and opens up too close to the cursor, for example.)

* These issues might be (partially) resolved with the decomposition of Qubes Manager in 4.0 (#2132), so if you think the UX suggestions should go on that issue, that's fine with me.

**Comment by andrewdavidwong** [comment] 2017-01-12 05:06
> I don't think changing mouse timing settings is the answer. Accidentally opening the Firewall settings tab, for example, occurs with only a single right-click if there's even the slightest mouse movement to the right while right-clicking.

On second thought, maybe this could be the answer. If "single right-click while ever-so-slightly moving the mouse" is being interpreted as "two right-clicks" (maybe this is what @gutsle meant [above](https://github.com/QubesOS/qubes-issues/issues/1911#issuecomment-216666287)), then this could be (at least part of) the problem.

However, a cursory examination (no pun intended) of Xfce's "Mouse and Touchpad" settings panel doesn't immediately reveal any way to control this particular timing.

**Comment by adrelanos** [comment] 2017-01-12 14:15
Andrew David Wong:
> For example, I *very* often find myself opening the Firewall settings tab of a VM when I intended only to open the right-click context menu for that VM.

And I always assumed I messed up something! Okay, so I can confirm this
happening quite often for me in QVMM only as well.

**Comment by unman** [comment] 2017-01-13 00:17
I 'm not aware that this has ever happened to me, although I don't use the manager all that much.
Perhaps I have superior mousing skills? ;-)

I'm looking at the code now - is it an issue that could be fixed by offsetting the menu somewhat to make it less likely that folk will hit this?
It seems to me that the crucial part from the original report is this:
> I can click and release immediately and if I do this _while moving the mouse slightly to the right_

**Comment by unman** [comment] 2017-01-13 00:55
@andrewdavidwong @adrelanos 
Can you try this?

Copy /usr/lib64/python2.7/site-packages/qubesmanager  to a safe place.
cd /usr/lib64/python2.7/site-packages/qubesmanager
rm main.pyc
rm main.pyo
Edit main:py - find the line that says: `self.context_menu.exec_(self.table.mapToGlobal(point))`
(line 1723 in my copy)
and change `point` to `point+QPoint(10,0)`
So the final line is `self.context_menu.exec_(self.table.mapToGlobal(point+QPoint(10,0)))`

This will offset the menu 10 pts from the click point, which seems about right to me.
See if that resolves your issue, or try a larger offset

You'll need to kill the existing qubes-manager instance before you see the difference, obviously.

**Comment by andrewdavidwong** [comment] 2017-01-13 09:58
> Perhaps I have superior mousing skills? ;-)

Quite likely. 😄 

> Can you try this? [...]

Thanks! I'll try this for a while and monitor my error rate.

**Comment by unman** [comment] 2017-04-03 00:38
@andrewdavidwong Did you try this Andrew? Did you find it resolved the issue?

**Comment by andrewdavidwong** [comment] 2017-04-03 00:47
@unman: Yes, it's been working great! Thanks!

**Comment by unman** [comment] 2017-04-03 00:53
@andrewdavidwong  Thanks - I'll put in a PR to incorporte this.

**Closed** 2018-07-12 21:48 UTC
Labels: C: qubes-manager, P: major, UX, bug
