### ISSUE TITLE
Qubes Windows Tools GUI Driver, Huge Lag

### ISSUE THREAD

**Issue by this-is-the-username** [QubesOS/qubes-issues#4848] opened 2019-02-27 04:20 UTC
I'm having a huge amount of lag with the Windows GUI driver for QWT. Trying to run that single Window VM with the GUI driver installed (in or out of seamless mode) is laggy right from boot. Like when I hold down left-click and drag my mouse across the screen creating that selector for the icons on the desktop I have to wait 1-2 seconds for it to update some times. Typing is even worse. Trying to open something that updates its gui frequently like procexp and it's practically unusable. I'm using a Nvidia 10 series card if that would have anything to do with it I could use my Intel iGPU.

I also tried just not installing the gui driver (just Qubes core copy/paste functions and planning to use it like a normal vm with a desktop) and it works GREAT (ZERO lag) and I'm happy with this (I also make the screen resolution bigger in the Windows settings, 1080p) but then for some reasons when I try to boot it up again (or sometimes 2nd/3rd time) it doesn't show me any gui. It has the green light beside it but I don't get a window to interact with the VM. I try sending it the explorer command I get nothing.

As a desperate attempt to get anything that's not extremely laggy working I tried to install the Qubes GUI driver then disable it on Device Manager which worked at first (with a bunch of weird errors but it ran). Until I tried launching a couple programs and the VM A. Dies instantly or B. Blue screens

Any advice? Really loving the project, but the lag is unbearable and I can't work on it under those conditions.

Thank you.

EDIT: Also I have a ultrawide 21:9 monitor @75 hz 1080p, just in case that helps...

**Comment by andrewdavidwong** [comment] 2019-02-28 04:58
Duplicate of #1045

**Comment by andrewdavidwong** [comment] 2019-02-28 04:59
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Closed by andrewdavidwong** 2019-02-28 04:59 UTC
