### ISSUE TITLE
Qubes PDF converter silently fails to convert certain PDF files

### ISSUE THREAD

**Issue by tungsten987** [QubesOS/qubes-issues#7759] opened 2022-09-13 15:07 UTC
### Qubes OS release

4.1.1, using the default Debian disposable VM as the default disposable VM.

### Brief summary

Qubes PDF converter silently fails to convert certain PDF files. This happens using both the graphical option in Nautilus and the `qvm-convert-pdf` command-line tool.

An example file that triggers the issue is: https://archive.org/download/de_funkstille_zine/de_funkstille_zine.pdf

### Steps to reproduce

Try to use `qvm-convert-pdf` on the file linked above.

### Expected behavior

A new `trusted.pdf` file is created and the old, untrusted file is deleted.

### Actual behavior

The command-line tool does not output any error, it simply outputs "Total Sanitized Files:  0/1" and the PDF file is not converted: the new `.trusted.pdf` file is not created and the old untrusted file is not deleted.

### Troubleshooting

The issue lies in [client.py](https://github.com/QubesOS/qubes-app-linux-pdf-converter/blob/master/qubespdfconverter/client.py). The call to `images[0].save` on line 410 raises an exception which is not catched because line 418 only catches `IOError`. If we change lines 418-419 from:

```
        except IOError as e:
            raise RepresentationError("Failed to save representation") from e
```
to:
```
        except Exception as e:
            traceback.print_exc()
            raise RepresentationError("Failed to save representation") from e
```
and we `import traceback` at the top of the file, the following stacktrace gets printed:
```
Traceback (most recent call last):
  File "/home/user/tmp/client.py", line 409, in _save_reps
    await asyncio.get_running_loop().run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2164, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/PdfImagePlugin.py", line 41, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/usr/lib/python3/dist-packages/PIL/PdfImagePlugin.py", line 138, in _save
    palette = im.im.getpalette("RGB")
AttributeError: 'NoneType' object has no attribute 'getpalette'
```
So at this point, the issue seems to come from the Python Imaging Library (PIL). However, if we read [PIL documentation](https://pillow.readthedocs.io/en/stable/reference/Image.html) on the `PIL.Image.open` method, we learn that:
> This is a lazy operation; this function identifies the file, but the file remains open and the actual image data is not read from the file until you try to process the data (or call the [load()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.load) method).

### Fix

If we change Qubes PDF converter so that it calls load() after calling open(), by changing lines 394-398 from:
```
                images.append(await asyncio.get_running_loop().run_in_executor(
                    None,
                    Image.open,
                    Path(self.pdf.parent, f"{page}.png"))
                )
```
to:
```
                images.append(await asyncio.get_running_loop().run_in_executor(
                    None,
                    Image.open,
                    Path(self.pdf.parent, f"{page}.png"))
                )
                for image in images:
                    await asyncio.get_running_loop().run_in_executor(
                        None,
                        image.load
                    )
```
the issue is solved, and the PDF file converts successfully.

This probably requires additional eyes but I believe my proposed fix is correct. I'm not submitting a merge request because I don't know how to do it and I'm too lazy to learn how to do it after this troubleshooting session :)

**Comment by unman** [comment] 2022-09-13 15:27
I think this is a duplicate of #6681, but great trouble shooting.
Thanks for the example file which was sorely missed in #6681, and what
looks like a reasonable fix.

**Comment by andrewdavidwong** [comment] 2022-09-13 22:46
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2022-09-13 22:46 UTC
Labels: T: bug, P: default
