### ISSUE TITLE
VM logs filled with "host kernel: xen:grant_table: g.e x still pending" messages

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7539] opened 2022-06-01 22:40 UTC
### Qubes OS release

4.1

### Brief summary

Usually i keep Qubes running for several days and i turn it off on weekends, Im discovering that longer the VM running the more logs getting duplication messages. 

### Steps to reproduce

- Open any VM and keep it open for several days (preferable to keep an app opened as well like thunderbird or hexchat ..etc)

- Open Terminal and write:

`sudo journalctl -b `

- See the output

### Expected behavior

No duplication to this level at least.

### Actual behavior

E.g log:

```
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x735 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x149 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1bb4 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x12e still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1980 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x17a1 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0xc1 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x18a8 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x18b3 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x14c still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1c21 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x198c still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0xdc still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x720 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x15d still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x189f still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x177e still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1d3c still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1881 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x732 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x207 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x17c7 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1cc1 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x121 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x174a still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1780 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x162 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x1833 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x19e3 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x18a0 still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x179d still pending
May 31 15:41:09 host kernel: xen:grant_table: g.e. 0x730 still pending
```

Full log: 

[journalctl-b.txt](https://github.com/QubesOS/qubes-issues/files/8819146/journalctl-b.txt)

**Comment by DemiMarie** [comment] 2022-06-02 00:42
This is a Linux kernel bug.  For kernels provided by dom0 it has been fixed in 5.10.112, 5.17.4, and later.  Otherwise, please report this to the maintainer of the kernel package in your distribution.

**Comment by DemiMarie** [comment] 2022-06-02 01:44
> > This is a Linux kernel bug. For kernels provided by dom0 it has been fixed in 5.10.112, 5.17.4, and later. Otherwise, please report this to the maintainer of the kernel package in your distribution.
> 
> Isnt Templates in general using the same Qubes kernel anyway?

By default, yes, though you can use pvgrub2-pvh as the kernel and have it boot an in-vm kernel.

> I have 5.10.112 while reporting this issue.

Whoops!  Patch coming.

**Comment by adrelanos** [comment] 2022-06-04 17:09
That's good but I am not sure that's sufficient.... Because... Speculating...:

There might be an issue for long running VMs.

These xen:grant_table still pending are piling up over a few days. Getting more and more. On the first days, there are 70 such messages. On the last days, after the 4. days in the log there are 264 such messages.

In other words, the longer the VM is running, the more xen:grant_table still pending are piling are generated. By just disabling the debug message about it, these code paths might still be active. Could be a loop that's somehow recursively called more and more often.

This long running VM then might on the fourth day have started producing an unrelated error.

> Jun 01 00:09:33 host systemd-socket-proxyd[1619]: Failed to get remote socket: Too many open files

Is it possible that somehow more and more files are opened but never closed?

Until the messages getting more and more issue being resolved, it might not be a good idea to disable these messages?

**Comment by tzwcfq** [comment] 2022-06-04 19:13
I have this problem only with qubes based on whonix-ws/whonix-gw templates.
I can reliably trigger these messages in sys-whonix qube if I restart sdwdate.
1. Clone sys-whonix to sys-whonix2.
2. Open sys-whonix2 terminal and run:
`sudo journalctl -f -g grant_table`
3. Open Time Synchronisation Monitor widget for sys-whonix2 in tray and click on Restart sdwdate.
4. Exactly after 60 seconds I'm getting a bunch of xen:grant_table still pending warnings in sys-whonix2.

I thought it was related to qrexec_timeout so I've changed it from 60 seconds to 90 seconds for sys-whonix2 but still the warnings were coming after 60 seconds.
I've also tried to change default qrexec_timeout but it didn't change anything as well:
`qubes-prefs default_qrexec_timeout 90`

**Comment by DemiMarie** [comment] 2022-06-05 04:01
> Is it possible that somehow more and more files are opened but never closed?

Not sure.  At some point I plan to add some statistics (most likely to debugfs or sysfs) that allow monitoring the number of unreleased grants.  I had a hacky implementation that abused module parameters, but it was (rightly) rejected.  Module parameters are for configuration, not statistics.

**Comment by adrelanos** [comment] 2022-06-05 09:48
@tzwcfq
> I have this problem only with qubes based on whonix-ws/whonix-gw templates. I can reliably trigger these messages in sys-whonix qube if I restart sdwdate.
> 
> 1. Clone sys-whonix to sys-whonix2.
> 2. Open sys-whonix2 terminal and run:
>    `sudo journalctl -f -g grant_table`
> 3. Open Time Synchronisation Monitor widget for sys-whonix2 in tray and click on Restart sdwdate.
> 4. Exactly after 60 seconds I'm getting a bunch of xen:grant_table still pending warnings in sys-whonix2.
> 
> I thought it was related to qrexec_timeout so I've changed it from 60 seconds to 90 seconds for sys-whonix2 but still the warnings were coming after 60 seconds. I've also tried to change default qrexec_timeout but it didn't change anything as well: `qubes-prefs default_qrexec_timeout 90`

To avoid all complexity and mystery from sdwdate...
The consideration that sdwdate doing something very special, funky can most likely be removed from this issue. To see sdwdate effectively does is this:

    sudo journalctl | grep date | grep "\-\-set"

> Jun 04 17:17:33 host sdwdate[899]: 2022-06-04 17:17:33 - sdwdate - INFO - Instantly setting the time by using command: /bin/date --utc "+%Y-%m-%d %H:%M:%S" --set "@1654363053.400096416"
> Jun 05 09:41:30 host sdwdate[19460]: 2022-06-05 09:41:30 - sdwdate - INFO - Instantly setting the time by using command: /bin/date --utc "+%Y-%m-%d %H:%M:%S" --set "@1654422089.232627153"

The command can be copied from there. Then just prepend sudo. For example:

    sudo /bin/date --utc "+%Y-%m-%d %H:%M:%S" --set "@1654422089.232627153"

Can you confirm that these messages can be reliably reproduced by changing the system time using `date` for example by using above command?

**Comment by tzwcfq** [comment] 2022-06-05 14:42
I can't trigger this with just `date`.
Also I can't trigger this (or at least it's not reliable and it's not exactly after 60 seconds) when I run in sys-whonix2:
`sudo /usr/sbin/sdwdate-clock-jump`
I also can't trigger it with:
`sudo --non-interactive rm /var/run/sdwdate/success; sudo --non-interactive systemctl --no-pager --no-block restart sdwdate`
But I can trigger this every time when I restart sdwdate from sdwdate-gui tray icon.
Not sure what code will be executed when I do it from sdwdate-gui. Maybe it's called with `qrexec-client-vm`?

**Comment by tzwcfq** [comment] 2022-06-06 05:47
I've tested some more and if I close sdwdate-gui (Time Synchronisation Monitor -> Exit) then I can't trigger these messages by running any commands from my previous comment in terminal. It seems that I got these messages before just by random.
I guess that these messages are coming from sdwdate-gui but I don't know what exactly is causing them.

**Comment by adrelanos** [comment] 2022-06-08 10:21
This qubes-linux-kernel commit might be the cause?
https://github.com/QubesOS/qubes-linux-kernel/commit/a9ac49d5d0ea022d2d6103b3efab141bf3ea60d5

In other words, this qubes-linux-kernel patch might be the cause?
https://github.com/QubesOS/qubes-linux-kernel/blob/master/increase-reclaim-speed.patch

It contains textual string:
`deferring`

And related pull request https://github.com/QubesOS/qubes-linux-kernel/pull/592/files contains textual string:
`still pending`.

----

I can now reproduce it. So sdwdate-gui usage resulting in `deferring` messages for me while bug reporter experiencing `still pending` messages.

Actually sdwdate restart action from sdwdate-gui isn't even required for me. Just by using sdwdate-gui menu alone I am able to cause a ton of `deferring` messages.

sdwdate-gui as a simple non-root application shouldn't be able to cause any trouble for the Qubes kernel. Any idea how that is possible?

**Comment by adrelanos** [comment] 2022-06-08 10:34
### Qubes OS release

4.1

### Brief summary

A GUI application is able to cause lots of duplicated kernel messages and potentially a VM crash.

### Simple steps to reproduce

1. start sys-whonix

2. open a terminal and follow journal `sudo journalctl -f`

3. open sdwdate-gui menu

4. close sdwdate-gui menu by clicking somewhere else

5. witness `deferring` messages spam in the systemd journal log

### Advanced steps to reproduce

These "advanced steps" are to exclude the potential source of cause that GNU date / sclockadj / time setting could be the cause.

1. start sys-whonix

2. stop and mask sdwdate systemd unit

```
sudo systemctl stop sdwdate
```

```
sudo systemctl mask sdwdate
```

2. open a terminal and follow journal `sudo journalctl -f`

3. open sdwdate-gui menu

4. close sdwdate-gui menu by clicking somewhere else

5. witness `deferring` messages spam in the systemd journal log

### Notes

* sdwdate-gui is able to trigger this issue but the root issue is most likely in qubes-linux-kernel.
* sdwdate restart action from sdwdate-gui menu is not even requried.
* sdwdate systemd unit can be stopped/masked and probably even uninstalled.

### Expected behavior

* No duplicates log output.
* No potential of opening too many open files. (https://github.com/QubesOS/qubes-issues/issues/7539#issuecomment-1146651227)

### Actual behavior

```
Jun 08 10:20:43 host kernel: deferring g.e. redacted (pfn redacted)
Jun 08 10:20:43 host kernel: deferring g.e. redacted (pfn redacted)
Jun 08 10:20:43 host kernel: deferring g.e. redacted (pfn redacted)
...
```

### Impact / Severity

* Duplicated log output.
* While sdwdate-gui (without sdwdate) was found to be able to trigger this issue, other, more complex GUI applications might result in too many files to be opened and the VM crashing because of it.

### For issue tracking purposes

* This is a Qubes kernel issue.
* This is very most likely not an sdwdate-gui / Qubes-Whonix issue.
* Qubes-Whonix affected: yes.

**Comment by andrewdavidwong** [comment] 2022-06-08 21:16
@adrelanos, your latest comment on this issue is confusing to me. It appears to be a bug report using our issue template, but it's a comment on an existing bug report. While I appreciate that you are providing information in a structured and easy-to-read format, I am left puzzled about what to do with this information and how to process it, given the manner in which it was delivered. Could you please explain what you had in mind when posting this and what your intention is here?

**Comment by adrelanos** [comment] 2022-06-09 16:13
### Even simpler steps to reproduce

1. start a `debian-11` based App Qube

2. open a terminal and follow journal `sudo journalctl -f`

3. start `firefox`

(From the usual packages.debian.org repository.)

5. close `firefox`

6. witness `deferring` messages spam in the systemd journal log

### Other applications this can be reproduced with

* `chromium`
* `mousepad`

(From the usual packages.debian.org repository.)

Seems like any GUI application can cause that. Not only "complex" ones. Also pretty comparatively "simple" ones such as `mousepad`.

### potential error causes already excluded

* Kicksecure
* Whonix
* sdwdate
* sdwdate-gui

...because none of these were installed in the vanilla/stock `debian-11` template.
(I always keep a stock Qubes `debian-11` template, fully upgraded for purposes of comparison, testing, bug reporting.)

### reason why I am dedicated to this issue

It would be sad to see pull request https://github.com/QubesOS/qubes-linux-kernel/pull/592 which is only a cosmetic fix disabling the message spam to be the reason this issue gets closed and forgotten. It doesn't address the following:

It might be a cause for "opening too many files", general VM instability, crashing? -> https://github.com/QubesOS/qubes-issues/issues/7539#issuecomment-1146651227 Yes, possibly. -> https://github.com/QubesOS/qubes-issues/issues/7539#issuecomment-1146736989

**Comment by DemiMarie** [comment] 2022-06-10 01:43
@adrelanos: would it be sufficient to provide sysfs files that include statistics?

**Comment by adrelanos** [comment] 2022-06-10 09:47
> Edit: This will not fix the problem, but it will be necessary to track down what is happening. The large volume of log messages is not helpful for debugging. My plan is to have the logging off by default, but include additional information when it is on.

Understood. Its an excellent plan.

> @adrelanos: would it be sufficient to provide sysfs files that include statistics?

That would certainly be most helpful. However, I am worried that if this is causing an issue later, nobody will get the idea to check the file in sysfs to see its contents. Hence, wondering...

Would it be possible to occasionally (non-spam) send kernel messages (which then end up in journal) with a summary or as a notification if some worrisome / useful for debugging thresholds are exceeded in the statistics?

My assumption is the sysfs statistics will contain some numbers as well as that you know which numbers seem normal and which excessive to warrant further debugging. Even if not excessive now, something else in the kernel or otherwise might change and this could be an issue later on. In that case, if any of the measurements (statistics) looks excessive -> post a warning in kernel messages with a hint to check out the sysfs file and report to developers.

**Comment by marmarek** [comment] 2022-06-10 13:46
> Would it be possible to occasionally (non-spam) send kernel messages (which then end up in journal) with a summary or as a notification if some worrisome / useful for debugging thresholds are exceeded in the statistics?

That's might be a good idea. In fact, there is a code to collect statistics for such summary already. @DemiMarie can you make the `gnttab_handle_deferred` print a summary at info(?) level? I think it can go instead of `Freed %zu references` message, but include both `referred_count` and `leaked_count` (the latter wont change there, but is useful to print anyway). It might be useful to add another counter within `gnttab_handle_deferred` - how many of those deferred entries are past `warn_delay`. And maybe even condition loglevel based on that (if any gets to `warn_delay==0` - print stats as "info" or "warn", otherwise as "debug").

In any case, the `still pending` message does reveal some actual problem. It is printed only if a page isn't released after some longer time (60s?) - which should _not_ happen normally (we have few places where shared memory is released asynchronously, but the delay should be rather minimal).

**Closed** 2022-07-20 02:23 UTC
Labels: T: bug, C: kernel, P: default, needs diagnosis

**Comment by adrelanos** [comment] 2022-07-22 09:25
Is comment by https://github.com/QubesOS/qubes-issues/issues/7539#issuecomment-1152380726 now obsoleted with this fix? Or should a new ticket created for it?

I guess, should there be a similar issue we'll have `still pending` messages in journal. Since `still pending` won't be hidden, the print summary in journal solution as described in https://github.com/QubesOS/qubes-issues/issues/7539#issuecomment-1152380726 won't be required?

**Comment by marmarek** [comment] 2022-07-22 09:58
> Is comment by [#7539 (comment)](https://github.com/QubesOS/qubes-issues/issues/7539#issuecomment-1152380726) now obsoleted with this fix?

Not worth doing.

**Comment by Nanzikambe** [comment] 2022-07-30 11:37
I'm tracking down something that _might_ be unrelated to this bug:

Using firefox 103 (latest) using picture-in-picture then clicking the fullscreen button frequently results in a totally unresponsive appvm (all apps, not just terminal) requiring me to reboot or qvm-kill it from dom0. I'm unable to find anything in the logs specifically related to that however I came across hundreds of thousands of these messages:

`[Sat Jul 30 13:14:13 2022] deferring g.e. 0xdc65 (pfn 0x177259)`

The reason I think these are unrelated to my firefox issue is that I can find them in *ALL* appvms regardless of  my use of the system (sys-net, sys-whonix, etc) and whether or not that appvm has firefox (latest or esr even installed). To test this I just upgraded to qubes-gui-daemon as described in this thread, and the behavior continues...

dom0
```user@dom0:~$ dnf list qubes-gui-daemon
Qubes OS Repository for Dom0                    2.9 MB/s | 3.0 kB     00:00    
Qubes OS Repository for Dom0                     22 MB/s | 137 kB     00:00    
Installed Packages
qubes-gui-daemon.x86_64             4.1.23-1.fc32             @qubes-dom0-cached
```

app-vm after doing nothing more than starting firefox 103 and restoring previous session:

```user@appvm:~$ sudo dmesg --ctime | egrep "deferring g.e." | wc -l
5461```

Questions: are these unrelated as I suspect? How do I prevent appvms filling my logs & wearing out my SSDs with these spammed messages.

**Comment by TheWanderer1983** [comment] 2022-08-08 03:19
I'm still having this issue. 
I have upgraded kernel on VMs to  5.18.9-1.fc32.qubes.x86_64. Kernel in Dom0 upgraded to 5.18.9-1fc32
qubes-gui-daemon  4.1.23-1+deb11u1. 
I'm noticing this when I have firefox and thunderbird open on different vms. Both show same flooding in logs.

**Comment by m-v-b** [comment] 2022-08-08 06:45
I am not 100% certain, but I believe that this issue is the same as issue #7631, and I think that we will need a kernel patch similar to the one discussed in that issue to resolve the "still pending" messages. I will add a comment to #7631, shortly, as well.
