### ISSUE TITLE
can't override dpi setting on fedora-29 template

### ISSUE THREAD

**Issue by kamou** [QubesOS/qubes-issues#4679] opened 2019-01-04 00:58 UTC
### Qubes OS version:

Qubes R4.0

### Affected component(s): 

X11

---

### Steps to reproduce the behavior:

1. install fedora-29 template with
```
sudo qubes-dom0-update qubes-template-fedora-29
```

2. start the fedora-29 template
3. edit `~/.Xresources` and add `Xft.dpi: 220`
4. edit `/etc/X11/Xresources` and add `Xft.dpi: 220`
5. reboot the template 

### Expected behavior:

`xdpyinfo | grep resolution` shows:
```
resolution:     220x220 dots per inch
```

### Actual behavior:

`xdpyinfo | grep resolution` shows:
```
resolution:     96x96 dots per inch
```

### General notes:

Works pretty well with dom0, fedora-26 template, and sys-whonix template

---

**Comment by andrewdavidwong** [comment] 2019-01-04 02:02
Possible duplicate of #1951.

**Comment by kamou** [comment] 2019-01-05 13:01
also tried adding `-dpi 220` option in /usr/bin/qubes-run-xorg.sh
but it seems that either it is not taken into account or it just gets overridden later during runtime.
also checking dpyinfo might not be that relevant as dpyinfo is not showing proper value when dpi is correctly set on other templates

**Comment by taradiddles** [comment] 2019-01-06 08:07
See https://github.com/Qubes-Community/Contents/blob/master/docs/customization/dpi-scaling.md
Please tell me if that worked for you (maybe something changed in f29). At some point I'll send a PR to include that doc in the official qubes docs since it seems to be a frequent issue amongst qubes users.

**Comment by kamou** [comment] 2019-01-08 07:14
thank you @taradiddles I tried that page, it worked for the fedora-29 VM,
however, when changing my `personal` VM to use the fedora-29 template, the settings from  `/etc/dconf/db/local.d/dpi` did not apply anymore.
The solution was to remove .config/dconf/user and apply the settings again with:
```
gsettings set org.gnome.desktop.interface scaling-factor 2
gsettings set org.gnome.desktop.interface text-scaling-factor 2
```
also, I'd like to add that changing `scaling-factor` doesn't change anything (on my side), only `text-scaling-factor` seems to change something. I guess Qt applications, for example, won't be properly scaled.

**Comment by kamou** [comment] 2019-01-08 07:16
Confirmed, just tried kdiff3, icons are too small, but the text is OK.
It is ok for my use cases for now, but I guess there still is a problem.
If you have any other thoughts, will be glad to help and try.

**Comment by taradiddles** [comment] 2019-01-10 09:17
@kamou, thanks for the feedback.
I'll update the doc to reflect that one should reset the values in the AppVM too if they were set beforehand.
No idea about the small icons in kdiff3. Did they at least change size when increasing the dpi ?

**Closed** 2023-08-05 09:19 UTC
Labels: C: Fedora, P: default, eol-4.0
