### ISSUE TITLE
garcon and xfwm4 failed to install

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4928] opened 2019-03-29 17:44 UTC
**Qubes OS version**
The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal.

4.1 (although cat /etc/qubes-release showing 4.0)

**Affected component(s) or functionality**
The component or functionality of Qubes OS that is not working as expected.

updating garcon and xfwm4 in dom0

**To Reproduce**

just run `sudo qubes-dom0-update` in dom0 terminal

**Screenshots**

![qubeissue](https://user-images.githubusercontent.com/11895339/55252149-1848ea00-524a-11e9-887b-cd533522e552.png)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here.

#4225 (maybe)

**Comment by TNTBOMBOM** [comment] 2019-03-29 17:46
(the labels of the bug added by default ...)

**Comment by marmarek** [comment] 2019-03-29 18:26
There is no instalable or testable version of R4.1 yet. Especially, Xfce are not uploaded into R4.1 repository (you can check specific components [here](https://ftp.qubes-os.org/~qubesosbot/status.html), in "Packages for fc29 dom0" section).
So, until there is any testable version of R4.1, I'm going to say it's expected behavior.
I don't think there is point in having separate issues for every package that needs to be updated to fc29 (#4225 is a good place to track it already), so I'm closing this one.

**Closed by marmarek** 2019-03-29 18:26 UTC
Labels: P: default, T: bug

**Comment by andrewdavidwong** [comment] 2019-03-30 00:07
> (the labels of the bug added by default ...)

Yes, it's set up that way intentionally. The labels appear to be correct for this issue. What's the problem?

**Comment by andrewdavidwong** [comment] 2019-03-30 00:08
This is actually a duplicate of #4792. You just have to do:

```
$ sudo dnf reinstall garcon xfwm4

```

I had to do this 10 days ago.

**Comment by TNTBOMBOM** [comment] 2019-04-01 08:27
> There is no instalable or testable version of R4.1 yet.

Sorry its a typo meant to say 4.0.1

> Yes, it's set up that way intentionally. The labels appear to be correct for this issue. What's the problem?

no problems , just looked weird. 

> $ sudo dnf reinstall garcon xfwm4

Thanks that solved it.
