### ISSUE TITLE
[split-gpg] `zenity` aborts on Fedora-40-minimal

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#9307] opened 2024-06-18 07:48 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.2

### Brief summary

Running any `qubes-gpg-client` command fails since the latest update with:
```
/etc/qubes-rpc/qubes.Gpg: line 38:  2205 Aborted                 (core dumped) zenity --question --no-wrap --text "$msg_text" 2> /dev/null < /dev/null > /dev/null
EOF
```

So the `zenity` command aborts in the `split-gpg` VM.

### Steps to reproduce

```
> qubes-gpg-client
/etc/qubes-rpc/qubes.Gpg: line 38:  2205 Aborted                 (core dumped) zenity --question --no-wrap --text "$msg_text" 2> /dev/null < /dev/null > /dev/null
EOF

```

### Expected behavior

Command gets executed

### Actual behavior

Apparently `Zenity` aborts.

### Additional info

I will provide a `valgrind` stack trace later.

**Comment by ben-grande** [comment] 2024-06-18 08:57
Duplicate of:

- https://github.com/QubesOS/qubes-issues/issues/9268

**Closed** 2024-06-19 05:40 UTC
Labels: T: bug, R: duplicate, P: default
