### ISSUE TITLE
processes created from UI/qvm-run do not inherit PATH environment variable from login shell

### ISSUE THREAD

**Issue by qubesanon** [QubesOS/qubes-issues#7425] opened 2022-04-06 00:42 UTC
### Qubes OS release
4.1. This is a recent regression. I believe the behavior changed in the last week or two.

### Brief summary
Qubes does create a login shell upon VM start and for the most part applications inherit from that environment. However, the `PATH` environment variable gets overridden at some point.

Other GNU/Linux OSes handle this differently. For example, Ubuntu correctly inherits `PATH` from the GUI login.

### Steps to reproduce
Edit some VM to add some instrumentation to ~/.bash_profile.
```
[user@<vm> ] $ echo >>~/.bash_profile 'echo >>~/login.log "$(date --rfc-3339=seconds) $(pstree --arguments --show-parents --show-pids --vt100 $$)"'
[user@<vm> ] $ echo >>~/.bash_profile 'export PROFILE_SOURCED=1'
[user@<vm> ] $ echo >>~/.bash_profile 'export PATH="${PATH}":~/test/bin/'
```

From dom0, start VM.
```
qvm-start <vm> && sleep 20s && qvm-run <vm> gnome-terminal
```

In terminal, verify that log was written to, but from a different process tree than our own. Also verify that `PROFILE_SOURCED` is set but `PATH` is not modified as expected.
```
[user@<vm> ] $ echo $PROFILE_SOURCED
[user@<vm> ] $ echo $PATH
```
### Expected behavior
Profile is sourced once, not by the terminal. `PATH` is correctly updated.

### Actual behavior
Same as expected, except `PATH` does not have the desired modification.

**Comment by marmarek** [comment] 2022-04-06 01:08
Generally, login shell settings do not necessary need to propagate into GUI applications. In fact, login shell may be not involved in GUI application start at all. The fact that on Qubes it does, is rather detail of the current implementation, which at some angle can be even considered a bug.

There are alternative mechanisms for setting env variables for all user applications, including `environment.d` or `systemctl --user set-environment`. [This commit](https://github.com/QubesOS/qubes-gui-agent-linux/pull/151/commits/ac4b08b15c236a1a463e079fa77ccf8daea1e482) is related.

**Comment by andrewdavidwong** [comment] 2022-04-06 04:12
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2022-04-06 04:12 UTC
Labels: T: bug, P: default

**Comment by qubesanon** [comment] 2022-04-06 11:29
That's great! I'm happy to see that support for that is implemented. That works for my use case, is sufficiently general, and a standard.

This works for me and I am ok with leaving this as "not an issue". Thanks manuel @rudd-o!
