### ISSUE TITLE
`qubes-dom0-update` shows `No updates available` in case of network is down / `qubes-dom0-update` fails to notice if repositories are unreachable / network is down

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7254] opened 2022-02-09 11:08 UTC
### Qubes OS release

R4.1

### Brief summary

* `qubes-dom0-update` shows `No updates available` in case of network down.
* `qubes-dom0-update` fails to notice if repositories are unreachable.
* `qubes-dom0-update` fails to notice if network is down.

### Steps to reproduce

* remove network cable / disable WiFi
* run `sudo qubes-dom0-update`
* see `No updates available`
* Be confused that `No updates available` even though some packages are outdated.

### Actual behavior

> sudo qubes-dom0-update --show-output --console

```
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
No updates available
```

It shows the VM window too quickly before it closes. Impossible to read it.

Impossible to know that networking is actually down.

### Expected behavior

`sudo qubes-dom0-update` output should be same as `sudo qubes-dom0-update --show-output --console`.

> sudo qubes-dom0-update --show-output --console

```
Using sys-vpn-work as UpdateVM to download updates for Dom0; this may take some time...
Unable to detect release version (use '--releasever' to specify release version)
Fedora 32 - x86_64 - Updates                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'updates':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Fedora 32 - x86_64                              0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Qubes Dom0 Repository (updates)                 0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'qubes-dom0-current':
  - Curl error (6): Couldn't resolve host name for https://yum.qubes-os.org/r4.1/current/dom0/fc32/repodata/repomd.xml.metalink [Could not resolve host: yum.qubes-os.org]
Error: Failed to download metadata for repo 'qubes-dom0-current': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://yum.qubes-os.org/r4.1/current/dom0/fc32/repodata/repomd.xml.metalink [Could not resolve host: yum.qubes-os.org]
Qubes Templates repository                      0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'qubes-templates-itl':
  - Curl error (6): Couldn't resolve host name for https://yum.qubes-os.org/r4.1/templates-itl/repodata/repomd.xml.metalink [Could not resolve host: yum.qubes-os.org]
Error: Failed to download metadata for repo 'qubes-templates-itl': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://yum.qubes-os.org/r4.1/templates-itl/repodata/repomd.xml.metalink [Could not resolve host: yum.qubes-os.org]
Ignoring repositories: updates, fedora, qubes-dom0-current, qubes-templates-itl
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
No updates available
```

That part...

```
Nothing to do.
Complete!
No packages downloaded
No updates available
```

is still wrong and confusing but one reading the output would know that something is wrong.

`--show-output --console` disabled by default is a bad idea at this stage of development. +1 for usability in case everything is OK but -5 usability/security/debuggability in case of issues.

## misc

Maybe could be split in 2-3 separate issues but not sure that would be useful.

This is not a bug report about a specific failure that needs debugging on my side. (Which was my fault - network cable not connected - now resolved.) This is a bug report for the way error handling in case of networking issues.

**Comment by andrewdavidwong** [comment] 2022-02-09 14:59
Duplicate of #6585

**Comment by andrewdavidwong** [comment] 2022-02-09 15:02
On second look, maybe it's not a duplicate. (See the difference between what's observed here and my observations about `qubes-dom0-update` in #6585.) Either way, it's closely related and might ultimately have the same fix, but I'll reopen since it's technically different.

**Comment by andrewdavidwong** [comment] 2022-08-23 23:39
I'm not sure if I'm experiencing the same bug, but I occasionally get this error message when updating dom0 via `qubesctl`:

```
          ID: update
    Function: pkg.uptodate
      Result: False
     Comment: Command failed with status 1. Additional info follows:
              
              cmd:
                  - --quiet
                  - --console
                  - --show-output
                  - --action=list
                  - upgrades
              retcode:
                  1
              stderr:
                  Running scope as unit: run-rb517a4e12e9c4ada8a21331e67d94184.scope
                  Using sys-update as UpdateVM to download updates for Dom0; this may take some time...
                  Unable to detect release version (use '--releasever' to specify release version)
                  Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f32&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
              stdout:
     Started: 11:25:12.326926
    Duration: 42273.492 ms
     Changes:   

```

**Comment by DemiMarie** [comment] 2022-08-24 04:25
This is expected @andrewdavidwong.

**Comment by 3hhh** [comment] 2022-08-25 16:12
Updating via salt should be fixed by #6585 thanks to @DemiMarie.

The `qubes-dom0-update` issue described here is likely a byproduct of #7558, if it works with `--console`.

**Comment by 3hhh** [comment] 2023-03-18 10:42
Might be fixed by https://github.com/QubesOS/qubes-core-admin-linux/commit/41c5f12ae4bbe5e79676abc5b90700d724dd3109 - I haven't tested it yet.

**Closed** 2024-12-07 14:37 UTC
Labels: T: bug, P: major, ux, diagnosed, C: updates, affects-4.1, eol-4.1

**Comment by DemiMarie** [comment] 2024-12-08 02:51
Definitely fixed.
