### ISSUE TITLE
Fedora 26 and fedora 26 minimal templates "update sign" stuck in Qubes R 3.2

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#3743] opened 2018-03-25 17:35 UTC
### Qubes OS version:

R 3.2

### Affected component(s): 

Fedora-26 based templates 

Fedora 26-minimal based templates 

---

### Steps to reproduce the behavior:

Carefully observe the Qubes VM manager after updating a bunch of F25 templates to F26

### Expected behavior:

No update sign, since they are definitely, totally, very certainly updated to F26 and all updates are installed

### Actual behavior:

Update sign (the downwards facing green arrow) is present.

If update process is initiated it runs without issue, but reports that there is nothing to do (no fresh updates available)

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-03-25 17:54
Duplicate of #2009

**Comment by andrewdavidwong** [comment] 2018-03-25 17:54
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-25 17:54 UTC
