### ISSUE TITLE
pulseaudio-qubes needs an update for PulseAudio 12 in Fedora 28

### ISSUE THREAD

**Issue by mattmccutchen** [QubesOS/qubes-issues#4072] opened 2018-07-12 20:28 UTC
Fedora 28 has updated to PulseAudio 12 yesterday ([update entry](https://bodhi.fedoraproject.org/updates/pulseaudio-12.0-3.fc28#comment-809789)).  pulseaudio-qubes currently has a dependency on PulseAudio 11.1 and needs an update to match.  I didn't find any previous discussion on qubes-users or qubes-devel.

### Qubes OS version:

4.0

### Affected component(s):

pulseaudio-qubes

---

### Steps to reproduce the behavior:

```
dnf distro-sync --best
```

### Expected behavior:

Successful update.

### Actual behavior:

```
Error: 
 Problem 1: package pulseaudio-qubes-4.0.10-1.fc28.x86_64 requires pulseaudio = 11.1, but none of the providers can be installed
  - cannot install both pulseaudio-11.1-18.fc28.x86_64 and pulseaudio-12.0-3.fc28.x86_64
  - cannot install the best update candidate for package pulseaudio-qubes-4.0.10-1.fc28.x86_64
  - cannot install the best update candidate for package pulseaudio-11.1-18.fc28.1.x86_64
  - pulseaudio-11.1-18.fc28.1.x86_64 does not belong to a distupgrade repository
 Problem 2: problem with installed package pulseaudio-qubes-4.0.10-1.fc28.x86_64
  - package pulseaudio-qubes-4.0.10-1.fc28.x86_64 requires pulseaudio = 11.1, but none of the providers can be installed
  - package pulseaudio-11.1-18.fc28.x86_64 requires libpulsecommon-11.1.so()(64bit), but none of the providers can be installed
  - cannot install both pulseaudio-libs-11.1-18.fc28.x86_64 and pulseaudio-libs-12.0-3.fc28.x86_64
  - package pulseaudio-11.1-18.fc28.1.x86_64 requires pulseaudio-libs(x86-64) = 11.1-18.fc28.1, but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-libs-11.1-18.fc28.1.x86_64
  - pulseaudio-libs-11.1-18.fc28.1.x86_64 does not belong to a distupgrade repository
```

### General notes:

---

**Comment by marmarek** [comment] 2018-07-12 20:40
Related: https://github.com/QubesOS/qubes-gui-agent-linux/pull/44 - waiting for @arjan-s to sign the commit.

// imagine here a rant about Fedora putting major, potentially incompatible changes, into a _stable_ release, instead of putting it only to devel branch, which will be released only few months from now anyway

**Comment by akkuladezeit** [comment] 2018-07-14 04:17
i think there is now the issuse on Fedora27 templates...

**Comment by Aekez** [comment] 2018-07-14 11:03
> i think there is now the issuse on Fedora27 templates...

Indeed, it seems the imaginary rant can be extended now after they now also included it in fedora-27 stable repo's as well :') 

I wonder, how come the fedora developers did the same to fedora-27, don't they actually observe their own updates i.e. in fedora-28, before doing the same to fedora-27 (especially since there was a delay between the 27/28 update)? Broken autoremoval dependencies, failed updates due to wrong dependencies, and also (as far as I can tell) weak security in the updating process from man in the middle attacks? It does kind of give the feeling the fedora developers aren't taking reliability and security very seriously. But then again, what do I know, I don't have that kind of insight after all :)

**Comment by akkuladezeit** [comment] 2018-07-15 09:34
when is will be fix? or how can i fix it XD?

**Closed** 2018-07-15 21:35 UTC
Labels: C: other, task

**Comment by MilkManzJourDaddy** [comment] 2018-07-31 13:09
I would rather see the dependencies fixed/pushed to r3.2 stable repo's before this issue was closed.  Some of us are still running 3.2, perhaps due to budget, or waiting for a good selection of hardware confirmed for 4.x

**Comment by marmarek** [comment] 2018-07-31 15:05
Our workflow include closing issue when fix is committed to master branch. Tracking what happens later is achieved using labels and updates-status repository, which reference relevant tickets here.
Update fixing this particular issue for R3.2 is here: https://github.com/QubesOS/updates-status/issues/622

**Comment by MilkManzJourDaddy** [comment] 2018-08-02 10:57
Another repo' instead of the issues repo'…  Hmmm.  So I need a chart and tutorial on how to follow issue resolution.  Well thanks for sharing.

**Comment by akkuladezeit** [comment] 2018-08-02 16:46
not fixed ... is used testing and it was solved but today. its back .... 
 
Problem 1: package pulseaudio-qubes-4.0.11-1.fc27.x86_64 requires pulseaudio = 12.0, but none of the providers can be installed
  - cannot install both pulseaudio-12.2-1.fc27.x86_64 and pulseaudio-12.0-3.fc27.x86_64
  - cannot install the best update candidate for package pulseaudio-qubes-4.0.11-1.fc27.x86_64
  - cannot install the best update candidate for package pulseaudio-12.0-3.fc27.x86_64
 Problem 2: package qubes-vm-recommended-4.0.2-1.fc27.noarch requires pulseaudio-qubes, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.11-1.fc27.x86_64 requires pulseaudio = 12.0, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.10-1.fc27.x86_64 requires pulseaudio = 11.1, but none of the providers can be installed
  - package pulseaudio-12.0-3.fc27.x86_64 requires libpulsecommon-12.0.so()(64bit), but none of the providers can be installed
  - package pulseaudio-11.1-3.fc27.x86_64 requires libpulsecommon-11.1.so()(64bit), but none of the providers can be installed
  - cannot install both pulseaudio-libs-12.2-1.fc27.x86_64 and pulseaudio-libs-12.0-3.fc27.x86_64
  - cannot install both pulseaudio-libs-11.1-3.fc27.x86_64 and pulseaudio-libs-12.2-1.fc27.x86_64
  - cannot install the best update candidate for package qubes-vm-recommended-4.0.2-1.fc27.noarch
  - cannot install the best update candidate for package pulseaudio-libs-12.0-3.fc27.x86_64
 Problem 3: problem with installed package pulseaudio-qubes-4.0.11-1.fc27.x86_64
  - package pulseaudio-qubes-4.0.11-1.fc27.x86_64 requires pulseaudio = 12.0, but none of the providers can be installed
  - cannot install both pulseaudio-12.2-1.fc27.x86_64 and pulseaudio-12.0-3.fc27.x86_64
  - package pulseaudio-module-bluetooth-12.2-1.fc27.x86_64 requires libpulsecore-12.2.so()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-bluetooth-12.0-3.fc27.x86_64
 Problem 4: problem with installed package qubes-vm-recommended-4.0.2-1.fc27.noarch
  - package qubes-vm-recommended-4.0.2-1.fc27.noarch requires pulseaudio-qubes, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.11-1.fc27.x86_64 requires pulseaudio = 12.0, but none of the providers can be installed
  - package pulseaudio-qubes-4.0.10-1.fc27.x86_64 requires pulseaudio = 11.1, but none of the providers can be installed
  - cannot install both pulseaudio-12.2-1.fc27.x86_64 and pulseaudio-12.0-3.fc27.x86_64
  - cannot install both pulseaudio-11.1-3.fc27.x86_64 and pulseaudio-12.2-1.fc27.x86_64
  - package pulseaudio-module-x11-12.2-1.fc27.x86_64 requires libpulsecore-12.2.so()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-x11-12.0-3.fc27.x86_64
=======================================================================================
 Package                       Arch     Version          Repository               Size
=======================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 pulseaudio                    x86_64   11.1-3.fc27      fedora                  983 k
 pulseaudio                    x86_64   12.2-1.fc27      updates                 997 k
 pulseaudio-libs               x86_64   11.1-3.fc27      fedora                  666 k
 pulseaudio-libs               x86_64   12.2-1.fc27      updates                 681 k
Skipping packages with broken dependencies:
 pulseaudio-module-bluetooth   x86_64   12.2-1.fc27      updates                  83 k
 pulseaudio-module-x11         x86_64   12.2-1.fc27      updates                  42 k
 pulseaudio-qubes              x86_64   4.0.10-1.fc27    qubes-vm-r4.0-current    19 k

Transaction Summary
=======================================================================================
Skip  7 Packages

**Comment by akkuladezeit** [comment] 2018-08-02 16:52
its also in the testing....

**Comment by andrewdavidwong** [comment] 2018-08-03 03:40
@MilkManzJourDaddy:

> Another repo' instead of the issues repo'… Hmmm. So I need a chart and tutorial on how to follow issue resolution. Well thanks for sharing.

> `QubesOS/updates-status` is described as "Track packages in **testing** repository".  I referred to the **stable** repo'.   Perhaps there is  a doc' somewhere on following the logic.  Thanks.

I don't entirely understand what you're asking for, but perhaps this documentation will help:

https://www.qubes-os.org/doc/testing/

**Comment by mattmccutchen** [comment] 2018-08-03 03:57
This issue is not to be confused with #4151, which is not in stable yet.

**Comment by akkuladezeit** [comment] 2018-08-03 15:18
ok so i have to create an new issue for the error on F27 ? this thread seams to be f28 only? or nobody cared about the F27 comments.

**Comment by mattmccutchen** [comment] 2018-08-03 19:55
> ok so i have to create an new issue for the error on F27 ? this thread seams to be f28 only? or nobody cared about the F27 comments.

I see what happened: each time pulseaudio-qubes is built, it picks up a dependency on the current stable version of PulseAudio in each version of Fedora.  At the time pulseaudio-qubes-4.0.14 was built, Fedora 28 stable was on PulseAudio 12.2 but Fedora 27 stable was still on PulseAudio 12.0.  Now Fedora 27 stable is on PulseAudio 12.2, so we need another rebuild (which will fix Fedora 27 and make no difference to Fedora 28).  I filed #4180.
