### ISSUE TITLE
Intel Nuc13 fails to resume from suspend

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#8379] opened 2023-07-31 01:56 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.2

### Brief summary

Intel Nuc13 fails to resume from suspend.

### Steps to reproduce

1. open terminal on dom0
2. enter `systemctl suspend`
3. Wait for the power button to indicate successful entrance to the suspend state
4. attempt to resume: either type on keyboard or hit the power button

### Expected behavior

The system should resume.

### Actual behavior

The system remains in the suspend state, as evidenced by the power button remaining in the BIOS-selected mode.
For instance, I made BIOS settings to reduce the illumination to 50% and turn green and do a "strobling".  Yes, there are some entertaining names for various effects one can programme the power button when in certain power states.

No manner of keyboard activity, USB device removal/insertion, ThunderBolt attached device removal/insertion, strobling-button presses, will cause the system to resume.  The sole remedy is to press and hold the strobling button until it ceases strobling and the system turns off, usually 15 seconds or so.

For comparison, I booted my Tails USB device and did a suspend.  Resume worked immediately.  One press of the strobling button cause it to immediately cease strobling, turn back to 100% white, and the lock screen to be presented.  After unlock, the system ran perfectly.  Performed several suspend/resume cycles.  Joyful strobling for all.

**Comment by jamke** [comment] 2023-07-31 13:17
It's probably not a NUC-related problem. Qubes OS is not resume/suspend properly on many modern Intel CPUs even in supported `S3` mode.
Read other issues and forum about this issue, plenty of cases. Sometime different kernel versions of `dom0` and/or qubes can help. But in many cases suspend simply will not worki in Qubes OS nowadays.

**Comment by DemiMarie** [comment] 2023-07-31 18:28
I think there are two problems here:

1. S3 being deprecated by Intel and therefore likely either not implemented at all or buggy.
2. S0ix not being supported by Xen.

Closing as a duplicate of #6411 as that is the actual solution.  Anything else (including S3) is just a temporary hack.

**Comment by marmarek** [comment] 2023-07-31 18:43
> 1. S3 being deprecated by Intel and therefore likely either not implemented at all or buggy.

There are mixed signals about this, but if OEM does support it (as present in firmware settings), it should work. Please don't introduce confusion.

**Comment by jamke** [comment] 2023-07-31 19:18
> There are mixed signals about this, but if OEM does support it (as present in firmware settings), it should work. Please don't introduce confusion.

It is true. S3 is still supported on the newest Thinkpads and on the recently QubesOS-certified laptop model.

But suspend in Qubes OS is not working on these S3 devices in many cases due to kernel/xen/qubes os problems. But it works in *ubuntu. 
So, I do not think the issue is a duplicate of #6411. Maybe it is duplicate of something else, but not #6411.

**Comment by permezel** [comment] 2023-08-01 01:20
> It's probably not a NUC-related problem. Qubes OS does not resume/suspend properly on many modern Intel CPUs even in supported `S3` mode. Read other issues and forum about this issue, plenty of cases. Sometime different kernel versions of `dom0` and/or qubes can help. But in many cases suspend simply will not worki in Qubes OS nowadays.

Worked perfectly on the Nuc10 I was running on.  I know, 'nuc*' does not imply compatibility.  I am not looking for reasons why I should expect it not to work.  Rather, I would like to, having reported the bug, work towards a fix, which might benefit all.  The main problem with NUC*, though, is that they have no serial port or JTAG connexion (that I know of) to facilitate debug.
I do have a magic USB debug cable, but never found much support for it on any platforms I have tried it on.  There is a USB spec which states that if a cable has certain attributes, it can be used as a debug cable.  I suppose I should dig up info on it and see if I can get it to function on the NUC.
I used to write low level debuggers and real time kernels from scratch, so even though my brain is now 93% mush, I may be able to facilitate debug.
Weird hardware states do make things more challenging, though.

**Comment by marmarek** [comment] 2023-08-01 01:49
> I do have a magic USB debug cable

USB 2 (EHCI) or USB 3 (XHCI) one? Theoretically both may work with Xen, [with appropriate parameters](https://xenbits.xen.org/docs/unstable/misc/xen-command-line.html#console):
 - `dbgp=ehci console=ehci`
 - `dbgp=xhci,share=yes console=xhci`

The practice is more complicated. I never managed to get EHCI one working. For XHCI, it kinda works, you may need to adjust the controller number (`dbgp=xhci1`, `dbgp=xhci2`, or simply specific PCI device like `dbgp=xhci@pci00:14.0`), and you need to have the cable plugged in during boot. But then, depending on specific system, sys-usb may not be happy ([patch series dealing with the issue](https://lore.kernel.org/xen-devel/CAKf6xpspPdt6mM4MuL2-vwXHu23ahm874e4kZqROqCwC4cd=fA@mail.gmail.com/t/#ecae36efcd2c0e214c1346264ffe15e57be94135a)).

**Comment by marmarek** [comment] 2023-08-01 01:52
Another thing worth checking: see `/sys/power/mem_sleep` - currently only `deep` mode is expected to work. If you have `s2idle` selected, you need to change that.

**Comment by permezel** [comment] 2023-08-01 07:05
> Another thing worth checking: see `/sys/power/mem_sleep` - currently only `deep` mode is expected to work. If you have `s2idle` selected, you need to change that.

```
# cat /sys/power/mem_sleep 
[s2idle] deep
# echo deep >/sys/power/mem_sleep
# cat /sys/power/mem_sleep 
s2idle [deep]
```

I'll try that....

**Comment by permezel** [comment] 2023-08-01 08:02
> Another thing worth checking: see `/sys/power/mem_sleep` - currently only `deep` mode is expected to work. If you have `s2idle` selected, you need to change that.

I tried suspend with "deep".  The power button remained white, indicating it did not go into pause mode.

**Comment by marmarek** [comment] 2023-08-01 12:10
> [105419.663490] usb usb5-port1: Cannot enable. Maybe the USB cable is bad?

This is expected without boot params.

**Comment by permezel** [comment] 2023-08-02 07:11
> > [105419.663490] usb usb5-port1: Cannot enable. Maybe the USB cable is bad?
> 
> This is expected without boot params.

Got it working!  This is really slick.  I can now log-in to dom0 over serial.  This is going to make things so much easier.  To evidence this, witness the console debug info I can now effortlessly capture and add:

```
(XEN) d14v1 EPT violation 0xdaa (-w-/r-x) gpa 0x000000f2088470 mfn 0x6124188 type 5
(XEN) d14v1 Walking EPT tables for GFN f2088:
(XEN) d14v1  epte 9c000008dddec107
(XEN) d14v1  epte 9c000008dddeb107
(XEN) d14v1  epte 9c000008dddce107
(XEN) d14v1  epte 9c50006124188145
(XEN) d14v1  --- GLA 0xffffb2f5403b8470
(XEN) domain_crash called from vmx.c:3545
(XEN) Domain 14 (vcpu#1) crashed on cpu#4:
(XEN) ----[ Xen-4.14.5  x86_64  debug=n   Not tainted ]----
(XEN) CPU:    4
(XEN) RIP:    0010:[<ffffffffabc01ca4>]
(XEN) RFLAGS: 0000000000010286   CONTEXT: hvm guest (d14v1)
(XEN) rax: 00000000e0000000   rbx: ffff9ba401c1f000   rcx: 00000000f208ffff
(XEN) rdx: 000000000000846c   rsi: 00000000f2080000   rdi: ffffffffae69bbd0
(XEN) rbp: ffffb2f5403b846c   rsp: ffffb2f54001fd78   r8:  0000000000000000
(XEN) r9:  00000000000f208f   r10: ffff9ba401c741e0   r11: 0000000000020fff
(XEN) r12: ffffb2f5403b0000   r13: ffffb2f5403b8470   r14: 0000000000002201
(XEN) r15: 00000000242e5241   cr0: 0000000080050033   cr4: 0000000000750ee0
(XEN) cr3: 0000000013c22000   cr2: 0000000000000000
(XEN) fsb: 0000000000000000   gsb: ffff9ba417100000   gss: 0000000000000000
(XEN) ds: 0000   es: 0000   fs: 0000   gs: 0000   ss: 0000   cs: 0010
qrexec-daemon startup failed: 2023-08-02 16:58:53.286 qrexec-daemon[13647]: qrexec-daemon.c:135:sigchld_parent_handler: Connection to the VM failed

```

This was from
```
[nimda@dom0 ~]$ qvm-start sys-usb
```

I can no longer interact with the USB keyboard, mouse, and thus cannot login "normally".
I saw some goog-results about debugging guest VMs.  I thought: not interested in that right now, I need to debug xen+dom0, not guests.  Wrong again.

**Comment by permezel** [comment] 2023-08-02 07:16
> > Another thing worth checking: see `/sys/power/mem_sleep` - currently only `deep` mode is expected to work. If you have `s2idle` selected, you need to change that.
> 
> I tried suspend with "deep". The power button remained white, indicating it did not go into pause mode.

More data points.  Booted ubuntu live USB thumb (more recent version).  Verified that the default is `[s2idle]`.  Changed to `deep` and tried to suspend.  Did not resume.  Did not appear to enter paused state.  Power button remained 100%.

Tried again with the default `[s2idle]`.  Pause did set 50%+green, but was resistant to resume.

Made space available and did an install from the live system.  On reboot, suspend/resume works.  Must have applied some updates during the "install to disc" process.

**Comment by marmarek** [comment] 2023-08-02 10:09
> `(XEN) d14v1 EPT violation 0xdaa (-w-/r-x) gpa 0x000000f2088470 mfn 0x6124188 type 5`

I'm pretty sure it is this issue:

> But then, depending on specific system, sys-usb may not be happy ([patch series dealing with the issue](https://lore.kernel.org/xen-devel/CAKf6xpspPdt6mM4MuL2-vwXHu23ahm874e4kZqROqCwC4cd=fA@mail.gmail.com/t/#ecae36efcd2c0e214c1346264ffe15e57be94135a)).

Anyway, you can probably suspend the system using usb console and then see what happens.

**Comment by permezel** [comment] 2023-08-07 02:38
> > `(XEN) d14v1 EPT violation 0xdaa (-w-/r-x) gpa 0x000000f2088470 mfn 0x6124188 type 5`
> 
> I'm pretty sure it is this issue:
> 
> > But then, depending on specific system, sys-usb may not be happy ([patch series dealing with the issue](https://lore.kernel.org/xen-devel/CAKf6xpspPdt6mM4MuL2-vwXHu23ahm874e4kZqROqCwC4cd=fA@mail.gmail.com/t/#ecae36efcd2c0e214c1346264ffe15e57be94135a)).


@marmarek  I agree.   I have been trying to put together another system so I can build/debug xen so I can figure out where those patches are.  Been trying with FreeBSD 13.2 as dom0 and domU but that has its own issues.

Do you know if the patches are in  Qubes 4.2 Xen version?  I'll probably try that next.

**Closed** 2024-12-07 13:41 UTC
Labels: T: bug, P: default, hardware support, needs diagnosis, C: power management, affects-4.1, eol-4.1
