### ISSUE TITLE
Attaching Android devices via qvm-usb fails if the device is in USB debugging mode

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#3080] opened 2017-09-05 16:15 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25 but I don't think it's template dependent.

---

### Expected behavior:
qvm-usb -a <appvm> <device> works for USB debugging

### Actual behavior:
ERROR: Invalid speed received is printed in the console

### Steps to reproduce the behavior:
Enable USB debugging on the Android device
Connect the device to machine with sys-usb enabled
Try attaching the device via qvm-usb

### General notes:
Issue does not occur when USB Debugging is not enabled.

---

**Comment by matheusd** [comment] 2018-03-14 17:48
I have this problem on an android 5.1.1 phone, but **not** on an android 4.2 phone.

**Comment by rustybird** [comment] 2018-03-14 20:23
Duplicate of #2202 - at some point in Android history (when exactly depends on the ROM), the adb server started resetting the USB device and became incompatible with USB forwarding.

**Comment by andrewdavidwong** [comment] 2018-03-15 05:25
Duplicate of #2022

**Comment by andrewdavidwong** [comment] 2018-03-15 05:25
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-15 05:25 UTC
Labels: C: other, bug

**Comment by eug48** [comment] 2018-12-27 08:50
Typo: should be duplicate of #2202

**Comment by andrewdavidwong** [comment] 2018-12-27 09:53
> Typo: should be duplicate of #2202

Thanks. Sorry about that.
