### ISSUE TITLE
Resizing Debian 9 root fs images to add 10MB results in unbootable VM

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4821] opened 2019-02-14 19:52 UTC
### Qubes OS version:

R4.0

### Affected component(s):

Qubes Manager/VM resize code

---

### Steps to reproduce the behavior:

1. Create a standalone VM based on a Debian 9 template
2. Boot it and then halt it
3. Resize the root fs storage to be 10 MB bigger
4. Boot the VM

### Expected behavior:

VM boots

### Actual behavior:

VM does not boot and Xen console logs show a kernel panic because the root fs could not be mounted

### General notes:

Filed per https://github.com/QubesOS/qubes-core-agent-linux/pull/152#issuecomment-462260529.

---

**Comment by lunarthegrey** [comment] 2019-02-23 09:20
Tried testing this by adding 10MiB and 20MiB and my VM was bootable. From what size are you testing it, 10240MiB to 10250MiB and so on?

**Comment by unman** [comment] 2019-02-24 11:20
@lunarthegrey  Did you test with a standaloneVM?
@strugee Are you using CLI or GUI for step3? If CLI, what command?

**Comment by lunarthegrey** [comment] 2019-02-24 15:02
@unman I tested with a StandaloneVM, yes. I also used the GUI.

**Comment by unman** [comment] 2019-02-24 15:59
@lunarthegrey Thanks. 

Works for me too.

**Comment by unman** [comment] 2019-02-24 16:01
@strugee In addition to previous questions, can you report on the packages you have installed? Which repos are you using?

**Comment by unman** [comment] 2019-03-04 16:11
@andrewdavidwong In absence of further information, and given independent reports of resizing working as expected, I suggest you close this.

**Comment by andrewdavidwong** [comment] 2019-03-05 01:31
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by strugee** [comment] 2019-03-05 04:33
Hi, sorry. It's midterms season for me so I haven't found the time to respond to this issue.

I can still reproduce this issue. System storage max size is going from 10240 MiB to 10250 MiB. All operations were done using Qubes Manager.

I'm attaching the dom0 [Xen console logs](https://github.com/QubesOS/qubes-issues/files/2929273/guest-my-new-qube.log) for the test StandaloneVM to this ticket, as well as [`dpkg -l`](https://github.com/QubesOS/qubes-issues/files/2929274/dpkg-l.txt) from the TemplateVM the test StandaloneVM was based on. I haven't added any custom repositories besides what comes with the standard Debian 9 template.

**Comment by marmarek** [comment] 2019-03-05 09:41
Can you try switching to in-VM kernel? Set virt mode to HVM and kernel to none (in case of CLI, `qvm-prefs VMNAME kernel ''`). I suspect it may be related to https://github.com/QubesOS/qubes-linux-utils/commit/5eb526d, which is applied when using in-VM kernel only (you already have qubes-utils 4.0.23). If that will help, I need to apply the same to initramfs bundled with dom0-provided kernel.

**Comment by unman** [comment] 2019-03-05 15:37
@strugee Thanks for coming back!

I still cant reproduce this with a standalone Debian-9 based on a template.
In my case, using Qube Manager the System storage gets set to 10252, (rather than the 10250 I set). The new qube starts as expected.
That's using the default kernel (4.14.74-1), and PVH.

My apt list is wildly different from yours, of course, and still has qubes-utils 4.0.22. I'll try upgrading that, and then selecting some of your packages.
In the meantime can you please confirm that things work fine with a stock debian-9 template.

**Comment by unman** [comment] 2019-03-06 00:37
@strugee I have just taken a stock debian-9 template, installed all the packages from your dpkg list, and confirmed all qubes packages in particular are at the same version number.
I have then created a new standaloneVM using that template, and set to kernel you are using.
The new StandaloneVM starts, and also starts after resizing the rootfs.
So I'm left (again) unable to confirm this bug.

Any thoughts?
(I'm assuming you've tried this with a number of different StandaloneVMS with the same result.)
Is there anything particular about your setup? What fs are you using?

**Comment by strugee** [comment] 2019-03-11 21:00
> @strugee Thanks for coming back!

Sure! Thanks for being patient - I know it's frustrating to get a bug report and then the reporter never follows up.

>  (I'm assuming you've tried this with a number of different StandaloneVMS with the same result.)

Yes, every time I reproduce I create and then destroy a new StandaloneVM.

>  Is there anything particular about your setup? What fs are you using?

I don't think so? It's LVM (not LVM Thin) for dom0, standard ext4 inside VMs.

Unfortunately my Qubes VM Settings are borked due to a different bug, which I'll investigate later today, so it's difficult to look into the rest of the questions here. But it's definitely on my list.

**Comment by strugee** [comment] 2019-03-13 05:48
> Unfortunately my Qubes VM Settings are borked due to a different bug, which I'll investigate later today, so it's difficult to look into the rest of the questions here. But it's definitely on my list.

Looks like I'm hitting #4866. When that's fixed I'll be able to look into this. Thanks for everyone's patience :thumbsup:

**Comment by strugee** [comment] 2019-03-20 03:11
> Can you try switching to in-VM kernel? Set virt mode to HVM and kernel to none (in case of CLI, `qvm-prefs VMNAME kernel ''`).

@marmarek OK, so, with the following STR:

1. Create new StandaloneVM clone based on my debian-9 template
2. Boot the new qube
3. Shut down the qube
4. In Qubes Manager's settings, set the new qube's virt mode to HVM and its kernel to `(none)`
5. Boot and shut down qube again (don't think this matters, just including it in this list because I accidentally did it before resizing the system volume)
6. Resize system volume in Qubes Manager VM settings to be 10 MiB more (i.e. 10250MiB)
7. Boot qube again

The new qube still reports failure to connect to the qrexec agent for 60 seconds... but weirdly enough, I don't see anything in the Xen logs. I mean _nothing_. I literally watched with `tail -f` and nothing changed.

> In my case, using Qube Manager the System storage gets set to 10252, (rather than the 10250 I set).

@unman weird! I do not observe this same behavior, even after I hit OK and reopen the VM settings window. I'm on Qubes Manager 4.0.31, according to `dnf info qubes-manager`.

I almost wonder if I should just upload a backup of the TemplateVM somewhere so both of you can reproduce this problem. It shouldn't be too hard to scrub any personal information out of it (there's barely any in there anyway, and all in the private volume).

**Comment by LockedTab** [comment] 2019-10-30 20:12
Hi! I am experiencing similar problems with VM resizing in Qube Manager. But in my case it happens not only with Debian , but Fedora aswell. Or actually any VM. Standalone  Template or AppVM does not matter.
I recently reinstalled the 4.0.1 Qubes OS, as i made a dom0 update and then i started experiencing this issue. I cloned Fedora 30 template, resized system storage with Qube Manager, then it failed to boot. Then i tried same clone, resize with Debian 10, same outcome. 
Now i have a completely fresh Qubes install, Fedora 30, Debian 10 and whonix 15 templates. do Updated latest. And i have the same.

the VM qrexec log contains only this:
domain dead
cannot connect to qrexec agent: No such process

Resizing even with the smallest steps produces the same. 
Tried also to resize in dom0 with   sudo qvm-volume extend VM:root/private XGB  (resize done without issue, but VM fail to boot) 
I use kernel 4.19.80-1 PVH 
If i switch to 4.14.74-1 PVH issue persists. "
If i switch to no kernel with HVM mode i get the message: domain failed to start cannot connect to qrexec agent for 60 sec. see log. I can not really translate the log to troubleshoot this.
I can reproduce this anytime with any vm at the moment, What means, if i run out of the default given space, i stuck. The Dom0 has 400GB free. 
Could you help to somehow troubleshoot this please? Or pinpoint where to look? 
I started to use linux with Qubes OS only 2 month ago.

**Comment by marmarek** [comment] 2019-10-30 22:52
Take a look at `/var/log/xen/console/guest-VMNAME.log` (replace VMNAME with actual name). The most interesting part should be at the end. You can also watch it using `tail -F` while starting the VM to see what new content appears there.

**Comment by LockedTab** [comment] 2019-10-30 23:02
Hi again!
It seems after two day of struggling, i found the extremely simple cause. But it is still a problem for others in the future.
I did resize my base template already to 25GBroot 11GBprivate BEFORE i started cloning.
Cloned the template, and the settings tab showing : Private Storage: 2048MB , System Storage : 10240MB. I did NOT checked the size at all with any other tool, i relied completely what the Qube Manager UI showing.
Now i had a hunch, i should check in dom0 /var/lib/qubes/vm-templates/myvm
Surprisingly the file sizes ofthe NEW cloned VM were not 10GB and 2GB, but exactly the same size as the source VM from which i cloned. a.k.a: root 25GB, private 11GB. 
When i tried to resize i was always sized 1-2 GB from the baseline 10GB what Qube Manager was showing. But that was actually SHRINKING the size. 
So now i typed in into the resize section in the Manager 27648MB. And everything went smooth. The VM started without issue. My problem seems to be solved. But maybe this idea helps others.

**Comment by marmarek** [comment] 2019-10-30 23:16
The tool should prevent you from shrinking, exactly for this reason. So, the issue is it actually allowed you to to shrink the disks. Also, displaying the volume sizes is wrong here.
What storage pool you use? As you mentioned `/var/lib/qubes/vm-templates/myvm` I assume it's `file` driver, not LVM, right? You can check that with `qvm-volume ls myvm` (observe first column).

**Comment by LockedTab** [comment] 2019-10-30 23:30
i do notknow if this is what you ask, but here is the outcome:
[Superman@dom0 ~]$ qvm-volume ls myvm
POOL:VOLUME                                       VMNAME          VOLUME_NAME  REVERT_POSSIBLE
linux-kernel:4.19.80-1                                 myvm                 kernel                No
varlibqubes:vm-templates/myvm/private     myvm                private                No
varlibqubes:vm-templates/myvm/root          myvm               root                     No
varlibqubes:vm-templates/fmyvm/volatile      myvm            volatile                 No

i already cloned/resized the third VM, and every time the Qube Manager shows 10240MBroot 2048MB private. no matter the size of the original. I am live checking the vm-template folder when cloning, and the file size is going up in the process till the exact match of the original VM size.  But Manager still shows default sizes.

**Comment by marmarek** [comment] 2019-10-30 23:39
And most likely this is exactly why qvm-volume didn't prevented you from shrinking.

**Comment by LockedTab** [comment] 2019-10-30 23:45
Intrestingly, when you create an AppVM  or a Standalone from the cloned template, without resizing it properly. the size shown on the new VM also the default 10GB 2GB. but the actual root.img and private.img size matches the supposed size.

**Comment by marmarek** [comment] 2019-10-30 23:49
Yes, that's exactly the issue - size in "file" storage driver (the one for `varlibqubes` pool) is taken from configuration, instead of actual image size. And clone operation lack updating that value. I'll fix this shortly.

**Comment by LockedTab** [comment] 2019-10-31 00:10
Now i  resized correctly, and installed some software, and did an update in the cloned TemplateVM (fedora30). Created a new AppVM based on this template, and without i touched it, the Qube Manager shows the correct numbers on the new AppVM. 
Is this because when i installed stuff, the size changed, and then it updated correctly?

**Comment by LockedTab** [comment] 2019-10-31 19:35
Thank you. And someone dared to say that Qubes has bad support. I strongly disagree.

**Closed** 2019-11-12 22:31 UTC
Labels: C: core, P: default, T: bug, r4.0-dom0-stable
