### ISSUE TITLE
R4.0-rc1 - Improper boot-time LUKS keyboard layout

### ISSUE THREAD

**Issue by alexis-** [QubesOS/qubes-issues#2971] opened 2017-08-04 13:34 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### Expected behavior:
Keyboard layout during boot-time for LUKS disk encryption should be the one set by default, during the installation procedure.

### Actual behavior:
Keyboard layout is set to qwerty, regardless of default keyboard layout.

### Steps to reproduce the behavior:
- Run Qubes R4.0-rc1 install
- Select US language
- Select a custom keyboard layout
- Proceed with rest of configuration, and install (default options in my case)
- At boot time, described issue occur

### General notes:
Keyboard layout otherwise behaves as expected (after disk de-encryption)

---

**Comment by KuroSaru** [comment] 2017-08-04 14:14
Can confirm this behaviour.

**Comment by alexis-** [comment] 2017-08-04 19:06
UEFI here

**Comment by awokd** [comment] 2018-03-19 01:58
Resolving https://github.com/QubesOS/qubes-issues/issues/3624 might resolve this one too?

**Comment by alexis-** [comment] 2018-03-23 15:17
I thought it was already solved ? I haven't faced this issue since RC2.

**Comment by andrewdavidwong** [comment] 2018-03-24 00:46
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-03-24 00:46 UTC
Labels: C: installer, P: major, bug

**Comment by awokd** [comment] 2018-04-01 16:17
@andrewdavidwong Not sure this one is fully resolved yet- https://www.mail-archive.com/qubes-users@googlegroups.com/msg20710.html.

**Comment by marmarek** [comment] 2018-04-01 18:02
Is it the same as #3234? There were relevant fixes in final 4.0 that didn't managed to get into rc5.

**Comment by awokd** [comment] 2018-04-01 18:36
Indeed; please disregard my comment!
