### ISSUE TITLE
Allow users to attach arbitrary free-form metadata to qubes for their own use

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6572] opened 2021-04-29 18:53 UTC
**The problem you're addressing (if any)**

I would like for users to be able to attach arbitrary freeform metadata to qubes for their own use.  This metadata is not machine readable, but it should be editable in the GUI, and qubes should be able to be grouped based on it.  Furthermore, it must support fairly arbitrary UTF-8 strings, since users need to be able to set it in their native language.

**Describe the solution you'd like**

I suggest reserving the `human.*` namespace of features for use by humans.  Such features are to be considered opaque to programs, and have no meaning beyond what the human user gives them.

**Where is the value to a user, and who might that user be?**

Users will be able to assign arbitrary freeform metadata.

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by ninavizz** [comment] 2021-04-29 19:22
This reads an awful lot like a follow-up to #6560... may I ask, is it @DemiMarie? 

Also: I love this issue so much, just because it proposes a designation for things in the code to be meaningful to human eyes, only. <3

**Comment by DemiMarie** [comment] 2021-04-29 19:40
> This reads an awful lot like a follow-up to #6560... may I ask, is it @DemiMarie?

No, but it is a follow-up to #6555 and thus to #2949.

> Also: I love this issue so much, just because it proposes a designation for things in the code to be meaningful to human eyes, only. <3

Thank you <3

In practice, such features will likely wind up being base64-encoded (or otherwise escaped) at some point, so that they can fit within the restrictions imposed by other parts of QubesOS.  Those restrictions are there for legitimate security reasons and I do not want to remove them.  But they will be unescaped in the GUI.

**Comment by andrewdavidwong** [comment] 2021-04-29 20:25
Related:#952

**Comment by ctrlaltf24** [comment] 2021-04-30 02:36
> In practice, such features will likely wind up being base64-encoded (or otherwise escaped) at some point, so that they can fit within the restrictions imposed by other parts of QubesOS. Those restrictions are there for legitimate security reasons and I do not want to remove them. 

Good Idea using base64! However, it could still be used as an attack vector; being able to put a binary blob in qubes.xml that is auto-decoded by qubes-manager, or other trusted software is problematic. https://github.com/QubesOS/qubes-issues/issues/899#issuecomment-290866746 .

> But they will be unescaped in the GUI.

Auto-decoding base64 in any trusted environment risks breaking the nice property of "The ultimate goal for qvm-backup-restore should be that, even if the backup was made on a compromised Qubes system, than the new system" https://github.com/QubesOS/qubes-issues/issues/899#issuecomment-290914510 . Perhaps by default only using ascii, but add an addition to enable UFT-8 (behind the scenes that would use base64 and validate the UTF-8), similar to allow_utf8_titles https://github.com/QubesOS/qubes-issues/issues/899#issuecomment-290891263 . Additionally adding a setting in qubes-manager to change whether to allow UTF-8 from within the UI). So an out of the box Qubes install would still have the nice security properties, however if users choose to accept the risk, they can use UTF-8, accepting the slight risk.

**Comment by marmarek** [comment] 2021-05-11 03:11
Rendering UTF-8 is not the only "scary" thing. Some toolkits (including both GTK and Qt) support (a subset of) markups like HTML or similar. So, allowing ascii only may still carry significant attack surface if not done carefully.

**Comment by ctrlaltf24** [comment] 2021-05-11 07:57
Correct me if I'm wrong, but can't Qubes also set their own features? Like when QWT sets gui [here](https://github.com/QubesOS/qubes-core-agent-windows/blob/a2aea339f91f972a5c334a0485f4c4783ffc12f7/src/advertise-tools/advertise-tools.c#L223)? If they can, then a Qubes-aware attack from an infected domU could inject a feature starting with `human.` and attempt to compromise the relatively complex dom0 parser (If it properly handles HTML, UTF-8, base64, ect). Doing a check for `human.` wouldn't be ideal as future development that allows for modification of features would need to be aware implement that check.

@ninavizz in the responses in the appmenu survey https://github.com/QubesOS/qubes-issues/issues/6560#issuecomment-837604021 did people want one UTF-8 compatible notes field, or multiple? Did they want to sort/filter on that? Or just have a separate dialog for seeing and editing the notes? Personally I'm fine with just ascii (aka valid input to qvm-features/qvm-tags).

**Comment by andrewdavidwong** [comment] 2023-09-22 19:33
Duplicate of #899

**Comment by andrewdavidwong** [comment] 2023-09-22 19:33
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-09-22 19:33 UTC
Labels: T: enhancement, C: other, localization, P: default
