### ISSUE TITLE
Qube Manager crashes when deleting just created AppVM

### ISSUE THREAD

**Issue by mio-19** [QubesOS/qubes-issues#6495] opened 2021-03-29 10:36 UTC
**Qubes OS version**

Qubes-20210327-x86_64.iso

**Affected component(s) or functionality**

Qube Manager

**To Reproduce**

1. Create a VM
2. Delete it

**Actual behavior**

It crashes

**Comment by EncryptedGiraffe** [comment] 2021-03-30 07:45
This also occurs in my recent build of 4.1, creating a qube then immediately deleting it crashes Qube Manager. The qube is actually deleted though. Additionally, if I create the qube, then close and open Qube Manager again, I'm able to delete it normally.

**Comment by EncryptedGiraffe** [comment] 2021-04-29 09:53
A bit of an update, I've realized that this also occurs with disposable VMs, if I create one based off a template, so it's called dispxxxx, then select it in the qube manager, then shutdown the qube, the manager crashes as well. So the issue isn't just deleting qubes, maybe just anytime the currently selected qube is removed? 

Going back to the original issue, I've attached the `journalctl -r` output for a test where I created a qube named `crash-testing` then immediately deleted it. I put the output in a text file just because there's so much of it, with the stack traces and everything.
Here it is: [log.txt](https://github.com/QubesOS/qubes-issues/files/6397688/log.txt)

**Comment by theperelomov** [comment] 2021-06-09 08:04
qubes-manager version 4.1.15-1
Some logs of qubes-qube-manager
`TypeError: invalid result from QubesTableModel.flags(), bool cannot be converted to PyQt5.QtCore.ItemFlags in this context`

My HotFix - And manager work fine
`return False` -> `return Qt.NoItemFlags` 
https://github.com/QubesOS/qubes-manager/blob/4e0ab3b46e477701b955bc28425648df5a5f5936/qubesmanager/qube_manager.py#L489

**ATTENTION**
think, this not solve issue
because 
>  Additionally, if I create the qube, then close and open Qube Manager again, I'm able to delete it normally.

**Comment by marmarta** [comment] 2023-12-11 23:14
Fixed by  https://github.com/QubesOS/qubes-manager/commit/703ea05460e42daa2c631abc749c8cd465fcdaba

**Closed by marmarta** 2023-12-11 23:14 UTC
Labels: T: bug, C: manager/widget, P: major, needs diagnosis, affects-4.1
