### ISSUE TITLE
Cannot Restore Backups from Qubes 4.0

### ISSUE THREAD

**Issue by Joeviocoe** [QubesOS/qubes-issues#3698] opened 2018-03-14 02:01 UTC
### Qubes OS version:
`R3.2`

### Affected component(s): 
Qubes-backup-restore

### Steps to reproduce the behavior:
Create any VM backup on Qubes 4.0 rc4/rc5
Copy file to Qubes 3.2 machine (verify same hash).
Restore with either GUI Qubes-Manager restore VM function or command-line qubes-backup-restore.

### Expected behavior:
Prompt to select VMs to restore

### Actual behavior:
`UnicodeDecodeError:  'ascii' codec can't decode byte 0xda in position 25: ordinal not in range(128)`

### General notes:
Can backup and restore 4.0 to 4.0, and 3.2 to 3.2.

### Related issues:
Also, Qubes 4.0 backup GUI does not show progress bar percentage.

**Comment by marmarek** [comment] 2018-03-14 02:07
This wont work. Restoring backup from newer major release is not supported on older one.

**Comment by andrewdavidwong** [comment] 2018-03-15 05:16
Closing as "not a bug," since migration in this direction is never intended or supported. If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2018-03-15 05:16 UTC
