### ISSUE TITLE
Dracut initqueue timeout on boot no dom0-root and swap.

### ISSUE THREAD

**Issue by Qubesafs** [QubesOS/qubes-issues#5372] opened 2019-10-05 20:33 UTC
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Whole system

**Brief summary**
When starting up the system, qubes OS takes ages to boot and when it boots it got thrown back into command prompt with errors.

**To Reproduce**
Shut down running qubes OS

**Expected behavior**
Expected to enter password to decrypt the disk

**Actual behavior**
No password required, no graphical interface, back to prompt
[222.987709] dracut-initqueue[337]: Warning:  dracut-initqueue timeout - starting timout scripts
[222.988659] dracut-initqueue[337]: Warning: Could not boot
[222.228845] dracut-initqueue[337]: Warning:  /dev/mapper/qubes_dom0-root does not exist
[222.236717] dracut-initqueue[337]: Warning:  /dev/qubes_dom0/root does not exist
[222.312342] dracut-initqueue[337]: Warning:  /dev/qubes_dom0/swap does not exist
[222.342322] dracut-initqueue[337]: Warning:  crypt LUKS UUID 1*****-****-**** not found
              Starting Dracut Emergency shell

Entering Emergency mode.Exit the shell to continue
etc etc

**Solutions you've tried**
Enter "reboot" in command prompt to reboot the system again.
After rebooting the system, the crypt password is being asked and then it boots.
When I shut down Qubes OS again and want to start it then same error, so have to reboot again.

**Comment by dracgitdev12** [comment] 2019-11-09 08:49
I've encountered almost the same issue, actually I had to type password and then it slowly boots right into emergency shell with the same errors except I dont have these lines:
"[222.342322] dracut-initqueue[337]: Warning: crypt LUKS UUID 1*****-- not found".  
"[222.312342] dracut-initqueue[337]: Warning: /dev/qubes_dom0/swap does not exist"

I have no clue what could be the reason of this because the last successful boot was ordinary, GUI showed that I had 59%~ of free space, full battery, no dom0 updates, shut down process was regular with no errors. Also my system is not dual-boot, only Qubes OS installed. The only thing I remember that about 2 weeks ago I had the same error but after single reboot it was solved somehow so I just ignored it. 

I've tried to find solution in mailing list and followed some advices but `lvchange` `vgchange` `lvconvert --repair` didn't help, though I managed to activate like half of my VMs and qubes_dom0/pool00 volume, but qubes_dom0/root stays inactive all the time. 

Offtopic: actually I'm not the first person to encounter this issue, but unfortunately I never saw even a single advice from devs how this can be repaired or how you can recover the data or at the very least prevent it from happening, because as regular Qubes OS user I find this bug to be critical and it demotivates me from using such an amazing product.

**Comment by StevenLColeman42** [comment] 2020-01-03 20:39
It appears that I have the same issue on my desktop at home according to the photo I just received.

I just repaired the logical volumes on Wednesday for a very similar issue.  It was just like issue #5160 only it was not after a fresh install. 

On Wed:
Check of pool qubes_dom0/pool100 failed (status:!). Manual repair required!
Warning: dracut-initqueue timeout - starting timeout scripts
Warning: Could not boot.
Warning: /dev/mapper/qubes_dom0-root does not exist
Warning: /dev/qubes_dom0/root does not exist

Today:
Warning: dracut-initqueue timeout - starting timeout scripts
Warning: Could not boot
Warning: /dev/mapper/qubes_dom0-root does not exist
Warning: /dev/qubes_dom0/root does not exist

The basic difference is there is no "manual repair required" message today. My root swap was not affected as near as I can tell.

I'm guessing I will have to rebuild it when I get home. I did get a backup after the first LVM repair Wed, hopefully, they are not backups of some trashed lvm volumes. It seemed to run perfectly fine in between though. It's just the booting in between that is problematic.

**Comment by hodlon** [comment] 2020-04-25 02:13
Bumping this issue as I just ran into it myself. Has there been any resolution?

**Comment by xaki23** [comment] 2020-04-25 10:25
> Bumping this issue as I just ran into it myself. Has there been any resolution?

what is your actual problem?
this issue is a hodgepodge of at least two entirely different problems. (probably more like 3-4)

some key questions:
* what version of qubes did you install?
* did the install ever work/boot correctly?
* what is not working now? 
* * is it "not asking for a luks passphrase"? 
* * or "after entering the luks passphrase, lvm is throwing errors"?
* if you look at the luks and lvm from a live image, what do things look like?

**Comment by andrewdavidwong** [comment] 2020-04-25 21:31
> this issue is a hodgepodge of at least two entirely different problems. (probably more like 3-4)

If that's the case, this should be separated into 2-4 separate issues. Could you help delineate what you see as the separate problems here?

**Comment by xaki23** [comment] 2020-04-26 09:03
> If that's the case, this should be separated into 2-4 separate issues. Could you help delineate what you see as the separate problems here?

there are at least two bigger clusters:

### LUKS problem(s)
* not asking for the LUKS password, long timeout, "crypt LUKS UUID 1*****-- not found"
* the initial post of this issue seems to fall in this category.
* this means something goes wrong very, very early.
* i have seen something like this happen if the installer can not figure out the luks UUID and just writes something useless into the boot config instead. (that particular case would be "installer seems to work, but firstboot does not")
* if there is a useful UUID in the boot config, the question is if it is the right UUID for the luks device.

### LVM problem(s)
* this means they are problems happening _after_ it asks for the luks passphrase and accepts it.
* none of the posts contain useful information to figure out _what_ is going on.
* semirandom guess would be "pool hit a out-of-space wall, hard".

the key distinguishing part between the clusters is "does it even ask for the luks passphrase or not".

**Comment by andrewdavidwong** [comment] 2020-04-27 14:10
Thank you. I propose that we consider this issue (#5372) to be for "LUKS problem(s)," and if the OP or anyone else desires, they can file a separate issue (or find an existing one) for "LVM problem(s)."

**Comment by hodlon** [comment] 2020-05-05 06:28
**Issue**: Booting up the system leads to a errors instead of booting fully into Qubes.

**Version**: Qubes 4.0

**Steps**:
1) Boot up the computer.
2) After being prompted, enter LUKS password.

**Expected**: After decrypting with my LUKS password being prompted for my system password in order to login.

**Observed**: The following errors display:

```[   211.961022] dracut -initqueue[418]: Warning: dracut-initqueue timeout - starting timeout scripts
[   212.490748] dracut -initqueue[418]: Warning: dracut-initqueue timeout - starting timeout scripts
[   213.019012] dracut -initqueue[418]: Warning: dracut-initqueue timeout - starting timeout scripts
[   213.019192] dracut -initqueue[418]: Warning: Could not boot.
[   213.051408] dracut -initqueue[418]: Warning: /dev/mapper/qubes_dom0-root does not exist
[   213.052114] dracut -initqueue[418]: Warning: /dev/qubes_dom0-root does not exist
Starting Dracut Emergency shell...
Warning: /dev/mapper/qubes_dom0-root does not exist
Warning: /dev/qubes_dom0-root does not exist

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue```

**Note**: The system was up-to-date and booting just fine before running into this issue for the first time just the other week.

Also, this thread describes my issue as well: https://groups.google.com/forum/#!topic/qubes-users/iVAamHcpH20

**Comment by eloquence** [comment] 2020-06-02 19:51
@marmarek and @andrewdavidwong: FYI, we so far have 2 internal and 3 external reports of users encountering [this](https://github.com/QubesOS/qubes-issues/issues/5372#issue-503012703) or very similar issues during long-term Qubes usage, where the system will fail to boot and the user gets dropped into this dracut shell.

Hypotheses I've heard around what can cause such behavior include:
- running out of disk space
- high concurrent disk usage
- unsafe shutdown (e.g., loss of battery power)

Can we help you narrow down this issue by investigating any of these, or other, hypotheses further, or do you feel you feel you have a pretty good sense of plausible root cause(s) at this point?

**Comment by marmarek** [comment] 2020-06-02 21:33
After getting the shell in dracut execute `lvm lvs | head` (drop `| head` if it isn't available) and see `pool00` and `root` usage stats. There should be `Data%` and `Meta%` columns. If any of them is near 100, then this is a disk space issue (data or metadata). 
You can also try to activate LVM volume groups with: `lvm vgchange -ay` and observe what error you'll get (if any).

**Comment by eloquence** [comment] 2020-06-02 23:12
Thanks @marmarek! Any thoughts on what could be done at the OS level to prevent users from encountering this issue during ordinary use?

**Comment by brendanhoar** [comment] 2020-06-02 23:58
Newly installed 4.1 systems will have a larger % set-aside for thin-pool metadata making it less likely to encounter one cause of this issue. 4.1 will also have substantially more warnings thrown to users when pools and volumes get close to full.

**Comment by lzmartinico** [comment] 2020-06-06 18:53
I am running into a possibly related problem (although maybe more akin to #5602 ). At boot, the luks prompt always fails with an invalid password error, and after three incorrect entries I am sent to dracut, with errors 
```
/dev/mapper/qubes_dom0-root does not exist
/dev/qubes_dom0/root does not exist
/dev/qubes_dom0/swap does not exist
```
Trying to luksOpen the partition does not work, and all of the lvm commands suggested in this thread or in the google groups thread do not return any meaningful output, as there are no volumes available. Before finding this bug report I suspected that I had forgotten my password or that I was typing it incorrectly, but after a "brute force" script to go through all possible typos I still couldn't decrypt it. I am also still able to boot into a second non-qubes hard drive, as well as opening that volume from dracut.

This is on a machine running up-to-date Qubes 4.0. It isn't the original machine where the disk was first encrypted, but I was still able to successfully boot into Qubes once before (if that could make any difference)

**Comment by Clef-0** [comment] 2020-06-08 09:42
Also having the same problem (crypto LUKS not found and emergency shell) after having a Qubes 4.0 installation (on a Dell XPS 7590 with EFI runtime services disabled) that had been working fine for about a week except for an issue where it wouldn't restore after entering sleep and I'd have to unsafely turn off the machine, though this time after turning it off and restarting it's produced this error. Someone mentioned rebuilding something and the console output mentioned regenerating initramfs - is it possible to restore the system without reinstalling then?

**Comment by Clef-0** [comment] 2020-06-17 12:15
To clarify, the issue started for me after an unsafe shutdown, and the system does not prompt me for a LUKS password. lvm lvs has no output in emergency mode, and I can't see the disk at all with fdisk or parted when I boot from the Installer USB. If there's anything I can do or provide to help diagnose it, I'm happy to. I've not reinstalled the system yet as there's a text document I'd ideally like to recover on one of the qubes, but it's not absolutely essential.

**Comment by DemiMarie** [comment] 2020-11-25 20:26
Not being able to find a LUKS volume honestly looks like hard disk corruption.  Could this be due to a hardware failure?

**Comment by DemiMarie** [comment] 2021-11-12 19:45
Is this problem still present?

**Comment by marmarek** [comment] 2021-12-21 21:44
Closing due to no recent similar reports, nor confirmation it still happens.

**Comment by rolls01** [comment] 2023-03-14 18:36
It's still happening. Same issue as described before.

**Comment by xaki23** [comment] 2023-03-14 23:32
> It's still happening. Same issue as described before.

what exactly is "as described"?
is this about a fresh install that fails on firstboot? which installer // iso was used?
is this about a install that worked before, but now doesnt? did anything happen that might have caused this?
do you get to the luks prompt or does it slow-fail without ever asking?

also, please try booting in text mode (remove rhgb and quiet from the kernel commandline at the grub prompt) to see more detail of what might be going wrong.

**Closed** 2024-12-07 13:43 UTC
Labels: T: bug, C: other, P: critical, needs diagnosis, affects-4.1, eol-4.1
