### ISSUE TITLE
rollback template change documentation is outdated

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#8284] opened 2023-06-21 07:09 UTC
### Qubes OS release

R4.1

### Brief summary

The documentation about [rollback template change](https://www.qubes-os.org/doc/template-implementation/#rollback-template-changes) seems outdated. It refers to a command `qvm-revert-template-changes` and to a script `/etc/xen/scripts/block-snapshot` while both don't exist on a stock R4.1.

### Expected behavior

The documentation should apply to the current release

### Actual behavior

It's not possible to use the documentation.

### Solution

There is a documentation explaining how to revert volumes, it's for advanced users, but I don't think this procedure is more complicated that the one is outdated. Maybe a link to https://www.qubes-os.org/doc/volume-backup-revert/ may be enough to replace the whole outdated content.

**Comment by unman** [comment] 2023-06-21 10:51
Duplicate of #8280

**Closed** 2023-06-21 10:52 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2023-06-21 22:47
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
