### ISSUE TITLE
4rc1 - Restored vm will not start due to uuid already existing?

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3144] opened 2017-10-03 19:00 UTC
#### Affected TemplateVMs: fedora-25
---
### Steps to reproduce the behavior:

Restore a previously backed up vm and try to start it.

### Expected behavior:

vm should not already have a uuid set as it was deleted  after backup.

### Actual behavior:

qvm-remove does not appear to fully delete a vm from the system, leaving crud that stops a subsequent restore starting.

### General notes:

I also note that qvm-remove **-v** does not add any verbosity? gives no output as without it.

---

**Comment by marmarek** [comment] 2017-10-06 20:57
Do you see the VM on `virsh -c xen:/// list --all` after removing with qvm-remove?

**Comment by mannp** [comment] 2017-10-07 16:46
Its giving me a 'command not found' executing that in the dom0 command line.

**Comment by marmarek** [comment] 2017-10-16 03:17
Install `libvirt-client` package in dom0 (`sudo qubes-dom0-update libvirt-client`) and try again.

**Comment by mannp** [comment] 2017-10-16 09:57
@marmarek I have reinstalled again so that I could continue using qubes, so can no longer debug this item.

**Comment by marmarta** [comment] 2019-01-16 20:19
It looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/4253 ; due to that and it not being replicable by the original bug finder, I'm closing this.

**Closed by marmarta** 2019-01-16 20:19 UTC
Labels: C: core, bug

**Comment by andrewdavidwong** [comment] 2019-01-17 07:39
@marmarta: Except in very rare circumstances, when there are duplicate issues, we always close the newer one as a duplicate of the older one. So, if #3144 and #4253 are indeed duplicates, then this one should be reopened and #4253 should be closed. However, I'm confused by your second comment. If they're duplicates, then why does the fact that the original reporter was unable to reproduce matter? Alternatively, why doesn't it also speak in favor of closing #4253?

**Comment by andrewdavidwong** [comment] 2019-01-18 03:04
Ok, maybe this is a case in which it makes sense to close the older one as a duplicate of the newer one, because we didn't discover until much later that both issues have the same underlying cause. (I don't actually know whether they have the same underlying cause, but I'm willing to defer to you on this.)
