### ISSUE TITLE
DisposableVM shuts down when a child window is closed even though original window is still open

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6346] opened 2021-01-16 20:47 UTC
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

DisposableVMs

**Brief summary**

Normally, a DisposableVM should continue running until its original window is closed. In this case, the DisposableVM shuts down  unexpectedly when a non-original window is closed.

**How Reproducible**

100%

**To Reproduce**

1. Have an archive of PDFs named `pdfs.tar.xz` in some VM
2. Open a Nautilus file manager window in a fresh DisposableVM (mine is based on Fedora Minimal)
3. qvm-copy `pdfs.tar.xz` to the fresh DisposableVM
4. Un-archive `pdfs.tar.xz` by double-clicking on it, creating a normal directory containing the PDFs
5. Open one of the PDFs in a PDF viewer or browser window
6. Close the PDF window you just opened

**Expected behavior**

Closing the PDF window does not cause the DisposableVM to shut down, because the DisposableVM's original window is Nautilus, which is still open.

**Actual behavior**

The DisposableVM shuts down unexpectedly, resulting in other unsaved work being lost.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/disposablevm/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found

**Comment by andrewdavidwong** [comment] 2021-01-16 21:01
Another way to reproduce:

1. Create an archive of some PDFs named `pdfs.tar.xz` in a DisposableVM
2. qvm-copy `pdfs.tar.xz` to some normal VM

As soon as the qvm-copy is done, the DisposableVM shuts itself down, even though all DisposableVM windows were still open (including the original).

**Comment by billystonka** [comment] 2021-02-23 23:45
Is there anything that can be provided to speed up diagnosing/fixing this? Any kind of logs or data?

I'm seeing this bug on a fresh 4.04rc2 install. It'd would be nice feature to have working.

**Comment by marmarek** [comment] 2021-02-24 00:35
I cannot reproduce it on R4.0, with fedora-33 based DisposableVM.

**Comment by andrewdavidwong** [comment] 2021-02-24 21:55
In my case, it occurred with Fedora 32. I haven't had a chance to try with Fedora 33 yet.

**Comment by neowutran** [comment] 2021-04-27 19:48
I was able to reproduce this issue in fedora 33.

1. in dom0: ``qvm-run -v --dispvm=fedora-dvm --service qubes.StartApp+org.gnome.Nautilus``
2. in the dispvm -> Open something (I tested the behavior on a PDF (with "evince" as the default pdf reader), and on a text file (with "gedit" as the default editor) 
3. close evince/gedit (nautilus is still running)

The disposableVM shutdown

(same as andrew, but "qvm-copy" and "un-archive" are not necessary to reproduce this issue)

**Comment by neowutran** [comment] 2021-04-27 20:32
The issue come from the parameter "DBusActivatable=true" in the nautilus desktop file "/usr/share/applications/org.gnome.Nautilus.desktop". If you remove it, the issue disappear.
Maybe related to https://github.com/QubesOS/qubes-issues/issues/1031 , how dbus interact with qrexec

**Comment by neowutran** [comment] 2021-04-28 23:02
To simulate the issue you can run ``/usr/bin/qubes-desktop-run /usr/share/applications/org.gnome.Nautilus.desktop``, the process stop when the "evince" / "gedit" is killed. 
It come from qubesagent/xdg.py:

https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubesagent/xdg.py#L96
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubesagent/xdg.py#L71

(never done any dbus related thing before, so from the few tests I did: )

This code will quit the loop if it receive a signal saying that a dbus process have been terminated (any process)

```python
def dbus_name_change(loop, name, old_owner, new_owner):
    if not new_owner:
        loop.quit()
```

I did the following modification:

```python
def dbus_name_change(loop, service_id, name, old_owner, new_owner):
    if name != service_id:
        return
    if not new_owner:
        loop.quit()
```

```python
match = bus.add_signal_receiver(
                        functools.partial(dbus_name_change, loop, service_id),
                        'NameOwnerChanged',
                        None,
                        None,
                        None)
```

The intend is to quit the loop only if the process terminated is our original dbus process (service_id).

Didn't tested it extensively, but it seem to work

**Comment by marmarek** [comment] 2021-04-28 23:14
This looks like the right fix! Can you submit it as a pull request?

**Comment by tlaurion** [comment] 2021-06-29 18:40
@marmarek this was not packaged and uploaded yet?

**Comment by tlaurion** [comment] 2021-09-02 16:01
@marmarek @andrewdavidwong 
This issue is not completely fixed, see https://github.com/QubesOS/qubes-core-agent-linux/pull/299#issuecomment-911834950

**Comment by marmarek** [comment] 2021-09-02 18:44
@tlaurion are you sure it isn't about #2581 ? Your description sounds like a gnome-terminal issue, not the "shutting down after closing another window"

**Comment by tlaurion** [comment] 2021-09-02 20:11
@marmarek @andrewdavidwong my bad. Xterm works. Didn't read #2581 sorry!

**Closed** 2021-09-03 05:33 UTC
Labels: T: bug, C: core, P: major, needs diagnosis
