### ISSUE TITLE
domU storage encryption

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4409] opened 2018-10-19 21:31 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

dom0 storage management

---

### Steps to reproduce the behavior:

Discover that the domU storage devices are encrypted by FDE (only).

### Expected behavior:

domU storage devices are encrypted with a unique key.  This key is stored in NVRAM (encrypted with a key on the hard disk and/or TPM), or other place from which it can be securely deleted, and is wiped when the domain is deleted.

### Actual behavior:

No such encryption.

### General notes:

This is related to #4408, but this issue covers persistent storage, while #4408 covers swap.

---

### Related issues:

#4408

**Comment by unman** [comment] 2018-10-20 01:31
Is this not a duplicate of #1293?

**Comment by andrewdavidwong** [comment] 2018-10-20 03:09
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-10-20 03:09 UTC
