### ISSUE TITLE
Appmenus from HVM- and other-than-fedora-based AppVMs populate System Tools menu

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2277] opened 2016-08-29 07:25 UTC

**Comment by marmarek** [comment] 2016-08-30 15:35
Does it apply to VMs restored from backup? It should be fixed after you
update template of those VMs.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment] 2016-09-07 23:22
> Does it apply to VMs restored from backup?

yes, and ones that were not (like `sys-firewall`). seems like a quite arbitrary collection of apps with no clear pattern.

I can also confirm in my case that Appmenus for fedora 23-based AppVMs also populate the menu.

**Comment by jpouellet** [comment] 2016-12-10 14:00
The root cause was fixed by https://github.com/QubesOS/qubes-core-admin-linux/commit/7080c0371dc7bf8ea4de43b28adb9808240b98c9

To fix existing VMs, perform:
```
Dom0$ for x in /var/lib/qubes/appvms/*/apps.templates/qubes-start.desktop; do \
>   cp -v /usr/share/qubes-appmenus/qubes-start.desktop "$x"; \
> done
```
and `qvm-sync-appmenus` (or add/remove a shortcut from the qubes-manager gui) for the affected VM(s).

I think this issue can be closed now.

**Closed** 2016-12-11 04:35 UTC
Labels: bug, C: desktop-linux, C: desktop-linux-xfce4, P: minor, UX
