### ISSUE TITLE
removal of DVM Template too cumbersome

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4081] opened 2018-07-15 11:18 UTC
### Qubes OS version:
R4

### Affected component(s): 
dom0 Qubes VM Manager (QVMM)

### Steps to reproduce the behavior:
    qvm-remove whonix-ws-14-dvm

### Expected behavior:
whonix-ws-14-dvm removed.

### Actual behavior:

Not removed. journalctl reports for quesdb `Cannot remove whonix-ws-14-dvm, used by whonix-ws-14-dvm.default_dispvm`. And it goes on and on and on because it is the default DispVM for any VM on the system, including dom0.

Note: although the example is using Whonix, this is not a Whonix related issue.

**Comment by marmarek** [comment] 2018-07-15 11:51
This is a duplicate of #3993, which already have proposed solution.

**Closed by marmarek** 2018-07-15 11:51 UTC
