### ISSUE TITLE
Unified notifications through libnotify

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#1001] opened 2015-05-21 07:59 UTC
As this was discussed in the Groups, I'd like to create an issue for such nice-to-have feature. There is already a PoC.

Related discussion: https://groups.google.com/forum/#!searchin/qubes-devel/libnotify/qubes-devel/1Lzv9SQCzFc/2Jk5bPzF9tcJ

**Comment by marmarek** [comment] 2015-05-21 09:46
This looks like a duplicate of #889, so linked there.

**Closed by marmarek** 2015-05-21 09:46 UTC
