### ISSUE TITLE
Cannot use 'qvm-run -u root' after upgrade to debian 11

### ISSUE THREAD

**Issue by p1llule** [QubesOS/qubes-issues#7105] opened 2021-12-08 18:03 UTC
### Qubes OS release
4.0

### Brief summary
Upgrading my debian VMs in place, I see that I cannot anymore use `qvm-run -u root $VM xterm`

### Steps to reproduce
[Follow the instructions of qubes-os.org ](https://www.qubes-os.org/news/2021/12/07/debian-11-templates-available/) to make an upgrade in place.

`qvm-run -u root $VM xterm` will output $VM: command failed with code: 1
Using the --pass-io option does not give more clue.

This is not specific to xterm.
This is specific to the -u root option.

**Comment by p1llule** [comment] 2021-12-08 19:48
This issue disappear when rebooting the template.

**Comment by andrewdavidwong** [comment] 2021-12-08 21:28
> This issue disappear when rebooting the template.

Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-12-08 21:28 UTC
Labels: T: bug, P: default
