### ISSUE TITLE
CPU temperature rises after suspend/resume

### ISSUE THREAD

**Issue by tfm1** [QubesOS/qubes-issues#4455] opened 2018-10-30 12:52 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

Suspend and resume the system.

### Expected behavior:

`sensors` shows roughly the same idle temperature as before.

### Actual behavior:

`sensors` shows roughly 10C higher temperature. Fans might run more often/faster.

### General notes:

Thinkpad X1 Carbon 6th gen. See [https://groups.google.com/forum/#!topic/qubes-users/5VzS5E-JaFg](https://groups.google.com/forum/#!topic/qubes-users/5VzS5E-JaFg)

The issue disappears after reverting to `smt=on` boot option.

---

**Comment by andrewdavidwong** [comment] 2018-10-31 05:30
Duplicate of #4252

**Comment by andrewdavidwong** [comment] 2018-10-31 05:30
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #4252 (see the comments on this issue further down). If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2018-10-31 05:54 UTC
Labels: duplicate
