### ISSUE TITLE
4.1: Qube Manager does not save autostart preference

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#5882] opened 2020-06-06 17:47 UTC
**Qubes OS version**

4.1

**Affected component(s) or functionality**

Qube Manager

**Brief summary**

I've installed 4.1 onto a new system and `sys-whonix` starts on every boot. I untick the "Start qube automatically on boot" option in it's Qube Manager settings and press "Apply". A few moments later the box is reticked by itself.

**Comment by andrewdavidwong** [comment] 2020-06-08 02:12
Related (possible duplicate of): #3606, #3554

**Comment by jpds** [comment] 2020-06-22 19:18
I do not see this after using the `4.1-20200614` ISO.

**Comment by andrewdavidwong** [comment] 2020-06-23 02:20
> I do not see this after using the `4.1-20200614` ISO.

Closing as resolved, but please let us know if the problem returns so that we can reopen this. Thank you.

**Closed by andrewdavidwong** 2020-06-23 02:20 UTC
Labels: C: manager/widget, P: default, T: bug, needs-diagnosis
