### ISSUE TITLE
Problems with update proxy after in-place upgrade to 4.2

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#8460] opened 2023-08-28 19:15 UTC
### Qubes OS release
4.1 -> 4.2

### Brief summary
After first 3 stages of in-place dist upgrade update proxy stop working.

### Steps to reproduce
1.) On 4.1 create dvm sys-firewall based on minimal fedora-38. Not check any services in option window.
2.) Updates on 4.1 should work ok.
3.)Perform in-place upgrade to 4.2
4.) After 3 stage and reboot upgrade proxy not working

### Expected behavior
Update proxy should work as on 4.1

### Actual behavior
Update proxy not working. It start working again after:
1.)  adding user policy:
`qubes.UpdatesProxy	*   @type:TemplateVM        @default    allow target=sys-firewall`
2.) adding qubes-updates-proxy service and checking it in sys-firewall options window

But during templates upgrade I still have such warnings for debian-11 based templates:

```
qubes-sync-time.service is a disabled or a static unit not running, not starting it.
qubes-update-check.service is a disabled or a static unit not running, not starting it.
Job for qubes-mount-dirs.service failed because the control process exited with error code.
See "systemctl status qubes-mount-dirs.service" and "journalctl -xe" for details.
```

**Comment by andrewdavidwong** [comment] 2023-08-28 19:18
Sounds like a potential 4.2 blocker (if not unique to one user). Provisionally increasing priority. Devs, feel free to knock it back down if not really a blocker.

**Comment by marmarek** [comment] 2023-08-28 19:26
Duplicate of #8458 ?

**Comment by Szewcson** [comment] 2023-08-28 19:41
I 

> Duplicate of #8458 ?

I think this is another issue since when I test if I can remove qubes-updates-proxy service it stop working again. For whonix-gw I don't have this service enabled, and on 4.1 I also don't have it for sys-firewall. Also I'm courious about those messages from Debian-11. Should I add some config to sys-firewall to suppress those? Can it cause more problems in the future?

**Comment by marmarek** [comment] 2023-08-28 19:54
> 4.1 I also don't have it for sys-firewall

Both on 4.1 and 4.2 the default updates proxy is sys-net.

**Comment by Szewcson** [comment] 2023-08-28 19:58
Ok, I will check it on sys-net but on 4.1 I also don't have that service checked for sys-net.

**Comment by marmarek** [comment] 2023-08-28 19:59
It's implicitly enabled by default in any netvm (documented in `man qvm-service`)

**Comment by Szewcson** [comment] 2023-08-28 20:27
Ok, now I delete those update proxy policy and it working on sys-net. So maybe the root cause was that I first try it with qubes.skip_autostart (since my my keyboard was blocked) and sys-net and sys-firewall started manually. So my last question is: are those warnings during template upgrade can produce more issues in the future?

**Closed** 2023-08-29 02:09 UTC
Labels: T: bug, P: blocker, needs diagnosis, C: updates, affects-4.2
