### ISSUE TITLE
Fedora-32 can not update with qubesctl

### ISSUE THREAD

**Issue by p1gp1g** [QubesOS/qubes-issues#6192] opened 2020-11-09 09:58 UTC
**Qubes OS version**
`R4.0`

**Affected component(s) or functionality**
Updater, qubesctl, fedora-32 template

**Brief summary**
Updating fedora-32 template with qubesctl (or with the updater icon on system tray) fails.

**How Reproducible**
The bug always occurs when I want to update via the updater icon (or qubesctl). I don't know how reproducible it is from a fresh install.

**To Reproduce**

```
sudo qubesctl --skip-dom0 --targets=fedora-32-test --show-output state.sls update.qubes-vm
```

**Expected behavior**
It should update the template without error.

**Actual behavior**
It aborts with as assertion error:
```
2020-11-09 09:26:42,521 calling 'state.sls update.qubes-vm'...
2020-11-09 09:26:59,582 output: fedora-32-test:
2020-11-09 09:26:59,584 output:     ----------
2020-11-09 09:26:59,584 output:     _error:
2020-11-09 09:26:59,584 output:         Failed to return clean data
2020-11-09 09:26:59,584 output:     retcode:
2020-11-09 09:26:59,584 output:         1
2020-11-09 09:26:59,584 output:     stderr:
2020-11-09 09:26:59,584 output:         Traceback (most recent call last):
2020-11-09 09:26:59,584 output:           File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
2020-11-09 09:26:59,584 output:             sys.exit(main())
2020-11-09 09:26:59,584 output:           File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
2020-11-09 09:26:59,584 output:             return ssh(args)
2020-11-09 09:26:59,584 output:           File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
2020-11-09 09:26:59,585 output:             assert args[1] == '/bin/sh'
2020-11-09 09:26:59,585 output:         AssertionError
2020-11-09 09:26:59,585 output:     stdout:
2020-11-09 09:26:59,585 exit code: 20
```

**Additional context**
It happened just after the upgrade from salt-ssh and salt from 3001.1-1 to 3001.3-1.

**Solutions you've tried**
I tried to downgrade salt and salt-ssh to 3001.1-1 but there are not in the repo any more.
Downgrading to 3000.1-1 fails with a [known issue](https://github.com/QubesOS/qubes-issues/issues/5919)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
-

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
May be related : 
* https://github.com/QubesOS/qubes-issues/issues/6156

**Comment by marmarek** [comment] 2020-11-09 10:01
Duplicate of #6188

**Comment by marmarek** [comment] 2020-11-09 10:02
See this comment how to install the fix: https://github.com/QubesOS/qubes-issues/issues/6188#issuecomment-723523628

**Closed by marmarek** 2020-11-09 10:01 UTC
Labels: P: default, T: bug
