### ISSUE TITLE
UI/UX issue: do not (only) use service names for firewall rules

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#5211] opened 2019-08-01 13:18 UTC
**The problem you're addressing (if any)**

Using Qubes 4.0 with all current updates.

For some VMs, I have a "block most outgoing connections" policy and only allow specific targets / specific services (some common ones, like ssh and https and also some less common ones).

The problem here is that the `Qubes Settings -> Firewall rules` UI only displays the service name (if it can find any), but that service name is not necessarily well known nor what I am using it for.

E.g. it **only** displays very unhelpful stuff like:
- rockwell-csp2
- efi-mg
- rcip-itu
- di-drm
- rhwois

I could not even find them in my `/etc/services`.

I don't use any of these named services, but obviously I did enter these ports by number for some other service I needed.

The problem is that I can't see the port numbers any more, so I basically do not know what I have nor what I might be missing if something does not work and needs more ports to be allowed.

The problem is in the overview list and also if I choose to edit one of the rules, it still does not tell me the port number, but only the (not well known and not applicable) service name.

**Describe the solution you'd like**

Reverse this!
- Show port numbers as the "real information" in the list and in the edit dialog.
- If you like, you can add the service name in parentheses. It might be helpful sometimes.

  - `22 (ssh)` is helpful.
  - `4321 (rwhois)` is at least usable although the service name is not helpful if you don't use rwhois.

**Where is the value to a user, and who might that user be?**

It's not usable as it is and everybody using firewall rules for not only the most well-known services can also use it then.

**Comment by unman** [comment] 2019-08-01 14:15
It's the service name that is the unique key in the ports database. It should be straightforward to find the relevant port by consulting /etc/services in dom0:

rockwell-csp2   2223
efi-mg               2224
rcip-itu              2225
di-drm               2226
rhwois               4321 

qvm-firewall will show you the port numbers, rather than the service names.

I like your suggestion though - the only scope for confusion would be running a service on a non-standard port - eg ssh on 443, when the description would be 443(https)

**Comment by marmarek** [comment] 2019-08-01 14:32
>     * If you like, you can add the service name in parentheses. It might be helpful sometimes.

I like this idea.

**Comment by ThomasWaldmann** [comment] 2019-08-01 15:02
Manually consulting /etc/services for each port where I entered a number and do not get shown the number any more is not practicable if you have a lot of rules.

**Comment by dmoerner** [comment] 2019-08-01 17:19
This is more or less a dupe of https://github.com/QubesOS/qubes-issues/issues/4766. I think that listing both the port number and the service name is clearer; e.g., the port 587 is better-known for smtp than the service name "submission".

**Comment by ThomasWaldmann** [comment] 2019-08-01 19:55
It does not sound like a duplicate.

**Closed** 2019-08-02 18:03 UTC
Labels: C: manager/widget, P: default, T: enhancement, ux
