### ISSUE TITLE
[UX] have AdminVM manage inter-vm file copying

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1443] opened 2015-11-20 16:57 UTC
this came out of a discussion with @bnvk:

when copying a file/folder, Instead of source qube1 popping up a window where one types in the destination qube2 name, which is then confirmed via AdminVM, why not have a dialog in AdminVM pop up that allows one to have a drop-down of available VMs, and even available programs within those VMs? 

Current workflow:
1. right-click on flie, select Copy/Send/Move To VM
2. source qube1 dialog box: user types in destination qubes2 name
3. AdminVM dialog box: confirm file transfer

Proposed workflow:
1.  right-click on flie, select Copy/Send/Move To VM
2. AdminVM dialog box: select destination VM (confirmation of file transfer is implicit)

This would also remove the spamming of source qube1 dialog box if one has selected multiple files to copy.

**Comment by marmarek** [comment] 2015-11-20 17:30
This is duplicate of #910 
And yes, generally IMO good idea.

**Closed by marmarek** 2015-11-20 17:30 UTC
Labels: duplicate
