### ISSUE TITLE
Clarify "compacting" TemplateVM in Qubes 4+

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#5260] opened 2019-08-20 14:11 UTC
The `qvm-trim-template` command does not exists in Qubes 4+ anymore. However, the [Debian upgrade guide](https://www.qubes-os.org/doc/template/debian/upgrade/) mentions:

> 6. Compact the template.

But there are no instructions provided on how to actually compact the template.

My question is: How does one `compact` a template?

**Comment by andrewdavidwong** [comment] 2019-08-21 02:18
That statement is probably just out-of-date and superseded by https://www.qubes-os.org/doc/templates/#important-notes

**Comment by Jeeppler** [comment] 2019-08-21 07:00
@andrewdavidwong thanks.

**Comment by andrewdavidwong** [comment] 2019-08-22 01:37
Docs should still be improved.

**Comment by Jeeppler** [comment] 2019-08-31 08:19
@andrewdavidwong how about creating a new issue, with an actionable title. I assume there are a couple of references which mention `qvm-trim-template`. I do not know exactly when  `qvm-trim-template` was removed. If we know that we could prefix the references to `qvm-trim-template` with Qubes OS version X. And also mention it in the Debian upgrade guide.

**Comment by andrewdavidwong** [comment] 2019-09-01 00:17
> how about creating a new issue, with an actionable title.

A new issue about this same task would be a duplicate of this issue. Why not just use this one? The new title is actionable, but I'm open to further improvements.

> If we know that we could prefix the references to `qvm-trim-template` with Qubes OS version X.

Those references should be removed, since there is no longer a supported version of Qubes OS to which they apply.

**Closed** 2019-09-02 03:36 UTC
Labels: C: doc, P: default, T: task
