### ISSUE TITLE
Its just a name. 

### ISSUE THREAD

**Issue by miguelspaw** [QubesOS/qubes-issues#1481] opened 2015-12-03 20:20 UTC
How can it be any easier. You'll have similar issues going from say arch to ubuntu to suse.

**Comment by miguelspaw** [comment] 2015-12-03 20:22
Leave as is so its distinctive. Don't try to blend in. Just take a minute to think of why you use cubes...cause its different etc.

**Comment by axon-qubes** [comment] 2015-12-04 00:40
Uh... what is this in reference to?

**Comment by miguelspaw** [comment] 2015-12-04 04:11
Its about the discussion of changing dom to something more common.

**Comment by mfc** [comment] 2015-12-07 20:36
this is duplicate of: https://github.com/QubesOS/qubes-issues/issues/1015, please contribute there if you are interested.

dom0 is actually the generic Xen term, it is not a Qubes-specific term. So changing it from dom0 to something else is about making more specific, relevant, and understandable to Qubes users.

**Closed by mfc** 2015-12-07 20:36 UTC
Labels: duplicate

**Comment by miguelspaw** [comment] 2015-12-10 01:42
Sorry
