### ISSUE TITLE
Qubes Updater considers in-place upgraded qubes to be "no longer supported"

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#8725] opened 2023-11-23 09:42 UTC
### Qubes OS release
4.2-rc4

### Brief summary
The new Qubes Updater introduced [a new way](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qui/utils.py#L83-L95) to detect if a template or standalone qube is no longer supported.
It works, but shows false positives for users who use the in-place upgrade method for their qubes.
The "template-name" option in qvm-features retains its old value and Qubes Updater uses it to check if the system is EOL.

### Steps to reproduce
Not really reproducible by itself, since it only happens to users who upgrade their templates/standalone qubes in-place.
Can be artificially reproduced by changing the `template-name` value to an old template version:
- `qvm-features fedora-38-xxx template-name fedora-35`

### Expected behavior
No "no longer supported" message should appear in Qubes Updater qui if the qube runs a supported release.

### Actual behavior
Say that some of my qubes are no longer supported (reported as "obsolete" in Qubes Updater itself) when they are fully upgraded to fedora-38.
Running qvm-features on one of the affected template reports the following:
```
template-name                               fedora-35
template-epoch                              0
template-version                            4.0.6
template-release                            202111131804
template-reponame                           qubes-templates-itl-testing
template-buildtime                          2021-11-13 19:14:50
template-installtime                        2021-12-07 18:11:25
template-license                            GPL
template-url                                http://www.qubes-os.org
template-summary                            Qubes template for fedora-35
template-description                        Qubes template for fedora-35
```

**Comment by ben-grande** [comment] 2023-11-23 11:47
Note that these features are set on package installation, not when modifying the qube from inside.

If this is a bug, it is in the documentation, maybe it should tell you to update the `template-name`, `template-summary` and `template-description` feature? I don't know if the other features should be changed.

But then it would also need to recommend you to set a new feature `template-original-name` or something like it, so you can know from which version you started doing in-place upgrades. This way the Updater could work with in-place upgrades.

**Comment by avaaum** [comment] 2023-12-10 19:26
does not work for me. the issue still persists.

**Comment by runephilosof-abtion** [comment] 2024-01-09 07:45
> does not work for me. the issue still persists.

I had to reboot after changing the template names to have the updater notice it.

**Comment by runephilosof-abtion** [comment] 2024-01-09 07:48
According to https://forum.qubes-os.org/t/fedora-template-no-longer-supported-4-2-0-rc5/22506/4, it should be enough to restart the widget. But I don't know how to do that.

**Comment by sjvudp** [comment] 2024-01-19 22:24
As I'm affected, too, I can tell:
`qvm-features fedora-38` reports (among many other lines):
```
template-name                               fedora-36
template-epoch                              0
template-version                            4.0.6
template-release                            202205270243
template-reponame                           @commandline
template-buildtime                          2022-05-27 03:11:26
template-installtime                        2022-09-02 22:50:42
template-license                            GPL
template-url                                http://www.qubes-os.org
template-summary                            Qubes template for fedora-36
template-description                        Qubes template for fedora-36
updates-available                           
last-updates-check                          2024-01-19 22:21:28
```
So my guess is that one step in the template upgrade guide is missing ;-)

**Comment by Minimalist73** [comment] 2024-02-19 10:43
@unman A proper fix for this issue is coming (see marmarek's commits) and will make this part of the documentation obsolete. I don't think this merge should close this issue until the changes in https://github.com/QubesOS/qubes-core-agent-linux/pull/481 and https://github.com/QubesOS/qubes-core-admin/pull/578 are merged.

**Comment by loneicewolf** [comment] 2024-03-08 19:45
I had a similar issue on my Qubes!

Just Updated it and stuff, And.. Very *bizzare* 'error' (or, "warning", as it wasn't really any error) message, I have to admit.

if I remember correctly, it was just after I was done installing my new qubes (latest version) and ALWAYS a  RED text would appear, on the qubes update GUI (which is advised in the docs)'  `"OBSOLETE" cubes are used, use the template manager to install the new template (something)'` <- really, really weird. It's from a clean, from scratch, (completely new SSD as well) the latest Qubes Version, and I searched on this, and **surprisingly** there's only.. Like, 2 or maybe at most 3 (recent/actually relevant) results on google 

*Being extremely paranoid as I am, this really really making me confused, like, are they obsolete or updated?*


Just wanted to point this out; if anyone else has this as well;

**Comment by Minimalist73** [comment] 2024-03-08 20:03
> I _have_ a similar issue on my Qubes!
> 
> Just Updated it and stuff, And.. Very _bizzare_ 'error' (or, "warning", as it wasn't really any error) message, I have to admit.
> 
> if I remember correctly, it was just after I was done installing my new qubes (latest version) and ALWAYS a RED text would appear, on the qubes update GUI (which is advised in the docs)' `"OBSOLETE" cubes are used, use the template manager to install the new template (something)'` <- really, really weird. It's from a clean, from scratch, (completely new SSD as well) the latest Qubes Version, and I searched on this, and **surprisingly** there's only.. Like, 2 or maybe at most 3 (recent/actually relevant) results on google
> 
> _Being extremely paranoid as I am, this really really making me confused, like, are they obsolete or updated?_
> 
> Just wanted to point this out; if anyone else has this as well;

If you are talking about the bottom text in the updater GUI, it's an informative text that explain what "OBSOLETE" means when it appears next to a qube in the list. If you don't see any qubes having that, you don't have to worry about it.

**Comment by loneicewolf** [comment] 2024-03-08 20:06
> > I _have_ a similar issue on my Qubes!
> > Just Updated it and stuff, And.. Very _bizzare_ 'error' (or, "warning", as it wasn't really any error) message, I have to admit.
> > if I remember correctly, it was just after I was done installing my new qubes (latest version) and ALWAYS a RED text would appear, on the qubes update GUI (which is advised in the docs)' `"OBSOLETE" cubes are used, use the template manager to install the new template (something)'` <- really, really weird. It's from a clean, from scratch, (completely new SSD as well) the latest Qubes Version, and I searched on this, and **surprisingly** there's only.. Like, 2 or maybe at most 3 (recent/actually relevant) results on google
> > _Being extremely paranoid as I am, this really really making me confused, like, are they obsolete or updated?_
> > Just wanted to point this out; if anyone else has this as well;
> 
> If you are talking about the bottom text in the updater GUI, it's an informative text that explain what "OBSOLETE" means when it appears next to a qube in the list. If you don't see any qubes having that, you don't have to worry about it.

Hello! thanks for the quick reply 

Okay, if that's the case, the text maybe is not clear enough because I got, 100%, the indication (or, "understanding") that, it was some issue with my "qubes" or "templates" <- Now I do remember the YELLOW marked text **which DID appear on some of the qubes, it disappeared when I updated them though**,  and - `No` I have not seen any 'OBSOLETE' text on a qube itself, soo..

...I guess I misunderstood `<_<` 

***Thanks **so much** for this reply @Minimalist73!***

**Comment by loneicewolf** [comment] 2024-03-08 20:09
Also - about confusing text - I don't know if this confusion is a 'only me' problem,  but if other people also are confused - 
__do reply to this convo whoever reads this__, so it becomes more clear that maybe the text needs to be changed/improved;

Now ill not type more; Thanks again! 
And Have a great Weekend 👋🏼 💯 
//Will

**Comment by loneicewolf** [comment] 2024-03-09 13:24
Oh of course; editing the reply - It was a bit vague and a bit wrongly typed; thanks!

**Comment by kennethrrosen** [comment] 2024-06-01 10:43
This issue seems to have resurfaced in R4.2.1 using the testing repository, kernel 6.6.31-1. Updating qvm-features and rebooting does not fix.

**Comment by marmarek** [comment] 2024-06-01 23:58
Which template specifically? What qvm-features shows and what is actually running inside? Do you see os-* qvm-features present?

**Comment by kennethrrosen** [comment] 2024-06-02 09:05
@marmarek it was indeed the os-eol date in the template and standalone.

**Comment by kennethrrosen** [comment] 2024-06-02 12:10
I've updated the above scripts to correct this

**Comment by marmarek** [comment] 2024-06-02 18:26
Setting os-eol to +6 months manually is wrong, please do **not** do it. It should be set to the actual EOL date, and it should happen automatically on update. Can you say what value you've got, for which template (before and after upgrade)?

**Comment by kennethrrosen** [comment] 2024-06-02 18:45
The os-eol 2024-05-21 (F38). What's a better way to populate the actual EOL date?

**Comment by marmarek** [comment] 2024-06-02 18:54
> The os-eol 2024-05-21 (F38). 

This looks correct. Yes, Fedora 38 is EOL already, see the end of https://fedorapeople.org/groups/schedule/f-38/f-38-key-tasks.html

**Comment by kennethrrosen** [comment] 2024-06-02 20:24
But the upgrade to F39 did not update the EOL date.

**Comment by marmarek** [comment] 2024-06-02 21:21
Did you get any errors during upgrade? Retrieving EOL date is during the "Notifying dom0 about installed applications" phase.

**Comment by kennethrrosen** [comment] 2024-06-03 08:29
None that I saw

**Comment by marmarek** [comment] 2024-06-03 10:16
If for some reason it didn't happen automatically, you can also force refreshing it with `qvm-run -u root --service fedora-39 qubes.PostInstall`. But I'd like to learn why it didn't happen automatically...

**Comment by CumpsD** [comment] 2024-06-20 21:44
My Fedora 38 templates become Obsolete and I just updated them all in-place to Fedora 40, but the Obsolete remains. What's the current fix for this?

**Comment by marmarek** [comment] 2024-06-20 23:28
> But I'd like to learn why it didn't happen automatically...

I have an (unconfirmed) idea: it's due to python upgrade. F38 has Python 3.11, but F39 has Python 3.12, so the DNF plugins migrate from `/usr/lib/python3.11/site-packages/dnf-plugins` to `/usr/lib/python3.12/site-packages/dnf-plugins` during update, but the running DNF still expects them in the former location. One issue with this hypothesis is that DNF log claims to load plugins at the start, so at the point the old location is removed, they should be loaded already. But in any case, I can confirm that the qubes-hooks does not report upgrade to dom0 after performing `dnf distro-sync` from F38 to F40 (and I guess to F39 too). But it does report it when doing `dnf distro-sync` within the same release.


> What's the current fix for this? Apparently I need to restart the update widget, how to do that?

If you hit the same issue, install updates in the template once, it should refresh things. Or execute `qvm-run` command listed in my earlier comment.

As for the list of obsolete templates in the widget, indeed it looks to not refresh itself. You can restart the widget with `systemctl --user qubes-widget@qui-updates` command in dom0.

@marmarta ^^

**Comment by alimirjamali** [comment] 2024-06-21 00:45
I tested the above patch for Tray Update Notifier by changing `os-eol` feature of archlinux templates to different times in future and past.

**Closed** 2024-06-23 23:23 UTC
Labels: T: bug, C: manager/widget, C: doc, P: critical, diagnosed, pr submitted, C: updates, r4.2-vm-fc37-stable, r4.2-vm-bookworm-stable, r4.2-host-stable, r4.2-vm-fc38-stable, affects-4.2, r4.2-vm-fc39-stable, r4.2-vm-trixie-stable, r4.2-vm-fc40-stable, r4.3-vm-bookworm-cur-test, r4.3-vm-trixie-cur-test, r4.3-vm-fc39-cur-test, r4.3-vm-fc40-cur-test

**Comment by CumpsD** [comment] 2025-05-28 14:42
This is how it looks in Template Manager, the version seems different, does it base it on that?

![Image](https://github.com/user-attachments/assets/0e5f4972-19dd-42f4-8b01-858f380f9f1d)
![Image](https://github.com/user-attachments/assets/19c68cf0-7a34-49d3-b559-64120ae56d49)

**Comment by CumpsD** [comment] 2025-05-28 14:54
> do you see any errors in the update log (near the end), especially about qvm-features-request call? You can check that in the updater just after the update, but also later in /var/log/qubes/ - `qubes-(template name).log` files.

Do you mean the `update-{template name}.log` files? 

Nothing particular in there:
![Image](https://github.com/user-attachments/assets/d74c5607-65d5-4c3d-9556-a5916feb6bc1)

**Comment by marmarek** [comment] 2025-05-28 15:02
Yes, this log. Do you see any older that actually had some updates installed?

**Comment by CumpsD** [comment] 2025-05-28 15:07
> Yes, this log. Do you see any older that actually had some updates installed?

Nope, after doing the in place upgrade nothing had any updates. Even though it had the update icon at first, when I did upgrade there was nothing.

**Comment by marmarek** [comment] 2025-05-28 15:12
There is post-update hook that should update the metadata. Normally it should happen after an update, but if none are available right now (which is a bit suspicious, TBH...) you can trigger that manually by calling `qvm-run -p -u root --service fedora-41 qubes.PostInstall`
