### ISSUE TITLE
Debian-based DispVM template has invalid App Shortcuts by default

### ISSUE THREAD

**Issue by meithecatte** [QubesOS/qubes-issues#8149] opened 2023-04-23 04:43 UTC
### Qubes OS release

R4.1.2

### Brief summary

`debian-11-dvm`'s "Applications" tab in the settings shows "Application missing in template! (firefox.desktop)" and likewise for xterm. This makes the dom0 applications menu hide the entire category of "start a DVM".

Note: This is simple enough that I double-checked the issue tracker, but couldn't find a pre-existing issue about this.

I'll look into this once I get my setup back up after The Incident ;3

### Steps to reproduce

1. During the Qubes installation, pick Debian as the base for all templates.
2. (Install all updates and reboot.)
3. Attempt to start a dispVM through the app menu and/or inspect the Qube settings for `debian-11-dvm`.

### Expected behavior

No entry in menu, invalid application menu setup.

### Actual behavior

Equivalent to Fedora-based dispVM.

**Comment by andrewdavidwong** [comment] 2023-04-23 04:54
Duplicate of #6805?

**Comment by unman** [comment] 2023-04-23 06:14
Yes

**Comment by andrewdavidwong** [comment] 2023-04-23 13:22
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-04-23 13:22 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, needs diagnosis
