### ISSUE TITLE
Port over documentation from third-party sites

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1202] opened 2015-09-22 19:14 UTC
Focusing on the "User Documentation" one of the more jarring things a new user encounters is being redirected to other sites to learn about using Qubes- thus, porting over (and in some cases updating the content dating back to 2011) from the ITL blog, Google Group, and Whonix seem in high order... 

The clearest / most important pieces of documentation for porting over are:

- [x] [Creating Whonix VMs in Qubes](https://www.whonix.org/wiki/Qubes)
- [x] [Creating NetBSD VM](https://groups.google.com/forum/#!msg/qubes-devel/nfIrigcZ0Ec/hTmBCpDIFUAJ)
- [x] [Creating Custom NetVMs and ProxyVMs](http://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html)
- [x] [How to make proxy for individual tcp connection from networkless VM](https://groups.google.com/group/qubes-devel/msg/4ca950ab6d7cd11a)
- [x] [HTTP filtering proxy in Qubes firewall VM](https://groups.google.com/forum/#!topic/qubes-devel/UlK8P27UtD4)
- [x] [Booting with GRUB2 and GPT](https://groups.google.com/forum/#!topic/qubes-devel/5KwJPKvTfSs)
- [x] [Customizing the GUI experience with KDE](https://groups.google.com/forum/#!topic/qubes-users/KhfzF19NG1s/discussion)

Also for inclusion are these posts, which might make sense to move away from "Documentation" and more towards "Intro / Tour" part of the site...

- [x] [Further reading: How is Qubes different from…?](http://blog.invisiblethings.org/2012/09/12/how-is-qubes-os-different-from.html)
- [x] [Further reading: Why Qubes is more than a collection of VMs](http://invisiblethingslab.com/resources/2014/Software_compartmentalization_vs_physical_separation.pdf)
- [x] **[Use Qubes without installing: Qubes Live USB (alpha)](https://groups.google.com/forum/#!msg/qubes-users/IQdCEpkooto/iyMh3LuzCAAJ)**

Least important, but still worthwhile to port over are the troubleshooting docs

- [x] **[Installing on system with new AMD GPU (missing firmware problem)](https://groups.google.com/group/qubes-devel/browse_thread/thread/e27a57b0eda62f76)**
- [x] [Solving problems with Macbook Air 2012](https://groups.google.com/group/qubes-devel/browse_thread/thread/b8b0d819d2a4fc39/d50a72449107ab21#8a9268c09d105e69)

**Comment by adrelanos** [comment] 2015-09-22 19:29
Whonix HVM? I guess that's a mistake. [HVM](https://www.qubes-os.org/doc/HvmCreate/)? Usually I run Whonix in usual PV.

About moving Whonix's documentation to qubes-os.org I answered here:
https://github.com/QubesOS/qubes-issues/issues/1201#issuecomment-142392885

**Comment by desci** [comment] 2015-10-14 00:31
I agree with the google groups stuff being adapted and moved to the website, I could help with that

**Comment by bnvk** [comment] 2016-02-18 01:38
@desci heya, are you still interested in helping with this? That would be super!

**Comment by mfc** [comment] 2016-03-16 09:25
@axon-qubes could you help with this given it's about documentation? this would help tremendously the effort to be able to provide comprehensive offline documentation to users https://github.com/QubesOS/qubes-issues/issues/1019

**Comment by axon-qubes** [comment] 2016-03-16 10:55
If there are specific documents that are known and confirmed to be: 1) accurate, 2) up-to-date, and 3) ought to be in the official documentation, then yes, I can help convert those into Markdown and add them to the repo. But it's not clear to me which of the ones in the list above are known to meet all three criteria (and I don't have the expertise to evaluate many of them).

Also, I'm not really that comfortable with taking content from anyone's personal website or blog and appropriating it for the documentation without express permission from the author. Even taking someone's words from a message to the MLs without permission seems a bit wrong.

**Comment by axon-qubes** [comment] 2016-03-16 10:57
I don't think it's a bad thing to have links to external websites, as long as we clearly mark them as external links. We could even have a designated section for them, like "Outside Qubes Guides" or something.

**Comment by mfc** [comment] 2016-03-17 22:24
I agree some of it does not seem to be relevant, up-to-date, etc. Or are really narrow. I've crossed out some of the ones I don't think are relevant.

I think this should initially focus on ITL / Qubes materials (like the blogpost re: Qubes Live USB, that should really be in documentation) and on troubleshooting materials.

I also think we should be bringing in the actual relevant content from Google Group threads that are referenced in the existing documentation. For example, this entry: https://www.qubes-os.org/doc/language-localization/

Besides the jarring aspect of having documentation all over the place, this is important for offline documentation so that it actually has the relevant content the user needs.

**Comment by axon-qubes** [comment] 2016-03-17 22:33
> I've crossed out some of the ones I don't think are relevant.

In the OP? I don't see any crossed-out entries...

> (like the blogpost re: Qubes Live USB, that should really be in documentation)

Added that one in December: https://www.qubes-os.org/doc/live-usb/

> For example, this entry: https://www.qubes-os.org/doc/language-localization/

Yeah, not sure who made that page. :\

**Comment by axon-qubes** [comment] 2016-03-17 22:35
I moved the two "further reading" entries as suggested.

**Comment by mfc** [comment] 2016-03-17 22:52
> Added that one in December: https://www.qubes-os.org/doc/live-usb/
> I moved the two "further reading" entries as suggested.

nice, check-marked them! 

for all the other suggested doc ports, they are really old. I think it would be better to make sure that these Google Group threads are being referenced to in the current Documentation. If not, they we should drop them. If so, then maybe get Marek or someone to confirm they are still relevant.

**Comment by axon-qubes** [comment] 2016-03-17 23:13
Language localization is also done.

**Comment by axon-qubes** [comment] 2016-03-17 23:17
> I think it would be better to make sure that these Google Group threads are being referenced to in the current Documentation. If not, we should drop them. If so, then maybe get Marek or someone to confirm they are still relevant.

Shouldn't it be the other way around? We should check to see if they're relevant (and accurate) first, then either add or remove them based on that. Old information shouldn't stay in the docs just because it's already there.

**Comment by mfc** [comment] 2016-03-17 23:36
yep sure, let's loop in @marmarek

**Comment by marmarek** [comment] 2016-03-18 12:22
I haven't reviewed all the linked documentation, but my guess about them:
- [ ] [Creating NetBSD VM](https://groups.google.com/forum/#!msg/qubes-devel/nfIrigcZ0Ec/hTmBCpDIFUAJ) - probably still applies
- [ ] [Creating Custom NetVMs and ProxyVMs](http://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html) - mostly outdated, but I think also mostly already integrated into our docs
- [ ] [How to make proxy for individual tcp connection from networkless VM](https://groups.google.com/group/qubes-devel/msg/4ca950ab6d7cd11a) - mostly up to date
- [ ] [HTTP filtering proxy in Qubes firewall VM](https://groups.google.com/forum/#!topic/qubes-devel/UlK8P27UtD4) - probably up to date

**Comment by axon-qubes** [comment] 2016-03-18 17:22
>  Creating NetBSD VM 

Done.

> Creating Custom NetVMs and ProxyVMs 

Skipping. (already integrated)

> How to make proxy for individual tcp connection from networkless VM 

I don't see an actual guide. Is it the one [linked](https://groups.google.com/forum/#!topic/qubes-devel/RFH1Vx99jsg/discussion) from that message?

> HTTP filtering proxy in Qubes firewall VM

Done.

**Comment by mfc** [comment] 2016-04-20 09:32
i think this is fine as is and can be closed? 

the "guide" for making proxy for individual tcp connection from networkless VM is a bash script from 2012, if it is not already linked in the docs I would lean towards not including it (since "mostly up-to-date" is not "up-to-date").

**Comment by bnvk** [comment] 2016-04-20 10:37
There is still quite a few links in the Docs that point elsewhere. I think these should either be removed (from the Docs) or imported to the repo, full stop.

- [ ] [Creating Custom NetVMs and ProxyVMs](http://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html) - should be removed from Docs since it's out of date
- [ ] **How to make proxy for individual tcp connection from networkless VM** should probably be [the linked one](https://groups.google.com/forum/#!topic/qubes-devel/RFH1Vx99jsg/discussion) @axon-qubes pointed out should be added

And these three things, 

- [ ] [Booting with GRUB2 and GPT](https://groups.google.com/group/qubes-devel/browse_thread/thread/e4ac093cabd37d2b/d5090c20d92c4128#d5090c20d92c4128)
- [ ] [Adding SSD storage cache](https://groups.google.com/d/msgid/qubes-users/a08359c9-9eb0-4d1a-ad92-a8a9bc676ea6%40googlegroups.com)
- [ ] [Installing on system with new AMD GPU (missing firmware problem)](https://groups.google.com/group/qubes-devel/browse_thread/thread/e27a57b0eda62f76)

If we want a page or section on the website of these helpful links that *does not* get packaged in offline docs, then move these there perhaps...

**Comment by mfc** [comment] 2016-04-20 17:20
re: "Installing on system with new AMD GPU (missing firmware problem)" from the thread itself the missing package is now included in Qubes. That can be trashed.

re: "Booting with GRUB2..." no solution is actually provided in the thread. That can be trashed.

re: "Adding SSD storage cache", that should be added to the Documentation. Good find.

re: "How to make proxy...", sound good, let's add it. 

I agree with you, for everything else we have evaluated they should be removed from Docs. We should lean towards not including topics if we have doubts, as we can always add topics from the google groups if the associated email threads are refreshed by users (acknowledging they are still relevant issues).

**Comment by andrewdavidwong** [comment] 2016-04-30 04:45
@mfc (#1938):
> as a note, I would argue this documentation should be ported to Qubes website so that it can be included in the offline docs (very, very useful information to have offline for users).
> 
> - [ ] port bridges documentation over to Qubes website
> - [ ] implement GUI

**Comment by desci** [comment] 2016-05-12 00:12
@bnvk yes. I'll send a pull request whenever I find time to do so.

**Comment by adrelanos** [comment] 2016-09-21 00:34
> @bnvk yes. I'll send a pull request whenever I find time to do so.

Any update?

**Comment by andrewdavidwong** [comment] 2016-10-15 22:23
@mfc: Can we close this issue?

**Comment by desci** [comment] 2016-10-16 16:01
From what I've seen, it has been all done already.

**Closed** 2016-10-18 20:52 UTC
Labels: C: doc, C: website, task
