### ISSUE TITLE
output by `/etc/profile.d` (or `/etc/X11/Xsession.d`?) scripts breaks Qubes UpdatesProxy

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8610] opened 2023-10-14 06:09 UTC
### Qubes OS release

R4.2

### Brief summary

Output generated by `/etc/profile.d` (or `/etc/X11/Xsession.d`?) breaks Qubes UpdatesProxy.

This can cause confusing, difficult to debug situations. (https://github.com/QubesOS/qubes-issues/issues/8606)

### Steps to reproduce

in UpdatesProxy VM:

(that VM used as UpdatesProxy by a Template)

1. add a script to  `/etc/profile.d` (or `/etc/X11/Xsession.d`?)  
2. make the script `echo` something to stdout and stderr
3. make it executable

in the Template:

5. run `sudo apt update` 

### Expected behavior

Qubes UpdatesProxy unaffected.

 `/etc/profile.d` (or `/etc/X11/Xsession.d`?) shouldn't interact with UpdatesProxy.

### Actual behavior

Qubes UpdatesProxy broken.

 `/etc/profile.d` (or `/etc/X11/Xsession.d`?) interacts with UpdatesProxy.

**Comment by marmarek** [comment] 2023-10-14 08:39
Shell startup scripts should never output anything, exactly because it breaks machine-readable output. This is well known fact, and includes for example things like scp, rsync. I don't think qubes.UpdatesProxy needs to be any special here.
Theoretically, it could be changed by having (all) qrexec services not load those scripts at all, but that will have major downside by not having environment variables (and similar things) set by those scripts.

**Comment by andrewdavidwong** [comment] 2023-10-14 17:36
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-10-14 17:36 UTC
Labels: T: bug, P: default

**Comment by adrelanos** [comment] 2024-01-31 16:11
Is this only an issue for `/etc/profile` or also for `/etc/X11/Xsession`?

Asking because of this:
https://forums.whonix.org/t/update-torbrowser-is-currently-broken/18279

**Comment by adrelanos** [comment] 2024-01-31 16:20
Created,

* https://github.com/QubesOS/qubes-issues/issues/8905

for it.
