### ISSUE TITLE
Cannot Permanently Set GUI to Seamless

### ISSUE THREAD

**Issue by DOEResearch** [QubesOS/qubes-issues#4166] opened 2018-07-30 16:11 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Windows 7
Windows tools 3.2 and 4.01

---

### Steps to reproduce the behavior:

echo SEAMLESS | qvm-run -p --service VMNAME qubes.SetGuiMode

### Expected behavior:

Should permanently set GUI to SEAMLESS

### Actual behavior:

Sets GUI only for the Session

### General notes:

Is there another way to the set the GUI to SEAMLESS? Qubes Preferences Manager does not have GUI preference.

---

**Comment by andrewdavidwong** [comment] 2018-07-31 00:43
Duplicate of https://github.com/QubesOS/qubes-issues/issues/3585#issuecomment-408802826

**Comment by andrewdavidwong** [comment] 2018-07-31 00:43
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-07-31 00:43 UTC

**Comment by tlaurion** [comment] 2018-08-14 17:46
Following https://github.com/QubesOS/qubes-issues/issues/3585#issuecomment-408842706 

I would have expected to put that registry value to 1, and still be able to launch Windows with Debug option on, which would disable seamless mode temporarily. 

@marmarek ?

**Comment by andrewdavidwong** [comment] 2018-08-14 19:38
> Following #3585 (comment)
> 
> I would have expected to put that registry value to 1, and still be able to launch Windows with Debug option on, which would disable seamless mode temporarily.

@tlaurion, please ask this on #3585.
