### ISSUE TITLE
Fedora manual (command) upgrade shows uprades while qubes manager dont

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7830] opened 2022-10-20 03:14 UTC
### Qubes OS release

4.1.1

### Brief summary

It seems like qubes manager upgrade button using a command within fedora which doesnt refresh the repos properly leading into false assumption that everything is upgraded (because terminal says so..).

But if someone use the manual command for upgrade within fedora template he will get the upgrades.

Issue i think: qubes doesnt use `--refresh` with the upgrade command, but according to upstream this is better to be used: (`---refresh` before or after `upgrade` gonna work in my test) 

`sudo dnf upgrade --refresh`

https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/#sect-performing-system-upgrade

### Screenshots/Steps

![diffupgrade](https://user-images.githubusercontent.com/11895339/196847103-fb3d2e79-1606-4d3e-881f-be1977262e73.png)

![diffupgrade2](https://user-images.githubusercontent.com/11895339/196847128-b6f8780a-e3a8-44ff-b095-0e159d2c56b8.png)

### Expected behavior

Should have all the upgrades available when pressing qubes manager button for upgrade.

### Actual behavior

Doesnt show any upgrade.

**Comment by unman** [comment] 2022-10-20 12:34
There's already an issue to say that QM should use the *same* update
mechanism as the widget.
This is subordinate to that issue.

**Comment by andrewdavidwong** [comment] 2022-10-21 13:19
Duplicate of #6635

**Comment by andrewdavidwong** [comment] 2022-10-21 13:19
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-10-21 13:19 UTC
Labels: T: bug, C: Fedora, P: default, needs diagnosis, C: updates
