### ISSUE TITLE
Reboot-button in Qubes-Manager missing

### ISSUE THREAD

**Issue by nielsk** [QubesOS/qubes-issues#2067] opened 2016-06-14 14:00 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): all

---

After updating a template VM you have to reboot all VMs based on it, so that they get the updated file system. The Qubes Manager has only a shutdown and a start/restore-button. It would be nice to have a reboot-button to be able to save a click. Bonus points if after a reboot apps would be automatically reopened that were open before.

**Comment by marmarek** [comment] 2016-06-14 23:27
This is duplicate of #1499 . As for restarting apps - this is hard, especially if you want to restart not only application itself but also for example reopen documents you were working with. So, unless someone is going to research and contribute implementation, I think it isn't going to happen.

**Closed by marmarek** 2016-06-14 23:27 UTC
Labels: duplicate
