### ISSUE TITLE
Fully updated Debian 11+ or Ubuntu Jammy have broken docker network

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#8222] opened 2023-05-24 10:44 UTC
Fully updated templates for Debian or Ubuntu have broken network for containers. Steps to reproduce:

1. Full update a Debian template with testing repository enabled and install docker,
2. Create an AppVM based on this updated template,
3. Start it and pull any docker image e.g., `fedora:latest`: `sudo docker pull fedora:latest`,
4. `sudo docker run -it fedora bash`
5. Try any network operation like `dnf update`.

First investigation is that `nft` qubes table is breaking it. I removed the table and it works.

**Comment by fepitre** [comment] 2023-05-24 10:44
@DemiMarie @marmarek

**Comment by dukeh3** [comment] 2023-05-24 12:28
The problem is a drop statement in nft qubes table in the forward chain.

iifgroup != 2 counter packets 744 bytes 52546 drop

The workaround is:

nft add rule qubes custom-forward accept

**Comment by DemiMarie** [comment] 2023-05-25 02:11
We should not ship a release with this bug.  Marking as `P: blocker`.

**Closed** 2023-05-29 17:21 UTC
Labels: T: bug, C: core, P: blocker, diagnosed, pr submitted, C: networking
