### ISSUE TITLE
Qube Manager: Sorting by state no longer groups dom0 with running qubes; sorting is inverted

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7632] opened 2022-07-21 02:57 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

In 4.0, sorting by the "state" column would group dom0 together with all running qubes. Now, in 4.1.1, sorting by state groups all running qubes on one end and dom0 on the opposite end (e.g., all running qubes at the top and dom0 at the bottom of the list).

(Note: When I say "running qubes," I really mean "all qubes that have an icon in the 'state' column," including e.g., qubes with updates available.)

Not sure if this is intentional, but the old behavior makes more sense to me for two reasons: (1) dom0 is actually running, and (2) dom0 has an icon in the state column.

**Comment by andrewdavidwong** [comment] 2022-07-21 03:05
Oh, I see what's happening: The sorting is inverted! In order to get all running qubes to the top of the list, I have click the "State" column heading twice. The first time I click it, it puts only dom0 at top and all running qubes at the bottom of the list. The second time I click it, it inverts the list, so dom0 is at the bottom while all running qubes are at the top. But here's the telltale sign: The running qubes are in *reverse* alphabetical order! In other words, the running qubes are all sorted together, then *subsorted* in *reverse* alphabetical order at the top of the whole Qube Manager list.

**Comment by unman** [comment] 2022-08-27 15:30
Duplicate of #7073

**Comment by andrewdavidwong** [comment] 2022-08-27 22:53
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2022-08-27 22:53 UTC
Labels: T: bug, C: manager/widget, P: minor, needs diagnosis
