### ISSUE TITLE
Qubes-R4.0.4-rc2-x86_64 fails to boot on NUC10

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6373] opened 2021-01-29 12:44 UTC
**Qubes OS version**

R4.0.4-rc2

**Affected component(s) or functionality**

Initial boot.

**Brief summary**

Boot from USB.  Brief flash on screen.  Reboot.

**How Reproducible**

100%

**To Reproduce**

1. Copy Qubes-R4.0.4-rc2-x86_64.iso to USB
2. Plug into Intel NUC10
3. Boot

**Expected behavior**

It would be nice if I was able to install and run on the Intel NUC 10.

**Actual behavior**

Crash/reboot/repeat

**Screenshots**

https://www.dropbox.com/s/3tc5vvsbpjl8bp2/NUC10-Boot-Qubes-R4.0.4-rc2-x86_64.png?dl=0

**Additional context**

**Solutions you've tried**

Can't even get to the initial boot screen to tweak any boot parms.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by permezel** [comment] 2021-01-29 13:19
Here is some info from a debian sid system running on the NUC10:

[cpuinfo.txt](https://github.com/QubesOS/qubes-issues/files/5894021/cpuinfo.txt)
[dmesg.txt](https://github.com/QubesOS/qubes-issues/files/5894022/dmesg.txt)
[intr.txt](https://github.com/QubesOS/qubes-issues/files/5894023/intr.txt)
[lspci.txt](https://github.com/QubesOS/qubes-issues/files/5894024/lspci.txt)

**Comment by andrewdavidwong** [comment] 2021-01-30 04:53
Is this a duplicate of #6372?

**Comment by permezel** [comment] 2021-01-30 05:57
I have just installed Fedora33 on the NUC10.  I am in the process of building Qubes.  I intend to do whatever I can to assist in getting to the bottom of this, which I guess initially means trying to see why this crashes so soon in the boot process.

The dmesg from the Fedora 33 boot is here:
[fed33-dmesg.txt](https://github.com/QubesOS/qubes-issues/files/5897456/fed33-dmesg.txt)

**Closed** 2023-08-05 09:28 UTC
Labels: T: bug, C: installer, P: default, hardware support, needs diagnosis, eol-4.0
