### ISSUE TITLE
qvm-run qubes.StartApp+ not handling long names of .desktop files

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7760] opened 2022-09-13 16:55 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
"Installed" Telegram AppImage that creates own .desktop shortcut. When I want to run it from qubes "start menu" nothing happens. After small investigation I found out that if I create .desktop file with long name it is visible in the menu but it not work (also from the CLI), but same file with short name works as normal. Original nameame of that Telegram app shortcut is
`appimagekit_e9d4f8123d28a5a3f93f92ec58a23421-Telegram_Desktop.desktop`

### Steps to reproduce
1.) Create .desktop file in ~/.local/share/applications with long name (use the one from Telegram app to be sure is long enough)
2.) Refresh Applications
3.) Try to run application from the menu, or using qvm-run with qubes.StartApp+

### Expected behavior
Application should run as normal

### Actual behavior
Nothing happens

**Comment by andrewdavidwong** [comment] 2022-09-16 12:46
See #7766 (and its comments) for more on this bug.

**Comment by Szewcson** [comment] 2022-10-02 09:48
Same is true for Chrome/Chromium shortcuts for PWA. They are also have longer filename then qubes limit.

**Comment by marmarek** [comment] 2024-02-25 02:12
Duplicate of https://github.com/QubesOS/qubes-issues/issues/7421

**Closed by marmarek** 2024-02-25 02:12 UTC
Labels: T: bug, C: core, P: default, needs diagnosis, affects-4.1
