### ISSUE TITLE
wpa_supplicant stops working after suspend with debian-11

### ISSUE THREAD

**Issue by mtdcr** [QubesOS/qubes-issues#7185] opened 2022-01-07 21:52 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

- 4.0.4
- 4.1.0-rc3

### Brief summary

Every time my machine wakes up from suspend, the wireless connection is broken. Selecting a different network from nm-applet does not help. I need to restart wpa_supplicant manually to fix it. 

### Steps to reproduce

- Install Qubes OS on ThinkPad T490 with Intel Wireless-AC 9560
- Use debian-11 for sys-net
- Install firmware-iwlwifi
- Connect to a wireless network
- Enter suspend
- Exit suspend

### Expected behavior

Network connection gets restored.

### Actual behavior

Network connection does not get restored.

**Comment by unman** [comment] 2022-01-08 15:41
Whenever this sort of issue comes up, (and it does - see #6570, #5956,
#3008) my thought is the same - I don't WANT my machine
to start spewing network data when it wakes from suspend.
I'm (probably) in a minority.

**Comment by mtdcr** [comment] 2022-01-15 12:52
> Whenever this sort of issue comes up, (and it does - see #6570, #5956, #3008) my thought is the same - I don't WANT my machine to start spewing network data when it wakes from suspend. I'm (probably) in a minority.

While I understand your point, I want to make clear that this bug is not about personal preferences, but about software remaining in a disfunctional state after returning from suspend. Just to avoid confusion.

**Comment by Warthog-Capital** [comment] 2022-08-05 13:51
This also happens to me. Wifi does not reconnect after resume from suspend.

### Qubes OS release

4.1.1

### Brief summary

On a fresh Qubes 4.1.1 installation, my Wifi connection does not come back after I suspend my laptop, and then start it again.

Solutions got get Wifi available again:
- opening a terminal in sys-net and running `sudo systemctl restart wpa_supplicant`
- restarting sys-net, by restarting all other VMs that depend on it, first
- restarting Qubes OS

My laptop is Thinkpad T440P with Intel network card (iwlwifi). The template is debian-11. Fully updated, but the issue already happens right after the first start of Qubes OS.

### Steps to reproduce

1. Install Qubes 4.1.1
2. Connect to wireless LAN
3. Suspend laptop by closing it, or suspending via the XFCE panel menu, 
4. Resume laptop by opening it or pressing the start button
5. Unlock the screen

### Expected behavior

Wifi should reconnect automatically.

### Actual behavior

The NetworkManager icon keeps spinning. Occasionally, a message toast pops up which says that "The network connection has been disconnected". After a few tries, it stops trying and my Wifi remains disconnected.

Some debug output from sys-net:

- [sudo journalctl -xefu NetworkManager.service](https://github.com/QubesOS/qubes-issues/files/9269100/journalctl.txt)
- [dmesg.txt](https://github.com/QubesOS/qubes-issues/files/9269115/dmesg.txt)

### Possibly related issues

- https://github.com/QubesOS/qubes-issues/issues/6570
  - Seems to be the same problem but with iwd
- https://github.com/QubesOS/qubes-issues/issues/3008
  - Qubes 3.2
- https://github.com/QubesOS/qubes-issues/issues/6587
  - This also happens to me, still with Qubes 4.1. Each network will end up being configured two times in NetworkManager, one for wls6 and one for wls7

**Comment by andrewdavidwong** [comment] 2022-08-05 16:56
> restarting sys-net, by shutting down all other VMs that recursively depend on it, first

Just FYI, you don't have to shut down all dependent VMs. You can instead just set `sys-firewall`'s NetVM to `none`, restart `sys-net`, then set `sys-firewall`'s NetVM back to `sys-net` again.

**Comment by unman** [comment] 2022-08-06 10:38
Sometimes, (if restart is absolutely necessary), `qvm-kill sys-net && sleep 5 && qvm-start sys-net` will do the the job.
I have that saved.

**Comment by mtdcr** [comment] 2022-08-06 10:52
FWIW, here's what I ended up with:

```sh
$ cat /etc/qubes/suspend-post.d/wpa-supplicant.sh 
#!/bin/sh
if systemctl -q is-active wpa_supplicant.service; then
	systemctl restart wpa_supplicant.service
fi
```

**Closed** 2024-12-07 13:40 UTC
Labels: T: bug, P: default, hardware support, needs diagnosis, C: networking, affects-4.1, eol-4.1
