### ISSUE TITLE
Qubes-3.1 install wizard breaks if dom0 username isn't "user"

### ISSUE THREAD

**Issue by isislovecruft** [QubesOS/qubes-issues#1540] opened 2015-12-25 15:08 UTC
I installed Qubes-3.1, and at some point during the initial configuration wizard it asked for me to create a new user (in dom0) and set the password for that user. I chose `isis`, and then the rest of the install failed with a bunch of errors (to be clear, the same error over and over again) because some Python module somewhere "could not find user 'user'". (I apologise that I didn't save the error log.) Reinstalling, going through the wizard again, and choosing "user" as my username fixed the issue.

**Comment by marmarek** [comment] 2015-12-25 15:11
Duplicate of #1504 (will be included in R3.1-rc2)

**Closed by marmarek** 2015-12-25 15:11 UTC
Labels: duplicate

**Comment by isislovecruft** [comment] 2015-12-25 15:12
@marmarek Oops, sorry! I should have searched first.
