### ISSUE TITLE
Xorg pages locking problem strikes back on FC23

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1688] opened 2016-01-25 12:29 UTC
Under heavy load (i.e. lots of VMs, tight memory constrains) my FC23-based VMs start to show the problem we previously say on Debian template. IIRC it was caused then by Xorg running as non-root and not being able to properly lock pages holding composition buffers, which resulted in random garbage appearing in GUID windows from time to time.

This now happens on the default FC23 template in 3.1-rc2.

**Comment by marmarek** [comment] 2016-01-25 12:32
Duplicate of #1028

**Closed by marmarek** 2016-01-25 12:32 UTC
Labels: bug, C: gui-virtualization, duplicate, P: critical
