### ISSUE TITLE
4.0.4 ISO fails to boot on Intel NUC10

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6449] opened 2021-03-09 12:18 UTC
**Qubes OS version**

4.0.4

**Affected component(s) or functionality**

Boot Install ISO

**Brief summary**

Tried the 4.0.4 install ISO on the Intel NUC105FNH4

**How Reproducible**

100%

**To Reproduce**

1. Obtain and verify 4.0.4 install ISO
2. Copy to USB SSD Drive
3. Boot
4. Hit F10
5. Select the SSD from the list
6. Watch in horror as it summarily carks. 

**Expected behavior**

I would have liked to be able to install 4.0.4 on the NUC10

**Actual behavior**

Nothing of use to anyone

**Screenshots**

![image](https://user-images.githubusercontent.com/2313876/110463183-50872180-811d-11eb-9a4d-17891662796d.png)
That is as far as it gets.  The screen clears next, and after a while, it reboots to the Qubes 4.1 system installed.

**Additional context**

I have installed 4.1 from an ISO I built to test a boot problem.  It runs OK, but as 4.1 is for non-production use, and there are no recent ISOs being produced which would include the required fix, I figured I would put 4.0.4 on the NUC10 and go away and be happy.

**Solutions you've tried**

I have confirmed that the image written to the boot SSD matches the GPG signatures, by reading it back and comparing.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment] 2021-03-10 22:11
Can you please confirm that this hardware satisfies all the system requirements and that you have gone through the installation troubleshooting documentation?

**Comment by permezel** [comment] 2021-03-11 02:58
I can confirm that I successfully installed 4.1 on it afer https://github.com/QubesOS/qubes-issues/issues/6373 was fixed.
I believe this implies it satisfies all the system requirements.  Once I installed 4.1, I restored all my latest 4.0.X backups on it and confirmed that everything was working: various split-gpg pairs for email and admin, etc.

I'll work thru the trouble shooting stuff later on today, to see if I get further.

I'd prefer to just run 4.1 on it but the "not for production use" put me off.....

**Comment by permezel** [comment] 2021-03-17 13:35
Boots into the installer if I turn off UEFI booting in the BIOS.
4.1 install ISO I built booted/installed with UEFI enabled, legacy disabled.
I was just booting the 4.0.4 install ISO on everything at hand, but I am running 4.1 on the NUC10 for now.
If anyone cares about why this fails to boot in UEFI mode and wants me to try some things, I can do so.
If not, just close this.

**Comment by andrewdavidwong** [comment] 2021-03-18 01:43
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed** 2021-03-18 01:43 UTC
Labels: C: installer, P: default, T: bug, hardware support
