### ISSUE TITLE
Latest kernel-latest 5.1.15 fails module builds

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#5185] opened 2019-07-21 18:19 UTC
Qubes 4.0 latest.  See attached log.  The ZFS on Linux folks say this:

https://github.com/zfsonlinux/zfs/issues/9071
[make.log](https://github.com/QubesOS/qubes-issues/files/3414910/make.log)

**Comment by marmarek** [comment] 2019-07-21 19:13
Yes, linked commit is included in 5.2 only, you're building 5.1. Actually, that's weird as according to that commit message, the error shouldn't happen before 5.2...
But there is another thing: we try to disable gcc plugins for external modules build, to workaround #2844 , so this code shouldn't be compiled at all. Apparently I missed some place.

**Comment by Rudd-O** [comment] 2019-07-25 02:00
I will retry once you guys release 5.2 kernel-latest.

On July 21, 2019 9:13:09 PM GMT+02:00, "Marek Marczykowski-Górecki" <notifications@github.com> wrote:
>Yes, linked commit is included in 5.2 only, you're building 5.1.
>Actually, that's weird as according to that commit message, the error
>shouldn't happen before 5.2...
>But there is another thing: we try to disable gcc plugins for external
>modules build, to workaround #2844 , so this code shouldn't be compiled
>at all. Apparently I missed some place.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/5185#issuecomment-513579869

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fepitre** [comment] 2019-07-27 10:44
It's on the road but I'm debugging why I still have trouble to make our CONFIG_GCC_PLUGIN merging into final configuration. That problem was solved before by adding gcc-c++.

**Comment by fepitre** [comment] 2019-07-27 12:43
@Rudd-O: you should be able to try soon: https://github.com/QubesOS/qubes-linux-kernel/pull/77

**Comment by marmarek** [comment] 2020-01-10 13:11
@Rudd-O does it still happen?

**Comment by DemiMarie** [comment] 2021-12-24 13:54
@andrewdavidwong time to close this?

**Comment by andrewdavidwong** [comment] 2021-12-25 09:29
Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-12-25 09:29 UTC
Labels: T: bug, C: builder, C: kernel, R: cannot reproduce, P: default

**Comment by Rudd-O** [comment] 2021-12-25 13:14
Yeah this isn't an issue anymore.
