### ISSUE TITLE
qubes' suspend hooks aren't called after VM suspend/resume (so VM clock is out of sync)

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3489] opened 2018-01-23 14:11 UTC
#### Qubes OS version:

R4.0rc3

#### Affected TemplateVMs: 

fedora-26 (default - qubes rpm)

---

### Steps to reproduce the behavior:

Start VM
Check time in dom0 and VM
Suspend laptop
Resume laptop X seconds later
Check time in dom0 and VM

### Expected behavior:

Time in VM and dom0 should be the same

### Actual behavior:

Time in dom0 is OK, but time in VM is lagging by X seconds

### General notes:

running qvm-sync-clock manually in the VM synchronizes the clock so it looks like Qubes' suspend hooks aren't called ; dropping an executable debug script in /etc/qubes/suspend-post.d/ shows that it's indeed not called upon resume. 

I didn't see anything relevant to suspend/resume in dom0 /var/log/qubes/vm-name.log

I'll be happy to test whatever is needed to help debugging but I'm not familiar enough with qubes-rpc and how events/hooks are propagated...

---

**Comment by andrewdavidwong** [comment] 2018-01-23 14:53
Is this related to (or possibly even a duplicate of) #3135?

**Comment by taradiddles** [comment] 2018-01-23 15:05
I don't think those are related:
- #3135 is related to NetworkManager: the dispatch "implementation" works but qubes-nmhook doesn't filter NM's events (interface down, change of connectivity, interface up, ...) and ends up being executed a few times in very short time span.
- the problem here seems to be specifc to qubes (rpc / suspend hooks).

Note that I don't have anything "custom" on this 4.0rc3 install: I use the default fedora-26 template (+ some additional rpms but they don't have anything to do with qubes), and I only imported my 3.2 backups. FWIW, the hardware is the same as yours - T450s.

**Comment by taradiddles** [comment] 2018-01-25 09:08
I rebooted my laptop (without any new updates) and after a full night suspended I don't see any time lag in VMs today. That's odd; I'll try to investigate when/if the problem reappears. Meanwhile, any pointer on what to look at (logs, rpc commands, ...) is welcome.

**Comment by taradiddles** [comment] 2018-01-27 09:08
Closing, everything works as expected now although I didn't change *anything* (no updates, no tweaks, ...).
Probably a transient issue or a difficult-to-reproduce bug.
Will reopen if it happens again.

**Comment by andrewdavidwong** [comment] 2019-02-07 02:36
Reopening due to report in #4793.

**Comment by marmarek** [comment] 2019-02-24 02:16
@beanjo55 can you check logs of `qubes-suspend` service in dom0 (`sudo journalctl -u qubes-suspend`)? It is responsible for triggering suspend-related events, including time synchronization. Especially, shortly after resume, check the service status (`systemctl status qubes-suspend`) - it should be "inactive (dead)". If it's still "running", it may mean some qube hang. In that case, you can observe running `qrexec-client` processes and see if there is any related to suspend (with `QUBESRPC qubes.SuspendPost` argument) or time synchronization (with `QUBESRPC qubes.GetDate` argument).

@ThomasWaldmann this may be related to #4835

**Comment by beanjo55** [comment] 2019-02-24 03:25
@marmarek 
The output of  ```sudo journalctl -u qubes-suspend``` is:
```Feb 23 21:38:57 dom0 systemd[1]: Starting Qubes suspend hooks...
Feb 23 21:38:57 dom0 52qubes-pause-vms[16059]: 2
Feb 23 21:38:57 dom0 systemd[1]: qubes-suspend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 23 21:38:57 dom0 systemd[1]: Failed to start Qubes suspend hooks.
Feb 23 21:38:57 dom0 systemd[1]: qubes-suspend.service: Unit entered failed state.
Feb 23 21:38:57 dom0 systemd[1]: qubes-suspend.service: Failed with result 'exit-code'.
```

When it works, the log entry is:
```
Feb 12 19:43:08 dom0 systemd[1]: Starting Qubes suspend hooks...
Feb 12 19:43:13 dom0 52qubes-pause-vms[7754]: 0
Feb 12 19:43:13 dom0 systemd[1]: Started Qubes suspend hooks.
Feb 12 20:34:25 dom0 systemd[1]: qubes-suspend.service: Unit not needed anymore. Stopping.
Feb 12 20:34:25 dom0 systemd[1]: Stopping Qubes suspend hooks...
```

The output of ```systemctl status qubes-suspend``` about 30 seconds after resume is:
```
● qubes-suspend.service - Qubes suspend hooks
   Loaded: loaded (/usr/lib/systemd/system/qubes-suspend.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-02-23 21:59:12 EST; 4min 22s ago
  Process: 16452 ExecStart=/usr/lib64/pm-utils/sleep.d/52qubes-pause-vms suspend suspend (code=exited, status=2)
 Main PID: 16452 (code=exited, status=2)

Feb 23 21:59:12 dom0 systemd[1]: Starting Qubes suspend hooks...
Feb 23 21:59:12 dom0 52qubes-pause-vms[16452]: 2
Feb 23 21:59:12 dom0 systemd[1]: qubes-suspend.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 23 21:59:12 dom0 systemd[1]: Failed to start Qubes suspend hooks.
Feb 23 21:59:12 dom0 systemd[1]: qubes-suspend.service: Unit entered failed state.
Feb 23 21:59:12 dom0 systemd[1]: qubes-suspend.service: Failed with result 'exit-code'.
```

Since reporting the issue, I have noticed that while the issue temporarily resolves itself after reboot, there is no noticeable pattern or cause. After some reboots the issue appears after the first suspend-resume cycle, other times it has successfully synced five or more times before the issue returns. When the issue occurs, it occurs on every suspend-resume cycle until the next reboot.

Also, in case it may be related, the module unloading and loading upon resume does not occur either, despite modules being listed in ```/rw/config/suspend-module-blacklist```

The ```rc.local``` and ```qubes-firewall-user-script``` scripts do not seem to be executing either, but I have not observed these to work before on my system, whereas the suspend-resume behavior worked as intended and then began to fail. I am going to so some more testing to determine if this is my error or a bug and respond if necessary.

**Comment by marmarek** [comment] 2019-02-24 03:58
This looks to be related to the problem, especially "Failed to start Qubes suspend hooks". Module unloading and loading problem is also related, as the same mechanism is used to do that.
I'd expect a little more than just "2" from `52qubes-pause-vms` script... Can you look up messages from `qubesd` service about that time?

**Comment by marmarek** [comment] 2019-02-24 04:00
Is your sys-usb alive? Or does it hang after such failed suspend-resume? Does such suspend take noticeably longer?

**Comment by beanjo55** [comment] 2019-02-24 05:18
Around the time of suspend, there are messages reading ```dom0 qubesd[####]: socket.send() raised exception``` but I have also found these messages in other places of the full log that do not correlate with a suspend or resume. These also do not appear consistently with a failed suspend, so this may be unrelated. 
I looked at the entire log as well from ```journalctl``` for today and noticed nothing new related to the qubes suspend process in ether a successful or failed instance.

I never explicitly made a sys-usb VM so all USB functionality is as a like new 4.0.1 install. the trackpad, mouse(these are over internal usb in my system), and external devices work as normal. It does not take longer than a normal suspend.

I also confirmed the behavior from #4835 happens when using the Xfce desktop enviroment shipped with Qubes, but not in KDE.

**Comment by beanjo55** [comment] 2019-02-24 05:59
I may have accidentally discovered the cause of the issue in my case. In the process of trying to confirm #4835 i closed all the open windows on my desktop in preparation to logout. That included a windows 7 HVM. After confirming #4835 I did not restart the windows HVM and the issue no longer occurred.

I did a very brief test by doing suspend-resume with the HVM closed then checking the output of ```journalctl -e -u qubes-suspend`` and qubes-suspend completed without error. After starting the HVM and doing sleep-resume there was now an error entry for qubes-suspend. after closing the HVM and doing another suspend-resume the log showed a clean qubes-suspend.

I havn't done enough testing to know if this is an HVM issue or an issue with this specific HVM, but can provide configuration details for the HVM if necessary.

**Comment by marmarek** [comment] 2019-02-24 13:09
That's it! Fix on the way.

**Closed** 2019-03-01 04:02 UTC
Labels: C: core, C: templates, bug

**Comment by aslfv** [comment] 2019-03-14 01:20
@marmarek thank you! After installing `qubes-core-dom0-4.0.41-1.fc25` the issue highlighted in
https://github.com/QubesOS/qubes-issues/issues/4658#issuecomment-470626036 was essentially solved: VMs such as `sys-net` can now resume properly from suspend even when a windows VM -- without QWT -- is running, while the machine is suspending.

However, only in the case of `sys-usb` the machine still fails to resume (and instead reboots) when `sys-usb` is in a transient state (i.e. qube manager displaying the VM with a yellow dot).
