### ISSUE TITLE
Qubes Update feature request

### ISSUE THREAD

**Issue by jlariviere1** [QubesOS/qubes-issues#7601] opened 2022-07-04 16:49 UTC
### The problem you're addressing (if any)
Qubes Update (GUI) can take a long time to complete, and if it has an error, can be difficult to identify the precise issue.  The Details window only provides information after that particular qube has completed the process (whether with or without errors).  

### The solution you'd like
It would be wonderful if the Details window was reasonably 'live', providing details of the current task.  Not the one qube being update, but the specific program trying to be updated or terminal command being run.  

### The value to a user, and who that user might be
The user would be able to identify the particular task that is having issues; whether purely network related, a large update file, system unable to locate the updated file, etc.  It would also provide a better status instead of waiting for well over an hour for one qube to get an "I'm sorry something went wrong and I wasn't able to update, but I am moving on to the next"

**Comment by andrewdavidwong** [comment] 2022-07-05 02:14
This sounds like it is probably a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of (in the sense that it is likely subsumed by) #7443. If so, please comment on that existing issue instead. If anyone believes this is not really a duplicate of #7443, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-07-05 02:14 UTC
Labels: T: enhancement, P: default
