### ISSUE TITLE
Wireguard failure with recent kernels

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#3591] opened 2018-02-15 20:38 UTC
#### Qubes OS version:

R4.0-rc4
R3.2

#### Affected TemplateVMs: 

debian-9
fedora-26

---

### Steps to reproduce the behavior:

attempt creation wireguard tunnel

### Expected behavior:

normal wireguard function

### Actual behavior:

wireguard no longer functional

### General notes:

normal function with 4.9.56-21 kernel
failure with 4.14.x kernels:
 ip link add mullvad-ch1 wireguard
RTNETLINK answers: operation not supported
Unable to get device: Protocol not supported

---

**Comment by tortugaverde98** [comment] 2018-06-04 23:44
Same problem with qubes 4, fedora 28 minimal, kernel 4.14.35-1.

**Comment by danielschmalhofer** [comment] 2018-11-27 10:03
same problem with fedora 29, kernel 4.19.4

**Comment by danielschmalhofer** [comment] 2018-11-27 17:38
nope - running it doesn't update a thing - doesn't fix it, but thanks :)

**Comment by dirtbag** [comment] 2018-12-04 01:37
Im having this problem as well. Just upgraded to fedora 29 and the wireguard dkms is busted somehow..
there is no wireguard kernel module getting built.

**Comment by danielschmalhofer** [comment] 2018-12-04 08:18
I just deleted and then reinatalled it - works like a charm now.

**Comment by dirtbag** [comment] 2018-12-04 12:37
that worked! thanks danielschmalhofer!!

**Comment by cfcs** [comment] 2018-12-04 16:12
@pugege does that fix it for you?

Sounds like this issue should be closed.

**Comment by andrewdavidwong** [comment] 2018-12-05 01:29
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by aliyazdani** [comment] 2019-01-08 19:46
im experiencing this issue under Fedora 29 - 4.19.10-300.fc29.x86_64
I tried removing the packages and reinstalling and upgrading and still not working.

**Comment by vladimir-lu** [comment] 2019-01-12 13:08
@danielschmalhofer Did installing the dkms package directly in a fedora-29 TemplateVM work for you? I used to run into #3835 so I still compile the DKMS module in a fedora-25 TemplateVM before copying it over.

**Comment by tasket** [comment] 2019-01-13 15:11
This has been working for me in Debian 9 with the 4.9 kernel. There is no problem as long as wireguard-dkms is installed/updated while the template is in HVM mode with kernel=''.

I'm updating my wiki page to provide general setup instructions:
https://github.com/tasket/Qubes-vpn-support/wiki/Wireguard-VPN-connections-in-Qubes-OS

**Comment by tasket** [comment] 2019-01-17 23:41
@pugege I've had mainly reports of success so far. Did you test the connection before installation?

If you're getting any specific errors in the log, you can open an issue at
https://github.com/tasket/Qubes-vpn-support/issues

**Comment by tasket** [comment] 2019-03-25 10:13
Just a note that the stock Debian 9 kernel (v4.9) no longer seems to boot in Qubes HVM mode.

I've re-tested the setup process for Debian using kernel 4.19 instead and updated the [wiki page.](https://github.com/tasket/Qubes-vpn-support/wiki/Wireguard-VPN-connections-in-Qubes-OS)

**Comment by unman** [comment] 2019-03-25 11:53
On Mon, Mar 25, 2019 at 03:13:38AM -0700, tasket wrote:
> Just a note that the stock Debian 9 kernel (v4.9) no longer seems to boot in Qubes HVM mode.
> 
> I've re-tested the setup process for Debian using kernel 4.19 instead and updated the [wiki page.](https://github.com/tasket/Qubes-vpn-support/wiki/Wireguard-VPN-connections-in-Qubes-OS)
> 

Works for me.
What set up do you have that might prevent this working?

**Comment by tasket** [comment] 2019-03-25 14:06
A fair amount of mundane tools and the config changes are conditions added to wpa-supplicant service, disabled apt-daily services, disabled lvm2-monitor service, added vm-boot-protect service (disabled for tests), and modified auth config in accordance with the Qubes doc/vm-sudo instructions. One package is installed from testing: thin-provisioning-tools.

All of this was working with hvm mode for some time (Dec-Jan) until I tried it again last week. I wondered if the last Debian kernel update got corrupted, but lo-and-behold...... Fedora 28 doesn't work in hvm mode, either. *That* template is unmodified.

Symptoms: Telling it to run a terminal in hvm mode with kernel='', the vm starts and status shows as running after 10 sec, then it seems to busy-wait with 30% cpu usage. After >3min a term window may appear and it will be blank or have random noise; its unusable and `xl console` won't work either.

If it matters, I'm running the latest dom0 stable updates + 4.19.15-1 dom0 kernel. I wonder now if this has to do with recent changes to make gtk+ apps start correctly..?

**Comment by tasket** [comment] 2019-03-25 14:19
I feel like opening an issue to have the qubes-vm kernels packaged for the templates themselves. Maybe I'm wrong, but I think this could make module installation issues far simpler for Qubes devs and users alike. The price we pay is some extra disk space. Good idea?

**Comment by marmarek** [comment] 2019-06-05 23:37
kernel-latest-(qubes-vm) now contains wireguard module out of the box: https://github.com/QubesOS/qubes-linux-kernel/commit/790685154f0c657508a60ffe231d04715109e771

**Closed by marmarek** 2019-06-05 23:37 UTC
Labels: C: other, P: major, T: bug

**Comment by xaki23** [comment] 2019-07-28 10:47
just leaving a note here for the next one to find this ...

to install the kernel-latest pkg (which includes wireguard.ko):

dom0$ sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing kernel-latest-qubes-vm

pay attention to what version is being installed.
right now thats a 5.1.17 for me.
set that as kernel for your WG gateway vm via qvm-prefs or gui.

TA-DAH!
