### ISSUE TITLE
qubes-template-fedora-26-minimal does not allow root access

### ISSUE THREAD

**Issue by virtualdxs** [QubesOS/qubes-issues#4432] opened 2018-10-26 02:31 UTC
### Qubes OS version:
R4.0

### Affected component(s): 
VMs running fedora-28-minimal

### Steps to reproduce the behavior:
`sudo qubes-dom0-update fedora-28-minimal`
Create a StandaloneVM based on fedora-28-minimal
Open a terminal
Run a sudo command

### Expected behavior:
Without asking a password, it does what you ask

### Actual behavior:
Asks for a password. `sudo -v` says user is not allowed to use sudo

### General notes:
Can't get passwordless root via xl console either
---
### Related issues:
#1130

**Comment by andrewdavidwong** [comment] 2018-10-26 02:55
Duplicate of #3833

**Comment by andrewdavidwong** [comment] 2018-10-26 02:55
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-10-26 02:55 UTC
