### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.9.56-21.pvops.qubes.x86_64

### ISSUE THREAD

**Issue by DiagonalArg** [QubesOS/qubes-issues#3428] opened 2017-12-25 13:10 UTC
#### Qubes OS version:

R 4.0-rc3

#### Affected TemplateVMs: 

whonix-gw

### Steps to reproduce the behavior:

New install on a Thinkpad W520.  Everything went without a hitch.  Then, update the whonix-gw vm, using:

`sudo apt-get update && sudo apt-get dist-upgrade`

### Actual behavior:

[Had to transcribe.  Excuse any typing errors.]

```
Loading new u2mfn-4.0.11 DKMS files...
dpkg: warning: version '4.9.56-21.pvops.qubes.x86_64' has bad syntax: invalid character in revision number
It is likely that 4.9.56-21.pvops.qubes.x86_64 belongs to a chroot's host
Building initial module for 4.9.56-21.pvops.qubes.x86_64
Error! Bad return status for module build on kernel: 4.9.56-21.pvops.qubes.x86_64 (x86_64)
Consult /var/lib/dkms/u2mfn/4.0.11/build/make.log
```

/var/lib/dkms/u2mfn/4.0.11/build/make.log

```
DKMS make.log for u2mfn-4.0.11 for kernel 4.9.56-21.pvops.qubes.x86_64 (x86_64)
Mon Dec 25 12:27:49 UTC 2017
make: Entering directory '/lib/modules/4.9.56-21.pvops.qubes.x86_64/build'
   LD      /var/lib/dkms/u2mfn/4.0.11/build/built-in.o
   CC     /var/lib/dkms/u2mfn/4.0.11/build/u2mfn.o
ccl: error: cannot load plugin ./scripts/gcc-plugins/latent_entropy_plugin.so
./scripts/Makefile.build:299: recipe for target '/var/lib/dkms/u2mfn/4.0.11/build/u2mfn.o' failed
make[1]: *** [/var/lib/dkms/u2mfn/4.0.11/build/u2mfn.o] Error 1
Makefile: 1493: recipe for target ' module_/var/lib/dkms/u2mfn/4.0.11/build' failed
make: *** [_module_/var/lib/dkms/u2mfn/4.0.11/build] Error 2
make: Leaving diretory '/lib/modules/4.9.56-21.pvops.qubes.x86_64/build'
```

**Comment by marmarek** [comment] 2017-12-25 13:22
1. Duplicate of #2844 
2. Should be harmless in practice - the module is already provided for this kernel in binary form too.

**Closed by marmarek** 2017-12-25 13:22 UTC
