### ISSUE TITLE
disp VMs created when importing from 3.2

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3850] opened 2018-04-24 09:40 UTC
### Qubes OS version:
4.0

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

Import Qubest from 3.2

### Expected behavior:

The VM from 3.2 will be imported as a Qube in 4.0

### Actual behavior:

The VM is imported as a Qube and also another Qube called disp-<VM-name> exists. 

### General notes:

Can I delete these disp Qubes?  Why are they there?

**Comment by andrewdavidwong** [comment] 2018-04-25 04:03
Didn't you just file this as #3846?

**Comment by andrewdavidwong** [comment] 2018-04-25 04:03
Duplicate of #3273

**Comment by andrewdavidwong** [comment] 2018-04-25 04:03
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-04-25 04:03 UTC
