### ISSUE TITLE
Qube Manager: Right click instantly selects edit firewall

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4003] opened 2018-06-14 22:36 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

Here are the different effects:
1. If you left click a Qube:
Nothing happens.
2. If you right click a Qube, do not move the mouse, and instantly let go:
The context menu displays and stays displayed even though you are not holding down a mouse key.
- Then move the mouse over a menu item and left or right click:
You execute that menu item.
3. If you right click a Qube, hold down the mouse, do not move the mouse, wait a moment, and then let go:
Effect # 2 still happens.
4. If you right click a Qube, hold down the mouse, move slightly to the left, and then let go: 
The context menu displays but then disappears.
5. If you right click a Qube, hold down the mouse, move slightly to the right, and then let go: 
A popup displays: "[Dom0] Qube configuration problem!", because the context menu displayed and selected "Edit qube firewall rules" so fast you are confused as to why Qube Manager has this glitch.
6. If you right click a Qube, hold down the mouse, wait.
The context menu displays and stays displayed as long as you hold the mouse button.
- Then move the mouse over a menu item and let go or left click:
You execute that menu item.

### Expected behavior:

- The Qube Manager should not register a right click release, within so many milliseconds (200ms?) of opening the context menu, as a menu item selection but instead as Effect # 2.
- Should a left click a qube, and then releasing the left mouse button while still over the same qube also cause Effect # 2?

### Actual behavior:

See "Steps to reproduce the behavior"

**Comment by andrewdavidwong** [comment] 2018-06-14 23:34
Duplicate of #1911

**Comment by andrewdavidwong** [comment] 2018-06-14 23:34
This appears to be a duplicate of an existing issue (see https://github.com/QubesOS/qubes-issues/issues/1911#issuecomment-272076488). If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-06-14 23:34 UTC
