### ISSUE TITLE
Shift wireless tools from packages_minimal.list to qubes-vm-recommended

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8365] opened 2023-07-18 12:40 UTC
### Qubes OS release (if applicable)

4.2

### Brief summary

https://github.com/QubesOS/qubes-builder-debian/pull/74

https://github.com/QubesOS/qubes-meta-packages/pull/66

(a) Gradual fix of #6566

**Comment by marmarek** [comment] 2023-07-21 01:21
> * Close this issue as a duplicate of 6566 and perform the action described here as part of 6566 (assuming 6566 isn't closed as "won't do," "invalid," etc.)

This one IMO makes more sense (in this case). Then, it's okay to link several PRs into that issue, if needed some iterations.

**Comment by marmarek** [comment] 2023-07-21 01:21
Duplicate of #6566

**Closed by marmarek** 2023-07-21 01:21 UTC
Labels: T: enhancement, C: Debian/Ubuntu, P: default, pr submitted

**Comment by andrewdavidwong** [comment] 2023-07-21 03:07
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
