### ISSUE TITLE
 Pasting VM to VM does not work

### ISSUE THREAD

**Issue by Massquirrel** [QubesOS/qubes-issues#7743] opened 2022-09-07 09:13 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1 (Qubes 4.1.1 (R4.1))

### Brief summary
Pasting clipboard content does not work on all VMs (AppVM, TemplateVM, StandaloneVM).
In every program in a destination VM.

### Steps to reproduce
Install new Qubes OS, restore backuped AppVMs.

### Expected behavior
Press CTRL+SHIFT+V to insert arbitrary text.

### Actual behavior
- Using CTRL+SHIFT+C. A pop up appears stating that x bytes where copied to the clipboard.
- Press CTRL+SHIFT+V has no effect. No paste notification appears.

The log error on each CTRL+SHIFT+V press : `/var/log/qubes/quid.any-appvm.log` :
`connect: No such file or directory`

**Comment by marmarek** [comment] 2022-09-07 09:35
Check if `qubes-qrexec-policy-daemon` service is running in dom0.

**Comment by Massquirrel** [comment] 2022-09-07 09:54
Thank you very much! The problem is solved!

The service restart saved the situation:
`sudo systemctl restart qubes-qrexec-policy-daemon.service`

Cause of problem: I put not a proper format (comma separated tags, like @tags:one,two,three) in config: `/etc/qubes-rpc/policy/qubes.ClipboardPaste`

And it's causing the service crash:
```
Sep 07 02:06:54 dom0 qrexec-policy-daemon[4219]: qrexec.exc.PolicySyntaxError: /etc/qubes-rpc/policy/qubes.ClipboardPaste:9: invalid action: red
Sep 07 02:06:54 dom0 systemd[1]: qubes-qrexec-policy-daemon.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 02:06:54 dom0 systemd[1]: qubes-qrexec-policy-daemon.service: Failed with result 'exit-code'.
```

**Comment by lubellier** [comment] 2022-09-07 19:57
@Massquirrel so please, close this issue. Thank.

**Comment by andrewdavidwong** [comment] 2022-09-07 20:51
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2022-09-07 20:51 UTC
Labels: T: bug, P: default
