### ISSUE TITLE
Inconsistency in displaying of app icons in the toolbar R4.0 rc4

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#3537] opened 2018-02-04 19:44 UTC
#### Qubes OS version:
R4.0 rc4

#### Affected TemplateVMs: 
Fedora-based
### Steps to reproduce the behavior:
Open a few applications from Fedora based AppVMs Work and Personal and look at the icons in the toolbar.

### Expected behavior:
Firefox, Nautilus, Terminals etc should have their own icons, but in yellow or blue

### Actual behavior:
Firefox in Personal has the correct icon but Firefox in Work has the padlock. Nautilus has padlock icons rather than the filing cabinet icon for both Personal and Work
![2018-02-04-194332](https://user-images.githubusercontent.com/12783198/35781581-da2331ae-09e3-11e8-8d0a-c440861b2b93.png)
.  
In this image Home is Nautilus, New I... is Firefox, Mozilla is Firefox, Qubes.. is LibreOffice Write

**Comment by andrewdavidwong** [comment] 2018-02-04 23:38
Duplicate of #1495.

**Comment by andrewdavidwong** [comment] 2018-02-04 23:38
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-04 23:38 UTC

**Comment by JPL1** [comment] 2018-02-05 08:25
Yes, probably the same thing
