### ISSUE TITLE
Max ~40 firewall rules

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#4018] opened 2018-06-19 17:45 UTC
### Qubes OS version:
4.0

### Affected component(s): 
qvm-firewall

### Steps to reproduce the behavior:
Create a VM with more than ~40 firewall rules.

I directly edited firewall.xml and restarted the machine and/or qubesd for that.

### Expected behavior:
VM starts.

### Actual behavior:
VM doesn't start and some error about iptables is shown in journalctl.

If you do the same with ~30 rules, the VM starts.

### General Notes:
Why is there a limit at all?

### Related issues:
This **is** issue #1570, which was supposedly fixed, but apparently is not.
I however don't have the rights to reopen it.

**Comment by marmarek** [comment] 2018-06-19 17:56
There is compatibility layer to make templates/standalonevms imported
from 3.2 working. And it fails there. Maybe this compat layer should be
optional, opt-in? Or at least opt-out...

**Comment by andrewdavidwong** [comment] 2018-06-20 01:04
> I however don't have the rights to reopen it.

You can simply leave a comment on a closed issue indicating that it should be opened, and we'll reopen it.

**Comment by andrewdavidwong** [comment] 2018-06-20 01:04
Duplicate of #1570

**Comment by andrewdavidwong** [comment] 2018-06-20 01:04
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-06-20 01:04 UTC
