### ISSUE TITLE
qubes-guid crashed for all AppVMs, possibly after unplugging external display

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7387] opened 2022-03-29 05:15 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

I have once plugged an HDMI external display to my computer. The HDMI display has very high resolution - 4 times my original screen in dimension and I have extend the screen rather than mirroring. I put one window to the second screen. After a while I unplugged the HDMI display (probably I forget to draw the window back to my main screen) and suspend the computer. After I have resumed the computer I am surprised to find out that all appVM windows are missing.

I suspect that it is `guid` that is missing, so I have started up a new VM to see the command line format of `guid` - `/usr/bin/qubes-guid -N name -C color_in_hex -l 1 -C /var/run/qubes/guid-conf.vmid -d vmid`, and when I rerun the command for each VM, the VM windows come back.

The guid log shows as follows:
```
Window 0x4a035da is still set as transient_for for a 0x4a035df window, but VM tried to destroy it
PANIC: invalid work area:
     x: 0 (limit 1048576)
     y: 0 (limit 1048576)
 width: 1920 (limit 1048576)
height: 18446744073709551583 (limit 1048576)
Exiting!
```
or
```
Icon size: 128x128
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x4e001ec
                 Failed serial number:  3122
                 Current serial number: 3123
XShmAttach failed for window 0x4e001eb(remote 0xa000f8)
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
PANIC: invalid work area:
     x: 0 (limit 1048576)
     y: 0 (limit 1048576)
 width: 1920 (limit 1048576)
height: 18446744073709551583 (limit 1048576)
Exiting!
```

My main screen is 1920x1080 now.

btw one another error log from ~/.xsession-error:
```
vmname: Sending monitor layout
asyncio: Task exception was never retrieved
future: <Task finished name='Task-88' coro=<DAEMONLauncher.send_monitor_layout() done, defined at /usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_start_daemon.py:338> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_start_daemon.py", line 362, in send_monitor_layout
    with open(self.guid_pidfile(vm.xid)) as pidfile:
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/qubes/guid-running.8'
```
This log appears for each appVM. This may provide hint about what the time is when guid exits.

### Steps to reproduce

(I have only seen this once, so I cannot tell whether some of the operations are unrelated; it is not everyday that I can reproduce the issue on that exact big HDMI screen since that screen is not mine ;d )

1. plug a HDMI screen, and extend rather than to mirror
2. move a window there
3. unplug HDMI screen
4. suspend
5. resume

### Expected behavior

The window layout is as normal.

### Actual behavior

All the `qubes-guid` exited and VM windows are hidden.

**Comment by jevank** [comment] 2022-03-29 06:20
duplicate https://github.com/QubesOS/qubes-issues/issues/7309 ?

**Comment by DemiMarie** [comment] 2022-03-29 17:02
Yup, duplicate of #7309.  Should be fixed in updates-testing.

**Closed by DemiMarie** 2022-03-29 17:02 UTC
Labels: T: bug, P: default
