### ISSUE TITLE
qubes.GetAppmenus silently fails when /usr/local/share/applications does not exit

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7149] opened 2021-12-22 18:51 UTC
### Qubes OS release

4.1rc

### Brief summary

Somewhat similar to https://forum.qubes-os.org/t/troubleshooting-qvm-sync-appmenus-on-unsupported-distro/5783, I get this `Error getting application list`, on qubes based on debian10 and debian11, but not those based on fedora:

```
[yann@dom0 ~]$ qvm-sync-appmenus -v [yann@dom0 ~]$ qvm-sync-appmenus -vvv  webapps-dvm-template
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 11, in <module>
    load_entry_point('qubesdesktop==4.1.11', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.8/site-packages/qubesappmenus/receive.py", line 398, in main
    new_appmenus = retrieve_appmenus_templates(vm, use_stdin=use_stdin)
  File "/usr/lib/python3.8/site-packages/qubesappmenus/receive.py", line 374, in retrieve_appmenus_templates
    new_appmenus = get_appmenus(vm if not use_stdin else None)
  File "/usr/lib/python3.8/site-packages/qubesappmenus/receive.py", line 154, in get_appmenus
    raise qubesadmin.exc.QubesException(
qubesadmin.exc.QubesException: Error getting application list
```

In the VM, the script does indeed exit in error, and includes an empty line:
```
user@webapps-dvm-template:~$ /etc/qubes-rpc/qubes.GetAppmenus 
discord.desktop:Name=Discord
discord.desktop:Exec=qubes-desktop-run discord.desktop
discord.desktop:Terminal=false
discord.desktop:X-MultipleArgs=false
discord.desktop:Type=Application
discord.desktop:Icon=firefox-esr
discord.desktop:Categories=Network;WebBrowser;
discord.desktop:StartupWMClass=Firefox-esr
discord.desktop:StartupNotify=true

user@webapps-dvm-template:~$ echo $?
1
```

and tracing it reveals the lack of `/usr/local/share/applications` is the problem:
```
+ case $i in
+ :
+ [[ -d /usr/local/share//applications ]]
```

Manually creating this directory allows the command to proceed successfully, but it should not be necessary at all.

**Comment by marmarek** [comment] 2021-12-22 20:18
Duplicate of https://github.com/QubesOS/qubes-issues/issues/7115

**Closed by marmarek** 2021-12-22 20:18 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2021-12-23 19:08
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
