### ISSUE TITLE
Can't shutdown VMs from Qubes widget

### ISSUE THREAD

**Issue by n1m1** [QubesOS/qubes-issues#3739] opened 2018-03-24 19:19 UTC
### Qubes OS version:

R4.0-rc5

### Affected component(s): 

Qubes widget
All templates and AppVM

---

### Steps to reproduce the behavior:

In Qubes 4.0-rc5 (the problem was not present in 4.0-rc4) I am experiencing a weird issue with Qubes widget. Please, take a look to this picture.

![qubes-widget-kill](https://user-images.githubusercontent.com/7090974/37867736-6485183c-2f94-11e8-99f2-3a25c5ab212d.jpg)

When I open a VM (be it an AppVM or a ProxyVM) or a Template (be it Fedora, Debian or Whonix), a circle appears in the widget  - I do not know what it means exactly - and it never stops. In the menu of the VMs affected by this problem, the "Shutdown" button is not present anymore (only the "Kill" one). In order to shutdown a VM or a Template i need to run

`qvm-shutdown nameoftheVM`

in Dom0.

If I click on "Console log", "Qrexec log" or "GUI Daemon Log" nothing happens.

This issue appears randomly: as mentioned above, it affects AppVM and ProxyVM, independently from the template they are based on. Sometimes a VM is not affected by this problem, but after a reboot it is.

No idea how to debug this problem, nor which logs I should look at.

**Comment by andrewdavidwong** [comment] 2018-03-25 02:36
Duplicate of #3660

**Comment by andrewdavidwong** [comment] 2018-03-25 02:36
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-25 02:36 UTC
