### ISSUE TITLE
modify qrexec policy syntax to allow autostart=no in the policy (allows to avoid unexpected autostart of VMs issue)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7168] opened 2021-12-31 12:51 UTC
Quote @marmarek in https://phabricator.whonix.org/T930

> modify qrexec policy syntax to allow `autostart=no` in the policy

> This way, `whonix.SdwdateStatus` could be configured to not start the domain. 

----

related:

* https://github.com/QubesOS/qubes-issues/issues/5930
* https://github.com/QubesOS/qubes-issues/issues/5253

**Comment by marmarek** [comment] 2021-12-31 13:01
Duplicate of https://github.com/QubesOS/qubes-issues/issues/5952 (already done)

**Closed** 2021-12-31 13:56 UTC
Labels: T: enhancement, P: default

**Comment by andrewdavidwong** [comment] 2022-01-01 08:32
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
