### ISSUE TITLE
Application missing in template!

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7245] opened 2022-02-07 08:23 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1

### Brief summary

when installing new/fresh templates (here is whonix) it will show multiple missing application message when i go to qube settings -> applications (check the uploaded image)  

### Steps to reproduce

install whonix from qubes repo (not the default/offline within dvd)

### Expected behavior

without these messages

### Actual behavior

![applications-missing](https://user-images.githubusercontent.com/11895339/152749348-bcba03d4-2d36-4c44-9841-7eda959d312f.png)

### Workaround 

- go to qube applications from qubes manager for the template/appvm
- press on << (moving these errors from right to left)
- then press Apply then OK
- then it will disappear

**Comment by adrelanos** [comment] 2022-02-08 14:42
Whonix specific:
Until yesterday there was still an outdated Template in Qubes community stable repository. (https://github.com/QubesOS/qubes-issues/issues/6890#issuecomment-1031429983) That was fixed a long time ago (https://github.com/QubesOS/qubes-issues/issues/6805#issuecomment-945188195) but until yesterday not in Qubes R4.1 community stable repository.
The ones listed in above screenshot should no longer be happening.

Qubes specific:
Duplicate of https://github.com/QubesOS/qubes-issues/issues/6805.

**Comment by andrewdavidwong** [comment] 2022-02-09 01:27
> Whonix specific:
> 
> Until yesterday there was still an outdated Template in Qubes community stable repository. (https://github.com/QubesOS/qubes-issues/issues/6890#issuecomment-1031429983) That was fixed a long time ago (https://github.com/QubesOS/qubes-issues/issues/6805#issuecomment-945188195) but until yesterday not in Qubes R4.1 community stable repository.
> 
> The ones listed in above screenshot should no longer be happening.
> 
> 
> 
> Qubes specific:
> 
> Duplicate of https://github.com/QubesOS/qubes-issues/issues/6805.

Thanks, @adrelanos. Closing, since one part is fixed, and the other part is a duplicate. 

If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

This appears to be a **partial** [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-02-09 01:27 UTC
Labels: T: bug, C: manager/widget, C: Whonix, P: default, diagnosed

**Comment by wit-g** [comment] 2022-05-13 13:40
Hi @andrewdavidwong 
I downloaded on April 22nd the new version of Qubes OS and finally installed it last night. When I went to the "sys-whonix, whonix-gw-16, whonix-ws-16, anon-whonix and fedora-34 Settings, it showed me multiple missing applications message. (Fedora-34 only "gpk...something" :/ )
Today, I was looking for some help on net and found your page. I did what you commented above. I moved these messages to the left and pressed ok.
It seems like all are fixed. Thank you :)
