### ISSUE TITLE
Pausing or changing audio source causes AppVM to lose all audio

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2117] opened 2016-06-26 18:34 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-8 (only tested with debian-8)
---
### Expected behavior:

Always able to play audio.
### Actual behavior:

The sound from a specific appVM can disappear after a pause or change of audio source, e.g. pause video or load other video on YouTube.
### Steps to reproduce the behavior:
1. Play media file, either via web browser or local media player.
2. Notice that the sound can disappear after pausing or changing audio source.
### General notes:

Restarting pulseaudio with `pulseaudio -k` and `pulseaudio --start` doesn't help. I can't find anything relevant at the end of the output from `dmesg`. **The only thing that helps is to restart the appvm.**

It seems that the audio only disappears while there is no media file playing. I.e. the audio doesn't disappears while a media file is actively playing, but happens when it's paused or loading other audio source.

**Comment by marmarek** [comment] 2016-06-29 23:09
Can't reproduce. Check `/var/log/qubes/pacat.VMNAME.log` (replace `VMNAME` with actual VM name) for more details.

**Comment by 0keh** [comment] 2016-09-29 21:10
I have the same behavior and found out what is happen: When I - in example - have a webvideo playing in AppVM Browser and I hit the Mute-Hotkey on my Laptop, the sound is muted. If I press the mute button again, notification shows me it is unmuted but no sound at all.
Happens to all AppVMs.
Because while activating mute-mode, Pulseaudio mutes the channel Master and Speaker+LO. 
Deactivating mute-mode just restores the Master-channel. If I plug headphones in, the sound is available. If I unmute the channel in pulseaudio manually, all sound of any AppVM is available.

It always happens. 
Iam using fresh installed Qubes R3.2

**Comment by unman** [comment] 2016-11-08 13:31
@andrewdavidwong   Like @marmarek I can't reproduce this. In absence of response from @dumbl3d0re I suggest closing.
On hardware I've tested the issue reported by @0keh doesn't exist: the mute button mutes/unmutes all channels.

**Comment by andrewdavidwong** [comment] 2016-11-09 22:36
Closing. We can reopen this if anyone else can reproduce it.

**Closed by andrewdavidwong** 2016-11-09 22:36 UTC
Labels: bug, C: Debian

**Comment by ryannoblett** [comment] 2016-12-31 12:12
I have the same issue as @0keh where pressing mute mutes everything, and pressing it again does not unmute the speakers, only the analog out, and I have to unmute manually via PulseAudio Volume Control. I have a Thinkpad X220.

**Comment by andrewdavidwong** [comment] 2016-12-31 17:48
@ryannoblett: So that's actually a different issue from the original one, right? If so, do you mind filing a new issue?

**Comment by ryannoblett** [comment] 2017-01-02 02:43
@andrewdavidwong Sure. I've created https://github.com/QubesOS/qubes-issues/issues/2550 after updating my system to make sure it's not already patched.
