### ISSUE TITLE
Display sleep -> "tiny display area" on VMs

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#6300] opened 2020-12-22 08:10 UTC
Latest stable Qubes OS, KDE desktop although I think this happens with XFCE too.  Please help me give you more debugging information.

Since I enabled display power management, whenever the display goes to sleep, after it wakes up, windows in the open VMs are unclickable except for the controls in the top left corner of windows placed against the top left corner of the screen.  Using the Display resolution tool fixes this problem with the following procedure: (1) reduce display size one or two steps, say to 1920x1080 (2) increase display size to the maximum resolution, which was the previous setting.  Keyboard input to windows from the VM is unaffected.  VMs not running at the time are also unaffected (of course, if I restart the VM, the problem goes away for that VM).

I suspect what is going on is that, after sleep, VMs get notified that the display resolution has changed to some absurdly small value, but when the display is woken up, the converse notification does not take place.

**Comment by iamahuman** [comment] 2020-12-22 09:18
Before entering the suspend state, please have an AppVM window placed at the top left corner of the first screen. Can you interact with it after resuming?

**Comment by iamahuman** [comment] 2020-12-22 09:38
Would you start the following commands in different terminals in Dom0, do suspend/resume, and post the results?

1. `strace -e trace=none -e signal=hup -r -p "$(pidof -S, watch-screen-layout-changes)"`
2. `xev -root -events visibility -events structure -events property -events randr`

**Comment by Rudd-O** [comment] 2020-12-28 03:38
I will take a look at running these commands.  Thank you.

**Comment by iamahuman** [comment] 2021-01-16 15:51
Related: #2421

**Comment by iamahuman** [comment] 2021-02-11 03:00
Does `coredumpctl` shows xrandr crashes? Then, #6375 is a duplicate of this issue.

**Comment by Rudd-O** [comment] 2021-02-11 12:14
I've seen some coredumpctl crashes but that was last month.  It's not crashing when "tiny screen in VMs but not in dom0" happens three times a day.

**Comment by marmarek** [comment] 2021-02-11 12:21
Does `qvm-start-gui --notify-monitor-layout` workaround help? Can you check `xrandr` output in an affected VM (before fixing it)?

**Comment by pabpas** [comment] 2021-03-06 15:16
`qvm-start-gui --notify-monitor-layout` works for me.

Output of `xrandr`while it was happening:

> $ xrandr 
Screen 0: minimum 64 x 64, current 64 x 64, maximum 32767 x 32767
DUMMY0 connected primary
   QB2560x1080   46.11 +

vs normal output:
> $ xrandr 
Screen 0: minimum 64 x 64, current 2560 x 1080, maximum 32767 x 32767
DUMMY0 connected primary 2560x1080+0+0 0mm x 0mm
   QB2560x1080   46.11*+

**Comment by iamahuman** [comment] 2021-03-06 15:24
> Would you start the following commands in different terminals in Dom0, do suspend/resume, and post the results?
> 
>     1. `strace -e trace=kill -r -p "$(pidof -S, watch-screen-layout-changes)"`
> 
>     2. `xev -root -events visibility -events structure -events property -events randr`

I believe the results of these commands to be helpful in diagnosing potential timing issues.

**Comment by pabpas** [comment] 2021-03-23 16:11
Attached the output of the two commands.

Some things to note:
- It didn't happen after suspending/resuming but after unlocking the screen.
- The affected AppVM had no windows open when it happened. I noticed the issue after launching a program.
- `qvm-start-gui --notify-monitor-layout` worked. I stopped the logs after executing it.

[qubes_issue_6300_strace.txt](https://github.com/QubesOS/qubes-issues/files/6191071/qubes_issue_6300_strace.txt)
[qubes_issue_6300_xev.txt](https://github.com/QubesOS/qubes-issues/files/6191075/qubes_issue_6300_xev.txt)

**Comment by iamahuman** [comment] 2021-03-25 02:57
Apologies for my mistake, I specified the wrong syscall.

Would you try again, this time with:

```
(
strace -e trace=select,clone -r -p "$(pidof -S, watch-screen-layout-changes)" &
xev -root -events visibility -events structure -events property -events randr &
wait
) >> out.log
```

Thanks for helping out!

**Comment by pabpas** [comment] 2021-03-28 08:53
There you go. I had to change a bit the command because strace outputs to stderr. Hope now it is useful.
> ) 1>> 1out.log 2>&1

[1out.log](https://github.com/QubesOS/qubes-issues/files/6217051/1out.log)

**Comment by iamahuman** [comment] 2021-03-30 22:23
> Attached the output of the two commands.
> 
> Some things to note:
> 
> * It didn't happen after suspending/resuming but after unlocking the screen.
> * The affected AppVM had no windows open when it happened. I noticed the issue after launching a program.
> * `qvm-start-gui --notify-monitor-layout` worked. I stopped the logs after executing it.
> 
> [qubes_issue_6300_strace.txt](https://github.com/QubesOS/qubes-issues/files/6191071/qubes_issue_6300_strace.txt)
> [qubes_issue_6300_xev.txt](https://github.com/QubesOS/qubes-issues/files/6191075/qubes_issue_6300_xev.txt)

Your logs show that VM monitor layout update is indeed happening. However, there seems to be the time window where the DisplayPort is briefly disconnected.

As to how to fix the issue, perhaps throttleing/coalescing monitor layout update might help.

**Comment by Rudd-O** [comment] 2021-04-29 21:52
I switched to a different video card (AMD), and so far no problems.  I would not call victory yet tho.

**Closed** 2023-08-05 09:29 UTC
Labels: T: bug, C: gui-virtualization, P: default, more info needed, needs diagnosis, eol-4.0
