### ISSUE TITLE
Disabling the Community Templates through Qubes OS Global Config doesn't work.

### ISSUE THREAD

**Issue by cheesestickstomatojuice** [QubesOS/qubes-issues#9247] opened 2024-05-18 15:23 UTC
### Qubes OS release
Qubes 4.2.1 (R4.2) up-to-date

### Brief summary
Disabling the Community Templates via Qubes OS Global Config doesn't work. When you uncheck the box in Qubes Global Config and click "Apply," both the Community Template and Community Testing Template are selected. Additionally, enabling and then disabling the Community Testing Template still displays it in the Template Manager and Community Templates are not showed.

### Steps to reproduce

1. Open Qubes OS Global
2. Navigate to Updates
3. Scroll down to Template Repositories
4. Check the box for community templates and than uncheck it, it should both enable community testing templates and community templates.
5. If you uncheck community testing templates and go to template manager it shows you only the community testing templates in Template Manager.

### Expected behavior

If the box is unchecked, it should deactivate both the community templates and community testing templates, and the Template Manager should not display any of them. Alternatively, if one is enabled, it should correctly display that template rather than the community testing template. If both are enabled both templates should be shown in Template Manager.

### Actual behavior

When the community templates box is unchecked, it activates both Community Templates and Community Testing Templates, but only the Community Testing Template is shown in Template Manager. Even if you uncheck the community testing templates, the Template Manager still displays the Community Testing Templates.

**Comment by UndeadDevel** [comment] 2024-05-18 20:43
Duplicate of #8802.

**Closed** 2024-05-19 17:59 UTC
Labels: T: bug, R: duplicate, C: manager/widget, P: default, affects-4.2
