### ISSUE TITLE
`qubes-update-gui` crashes when no qubes need to be updated

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9226] opened 2024-05-14 02:08 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

If there are no qubes that need to be updated, `qubes-update-gui` crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 60, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 167, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 106, in populate_vm_list
    self.refresh_update_list(settings.update_if_stale)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 119, in refresh_update_list
    to_update = self._get_stale_qubes(cmd)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 214, in _get_stale_qubes
    in output.decode().split("\n", maxsplit=1)[0]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 60, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.11/site-packages/qui/updater/updater.py", line 167, in perform_setup
    self.intro_page.populate_vm_list(self.qapp, self.settings)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 106, in populate_vm_list
    self.refresh_update_list(settings.update_if_stale)
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 119, in refresh_update_list
    to_update = self._get_stale_qubes(cmd)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qui/updater/intro_page.py", line 214, in _get_stale_qubes
    in output.decode().split("\n", maxsplit=1)[0]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

### Steps to reproduce

Start `qubes-update-gui` with no qubes needing to be updated.

### Expected behavior

No crash.

### Actual behavior

Crash.

**Comment by marmarek** [comment] 2024-05-14 02:55
Duplicate of #9203

**Closed** 2024-05-14 02:55 UTC
Labels: T: bug, R: duplicate, P: default, C: updates
