### ISSUE TITLE
Is build error rpm ?

### ISSUE THREAD

**Issue by thxqua** [QubesOS/qubes-issues#4132] opened 2018-07-23 12:15 UTC
I already got this error for 8 times...

qubes-src/linux-scrypt/pkgs/fc28/x86_64/scrypt-1.2.1-1.fc28.x86_64.rpm
      qubes-src/linux-scrypt/pkgs/fc28/x86_64/scrypt-debuginfo-1.2.1-1.fc28.x86_64.rpm
      qubes-src/linux-scrypt/pkgs/fc28/x86_64/scrypt-debugsource-1.2.1-1.fc28.x86_64.rpm
Makefile:193: target 'template-whonix.get-sources' given more than once in the same rule
Makefile:193: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:195: target 'template-whonix.get-sources-extra' given more than once in the same rule
Makefile:195: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:215: target 'template-whonix-vm' given more than once in the same rule
Makefile:215: target 'builder-debian-vm' given more than once in the same rule
Makefile:227: target 'template-whonix-dom0' given more than once in the same rule
Makefile:227: target 'builder-debian-dom0' given more than once in the same rule
Makefile:549: target 'template-whonix.grep' given more than once in the same rule
Makefile:549: target 'builder-debian.grep' given more than once in the same rule
-> Building template fc26 (logfile: build-logs/template-fc26.log)...
--> Done.
Makefile:193: target 'template-whonix.get-sources' given more than once in the same rule
Makefile:193: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:195: target 'template-whonix.get-sources-extra' given more than once in the same rule
Makefile:195: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:215: target 'template-whonix-vm' given more than once in the same rule
Makefile:215: target 'builder-debian-vm' given more than once in the same rule
Makefile:227: target 'template-whonix-dom0' given more than once in the same rule
Makefile:227: target 'builder-debian-dom0' given more than once in the same rule
Makefile:549: target 'template-whonix.grep' given more than once in the same rule
Makefile:549: target 'builder-debian.grep' given more than once in the same rule
-> Building template fc27 (logfile: build-logs/template-fc27.log)...
--> Done.
Makefile:193: target 'template-whonix.get-sources' given more than once in the same rule
Makefile:193: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:195: target 'template-whonix.get-sources-extra' given more than once in the same rule
Makefile:195: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:215: target 'template-whonix-vm' given more than once in the same rule
Makefile:215: target 'builder-debian-vm' given more than once in the same rule
Makefile:227: target 'template-whonix-dom0' given more than once in the same rule
Makefile:227: target 'builder-debian-dom0' given more than once in the same rule
Makefile:549: target 'template-whonix.grep' given more than once in the same rule
Makefile:549: target 'builder-debian.grep' given more than once in the same rule
-> Building template fc28 (logfile: build-logs/template-fc28.log)...
--> Done.
Makefile:193: target 'template-whonix.get-sources' given more than once in the same rule
Makefile:193: target 'builder-debian.get-sources' given more than once in the same rule
Makefile:195: target 'template-whonix.get-sources-extra' given more than once in the same rule
Makefile:195: target 'builder-debian.get-sources-extra' given more than once in the same rule
Makefile:215: target 'template-whonix-vm' given more than once in the same rule
Makefile:215: target 'builder-debian-vm' given more than once in the same rule
Makefile:227: target 'template-whonix-dom0' given more than once in the same rule
Makefile:227: target 'builder-debian-dom0' given more than once in the same rule
Makefile:549: target 'template-whonix.grep' given more than once in the same rule
Makefile:549: target 'builder-debian.grep' given more than once in the same rule
-> Building template stretch (logfile: build-logs/template-stretch.log)...
--> Done.
make[1]: Entering directory '/home/user/qubes-builder'
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/pykickstart//pykickstart-2.32.tar.gz ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/pykickstart/ pykickstart-2.32.tar.gz
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/blivet//blivet-2.1.6.tar.gz ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/blivet/ blivet-2.1.6.tar.gz
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/lorax//lorax-25.19.tar.gz ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/lorax/ lorax-25.19.tar.gz
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/lorax-templates-qubes//lorax-templates-qubes-4.0.2.tar.bz2 ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/lorax-templates-qubes/ lorax-templates-qubes-4.0.2.tar.bz2
~/qubes-builder/chroot-fc25/home/user/qubes-src/installer-qubes-os/lorax-templates-qubes ~/qubes-builder
~/qubes-builder
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/pungi//pungi-4.1.14.tar.bz2 ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/pungi/ pungi-4.1.14.tar.bz2
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/anaconda//anaconda-25.20.9.tar.bz2 ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/anaconda/ anaconda-25.20.9.tar.bz2
~/qubes-builder/chroot-fc25/home/user/qubes-src/installer-qubes-os/anaconda ~/qubes-builder
~/qubes-builder
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/qubes-anaconda-addon//qubes-anaconda-addon-4.0.7.tar.gz ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/qubes-anaconda-addon/ qubes-anaconda-addon-4.0.7.tar.gz
~/qubes-builder/chroot-fc25/home/user/qubes-src/installer-qubes-os/qubes-anaconda-addon ~/qubes-builder
~/qubes-builder
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/qubes-release//qubes-release-4.0.tar.bz2 ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/qubes-release/ qubes-release-4.0.tar.bz2
~/qubes-builder/chroot-fc25/home/user/qubes-src/installer-qubes-os/qubes-release ~/qubes-builder
~/qubes-builder
# Create the archive for specific Qubes packages
[[ -e /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/qubes-release//qubes-dom0-dist-upgrade-2.0.tar.bz2 ]] \
	|| /home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/installer-qubes-os/qubes-release/ qubes-dom0-dist-upgrade-2.0.tar.bz2
~/qubes-builder/chroot-fc25/home/user/qubes-src/installer-qubes-os/qubes-release ~/qubes-builder
~/qubes-builder
-> Building installer-qubes-os (pykickstart/pykickstart.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/pykickstart-2.32-4.fc25.noarch.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/python-kickstart-2.32-4.fc25.noarch.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/python3-kickstart-2.32-4.fc25.noarch.rpm
-> Building installer-qubes-os (blivet/python-blivet.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/python3-blivet-2.1.6-5.fc25.noarch.rpm
-> Building installer-qubes-os (lorax/lorax.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/lorax-25.19-1.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/lorax-lmc-novirt-25.19-1.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/lorax-lmc-virt-25.19-1.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/lorax-templates-generic-25.19-1.fc25.x86_64.rpm
-> Building installer-qubes-os (lorax-templates-qubes/lorax-templates-qubes.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/lorax-templates-qubes-4.0.2-1.fc25.noarch.rpm
-> Building installer-qubes-os (pungi/pungi.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/pungi-4.1.14-2.fc25.noarch.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/pungi-utils-4.1.14-2.fc25.noarch.rpm
-> Building installer-qubes-os (anaconda/anaconda.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-core-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-debuginfo-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-dracut-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-gui-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-tui-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-widgets-25.20.9-13.fc25.x86_64.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/x86_64/anaconda-widgets-devel-25.20.9-13.fc25.x86_64.rpm
-> Building installer-qubes-os (qubes-anaconda-addon/qubes-anaconda-addon.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/qubes-anaconda-addon-4.0.7-1.fc25.noarch.rpm
-> Building installer-qubes-os (qubes-release/qubes-release.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/qubes-release-4.0-4.noarch.rpm
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/qubes-release-notes-4.0-4.noarch.rpm
-> Building installer-qubes-os (qubes-release/qubes-dom0-dist-upgrade.spec) for fc25 dom0 (logfile: build-logs/installer-qubes-os-dom0-fc25.log)
--> Done:
      qubes-src/installer-qubes-os/pkgs/fc25/noarch/qubes-dom0-dist-upgrade-2.0-2.noarch.rpm
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
-> Building antievilmaid (anti-evil-maid/anti-evil-maid.spec) for fc25 dom0 (logfile: build-logs/antievilmaid-dom0-fc25.log)
--> Done:
      qubes-src/antievilmaid/pkgs/fc25/x86_64/anti-evil-maid-4.0.1-1.fc25.x86_64.rpm
-> Building antievilmaid (tpm-extra/tpm-extra.spec) for fc25 dom0 (logfile: build-logs/antievilmaid-dom0-fc25.log)
--> Done:
      qubes-src/antievilmaid/pkgs/fc25/x86_64/tpm-extra-4.0.1-1.fc25.x86_64.rpm
-> Building antievilmaid (trousers-changer/trousers-changer.spec) for fc25 dom0 (logfile: build-logs/antievilmaid-dom0-fc25.log)
--> Done:
      qubes-src/antievilmaid/pkgs/fc25/x86_64/trousers-changer-4.0.1-1.fc25.x86_64.rpm
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
make[1]: Leaving directory '/home/user/qubes-builder'
make[1]: Entering directory '/home/user/qubes-builder'
make[1]: Leaving directory '/home/user/qubes-builder'
[user@vault qubes-builder]$ make iso
-> Preparing for ISO build...
--> Removing old rpms from the installer repos...
---> Cleaning up repo: dom0-updates...
---> Cleaning up repo: installer...
---> Cleaning up repo: qubes-dom0...
--> Copying vmm-xen RPMs...
--> Copying core-libvirt RPMs...
--> Copying core-vchan-xen RPMs...
--> Copying core-qubesdb RPMs...
--> Copying linux-utils RPMs...
--> Copying python-xcffib RPMs...
--> Copying python-sphinx RPMs...
--> Copying python-pillow RPMs...
--> Copying core-admin RPMs...
--> Copying core-admin-client RPMs...
--> Copying core-admin-addon-whonix RPMs...
--> Copying core-admin-linux RPMs...
--> Copying core-agent-linux RPMs...
--> Copying intel-microcode RPMs...
--> Copying linux-firmware RPMs...
--> Copying linux-kernel RPMs...
--> Copying artwork RPMs...
--> Copying gui-common RPMs...
--> Copying gui-daemon RPMs...
--> Copying gui-agent-linux RPMs...
make: *** No rule to make target 'iso.copy-rpms.gui-agent-xen-hvm-stubdom', needed by 'iso.copy-rpms'.  Stop.

**Comment by marmarek** [comment] 2018-07-23 12:35
This is a duplicate of #4118

**Closed by marmarek** 2018-07-23 12:35 UTC
