### ISSUE TITLE
fedora-minimal templates missing passwordless-root (R4.0-rc1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3157] opened 2017-10-09 15:45 UTC
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25-minimal
fedora-26-minimal

---

### Steps to reproduce the behavior:
install template, run 'su' or 'sudo'
### Expected behavior:
works without asking for user password
### Actual behavior:
asks for user password.

**Comment by marmarek** [comment] 2017-10-09 23:10
Well, this was intended effect. Minimal template is a base for custom needs. One may choose to setup https://www.qubes-os.org/doc/vm-sudo/.
But indeed it should be included in documentation. together with information how to access root without sudo (`qvm-run -u root fedora-25-minimal xterm`).

**Comment by tasket** [comment] 2017-12-03 04:02
I just ran into this myself. I think this policy change also means the vm-sudo doc will have to take the minimal configuration into account?

**Comment by mossy-nw** [comment] 2018-01-23 17:02
Since fedora-minimal.md docs now make clear how to address this (previous changes and current pull request -- https://github.com/QubesOS/qubes-doc/pull/525) can this issue be considered resolved and closed?

**Comment by andrewdavidwong** [comment] 2018-01-24 10:10
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-01-24 10:10 UTC
Labels: C: doc, P: major, task
