### ISSUE TITLE
Cannot change TemplateVM of a DisposableVM (need to recreate sys-usb-dvm at each TemplateVM upgrade)

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#6270] opened 2020-12-10 21:20 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
[sys-usb-dvm (disposablevm-template)](https://www.qubes-os.org/doc/disposablevm-customization/#create-the-sys-usb-disposablevm) (private container data here used under DispVM) cannot be changed to another, already created [DisposableVM Template](https://www.qubes-os.org/doc/disposablevm-customization/#creating-a-new-disposablevm-template) from manually cloned+upgraded/freshly downloaded TemplateVM.

So for each TemplateVM release/upgrade, user has to:
- recreate template-version-dvm(DisposableVM TemplateVM based on TemplateVM)
- recreate sys-usb-dvm (DisposableVM) itself.

It is not possible to simply point that DispVM to new DispTemplateVM based on upgrade TemplateVM.
```
qvm-prefs sys-usb-dvm template fedora-32-dvm
Cannot change template of Disposable VM
```

Let's say I would like to simplify OEM disk management and end user's friction of using a sys-usb-dvm.
I would then remove versioning on the fedora-dvm creation in a guide.

But then again:
```
qvm-prefs fedora-dvm template fedora-32
qvm-prefs error: Cannot change template while there are DispVMs based on this qube
```

**Brief summary**

Impossibility to change DispTemplateVM of a DispVM
Needs recreating DispTemplateVM, then recreating of DispVM and sys-usb-dvm TemplateVM deployment/upgrade

**How Reproducible**

Each time

**To Reproduce**

1. Create TemplateDispVM
2. Create DispVM based on TemplateDispVM
3. Simulate an upgrade by attempting to assign dispvm to other TemplateDispVM, or Other TemplateDispVM to other TemplateVM.

**Expected behavior**

Being able to use DispVM as disposable private storage base, and DispTemplateVM as disposable root storage for sys-usb-dvm

**Actual behavior**

Have to recreate at each TemplateVM upgrade
1- [Recreate a new DispTemplateVM](https://www.qubes-os.org/doc/disposablevm-customization/#creating-a-new-disposablevm-template)
2- [Recreate a new Dispvm template for your sys-usb-dvm and recreate sys-usb-dvm ](https://www.qubes-os.org/doc/disposablevm-customization/#create-the-sys-usb-disposablevm)

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment] 2020-12-10 21:38
This is a duplicate of https://github.com/QubesOS/qubes-issues/issues/5491 and https://github.com/QubesOS/qubes-issues/issues/3576
It is fixed in 4.1, I'll look into backporting it into 4.0, but it may be too risky.

**Comment by tlaurion** [comment] 2020-12-10 21:39
mitigation: 
1- shutdown sys-usb-dvm
1- remove sys-usb-dvm:
`qvm-remove -f sys-usb-dvm`
2- [Follow doc and recreate sys-usb no-dvm](https://www.qubes-os.org/doc/usb-qubes/#creating-and-using-a-usb-qube)
`sudo qubesctl state.sls qvm.sys-usb`

And:
- Wait for 4.1 prior of using ServiceAppVMs based on DispVMs

Or

- Recreate DispTemplateVM based on debian (less frequent releases)

**Comment by tlaurion** [comment] 2020-12-10 21:41
Will follow https://github.com/QubesOS/qubes-issues/issues/3576#issuecomment-457051234

**Comment by andrewdavidwong** [comment] 2020-12-11 03:05
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-12-11 03:05 UTC
Labels: P: default, T: bug
