### ISSUE TITLE
package manager refuse to update packages with .rpm

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5024] opened 2019-05-07 02:26 UTC
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

R4.0.1

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

Package Update

**Brief summary**
_A clear and concise summary of the bug._

there is problem of updating package named with .rpm at the end of it (which it should be), removing it .rpm with `dnf reinstall` then the package name this will overcome the issue.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to Qubes Terminal
_2. Run `sudo qubes-dom0-update`
_3. New packages will be shown but none of them can be installed

**Expected behavior**
_A clear and concise description of what you expected to happen._

When there are new updates , distro should be updated smoothly

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

refusing to update

**Screenshots**
_If applicable, add screenshots to help explain your problem._

![qubesissue](https://user-images.githubusercontent.com/11895339/57267294-0fc8a800-706f-11e9-8474-5bb34bb5b311.png)

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

Fix the issue by running `sudo dnf reinstall xxx(name of the package) without .rpm at the end`

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

This might be related #3756

**Comment by lunarthegrey** [comment] 2019-05-07 22:02
This is a known issue, although I don't have time to search for the related issue at the moment. The solution is to simply do `sudo dnf reinstall anaconda-core etc etc` to reinstall all of the packages.

**Comment by andrewdavidwong** [comment] 2019-05-08 01:35
Duplicate of #4792

**Comment by andrewdavidwong** [comment] 2019-05-08 01:36
@TNTBOMBOM, you previously filed #4928, which was also a duplicate of #4792. Perhaps you forgot?

**Comment by andrewdavidwong** [comment] 2019-05-08 01:36
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-05-08 01:36 UTC
Labels: P: default, T: bug

**Comment by TNTBOMBOM** [comment] 2019-05-09 03:44
@andrewdavidwong oh i really forgot that , thank you for notifying me.
