### ISSUE TITLE
qvm-backup-restore fails to properly parse labels

### ISSUE THREAD

**Issue by jwoytek** [QubesOS/qubes-issues#3219] opened 2017-10-26 17:52 UTC
#### Qubes OS version:

4.0

#### Affected TemplateVMs: 

N/A

---

### Steps to reproduce the behavior:

Attempt to restore a backup from another Qubes 4.0 system that may be running a slightly different update level.

### Expected behavior:

Restore should succeed.

### Actual behavior:

Restore fails with a KeyError exception at line 134 in file /usr/lib/python3.5/site-packages/qubesadmin/backup/core3.py

This exception occurs because some backups seem to have the color stored in vm.properties, and some systems have "label-X" instead of colors in self.labels. When working with multiple machines, we found that some had label-X in self.labels, and some had colors. The restore process seems to assume that self.labels has colors as keys. 

All systems involved were Qubes 4.0rc1. rc2 does not function on any of our hardware, so we were unable to test that.

### General notes:

---

**Comment by jwoytek** [comment] 2017-10-26 18:01
Quick fix: 

At line 134 in file /usr/lib/python3.5/site-packages/qubesadmin/backup/core3.py:
vm.label = vm.properties.pop('label')
try:
   vm.label = self.labels[vm.label]
except KeyError:
   pass

**Comment by andrewdavidwong** [comment] 2017-10-27 00:32
This appears to be a duplicate of #3211. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-10-27 00:32 UTC

**Comment by jwoytek** [comment] 2017-10-27 03:24
Concur on the duplicate issue. There was a delay between discovery and filing, and I missed the prior report. Sorry!
