### ISSUE TITLE
4.0.1 debian-based templates (debian-9 and whonix-*-14 both) ignore all keyboard settings

### ISSUE THREAD

**Issue by ryan-green** [QubesOS/qubes-issues#4522] opened 2018-11-19 02:02 UTC
With a 4.0.1 host, all debian-based templates ignore keyboard settings (set via localectl 00-keyboard.conf, xfce, xkbmap, and Qubes-manager per-vm) from host. When downgrading to debian-9 or whonix-14 versions 4.0.0-*, the same VM guests full work as expected. Further, setting /etc/keyboard/default and localectl in the debian VMs themselves has no effect, even though files persist across reboot. setxkbmap in the vm temporarily works, but naturally does not persist. I have reproduced this on two machines, and downgrades to 4.0.0 guests worked each time. I tried with the keyboard set at install time, and changing it after, and all reproduce results. Also tested with us variants (colemark, dvorak, etc). This is not consistent with the faq (https://www.qubes-os.org/faq/). This appears to be a regression and/or new issue. Fedora-29 guests accept global keyboard settings as expected.

**Comment by marmarek** [comment] 2018-11-19 22:17
Duplicate of #4489 
(also, updates-status repo is not a place for bug reports, qubes-issues is)

**Closed by marmarek** 2018-11-19 22:17 UTC

**Comment by ryan-green** [comment] 2018-11-20 05:21
> Duplicate of #4489
> (also, updates-status repo is not a place for bug reports, qubes-issues is)

Perhaps I mis-understood this quoted blurb:
https://www.qubes-os.org/doc/reporting-bugs/

"If you’re reporting a bug in a package that is in a testing repository, please reference the appropriate issue in the updates-status repository. "

Aren't those templates in the testing repos?

**Comment by marmarek** [comment] 2018-11-20 09:47
"reference", as in "include a link to the update" - https://github.com/QubesOS/updates-status/issues/763 in this case
