### ISSUE TITLE
Disposable template does not have right icon in app menu; launches apps in disposable template rather than in disposable based on template

### ISSUE THREAD

**Issue by kototama** [QubesOS/qubes-issues#3464] opened 2018-01-15 08:54 UTC
#### Qubes OS version:
Q4RC3

#### Affected TemplateVMs: 

fedora 26

---

### Steps to reproduce the behavior:

Install fedora 26 template with:

```
sudo qubes-dom0-update qubes-template-fedora-26
qvm-create -l red -t fedora-26 fedora-26-dvm
qvm-prefs fedora-26-dvm template_for_dispvms True
qvm-features fedora-26-dvm appmenus-dispvm 1
qubes-prefs default-dispvm fedora-26-dvm
```

### Expected behavior:

A menu entry with `Disposable: fedora-26-dvm` is created

### Actual behavior:

A menu entry with `Domain: fedora-26-dvm ` is created

### General notes:
Is there a workaround? How can I start a fedora 26 disposable VM?

---

**Comment by marmarek** [comment] 2018-01-15 09:45
> qvm-features fedora-26-dvm appmenus-dispm 1

Typo, should be `appmenus-dispvm`.
If that doesn't help, try `qvm-appmenus --update fedora-26-dvm`

**Comment by kototama** [comment] 2018-01-15 09:57
Sorry what is the typo? You mean it should be `appmenu-dispvm` ??

**Comment by marmarek** [comment] 2018-01-15 10:01
You wrote appmenus-dispm, should be appmenus-disp**v**m.

**Comment by kototama** [comment] 2018-01-15 10:04
I see. I had it right in the bash history, just typed it wrongly for this bug report.
Typing `qvm-appmenus --update fedora-26-dvm` solved it. Thank you very much.

One more question, I have: `update-availables 1` in fedora-25-dvm prefs but not in fedora-26-dvm. Do I need to set it?

**Comment by kototama** [comment] 2018-01-15 10:05
I am editing the bug report for the typo, since the bug is not due to a typo...

**Comment by marmarek** [comment] 2018-01-15 10:47
> One more question, I have: update-availables 1 in fedora-25-dvm prefs but not in fedora-26-dvm. Do I need to set it?

No. It should be on the template (fedora-26), not fedora-26-dvm. It is info that you have some updates pending for that template. `updates-available` should be handled automatically, no manual action should be required.

**Comment by andrewdavidwong** [comment] 2018-01-16 05:17
@kototama, would you be willing to help us document this? Please see the [Documentation Guidelines](https://www.qubes-os.org/doc/doc-guidelines/) for details.

**Comment by iamahuman** [comment] 2021-02-07 13:34
Fedora 26 is no longer supported. It might be a good idea to close this issue.

**Comment by andrewdavidwong** [comment] 2021-02-08 11:21
If anyone would like this issue to be reopened, please leave a comment. Thank you.

**Comment by tlaurion** [comment] 2021-11-17 18:05
@marmarek 

Any idea why `qvm-appmenus --update fedora-34-dvm` is required to be entered manually after following https://www.qubes-os.org/doc/templates/#switching instructions:

```
 [user@dom0 ~]$ qvm-create -l red -t fedora-34 fedora-34-dvm
 [user@dom0 ~]$ qvm-prefs fedora-34-dvm template_for_dispvms True
 [user@dom0 ~]$ qvm-features fedora-34-dvm appmenus-dispvm 1
 [user@dom0 ~]$ qubes-prefs default-dispvm fedora-34-dvm
```

Which for clarity until bug fixed should be :
 ```
[user@dom0 ~]$ qvm-create -l red -t <NEW_TEMPLATE> <NEW_DISPOSABLE_TEMPLATE>
 [user@dom0 ~]$ qvm-prefs <NEW_DISPOSABLE_TEMPLATE> template_for_dispvms True
 [user@dom0 ~]$ qvm-features <NEW_DISPOSABLE_TEMPLATE> appmenus-dispvm 1
 [user@dom0 ~]$ qubes-prefs default-dispvm <NEW_DISPOSABLE_TEMPLATE>
 [user@dom0 ~]$ qvm-appmenus --update <NEW_DISPOSABLE_TEMPLATE>
```

**Comment by marmarek** [comment] 2021-11-17 18:47
Thanks for the report, I'll take a look. I assume it's Qubes 4.0, right?

> For the sake of simplicity of in-template upgrades, is there a reason why the templates would not be simply named fedora, debian, whonix-ws and whonix-gw instead of having their name+version when deployed?

There is very real benefit of having version in the template name: you can switch between them. This includes migrating to a newer template in parts, but also ability to go back _quickly_ to the previous one if something isn't compatible with the new one yet. This means for example you can migrate some of your VMs to a newer version, without disrupting some time-critical work you do in others.

The update experience is something we do need to work on, and updating templates to newer version is part of that task (including #3430).

**Comment by tlaurion** [comment] 2021-11-17 19:15
> Thanks for the report, I'll take a look. I assume it's Qubes 4.0, right

Right.

**Comment by andrewdavidwong** [comment] 2021-11-19 07:02
Possibly related: #7058

**Comment by andrewdavidwong** [comment] 2021-11-19 07:04
Wait, isn't this (now) a duplicate of #3574?

**Comment by ninavizz** [comment] 2021-11-19 07:54
This is from 2018 and the icons have changed entirely. 
The new app menu is also an entirely different beast, I believe. @marmarta correct me if I'm wrong?

I feel like this issue should be closed. Will defer to Marta.

**Closed** 2023-08-05 09:32 UTC
Labels: T: bug, C: desktop-linux, P: default, needs diagnosis, eol-4.0
