### ISSUE TITLE
Table of contents in FAQ for linking

### ISSUE THREAD

**Issue by anonaddict** [QubesOS/qubes-issues#7515] opened 2022-05-17 18:04 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Most pages have a table of contents so you can easily link to each subject or navigate the FAQ when looking at it for the first time so they are presented with 10-20 lines when looking a solution to their problem instead of having to skim an entire faq. The people helping will also have an easier time linking to a specific faq section

### The solution you'd like
Add a bigger table of contents

### The value to a user, and who that user might be
Both people helping newcomers on forums and people who look at the faq by theselves

**Comment by tzwcfq** [comment] 2022-05-17 18:48
>The people helping will also have an easier time linking to a specific faq section

It's already available, example:
https://i.ibb.co/CQQdGQ9/qubes-faq-link.png
https://www.qubes-os.org/faq/#how-does-qubes-os-provide-privacy

**Comment by andrewdavidwong** [comment] 2022-05-18 06:24
As @tzwcfq pointed out, every hearing already has an anchor link icon. You just have to hover your cursor over the heading to see it (or, on a mobile device, tap or long press). Since this issue is primarily about linking, does that resolve your concern?

Having a table of contents for the purpose of reading or skimming would be nice, and we used to have one, but it became too unwieldy to manually keep in sync with the contents, inconsistencies arose as people editing the FAQs while forgetting to update the table of contents, and so on. We figured the ability to use Ctrl+F on the whole page is good enough for searching, though we'd be open to some better solution. (I believe there's already an issue for this.)

**Comment by andrewdavidwong** [comment] 2022-05-18 06:28
Is this a duplicate of #7005?

**Comment by DemiMarie** [comment] 2022-05-18 19:48
> Is this a duplicate of #7005?

I think so, yes.

**Comment by andrewdavidwong** [comment] 2022-05-18 19:50
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2022-05-18 19:50 UTC
Labels: T: enhancement, help wanted, C: doc, P: default
