### ISSUE TITLE
Feature Request: Encrypted VMs

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4826] opened 2019-02-17 07:04 UTC
### Qubes OS version:
R 4.0

### Affected component(s):

Workstation VMs (all)

---

### Steps to reproduce the behavior:

Create a VM.  Open another VM that you have to keep running for hours.  Walk away from your computer.  Some evil maid steals everything.

### Expected behavior:

It would be useful for this case if individual VMs could be encrypted

### Actual behavior:

An evil maid could open every one of your VMs even though you only need one to be in use.

### General notes:

Feature Request not a bug.

---

**Comment by t4777sd** [comment] 2019-02-17 15:29
Looks like a duplicate of #1293

**Comment by andrewdavidwong** [comment] 2019-02-17 19:58
Duplicate of #1293

**Comment by andrewdavidwong** [comment] 2019-02-17 19:58
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-02-17 19:58 UTC

**Comment by straussmaus** [comment] 2019-02-19 13:47
I agree.  I am sorry I did not notice that.  Different search terms probably.

**Comment by straussmaus** [comment] 2020-01-12 10:03
@andrewdavidwong I read https://github.com/QubesOS/qubes-issues/issues/5249 https://github.com/QubesOS/qubes-issues/issues/904 and https://www.qubes-os.org/attachment/wiki/QubesArchitecture/arch-spec-0.3.pdf again.

I won't say I understood the PDF but I tried.

I think this Feature Request is different.

The problem I see is that you can not have an unimportant Qube running (downloading a large file for example) and also leave the house because to access the unimportant Qube you have to decrypt the disk.  But decrypting the disk means all Qubes are unencrypted.

Putting files in the Qube in an encrypted container does not solve the problem exactly because VeraCrypt for example requires 2x the disk capacity (I think?)

So I think this is a good feature request but @marmarek might disagree?  I am really trying to understand but I might not understand yet.

**Comment by andrewdavidwong** [comment] 2020-01-13 10:57
> @andrewdavidwong I read #5249 #904 and https://www.qubes-os.org/attachment/wiki/QubesArchitecture/arch-spec-0.3.pdf again.
> 
> I won't say I understood the PDF but I tried.
> 
> I think this Feature Request is different.
> 
> The problem I see is that you can not have an unimportant Qube running (downloading a large file for example) and also leave the house because to access the unimportant Qube you have to decrypt the disk. But decrypting the disk means all Qubes are unencrypted.
> 
> Putting files in the Qube in an encrypted container does not solve the problem exactly because VeraCrypt for example requires 2x the disk capacity (I think?)
> 
> So I think this is a good feature request but @marmarek might disagree? I am really trying to understand but I might not understand yet.

As far as I can tell, these reasons do not suggest that this is not a duplicate of #1293.

**Comment by straussmaus** [comment] 2020-01-14 06:37
@andrewdavidwong 

#1293 says "that anyone compromising dom0 or getting past full disk encryption can potentially read things that were in application memory of any VM at any point in past time"

But this issue is not about anything in application memory of any VM.  It is about the VM file itself being encrypted.  There is no similarity between these two issues that I see.  What do you see that I don't see?

**Comment by andrewdavidwong** [comment] 2020-01-15 11:01
> @andrewdavidwong
> 
> #1293 says "that anyone compromising dom0 or getting past full disk encryption can potentially read things that were in application memory of any VM at any point in past time"
> 
> But this issue is not about anything in application memory of any VM. It is about the VM file itself being encrypted. There is no similarity between these two issues that I see. What do you see that I don't see?

#1293 is also about the VM file itself being encrypted.
