### ISSUE TITLE
Reeboot hangs qubes 4.1

### ISSUE THREAD

**Issue by Trunk77** [QubesOS/qubes-issues#6872] opened 2021-09-03 15:51 UTC
Machine hangs on blank screen and does not shut down after clicking restart.

**Comment by DemiMarie** [comment] 2021-09-03 17:14
I have the same problem rarely.

**Comment by Trunk77** [comment] 2021-09-03 17:20
I hope they decide to fix it.
This is a basic function that any os should handle without problems. Thank
you Demi for responding.
Dean

**Comment by brendanhoar** [comment] 2021-09-03 17:31
I've become accustomed (under 4.0) to manually completing shut down all VMs before initiating a dom0 shutdown or dom0 restart due to hangs on dom0 shutdown a few years ago.

Is this similar or a different issue?

B

**Comment by Trunk77** [comment] 2021-09-03 17:43
Brendan, it may be the same. I'll have to try manual vm shutdowns and then
do a restart. If it works, i'll report back. I do think it's the same issue
which has been going on for a couple of years.
Dean

**Comment by ivpn786** [comment] 2021-09-03 17:53
Was any VM in Emergency pause while you tried reboot? I have seen this only in that situation. Might be different bug..

**Comment by Trunk77** [comment] 2021-09-03 18:04
I don't know if any vm(vms) were in emergency pause. I can tell you this
issue has been going on for years and multiple complaints have been sent to
the Qubes team over the years from users with various computer models and
hardware which is qubes compatible.
Dean

**Comment by DemiMarie** [comment] 2021-09-03 18:48
@marmarek any idea what would cause this?

**Comment by andrewdavidwong** [comment] 2021-09-03 21:12
Is this a duplicate/regression of #1581?

**Comment by marmarek** [comment] 2021-09-03 21:47
I'd rather think it's a duplicate of https://github.com/QubesOS/qubes-issues/issues/6258

**Comment by andrewdavidwong** [comment] 2021-09-03 22:08
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-09-03 22:08 UTC
Labels: T: bug, C: other, P: major, needs diagnosis

**Comment by Trunk77** [comment] 2021-09-03 22:37
Andrew
I don't understand why you closed this issue of reboot failures. It hasn't been corrected by the Qubes Dev Team. It is an existing issue that has never been fixed. Why close it. It needs to be fixed

**Comment by Trunk77** [comment] 2021-09-03 22:41
Why did you close this issue when it hasn't been fixed yet?
Dean

**Comment by andrewdavidwong** [comment] 2021-09-03 23:05
@Trunk77: 
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by Trunk77** [comment] 2021-09-04 03:36
I'm commenting on an already existing issue which was never resolved by the
Qubes team. This issue should never have been closed. After the problem is
corrected, close the issue, but not untill the team fixes this
important issue.
Dean

**Comment by andrewdavidwong** [comment] 2021-09-04 04:21
> I'm commenting on an already existing issue which was never resolved by the
> Qubes team. This issue should never have been closed. After the problem is
> corrected, close the issue, but not untill the team fixes this
> important issue.
> Dean
> 

This issue, which you opened ~12h ago, is a duplicate of #6258. We don't keep duplicate issues open. 
Please see our issue tracking guidelines for more information:

https://www.qubes-os.org/doc/issue-tracking/
