### ISSUE TITLE
Enhancement: battery charging thresholds on thinkpads

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3851] opened 2018-04-24 10:04 UTC
### Qubes OS version:

up to 4.0

### Enhancement

**Rationale**: When properly set, battery charging thresholds can significantly extend battery life. Unfortunately Qubes OS doesn't ship the [acpi_call](https://github.com/mkottman/acpi_call) kernel module required to use such feature on Thinkpads, which are popular laptops amongst qubes users. People who want to use that functionality have to boot a customized live distro (eg. Fedora on USB with persistent storage with the required kernel module + user space scripts) in order to set the thresholds. That's cumbersome and not secure.

**Proposal**: include the acpi_call module in dom0's kernel (maybe shipped by default or as a rpm add-on). On other distros [TLP](http://linrunner.de/en/tlp/tlp.html) is usually used to set thresholds from user-space but it should be easy to extract the threshold functionality from TLP's bash scripts (I could do that if this enhancement is accepted). I don't think including and using the module would increase dom0's attack surface, but I'm not a security expert. For info the acpi_call module is only 332 sloc.

**Related hardware**: Thinkpads with Sandy Bridge and newer models (X220/T420, X230/T430 et al.)

edit: I [posted](https://groups.google.com/d/msg/qubes-devel/axzZz-ut0LI/4nixsjfxCwAJ) this idea some time ago on qubes-devel but didn't get a reply except a +1 from another user

**Comment by rustybird** [comment] 2018-04-25 11:57
[ectool](https://www.coreboot.org/Ectool) from the coreboot project could be an alternative, it talks directly to the embedded controller and doesn't need any kernel patch. Theoretically, this should work for stock BIOS too?

You have to look up the right command line arguments for your notebook model, e.g. [for an x230](https://www.coreboot.org/Board:lenovo/x230#Setting_battery_threshold_on_a_X230_with_coreboot).

**Comment by taradiddles** [comment] 2018-04-25 12:51
I didn't know about ectool - just compiled it, it seems to work. Thanks **a lot** !

I'll play with it a bit more and I'll write a doc in the [Qubes-Community](https://github.com/Qubes-Community) project since it's not really specific to Qubes.

Closing the issue then ...

**Comment by jharveyb** [comment] 2018-05-25 10:27
@taradiddles Which machine did it work on for you? I have a T460 here & the X230 positions have no effect - could not find documentation for the correct locations in EC RAM. tp_smapi also doesn't support T430's and newer so curious as to your setup.

**Comment by taradiddles** [comment] 2018-05-25 19:09
I have a T450s with 2 batteries: an integrated one and a removable one.

Here's the output of `ectool` for the b0 to bc addresses


 ; the first four values are the battery charing thresholds for the 2 batteries:
-

**Comment by jharveyb** [comment] 2018-05-26 01:27
Those same addresses seem to work for me!

I only had b0 & b1 written before, started testing with the internal battery above start threshold and AC attached; no charging, as expected.
After adding an external battery without writing to b2 or b3, it began charging. Writing the same thresholds to b2 & b3 and reintroducing AC didn't cause either battery to charge (though upower and the xfce-power-manager still thought they were).
Discharging the internal battery below its start threshold and reintroducing AC caused it to charge up to the stop threshold - tl;dr it works perfectly, thank you for the help!

**Comment by evilaliv3** [comment] 2019-03-16 13:22
I tried as well ectool and seems to work correctly on the T480.

In relation to the battry i just found out that my laptop is not anymore charging the internal battery. Do you have any idea if this could be a bug in qubes or an hardware problem in my lapopt and how to discern the two situations?

thank you!

**Comment by andrewdavidwong** [comment] 2019-03-16 17:42
> In relation to the battry i just found out that my laptop is not anymore charging the internal battery. Do you have any idea if this could be a bug in qubes or an hardware problem in my lapopt and how to discern the two situations?

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by lvid** [comment] 2019-05-27 09:28
I consider the ectool a hack and not a real solution to the issue. At least for me it's too complicated to use, and this is a deal breaker to me. I think this should be reopened.

**Comment by lvid** [comment] 2019-08-13 18:32
Will this be fixed already in 4.0.2? :3 Looking forward to installing Qubes again...

**Comment by randomshinichi** [comment] 2021-05-25 23:10
I'd like this to be resolved properly too with the acpi_call module

**Comment by DemiMarie** [comment] 2021-05-25 23:31
:+1: but the kernel module will need to be reviewed by @marmarek before it can ship.

**Comment by iamahuman** [comment] 2021-07-10 17:00
Linux kernel >= v4.19 (at least) has built-in control for charging thresholds (`/sys/class/power_supply/BAT0/charge_*_threshold`), which can be used either directly (by writing to the files) or indirectly (via TLP). These controls talk to the ACPI AML interpreter and thus are effectively equivalent to `acpi_call`. This should be much safer than fiddling with EC fields directly.

**Comment by andrewdavidwong** [comment] 2021-07-10 18:29
> Linux kernel >= v4.19 (at least) has built-in control for charging thresholds (`/sys/class/power_supply/BAT0/charge_*_threshold`) for some (most?) ThinkPad laptops, which can be used either directly (by writing to the files) or indirectly (via TLP). These controls talk to the ACPI AML interpreter (calls AML methods) and thus replaces `acpi_call` on this aspect. This should be much safer than fiddling with EC fields directly.
> 
> Since Qubes R4.0 ships with a kernel version recent enough, you can already set battery charge thresholds via the controls above. Unless the scope of the issue extends to user-friendly access to battery threshold controls, perhaps we can close this issue.

Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-07-10 18:29 UTC
Labels: C: kernel, P: default, T: enhancement, hardware support
