### ISSUE TITLE
Fedora-24-minimal: GUI integration (MRU entry tool) broken / missing dependencies

### ISSUE THREAD

**Issue by cfcs** [QubesOS/qubes-issues#2816] opened 2017-05-18 00:37 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-24-minimal
---

### Expected behavior:

The Nautilus and Thunderbird integration should pop up dialogs when you click the buttons (like "move to vm" and "open in disposable vm").

### Actual behavior:

 `/usr/bin/qvm-mru-entry` depends on the python `gtk` module, which is not installed in the template.

### Steps to reproduce the behavior:

1) Open Nautilus or Thunderbird, right-click on something and choose "Move to VM...".
2) Nothing happens.

### Proposed fix:

`dnf install python-gobject pycairo` in the `fedora-24-minimal` template.

**Comment by marmarek** [comment] 2017-05-18 08:02
This is somehow intentional to make the template minimal. But indeed it should be handled better - "Move to VM..." etc entries should not be added to menu at all. And documented. This depends on splitting core-agent-linux package: #2771

**Comment by cfcs** [comment] 2017-05-18 14:01
I take it the intention was to not have the GTK package, not to intentionally cripple the GUI helpers.

Either way I'd like to state for the record the current minimal Fedora 24 template takes up 1.6 GB when installed and updated, and the `download size` reported by dnf for `dnf install python-gobject` (which has `pycairo` as its only dependency) is `503 k`, with an `installed size` of `1.0M`, and that `root.img` increased in size by exactly `376 832 bytes` after installing this package.

But if extending the installed size of the template by 0.02% goes against this principle of minimality, I'm all for keeping it in a broken state for now, or removing the Nautilus integration - I mean the Qubes Nautilus plugins do take up a whopping `50 K` of precious disk space.

**Comment by marmarek** [comment] 2017-05-18 15:51
Intended fix is to remove Nautilus, together with its Qubes integration from minimal template. Which should be possible after implementing #2771

**Comment by andrewdavidwong** [comment] 2017-05-21 00:27
This is a duplicate of #2071 and/or #2566. For the discussion on how "minimal" `fedora-minimal` should be, see #2435.

**Closed by andrewdavidwong** 2017-05-21 00:27 UTC
