### ISSUE TITLE
Qubes 4.1 Building. error: Bad exit status from /var/tmp/rpm-tmp.sZTsgw

### ISSUE THREAD

**Issue by kulibinks** [QubesOS/qubes-issues#6883] opened 2021-09-09 12:39 UTC
**Qubes OS release**

Qubes 4.0.4

**Brief summary**

Trying to build 4.1 following this doc https://www.qubes-os.org/doc/qubes-iso-building . Have used ./setup script, also changed linux kernel to 5.13.5 by `edit qubes-src/linux-kernel/version` . First of all i faced same problem like here https://github.com/QubesOS/qubes-issues/issues/6522 Solved it, comment out `%_pkgverify_level all` in `/usr/lib/rpm/macros.d/macros.qubes`
So building proccess starts normal and when it's starts kernel compilation there is strange error: `error: Bad exit status from /var/tmp/rpm-tmp.sZTsgw`

![2 cleaned](https://user-images.githubusercontent.com/90392743/132685766-b03fea90-1632-4aec-b5c6-7984ef9d7c5f.jpg)

So I tried to check` /var/tmp`, screen below shows what it contain:

![1 cleaned](https://user-images.githubusercontent.com/90392743/132686050-f3ec38e6-244d-4bf9-9b50-b78b943c7356.jpg)

**Steps to reproduce**

1. Qubes 4.0.4 and fc32 as tempalte.
2. ./setup configuration:
```
Yes
Yes
4.1
Stable
Yes
Current
No
fc30 + xfce, buster, whonix-gateway-15, whonix-workstation-15
builder-rpm, builder-debian, template-whonix, mgmt-salt
Yes
OK
```
3. `make install-deps`
4. `edit qubes-src/linux-kernel/version`
5. `make get-sources`
6. `make qubes`

**Expected behavior**

Builder should be OK.

**Actual behavior**

`error: Bad exit status from /var/tmp/rpm-tmp.sZTsgw`

**Comment by marmarek** [comment] 2021-09-09 12:43
> changed linux kernel to 5.13.5 by `edit qubes-src/linux-kernel/version`

The build fails because one of the kernel patches needs to be adjusted to the new kernel version. In fact, this patch may be not needed anymore (the fix already included upstream)

**Comment by kulibinks** [comment] 2021-09-09 12:51
> > changed linux kernel to 5.13.5 by `edit qubes-src/linux-kernel/version`
> 
> The build fails because one of the kernel patches needs to be adjusted to the new kernel version. In fact, this patch may be not needed anymore (the fix already included upstream)

Hi! Thank you for reply! When this fix have been included? I try to build it 2 days ago. I'm newbie here, so i'm apologize for silly questions.

**Comment by marmarek** [comment] 2021-09-09 13:01
I see it included only in 5.14 kernel, not 5.13, so strictly speaking, the patch is still necessary. But, this particular bug is unlikely to affect you (it affects only PV domains, which are not used by default). For now you can simply comment out related "Patch" line in `kernel.spec.in` file.

**Comment by kulibinks** [comment] 2021-09-09 20:45
> I see it included only in 5.14 kernel, not 5.13, so strictly speaking, the patch is still necessary. But, this particular bug is unlikely to affect you (it affects only PV domains, which are not used by default). For now you can simply comment out related "Patch" line in `kernel.spec.in` file.

So decide start from begining and make same steps, choose 5.13.5 like berfore, but after `edit qubes-src/linux-kernel/version` and `make get-sources` i get this strange thing, this is a first time:
![3 cleaned](https://user-images.githubusercontent.com/90392743/132759982-bd5ff94e-3d99-4afb-a4bf-51fde883e387.jpg)

Maybe you have any ideas? Thank you

**Comment by marmarek** [comment] 2021-09-10 11:14
Broken download? Remove the tarball from `qubes-src/vmm-xen-stubdom-linux/dl/` and try again

**Comment by kulibinks** [comment] 2021-09-10 20:22
> Broken download? Remove the tarball from `qubes-src/vmm-xen-stubdom-linux/dl/` and try again

Nothing help. Decided start from begining again. This time, i was did standart configuration from here https://www.qubes-os.org/doc/qubes-iso-building . Used kernel that already written in `qubes-os-master.conf ` and faced with new error at `make get-sources`
![4 cleaned](https://user-images.githubusercontent.com/90392743/132913255-1e8d9cce-19a4-4e77-900c-acc10e16e0f9.jpg)

**Comment by andrewdavidwong** [comment] 2021-09-10 21:02
> > Broken download? Remove the tarball from `qubes-src/vmm-xen-stubdom-linux/dl/` and try again
> 
> 
> 
> Nothing help. Decided start from begining again. This time, i was did standart configuration from here https://www.qubes-os.org/doc/qubes-iso-building . Used kernel that already written in `qubes-os-master.conf ` and faced with new error at `make get-sources`
> 
> ![4 cleaned](https://user-images.githubusercontent.com/90392743/132913255-1e8d9cce-19a4-4e77-900c-acc10e16e0f9.jpg)
> 
> 

Since this is a new error, please open a new issue for it.


Closing this issue as "cannot reproduce" (we were unable to reproduce this issue). If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed** 2021-09-10 21:02 UTC
Labels: T: bug, C: builder, P: default, diagnosed

**Comment by andrewdavidwong** [comment] 2021-09-10 21:05
Actually, it looks like the original bug reported might have been resolved all the way back in https://github.com/QubesOS/qubes-issues/issues/6890, so perhaps it's not a "cannot reproduce." Removing that label.

**Comment by andrewdavidwong** [comment] 2021-09-10 21:09
I think part of the confusion in this issue is the result of treating it like a support ticket (tacking on each subsequent problem encountered). Please remember that [qubes-issues is not a support system,](https://www.qubes-os.org/doc/issue-tracking/) and 
[every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing)
