### ISSUE TITLE
PCI device initalization fails with "address conflict with Unusable memory"

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#6042] opened 2020-09-10 15:05 UTC
**Qubes OS version**
R4.0 running on a T430s with Heads installed.

**Affected component(s) or functionality**
USB/SD-Card reader PCI devices connected to a ~~HVM or~~ PV VM won't be initialized.  (HVM (Ubuntu18.04) works again for whatever reason)

**Brief summary**
The PCI devices won't be initialized on boot of the VM. This doesn't happen for network related devices.
`dmesg` gives the following error messages:

> [    7.733362] pcifront pci-0: claiming resource 0000:00:00.0/0
> [    7.733382] pci 0000:00:00.0: can't claim BAR 0 [mem 0xe1940000-0xe19403ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
> [    7.733399] pcifront pci-0: Could not claim resource 0000:00:00.0/0! Device offline. Try using e820_host=1 in the guest config.

<details>
<summary>full PCI init logs in sys-usb fedora-32 template</summary>

```
[    7.389504] pcifront pci-0: Installing PCI frontend
[    7.389827] pcifront pci-0: Creating PCI Frontend Bus 0000:00
[    7.389870] pcifront pci-0: PCI host bridge to bus 0000:00
[    7.389880] pci_bus 0000:00: root bus resource [io  0x0000-0xffff]
[    7.389890] pci_bus 0000:00: root bus resource [mem 0x00000000-0xfffffffff]
[    7.389900] pci_bus 0000:00: root bus resource [bus 00-ff]
[    7.390176] pci 0000:00:00.0: [8086:1e26] type 00 class 0x0c0320
[    7.391151] pci 0000:00:00.0: reg 0x10: [mem 0xe1940000-0xe19403ff]
[    7.404215] pci 0000:00:01.0: [8086:1e2d] type 00 class 0x0c0320
[    7.412220] pci 0000:00:01.0: reg 0x10: [mem 0xe193f000-0xe193f3ff]
[    7.442381] pci 0000:00:02.0: [8086:1e31] type 00 class 0x0c0330
[    7.444905] pci 0000:00:02.0: reg 0x10: [mem 0xe1920000-0xe192ffff 64bit]
[    7.488779] pci 0000:00:03.0: [1180:e823] type 00 class 0x080500
[    7.490803] pci 0000:00:03.0: MMC controller base frequency changed to 50Mhz.
[    7.504179] pci 0000:00:03.0: reg 0x10: [mem 0xe0800000-0xe08000ff]
[    7.607283] pci 0000:00:03.0: supports D1 D2
[    7.733362] pcifront pci-0: claiming resource 0000:00:00.0/0
[    7.733382] pci 0000:00:00.0: can't claim BAR 0 [mem 0xe1940000-0xe19403ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    7.733399] pcifront pci-0: Could not claim resource 0000:00:00.0/0! Device offline. Try using e820_host=1 in the guest config.
[    7.733414] pcifront pci-0: claiming resource 0000:00:01.0/0
[    7.733966] pci 0000:00:01.0: can't claim BAR 0 [mem 0xe193f000-0xe193f3ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    7.733983] pcifront pci-0: Could not claim resource 0000:00:01.0/0! Device offline. Try using e820_host=1 in the guest config.
[    7.733998] pcifront pci-0: claiming resource 0000:00:02.0/0
[    7.734007] pci 0000:00:02.0: can't claim BAR 0 [mem 0xe1920000-0xe192ffff 64bit]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    7.734024] pcifront pci-0: Could not claim resource 0000:00:02.0/0! Device offline. Try using e820_host=1 in the guest config.
[    7.734038] pcifront pci-0: claiming resource 0000:00:03.0/0
[    7.734048] pci 0000:00:03.0: can't claim BAR 0 [mem 0xe0800000-0xe08000ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    7.734066] pcifront pci-0: Could not claim resource 0000:00:03.0/0! Device offline. Try using e820_host=1 in the guest config.
[    7.734563] pci 0000:00:00.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    7.734579] pci 0000:00:00.0: Can't enable PCI device, BIOS handoff failed.
[    7.734700] pci 0000:00:01.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    7.734712] pci 0000:00:01.0: Can't enable PCI device, BIOS handoff failed.
[    7.734902] pci 0000:00:02.0: can't enable device: BAR 0 [mem size 0x00010000 64bit] not assigned
[    7.734915] pci 0000:00:02.0: Can't enable PCI device, BIOS handoff failed.
[    7.818602] intel_rapl: Found RAPL domain package
[    7.818619] intel_rapl: Found RAPL domain core
[    7.818630] intel_rapl: Found RAPL domain uncore
[    8.014189] Adding 1048572k swap on /dev/xvdc1.  Priority:-2 extents:1 across:1048572k SSFS
[    8.033118] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    8.069643] ehci-pci: EHCI PCI platform driver
[    8.072410] ehci-pci 0000:00:00.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    8.091252] ehci-pci 0000:00:01.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    8.105949] sdhci: Secure Digital Host Controller Interface driver
[    8.105967] sdhci: Copyright(c) Pierre Ossman
[    8.117143] xhci_hcd 0000:00:02.0: can't enable device: BAR 0 [mem size 0x00010000 64bit] not assigned
[    8.154384] sdhci-pci 0000:00:03.0: SDHCI controller found [1180:e823] (rev 7)
[    8.155430] sdhci-pci 0000:00:03.0: can't enable device: BAR 0 [mem size 0x00000100] not assigned
[    8.158197] sdhci-pci: probe of 0000:00:03.0 failed with error -22
```
</details>

<details>
<summary>full PCI init logs in sys-usb debian-10 template</summary>

```
[    2.763782] Invalid max_queues (4), will use default max: 2.
[    3.275529] blkfront: xvda: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    3.287251]  xvda: xvda1 xvda2 xvda3
[    3.337542] blkfront: xvdb: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    3.363564] blkfront: xvdc: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    3.370664] blkfront: xvdd: flush diskcache: enabled; persistent grants: enabled; indirect descriptors: enabled;
[    3.462954]  xvdc: xvdc1 xvdc3
[    3.569425] EXT4-fs (xvda3): mounted filesystem with ordered data mode. Opts: (null)
[    3.606074] EXT4-fs (xvdd): mounting ext3 file system using the ext4 subsystem
[    3.611964] EXT4-fs (xvdd): mounted filesystem with ordered data mode. Opts: (null)
[    3.787572] EXT4-fs (xvda3): re-mounted. Opts: (null)
[    4.091806] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    4.091971] systemd[1]: Detected virtualization xen.
[    4.092034] systemd[1]: Detected architecture x86-64.
[    4.100480] systemd[1]: No hostname configured.
[    4.100507] systemd[1]: Set hostname to <localhost>.
[    4.699352] systemd[1]: /lib/systemd/system/qubes-meminfo-writer.service:7: PIDFile= references path below legacy directory /var/run/, updating /var/run/meminfo-writer.pid → /run/meminfo-writer.pid; please update the unit file accordingly.
[    4.706237] systemd[1]: /etc/systemd/system/haveged.service:1: .include directives are deprecated, and support for them will be removed in a future version of systemd. Please use drop-in files instead.
[    4.729856] systemd[1]: Listening on udev Control Socket.
[    4.730575] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    4.730885] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    5.092886] lp: driver loaded but no devices found
[    5.131616] ppdev: user-space parallel port driver
[    5.135265] parport_pc parport_pc.956: Unable to set coherent dma mask: disabling DMA
[    5.135364] parport_pc parport_pc.888: Unable to set coherent dma mask: disabling DMA
[    5.135448] parport_pc parport_pc.632: Unable to set coherent dma mask: disabling DMA
[    5.154587] xen:xen_evtchn: Event-channel device installed
[    5.173816] u2mfn: loading out-of-tree module taints kernel.
[    5.191985] EXT4-fs (xvda3): re-mounted. Opts: discard
[    5.241015] systemd-journald[219]: Received request to flush runtime journal from PID 1
[    6.058618] RAPL PMU: API unit is 2^-32 Joules, 3 fixed counters, 163840 ms ovfl timer
[    6.058635] RAPL PMU: hw unit of domain pp0-core 2^-16 Joules
[    6.058644] RAPL PMU: hw unit of domain package 2^-16 Joules
[    6.058653] RAPL PMU: hw unit of domain pp1-gpu 2^-16 Joules
[    6.092623] input: PC Speaker as /devices/platform/pcspkr/input/input0
[    6.094055] pcifront pci-0: Installing PCI frontend
[    6.097032] pcifront pci-0: Creating PCI Frontend Bus 0000:00
[    6.097079] pcifront pci-0: PCI host bridge to bus 0000:00
[    6.097090] pci_bus 0000:00: root bus resource [io  0x0000-0xffff]
[    6.097100] pci_bus 0000:00: root bus resource [mem 0x00000000-0xfffffffff]
[    6.097111] pci_bus 0000:00: root bus resource [bus 00-ff]
[    6.097853] pci 0000:00:00.0: [8086:1e26] type 00 class 0x0c0320
[    6.099855] pci 0000:00:00.0: reg 0x10: [mem 0xe1940000-0xe19403ff]
[    6.107316] pci 0000:00:01.0: [8086:1e2d] type 00 class 0x0c0320
[    6.109673] pci 0000:00:01.0: reg 0x10: [mem 0xe193f000-0xe193f3ff]
[    6.117583] pci 0000:00:02.0: [8086:1e31] type 00 class 0x0c0330
[    6.118377] pci 0000:00:02.0: reg 0x10: [mem 0xe1920000-0xe192ffff 64bit]
[    6.128488] pci 0000:00:03.0: [1180:e823] type 00 class 0x080500
[    6.130648] pci 0000:00:03.0: MMC controller base frequency changed to 50Mhz.
[    6.134226] pci 0000:00:03.0: reg 0x10: [mem 0xe0800000-0xe08000ff]
[    6.155629] pci 0000:00:03.0: supports D1 D2
[    6.166411] pcifront pci-0: claiming resource 0000:00:00.0/0
[    6.166429] pci 0000:00:00.0: can't claim BAR 0 [mem 0xe1940000-0xe19403ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    6.166447] pcifront pci-0: Could not claim resource 0000:00:00.0/0! Device offline. Try using e820_host=1 in the guest config.
[    6.166463] pcifront pci-0: claiming resource 0000:00:01.0/0
[    6.166474] pci 0000:00:01.0: can't claim BAR 0 [mem 0xe193f000-0xe193f3ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    6.166491] pcifront pci-0: Could not claim resource 0000:00:01.0/0! Device offline. Try using e820_host=1 in the guest config.
[    6.166507] pcifront pci-0: claiming resource 0000:00:02.0/0
[    6.166518] pci 0000:00:02.0: can't claim BAR 0 [mem 0xe1920000-0xe192ffff 64bit]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    6.166536] pcifront pci-0: Could not claim resource 0000:00:02.0/0! Device offline. Try using e820_host=1 in the guest config.
[    6.166552] pcifront pci-0: claiming resource 0000:00:03.0/0
[    6.166562] pci 0000:00:03.0: can't claim BAR 0 [mem 0xe0800000-0xe08000ff]: address conflict with Unusable memory [mem 0x25800000-0xfebfffff]
[    6.166578] pcifront pci-0: Could not claim resource 0000:00:03.0/0! Device offline. Try using e820_host=1 in the guest config.
[    6.166742] pci 0000:00:00.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    6.166755] pci 0000:00:00.0: Can't enable PCI device, BIOS handoff failed.
[    6.166985] pci 0000:00:01.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    6.166996] pci 0000:00:01.0: Can't enable PCI device, BIOS handoff failed.
[    6.167163] pci 0000:00:02.0: can't enable device: BAR 0 [mem size 0x00010000 64bit] not assigned
[    6.167176] pci 0000:00:02.0: Can't enable PCI device, BIOS handoff failed.
[    6.241710] EXT4-fs (xvdb): mounted filesystem with ordered data mode. Opts: discard
[    6.324411] Error: Driver 'pcspkr' is already registered, aborting...
[    6.654888] intel_rapl: Found RAPL domain package
[    6.654905] intel_rapl: Found RAPL domain core
[    6.654915] intel_rapl: Found RAPL domain uncore
[    6.805703] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    6.810150] ehci-pci: EHCI PCI platform driver
[    6.813197] ehci-pci 0000:00:00.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    6.816790] ehci-pci 0000:00:01.0: can't enable device: BAR 0 [mem size 0x00000400] not assigned
[    6.843596] sdhci: Secure Digital Host Controller Interface driver
[    6.843613] sdhci: Copyright(c) Pierre Ossman
[    6.848262] xhci_hcd 0000:00:02.0: can't enable device: BAR 0 [mem size 0x00010000 64bit] not assigned
[    6.852411] sdhci-pci 0000:00:03.0: SDHCI controller found [1180:e823] (rev 7)
[    6.856529] sdhci-pci 0000:00:03.0: can't enable device: BAR 0 [mem size 0x00000100] not assigned
[    6.856710] sdhci-pci: probe of 0000:00:03.0 failed with error -22
[    6.966319] Adding 1048572k swap on /dev/xvdc1.  Priority:-2 extents:1 across:1048572k SSFS
[    9.702919] loop: module loaded
[    9.720993] squashfs: version 4.0 (2009/01/31) Phillip Lougher

```

</details>

**Additional context**
- It doesn't matter which template is used for sys-usb. Fedora 32 and Debian 10 are both affected.
- I can't point at the specific update in fedora-32 and debian-10. I _think_ it still worked roughly 1-2 week ago (I rarely use sys-usb).
- It is not a bootloader issue. Heads recognizes the devices.

**Solutions you've tried**
A similarissue was described [here](https://www.linuxquestions.org/questions/linux-kernel-70/kernel-fails-to-assign-memory-to-pcie-device-4175487043/). They tried this (fedora template): 

```
# echo 1 > /sys/bus/pci/devices/0000\:00\:00.0/remove
# echo 1 > /sys/bus/pci/devices/0000\:00\:01.0/remove
# echo 1 > /sys/bus/pci/devices/0000\:00\:02.0/remove
# echo 1 > /sys/bus/pci/devices/0000\:00\:03.0/remove
# echo 1 > /sys/bus/pci/rescan
```

Doing this lets sys-usb freezes for 1min and finally it crashes. 
I do not know much about analyzing kernel panics. Any suggestions how to analyze this bug further?

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
- https://github.com/QubesOS/qubes-issues/issues/2019
- https://www.linuxquestions.org/questions/linux-kernel-70/kernel-fails-to-assign-memory-to-pcie-device-4175487043/

**Comment by Rot127** [comment] 2020-09-21 09:45
Reinstalling sys-usb fixes the problem. May be we can close this issue?
Reinstall sys-usb via:

```bash
sudo qvm-remove sys-usb
sudo qubesctl state.sls qvm.sys-usb
```

**Comment by andrewdavidwong** [comment] 2020-09-21 17:58
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-09-21 17:58 UTC
Labels: C: other, P: default, T: bug, hardware support, needs-diagnosis
