### ISSUE TITLE
qubes-manager errors out when enabling "checking for updates for all qubes"

### ISSUE THREAD

**Issue by lunarthegrey** [QubesOS/qubes-issues#4425] opened 2018-10-23 14:29 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-manager

---

### Steps to reproduce the behavior:

Open Qubes Manager -> Global Settings -> Click "Enable checking for updates for all qubes" -> Click "OK"

### Expected behavior:

Update checking is enabled with no errors.

### Actual behavior:

I get an error after pressing "OK". Pasting it below.

```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

AttributeError: 'NoneType' object has no attribute 'qid'
at line 1337
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

----
line: self.vms_in_table[vm.qid].update()
func: on_domain_changed
line no.: 476
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: handler(subject, event, **kwargs)
func: handle
line no.: 220
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: self.handle(subject, event, **kwargs)
func: _listen_for_events
line no.: 186
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: yield from self._listen_for_events(vm)
func: listen_for_events
line no.: 126
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: result = coro.send(None)
func: _step
line no.: 240
file: /usr/lib64/python3.5/asyncio/tasks.py
----
line: raise self._exception
func: result
line no.: 294
file: /usr/lib64/python3.5/asyncio/futures.py
----
line: return future.result()
func: run_until_complete
line no.: 289
file: /usr/lib/python3.5/site-packages/quamash/__init__.py
----
line: asyncio.ensure_future(dispatcher.listen_for_events()))
func: main
line no.: 1337
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

### General notes:

My Qubes OS is fully patched with the latest stable updates (ones pushed yesterday and a few days ago).

---

### Related issues:

Unknown, please reference if you find anything. I wasn't able to find a similar issue with Googling.

**Comment by lunarthegrey** [comment] 2018-10-23 14:29
Tagging @marmarta for review.

**Comment by marmarek** [comment] 2018-10-23 14:35
This is exact duplicate of  #4317, which is already fixed in testing repository.

**Closed by marmarek** 2018-10-23 14:35 UTC

**Comment by lunarthegrey** [comment] 2018-10-23 14:41
I see. Thank you. Google didn't serve me well today.

**Comment by lunarthegrey** [comment] 2018-10-23 14:49
@marmarek I upgraded to `qubes-manager-4.0.22-1.fc25` and I'm presented with another error when following the same steps in my original issue.

```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

AttributeError: 'NoneType' object has no attribute 'qid'
at line 1343
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

----
line: self.vms_in_table[vm.qid].update()
func: on_domain_changed
line no.: 480
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: handler(subject, event, **kwargs)
func: handle
line no.: 220
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: self.handle(subject, event, **kwargs)
func: _listen_for_events
line no.: 186
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: yield from self._listen_for_events(vm)
func: listen_for_events
line no.: 126
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: result = coro.send(None)
func: _step
line no.: 240
file: /usr/lib64/python3.5/asyncio/tasks.py
----
line: raise self._exception
func: result
line no.: 294
file: /usr/lib64/python3.5/asyncio/futures.py
----
line: return future.result()
func: run_until_complete
line no.: 289
file: /usr/lib/python3.5/site-packages/quamash/__init__.py
----
line: asyncio.ensure_future(dispatcher.listen_for_events()))
func: main
line no.: 1343
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

**Comment by marmarek** [comment] 2018-10-23 15:48
#4385 ?
