### ISSUE TITLE
Fedora packaging bug: general file manager packages provided by *-nautilus

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#6612] opened 2021-05-16 06:57 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Copy and move in Dolphin in KDE-based templates without `nautilus` and `qubes-core-agent-nautilus`. At least it's true for fedora-based templates.

**Brief summary**
There is no proper way to have Copy-Move functions in Dolphin without installing `nautilus`.
In KDE-based templates the package `qubes-core-agent-nautilus` installs `nautilus` with it's dependencies and a lot of related problems (e.g. affecting a lot of file mime connections).
Without it `Dolphin` has no ability to secure copy/move files to other VMs.

**How Reproducible**
Always.

**To Reproduce**
1. Create new template from fedora-33 minimal.
2. Install filemanager `Dolphin` and any Qubes OS related stuff. DO NOT install filemanager `nautilus` or any packages that install it as dependencies.
3. Copy To VM and Send To VM are available in service menu of `Dolphin`.

**Expected behavior**
Copy To VM and Move To VM commands work in Dolphin in AppVM based on KDE-based template.

**Actual behavior**
Copy To VM and Move To VM commands does not work in Dolphin in AppVM based on KDE-based template.

**Additional context**
Installing and ignoring `Nautilus` is not an option, because it is not only redundant when you have `Dolphin` or other proper file manager but also brings a lot of useless stuff, dependencies and problems, e.g. makes a lot of mime-connections with itself, e.g. for directories (folders), archives and etc. So, it's not possible to install `Nautilus` and ignore it, nor it's a good approach.

Installing `qubes-core-agent-nautilus` with --nodeps is not a proper option too, because during Qubes OS updates the template would get Nautilus and all the related problems.

Also, please change "**Send To**" to "**Copy To**". Obviously, it was a bad decision to make Send/Move commands instead of Copy/Move. Send can mean move (like physical send of the letters) but means copy in Qubes OS.
Send = dubious naming for Copy command.

**Solutions you've tried**
I'm using this workaround:

In AppVM based on KDE-based template:
`dnf download qubes-core-agent-nautilus`
Then manually copy script and symlink to /usr/lib/qubes from the downloaded `qubes-core-agent-nautilus` archive.
Drawback: this copy/move script in /usr/lib/qubes will not be updated during template updates. So the workaround is not perfect.

I would offer to extract functionality of copy/move scripts from qubes-core-agent-nautilus and store as qubes-core-agent-filewrapper package or something, so KDE people could live without `Nautilus` and it's problems.

**Comment by unman** [comment] 2021-05-16 11:01
Cant reproduce this in a Debian template, so (subject to confirmation)
it is Fedora specific.
Please update title.

**Comment by jamke** [comment] 2021-05-16 16:15
@unman 
I'm not using Debian templates as Fedora is the main and primary distribution for Qubes OS.
Do you have `/usr/lib/qubes/qvm-copy-to-vm.gnome` script and `/usr/lib/qubes/qvm-copy-to-vm.kde` symlink? Probably yes, then do you know where did this `qvm-copy-to-vm.gnome came from` - which package and what are dependencies of this package? It can help to find out if Debian is affected.

-----------------

My another solution will be to move these scripts/symlinks:
`/usr/lib/qubes/qvm-copy-to-vm.gnome`
`/usr/lib/qubes/qvm-copy-to-vm.kde`
`/usr/lib/qubes/qvm-move-to-vm.gnome`
`/usr/lib/qubes/qvm-move-to-vm.kde`

from `qubes-core-agent-nautilus` to a new package `qubes-core-agent-filecoping` without `nautilus` or any other gtk/gnome dependencies.
Because this scripts are needed to use copy and move files in `Dolphin`.

**Comment by unman** [comment] 2021-05-16 17:07
I've just told you that Debian is *not* affected.
The commands work in Debian without nautilus being installed. (There's a
separate issue re zenity but that's to be expected when using minimal
templates - that's why they carry a health warning)
In Debian the qvm-copy-to-vm.gnome script is provided by
qubes-core-agent.

imo this is covered by the standard warning about using minimal
templates. They are for advanced users.
The issue wont arise on a standard template.

In this case all you have to do is:
`dnf download qubes-core-agent-nautilus`
`rpm --nodeps -i qubes-core-agent-nautilus...`

You would probably want to block the package from being upgraded without
warning, or block nautilus, and the rest, from being installed.

**Comment by herypt** [comment] 2021-05-16 17:15
The issue is that qvm-copy-to-vm.kde, which gets installed by qubes-core-agent, is just a symlink to qvm-copy-to-vm.gnome, which gets installed by qubes-core-agent-nautilus in Fedora templates. qvm-copy-to-vm.gnome should be moved to the qubes-core-agent package, which is already the case in Debian, or qvm-copy-to-vm.kde should become an actual file instead of a symlink to fix this issue.

**Comment by DemiMarie** [comment] 2021-05-16 18:42
> imo this is covered by the standard warning about using minimal templates. They are for advanced users. The issue wont arise on a standard template. In this case all you have to do is: `dnf download qubes-core-agent-nautilus` `rpm --nodeps -i qubes-core-agent-nautilus...`

This is still a bug in Qubes OS.  @herypt patch coming.

**Comment by herypt** [comment] 2021-05-16 18:44
@DemiMarie This will actually already get fixed by https://github.com/QubesOS/qubes-core-agent-linux/pull/307

**Comment by jamke** [comment] 2021-05-17 09:00
Thanks guys. I hope the hack with `dnf download` will be redundant soon.

As you know this topic - is there a ticket to change menu text of service for Dolphin from "Send to VM" to "Copy to VM"? 
Or should I create one?
Because Send - means you move something (sending letter). So having Send and Move is very mind-blowing. I had to modify it in my templates manually to change things like that.

**Comment by andrewdavidwong** [comment] 2021-05-17 12:17
> As you know this topic - is there a ticket to change menu text of service for Dolphin from "Send to VM" to "Copy to VM"? 
> 
> Or should I create one?
> 

Pretty sure there's already an issue for that. Sounds familiar.

**Comment by unman** [comment] 2021-05-17 13:26
On Mon, May 17, 2021 at 05:17:22AM -0700, Andrew David Wong wrote:
> 
> > As you know this topic - is there a ticket to change menu text of service for Dolphin from "Send to VM" to "Copy to VM"? 
> > 
> > Or should I create one?
> > 
> 
> Pretty sure there's already an issue for that. Sounds familiar.
> 

It's #1040 - the language unified the wrong way, and has never been
corrected.

**Comment by unman** [comment] 2021-05-17 14:04
On Mon, May 17, 2021 at 02:26:27PM +0100, unman wrote:
> On Mon, May 17, 2021 at 05:17:22AM -0700, Andrew David Wong wrote:
> > 
> > > As you know this topic - is there a ticket to change menu text of service for Dolphin from "Send to VM" to "Copy to VM"? 
> > > 
> > > Or should I create one?
> > > 
> > 
> > Pretty sure there's already an issue for that. Sounds familiar.
> > 
> 
> It's #1040 - the language unified the wrong way, and has never been
> corrected.

I've put in PR.
I haven't addressed the order of items raised in that issue - I don't know
if this differs between file managers or if this is a problem?
@andrewdavidwong @ninavizz ??

**Comment by andrewdavidwong** [comment] 2021-05-17 14:34
> On Mon, May 17, 2021 at 02:26:27PM +0100, unman wrote:
> > On Mon, May 17, 2021 at 05:17:22AM -0700, Andrew David Wong wrote:
> > > 
> > > > As you know this topic - is there a ticket to change menu text of service for Dolphin from "Send to VM" to "Copy to VM"? 
> > > > 
> > > > Or should I create one?
> > > > 
> > > 
> > > Pretty sure there's already an issue for that. Sounds familiar.
> > > 
> > 
> > It's #1040 - the language unified the wrong way, and has never been
> > corrected.
> 
> I've put in PR.
> I haven't addressed the order of items raised in that issue - I don't know
> if this differs between file managers or if this is a problem?
> @andrewdavidwong @ninavizz ??
> 
> 

Let's discuss it on that issue instead of this one, please.

**Comment by jamke** [comment] 2021-05-18 14:16
1)

> imo this is covered by the standard warning about using minimal
> templates. They are for advanced users.
> The issue wont arise on a standard template.

It's not true. Install standard fedora-33 template, remove nautilus, qubes-core-agent-nautilus and copy/move in Dolphin won't work.
I use minimal template just to avoid removing of nautilus and other gnome and gtk useless stuff.

2)
> This is still a bug in Qubes OS. @herypt patch coming.

Thanks. Maybe the issue should have bug label back, more consistent with the situation/

3)
@herypt  thanks for the patch!

This issue can be closed if it's really fixed (I have not not checked).

**Comment by andrewdavidwong** [comment] 2021-05-18 14:24
> > imo this is covered by the standard warning about using minimal
> 
> > templates. They are for advanced users.
> 
> > The issue wont arise on a standard template.
> 
> 
> 
> It's not true. Install standard fedora-33 template, remove nautilus, qubes-core-agent-nautilus and copy/move in Dolphin won't work.
> 

He obviously meant the standard template without removing default pre-installed packages. 

> I use minimal template just to avoid removing nautilus and other gnome and gtk useless stuff.
> 
> 
> 
> > This is still a bug in Qubes OS. @herypt patch coming.
> 
> 
> 
> Thanks. Maybe the issue should have bug label back, more consistent with the situation.
> 

To me, this looks like an enhancement request for better Dolphin support.

What exactly is the alleged bug?

**Comment by DemiMarie** [comment] 2021-05-18 14:47
> > I use minimal template just to avoid removing nautilus and other gnome and gtk useless stuff.
> > > This is still a bug in Qubes OS. @herypt patch coming.
> > 
> > 
> > Thanks. Maybe the issue should have bug label back, more consistent with the situation.
> 
> To me, this looks like an enhancement request for better Dolphin support.
> 
> What exactly is the alleged bug?

As far as I can tell, the problem appears that certain files are belong to a `-nautilus` package, when they really do not depend on Nautilus and are useful with Dolphin/Thunar/etc as well.  Not sure if this is a bug or an enhancement.  Personally, I consider it a bug because having to install `-nautilus` packages for this should not be required.

**Comment by andrewdavidwong** [comment] 2021-05-18 15:17
> > What exactly is the alleged bug?
> 
> 
> 
> As far as I can tell, the problem appears that certain files are belong to a `-nautilus` package, when they really do not depend on Nautilus and are useful with Dolphin/Thunar/etc as well.  Not sure if this is a bug or an enhancement.  Personally, I consider it a bug because having to install `-nautilus` packages for this should not be required.

Tried to update title to more accurately express this. Please edit further if you can further improve accuracy or clarity.

**Closed** 2021-05-24 03:17 UTC
Labels: C: other, P: minor, T: bug, pr-submitted
