### ISSUE TITLE
Problems with Qubes Tools dependencies

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#4487] opened 2018-11-07 17:53 UTC
### Qubes OS version:
R4.0
### Affected component(s): 

qubes-core-agent-dom0-updates qubes-core-agent-passwordless-root
qubes-gpg-split qubes-img-converter qubes-input-proxy-sender
qubes-pdf-converter qubes-thunderbird qubes-usb-proxy
qubes-mgmt-salt-vm-connector qubes-vm-recommended

### General notes:
Today I launched the upgrade for my kali linux template based on debian buster.
https://0bin.net/paste/QiLG3g3FpPnw-X44#rtKSNtzAjmB8z3JQwa-HUlpux7yKiRPQKuLn2CywqDV

Then when I tried to run dist-upgrade, such problems with dependencies appeared:
https://0bin.net/paste/D5+dsbISZbPb3Vx8#gLkMq-BzGon5XE/R8c1IF/1eUbrctLMdOsj8Bcosdt6

**Comment by toxub23** [comment] 2018-11-13 18:02
@marmarek any idea?

**Comment by marmarek** [comment] 2018-11-13 19:08
You have salt package from stretch (`+deb9` in version), so it worked before. But buster lack salt packages completely, for some reason. And probably some new upload to buster conflicts with the stretch's salt packages. This may be even the reason why there is no salt in buster (but unlikely).
It may be related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908430

Anyway, it looks like an Debian buster problem (missing salt packages). I'd suggest asking Debian folks about this.

**Comment by h01ger** [comment] 2018-11-13 19:28
Dear salt maintainers,

do you plan to update salt in time for buster? It seems a new upstream
version is needed...

On Tue, Nov 13, 2018 at 11:08:34AM -0800, Marek Marczykowski-Górecki wrote:
> It may be related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908430
> 
> Anyway, it looks like an Debian buster problem (missing salt packages). I'd suggest asking Debian folks about this.

according to https://tracker.debian.org/salt salt is not in buster
because of the bug above (#908430) and #893817, #896921, #904654 and
#913475.

https://salsa.debian.org/salt-team/salt/commits/master has some commits
since the last upload 8 months ago, but nothing major.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by h01ger** [comment] 2018-11-14 15:10
Hi Holger,

Am Dienstag, den 13.11.2018, 19:27 +0000 schrieb Holger Levsen:
> Dear salt maintainers,
> 
> do you plan to update salt in time for buster? It seems a new
> upstream
> version is needed...
> 
> On Tue, Nov 13, 2018 at 11:08:34AM -0800, Marek Marczykowski-Górecki
> wrote:
> > It may be related to 
> > https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908430
> > 
> > Anyway, it looks like an Debian buster problem (missing salt
> > packages). I'd suggest asking Debian folks about this.
> 
> according to https://tracker.debian.org/salt salt is not in buster
> because of the bug above (#908430) and #893817, #896921, #904654 and
> #913475.
> 
> https://salsa.debian.org/salt-team/salt/commits/master has some
> commits
> since the last upload 8 months ago, but nothing major.

Getting the salt package in shape before buster is on my todo list. I
already started with that work and pushed it into the wip-2018.11
branch.

-- 
Benjamin Drung
System Developer
Debian & Ubuntu Developer

1&1 IONOS Cloud GmbH | Greifswalder Str. 207 | 10405 Berlin | Germany
E-mail: benjamin.drung@cloud.ionos.com | Web: www.ionos.de

Head Office: Berlin, Germany
District Court Berlin Charlottenburg, Registration number: HRB 125506 B
Executive Management: Christoph Steffens, Matthias Steinberg, Achim
Weiss

Member of United Internet

**Comment by h01ger** [comment] 2018-11-14 15:14
Hi Benjamin,

On Wed, Nov 14, 2018 at 04:10:51PM +0100, Benjamin Drung wrote:
> Getting the salt package in shape before buster is on my todo list. I
> already started with that work and pushed it into the wip-2018.11
> branch.

ah, very cool & thank you for letting us know! (& the work too...! :)


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by toxub23** [comment] 2018-12-15 19:08
@marmarek @h01ger I only informs that the problem still occurs and here the list from the "sudo apt-get -V dist-upgrade" command.
https://0bin.net/paste/ruXn3vQ4jswUz8mK#YJN3LW79zO8us2T-BD+3qhrphr3PcTxIzN2VecjH+7W

**Comment by unman** [comment] 2019-02-25 13:22
@andrewdavidwong  Debian testing has had salt for some time now, and I can confirm that buster upgrades work as expected.
Please close this issue.

**Closed** 2019-02-25 17:59 UTC
Labels: C: Debian/Ubuntu, C: mgmt, bug
