### ISSUE TITLE
Errors (possibly spurious) during installation from 'systemctl enable' commands

### ISSUE THREAD

**Issue by HeDamsja** [QubesOS/qubes-issues#1972] opened 2016-05-07 00:59 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.1

---

### Expected behavior:
Either not have the `initial-setup-text.service` and `initial-setup-graphical.service` be attempted to be enabled, or set them up to succeed.

### Actual behavior:
From `/tmp/program.log`:
```
21:26:54,282 INFO program: Running... systemctl enable initial-setup-graphical.service
21:26:54,309 INFO program: Failed to get unit file state for initial-setup-graphical.service: No such file or directory
21:26:54,310 INFO program: Operation failed: No such file or directory
21:26:54,310 DEBUG program: Return code: 1
21:26:54,310 INFO program: Running... systemctl enable initial-setup-text.service
21:26:54,336 INFO program: Failed to get unit file state for initial-setup-text.service: No such file or directory
21:26:54,337 INFO program: Operation failed: No such file or directory
21:26:54,337 DEBUG program: Return code: 1
```

### Steps to reproduce the behavior:

Install Qubes OS R3.1, look in /tmp/program.log before rebooting.

### General notes:

Those two's presence seems confusing. Possibly left-overs from [something else](https://github.com/rhinstaller/initial-setup/blob/master/initial-setup.spec)? Or are these expected to be there and do something on first boot (that'd be welcomed, the text-only setup of some basic VMs until graphics is enabled or fixed without having to sneakernet things?) Haven't had a chance to look at the source of the initial GUI setup - would it be useful to modify the stock FedoraCore/Anaconda's `initial-setup-text.service` replicate the first-boot Qubes OS GUI-based setup menu?

---

#### Related issues:
1952
#### Relevant labels:
installation text-only

**Comment by andrewdavidwong** [comment] 2016-05-07 17:37
Can you clarify how this is related to #1952?

**Comment by marmarek** [comment] 2016-05-07 20:02
Actually in Qubes 3.2 we will use initial-setup (instead of firstboot), it is already implemented. Since there are no plans for installer update for 3.1 and the problem isn't critical, closing this as `wontfix`.

**Closed by marmarek** 2016-05-07 20:02 UTC
Labels: C: installer, question
