### ISSUE TITLE
Split-gpg configuration can stop you from pasting into VMs

### ISSUE THREAD

**Issue by hackerncoder** [QubesOS/qubes-issues#6173] opened 2020-11-01 09:26 UTC
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

Pasting into any VM

**Brief summary**

Depending on the configuration in /etc/qubes-rpc/policy/qubes.Gpg you cannot past into any VM, copying seems fine.

**To Reproduce** 

1. Edit `/etc/qubes-rpc/policy/qubes.Gpg`
2. Put in a wrong configuration. As long as 1 character is wrong, pasting won't work. (Except if it is a character in a VMs name).

**Expected behavior**

Pasting into VMs should work. Independent of split-gpg.

**Actual behavior**

Pasting just doesn't seem to happen. The notification about pasting into a VM and clearing the clipboard doesn't show, and nothing can be pasted inside the VM. 

**Solutions you've tried**

Removing the offending line from the configuration allows you to paste into VMs again.

**Comment by marmarek** [comment] 2020-11-01 11:29
In R4.1 we load qrexec policy as a whole - if the policy is invalid, all the calls will be denied, including `qubes.ClipboardPaste` (which is responsible for the copy/paste). While it may look like an unrelated change, it is a configuration file for the same thing - qrexec.
Currently any syntax error results in a log entry. To avoid confusion, we can add a notification.
There is also `qrexec-policy-graph` tool to analyze the policy, which can be used to validate it. There is also a policy editor in preparation, which validates the policy before saving it.

**Comment by hackerncoder** [comment] 2020-11-02 20:46
That was what I thought.

I think that a notification would be great.

Ah, I would like to help on the policy editor, where is it?

**Comment by marmarek** [comment] 2020-11-02 21:05
> Ah, I would like to help on the policy editor, where is it?

Tracking issue is [here](https://github.com/QubesOS/qubes-issues/issues/4721), but there is not much info. Most of the backend is already done here: https://github.com/QubesOS/qubes-core-qrexec/pull/54

**Comment by andrewdavidwong** [comment] 2020-11-03 06:11
> Currently any syntax error results in a log entry. To avoid confusion, we can add a notification.

> I think that a notification would be great.

I believe this is #3904.

**Comment by andrewdavidwong** [comment] 2020-11-03 06:15
If I understand correctly, the observed behavior is not a bug.

However:

- Improved UX would make this behavior easier to deal with. (#3904)
- A policy editor tool would make the observed behavior less likely. (#4721)

Since there is no bug to fix here, and all relevant action items are already covered in existing issues, it appears that this should be closed as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2020-11-03 06:15 UTC
Labels: P: default, T: bug
