### ISSUE TITLE
Application windows doesn't open directly, but runs in background

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2085] opened 2016-06-19 20:32 UTC
#### Qubes OS version (e.g., `R3.1`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
When open an application from the launcher the application should start and the window should open.

### Actual behavior:
Application is started, but "hidden" until some action. I.e. after arbitrary thing happen the windows pops-up and become view able.

### Steps to reproduce the behavior:
Start application from the application launcher or update from Qubes manager. Doesn't always happens, but in the majority of cases.

**Comment by andrewdavidwong** [comment] 2016-06-20 17:54
Does this happen when you start a VM by clicking an application shortcut in the main launcher? If so, is the VM status color yellow in Qubes Manager when this happens?

**Comment by dumbl3d0re** [comment] 2016-06-20 18:28
Yes, it happens when I start an application using the application launcher. The color of the state icon changes from yellow --> green (about 1 sec) --> yellow.

**Comment by andrewdavidwong** [comment] 2016-06-20 18:55
> Yes, it happens when I start an application using the application launcher.

Sorry, but that's not what I asked. I asked:

>> Does this happen when you **start a VM by** clicking an application shortcut in the main launcher?

In other words, is the VM powered off *before* you try to start the application, or is it already running?

**Comment by dumbl3d0re** [comment] 2016-06-20 22:05
It's powered off when I try to start an application.

**Comment by andrewdavidwong** [comment] 2016-06-21 00:02
What kind of application are you starting from the launcher, and what kind of event causes the window to become viewable (and the state of the VM to change from yellow to green)?

I've noticed similar behavior in R3.1, but only when starting some non-GUI program. In my case, opening any kind of GUI window causes the state to change from yellow to green.

**Comment by dumbl3d0re** [comment] 2016-06-21 07:58
Andrew David Wong:
> What kind of application are you starting from the launcher, and what kind of event causes the window to become viewable (and the state of the VM to change from yellow to green)?
It happens for all applications. To get the windows visible I've to
click on an menu entry for the same appVM one more time. E.g. try to
open two browser windows, or one browser window and one terminal. Both
then become visible. If I try to open two browser windows two tabs will
open. I've noticed that it mainly happens to new appVMs that I haven't
started earlier.

The yellow icon becomes green when the window(s) become visible.

> I've noticed similar behavior in R3.1, but only when starting some non-GUI program. In my case, opening any kind of GUI window causes the state to change from yellow to green.
It never happened for me on R3.1, or it was so rare so that I didn't
notice it.

**Comment by andrewdavidwong** [comment] 2016-06-22 03:35
It's not a duplicate of #1451, right?

In other words, the window is not just *partially* rendered, but rather not visible *at all*?

**Comment by dumbl3d0re** [comment] 2016-06-23 21:54
No, it isn't. This is what happens.

1. Try to open an application from the application launcher in an shutdown VM.
2. The virtual machine is started up, and the applications launcher is jumping around (the "loading" icon)
3. Nothing else happens (when his problem occur). E.g. the window doesn't show up in the task switcher (Alt+Tab).
4. Try to start another application, or the same, in the same virtual machine almost instantly makes the first and second application windows show up.

**Comment by marmarek** [comment] 2016-06-24 02:12
I've managed to reproduce this. The problem is that gui daemon sometimes
crashes at VM startup. But since it's automatically restarted (when needed)
when trying to start new application, the first application also shows up.

The actual error message in `/var/log/qubes/guid.VMNAME.log` (or `.old` one
when gui daemon gets restarted):

	 XDestroyWindow 0x5e00005
	ErrorHandler: BadWindow (invalid Window parameter)
					 Major opcode: 10 (X_UnmapWindow)
					 ResourceID:   0x5e00005
					 Failed serial number:  194
					 Current serial number: 197

Looks like some race condition on destroying window.

**Comment by marmarek** [comment] 2016-06-24 22:18
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.2-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/8e36881ceeeff19a7c04ae7341e213b0ef1a9f3b...50715fa1aba2e6f44d9328bea00084c626082b7b

**Comment by marmarek** [comment] 2016-07-28 12:49
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/8e36881ceeeff19a7c04ae7341e213b0ef1a9f3b...7f6809f06f88404bceecfc6656af99e7abf8f8e9

**Closed** 2016-08-08 12:17 UTC
Labels: bug, C: core, C: gui-virtualization, P: major, r3.2-dom0-stable

**Comment by marmarek** [comment] 2016-08-08 12:21
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.4-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/7f6809f06f88404bceecfc6656af99e7abf8f8e9...26bc90b7c41f19061423f01ff076f669e9136e5f

**Comment by marmarek** [comment] 2016-08-31 11:11
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.4-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/7f6809f06f88404bceecfc6656af99e7abf8f8e9...26bc90b7c41f19061423f01ff076f669e9136e5f
