### ISSUE TITLE
Not able to mount USB media via the applet top right

### ISSUE THREAD

**Issue by NinjaTurtle007** [QubesOS/qubes-issues#3343] opened 2017-11-28 07:52 UTC
#### Qubes OS version:

4 rc3

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behavior:

1. plug usb device
2. activate the drop down menu from the pcs icon on top right
3. select your media and then select the VM you want to mount it to
4. Nothing happens, except the + icon changes to eject icon.

### Expected behavior:
To actually mount the usb media in the selected VM and be visible under Devices in file manager

### Actual behavior:
Nothing happens, except changing the + icon to eject icon in the applet menu for that device and vm

### General notes:

---

**Comment by SubjectMatterExpert** [comment] 2017-11-30 05:02
+1
Clean install of 4.0 RC3 - regardless of the USB mass media type (tried with at least 7 different USB flash sticks and USB HDD-s) this issue is really there.

**Comment by NinjaTurtle007** [comment] 2017-11-30 05:18
I have a tiny progress. After unplugging the PC from the power for 5-10mins I'm finally able to start the installation of Ubuntu 17.10
qubes rc2 is still stuck at that xen screen though

will finish the ubuntu install and try the rc2 and 3 again over it


I cant imagine what would prevent installing anything, oddest thing I have ever encountered.
How can qubes mess it up on such a deep level?

**Comment by NinjaTurtle007** [comment] 2017-11-30 07:43
Not sure why you would close it @SubjectMatterExpert 
your reference is for working OS that can't see USB
here we have a problem that USB booting doesnt proceed on boot level


update on my progress, Ubuntu 17.10 installed and works. I have no qubes OS at all at the system now (fully wiped the ssd) however, I still can't boot the qubes bootable USB.

**Comment by andrewdavidwong** [comment] 2017-12-01 05:26
@NinjaTurtle007: I think you're confused by the GitHub interface. @SubjectMatterExpert didn't close anything. I closed #3358 because it's a duplicate of #2860. That's the only reason you see a little "closed" icon on the right above your [comment](https://github.com/QubesOS/qubes-issues/issues/3343#issuecomment-348107930). This issue (#3343) is still open.

**Comment by najamelan** [comment] 2018-01-01 11:56
@NinjaTurtle007 Do you still have this problem?

Note that the applet has 2 sections. One for passing a block device through to another VM (eg. it will say `sys-usb:sda1`) and one for passing the actual usb hardware to another VM, which would show something like `sys-usb:4-3`. The latter won't do USB3.0 for now, but you don't need it to have access your files, and it should even be more secure to pass the block device.

If you have problems with the block device method, look at how I found a solution for a similar problem in the description of [this issue](https://github.com/QubesOS/qubes-issues/issues/3351#issuecomment-354649477), most likely that's your problem.

**Closed** 2023-08-05 09:15 UTC
Labels: T: bug, C: manager/widget, eol-4.0
