### ISSUE TITLE
Critical error VM Settings

### ISSUE THREAD

**Issue by umbratic** [QubesOS/qubes-issues#9442] opened 2024-09-06 20:13 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release: Qubes release 4.2.2 (R4.2)

Linux dom0 6.10.3-1.qubes.fc37.x86_64 
fedora-39, fully updated

### Brief summary
"Settings" crashes after setting firewall in Disposable to allow for 5 minutes.

### Steps to reproduce
Open a Disposable terminal: dispXXXX

Open "Settings" for dispXXXX / Firewall  /  (X) Allow full access for 5 min / Apply / OK

Open "Settings" for dispXXXX 

Pop-up window with crash notice (see below). Sometimes "Settings" must be opened / closed 2-3 times to trigger this.

### Expected behavior
No error

### Actual behavior
**Pop-up window:**

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

TypeError: unsupported operand type(s) for -: 'int' and 'str'
at line 33
of file /usr/bin/qubes-vm-settings.

**Show Details:**

line: expire_time = model.temp_full_access_expire_time - \
func: set_fw_model
line no.: 1464
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py

line: self.set_fw_model(model)
func: __init__
line no.: 192
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py

line: window = window_class(qt_app, qubes_app)
func: run_synchronous
line no.: 558
file: /usr/lib/python3.11/site-packages/qubesmanager/utils.py

line: utils.run_synchronous(functools.partial(VMSettingsWindow, vm, args.tab))
func: main
line no.: 1540
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py

line: sys.exit(load_entry_point('qubesmanager==4.2.8', 'console_scripts', 'qubes-vm-settings')())
func: <module>
line no.: 33
file: /usr/bin/qubes-vm-settings

**Comment by marmarek** [comment] 2024-09-06 20:44
Duplicate of #8685

**Closed** 2024-09-06 20:45 UTC
Labels: T: bug, R: duplicate, P: default
