### ISSUE TITLE
Debian 11 template upgrade problem, all guests broken

### ISSUE THREAD

**Issue by gangamstyle** [QubesOS/qubes-issues#7865] opened 2022-11-05 19:26 UTC
### Qubes OS release
4.1

### Brief summary
For a long time I used debian-11 template which worked fine.
Today I tried to upgrade this template using Qubes upgrade tool and upgrade failed.
After upgrade using "apt" I discovered that this happened because qubes tor repository now lacks r4.0 files (http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.0/vm)
And I had this link in my /etc/apt/sources.list.d/qubes-r4.list , with r4.0 and not r4.1 in URL.

To fix this problem I have changed repository link like this: 
http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm

After that I restarted upgrade process using Qubes upgrade toot, upgrade failed without description.
After this error template became unresponsive and unbootable. All template based guest vm's failed to boot.

This part of the problem was fixed by removing this broken template and reinstalling Debian 11 template.
But I also have standalone OS based on that template which I can't fix so simple and if fails to upgrade too.

This is "apt upgrade" error:
```
....
Processing triggers for qubes-core-agent (4.0.65-1+deb11u1) ...
/usr/lib/qubes/qrexec-client-vm: error while loading shared libraries: libqrexec-utils.so.2: cannot open shared object file: No such file or directory
qrexec-client-vm: error while loading shared libraries: libqrexec-utils.so.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 88, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 83, in main
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['qrexec-client-vm', 'dom0', 'qubes.FeaturesRequest']' returned non-zero exit status 127.
............
...........
Setting up qubes-vm-dependencies (4.1.20-1+deb11u1) ...
/usr/lib/qubes/qrexec-client-vm: error while loading shared libraries: libqrexec-utils.so.2: cannot open shared object file: No such file or directory

```

I tried: apt install --reinstall qubes-core-agent qubes-vm-dependencies
but it fails too:
```
Unpacking xen-utils-guest (4.14.5-10+deb11u1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-1234/2-xen-utils-guest_4.14.5-10+deb11u1_amd64.deb (--unpack):
 trying to overwrite '/lib/systemd/system/xendriverdomain.service', which is also in package xen-utils-common 2001:4.8.5-42+deb11u1

```
 ... and after this standalone VM becomes broken and fails to boot.

**Comment by gangamstyle** [comment] 2022-11-05 19:29
I have working clone of that standalone VM it still works with old software but how to upgrade it ?

**Comment by DemiMarie** [comment] 2022-11-06 19:10
@gangamstyle: try removing the old package versions first.  Obviously, it is best to do this on a clone in case something goes wrong.

**Comment by gangamstyle** [comment] 2022-11-23 10:39
@DemiMarie you can't do that, because VM stops after removal - these packages are used for communication with dom0

**Comment by 0spinboson** [comment] 2022-11-23 11:07
> @DemiMarie you can't do that, because VM stops after removal - these packages are used for communication with dom0

not even using sudo xl console debian-11 from dom0?

**Comment by DemiMarie** [comment] 2022-11-23 15:21
> > @DemiMarie you can't do that, because VM stops after removal - these packages are used for communication with dom0
> 
> not even using sudo xl console VMNAME from dom0?

`qvm-console-dispvm` is a safer option

**Comment by Kixunil** [comment] 2023-01-27 17:32
I have the same problem. I tried to update using `qvm-console-dispvm` but removing the offending package first removes updates proxy which makes subsequent operations impossible. I tried pre-downloading the packages but I'm still getting errors. It seems that Qubes and Debian repository both provide the same-named packages and this is causing the problems.

IMO Qubes (or any other project) should never contain packages that conflict with the Debian ones. Otherwise there will be ridiculous problems like this.

**Comment by marmarek** [comment] 2023-01-28 01:09
@Kixunil so, you tried upgrading template/standalone from R4.0 to R4.1, right? The source of the problem is that in R4.1 we actually stopped shipping own duplicated xen packages, and are relying on those from official Debian repositories. But the upgrade path requires manual step because of that.
The in-place R4.0 -> R4.1 upgrade tool handle that automatically, but in case of manual upgrade, see this part:
https://github.com/QubesOS/qubes-dist-upgrade/blob/release4.0/scripts/upgrade-template-standalone.sh#L37-L72

**Comment by Kixunil** [comment] 2023-01-29 20:00
Performing the steps from the script manually helped, thanks a lot!

**Comment by unman** [comment] 2023-04-02 04:10
I do not think there is any thing actionable here.
The issues arose because upgrades were made long after 4.0 had gone eol, repository definitions had not been updated, and the automated tool no longer worked.
@andrewdavidwong - close?

**Comment by andrewdavidwong** [comment] 2023-04-02 06:35
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-04-02 06:35 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, needs diagnosis, C: updates
