### ISSUE TITLE
Failed to start Load Kernel Modules

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2638] opened 2017-02-16 20:16 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
---

### Expected behavior:
System should start without giving any errors.

### Actual behavior:
The system works fine but every time i start it i get the following error since i installed it fot the first time: "Failed to start Load Kernel Modules".

### Steps to reproduce the behavior:
Simply start the system.

### General notes:

  ```
 $ systemctl status systemd-modules-load -l
    ● systemd-modules-load.service - Load Kernel Modules
    Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static; vendor preset: disabled)
    Active: failed (Result: exit-code) since dom 2017-02-12 02:35:48 CET; 30min ago
    Docs: man:systemd-modules-load.service(8)
    man:modules-load.d(5)
    Process: 1098 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
    Main PID: 1098 (code=exited, status=1/FAILURE)

    feb 12 02:35:47 dom0 systemd-modules-load[1098]: Module 'xen_evtchn' is builtin
    feb 12 02:35:47 dom0 systemd-modules-load[1098]: Module 'xen_gntdev' is builtin
    feb 12 02:35:47 dom0 systemd-modules-load[1098]: Module 'xen_gntalloc' is builtin
    feb 12 02:35:48 dom0 systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
    feb 12 02:35:48 dom0 systemd[1]: Failed to start Load Kernel Modules.
    feb 12 02:35:48 dom0 systemd[1]: systemd-modules-load.service: Unit entered failed state.
    feb 12 02:35:48 dom0 systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
```
---

#### Related issues:

**Comment by DimSKho** [comment] 2017-07-04 20:51
I actually encountered the same issue issue as it looks like too place previously. 

It was an attempt to run Qubes 3.2 in a VM using vmWare Workstation pro, once installed and rebooted, i barely had enough time to take this SS.
![2017-07-04_21-12-39](https://user-images.githubusercontent.com/10298367/27842477-126786b6-6113-11e7-9ba1-f2e02621cae4.jpg)

The VM seems to be configured according to the requirements.
![2017-07-04_21-21-10](https://user-images.githubusercontent.com/10298367/27842557-a7ce4578-6113-11e7-843a-a9df6ec7c7bf.jpg)

Please let me know what im doing wrong or how it would be possible to resolve the issue?

**Comment by andrewdavidwong** [comment] 2017-07-08 17:18
@DimSKho: Please note that [Qubes is not intended to run as a VM under another hypervisor](https://www.qubes-os.org/doc/user-faq/#can-i-install-qubes-in-a-virtual-machine-eg-on-vmware). Of course, if you can get it to work, or if someone can provide the information you need, that's great! I just wouldn't want you to be under the impression that it's "supposed" to work.

**Comment by aidecoe** [comment] 2017-08-11 20:10
I've hit the same issue on first boot of freshly installed QubesOS 3.2 on a real hardware.

**Comment by Malumake** [comment] 2017-08-31 18:15
Same issue, fresh install QubesOS 3.2 on HP Proliant  DL380 Gen9 .

**Comment by alpharou** [comment] 2017-09-10 14:07
same issue here in 3.2, it seems PC independent.

**Comment by sporkmonger** [comment] 2017-11-15 02:07
Same issue in 3.2 on Dell 7520.

**Comment by danieleiba** [comment] 2017-11-22 12:14
Same issue on MacBook Air

**Comment by jupiter126** [comment] 2017-11-23 12:27
Same issue on 4.0rc2 on asus z10pe d16ws

**Comment by mannp** [comment] 2017-12-05 16:06
Same issue on macbook air 5,2 with all testing updated applied after v4rc3

**Comment by unman** [comment] 2017-12-08 11:45
@andrewdavidwong This has been an issue for some time, and it's been reported on mailing lists also.
But it is, I think, spurious. Whenever I have looked at the logs (as instructed) I see the modules-load service active since boot time, with the process exiting SUCCESS. I'll warrant that the same applies in every report here.
@danieleiba @jupiter126 @mannp - Can you please check the service status and view the process outcome?

I suggest that we close this with an entry in the FAQ

**Comment by andrewdavidwong** [comment] 2017-12-09 01:48
@unman:
> This has been an issue for some time, and it's been reported on mailing lists also.
But it is, I think, spurious. Whenever I have looked at the logs (as instructed) I see the modules-load service active since boot time, with the process exiting SUCCESS. I'll warrant that the same applies in every report here.

Wouldn't that entail that the "Failed to start Load Kernel Modules" message is false? If so, that's the bug here. The message should be prevented, hidden, or suppressed.

**Comment by unman** [comment] 2017-12-09 02:13
On Sat, Dec 09, 2017 at 01:48:08AM +0000, Andrew David Wong wrote:
> @unman:
> > This has been an issue for some time, and it's been reported on mailing lists also.
> But it is, I think, spurious. Whenever I have looked at the logs (as instructed) I see the modules-load service active since boot time, with the process exiting SUCCESS. I'll warrant that the same applies in every report here.
> 
> Wouldn't that entail that the "Failed to start Load Kernel Modules" message is false? If so, that's the bug here. The message should be prevented, hidden, or suppressed.
> 

This would be an upstream bug.
In fact, with the latest dom0 updates I think the issue disappears completely in 3.2 - anyone else confirm? And report situation in 4rc3?

**Comment by mannp** [comment] 2017-12-09 20:06
@unman wifi and thunderbolt ethernet are not compatible with qubes on my laptop so I have removed qubes for Arch, so am unable to feedback.

**Comment by githubnub6** [comment] 2017-12-28 21:45
I can confirm dom0 update fixed it for me. I had the exact same "failed to start Load Kernel Modules" after fresh install of 3.2 and by updating dom0 (using the current-testing repo) it stopped showing it. This was only for legacy boot however.

This was NOT the case for when I had 3.2 installed in UEFI mode. The annoying red error at the top of the log"failed to start Load Kernel Modules"  when booting persists after updating dom0 and even showed up when I tried installing 4.0rc3.


There should really be some warnings somewhere thats says if you try and install Qubes using UEFI then you might not have a good time.*

*might be because of my AMD gpu that I cant for the life of me figure out why iommu wont activate. Its a "mullins" model amd APU

**Comment by e6lk7dqzm83p** [comment] 2018-06-16 16:04
I have this on a brand new 4.0 install; unable to tell if it is affecting anything due to other issues (sys-net not loading).

**Comment by mdsabirali** [comment] 2018-10-31 02:56
Hi, I am trying to install qubes 4.2 and download fresh iso, followed the instructions and made my usb bootable with rufus and installed it on my hp follio 9470m, but getting error everytime I installed it on real hardware, 
Please help me
Screenshot below


https://user-images.githubusercontent.com/10298367/27842477-126786b6-6113-11e7-9ba1-f2e02621cae4.jpg

My laptop is not accessible I am formatting it, changing bios setting but no luck, request anyone to help, any help is appreciated.

**Comment by BmetaMax** [comment] 2019-01-09 21:37
Hello, also seeing this on a Dell Optiplex 780 running A15 firmware as recommended by the HW guide. System still boots up though. I also seem to be having a network problem but I'll see if I can find the right issue for it before going into details.

**Comment by thecircleoflifefree** [comment] 2019-01-16 16:39
Same issue on:

QUBES 4.x
4RAM
50GB HD
VMware® Workstation 14 Pro
14.1.1 build-7528167

HOST:
Windows 7 Home Premium, 64-bit 6.1.7601, Service Pack 1

HARDWARE:
Toshiba Satellite L855-S5372
Intel(R) Core(TM) i7-3660QM CPU @ 2.
RAM 8 GB

**Closed** 2019-02-19 04:00 UTC
Labels: C: kernel, P: major, bug

**Comment by GWeck** [comment] 2019-11-09 13:37
The error message "Failed to start Load Kernel Modules" reappeared on a newly installed R4.0.2-rc2 system (Xen 4.8.5-11.fc25 and Kernel 4.19.80-1). The system, however, runs without problems.
A System, which I upgraded from R4.0.2-rc1 (Xen 4.8.5-10.fc25 and Kernel 4.19.80-1) does not show the error. Could it be that the different version of Xen is causing this?
