### ISSUE TITLE
Some docker containers fail to start with Xen 4.14.4

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#7313] opened 2022-02-28 03:07 UTC
### Qubes OS release
4.1 (upgraded from 4.0

### Brief summary
Some docker containers (tested with rancher/k3s, every version for the last few months) fail to start with xen-hypervisor 4.14.4. Downgrading to 4.14.3 resolves the issue.

### Steps to reproduce
1. Install `xen-hypervisor` 4.14.4 from the current-testing repo.
2. In an AppVM (Fedora 34 and Debian 11 tested) run `sudo docker run -it rancher/k3s:latest`. 
3. The process will hang after "Storing Signatures". k3s will not start.
4. Downgrade to 4.14.3 and repeat, the container will run as normal.

### Expected behavior
Hypervisor upgrades should not break VM applications.

### Actual behavior
Docker container (or something the application attempts) is broken.

**Comment by DemiMarie** [comment] 2022-02-28 03:16
That is strange.  Can you post any relevant log sections?  Feel free to redact anything sensitive.

**Comment by marmarek** [comment] 2022-02-28 11:17
I think it would be useful to see:
 - failed docker start logs
 - kernel logs of the VM in which docker runs
 - hypervisor logs (`xl dmesg` in dom0)

**Comment by marmarek** [comment] 2022-02-28 11:21
Some information about the hardware (especially - what CPU model) would be useful too.

**Comment by JarrahG** [comment] 2022-02-28 21:31
Strange is how I'd describe it too, but It's perfectly reproducible for me.

Docker start logs:
```
sudo docker run -it rancher/k3s:latest                                                                      ~
Unable to find image 'rancher/k3s:latest' locally
latest: Pulling from rancher/k3s
0f1a4e1ffcea: Pull complete 
94eff401a8ce: Pull complete 
00042d190e28: Pull complete 
Digest: sha256:24b7551320a241cfcdc0403436bc8bcc96b2d349084c1caf71f226a08784c417
Status: Downloaded newer image for rancher/k3s:latest
<hang>
```

Docker Daemon logs:
```
level=info msg="API listen on /run/docker.sock"
level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/8e61c0edecf414e4681d80f15244ac9270968645b56cdef88f2da22a47a21c11 pid=2481 runtime=io.containerd.runc.v2
```

VM kernel logs:
```
[   15.931991] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[   20.516628] kauditd_printk_skb: 117 callbacks suppressed
[   20.516631] audit: type=1131 audit(1646082768.752:95): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-resolved comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   34.443228] xen:grant_table: WARNING: g.e. 0x578f still in use!
[   34.443260] xen:grant_table: WARNING: g.e. 0x5752 still in use!
[   34.443295] xen:grant_table: WARNING: g.e. 0x5707 still in use!
[   34.443316] xen:grant_table: WARNING: g.e. 0x56d7 still in use!
[   34.443341] xen:grant_table: WARNING: g.e. 0x56a7 still in use!
[   34.443358] xen:grant_table: WARNING: g.e. 0x5683 still in use!
[   34.443380] xen:grant_table: WARNING: g.e. 0x5654 still in use!
[   34.443425] xen:grant_table: WARNING: g.e. 0x560d still in use!
[   34.443442] xen:grant_table: WARNING: g.e. 0x55ed still in use!
[   34.443463] xen:grant_table: WARNING: g.e. 0x55bf still in use!
[   34.443482] xen:grant_table: WARNING: g.e. 0x5597 still in use!
[   34.443504] xen:grant_table: WARNING: g.e. 0x556c still in use!
[   34.443526] xen:grant_table: WARNING: g.e. 0x553c still in use!
[   34.443547] xen:grant_table: WARNING: g.e. 0x5517 still in use!
[   34.443567] xen:grant_table: WARNING: g.e. 0x54e7 still in use!
[   34.443601] xen:grant_table: WARNING: g.e. 0x54a4 still in use!
[   34.443618] xen:grant_table: WARNING: g.e. 0x5482 still in use!
[   34.443700] xen:grant_table: WARNING: g.e. 0x53ef still in use!
[   34.443737] xen:grant_table: WARNING: g.e. 0x539f still in use!
[   34.443753] xen:grant_table: WARNING: g.e. 0x5380 still in use!
[   34.443815] xen:grant_table: WARNING: g.e. 0x52fb still in use!
[   34.443988] xen:grant_table: WARNING: g.e. 0x518f still in use!
[   34.444019] xen:grant_table: WARNING: g.e. 0x5154 still in use!
[   34.444044] xen:grant_table: WARNING: g.e. 0x5123 still in use!
[   34.444061] xen:grant_table: WARNING: g.e. 0x50fb still in use!
[   34.444089] xen:grant_table: WARNING: g.e. 0x50bf still in use!
[   34.444106] xen:grant_table: WARNING: g.e. 0x509a still in use!
[   34.444124] xen:grant_table: WARNING: g.e. 0x5078 still in use!
[   34.444139] xen:grant_table: WARNING: g.e. 0x5057 still in use!
[   34.444160] xen:grant_table: WARNING: g.e. 0x5028 still in use!
[   34.444186] xen:grant_table: WARNING: g.e. 0x4fec still in use!
[   34.444213] xen:grant_table: WARNING: g.e. 0x4fb7 still in use!
[   34.444229] xen:grant_table: WARNING: g.e. 0x4f99 still in use!
[   48.414003] audit: type=1131 audit(1646082796.650:96): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=mlocate-updatedb comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   49.913545] audit: type=1131 audit(1646082798.149:97): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   49.959865] audit: type=1334 audit(1646082798.196:98): prog-id=0 op=UNLOAD
[   49.959887] audit: type=1334 audit(1646082798.196:99): prog-id=0 op=UNLOAD
[   65.994966] audit: type=1130 audit(1646082814.231:100): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=unbound-anchor comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   65.995013] audit: type=1131 audit(1646082814.231:101): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=unbound-anchor comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   79.695396] audit: type=1101 audit(1646082827.931:102): pid=1289 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unix acct="user" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[   79.695443] audit: type=1123 audit(1646082827.931:103): pid=1289 uid=1000 auid=1000 ses=1 msg='cwd="/home/user" cmd=646E6620696E7374616C6C20646F636B6572 exe="/usr/bin/sudo" terminal=pts/0 res=success'
[   79.695919] audit: type=1110 audit(1646082827.932:104): pid=1289 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[   79.697371] audit: type=1105 audit(1646082827.933:105): pid=1289 uid=1000 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  117.090587] audit: type=1116 audit(1646082865.326:106): pid=1350 uid=0 auid=1000 ses=1 msg='op=add-group id=976 exe="/usr/sbin/groupadd" hostname=? addr=? terminal=? res=success'
[  117.096192] audit: type=1132 audit(1646082865.332:107): pid=1350 uid=0 auid=1000 ses=1 msg='op=add-shadow-group id=976 exe="/usr/sbin/groupadd" hostname=? addr=? terminal=? res=success'
[  124.238304] audit: type=1130 audit(1646082872.474:108): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=run-r5d38eb0d3d6e44a297658a006ce0002d comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  124.258522] audit: type=1334 audit(1646082872.494:109): prog-id=0 op=UNLOAD
[  124.258559] audit: type=1334 audit(1646082872.494:110): prog-id=0 op=UNLOAD
[  124.258959] audit: type=1334 audit(1646082872.495:111): prog-id=16 op=LOAD
[  124.259204] audit: type=1334 audit(1646082872.495:112): prog-id=17 op=LOAD
[  124.259985] audit: type=1334 audit(1646082872.496:113): prog-id=0 op=UNLOAD
[  124.260004] audit: type=1334 audit(1646082872.496:114): prog-id=0 op=UNLOAD
[  124.260267] audit: type=1334 audit(1646082872.496:115): prog-id=18 op=LOAD
[  124.260949] audit: type=1334 audit(1646082872.497:116): prog-id=19 op=LOAD
[  124.261836] audit: type=1334 audit(1646082872.498:117): prog-id=0 op=UNLOAD
[  135.989292] kauditd_printk_skb: 56 callbacks suppressed
[  135.989295] audit: type=1131 audit(1646082884.225:174): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=libvirtd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  136.316051] audit: type=1101 audit(1646082884.552:175): pid=2226 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unix acct="user" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  136.316096] audit: type=1123 audit(1646082884.552:176): pid=2226 uid=1000 auid=1000 ses=1 msg='cwd="/home/user" cmd=73797374656D63746C20737461727420646F636B6572 exe="/usr/bin/sudo" terminal=pts/0 res=success'
[  136.316304] audit: type=1110 audit(1646082884.552:177): pid=2226 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  136.317796] audit: type=1105 audit(1646082884.553:178): pid=2226 uid=1000 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  136.466726] Bridge firewalling registered
[  136.491386] audit: type=1325 audit(1646082884.727:179): table=nat family=2 entries=14 op=xt_replace pid=2283 comm="iptables"
[  136.491418] audit: type=1300 audit(1646082884.727:179): arch=c000003e syscall=54 success=yes exit=0 a0=4 a1=0 a2=40 a3=58b42c9f8c80 items=0 ppid=2230 pid=2283 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-legacy-multi" key=(null)
[  136.491474] audit: type=1327 audit(1646082884.727:179): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D74006E6174002D4E00444F434B4552
[  136.493226] audit: type=1325 audit(1646082884.729:180): table=filter family=2 entries=19 op=xt_replace pid=2285 comm="iptables"
[  136.493257] audit: type=1300 audit(1646082884.729:180): arch=c000003e syscall=54 success=yes exit=0 a0=4 a1=0 a2=40 a3=5bcbb0502c10 items=0 ppid=2230 pid=2285 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-legacy-multi" key=(null)
[  144.034617] kauditd_printk_skb: 73 callbacks suppressed
[  144.034621] audit: type=1101 audit(1646082892.270:207): pid=2380 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unix acct="user" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  144.034677] audit: type=1123 audit(1646082892.270:208): pid=2380 uid=1000 auid=1000 ses=1 msg='cwd="/home/user" cmd=646F636B65722072756E202D69742072616E636865722F6B33733A6C6174657374 exe="/usr/bin/sudo" terminal=pts/0 res=success'
[  144.034908] audit: type=1110 audit(1646082892.271:209): pid=2380 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  144.036377] audit: type=1105 audit(1646082892.272:210): pid=2380 uid=1000 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[  155.332038] docker0: port 1(vethb5ce7fe) entered blocking state
[  155.332061] docker0: port 1(vethb5ce7fe) entered disabled state
[  155.332104] device vethb5ce7fe entered promiscuous mode
[  155.332153] audit: type=1700 audit(1646082903.568:211): dev=vethb5ce7fe prom=256 old_prom=0 auid=4294967295 uid=0 gid=0 ses=4294967295
[  155.332184] audit: type=1300 audit(1646082903.568:211): arch=c000003e syscall=44 success=yes exit=40 a0=10 a1=c000a2ef30 a2=28 a3=0 items=0 ppid=1 pid=2230 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="dockerd" exe="/usr/bin/dockerd" key=(null)
[  155.332203] docker0: port 1(vethb5ce7fe) entered blocking state
[  155.332244] audit: type=1327 audit(1646082903.568:211): proctitle=
[  155.332264] docker0: port 1(vethb5ce7fe) entered forwarding state
[  155.332629] docker0: port 1(vethb5ce7fe) entered disabled state
[  155.422624] audit: type=1334 audit(1646082903.658:212): prog-id=0 op=UNLOAD
[  155.422656] audit: type=1334 audit(1646082903.658:213): prog-id=0 op=UNLOAD
[  155.422948] audit: type=1334 audit(1646082903.659:214): prog-id=46 op=LOAD
[  155.423218] audit: type=1334 audit(1646082903.659:215): prog-id=47 op=LOAD
[  155.424404] audit: type=1334 audit(1646082903.660:216): prog-id=0 op=UNLOAD
[  155.424439] audit: type=1334 audit(1646082903.660:217): prog-id=0 op=UNLOAD
[  155.424640] audit: type=1334 audit(1646082903.660:218): prog-id=48 op=LOAD
[  155.522006] eth0: renamed from veth61fe4b7
[  155.531054] IPv6: ADDRCONF(NETDEV_CHANGE): vethb5ce7fe: link becomes ready
[  155.531128] docker0: port 1(vethb5ce7fe) entered blocking state
[  155.531144] docker0: port 1(vethb5ce7fe) entered forwarding state
[  155.531178] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
[  178.415535] kauditd_printk_skb: 13 callbacks suppressed
[  178.415539] audit: type=1101 audit(1646082926.651:232): pid=2622 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unix acct="user" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[  178.415594] audit: type=1123 audit(1646082926.651:233): pid=2622 uid=1000 auid=1000 ses=1 msg='cwd="/home/user" cmd="dmesg" exe="/usr/bin/sudo" terminal=pts/1 res=success'
[  178.415832] audit: type=1110 audit(1646082926.652:234): pid=2622 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
[  178.417271] audit: type=1105 audit(1646082926.653:235): pid=2622 uid=1000 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
```

Hypervisor logs:
```
(XEN) Built-in command line: ept=exec-sp
 Xen 4.14.4
(XEN) Xen version 4.14.4 (mockbuild@[unknown]) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)) debug=n  Thu Feb 17 00:00:00 UTC 2022
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.02~beta3
(XEN) Command line: placeholder console=none dom0_mem=min:1024M dom0_mem=max:6128M ucode=scan smt=on smt=on gnttab_max_frames=4096 gnttab_max_maptrack_frames=8172 smt=off
(XEN) Xen image load base address: 0
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN)  VBE/DDC methods: none; EDID transfer time: 0 seconds
(XEN)  EDID info not retrieved because no DDC retrieval method detected
(XEN) Disc information:
(XEN)  Found 4 MBR signatures
(XEN)  Found 6 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  [0000000000000000, 000000000009d3ff] (usable)
(XEN)  [000000000009d400, 000000000009ffff] (reserved)
(XEN)  [00000000000e0000, 00000000000fffff] (reserved)
(XEN)  [0000000000100000, 0000000009deffff] (usable)
(XEN)  [0000000009df0000, 0000000009ffffff] (reserved)
(XEN)  [000000000a000000, 000000000affffff] (usable)
(XEN)  [000000000b000000, 000000000b01ffff] (reserved)
(XEN)  [000000000b020000, 00000000776e2fff] (usable)
(XEN)  [00000000776e3000, 0000000078c2dfff] (reserved)
(XEN)  [0000000078c2e000, 0000000078d1bfff] (usable)
(XEN)  [0000000078d1c000, 000000007916afff] (ACPI NVS)
(XEN)  [000000007916b000, 0000000079f12fff] (reserved)
(XEN)  [0000000079f13000, 000000007bffffff] (usable)
(XEN)  [000000007c000000, 000000007fffffff] (reserved)
(XEN)  [00000000b7a00000, 00000000b7a00fff] (reserved)
(XEN)  [00000000b7b00000, 00000000b7b7ffff] (reserved)
(XEN)  [00000000ef800000, 00000000ef8fffff] (reserved)
(XEN)  [00000000efc00000, 00000000efc00fff] (reserved)
(XEN)  [00000000efd00000, 00000000efd7ffff] (reserved)
(XEN)  [00000000fea00000, 00000000feafffff] (reserved)
(XEN)  [00000000fec00000, 00000000fec00fff] (reserved)
(XEN)  [00000000fec10000, 00000000fec10fff] (reserved)
(XEN)  [00000000fec30000, 00000000fec30fff] (reserved)
(XEN)  [00000000fed00000, 00000000fed00fff] (reserved)
(XEN)  [00000000fed40000, 00000000fed44fff] (reserved)
(XEN)  [00000000fed80000, 00000000fed8ffff] (reserved)
(XEN)  [00000000fedc0000, 00000000fedc0fff] (reserved)
(XEN)  [00000000fedc2000, 00000000fedcffff] (reserved)
(XEN)  [00000000fedd4000, 00000000fedd5fff] (reserved)
(XEN)  [00000000fee00000, 00000000feefffff] (reserved)
(XEN)  [00000000ff000000, 00000000ffffffff] (reserved)
(XEN)  [0000000100000000, 000000067f37ffff] (usable)
(XEN)  [000000067f380000, 000000067fffffff] (reserved)
(XEN)  [0000000680000000, 0000000c7ff7ffff] (usable)
(XEN)  [0000000c7ff80000, 0000000c7fffffff] (reserved)
(XEN) New Xen image base address: 0x7ba00000
(XEN) ACPI: RSDP 000F05B0, 0024 (r2    AMD)
(XEN) ACPI: XSDT 78D1C0B0, 00DC (r1    AMD   A M I   3242016 AMI     10013)
(XEN) ACPI: FACP 78D27258, 0114 (r6    AMD   A M I   3242016 AMI     10013)
(XEN) ACPI: DSDT 78D1C220, B035 (r2    AMD   A M I   3242016 INTL 20120913)
(XEN) ACPI: FACS 79168700, 0040
(XEN) ACPI: APIC 78D27370, 046A (r3    AMD   A M I   3242016 AMI     10013)
(XEN) ACPI: FPDT 78D277E0, 0044 (r1    AMD   A M I   3242016 AMI     10013)
(XEN) ACPI: FIDT 78D27828, 009C (r1    AMD    A M I  3242016 AMI     10013)
(XEN) ACPI: SSDT 78D278C8, 8C4C (r2    AMD AMD ALIB        2 MSFT  4000000)
(XEN) ACPI: SSDT 78D30518, 01CC (r2    AMD  CPUSSDT  3242016 AMI   3242016)
(XEN) ACPI: SSDT 78D306E8, 2CFA (r1    AMD  AMD AOD        1 INTL 20120913)
(XEN) ACPI: MCFG 78D333E8, 003C (r1    AMD    A M I  3242016 MSFT    10013)
(XEN) ACPI: AAFT 78D33428, 048C (r1    AMD OEMAAFT   3242016 MSFT       97)
(XEN) ACPI: SSDT 78D338B8, 4604 (r1    AMD  AMD CPU        1 AMD         1)
(XEN) ACPI: SRAT 78D37EC0, 0320 (r3    AMD AMD SRAT        1 AMD         1)
(XEN) ACPI: MSCT 78D381E0, 004E (r1    AMD AMD MSCT        0 AMD         1)
(XEN) ACPI: SLIT 78D38230, 0030 (r1    AMD AMD SLIT        1 AMD         1)
(XEN) ACPI: CRAT 78D38260, 1E70 (r1    AMD AMD CRAT        1 AMD         1)
(XEN) ACPI: CDIT 78D3A0D0, 002C (r1    AMD AMD CDIT        1 AMD         1)
(XEN) ACPI: HPET 78D3A100, 0038 (r1    AMD    A M I  3242016 AMI         5)
(XEN) ACPI: SSDT 78D3A138, 0024 (r1 AMDFCH    FCHZP     1000 INTL 20120913)
(XEN) ACPI: UEFI 78D3A160, 0048 (r1    AMD   A M I         2       1000013)
(XEN) ACPI: TPM2 78D3A1A8, 0034 (r4    AMD   A M I         1 AMI         0)
(XEN) ACPI: IVRS 78D3A1E0, 0130 (r2    AMD AMD IVRS        1 AMD         0)
(XEN) ACPI: SSDT 78D3A310, 1A41 (r1    AMD AmdTable        1 INTL 20120913)
(XEN) ACPI: SSDT 78D3BD58, 00F8 (r1    AMD   AMD PT     1000 INTL 20120913)
(XEN) ACPI: WSMT 78D3BE50, 0028 (r1    AMD   A M I   3242016 AMI     10013)
(XEN) System RAM: 49033MB (50209964kB)
(XEN) Domain heap initialised DMA width 32 bits
(XEN) ACPI: 32/64X FACS address mismatch in FADT - 79168700/0000000000000000, using 32
(XEN) IOAPIC[0]: apic_id 128, version 33, address 0xfec00000, GSI 0-23
(XEN) IOAPIC[1]: apic_id 129, version 33, address 0xefc00000, GSI 24-55
(XEN) IOAPIC[2]: apic_id 130, version 33, address 0xb7a00000, GSI 56-87
(XEN) Enabling APIC mode:  Phys.  Using 3 I/O APICs
(XEN) PCI: Not using MCFG for segment 0000 bus 00-7f
(XEN) microcode: CPU0 updated from revision 0x800820b to 0x800820d
(XEN) CPU0: 2200 ... 3500 MHz
(XEN) xstate: size: 0x340 and states: 0x7
(XEN) Speculative mitigation facilities:
(XEN)   Hardware hints:
(XEN)   Hardware features: IBPB
(XEN)   Compiled-in support: INDIRECT_THUNK
(XEN)   Xen settings: BTI-Thunk LFENCE, SPEC_CTRL: No, Other: IBPB BRANCH_HARDEN
(XEN)   Support for HVM VMs: RSB
(XEN)   Support for PV VMs: None
(XEN)   XPTI (64-bit PV only): Dom0 disabled, DomU disabled (without PCID)
(XEN)   PV L1TF shadowing: Dom0 disabled, DomU disabled
(XEN) Using scheduler: SMP Credit Scheduler rev2 (credit2)
(XEN) Initializing Credit2 scheduler
(XEN) Platform timer is 14.318MHz HPET
(XEN) Detected 3493.462 MHz processor.
(XEN) AMD-Vi: IOMMU Extended Features:
(XEN) - Peripheral Page Service Request
(XEN) - NX bit
(XEN) - Invalidate All Command
(XEN) - Guest APIC
(XEN) - Performance Counters
(XEN) - Host Address Translation Size: 0x2
(XEN) - Guest Address Translation Size: 0
(XEN) - Guest CR3 Root Table Level: 0x1
(XEN) - Maximum PASID: 0xf
(XEN) - SMI Filter Register: 0x1
(XEN) - SMI Filter Register Count: 0x2
(XEN) - Guest Virtual APIC Modes: 0x1
(XEN) - Dual PPR Log: 0x2
(XEN) - Dual Event Log: 0x2
(XEN) - User / Supervisor Page Protection
(XEN) - Device Table Segmentation: 0x3
(XEN) - PPR Log Overflow Early Warning
(XEN) - PPR Automatic Response
(XEN) - Memory Access Routing and Control: 0x1
(XEN) - Block StopMark Message
(XEN) - Performance Optimization
(XEN) - MSI Capability MMIO Access
(XEN) - Guest I/O Protection
(XEN) - Host Access
(XEN) - Enhanced PPR Handling
(XEN) - Attribute Forward
(XEN) - VM Table Size: 0
(XEN) AMD-Vi: IOMMU 0 Enabled.
(XEN) AMD-Vi: IOMMU 1 Enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
(XEN) Interrupt remapping enabled
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using new ACK method
(XEN) Allocated console ring of 64 KiB.
(XEN) HVM: ASIDs enabled.
(XEN) SVM: Supported advanced features:
(XEN)  - Nested Page Tables (NPT)
(XEN)  - Last Branch Record (LBR) Virtualisation
(XEN)  - Next-RIP Saved on #VMEXIT
(XEN)  - VMCB Clean Bits
(XEN)  - DecodeAssists
(XEN)  - Virtual VMLOAD/VMSAVE
(XEN)  - Virtual GIF
(XEN)  - Pause-Intercept Filter
(XEN)  - Pause-Intercept Filter Threshold
(XEN)  - TSC Rate MSR
(XEN) HVM: SVM enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB, 1GB
(XEN) microcode: CPU2 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU4 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU6 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU8 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU10 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU12 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU14 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU16 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU18 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU20 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU22 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU24 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU26 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU28 updated from revision 0x800820b to 0x800820d
(XEN) microcode: CPU30 updated from revision 0x800820b to 0x800820d
(XEN) Brought up 8 CPUs
(XEN) Scheduling granularity: cpu, 1 CPU per sched-resource
(XEN) mtrr: your CPUs had inconsistent variable MTRR settings
(XEN) xenoprof: Initialization failed. AMD processor family 23 is not supported
(XEN) Dom0 has maximum 1336 PIRQs
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x4000000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000c50000000->0000000c58000000 (1523983 pages to be allocated)
(XEN)  Init. ramdisk: 0000000c7cf0f000->0000000c7fdff557
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff84000000
(XEN)  Init. ramdisk: 0000000000000000->0000000000000000
(XEN)  Phys-Mach map: 0000008000000000->0000008000bf8000
(XEN)  Start info:    ffffffff84000000->ffffffff840004b8
(XEN)  Xenstore ring: 0000000000000000->0000000000000000
(XEN)  Console ring:  0000000000000000->0000000000000000
(XEN)  Page tables:   ffffffff84001000->ffffffff84026000
(XEN)  Boot stack:    ffffffff84026000->ffffffff84027000
(XEN)  TOTAL:         ffffffff80000000->ffffffff84400000
(XEN)  ENTRY ADDRESS: ffffffff831191c0
(XEN) Dom0 has maximum 8 VCPUs
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Scrubbing Free RAM in background
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) *** Serial input to DOM0 (type 'CTRL-a' three times to switch input)
(XEN) Freed 540kB init memory
(XEN) INVALID_DEV_REQUEST 00000000 8a000000 f8000000 fffffffd
```

CPU: AMD Threadripper 2950X
Motherboard: Asrock Taichi X399
Dom0 and VM Kernel: 5.16.11-1

**Comment by marmarek** [comment] 2023-11-09 15:08
> `[ 15.931991] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.`

Too old container for too new kernel?

Anyway, I can't reproduce with the current version of that container, so I'm closing it now. If that still happens somewhere, please leave a comment so we can reopen.

**Closed by marmarek** 2023-11-09 15:08 UTC
Labels: T: bug, C: Xen, P: default, needs diagnosis, affects-4.1
