### ISSUE TITLE
Java application dialog (sub)windows immediately close 

### ISSUE THREAD

**Issue by ehanoc** [QubesOS/qubes-issues#5915] opened 2020-06-29 12:05 UTC
**Qubes OS version**
Qubes 4.0

**Summary**
java sub windows / dialogs immediately close

**To Reproduce**
- Install Android Studio or regular JetBrains (both java applications)
- Right click any file in the explorer
- It opens the dialog window but closes immediately

**Expected behavior**
- should keep the dialog window open

This is a blocker for development in Qubes

**Comment by andrewdavidwong** [comment] 2020-06-30 11:46
Duplicate of #3982

**Comment by andrewdavidwong** [comment] 2020-06-30 11:47
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-06-30 11:47 UTC
Labels: P: default, T: bug
