### ISSUE TITLE
4.2 qubes backups corrupted

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#8810] opened 2023-12-30 05:11 UTC
### Qubes OS release
4.2.0  6.6.2 & 6.1.62 and earlier RCs

### Brief summary
Qubes backups do not pass the backup verification test and are unusable.

### Steps to reproduce
Instal 4.2.0 6.6.2 all packages. Write a full backup to an appVM private volume (or anywhere else). Immediately run a verification restore.

### Expected behavior
A verification restore will pass, provided there are no hardware errors.
I do believe my main SSD is working without errors as everything else is working fine.

### Actual behavior
The backup restore fails at different places: for the above example, always vm2 root or private, block anywhere from 000 to 019 with passphrase incorrect error, around the 5GB mark (out of 5.5GB).  I have seen an invalid scrypt format error as well.  Every backup that I have going back months fails at different places. On 6.1.62  with ~80GB backup, failed at vm21/private.image.053.enc with passphrase incorrect.  Since all blocks before passed, there must be a data corruption there.

I do find it difficult to believe that this has not been reported!   Must be somehow related to my hardware: AMD 7950X + 670E.

I do consider it a bug that one cannot write an unencrypted backup (Next button stays greyed out until pass phrase entered).

**Comment by rustybird** [comment] 2023-12-30 13:52
> The backup restore fails at different places: for the above example, always vm2 root or private, block anywhere from 000 to 019 with passphrase incorrect error

> Must be somehow related to my hardware: AMD 7950X + 670E.

Seems like a duplicate of #4493

**Closed** 2023-12-30 22:18 UTC
Labels: T: bug, R: duplicate, C: core, P: default, affects-4.2
