### ISSUE TITLE
Turning off dispvm for dom0 not functional (from Qubes OS Global Config)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8333] opened 2023-07-07 21:17 UTC
### Qubes OS release

4.2

### Brief summary

I want to turn off possibility of using dispvm in dom0, if found this option in global settings and turned the option to none, but actually it does nothing.

### Steps to reproduce

Open Qubes config global settings -> General Settings -> Turn Default disposable template to none

You can just press on "Learn more" to see if its functional or not (or have any file in dom0 like desktop screenshot and try to open it with dispvm):

![dispvmstillcon](https://github.com/QubesOS/qubes-issues/assets/11895339/b2fcf51c-72eb-47a3-9c95-862b93d0e84f)

### Expected behavior

No dispvm should be open.

### Actual behavior

dispvm working as if its not disabled.

**Comment by marmarek** [comment] 2023-07-07 21:25
Duplicate of https://github.com/QubesOS/qubes-issues/issues/8271

**Closed by marmarek** 2023-07-07 21:25 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2023-07-08 12:17
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
