### ISSUE TITLE
USB WiFi Device attach failed on sys-net VM: Invalid speed received after qvm-usb attach command

### ISSUE THREAD

**Issue by golia78** [QubesOS/qubes-issues#3272] opened 2017-11-02 14:51 UTC
#### Qubes OS version:
4.0rc2

#### Affected TemplateVMs: 
Fedora 25

### Steps to reproduce the behavior:
- Plug the USB WiFi device (Realtek_802.11ac)
- The device is detected and Dom0 shows a popup
- Execute "qvm-usb" in dom0, the device appears in the output list of the command(dom0:1-6)
- Execute "qvm-usb attach sys-net dom0:1-6"
- Receive the message "Device attach failed: invalid speed received"
- Click on the new icon for attach/detach devices near the"Q" icon, the device result attached
- Execute "lsusb" in sys-net terminal, the device doesn't appear in the list

### Expected behavior:
USB WiFi device correctly attached to sys-net VM

### Actual behavior:
Receive the error message "Device attach failed: invalid speed received"

### General notes:
Hi, i don't know if my issue is a real issue. Am I doing something wrong?
Below the pictures of my test:

USB WiFi device image:
https://1drv.ms/i/s!ArxlgBzROcFtiqUMrXe-vroQOyKv2A

dom0 terminal image:
https://1drv.ms/i/s!ArxlgBzROcFtiqUO5em8haOZlwbjUQ

sys-net terminal image:
https://1drv.ms/i/s!ArxlgBzROcFtiqUPv6wA8o-MnwgKeg

new attach/detach icon tool image:
https://1drv.ms/i/s!ArxlgBzROcFtiqUNbobsoQwkU7g4bg

**Comment by x63x6b** [comment] 2017-11-12 13:18
I am having pretty much the same issue with USB Ethernet adapter on the latest 4.0 rc2. It's visible on dom0, however, cannot be attached to any qube yielding the same error. Some hopefully relevant info:

```
dom0$ qubes-hcl-report
Qubes release 4.0 (R4.0)
Brand: LENOVO
Model: 20175
BIOS: 66CN51WW
Xen: 4.8.2
Kernel: 4.9.56-21
...
Net:
```
```
dom0$ diff dmesg.pre_plugin dmesg.post_plugin
> [...] usb 1-2.4: new high-speed USB device number 8 using xhci_hcd
> [...] usb 1-2.4: New USB device found, idVendor=0b95, idProduct=772b
> [...] usb 1-2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [...] usb 1-2.4: Product: AX88772B
> [...] usb 1-2.4: Manufacturer: ASIX Elec. Corp.
> [...] usb 1-2.4: SerialNumber: XXXXXX
> [...] asix 1-2.4:1.0 eth0: register 'asix' at usb-0000:00:14.0-2.4, ASIX AX88772B USB 2.0 Ethernet, /MAC here/
> [...] asix 1-2.4:1.0 enp0s20u2u4: renamed from eth0
```
```
dom0$ lsusb
Bus 001 Device 008: ID 0b95:772b ASIX Electronics Corp. AX88772B
```
```
dom0$ qvm-usb l | grep 1-2.4
dom0:1-2.4   ASIX_Elec._Corp._AX88772B_XXXXXX
```
```
dom0$ qvm-usb -v a sys-net dom0:1-2.4
Device attach failed: Invalid speed received
```
```
sys-net$ lsusb
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0627:001 Adomax Technology Co., Ltd
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```
```
sys-net$ diff dmesg.pre_attach dmesg.post_attach
```

**Comment by marmarek** [comment] 2017-11-20 22:44
This is duplicate of #3026

**Closed by marmarek** 2017-11-20 22:44 UTC
Labels: bug, C: core
