### ISSUE TITLE
qubes-dom0-update -> Cache cleaned / Could not clean cache

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#8062] opened 2023-02-24 07:14 UTC
### The problem you're addressing (if any)
Run 'sudo qubesctl --show-output state.sls update.qubes-dom0' in dom0 to update it.
Wait for the update to finish.
Looks aboutl like this:

```
local:
----------
          ID: /etc/yum.repos.d/qubes-dom0.repo
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 07:56:28.142641
    Duration: 12.302 ms
     Changes:   
----------
          ID: /etc/yum.repos.d/qubes-templates.repo
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 07:56:28.155078
    Duration: 1.467 ms
     Changes:   
----------
          ID: update
    Function: cmd.run
        Name: if qubes-dom0-update --quiet --assumeyes --clean --action=clean expire-cache >/dev/null 2>&1; then
    echo "result=True comment='Cache cleaned'"
else
    echo "result=False comment='Could not clean cache'"
fi

      Result: True
     Comment: Cache cleaned
     Started: 07:56:28.157695
    Duration: 4317.782 ms
     Changes:   
----------
          ID: update
    Function: pkg.uptodate
      Result: True
     Comment: System is already up-to-date
     Started: 07:56:33.758609
    Duration: 416135.384 ms
     Changes:   

Summary for local
------------
Succeeded: 4
Failed:    0
------------
Total states run:     4
Total run time: 420.467 s
```

### The solution you'd like
Looks like the part with 'Cache cleaned' isn't executed, but the command instead just echo'ed.

### The value to a user, and who that user might be
If this is a bug, then the cache won't be cleaned at all.
Have seen this for months now. At least since https://github.com/QubesOS/qubes-issues/issues/7505

**Comment by DemiMarie** [comment] 2023-02-24 20:41
The bug is that `Name` is the entire script, which it should not be.

**Comment by andrewdavidwong** [comment] 2023-02-24 21:08
Duplicate of #7641?

**Comment by andrewdavidwong** [comment] 2023-02-24 21:09
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-02-24 21:09 UTC
Labels: T: bug, P: default, C: updates
