### ISSUE TITLE
Error while rebuilding Whonix Gateway template

### ISSUE THREAD

**Issue by rocko45** [QubesOS/qubes-issues#4961] opened 2019-04-08 04:22 UTC
**Qubes R4.0**

**Affected component(s) or functionality-  Error building new whonix gateway template, as per first step in a secure installation of R4.0

**Brief summary-  im receiving an error when trying to rebuild my whonix gateway template, as per the instructions on what to do first on a fresh install of R4.0

**To Reproduce-  
sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-gw-14 

As per https://www.qubes-os.org/doc/installation-guide/#qubes-401-warning

**Expected behavior**
Rebuilding of whonix gateway template

Actual behavior-
Template VM haulted
Attempting to operate on template of UpdateVM... backing up whonix-gw-14 to whonix-gw-14-backup-20190407-dMa
qvm-clone: error: VM name must be shorter than 32 characters 
Unable to make backup of UpdateVM template!

What is the workaround for this problem?  Thanks for your time!

**Comment by andrewdavidwong** [comment] 2019-04-08 06:32
Duplicate of #4829

**Comment by andrewdavidwong** [comment] 2019-04-08 06:32
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-04-08 06:32 UTC
