### ISSUE TITLE
Backport Xen patch for zero-length records in migration v2

### ISSUE THREAD

**Issue by maxdev123** [QubesOS/qubes-issues#2182] opened 2016-07-19 13:23 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): all

---
### General notes: This issue was manifested since R3.1. I tried all possible available updates

[cpuinfo.txt](https://github.com/QubesOS/qubes-issues/files/371514/cpuinfo.txt)
[dmesg.txt](https://github.com/QubesOS/qubes-issues/files/371513/dmesg.txt)
[dmesg_xen.txt](https://github.com/QubesOS/qubes-issues/files/371517/dmesg_xen.txt)
[libxl-driver.log.txt](https://github.com/QubesOS/qubes-issues/files/371518/libxl-driver.log.txt)
[lspci.txt](https://github.com/QubesOS/qubes-issues/files/371515/lspci.txt)
[xsession-errors.txt](https://github.com/QubesOS/qubes-issues/files/371516/xsession-errors.txt)

(current-testing, unstable)  

---

**Comment by andrewdavidwong** [comment] 2016-07-19 17:40
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.

**Comment by andrewdavidwong** [comment] 2016-07-19 17:44
Also: In case this happens to be a duplicate of #2125, please try starting your DVM template and shutting it down before launching a DispVM.

**Comment by maxdev123** [comment] 2016-07-19 19:24
I already saw the issue #2125 but the problem seem different. In particular in file libxl-driver.log.txt you can notice this line:

 xc: error: X86_PV_VCPU_MSRS record truncated: length 8, min 9: Internal error

**Comment by andrewdavidwong** [comment] 2016-07-19 20:34
Please send this to `qubes-users`, at least at first. This is probably a problem somewhat unique to you rather than a bug (since many other people have no problem starting DispVMs). But if it turns out to be a bug, we can reopen this or create a new issue for it. We don't have enough information yet to make a useful ticket.

**Comment by marmarek** [comment] 2016-07-25 12:29
Fix is already discussed on xen-devel in thread "Fix issues with zero-length records in migration v2"

**Comment by maxdev123** [comment] 2016-07-25 12:51
As reported to xen-devel the patches resolve my issue. I attach patch to include the zero-length patches  in qubes-builder-vmm.git (for qubes-builder the patch does apply in  /path/to/qubes-builder/qubes-src/vmm-xen ). Consider 
[zero-length-stream-v2.patch.txt](https://github.com/QubesOS/qubes-issues/files/381524/zero-length-stream-v2.patch.txt)

this patch as experimental/start point.

**Comment by marmarek** [comment] 2016-07-25 13:23
I'd wait for patch being committed to xen-unstable, then backport it to our version.

**Comment by andrewdavidwong** [comment] 2016-07-26 03:50
(Took my best guess at a more descriptive issue title.)

**Comment by andrewdavidwong** [comment] 2019-04-01 04:11
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Closed by andrewdavidwong** 2019-04-01 04:11 UTC
Labels: C: Xen, P: major, T: bug
