### ISSUE TITLE
Installation of Qubes R4.0.4 fails

### ISSUE THREAD

**Issue by hgoumner** [QubesOS/qubes-issues#7030] opened 2021-11-01 14:55 UTC
### Qubes OS release

Qubes R4.0.4

### Brief summary

The booting/installation process fails before any installation menu is shown. See screenshot below:

![IMG_20211101_153857](https://user-images.githubusercontent.com/11947421/139690807-8cc0bae2-62ec-4fba-8091-551e3485c02e.jpg)

### Steps to reproduce

Current setup: Dell Optiplex 9020 with Ubuntu 20.04

1. Download the Qubes R4.0.4 iso and copy it onto a USB drive.

2. Set booting setting to boot from USB.

3. Boot.

### Expected behavior

Installation menu is shown to continue with the installation.

### Actual behavior

System shows error in screenshot and hangs there.

-----------------------------------------------------------------------------------------------

Thanks in advance.

**Comment by tokideveloper** [comment] 2021-11-01 16:47
Maybe the ISO image on your USB drive is broken. You should

- verify that the ISO image on the USB drive is a copy of the Qubes R4.0.4 ISO image and
- repair the ISO image on the USB drive if needed.

If you like, you could use my tool [ddpolymerase](https://codeberg.org/tokideveloper/ddpolymerase/) in order to do so.

**Comment by tokideveloper** [comment] 2021-11-02 12:40
@hgoumner Hint: If you want to use my tool, you should build it from source to make it work.

On the other hand, at least the verification step can be easily done via the following steps (on a Linux system).

First, open a terminal and change to the directory where the `Qubes-R4.0.4-x86_64.iso` file is.

Second, make a copy of your USB drive of the size of the `Qubes-R4.0.4-x86_64.iso` file (make sure `usb_drive.iso` is not an already existent file (otherwise it will be overridden) and replace `/dev/sdX` with your USB drive device name):

```
sudo dd bs=1 count=5199888384 if=/dev/sdX of=usb_drive.iso
```

(This may take a while.)

Third, compare both images:

```
diff usb_drive.iso Qubes-R4.0.4-x86_64.iso
```

If there is no output then the images are the same and thus on your USB drive is indeed a copy of the `Qubes-R4.0.4-x86_64.iso` image, which is good. Otherwise not.

As a last step, you can remove the file `usb_drive.iso`:

```
sudo rm usb_drive.iso
```

**Comment by hgoumner** [comment] 2021-11-02 12:46
Hello again,

thanks a lot for the quick replies. You were right that it was an issue with the USB drive. The diff showed me that the isos don't match. When i tried formatting it to copy over the Qubes OS again, it threw an error and now the drive is no longer usable. I will get a new one and try again.

Thanks again for the help :)

**Comment by tokideveloper** [comment] 2021-11-02 16:19
No problem. Good luck!

**Comment by andrewdavidwong** [comment] 2021-11-03 05:03
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2021-11-03 05:03 UTC
Labels: T: bug, C: installer, P: default, hardware support, diagnosed

**Comment by sjvudp** [comment] 2022-02-17 13:22
> sudo dd bs=1 count=5199888384 if=/dev/sdX of=usb_drive.iso

Actually there's a way to do it without a temporary file:
Say Qubes-R4.1.0-x86_64.iso has size 5954863104 (equals 90864 * 64kB), then you can use this command:
`sudo dd if=/dev/sda bs=64k count=90864 | diff --binary - Qubes-R4.1.0-x86_64.iso`

Despite of saving space and time, the command aborts as soon as a difference was found.
