### ISSUE TITLE
Strange window behaviour in Vault vm - works on primary monitor, malfunctions on other.

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#6846] opened 2021-08-22 11:24 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

I use an external monitor (primary; eye-height) on an x230 laptop (secondary screen) docked on desk.

Applications in **Vault** do not work properly on the laptop screen. Have tried KeePassXC and (without network of course) Firefox.

On secondary monitor, applications lose _almost_ all response to mouse clicks, i.e. no menu bar item, no right-click menus. But - e.g. in KeePassXC - a double-click can still open an entry for edit, can enter search text field. The applications aren't frozen.

Some menu items display this when neighboring items don't: e.g. when KeepassXC database is locked, menu will only respond to "Group", all greyed out, and only display that on the bottom of the primary monitor. Not responsive at all when database is unlocked.

Behavior ceases when _all_ of the window is moved to the external/primary monitor. (A little bit in the laptop screen-> acts funny again).

I make a confession - have I read about / seen this before? Can't see it. But passwords its important so I will post.

Possibly related: Around the same time a few days ago in a _different_ AppVM (networked), I noticed flickering boxes appear across Firefox windows. Only a portion of the screen is affected. Sometimes a black box, sometimes a frame. Lasts for a second or less. Number of tabs has been 30-40, about:performance did not indicate problems. 

### Expected behavior

Seamless app behavior across screens.

**Comment by andrewdavidwong** [comment] 2021-08-22 19:15
Possible duplicate of: #3253

**Comment by marmarek** [comment] 2021-08-22 21:21
Take a look at https://www.qubes-os.org/doc/gui-configuration/

**Comment by andrewdavidwong** [comment] 2021-08-23 02:07
> Take a look at https://www.qubes-os.org/doc/gui-configuration/

Does that mean this is not a bug?

**Comment by marmarek** [comment] 2021-08-23 17:18
> Is this the same as a un/plug event for dom0? Could this be causing the memory to be swamped?

Yes. What counts, is the total screen area combined. 1366x768 overlapped with 1680x1050 is still 1680x1050.
I recognize it sounds stupid, but we haven't figure out how to change the allocation dynamically (without restarting VM), and allocating always max amount for all the possible configurations means a lot of memory _in each VM_. So, the default has only a bit of margin...
We should really have some notification when this happens, to point at the right setting, or maybe even ask to adjust it automatically - for the next startup...

**Comment by marmarek** [comment] 2021-08-23 22:46
Is by a chance just with a fedora-34 template? If so, then it may be missing xrandr (https://github.com/QubesOS/qubes-issues/issues/6568#issuecomment-902628229)

**Comment by Ark-of-the-copepod** [comment] 2021-08-24 05:17
yes, the reallocation of videoram seems to have solved the Vault menu problems. Its only been an hour but it looks like the black boxing is gone also. Thank you.

I'm using the Fedora-33 template.

> I recognize it sounds stupid, but we haven't figure out how to change the allocation dynamically (without restarting VM),

OK some things are like that. But I don't understand then why everything is working for me _without_ a restart of the VMs that were causing problems. Last night and today.

For work to do now, a notification with settings change option would be good. Maybe with option to switch off notification as well. Also, is there a `qvm-features` command I miss that tells me what my current videoram setting is? Important to know baseline before experimenting and changing.

Also then it makes sense to have qubes just recognize my monitor setup at boot? And just tell qvm-features what that is for videoram?

For my monitor setup, now I use a shortcut xrandr command. Ctl+arrow = dual monitors, easy. If I am going to have to do this manually or script it I will add the videoram commands. But then important not to have a popup videoram notification as well that can't be turned off.

**Closed** 2023-08-05 09:31 UTC
Labels: T: bug, C: gui-virtualization, P: default, hardware support, needs diagnosis, eol-4.0
