### ISSUE TITLE
Qubes 4.0 will not wake after sleep on ThinkPad W530

### ISSUE THREAD

**Issue by JamesRBrown** [QubesOS/qubes-issues#3411] opened 2017-12-18 17:25 UTC
#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

1) Obtain a ThinkPad W530
2) Install Qubes 4.0-rc3 on it.
3) Boot the system into Qubes 4.0-rc3.
4) Close laptop lid to sleep system.
5) Open the laptop's lid and attempt to wake system.

### Expected behavior:

The expected behavior is that the system will resume after sleep.

### Actual behavior:

There are two behaviors.

1) The system will not wake from sleep, and hard power off is required.

2) The system reboots on wake.

### General notes:

I'm running Qubes OS on 4.0-rc3 on  a ThinkPad W530 and sleep does not work (or perhaps more accurately wake does not work).   When I close the lid, the laptop indicates that it goes to sleep.  Fans turn off, and the sleep light comes on.  However, when I open the lid one of two behaviors occur...

Behavior 1:  The laptop will not wake up.  No amount of pressing keys or tapping the power button will wake the machine.  Everything indicates the system is still in sleep mode, including a pulsing power ring light around the power button.  In order to get the system to respond I have to hold the power button until the system powers down, then power back on.

Behavior 2: I open the lid, the indicator lights flash, and then go dark.  As soon as I press the power button the system POSTs and begins booting.  

NOTE 1: I have attempt to sleep the system about 15 times, and the above is the behavior every time.  I haven't actually witnessed 4.0-rc3 successfully recover from sleep yet. 

NOTE 2: I have a second W530 system, which I have also attempt this on, and witnessed the same behavior.  

NOTE 3: As a point of comparison, when I replace the system drive with another drive (on the same system) containing Qubes release 3.2 R3.2 the system sleeps and wakes just fine.  So this is a problem that's been introduced in the new 4.0 code.  Of the 4.0 releases I have only used 4.0-rc3, so I can't comment on whether this issue has been present through the entire 4.0 release cycle.  Also, between this observation and the one made in NOTE 2 we know this isn't a hardware issue.

---

**Comment by mcspadden** [comment] 2018-01-11 18:03
I too have Behavior 1 on a Dell XPS 15 9560. Running 4.0 RC3 and everytime I close the lid or place it into Suspend mode via my username in the top right, the issue arises. Only a hard reboot will get Qubes running again. Should I submit a new issue because of the difference in devices or can the both exist in this open issue?

**Comment by andrewdavidwong** [comment] 2018-01-12 04:51
> I too have Behavior 1 on a Dell XPS 15 9560. Running 4.0 RC3 and everytime I close the lid or place it into Suspend mode via my username in the top right, the issue arises. Only a hard reboot will get Qubes running again. Should I submit a new issue because of the difference in devices or can the both exist in this open issue?

Until we know more about the cause, it's fine to use the same issue as long as your reproduction steps and observed behavior are otherwise the same (i.e., same except for the hardware difference).

**Comment by molnara** [comment] 2018-01-19 18:05
I am having the exact issue after applying updates from the test repo.  It was working fine before the updates.  My laptop is an Asus Zenbook UX430U

**Comment by marmarek** [comment] 2018-01-19 18:11
I had similar problems on Thinkpad X1 Carbon 5th gen. Adding `iwlmvm` (generally: the wifi driver) to `/rw/config/suspend-module-blacklist` in sys-net solved the problem for me.
What kernel version do you have in dom0? There is 4.14.13 in testing repository, it may help too.

**Comment by molnara** [comment] 2018-01-19 18:18
I had `iwlmvm` and `iwlwifi` already blacklisted and I am using 4.14.13.  Not sure what to do now, is it possible to downgrade a kernel?

**Comment by marmarek** [comment] 2018-01-19 18:31
If you installed 4.0-rc3, you probably have 4.9 kernel still installed, just need to select it in bootloader (in grub there is a menu, for UEFI - edit /boot/efi/EFI/qubes/xen.cfg - `default` setting).
If you don't have it anymore, you can install it this way:

1. `sudo qubes-dom0-update 'kernel-4.9*'` (it will fail at the end, but package will be downloaded)
2. `sudo dnf downgrade 'kernel-4.9*'`

**Comment by molnara** [comment] 2018-01-20 03:32
I can confirm reverting back to kernel 4.9.56-21 now allows me to wake my laptop by opening the lid again.

**Comment by AntK2** [comment] 2018-02-04 00:04
Same issue on thinkpad e470, with 4.0-rc4. I tried blacklisting wlmvm and iwlwifi and downgrading to an older kernel, both had no effect on this issue.

**Comment by JamesRBrown** [comment] 2018-04-20 17:58
I have confirmed that this issue is still present in the Qubes-R4.0-x86_64 release.  

I also performed the steps Marmarek discribed on 1.19.18.

Booting into the 4.9 kernel didn't resolve the issue on my W530.

**Comment by andrewdavidwong** [comment] 2018-04-21 18:59
> I can confirm reverting back to kernel 4.9.56-21 now allows me to wake my laptop by opening the lid again. Is there somewhere I should be reporting this?

Reporting it here as you did is fine. Thanks!

> I have confirmed that this issue is still present in the Qubes-R4.0-x86_64 release.
> 
> I also performed the steps Marmarek discribed on 1.19.18.
> 
> Booting into the 4.9 kernel didn't resolve the issue on my W530.

Thanks for checking!

**Comment by tweidinger** [comment] 2018-06-15 23:50
Having the issue on my end aswell with a T460p and the current 4.0 release.
Is there any more info needed for this issue?

**Comment by SenorFusion** [comment] 2018-06-24 19:17
+1 same here.

I have the most update to date Qubes-stable as of today, but Suspend or Sleep has never worked on any version of 4.0. Thinkpad P70 with Skylake.

- Kernel Flags: i915.alpha_support=1 rd.blacklist.drivers=nouveau nouveau.modeset=0
- Bios:
- --USB UEFI BIOS Support: Enabled
- --UEFI/Legacy Boot: UEFI Only
- --Secure Boot: Disabled

After suspend a hard-reset reboot (hold down physical power button) is require to get Qubes back.

**Comment by Marcosmos747** [comment] 2018-06-27 20:07
I too and experiencing the same thing. i'm using
ROG Strix GL502VS-WS71 15.6" Gaming Laptop Computer; Intel Core i7-7700HQ Processor 2.8GHz; NVIDIA GeForce GTX 1070 8GB GDDR5; 16GB DDR4 RAM; 1TB HDD + 256GB SSD; Microsoft Windows 10 64-bit; Media Card Reader; 10/100/100 Network; 2x2 802.11ac Wireless+Bluetooth 4.1; 15.6" Full HD G-Sync Display.
after a few minutes AFK screen goes black and unresponsive. Idk what to do lol.

**Comment by tweidinger** [comment] 2018-06-28 11:16
Just deactivate the TPM module if you have one, if you can live with this.
(Worked for me)

**Comment by richdbdb** [comment] 2018-08-05 21:52
I have a Thinkpad X1 Carbon Gen 6  and this issue exists on Release 4.0 x86_64. Symptoms are exactly as OP described. Manually putting the laptop into sleep or closing the lid will cause suspend from which no action can wake it. 

I have tried:

Disabling TPM, no fix

Adding iwlmvm and iwlwifi to suspend blacklist in sys-net, no fix

I will try downgrading kernel and report back.

**Comment by SenorFusion** [comment] 2018-09-20 18:17
For anyone following this issue - Some progress has been made over in the Qubes-user group.

https://groups.google.com/forum/#!msg/qubes-users/TmGDlkluJgM/fn4wc2E5CQAJ

Related: #3689

**Comment by bigdx** [comment] 2018-12-11 10:10
Same here with a T440s. Most times wakes up from suspend (after lid was closed and reopened) as it should, but sometimes screen stays black and then reboots. Haven't found out yet what is different when this happens.
TPM is already disabled and the T440s has no USB Type-C (as mentioned in #3689).

**Comment by AlexanderMint** [comment] 2019-09-09 18:43
+1 same here, dell 5390, qubes 4.0.2-rc1

**Comment by lucaszanella** [comment] 2019-10-08 16:47
same here, qubes 4.0.1, Razer Blade Stealth 2016

**Comment by dadelpe** [comment] 2020-01-29 17:11
Lenovo Carbon X1 Gen 6 last BIOS version n23ur22w
Changed option: Config -> Power -> Sleep State -> Linux and activated Thunderbolt assist. Fixed the Sleep function. Qubes Release 4.0.3 and 5.4.10-1 kernel version.

**Comment by nakoo** [comment] 2020-05-26 02:13
Same issue here. Suspend hasn’t been working. I have to do hard power-off. I tried (1)Disabling TPM (2)Adding iwlmvm and iwlwifi to suspend blacklist (3)Blocking sleep . None of them has been worked.

XPS 9570 (4K + 1050Ti)
BIOS Version: 1.16.2 (latest)

**Comment by Pmonf** [comment] 2020-07-06 14:32
I recently installed Qubes 4.0.3 on a new Thinkpad E15 Intel i-5-10210U with 16GB ram with a 512SSD and a 1T drive. The installation was on the SSD. I had two failures on installation (wiping the pesky windoze) both times while entering the user password. Error was "unexpected error". I did not report it and selected "quit". I then decided to try installing LM 19.2 and then see if Qubes would install over that. It worked! Qubes is the only os installed and it is on the 512SSD.

Everything seems to work so far, except:

1. The apparently common problem of not resuming after suspend, and having to button off to shut down. I have not tried hibernate yet.

2. The touchpad and mouse cursor does not move smoothly across the screen. It hops. It was necessary to select a larger windows scheme in order to have a bigger target for the cursor's inprecise movements. Not sure if this may be a memory problem or how to fix it. If anyone knows I would like to hear it.

I would like to thank Marek and Marta for the great article on the coming Qubes 4.1 and the GUI dom.

**Comment by andrewdavidwong** [comment] 2020-07-07 11:05
> I recently installed Qubes 4.0.3 on a new Thinkpad E15 Intel i-5-10210U with 16GB ram with a 512SSD and a 1T drive. The installation was on the SSD. I had two failures on installation (wiping the pesky windoze) both times while entering the user password. Error was "unexpected error". I did not report it and selected "quit". I then decided to try installing LM 19.2 and then see if Qubes would install over that. It worked! Qubes is the only os installed and it is on the 512SSD.
> 
> Everything seems to work so far, except:
> 
> 1. The apparently common problem of not resuming after suspend, and having to button off to shut down. I have not tried hibernate yet.
> 2. The touchpad and mouse cursor does not move smoothly across the screen. It hops. It was necessary to select a larger windows scheme in order to have a bigger target for the cursor's inprecise movements. Not sure if this may be a memory problem or how to fix it. If anyone knows I would like to hear it.
> 
> I would like to thank Marek and Marta for the great article on the coming Qubes 4.1 and the GUI dom.

Thanks for the feedback, @Pmonf! However, typically feedback like this should be sent in the form of a [Hardware Compatibility List (HCL)](https://www.qubes-os.org/hcl/) report (see [What is the HCL?](https://www.qubes-os.org/doc/hcl/) and [How do I submit an HCL report?](https://www.qubes-os.org/doc/hcl/#generating-and-submitting-new-reports)). Please consider submitting this as an HCL report now!

P.S. -- Xen does not support hibernation, so there is no need to try that.

**Comment by atanasantonov** [comment] 2021-01-06 20:59
Same here. Qubes 4.0.3 on Lenovo Thinkpad T460p with Intel i7 6820HQ and  32GB RAM. Interesting is that on T460 with i5 there are no issues, so that was surprising.

**Comment by JamesRBrown** [comment] 2021-04-07 01:45
It's been two and a half years since my initial report, and this issue is still present in the latest builds (just tested with R4.0.4, computers sleeps, and reboots on wake).  Is this just not fixable?  (Odd since it wasn't an issue in R3.2.)  It's unfortunate, since this is basically a complete show stopper.

**Comment by gw0** [comment] 2021-06-10 01:18
> @nakoo Same issue here. Suspend hasn’t been working. I have to do hard power-off. I have tried (1)Disabling TPM (2)Adding iwlmvm and iwlwifi to suspend blacklist (3)Blocking sleep. None of them has been worked. DELL XPS 9570 (4K + 1050Ti)

For Dell XPS 15 I had to make the following adjustments (mentioned on https://www.qubes-os.org/hcl/): "To boot the installer, you need to remove mapbs=1 and noexitboot=1. To get suspend to work, you need to add mem_sleep_default=deep to the kernel= line in /boot/efi/EFI/qubes/xen.cfg."

**Comment by nakoo** [comment] 2021-06-10 09:34
> > @nakoo Same issue here. Suspend hasn’t been working. I have to do hard power-off. I have tried (1)Disabling TPM (2)Adding iwlmvm and iwlwifi to suspend blacklist (3)Blocking sleep. None of them has been worked. DELL XPS 9570 (4K + 1050Ti)
> 
> For Dell XPS 15 I had to make the following adjustments (mentioned on https://www.qubes-os.org/hcl/): "To boot the installer, you need to remove mapbs=1 and noexitboot=1. To get suspend to work, you need to add mem_sleep_default=deep to the kernel= line in /boot/efi/EFI/qubes/xen.cfg."
> 
> I believe the ThinkPad issue is different.

Thanks a lot. I will try it sooner and will post the result here!

**Comment by andrewdavidwong** [comment] 2023-04-07 22:48
Is this still a problem in 4.1?

**Comment by Pmonf** [comment] 2023-04-12 21:32
I no longer have a problem with suspend or the cursor movement. Thanks.

**Comment by andrewdavidwong** [comment] 2023-04-12 23:29
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Closed by andrewdavidwong** 2023-04-12 23:29 UTC
Labels: T: bug, P: major, hardware support, needs diagnosis, C: power management
