### ISSUE TITLE
Appmenus not syncing for Debian 10 Standalone VMs

### ISSUE THREAD

**Issue by roasting223** [QubesOS/qubes-issues#5999] opened 2020-08-14 12:37 UTC
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qvm-sync-appmenus for Standalone VMs and the reverse triggers in Standalone VMs when installing packages

**Brief summary**
I have a number of Debian 10 Standalone VMs that were restored from a backup (original system also Qubes 4.0). All these VMs can't sync App menus to dom0 since being restored. Before it worked fine.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. run qvm-sync-appmenus <Name of Standalone Debian 10 VM> in dom0
or _2. install / remove packge in the VM

**Expected behavior**
Dom0 is able to get App menus from Standalone VMs and ist also notified correctly about changes in the menus.

**Actual behavior**
_1.  qvm-sync-appmenus yields
```
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.20', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 397, in main
    new_appmenus = retrieve_appmenus_templates(vm, use_stdin=use_stdin)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 373, in retrieve_appmenus_templates
    new_appmenus = get_appmenus(vm if not use_stdin else None)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 155, in get_appmenus
    "Error getting application list")
qubesadmin.exc.QubesException: Error getting application list

```
_2.  installing, uninstalling or updating packages in the VM yields

```
[...]
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for qubes-core-agent (4.0.56-1+deb10u1) ...
execv: Permission denied
Processing triggers for desktop-file-utils (0.23-4) ...

```

**Additional context**
For newly created Debian 10 Standalone VMs it works fine. Not an option in this case though.

**Solutions you've tried**

`qvm-appmenus --update --force <vm_name>`

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/managing-appvm-shortcuts/

**Comment by marmarek** [comment] 2020-08-14 18:32
What permissions on `/etc/qubes-rpc/qubes.GetAppmenus` do you have? should be 755

**Comment by roasting223** [comment] 2020-08-14 18:42
it is 755

**Comment by marmarek** [comment] 2020-08-14 18:51
Try to run it, you should get a lot of output about installed applications.

**Comment by roasting223** [comment] 2020-08-14 19:05
Sorry, forget my last answer, i looked in dom0 and confused it with qubes.SyncAppMenus.
qubes.GetAppmenus was actually 644. Setting it to 755 worked. Thank you! This must have somehow happened in the restore process then as I could never sync menus after restoring.
Should all files in that directory be 755? There are some more with 644:

644 qubes.Backup
755 qubes.ConnectTCP
644 qubes.DetachPciDevice
644 qubes.Filecopy
755 qubes.GetAppmenus
755 qubes.GetDate
644 qubes.GetImageRGBA
755 qubes.Gpg
755 qubes.GpgImportKey
755 qubes.InstallUpdatesGUI
644 qubes.OpenInVM
755 qubes.OpenURL
777 qubes.PdfConvert
755 qubes.PostInstall
755 qubes.ResizeDisk
644 qubes.Restore
755 qubes.SaltLinuxVM
644 qubes.SelectDirectory
644 qubes.SelectFile
644 qubes.SetDateTime
777 qubes.SetMonitorLayout
755 qubes.ShowInTerminal
755 qubes.StartApp
644 qubes.SuspendPost
755 qubes.SuspendPostAll
644 qubes.SuspendPre
755 qubes.SuspendPreAll
644 qubes.SyncNtpClock
755 qubes.UpdatesProxy
755 qubes.VMRootShell
644 qubes.VMShell
644 qubes.WaitForSession

**Comment by marmarek** [comment] 2020-08-14 20:23
It was like this in some older version, but should not be anymore if you have all updates installed (all should be 755).

**Comment by roasting223** [comment] 2020-08-14 20:38
okay, strange, since all updates are installed. i replaced the whole folder with a correct one from another debian template. thank you!

**Comment by andrewdavidwong** [comment] 2020-08-15 07:03
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-08-15 07:03 UTC
Labels: C: desktop-linux, P: default, T: bug, diagnosed
