### ISSUE TITLE
Intermittent system freezes followed by reboot with kernel-latest 

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5272] opened 2019-08-25 00:47 UTC
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

`kernel-latest` package in dom0

---

### Steps to reproduce the behavior:

Install `kernel-latest` in dom0

### Expected or desired behavior:

System is stable

### Actual behavior:

The system intermittently freezes entirely, followed by a hard reset.

### General notes:

The reset is probably due to the watchdog timer expiring, causing the motherboard hardware to reset the processor.  My system is a Lenovo P51.

The default dom0 kernel (`kernel` package) works fine.

Due to the nature of the failure, I do not have a stack trace or crash dump.

---

**Comment by dnalok** [comment] 2019-09-11 01:54
Hello, I'm writing to confirm this is an issue I'm having with Qubes Release 4.0.1.

My laptop had no issues booting 4.14.74-1 that ships with the Stable Release; however once I update Dom0 to current repo kernel 4.19.67-1 or kernel-latest 5.2.11-1 booting fails or the shutdown command causes the system to freeze.

Boot will act normally all the way up until the Account Management service starts for the login page and then the computer will restart.

When I am able to login to the desktop, the system runs normally but freezes instantly when the shutdown command is issued.

I have tried everything I could find in Qubes Docs / Online by updating to kernel-latest, adjusting memory options, and shutting down VMs before shutting down the system. Unfortunately I'm at a loss after hours of guessing games due to the nature of kernel panic. It's most likely my hardware.

My system boots and shuts down normally with kernel 4.14.74-1. Is there anyway to configure the Grub Boot Menu to automatically boot this older kernel instead of the latest installed on my system which leads to a crash? Grub.cfg cannot be edited normally.

This is my first post ever, and I didn't want to write up a duplicate. I understand I may not get feedback but hopefully someone may have a suggestion about the boot menu customization. Thanks so much! 

System Specifications:
MSI PL62 7RC-001
Processor:
Intel Core i7-7700HQ (Intel Core i7)
Graphics adapter:
NVIDIA GeForce MX150 - 2048 MB, GDDR5
Mainboard:
Intel HM175
Connections:
1 USB 2.0, 2 USB 3.0 / 3.1 Gen1, 1 HDMI, 1 DisplayPort, Audio Connections: 3.5mm, Card Reader: SD, USB 3.0 Type-C
Networking:
Qualcomm Atheros AR8171/8175 PCI-E Gigabit Ethernet (10/100/1000/2500/5000MBit/s), Intel Dual Band Wireless-AC 3168 (a/b/g/n = Wi-Fi 4/ac = Wi-Fi 5), Bluetooth 4.0

**Comment by andrewdavidwong** [comment] 2019-09-12 04:08
@dnalok: Thanks for your report. To get additional help with your specific situation, please consider writing to `qubes-users` [mailing list](https://www.qubes-os.org/support/).

**Comment by awokd** [comment] 2019-09-16 10:57
@DemiMarie What CPU & chipset is that Lenovo?

**Comment by zidz** [comment] 2019-09-20 09:04
I experience the same thing on the latest kernel, freeze when login screen appears. If I'm fast I may login but computer freezes shortly after the login in that case. Hard reset is required. 
Lenovo ThinkPad T480
CPU: Intel i7 8550U

**Comment by dnalok** [comment] 2019-09-20 17:04
ISSUE RESOLVED UPDATE: 

Well I figured out the issue on my end. I had to disable the Nouveau driver by blacklisting it permanently as per the Qubes Doc here:

https://www.qubes-os.org/doc/nvidia-troubleshooting/

All kernels: current and current-latest; are running smoooooth; no crashes.

If anyone here has an Nvidia Dedicated Card on their rig and having this problem I would try it.

**Comment by evadogstar** [comment] 2019-09-20 20:37
I have the same problem with freeze after login screen with all new kernels. The same proccessor as mention before Intel i7 8550U

@dnalok I have Nvidia on board the main GPU is intel. 

https://www.qubes-os.org/doc/nvidia-troubleshooting/ 

This instruction does not have details about how to disable Nouveau driver with UEFI boot.

**Comment by awokd** [comment] 2019-09-20 21:56
@dnalok Did you only need to add `rd.driver.blacklist=nouveau`, or all three options?

**Comment by evadogstar** [comment] 2019-09-21 08:14
@awokd it remains to find out what options to add exactly and what disadvantages to make this.
p.s. is this mean that qubes installer will not work for me in the future and new installation with new kernel also will have problem?

**Comment by awokd** [comment] 2019-09-21 12:08
@evadogstar New kernels might fix the crash, but if not and those options help your system you would want to modify your new installer with https://www.qubes-os.org/doc/uefi-troubleshooting/#change-installer-kernel-parameters-in-uefi.

**Comment by evadogstar** [comment] 2019-09-22 17:04
@awokd I can confirm that with `nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off` system boot without troubles with newer kernel > than `4.14.116-1`

_By the way, now qubes-dom0-update show new update with new kernel, but this update want to remove `4.14.116-1` what I can do with this to keep it?_

**Comment by awokd** [comment] 2019-09-22 18:38
@evadogstar Items not directly related to this issue might be better handled on the mailing list, but I am glad @dnalok's options helped! Anyways, if you want to keep the old kernel around, delete the second oldest before updating:
~~~
dnf list installed | grep kernel
[locate the "middle"/second oldest version number and replace in the next two lines]
sudo dnf remove kernel-4.19.47-1.pvops.qubes
sudo dnf remove kernel-qubes-vm-4.19.47-1.pvops.qubes
sudo qubes-dom0-update
~~~

**Comment by dnalok** [comment] 2019-09-22 20:20
> @awokd it remains to find out what options to add exactly and what disadvantages to make this.
> p.s. is this mean that qubes installer will not work for me in the future and new installation with new kernel also will have problem?

"nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off" options added to:
GRUB_CMDLINE_LINUX:
Via:
cd /etc/default/
sudo nano grub
For Legacy Boot

Unfortunately, I'm unaware of any issues this may case. Glad it worked for you though. 


> @dnalok Did you only need to add `rd.driver.blacklist=nouveau`, or all three options?
> @evadogstar To add options to UEFI:
> 
>     * dom0 terminal
> 
>     * sudo nano /boot/efi/EFI/qubes/xen.cfg
> 
>     * locate the three `kernel=` lines and add your option(s) towards the end of them, after `rhgb quiet`
> 
>     * `ctrl-x`, `y` to save changes
> 
>     * reboot

All three options to the grub boot config. "nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off"

**Comment by gnu3ra** [comment] 2020-07-29 01:50
It should be noted that I am experiencing this issue without an nvidia discrete GPU. I have an i7-10710U and am running off the iGPU. Roughly once every two days I get a system lockup and reset, which did not happen on kernels earlier than 5.4 (roughly)

**Comment by gnu3ra** [comment] 2020-08-09 02:11
I managed to capture logs for the failure I was experiencing by disabling panic_on_oops with `echo 0 > /proc/sys/kernel/panic_on_oops` This may or may not be related though. Dmesg shows

```
Jul 31 10:14:34 dom0 kernel: i915 0000:00:02.0: HDMI-A-1: EDID is invalid:
Jul 31 10:14:34 dom0 kernel:         [00] BAD  00 ff ff ff ff ff ff 00 ff ff 00 00 59 3a 3a 67
Jul 31 10:14:34 dom0 kernel:         [00] BAD  00 00 01 01 01 01 01 01 00 00 16 01 01 03 03 80
Jul 31 10:14:34 dom0 kernel:         [00] BAD  29 29 17 78 78 2a 2a 5d b5 b5 a3 59 59 53 53 a0
Jul 31 10:14:34 dom0 kernel:         [00] BAD  27 27 10 50 50 54 a5 a5 46 46 00 01 01 01 01 01
Jul 31 10:14:34 dom0 kernel:         [00] BAD  01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01
Jul 31 10:14:34 dom0 kernel:         [00] BAD  01 01 01 01 01 66 21 21 50 b0 b0 51 51 00 1b 1b
Jul 31 10:14:34 dom0 kernel:         [00] BAD  30 40 40 70 36 36 00 00 9a e6 e6 10 00 00 00 00
Jul 31 10:14:34 dom0 kernel:         [00] BAD  1e 64 64 19 00 00 40 40 41 00 00 26 30 30 18 88
Jul 31 10:14:35 dom0 kernel: [drm:drm_dp_dual_mode_detect [drm_kms_helper]] *ERROR* Unexpected DP dual mode adaptor ID 50
Jul 31 10:14:36 dom0 kernel: BUG: unable to handle page fault for address: ffff888140222900
Jul 31 10:14:36 dom0 kernel: #PF: supervisor read access in kernel mode
Jul 31 10:14:36 dom0 kernel: #PF: error_code(0x0000) - not-present page
Jul 31 10:14:36 dom0 kernel: PGD 260c067 P4D 260c067 PUD 6a155067 PMD 6a153067 PTE 0
Jul 31 10:14:36 dom0 kernel: Oops: 0000 [#1] SMP NOPTI
Jul 31 10:14:36 dom0 kernel: CPU: 3 PID: 4557 Comm: Xorg Tainted: G        W         5.7.10-1.qubes.x86_64 #1
Jul 31 10:14:36 dom0 kernel: Hardware name: LENOVO 20R1S04100/20R1S04100, BIOS N2QET29P (1.23 ) 07/02/2020
Jul 31 10:14:36 dom0 kernel: RIP: e030:connector_bad_edid+0x55/0x170 [drm]
Jul 31 10:14:36 dom0 kernel: Code: c7 44 24 04 00 00 00 00 48 c7 44 24 0c 00 00 00 00 c7 44 24 14 00 00 00 00 c1 e2 07 48 63 d2 48 8d 04 16 48 8d 4c 16 7f 31 d2 <02> 10 48 83 c0 01 48 39 c8 75 f5 8b 87 24 04 00 00 f7 da 88 97 29
Jul 31 10:14:36 dom0 kernel: RSP: e02b:ffffc9000239fae8 EFLAGS: 00010246
Jul 31 10:14:36 dom0 kernel: RAX: ffff888140222900 RBX: ffff888140221d00 RCX: ffff88814022297f
Jul 31 10:14:36 dom0 kernel: RDX: 0000000000000000 RSI: ffff888140221d00 RDI: ffff88818b5f9000
Jul 31 10:14:36 dom0 kernel: RBP: 0000000000000001 R08: 0000000000000003 R09: 000000000000000a
Jul 31 10:14:36 dom0 kernel: R10: ffffc9000239fb38 R11: 0000000000000000 R12: ffff888140221d00
Jul 31 10:14:36 dom0 kernel: R13: ffff88818b5f9000 R14: ffffffffc0100f80 R15: ffff888188c00e78
Jul 31 10:14:36 dom0 kernel: FS:  00007b92434b6a40(0000) GS:ffff8881956c0000(0000) knlGS:0000000000000000
Jul 31 10:14:36 dom0 kernel: CS:  e030 DS: 0000 ES: 0000 CR0: 0000000080050033
Jul 31 10:14:36 dom0 kernel: CR2: ffff888140222900 CR3: 000000017a1c8000 CR4: 0000000000040660
Jul 31 10:14:36 dom0 kernel: Call Trace:
Jul 31 10:14:36 dom0 kernel:  ? drm_edid_get_monitor_name+0xa0/0xa0 [drm]
Jul 31 10:14:36 dom0 kernel:  drm_do_get_edid+0x2f2/0x300 [drm]
Jul 31 10:14:36 dom0 kernel:  drm_get_edid+0x57/0x3b0 [drm]
Jul 31 10:14:36 dom0 kernel:  intel_hdmi_set_edid+0x4a/0x290 [i915]
Jul 31 10:14:36 dom0 kernel:  intel_hdmi_detect+0xcb/0xf0 [i915]
Jul 31 10:14:36 dom0 kernel:  drm_helper_probe_single_connector_modes+0xe7/0x6e0 [drm_kms_helper]
Jul 31 10:14:36 dom0 kernel:  drm_mode_getconnector+0x421/0x450 [drm]
Jul 31 10:14:36 dom0 kernel:  ? _cond_resched+0x16/0x40
Jul 31 10:14:36 dom0 kernel:  ? _cond_resched+0x16/0x40
Jul 31 10:14:36 dom0 kernel:  ? drm_connector_property_set_ioctl+0x70/0x70 [drm]
Jul 31 10:14:36 dom0 kernel:  drm_ioctl_kernel+0xb6/0x100 [drm]
Jul 31 10:14:36 dom0 kernel:  drm_ioctl+0x308/0x390 [drm]
Jul 31 10:14:36 dom0 kernel:  ? drm_connector_property_set_ioctl+0x70/0x70 [drm]
Jul 31 10:14:36 dom0 kernel:  ksys_ioctl+0x92/0xb0
Jul 31 10:14:36 dom0 kernel:  __x64_sys_ioctl+0x16/0x20
Jul 31 10:14:36 dom0 kernel:  do_syscall_64+0x5b/0x1d0
Jul 31 10:14:36 dom0 kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Jul 31 10:14:36 dom0 kernel: RIP: 0033:0x7b9240b4f6a7
Jul 31 10:14:36 dom0 kernel: Code: 00 00 00 48 8b 05 e1 27 2c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 2e 0f 1f 84 00 00 00 00 00 b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d b1 27 2c 00 f7 d8 64 89 01 48
Jul 31 10:14:36 dom0 kernel: RSP: 002b:00007ffd15d0f908 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Jul 31 10:14:36 dom0 kernel: RAX: ffffffffffffffda RBX: 0000000001a133b0 RCX: 00007b9240b4f6a7
Jul 31 10:14:36 dom0 kernel: RDX: 00007ffd15d0f950 RSI: 00000000c05064a7 RDI: 000000000000000e
Jul 31 10:14:36 dom0 kernel: RBP: 00007ffd15d0f950 R08: 000000000000ffff R09: 00007ffd15de3080
Jul 31 10:14:36 dom0 kernel: R10: 00007ffd15d0f8e0 R11: 0000000000000246 R12: 00000000c05064a7
Jul 31 10:14:36 dom0 kernel: R13: 000000000000000e R14: 00000000c05064a7 R15: 0000000001a13230
Jul 31 10:14:36 dom0 kernel: Modules linked in: loop ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter vfat fat btrfs blake2b_generic xor raid6_pq snd_soc_skl_hda_dsp snd_hda_codec_hdmi snd_soc_hdac_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_soc_dmic snd_sof_pci snd_sof_intel_byt snd_sof_intel_ipc snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_xtensa_dsp snd_sof_intel_hda snd_sof iTCO_wdt mei_hdcp iTCO_vendor_support snd_soc_skl intel_rapl_msr snd_soc_sst_ipc snd_soc_sst_dsp snd_hda_ext_core snd_soc_acpi_intel_match snd_soc_acpi intel_wmi_thunderbolt wmi_bmof joydev snd_soc_core snd_compress ac97_bus snd_pcm_dmaengine hid_multitouch snd_hda_intel x86_pkg_temp_thermal intel_powerclamp coretemp snd_intel_dspcfg rapl snd_hda_codec snd_hda_core snd_hwdep pcspkr snd_seq iwlwifi snd_seq_device e1000e snd_pcm i2c_i801 snd_timer mei_me thunderbolt cfg80211 mei idma64 processor_thermal_device ucsi_acpi intel_rapl_common typec_ucsi intel_soc_dts_iosf typec wmi thinkpad_acpi ledtrig_audio
Jul 31 10:14:36 dom0 kernel:  snd soundcore rfkill int3403_thermal int340x_thermal_zone pinctrl_cannonlake pinctrl_intel acpi_tad int3400_thermal acpi_thermal_rel xen_acpi_processor xenfs ip_tables dm_thin_pool dm_persistent_data libcrc32c dm_bio_prison dm_crypt i915 crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel video i2c_algo_bit cec serio_raw drm_kms_helper nvme xhci_pci drm xhci_hcd nvme_core i2c_hid xen_privcmd xen_pciback xen_blkback xen_gntalloc xen_gntdev xen_evtchn uinput
Jul 31 10:14:36 dom0 kernel: CR2: ffff888140222900
Jul 31 10:14:36 dom0 kernel: ---[ end trace 3474ff0239422498 ]---
Jul 31 10:14:36 dom0 kernel: RIP: e030:connector_bad_edid+0x55/0x170 [drm]
Jul 31 10:14:36 dom0 kernel: Code: c7 44 24 04 00 00 00 00 48 c7 44 24 0c 00 00 00 00 c7 44 24 14 00 00 00 00 c1 e2 07 48 63 d2 48 8d 04 16 48 8d 4c 16 7f 31 d2 <02> 10 48 83 c0 01 48 39 c8 75 f5 8b 87 24 04 00 00 f7 da 88 97 29
Jul 31 10:14:36 dom0 kernel: RSP: e02b:ffffc9000239fae8 EFLAGS: 00010246
Jul 31 10:14:36 dom0 kernel: RAX: ffff888140222900 RBX: ffff888140221d00 RCX: ffff88814022297f
Jul 31 10:14:36 dom0 kernel: RDX: 0000000000000000 RSI: ffff888140221d00 RDI: ffff88818b5f9000
Jul 31 10:14:36 dom0 kernel: RBP: 0000000000000001 R08: 0000000000000003 R09: 000000000000000a
Jul 31 10:14:36 dom0 kernel: R10: ffffc9000239fb38 R11: 0000000000000000 R12: ffff888140221d00
Jul 31 10:14:36 dom0 kernel: R13: ffff88818b5f9000 R14: ffffffffc0100f80 R15: ffff888188c00e78
Jul 31 10:14:36 dom0 kernel: FS:  00007b92434b6a40(0000) GS:ffff8881956c0000(0000) knlGS:0000000000000000
Jul 31 10:14:36 dom0 kernel: CS:  e030 DS: 0000 ES: 0000 CR0: 0000000080050033
Jul 31 10:14:36 dom0 kernel: CR2: ffff888140222900 CR3: 000000017a1c8000 CR4: 0000000000040660
```
when the failure happens. At that time the screen blacks out and I cannot get back to x11.

**Comment by DemiMarie** [comment] 2021-06-28 15:18
This problem has since gone away for me.  Should this issue be closed?

**Comment by andrewdavidwong** [comment] 2021-06-28 16:16
Closing for now. If anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-06-28 16:16 UTC
Labels: C: kernel, P: default, T: bug, needs diagnosis
