### ISSUE TITLE
notifications do not respect xfce panel position

### ISSUE THREAD

**Issue by dzklaim** [QubesOS/qubes-issues#2820] opened 2017-05-19 16:10 UTC
#### Qubes OS version (e.g., `R3.2`):

R3.2

 Notifications from AppVms do not respect the position of the xfce panel creating an inconsistent experience. (of course, this does not happen with the notifications from dom0).

not a fix but if Qubes provides a default xfce setup (see https://github.com/QubesOS/qubes-issues/issues/2531) at least the notifications could be positioned opposite to the xfce panel (for example: panel -> bottom notifications -> top).

**Comment by marmarek** [comment] 2017-05-19 16:17
Maybe it's not obvious, but this is a duplicate of #889

**Closed by marmarek** 2017-05-19 16:17 UTC

**Comment by dzklaim** [comment] 2017-05-19 16:19
ah thanks :)
