### ISSUE TITLE
Bash errors in all Terminals after recent updates

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1351] opened 2015-10-21 04:05 UTC
I recently ran a bunch of updates in all my template VMs as well as the dom0 updates. However, now I am noticing the following error in all my Fedora related AppVMs (even Fedora StandaloneVMs) when launching a Terminal

```
bash: export: `BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`': not a valid identifier
bash: export: `}': not a valid identifier
bash: export: `BASH_FUNC_scl()=() {  local CMD=$1;': not a valid identifier
bash: export: `if [ "$CMD" = "load" -o "$CMD" = "unload" ]; then': not a valid identifier
bash: export: `eval "module $@";': not a valid identifier
bash: export: `/usr/bin/scl "$@";': not a valid identifier
bash: export: `}': not a valid identifier
```

Curiously, none of my Debian 8 templates are showing this sort of error!

**Comment by marmarek** [comment] 2015-10-21 09:58
Duplicate of #1350

**Closed by marmarek** 2015-10-21 09:58 UTC
