### ISSUE TITLE
DispVM: use XfceTerminal or LXTerminal by default

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5601] opened 2020-01-26 13:55 UTC
**The problem you're addressing (if any)**
xterm lacks many necessary features

**Describe the solution you'd like**
use XfceTerminal or LXTerminal by default

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by andrewdavidwong** [comment] 2020-01-26 14:14
Duplicate of #2581

**Comment by andrewdavidwong** [comment] 2020-01-26 14:14
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-01-26 14:14 UTC
Labels: P: default, T: enhancement
