### ISSUE TITLE
No user feedback when "Edit in DisposableVM" fails on policy

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5384] opened 2019-10-11 12:56 UTC
**Qubes OS version**
R4.0 updated on testing

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
GUI UX
Desktop
"Open in Disposable VM"

**Brief summary**
`Edit in DisposableVM` fails silently.
At command line, `qvm-open-in-dvm` fails with "Request refused", which at least points in right direction.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Right Click on File_
_2. Select "Edit in DisposableVM" from Menu_
_3. Nothing Happens_

**Expected behavior**
File will open for editing in DisposableVM or error message will be shown.

**Actual behavior**
Nothing

**Screenshots**

**Additional context**
Fedora based qube.
KDE

**Solutions you've tried**
With correct setting in policy file everything works - it's the absence of feedback at GUI level that's the issue

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5235 is about policy
#1773 is about failure where file is not handled at destination

**Comment by andrewdavidwong** [comment] 2019-10-12 01:46
Duplicate of #3904

**Comment by andrewdavidwong** [comment] 2019-10-12 01:46
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-10-12 01:46 UTC
Labels: P: default, T: bug
