### ISSUE TITLE
dom0 , OSError: [Errno 2] No such file or directory: '/var/lib/qubes/servicevms/dom0/apps.templates'

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1491] opened 2015-12-05 13:09 UTC
after the last dom0 updates , something looks wrong with dom0:- 

firstly:- if you go to dom0 and hit right click then choose "Add/remove apps shortcuts" this message going to appear:- 

> Whoops A critical error has occured. This is most likely a bug in Qubes Manager.
 **OSError: [Errno 2] No such file or directory: '/var/lib/qubes/servicevms/dom0/apps.templates'** 
at line **71**
of file appmenu_select.py.

now there is Show Details.... , when i press one it , it shows these messages:- 

> **----**
line: template_file_list = os.listdir(template_dir)
func: fill_apps_list
line no.: 71
file: /usr/lib64/python2.7/site-
packages/qubesmanager/appmenu_select.py
**----**
line: self.fill_apps_list()
func: _init_
line no.: 65
file: /usr/lib64/python2.7/site-
packages/qubesmanager/appmenu_select.py
**----**
line: self.AppListManager = AppmenuSelectManager(self.vm,self.app_list)
func: _init_
line no.:106
file: /usr/lib64/python2.7/site-packages/qubesmanager/settings.py
**----**
line: "applications")
func: action_appmenu_triggered
line no.: 1296
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py

secondly:- the update icon keeps appearing even if i press the update button and there is no updates.

thirdly:- i would like to copy the dom0 logs and add it here but since i cant copy/paste directly. it is too hard to write it down here. (hope u make sucha way to do that easier in the future). tho in the last two lines i read there is an error:-
>
(XEN) event_channel.c:271:d0 EVTCHNOP failure: domain 17, error -22
(XEN) event_channel.c:271:d0 EVTCHNOP failure: domain 19, error -22

**Comment by pqg** [comment] 2015-12-08 03:37
Just wrt moving logs out of dom0:

If you're confident that the logs do not contain any sensitive info, you can copy a file out of dom0 thusly:

$ qvm-run --pass-io $VMNAME 'cat > $FILENAME' < $FILEPATH

(Paths in the command are relative to /home/user/ .  If concerned about the VM piping data back to dom0, consider appending a " 2>&1 >/dev/null " to the command.)

**Comment by TNTBOMBOM** [comment] 2015-12-09 17:57
hmm well thats weird , all logs wiped after shutdown. is it that by default ? is there a way to re-back them?
but the update icon still hanging there no matter how much u restart/shutdown the pc or clicking on "update vm system" icon, and there r no updates.

and how about the rest of the messages above ? sound normal ? if they r normal . then it is better to change the message for more confidential to the user when he press on "add/remove app shortcuts".

**Comment by TNTBOMBOM** [comment] 2015-12-10 10:41
ok i reproduce the dom0 log , by pc-shutdown -> cut off the internet (i just removed the cable because i dont use the wifi) -> turn on the pc & go to dom0 logs = tada! 

hmm but the problem is still witha dom0 logs copy

i have saved the logs in /home/myusername

i tried these:- 

qvm-run --pass-io untrusted 'cat > log.txt' < /home/myusername

and it give:- 

python error: <stdin> is a directory, cannot continue 

different python version?

**Comment by marmarek** [comment] 2015-12-10 18:10
On Thu, Dec 10, 2015 at 02:41:14AM -0800, TNT BOM BOM wrote:
> qvm-run --pass-io untrusted 'cat > log.txt' < /home/myusername

You're trying to write a directory instead of file...
 
-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by TNTBOMBOM** [comment] 2015-12-12 20:40
ok here:- (couldnt drag and drop the file here, it says:- "Something went really wrong, and we can’t process that file. Try again." so copy/paste as code)

` Xen 4.4.3-10.fc20
(XEN) Xen version 4.4.3 (user@) (gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)) debug=n Sun Nov 15 04:19:14 UTC 2015
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.00
(XEN) Command line: placeholder console=none dom0_mem=min:1024M
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN)  VBE/DDC methods: V2; EDID transfer time: 1 seconds
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  0000000000000000 - 000000000009c800 (usable)
(XEN)  000000000009c800 - 00000000000a0000 (reserved)
(XEN)  00000000000e0000 - 0000000000100000 (reserved)
(XEN)  0000000000100000 - 00000000b97fc000 (usable)
(XEN)  00000000b97fc000 - 00000000b9803000 (ACPI NVS)
(XEN)  00000000b9803000 - 00000000ba06e000 (usable)
(XEN)  00000000ba06e000 - 00000000ba2fa000 (reserved)
(XEN)  00000000ba2fa000 - 00000000c98e0000 (usable)
(XEN)  00000000c98e0000 - 00000000c9af7000 (reserved)
(XEN)  00000000c9af7000 - 00000000c9e1c000 (usable)
(XEN)  00000000c9e1c000 - 00000000cab1f000 (ACPI NVS)
(XEN)  00000000cab1f000 - 00000000cafff000 (reserved)
(XEN)  00000000cafff000 - 00000000cb000000 (usable)
(XEN)  00000000cbc00000 - 00000000cfe00000 (reserved)
(XEN)  00000000f8000000 - 00000000fc000000 (reserved)
(XEN)  00000000fec00000 - 00000000fec01000 (reserved)
(XEN)  00000000fed00000 - 00000000fed04000 (reserved)
(XEN)  00000000fed1c000 - 00000000fed20000 (reserved)
(XEN)  00000000fee00000 - 00000000fee01000 (reserved)
(XEN)  00000000ff000000 - 0000000100000000 (reserved)
(XEN)  0000000100000000 - 000000022f200000 (usable)
(XEN) ACPI: RSDP 000F0490, 0024 (r2 _ASUS_)
(XEN) ACPI: XSDT C9EA4088, 009C (r1 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: FACP C9EB7E58, 010C (r5 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: DSDT C9EA4240, 13C16 (r2 _ASUS_ Notebook       12 INTL 20120711)
(XEN) ACPI: FACS CAB1DF80, 0040
(XEN) ACPI: APIC C9EB7F68, 0092 (r3 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: FPDT C9EB8000, 0044 (r1 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: ECDT C9EB8048, 00C1 (r1 _ASUS_ Notebook  1072009 AMI.        5)
(XEN) ACPI: SSDT C9EB8110, 019D (r1  Intel    zpodd     1000 INTL 20120711)
(XEN) ACPI: SSDT C9EB82B0, 0539 (r1  PmRef  Cpu0Ist     3000 INTL 20120711)
(XEN) ACPI: SSDT C9EB87F0, 0AD8 (r1  PmRef    CpuPm     3000 INTL 20120711)
(XEN) ACPI: MCFG C9EB92C8, 003C (r1 _ASUS_ Notebook  1072009 MSFT       97)
(XEN) ACPI: HPET C9EB9308, 0038 (r1 _ASUS_ Notebook  1072009 AMI.        5)
(XEN) ACPI: SSDT C9EB9340, 0298 (r1 SataRe SataTabl     1000 INTL 20120711)
(XEN) ACPI: SSDT C9EB95D8, 44FA (r1 SaSsdt  SaSsdt      3000 INTL 20091112)
(XEN) ACPI: SSDT C9EBDAD8, 17D1 (r1  SgRef    SgPeg     1000 INTL 20120711)
(XEN) ACPI: DMAR C9EBF2B0, 00B8 (r1 INTEL      HSW         1 INTL        1)
(XEN) ACPI: SSDT C9EBF368, 13ED (r1 OptRef  OptTabl     1000 INTL 20120711)
(XEN) ACPI: MSDM C9AF4E18, 0055 (r3 _ASUS_ Notebook        0 ASUS        1)
(XEN) System RAM: 8075MB (8268860kB)
(XEN) Domain heap initialised
(XEN) ACPI: 32/64X FACS address mismatch in FADT - cab1df80/0000000000000000, using 32
(XEN) Processor #0 7:12 APIC version 21
(XEN) Processor #2 7:12 APIC version 21
(XEN) Processor #4 7:12 APIC version 21
(XEN) Processor #6 7:12 APIC version 21
(XEN) Processor #1 7:12 APIC version 21
(XEN) Processor #3 7:12 APIC version 21
(XEN) Processor #5 7:12 APIC version 21
(XEN) Processor #7 7:12 APIC version 21
(XEN) IOAPIC[0]: apic_id 8, version 32, address 0xfec00000, GSI 0-23
(XEN) Enabling APIC mode:  Flat.  Using 1 I/O APICs
(XEN) Switched to APIC driver x2apic_cluster.
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Detected 2494.281 MHz processor.
(XEN) Initing memory sharing.
(XEN) xstate_init: using cntxt_size: 0x340 and states: 0x7
(XEN) Intel VT-d iommu 0 supported page sizes: 4kB.
(XEN) Intel VT-d iommu 1 supported page sizes: 4kB.
(XEN) Intel VT-d Snoop Control not enabled.
(XEN) Intel VT-d Dom0 DMA Passthrough not enabled.
(XEN) Intel VT-d Queued Invalidation enabled.
(XEN) Intel VT-d Interrupt Remapping enabled.
(XEN) Intel VT-d Shared EPT tables not enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
(XEN) Interrupt remapping enabled
(XEN) Enabled directed EOI with ioapic_ack_old on!
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using old ACK method
(XEN) Platform timer is 14.318MHz HPET
(XEN) Allocated console ring of 16 KiB.
(XEN) VMX: Supported advanced features:
(XEN)  - APIC MMIO access virtualisation
(XEN)  - APIC TPR shadow
(XEN)  - Extended Page Tables (EPT)
(XEN)  - Virtual-Processor Identifiers (VPID)
(XEN)  - Virtual NMI
(XEN)  - MSR direct-access bitmap
(XEN)  - Unrestricted Guest
(XEN) HVM: ASIDs enabled.
(XEN) HVM: VMX enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB, 1GB
(XEN) Brought up 8 CPUs
(XEN) *** LOADING DOMAIN 0 ***
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x2269000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000220000000->0000000224000000 (1977146 pages to be allocated)
(XEN)  Init. ramdisk: 000000022c56c000->000000022f1ff200
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff82269000
(XEN)  Init. ramdisk: 0000000000000000->0000000000000000
(XEN)  Phys-Mach map: ffffffff82269000->ffffffff831b4e70
(XEN)  Start info:    ffffffff831b5000->ffffffff831b54b4
(XEN)  Page tables:   ffffffff831b6000->ffffffff831d3000
(XEN)  Boot stack:    ffffffff831d3000->ffffffff831d4000
(XEN)  TOTAL:         ffffffff80000000->ffffffff83400000
(XEN)  ENTRY ADDRESS: ffffffff81d341f0
(XEN) Dom0 has maximum 8 VCPUs
(XEN) Bogus DMIBAR 0xfed18001 on 0000:00:00.0
(XEN) Scrubbing Free RAM: .done.
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) *** Serial input -> DOM0 (type 'CTRL-a' three times to switch input to Xen)
(XEN) Freed 264kB init memory.
(XEN) Bogus DMIBAR 0xfed18001 on 0000:00:00.0
(XEN) event_channel.c:271:d0 EVTCHNOP failure: domain 9, error -22`

**Comment by TNTBOMBOM** [comment] 2015-12-12 21:47
this is new one:- (when i hit update button for dom0, dom0 not updating nor saying there r no dom0 updates. just nothing)

>  Xen 4.4.3-10.fc20
(XEN) Xen version 4.4.3 (user@) (gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)) debug=n Sun Nov 15 04:19:14 UTC 2015
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.00
(XEN) Command line: placeholder console=none dom0_mem=min:1024M
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN)  VBE/DDC methods: V2; EDID transfer time: 1 seconds
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  0000000000000000 - 000000000009c800 (usable)
(XEN)  000000000009c800 - 00000000000a0000 (reserved)
(XEN)  00000000000e0000 - 0000000000100000 (reserved)
(XEN)  0000000000100000 - 00000000b97fc000 (usable)
(XEN)  00000000b97fc000 - 00000000b9803000 (ACPI NVS)
(XEN)  00000000b9803000 - 00000000ba06e000 (usable)
(XEN)  00000000ba06e000 - 00000000ba2fa000 (reserved)
(XEN)  00000000ba2fa000 - 00000000c98e0000 (usable)
(XEN)  00000000c98e0000 - 00000000c9af7000 (reserved)
(XEN)  00000000c9af7000 - 00000000c9e1c000 (usable)
(XEN)  00000000c9e1c000 - 00000000cab1f000 (ACPI NVS)
(XEN)  00000000cab1f000 - 00000000cafff000 (reserved)
(XEN)  00000000cafff000 - 00000000cb000000 (usable)
(XEN)  00000000cbc00000 - 00000000cfe00000 (reserved)
(XEN)  00000000f8000000 - 00000000fc000000 (reserved)
(XEN)  00000000fec00000 - 00000000fec01000 (reserved)
(XEN)  00000000fed00000 - 00000000fed04000 (reserved)
(XEN)  00000000fed1c000 - 00000000fed20000 (reserved)
(XEN)  00000000fee00000 - 00000000fee01000 (reserved)
(XEN)  00000000ff000000 - 0000000100000000 (reserved)
(XEN)  0000000100000000 - 000000022f200000 (usable)
(XEN) ACPI: RSDP 000F0490, 0024 (r2 _ASUS_)
(XEN) ACPI: XSDT C9EA4088, 009C (r1 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: FACP C9EB7E58, 010C (r5 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: DSDT C9EA4240, 13C16 (r2 _ASUS_ Notebook       12 INTL 20120711)
(XEN) ACPI: FACS CAB1DF80, 0040
(XEN) ACPI: APIC C9EB7F68, 0092 (r3 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: FPDT C9EB8000, 0044 (r1 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: ECDT C9EB8048, 00C1 (r1 _ASUS_ Notebook  1072009 AMI.        5)
(XEN) ACPI: SSDT C9EB8110, 019D (r1  Intel    zpodd     1000 INTL 20120711)
(XEN) ACPI: SSDT C9EB82B0, 0539 (r1  PmRef  Cpu0Ist     3000 INTL 20120711)
(XEN) ACPI: SSDT C9EB87F0, 0AD8 (r1  PmRef    CpuPm     3000 INTL 20120711)
(XEN) ACPI: MCFG C9EB92C8, 003C (r1 _ASUS_ Notebook  1072009 MSFT       97)
(XEN) ACPI: HPET C9EB9308, 0038 (r1 _ASUS_ Notebook  1072009 AMI.        5)
(XEN) ACPI: SSDT C9EB9340, 0298 (r1 SataRe SataTabl     1000 INTL 20120711)
(XEN) ACPI: SSDT C9EB95D8, 44FA (r1 SaSsdt  SaSsdt      3000 INTL 20091112)
(XEN) ACPI: SSDT C9EBDAD8, 17D1 (r1  SgRef    SgPeg     1000 INTL 20120711)
(XEN) ACPI: DMAR C9EBF2B0, 00B8 (r1 INTEL      HSW         1 INTL        1)
(XEN) ACPI: SSDT C9EBF368, 13ED (r1 OptRef  OptTabl     1000 INTL 20120711)
(XEN) ACPI: MSDM C9AF4E18, 0055 (r3 _ASUS_ Notebook        0 ASUS        1)
(XEN) System RAM: 8075MB (8268860kB)
(XEN) Domain heap initialised
(XEN) ACPI: 32/64X FACS address mismatch in FADT - cab1df80/0000000000000000, using 32
(XEN) Processor #0 7:12 APIC version 21
(XEN) Processor #2 7:12 APIC version 21
(XEN) Processor #4 7:12 APIC version 21
(XEN) Processor #6 7:12 APIC version 21
(XEN) Processor #1 7:12 APIC version 21
(XEN) Processor #3 7:12 APIC version 21
(XEN) Processor #5 7:12 APIC version 21
(XEN) Processor #7 7:12 APIC version 21
(XEN) IOAPIC[0]: apic_id 8, version 32, address 0xfec00000, GSI 0-23
(XEN) Enabling APIC mode:  Flat.  Using 1 I/O APICs
(XEN) Switched to APIC driver x2apic_cluster.
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Detected 2494.281 MHz processor.
(XEN) Initing memory sharing.
(XEN) xstate_init: using cntxt_size: 0x340 and states: 0x7
(XEN) Intel VT-d iommu 0 supported page sizes: 4kB.
(XEN) Intel VT-d iommu 1 supported page sizes: 4kB.
(XEN) Intel VT-d Snoop Control not enabled.
(XEN) Intel VT-d Dom0 DMA Passthrough not enabled.
(XEN) Intel VT-d Queued Invalidation enabled.
(XEN) Intel VT-d Interrupt Remapping enabled.
(XEN) Intel VT-d Shared EPT tables not enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
(XEN) Interrupt remapping enabled
(XEN) Enabled directed EOI with ioapic_ack_old on!
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using old ACK method
(XEN) Platform timer is 14.318MHz HPET
(XEN) Allocated console ring of 16 KiB.
(XEN) VMX: Supported advanced features:
(XEN)  - APIC MMIO access virtualisation
(XEN)  - APIC TPR shadow
(XEN)  - Extended Page Tables (EPT)
(XEN)  - Virtual-Processor Identifiers (VPID)
(XEN)  - Virtual NMI
(XEN)  - MSR direct-access bitmap
(XEN)  - Unrestricted Guest
(XEN) HVM: ASIDs enabled.
(XEN) HVM: VMX enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB, 1GB
(XEN) Brought up 8 CPUs
(XEN) *** LOADING DOMAIN 0 ***
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x2269000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000220000000->0000000224000000 (1977146 pages to be allocated)
(XEN)  Init. ramdisk: 000000022c56c000->000000022f1ff200
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff82269000
(XEN)  Init. ramdisk: 0000000000000000->0000000000000000
(XEN)  Phys-Mach map: ffffffff82269000->ffffffff831b4e70
(XEN)  Start info:    ffffffff831b5000->ffffffff831b54b4
(XEN)  Page tables:   ffffffff831b6000->ffffffff831d3000
(XEN)  Boot stack:    ffffffff831d3000->ffffffff831d4000
(XEN)  TOTAL:         ffffffff80000000->ffffffff83400000
(XEN)  ENTRY ADDRESS: ffffffff81d341f0
(XEN) Dom0 has maximum 8 VCPUs
(XEN) Bogus DMIBAR 0xfed18001 on 0000:00:00.0
(XEN) Scrubbing Free RAM: .done.
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) *** Serial input -> DOM0 (type 'CTRL-a' three times to switch input to Xen)
(XEN) Freed 264kB init memory.
(XEN) Bogus DMIBAR 0xfed18001 on 0000:00:00.0
(XEN) event_channel.c:271:d0 EVTCHNOP failure: domain 9, error -22
 Xen 4.4.3-10.fc20
(XEN) Xen version 4.4.3 (user@) (gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)) debug=n Sun Nov 15 04:19:14 UTC 2015
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.00
(XEN) Command line: placeholder console=none dom0_mem=min:1024M
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN)  VBE/DDC methods: V2; EDID transfer time: 1 seconds
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  0000000000000000 - 000000000009c800 (usable)
(XEN)  000000000009c800 - 00000000000a0000 (reserved)
(XEN)  00000000000e0000 - 0000000000100000 (reserved)
(XEN)  0000000000100000 - 00000000b97fc000 (usable)
(XEN)  00000000b97fc000 - 00000000b9803000 (ACPI NVS)
(XEN)  00000000b9803000 - 00000000ba06e000 (usable)
(XEN)  00000000ba06e000 - 00000000ba2fa000 (reserved)
(XEN)  00000000ba2fa000 - 00000000c98e0000 (usable)
(XEN)  00000000c98e0000 - 00000000c9af7000 (reserved)
(XEN)  00000000c9af7000 - 00000000c9e1c000 (usable)
(XEN)  00000000c9e1c000 - 00000000cab1f000 (ACPI NVS)
(XEN)  00000000cab1f000 - 00000000cafff000 (reserved)
(XEN)  00000000cafff000 - 00000000cb000000 (usable)
(XEN)  00000000cbc00000 - 00000000cfe00000 (reserved)
(XEN)  00000000f8000000 - 00000000fc000000 (reserved)
(XEN)  00000000fec00000 - 00000000fec01000 (reserved)
(XEN)  00000000fed00000 - 00000000fed04000 (reserved)
(XEN)  00000000fed1c000 - 00000000fed20000 (reserved)
(XEN)  00000000fee00000 - 00000000fee01000 (reserved)
(XEN)  00000000ff000000 - 0000000100000000 (reserved)
(XEN)  0000000100000000 - 000000022f200000 (usable)
(XEN) ACPI: RSDP 000F0490, 0024 (r2 _ASUS_)
(XEN) ACPI: XSDT C9EA4088, 009C (r1 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: FACP C9EB7E58, 010C (r5 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: DSDT C9EA4240, 13C16 (r2 _ASUS_ Notebook       12 INTL 20120711)
(XEN) ACPI: FACS CAB1DF80, 0040
(XEN) ACPI: APIC C9EB7F68, 0092 (r3 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: FPDT C9EB8000, 0044 (r1 _ASUS_ Notebook  1072009 AMI     10013)
(XEN) ACPI: ECDT C9EB8048, 00C1 (r1 _ASUS_ Notebook  1072009 AMI.        5)
(XEN) ACPI: SSDT C9EB8110, 019D (r1  Intel    zpodd     1000 INTL 20120711)
(XEN) ACPI: SSDT C9EB82B0, 0539 (r1  PmRef  Cpu0Ist     3000 INTL 20120711)
(XEN) ACPI: SSDT C9EB87F0, 0AD8 (r1  PmRef    CpuPm     3000 INTL 20120711)
(XEN) ACPI: MCFG C9EB92C8, 003C (r1 _ASUS_ Notebook  1072009 MSFT       97)
(XEN) ACPI: HPET C9EB9308, 0038 (r1 _ASUS_ Notebook  1072009 AMI.        5)
(XEN) ACPI: SSDT C9EB9340, 0298 (r1 SataRe SataTabl     1000 INTL 20120711)
(XEN) ACPI: SSDT C9EB95D8, 44FA (r1 SaSsdt  SaSsdt      3000 INTL 20091112)
(XEN) ACPI: SSDT C9EBDAD8, 17D1 (r1  SgRef    SgPeg     1000 INTL 20120711)
(XEN) ACPI: DMAR C9EBF2B0, 00B8 (r1 INTEL      HSW         1 INTL        1)
(XEN) ACPI: SSDT C9EBF368, 13ED (r1 OptRef  OptTabl     1000 INTL 20120711)
(XEN) ACPI: MSDM C9AF4E18, 0055 (r3 _ASUS_ Notebook        0 ASUS        1)
(XEN) System RAM: 8075MB (8268860kB)
(XEN) Domain heap initialised
(XEN) ACPI: 32/64X FACS address mismatch in FADT - cab1df80/0000000000000000, using 32
(XEN) Processor #0 7:12 APIC version 21
(XEN) Processor #2 7:12 APIC version 21
(XEN) Processor #4 7:12 APIC version 21
(XEN) Processor #6 7:12 APIC version 21
(XEN) Processor #1 7:12 APIC version 21
(XEN) Processor #3 7:12 APIC version 21
(XEN) Processor #5 7:12 APIC version 21
(XEN) Processor #7 7:12 APIC version 21
(XEN) IOAPIC[0]: apic_id 8, version 32, address 0xfec00000, GSI 0-23
(XEN) Enabling APIC mode:  Flat.  Using 1 I/O APICs
(XEN) Switched to APIC driver x2apic_cluster.
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Detected 2494.286 MHz processor.
(XEN) Initing memory sharing.
(XEN) xstate_init: using cntxt_size: 0x340 and states: 0x7
(XEN) Intel VT-d iommu 0 supported page sizes: 4kB.
(XEN) Intel VT-d iommu 1 supported page sizes: 4kB.
(XEN) Intel VT-d Snoop Control not enabled.
(XEN) Intel VT-d Dom0 DMA Passthrough not enabled.
(XEN) Intel VT-d Queued Invalidation enabled.
(XEN) Intel VT-d Interrupt Remapping enabled.
(XEN) Intel VT-d Shared EPT tables not enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
(XEN) Interrupt remapping enabled
(XEN) Enabled directed EOI with ioapic_ack_old on!
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using old ACK method
(XEN) Platform timer is 14.318MHz HPET
(XEN) Allocated console ring of 16 KiB.
(XEN) VMX: Supported advanced features:
(XEN)  - APIC MMIO access virtualisation
(XEN)  - APIC TPR shadow
(XEN)  - Extended Page Tables (EPT)
(XEN)  - Virtual-Processor Identifiers (VPID)
(XEN)  - Virtual NMI
(XEN)  - MSR direct-access bitmap
(XEN)  - Unrestricted Guest
(XEN) HVM: ASIDs enabled.
(XEN) HVM: VMX enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB, 1GB
(XEN) Brought up 8 CPUs
(XEN) *** LOADING DOMAIN 0 ***
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x2269000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000220000000->0000000224000000 (1977146 pages to be allocated)
(XEN)  Init. ramdisk: 000000022c56c000->000000022f1ff200
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff82269000
(XEN)  Init. ramdisk: 0000000000000000->0000000000000000
(XEN)  Phys-Mach map: ffffffff82269000->ffffffff831b4e70
(XEN)  Start info:    ffffffff831b5000->ffffffff831b54b4
(XEN)  Page tables:   ffffffff831b6000->ffffffff831d3000
(XEN)  Boot stack:    ffffffff831d3000->ffffffff831d4000
(XEN)  TOTAL:         ffffffff80000000->ffffffff83400000
(XEN)  ENTRY ADDRESS: ffffffff81d341f0
(XEN) Dom0 has maximum 8 VCPUs
(XEN) Bogus DMIBAR 0xfed18001 on 0000:00:00.0
(XEN) Scrubbing Free RAM: .done.
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) *** Serial input -> DOM0 (type 'CTRL-a' three times to switch input to Xen)
(XEN) Freed 264kB init memory.
(XEN) Bogus DMIBAR 0xfed18001 on 0000:00:00.0
(XEN) [VT-D]DMAR:[DMA Write] Request device [0000:01:00.0] fault addr 8c000, iommu reg = ffff82c000203000
(XEN) [VT-D]DMAR: reason 05 - PTE Write access is not set
(XEN) [VT-D]DMAR:[DMA Write] Request device [0000:01:00.0] fault addr 8c000, iommu reg = ffff82c000203000
(XEN) [VT-D]DMAR: reason 05 - PTE Write access is not set
(XEN) [VT-D]DMAR:[DMA Write] Request device [0000:01:00.0] fault addr 8c000, iommu reg = ffff82c000203000
(XEN) [VT-D]DMAR: reason 05 - PTE Write access is not set
(XEN) [VT-D]DMAR:[DMA Write] Request device [0000:01:00.0] fault addr 8c000, iommu reg = ffff82c000203000
(XEN) [VT-D]DMAR: reason 05 - PTE Write access is not set
(XEN) [VT-D]DMAR:[DMA Write] Request device [0000:01:00.0] fault addr 8c000, iommu reg = ffff82c000203000
(XEN) [VT-D]DMAR: reason 05 - PTE Write access is not set
(XEN) printk: 10 messages suppressed.
(XEN) event_fifo.c:50:d0 domain 0, port 150 already on a queue

**Comment by marmarek** [comment] 2015-12-13 00:08
Duplicate of #1367

**Closed by marmarek** 2015-12-13 00:08 UTC
