### ISSUE TITLE
add support for additional audio devices

### ISSUE THREAD

**Issue by rjrizzuto** [QubesOS/qubes-issues#8943] opened 2024-02-14 02:50 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
There are use cases where a user wants private listening, e.g. for privacy, to not disturb others, etc. In these cases, the speaker of say a laptop is not an option.  Aux ports are sometimes, but not always, available.  

### The solution you'd like
Support USB and Bluetooth audio devices, such as headsets and earbuds.

### The value to a user, and who that user might be
The ability to listen to audio without disturbing others.  Some additional privacy (at least for 1 side of a conversation) in a teleconference.

**Comment by xaki23** [comment] 2024-02-14 02:57
this one is somewhat of a documentation issue for a few years now.
could be considered a dupe of https://github.com/QubesOS/qubes-issues/issues/8093
there is also https://www.qubes-os.org/doc/audio-virtualization/
(from my pov the main problem is that there are so, sooo many ways to set up your qubes audio, and they are basicly all technically viable by now, but i have no idea how to document it for the general population...)

**Comment by rjrizzuto** [comment] 2024-02-14 03:25
I guess it would be worth collecting the use cases and see what falls out naturally. Thankfully, laptops, unlike phones, still have aux jacks, so that is always a last resort that can be used.

From my experience, the 2 cases I know of are:

- wanting to use bluetooth earbuds for the convenience of a wireless connection
- having a USB headset instead of an aux one. Since both are wired, that is maybe less important.

Somewhat related, support of bluetooth mice would be nice. Again, the convenience of cordless. As an alternate, I am using a cordless mouse with a USB dongle.

**Closed** 2024-02-14 13:10 UTC
Labels: R: duplicate, T: enhancement, R: not applicable, P: default

**Comment by rjrizzuto** [comment] 2024-02-14 15:00
Since you say that bluetooth audio is supported, can you please point me to documentation to how to set up bluetooth, pair a headset, and get the audio configured such that audio output from all qubes goes to the bluetooth headset instead of the speaker?

All of those steps are simple on Linux Mint.

**Comment by rjrizzuto** [comment] 2024-02-14 23:21
I did look at them and will again. They didn't seem at all easy to follow, so I still think there should be a ticket to make using Bluetooth audio simpler.

I've gotten some good advice on the forums but also a lot of useless or bad advice as well. It would be nice to see a way of using Bluetooth that's been vetted by the developers.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by rjrizzuto** [comment] 2024-02-15 16:39
Looks like that's been moved to https://github.com/QubesOS/qubes-issues/issues/7750
