### ISSUE TITLE
Remove portion of vm-sudo doc that has been moved to the community docs

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8375] opened 2023-07-29 12:03 UTC
Quote @andrewdavidwong https://github.com/QubesOS/qubes-doc/pull/1295#issuecomment-1430876566:
> The section on replacing passwordless root with a dom0 prompt is now live in the community docs:
> 
> https://github.com/Qubes-Community/Contents/blob/master/docs/security/replacing-passwordless-root-with-dom0-prompt.md
> 
> @adrelanos, would you mind submitting your changes there?

Why is

* https://github.com/QubesOS/qubes-doc/blob/main/user/security-in-qubes/vm-sudo.md
* https://www.qubes-os.org/doc/vm-sudo/

still online?

Shouldn't https://github.com/Qubes-Community/Contents/blob/master/docs/security/replacing-passwordless-root-with-dom0-prompt.md now be the only version what it is live?

**Comment by andrewdavidwong** [comment] 2023-07-29 23:38
As I wrote in https://github.com/QubesOS/qubes-doc/pull/1295#discussion_r1106737825:

> Okay, thank you both for your input. It sounds like the original intention for this page was just to document passwordless root itself and the configuration changes associated with it. When the unofficial workaround to replace passwordless root with a dom0 prompt was devised, this seemed like the natural place to document it. In retrospect, though, that turned out to be scope creep (for this doc page). It sounds like the right thing to do is to move this page to the developer docs and move the section on replacing passwordless root with a dom0 prompt to the community docs. I've opened a separate PR for that: #1296

In other words, that community doc was never intended to completely replace the official doc page. The intention was merely to move the stuff that doesn't belong in the official docs out of the official docs and leave the remaining stuff (which does belong in the official docs) in the official docs. So, as long as there is still remaining stuff that's appropriate for the official docs, it makes sense that the page still exists.

(By the way, I am  no longer the website or documentation maintainer. @unman [is the new website and documentation maintainer](https://forum.qubes-os.org/t/18457/10), so any decisions or actions going forward are likely to be his. I'm helping with the transition and providing any insight I can into what occurred while I held those positions.)

**Comment by andrewdavidwong** [comment] 2023-07-29 23:38
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by adrelanos** [comment] 2023-07-30 15:56
The part which was moved to Qubes community however should be removed from Qubes website to avoid confusion and duplication.

Please re-open.

**Comment by adrelanos** [comment] 2023-07-30 16:04
https://github.com/QubesOS/qubes-doc/pull/1330

**Closed** 2023-10-29 15:25 UTC
Labels: T: bug, C: doc, P: default, pr submitted
