### ISSUE TITLE
Qubes 4.0-rc4 - qvm-run on stopped VM is starting VM, but not application

### ISSUE THREAD

**Issue by maaca** [QubesOS/qubes-issues#3544] opened 2018-02-06 08:35 UTC
#### Qubes OS version:
4.0-rc4

### Steps to reproduce the behavior:
Executing: 
qvm-run <whatever_vm> <whatever_command>
is starting VM, but command is not executed, no app window is opened.
qvm-run is working well with started VM.

### Expected behavior:
Expecting to have started VM and executed command inside it.

Worked well in 4.0-rc2 and 4.0-rc3

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-02-07 05:08
Related thread:
https://groups.google.com/d/topic/qubes-users/PDIQzFlupS0/discussion

**Comment by awokd** [comment] 2018-02-07 13:31
@maaca Could you please verify your templates and dom0 are using the same repository (both are set to the Testing one for example) and have both been updated recently? 
If not, try that and see if it fixes it? I did experience some strange behaviour when I had dom0 on Testing but my template on Current.

**Comment by awokd** [comment] 2018-02-07 13:57
And in case it's not clear in the above comment, I mean your Qubes repositories (these https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories and https://www.qubes-os.org/doc/software-update-vm/#testing-repositories) only, not your operating system ones.

**Comment by maaca** [comment] 2018-02-07 16:03
@awokd It is fresh 4.0-rc4 installation with default Fedora-26 template. Testing and unstable repos are disabled in both, template and dom0. Both are updated.

**Comment by awokd** [comment] 2018-02-07 16:18
@maaca Thanks. I'm on testing on both and it's working fine for me. Maybe there's already a fix out there and it just needs to be pushed to current, or could be some other issue entirely.

**Comment by mirrorway** [comment] 2018-02-08 02:57
On 4.0rc4, I believe I can reproduce this by having two VM { ... } sections in /etc/qubes/guid.conf. Not sure if that is an example of a malformed guid.conf.

Merging the sections fixed the issue for me, though it seems like it takes a few minutes / VM restarts to get qvm-run going again.

**Comment by maaca** [comment] 2018-02-09 11:07
@mirrorway I've only uncommented allow_fullscreen in the guid.conf.txt. 
VM starts normally in tens of seconds.

**Comment by awokd** [comment] 2018-02-10 13:54
@maaca OK, fresh install of 4.0rc4 with 0 patches or other system changes. `qvm-run work firefox` starts Firefox whether the work qube has already been started or not. Rebooted to make sure it wasn't an issue with the first qube to start.

> VM starts normally in tens of seconds.

This makes me wonder if your VMs aren't starting quickly enough and qrexec is timing out. What is your `qvm-prefs <vmname> qrexec_timeout` set to? Default is 60 seconds, maybe try making it 120 if your VMs take longer?

**Comment by maaca** [comment] 2018-02-10 17:34
@awokd Setting qrexec_timeout to higher value didn't help.

Maybe heplful finding: I run qvm-run, it is running for cca 5 seconds. Then qvm-run ends (without error) and xfce is showing "Domain xxxx is started", but in qvm-ls I can see that the VM state is "Transient".

**Comment by marmarek** [comment] 2018-02-10 17:52
@maaca did you had any problems during installation? I guess the relevant template isn't marked as supporting GUI applications, so starting the VM do not wait until X server is started there. You can verify this with `qvm-features fedora-26` (in case of fedora-26 template). There should be `gui` entry. If it's missing, add it with:

    qvm-features fedora-26 gui 1

And the same for `qrexec` - both should be set there.

**Comment by maaca** [comment] 2018-02-10 18:03
@marmarek Thank you for the hint. Adding these features solved the issue.

You are right, I had to run post-installation setting twice, because it failed first time. The second run went well, so I forgot on that.

**Comment by andrewdavidwong** [comment] 2018-02-10 20:12
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-02-10 20:12 UTC
Labels: C: core, bug
