### ISSUE TITLE
Cloning sys-net in the Qubes Manager creates a qube that cannot be cleanly removed

### ISSUE THREAD

**Issue by gasull** [QubesOS/qubes-issues#4168] opened 2018-07-31 00:51 UTC
### Qubes OS version:

4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

1. Start Qubes Manager
2. Right-click sys-net and select "Clone qube" to clone sys-net.  Use the default name sys-net-clone-1.
3. After having created sys-net-clone-1, select it in the Qubes Manager and click on the icon at the top left to delete it.
4. Reboot the computer and look at the output messages.

### Expected behavior:

No errors should be shown when booting up the computer.

### Actual behavior:

At bootup, got a `[FAILED]` error:

```
[FAILED] Failed to start Start Qubes VM sys-net-clone-1
```

### General notes:

---

**Comment by gasull** [comment] 2018-11-09 03:37
As a workaround, the problem can be fixed with this command on `dom0`:
```bash
sudo systemctl disable qubes-vm@<name-of-your-qube>
```

**Comment by marmarek** [comment] 2018-11-09 09:29
This is a duplicate of #4014 (fix already in testing repo).

**Closed by marmarek** 2018-11-09 09:29 UTC
Labels: C: core, bug
