### ISSUE TITLE
with sys-usb i can not read my usb3 drive

### ISSUE THREAD

**Issue by adavida** [QubesOS/qubes-issues#3351] opened 2017-11-29 19:37 UTC
#### Qubes OS version:
R4.0rc3

#### Affected TemplateVMs: 
sys-usb

### Steps to reproduce the behavior:
plug usb3 disk

### Expected behavior:
with sys-usb i can not read my usb3 drive

the only thing i can do is go up to sys-usb and copy from vm to vm

I can not redefine the sys-usb: / dev / sdXX to another vm (ex: personal)

### General notes:

---

**Comment by andrewdavidwong** [comment] 2017-11-30 04:24
Please make sure you've read this page:

https://www.qubes-os.org/doc/usb/

Then provide more precise steps to reproduce.

**Comment by adavida** [comment] 2017-11-30 06:51
I created the vm during the installation of qubs os R4.0RC3 (I did not change anything)

when I plug the hard disk, qvm-usb on dom0, shows it to me. and if I type lsblk on sys-usb. I see him.

mo problem is that if i type qvm-block on dom0, i do not see it.

the problem is that usb3 does not work in usb passthrough.

**Comment by andrewdavidwong** [comment] 2017-12-01 05:33
In https://github.com/QubesOS/qubes-issues/issues/2860#issuecomment-348200816, @marmarek wrote:
> Is it USB 3.0 (or USB 3.1) device? I'm afraid those do not work with qvm-usb yet. Check sys-net kernel messages for details.

So, it seems USB 3.0 devices not working with `qvm-usb` is a known issue. @marmarek, is there another open issue for this?

**Comment by adavida** [comment] 2017-12-01 13:46
f I attach a usb3 disk on personal 
with **dmesg** on personal I have:
`vhci_hcd: Failed attach request for unsupported USB speed: super-speed`

on qubes R4.0 rc2, I had the possibility to get stuck like the other disk already present. with a name: **sys-usb:/dev/sdXn** (X = a,b,c,... n=1,2,3,...)
and there I could attach usb3 disk on any VM, and has work

**Comment by lead4good** [comment] 2017-12-09 18:22
Can confirm this. Plugging in a usb stick or usb hdd (usb 2.0 and 3.0) will list the usb devices with qvm-usb, but will not register the block devices under qvm-block. This worked in 4R2, in 4R3 it doesn't anymore.

**Comment by kushaldas** [comment] 2017-12-12 18:14
Fresh 4.0rc3 install on a laptop. I can also confirm the same issue with USB storage devices.

**Comment by arvog** [comment] 2017-12-14 20:31
same for me on 4rc3 updated from 4rc2.

**Comment by najamelan** [comment] 2017-12-29 03:17
Same issue here. qvm-block only shows devices from dom0, trying to attach with qvm-usb always gives: "Device attach failed:". 

Plugging the device in a usb2 port doesn't help.

Notifications about usb devices being plugged in and out do show, but when withdrawing a usb storage device, it showed "Synaptic large touch screen is removed". It seems that sys-usb is really broken right now.

Please fix this, because not being able to use a usb stick on a computer is quite a dealbreaker.

ps: maybe it's not my place to say, but priority wise I would think with 900 open issues and problems like this, I would focus dev resources on bug fixing, and postpone decomposing an actually working component like vm manager to later. I would suggest putting the vm manager back in Q4, fixing the worst bugs and releasing Q4.

**Comment by marmarek** [comment] 2017-12-29 10:38
Check version of qubes-utils package in sys-usb, very similar bug was fixed in 4.0.11 version.
If you have older one, install updates to fedora template.
If newer, check permissions on /usr/lib/qubes/udev-block-add-remove - it should be executable. If it isn't, make it executable (chmod +x) and try again.

**Comment by marmarek** [comment] 2017-12-29 10:41
Just clarify - this is about devices not showing up as block devices (qvm-block). USB passthrough in Linux (qvm-usb) do not support USB3.0 yet.

**Comment by najamelan** [comment] 2017-12-29 19:10
Ok, I will look into this as soon as I can, but currently in the middle of debugging another qubes issue. One at a time. 

The difference between qvm-usb and qvm-block wasn't clear to me. qvm-usb --help has not even got a single phrase explaining what it does, and I think I didn't find anything about it in the docs. It has no man page either. If it's not yet in stable that might be ok though, I run Q4.

**Comment by najamelan** [comment] 2018-01-01 11:53
@adavida Do you still have this problem. I had it and this is what solved it.

The cause was that in fedora-25 template which came with qubes-os, there is a script needed by udev which didn't have the executable bit set. This caused the export of the block devices to fail. Hence in dom0 `qvm-block` would not show my storage devices.

You can check this by going into your template for sys-usb, in the terminal do:
`ll /usr/lib/qubes/udev-block*`
All scripts should have the executable bit set, but notably the problematic one was: `/usr/lib/qubes/udev-block-change-add`.

Normally this was fixed in [this commit](https://github.com/QubesOS/qubes-linux-utils/commit/68d7be77dbd9871ed2df7ede71c84ae80c9105b5), but I suppose this is only in the testing repository? That might explain the several issues on usb not working.

**Comment by adavida** [comment] 2018-01-01 12:59
I test.
now actually it works, again.

thank you

**Comment by najamelan** [comment] 2018-01-01 16:52
@adavida maybe this issue can be closed?

**Closed** 2018-01-01 19:18 UTC
Labels: bug, C: other, P: major

**Comment by adavida** [comment] 2018-01-01 19:20
yes this work
