### ISSUE TITLE
Use generic modesetting driver instead i915/i965 as default

### ISSUE THREAD

**Issue by donob4n** [QubesOS/qubes-issues#4782] opened 2019-01-31 14:34 UTC
### Qubes OS version:

R4.1

### Affected component(s):

Xorg, fixes graphical artifacts with KDE (and others desktops)

---

### Steps to reproduce the behavior:
From https://groups.google.com/d/msgid/qubes-users/5cc49553-b12c-4e4d-7601-f961330a14e6%40gmail.com

I had some graphical artifacts with current stable kernel but testing latest version they become more problematic (it can not draw the main menu, task bar does not properly refresh when switching virtual desktops and also some app windows stops redrawing after some time).  

I noticed that it also fixed some ghost clicks from some windows to another (specially if they are full screen).

Also I have better system tray icons than with the other driver but I use "border1" mode. I tried to test default mode and it was pretty bad although I am not sure if it was worse or better than i915 driver.

### General notes:

According to https://www.phoronix.com/scan.php?page=news_item&px=Fedora-Xorg-Intel-DDX-Switch this seems the current default driver in Fedora so probably Qubes dom0 should adopt the same decision.

---

### Related issues:
https://github.com/QubesOS/qubes-issues/issues/3267

**Comment by marmarek** [comment] 2019-01-31 22:50
This should resolve itself automatically once we update dom0 in R4.1.

**Comment by dmoerner** [comment] 2021-11-22 21:09
On my X1 carbon 3rd generation, running R4.1, I was getting graphical artifacts in gnome-terminal and firefox when scrolling. Switching back to the "intel" xorg driver from the modesetting driver seems to fix this problem. Thank you to drpfef on IRC for suggesting this.

That is, I added the following to `/etc/X11/xorg.conf.d/20-intel.conf`

```
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
EndSection
```

I think that perhaps something like this could be added to https://github.com/Qubes-Community/Contents/blob/master/docs/troubleshooting/intel-igfx-troubleshooting.md for R4.1 users who are having trouble with the new modesetting driver? I didn't submit a pull request for the docs myself because so far this is just my one case.

**Comment by dmoerner** [comment] 2022-01-10 21:20
Just wanted to add that I also see this graphics corruption with the modesetting driver on a T460 (HD Graphics 520), although for some reason it's much rarer.

**Comment by AlxHnr** [comment] 2022-03-10 20:32
Thanks @dmoerner! Switching from `modesetting` to `intel` fixed the problem for me. Without this, I was seeing artifacts on Qubes 4.1 on my T430i (Intel HD 4000):

![animated-preview-of-artifacts](https://user-images.githubusercontent.com/8235638/157747897-08baca6e-51d8-4fd3-9667-60d4208e83e5.gif)

I also get glitches at the boot password prompt. I tried fiddling with `i915.mitigations=off`, but that makes no difference.

**Comment by alt3r-3go** [comment] 2022-04-10 17:43
As an additional data point - I also observe something very similar (streak-like artifacts on changed/highlighted portions of the screen, only in the GUI part - e.g. boot trace and Ctr+Alt+F2 console work fine) on my Intel ADL-H-based laptop. The default or explicit "modesetting" driver exhibit that and only the "intel" one fixes the problem (none provide acceleration though). That's on `kernel-latest` from the stable repo (5.16.13 as of right now), but relatively old Mesa packages that dom0 provides.

**Comment by DemiMarie** [comment] 2022-04-11 02:24
> As an additional data point - I also observe something very similar (streak-like artifacts on changed/highlighted portions of the screen, only in the GUI part - e.g. boot trace and Ctr+Alt+F2 console work fine) on my Intel ADL-H-based laptop. The default or explicit "modesetting" driver exhibit that and only the "intel" one fixes the problem (none provide acceleration though). That's on `kernel-latest` from the stable repo (5.16.13 as of right now), but relatively old Mesa packages that dom0 provides.

@marmarek is there any chance we can provide a newer Mesa?

**Comment by marmarek** [comment] 2022-04-11 03:51
> @marmarek is there any chance we can provide a newer Mesa?

If proven to solve the issue _first_, then maybe. But that's quite a few packages to repackage/rebuild, and I'm not going to do it "just in case". `sys-gui-gpu` may be helpful with testing various versions. Anyway, since the issue applies to relatively old hardware too (especially - way older than fc32 we have in dom0), it's unlikely the upgrade would help.

**Comment by alt3r-3go** [comment] 2022-04-17 11:46
Yeah, I'm not sure Mesa is the culprit here, TBH. One thing I forgot to mention is that booting the same dom0 directly (i.e. commenting out Xen and changing `module` directives to `linux` and `initrd` respectively) yields no artifacts - so it looks like that added variable of Xen changes it, though I don't see anything significant in the log diff.

There's still no HW acceleration though - and that's where newer Mesa would probably help, but that's orthogonal to the original issue reported in this thread and I just mentioned that for completeness.

**Comment by DemiMarie** [comment] 2022-04-17 12:38
> Yeah, I'm not sure Mesa is the culprit here, TBH. One thing I forgot to mention is that booting the same dom0 directly (i.e. commenting out Xen and changing `module` directives to `linux` and `initrd` respectively in the Grub menu) yields no artifacts - so it looks like that added variable of Xen changes something, though I don't see anything significant in the log diff.

That is interesting.  I wonder if disabling the IOMMU for the i915 integrated GPU would help.  @marmarek is it safe to do this, on the assumption that the iGPU is trusted?

**Comment by marmarek** [comment] 2022-04-19 10:15
> I also get glitches at the boot password prompt. I tried fiddling with `i915.mitigations=off`, but that makes no difference.

I have this on one device too. There, starting just Linux (without Xen) helps(*), but `iommu=no-igfx` does not. 

(*) there are no glitches, but when the prompt appears, I need to press ESC twice to make it update after key presses - otherwise no got appears when entering the passphrase. Could be totally unrelated issue to the graphics driver.

**Comment by marmarek** [comment] 2022-07-08 13:23
> I also get glitches at the boot password prompt.

In my instance, https://github.com/torvalds/linux/commit/bdd8b6c98239cad fixes the issue. Unfortunately, I've seen regressions elsewhere caused by this commit (https://github.com/QubesOS/qubes-issues/issues/7479).

**Comment by marmarek** [comment] 2022-07-08 13:24
@alt3r-3go @AlxHnr can you test any of the 5.18.x kernel-latest package? It includes the commit mentioned above, and also a follow up fix for it.

**Comment by DemiMarie** [comment] 2022-07-09 02:32
> @alt3r-3go @AlxHnr can you test any of the 5.18.x kernel-latest package? It includes the commit mentioned above, and also a follow up fix for it.

Does that follow up fix fix #7479?

**Comment by marmarek** [comment] 2022-07-09 03:02
> Does that follow up fix fix #7479?

Yes. But when both are applied on top of 5.15.52, it brings back glitches on plymouth (on this specific hw). Which is kind of expected as the follow up fix un-does https://github.com/torvalds/linux/commit/bdd8b6c98239cad from i915 driver point of view... There is probably some other relevant commit somewhere there, but I'd like to know how it looks for others.

**Comment by DemiMarie** [comment] 2022-07-09 03:47
Maybe there needs to be some hardware-specific quirks?

**Comment by AlxHnr** [comment] 2022-07-09 12:32
> @alt3r-3go @AlxHnr can you test any of the 5.18.x kernel-latest package? It includes the commit mentioned above, and also a follow up fix for it.

No, I don't want to. I've stopped using graphical plymonth some months ago.

**Comment by marmarek** [comment] 2022-07-09 13:55
Can you try `nopat` option to the dom0 Linux kernel?

**Comment by marmarek** [comment] 2022-07-09 15:25
Ok, `nopat` is doing more or less what the commit mentioned above. So we have (at least) two types of hardware:
 - where `nopat` (or equivalent commit) fixes glitches
 - where `nopat` (or equivalent commit) causes #7479 

I don't think `nopat` is a real solution, I think it's rather a workaround that disables something that is broken. But at least we confirmed it is the same issue (or at least very closely related) that I can reproduce locally.

**Comment by aslfv** [comment] 2022-08-27 21:57
Just for the record, this solved the issue on an alder lake notebook:
https://github.com/QubesOS/qubes-issues/issues/7507#issuecomment-1153081021

**Comment by marmarek** [comment] 2022-11-21 14:19
`nopat` might make things a bit slower (not sure if noticeable in practice). But it should not cause reboot. Can you collect a bit more details about the issue? Maybe add `noreboot` option to Xen and see if you can see the actual crash message?

**Comment by taradiddles** [comment] 2022-11-23 15:21
Quick note - I've recently opened #7894 but it seems to be a duplicate of this issue.
I've tested the `nopat` boot option workaround but still get glitches.
Using xorg's `intel` driver as a workaround isn't stable for me, I get a few random hard reboots a day.

**Comment by dmoerner** [comment] 2022-11-23 15:24
Do you see the crashes with the intel driver + kernel 5.10.112?

**Comment by taradiddles** [comment] 2022-11-23 15:29
> Do you see the crashes with the intel driver + kernel 5.10.112?

I don't remember testing that specific kernel version - I'm running 5.15.76-1 now. If there's a need to test 5.10.112 I could do so, although as mentioned crashes with the intel driver seem totally random and don't happen often, so there's no guarantee that a day without crash would mean that a particular kernel version works...

**Comment by dmoerner** [comment] 2022-11-23 15:38
Sorry, I should have provided more context. There's a few other bugs that could be causing these crashes, and I haven't seen anything since I stayed on an older kernel. 

https://github.com/QubesOS/qubes-issues/issues/7664
https://github.com/QubesOS/qubes-issues/issues/7902

**Comment by taradiddles** [comment] 2022-11-24 07:08
@dmoerner, do I understand correctly that you're using the `intel` driver without crashes with an older kernel ? If so, is that the version you mentioned - kernel 5.10.112 ?
Coincidentally there's a a long [forum thread](https://forum.qubes-os.org/t/qubesos-freeze-crash-and-reboots/12851) (which you might be aware of) mentioning plenty of crashes people are having for quite some time - not explicitly with `intel` - although that could actually end up being one of the culprits. It'd be interesting to know by what time you began to have issues...

**Comment by marmarek** [comment] 2022-11-25 14:48
As noted in https://github.com/QubesOS/qubes-issues/issues/7894#issuecomment-1325260948, the glitches with modesetting driver seems to affect window managers not using compositing.

FWIW, I can see the same behavior under Xen 4.17(-rc3).

**Comment by DemiMarie** [comment] 2022-11-27 02:43
@alt3r-3go: does `iommu=no-igfx` on the Xen command line make the problems go away, with or without `nopat` on the Linux command line?

**Comment by DemiMarie** [comment] 2022-11-28 01:24
> Would the above but with the `modesetting` driver be of interest?

It absolutely would, thanks!  Also, a test using a both a compositing manager and `modesetting` at the same time would be greatly appreciated.

> In the past (older kernels), that didn't help with the artifacts and as this is my daily driver I'm wary of getting into a state where disk corruption is possible (in case it hangs in a similar way and the console trick doesn't work and I have to hard-shutdown it), if there's no real need.

There are known problems with the `intel` driver that can cause system misbehavior.  These are bugs in Xorg but are not likely to be fixed any time soon.

**Comment by taradiddles** [comment] 2022-11-28 05:32
> There are known problems with the `intel` driver that can cause system misbehavior

For the record, switching to the older "UXA" acceleration method seems to [fix crashes](https://forum.qubes-os.org/t/qubesos-freeze-crash-and-reboots/12851/177) some people had with `intel`. YMMV - it made my laptop freeze at suspend.

```
Section "Device"
          Identifier "Intel Graphics"
          Driver "Intel"
          Option "AccelMethod" "UXA"
EndSection
```

**Comment by DemiMarie** [comment] 2022-11-29 20:55
> @DemiMarie,
> 
> > > Would the above but with the `modesetting` driver be of interest?
> > 
> > 
> > It absolutely would, thanks! Also, a test using a both a compositing manager and `modesetting` at the same time would be greatly appreciated.
> 
> Tested this, makes no difference to the `intel` driver (except for the artifacts, of course) - same freeze.

Do you mean that:

- The freezes are observed when using the modesetting driver, as well as when using the Intel driver, if the default command line options are used?
- The artifacts are present with modesetting but not with intel?

> The compositioning is enabled in the Window Manager Tweaks, throughout all those tests - is that what you mean?

Yes

**Comment by DemiMarie** [comment] 2022-12-01 22:59
@alt3r-3go: does `i915.enable_psr=0` help?

**Comment by marmarek** [comment] 2022-12-03 15:37
That's interesting observation. Huge pages are not supported under Xen PV, but I can try checking if native Linux with huge pages disabled will have this issue then (that would be far not the only difference, so it isn't comprehensive test, but maybe will find something...).

**Comment by marmarek** [comment] 2022-12-03 20:50
Negative. With huge pages disabled, native Linux still works fine on the same machine.
For reference, here are 3 kernel logs: native with huge pages enabled, huge pages disabled, and xen pv: https://gist.github.com/marmarek/ac54c1f76fec64b5fa6d6ea937eaa6ec

**Comment by marmarek** [comment] 2022-12-05 20:25
Observation: taking a screenshot in dom0 makes all the current glitches go away (but as soon as something changes on the screen, it's again glitchy).

**Comment by marmarek** [comment] 2022-12-05 21:24
The other issue (affecting VM windows only, if composition is disabled) is also gone with the above patch.
Now we need proper solution...

**Comment by DemiMarie** [comment] 2023-02-24 02:27
The modesetting driver still needs to actually be made the default.  @marmarek: can the TearFree patch be backported?

**Comment by marmarek** [comment] 2023-02-24 09:43
> The modesetting driver still needs to actually be made the default.

It is already the case (see the very first comment in the issue).

> can the TearFree patch be backported?

I don't know what you are talking about. But it looks offtopic in this issue.

**Closed by marmarek** 2023-02-24 09:43 UTC
Labels: T: enhancement, C: other, P: default, r4.1-buster-stable, hardware support, r4.1-bullseye-stable, r4.1-dom0-stable, r4.1-centos-stream8-stable, r4.1-bookworm-stable
