### ISSUE TITLE
xfce problem with volume - + 

### ISSUE THREAD

**Issue by gulyaev-artem** [QubesOS/qubes-issues#5858] opened 2020-05-27 18:24 UTC
**Qubes OS version**
R4.0
dell xps 15 9560

**Affected component(s) or functionality**
xfce brightness 

**Brief summary**
I have f11 and f12 keys for setting suitable brightness. But ~2weeks ago this function was broken. When key is pressing I can see a notification in the bottom right angle but the brightness is not adjustable.

**To Reproduce**
_Steps to reproduce the behavior:_
_1._ Press f11 or f12

**Expected behavior**
Increase or decrease brightness

**Actual behavior**
doing nothing

**Solutions you've tried**
Set brightness via driver in /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness

**Comment by Aporbel** [comment] 2020-07-31 15:50
still does not work

**Comment by rapenne-s** [comment] 2023-06-29 20:20
Could you try on R4.1 with latest kernel?

**Comment by andrewdavidwong** [comment] 2023-07-14 18:39
Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2023-07-14 18:39 UTC
Labels: T: bug, R: cannot reproduce, C: desktop-linux-xfce4, P: default, hardware support, needs diagnosis
