### ISSUE TITLE
"Domain halting" message on qube startup

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3680] opened 2018-03-08 21:42 UTC
#### Qubes OS version:

R4.0rc5

#### Affected component(s): 

Desktop

---

### Steps to reproduce the behavior:

Start qube

### Expected behavior:

Notification - "Domain xxx is starting"

### Actual behavior:

On Occasion the notification says:
"Domain xxx is halting" - the qube starts none the less.

### General notes:

I can see no consistent pattern.
In any case "Domain" should be replaced as per normal usage.
Issues raised on qubes-users list

---

**Comment by marmarta** [comment] 2018-07-15 22:51
Fixed by https://github.com/QubesOS/qubes-desktop-linux-manager/commit/0e52962f5a73c7e80503e88764b9904c1945816f - notifications were rewritten and also checked if they are attached to correct events (which this one was not).

**Comment by constantoverride** [comment] 2018-08-21 19:42
However, if you try to shutdown `sys-net` while `sys-firewall` is running, the notification `Domain sys-net is halting.` is shown, but `sys-net` isn't really halting (it can't because `sys-firewall` must be shutdown first), so it's a fake notification... It should either not be shown, or better yet, show a text describing that other VMs depend on `sys-net` so it can't be halted.

**Comment by marmarek** [comment] 2019-12-11 01:53
I believe it is a duplicate of #5380 (already fixed in R4.1).

**Closed by marmarek** 2019-12-11 01:53 UTC
Labels: C: core, T: bug, ux
