### ISSUE TITLE
Debian 8 Terminal no longer starts up

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1195] opened 2015-09-19 20:38 UTC
I'm not really sure what happened, but as of early this week, after running normal Debian package update, the terminal app will no longer launch in either the `debian-8` TemplateVM or any of my AppVMs based on this template. Launching terminal looks like it is going to start up, but after the icon bounces up and down for a few moments it then disappears and never launches.

However, running Chromium from my AppVMs based on my debian-8 template still seems to run.

**Comment by marmarek** [comment] 2015-09-19 20:47
Try starting `xterm` and check `locale` output - you'll probably receive
some error - please tell what exactly message is.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment] 2015-09-19 21:01
@marmarek I added XTerm to the TemplateVM launcher and ran it. Then I typed `locale` into that terminal. Here is the printout

```
user@debian-8:~$ local
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MOENTARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
user@devian-8~$
```

**Comment by marmarek** [comment] 2015-09-19 21:05
Ok, so you don't have `en_US.UTF-8` locale generated - run `sudo
dpkg-reconfigure locales` and make sure the entry `en_US.UTF-8` is
selected.
I'll add some script to somehow automate this task...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment] 2015-09-19 21:11
@adrelanos what is the best way to fix this problem? Changing
`/etc/locale.gen` in qubes-agent-linux.postinst doesn't look like the
cleanest solution... The problem is that users already have system
installed and if selected locale isn't generated, some applications
(notably `gnome-terminal`) doesn't work at all. So we need some solution
for already installed systems, not only for fresh template installs.
Maybe pulling locales-all package is the way to go?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment] 2015-09-20 04:17
Not sure. This is essentially what @grml -debootstrap does during build.

```
[ -n "$DEFAULT_LANGUAGE" ] || DEFAULT_LANGUAGE='en_US:en'
[ -n "$DEFAULT_LOCALES" ] || DEFAULT_LOCALES='en_US.UTF-8'
/usr/sbin/update-locale LANGUAGE="$DEFAULT_LANGUAGE" LANG="$DEFAULT_LOCALES"
```

Does that help, fix it? Do you have instructions on how to force/reproduce this issue? Then I might be able to research how to fix this.

I also think inventing code to write to `/etc/locale.gen` is too hacky/unstable. If still needed, we could try reusing code from `/var/lib/dpkg/info/locales.postinst`.

If still it would fix this reliably, I guess installing the `locales-all` package by making it a dependency would also be an acceptable solution. Not great. (Not most minimal image.) But nevermind.

**Comment by bnvk** [comment] 2015-09-20 10:38
@marmarek thanks much. Setting the locale solved the issue and I can now run Terminal again.

Regarding @adrelanos question, I'm not sure what caused the issue exactly, but I just opened #1196 as I've been having weird issues updating my debian-8 TemplaceVM for the last week or two and the Terminal / locale issue might be correlated!

**Comment by marmarek** [comment] 2015-09-20 11:26
On Sat, Sep 19, 2015 at 09:17:15PM -0700, Patrick Schleizer wrote:
> Does that help, fix it?

No, the problem is when the locale is set to value not present in
`/etc/locale.gen`, it will not be regenerated. And even worse - when
generated manually, it will be removed on next `locale-gen` run (for
example `locales` package upgrade.
By default `/etc/locale.gen` contains only comments.

> Do you have instructions on how to force/reproduce this issue? Then I might be able to research how to fix this.

Ensure you have unmodified `/etc/locale.gen`, then call `locale-gen` (as
it would be called on `locales` package upgrade). You'll see that
`locale` command returns errors now and `gnome-terminal` isn't working.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment] 2015-10-05 15:05
@adrelanos how should we proceed here? Install `locales-all` or some better idea? 
Does apt-get install the `Recommends:` packages on dist-upgrade? If not, how this should be done (to not force `locales-all` in minimal template at the same time)?

**Comment by adrelanos** [comment] 2015-10-05 15:39
I don't know yet.

Marek Marczykowski-Górecki:
> Does apt-get install the `Recommends:` packages on dist-upgrade?

Definitively not.

> If not, how this should be done (to not force `locales-all` in minimal
template at the same time)?

There is no great solution to this. As a technical limitation of apt
(and others), there is no such thing as a "weak dependency". What you
could do is inventing a qubes-recommended-packages meta package, that
depends on locales-all. Not great. I would suggest to not care about
minimal packages. If it helps, just install locales-all. It's not that big.

**Comment by iuriguilherme** [comment] 2015-10-09 02:42
`sudo dpkg-reconfigure locales` on the debian-8 template haven't helped, when trying to launch terminal from menu in an AppVM with debian-8 template, it still doesn't show up. Also, once it crashed the Qubes VM Manager.

I'm still right-clicking on the AppVM and running `x-terminal-emulator`.

PS: I used "pt_BR.UTF-8" as locale.

**Comment by iuriguilherme** [comment] 2015-10-09 02:55
The fix provided in #1182 (using en_US.UTF-8) seemed to have no effect whatsoever.

Also, adding Xterm and UXterm shortcuts on the menu also won't work.

"Run command in VM" from right-clicking in the AppVM on Qubes VM Manager is the only thing that works, giving these options:

```
x-terminal-emulator
gnome-terminal
xterm
uxterm
```

`debian-7` TemplateVM doesn't seem to be affected, nor its AppVMs.

**Comment by marmarek** [comment] 2015-10-09 10:39
Try installing updates, similar problem (about missing `python-dbus`
package) was recently fixed. The locale problem affected only
gnome-terminal, not xterm.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by iuriguilherme** [comment] 2015-10-12 16:04
> The locale problem affected only gnome-terminal, not xterm.

As I stated, my AppVMs relying on `debian-8` TemplateVM won't start anything from the KDE menu.

Also, I can no longer use commands like "attach/detach audio/bloc device" from within the Qubes VM Manager on those AppVMs.

They're only usable when I "run command in VM" and `x-terminal-emulator`.

I am forced to use `debian-7` for all my non Fedora work (Mumble, for instance).

**Comment by desci** [comment] 2015-10-13 22:33
Just backed up everything, installed R3 and restored backup.

AppVM previously relying on `debian-7` was assigned to `debian-8` and seems to be working.

Not sure how people who had installed R3 rc3 will deal with this, though.

**Comment by adrelanos** [comment] 2015-10-21 16:18
It seems "just install `locales-all`" is the "easy, magic fix" here, no? I think that is much better than troubling more with config file edit by scripts and manual locale generation.

My suggestion is:

* remove all the custom code
* install `locales-all`
* minimal templates complaints (I doubt that) -> patches welcome

One day, for multiple languages support, we'd need this anyhow, no?

**Comment by marmarek** [comment] 2015-10-21 16:37
On Wed, Oct 21, 2015 at 09:18:07AM -0700, Patrick Schleizer wrote:
> * install `locales-all`

Ok, so it should go to `Depends:`, right?

> One day, for multiple languages support, we'd need this anyhow, no?

Yes, probably.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment] 2015-10-21 16:58
Marek Marczykowski-Górecki:
> On Wed, Oct 21, 2015 at 09:18:07AM -0700, Patrick Schleizer wrote:
>> * install `locales-all`
> 
> Ok, so it should go to `Depends:`, right?

Yes.

(I see no other way to install it / fix it on existing systems.)

**Closed** 2015-10-30 14:18 UTC
Labels: bug, C: Debian, C: templates, P: major

**Comment by marmarek** [comment] 2015-10-30 16:52
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment] 2015-10-30 16:52
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment] 2015-11-01 00:37
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment] 2015-11-01 00:37
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by adrelanos** [comment] 2015-11-02 16:25
The `sudo apt-get install locales-all` approach has worked for another existing user. (https://www.whonix.org/forum/index.php/topic,1855.0.html) I think the above commit is a good solution.

**Comment by marmarek** [comment] 2015-11-12 03:46
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment] 2015-11-12 03:46
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment] 2015-11-12 22:44
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/f7fa61e0b34ec36b689c4b8fb1e157e96c8cce37...45d9f78ebc885dd4095cfa66a43637a9d0726d68

**Comment by marmarek** [comment] 2015-11-12 22:45
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/f7fa61e0b34ec36b689c4b8fb1e157e96c8cce37...45d9f78ebc885dd4095cfa66a43637a9d0726d68

**Comment by v6ak** [comment] 2015-11-13 20:11
Because I have a VM with 1GiB root filesystem, adding locales-all was a space issue for me. So I have created following exclusion file:
https://gist.github.com/v6ak/b3cfbb9de5101d5393fd

Reinstall of some packages is needed after adding the file to /etc/dpkg/dpkg.cfg.d/ .

**Comment by adrelanos** [comment] 2015-11-13 20:41
I didn't know about the `path-exclude` feature yet. Thanks for sharing!
