### ISSUE TITLE
Qubes i3 Bar Color Not Changing Correctly

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#2632] opened 2017-02-14 03:21 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Gui-dom issue

---
Screencasts of the issue: https://streamable.com/ofuuk https://streamable.com/25b3u

### Expected behavior:
Moving the mouse from a red-color AppVM windows to a container of two gray-color AppVM windows should keep its gray-color.

### Actual behavior:
The container of two gray-color AppVM windows should remain gray.

### Steps to reproduce the behavior:
* Open i3wm in Qubes Gui-VM
* Open a container of two or more AppVM windows
* Arrange in a similar fashion to one of the screencasts
* Find that Window Title color of container sometimes does not change correctly

### General notes:
* The bug does not depends on how fast you switch between windows
* Switching between windows can be done with the mouse of relative keyboard shortcuts

---

**Comment by anadahz** [comment] 2018-11-17 22:53
@anoadragon453 are you still able to reproduce this issue?

**Comment by anoadragon453** [comment] 2018-11-17 23:38
Not sure, I don't have a Qubes OS machine to test at the moment. Feel free to close for the moment until somebody else reports :)

**Comment by andrewdavidwong** [comment] 2018-11-17 23:42
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-11-17 23:42 UTC
Labels: C: desktop-linux, P: minor, bug, help wanted
