### ISSUE TITLE
/usr/lib/qubes/usb-import: cannot open /sys/devices/platform/vhci_hcd/status: No such file

### ISSUE THREAD

**Issue by Joeviocoe** [QubesOS/qubes-issues#3483] opened 2018-01-21 04:53 UTC
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

debian-9
fedora-25

---

### Steps to reproduce the behavior:

qvm-usb -a untrusted sys-usb:2-12

### Expected behavior:

No error, usb device from sys-usb VM attaches to the untrusted AppVM

### Actual behavior:

/usr/lib/qubes/usb-import: 34: /usr/lib/qubes/usb-import: cannot open /sys/devices/platform/vhci_hcd/status: No such fileNo unused port found!/usr/lib/qubes/usb-import: 52: /usr/lib/qubes/usb-import: cannot create /sys/devices/platform/vhci_hcd/attach: Directory nonexistent

### General notes:

On target AppVM, there is no longer a directory called /sys/devices/platform/**vhci_hcd**
There is a directory called **vhci_hcd.0**

I don't know how or when this changed.  It worked fine on Jan 16, 2018.  But not today Jan 20, 2018.

The contents of /sys/devices/platform:
alarmtimer   dummy_udc.0       platform-framebuffer.0  uevent
coretemp.0   Fixed MDIO bus.0  power		       vhci_hcd.0
dummy_hcd.0  pcspkr	       serial8250

Looks like devices do end in ".0"
 **vhci_hcd.0** only shows up after `modprobe vhci_hcd` is run from /usr/lib/qubes/usb-import: line 3
/usr/lib/qubes/usb-import: line 5 shows:
DEVPATH="/sys/devices/platform/vhci_hcd"

The workaround that seems to work is to edit line 5 of /usr/lib/qubes/usb-import on the target VMs template to reflect the new naming convention
DEVPATH="/sys/devices/platform/vhci_hcd.0"

---

**Comment by marmarek** [comment] 2018-01-21 09:42
Duplicate of #3455, fix already in testing repository.

**Closed by marmarek** 2018-01-21 09:42 UTC
