### ISSUE TITLE
gpg fails in debian-9 based TemplateVM through Qubes UpdatesProxy - gpg: keyserver receive failed: No keyserver available

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4291] opened 2018-09-09 07:47 UTC
### Qubes OS version:
R4

### Affected component(s): 
debian-9

---

### Steps to reproduce the behavior:

Simplified gpg command for easier testing.

    sudo http_proxy=http://127.0.0.1:8082/ gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-keys 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA

The actual command of interest here would be something like the following.

    sudo http_proxy=http://127.0.0.1:8082/ apt-key --keyring /etc/apt/trusted.gpg.d/whonix.gpg adv --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-keys 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA

This is for the purpose of being able to have instructions on how one could easily add Whonix signing key to a Debian based TemplateVM or StandaloneVM so packages like tb-updater, apparmor-profiles-whonix, security-misc, etc. could be used there.

### Expected behavior:

```
sudo http_proxy=http://127.0.0.1:8082/ gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-keys 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA
gpg: requesting key 2EEACCDA from hkp server ipv4.pool.sks-keyservers.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 2EEACCDA: public key "Patrick Schleizer <adrelanos@riseup.net>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

### Actual behavior:

```
sudo http_proxy=http://127.0.0.1:8082/ gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-keys 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No keyserver available
```

### General notes:

Maybe this isn't sane to begin with and there should be some sort of Qubes service (question popup) to fetch gpg keys in DispVMs to import apt signing keys in TemplateVMs?

**Comment by unman** [comment] 2018-09-12 01:02
@andrewdavidwong This isnt a Debian bug, as it applies to any non-networked template, Fedora included.

@adrelanos 

>  there should be some sort of Qubes service (question popup) to fetch gpg keys in DispVMs to import apt signing keys in TemplateVMs

This is an excellent idea.

**Comment by andrewdavidwong** [comment] 2021-06-23 19:34
Duplicate of #4231

**Comment by andrewdavidwong** [comment] 2021-06-23 19:34
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue (see https://github.com/QubesOS/qubes-issues/issues/4231#issuecomment-866745593). If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-06-23 19:34 UTC
Labels: C: templates, T: bug
