### ISSUE TITLE
DNS resolution stopped working in sys-net and sys-firewall based on Debian 9 TemplateVM

### ISSUE THREAD

**Issue by kototama** [QubesOS/qubes-issues#5291] opened 2019-09-04 09:02 UTC
**Qubes OS version**
4.0

**Affected component(s) or functionality**
The DNS functionality of a debian VM template. 

**Brief summary**
When connecting my VM either to sys-net or sys-firewall, the DNS does not work:

**To Reproduce**

```
user@personal-email:~$ ping 10.137.0.34
PING 10.137.0.34 (10.137.0.34) 56(84) bytes of data.
64 bytes from 10.137.0.34: icmp_seq=1 ttl=64 time=0.214 ms
64 bytes from 10.137.0.34: icmp_seq=2 ttl=64 time=0.213 ms
^C
--- 10.137.0.34 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1045ms
rtt min/avg/max/mdev = 0.213/0.213/0.214/0.014 ms
user@personal-email:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 10.137.0.34 icmp_seq=1 Packet filtered
From 10.137.0.34 icmp_seq=2 Packet filtered
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1015ms

user@personal-email:~$ ping www.google.com
ping: www.google.com: Temporary failure in name resolution
user@personal-email:~$ cat /etc/resolv.conf 
nameserver 10.139.1.1
nameserver 10.139.1.2
```

**Expected behavior**
Name resolution is working.

**Actual behavior**
Name resolution is not working

**Additional context**
This VM is restored from a Qubes 3.2 installation. Nonetheless, I have other such VMs and the networking is working.

**Solutions you've tried**
Allow all outdoing connections in the firewall settings. Checked DNS resolution in the sys-net or sys-firewall: they are working.

**Comment by kototama** [comment] 2019-09-09 14:18
I got inspired by reading https://github.com/QubesOS/qubes-issues/issues/5269 and manage to regain the DNS connectivity by removing all entries in the firewall tab, disabling the firewall and rebooting the VM.

**Comment by andrewdavidwong** [comment] 2019-09-10 03:00
> I got inspired by reading #5269 and manage to regain the DNS connectivity by removing all entries in the firewall tab, disabling the firewall and rebooting the VM.

Glad to hear you got it fixed! It sounds like there's no further action to be taken on this issue, so I'll close it. Let me know if you had something else in mind.

**Comment by kototama** [comment] 2019-09-10 08:39
It still looks like it was a bug to me though. I don't know how to reproduce it. I guess we can keep it close and reopen if somebody encounters it again. At least now it is documented. Thank you.

**Comment by andrewdavidwong** [comment] 2019-09-11 01:25
> It still looks like it was a bug to me though. I don't know how to reproduce it. I guess we can keep it close and reopen if somebody encounters it again. At least now it is documented. Thank you.

Ok, reopening. To be clear, my understanding is that the bug is that a Debian template (which version of Debian?), when restored from a 3.2 backup into a 4.0 installation, does not have working name resolution.

**Comment by kototama** [comment] 2019-09-11 06:53
Sorry Andrew, I did not expressed myself very clearly: the VM used to work, even after the backup. So I don't know how much the fact that it is an old VM affects this bug.

It's Debian 9.0.

**Comment by andrewdavidwong** [comment] 2019-09-12 04:09
> Sorry Andrew, I did not expressed myself very clearly: the VM used to work, even after the backup. So I don't know how much the fact that it is an old VM affects this bug.
> 
> It's Debian 9.0.

Ok, I've updated the issue title accordingly.

**Comment by unman** [comment] 2019-10-20 01:06
I don't mind open ended bugs, but I have no idea how to approach this. I'm running a number of 3,2-4.0 VMs and haven't encountered this. I note that @kototama also has a number of other qubes where this issue has not arisen, and indeed that **this** qube worked for some time.

Unless @kototama can provide *some* hint as to actions taken/configuration that may have triggered this, I would go with his suggestion of closing it, because I see no purpose in keeping it open.

**Comment by kototama** [comment] 2019-12-07 06:51
I had the same problem again and was able to regain connectivity only by removing every entries in the firewall tab. Using `sys-net` or settiing `allow all outgoing connexions` did not helped prior to that.

I added a few rules (domains) in the firewall before losing the connectivity so maybe there is a bug with that.

**Comment by caluml** [comment] 2020-08-31 20:54
I found this report while searching for a problem I have, and think I have the same (or very similar) issue. I'm not sure what caused it to get into this state (it used to work fine), but it happens every time I start the Qube now, so I can look at logs, scripts, iptables rules etc, and try and work it out.

On the problem Qube:
```
$ cat /etc/debian_version 
10.5
$ /sbin/route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.137.0.6      0.0.0.0         UG    0      0        0 eth0
10.137.0.6      0.0.0.0         255.255.255.255 UH    0      0        0 eth0
```
```

$ ping 10.137.0.6
PING 10.137.0.6 (10.137.0.6) 56(84) bytes of data.
64 bytes from 10.137.0.6: icmp_seq=1 ttl=64 time=0.380 ms
^C
--- 10.137.0.6 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.380/0.380/0.380/0.000 ms
```

```
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 10.137.0.6 icmp_seq=1 Packet filtered
From 10.137.0.6 icmp_seq=2 Packet filtered
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 26ms
```

10.137.0.6 is the IP of my sys-firewall.

All traffic from this Qube is apparently filtered by the firewall.
I have some rules in the Qube's firewall, but ICMP should be allowed anyway, and changing it to "allow all outgoing traffic", or disabling for 5 minutes don't make any difference.

All my other Qubes are fine, so it's not a problem with the networking in general.

Are the individual Qubes Firewalling rules applied on sys-firewall? Because I can't see any of the qube's firewall rules by running iptables on sys-firewall - just generic looking rules.

Please let me if there's anything else I can try/run to help out.

**Comment by caluml** [comment] 2020-08-31 21:04
I just found #5269 and checked all the DNS entries in the firewall list, and one of them was no longer resolvable. Removing it made everything work again as expected.

**Comment by unman** [comment] 2021-05-29 14:42
I've re-read this issue, and simply have no idea.
It *looks* like it may have been an issue with qubes-firewall , rather than anything Debian specific, but since I cant reproduce it (because I have no idea what the triggering events might be), and have not experienced it myself, that gets us no further forward.
In view of the lack of progress, I suggest it be closed. @andrewdavidwong

**Comment by andrewdavidwong** [comment] 2021-05-29 16:32
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-05-29 16:33 UTC
Labels: C: Debian/Ubuntu, P: default, T: bug
