### ISSUE TITLE
Are dots allowed in VM names?

### ISSUE THREAD

**Issue by svenssonaxel** [QubesOS/qubes-issues#3382] opened 2017-12-09 17:14 UTC
#### Qubes OS version: R3.2

---

### Steps to reproduce the behavior:

1. In dom0, execute `qvm-create --label red example.1`
2. In Qubes VM Manager, click VM, Create new VM, type "example.2" as VM name and click OK.

### Expected behavior:

3. Both, OR none, of VMs "example.1" and "example.2" are created.

### Actual behavior:

3. VM "example.1" is created, but the VM created through the manager is named "example2" rather than "example.2".

### General notes:

The input box for VM name does not accept the dot character.
If dots are allowed in VM names then it should be possible to type a dot in this input field.
If dots are not allowed in VM names then `qvm-create` should not accept names that include dots.

**Comment by unman** [comment] 2017-12-09 18:07
@andrewdavidwong Duplicate of #2422. Please close

**Comment by andrewdavidwong** [comment] 2017-12-09 19:57
This appears to be a duplicate of #2422. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-09 19:57 UTC
