### ISSUE TITLE
Flickering screen when switching windows in i3

### ISSUE THREAD

**Issue by minad** [QubesOS/qubes-issues#2391] opened 2016-10-22 20:10 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0
---
### Expected behavior:

Switching between fullscreen windows should not produce a visible flickering.
### Actual behavior:

Switching fullscreen windows in the i3 window manager results in a white flicker.
### Steps to reproduce the behavior:

...
### General notes:

I am not sure if this happens only in the i3 window manager (I am currently using only i3). Maybe this is an issue of the window manager, but it could also be an issue of the isolation of dom0 X and the VM graphical output. 
---

**Comment by andrewdavidwong** [comment] 2016-10-23 07:05
Have you or anyone else been able to duplicate this on different hardware?

**Comment by minad** [comment] 2016-10-23 08:37
Maybe to clarify: With flicker I mean that when I switch from a black terminal window to another black terminal the screen is cleared in between with white and this produces the visible effect.

I will test how other window managers behave. Right now I am using qubes only on one system (lenovo yoga x1) and I am still using an old kernel 4.2.8 due to issue #2186

**Comment by andrewdavidwong** [comment] 2016-10-23 10:31
Ok. If you have access to other hardware, or if anyone else reading this can test this, it would be worth seeing whether this is reproducible on other systems, or whether it's likely a hardware-specific issue.

**Comment by minad** [comment] 2016-10-24 17:07
I switched to the new kernel (3.2 reinstallation), but the flickering is still there.

**Comment by marmarek** [comment] 2016-10-25 18:18
I think I've seen similar issue somewhere. And enabling or disabling
composition helped (don't remember which one).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by tfm1** [comment] 2016-11-06 23:25
I have the same issue (screen flashes white when switching between black terminals). I am _I_ can add that it does not happen when switching _to_ a terminal in dom0. 

I attached the qubes-hcl-report output. I also tried Qubes on an older Dell laptop a couple of month ago and had the same issue.

[Qubes-HCL-Dell_Inc_-Latitude_E7270-20161107-001406.yml.txt](https://github.com/QubesOS/qubes-issues/files/574199/Qubes-HCL-Dell_Inc_-Latitude_E7270-20161107-001406.yml.txt)

**Comment by andrewdavidwong** [comment] 2016-11-07 03:03
@minad, @tfm1: Please try enabling and disabling composition to see whether the problem is improved or resolved in either state (with composition enabled or disabled), and let us know.

**Comment by tfm1** [comment] 2016-11-07 09:48
On Sun, Nov 06, 2016 at 07:03:13PM -0800, Andrew David Wong wrote:
> @minad, @tfm1: Please try enabling and disabling composition to see whether the problem is improved or resolved in either state (with composition enabled or disabled), and let us know.

I'm sorry, but how do I do that?

**Comment by minad** [comment] 2016-11-07 11:15
@tfm1 thanks for mentioning that it doesn't happen for dom0 (for me neither). Therefore I suspect that it has something to do with the VM isolation and how the buffers between dom0 and the vms are separated.

@andrewdavidwong I think i3 doesn't use composition by default. However it seems one could use a separate composite manager. Do you expect this to go away with composition due some GL double buffering?

Maybe related issue concerning i3 and missing composition: http://askubuntu.com/questions/751149/screen-tearing-when-using-i3-none-when-using-unity

**Comment by tfm1** [comment] 2016-11-07 16:17
I tried XFCE4 and made two terminals in VMs other then dom0.
I made both terminals fullscreen then minimized the one currently on top.
It showed the other terminal _without_ flashing of the screen.

**Comment by andrewdavidwong** [comment] 2016-11-08 09:03
Hm, I'm not sure. I just wanted to make sure we tried @marmarek's [suggestion](https://github.com/QubesOS/qubes-issues/issues/2391#issuecomment-256119855) as part of the troubleshooting process, but it seems unclear how to do it with i3.

It is indeed helpful to know that it doesn't happen for dom0, though.

**Comment by cyrinux** [comment] 2016-11-08 09:53
FYI, I have less flickering problem with use of xcompmgr for enable
composition on i3

Le lun. 7 nov. 2016 à 10:48, tfm1 <notifications@github.com> a écrit :

On Sun, Nov 06, 2016 at 07:03:13PM -0800, Andrew David Wong wrote:
> @minad, @tfm1: Please try enabling and disabling composition to see
whether the problem is improved or resolved in either state (with
composition enabled or disabled), and let us know.

I'm sorry, but how do I do that?

>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/QubesOS/qubes-issues/issues/2391#issuecomment-258737301

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/QubesOS/qubes-issues/issues/2391#issuecomment-258790452>,
or mute the thread

**Comment by minad** [comment] 2016-11-08 20:08
It works with xcompmgr. At least the flickering when switching terminals is reduced greatly!

1. install xcompmgr in dom0
2. start xcompmgr in .i3/config

See https://github.com/minad/i3-config in the autostart file

**Closed** 2016-11-08 20:08 UTC
Labels: bug, C: desktop-linux, C: gui-virtualization
