### ISSUE TITLE
xen-libs as provided by Fedora 23 updates in template can never be updated

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1648] opened 2016-01-16 20:18 UTC
Hi, look at what happens when `dnf update` is run on the template:

```
[root@buildserver ~]# dnf update xen-libs
needs-restart for 23 - x86_64                                                                                   1.1 MB/s | 1.7 kB     00:00    
Last metadata expiration check performed 0:00:00 ago on Sat Jan 16 20:17:12 2016.
Dependencies resolved.
================================================================================================================================================
 Package                           Arch                     Version                               Repository                               Size
================================================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 gperftools-libs                   x86_64                   2.4-5.fc23                            fedora                                  273 k
 qemu-common                       x86_64                   2:2.4.1-5.fc23                        updates                                 294 k
 xen-libs                          x86_64                   2001:4.6.0-12.fc23                    qubes-vm-r3.1-current                   561 k
 xen-qubes-vm                      x86_64                   2001:4.6.0-12.fc23                    qubes-vm-r3.1-current                   192 k

Transaction Summary
================================================================================================================================================
Skip  4 Packages

Nothing to do.
```

Naturally, this means that the little updates icon next to the template's name in Qubes VM Manager remains on all the time.

DNF is smart enough not to delete the Qubes packages unless told otherwise:

```
[root@buildserver ~]# dnf update --best --allowerasing xen-libs
needs-restart for 23 - x86_64                                                                                   1.1 MB/s | 1.7 kB     00:00    
Last metadata expiration check performed 0:00:00 ago on Sat Jan 16 20:15:12 2016.
Dependencies resolved.
================================================================================================================================================
 Package                           Arch                     Version                               Repository                               Size
================================================================================================================================================
Installing:
 gperftools-libs                   x86_64                   2.4-5.fc23                            fedora                                  273 k
Upgrading:
 qemu-common                       x86_64                   2:2.4.1-5.fc23                        updates                                 294 k
 xen-libs                          x86_64                   2001:4.6.0-12.fc23                    qubes-vm-r3.1-current                   561 k
 xen-qubes-vm                      x86_64                   2001:4.6.0-12.fc23                    qubes-vm-r3.1-current                   192 k
Removing:
 qemu-kvm                          x86_64                   2:2.1.3-11.fc21                       @System                                   0  
 qemu-system-x86                   x86_64                   2:2.1.3-11.fc21                       @System                                  12 M

Transaction Summary
================================================================================================================================================
Install  1 Package
Upgrade  3 Packages
Remove   2 Packages

Total download size: 1.3 M
Is this ok [y/N]:
```

It seems that the Qubes packages require an older `xen-libs` version by specific version.  That probably needs to change, or they need to be rebuilt.

**Comment by Rudd-O** [comment] 2016-01-16 20:19
Note that this bug is only revealed when `qemu-common` is installed in the template.  It won't be detected on the base template as is.

**Comment by marmarek** [comment] 2016-01-17 00:24
Interesting, according to the above, you still had qemu packages from Fedora 21. Something went wrong during upgrade?

**Comment by Rudd-O** [comment] 2016-01-17 21:41
No.  DNF correctly computed that Qubes' packages are not compatible with the F23 version of QEMU.

**Comment by Rudd-O** [comment] 2016-01-17 21:42
once I upgraded the Qubes packages (by first deleting the QEMU packages), I tried to install the QEMU packages again:

[root@ring2-buildserver user]# dnf install qemu-common qemu-kvm qemu-system-x86
Last metadata expiration check performed 0:00:31 ago on Sun Jan 17 21:40:52 2016.
Error: package qemu-system-x86-2:2.4.0.1-1.fc23.x86_64 requires libxenctrl.so.4.5()(64bit), but none of the providers can be installed.
package xen-qubes-vm-2001:4.6.0-12.fc23.x86_64 requires xen-libs = 2001:4.6.0-12.fc23, but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)

**Comment by marmarek** [comment] 2016-01-17 22:31
I see, qemu-system-x86 in F23 is linked with older version of xen-libs (4.5) than we use (4.6).
So the only way currently would be rebuilding qemu with xen-libs 4.6. It's simple:
```
dnf download --source qemu
dnf builddep qemu
rpmbuid --rebuild qemu*src.rpm
```

As a more long-term solution, we may try to use upstream `xen-libs` package instead of our own, but first need to verify if all the required features are there. At least 4.5 is new enough to have `libxenvchan` library and it is packaged there. But it is too late for such change in R3.1.

**Comment by Rudd-O** [comment] 2016-01-17 22:55
On 01/17/2016 10:31 PM, Marek Marczykowski-Górecki wrote:
>
> I see, qemu-system-x86 in F23 is linked with older version of xen-libs
> (4.5) than we use (4.6).
> So the only way currently would be rebuilding qemu with xen-libs 4.6.
> It's simple:
>
> |dnf download --source qemu dnf builddep qemu rpmbuid --rebuild
> qemu*src.rpm |
>
> As a more long-term solution, we may try to use upstream |xen-libs|
> package instead of our own, but first need to verify if all the
> required features are there. At least 4.5 is new enough to have
> |libxenvchan| library and it is packaged there. But it is too late for
> such change in R3.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QubesOS/qubes-issues/issues/1648#issuecomment-172391274>.
>

Can you supply in the repos updated qemu packages to override the Fedora
ones?

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by Rudd-O** [comment] 2016-06-08 21:48
Is this coming along for F23?  What about F24?

**Comment by marmarek** [comment] 2016-06-08 21:52
F24 uses Xen 4.6, so the problem shouldn't exists there. Actually, it should be possible to install qemu from F24 repositories in Fedora-23 based Qubes VM:
```
sudo dnf install --releasever=24 --disablerepo=qubes* qemu 
```
If that would work for you, I propose to close this issue.

**Comment by Rudd-O** [comment] 2016-06-08 21:59
That's probably not good enough for most users.  It's a nice workaround,
but the packages should work with the version of Xen available on the
distro.

**Comment by marmarek** [comment] 2016-06-08 22:08
As Fedora 24 should be out very soon, it will not be a problem anymore. Until next divergence in Xen version in Qubes vs Fedora... On the other hand, in VM should not be _that_ hard to make use of original distro Xen libs package, even if it's of different version. But requires careful review of that  package and our patches (the few that at applied for VM package - listed in `series-vm.conf` file).

**Comment by Rudd-O** [comment] 2016-06-08 23:48
On 06/08/2016 10:08 PM, Marek Marczykowski-Górecki wrote:
>
> As Fedora 24 should be out very soon, it will not be a problem
> anymore. Until next divergence in Xen version in Qubes vs Fedora...
>

See, that is the issue, it won't be a problem in F24, but it will become
a problem until it diverges again in that way, and that seems to be
going to be a recurring issue.  So we should have a solution that scales
over time.

**Comment by marmarek** [comment] 2019-04-12 13:31
There is a duplicate of this issue with more details and solutions: #3945

**Closed by marmarek** 2019-04-12 13:31 UTC
Labels: C: templates, P: minor, T: enhancement
