### ISSUE TITLE
In-game mouse in FPS "stuck staring at ground"

### ISSUE THREAD

**Issue by maltfield** [QubesOS/qubes-issues#8030] opened 2023-02-12 20:17 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary

If I install and open an FPS video game in a Qubes AppVM, then as soon as I touch the mouse, my view slips down to staring at the ground beneath my character's feet. If I move the mouse, all it does is spin around in circles as I stare at the ground.

Obviously, this makes FPS unplayable in Qubes OS :(

### Steps to reproduce

The below steps are specific to openarena, but this issue has been present for every FPS game that I've tried to play in Qubes.

Run the following commands to install and run Open Arena on a Debian-11-based AppVM:

```
sudo apt-get install openarena
openarena
```

Then choose the following in-game to launch into an "arena" to duplicate this bug:

1. Press `<enter>` to choose `SINGLE PLAYER`
2. Press `<enter>` to choose `fight`
3. Press `<enter>` to choose `BRING IT ON`

After a few seconds, the actual FPS game will launch. At this point, moving the mouse at all will reproduce the issue. The view on the screen will be pointed directly at the ground. Moving the mouse will just circle around the ground; you cannot look up and actually play the game.

### Expected behavior

Mouse should work like normal

### Actual behavior

I can't "look up" in the game.

**Comment by maltfield** [comment] 2023-02-12 20:22
See also https://github.com/minetest/minetest/issues/8539

**Comment by andrewdavidwong** [comment] 2023-02-13 03:10
Duplicate of #4986

**Comment by andrewdavidwong** [comment] 2023-02-13 03:10
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-02-13 03:10 UTC
Labels: T: bug, P: default
