### ISSUE TITLE
AEM boot option causes hard reboot/partial shutdown

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2155] opened 2016-07-05 22:33 UTC
#### Qubes OS version (e.g., `R3.1`):

`R3.1`, `R3.2-rc1`
#### Brief Problem Description:

Everything goes smoothly with the AEM installation up to  step 5 (reboot and select the "AEM Qubes" GRUB option). I select that  option (or allow it to be auto-selected, or select the one in the  "advanced" submenu). It gets about 4 lines in (up to "loading initial  ramdisk"), then the laptop appears to do a hard reboot/partial shutdown. Instead of a normal reboot with the BIOS and normal boot process, the screen is blank, but the system retains power. (Power button is lit and keyboard backlight brightness can be changed.)

More precisely, here are the physical symptoms, in order:
1. Screen goes blank. 
2. Screen and keyboard backlight both flash briefly, then go blank  again. 
3. Faint "pop" sound (sounds power-related). 
4. Fan dies down. 
5. Screen and keyboard backlight are dark, but Fn (function) key and power button LED are lit. 
6. Pressing keyboard backlight combination (Fn + space) toggles backlight brightness. All other keys/combinations are unresponsive. 
7. Briefly holding down power button completely shuts down the laptop (~1 second; much faster than usual).

**Comment by ttasket** [comment] 2016-07-13 04:43
For the record, I've tried various kernels including 4.1 and 4.2 copied from R3.1. Those copied kernels can boot past the AEM target and there is no reset. This suggests that a kernel 4.2 released for R3.2 could be a solution to the problem.
Kernel 4.4.14-10 from the testing repo in combination with tboot still causes system resets.

**Comment by ttasket** [comment] 2016-07-13 15:20
Per my thread post:
I am able to get 4.4.* to boot now! The trick was to add `min_ram=0x2000000` to the tboot options.

But now I cannot get AEM to seal the secret. Nothing at all about AEM is displayed during startup, even though rd.antievilmaid is on the kernel options line.

@andrewdavidwong Can you try the min_ram option? You only need to add `min_ram=0x2000000` to the `multiboot tboot` line in grub.

**Comment by rustybird** [comment] 2016-07-13 18:07
> But now I cannot get AEM to seal the secret. Nothing at all about AEM is displayed during startup, even though rd.antievilmaid is on the kernel options line.

I think this might be fixed by https://github.com/QubesOS/qubes-core-admin-linux/commit/fe6846d5ebd63c84b4dd5698a93675f09546e80a (which hasn't been released in a new package version yet)

**Comment by rustybird** [comment] 2016-07-13 18:12
@ttasket:

Sorry, forgot to say: You could try `sudo systemctl enable anti-evil-maid-seal` in dom0.

**Comment by ttasket** [comment] 2016-07-14 01:40
@rustybird Thanks, but that service is already enabled. Status shows it ran with failure code:
~~~
$ sudo systemctl status anti-evil-maid-unseal
● anti-evil-maid-unseal.service - Anti Evil Maid unsealing
   Loaded: loaded (/usr/lib/systemd/system/anti-evil-maid-unseal.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-07-13 20:55:54 EDT; 33min ago
 Main PID: 455 (code=exited, status=1/FAILURE)

Jul 13 20:55:53 dom0 systemd[1]: Starting Anti Evil Maid unsealing...
Jul 13 20:55:53 dom0 anti-evil-maid-unseal[455]: anti-evil-maid-unseal: Mounting the aem device...
Jul 13 20:55:53 dom0 anti-evil-maid-unseal[455]: anti-evil-maid-unseal: Initializing TPM...
Jul 13 20:55:53 dom0 anti-evil-maid-unseal[455]: tcsd_changer_identify: identifying TPM
Jul 13 20:55:54 dom0 anti-evil-maid-unseal[455]: install: invalid user 'tss'
Jul 13 20:55:54 dom0 systemd[1]: anti-evil-maid-unseal.service: Main process exited, code=exited, status=1/FAILURE
Jul 13 20:55:54 dom0 systemd[1]: Failed to start Anti Evil Maid unsealing.
Jul 13 20:55:54 dom0 systemd[1]: anti-evil-maid-unseal.service: Unit entered failed state.
Jul 13 20:55:54 dom0 systemd[1]: anti-evil-maid-unseal.service: Failed with result 'exit-code'.
~~~

**Comment by marmarek** [comment] 2016-07-14 01:49
This is already fixed by HW42. Just building&uploading fixed package (v3.0.3).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by ttasket** [comment] 2016-07-14 14:55
AEM now works again on my system. The keys were to update to anti-evil-maid 3.0.3 from the testing repo so it would seal, and adding the `min_ram` parameter to tboot so the system doesn't crash/restart with 4.4 kernels.

**Comment by marmarek** [comment] 2016-07-15 00:29
I wonder whether `min_ram` should be added by default. Does it have any negative side effects?

**Comment by ttasket** [comment] 2016-07-15 23:43
That would be a good question for upstream. I've CC'd gang.wei@intel.com with no response so far; I'd like to post it to the tboot mailing list after others ( @andrewdavidwong , Todd Lasman) try it out. They might say its better to upgrade tboot.

I started a fresh thread in qubes-users... https://groups.google.com/d/msgid/qubes-users/25ec3d4f-17cb-32a9-01b9-8a30c0150fe4%40openmailbox.org

**Comment by nsun1** [comment] 2016-08-03 03:44
that is platform specific, try different vendors platforms to see if this issue can be seen on all the platforms

**Comment by andrewdavidwong** [comment] 2016-08-04 04:07
Todd [confirmed](https://groups.google.com/d/msgid/qubes-users/b4d04e38-489e-2b4c-f66d-b780ed1eae60%40nowlas.org) that the `min_ram` fix worked for him.

**Comment by andrewdavidwong** [comment] 2016-08-06 05:49
@ttasket: I've now tested this. Unfortunately, there is no change on my end. I tested with `anti-evil-maid-3.0.4-1.fc20.x86_64` and added `min_ram=0x2000000 to the `tboot` options as instructed. The system still fails to boot in the same way.

**Comment by ttasket** [comment] 2016-08-06 09:42
@andrewdavidwong My AEM version is 3.0.4-1.fc23 not fc20. If you're still running Qubes 3.1 you may want to upgrade to 3.2 rc2; that's what I'm using.

tboot-devel thread here: https://sourceforge.net/p/tboot/mailman/tboot-devel/thread/005196f3-3afd-eca1-787b-841e3953b39f%40openmailbox.org/#msg35257679

Newer versions of tboot do work with Linux 4.4, at least Ubuntu's.

@marmarek Are there any specific guidelines for compiling and installing tboot for Qubes?

**Comment by marmarek** [comment] 2016-08-06 10:06
> @marmarek Are there any specific guidelines for compiling and installing tboot for Qubes?

Look at fedora package - especially spec file. It should just work to
bump the version there and provide it new tarball.

As you've probably seen, I'm looking for a way to get somehow verified
sources, as there are multiple red flags with those on sf.net.
Then we may include it aem repository as just another package (until
newer version land in Fedora).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment] 2016-08-07 01:11
@ttasket: Ok, I'll try again after I install 3.2* on this laptop.

**Comment by ttasket** [comment] 2016-09-02 17:01
@marmarek We got a signed copy of tboot 1.9.4 from ning.sun@intel.com (see inbox). Do you want to package it for Qubes and test, or test it first?

**Comment by chris-hacker-news** [comment] 2016-10-01 18:51
I had the same issue with TBOOT causing a reboot after GETSEC[SENTER]...

I am using Qubes R3.2, anti-evil-maid 3.0.4 and have a 6th gen i7 SINIT file.
I can confirm that this is an issue with an outdated TBOOT kernel.

You can manually upgrade it via Ubuntu: https://launchpad.net/ubuntu/yakkety/amd64/tboot/1.9.4-0ubuntu1

just unpack it from there and drop the "tboot.gz" and "tboot-syms" into your boot folder. Would be nice to have this by default or AT LEAST have a huge troubleshooter box over AEM which tells you to take this step manually for the time being. Searching for this issue is a freakin nightmare (and it was just one issue in a long list of avoidable problems) to be honest and in total I probably spent two full days on getting AEM to work just because the install process is so fundamentally broken and badly documented.

But in my opinion Anti Evil Maid on an SD card is pretty much necessary for running a system like Qubes OS, and some work should be done to make AEM more seamless. Qubes without AEM is terribly unsafe. This is why I think the whole process needs urgent streamlining.

So many points of failure:
1) Forgot to encrypt the volume group instead of each volume? You're fucked, but you won't know until AEM refuses to boot two hours later.
2) Selected EFI install? You're fucked yet again, but you won't know until AEM refuses to boot two hours later.
3) Forgot to fetch your latest TBOOT on your own? Well go figure, because unless you have some cool Google foo it's going to be a nightmare to debug this issue where the PC goes blank without any debug output or log...
4) Just don't get me started about the whole TPM and debugging it's refusal to let the owner own it... IMHO a TPM is a freakin schizophrenic child and your job is to cure it without a PhD degree in psychology.

**Comment by tasket** [comment] 2016-10-01 19:49
Thanks for the input @oldblob666 ...

I did look for tboot in debian and couldn't find it... assumed incorrectly that Ubuntu didn't have it either.

Of course, verifying the Ubuntu tboot package with their distro key is recommended before using it as a replacement for the fedora tboot.

> But in my opinion Anti Evil Maid on an SD card is pretty much necessary for running a system like Qubes OS, and some work should be done to make AEM more seamless. Qubes without AEM is terribly unsafe. This is why I think the whole process needs urgent streamlining.

Agreed. I think what many Qubes users lose sight of is that AEM isn't just a mitigation for physical attacks. It could also warn you if a remote attack somehow got to your firmware. So, yes, the AEM type of protection or warning system should be considered necessary for security in general.

@andrewdavidwong : Numbers 1) and 2) should be made into their own issues... these are essentially bugs addressable directly by Qubes. Though, I'll add that AEM has already streamlined somewhat over the years (re-sealing is now automatic, for instance).

As for tboot version, I think the assumption so far is that AEM is an 'extra' feature and its OK to defer to Fedora's decisions about updating it. But Qubes can address that, too, by supplying updated version directly.

TPM unfortunately is idiosyncratic with insufficient documentation of the ownership flow or the significance/mechanics of physical presence. The AEM documentation might be a good place to shed light on that topic, though one would expect the computer's documentation to supply the right info.

**Comment by oldblob666** [comment] 2016-10-01 20:14
@tasket Thanks for your answer :).

5) "tpm_takeownership -y -z" seems to be strictly necessary as the tools around TPM and AEM doen't seem to support SRK and it's even worse if you enter an owner key. 

6) $LABEL_SUFFIX is set to /run/anti-evil-maid/suffix, which does not exist. Why not simply use the UUID of the AEM drive?

I have basically just on issue left. And that is unsealing doesn't work. I think it's related to (6). I could fix the "anti-evil-maid-seal" script by simply hard-coding the proper AEM drive path into it. Unfortunately I couldn't yet find the "anti-evil-maid-unseal" script. It seems as if it would pickup the correct label "aem" but can't find it... I think I would change it to UUID, if I could only locate the script for unseal :D.

**Comment by oldblob666** [comment] 2016-10-01 21:10
FINALLY I got it to work, see my updated comment above!

**Comment by oldblob666** [comment] 2016-10-01 21:23
Sorry for spamming ^^... Another thing I would like to see (I may even implement it myself someday) is a randomized boot keyboard, so that a keylogger is not sufficient to record your boot encryption password.

There is a tradeoff by simply having a strong long key that you never enter (backup key), plus a combination of a shorter key + TPM sealed file that is unsealed with the secret. Then a keylogger is also not enough (but you basically just need one AEM device)... Which is why I would prefer the randomized keyboard. This would make it pretty much impossible to get access without some really elaborate hardware modifications that still pass the TPM check, right?

**Comment by tasket** [comment] 2016-10-04 15:23
@nsun1 : Using the tboot 1.9.4 that I compiled doesn't seem to help. If I remove the min_ram parameter, the system restarts much like before.

With min_ram, the system unseals the secret and boots normally-- but wake from suspend no longer works. When its suspended and I press the power button, the HD light flashes like it normally does, but the screen never powers on. The power button keeps pulsing as if the system were still asleep, but after a minute the CPU fan starts running fast.

@chris-hacker-news : Does tboot 1.9.4 allow your system to sleep and wake up?

**Comment by nsun1** [comment] 2016-10-04 18:54
It looks like your machine needs min_ram parameter, so far we cannot tell if S3 was failed. One way is to collect from your serial port during S3 transition to identify this issue root cause.
Tboot 1.9.4 allows the S3 sleep and wake up, we usually test it with this command in linux “rtcwake -u -s 10 -m mem”

Do you have chance to get another vPro brand PC or laptop to run tboot on it, like HP, Dell all have this kind of machines?

-ning

**Comment by tasket** [comment] 2016-10-05 13:49
@nsun1 : AFAIK there are no recent Thinkpad models with rs232 ports or with docks bearing them. The other computers here are AMD or otherwise don't have TXT.

I get the same behavior using the rtcwake command. Is there a log file that might be recording info during the wake attempt?

**Comment by nsun1** [comment] 2016-10-05 16:31
I am using the HP EliteDesk 800 and Dell T430 server for tboot dev.
When tboot got control returned from S3, tboot log will have all the print out afterwards, attached is an example from my HP EliteDesk.

**Comment by tasket** [comment] 2016-10-13 14:55
@andrewdavidwong @chris-hacker-news : Is it possible to test tboot 1.9.4 on your systems to see how sleep/wake work? It would be good to have the extra input and get a sense for how common the waking problem is.

**Comment by andrewdavidwong** [comment] 2016-10-13 18:06
@tasket: Not sure when exactly I'll have time to do this, but I'll try!

**Comment by tasket** [comment] 2016-10-13 21:37
Thanks Andrew!

@nsun1 : If that log is from a serial port, can I get similar output on the vga display somehow? Unfortunately, the display doesn't seem to turn on when resuming from S3, even if tboot was loaded with the vga logging option. I somewhat doubt an in-memory log would survive a reboot on my system... is this even an option?

**Comment by tasket** [comment] 2016-10-25 22:10
Update:
I have tried updating to the latest BIOS version and installed xen 4.6.3 without any improvement. Also, switching to Linux 4.4.12 in dom0 has no effect -- System still appears to freeze during resume.

**Comment by nsun1** [comment] 2016-10-25 22:58
Usually, we try linux kernel w/ tboot, and do s3 resume with command: rtcwake –u –s 10  -m mem.

**Comment by tasket** [comment] 2016-11-01 09:48
@nsun1 : The rtcwake command in this case doesn't behave any differently than other methods of going into sleep/wake modes.

If you know of some way to retrieve a boot log from memory then I can try that. However, I'm assuming recent Intel systems scramble RAM after a system reset, making log recovery impossible.

**Comment by andrewdavidwong** [comment] 2016-11-13 11:24
@ttasket: I just re-tested the `min_ram` option on the latest R3.2 with `anti-evil-maid-3.0.4-1.fc23.x86_64`. Unfortunately, there's still no change. The system still fails to boot in the same way.

**Comment by tasket** [comment] 2016-11-14 03:38
@andrewdavidwong Thanks :)

Let us know if you test it also with tboot 1.9.4, which does boot for me; Its available from https://sourceforge.net/projects/tboot/files/tboot/ and IIRC you should have a cc of email from nsun1@intel.com 9/1/2016 with tboot signature. This newer tboot does have an issue where my system can't wake from sleep.

**Comment by rustybird** [comment] 2016-11-26 14:54
@tasket Can you paste the tboot signature into a gist? Maybe that will get more testers.

**Comment by cyrinux** [comment] 2016-11-26 17:10
i guys, I would like to try too, I have a t450s and anti-evil-maid doesn't work since my last bios update.
I can't find a rpm pour tboot 1.9.4, could you help me?

**Comment by tasket** [comment] 2016-11-27 18:44
@rustybird @cyrinux : You can download it here...

https://sourceforge.net/projects/tboot/files/tboot/

The signature is attached to this post (unzip it before using it to `gpg --verify`)
[tboot-1.9.4.gpg.zip](https://github.com/QubesOS/qubes-issues/files/614900/tboot-1.9.4.gpg.zip)

**Comment by tasket** [comment] 2016-11-27 18:50
Forgot to mention that is source code so you will have to use `make` to create the binary that is placed on the AEM boot volume.

**Comment by rustybird** [comment] 2016-11-28 17:58
@tasket:
> The signature is attached to this post (unzip it before using it to gpg --verify)
> tboot-1.9.4.gpg.zip

Thanks!

Do you know if the signing key (which was created on the same day as the signature) is mentioned anywhere online? The keyserver had 4 more keys for his email address:

````
$ gpg --verify tboot-1.9.4.tar.gz.gpg
gpg: Signature made Thu 01 Sep 2016 01:33:40 AM UTC
gpg:                using RSA key 0x314B1F9A2252E060
gpg: Good signature from "Ning Sun <ning.sun@intel.com>" [unknown]
gpg: WARNING: Using untrusted key!

$ gpg --search-keys ning.sun@intel.com
gpg: searching for "ning.sun@intel.com" from hkp server qdigse2yzvuglcix.onion
(1)     Ning Sun <ning.sun@intel.com>
          2048 bit RSA key 0x314B1F9A2252E060, created: 2016-09-01
(2)     Ning Sun <ning.sun@intel.com>
          2048 bit RSA key 0x2E06527408EB8FF1, created: 2015-04-15
(3)     Ning Sun <ning.sun@intel.com>
          2048 bit RSA key 0x6B6F8FEC54688283, created: 2015-03-06
(4)     NINGSUN <ning.sun@intel.com>
          2048 bit RSA key 0x9D127ACB85C97614, created: 2015-03-06
(5)     Ning Sun <ning.sun@intel.com>
          2048 bit RSA key 0x474191673CD2A023, created: 2015-03-05
````

(FWIW, the signature's data payload was identical to the tboot-1.9.4.tar.gz I downloaded from one of SourceForge's HTTP mirrors over Tor. Hurray)

**Comment by tasket** [comment] 2016-11-28 21:53
@rustybird -
@nsun1 can comment about the key that was used (seems to have prefered making a new key for that purpose). I get the impression trusted boot isn't a high priority project for Intel. I don't know what else to make of it.

You might feel better about verifying and unpacking the Ubuntu package instead?

**Comment by nsun1** [comment] 2016-11-28 22:40
If it is for try out or test purpose, tboot source code can be found from here: https://sourceforge.net/p/tboot/code/ci/default/tree/

You can download it with command: hg clone http://hg.code.sf.net/p/tboot/code tboot-code

**Comment by bburky** [comment] 2017-01-12 05:35
I had the same crash/reboot after `executing GETSEC[SENTER]`. I was able to fix it by using the files unpacked from the Ubuntu package.

`rtcwake –u –s 10 -m mem` seems to crash the computer with or without tboot. This is a desktop, so I don't really care though. The power light does blink like it goes into suspend. But the CPU fan goes full speed and the screen goes blank. Can't wake it. Somehow even the physical reset button didn't work. S3 suspend is enabled in BIOS. Or one time the fan didn't spin, and the reset button did work, but the computer couldn't be woken. "Sleep" works in Windows on this machine.

* [X11SSV-Q](https://www.supermicro.com/products/motherboard/Core/Q170/X11SSV-Q.cfm)
* i7-6700

(Yes, it's a weird computer. I know. Was mostly intended for gaming, decided to pick some specs to allow running Qubes and AEM too though. Need to manage to add a second USB controller for the keyboard somehow though.)

**Comment by earque** [comment] 2017-03-11 03:06
I recently experienced this same issue though I'm not sure how.  I'm pretty new to linux so my diagnosis skills are limited. 

About 3 months ago I installed qubes 3.2 on my x230 thinkpad, no issues, everything works.  AEM working fine, with a well known owner. I'm not sure what caused the change. Best I can figure is that whenever I saw a dom0 update, I updated (rather carelessly, it turns out), without really testing or even restarting.  In fact I almost never shut my machine down below s3 sleep.

One day I got tired of waiting for my laptop to become responsive and I hard restarted. The AEM grub option goes into a boot loop, which I think people in this thread are familiar with. After several days of penitent googling, it turns out that AEM now only works with 1) a well known owner, 2) the min_ram parameter set, 3) tboot 1.9.4 binaries. 

So there you have it. FWIW, AEM is installed to my boot sector and I haven't tried it on a usb device. It's hard enough to get it working as it is.

**Comment by tasket** [comment] 2017-03-13 05:53
@earque It was a Xen or Linux upgrade that triggered the problem for me... wish I could be more specific.

If you are using removable media for the boot volume, you also have to be mindful about which package updates will require that volume to be mounted as /boot (during the update). That includes xen* packages, kernel, tboot, grub and anything that gets included in the initramfs.

**Comment by n1m1** [comment] 2018-12-21 20:23
Hi,
I am experiencing the same problem with Qubes 4.0.1 and tboot 1.99 (downloaded and compiled: with the rpm provided by Fedora repo the machine does not even boot) on a Thinkpad X1 Carbon 4th gen (bios updated to the last version).

The AEM setup (2FA with TOTP and usb stick), as described on the README doc, has been pretty straightforward. No problem with the boot/sealing process. However, when put in sleep state, my laptop reboots.

I've tried to add several options to grub.cfg (i.e.` min_ram=0x2000000` and, as suggested in tboot doc, `intel_iommu=on` and `iommu=required `) but, unfortunately, without success. Without solving this problem, it is pretty hard to use AEM on a laptop.

**Closed** 2023-08-05 09:25 UTC
Labels: T: bug, C: other, P: major, eol-4.0
