### ISSUE TITLE
Qubes Manager / Restart VM not working

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3523] opened 2018-02-03 14:36 UTC
#### Qubes OS version:

Qubes 4.0 r4

#### Affected TemplateVMs: 

All

---

### Steps to reproduce the behavior:

Restart VM from Qubes Manager

### Expected behavior:

restart of the VM

### Actual behavior:

The VM stop but do not restart

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-02-03 18:28
Duplicate of #2362.

This appears to duplicate an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-02-03 18:28 UTC
