### ISSUE TITLE
Qubes Updater tray icon shows updates for fully up-to-date VMs

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#5683] opened 2020-02-22 23:24 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes Updater

**Brief summary**
Qubes Updater reports that a VM has available updates. However, I have updated the VM using the updater, and also manually tried running the update commands within the VM. The VM seems to be up to date, but the tray icon persists, even after rebooting Qubes OS.

**To Reproduce**
Not sure about exact steps to reproduce. I could provide any logs that would be helpful. I don't think I had this issue earlier. May be a recent regression?

**Solutions you've tried**
Both manually updating the VM and running Qubes Updater for it.

**Comment by hexagonrecursion** [comment] 2020-02-23 09:11
I occasionally run into this with fedora templates. The icon says there are updates available, but running the update says that the system is up to date. I think this might be caused by the fact that update check and the update itself may use different fedora mirrors. It is possible for the update to use a mirror that is less up to date than the one that was used to check for updates. Running the update several times usually fixes it.

**Comment by SaswatPadhi** [comment] 2020-02-23 09:26
Yes, I also noticed with my Fedora templates. May be different mirrors is indeed the root cause, as @hexagonrecursion mentioned.

**Comment by andrewdavidwong** [comment] 2020-02-23 10:45
Duplicate of #4667

**Comment by andrewdavidwong** [comment] 2020-02-23 10:45
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-02-23 10:45 UTC
Labels: P: default, T: bug
