### ISSUE TITLE
grave updates-preventing bug in qubes-download-dom0-updates.sh

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1593] opened 2016-01-07 21:43 UTC
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/misc/qubes-download-dom0-updates.sh#L87

and many other places there

grep -v is used.

I see why.

But that grep needs to be || true'd, otherwise whenever the grep fails, then the update itself just fails.

I had a ton of packages, they were not updated here.

Please fix.

**Comment by marmarek** [comment] 2016-01-07 22:36
There is no `set -e` before that.
Also the line you've pointed already contains a fix (https://github.com/QubesOS/qubes-core-agent-linux/commit/c46c1e4d2ce739697a64b427c5ab056a39751902) - saving exit code before `grep -v`. 
So, it would be duplicate of #1475
Maybe simply you don't have fixed package installed. Note that it wasn't backported to R3.0 yet...

**Closed by marmarek** 2016-01-07 22:36 UTC
Labels: duplicate

**Comment by Rudd-O** [comment] 2016-01-07 23:02
OK, I just upgraded, I hope that is no longer a problem, but it was causing my Qubes dom0 not to update, and I had to constantly patch the file in the updatevm.

Wish me luck, as I'm rebooting.

Did you know you're the most diligent bug fixer person I know?  Very few people at Google match your turnaround time.
