### ISSUE TITLE
No easy way to back up Salt states in dom0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7679] opened 2022-08-06 18:17 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Some users, such as myself, have a large amount of Salt states in dom0.  However, there is no built-in support for backing up these states, as they are outside of the user’s home directory.

### The solution you'd like

Provide an easy way to do exactly that.

### The value to a user, and who that user might be

All users who use Salt heavily will be able to migrate their states to another machine more easily.

**Comment by unman** [comment] 2022-08-07 10:09
There is an easy way to back up *anything* outside of the home
directory.
Copy it there.
Are you really saying that this isn't easy for anyone who customises
dom0, whether by writing salt states or by other means?

If you want a special mechanism for salt, what about other
configurations?

**Comment by andrewdavidwong** [comment] 2022-08-07 18:36
I think the spirit of #1635 arguably already encompasses this. How about generalizing #1635 and closing this as a duplicate of that issue?

**Closed** 2022-08-07 18:40 UTC
Labels: T: enhancement, P: default
