### ISSUE TITLE
Unsupported Hardware Detected: xl call failed

### ISSUE THREAD

**Issue by dimitar-petrov** [QubesOS/qubes-issues#4034] opened 2018-06-25 05:31 UTC
### Qubes OS version:

R4.0 - UEFI

### Affected component(s): 

Installation

---

### Actual behavior:

I am getting the following error:
```
Usupported Hardware Detected

This hardware lacks features requred by Qubes OS. Missing features: xl call failed .......
```

### General notes:

CPU: Intel® Core™ i7-7700HQ 2.8 GHz; Quad-core
GPU: GPU: NVIDIA® GeForce® GTX 1050 Up to 4 GB GDDR5 Dedicated graphics memory

---

**Comment by marmarek** [comment] 2018-07-26 11:47
Anything special about how you've launched the installer? It looks like you've started Linux directly, not xen. Do you use reFINd, or EFI shell for this?

**Comment by osresearch** [comment] 2020-08-04 15:54
![IMG_20200804_174532](https://user-images.githubusercontent.com/3068843/89315416-17646b80-d67b-11ea-9647-dce70cd0c290.jpg)

I've also encountered the "`xl call failed`" error when booting the Qubes installer from the EFI boot manager, although I'm using a modified version of Xen built from the head of the current Xen tree.

**Comment by marmarek** [comment] 2020-08-04 16:03
Have you also re-built toolstack included in the installer, or just xen binary? Generally those two requires matching versions.
You can also try switching to tty2 and call `xl info` to see what happens.

**Comment by osresearch** [comment] 2020-08-04 17:01
This was with just a swapped out xen binary and everything else straight from the DVD image.  I'll try applying my xen `boot.c` patch to 4.13.1 and booting it again.

**Comment by osresearch** [comment] 2020-08-05 08:55
There is something weird in the [Xen 4.13.1](https://github.com/QubesOS/qubes-vmm-xen) EFI build that produces a corrupted executable. My `unify-xen` script fails with an `objcopy` error on a clean build, and even the official Qubes 4.0.2 `BOOTX64.efi` (Xen 4.8?) seems odd:

```
$ sha256sum /tmp/qubes/EFI/BOOT/BOOTX64.efi
c571c7c0a5f2434418c5815836b2499e66150f1c489c1b82277c360806929f63  /tmp/qubes/EFI/BOOT/BOOTX64.efi
$ objcopy /tmp/qubes/EFI/BOOT/BOOTX64.efi test.efi
objcopy: /tmp/qubes/EFI/BOOT/BOOTX64.efi[.bss]: relocation count is negative: file truncated
objcopy: test.efi: failed to read debug data section
objcopy: test.efi: error copying private BFD data: file truncated
```

**Comment by osresearch** [comment] 2020-08-06 20:31
![image](https://user-images.githubusercontent.com/3068843/89579501-2f331f80-d834-11ea-9c81-69a342e847c8.png)

Running with the correct version of Xen fixed this for me (in this case Xen 4.13 built from source, with the Qubes installer kernel and initrd bundled into a single, signed unified image for UEFI SecureBoot testing).

**Comment by andrewdavidwong** [comment] 2020-08-07 06:47
Glad to hear you were able to fix it. It sounds like this has been resolved, so I'll close the issue. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-08-07 06:47 UTC
Labels: C: installer, P: default, T: bug, diagnosed

**Comment by 0nelight** [comment] 2020-08-31 13:53
> Anything special about how you've launched the installer? It looks like you've started Linux directly, not xen. Do you use reFINd, or EFI shell for this?

I also got this error when launching the installer (only vmlinux.efi, fallback and legacy is shown) from rEFInd and the solution was:
I had to switch to the EFI Shell and boot from /EFI/BOOT/BOOTX64.efi from the Disc to avoid this error.
