### ISSUE TITLE
Windows manager does not always show icon

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4171] opened 2018-07-31 19:10 UTC
### Qubes OS version:
4.0

### Affected component(s): 
Window manager. Referring to the icon that displays in the task bar used to differentiate windows

### Steps to reproduce the behavior:
In the default install you can see nautilus is installed. I believe it is named "Files". It's icon is a file cabinet. Open up this software and look in the task bar. The icon will be a padlock which is the default qubes icon.

In the application list it is correct as a file cabinet, but the open window does not match this.

### Expected behavior:
The icon should be a file cabinet

### Actual behavior:
Icon is a padlock. 

### General notes:
My guess is this is done because it is looking for different icon sizes or something and the icon size exists that the application list uses, but not the size that the task bar uses. If that is the case, then maybe it should default to whichever working icon size it has instead of using a default padlock.

**Comment by esote** [comment] 2018-07-31 21:10
It looks like the icon appears for an instant, then changes to a padlock. Hard to confirm though because it happens too fast.

**Comment by t4777sd** [comment] 2018-08-01 00:15
I also made another observation. There appears to be some problem that can cause an app to lose the icon. Previously Thunar's app showed correctly as a folder. However, now it is only showing the padlock.

I know for sure it was previously showing correctly because I still have an instance open. So, one instance shows the correct icon. Any newly created instance shows an incorrect icon..

**Comment by andrewdavidwong** [comment] 2018-08-01 01:32
Duplicate of #1495

**Comment by andrewdavidwong** [comment] 2018-08-01 01:32
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-01 01:32 UTC
