### ISSUE TITLE
Error in qubes-core-agent debian package

### ISSUE THREAD

**Issue by bleuchtang** [QubesOS/qubes-issues#4430] opened 2018-10-24 08:45 UTC
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Debian template.

---

### Steps to reproduce the behavior:

apt update && apt upgrade

### Expected behavior:

No errors

### Actual behavior:

Processing triggers for qubes-core-agent (4.0.37-1+deb9u1) ...
/etc/qubes-rpc/qubes.GetAppmenus: 20: /etc/qubes-rpc/qubes.GetAppmenus: Syntax error: "(" unexpected

### General notes:

---

**Comment by marmarek** [comment] 2018-10-24 09:44
This is duplicate of #4417

**Closed by marmarek** 2018-10-24 09:44 UTC

**Comment by bleuchtang** [comment] 2018-10-24 09:50
Sorry, I only searched in open issues...

Thank for all the jobs!
