### ISSUE TITLE
Clear RAM from data regularly, etc.

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6549] opened 2021-04-23 01:28 UTC
**The problem you're addressing (if any)**
Need some protection against a hacker pulling out a RAM chip with potentially sensitive data after connecting to it another electricity source.

**Describe the solution you'd like**
- If the disk swap is already ciphered (and otherwise this makes no sense), it can be solved by flushing VMs to
disk after a period of inactivity and clearing both memory of the VM and other memory areas.

- Another solution would be use (I don't remember a cryptographic term, but the theorem that that's possible (I think, in the assumption that P!=NP) does exist) processing data in memory _without deciphering even temporarily_ (so the data remains ciphered even in CPU registers). This solution seems inefficient and any ciphers that allows processing without deciphering are less "secure" (I don't know the details) than usual ciphers. But this second solution may be the most secure (but that doesn't matter much for desktop systems where secret data could be seen on the screen during the work, anyway).

**Where is the value to a user, and who might that user be?**
Anyone who has costly or dangerous secrets:
- militaries.
- governments.
- big tech
- big pharma
- etc.

**Describe alternatives you've considered**
Turn it off (or reboot) automatically after a period of no user input to clear the memory.

**Additional context**
I do understand that it's hard to implement.

I do understand that it matters only if the attacker is rich enough to produce a specialized memory controller to do the relevant attack.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment] 2021-04-23 02:18
Duplicate of #1562

**Comment by andrewdavidwong** [comment] 2021-04-23 02:19
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-04-23 02:19 UTC
Labels: P: default, T: enhancement

**Comment by vporton** [comment] 2021-04-23 07:38
It isn't a duplicate of #1562: That one to wipe memory only on shutdown and I suggest to wipe it while running (e.g. periodically).

**Comment by andrewdavidwong** [comment] 2021-04-23 08:33
> It isn't a duplicate of #1562: That one to wipe memory only on shutdown and I suggest to wipe it while running (e.g. periodically).

You didn't read the issue history. It also included wiping memory returned during memory rebalancing, but that already occurs. It also makes no sense to wipe memory while in use, because the system would be unusable. Users would be losing their data. You say to wait for a period of idle inactivity. That will never fly. Users who get a phone call and have to go afk will come back to lost work, etc. Anyway, the other issue is meant to cover all such relevant cases, so it'd still be a duplicate.

**Comment by vporton** [comment] 2021-04-23 10:33
> > It isn't a duplicate of #1562: That one to wipe memory only on shutdown and I suggest to wipe it while running (e.g. periodically).
> 
> You didn't read the issue history. It also included wiping memory returned during memory rebalancing, but that already occurs. It also makes no sense to wipe memory while in use, because the system would be unusable. Users would be losing their data. You say to wait for a period of idle inactivity. That will never fly. Users who get a phone call and have to go afk will come back to lost work, etc. Anyway, the other issue is meant to cover all such relevant cases, so it'd still be a duplicate.

I did read but didn't notice a reference to the "rebalancing" thing. But this isn't a duplicate:

Certainly, I meant wiping _unused_ memory. You seems to say that the current version of Qubes already does this.

The difference of my proposal is to write memory to disk in a ciphered form and then clear _all_ sensitive information in memory (not only "unused" memory). After this the system is "stopped" and asks for disk password again.

The measures of #1562 are not enough, because #1562 doesn't wipe disk uncipher info from the memory.
