### ISSUE TITLE
Caching in updates proxy

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4643] opened 2018-12-20 14:07 UTC
### Qubes OS version:

`R4.0`

### Affected component(s): 

Updates proxy

---

### Steps to reproduce the behavior:

Update multiple qubes of the same distribution

### Expected behavior:

Files are only downloaded once, and then cached by the updates proxy.

### Actual behavior:

Files are downloaded many times.

### General notes:

This can be a problem for users with many similar templates and metered network connections.

---

**Comment by marmarek** [comment] 2018-12-20 14:15
Duplicate of #1957

**Closed by marmarek** 2018-12-20 14:15 UTC
