### ISSUE TITLE
Qubesd fails to start, freshinstall R4.0, string to float, localization

### ISSUE THREAD

**Issue by Bockwurst-Mit-Puls** [QubesOS/qubes-issues#3960] opened 2018-06-05 13:04 UTC
### Affected component(s): 

---

### General notes:

---

**Comment by marmarek** [comment] 2018-06-05 13:08
Looks like a duplicate of (already fixed in updates) https://github.com/QubesOS/qubes-issues/issues/3960
Let me guess, en_DK locale? You can install with different locale, update, then change back to en_DK.

**Closed by marmarek** 2018-06-05 13:08 UTC

**Comment by Bockwurst-Mit-Puls** [comment] 2018-06-05 13:12
Yeah, I just made some typing here because of the fickle mobile site. At first the issue was empty.

**Comment by andrewdavidwong** [comment] 2018-06-06 01:00
@marmarek 
> Looks like a duplicate of (already fixed in updates) #3960

Typo? #3960 is this issue.

**Comment by marmarek** [comment] 2018-06-06 12:00
The correct issue is https://github.com/QubesOS/qubes-issues/issues/3753

**Comment by andrewdavidwong** [comment] 2018-06-07 04:07
Duplicate of #3753
