### ISSUE TITLE
Error with qubes.GetAppmenus

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#4486] opened 2018-11-07 17:41 UTC
### Qubes OS version:
R4.0
### Affected component(s): 
qubes.GetAppmenus
### Steps to reproduce the behavior:
Update debian buster to lastest version
### General notes:
I know that this topic has already been discussed on GitHub but I saw that it was only discussed for debian stretch and for the debian buster there was no such topic. The solution has already been given "qvm-sync-appmenus debian-10 from dom0" but I only informs that there is such an error after the last update in the debian buster.
https://0bin.net/paste/ZqXPZSOm5Lx3dUNx#rhPnhUzMUZUBeQVC38x2z3AiDgBCEoc-ps0JIMlrTcK

**Comment by andrewdavidwong** [comment] 2018-11-08 04:34
Duplicate of #4417

**Comment by andrewdavidwong** [comment] 2018-11-08 04:35
> I know that this topic has already been discussed on GitHub

**Always** include the issue number of the issue you're referencing.

> but I saw that it was only discussed for debian stretch and for the debian buster there was no such topic.

1. We usually don't have separate issues for separate versions.
2. That issue (#4417) **does** include Debian Buster. It clearly has the `r4.0-buster-cur-test` label.

> https://0bin.net/paste/ZqXPZSOm5Lx3dUNx#rhPnhUzMUZUBeQVC38x2z3AiDgBCEoc-ps0JIMlrTcK

This looks like spam or a phishing attempt (random link to an unfamiliar domain with no description or explanation for its presence in the bug report). Use GitHub's built-in file hosting instead.

**Closed by andrewdavidwong** 2018-11-08 04:35 UTC
