### ISSUE TITLE
Issue Starting AppVM (Libxenlight)

### ISSUE THREAD

**Issue by Rspigler** [QubesOS/qubes-issues#6040] opened 2020-09-09 21:11 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Starting AppVM

**Brief summary**
I usually have an issue starting this one specific AppVM.  It is nothing special (Qube based on a fedora-32 templateVM; PVH mode).

My hardware supports IOMMU and has a TPM (supports all requirements for 4.0).

Starting the AppVM through the Qubes menu results in this error:

> 'AppVM Name' has failed to start:  internal error: libxenlight failed to create new domain 'Name'

Attempting to start with `qvm-run 'AppVM Name' xterm` results in the error:

> 'AppVM Name': Start failed:  internal error: libxenlight failed to create new domain 'AppVM Name', see /var/log/libvert/libxl/libxl-driver.log for details

The log shows:

> xc: panic: xc_dom_boot.c:141 xc_dom_boot_mem_init: can't allocate low memory for domain: Out of memory
libxl: libxl_dom.c:692:libxl_build_dom: xc_dom_boot_mem__init failed: Operation not permitted
libxl: libxl_create.c:1288:domcreate_rebuild_done: cannot (re-)build domain:  -3

While it may seem like I have too many AppVM's open, the only Qubes I have running are sys-net and sys-firewall.  I am able to start other AppVMs.  When I quit them, I still cannot start this AppVM.

**To Reproduce**
Don't know how to reproduce.  Usually only happens for this one AppVM.  Restarting my laptop fixes the issue.

**Expected behavior**
AppVM should start

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/3125
https://github.com/QubesOS/qubes-issues/issues/2482

**Comment by andrewdavidwong** [comment] 2020-09-09 21:20
Are there any devices assigned to the VM? In particular, devices that are also assigned to the running `sys-net`, for example?

**Comment by Rspigler** [comment] 2020-09-09 21:26
No, no devices assigned

**Comment by marmarek** [comment] 2020-09-10 23:17
How much memory the VM has assigned? Check both 'maxmem' and 'memory' properties.

**Comment by Rspigler** [comment] 2020-09-14 20:03
I had raised that previously to try to fix the problem - is it possible I raised it too high?

Initial memory: 2095 MB
Max memory:  20950 MB
VCPUs no.: 8
(Include in memory balancing checked)

**Comment by unman** [comment] 2020-09-15 01:12
On Mon, Sep 14, 2020 at 01:03:30PM -0700, Robert Spigler wrote:
> I had raised that previously to try to fix the problem - is it possible I raised it too high?
> 
> Initial memory: 2095 MB
> Max memory:  20950 MB
> VCPUs no.: 8
> (Include in memory balancing checked)
> 

If I set *any* of my qubes to that level of maxmem, they wont start.
Just saying.

**Comment by Rot127** [comment] 2021-04-27 18:34
I've got the same problem and fixed it by creating it again with another name.
In my case I tried to create a VM with the name "Android". Renaming it to "Android-9" solved the problem.

The root cause was an old template VM I had already deleted which had also the name "Android".
In order to install the Android-x86 image I had to change the file: `etc/qubes/templates/libvirt/xen/by-name/Android.xml `.
Because of the change it wasn't deleted when I deleted the old Android VM.
Removing this file allowed me to create a new Android VM and start it.

**Comment by Rspigler** [comment] 2021-04-27 18:39
I'm sorry, @unman solved this for me last year. I thought I had responded and closed.

Mam memory was set too high.

**Comment by jamke** [comment] 2022-12-13 17:41
I have the same issue, please consider reopening the ticket as it actually has **no solution**.

> If I set *any* of my qubes to that level of maxmem, they wont start.

I have qubes with 32GB max limit that have been starting with no issues for a long time (at least from R4.0).

The situation:
- I have a qube with 4GB-32GB min-max memlimit set on a PC with 64 GB of memory.
- After I shut this qube down - the memory was given to other VMs (even if those does not need it) and I could not start qube again because of not enough memory for 4GB start. I checked free memory in `dom0` using `xentop`, as I hope it provides proper results, and it was not enough memory (less than 4GB).
- I checked the logs - the messages are the same as @Rspigler, so it's the same issue.

So, the whole Qubes/Xen approach with memory is a bit dubious, isn't it:
- The qube allocates 15GB of memory of 32GB maxmem allowed
- The qube gets shut down manually, 
- Almost all freed memory is spread for VMs that did not need it a second ago,
- The qube won't start again (even 4GB is not available anymore),
- Other VMs do not need that much memory, they just have maxmem set high for different occasions when they need it.

Maybe this situations can be somehow improved? I never had it on R4.0 with the same amount of memory, but @Rspigler did, so I guess I just was lucky for such a long time.

**Comment by andrewdavidwong** [comment] 2022-12-13 23:02
@jamke: Just to make sure, you're on 4.1 (not 4.0), right?

**Comment by jamke** [comment] 2022-12-14 04:36
> @jamke: Just to make sure, you're on 4.1 (not 4.0), right?

@andrewdavidwong, yes, R4.1.1.

**Comment by jamke** [comment] 2022-12-14 04:39
Theoretical question:
- We have 64GB of memory
- We have 10 qubes with minmem 4GB and maxmem 32GB. These qubes do nothing and consume less than 50MB each. 
Can we start all 10 qubes one after another by Qubes OS design?
Or is situation with `Out of memory` an excepted behavior?

**Comment by DemiMarie** [comment] 2022-12-14 08:12
> Theoretical question:
> 
> * We have 64GB of memory
> * We have 10 qubes with minmem 4GB and maxmem 32GB. These qubes do nothing and consume less than 500MiB each.
> 
> Can we start all 10 qubes one after another by Qubes OS design? Or is situation with `Out of memory` an excepted behavior?

This should work.  I suspet the actual problem is that qmemman is not eager enough to take memory that is not being used.  (This is an area where KVM would make the problem trivial, as KVM can just use the host’s swap.)

**Comment by jamke** [comment] 2022-12-14 09:15
> This should work. I suspet the actual problem is that qmemman is not eager enough to take memory that is not being used. (This is an area where KVM would make the problem trivial, as KVM can just use the host’s swap.)

I see. Maybe it does work most of the time, because I had this `Out of memory` issue for the first time in years (while this problem existed in R4.0 according to the ticket).

**Comment by jamke** [comment] 2023-01-06 07:17
Today I was not able to start qube with only 1 GiB of memory (no balancing) because of out of memory on a system with 64 GB of memory and only ~10 GB of memory actually used by running qubes.
`xentop` showed that only 800 MiB was free, because all the memory was distributed to the running qubes up to the highmem settings, even if this qubes did not need that amount of memory at all.

=> The memory allocation process is kind of broken in this case, when some qube starts, isn't it?

**Closed** 2024-12-07 14:22 UTC
Labels: T: bug, C: Xen, P: default, affects-4.1, eol-4.1
