### ISSUE TITLE
qubesd daemon failed to start after update

### ISSUE THREAD

**Issue by UnitedHaxor** [QubesOS/qubes-issues#7997] opened 2023-01-19 07:35 UTC
### Qubes OS release
R4.1

### Brief summary
Yesterday I did an update with the Qubes Update UI, set the checkbox "Enable updates for qubes without known available updates" and checked dom0.
After reboot, the qubesd daemon did not start anymore and therefore no AppVMs were able to start (including sys-net, sys-usb, sys-firewall etc.).
I checked journalctl and got the following error:

Jan 19 07:48:15 dom0 qubesd[3059]: Traceback (most recent call last):
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/bin/qubesd", line 5, in <module>
Jan 19 07:48:15 dom0 qubesd[3059]:     sys.exit(main())
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/lib/python3.8/site-packages/qubes/tools/qubesd.py", line 38, in main
Jan 19 07:48:15 dom0 qubesd[3059]:     args = parser.parse_args(args)
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/lib/python3.8/site-packages/qubes/tools/__init__.py", line 359, in parse_args
Jan 19 07:48:15 dom0 qubesd[3059]:     namespace.app = qubes.Qubes(namespace.app,
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 886, in __init__
Jan 19 07:48:15 dom0 qubesd[3059]:     self._extensions = qubes.ext.get_extensions()
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/lib/python3.8/site-packages/qubes/ext/__init__.py", line 58, in get_extensions
Jan 19 07:48:15 dom0 qubesd[3059]:     return set(ext.load()()
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/lib/python3.8/site-packages/qubes/ext/__init__.py", line 58, in <genexpr>
Jan 19 07:48:15 dom0 qubesd[3059]:     return set(ext.load()()
Jan 19 07:48:15 dom0 qubesd[3059]:   File "/usr/lib/python3.8/site-packages/qubesusbproxy/core3ext.py", line 176, in __init__
Jan 19 07:48:15 dom0 qubesd[3059]:     self.devices_cache = collections.defaultdict(dict)
Jan 19 07:48:15 dom0 qubesd[3059]: NameError: name 'collections' is not defined
Jan 19 07:48:15 dom0 systemd[1]: qubesd.service: Main process exited, code=exited, status=1/FAILURE
Jan 19 07:48:15 dom0 systemd[1]: qubesd.service: Failed with result 'exit-code'.

I edited the file /usr/lib/python3.8/site-packages/qubesusbproxy/core3ext.py and added
import collections
after the first import (import asyncio)

I tried to start the daemon again - and it worked. Hence I rebooted, which was successful.

### Steps to reproduce
Did not try to update dom0 again, maybe the changes will be overwritten if the package would be upgraded.

**Comment by Minimalist73** [comment] 2023-01-19 08:50
I got this today too after updating my system yesterday. 
It seems to be fixed in QubesOS/updates-status/issues/3388 (https://github.com/QubesOS/qubes-app-linux-usb-proxy/commit/92cd99f) but since it's a few hours apart from the one with the issue (QubesOS/updates-status/issues/3385) a lot of people can be impacted. I can confirm that adding `import collections` manually in `/usr/lib/python3.8/site-packages/qubesusbproxy/core3ext.py` do fix this.

**Closed** 2023-01-19 15:09 UTC
Labels: T: bug, P: critical, C: usb proxy, updates testing
