### ISSUE TITLE
Installation problems with Qubes 4.0.2 final

### ISSUE THREAD

**Issue by linuxfan1000** [QubesOS/qubes-issues#5553] opened 2020-01-03 07:48 UTC
**Qubes OS version**
I am using Qubes 4.0.2 final and downloaded the ISO file immediately after release, yesterday.

**Affected component(s) or functionality**
Installer.

**Brief summary**
I used dd to write the image to an USB stick and verified the installation media. Qubes 4.0.2 installs fine until the last step when one has to choose the installation setup and check the boxes (create default vault, personal, etc; use Tor for updates) or "quit". After configuration of each template it reboots, one has to enter the pre-boot password in non-graphical mode with the error message "Failed to start Load Kernel Modules" and then it brings one back to that checkbox form configuration page. Then it will install the next template and reboot and the same process follows. The final time when I enter the password it boots and then I get something that looks like a kernel panic.

The laptop (Acer Aspire V) is fine. I have the latest BIOS firmware. I checked the memory and SSD. I have been using it with Qubes 3.1 until 4.0.1 without problems. I installed in BIOS Legacy mode.

**To Reproduce**
Install Qubes 4.0.2 final from USB Stick.

**Expected behavior**
Start install then log in normally after finished installation.

**Actual behavior**
Start install, few reboots with pre-boot password authorization and multiple post-config screens, then finally kernel panic(?).

**Screenshots**
At the very end I get a very similar screen of what  GaijinSystems posted below.

**Solutions you've tried**
Downloaded ISO again. Same problem. 
Used a different USB stick. Same problem. 
Upgraded BIOS to latest version. Same problem.
Tried to install in UEFI mode. Same problem.

I also tried adding the options  mapbs=1 and noexitboot=1 to the xen.cfg without success:
https://www.qubes-os.org/doc/uefi-troubleshooting/#installation-completes-successfully-but-then-boot-loops-or-hangs-on-black-screen

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/installation-guide/

**Comment by GaijinSystems** [comment] 2020-01-03 15:54
I'm experiencing the same problem with a thinkpad T450s.  I did not have this issue when installing 4.0.1.

My apologies for this being an image, but when switched to tty1 to see kernel/console output, it looks like a kernel panic with blk-core.c

![IMG_20200102_144757](https://user-images.githubusercontent.com/17348508/71733205-a0c66d80-2e0e-11ea-913d-2cdd869986d7.jpg)

**Comment by pure007** [comment] 2020-01-03 19:10
I can confirm this bug on my Inspiron 5379 after installing 4.0.2

**Comment by linuxfan1000** [comment] 2020-01-04 08:42
I spend all day yesterday trying to install Qubes OS 4.0.2.. This time I installed in UEFI mode. After every reboot I have to enter the pre-boot password in non-graphical mode with the error message "Failed to start Load Kernel Modules". After entering the password it always brings one back to the post installation config page and one has to select what to configure or press quit. At the very last reboot I also get a kernel panic like shown in the image of GaijinSystems posted above. Is it possible to get the ISO of 4.0.1 somewhere. It was working fine for me.

I have another questions. Is it recommended to install in Legacy BIOS mode or UEFI?

**Comment by mfp20** [comment] 2020-01-07 03:45
Similar problem here with threadripper on x399 mobo. I installed in UEFI mode, had to comment out mapbs and noexitboot in the USB installer boot cfg but I didn't in the installed system. I tried to do the post-install finalization procedure 2 times, and two times I got a sudden reboot. Third time I just ticked "do not configure anything" and continued to the installed system, but without the default VMs is hard for me to figure out what to do to manually configure them.

**Comment by marmarek** [comment] 2020-01-07 09:41
Yes, it's a known issue in the dom0 kernel, that's also why 4.0.2 is taken down from the download page. For now you can use 4.0.2-rc3.

**Comment by mfp20** [comment] 2020-01-07 13:54
> Yes, it's a known issue in the dom0 kernel, that's also why 4.0.2 is taken down from the download page. For now you can use 4.0.2-rc3.

I can confirm 4.0.2-rc3 works and ... is awesome!!! I've been testing QubesOS about once per year since the first public release and ... this is the first time I've the feeling I can replace my current distro with QubesOS. All the operations I tried went smooth, flawless. Even glxgears works! Probably steam games (proton) won't be so easy to run but ... it's a start.

Congratulation guys, it's really a good job. PLEASE, keep going.

**Comment by linuxfan1000** [comment] 2020-01-08 06:38
marmarek: Thx a lot for bringing back back the 4.0.2 RC version. I will try on the weekend.

Mayby the news section of the homepage should also be updated ASAP so users are not confused and look for the final version 0f 4.0.2.

Thx for the great work. I love Qubes. Best OS ever!

**Comment by andrewdavidwong** [comment] 2020-01-08 11:30
> Maybe the news section of the homepage should also be updated ASAP, so users are not confused and look for the final version 0f 4.0.2.

Thank you for the suggestion. I've just [added an update](https://github.com/QubesOS/qubes-posts/commit/32c3e34e59fb40d4d88319732a10d3b8c5f409bc) to the 4.0.2 announcement post.

**Comment by linuxfan1000** [comment] 2020-01-12 08:33
> > Maybe the news section of the homepage should also be updated ASAP, so users are not confused and look for the final version 0f 4.0.2.
> 
> Thank you for the suggestion. I've just [added an update](https://github.com/QubesOS/qubes-posts/commit/32c3e34e59fb40d4d88319732a10d3b8c5f409bc) to the 4.0.2 announcement post.

Hi David

I just wanted to note that in the news section of the web site it still says that the new version 4.0.2 is out. I think it would be better to also remove that so not to confuse anybody.

https://www.qubes-os.org/news/

Thx for the great work. I love Qubes OS.

**Comment by andrewdavidwong** [comment] 2020-01-12 23:27
> > > Maybe the news section of the homepage should also be updated ASAP, so users are not confused and look for the final version 0f 4.0.2.
> > 
> > 
> > Thank you for the suggestion. I've just [added an update](https://github.com/QubesOS/qubes-posts/commit/32c3e34e59fb40d4d88319732a10d3b8c5f409bc) to the 4.0.2 announcement post.
> 
> Hi David
> 
> I just wanted to note that in the news section of the web site it still says that the new version 4.0.2 is out. I think it would be better to also remove that so not to confuse anybody.
> 
> https://www.qubes-os.org/news/
> 
> Thx for the great work. I love Qubes OS.

Yes, I'm aware. That's because the News page contains a list of all the News posts, and the original 4.0.2 announcement post has not been taken down. We never take down a post after publishing it (we only add updates within the body of the post), because links to the post are immediately shared on mailing lists, social media websites, and elsewhere across the Web immediately after publication. Taking down the post would break all of those links, which would prevent people from seeing the update in the body of the post to learn what is going on. How about this: I'll add `[Delayed]` in front of the title, so that it's easier to see something's up before viewing the body of the post.

**Comment by marmarek** [comment] 2020-01-14 09:44
Updated installation image, soon to be published as R4.0.3-rc1:
https://openqa.qubes-os.org/tests/5506/asset/iso/Qubes-R4.0.3-rc1pre1-x86_64.iso

**Comment by GWeck** [comment] 2020-01-19 10:06
The installation process for this iso still has the problem that the second phase of the installation is aborted if manual partitioning is selected and the partition sizes are given in GB instead of in GiB.

See #5003 for a detailed description of this situation.

**Comment by demokir** [comment] 2020-01-26 12:00
This issue can be closed now @andrewdavidwong

**Comment by andrewdavidwong** [comment] 2020-01-26 13:53
Closing since Qubes 4.0.3 (in which this issue is fixed) has been released.

**Comment by strugee** [comment] 2020-01-28 22:45
@andrewdavidwong should this issue be unpinned then?

**Comment by firstabor** [comment] 2020-05-09 12:30
I have the same issue with R4.0.3

**Comment by andrewdavidwong** [comment] 2020-05-10 13:50
> I have the same issue with R4.0.3

Are you sure it's the same bug? Can you provide any additional details about the problem you're experiencing?

**Comment by firstabor** [comment] 2020-05-10 21:18
I don't know how to actually reproduce it.

But i used DD & Rufus and even the "Lenovo Troubleshooting" with livecd-tools.

I get an 

Panic on CPU 0 Blackscreen when booting with the installation usb plugged in.

**Comment by DashaVoronina** [comment] 2020-09-01 00:00
> Я не знаю, как это воспроизвести.
> 
> Но я использовал DD & Rufus и даже «Lenovo Troubleshooting» с livecd-tools.
> 
> как бы то ни было, я получаю
> 
> Паника на CPU 0 Черный экран при загрузке с подключенным установочным usb.

+++++ +++

**Comment by n0101** [comment] 2020-09-27 16:28
Same problem as firstabor.  Dell Precision 7540 with most recent BIOS.  Read through installation docs to see which BIOS settings to try changing. No luck trying to install 4.03 from usb made with rufus dd.  Following settings have been tested
intel software guard extension set to enabled, disabled, controlled by OS.
secure boot is disabled.
TPM off
TPM 2.0 on
Fastboot minimal
Fastboot thorough
Switchable graphics (nvidia optimus/and power express) enabled and disabled.

All have resulted in attached screenshot when attempting to boot to usb.
![PXL_20200927_160426382](https://user-images.githubusercontent.com/43557511/94370149-36e8a500-00bc-11eb-96f0-5f72baaff2c3.jpg)

And it doesn't ever reboot, have to manually restart.

Not sure if this means anything but the top of the screen says ioapic_old_on and using old ack method.

**Comment by marmarek** [comment] 2020-09-27 17:33
This looks like a different issue than the one here reported originally. Moved to a new issue: https://github.com/QubesOS/qubes-issues/issues/6092

**Closed by marmarek** 2020-09-27 17:33 UTC
Labels: C: kernel, P: critical, T: bug
