### ISSUE TITLE
Updates with no action, no detail (including dom0)

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#6916] opened 2021-09-24 02:10 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0

### Brief summary
1. a dom0 update (via the Updater) did nothing:

```
Updating dom0

local:
    ----------
```

This was on 22 Sept., two days ago. Copy of [`/var/log/dnf.log`](https://gist.github.com/Ark-of-the-copepod/7409b45bc84ef7bd82e54517a84c6bcb.js), and [the log previous](https://gist.github.com/Ark-of-the-copepod/201b226fa61b13a967a4a65c18c2074d). 

Could this just be wifi dropping out?
`Sep 22 12:37:24 DEBUG not found deltainfo for: Qubes OS Repository for Dom0`

`Sep 22 12:37:24 DEBUG not found updateinfo for: Qubes OS Repository for Dom0`

2. 
Now I am slightly spooked, I also wonder why the updates to my identical VPN vms (debian 10, PVH, standalone) have not asked me to reboot (e.g. shown the little green circular arrow). [Log](https://gist.github.com/Ark-of-the-copepod/88d2e8e96da658add8f38b8e568a5ddf).

### Steps to reproduce

Follow update prompts from Updater.

### Expected behavior

See informative details. 

- If it is a connectivity failure, a meaningful error message should be reported.
- if no reboot (of vm) is required, a different icon to show that (e.g. circle arrow with small checkmark) in Qubes Manager

### Actual behavior

Fail or not with no indication.

**Comment by andrewdavidwong** [comment] 2021-09-24 06:36
Duplicate of #6632

**Comment by andrewdavidwong** [comment] 2021-09-24 06:36
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-09-24 06:36 UTC
Labels: T: bug, P: default

**Comment by Ark-of-the-copepod** [comment] 2021-09-24 07:48
I missed that post.

However, there is still point 2:

> ... I also wonder why the updates to my identical VPN vms (debian 10, PVH, standalone) have not asked me to >reboot (e.g. shown the little green circular arrow). Log.

**Comment by andrewdavidwong** [comment] 2021-09-24 08:47
> However, there is still point 2:
> 
> > ... I also wonder why the updates to my identical VPN vms (debian 10, PVH, standalone) have not asked me to >reboot (e.g. shown the little green circular arrow). Log.

[Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) However, this sounds more like a question. Since 
[the issue tracker is not the right place to ask questions,](https://www.qubes-os.org/doc/issue-tracking/#do-not-submit-questions), you might wish to ask about this on the Qubes Forum or qubes-users instead.
