### ISSUE TITLE
Merge PR#192 with branch release4.0

### ISSUE THREAD

**Issue by jdorel** [QubesOS/qubes-issues#5495] opened 2019-12-01 12:11 UTC
**Qubes OS version (if applicable)**: R4.0

**Affected component(s) or functionality (if applicable)**: qubes-core-agent-linux

**Brief summary**
Merge https://github.com/QubesOS/qubes-core-agent-linux/pull/193 with branch `release4.0`

**Additional context**
The issue this PR fixes affects current archlinux templates

**Comment by andrewdavidwong** [comment] 2019-12-01 23:11
@marmarek, after reading https://www.qubes-os.org/doc/version-scheme/#git-tags-and-branches, it is clear that all new development happens in the `master` branch of each repo, which explains why https://github.com/QubesOS/qubes-core-agent-linux/pull/193 was merged into `master`. However, it is not clear what the process is for getting bug fixes into the current, latest release branch (currently `release4.0`). This would not be a backport, since 4.0 is the latest supported release, so it's not clear why this request is necessary.

**Comment by andrewdavidwong** [comment] 2019-12-01 23:58
(Pinning was accidental.)

**Comment by marmarek** [comment] 2019-12-02 00:23
I backport fixes periodically, based on issues labels (for info whether fix is uploaded to the repository) and milestones. This is why issues should have milestone set to "oldest affected, supported version".
Helpful links with issues filters are here: https://github.com/QubesOS/qubes-issues/#issues-by-release
This particular commit/PR isn't listed there, because the commit had only reference to issue, but not "fixes" keyword, so the issue isn't considered fixed yet (by filters, github etc). This is also why the issue #5443 is still open. And sadly our tooling doesn't support retroactively marking a commit as a fix for some issue, because that information is taken from the commit message which is immutable as soon as it's merged.

**Comment by andrewdavidwong** [comment] 2019-12-02 14:24
> I backport fixes periodically, based on issues labels (for info whether fix is uploaded to the repository) and milestones. This is why issues should have milestone set to "oldest affected, supported version".
> Helpful links with issues filters are here: https://github.com/QubesOS/qubes-issues/#issues-by-release
> This particular commit/PR isn't listed there, because the commit had only reference to issue, but not "fixes" keyword, so the issue isn't considered fixed yet (by filters, github etc). This is also why the issue #5443 is still open. And sadly our tooling doesn't support retroactively marking a commit as a fix for some issue, because that information is taken from the commit message which is immutable as soon as it's merged.

If I'm understanding correctly, this means:

* https://github.com/QubesOS/qubes-core-agent-linux/pull/193 was merged into `master` _because_
* it was classified as "new development" rather than a bug fix for R4.0 _because_
* it did not claim to `fix` #5443 (using a "fixes"/"closes" keyword)

If it had, then everything would have worked, because #5443 is correctly on the 4.0 milestone.

Questions:

* If a PR is correctly classified as a **fix** for a bug in 4.0, would there be any backporting involved? (I'm thinking no, because 4.0 is the latest support release. But if so, then I want to align my understanding and use of the term "backport" to yours.)
* Does the above effectively make this issue a duplicate of #5443?

**Comment by marmarek** [comment] 2019-12-02 16:17
> * [QubesOS/qubes-core-agent-linux#193](https://github.com/QubesOS/qubes-core-agent-linux/pull/193) was merged into `master` _because_
> 
> * it was classified as "new development" rather than a bug fix for R4.0 _because_
> 
> * it did not claim to `fix` #5443 (using a "fixes"/"closes" keyword)

No, both new feature and bug fixes are merged to master first. But then bug fixes are backported to R4.0 (or other supported branches).

> Does the above effectively make this issue a duplicate of #5443?

Yes.

**Comment by andrewdavidwong** [comment] 2019-12-03 07:49
Duplicate of #5443

**Closed** 2019-12-03 07:48 UTC
Labels: C: core, P: default, T: task
