### ISSUE TITLE
4.1, window focusing not always working

### ISSUE THREAD

**Issue by jalbstmeijer** [QubesOS/qubes-issues#7100] opened 2021-12-02 10:37 UTC
### Qubes OS release

R4.1

### Brief summary

It seems sometimes it's not possible to get the focus on a window by clicking on it.
I think toggling "Always on top" such window causes it to happen. The underlying window might get the focus instead sometimes.
You need to retry a coupe of times to get the focus working again.

### Steps to reproduce

1. Open a app window, in my case a browser
2. Open on top of that two terminal windows
3. Toggle for one of those terminal windows "Always on top"
4. Click around to switch focus between the tree windows, and see that sometimes the "Always on top" window does not get the focus and you need to fiddle around to give it focus.

### Expected behavior

Any mouse click on a window should give that window focus.

### Actual behavior

Sometimes windows don't get focus and that state seems to stick till you  fiddle around a bit between windows.

**Comment by andrewdavidwong** [comment] 2021-12-03 21:33
Possible duplicate of #1455 and/or #3267.

**Comment by steakknife** [comment] 2021-12-21 23:21
I also experience this. It happens after Qubes has been running a while.

**Comment by locriacyber** [comment] 2022-03-08 00:55
Cannot reproduce under branch https://github.com/QubesOS/qubes-gui-agent-linux/pull/152

**Closed** 2024-12-07 14:15 UTC
Labels: T: bug, C: gui-virtualization, P: default, affects-4.1, eol-4.1
