### ISSUE TITLE
Fedora update dependency issues - dom0 & Fedora 28 template

### ISSUE THREAD

**Issue by torjunkie** [QubesOS/qubes-issues#4629] opened 2018-12-17 08:27 UTC
### Qubes OS version:

4.0

### Affected component(s): 

1. dom0 updates
2. Fedora 28 template updates

---

### Steps to reproduce the behavior:

In dom0, run: 

sudo qubes-dom0-update

In Fedora-28 template, update via Qubes Manager.

### Expected behavior:

Installs all available updates.

### Actual behavior:

Actual outcome:

1. dom0 won't update this package due to "skipping packages with conflicts"

qubes-mgmt-salt-dom0-virtual-machines.noarch 4.0.15-1.fc25

2. Fedora 28 won't update these packages:

Problem 1: cannot install the best update candidate for package libsane-hpaio-3.18.6-10.fc28.x86_64
  - problem with installed package libsane-hpaio-3.18.6-10.fc28.x86_64
  - nothing provides libnetsnmp.so.35()(64bit) needed by libsane-hpaio-3.18.6-11.fc28.x86_64
 Problem 2: cannot install the best update candidate for package hplip-libs-3.18.6-10.fc28.x86_64
  - problem with installed package hplip-libs-3.18.6-10.fc28.x86_64
  - nothing provides libnetsnmp.so.35()(64bit) needed by hplip-libs-3.18.6-11.fc28.x86_64
 Problem 3: cannot install the best update candidate for package hplip-3.18.6-10.fc28.x86_64
  - problem with installed package hplip-3.18.6-10.fc28.x86_64
  - nothing provides libnetsnmp.so.35()(64bit) needed by hplip-3.18.6-11.fc28.x86_64
================================================================================
 Package              Arch          Version                Repository      Size
================================================================================
Skipping packages with broken dependencies:
 hplip                x86_64        3.18.6-11.fc28         updates         16 M
 hplip-libs           x86_64        3.18.6-11.fc28         updates        204 k
 libsane-hpaio        x86_64        3.18.6-11.fc28         updates        127 k

Transaction Summary
================================================================================
Skip  3 Packages

Nothing to do.
Complete!

### General notes:

Note: running standard dom0 packages, standard Fedora 28 template with zero tweaks i.e. I didn't cause this issue with any cute changes. --allowerasing doesn't fix it. --best wants to remove packages, so that won't work.

On a side note, Debian rarely has these dependency issues - but it seems to be a semi-regular issue with Fedora. Will be nice when you ditch Fedora for something better in dom0.

---

**Comment by RooneyMcNibNug** [comment] 2018-12-17 21:31
Can confirm I am having this same issue with the Fedora 28 template VM as well upon attempting to update - "cannot install the best update candidate for package libsane-hpaio-3.18.6-10.fc28.x86_64"

**Comment by andrewdavidwong** [comment] 2018-12-18 06:08
Same.

**Comment by torjunkie** [comment] 2018-12-18 08:09
Fedora 28 workaround

Don't know if it's the canonical method, but this works (but ends up removing 3 packages), but enables "normal" updates via Qubes Manager etc. without any further errors:

1. Create a clone of the Fedora 28 template (just in case)
2. Run (as per jrsmiley in associated ticket):

sudo dnf clean all
sudo dnf --releasever=28 distro-sync --best --allowerasing

3. Restart Fedora 28 template

Run normal update

sudo dnf update

Dependencies are resolved.

dom0 issue

dom0 package is still a major problem, since it gives you the sys-whonix or sys-firewall failing with error code "1" when you try to run a normal dom0 update. 

That is, if you had upgraded all the other recent packages, except that one that is skipped. This explains the qubes forums posts about this issue in a few places recently with the same dom0 error.

So some sort of manual workaround is required i.e. force update of that package somehow.
 
BTW it is easy enough to upgrade without noticing it was skipping one package, so perhaps that could be highlighted better in the default dom0 messaging (different color for skipped packages?). Needs also a default msg that it is recommended against, since it will likely lead to a broken system, as in this instance?

**Comment by marmarek** [comment] 2018-12-18 14:01
> dom0 package is still a major problem, since it gives you the sys-whonix or sys-firewall failing with error code "1" when you try to run a normal dom0 update.

The `failed with code: 1` message is spurious, it doesn't indicate any problem in that place (fix for it is already in current-testing). https://github.com/QubesOS/qubes-issues/issues/4616

qubes-mgmt-salt-dom0-virtual-machines 4.0.15 require qubes-core-dom0 >= 4.0.35 (which is already in stable). What version do you have? If older, then it's correct that qubes-mgmt-salt-dom0-virtual-machines update is skipped. But then, it's interesting why you don't see qubes-core-dom0 update...

I've tried on several R4.0 systems and none of them tried to skip `qubes-mgmt-salt-dom0-virtual-machines` update. Anything special about the configuration? Non-default mirror?

As for the Fedora 28 dependency issue, looks to be an update that went into stable to soon: https://bodhi.fedoraproject.org/updates/FEDORA-2018-e7d66d4d3f

**Comment by torjunkie** [comment] 2018-12-18 21:19
Thanks marmarek. 

Perhaps it was a weird mirror issue? Further qubes0dom0-update command (ignoring exit code 1) solves the problem and correctly updated everything, including that package. The dom0 issue is 'solved'. +1

**Comment by andrewdavidwong** [comment] 2018-12-19 06:02
Looks like the Fedora 28 issue is `not our bug` (upstream Fedora issue), and `sys-whonix: command failed with code: 1` is a duplicate of #4616.

So, this issue is only about getting "skipping packages with conflicts" with respect to `qubes-mgmt-salt-dom0-virtual-machines.noarch 4.0.15-1.fc25`.

**Comment by torjunkie** [comment] 2018-12-19 08:07
Hi Andrew,

This is closeable:

- Fedora 28 issue (not your bug).
- dom0 issue resolved by running qubes-dom0-update again and ignoring spurious failure message regarding network connection (that msg is itself fixed in testing repo).
- Probable outlier mirror issue (?) and/or other general network problem suspected in the dom0 instance since it can't be reproduced by anyone.

**Closed** 2018-12-19 23:38 UTC
Labels: C: other, bug
