### ISSUE TITLE
QubesOs 4.0.1 Installation fatal error when installing qubes-template-fedora-29-noarch (973/1042)

### ISSUE THREAD

**Issue by fedoraerror1** [QubesOS/qubes-issues#4840] opened 2019-02-23 19:58 UTC
### Qubes OS version: 4.0.1 
Fatal error during clean install from ISO. V4.0.1. All systems affected and even baremetal USB installation fails during package 973.
Message during install:

The following error occured while installing. This is a fatal error and installation will be aborted.

DNF error: Non-fatal POSTIN scriplet failure in rpm package qubes-template-fedora-29
"
EOM

**Comment by marmarek** [comment] 2019-02-23 20:09
Do you see any more details about that failure? You can also switch to tty2 and look into /tmp, you should find various logs there. Especially packaging.log and anaconda.log may be useful.

What partitioning layout do you use? How large is the target device? Maybe it's just too small?

**Comment by fedoraerror1** [comment] 2019-02-23 20:19
tried on 128GB and 256GB. Both failed. 
Completeley new SSD disks. clean out of the box.
Going to give it another try. How do I switch to tty2? ALT+F2 didnt work.

**Comment by marmarek** [comment] 2019-02-23 20:20
Alt+Ctrl+F2

**Comment by fedoraerror1** [comment] 2019-02-23 20:39
anaconda.log
21:21:28,051 WARN anaconda: /usr/lib64/python3.5/_collections_abc.py:603: DeprecationWarning: Will be removed in 1.0. Access properties with Device.properties.
self[key]
21:21:28,053 WARN anaconda: /usr/lib/python3.5/site-packages/blivet/udev.py:117: DeprecationWarning: Will be removed in 1.0. Access properties with Device.properties.
if ret:
21:21:28,056 WARN anaconda: /usr/lib64/python3.5/site-packages/dnf/base.py:1280 DeprecationWarning: group_install() expects group id instead of Comps object.
dnf.logging.depr(msg)
21:21:28,626 INFO anacond: Preparing transaction from installation source

Interesting enough now the package is running further and is currently at package 975.
I'll let it run and if it finishes successfully, I'll try it again to reproduce the error and get the packaging.log

**Comment by fedoraerror1** [comment] 2019-02-23 20:51
Finished. 
Got in packaging.log only these 2 things.
ERR dnf.rpm: Non-fatal POSTTRANS scriptlet failure in rpm package kernel
WARN packaging: Can't delete nonexistent download location: /mnt/sysimage/dnf.package.cache.

Going to run a new installation again.

**Comment by marmarek** [comment] 2019-02-23 22:03
Oh, different package this time.
See also other logs there...

**Comment by tvori-dobro** [comment] 2021-01-17 23:14
Same here: Qubes OS version 4.0.3
Message: "The following error occurred while installing. This is a fatal error and installation will be aborted.

DNF error: Error unpacking rpm package qubes-template-fedora-30-4.0.1-201912252234.noarch"

No luck to install Qubes OS.

I've tried two completely different USB drives written on different PCs with checksums verified, but the result is the same. Unusual things about the computer are an ~7 y.o. processor and only 8GB of RAM available.

Did not have a lot of time to dig into it, though.

**Comment by Quantumdit** [comment] 2021-01-18 04:46
I got a similar error as @tvori-dobro today, also on 4.0.3, also on a machine with an older processor (~5 years old) and 8GB of RAM, also verified checksums.

Message: "The following error occurred while installing. This is a fatal error and installation will be aborted.

DNF error: Error unpacking rpm package qubes-template-whonix-ws-15-4.0.1-201910102356.noarch"

**Comment by tvori-dobro** [comment] 2021-01-19 00:25
@Quantumdit did you try to deselect Whonix 15 Template package before installing Qubes OS? 

I was able to install  4.0.2 without any issues. ISOs and additional files here: https://mirrors.edge.kernel.org/qubes/iso/

Absolutely all logs and errors in two versions were identical, except /tmp/packaging.log 
_"DEBUG dnf: Warning: scriptlet or other non-fatal errors occurred during transaction.
CRIT dnf: qubes-template-fedora-30-4.0.1-201912252234.noarch was supposed to be installed but is not!"_

Unsuccessful installation had general log format:
_"dnf.rpm: Installed: qubes-template-fedora-30-4.0.1-201912252234.noarch"_

But successful installation had another format:
_"Installed: qubes-template-fedora-30-4.0.1-201912252234.noarch
dnf.rpm: qubes-template-fedora-30-4.0.1-201912252234.noarch"_

I do not know what is wrong with 4.0.1 and 4.0.3 release, but it seems that in 4.0.2 it was fixed. 
dnf error "was supposed to be installed but is not!" has a long history on the forums.

I am out of time, that's all I can help.

**Comment by Jashan092** [comment] 2021-03-07 05:33
I also get the same error and I checked packaging.log and get this in the last lines. ![20210307_110255.jpg](https://user-images.githubusercontent.com/79596062/110230126-b042ba00-7edc-11eb-8582-281a7d2c9249.jpg)

**Comment by tokideveloper** [comment] 2021-06-27 07:28
I got the same message like @tvori-dobro [above](https://github.com/QubesOS/qubes-issues/issues/4840#issuecomment-761897954), too, but when installing R4.0.4 on a certain machine A. I also got this message on another machine B where I could install R4.0.1 (or was it R4.0?) *successfully* in the past.

I'd like to help to find the bug. What can I do?

**Comment by tokideveloper** [comment] 2021-07-03 15:38
Now, I got Qubes OS successfully installed on machine A. The thing was that the ISO image on my USB stick was broken although the downloaded ISO image is not. However, I could repair the ISO image on my USB stick and now it works!

Since I had to boot in UEFI mode, the boot screen where I could have test the media did not appear. Is it possible to test the media in UEFI mode before starting installing? This would be great!

**Comment by marmarek** [comment] 2021-07-03 21:35
> Since I had to boot in UEFI mode, the boot screen where I could have test the media did not appear.

It is back there in R4.1.

**Comment by eggshellwalker** [comment] 2021-08-03 12:48
> Now, I got Qubes OS successfully installed on machine A. The thing was that the ISO image on my USB stick was broken although the downloaded ISO image is not. However, I could repair the ISO image on my USB stick and now it works!
> 
> Since I had to boot in UEFI mode, the boot screen where I could have test the media did not appear. Is it possible to test the media in UEFI mode before starting installing? This would be great!

How did you fix the media? I have the exact same problem as you installing Qubes.

**Comment by tokideveloper** [comment] 2021-08-04 15:20
> > Now, I got Qubes OS successfully installed on machine A. The thing was that the ISO image on my USB stick was broken although the downloaded ISO image is not. However, I could repair the ISO image on my USB stick and now it works!
> > Since I had to boot in UEFI mode, the boot screen where I could have test the media did not appear. Is it possible to test the media in UEFI mode before starting installing? This would be great!
> 
> How did you fix the media? I have the exact same problem as you installing Qubes.

With a quick-and-dirty-written prototype-like homemade tool. ;-)  It only works on a Linux system and is not for production.

Since I think that there is a broader interest in that tool, I started a little project some time ago which is not yet ready for production and not yet published. If you like, I can inform you here when it's ready.

However, there is no guarantee that the media can be fixed at all due to hardware issues.

**Comment by tokideveloper** [comment] 2021-08-30 22:08
@eggshellwalker: Now, I've released the first version (0.1.0) of my repair tool: https://codeberg.org/tokideveloper/ddpolymerase/

Hope that it will be helpful.

**Comment by DemiMarie** [comment] 2021-11-12 20:04
Okay to close as “won’t fix for R4.0, fixed in R4.1”?

**Comment by tokideveloper** [comment] 2021-11-13 08:23
> Okay to close as “won’t fix for R4.0, fixed in R4.1”?

IMHO, the problem is not of Qubes OS, so it cannot be fixed by any Qubes OS Release.

The [self-test routine](https://github.com/QubesOS/qubes-issues/issues/4840#issuecomment-873473606) could be broken or even the partition table (which would lead to a non-bootable medium).

What we could do is to put instructions for verifying the ISO image on the USB drive, similar like [here](https://github.com/QubesOS/qubes-issues/issues/7030#issuecomment-957474638), onto the Qubes OS website. But that step alone will not repair the USB drive image in case it is broken.

**Comment by DemiMarie** [comment] 2021-11-13 10:35
Closing as “not our bug” (Qubes OS is not responsible for the problem, in this case a broken USB drive).

**Closed by DemiMarie** 2021-11-13 10:35 UTC
Labels: T: bug, C: installer, P: major, R: not our bug, hardware support, diagnosed
