### ISSUE TITLE
Power outage caused gedit bug

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4019] opened 2018-06-19 19:22 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

gedit

---

### Steps to reproduce the behavior:

In the Application Menu, in `Domain: work`, select `work: Qube Settings`, goto the `Applications` tab, and move `Text Editor` over to the `Selected` category. In the Application Menu, in `Domain: work`, select `work: Text Editor`.

Note: Now gedit should be open.

Create a new document, add `change 1.` into it, save file as test.txt, add to the document `change 2.`, DO NOT SAVE. *unplug your computer while it is running*, replug in your computer, start Qubes OS.

In the Application Menu, in `Domain: work`, select `work: Text Editor`.

Note: Nothing happens.

In the Application Menu, in `Domain: work`, select `work: Text Editor`.

Note: Nothing happens.

In the Application Menu, in `Domain: work`, select `work: Text Editor`.

Note: Nothing happens.

In the Widget taskbar, click on the Qube widget (Upper right blue `Q`), in `work`, select `Preferences`.
Verify `Run in debug mode` is checked, which it was for me, then after making no changes, I clicked `OK`

In the Application Menu, in `Domain: work`, select `work: Text Editor`.

Note: gedit opens, but with no recovery screen.

Reopen test.txt.

Note: `change 2.` is lost.

### Expected behavior:

Using the Application Menu to open gedit should work the first time.
The default text editor of Fedora Qubes should recover changes since last save when a crash occurs.

### Actual behavior:

See `Steps to reproduce the behavior`

### General notes:

What might be happening with no gedit recovery:
1) gedit was trying to open a recovery window, but Qubes OS wasn't displaying the window. If so, then Qubes needs to detect this non-standard window.
2) gedit saved the recovery file in a temporary folder that does not get saved between Qube Reboots. If so, then a solution needs to be implemented so gedit recovery files are saved between reboots.
3) gedit does not have a recovery feature. In this case, either a bug report needs to be opened with gedit upstream, or a different default text editor needs to be implemented for the default Template of Qubes OS (which fedora-28 is from my understanding).

Except for # 1, these don't touch on the issue of gedit not opening the first time it is ran.

---

**Comment by andrewdavidwong** [comment] 2018-06-20 01:14
> gedit does not have a recovery feature. In this case, either a bug report needs to be opened with gedit upstream,

Looks like it autosaves if the file was previously saved, but the autosaved file is a hidden file with `~` appended:

https://askubuntu.com/questions/794918/recover-files-from-gedit

So there's no recovery screen.

> or a different default text editor needs to be implemented for the default Template of Qubes OS (which fedora-28 is from my understanding).

No: https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

-----

So, really the only issue here is Gedit not started from the application menu, which appears to be a duplicate of #3533.

**Comment by andrewdavidwong** [comment] 2018-06-20 01:14
Duplicate of #3533

**Comment by andrewdavidwong** [comment] 2018-06-20 01:14
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-06-20 01:14 UTC
