### ISSUE TITLE
Qubes Updater doesn't scroll when there are too many TemplateVMs and StandaloneVMs

### ISSUE THREAD

**Issue by djoate** [QubesOS/qubes-issues#6762] opened 2021-07-04 01:56 UTC
### Qubes OS version

R4.0

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

None

### Are you providing feedback about a specific package or packages in testing?

No

### Affected component(s) or functionality

Qubes Updater

-----
### Brief summary

If you have a lot of StandaloneVMs and TemplateVMs, the updater doesn't scroll. As a result, the updater window expands the screens, resulting in buttons and VMs will get cut off by the bottom of the screen. There is no way to resize it.

### How reproducible

Every time the updater is open

### Steps to reproduce

1. Have enoughTemplateVMs and StandaloneVMs to cause the updater to grow out of bounds
2. Open the updater

### Expected behavior

There is a scroll bar and we are able to scroll to see VMs and the buttons at the bottom

### Actual behavior

There is no scroll bar and we are not able to scroll to see VMs and the buttons at the bottom. Unable to press the update button or select VMs at the bottom (other than using TAB and ENTER)

### Solutions you've tried

N/A

### Additional context

N/A

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

N/A

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

N/A

**Comment by andrewdavidwong** [comment] 2021-07-04 03:55
Duplicate of #6221

**Comment by andrewdavidwong** [comment] 2021-07-04 03:55
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2021-07-04 03:55 UTC
Labels: P: default, R: duplicate, T: bug
