### ISSUE TITLE
Make it possible to set kernelopts through the Qube Manager GUI

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6248] opened 2020-12-02 03:29 UTC
Currently the `Kernel opts:` property in Qube Manager GUI is static and changable only through CLI e.g. `qvm-prefs -s <VMNAME> kernelopts "value"`.

Proposing to make it possible for the end-users to change the kernelopts through the Qube Manager GUI.

This could resolve following UI issue: https://github.com/QubesOS/qubes-issues/issues/6247

![2020-12-02_04-27](https://user-images.githubusercontent.com/11302521/100824624-d167ba80-3456-11eb-9010-0eac28e4ee25.png)

**Comment by alimirjamali** [comment] 2024-07-12 12:03
Duplicate of #4797?

Final [decision](https://github.com/QubesOS/qubes-issues/issues/4797#issuecomment-581112687) on the above.

**Closed** 2024-07-12 22:35 UTC
Labels: R: duplicate, T: enhancement, C: kernel, C: manager/widget, P: default
