### ISSUE TITLE
Error in Initial Setup part of install

### ISSUE THREAD

**Issue by androto** [QubesOS/qubes-issues#3754] opened 2018-03-27 20:24 UTC
### Qubes OS version:

4.0-rc5

### Affected component(s): 

Install and Initial Setup

---

### Steps to reproduce the behavior:

Run Install via USB flash drive
1. Complete first step in the Install
2. Reboot
3. Use default settings in the initial setup and try to continue.

### Expected behavior:

The installation should complete without issues.

### Actual behavior:

The installationen show an error and stops the install:

![img_5663](https://user-images.githubusercontent.com/37738881/37992976-75072e86-320d-11e8-8d2f-be4db9739af6.jpg)

### General notes:

Hardware is:
Lenovo X1 Carbon 5th Gen.

---

**Comment by marmarek** [comment] 2018-03-27 20:27
Looks like something is wrong with qubesd service. After you login into the system, check `journalctl -u qubesd.service` command output in dom0.

**Comment by andrewdavidwong** [comment] 2018-03-28 01:50
Is this a duplicate of #3753? The error messages appear to be the same.

**Comment by marmarek** [comment] 2018-03-28 01:52
Yes, it's a duplicate.

**Closed by marmarek** 2018-03-28 01:52 UTC
Labels: C: installer, bug

**Comment by andrewdavidwong** [comment] 2018-03-28 01:54
Duplicate of #3753
