### ISSUE TITLE
Changing firewall rules doesn't affect established connections

### ISSUE THREAD

**Issue by kirill9000** [QubesOS/qubes-issues#1717] opened 2016-02-02 22:13 UTC
I.e.: 1) start downloading something in AppVM, 2) go to VM Manager and change AppVM's firewall rules to "Deny" with no exceptions, 3) download continues.
That's because of "global" allowing rule in FirewallVM: `-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`
Maybe it should be split to per-AppVM rules?

**Comment by marmarek** [comment] 2016-02-02 22:25
It looks like a duplicate of #974 and feature discussed in https://groups.google.com/d/msgid/qubes-devel/20160114163808.GW4892%40mail-itl
But generally - the ultimate way for cutting a VM from the network, is setting its "netvm" to "none".

**Closed by marmarek** 2016-02-02 22:25 UTC
