### ISSUE TITLE
[enhancement] giving the option back to default for dom0 Global settings

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1509] opened 2015-12-11 17:49 UTC
i have messed a little bit with dom0 global settings , but it seems im not getting to know the right default settings. what r the default settings ? and can we have a button for that ? 

thnx

**Comment by adrelanos** [comment] 2015-12-12 02:46
UpdateVM: sys-firewall
ClockVM: sys-net
Default NetVM: sys-firewall
Default template: Fedora (?)
Default kernel: 3.18.17-7
Minimal VM's memory: 200 MiB
dom0 memory boost: 350 MiB
checked Keep dispVM in memory

**Comment by TNTBOMBOM** [comment] 2015-12-12 20:33
thnx :)

**Comment by axon-qubes** [comment] 2015-12-13 00:21
Duplicate of #1363.

**Closed by axon-qubes** 2015-12-13 00:21 UTC
Labels: duplicate
