### ISSUE TITLE
Keyboard layout changes don't propagate from dom0

### ISSUE THREAD

**Issue by hdevalence** [QubesOS/qubes-issues#1396] opened 2015-11-09 20:48 UTC
When the keyboard layout is changed in dom0 (e.g., using the KDE layout switcher in the icon tray) the change doesn't propagate to other VMs, in particular any VM you would actually be using.

This makes it basically impossible to (e.g., temporarily) change keyboard layouts from your default, since you have to go to every VM and manually reconfigure their input methods, and then do it all over again to change back.

**Comment by marmarek** [comment] 2015-11-09 21:10
Does that affect also VM started after layout change?

Currently keyboard layout is set in the VM only at VM startup time. Yes,
somehow suboptimal solution...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by hdevalence** [comment] 2015-11-09 21:27
Yes, VMs started after the layout change also don't inherit the (X11) keyboard layout from dom0.

**Comment by marmarek** [comment] 2015-11-09 21:33
Did you used per-VM layout setting in those VMs? It overrides layout
retrieved from dom0.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment] 2015-11-21 17:37
I've noticed weird behavior with International keyboards (I have 3 installed), most of the time when I switch to one (via clicking an icon in the main KDE navbar, it seems to do nothing. However, once in awhile, I'm able to access Int. characters by holding the `Alt` or `Opt` key and then typing certain keys!

**Comment by dumbl3d0re** [comment] 2016-06-08 15:07
What's the status for the fix? It's one of the biggest problems I've with Qubes.

**Comment by marmarek** [comment] 2016-06-08 22:24
For now the workaround is to use per-VM keyboard layout change feature. It should work regardless of dom0 layout, and in fact dom0 layout will no longer be propagated there.

**Comment by dumbl3d0re** [comment] 2016-06-09 09:29
Marek Marczykowski-Górecki:
> For now the workaround is to use per-VM keyboard layout change feature. It should work regardless of dom0 layout, and in fact dom0 layout will no longer be propagated there.

Yes it works, but it's really frustrating to switch layout (that takes
one to one and a half minute) just for writing "å", "ä", and "ö". And
then switch back to US layout then I'm finished. This happens quite
often because I write in Swedish (or simply write my name) quite often.

**Comment by marmarek** [comment] 2016-06-09 20:49
Do you know how to install some hook on dom0 keyboard layout change? It can be anything - from registering a script somewhere, to having a tool listening on some events.

**Comment by dumbl3d0re** [comment] 2016-06-12 07:36
Marek Marczykowski-Górecki:
> Do you know how to install some hook on dom0 keyboard layout change? It can be anything - from registering a script somewhere, to having a tool listening on some events.

No, I don't know how to do that. I'm guessing that it exist a solution,
but I have to do it myself?

**Comment by marmarek** [comment] 2016-06-12 08:45
Just looking how to trigger keyboard layout change in the VM to properly fix this issue.

**Comment by tlaurion** [comment] 2016-06-12 22:00
I Also have the same problem with "ca" keyboard.
As an example,pressing AltCar+2 is supposed to give an arobas. For some reason, that AlCar key is not working, that altcar key having the same behavior as the standard alt key. 

Dom0 is set to use english keyboard. From Qubes-manager i've selected ca keyboard. No change.I also have tried changing settings through gnome-control-center without any success from inside the VM. 

A writeup on how to fix that would be nice, since the FAQ is not helping the intl user in any way.
https://www.qubes-os.org/doc/user-faq/#my-keyboard-layout-settings-are-not-behaving-correctly-what-should-i-do

**Comment by tlaurion** [comment] 2016-06-12 22:24
What is weird is that the key sequence is seen and the key are mapped ok inside xev. I do not understand why it is impossible to type the good character directly into an application.

xev output:
```
KeyPress event, serial 31, synthetic NO, window 0x1600001,
    root 0x266, subw 0x0, time 5866343, (-681,13), root:(64,417),
    state 0x0, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 31, synthetic NO, window 0x1600001,
    root 0x266, subw 0x0, time 5867038, (-681,13), root:(64,417),
    state 0x80, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 31, synthetic NO, window 0x1600001,
    root 0x266, subw 0x0, time 5867039, (-681,13), root:(64,417),
    state 0x88, keycode 11 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XmbLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False

KeyRelease event, serial 31, synthetic NO, window 0x1600001,
    root 0x266, subw 0x0, time 5867333, (-681,13), root:(64,417),
    state 0x88, keycode 11 (keysym 0x40, at), same_screen YES,
    XLookupString gives 1 bytes: (40) "@"
    XFilterEvent returns: False

KeyRelease event, serial 31, synthetic NO, window 0x1600001,
    root 0x266, subw 0x0, time 5868574, (-681,13), root:(64,417),
    state 0x88, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

FocusOut event, serial 31, synthetic NO, window 0x1600001,
    mode NotifyNormal, detail NotifyNonlinear
```

**Comment by tlaurion** [comment] 2016-06-14 02:23
To truely have an intl keyboard, both Dom0 and Appvm need to have the same keyboard layout applied. Else, a "can" keyboard configured only through Qubes Vm manager alone will not result in the right desired behavior, eg: pressing altcar+2 won't result in "@"character that appear when both dom0 and domu are configured to use the same layout.

It seems that dom0 selected layout needs to propagate to domu.

**Comment by marmarek** [comment] 2016-06-14 03:22
> It seems that dom0 selected layout needs to propagate to domu.

Exactly why I'm looking for a way of getting a notification when dom0 keyboard layout is changed.

**Comment by marmarek** [comment] 2016-06-14 03:25
An idea: watch `_XKB_RULES_NAMES` property on root window. But first requires a verification if that's part of official API, not an implementation detail (which may work with some tools but not others).

**Comment by taradiddles** [comment] 2016-08-29 06:36
(copy/paste from a reply in the dev ML)

the following workaround has been working well for me for many years, in stock fedora and now in Qubes: in a terminal in dom0, type the following (obviously replace the bg(phonetic) version with whatever layout you're using)

setxkbmap -layout "us,bg(phonetic)" -option "grp:shifts_toggle"

then you'll be able to press both shift keys to switch the layout in specific VMs.

you can automate this by putting this line in a script called by the window manager during startup.

caveats:
- no layout notification; not a problem for me, if you don't remember which layout you've enabled, in the worst case you'll type a letter, see that you're in the wrong layout, press both shift keys, and continue. It takes 1 second.
- my biggest gripe: when the screensaver kicks in (xscreensaver here), there's no way to know in which layout you're typing your password. Typing your English password with - say - Cyrillic letters will obviously fail, so you'll have to press both shift keys and try again.

**Comment by modulistic** [comment] 2017-04-04 22:50
After some frustration with a fresh qubes R3.2 install with stock XFCE, I found the "right" way to set the (xorg) system-wide keyboard layout (and options); This feels like a work-around for me, but anyway:

In `Q` → `System Tools` → `Keyboard` → `Layout`, leave the checkbox `Use system defaults` checked. Do not customize the keyboard layout here.

Set the system-wide layout and options for `xorg` with the `localectl` command in `dom0`. You can use `localectl --help` as a starting point.

Example: `localectl set-x11-keymap us dell ,qwerty compose:caps`.

This generates the appropriate configuration in `/etc/X11/xorg.conf.d/00-keyboard.conf`.

Restarting `xorg` is required. The easy way is to reboot the system.

I just opened [a PR](https://github.com/QubesOS/qubes-doc/pull/340) that adds this explanation to the FAQ.

BTW, I've been unable to figure how the current layout is propagated from dom0's xorg to the other VMs, along with others such as the display geometry. It would be nice to have this explained somewhere in the documentation, even if it is in the developer documentation.

**Comment by andrewdavidwong** [comment] 2019-04-01 04:11
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by hexagonrecursion** [comment] 2019-10-29 10:02
I can confirm that this issue affects Qubes 4.0.
To reproduce:
1. Configure multiple keyboard layouts in dom0 keyboard settings
2. Try switching between them
Expected:
Keyboard layout changes affect all qubes
Actual:
Only dom0 keyboard layout is set

**Comment by marmarek** [comment] 2019-10-29 10:27
The currently implemented behavior is to propagate keyboard layout only at qube start. Right now, there is no propagation while qubes are running. But indeed that would be a useful thing.

**Comment by GWeck** [comment] 2020-02-07 12:45
In the latest version of R4.1 (20200113 fully patched), dom0 keyboard layout (in my case German) does no longer propagate to fedora-30 VMs (template and AppVMs) - they use the US keyboard. It is also now impossible to set their keyboard layout; neither `gnome-control-center` nor the command `localectl` have any effect. `localectl status` shows the German locale and keyboard, but still the US layout is used.

dom0, debian and Whonix use the German keyboard as expected, only Fedora is affected.

**Comment by tlaurion** [comment] 2020-10-07 19:51
@marmarta @marmarek : https://www.qubes-os.org/faq/#my-keyboard-layout-settings-are-not-behaving-correctly-what-should-i-do refers here, while packages seems to be updates for 4.1. What is the current situation? Is the FAQ up to date?

(Canadian here, so need to have US keyboard by default but have @ in canadian-fr keyboad in some VMs, still not attainable. Better issue? Ope a new one? Please tag me here or elsewhere. So I can test/reproduce/create new issue)

**Comment by tlaurion** [comment] 2020-10-07 20:05
@andrewdavidwong @marmarek @marmarta :
followed [guidance](https://groups.google.com/g/qubes-devel/c/d8ZQ_62asKI/m/uqSR3FfQAQAJ) 
`setxkbmap -layout "us,ca" -option "grp:shifts_toggle" `

Without success either.

What are supposed to be the working instructions relative to current pushed changes?

**Comment by fepitre** [comment] 2020-10-07 20:10
@tlaurion Try to set the keyboard layout in XFCE settings by unselecting `Use system defaults`. It should propagate to AppVM.

**Comment by marmarek** [comment] 2020-10-07 20:15
In R4.0 the keyboard layout is loaded by an AppVM only at its start time. This means, if you want to switch keyboard layout when the VM is running, you either need to restart it, or change it manually in both dom0 and the VM.

**Comment by tlaurion** [comment] 2020-10-07 20:24
> @andrewdavidwong @marmarek @marmarta :
> followed [guidance](https://groups.google.com/g/qubes-devel/c/d8ZQ_62asKI/m/uqSR3FfQAQAJ)
> `setxkbmap -layout "us,ca" -option "grp:shifts_toggle" `
> 
> Without success either.
> 
> What are supposed to be the working instructions relative to current pushed changes?
This works after restarting personal.
But again, alt-2 (for @) is not available.
But, switching between US and CA works by hitting both shift keys. So we have mitigation since having '@' can be obtained by switching to US keybaord and shift+2.

Will do other recommendations and activate multiple keyboard on dom0 prior of launching AppVMs and report back.

**Comment by tlaurion** [comment] 2020-10-07 20:41
@fepitre set in dom0:
![xfce](https://user-images.githubusercontent.com/827570/95385139-92d0dc00-08bb-11eb-8d51-f04ac8e0c942.png)

The removing past customization under QubesOS Manager:
![None](https://user-images.githubusercontent.com/827570/95385335-d75c7780-08bb-11eb-9f4a-d3b2cd2529d0.png)

Result:
- Pressing both shift keys alternates between US and Canadian-FR keyboards, mitigating the fact that there is no recognition of alt-2 key to type '@' key.

**Comment by andrewdavidwong** [comment] 2020-10-08 06:48
> https://www.qubes-os.org/faq/#my-keyboard-layout-settings-are-not-behaving-correctly-what-should-i-do refers here, while packages seems to be updates for 4.1. What is the current situation? Is the FAQ up to date?

You can see in the [blame view](https://github.com/QubesOS/qubes-doc/blame/master/introduction/faq.md) that the most recent update to that FAQ entry was 8 months ago, so it's certainly not describing 4.1. Historically, our documentation has always described the latest stable release, so it wouldn't describe 4.1 until 4.1 is actually a stable release. (However, I'm working on versions-specific docs.)

It's unclear to me whether this issue needs to be reopened.

**Comment by tlaurion** [comment] 2020-10-08 14:19
@andrewdavidwong : The documentation needs to be updated. My tests https://github.com/QubesOS/qubes-issues/issues/1396#issuecomment-705182253 show 4.0 testing, where if followed, permits mitigation of keyboard issues of multi-language support.

From my quick verification of 4.1, the difference there is that it doesn't require shuttoing down active VM since propagation is live, not only done at startup of the AppVM.

**Comment by arkenoi** [comment] 2021-05-08 08:14
One more weird issue, not sure if it belongs here or if I should open a separate entry on github.

After a while, arrow keys and pgup/pgdn in VMs stop working. VM restart helps, but then the issue re-appear. Xev shows that keycodes are correct but mapping is all off. I checked the setting thoroughly and found out that xkbmap keycodes are slipped to "xfree86+aliases(qwerty) instead of normal "evdev+aliases(qwerty)". resetting it with setxkbmap -keycodes "evdev+aliases(qwerty)" restores normal behavior.

**Comment by arkenoi** [comment] 2021-05-08 13:44
apparently every layout switch forces it back from "evdev" to "xfree86"!

**Comment by palainp** [comment] 2021-07-21 13:49
Not sure if this comment is relevant here, if it's a different issue or if I just have a buggy configuration.

I am with the same settings as in https://github.com/QubesOS/qubes-issues/issues/1396#issuecomment-705182253 but with only one layout (French alternative), when I start a vm, I can run :
```
$ setxkbmap -v -print
Trying to build keymap using the following components:
keycodes: evdev + aliases (qwerty)
types: complete
compat: complete
symbols: pc + us + inet (evdev)
geometry: pc (pc105)
xkb_keymap {
xkb_keycodes {include "evdev + aliases (qwerty)"};
xkb_types {include "complete"};
xkb_compat {include "complete"};
xkb_symbols {include "pc + us + inet (evdev)"};
xkb_geometry {include "pc (pc105)"};
};
```
but as I can type in french (azerty) I may have a missconfiguration or something ?

The interesting part is when I attach a Sennheiser SP 20 USB to the VM, the layout changes to us (qwerty, in accordance with what setxkbmap says). This appears no matter if the VM is templated or standalone. The kernel logs shows :
```
[ 9021.779635] vhci_hcd vhci_hcd.0: USB/IP Virtual Host Controller
[ 9021.779690] vhci_hcd vhci_hcd.0: new USB bus registered, assigned bus number 2
[ 9021.780062] vhci_hcd: created sysfs vhci_hcd.0
[ 9021.780103] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[ 9021.780127] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 9021.780150] usb usb2: Product: USB/IP Virtual Host Controller
[ 9021.780168] usb usb2: Manufacturer: Linux 5.4.125-1.fc25.qubes.x86_64 vhci_hcd
[ 9021.780189] usb usb2: SerialNumber: vhci_hcd.0
[ 9021.780269] hub 2-0:1.0: USB hub found
[ 9021.780286] hub 2-0:1.0: 8 ports detected
[ 9021.780522] vhci_hcd vhci_hcd.0: USB/IP Virtual Host Controller
[ 9021.780566] vhci_hcd vhci_hcd.0: new USB bus registered, assigned bus number 3
[ 9021.780597] usb usb3: We don't know the algorithms for LPM for this host, disabling LPM.
[ 9021.780633] usb usb3: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.04
[ 9021.780655] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[ 9021.780677] usb usb3: Product: USB/IP Virtual Host Controller
[ 9021.780696] usb usb3: Manufacturer: Linux 5.4.125-1.fc25.qubes.x86_64 vhci_hcd
[ 9021.780726] usb usb3: SerialNumber: vhci_hcd.0
[ 9021.781080] hub 3-0:1.0: USB hub found
[ 9021.781097] hub 3-0:1.0: 8 ports detected
[ 9021.940684] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(0)
[ 9021.940708] vhci_hcd vhci_hcd.0: devid(131076) speed(2) speed_str(full-speed)
[ 9021.940733] vhci_hcd vhci_hcd.0: Device attached
[ 9022.110974] vhci_hcd: vhci_device speed not set
[ 9022.162824] usb 2-1: new full-speed USB device number 2 using vhci_hcd
[ 9022.225904] vhci_hcd: vhci_device speed not set
[ 9022.277892] usb 2-1: SetAddress Request (2) to port 0
[ 9022.299082] usb 2-1: New USB device found, idVendor=1395, idProduct=0041, bcdDevice=95.90
[ 9022.299107] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9022.299129] usb 2-1: Product: Sennheiser SP 20 for Lync
[ 9022.299153] usb 2-1: SerialNumber: A0004...
[ 9022.312083] input: Sennheiser SP 20 for Lync as /devices/platform/vhci_hcd.0/usb2/2-1/2-1:1.3/0003:1395:0041.0002/input/input7
[ 9022.312328] input: Sennheiser SP 20 for Lync as /devices/platform/vhci_hcd.0/usb2/2-1/2-1:1.3/0003:1395:0041.0002/input/input8
[ 9022.364007] input: Sennheiser SP 20 for Lync Consumer Control as /devices/platform/vhci_hcd.0/usb2/2-1/2-1:1.3/0003:1395:0041.0002/input/input9
[ 9022.364949] hid-generic 0003:1395:0041.0002: input,hiddev96,hidraw1: USB HID v1.11 Device [Sennheiser SP 20 for Lync] on usb-vhci_hcd.0-1/input3
[ 9022.412981] mc: Linux media interface: v0.10
[ 9022.541172] usbcore: registered new interface driver snd-usb-audio
[ 9022.557379] audit: type=1130 audit(1626873890.761:136): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=alsa-state comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 9023.647246] vhci_hcd: unlink->seqnum 75
[ 9023.647262] vhci_hcd: urb->status -104
[ 9023.647274] vhci_hcd: unlink->seqnum 76
[ 9023.647285] vhci_hcd: urb->status -104
[ 9023.647299] vhci_hcd: unlink->seqnum 77
...
```

**Comment by anadahz** [comment] 2021-07-21 15:15
> apparently every layout switch forces it back from "evdev" to "xfree86"!

I have the same issue as in https://github.com/QubesOS/qubes-issues/issues/1396#issuecomment-835199512 .
This wasn't the case a week ago.

Not sure if it's related, I have a custom keymap set by a setxkbmap command on `/etc/profile.d`.

**Comment by tlaurion** [comment] 2021-07-21 15:53
I confirm that on my side following https://github.com/QubesOS/qubes-issues/issues/1396#issuecomment-705182253 and not having changed anything else it works as intended on 4.0, but needs reboot as opposed to 4.1.

dual shift and then shift 2: @
dual shift and then shift 2: "

No layout configured under Qubes Manager for currently used AppVM.

**Comment by marmarek** [comment] 2021-11-30 21:49
This should be already fixed by https://github.com/QubesOS/qubes-core-admin-client/pull/193, that is included in https://github.com/QubesOS/updates-status/issues/2721 (already in stable). If anybody still see this issue even with that update installed, please leave a comment.

**Comment by loztcf** [comment] 2021-12-08 15:42
I set keyboard layout in dom0 with "localectl set-x11-keymap us,de 104,105 altgt-intl,nodeadkeys grp:l_alt_lshift_toggle"
If I use XFCE the keyboard layout propagates fine to any vm (and dom0) if I switch it via l_alt_shift_toggle. The keyboard layout is set correctly then without problems, I'm able to query and verify it via qvm-prefs.
If using i3wm the keyboard layout only switches in dom0 and doesn't propagate to any vm if - I query any via qvm-prefs the default one is still set.

**Comment by marmarek** [comment] 2021-12-09 21:33
When using i3wm, is `qvm-start-daemon --all --watch` process running?

**Comment by loztcf** [comment] 2021-12-09 22:40
Yes, it is.

**Comment by bashlund** [comment] 2022-04-11 11:20
> One more weird issue, not sure if it belongs here or if I should open a separate entry on github.
> 
> After a while, arrow keys and pgup/pgdn in VMs stop working. VM restart helps, but then the issue re-appear. Xev shows that keycodes are correct but mapping is all off. I checked the setting thoroughly and found out that xkbmap keycodes are slipped to "xfree86+aliases(qwerty) instead of normal "evdev+aliases(qwerty)". resetting it with setxkbmap -keycodes "evdev+aliases(qwerty)" restores normal behavior.

Thanks @arkenoi, your tip of resetting using `setxkbmap -keycodes "evdev+aliases(qwerty)` really saved my setup!

Whenever the arrow keys stop working I run that snippet and it all works again as expected.

**Comment by holiman** [comment] 2022-08-15 19:07
I am also having this problem, it appeared pretty recently (after upgrade to 4.1). Am on 4.1. `5.8.9-1` kernel. Use En and SE layouts, and double-shift to switch, but it does not propagate from dom0. 
Also on `i3`, and `qvm-start-daemon --all --watch` is running.

**Comment by bashlund** [comment] 2022-08-15 20:13
I noticed you poppin by @holiman, so I though it's time to share a snippet which works good as a workaround on this issue :)
The ideas to the snippet come from this thread.
It solves the problems by the user hitting a keyboard shortcut and the script then sets the keyboard layout in all VMs.

Whenever my layout totally breaks I just hit the shortcut two times to get back to the layout I was using, so it solves the issue of layout which stop working and also propagating layouts from dom0.

See the script header for details on how to set it up. The script must be copied to dom0, but no install are necessary. 

https://gist.github.com/bashlund/90f097d5ffea3c5a8c7ffd13867b5cb3

**Comment by marmarek** [comment] 2022-08-15 22:43
The layout switching involves several parts:
1. `qvm-start-daemon` monitors `_XKB_RULES_NAMES` and `XKLAVIER_ALLOW_SECONDARY` properties on the root window ( you can check with `xev -root -event property` if they change)
2. Then, it adjusts `keyboard_layout` property on dom0 (check with `qvm-prefs dom0 keyboard_layout`) 
3. Then, it's transferred using qubesdb to relevant VMs, where `qubes-keymap.sh` script should monitor it and apply the change (check process list in the VM to see if it runs)

**Comment by holiman** [comment] 2022-08-16 06:33
Interesting!

As far as I can tell, it's `1)` which is failing. If I switch layout, then indeed it works in dom0, but the `qvm-prefs dom0 keyboard_layout` does not change. The `xev -root -event property` only reacts when the cursor moves from one application screen to another. 

At this point, I exited `i3`, and started an `xfce` session instead. In `xcfe`, the `xev -root -event property` _did_ emit `XKLAVIER_ALLOW_SECONDARY` events, which updated the `qvm-prefs`, and the whole chain worked.

**Comment by jamke** [comment] 2023-05-07 07:55
> The layout switching involves several parts:
> 
>     1. `qvm-start-daemon` monitors `_XKB_RULES_NAMES` and `XKLAVIER_ALLOW_SECONDARY` properties on the root window ( you can check with `xev -root -event property` if they change)
> 
>     2. Then, it adjusts `keyboard_layout` property on dom0 (check with `qvm-prefs dom0 keyboard_layout`)
> 
>     3. Then, it's transferred using qubesdb to relevant VMs, where `qubes-keymap.sh` script should monitor it and apply the change (check process list in the VM to see if it runs)

@marmarek 
Thank you for this valuable piece of information!
Is it documentation somewhere? I want to investigate and fix #8035, but could not find documentation how layout switching works in R4.1. I mean your reply explains a lot, but maybe it is explained somewhere else too?

And why `XKLAVIER_ALLOW_SECONDARY` exactly? I tried to search for it and it seems that Qubes OS is almost the only somewhat popular project that relies on `XKLAVIER_ALLOW_SECONDARY` (I can easily be wrong about this).

**Comment by gangamstyle** [comment] 2023-10-06 19:12
Debugging:
1) qubesdb-watch /keyboard-layout in guests returns nothing, and this prevents layout update in guests
2) qvm-prefs dom0 keyboard_loyout in dom0 returns nothing

Script that tracks layout changes in dom0 and updates keyboard_layout for qvm-prefs:
/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_start_daemon.py
It listens to X events using xcffib library https://github.com/tych0/xcffib and that library may be bugged.

**Comment by gangamstyle** [comment] 2023-10-06 19:38
@marmarek can you please check if this pull request https://github.com/QubesOS/qubes-core-admin-client/commit/b99e45f081ab7c5ef51ed6be665dca3dae84ed02 can be affected by suspend/resume (this starts the bug)

**Comment by jamke** [comment] 2024-03-08 05:29
> I'm troubleshooting an issue whereby dom0 keyboard layout and setxkbmap options are being ignored by a Windows 7 Qube.

I have Windows 10 for a while that does not care about keyboard layout of other qubes, including `dom0`. Is the propagation expected to work with Windows qubes at all?

**Comment by sysfu** [comment] 2024-03-09 18:09
> > I'm troubleshooting an issue whereby dom0 keyboard layout and setxkbmap options are being ignored by a Windows 7 Qube.
> 
> I have Windows 10 for a while that does not care about keyboard layout of other qubes, including `dom0`. Is the propagation expected to work with Windows qubes at all?

I did some more research and believe this is due to missing Qubes Windows Tools. They were [replaced with a dummy file](https://forum.qubes-os.org/t/qwt-support-for-windows-in-qubes-os-is-not-available-anymore-when-will-this-be-solved/20523) around August 2023 on account of a Xen driver CVE.

You can [manually downgrade](https://www.qubes-os.org/doc/templates/windows/qubes-windows-tools-4-1/) to qubes-windows-tools-4.1.69 (for Qubes OS v4.2) but the updater will replace it with the dummy file again if you're not careful.

**Comment by jamke** [comment] 2024-03-10 03:32
Without QWT it will not propagate for user. I have QWT and it never propagated on Win10 for me, so, I am not sure it should.

**Comment by marmarek** [comment] 2024-03-10 12:05
I don't think keyboard layout switching is implemented in QWT yet.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Closed** 2024-12-07 14:32 UTC
Labels: T: bug, help wanted, C: core, C: gui-virtualization, C: doc, P: minor, localization, ux, r4.1-buster-stable, r4.1-stretch-stable, r4.1-fc29-stable, r4.1-fc30-stable, r4.1-bullseye-stable, r4.1-fc31-stable, r4.1-dom0-stable, r4.1-centos8-stable, r4.1-fc32-stable, affects-4.1, eol-4.1

**Comment by tlaurion** [comment] 2024-12-08 05:00
@andrewdavidwong is this fixed in 4.2?

**Comment by alimirjamali** [comment] 2024-12-08 15:18
> @andrewdavidwong is this fixed in 4.2?

It is currently broken on my r4.3 system (X11, dom0 as GUIVM, Dedicated audiovm) on Fedora 41 XFCE guests. There has been a noticeable delay which made the `qvm-start-daemon` layout change detection and propagation mechanism almost useless.

This issue is already very long and confusing. I believe it would be better to pin-point other other bugs and file new issues.

Some related issues: #9517,  #8109

**Comment by tlaurion** [comment] 2024-12-09 00:15
Someone having an understanding of the current issue could start a new issue then @andrewdavidwong @alimirjamali ?

I just gave up with ca-fr keyboard, never was able to make it work. I guess nobody can make it work either.

**Comment by holiman** [comment] 2024-12-09 06:44
This is still an issue for me, Qubes `R4.2.3`, Kernel `6.6.63-1, with `i3wm` window manager. 

The investigation I posted [here](https://github.com/QubesOS/qubes-issues/issues/1396#issuecomment-1216204635) is, afaik, still correct. 

----------------

Using two workarounds like this instead:

```
$ cat ~/bin/english 
setxkbmap -keycodes "evdev+aliases(qwerty)" -layout "us" -model pc105
```
