### ISSUE TITLE
fail to assign pci device at start of usbvm

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1544] opened 2015-12-26 12:33 UTC
I'm experiencing a weird error starting a usbvm:

```
[user@dom0 ~]$ qvm-start usbvm
--> Creating volatile image: /var/lib/qubes/appvms/usbvm/volatile.img...
--> Loading the VM (type = AppVM)...
Traceback (most recent call last):
  File "/usr/bin/qvm-start", line 125, in <module>
    main()
  File "/usr/bin/qvm-start", line 109, in main
    xid = vm.start(verbose=options.verbose,
preparing_dvm=options.preparing_dvm, start_guid=not options.noguid,
notify_function=tray_notify_generic if options.tray else None)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py",
line 1849, in start
    nd.dettach()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 5249, in
dettach
    if ret == -1: raise libvirtError ('virNodeDeviceDettach() failed')
libvirt.libvirtError: Requested operation is not valid: PCI device
0000:00:1a.0 is in use by driver xenlight, domain usbvm
```

Restarting libvirtd only aggravates the issue:

```
[user@dom0 ~]$ qvm-start usbvm
--> Creating volatile image: /var/lib/qubes/appvms/usbvm/volatile.img...
--> Loading the VM (type = AppVM)...
Traceback (most recent call last):
  File "/usr/bin/qvm-start", line 125, in <module>
    main()
  File "/usr/bin/qvm-start", line 109, in main
    xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1857, in start
    self.libvirt_domain.createWithFlags(libvirt.VIR_DOMAIN_START_PAUSED)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1059, in createWithFlags
    if ret == -1: raise libvirtError ('virDomainCreateWithFlags() failed', dom=self)
libvirt.libvirtError: internal error: libxenlight failed to create new domain 'usbvm'
```

Weird errors in libxl log:

```
2015-12-26 x:31:47 TZ libxl: error: libxl_pci.c:1000:do_pci_add: xc_assign_device failed: Operation not permitted
2015-12-26 x:31:47 TZ libxl: error: libxl_create.c:1422:domcreate_attach_pci: libxl_device_pci_add failed: -3
```

The hypervisor log says:

```
(XEN) [VT-D] It's disallowed to assign 0000:00:1a.0 with shared RMRR at dbe9a000 for Dom19.
(XEN) XEN_DOMCTL_assign_device: assign 0000:00:1a.0 to dom19 failed (-1)
```

**Comment by Rudd-O** [comment] 2015-12-26 12:37
What's that about the RMRR?

**Comment by Rudd-O** [comment] 2015-12-26 12:39
Appears to be some new shit:

http://www.gossamer-threads.com/lists/xen/devel/391684

**Comment by marmarek** [comment] 2015-12-26 12:59
> The VM has never been started.

Not even using autostart at boot?

> What's that about the RMRR?
> Appears to be some new shit:
> http://www.gossamer-threads.com/lists/xen/devel/391684

We have a way to set rdm_policy=relaxed, bundled with `pci_strictreset=false` - it should be set by default salt formula for `sys-usb`, exactly for this reason. 
My understanding is that those devices in fact shares some resources, so can't be safely isolated from each other. And Xen doesn't support group assignment (at least for now), so don't know that you are going to assign all such devices to the same VM (which should be safe).

**Comment by Rudd-O** [comment] 2015-12-26 13:06
Yes, the VM had autostart at boot and the systemd service had failed for this reason.

How do I determine which devices share the RMRR?   I couldn't find anything in my logs.

**Comment by Rudd-O** [comment] 2015-12-26 13:09
Holy shit, setting `pci_strictreset` to `False` actually let me start that stupid VM!

**Comment by marmarek** [comment] 2015-12-26 13:10
I don't know, but guess it is the other USB controller (or USB2.0/USB3.0). If you assign both/all of them to the same VM, you'll see the same address in xen log (assuming you set `pci_strictreset=False` first, otherwise VM start will fail at the first device...). Yes, kinda ugly way to determine that...

**Comment by Rudd-O** [comment] 2015-12-26 13:10
Wait, spoke too soon.  The VM never ran qrexec-daemon.

**Comment by Rudd-O** [comment] 2015-12-26 13:11
It now says in the hypervisor log "It's risky to assign blah blah".

**Comment by Rudd-O** [comment] 2015-12-26 13:12
libxl log:

```
<date> libxl: error: libxl_device.c:1215:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/24/0 not ready
```

**Comment by marmarek** [comment] 2015-12-26 13:15
Did it crashed just after startup (state "c" on `xl list`)? If so, probably not enough continuous memory available (take a look #1038 for details) . You can try to free some with `xl mem-set 0 <some-number-in-MB>` to reduce dom0 memory drastically. For example down to 1500. Sometimes it helps. Otherwise, reboot...

**Comment by Rudd-O** [comment] 2015-12-26 13:16
Yes.  It's state crashed.  I just checked.

Assigning all USB devices to the same VM worked to fix the problem.

This sucks.  Now I don't have my mouse.

**Comment by Rudd-O** [comment] 2015-12-26 13:17
Note that assigning all USB PCI devices did NOT help start the VM.   Even with pci_strictreset set to false.  It just killed my mouse.

**Comment by Rudd-O** [comment] 2015-12-26 13:18
I will try rebooting now.  BRB.

**Comment by marmarek** [comment] 2015-12-26 13:18
The VM crash at startup is generally a problem with starting VM with PCI devices after some system uptime, memory is much fragmented then. It is independent of previous problem (which is solved with pci_strictreset).

**Comment by Rudd-O** [comment] 2015-12-26 13:30
Alright, excellent.  My USB VM has now received the assignment of the two USB PCI devices I intended to isolate (the Bluetooth and camera devices).  I still keep the ability to use my mouse.  This is GREAT.

Thanks for the `pci_strictreset` trick.

Improvement: it really should be somehow autodetected whether it is necessary or not.

**Comment by marmarek** [comment] 2015-12-26 13:34
It is set for USB VM by salt formula by default.

**Comment by Rudd-O** [comment] 2015-12-26 13:35
Yes, that's true, but it would not be the default for a manually created USB VM, which was my case, and I bet the case in many cases.  A smart default lower in the stack would reduce the support load.

**Comment by marmarek** [comment] 2015-12-26 13:35
The proper solution would be to have PCI group assignment supported by Xen. This way it would detect whether it is really risky to assign particular devices to the VM.

**Comment by Rudd-O** [comment] 2015-12-26 13:36
Agreed.

**Comment by marmarek** [comment] 2016-01-06 23:09
Summary:
 - Xen missing feature of PCI group device assignment
 - libvirt bug in tracking which PCI device is used where (`libvirt.libvirtError: Requested operation is not valid: PCI device 0000:00:1a.0 is in use by driver xenlight, domain usbvm` while starting `usbvm`)

**Comment by Rudd-O** [comment] 2016-01-16 20:44
Quick update: I assigned two of my USB PCI devices (out of three) to a USB VM.  That caused hangs and reboots to happen around once each day.  They stopped happening as soon as I decided never to power on that VM again.  I still have yet to try adding all three USB PCI devices to the USB VM (doing so would disable all USB ports on this machine)  We'll see if that causes hangs.

**Comment by andrewclausen** [comment] 2016-03-14 22:08
The `pci_strictreset` option didn't have any effect for me.  (Exactly the same error messages, etc.)

**Comment by Rudd-O** [comment] 2016-03-15 05:09
I found my problem.  It was a mouse whose receiver stopped working properly, and started causing lockups and hard reboots whenever it was plugged, irrespective of which VMs it was assigned to.  The mouse is now in the trash.

**Comment by marmarek** [comment] 2016-03-15 12:38
There is a strange issue related to some Logitech receivers: #1689 . I can confirm it indeed happens, but no idea why. I'd rather blame some kernel driver, not the device itself.

**Comment by nothingmuch** [comment] 2016-10-23 01:05
I am getting this error too, with pci_strictreset on a clean install of R3.2 on a Lenovo Yoga 12 which previously had R3.1 working with a usbvm. Disabling USB3 in the bios seemed to work, upgrading the BIOS as mentioned in this thread https://groups.google.com/forum/#!msg/qubes-users/Z6bEMZTjiz4/FbV6T-l_AQAJ did not seem to make a difference.

**Comment by Rudd-O** [comment] 2016-10-23 19:59
The Logitech device issue is no longer a problem in modern kernels.

**Comment by nothingmuch** [comment] 2016-10-24 06:35
I'm seeing this with no external USB devices connected.

**Comment by Rudd-O** [comment] 2016-10-27 06:08
Since today, I cannot boot the VMs that have USB devices connected to them.  The VM doesn't even show an XL console.

**Comment by Rudd-O** [comment] 2016-10-27 06:08
I have pci_strictreset set to false.

**Comment by marmarek** [comment] 2016-10-27 15:49
Is that after upgrading Xen to 4.6.3?
What is exact error? If you start it from command line, does it show up
in `xl list` (when qvm-start is still running)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Rudd-O** [comment] 2016-10-28 20:27
No xl list entry, cannot even open the xen console to it — it just hangs for a little while and then exits.

This single line appears in the xl dmesg:

```
(XEN) [VT-D] It's risky to assign <PCI device ID> with shared RMRR at <address> for DomNNN
```

Note that this worked fine before.

**Comment by Rudd-O** [comment] 2016-10-28 20:28
Correction, the entry appears briefly:

```
usbvm            437   200   1   ---sc-     0.0
```

**Comment by Rudd-O** [comment] 2016-10-28 20:28
qrexec log for that VM says

```
domain dead
cannot connect to qrexec agent: No such process
```

**Comment by Rudd-O** [comment] 2016-10-28 20:29
libxl-driver.log says:

```
<time and date> libxl: error: libxl_device.c:1215:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/<domid>0 not ready
```

**Comment by Rudd-O** [comment] 2016-10-28 20:30
Xen on the dom0 is 4.6.1-20.fc23

**Comment by marmarek** [comment] 2016-10-28 20:38
Probably well known memory fragmentation issue - PV VM with PCI device needs few megs of _physically_ continuous memory for DMA purpose. You can free some by getting it away from dom0: `xl mem-set 0 <some-memory-size-in-MB>`, where the size is smaller than the current one (for example 500MB smaller). If it does not help, try shutdown some VMs. If still nothing, reboot...

**Comment by Rudd-O** [comment] 2016-10-28 20:54
Let me try.  But if this works, this really should be documented somewhere!

**Comment by Rudd-O** [comment] 2016-10-28 20:55
Nope, it did not work at all.

**Comment by marmarek** [comment] 2016-10-28 22:40
Ok, lets try harder: `touch /var/run/qubes/do-not-membalance`. Then try again `xl mem-set` and `qvm-start`. And if it doesn't work, repeat (just one more time).

**Comment by Rudd-O** [comment] 2016-10-30 19:06
On 10/28/2016 10:40 PM, Marek Marczykowski-Górecki wrote:
>
> Ok, lets try harder: |touch /var/run/qubes/do-not-membalance|. Then
> try again |xl mem-set| and |qvm-start|. And if it doesn't work, repeat
> (just one more time).
>

A reboot fixed it.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by xloem** [comment] 2017-01-01 08:04
Same experience.  I needed to to `touch /var/run/qubes/do-not-membalance` to get `xl mem-set` to do anything at all.  I kept dropping the dom0 ram in 512MB increments, and `qvm-start` kept failing, until the system stopped responding.  Then things worked after reboot.

Maybe some file to review to determine memory fragmentation, and where the VM memory is getting allocated, for next time?  Or some way to determine what made the VM crash?

**Comment by andrewdavidwong** [comment] 2021-05-08 07:59
This bug report has seen no activity in a very long time, and it is not assigned to any current release milestone. It looks like it was left open by mistake, so I'm closing it now. However, if anyone is still affected by this bug on a currently-supported release, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by brendanhoar** [comment] 2022-05-15 01:29
R4.0 kernel-latest=5.17.7 current-testing:

Just ran into the "failed to get contiguous memory for dma from xen" in sys-net-dm after shutting down all networking VMs and trying to start them again.

Several retries failed.

I saved all my work, shut down everything but dom0 and sys-net started w/o issue.

Pretty sure this happened one other time recently as well, can't prove it though. 

Next time it happens I'll try the xl mem-set 0 <smaller size> approach.

B

**Comment by xloem** [comment] 2022-05-15 01:40
I'm no longer using Qubes, but it looks like a workable next step here would be to take the effort to find what device file (and possibly kernel parameters) display the physical memory mapping of the system. Then this can be reviewed on next occurrence to verify that the instance is memory fragmentation, see if shrinking dom0 resolves it, and possibly discern a minimum contiguous block needed by the device.

It's likely possible to remap memory to resolve this confidently, but might need implementation by a dev.

**Comment by andrewdavidwong** [comment] 2023-04-07 22:06
Just a reminder that, for bug reports, the [milestone](https://www.qubes-os.org/doc/issue-tracking/#milestones) designates the earliest supported release in which the bug is known to exist, not when we plan to fix it.

**Comment by andrewdavidwong** [comment] 2023-04-19 14:20
> This is from 2015 and I have not been able to repro this since.

Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2023-04-19 14:20 UTC
Labels: T: bug, C: Xen, P: default, S: blocked, diagnosed
