### ISSUE TITLE
Kernel Taint Crash

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#8425] opened 2023-08-15 15:16 UTC
R4.1.2

Xen crash which leads to a tainted kernel

There is a guide here: [Tainted kernels — The Linux Kernel documentation](https://www.kernel.org/doc/html/latest/admin-guide/tainted-kernels.html)

which allows you to determine the reason for the taint using “cat /proc/sys/kernel/tainted”

which returns the value “64” (taint requested by userspace application); however there is no further

log information, like the user application which caused the taint.

**Comment by andrewdavidwong** [comment] 2023-08-15 15:56
Duplicate of #8423

**Comment by andrewdavidwong** [comment] 2023-08-15 15:57
This is a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. Please comment on the appropriate existing issue instead.

**Closed by andrewdavidwong** 2023-08-15 15:57 UTC
Labels: T: bug, P: default
