### ISSUE TITLE
warn the user if qubes-firewall settings are ignored

### ISSUE THREAD

**Issue by john-david-r-smith** [QubesOS/qubes-issues#2003] opened 2016-05-18 22:34 UTC
#### Qubes OS version

R3.1

---
### Setting:

VM A has some qubes-firewall settings.
A's netvm does not support qubes-firewall settings.
### Expected behavior:

Display a warning to the user when the netvm is set / fw options are added.
Maybe disconnect the netvm until the fw-rules are deleted / a netvm supporting qubes-fw settings is set. 
### Actual behavior:

The settings are dropped silently.

---
#### Related:

https://groups.google.com/forum/#!topic/qubes-users/FCJVUF07E2s

**Comment by marmarek** [comment] 2016-05-18 22:45
There is such message already:
![screenshot-firewall-netvm](https://cloud.githubusercontent.com/assets/726704/15377279/dc129fe4-1d5a-11e6-9e71-25bda32bf80e.png)
But it is visible only when switching to firewall tab, not when opening it directly from the toolbar...

**Comment by andrewdavidwong** [comment] 2016-05-19 07:03
CCing @bnvk so that this can be taken into account in the Qubes Manager rework (#1870).

**Comment by john-david-r-smith** [comment] 2016-05-19 07:40
i don't get this message.
maybe i did once and it only appears once? (this would be a bug in my opinion)
maybe you are using some dev-build? 
my system is R3.1, up to date (just checked again.) and i can't remember changing anything that would have disabled such a message.

**what i did:**
1) create a new vm with some whonix-gw "tor" as netvm
=> network: my-new-vm -> tor -> sys-firewall -> sys-net
2) set fw rules to deny networking + forbid ICMP + DNS => **(no message)**
3) tested network:
> [user@my-new-vm ~]$ curl torproject.com

and got the html code.
4) connected my-new-vm to sys-firewall
=> network: my-new-vm -> sys-firewall -> sys-net
5) tested network again. 
> [user@my-new-vm ~]$ curl torproject.com
> curl: (6) Could not resolve host: torproject.com

6) set tor as netvm **(no message)**
=> network: my-new-vm -> tor -> sys-firewall -> sys-net

**what i would expect to happen:**
**action 2) :**  display the warning you posted
**action 6) :** display a warning and set none as netvm.
i would set none to protect against user errors:
a) the user may have clicked the warning away.
b) the user may wanted to fix this later and forgot.
if either the old or new netvm is used there could be leaks.
in case of:
 * _new netvm:_ the fw rules are ignored
 * _old netvm:_ the user probably had a reason to change the netvm (e.g. from sys-firewall to tor)
  now there may be leaks of the user's ip.

**Comment by andrewdavidwong** [comment] 2016-05-19 07:52
This is actually a duplicate of #1815, then. The real issue you're describing is that Whonix-Gateway does not currently support firewall rules. This is a known issue, which I brought up [here](https://groups.google.com/d/topic/qubes-users/PAnwbpdP-jI/discussion) and [here](https://forums.whonix.org/t/how-to-add-a-proxyvm-between-anon-whonix-and-sys-whonix-whonix-ws-email-sys-fw-whonix-whonix-gw-sys-firewall-sys-net/2238), which branched off [here](https://forums.whonix.org/t/sys-whonix-does-not-yet-function-was-qubes-firewallvm/2239) and is being tracked in #1815 and [here](https://phabricator.whonix.org/T476).

Short answer: For now, there's no way to enforce firewall rules for a VM using a `whonix-gw` as its NetVM, but a solution is in the works.

**Comment by john-david-r-smith** [comment] 2016-05-19 09:52
but this was not about whonix not being able to apply the rules or enforcing these rules.
it was about the system warning the user if something like this happens (not only in combination with a `whonix-gw`, but with any netvm silently ignoring the settings)

**Comment by andrewdavidwong** [comment] 2016-05-19 10:02
Are there any other situations besides Whonix in which firewall rules are not enforced? If not, then wouldn't fixing that also fix this? The end result would be the same: there is never a failure to warn the user that firewall rules have not been enforced (because they're always enforced).

In other words: Isn't the proper solution (and therefore the proper issue to be filed) to make sure that firewall rules are always enforced, rather than trying to come up with a system that warns the user whenever they're not (which should never happen)?

**Comment by john-david-r-smith** [comment] 2016-05-19 10:21
you are right. currently i don't know any other cases where this happens.
but wont there be the same questions if in future something like this happens again (maybe there is a new proxyvm with missing support)?
if you tell the user what is wrong instead of failing silently it causes less confusion.
i think it would be good to have a warning if the implementation does not take to much code.
(i think it should not be that hard to implement, if the code triggering the warning from marmarek's post does work in this case)

furthermore i think qubes, as an security oriented os, should warn the user if some leaks could occur because of some component not working as expected. (as long as it can detect this)

**Comment by andrewdavidwong** [comment] 2016-05-19 10:29
Ok, I'll reopen this.

**Comment by andrewdavidwong** [comment] 2016-09-21 10:08
[On 2016-09-20 10:16, mittendorf@[...] wrote:](https://groups.google.com/d/msgid/qubes-users/9e5aebdb-199d-b25c-daf7-d38dd5fdf2b0%40digitrace.de)
> Hey,
> 
> Firewall rules are set for a specific VM/Qube. From common understanding people would probably think that those rules are active no matter what happens outside of that very VM/Qube, but in fact it seems like those rules are active if and only if there is an ProxyVM connected to that VM/Qube.
> 
> Examples:
> 
> 1) I can configure firewall rules for a ProxyVM, but they are not actived, if that ProxyVM is connected to a NetVM (if I connect another ProxyVM in between, this might probably work?!)
> 
> 2) I can configure firewall rules for a AppVM, which will not be active if that VM is connected
> 
> And: What happens if a ProxyVM does not implement the firewall service, or if the firewall service crashes in the ProxyVM ?
> I cannot find more information about the firewall mechanism than "centrally managed in Dom0 and exposed to each Proxy VM through Xen store" from http://theinvisiblethings.blogspot.de/2011/09/playing-with-qubes-networking-for-fun.html
> 
> Ideas:
> a) A warning if an AppVM is (about to be) connected to a NetVM (instead of a ProxyVM).
> 
> b) Do not allow "firewall rules" being set for ProxyVMs (I think Proxy-Chains are rather unlikely being used?!)
> 
> c) A warning about DNS-Names in firewall rules
> 
> [c) A warning if a connected ProxyVM does not activate the firewall rules]
> 
> thank you,
> 
> Robert Mittendorf
>

**Comment by tasket** [comment] 2016-09-22 10:11
In current 3.2RC I do not get any warning when switching a proxyvm from another proxyvm to a netvm. The configured firewall rules simply cease to work.

There should be a warning, and the firewall settings tab deactivated.

**Comment by ubestemt** [comment] 2017-04-27 16:01
@andrewdavidwong If you (or someone else) point me to the relevant code for the warning message (when opening the Firewall tab with sys-net as NetVM) I'll see if I'm able to implement it for sys-whonix too.

**Comment by andrewdavidwong** [comment] 2017-04-27 21:10
> If you (or someone else) point me to the relevant code for the warning message (when opening the Firewall tab with sys-net as NetVM) I'll see if I'm able to implement it for sys-whonix too.

@marmarek?

**Comment by marmarek** [comment] 2017-04-27 21:52
It's here: https://github.com/QubesOS/qubes-manager/blob/master/qubesmanager/settings.py#L192-L201
The problem is that, currently there is no information whether given ProxyVM really support firewall enforcing. You can guess bases on its name (`sys-whonix`), but if one rename this VM, it would not work anymore. But maybe indeed providing some warning at least in default configuration is better than no warning at all.

**Closed** 2017-07-16 09:06 UTC
Labels: C: Qubes GUI tools, P: major, ux, r4.0-fc24-cur-test, r4.0-fc25-cur-test, r4.0-jessie-cur-test, r4.0-stretch-cur-test, r4.0-dom0-cur-test
