### ISSUE TITLE
Nautilus does not open in AppVM on first attempt

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#4337] opened 2018-09-25 01:46 UTC
### Qubes OS version:

4.0 (with current dom0 updates)

### Affected component(s): 

Unknown

---

### Steps to reproduce the behavior:

1. Start and use the AppVM (in my case, 'work' - I have Firefox open long-term)

2. Invoke 'Files' from 'work' in top-left Qubes menu.

3. Wait (nothing happens)

4. Repeat step 2 (Nautilus opens within 1 second)

Note: My 'work' AppVM has been switched to use fedora-28 as a template, has several other apps (such as LibreOffice) installed, and has been updated using 'sudo dnf update'.  Unknown if any of these are prerequisites for the problem.

If I close Nautilus and try to open it again the problem repeats - I have to try twice again.

### Expected behavior:

Nautilus opens within a few seconds of being invoked. (Noting that extra time may be required if the relevant AppVM is not yet running).

### Actual behavior:

Nautilus does not open at all on first attempt. (Its not just slow, nothing ever happens).

### General notes:

I am happy to try to track down error messages or do any further debugging to help get further information. (I'm new to Qubes and don't know where to look).

---

**Comment by esote** [comment] 2018-09-25 02:36
I also experience this with all of my VMs trying to run Nautilus. However, I don't know if this is a Qubes-specific issue, I remember having this issue with older Fedora versions. One thing to note, is that this kind of thing doesn't happen when just running the `nautilus` command.

**Comment by andrewdavidwong** [comment] 2018-09-25 03:14
Duplicate of #2449

**Comment by andrewdavidwong** [comment] 2018-09-25 03:14
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-09-25 03:14 UTC
