### ISSUE TITLE
Regression: 5.9.14-1 kernel does not make it to GUI on Intel NUC10i7

### ISSUE THREAD

**Issue by arkenoi** [QubesOS/qubes-issues#6311] opened 2020-12-26 13:33 UTC
**Qubes OS version**

4.0

**Affected component(s) or functionality**

kernel-latest-5.9.14-1.qubes.x86_64

**Brief summary**

Kernel level regression, probably video driver for Intel UHD

**How Reproducible**

Always

**To Reproduce**

1. Upgrade dom0 to kernel-latest-5.9.14-1.qubes.x86_64
2. reboot

**Expected behavior**

The system boots up normally and login screen appears.

**Actual behavior**

The system boots up normally, but lightdm's login screen does not come up. A "text" cursor is seen on the black screen.

**Additional context**

The Xorg log file has rotated so I do not have it at hand. However, if it is absolutely necessary I could try to obtain it again.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/gui-troubleshooting/
https://www.qubes-os.org/doc/newer-hardware-troubleshooting/
https://github.com/Qubes-Community/Contents/blob/master/docs/troubleshooting/intel-igfx-troubleshooting.md

**Comment by the-ch0sen-0ne** [comment] 2020-12-26 14:56
I can confirm that this has also happened to me. To get to the desktop, I switched to another console (Ctrl + Alt + F2) and then switched back (Ctrl + Alt + F1) which should get me the login screen. 

This did not fix the issue, though. Everything was corrupted, tearing everywhere. Disabling the compositor did not fix the issue. Seems like Intel's newest drivers breaks X11.

I was able to fix the problem by enabling TripleBuffer and TearFree.
```
[anakin@dom0 ~]$ cat /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"

  Option "AccelMethod" ''sna"
  Option "TripleBuffer" "true"
  Option "TearFree" "true"
EndSection
```

**Comment by arkenoi** [comment] 2020-12-26 18:01
Looks like it is a decade old bug that suddenly re-activated :)

**Comment by GonzaloThought** [comment] 2020-12-29 12:43
I had a similar problem on a Darter Pro after updating to 5.9.14-1. I tried to run the workaround @the-ch0sen-0ne mentioned but ran into an issue.  

```
cat /etc/X11/xorg.conf.d/20-intel.conf
cat: /etc/X11/xorg.conf.d/20-intel.conf: No such file or directory
```
Putting sudo in front didn't return the error but also didn't provide any place to add the remaining text.

I went another route to create the file.

```
cd /etc/X11/xorg.conf.d
sudo touch 20-intel.conf
sudo nano 20-intel.conf
```

Then I added the same text as mentioned earlier and it worked. Not sure why cat wouldn't work, but glad something did!

**Comment by strugee** [comment] 2021-01-26 00:10
@GonzaloThought `cat` didn't work because the file does not exist. @the-ch0sen-0ne was just demonstrating that they were showing the file's contents (`cat` just concatenates the contents of its arguments; run `man cat` for more). You also don't need `touch` - `nano` will create files that don't exist just fine.

**Comment by strugee** [comment] 2021-01-26 00:36
I can confirm that @the-ch0sen-0ne's workaround works for me on a System76 oryp4 machine. It does not, however, fix the graphical tearing when switching back from a VT - that sounds a lot like #4943. Also, I found that the graphical system seemed to be fully active aside from the black screen - when I moved the mouse, it changed away from a text indicator to a regular pointer (seems it was positioned over the LightDM password field initially), and I was able to log into the session by typing blind. VMs clearly launched autostart items because I heard a notification sound coming from one of my VMs.

Here's some information from my machine:

```
[alex@dom0 ~]$ uname -a
Linux dom0 5.10.8-1.qubes.x86_64 #1 SMP Mon Jan 18 21:23:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[alex@dom0 ~]$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Device 3e9b
01:00.0 VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile 3GB] (rev a1)
[alex@dom0 ~]$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
On-line CPU(s) list:   0-5
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Stepping:              10
CPU MHz:               2200.000
BogoMIPS:              4416.07
Hypervisor vendor:     Xen
Virtualization type:   none
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              9216K
NUMA node0 CPU(s):     0-5
Flags:                 fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ht syscall nx lm constant_tsc arch_perfmon rep_good nopl nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor est ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch epb ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 bmi2 erms rdseed adx clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear
[alex@dom0 tmp]$ cat /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"

  Option "AccelMethod" "sna"
  Option "TripleBuffer" "true"
  Option "TearFree" "true"
EndSection
```

**Comment by lubellier** [comment] 2021-12-04 18:07
@arkenoi @the-ch0sen-0ne @strugee Is this issue now deprecated with the newer kernels? Closable issue?

**Comment by strugee** [comment] 2021-12-04 22:19
I haven't seen this issue in a long time.

**Comment by andrewdavidwong** [comment] 2021-12-07 17:07
Closing this for now as it appears that the issue no longer affects any Qubes users. If anyone believes this is a mistake, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-12-07 17:07 UTC
Labels: T: bug, C: kernel, P: default, needs diagnosis
