### ISSUE TITLE
Sys-net stops connecting to wifi after resume from sleep and needs to be restarted

### ISSUE THREAD

**Issue by tetrahedras** [QubesOS/qubes-issues#5508] opened 2019-12-08 03:31 UTC
### Qubes OS version:

R4.0

### Affected component(s) or functionality:
sys-net

---

### Steps to reproduce the behavior:
1. Put laptop to sleep
2. Move to somewhere where only unfamiliar Wi-Fi networks are in range (this step may be optional)
3. Resume laptop
4. Click the Wi-Fi network menu widget
5. Observe that no Wi-Fi networks are displayed, even though they are definitely in range
6. In dom0 execute `qvm-kill sys-net; qvm-start sys-net`
7. Once sys-net restarts, observe that the local Wi-Fi networks are correctly displayed in the menu widget and you are able to connect to them

(note this may be an intermittent issue, and this behaviour does not always appear)

### Expected or desired behavior:
Wi-Fi networks always appear in the sys-net menu widget after sleep

### Actual behavior:
Wi-Fi networks don't always appear in the sys-net menu widget after sleep

### General notes:
Problem appeared after upgrading from fedora-29 to fedora-30 (and changing sys-net to the fedora-30 template)

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

n/a -- this is pretty obviously a software bug, it seems unlikely documentation will help

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
https://github.com/QubesOS/qubes-issues/issues/4658
This looks like a near-duplicate except it's described for Qubes 3.2 and I'm using Qubes 4

https://github.com/QubesOS/qubes-issues/issues/3008
This could be a more detailed version of the same issue, I haven't tried reloading iwlwifi (yet)

**Comment by andrewdavidwong** [comment] 2019-12-09 05:53
> #4658
> This looks like a near-duplicate except it's described for Qubes 3.2 and I'm using Qubes 4

We generally do not maintain separate issues for the same bug in separate Qubes versions. The issue gets the milestone for the earliest affected Qubes version. So, I'll close this is as a duplicate of #4658. Please comment on that existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2019-12-09 05:53
Duplicate of #4658

**Closed by andrewdavidwong** 2019-12-09 05:53 UTC

**Comment by tetrahedras** [comment] 2022-11-24 16:39
In my case this issue ONLY affects the wireless card, not Ethernet. Ethernet connections continue to work fine even when this problem has manifested itself.
