### ISSUE TITLE
Easy method to prevet starting VMs on boot, for troubleshooting

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4312] opened 2018-09-16 03:22 UTC
It would be useful to have easy method to ignore `autostart=True` VMs on boot, for example when:
 - sys-usb was enabled, but the only keyboard is on USB and `qubes.InputKeyboard` service is disabled
 - some PCI device assigned to autostart VM crashes the system

Right now to recover from such a case, one need to boot another system (for example installer and switch to text console), mount qubes partition and manually disable `qubes-vm@`  services by removing relevant symlinks from `/etc/systemd/systemd/multi-user.wants`.

I think adding a `qubes.skip_autostart` option on kernel command line should be enough. It's easy enough to specify it in Grub. Unfortunately, this won't work on UEFI, because we don't have Grub there. And even if we had, xen.efi doesn't allow to modify dom0 kernel options from its arguments (only via xen.cfg). But lack of proper bootloader on UEFI is a separate issue.

**Comment by marmarek** [comment] 2018-09-16 19:05
@andrewdavidwong it would be good to document it somewhere, any ideas where it will be easiest to find?

**Comment by andrewdavidwong** [comment] 2018-09-16 21:27
I think a new page under [Troubleshooting](https://www.qubes-os.org/doc/#troubleshooting) would make sense.

**Comment by ejose19** [comment] 2021-01-29 16:11
This really should be docummented, under a new section in Troubleshooting ("Boot Troubleshooting" or "dom0 Troubleshooting" terms come to my mind when one wants to debug an issue like this) along with changing dom0 kernel. The're are many entries in qubes-users with solutions randing from editing qubes.xml (which does nothing) or trying to use qvm-prefs in chroot (which also doesn't work), so this is the best way to do it (I can confirm it works with UEFI as well)

**Comment by andrewdavidwong** [comment] 2021-01-30 04:55
> This really should be docummented, under a new section in Troubleshooting ("Boot Troubleshooting" or "dom0 Troubleshooting" terms come to my mind when one wants to debug an issue like this) along with changing dom0 kernel. The're are many entries in qubes-users with solutions ranging from editing qubes.xml (which does nothing) or trying to use qvm-prefs in chroot (which also doesn't work), so this is the best way to do it.
> 
> I can confirm it works with UEFI as well adding the parameter on xen.cfg

In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by fepitre** [comment] 2021-06-26 15:40
I'm closing it since we have the option + documentation now. If I've missed something, please reopen.

**Closed by fepitre** 2021-06-26 15:40 UTC
Labels: C: core, C: doc, P: minor, T: enhancement, r4.0-dom0-stable
