### ISSUE TITLE
Q4.1: Whonix 16 DVM has no applications

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#7064] opened 2021-11-15 11:58 UTC
### Qubes OS release

4.1.

### Brief summary

I followed https://www.whonix.org/wiki/Qubes/Install#Installation to install the whonix 16 templates and ended up with a DVM menu entry with no apps (and also the template whonix-ws-16 entry).

![Screenshot_2021-11-15_11-58-03](https://user-images.githubusercontent.com/29158971/141778287-1236114b-04ed-49e2-9470-4830eed1961b.png)

**Comment by Minimalist73** [comment] 2021-11-15 12:00
Can't you put application by going in Qube Settings and then "Applications"?

**Comment by jpds** [comment] 2021-11-15 12:04
@Minimalist73 Sure, there's still a bug somewhere though and whilst you might be into minimalism - you cannot expect every user to go and do that.

**Comment by Minimalist73** [comment] 2021-11-15 12:11
> @Minimalist73 Sure, there's still a bug somewhere though and whilst you might be into minimalism - you cannot expect every user to go and do that.

Maybe it's just me, but adding applications manually is something pretty basic in Qubes (It's what everybody do with AppVMs). Maybe they could add some basic applications but in the end the user will put his own preferred apps there so it makes no difference imo.

**Comment by adrelanos** [comment] 2022-02-10 20:05
Cannot reproduce. Never happened to me.

Still reproducible?

**Comment by DemiMarie** [comment] 2022-02-10 23:31
Never happened to me either.  Closing as “cannot reproduce” (the Qubes team was not able to reproduce the issue”.

**Closed by DemiMarie** 2022-02-10 23:31 UTC
Labels: T: bug, C: desktop-linux, C: Whonix, P: default, needs diagnosis
