### ISSUE TITLE
Global settings does not launch: TypeError

### ISSUE THREAD

**Issue by zS3mNH2** [QubesOS/qubes-issues#5146] opened 2019-07-07 00:11 UTC
**Qubes OS version**
Qubes latest version

**Affected component(s) or functionality**
Quebes Global Settings

**Brief summary**
Hitting "Global settings" in qubes manager causes this error. It is the same as #4988 but since that has been marked as fixed since May, this must be a new regression

Here is the output to stdout:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py", line 1094, in action_global_settings_triggered
    self.qubes_app)
  File "/usr/lib/python3.5/site-packages/qubesmanager/global_settings.py", line 60, in __init__
    self.__init_updates__()
  File "/usr/lib/python3.5/site-packages/qubesmanager/global_settings.py", line 248, in __init_updates__
    self.updates_dom0.setChecked(self.updates_dom0_val)
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'


```

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Open qubes manager
_2. Click global settings and it does not appear

**Expected behavior**
No errors. Global settings appears

**Actual behavior**
Listed error shows and no launch

**Additional context**
Same as closed issue I think, but it appears issue is still not resolved even though issue has been marked resolved.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#4988

**Comment by marmarek** [comment] 2019-07-07 00:17
What version of qubes-manager package do you have? Check with `rpm -q qubes-manager` in dom0.

**Comment by zS3mNH2** [comment] 2019-07-07 00:39
I run qubes-dom0-update and it says there are no updates:
```
Dependencies resolved.
Nothing to do.
Complete!
Qubes OS Repository for Dom0                    116 MB/s | 210 kB     00:00
```
I run the rpm command and it outputs:

`qubes-manager-4.0.33-1.fc25.noarch`

**Comment by marmarek** [comment] 2019-07-07 01:08
This version (and next 3) were stuck in testing repository. Should be in stable now. Try updating with `qubes-dom0-update --clean` to clean the cache first.

**Comment by zS3mNH2** [comment] 2019-07-08 01:41
Thanks for the reply, but that is not working. Could it be the update system is broken? Here is the output of "qubes-dom0-update --clean"

```
33 files removed
Fedora 25 - x86_64 - Updates                    2.3 MB/s |  24 MB     00:10    
Fedora 25 - x86_64                              3.7 MB/s |  50 MB     00:13    
Qubes Dom0 Repository (updates)                 2.0 MB/s |  11 MB     00:05    
determining the fastest mirror (15 hosts).. done..2 kB/s | 2.7 kB     00:00 ETA
Qubes Templates repository                      2.3 kB/s |  12 kB     00:05    
Last metadata expiration check: 0:00:01 ago on Mon Jul  8 01:40:12 2019.
Dependencies resolved.
Nothing to do.
Complete!
No packages downloaded
```

It says there are no updates. I don't think there has been updates in quite a while. I then run the rpm command just to verify and it still says:

`qubes-manager-4.0.33-1.fc25.noarch`

Any ideas on what it could be?

**Comment by andrewdavidwong** [comment] 2019-07-08 08:18
> Hitting "Global settings" in qubes manager causes this error. It is the same as #4988 but since that has been marked as fixed since May, this must be a new regression

Please do not open open a separate issue for a suspected regression. Instead, please comment on the existing issue to notify us of the suspected regression, and we will reopen that issue. Please see https://www.qubes-os.org/doc/reporting-bugs/ for the policy on this. Thank you.

**Comment by andrewdavidwong** [comment] 2019-07-08 08:19
Duplicate of #4988

**Comment by andrewdavidwong** [comment] 2019-07-08 08:19
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-07-08 08:19 UTC
Labels: P: default, T: bug
