### ISSUE TITLE
Windows Stuck at Install

### ISSUE THREAD

**Issue by MegaTraveller** [QubesOS/qubes-issues#2542] opened 2016-12-28 08:56 UTC
#### Affected TemplateVMs: Windows Standalone HVM

---

### Steps to reproduce the behavior: 
Copied ISOs to Work VM (debian 8)
Assigned ISO to HVM
Boot up

### General notes:
Retried Installation also with 32 Bit ISO, recreated HVM, also assigned CPUs from 1 till 4, also assigned up to 8 GB RAM

System is a Dell Latitude E5570

![bildschirmfoto_2016-12-28_09-54-26](https://cloud.githubusercontent.com/assets/618862/21518032/e3930de2-cce3-11e6-90bf-a0b8bebb86bd.png)

---

**Comment by andrewdavidwong** [comment] 2016-12-28 12:03
Possible duplicate of #2488.

**Closed** 2016-12-28 15:48 UTC
Labels: bug, C: windows tools
