### ISSUE TITLE
Shared directory

### ISSUE THREAD

**Issue by Bodup** [QubesOS/qubes-issues#4648] opened 2018-12-22 15:10 UTC
Probably a duplicate of #2826

If VM's could have a shared directory, it would open up a lot of use cases.
For example, one might use a tool such as [Cryptomator](https://cryptomator.org) to encrypt files on the shared directory while using a separate networked VM to run the cloud sync client. 
That way the plaintext files and encryption keys are never exposed to a networked VM running potentially untrusted sync clients. 

The virtual drive exposed by cryptomator could even be mounted on a different VM so that a potentially malicious file can't leak the files or keys by putting them in the shared directory. See visualization [here](https://imgur.com/a/S7kQVXe)

**Comment by andrewdavidwong** [comment] 2018-12-22 20:56
> Probably a duplicate of #2826

Yes, this looks like a duplicate of #2826. Please add this as a comment on that issue.

**Comment by andrewdavidwong** [comment] 2018-12-22 20:56
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-12-22 20:56 UTC
