### ISSUE TITLE
Debian 9 template not functioning

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3220] opened 2017-10-26 17:52 UTC
#### Qubes OS version:

R4.0rc2

#### Affected TemplateVMs: 

debian-9

---

### Steps to reproduce the behavior:

1. Install qubes-template-debian-9

2. qvm-start debian-9
...or any VM based on it

### Expected behavior:

VM starts and responds to input (run terminal, etc).

### Actual behavior:

The debian-9 template appears to install OK, but neither it nor VMs based on it will start properly. The menu list contains only the "VM Settings" entry. Starting in debug mode with `qvm-run debian-9 xterm` the last thing I see in the console window is "Probing EDD...ok" then a much larger blank window opens. Then it will just sit like that forever. This is 100% reproducible.

The vm-debian-9.log says:
Starting debian-9
Setting Qubes DB info for the VM
Starting Qubes DB
Activating the debian-9 VM 

### General notes:

https://groups.google.com/d/msgid/qubes-users/f44a670d-85d3-58a3-794c-4c613a0b271b%40posteo.net

---

**Comment by marmarek** [comment] 2017-10-26 18:25
This is a duplicate of #2370, recently reopened...

**Closed by marmarek** 2017-10-26 18:25 UTC
