### ISSUE TITLE
Nvidia X startup failed, aborting installation

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#6004] opened 2020-08-15 10:15 UTC
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Installer

**Brief summary**
Everything works up until Qubes tries to start an X server.

**To Reproduce**
1. Boot from USB.
2. Choose whatever option you like.
3. Wait until the screen with 3 dots goes away. _Kinda awkward that this renders in my opinion._
4. See log in "Additional context."

**Expected behavior**
The X server starts successfully.

**Actual behavior**
The X server fails to start.

**Screenshots**
N/A

**Additional context**
- Secure boot is disabled.
- Legacy support is enabled.
- Legacy boot first is enabled.

<details>

```
Starting installer, one moment...
anaconda 25.20.9-1 for Qubes R4.0.3 started.
 * installation for log files are stored in /tmp during the installation
 * shell is available on TTY2
 * if the graphical interface fails to start, try again with the inst.txt bootoption to start text installation.
 * when reporting a bug add logs from /tmp as separate text/plain attachments
XX:XX:XX Not asking for VNC because we don't have a network
XX:XX:XX X startup failed, aborting installation
XX:XX:XX X startup failed, aborting installation
The installation cannot continue and the system will be rebooted
Press ENTER to continue
(Enter)
Pane is dead
```
```
archlinux
    description: Notebook
    product: 81UH (LENOVO_MT_81UH_BU_idea_FM_Legion Y740-15IRHg)
    vendor: LENOVO
    version: Lenovo Legion Y740-15IRHg
    serial: MP1LENTF
    width: 64 bits
    capabilities: smbios-3.0.1 dmi-3.0.1 smp vsyscall32
    configuration: administrator_password=disabled boot=normal chassis=notebook family=Legion Y740-15IRHg frontpanel_password=disabled keyboard_password=disabled power-on_password=disabled sku=LENOVO_MT_81UH_BU_idea_FM_Legion Y740-15IRHg uuid=6BDA9AE0-6F78-E911-8101-9C5A445184A0
  *-core
       description: Motherboard
       product: LNVNB161216
       vendor: LENOVO
       physical id: 0
       version: SDK0R32862 WIN
       serial: MP1LENTF
       slot: Type2 - Board Chassis Location
     *-firmware
          description: BIOS
          vendor: LENOVO
          physical id: 0
          version: BVCN10WW(V1.06)
          date: 06/06/2019
          size: 128KiB
          capacity: 10MiB
          capabilities: pci upgrade shadowing cdboot bootselect edd int13floppynec int13floppytoshiba int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int9keyboard int10video acpi usb biosbootspecification uefi
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 4350MHz
          capacity: 4500MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d cpufreq
          configuration: cores=6 enabledcores=6 threads=12
        *-cache:0
             description: L1 cache
             physical id: 5
             slot: L1 Cache
             size: 384KiB
             capacity: 384KiB
             capabilities: synchronous internal write-back unified
             configuration: level=1
        *-cache:1
             description: L2 cache
             physical id: 6
             slot: L2 Cache
             size: 1536KiB
             capacity: 1536KiB
             capabilities: synchronous internal write-back unified
             configuration: level=2
        *-cache:2
             description: L3 cache
             physical id: 7
             slot: L3 Cache
             size: 12MiB
             capacity: 12MiB
             capabilities: synchronous internal write-back unified
             configuration: level=3
     *-memory
          description: System Memory
          physical id: 25
          slot: System board or motherboard
          size: 16GiB
        *-bank:0
             description: SODIMM DDR4 Synchronous 2667 MHz (0.4 ns)
             product: RMSA3260ME78HAF-2666
             vendor: Ramaxel
             physical id: 0
             serial: 136581AA
             slot: ChannelA-DIMM0
             size: 8GiB
             width: 64 bits
             clock: 2667MHz (0.4ns)
        *-bank:1
             description: SODIMM DDR4 Synchronous 2667 MHz (0.4 ns)
             product: RMSA3260ME78HAF-2666
             vendor: Ramaxel
             physical id: 1
             serial: 1215A28D
             slot: ChannelB-DIMM0
             size: 8GiB
             width: 64 bits
             clock: 2667MHz (0.4ns)
     *-pci
          description: Host bridge
          product: 8th Gen Core Processor Host Bridge/DRAM Registers
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 07
          width: 32 bits
          clock: 33MHz
          configuration: driver=skl_uncore
          resources: irq:0
        *-pci:0
             description: PCI bridge
             product: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16)
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 07
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:121 ioport:4000(size=4096) memory:50000000-640fffff ioport:92000000(size=1048576)
           *-display
                description: VGA compatible controller
                product: TU104BM [GeForce RTX 2080 Mobile]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:180 memory:63000000-63ffffff memory:50000000-5fffffff memory:60000000-61ffffff ioport:4000(size=128) memory:62000000-6207ffff
           *-multimedia
                description: Audio device
                product: TU104 HD Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:01:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:17 memory:64000000-64003fff
           *-usb
                description: USB controller
                product: TU104 USB 3.1 Host Controller
                vendor: NVIDIA Corporation
                physical id: 0.2
                bus info: pci@0000:01:00.2
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: msi pciexpress pm xhci cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:143 memory:92000000-9203ffff memory:92040000-9204ffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.8.1-arch1-1 xhci-hcd
                   physical id: 0
                   bus info: usb@3
                   logical name: usb3
                   version: 5.08
                   capabilities: usb-2.00
                   configuration: driver=hub slots=2 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.8.1-arch1-1 xhci-hcd
                   physical id: 1
                   bus info: usb@4
                   logical name: usb4
                   version: 5.08
                   capabilities: usb-3.10
                   configuration: driver=hub slots=4 speed=10000Mbit/s
           *-serial
                description: Serial bus controller
                product: TU104 USB Type-C UCSI Controller
                vendor: NVIDIA Corporation
                physical id: 0.3
                bus info: pci@0000:01:00.3
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: msi pciexpress pm bus_master cap_list
                configuration: driver=nvidia-gpu latency=0
                resources: irq:145 memory:64004000-64004fff
        *-generic:0
             description: Signal processing controller
             product: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
             vendor: Intel Corporation
             physical id: 4
             bus info: pci@0000:00:04.0
             version: 07
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm bus_master cap_list
             configuration: driver=proc_thermal latency=0
             resources: irq:16 memory:92410000-92417fff
        *-generic:1 UNCLAIMED
             description: System peripheral
             product: Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
             vendor: Intel Corporation
             physical id: 8
             bus info: pci@0000:00:08.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm bus_master cap_list
             configuration: latency=0
             resources: memory:92424000-92424fff
        *-generic:2
             description: Signal processing controller
             product: Cannon Lake PCH Thermal Controller
             vendor: Intel Corporation
             physical id: 12
             bus info: pci@0000:00:12.0
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=intel_pch_thermal latency=0
             resources: irq:16 memory:92425000-92425fff
        *-usb
             description: USB controller
             product: Cannon Lake PCH USB 3.1 xHCI Host Controller
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:142 memory:92400000-9240ffff
           *-usbhost:0
                product: xHCI Host Controller
                vendor: Linux 5.8.1-arch1-1 xhci-hcd
                physical id: 0
                bus info: usb@1
                logical name: usb1
                version: 5.08
                capabilities: usb-2.00
                configuration: driver=hub slots=16 speed=480Mbit/s
              *-usb:0
                   description: Keyboard
                   product: ITE Device(8910)
                   vendor: ITE Tech. Inc.
                   physical id: 4
                   bus info: usb@1:4
                   version: 13.11
                   capabilities: usb-2.01
                   configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usb:1
                   description: Keyboard
                   product: Corsair Gaming K95 RGB PLATINUM Keyboard
                   vendor: Corsai
                   physical id: 6
                   bus info: usb@1:6
                   version: 13.11
                   capabilities: usb-2.00
                   configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
              *-usb:2
                   description: Video
                   product: Integrated Camera
                   vendor: Chicony Electronics Co.,Ltd.
                   physical id: 7
                   bus info: usb@1:7
                   version: 0.27
                   serial: 0001
                   capabilities: usb-2.01
                   configuration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
              *-usb:3
                   description: Bluetooth wireless interface
                   vendor: Intel Corp.
                   physical id: e
                   bus info: usb@1:e
                   version: 0.02
                   capabilities: bluetooth usb-2.00
                   configuration: driver=btusb maxpower=100mA speed=12Mbit/s
           *-usbhost:1
                product: xHCI Host Controller
                vendor: Linux 5.8.1-arch1-1 xhci-hcd
                physical id: 1
                bus info: usb@2
                logical name: usb2
                version: 5.08
                capabilities: usb-3.10
                configuration: driver=hub slots=8 speed=10000Mbit/s
        *-memory UNCLAIMED
             description: RAM memory
             product: Cannon Lake PCH Shared SRAM
             vendor: Intel Corporation
             physical id: 14.2
             bus info: pci@0000:00:14.2
             version: 10
             width: 64 bits
             clock: 33MHz (30.3ns)
             capabilities: pm bus_master cap_list
             configuration: latency=0
             resources: memory:92420000-92421fff memory:92426000-92426fff
        *-network
             description: Wireless interface
             product: Wireless-AC 9560 [Jefferson Peak]
             vendor: Intel Corporation
             physical id: 14.3
             bus info: pci@0000:00:14.3
             logical name: wlp0s20f3
             version: 10
             serial: a4:c3:f0:48:3a:14
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical wireless
             configuration: broadcast=yes driver=iwlwifi driverversion=5.8.1-arch1-1 firmware=46.8902351f.0 9000-pu-b0-jf-b0- ip=192.168.0.157 latency=0 link=yes multicast=yes wireless=IEEE 802.11
             resources: irq:16 memory:92418000-9241bfff
        *-serial:0
             description: Serial bus controller
             product: Cannon Lake PCH Serial IO I2C Controller #0
             vendor: Intel Corporation
             physical id: 15
             bus info: pci@0000:00:15.0
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:16 memory:64100000-64100fff
        *-serial:1
             description: Serial bus controller
             product: Cannon Lake PCH Serial IO I2C Controller #1
             vendor: Intel Corporation
             physical id: 15.1
             bus info: pci@0000:00:15.1
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:17 memory:64101000-64101fff
        *-communication:0
             description: Communication controller
             product: Cannon Lake PCH HECI Controller
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: irq:146 memory:92429000-92429fff
        *-sata
             description: SATA controller
             product: Cannon Lake Mobile PCH SATA AHCI Controller
             vendor: Intel Corporation
             physical id: 17
             bus info: pci@0000:00:17.0
             version: 10
             width: 32 bits
             clock: 66MHz
             capabilities: sata msi pm ahci_1.0 bus_master cap_list
             configuration: driver=ahci latency=0
             resources: irq:128 memory:92422000-92423fff memory:9242e000-9242e0ff ioport:5040(size=8) ioport:5048(size=4) ioport:5020(size=32) memory:9242d000-9242d7ff
        *-pci:1
             description: PCI bridge
             product: Cannon Lake PCH PCI Express Root Port #17
             vendor: Intel Corporation
             physical id: 1b
             bus info: pci@0000:00:1b.0
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:122 ioport:6000(size=8192) memory:94000000-aa0fffff ioport:70000000(size=570425344)
        *-pci:2
             description: PCI bridge
             product: Cannon Lake PCH PCI Express Root Port #21
             vendor: Intel Corporation
             physical id: 1b.4
             bus info: pci@0000:00:1b.4
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:123 memory:92300000-923fffff
           *-nvme
                description: NVMe device
                product: SAMSUNG MZVLB1T0HALR-000L2
                vendor: Samsung Electronics Co Ltd
                physical id: 0
                bus info: pci@0000:3e:00.0
                logical name: /dev/nvme0
                version: 5L1QEXA7
                serial: S3RSNA0M539249
                width: 64 bits
                clock: 33MHz
                capabilities: nvme pm msi pciexpress msix nvm_express bus_master cap_list
                configuration: driver=nvme latency=0 nqn=nqn.2014.08.org.nvmexpress:144d144dS3RSNA0M539249      SAMSUNG MZVLB1T0HALR-000L2 state=live
                resources: irq:16 memory:92300000-92303fff
              *-namespace
                   description: NVMe disk
                   physical id: 1
                   bus info: nvme@0:1
                   logical name: /dev/nvme0n1
                   size: 953GiB (1024GB)
                   capabilities: gpt-1.00 partitioned partitioned:gpt
                   configuration: guid=80d810a0-377f-2342-92ff-13cce4d78d76 logicalsectorsize=512 sectorsize=512 wwid=eui.00253885910a1ab4
                 *-volume:0 UNCLAIMED
                      description: Windows FAT volume
                      vendor: mkfs.fat
                      physical id: 1
                      bus info: nvme@0:1,1
                      version: FAT32
                      serial: 0a59-a3af
                      size: 1022MiB
                      capacity: 1023MiB
                      capabilities: boot fat initialized
                      configuration: FATs=2 filesystem=fat
                 *-volume:1
                      description: EFI partition
                      physical id: 2
                      bus info: nvme@0:1,2
                      logical name: /dev/nvme0n1p2
                      serial: cb61dc16-6723-43fa-87cf-0165d4153db9
                      size: 952GiB
                      capacity: 952GiB
                      width: 2954862648 bits
                      capabilities: encrypted luks initialized
                      configuration: bits=11544797240 filesystem=luks hash=sha256 version=2
        *-pci:3
             description: PCI bridge
             product: Cannon Lake PCH PCI Express Root Port #13
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:124 ioport:3000(size=4096) memory:92200000-922fffff
           *-network
                description: Ethernet interface
                product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:3f:00.0
                logical name: enp63s0
                version: 15
                serial: 9c:5a:44:51:84:a0
                size: 1Gbit/s
                capacity: 1Gbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress msix bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=5.8.1-arch1-1 duplex=full firmware=rtl8168h-2_0.0.2 02/26/15 ip=192.168.0.241 latency=0 link=yes multicast=yes port=MII speed=1Gbit/s
                resources: irq:16 ioport:3000(size=256) memory:92204000-92204fff memory:92200000-92203fff
        *-communication:1
             description: Communication controller
             product: Cannon Lake PCH Serial IO UART Host Controller
             vendor: Intel Corporation
             physical id: 1e
             bus info: pci@0000:00:1e.0
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: irq:20 memory:64102000-64102fff
        *-isa
             description: ISA bridge
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 10
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master
             configuration: latency=0
        *-multimedia
             description: Audio device
             product: Cannon Lake PCH cAVS
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             version: 10
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=32
             resources: irq:178 memory:9241c000-9241ffff memory:92100000-921fffff
        *-serial:2
             description: SMBus
             product: Cannon Lake PCH SMBus Controller
             vendor: Intel Corporation
             physical id: 1f.4
             bus info: pci@0000:00:1f.4
             version: 10
             width: 64 bits
             clock: 33MHz
             configuration: driver=i801_smbus latency=0
             resources: irq:16 memory:9242b000-9242b0ff ioport:5000(size=32)
        *-serial:3
             description: Serial bus controller
             product: Cannon Lake PCH SPI Controller
             vendor: Intel Corporation
             physical id: 1f.5
             bus info: pci@0000:00:1f.5
             version: 10
             width: 32 bits
             clock: 33MHz
             capabilities: bus_master
             configuration: driver=intel-spi latency=0
             resources: irq:0 memory:fe010000-fe010fff
     *-pnp00:00
          product: Motherboard registers
          physical id: 1
          capabilities: pnp
          configuration: driver=system
     *-pnp00:01
          product: Motherboard registers
          physical id: 2
          capabilities: pnp
          configuration: driver=system
     *-pnp00:02
          product: Motherboard registers
          physical id: 3
          capabilities: pnp
          configuration: driver=system
     *-pnp00:03
          product: Motherboard registers
          physical id: 5
          capabilities: pnp
          configuration: driver=system
     *-pnp00:04
          product: AT Real-Time Clock
          physical id: 6
          capabilities: pnp
          configuration: driver=rtc_cmos
     *-pnp00:05
          product: PnP device INT3f0d
          physical id: 7
          capabilities: pnp
          configuration: driver=system
     *-pnp00:06
          product: IBM Enhanced keyboard controller (101/2-key)
          physical id: 8
          capabilities: pnp
          configuration: driver=i8042 kbd
     *-pnp00:07
          product: Motherboard registers
          physical id: 9
          capabilities: pnp
          configuration: driver=system
     *-pnp00:08
          product: Motherboard registers
          physical id: a
          capabilities: pnp
          configuration: driver=system
  *-battery
       description: Zinc Air Battery
       product: CRB Battery 0
       vendor: -Virtual Battery 0-
       physical id: 1
       version: 08/08/2010
       serial: Battery 0
       slot: Fake
  *-power UNCLAIMED
       description: OEM Define 1
       product: OEM Define 5
       vendor: OEM Define 2
       physical id: 2
       version: OEM Define 6
       serial: OEM Define 3
       capacity: 75mWh
```

</details>

**Solutions you've tried**
- I applied what I always did to get the Arch Linux installer to start: Add `nouveau.modeset=0` to the boot configuration.
- I consulted the [NVidia Troubleshooting Guide](https://www.qubes-os.org/doc/nvidia-troubleshooting/) and added `nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off` to my boot configuration.
- I consulted [this](https://www.reddit.com/r/Qubes/comments/i6ey7x/qubes_installation_failure_x_startup_failed/) reddit post. Although I added `xdriver=nouveau` instead of `xdriver=intel`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- [NVidia Troubleshooting Guide](https://www.qubes-os.org/doc/nvidia-troubleshooting/)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

**Comment by Guntisbe** [comment] 2020-09-10 18:37
I'm having the same issue, also Nvidia graphics card, but GTX 1650.

**Comment by dud1337** [comment] 2020-11-28 07:28
Confirmed with GTX 2070S Qubes 4.0.3

**Comment by maxss280** [comment] 2020-12-29 17:30
Same issue here with GTX 3060 ti

**Comment by Bright-Shard** [comment] 2021-01-07 00:22
I think the issue has something to do with the driver, because there's weird Xorg errors for both the Vesa and Nouveau drivers, but they're different ones. I tried running `xinit` and `X -configure` but neither worked on either driver. There's a [tutorial on installing NVidia proprietary drivers](https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/install-nvidia-driver.md), but it seems to assume you've already installed the system, because the commands don't work in the installer shell. If anyone knows how to get that working from the installer, that'd be great and I think it would fix it.

**Comment by vp00** [comment] 2021-02-28 13:15
Same issue here, RTX 2060. Also tried with the config `Xorg -configure` generates without success.

Any workarounds?

**Comment by vp00** [comment] 2021-02-28 13:35
This appears to be fixed in 4.0.4-rc2.

**Comment by CybaPunk** [comment] 2021-05-25 01:33
> This appears to be fixed in 4.0.4-rc2.

i hope so im running a 3080 and have been trying to get around the X Startup Failed for ages, ill try installing now

**Comment by FayDoom** [comment] 2022-02-05 16:25
The probleme is still there with the 4.1 release

**Comment by willneumann** [comment] 2022-11-21 04:19
Having the same issue when trying to install release 4.1.1. My graphics card is the Nvidia RTX 3070 TI (laptop GPU). "X startup failed, aborting installation".

**Comment by SlinkyGopher** [comment] 2023-05-06 17:45
I am having the same issue with an RTX 3070 Ti. Tried all the troubleshooting steps in the docs and have used Qubes OS before.

**Closed** 2024-12-07 14:19 UTC
Labels: T: bug, C: installer, P: default, hardware support, affects-4.1, eol-4.1

**Comment by oddbyte** [comment] 2026-02-07 02:46
Affects 4.3.0, nvidia 4060ti

**Comment by oddbyte** [comment] 2026-02-20 17:38
4.2.4 works fine (it installs, boots, and functions as intended) until i update dom0, after which i get a lightdm error
