### ISSUE TITLE
If meminfo-writer/qmemman needs to be disabled for VMs with PCI devices, it should be done by dom0 and not by the VM for PCI hotplug

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3248] opened 2017-10-28 15:17 UTC
Currently /usr/lib/qubes/init/qubes-sysinit.sh disables meminfo-writer if it finds a non-Qemu PCI device upon initialization.

However, this behavior obviously doesn't work properly with PCI hotplug, so it should be qmemman that doesn't balance memory on domains with PCI devices attached rather than the VM deciding to not run meminfo-writer.

Also, I'm not sure why this is needed at all: if all qmemman does is cause Xen balloon inflation, why would having PCI devices attached matter?

**Comment by marmarek** [comment] 2017-10-28 15:30
This is a duplicate of #3207

**Closed by marmarek** 2017-10-28 15:30 UTC
