### ISSUE TITLE
Renaming error

### ISSUE THREAD

**Issue by Drubble** [QubesOS/qubes-issues#2561] opened 2017-01-07 11:35 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

N/A
---

### Expected behavior:

Renaming a TemplateVM in the Qubes VM Manager should rename the VM as expected (KaliVM --> sys-kali)

### Actual behavior:

Name inside the GUI does not update. However, the name in /var/lib/qubes/vm-templates does update which messes up the VM Manager. Trying to perform any actions on the VM (such as opening its settings results in the following error:

`[Dom0]: OSError: [Errno 2] No such file or directory: '/var/lib/qubes/vm-templates/KaliVM/apps.templates' this is most likely a bug in the Qubes Manager`

### Steps to reproduce the behavior:

*Unable to reproduce

I created a kali VM using the steps listed [here](https://www.qubes-os.org/doc/pentesting/kali/) by cloning a Debian VM template and converting it to a Kali system.

### General notes:

I'd be able to fix the broken link if only I knew how to manually change it. 

---

**Comment by Drubble** [comment] 2017-01-07 11:50
I think this may be related to #2407

**Comment by andrewdavidwong** [comment] 2017-01-14 09:18
Duplicate of #2054.

**Closed by andrewdavidwong** 2017-01-14 09:18 UTC
Labels: bug, C: core, C: qubes-manager
