### ISSUE TITLE
windows disapper after xfce4 crash

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5647] opened 2020-02-13 05:07 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**

**Brief summary**
windows disapper after xfce4 crash

**To Reproduce**
Irreproducible

**Expected behavior**
windows of previously running programs appear after re-login

**Actual behavior**
Some windows disappear as soon as they appear.

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment] 2020-02-13 10:15
What version of qubes-gui-dom0 package do you have? I believe this is fixed in 4.0.10, in current-testing repository (https://github.com/QubesOS/updates-status/issues/1616).

**Comment by jamke** [comment] 2020-07-14 05:31
I had the same issue twice already and it's **critical**.

What happens:
1) all windows disappear.
2) Tray icon shows that AppVMs are running, but it's impossible to run anything including terminal in those AppVMs not using Qubes GUI, nor via `qvm-run`. I mean, it probably runs something but no windows are visible.
3) There is no way to correctly save changes in ALL opened AppVMs and the only way forward is to shutdown all the AppVMs, shutdown the whole system, boot again and hope it won't happen again too soon.

This crash (i'm not sure if it's xfce crash or not, but looks like it) was introduces in R4.0 about month or two ago. Before that I never faced it.

Now I have updated everything in `dom0` with `qubes-dom0-update` (including `qubes-gui-dom0` to 4.0.11) and hope it will never again.

Maybe there is a way to check what was the version of `qubes-gui-dom0` before I've updated it? Some kind of dnf log command or other way? If one provides this way I will tell what version of `qubes-gui-dom0` had this issue for sure (maybe 4.0.11 still has it, not sure).

**Comment by andrewdavidwong** [comment] 2020-07-15 07:26
@zaoqi, has `qubes-gui-dom0` version `4.0.10` or higher fixed this for you?

**Comment by zaoqi** [comment] 2020-07-16 11:05
I never face it again

**Comment by andrewdavidwong** [comment] 2020-07-16 13:20
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-07-16 13:20 UTC
Labels: C: gui-virtualization, P: major, T: bug, more-info-needed

**Comment by jamke** [comment] 2020-09-15 12:29
Just a note: I never faced it again too.
For people reading this issue - the fix was in `qubes-gui-dom0 4.0.11` or somewhat higher.
