### ISSUE TITLE
Error on dom0 update

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#3697] opened 2018-03-13 21:57 UTC
### Qubes OS version:
R4.0rc4

### Affected component(s): 
Updating dom0.

### Steps to reproduce the behavior:
Update dom0 for example with the GUI.

### Expected behavior:
No errors.

### Actual behavior:
qvm-ls: error: unrecognized arguments: --kernel

It's not exactly a system-breaking bug, but it looks bad.

**Comment by andrewdavidwong** [comment] 2018-03-14 00:33
Duplicate of #3694

**Comment by andrewdavidwong** [comment] 2018-03-14 00:33
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-03-14 00:33 UTC
Labels: C: other, P: minor, bug
