### ISSUE TITLE
dom0 update has broken mireage-firewall boot causing a crasha

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#8262] opened 2023-06-13 19:52 UTC
In reference to https://github.com/QubesOS/qubes-issues/issues/8243

How can you determine this is a mirageOS issue and not a QubesOS issue?

**Comment by andrewdavidwong** [comment] 2023-06-13 21:52
Duplicate of #8243

**Comment by andrewdavidwong** [comment] 2023-06-13 21:52
Please do not open a new issue to ask a question about an existing issue.

**Closed by andrewdavidwong** 2023-06-13 21:52 UTC
Labels: T: bug, P: default

**Comment by bluesteal** [comment] 2023-06-14 02:58
that issue has been marked as closed but hasn't been resolved.

**Comment by andrewdavidwong** [comment] 2023-06-14 19:22
> that issue has been marked as closed but hasn't been resolved.

That's still not a good reason to open a duplicate. Make your case on that issue and accept the outcome decided there. Don't spam the issue tracker just because you disagree with the devs.
