### ISSUE TITLE
Error after device assign

### ISSUE THREAD

**Issue by Visimar** [QubesOS/qubes-issues#2856] opened 2017-06-15 14:46 UTC
### Affected TemplateVMs (e.g., `fedora-23`, if applicable): fedora-23 or Win7
---
Issue:

After I assign a vm (fedora-23 or Win7) a device and start the vm I get the following error message:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

line: vm.name, thread_monitor.error_msg),
func: start_vm
line no.: 1217
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py

The error is with the following devices:
Audio Devices 
VGA Controllers
Ethernet Controllers

Steps to reproduce the behavior: ever time i start a vm, after install R3.2 and after update dom0

By the way:
Is it not possible to assign the second gpu device to a vm and output this vm to a second monitor? Or assign the second Audio Device for direct Audio access for the hvm?
I thought hvm allowed direct hardware access?

Very impressive what you do with this project! Thank you very much, Visimar

**Comment by andrewdavidwong** [comment] 2017-06-16 00:00
Looks like a duplicate of #2751.

**Closed by andrewdavidwong** 2017-06-16 00:00 UTC
