### ISSUE TITLE
gray labeled appVM generates green apps.icons/

### ISSUE THREAD

**Issue by nil0x42** [QubesOS/qubes-issues#4199] opened 2018-08-10 01:29 UTC
### Qubes OS version:

Qubes R 4.0

### Affected component(s): 

appmenus generator

---

### Steps to reproduce the behavior:

create an appvm with 'gray' label

### Expected behavior:

appvm's application icons are **gray**

### Actual behavior:

appvm's application icons are **green**

### General notes:

- it seems to only behave like from gray to green, so i suspect some regex someshere in the code.
(something like `^gr.*`)

- appvm's main icon is not affected by this issue (`/var/lib/qubes/appvms/<QUBE>/icon.png` is correctly set), only application icons are set to green.

---

### Related issues:

this old issue may be related: 
https://github.com/QubesOS/qubes-issues/issues/1606

**Comment by andrewdavidwong** [comment] 2018-08-10 03:49
Duplicate of #3471

**Comment by andrewdavidwong** [comment] 2018-08-10 03:49
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-10 03:49 UTC
