### ISSUE TITLE
Allow programs in full screen mode to capture the mouse

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5464] opened 2019-11-15 17:45 UTC
**The problem you're addressing (if any)**
Cannot use mouse to move camera vertically in games.

**Describe the solution you'd like**
Allow programs in full screen mode to capture the mouse

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/full-screen-mode/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4986

**Comment by andrewdavidwong** [comment] 2019-11-17 09:33
How is this not a duplicate of #4986?

**Comment by zaoqi** [comment] 2019-11-17 10:16
#4986 is not a bug, #4986 is a feature

**Comment by marmarek** [comment] 2019-11-17 13:17
Inability for a VM application to steal mouse is a feature of Qubes GUI isolation. Temporary disabling it for selected VM could be implemented, with explicit user consent. So, classification of this issue is more correct than #4986, but both are about the same thing.

**Comment by andrewdavidwong** [comment] 2019-11-17 15:06
> #4986 is not a bug, it is a feature

That doesn't necessarily mean they aren't duplicates. If the action is the same, then they can still duplicates, but it may mean one issue is not classified as accurately as it should be.

> Inability for a VM application to steal mouse is a feature of Qubes GUI isolation. Temporary disabling it for selected VM could be implemented, with explicit user consent. So, classification of this issue is more correct than #4986, but both are about the same thing.

I'll reclassify #4986 as an enhancement and close this as a duplicate of it.

**Closed by andrewdavidwong** 2019-11-17 15:06 UTC
Labels: C: other, P: default, T: enhancement
