### ISSUE TITLE
bug with qvm-prefs, crashed starting appvm 

### ISSUE THREAD

**Issue by Aporbel** [QubesOS/qubes-issues#6390] opened 2021-02-10 13:27 UTC
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qvm-prefs
qubes-backup

**Brief summary**
Yesterday, tried to do backup, got error: Got empty response from qubesd. See journalctl in dom0 for details. 
Journalctl : something wrong in code base.py 
More error:  “whoops. A critical error has occurred. This most likely a bug in qubes global settings application. QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.at line 81 of file base.py."

After those trying I won’t able to starting AppVM that tried adding to backup. 

Got error :domain “name” has failed to start: nested calls to start() 

More error: dirty volume cannot be starting after exported (or something like that, unfortunately could not save text of error)

How can I  create backup?

log when error received:
```
Feb 10 15:37:07 dom0 qubesd[1768]: unhandled exception while calling src=b'dom0' meth=b'admin.backup.Info' dest=b'dom0' arg=b'qubes-manager-backup-tmp' len(untrusted_payload)=0
Feb 10 15:37:07 dom0 qubesd[1768]: Traceback (most recent call last):
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 275, in respond
Feb 10 15:37:07 dom0 qubesd[1768]:     untrusted_payload=untrusted_payload)
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Feb 10 15:37:07 dom0 qubesd[1768]:     yield self  # This tells Task to wait for completion.
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Feb 10 15:37:07 dom0 qubesd[1768]:     future.result()
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Feb 10 15:37:07 dom0 qubesd[1768]:     raise self._exception
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Feb 10 15:37:07 dom0 qubesd[1768]:     result = coro.send(None)
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1539, in backup_info
Feb 10 15:37:07 dom0 qubesd[1768]:     skip_passphrase=True)
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1461, in _load_backup_profile
Feb 10 15:37:07 dom0 qubesd[1768]:     **kwargs)
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib/python3.5/site-packages/qubes/backup.py", line 353, in __init__
Feb 10 15:37:07 dom0 qubesd[1768]:     self._files_to_backup = self.get_files_to_backup()
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib/python3.5/site-packages/qubes/backup.py", line 373, in get_files_to_backup
Feb 10 15:37:07 dom0 qubesd[1768]:     volume.export(),
Feb 10 15:37:07 dom0 qubesd[1768]:   File "/usr/lib/python3.5/site-packages/qubes/storage/file.py", line 272, in export
Feb 10 15:37:07 dom0 qubesd[1768]:     'nested calls to export()'
Feb 10 15:37:07 dom0 qubesd[1768]: AssertionError: nested calls to export()
```

**Comment by rustybird** [comment] 2021-02-10 13:48
Duplicate of #6371

**Comment by marmarek** [comment] 2021-02-10 13:49
Duplicate of https://github.com/QubesOS/qubes-issues/issues/6371

**Comment by marmarek** [comment] 2021-02-10 13:49
And fix already in current-testing repository: https://github.com/QubesOS/updates-status/issues/2343

**Closed by marmarek** 2021-02-10 13:49 UTC
Labels: P: default, T: bug

**Comment by Aporbel** [comment] 2021-02-10 20:32
not fully works, cannot backuping TempleteVM, got error on string 102 in base.py

**Comment by Aporbel** [comment] 2021-02-10 20:43
> And fix already in current-testing repository: [QubesOS/updates-status#2343](https://github.com/QubesOS/updates-status/issues/2343)
not fully works, cannot backuping TempleteVM, got error on string 102 in base.py
file pool cannot export dirty volume

**Comment by rustybird** [comment] 2021-02-10 20:54
Sounds like false positive number 2 described in https://github.com/QubesOS/qubes-issues/issues/6371#issuecomment-775233856 for which a fix is still in development.
