### ISSUE TITLE
Unable to select target qube for backup.

### ISSUE THREAD

**Issue by lyuts** [QubesOS/qubes-issues#7987] opened 2023-01-16 04:43 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes: 4.1
Xen: 4.14.5
dom0 kernel: 5.15.81

### Brief summary

Backup manager fails when selecting target qube.

### Steps to reproduce

- Go to Qube Manager
- Click Backup
- Select qubes to back up
- Click Next
- In 'Target qube' dropdown select debian-11 based qube.
- Click on '...' button to select destination within the select qube. 

### Expected behavior

Last step above should succeed allowing to proceed with backing up qubes.

### Actual behavior

Last step above fails with

```
Error Command 'qubes.SelectDirectory' returned non-zero exit status 127. occurred.
```

**Comment by lyuts** [comment] 2023-01-16 06:10
Quick update, on one thing I thought was the case, but actually is not: the target qube is using minimal debian template, not the regular one.

**Comment by andrewdavidwong** [comment] 2023-01-16 12:31
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-01-16 12:31 UTC
Labels: T: bug, P: default
