### ISSUE TITLE
Nested virtualization

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4257] opened 2018-08-27 17:13 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Xen, mostly

---

### Steps to reproduce the behavior:

Note that VT-X and SVM are disabled in (non-PV) guests

### Expected behavior:

It is possible to enable nested virtualization

### Actual behavior:

There is no documented way to enable nested virtualization

### General notes:

This would prove very useful for:

* developing Qubes itself (I don’t want to put experimental code in my dom0)
* Android development (the Android emulator can run orders of magnitude faster if virtualization is supported)
* developing hypervisors from within Qubes
* running other hypervisors in an AppVM

---

**Comment by esote** [comment] 2018-08-27 17:52
As far as developing Qubes within a qube, I'm not sure if that would work as you intend. Per the [installation guide](https://www.qubes-os.org/doc/installation-guide/#hardware-requirements), even if you get Qubes working, it may perform differently or very slowly compared to outside of the virtualized environment.

**Comment by DemiMarie** [comment] 2018-08-27 20:01
@esote I know it would not work well.  This would be strictly for debugging Qubes itself, not for any sort of normal use.

**Comment by andrewdavidwong** [comment] 2018-08-28 01:12
Duplicate of #4104

**Comment by andrewdavidwong** [comment] 2018-08-28 01:12
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by t4777sd** [comment] 2018-08-28 01:12
Is there any documentation on how to develop for qubes? I have wanted to contribute but I have found it hard to get started. Many of the repos do not even have a readme or an explaination of what that repo functions as and how it fits into the broader qubes code. Let alone how to create a sane build environment.

**Closed by andrewdavidwong** 2018-08-28 01:12 UTC
