### ISSUE TITLE
Nothing happens when trying to start application in whonix-14

### ISSUE THREAD

**Issue by Bufil** [QubesOS/qubes-issues#4067] opened 2018-07-10 18:07 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

Whonix 14 Templates

---

### Steps to reproduce the behavior:

- Install Whonix 14 Templates like described here: https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14#Qubes-Whonix
- Try to start any application inside whonix-gw-14 or whonix-ws-14 with qvm-start or through Menu

### Expected behavior:

Application starts and GUI-Window pops up

### Actual behavior:

Nothing happens

### General notes:

I can not see any error message, so no idea whats the problem.

---

**Comment by andrewdavidwong** [comment] 2018-07-10 23:48
Duplicate of #3533

**Comment by andrewdavidwong** [comment] 2018-07-10 23:48
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by Bufil** [comment] 2018-07-12 00:40
It is not a duplicate because the apps are not opening at all.
In #3533 apps are opening if he select it again.
In my case they open never in Whonix 14 Templates and App-VMs. No matter if selected before or after starting the VM.

**Comment by Bufil** [comment] 2018-07-12 12:09
Please let me know if i can provide any more information.

**Comment by marmarek** [comment] 2018-07-12 12:42
Is qube starting at all? In qube manager you can right click on a qube and select logs submenu - check if you see any errors there.

**Comment by Bufil** [comment] 2018-07-12 16:15
Yes, qube is starting.
/var/log/xen/console/guest-whonix-gw-14.log ends with:

``
[.[0;32m  OK  .[0m] Started sets up Qubes-Whonix-Gatewa…al and internal network interface.


Welcome to Whonix!

https://www.whonix.org

default user account: user
default root account: root

default passwords: changeme
host login: 
``

**Comment by marmarek** [comment] 2018-07-12 16:18
Looks fine. What happens if you run something from a terminal using qvm-run *with -p option*? For example `qvm-run -p whonix-gw-14 xterm`?

**Comment by Bufil** [comment] 2018-07-12 16:58
If i interrupt it is:
```
[user@dom0 ~]$ qvm-run -p whonix-gw-14 xterm
^CTraceback (most recent call last):
  File "/usr/bin/qvm-run", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 205, in main
    wait_session.communicate(vm.default_user.encode())
  File "/usr/lib64/python3.5/subprocess.py", line 795, in communicate
    self.wait()
  File "/usr/lib64/python3.5/subprocess.py", line 1399, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.5/subprocess.py", line 1349, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
[user@dom0 ~]$ 
```

**Comment by marmarek** [comment] 2018-07-12 19:13
Looks like a problem with X session startup inside of VM (according to above traceback it hang in `wait_session`). You can access qube console with `sudo xl console whonix-gw-14`, login as root and check status of qubes-gui-agent service (`systemctl status qubes-gui-agent`). Check also if X server process is running.
Exit xl console with Ctrl+].

**Comment by Bufil** [comment] 2018-07-14 12:39
Thanks!
I fond out that i also had #3666.
I did:
```
sudo qubes-dom0-update --action=reinstall $(rpm -qal | grep
/usr/share/applications | xargs rpm -qf | sort -u) 
```
and it also solved this problem.

**Comment by andrewdavidwong** [comment] 2018-07-14 15:13
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-07-14 15:13 UTC
Labels: C: Whonix, C: desktop-linux, bug
