### ISSUE TITLE
 qubesctl state.sls qvm.anon-whonix (One or more requisite failed)

### ISSUE THREAD

**Issue by thxqua** [QubesOS/qubes-issues#4170] opened 2018-07-31 12:22 UTC
### Qubes OS version:
Qubes R4.0 (own build) 

WARNING ! AFTER INSTALL I ALREADY GOT A ERROR SYS-WHONIX NOT EXIST @ FIRSTBOOT

### Affected component(s): 

Whonix

---

### Steps to reproduce the behavior:

Already tried to delete, ws-gw but error stiill exists 

### Actual behavior:

Install sys-whonix and anon-whonix 

### General notes:

```
qubesctl state.sls qvm.anon-whonix
[ERROR   ] Command '['systemd-run', '--scope', 'qubes-dom0-update', '-y', '--best', '--allowerasing', '--disablerepo=*', '--enablerepo=qubes-templates-community', '--clean', '--action=install', 'qubes-template-whonix-ws-14']' failed with return code: 1
[ERROR   ] stdout: Running scope as unit: run-r5f6772bdd21346ea8880b8db1a258898.scope
Using sys-net as UpdateVM to download updates for Dom0; this may take some time...
37 files removed
determining the fastest mirror (7 hosts).. done.
Qubes Community Templates repository             21 kB/s | 3.0 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Tue Jul 31 09:36:14 2018.
No match for argument: qubes-template-whonix-ws-14
Error: Unable to find a match
[ERROR   ] retcode: 1
[ERROR   ] Error occurred installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r5f6772bdd21346ea8880b8db1a258898.scope
      Using sys-net as UpdateVM to download updates for Dom0; this may take some time...
      37 files removed
      determining the fastest mirror (7 hosts).. done.
      Qubes Community Temp  0% [                    ] ---  B/s |   0  B     --:-- ETA
      Qubes Community Templates repository             21 kB/s | 3.0 kB     00:00    
      Last metadata expiration check: 0:00:00 ago on Tue Jul 31 09:36:14 2018.
      No match for argument: qubes-template-whonix-ws-14
      Error: Unable to find a match
[WARNING ] /var/cache/salt/minion/extmods/states/ext_state_qvm.py:142: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  status = Status(retcode=1, result=False, stderr=err.message + '\n')

[ERROR   ] ====== ['features'] ======
Virtual Machine does not exist!

====== ['tags'] ======
[SKIP] Skipping due to previous failure!
[ERROR   ] Command '['systemd-run', '--scope', 'qubes-dom0-update', '-y', '--best', '--allowerasing', '--disablerepo=*', '--enablerepo=qubes-templates-community', '--action=install', 'qubes-template-whonix-gw-14']' failed with return code: 1
[ERROR   ] stdout: Running scope as unit: run-rf274cf0c714646c39a54fccdcb15c527.scope
Using sys-net as UpdateVM to download updates for Dom0; this may take some time...
Last metadata expiration check: 0:00:07 ago on Tue Jul 31 09:36:14 2018.
No match for argument: qubes-template-whonix-gw-14
Error: Unable to find a match
[ERROR   ] retcode: 1
[ERROR   ] Error occurred installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-rf274cf0c714646c39a54fccdcb15c527.scope
      Using sys-net as UpdateVM to download updates for Dom0; this may take some time...
      Last metadata expiration check: 0:00:07 ago on Tue Jul 31 09:36:14 2018.
      No match for argument: qubes-template-whonix-gw-14
      Error: Unable to find a match
[ERROR   ] ====== ['features'] ======
Virtual Machine does not exist!

====== ['tags'] ======
[SKIP] Skipping due to previous failure!
local:
----------
          ID: template-whonix-ws-14
    Function: pkg.installed
        Name: qubes-template-whonix-ws-14
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-r5f6772bdd21346ea8880b8db1a258898.scope
                    Using sys-net as UpdateVM to download updates for Dom0; this may take some time...
                    37 files removed
                    determining the fastest mirror (7 hosts).. done.
                    Qubes Community Temp  0% [                    ] ---  B/s |   0  B     --:-- ETA
                    Qubes Community Templates repository             21 kB/s | 3.0 kB     00:00    
                    Last metadata expiration check: 0:00:00 ago on Tue Jul 31 09:36:14 2018.
                    No match for argument: qubes-template-whonix-ws-14
                    Error: Unable to find a match
     Started: 09:36:03.805808
    Duration: 12198.804 ms
     Changes:   
----------
          ID: whonix-ws-tag
    Function: qvm.vm
        Name: whonix-ws-14
      Result: False
     Comment: ====== ['features'] ======
              Virtual Machine does not exist!
              
              ====== ['tags'] ======
              [SKIP] Skipping due to previous failure!
     Started: 09:36:16.007231
    Duration: 8.832 ms
     Changes:   
----------
          ID: whonix-ws-update-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is in correct state
     Started: 09:36:16.018494
    Duration: 3.127 ms
     Changes:   
----------
          ID: whonix-get-date-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.GetDate
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.GetDate is in correct state
     Started: 09:36:16.021706
    Duration: 1.098 ms
     Changes:   
----------
          ID: template-whonix-gw-14
    Function: pkg.installed
        Name: qubes-template-whonix-gw-14
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-rf274cf0c714646c39a54fccdcb15c527.scope
                    Using sys-net as UpdateVM to download updates for Dom0; this may take some time...
                    Last metadata expiration check: 0:00:07 ago on Tue Jul 31 09:36:14 2018.
                    No match for argument: qubes-template-whonix-gw-14
                    Error: Unable to find a match
     Started: 09:36:16.022880
    Duration: 7155.819 ms
     Changes:   
----------
          ID: whonix-gw-tag
    Function: qvm.vm
        Name: whonix-gw-14
      Result: False
     Comment: ====== ['features'] ======
              Virtual Machine does not exist!
              
              ====== ['tags'] ======
              [SKIP] Skipping due to previous failure!
     Started: 09:36:23.178952
    Duration: 8.178 ms
     Changes:   
----------
          ID: whonix-gw-update-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is in correct state
     Started: 09:36:23.187243
    Duration: 2.406 ms
     Changes:   
----------
          ID: sys-net
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-net 
              VM sys-net exists None
     Started: 09:36:23.189806
    Duration: 207.072 ms
     Changes:   
----------
          ID: sys-firewall
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-firewall 
              VM sys-firewall exists None
     Started: 09:36:23.397268
    Duration: 208.186 ms
     Changes:   
----------
          ID: sys-whonix
    Function: qvm.vm
      Result: False
     Comment: One or more requisite failed: qvm.template-whonix-gw.template-whonix-gw-14
     Changes:   
----------
          ID: whonix-ws-14-dvm
    Function: qvm.vm
      Result: False
     Comment: One or more requisite failed: qvm.sys-whonix.sys-whonix, qvm.template-whonix-ws.template-whonix-ws-14
     Changes:   
----------
          ID: qvm-appmenus --update whonix-ws-14-dvm
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: qvm.whonix-ws-dvm.whonix-ws-14-dvm
     Changes:   
----------
          ID: anon-whonix
    Function: qvm.vm
      Result: False
     Comment: One or more requisite failed: qvm.sys-whonix.sys-whonix, qvm.template-whonix-ws.template-whonix-ws-14, qvm.whonix-ws-dvm.whonix-ws-14-dvm
     Changes:   

Summary for local
------------
Succeeded: 5
Failed:    8
------------
Total states run:    13
Total run time:  19.794 s






```

**Comment by andrewdavidwong** [comment] 2018-08-01 01:27
Possible duplicate of #4082.

**Comment by marmarek** [comment] 2018-08-06 20:55
At the time you've tried (6 days ago) whonix-14 templates were only in templates-community-testing repository (which is disabled by default). They were pushed to templates-community 4 days ago, so it should work now. For instruction for testing versions see https://www.whonix.org/wiki/Qubes/Install/Testing

**Comment by adrelanos** [comment] 2020-03-01 18:52
Is this still an issue?

**Comment by andrewdavidwong** [comment] 2020-03-03 12:38
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-03-03 12:38 UTC
Labels: C: Whonix, C: mgmt, T: bug
