### ISSUE TITLE
Kernel modules can't compile natively on Debian (DKMS, Fedora gcc)

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3284] opened 2017-11-06 11:59 UTC
#### Affected TemplateVMs: 

debian-8
debian-9

---

### Steps to reproduce the behavior:

Install a dkms module like:
apt-get install wireguard-dkms

Website:
https://www.wireguard.com/install/

### Expected behavior:

Module compiles and installs

### Actual behavior:

> DKMS make.log for wireguard-0.0.20171017-1 for kernel 4.9.56-21.pvops.qubes.x86_64 (x86_64)
> cc1: error: incompatible gcc/plugin versions
> cc1: error: fail to initialize plugin ./scripts/gcc-plugins/latent_entropy_plugin.so

Make install fails.

### General notes:

Debian template was built using a Fedora-supplied version of gcc and Debian does not have this version in either stable, testing, etc. Failure apparently caused by gcc version mis-match.

---

**Comment by tasket** [comment] 2017-11-09 13:37
I think I have an example of this happening on a Fedora template also, on R3.2 as reported by a twitter user. Appears to be a more general issue with maintaining template self-consistency.

**Comment by marmarek** [comment] 2017-11-09 14:25
This is a duplicate of #2844 
See discussion there. Generally it looks like the best option (if you want to customize anything kernel related) is to use the one installed inside template, not provided by dom0. For 3.2 see https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm, for 4.0 it is even simpler because bootloader is already installed, it require only:

    qvm-prefs vmname kernel ''

**Closed by marmarek** 2017-11-09 14:25 UTC
Labels: bug, C: Debian, C: kernel
