### ISSUE TITLE
Qubes 4.0 bootloop

### ISSUE THREAD

**Issue by blkarchsux** [QubesOS/qubes-issues#3119] opened 2017-09-24 12:33 UTC
#### Qubes OS version (e.g., `R3.2`):
New release Qubes 4.0
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
boot up into OS
### Actual behavior:
all seems to boot into new system install as in 3.2 however is looping and restarting the boot up process restarting the machine
### Steps to reproduce the behavior:
clean new install of qubes 4.0 restart, all works fine until last step system reboots instead of running
### General notes:
alls aspects of the install went smoothly, password screen and progress bar appear normal, just restarts to the first menu, qubes or advanced options etc, continual loop in the process..........I run Qubes 3.2 normally, as my primary OS for both personal an business and the boot process is seamless on both 3.2 and 4.0  though with 4.0 its looping on the last step....so havent been ably to test drive it yet......................looking forward as qubes is the only secure stable os I trust for both stability, functionality and security............plus its fun to work with

---

**Comment by marmarek** [comment] 2017-09-24 13:14
Duplicate of #2953

**Closed by marmarek** 2017-09-24 13:14 UTC
Labels: duplicate
