### ISSUE TITLE
If I switch to Russian keyboard, no way to unlock XScreenSaver

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6543] opened 2021-04-19 21:30 UTC
### Qubes OS version:
R4.0

### Affected component(s) or functionality:
XScreenSaver

---

### Steps to reproduce the behavior:/
- Set XScreenSaver to lock screen with a password having an English letter.
- Switch using XFCE (the keyboard layout switcher panel widget) keyboard layout to Russian.
- Lock screen.

### Expected or desired behavior:
Switching to English (or other "main") keyboard layout when unlocking screensaver.

### Actual behavior:
- There is no way to unlock because you can type only Russian characters.
- The only way to make system work again is hard poweroff.

### General notes:

---

**Comment by andrewdavidwong** [comment] 2021-04-19 21:47
Duplicate of #3862

**Comment by andrewdavidwong** [comment] 2021-04-19 21:48
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2021-04-19 21:48 UTC
Labels: C: desktop-linux, P: default, R: duplicate, T: bug

**Comment by vporton** [comment] 2021-04-19 22:29
I have this behavior in #6543 but it happens _only_ if I switch keyboard layout (e.g. to Russian) before locking. Is this the only bug cause?

**Comment by andrewdavidwong** [comment] 2021-04-19 22:56
> I have this behavior in #6543 but it happens _only_ if I switch keyboard layout (e.g. to Russian) before locking. Is this the only bug cause?

Sorry, I can't understand what you're asking. Try rephrasing?

**Comment by vporton** [comment] 2021-04-19 23:02
> > I have this behavior in #6543 but it happens _only_ if I switch keyboard layout (e.g. to Russian) before locking. Is this the only bug cause?
> 
> Sorry, I can't understand what you're asking. Try rephrasing?
> 
> If you're asking a question about #3862, please comment on that issue instead.

I say that I confirm this bug in R4.0 but amend the report with the fact that (for me) the bug appears _only_ if I switched keyboard layout.

**Comment by andrewdavidwong** [comment] 2021-04-19 23:35
> > > I have this behavior in #6543 but it happens _only_ if I switch keyboard layout (e.g. to Russian) before locking. Is this the only bug cause?
> > 
> > 
> > Sorry, I can't understand what you're asking. Try rephrasing?
> > If you're asking a question about #3862, please comment on that issue instead.
> 
> I say that I confirm this bug in R4.0 but amend the report with the fact that (for me) the bug appears _only_ if I switched keyboard layout.

Ah, I see. I think that still means that this is a duplicate of #3862 (in which case any further comments should go there).

Of course, if these turn out not to be duplicate issues, we can reopen this one.
