### ISSUE TITLE
Document `kernel-next` for hardware enablement troubleshooting

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4495] opened 2018-11-09 19:34 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

dom0 sound (not really sure what component this is; feel free to edit)

---

### Steps to reproduce the behavior:

1. Have a System76 Oryx Pro
2. Install Qubes
3. Try to play something with audio

### Expected behavior:

Sound works.

### Actual behavior:

No sound output is possible.

### General notes:

Here's `aplay -L` in dom0:

```
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
    Default ALSA Output (currently PulseAudio Sound Server)
sysdefault:CARD=PCH
    HDA Intel PCH, ALC1220 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Digital
    IEC958 (S/PDIF) Digital Audio Output
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
hdmi:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 3
    HDMI Audio Output
hdmi:CARD=PCH,DEV=4
    HDA Intel PCH, HDMI 4
    HDMI Audio Output
```

`lspci | grep Audio` returns `00:1f.3 Audio device: Intel Corporation Device a348 (rev 10)`.

I decided to compare with my Pop!_OS installation (mostly just Ubuntu 18.04) since that has working audio. Here's `aplay -L` from there:

```
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=PCH
    HDA Intel PCH, ALC1220 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Digital
    IEC958 (S/PDIF) Digital Audio Output
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
hdmi:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 3
    HDMI Audio Output
hdmi:CARD=PCH,DEV=4
    HDA Intel PCH, HDMI 4
    HDMI Audio Output
dmix:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    Direct sample mixing device
dmix:CARD=PCH,DEV=1
    HDA Intel PCH, ALC1220 Digital
    Direct sample mixing device
dmix:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct sample mixing device
dmix:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Direct sample mixing device
dmix:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Direct sample mixing device
dmix:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Direct sample mixing device
dmix:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Direct sample mixing device
dsnoop:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=1
    HDA Intel PCH, ALC1220 Digital
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Direct sample snooping device
hw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=1
    HDA Intel PCH, ALC1220 Digital
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Direct hardware device without any conversions
plughw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC1220 Analog
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=1
    HDA Intel PCH, ALC1220 Digital
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Hardware device with all software conversions
```

As you can see there are _way_ more entries. I don't really understand what a lot of them are, but I suspected hardware compatibility issues so I booted a Fedora 25 Live CD since that's what dom0 is based on. Sure enough, audio didn't work in the live CD either.

Based on this I suspect that some component in dom0 is out of date and that's why my audio isn't working. `uname -a` in dom0 reports a modern kernel version so it _seems_ like the kernel should be new enough? What other components could be involved in this?

---

**Comment by andrewdavidwong** [comment] 2018-11-10 03:52
This issue is one or more of the following:
- Too localized
- A question that belongs on qubes-users
- A duplicate of/subsumed by/should instead be a "new/updated dom0 distro" issue

In case it helps, the standard replies for the first two are provided below.

-----

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

-----

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by strugee** [comment] 2018-11-12 00:12
Hey @andrewdavidwong, I can certainly understand why this got closed, but I don't think it really fits into those categories. What I'm asking for here is indeed actionable: a couple components in dom0 need to be backported for hardware enablement in a similar way to the kernel being backported. I don't know what _exactly_ those components are,  but I think the scope should be small enough that it's actionable. Note that this is much, much smaller than a request to update all of dom0.

It's also not a general support request, because the root cause of the issue is clear: the problem is not that a driver needs to be blacklisted, or that I need to tweak some config file etc. - it's that certain components are too old to support the hardware. (Note that I [did ask on qubes-users](https://groups.google.com/forum/#!topic/qubes-users/xDYngPWZrs8) and received a response that, while great, didn't suggest anything I hadn't already tried. This was also before I was able to gather the information present in this issue.)

That all being said, I do understand that this issue is uncomfortably close to a "please update dom0" issue, and very much exists in a gray area. I completely sympathize with the desire to keep a clean issue tracker and if you still want to leave it closed, I understand. Your hard work on Qubes is much appreciated!

**Comment by strugee** [comment] 2018-11-12 01:47
@marmarek `kernel-latest` fixed my audio! Thank you!

Can you reopen this bug as a documentation bug? I'll try and document this troubleshooting step if I find time.

**Comment by strugee** [comment] 2018-11-12 18:34
Filed QubesOS/qubes-doc#736.

**Closed** 2018-11-20 02:45 UTC
Labels: C: doc
