### ISSUE TITLE
Default XFCE

### ISSUE THREAD

**Issue by nasiralamreeki** [QubesOS/qubes-issues#7642] opened 2022-07-22 04:57 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Qubes OS is a resource intensive operating system due to running multiple VM's and by switching to a XFCE distro like Xubuntu could have drastic performance improvements for all users also fresher software.

### The value to a user, and who that user might be

**Comment by Minimalist73** [comment] 2022-07-22 08:54
dom0 is already based on Fedora xfce by default. You can also install xfce templates if you need it.

**Comment by andrewdavidwong** [comment] 2022-07-22 20:04
It appears that this issue is based on (a) false presupposition(s). Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2022-07-22 20:04 UTC
Labels: T: enhancement, P: default
