### ISSUE TITLE
No Qubes packages on https://mirror.linux.pizza/

### ISSUE THREAD

**Issue by eloquence** [QubesOS/qubes-issues#7101] opened 2021-12-02 22:30 UTC
### Qubes OS release

4.0.4

### Brief summary

Automatic installation of fedora-34 fails due to mirror now serving Qubes packages

### Steps to reproduce

Attempt to install fedora-34 template via `pkg.installed` Salt state

### Expected behavior

fedora-34 template installs

### Actual behavior

Salt state failure due to mirror not serving Qubes packages

```
                    [MIRROR] qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm: Status code: 404 for https://mirror.linux.pizza/qubes-os.org/repo/yum/r4.0/templates-itl/rpm/qubes-templa
te-fedora-34-4.0.6-202110020209.noarch.rpm (IP: 89.187.185.163)
                    [MIRROR] qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm: Curl error (23): Failed writing received data to disk/application for https://mirrors.edge.kernel.org/qub
es/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm [Failure writing output to destination]
                    [FAILED] qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm: Curl error (23): Failed writing received data to disk/application for https://mirrors.edge.kernel.org/qub
es/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm [Failure writing output to destination]
```

**Comment by gonzalo-bulnes** [comment] 2021-12-02 22:44
There is a [report on the forum][post] that seems to indicate that's been the case since at least Oct. 24, 2021.

  [post]: https://forum.qubes-os.org/t/is-mirror-linux-pizza-a-qubes-legit-mirror/7194

**Comment by gonzalo-bulnes** [comment] 2021-12-02 23:40
I believe this is where the list of mirrors is defined:
https://github.com/QubesOS/qubes-linux-yum/blob/9c9bf4164b85147ac2063df50a047126575001b6/mirrors.list#L9

**Comment by marmarek** [comment] 2021-12-02 23:44
> [FAILED] qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm: Curl error (23): Failed writing received data to disk/application for https://mirrors.edge.kernel.org/qub
> es/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-34-4.0.6-202110020209.noarch.rpm [Failure writing output to destination]

While there is an issue with this particular mirror, it's just a warning about switching to another mirror. The actual failure reason is the one quoted above ("Failure writing output to destination"). Out of disk space in updatevm (sys-firewall by default)?

**Comment by gonzalo-bulnes** [comment] 2021-12-02 23:46
You're likely right @marmarek, we've increased the disc size and I'll confirm in a moment. :+1:

**Comment by gonzalo-bulnes** [comment] 2021-12-02 23:47
To be clear, the mirror may have been missing packages for some time, and that in itself doesn't break updates. It's the fact that it doesn't contain _any_ Qubes OS packages at the moment that was surprizing.

**Comment by gonzalo-bulnes** [comment] 2021-12-03 00:40
You surely knew it already @marmarek, but just confirming here for the record that you were right. The installation error was a due to insufficient disk space. The mirror does indeed not contain Qubes OS packages at this point, but that doesn't cause installations to fail, because DNF retries downloads using other mirrors when needed.

I have no context on the status of `mirror.linux.pizza`. The missing packages may be a temporary issue, or not. I'll leave to you to advise on next steps @marmarek (which may include closing the issue).

I'm happy to get in touch with the admin contacts of the mirror if that's useful, just let me now :slightly_smiling_face:

**Comment by eloquence** [comment] 2021-12-03 01:43
I should know by know that "is it diskspace? it's not diskspace. it was diskspace" is always the answer with template update issues. ;) Yes, please feel free to close if the 404ing mirror is harmless.

**Comment by andrewdavidwong** [comment] 2021-12-03 21:35
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2021-12-03 21:35 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2021-12-03 21:36
> I'm happy to get in touch with the admin contacts of the mirror if that's useful, just let me now

That would be nice, thanks!

**Comment by andrewdavidwong** [comment] 2021-12-03 21:43
> Yes, please feel free to close if the 404ing mirror is harmless.

Correct. Qubes OS is in no way dependent on any particular mirror being non-malicious or functional. In general, we assume that any given mirror could be malicious or broken. The only way mirrors affect Qubes is in terms of making packages *available*.

For example, if *all* mirrors were down or compromised, then that would be a problem insofar as there would be no sources from which to obtain updates, but it still wouldn't directly harm the security of Qubes, because Qubes won't accept non-validly-signed updates in any case. (It could *in*directly harm security insofar as software would go unpatched until some acceptable update source was found.)

If a particular mirror proves to be persistently problematic (e.g., down for a long time with no word from the operator), the only thing to be done on our side would be to remove it from our mirror lists. We have no ability to fix third-party mirrors, as that infrastructure is someone else's property.

**Comment by andrewdavidwong** [comment] 2021-12-03 21:54
I will say, however, that there's clearly a UX issue with these `[MIRROR]` messages (see #7072 for another recent example). These messages make sense to those who are familiar with how package mangers in general (and DNF in particular) work, but they're misleading to most "mainstream" users. This is closely related to the difference between *warnings* and *errors*, which a distinction most users don't make until it's pointed out to them, leading them to misinterpret the semantics of "warning" messages. In the long run, the solution is probably to move mainstream users to the GUI update tool rather than the command line (see https://github.com/QubesOS/qubes-posts/pull/79).

**Comment by gonzalo-bulnes** [comment] 2021-12-06 21:25
I sent a message to the mirror admin/s, and will comment here if/when I hear back :slightly_smiling_face:

**Comment by wioxjk** [comment] 2021-12-07 11:36
Hi,
admin of the linux.pizza mirror here. Below is a copy of the answer that was sent to @gonzalo-bulnes 👍 
```
Hi,
Thank you for your email.
We actually stopped mirroring QubesOS last year due to almost 0 traffic. We did notify Andrew about that and gave the reason (severe lack of storage space).
I can't really answer for why it was not removed in the OS, and it was only noticed recently.

However, since our hardware issues has since then been resolved (we finance this from our own pockets), we could absotely start syncing the mirror again for QubesOS.

```

**Comment by gonzalo-bulnes** [comment] 2021-12-07 12:25
Hi @wioxjk!

Thanks for replying so quickly! That makes complete sense to me, thank you for maintaining the mirror in the first place!

I can't talk for Andrew or the Qubes OS team, and they'll have better context to help you make the decision either way : )

Over to you @andrewdavidwong!

**Comment by DemiMarie** [comment] 2021-12-07 19:57
@wioxjk To echo @gonzalo-bulnes: Thanks for maintaining the mirror for as long as you did!

**Comment by andrewdavidwong** [comment] 2021-12-07 20:31
> We did notify Andrew about that and gave the reason (severe lack of storage space).

Strange, I never received any such notification.

> However, since our hardware issues has since then been resolved (we finance this from our own pockets), we could absotely start syncing the mirror again for QubesOS.

That would be great, thank you!

> thank you for maintaining the mirror in the first place!

Yes, thank you. :slightly_smiling_face:

**Comment by andrewdavidwong** [comment] 2021-12-08 21:13
> > We did notify Andrew about that and gave the reason (severe lack of storage space).
> 
> Strange, I never received any such notification.
> 

Oh, I just found the old email. Apparently it wasn't showing up in Thunderbird search results because it was encrypted. My mistake.

It looks like what happened was that Jonathan asked me to remove the linux.pizza mirror from the list, so I removed it in https://github.com/QubesOS/qubesos.github.io/commit/115d5e8eb05c5d0d3c213df0ed7eb20022fef307. However, it looks like Qubes OS doesn't update from this list, so mirror was only removed from the Qubes website, while Qubes OS itself continued to use it.

@marmarek, @woju: In order to avoid these kinds of desync issues in the future, can we have one master mirror list that's used by both the website and Qubes OS itself? Or, if that's not feasible, can we have some automation that keeps the two lists in sync?

**Comment by andrewdavidwong** [comment] 2021-12-11 19:48
Jonathan has informed me that the LinuxPizza mirror has resumed syncing with Qubes, so I've added it back to the website mirror list:

https://github.com/QubesOS/qubesos.github.io/commit/3acf3d6341042d0713d6a8c41c46ec9496da6e94

Thanks again!
