### ISSUE TITLE
qvm-usb won't attach usb to appvm

### ISSUE THREAD

**Issue by SamuelHentschel** [QubesOS/qubes-issues#3490] opened 2018-01-23 17:06 UTC
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

Dom0, sys-usb(?)

---

### Steps to reproduce the behavior:

1. Insert a USB
2. Find its descriptor with qvm-usb -l
3. Try to attach usb to a VM via qvm-usb -a <VM-name> <usb-descriptor>

### Expected behavior:

Should attach usb to the specified VM until I detach it.

### Actual behavior:

I get the following error message after trying to attach in the Dom0 terminal:
ERROR: Device attach failed: /usr/lib/qubes/usb-import: line 32: /sus/devices/platform/vhci_hcd/status: No such file or directoryNo unused port found!/usr/lib/qubes/usb-import: line 51: /sys/devices/platform/vhci_hcd/attach: No such file or directory.

### General notes:

This started after the most recent Dom0 updates.

---

**Comment by marmarek** [comment] 2018-01-23 17:28
Duplicate of #3455, fix already in testing repository

**Closed by marmarek** 2018-01-23 17:28 UTC

**Comment by SamuelHentschel** [comment] 2018-01-23 17:38
mamarek, thanks!  Didn't see that one when I was searching.  Check my most recent one, might also be related since its with qvm-usb again.
