### ISSUE TITLE
Qubes 4.0 (R4.0) YubiKey + LUKS support

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4338] opened 2018-09-25 12:32 UTC
### Qubes OS version:

Qubes 4.0 (R4.0)

### Affected component(s): 

LUKS.

---

### Steps to reproduce the behavior:

We can not integrate the YubiKey with LUKS.

### Expected behavior:

There is a Qubes module for YukiKey + LUKS support.

### Actual behavior:

There isn't :(

### General notes:

---

**Comment by andrewdavidwong** [comment] 2018-09-26 01:17
Duplicate of #2712

**Comment by andrewdavidwong** [comment] 2018-09-26 01:18
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-09-26 01:18 UTC
