### ISSUE TITLE
sudoers config missing in fedora-X-minimal templates

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#3407] opened 2017-12-18 01:09 UTC
#### Qubes OS version:

R4-RC3

#### Affected TemplateVMs: 

fedora-25-minimal
fedora-26-minimal

---

### Steps to reproduce the behavior:

install fedora template
open xterm
sudo date
get password prompt

### Expected behavior:

passwordless sudo

### Actual behavior:

no passwordless sudo

### General notes:

/etc/sudoers.d/qubes is missing after template install

---

**Comment by andrewdavidwong** [comment] 2017-12-18 07:01
This appears to be a duplicate of #3157. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-18 07:01 UTC
