### ISSUE TITLE
Installation: Anaconda: Not asking for VNC because we don't have a network

### ISSUE THREAD

**Issue by glenjennings** [QubesOS/qubes-issues#7490] opened 2022-05-04 14:38 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.0

### Brief summary

I do NOT have a computer/technical background and this is my first time trying to install any form of Linux OS. I'm just trying to install this OS on a remote dedicated server as it has the perfect threat model that I need for the server. I've tried my best to figure this out and I don't know what else to do and I am ready to give up because I'm mentally exhausted. I can't get past installation of the OS from ISO. Once the Installation process reaches the point when the Anaconda scripts start running it says 

Starting installer, one moment...
anaconda xx.xxx.xx for Qubes R4.0.1 started.
* installation log files are stored in /tmp during the installation
* shell is available on TTY2
* if the graphical installation interface fails to start, try again with the inst.text boot option to start text installation* when reporting a bug add logs from /tmp as a separate text/plain attachments
18:02:41 Not asking for VNC because we don't have a network
18:02:41 X startup failed, aborting installation
18:02:41 X startup failed, aborting installation
The installation cannot continue and the system will be rebooted. Press ENTER to continue

### Steps to reproduce

1.) Downloaded fresh Qubes OS 4.1.0 ISO from https://www.qubes-os.org/downloads/
2.) Verified the source using GPG detached signature
3.) Logged in to my remote dedicated server viewer using .jnlp KVM IPMI access
4.) Attached ISO to KVM IPMI virtual media
5.) Turned on dedicated server and selected the boot option manager
6.) Selected the option that had my virtual CD ISO to boot from
7.) Installation begins successfully and log information starts to flow on the screen
8.) That stage completes and the log says closing Plymouth
9.) The screen clears and a green bar shows up on the bottom of the black screen and the aforementioned pops-up on the screen saying that there's no network. Then it goes to a black screen and I've tried leaving it overnight and have to ultimately restart the computer and try installation again.

### Expected behavior

Qubes OS To install successfully

### Actual behavior

Qubes OS doesn't install

### System Configuration

CPU: Intel i7-7700(k) 4.2GHz
Mobo: Supermicro X11SSH-F
BIOS: Supermicro Version 2.7 (Most recent update)
GPU: Integrated Processor Graphics Intel® HD Graphics 630
Memory: 64GB DDR4 RAM 2400MHz
Storage: 4 - 500GB NVMe SSD (2 RAID0 Configured with a hardware Raid Controller)
Network: 1GBps Ethernet

### Attempts to Fix the Issue

* Verified system meets the minimum requirements (https://www.qubes-os.org/doc/system-requirements/)

* UEFI Boot, Legacy Boot, DUAL Boot (https://www.qubes-os.org/doc/installation-troubleshooting/#not-asking-for-vnc-because-we-dont-have-a-network--x-startup-failed-aborting-installation--pane-is-dead-error-during-installation)

* Disabled Secure Boot

* Ensured VT-D is Enabled

* Downloaded new ISO two additional times and re-attempted installation about 6-7 times

* Searched for answers in Qubes Forums, and tried asking and posting on my own in Qubes Forums

* Tried searching on the web for answers

### Web pages that referenced this issue that I read through trying to fix this myself

https://www.reddit.com/r/Qubes/comments/ppctr3/cannot_install_not_asking_for_vnc_because_we_dont/
https://www.reddit.com/r/Qubes/comments/bfhrpn/installation_doesnt_actually_install_or_install/
https://www.reddit.com/r/Qubes/comments/bfjtlf/installer_stuck/
https://forum.qubes-os.org/t/not-asking-for-vnc-becouse-we-dont-have-a-network/3164
https://bugzilla.redhat.com/show_bug.cgi?id=952801
https://groups.google.com/g/qubes-users/c/-5dFjugKzLY
https://forum.qubes-os.org/t/installation-failing-on-new-pc-the-installation-cannot-continue/5259/6
https://forum.qubes-os.org/t/qubes-installation-on-new-2-000-high-end-pc-takes-60-minutes-to-load/10917/8

And more...

**Comment by andrewdavidwong** [comment] 2022-05-04 18:42
It doesn't sound like your use case is supported. Please see:

https://www.qubes-os.org/faq/#can-i-install-qubes-in-a-virtual-machine-eg-on-vmware

https://www.qubes-os.org/doc/installation-guide/#installation-summary

**Comment by andrewdavidwong** [comment] 2022-05-04 18:42
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by marmarek** [comment] 2022-05-04 19:21
> I'm just trying to install this OS on a remote dedicated server

It doesn't sound like a virtual machine.

> Mobo: Supermicro X11SSH-F

@fepitre do you have experience with similar machines, especially the way IPMI works there?

**Comment by DemiMarie** [comment] 2022-05-04 22:51
@glenjennings Installing Qubes OS on a bare metal dedicated server should definitely work, so if it does not work, that is a bug.

**Comment by andrewdavidwong** [comment] 2022-05-05 05:40
> > I'm just trying to install this OS on a remote dedicated server
> 
> It doesn't sound like a virtual machine.
> 

I wasn't necessarily assuming it was a virtual machine. Rather, it sounded like it was *either* a virtual machine *or* required the installer to support some kind of network access (hence the two links).

This part, in particular, sounds like something virtualized:

> 3.) Logged in to my remote dedicated server viewer using .jnlp KVM IPMI access
> 4.) Attached ISO to KVM IPMI virtual media

But I freely admit that I know nothing about IPMI, so you guys say it should work, then it should work.

-----

> So the templates were there but I had no way of installing them (based on my limited knowledge and ability).

You shouldn't have to try to manually install the default templates yourself. They should already be there. It sounds like something went terribly wrong during the installation. (I'm not suggesting that you selected an incorrect option or something. After all, there shouldn't be a user option for creating a broken installation and, as far as I know, there isn't.)

> The "Not asking for VNC because we don't have a network" error message is what I believe, in my limited knowledge, causes the other problem I experienced and now I can't even get it to install at all to get back to the dom0-only environment because I think the Host had to do some finessing to get it to that point.

I thought that was normal, since (as my second link explains) the installer is intentionally offline.

**Comment by DemiMarie** [comment] 2022-05-05 05:56
> > 3.) Logged in to my remote dedicated server viewer using .jnlp KVM IPMI access
> > 4.) Attached ISO to KVM IPMI virtual media
> 
> But I freely admit that I know nothing about IPMI, so if you guys say it should work, then it should work.

In this context, “KVM” means “Keyboard, Video, and Mouse”, not “Kernel-based Virtual Machine”.

**Comment by deeplow** [comment] 2023-01-01 11:56
> * ID: fedora-34-xfce
>   Function: qvm.template_installed
>   Result: False
>   Comment: Failed to install template fedora-34-xfce. Additional info follows:
>   ERROR: [Errno 2] No such file or directory: '/etc/qubes-rpc/qubes.TemplateSearch'

This problem looks like https://github.com/QubesOS/qubes-issues/issues/7287 and it was caused by an outdated template, which did not include the new template search mechanism.

**Closed** 2024-12-07 14:05 UTC
Labels: T: bug, C: installer, P: default, affects-4.1, eol-4.1
