### ISSUE TITLE
Arch now updates to xorg-server 1.20.4-1 which breaks again the dependency in qubes-gui-agent-linux/archlinux/PKGBUILD

### ISSUE THREAD

**Issue by dadigi** [QubesOS/qubes-issues#4905] opened 2019-03-22 15:44 UTC
Arch now updates to xorg-server 1.20.4-1 which breaks again the dependency in qubes-gui-agent-linux/archlinux/PKGBUILD

_Originally posted by @dadigi in https://github.com/QubesOS/qubes-issues/issues/3908#issuecomment-475666414_

**Comment by andrewdavidwong** [comment] 2019-03-23 07:39
Duplicate of #3908

**Comment by andrewdavidwong** [comment] 2019-03-23 07:39
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-03-23 07:39 UTC
