### ISSUE TITLE
qubesctl state.sls qvm.usb-keyboard breaks pasting in Global Clipboard

### ISSUE THREAD

**Issue by pmaurer2000** [QubesOS/qubes-issues#8497] opened 2023-09-06 09:09 UTC
### Qubes OS release

4.2.0-alpha (R4.2)

### Brief summary

`qubesctl state.sls qvm.usb-keyboard`  breaks pasting in Global Clipboard

### Steps to reproduce

`qubesctl state.sls qvm.usb-keyboard` 

### Expected behavior and Actual behavior

The issue here is that `qubesctl state.sls qvm.usb-keyboard`  adds `sys-usb dom0 allow` to the `/etc/qubes.policy.d/50-config-input.policy`. This is, if I understand correctly, the [old qrexec policy format](https://www.qubes-os.org/news/2020/06/22/new-qrexec-policy-system/). After a reboot this breaks the qrexec policy parser and not process the rest of the policies, including for pasting in the global clipboard. I don't remember which line and I don't want to break my system again, but I remember some python code where it looks like it should catch an exception and move on and I was wondering why it doesn't.

### Proposed fix

I think adding `sys-usb dom0 allow` is incorrect. I don't know what would be correct.

**Comment by andrewdavidwong** [comment] 2023-09-06 10:16
Duplicate of #8459

**Comment by andrewdavidwong** [comment] 2023-09-06 10:16
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-09-06 10:16 UTC
Labels: T: bug, P: default
