### ISSUE TITLE
Qubes Tray Icon Missing; Icon Error when Starting from dom0 CLI

### ISSUE THREAD

**Issue by imjustmatthew** [QubesOS/qubes-issues#5391] opened 2019-10-15 14:00 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes domain manager system tray icon is not appearing. When manually running with "qui-domains" in dom0, the program exits immediately with an error

**Brief summary**
$ qui-domains 
Traceback (most recent call last):
  File "/usr/bin/qui-domains", line 9, in <module>
    load_entry_point('qui==0.1', 'gui_scripts', 'qui-domains')()
  File "/usr/lib/python3.5/site-packages/qui/tray/domains.py", line 738, in main
    app.run()
  File "/usr/lib/python3.5/site-packages/qui/tray/domains.py", line 682, in run
    self.initialize_menu()
  File "/usr/lib/python3.5/site-packages/qui/tray/domains.py", line 657, in initialize_menu
    self.tray_menu.add(DomainMenuItem(None, self, self.icon_cache))
  File "/usr/lib/python3.5/site-packages/qui/tray/domains.py", line 304, in __init__
    self.name = self.decorator.name()
  File "/usr/lib/python3.5/site-packages/qui/decorators.py", line 150, in name
    namebox = DomainDecorator.VMName(self.vm)
  File "/usr/lib/python3.5/site-packages/qui/decorators.py", line 57, in __init__
    self.outdated_icon = create_icon('outdated')
  File "/usr/lib/python3.5/site-packages/qui/decorators.py", line 279, in create_icon
    icon_dev = Gtk.IconTheme.get_default().load_icon(name, 16, 0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'outdated' not present in theme Adwaita (0)

This may be related to a recent update. I'm not sure why it would be trying to show an "outdated" icon. I may be able to look at these source files later, but for right now I wanted to get this "on the board" in case anyone else is seeing this issue.

**Comment by imjustmatthew** [comment] 2019-10-15 15:21
Appears to be related to the changes that closed #3716 

and this commit: 

https://github.com/QubesOS/qubes-desktop-linux-manager/commit/69fdd30a290b714db472805b10a4caf4c98be32d

**Comment by imjustmatthew** [comment] 2019-10-15 15:31
Interestingly the icon file actually seems to have been placed in this directory: /usr/share/icons/Adwaita/22x22/status/outdated.png

If I change line 57 from:
`self.outdated_icon = create_icon('outdated')`
to:
`self.outdated_icon = create_icon('starred')`
qui-domains can start without a problem.

**Comment by marmarta** [comment] 2019-10-28 14:37
what is the exact version of desktop-linux-manager you have (`rpm -qa|grep desktop-linux-manager` ) ? I have problems reproducing it (this error usually happens when there's some weird problem with local environment).

**Comment by imjustmatthew** [comment] 2019-10-29 13:30
```
[USER@dom0 ~]$ rpm -qa | grep desktop-linux-manager
qubes-desktop-linux-manager-4.0.22-1.fc25.noarch
```
This is the version I have installed right now and the issue still occurs if I revert back to the original version of line 57 in /usr/lib/python3.5/site-packages/qui/decorators.py:

`self.outdated_icon = create_icon('outdated')`

When I change that line to:

`self.outdated_icon = create_icon('starred')`

qui-domains will start (but obviously uses a star icon for qubes that need to reboot)

I think everything related to qui is "out of the box" in dom0. I've added SSH agent to qubes in the rpc policy, but I don't think I've made any other changes in dom0 on this install.

**Comment by marmarta** [comment] 2019-10-29 13:50
Hm, I'm guessing you have either a different theme set up, or Gtk got confused about the theme. I'm going to try to fix this by putting the icon in a less stupid place (nobody has to use Adwaita after all) :)

**Comment by marmarek** [comment] 2019-10-29 14:22
I think it's about icon theme, another tab in that settings window.

**Comment by imjustmatthew** [comment] 2019-10-29 15:45
> I think it's about icon theme, another tab in that settings window.

Ah, thanks. My icon theme is still the default Adwaita

**Comment by marmarta** [comment] 2019-11-13 00:10
Okay, I tried to replicate this exact error (not more generic "file not found" error) and it doesn't happen on any on my test systems. If you still have it, does running `gtk-update-icon-cache` improve it in any way? Does the file /usr/share/icons/Adwaita/22x22/status/outdated.png look like a normal image, viewable in image viewer of your choice?

**Comment by marmarta** [comment] 2019-11-13 00:21
5 minutes after saying I can't reproduce it, I reproduced it :) 
Magic helping command is `sudo gtk-update-icon-cache /usr/share/icons/Adwaita`

**Comment by marmarta** [comment] 2020-04-06 13:46
so, no more people reported this bug, the refresh of icon cache is in the post-install script and I cannot reproduce it without manually meddling with the icons directory, I'm going to close it, and if someone gets this again, please don't hesitate to report / reopen

**Closed by marmarta** 2020-04-06 13:46 UTC
Labels: C: manager/widget, P: default, T: bug
