### ISSUE TITLE
dom0 updates false positive

### ISSUE THREAD

**Issue by fullTalgoRythm** [QubesOS/qubes-issues#7919] opened 2022-11-28 21:22 UTC
### Qubes OS release

4.1

### Brief summary

Update icon appears for dom0 even though no updates are available.

### Steps to reproduce

This is most likely due to stale fc25 packages from R4.0 upgrade. Icon appears everytime dom0 update check cron job runs.

### Expected behavior

Update icon for dom0 appears only when updates available.

### Actual behavior

Update icon appears for dom0 even when no updates available. This hides actual update status. Updates can be run but nothing updates, update icon does go but will return next time cron job runs to check for dom0 updates.

-------------------------------------------------------------------------------

Running the update utility as below was helpful

> qubes-dom0-update --check-only --show-output

This reveals the problem likely caused by report of 'Obsoleting Packages'
```
Available updates: 
Fedora 32 - x86_64                              2.4 kB/s | 3.9 kB     00:01    
Fedora 32 - x86_64 - Updates                     26 kB/s | 3.9 kB     00:00    
Qubes Dom0 Repository (updates)                 2.6 kB/s | 2.7 kB     00:01    
Obsoleting Packages
.....
There are dom0 updates available
```
Looks like these should be ignored or otherwise marked as a maintenance job.

Options like _--clean_ and _--action=autoremove_ did not work.

Manually running updates revealed a further problem. The _--show-output --console_ options are helpful here to view the issue.

> sudo qubes-dom0-update --show-output --console

It appears that a list of obsolete packages then shows and a message claims that the packages were removed but nothing actually happens as you can run over and over with the same result. I'm not sure if this a problem with dnf or not. There was no y/n prompt shown but it did say 14 packages were removed each time.

I decided in the end to manually remove all the packages which actually did appear to do something with the usual messages indicating removal. This also appears to have fixed the output from _qubes-dom0-update --check-only_ which now shows correct result.

Might be useful to put some of the above infromation in the documentation so people can investigate and provide more details for an error report.

**Comment by andrewdavidwong** [comment] 2022-11-29 01:16
Looks like a duplicate (i.e., regression) of #2086 and/or #1511, but since those issues have been dormant for several years and several releases now, I'm somewhat hesitant to close this issue as a duplicate of (either or both of) them and reopen (either or both of) them, as the cause in this release may be different. @marmarek, do you have a preference or opinion on this?

**Comment by marmarek** [comment] 2022-11-29 03:12
What exactly packages are listed there? Is it similar to the list in [this comment](https://github.com/QubesOS/qubes-issues/issues/7503#issuecomment-1147941722)?

**Comment by coyotebush** [comment] 2023-09-23 18:34
Similar list on my machine, yes:
```
$ sudo qubes-dom0-update --console --show-output
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Fedora 32 - x86_64                               10 kB/s | 2.8 kB     00:00    
Fedora 32 - x86_64 - Updates                     10 kB/s | 2.8 kB     00:00    
Qubes Dom0 Repository (updates)                 5.8 kB/s | 2.7 kB     00:00    
Dependencies resolved.
================================================================================
 Package                     Arch        Version             Repository    Size
================================================================================
Removing dependent packages:
 python2-backports_abc       noarch      0.5-1.fc25          @System       30 k
 python2-futures             noarch      3.1.1-1.fc25        @System       91 k
 python2-lxml                x86_64      4.1.1-1.fc25        @System      4.5 M
 python2-msgpack             x86_64      0.4.8-1.fc25        @System      276 k
 python2-pycurl              x86_64      7.43.0-6.fc25       @System      891 k
 python2-pygpgme             x86_64      0.3-18.fc25         @System      306 k
 python2-pysocks             noarch      1.6.7-1.fc25        @System       79 k
 python2-requests            noarch      2.10.0-4.fc25       @System      369 k
 python2-singledispatch      noarch      3.4.0.3-5.fc25      @System       46 k
 python2-systemd             x86_64      234-5.1.fc25        @System      263 k
 python2-tornado             x86_64      4.4.2-1.fc25        @System      3.9 M
 python2-urllib3             noarch      1.15.1-3.fc25       @System      443 k
 python2-zmq                 x86_64      15.3.0-2.fc25       @System      1.5 M

Transaction Summary
================================================================================
Remove  13 Packages

Freed space: 13 M
DNF will only download packages for the transaction.
Complete!
No packages downloaded
No updates available
$ qubes-dom0-update --check-only --show-output
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Checking for dom0 updates...
Available updates: 
Fedora 32 - x86_64                              6.3 kB/s | 2.8 kB     00:00    
Fedora 32 - x86_64 - Updates                     10 kB/s | 2.8 kB     00:00    
Qubes Dom0 Repository (updates)                 5.9 kB/s | 2.7 kB     00:00    
Obsoleting Packages
fedora-obsolete-packages.noarch               32-44                      fedora 
    authselect-compat.x86_64                  1.2.1-1.fc32               @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-backports_abc.noarch              0.5-1.fc25                 @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-futures.noarch                    3.1.1-1.fc25               @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-lxml.x86_64                       4.1.1-1.fc25               @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-msgpack.x86_64                    0.4.8-1.fc25               @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-pycurl.x86_64                     7.43.0-6.fc25              @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-pygpgme.x86_64                    0.3-18.fc25                @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-pysocks.noarch                    1.6.7-1.fc25               @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-requests.noarch                   2.10.0-4.fc25              @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-singledispatch.noarch             3.4.0.3-5.fc25             @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-systemd.x86_64                    234-5.1.fc25               @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-urllib3.noarch                    1.15.1-3.fc25              @System
fedora-obsolete-packages.noarch               32-44                      fedora 
    python2-zmq.x86_64                        15.3.0-2.fc25              @System
fedora-obsolete-packages.noarch               32-57                      updates
    authselect-compat.x86_64                  1.2.1-1.fc32               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-backports_abc.noarch              0.5-1.fc25                 @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-futures.noarch                    3.1.1-1.fc25               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-lxml.x86_64                       4.1.1-1.fc25               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-msgpack.x86_64                    0.4.8-1.fc25               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-pycurl.x86_64                     7.43.0-6.fc25              @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-pygpgme.x86_64                    0.3-18.fc25                @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-pysocks.noarch                    1.6.7-1.fc25               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-requests.noarch                   2.10.0-4.fc25              @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-singledispatch.noarch             3.4.0.3-5.fc25             @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-systemd.x86_64                    234-5.1.fc25               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-tornado.x86_64                    4.4.2-1.fc25               @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-urllib3.noarch                    1.15.1-3.fc25              @System
fedora-obsolete-packages.noarch               32-57                      updates
    python2-zmq.x86_64                        15.3.0-2.fc25              @System
There are dom0 updates available
```
Similarly fixed with `sudo dnf remove python2`.

**Closed** 2024-12-07 14:28 UTC
Labels: T: bug, P: default, C: updates, affects-4.1, eol-4.1
