### ISSUE TITLE
Cannot start CUPS in qube based on Debian 12 template

### ISSUE THREAD

**Issue by b90g** [QubesOS/qubes-issues#8508] opened 2023-09-11 09:41 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2rc3

### Brief summary

I am not able to just start the cups service (in fedora38 xfce its not even installed)

maybe after changes discussed in #5179 

### Steps to reproduce

sudo systemctl status cups

### Expected behavior

Active: active (running) 

### Actual behavior

```

user@disp9578:~$ sudo systemctl status cups
○ cups.service - CUPS Scheduler
     Loaded: loaded (/lib/systemd/system/cups.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/cups.service.d
             └─30_qubes.conf
     Active: inactive (dead)
TriggeredBy: ○ cups.socket
             ○ cups.path
  Condition: start condition failed at Mon 2023-09-11 11:19:03 CEST; 1s ago
             └─ ConditionPathExists=/var/run/qubes-service/cups was not met
       Docs: man:cupsd(8)

Sep 11 11:09:46 disp9578 systemd[1]: cups.service - CUPS Scheduler was skipped because of an unmet condition check (ConditionPathExists=/var/run/qubes-service/cups).
Sep 11 11:19:03 disp9578 systemd[1]: cups.service - CUPS Scheduler was skipped because of an unmet condition check (ConditionPathExists=/var/run/qubes-service/cups).

```

### Workarround

```
user@disp9578:~$ sudo mkdir /var/run/qubes-service/cups
user@disp9578:~$ sudo systemctl start cups
user@disp9578:~$ sudo systemctl status cups
● cups.service - CUPS Scheduler
     Loaded: loaded (/lib/systemd/system/cups.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/cups.service.d
             └─30_qubes.conf
     Active: active (running) since Mon 2023-09-11 11:20:11 CEST; 2s ago
TriggeredBy: ● cups.socket
             ○ cups.path
       Docs: man:cupsd(8)
    Process: 4243 ExecStartPost=/usr/lib/qubes/init/control-printer-icon.sh (code=exited, status=0/SUCCESS)
   Main PID: 4242 (cupsd)
     Status: "Scheduler is running..."
      Tasks: 1 (limit: 4617)
     Memory: 2.0M
        CPU: 28ms
     CGroup: /system.slice/cups.service
             └─4242 /usr/sbin/cupsd -l

Sep 11 11:20:11 disp9578 systemd[1]: Starting cups.service - CUPS Scheduler...
Sep 11 11:20:11 disp9578 systemd[1]: Started cups.service - CUPS Scheduler.
```

**Comment by DemiMarie** [comment] 2023-09-11 20:55
This is by design.  To enable CUPS, use `qvm-service QUBENAME cups on` in dom0.

Closing as “not a bug” (the reported behavior is not a bug and is already working as intended).

**Comment by nereocystis** [comment] 2024-01-22 00:40
The behavior has changed from 4.1 to 4.2.
In 4.1, my templates and qubes worked with cups on HP. 
In 4.2, the printers disappeared without notice.
If this behavior is expected, then the upgrade documents need to be changed to reflect that.

**Comment by marmarek** [comment] 2024-01-23 13:34
The comment https://github.com/QubesOS/qubes-issues/issues/8508#issuecomment-1714565636 is accurate, it is expected behavior.

**Closed** 2024-01-23 13:46 UTC
Labels: T: bug, R: not applicable, C: Debian/Ubuntu, P: default, needs diagnosis, affects-4.2

**Comment by q4747** [comment] 2024-02-18 21:06
See related discussion/guide here: https://forum.qubes-os.org/t/how-to-get-a-usb-mfp-printer-scanner-working-in-r4-2/24520
