### ISSUE TITLE
QubesManager UI - Crash when deleting a qube - R4.1

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#6728] opened 2021-06-22 16:24 UTC
**Qubes OS version**

R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

Yes. everything is testing

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
QubesManager

**Affected component(s) or functionality**

QubesManager

**Brief summary**

QubesManager GUI crash when deleting a qube

**How Reproducible**

100%

**To Reproduce**

1. Clone sys-usb ( to "toto" qube )
2. From QubeManager GUI, delete "toto"

**Expected behavior**

"toto" qube have been deleted, and the QubesManager GUI is still open

**Actual behavior**

"toto" qube is deleted, but the QubesManager GUI crash. 
When launching it manually from dom0, it crash with the following error message:
"TypeError: invalid result from QubesTableModel.flags(), bool cannot be converted to PyQt5.QtCore.ItemFlags in this context. Aborted (core dumped)"

**Screenshots**

**Additional context**

**Solutions you've tried**

It is annoying but not blocking. Just relaunch the QubesManager GUI

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by andrewdavidwong** [comment] 2021-06-22 18:34
https://github.com/QubesOS/qubes-issues/issues/6697 is also about an action performed on a qube causing the Qube Manager to crash.

**Comment by EncryptedGiraffe** [comment] 2021-06-25 23:57
perhaps related to this? https://github.com/QubesOS/qubes-issues/issues/6495

**Comment by andrewdavidwong** [comment] 2021-06-26 08:31
Duplicate of #6495

**Comment by andrewdavidwong** [comment] 2021-06-26 08:31
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-06-26 08:31 UTC
Labels: C: manager/widget, P: default, T: bug, needs diagnosis, updates testing
