### ISSUE TITLE
[GUI] dom0 VM Admin window cannot be resized, can only be moved

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2546] opened 2016-12-30 08:35 UTC
#### Qubes OS version (e.g., `R3.2`):
3.2

After adding some columns, I wanted to enlarge the dom0 VM Admin window so that all columns are visible, but this is not possible, I can only move the window.

**Comment by andrewdavidwong** [comment] 2016-12-31 17:43
This will soon be deprecated by #2132. Given that we closed #1870 as a "duplicate" for this reason (though not strictly a duplicate), I think we should close this for the same reason. (This issue is more like a duplicate of #1870.)

**Closed by andrewdavidwong** 2016-12-31 17:43 UTC
