### ISSUE TITLE
Debian template files window still have additional windows operations buttons

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7371] opened 2022-03-23 15:56 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1
debian-11 template

### Brief summary
In debian template contrary to fedora gnome file manager have additional  _ , 'square' and x buttons, they are not vanished even after installing gnome-settings-daemon and recompiling schemas.

### Steps to reproduce
1.) Open Files in debian VM 
2.) Look at additional buttons

### Expected behavior
Additional buttons should be hidden just like in Fedora

### Actual behavior
There are additional buttons. More with screenshots and not working workaround in that topic: 
https://forum.qubes-os.org/t/how-to-remove-nautilus-extra-button-in-fedora-minimal/3904/5
Also overrides seems not work at all for focal

**Comment by andrewdavidwong** [comment] 2023-08-06 00:58
I see that the original report mentions that this affects 4.1. Reopening.

**Comment by andrewdavidwong** [comment] 2023-08-06 01:01
Duplicate of #2813

**Comment by andrewdavidwong** [comment] 2023-08-06 01:01
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-08-06 01:01 UTC
Labels: T: bug, C: Debian/Ubuntu, P: default, needs diagnosis
