### ISSUE TITLE
"Denied: whonix.SdwdateStatus" error message after DispVM has halted

### ISSUE THREAD

**Issue by mmeeyyaa** [QubesOS/qubes-issues#7013] opened 2021-10-26 13:49 UTC
### Qubes OS release
4.1.0-rc1

### Brief summary
Error message after closing Tor Browser running in a DispVM.

### Steps to reproduce
1. Start Tor Browser in a DispVM whonix-ws-16. 
2. Close Tor Browser.
3. Error message is displayed.

(note no other applications are running in the qube)

Hardware: CPU: Ryzen 4700u

### Expected behavior
Notification of:
Qube dispxxxx has halted.

### Actual behavior
![Issue1](https://user-images.githubusercontent.com/93199124/138890050-8774be94-a594-44ea-9378-421590bd8af1.png)

**Comment by adrelanos** [comment] 2021-12-11 13:32
Is the error message correct? Why would sys-whonix sdwdate status notify disp1639?
It's the other way around. The sdwdate-gui stub (no own GUI, running in background, just sending qrexec messages) runs in disp1639 which then notifies sys-whonix (sdwdate-gui-qubes "full" GUI (systray)").

@DemiMarie:
> Qubes OS emits a notification for any failed qrexec call, but one reason for a failure is that the destination qube has shut down in the meantime. This should be treated separately from a denial.

Sounds good.

**Comment by andrewdavidwong** [comment] 2021-12-11 20:31
From comments on https://github.com/QubesOS/qubes-issues/issues/7067:

@marmarek wrote:
> This is mostly a consequence (duplicate?) of https://phabricator.whonix.org/T930

**Comment by adrelanos** [comment] 2022-02-14 10:42
Yay! `whonix.SdwdateStatus * @anyvm @default deny notify=no` is functional indeed. I was happy to notice that this only silences the GUI popup but it's still visible in dom0 journalctl logs which makes this easier to debug just in case this ever being required.

> dom0 qrexec-policy-daemon[2739]: qrexec: target 'disp4674' does not exist, using @default instead
> dom0 qrexec-policy-daemon[2739]: qrexec: whonix.SdwdateStatus: sys-whonix -> disp4674: denied: denied by policy /etc/qubes/policy.d/80-whonix.policy:6

`/etc/qubes/policy.d/80-whonix.policy`

```
# service            arg source            target            action params

whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
whonix.SdwdateStatus  *  sys-whonix        @tag:anon-vm      allow autostart=no
whonix.SdwdateStatus  *  @anyvm            @default          deny notify=no
whonix.SdwdateStatus  *  @anyvm            @anyvm            deny

whonix.NewStatus      *  @tag:anon-vm      @tag:anon-gateway allow autostart=no
whonix.NewStatus      *  @tag:anon-vm      sys-whonix        allow autostart=no
whonix.NewStatus      *  @anyvm            @anyvm            deny

whonix.GatewayCommand *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  sys-whonix        @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  @anyvm            @anyvm            deny
```

Will send a pull request soon.
(On top of / after the related https://github.com/QubesOS/qubes-core-admin-addon-whonix/pull/13.)

**Comment by adrelanos** [comment] 2022-02-14 11:08
While this bug was fixed it opened a new bug during proper shutdown of `anon-whonix`:

> dom0 qrexec-policy-daemon[2739]: qrexec: whonix.SdwdateStatus: sys-whonix -> anon-whonix: denied: target {} is denied because it would require autostart

There's a difference between `sudo poweroff` in `anon-whonix` versus a DispVM just being killed (without "proper shutdown").

**Comment by adrelanos** [comment] 2022-02-14 11:27
Tried adding `notify=no`, even everywhere but that didn't help.

```
# service            arg source            target            action params

whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no notify=no
whonix.SdwdateStatus  *  sys-whonix        @tag:anon-vm      allow autostart=no notify=no
whonix.SdwdateStatus  *  @anyvm            @default          deny notify=no
whonix.SdwdateStatus  *  @anyvm            @anyvm            deny notify=no

whonix.NewStatus      *  @tag:anon-vm      @tag:anon-gateway allow autostart=no
whonix.NewStatus      *  @tag:anon-vm      sys-whonix        allow autostart=no
whonix.NewStatus      *  @anyvm            @anyvm            deny

whonix.GatewayCommand *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  sys-whonix        @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  @anyvm            @anyvm            deny
```

Still same issue.

> dom0 qrexec-policy-daemon[2739]: qrexec: whonix.SdwdateStatus: sys-whonix -> anon-whonix: denied: target {} is denied because it would require autostart

Seems like if Qubes qrexec policy rule `whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no notify=no` is matched, `whonix.SdwdateStatus: sys-whonix -> anon-whonix: denied: target {} is denied because it would require autostart` will be noticed and `notify=no` being ignored.

Following lines, specifically `whonix.NewStatus      *  @anyvm            @anyvm            deny` are seemingly not matched either. (Because if there was only line  `whonix.NewStatus      *  @anyvm            @anyvm            deny` then no GUI denied notification popups will be shown.)

Possible bug in dom0 `qrexec-policy-daemon`?

**Comment by marmarek** [comment] 2022-02-14 11:32
> will be noticed and `notify=no` being ignored.

Indeed, looks like a bug in qrexec-policy-daemon, will fix shortly.

**Comment by adrelanos** [comment] 2022-02-14 11:40
Great! Created https://github.com/QubesOS/qubes-issues/issues/7267 for it.

**Comment by adrelanos** [comment] 2022-02-14 12:06
I will continue to work on the pull request as if https://github.com/QubesOS/qubes-issues/issues/7267 was fixed. Proposed:

```
# service            arg source            target            action params

whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no notify=no
whonix.SdwdateStatus  *  sys-whonix        @tag:anon-vm      allow autostart=no notify=no
whonix.SdwdateStatus  *  @anyvm            @default          deny notify=no
whonix.SdwdateStatus  *  @anyvm            @anyvm            deny

whonix.NewStatus      *  @tag:anon-vm      @tag:anon-gateway allow autostart=no
whonix.NewStatus      *  @tag:anon-vm      sys-whonix        allow autostart=no
whonix.NewStatus      *  @anyvm            @anyvm            deny

whonix.GatewayCommand *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  sys-whonix        @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  @anyvm            @anyvm            deny
```

Line `whonix.SdwdateStatus  *  @anyvm            @default          deny notify=no` uses `notify=no`.

But line `whonix.SdwdateStatus  *  @anyvm            @anyvm            deny` does not use `notify=no`.

I am not totally sure if that makes sense or not but I tend to think it makes sense.

Why? Line `whonix.SdwdateStatus  *  @anyvm            @default          deny notify=no` is expected and there's a good reason (this issue) for using `notify=no`. That should cover this issue.

`whonix.SdwdateStatus  *  @anyvm            @anyvm            deny` would be unexpected. Therefore good if a GUI denied popup being shown would be good.

**Comment by marmarek** [comment] 2022-02-14 12:41
Maybe even better to refine `whonix.SdwdateStatus * @anyvm @default deny notify=no` into `whonix.SdwdateStatus * @tag:anon-gateway @default deny notify=no`, as such calls from non-whonix-gateway would be unexpected too?

**Comment by adrelanos** [comment] 2022-02-14 12:56
I forgot to mention. One day there might be a community maintained Kicksecure template.
(https://www.kicksecure.com/wiki/Qubes#Template)

I am actually using a Kicksecure template daily.
(https://www.kicksecure.com/wiki/Qubes)

But sdwdate-gui / qrexec policy isn't developed yet for the Kicksecure template. No idea yet how that would be implemented. Trying to avoid inventing another `qvm-tag` `kicksecure-vm`.

A Kicksecure App Qube might have its own Tor daemon (which sdwdate connects to) and would not be using `sys-whonix` for networking. A Kicksecure App Qube would much more likely use `sys-firewall` (or `sys-vpn`).

**Comment by adrelanos** [comment] 2022-02-15 15:09
> Maybe even better to refine `whonix.SdwdateStatus * @anyvm @default deny notify=no` into `whonix.SdwdateStatus * @tag:anon-gateway @default deny notify=no`, as such calls from non-whonix-gateway would be unexpected too?

Unexpected, yes. But if they happen, we'd rather know about it?

**Comment by adrelanos** [comment] 2022-02-15 16:05
Understood now. Good point. Added in git branch referenced here in this ticket.

----

Small off-topic but hopefully not a big deal:
While I am at it `whonix.GatewayCommand` could be restricted to `arg` being `restart`, `stop`, `showlog`. Is it possible to write these in one line such as `(restart|stop|showlog)`?

**Comment by marmarek** [comment] 2022-02-15 16:38
> Is it possible to write these in one line such as `(restart|stop|showlog)`?

No, only explicit values are supported, not even shell-style patterns - the only wildcard supported is `*`. We are considering broadening scope here, but it needs to be careful, considering typo in complex pattern more likely...

**Comment by adrelanos** [comment] 2022-02-15 16:41
Yes, sure. Security matters here. I wouldn't write a feature request for this but if the feature existed already, I think it should have been used.

**Comment by TNTBOMBOM** [comment] 2022-04-14 21:36
Installing Kicksecure inside Debian Template (Following [distro-morphing](https://www.kicksecure.com/wiki/Debian) instructions) the Appvm which is based on kicksecure template will give tons of the same error reported above: (The Appvm called I2P)

![kicksecurecallsyswhonix](https://user-images.githubusercontent.com/11895339/163480499-54b5b0ec-e932-4d67-b812-d42572295f5b.png)

Any operation using the terminal/command line like e.g remove or install something it will regenerate similar messages. 


(This can be reproduced in StandaloneVM based on Debian then changed to Kicksecure)

**Comment by adrelanos** [comment] 2022-04-15 17:06
> Installing Kicksecure inside Debian Template (Following [distro-morphing](https://www.kicksecure.com/wiki/Debian) instructions) the Appvm which is based on kicksecure template will give tons of the same error reported above: (The Appvm called I2P)
> 
> ![kicksecurecallsyswhonix](https://user-images.githubusercontent.com/11895339/163480499-54b5b0ec-e932-4d67-b812-d42572295f5b.png)
> 
> Any operation using the terminal/command line like e.g remove or install something it will regenerate similar messages.
> 
> (This can be reproduced in StandaloneVM based on Debian then changed to Kicksecure)

Separate, unrelated issue. Created https://github.com/QubesOS/qubes-issues/issues/7447 for it.

**Comment by adrelanos** [comment] 2023-10-24 10:33
> Pull request [QubesOS/qubes-core-admin-addon-whonix#14](https://github.com/QubesOS/qubes-core-admin-addon-whonix/pull/14) created just now which will fix this ticket.

This was merged along time ago.

I cannot reproduce this issue anymore and suggest to close it. Should someone still have this issue, please reopen.

**Closed as completed** 2023-10-24 21:25 UTC
Labels: C: core, ux, C: Whonix, P: default, diagnosed, affects-4.1, community template
