### ISSUE TITLE
Qubes-Whonix salt failing - sudo qubesctl state.sls qvm.anon-whonix dom0

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4082] opened 2018-07-15 15:33 UTC
### Qubes OS version:
R4
### Affected component(s): 
Qubes-Whonix

### Steps to reproduce the behavior:
    sudo qubesctl state.sls qvm.anon-whonix dom0

### Expected behavior:
Functional, anon-whonix created, no error messages.

### Actual behavior:

```
[WARNING ] /var/cache/salt/minion/extmods/states/ext_state_qvm.py:142: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  status = Status(retcode=1, result=False, stderr=err.message + '\n')

[ERROR   ] ====== ['present'] ======
[TEST] /usr/bin/qvm-create sys-whonix --class=AppVM --template=whonix-gw-14 --label=black --property=memory=500 

====== ['prefs'] ======
Virtual Machine does not exist!
[0;31mlocal:[0;0m
[0;32m----------[0;0m
    [0;32m      ID: template-whonix-ws-14[0;0m
    [0;32mFunction: pkg.installed[0;0m
    [0;32m    Name: qubes-template-whonix-ws-14[0;0m
    [0;32m  Result: True[0;0m
    [0;32m Comment: Package qubes-template-whonix-ws-14 is already installed[0;0m
    [0;32m Started: 17:18:42.784996[0;0m
    [0;32mDuration: 1189.348 ms[0;0m
[0;32m     Changes:   [0;0m
[0;1;33m----------[0;0m
    [0;1;33m      ID: whonix-ws-tag[0;0m
    [0;1;33mFunction: qvm.vm[0;0m
    [0;1;33m    Name: whonix-ws-14[0;0m
    [0;1;33m  Result: None[0;0m
    [0;1;33m Comment: ====== ['features'] ======
              
              
              ====== ['tags'] ======[0;0m
    [0;1;33m Started: 17:18:43.978506[0;0m
    [0;1;33mDuration: 83.463 ms[0;0m
[0;1;33m     Changes:   
              [0;36m----------[0;0m
              [0;36mqvm.features[0;0m:
                  [0;36m----------[0;0m
                  [0;36mqvm.features[0;0m:
                      [0;36m----------[0;0m
                      [0;36mwhonix-ws[0;0m:
                          [0;36m----------[0;0m
                          [0;36mnew[0;0m:
                              [0;32m1[0;0m
                          [0;36mold[0;0m:
                              [0;1;33mNone[0;0m
              [0;36mqvm.tags[0;0m:
                  [0;36m----------[0;0m
                  [0;36mqvm.tags[0;0m:
                      [0;36m----------[0;0m
                      [0;36mnew[0;0m:
                          [0;32m- created-by-dom0[0;0m
                          [0;32m- whonix-updatevm[0;0m
                      [0;36mold[0;0m:
                          [0;32m- created-by-dom0[0;0m[0;0m
[0;1;33m----------[0;0m
    [0;1;33m      ID: whonix-ws-update-policy[0;0m
    [0;1;33mFunction: file.prepend[0;0m
    [0;1;33m    Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy[0;0m
    [0;1;33m  Result: None[0;0m
    [0;1;33m Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is set to be updated[0;0m
    [0;1;33m Started: 17:18:44.070188[0;0m
    [0;1;33mDuration: 14.671 ms[0;0m
[0;1;33m     Changes:   
              [0;36m----------[0;0m
              [0;36mdiff[0;0m:
                  [0;32m--- [0;0m
                  [0;32m+++ [0;0m
                  [0;32m@@ -1,3 +1,5 @@[0;0m
                  [0;32m+$tag:whonix-updatevm $default allow,target=sys-whonix[0;0m
                  [0;32m+$tag:whonix-updatevm $anyvm deny[0;0m
                  [0;32m #$type:TemplateVM $default allow,target=sys-whonix[0;0m
                  [0;32m [0;0m
                  [0;32m [0;0m[0;0m
[0;32m----------[0;0m
    [0;32m      ID: whonix-get-date-policy[0;0m
    [0;32mFunction: file.prepend[0;0m
    [0;32m    Name: /etc/qubes-rpc/policy/qubes.GetDate[0;0m
    [0;32m  Result: True[0;0m
    [0;32m Comment: File /etc/qubes-rpc/policy/qubes.GetDate is in correct state[0;0m
    [0;32m Started: 17:18:44.085194[0;0m
    [0;32mDuration: 4.203 ms[0;0m
[0;32m     Changes:   [0;0m
[0;32m----------[0;0m
    [0;32m      ID: template-whonix-gw-14[0;0m
    [0;32mFunction: pkg.installed[0;0m
    [0;32m    Name: qubes-template-whonix-gw-14[0;0m
    [0;32m  Result: True[0;0m
    [0;32m Comment: Package qubes-template-whonix-gw-14 is already installed[0;0m
    [0;32m Started: 17:18:44.089707[0;0m
    [0;32mDuration: 1.274 ms[0;0m
[0;32m     Changes:   [0;0m
[0;1;33m----------[0;0m
    [0;1;33m      ID: whonix-gw-tag[0;0m
    [0;1;33mFunction: qvm.vm[0;0m
    [0;1;33m    Name: whonix-gw-14[0;0m
    [0;1;33m  Result: None[0;0m
    [0;1;33m Comment: ====== ['features'] ======
              
              
              ====== ['tags'] ======[0;0m
    [0;1;33m Started: 17:18:44.091298[0;0m
    [0;1;33mDuration: 85.366 ms[0;0m
[0;1;33m     Changes:   
              [0;36m----------[0;0m
              [0;36mqvm.features[0;0m:
                  [0;36m----------[0;0m
                  [0;36mqvm.features[0;0m:
                      [0;36m----------[0;0m
                      [0;36mwhonix-gw[0;0m:
                          [0;36m----------[0;0m
                          [0;36mnew[0;0m:
                              [0;32m1[0;0m
                          [0;36mold[0;0m:
                              [0;1;33mNone[0;0m
              [0;36mqvm.tags[0;0m:
                  [0;36m----------[0;0m
                  [0;36mqvm.tags[0;0m:
                      [0;36m----------[0;0m
                      [0;36mnew[0;0m:
                          [0;32m- created-by-dom0[0;0m
                          [0;32m- whonix-updatevm[0;0m
                      [0;36mold[0;0m:
                          [0;32m- created-by-dom0[0;0m[0;0m
[0;1;33m----------[0;0m
    [0;1;33m      ID: whonix-gw-update-policy[0;0m
    [0;1;33mFunction: file.prepend[0;0m
    [0;1;33m    Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy[0;0m
    [0;1;33m  Result: None[0;0m
    [0;1;33m Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is set to be updated[0;0m
    [0;1;33m Started: 17:18:44.177058[0;0m
    [0;1;33mDuration: 6.176 ms[0;0m
[0;1;33m     Changes:   
              [0;36m----------[0;0m
              [0;36mdiff[0;0m:
                  [0;32m--- [0;0m
                  [0;32m+++ [0;0m
                  [0;32m@@ -1,3 +1,5 @@[0;0m
                  [0;32m+$tag:whonix-updatevm $default allow,target=sys-whonix[0;0m
                  [0;32m+$tag:whonix-updatevm $anyvm deny[0;0m
                  [0;32m #$type:TemplateVM $default allow,target=sys-whonix[0;0m
                  [0;32m [0;0m
                  [0;32m [0;0m[0;0m
[0;1;33m----------[0;0m
    [0;1;33m      ID: sys-net[0;0m
    [0;1;33mFunction: qvm.exists[0;0m
    [0;1;33m  Result: None[0;0m
    [0;1;33m Comment: /usr/bin/qvm-check sys-net 
              VM sys-net exists None[0;0m
    [0;1;33m Started: 17:18:44.183552[0;0m
    [0;1;33mDuration: 615.089 ms[0;0m
[0;1;33m     Changes:   [0;0m
[0;1;33m----------[0;0m
    [0;1;33m      ID: sys-firewall[0;0m
    [0;1;33mFunction: qvm.exists[0;0m
    [0;1;33m  Result: None[0;0m
    [0;1;33m Comment: /usr/bin/qvm-check sys-firewall 
              VM sys-firewall exists None[0;0m
    [0;1;33m Started: 17:18:44.799317[0;0m
    [0;1;33mDuration: 564.042 ms[0;0m
[0;1;33m     Changes:   [0;0m
[0;31m----------[0;0m
    [0;31m      ID: sys-whonix[0;0m
    [0;31mFunction: qvm.vm[0;0m
    [0;31m  Result: False[0;0m
    [0;31m Comment: ====== ['present'] ======
              [TEST] /usr/bin/qvm-create sys-whonix --class=AppVM --template=whonix-gw-14 --label=black --property=memory=500 
              
              ====== ['prefs'] ======
              Virtual Machine does not exist![0;0m
    [0;31m Started: 17:18:45.369526[0;0m
    [0;31mDuration: 1246.814 ms[0;0m
[0;31m     Changes:   [0;0m
[0;31m----------[0;0m
    [0;31m      ID: whonix-ws-14-dvm[0;0m
    [0;31mFunction: qvm.vm[0;0m
    [0;31m  Result: False[0;0m
    [0;31m Comment: One or more requisite failed: qvm.sys-whonix.sys-whonix[0;0m
[0;31m     Changes:   [0;0m
[0;31m----------[0;0m
    [0;31m      ID: qvm-appmenus --update whonix-ws-dvm[0;0m
    [0;31mFunction: cmd.run[0;0m
    [0;31m  Result: False[0;0m
    [0;31m Comment: One or more requisite failed: qvm.whonix-ws-dvm.whonix-ws-14-dvm[0;0m
[0;31m     Changes:   [0;0m
[0;31m----------[0;0m
    [0;31m      ID: anon-whonix[0;0m
    [0;31mFunction: qvm.vm[0;0m
    [0;31m  Result: False[0;0m
    [0;31m Comment: One or more requisite failed: qvm.sys-whonix.sys-whonix, qvm.whonix-ws-dvm.whonix-ws-14-dvm[0;0m
[0;31m     Changes:   [0;0m
[0;36m
Summary for local
------------[0;0m
[0;32mSucceeded: 9[0;0m ([0;1;33munchanged=6[0;0m, [0;32mchanged=4[0;0m)
[0;31mFailed:    4[0;0m
[0;36m------------
Total states run:    13[0;0m
[0;36mTotal run time:   3.810 s[0;0m
DOM0 configuration failed, not continuing
```

### General notes:
Running `/usr/bin/qvm-create whonix-ws-14-dvm --class=AppVM --template=whonix-ws-14 --label=red` manually followed by repeating the original command (`sudo qubesctl state.sls qvm.anon-whonix dom0`) and no more failed salt states.

---
### Related issues:
https://github.com/QubesOS/qubes-issues/issues/3765

//cc @viq

**Comment by marmarek** [comment] 2018-07-15 15:45
There shouldn't be `dom0` at the end of this command, but I don't it cause the problem.

> [TEST] /usr/bin/qvm-create sys-whonix --class=AppVM --template=whonix-gw-14 --label=black --property=memory=500

This looks like it's running in test mode. It is enabled by `test=True` on command line, but I don't see it in your case... Anyway, could you retry without `dom0` at the end?

**Comment by adrelanos** [comment] 2018-07-15 17:54
Dropping the `dom0` and no more issue.

**Comment by andrewdavidwong** [comment] 2018-07-15 19:32
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-07-15 19:32 UTC
Labels: C: Whonix, C: mgmt, bug
