### ISSUE TITLE
Qubes Build20200726-4.1 libxenlight errors on MacBook A1706

### ISSUE THREAD

**Issue by alzer89** [QubesOS/qubes-issues#5983] opened 2020-08-05 06:04 UTC
### Qubes OS version:

Build20200726-4.1

### Affected component(s) or functionality:

libxenlight (possibly others)

---

### Steps to reproduce the behavior:

Installed Qubes OS, modified udev rules to hide Broadcom 43602 wifi card on boot to prevent freeze (MacBook Pro), rebooted, configured Qubes OS. Tried opening any VM. 

### Expected or desired behavior:

VMs open and PCI passthrough works. 

### Actual behavior:

“Libxenlight Failed to Create new Domain ‘(qube name)’, see /var/log/libvirt/libxl/libxl-driver.log for details”

### General notes:

Running on a MacBook Pro A1706 with no other OS installed. 

I am fully aware that this is a testing alpha with no support, however I would still like to be able to provide any information to the developers that may be of use. 

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://github.com/QubesOS/qubes-issues/issues/3125

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues/3125
However it is from version 3.2.

**Comment by iamahuman** [comment] 2020-08-05 10:45
>“Libxenlight Failed to Create new Domain ‘(qube name)’, see /var/log/libvirt/libxl/libxl-driver.log for details”

Can you boot the machine to another OS and post the contents of file `/var/log/libvirt/libxl/libxl-driver.log` on https://gist.github.com/?

**Comment by alzer89** [comment] 2020-08-05 11:05
<script src="https://gist.github.com/alzer89/c0628106370b8d52064a83bb7e7d306d.js"></script>

Would anything else help? (dmesg, maybe?
[libxl-driver.log](https://github.com/QubesOS/qubes-issues/files/5027884/libxl-driver.log)
)

**Comment by iamahuman** [comment] 2020-08-05 11:12
Can you use Qubes R4.0 on the same machibe? Then, this is likely a regression.

**Comment by alzer89** [comment] 2020-08-05 11:24
No.  I haven't been able to get any Qubes to run successfully on this machine.

**Comment by alzer89** [comment] 2020-08-05 11:25
HVM works WITHOUT attaching any devices (I can run Windows 10, other Linux distros and MacOS in an HVM), but PV or PVH doesn't work at all.

**Comment by iamahuman** [comment] 2020-08-05 11:37
Working HVM implies that Xen's PV itself *at least* is also working as well, since there is a PV domain hosting QEMU device model for each HVM.

Is the following table correct?

|PCI passthrough|HVM|PV|PVH|
|---|---|---|---|
|No|✔|❌ (as a Qube)<br>✔ (Only as stubdom)|❌|
|Yes|❌|❌|❌|

**Comment by alzer89** [comment] 2020-08-05 11:48
No.  PV does not work at all (at least when it is selected in the Qube Settings tab).  

Also, when trying to shut down a qube that isn't a standalone qube, it says that qubesd returned a zero exit status.  

I've included some extra logs, hoping they might be helpful.  
[dmesg.log](https://github.com/QubesOS/qubes-issues/files/5028071/dmesg.log)
[journalctl.log](https://github.com/QubesOS/qubes-issues/files/5028073/journalctl.log)

**Comment by marmarek** [comment] 2020-08-05 12:24
I think the issue is that every VM you start is connected to network, so requires sys-net running. And sys-net fails to start, so regardless of your test VM type, it fails to start too.
Try testing with a VM that has netvm set to none ("networking" option in graphical VM settings).
You can also check why sys-net doesn't start - try starting it directly and collect some info - its console log (`/var/log/xen/console/guest-sys-net.log`) and perhaps also `xl dmesg` output.

**Comment by alzer89** [comment] 2020-08-05 12:39
All template VMs go "starting..." -> "started" -> "halted" within the space of 5-7 seconds.  

All other VMs with networking set to (none) do the same thing.  

Standalone VMs with no networking and the virtualisation mode set to HVM work completely fine (apart from the fact that they have no access to the outside world).  

Hopefully these help.
[guest-sys-net.log](https://github.com/QubesOS/qubes-issues/files/5028399/guest-sys-net.log)
[xl-dmesg.log](https://github.com/QubesOS/qubes-issues/files/5028405/xl-dmesg.log)

**Comment by marmarek** [comment] 2020-08-05 12:44
```
 mount: /sysroot: wrong fs type, bad option, bad superblock on /dev/xvda, missing codepage or helper program, or other error.
```
Looks like broken template. Can you switch to another one (debian for example)?

**Comment by alzer89** [comment] 2020-08-05 12:56
Sys-net starts as HVM (with no devices attached, I had to take its access to the Broadcom 43602 wifi card because it causes the entire machine to freeze) with fedora-32, debian-10 and archlinux as template.  

Sys-firewall returns "libxenlight failed to create new domain for 'sys-firewall'."

**Comment by andrewdavidwong** [comment] 2020-08-07 06:34
> #3125
> However it is from version 3.2.

I think you are misreading issue #3125. Even the original report says it's from 4.0, not 3.2.

In any case, [we do not typically have separate issues for the same bug in different versions of Qubes](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues). Instead, we have just one open issue on the milestone for the earliest affected version.

@marmarek, does this look like a duplicate of #3125?

**Closed** 2024-12-07 14:19 UTC
Labels: T: bug, C: Xen, P: default, hardware support, affects-4.1, eol-4.1
