### ISSUE TITLE
Touchscreen support in input proxy

### ISSUE THREAD

**Issue by atlhaua** [QubesOS/qubes-issues#2281] opened 2016-08-29 12:29 UTC
#### Qubes OS version : 

3.1

#### Affected TemplateVMs : 

all

### Expected behavior: 

Touchscreen used to work fine on the first installation.

### Actual behavior: 

after testing and tweaking the system for a while I decided to re-installed Qubes to have a fresh start. The only differences this time are that I have added a sys-usb service VM and that I have installed Qubes on an internal drive instead of an external one connected through USB.

### Steps to reproduce the behavior: 

explained above.

### General notes: 

I have found out that the touchscreen may be set up as an USB device and therefore isolated from dom0. This might explain why it is not working. Is there a way to make the touchscreen available to dom0 and the other VM's while keeping sys-usb?

```
[user@sys-usb /]$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
**Bus 002 Device 005: ID 03eb:8b03 Atmel Corp.** 
Bus 002 Device 004: ID 064e:9700 Suyin Corp. Asus Integrated Webcam
Bus 002 Device 003: ID 8087:07dc Intel Corp. 
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by andrewdavidwong** [comment] 2016-08-29 16:33
Yes, take a look at the USB documentation. You have to use either `qubes.InputKeyboard` or `qubes.InputMouse`, depending on which type of device your touchscreen is (probably the latter, but possibly both).

Please note that this type of query is not appropriate for `qubes-issues`. Please send any further replies to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.

**Comment by marmarek** [comment] 2016-08-30 14:43
Actually, input proxy do not support touchscreen devices currently. It shouldn't be hard do add it, but there are multiple higher priority tasks. But if anyone want to work on this, it require:
 - researching and adding appropriate data to initial proxy message: https://github.com/QubesOS/qubes-app-linux-input-proxy/blob/master/src/protocol.h (make sure to add new fields at the end of the structure - after "name" field, for protocol compatibility); this will most likely include min/max coordinates on each axis
 - make sure that dom0 part will still work even if remote sent no additional info - take a look at how "name" field was introduced
 - add support for appropriate message types (probably add `--touchscreen` option or such)
 - add appropriate qrexec service files, systemd units, and udev rules triggering them

It may be useful to examine the device using `evtest` first.

**Comment by atlhaua** [comment] 2017-02-21 11:03
Hi again,

I found a workaround solution assining the USB bus that manages the touchscreen to dom0 (on sys-usb services tab). The disadvantage in terms of security is that the other devices assigned to this bus (USB port and built-in camera are also assigned to dom0.

The news is that after upgrading to Qubes 3.2, this workaround solution does not work anymore. Thinking that it might be related to having Xfce instead of KDE I swaped the desktop environment to KDE as instructed in your help pages but it seems that was not the issue.
I do not know if this the right place for posting this issue but since marmarek reopened it, I thought I might as well update it  and enquire for a possible solution/workaround.
Thanks in advance.
Atlahua

**Comment by v6ak** [comment] 2017-05-13 17:07
I have a laptop that accidentally* has a touchscreen and I have looked at it.

Maybe the reason why @atlhaua has the issues it rd.qubes_hide_all_usb kernel parameter, which has appeared in a clean install.

I've also looked at the touch USB device. Command lsusb -l sees it as mouse. Probably the main difference from standard mouse is absolute coordinates vs. relative movements, plus maybe multipointer/multitouch support. There is some output from evtest: https://gist.github.com/v6ak/0732c1bc714473c65aa259e4a9e948f1

The input proxy seems to have at least some parts implemented. The sender part, well, at least produces some output (not sure if it is correct, but maybe sender part is rather cat with some header). The receiver part has --tablet support, but it does not seem to support it. The code seems to have some preliminary support, but there is comment absmax is missing. Maybe there is even ore missing.

I have also tried saving the proxy output to a file and then playing it to dom0, but it didn't work. Another surprising thing: When I tried to run receiver directly in dom0 on the saved file, it has always returned zero (even with --mouse or --keyboard). IIUC the code, it should have returned non-zero error code.

*) Well, touchscreen is by no means critical for me.

**Comment by marmarek** [comment] 2017-05-14 19:42
> but there is comment absmax is missing. Maybe there is even more missing.

Yes, exactly. According to your evtest output, this should be somehow added to the protocol handshake:
```
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   3134
      Min        0
      Max     4095
      Resolution      12
    Event code 1 (ABS_Y)
      Value    548
      Min        0
      Max     4095
      Resolution      21
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        9
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     4095
      Resolution      12
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     4095
      Resolution      21
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max 65535
```

The tricky part is that we want the initial message be a constant-size, but according to the above, there may be variable number of ranges. Maybe some arbitrary upper limit would work? Like 16, or even 8?

> The function validate_and_forward_event returns -1 on invalid EV_SYN or on unknown event, but it returns 1 on other ignored events, silently ignoring them. The caller function (i.e., process_events) considers any positive return value as success, so it is not propagated. Unfortunately, there does not seem to be any logging of skipped events.

Yes, this is partially intentional. For example if you attach some mouse+keyboard device but you only want to allow mouse (using qrexec policy), any other event would produce log entry, allowing to quickly fill up the whole disk...
Maybe we should add some `--verbose` / `--debug` option?

**Comment by v6ak** [comment] 2017-05-15 05:43
>Yes, this is partially intentional. For example if you attach some
>mouse+keyboard device but you only want to allow mouse (using qrexec
>policy), any other event would produce log entry, allowing to quickly
>fill up the whole disk...
>Maybe we should add some `--verbose` / `--debug` option?

This would be good. Plus some throttled logging (e.g., stop logging after 10 failures) might be also useful (but a bit controversial). Also, I understand that logging of input events can log something potentially sensitive (imagine typing your password on keyboard that was misdetected as a mouse…) I know this should be rare, but still… Maybe default logging could just warn like «Some key code from “sys-usb: some device” is not allowed, so it was skipped. This is either an attack or a bug. You can enable verbose logging to see more.».

**Comment by ncm** [comment] 2018-04-24 00:47
Please forgive me if this should be obvious, but how will we know when this fix will be in a "dom0 update", or if it has already arrived? Or, must we obtain it some other way? 

And, how do we enable it? dom0 Settings Manager?

Thank you.

**Comment by andrewdavidwong** [comment] 2018-04-24 02:29
@ncm: There should be an automated comment on this issue announcing when the package is available in each repo.

**Comment by andrewdavidwong** [comment] 2018-04-24 02:31
@ncm: I'm afraid I don't know how you'll enable it. I'll leave that for someone else to answer.

**Comment by ncm** [comment] 2018-04-25 23:28
Thank you, I will watch for the automated comment.
The touch screen on my ASUS UX501V shows up on the xfce panel's USB applet menu as "USBest Technology SiS HID Touch Controller". It shows up in sys-usb (actually sys-net, in my case) on lsusb as 0457:11d1 "Silicon Integrated Systems Corp", and also in dmesg, where it triggers loading the hid_multitouch kernel module.

**Comment by v6ak** [comment] 2018-04-26 12:42
I guess we will be able to enable it in a similar way as mouse, see https://www.qubes-os.org/doc/usb/ .

**Comment by marmarek** [comment] 2018-05-02 10:49
How to test: enable `qubes.InputTablet` service by editing `/etc/qubes-rpc/policy/qubes.InputTablet` file and adding `sys-usb dom0 allow` (or similar) line there.

**Comment by v6ak** [comment] 2018-05-02 19:41
When I try to use the `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing` command (even with --clean at the end) in R3.2 dom0, it does not found the package, just some kernel updates. What I am doing wrong?

I remember I have to wait some time, but ~9h could be enough.

I can find the package is published at https://ftp.qubes-os.org/repo/yum/r3.2/current-testing/dom0/fc23/rpm/qubes-input-proxy-1.0.11-1.fc23.x86_64.rpm , just my laptop does not see it.

**Comment by marmarek** [comment] 2018-05-02 19:55
Try now, I've triggered repository metadata update.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by v6ak** [comment] 2018-05-02 20:55
Thank you. I can confirm it works as expected (both installation and the proxy).

Some idea for @qubesos-bot: It would be IMHO ideal to push those messages when those packages are really available. Ideally, those can be just one comment (instead of those eight comments), grouped by OS version.

On the proxy:

* It works as expected. I got one hiccup, but it might have been caused by some dirt or so. If I get some more, I'll report it.
* It seems to be translated to mouse. I guess GUI daemon does not know touches.
* This might be useful for Android VMs, where mouse cursor desyncs. I haven't tested and I am not sure if it really helps.
* I haven't tested multimonitor setup (i.e., one monitor with touch layer and one without), which can be interesting. I'll test it.
* I have tested it just with R3.2 (not applicable to my R4 current installation, as it boots from USB).

**Comment by marmarek** [comment] 2018-05-02 21:13
> Some idea for @qubesos-bot: It would be IMHO ideal to push those messages when those packages are really available.

It mostly is the case, unless some error happens very late in the upload process (which was the case here).

> Ideally, those can be just one comment (instead of those eight comments), grouped by OS version.

I agree with the idea, but it's hard to do technically, because different packages are built in different VMs and there is no direct communication between them. Some idea could be just adding one comment - a link to updates-status repository, where you can find more details. More discussion here: #2494

Back to the topic:

> It seems to be translated to mouse. I guess GUI daemon does not know touches.

Yes, exactly.
It is also possible to connect the input proxy directly to the target VM, but it isn't straightforward:
 - install `qubes-input-proxy` package in the target VM (or its template)
 - setup udev rules to allow user access to /dev/input/event* (otherwise X server running as user won't have access to it) - this is probably caused by some misconfiguration of logind or such (similar to #3664 ?), but I don't have mental strength to debug it
 - setup qrexec policy in dom0 to redirect requests to that VM (you can also use `ask` to choose the target each time)

This of course means the device will be available only to that VM, but for some applications it's ok. Also, in this case, the mouse cursor (drawn by dom0) will not move accordingly. I've tried it with gimp and it works (gimp configuration required to actually use special features of the tablet).

**Comment by ncm** [comment] 2018-05-03 03:34
I find that there are packages `qubes-input-proxy-receiver` and `qubes-input-proxy-sender` in the Debian repository, claiming to be 1.0.11-1+deb9u1.

Packages `qubes-input-proxy` and `qubes-input-proxy-sender` are found in the Fedora repository, which claim to be version 1.0.11-1.

After doing a GUI dom0 update, rpm claims to have a `qubes-input-proxy` 1.0.11-1 installed, but not `qubes-input-proxy-sender`.

`qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-input-proxy-sender` appears to be willing to install the sender, but it is not clear that I want it in dom0. The text from `apt show qubes-input-proxy-receiver` and `-sender` seems to suggest I want `-sender` in `sys-usb` (or `sys-net`), where the gadget is, and non-sender in dom0, and nothing in the VMs where I want touch-scrolling to work. Correct?

Rebooting to try it.  But should it suffice to log out?

**Comment by v6ak** [comment] 2018-05-03 05:10
>The text from `apt show
>qubes-input-proxy-receiver` and `-sender` seems to suggest I want
>`-sender` in `sys-usb` (or `sys-net`), where the gadget is, and
>non-sender in dom0, and nothing in the VMs where I want touch-scrolling
>to work. Correct?

Exactly.

>Rebooting to try it.  But should it suffice to log out?

Logout will not do it, but reboot of whole system is not needed. You can just reboot sys-usb (a bit tricky on R3.2 – of you are unlucky, you will not have enough continuous memory and you won't be able to boot it again until you shutdown many other VMs). Probably sys-usb reboot is not needed, if you find the right service in sys-net (try systemctl | grep tablet), you can just start it and it will probably work.

**Comment by v6ak** [comment] 2018-05-03 05:44
You are trying to do it too much lowlevel. Try using the service. After running systemctl | grep tablet in USBVM, you will see the name (qubes-input-sender-tablet@eventN.service, where “N” will be some small number).

You should be able to start/restart/stop it or get its status then. Still in USBVM:

sudo systemctl start/restart/stop/status qubes-input-sender-tablet@eventN.service # pick the action you want and use the exact name of the service

That's it.

**Comment by ncm** [comment] 2018-05-03 17:01
I have backed out the changes I made based on the `README.md`. 
```
# ls /usr/lib/systemd/system/qubes-input*
qubes-input-sender-keyboard-mouse@.service
qubes-input-sender-keyboard@.service
qubes-input-sender-mouse@.service
# systemctl | grep tablet
# ls -l /dev/input/by-id | grep Touch
.... ->../event6
# udevadm info --query=property -name=/dev/input/event6 | grep INPUT
ID_INPUT=1
ID_INPUT_TOUCHSCREEN=1
ID_INPUT_HEIGHT_MM=195
ID_INPUT_WIDTH_MM=341
# pgrep -a proxy
699 input-proxy-sender event7
714 input-proxy-sender event8
# grep ID_INPUT /usr/bin/qubes-input-trigger
        if 'ID_INPUT_MOUSE' in udevreturn or \
                 'ID_INPUT_KEYBOARD' in udevreturn:
# udevadm trigger action=add -sysname-match=event6
```
The touchscreen does not announce itself as a mouse, but as `ID_INPUT_TOUCHSCREEN`. The `udevadm trigger` command has no detectable effect. There is no `qubes-input-sender-tablet` service in `/usr/lib/systemd/system`. Should I add one?

**Comment by marmarek** [comment] 2018-05-03 17:09
Looks like you don't have updated package. Have you restarted sys-usb after updating its template?

**Comment by ncm** [comment] 2018-05-03 17:15
```systemctl start qubes-input-sender-mouse@event6.service``` does start a process ```input-proxy-sender event6```, but I still don't get scrolling.
I have rebooted several times

**Comment by ncm** [comment] 2018-05-03 18:00
Thank you, the updates on `fedora-26` had not picked up the new version. (grr.)  Now I have `1.0.11-1`, and a tablet service file, but my usb VM still does not `input-proxy-sender /dev/input/event6` running.

`systemctl | grep tablet` reports about `qubes-input-sender-tablet@event6.service`: "loaded failed", but no mention in journalctl. `dmesg` has an audit line for it that says `res=failed`. `/usr/bin/qubes-input-trigger` still only looks for `ID_INPUT_MOUSE` and `ID_INPUT_KEYBOARD`, not `ID_INPUT_TOUCHSCREEN`, but in any case `udevadm trigger action=add -sysname-match=event6` still has no effect.

**Comment by v6ak** [comment] 2018-05-03 18:10
* ✔ You seem to have the correct version of proxysender in USBVM.
* ❔ Is the file /etc/qubes-rpc/policy/qubes.InputTablet automatically created in dom0? (If you have to create the file, you probably did not have the correct version in dom0…)
* ❔ Do you have correct policy? See https://github.com/QubesOS/qubes-issues/issues/2281#issuecomment-385937994 .

When you want to retry, just systemctl restart should be enough.

**Comment by ncm** [comment] 2018-05-03 21:33
It works now, thank you. 

Evidently `/usr/bin/qubes-input-trigger` is not used in starting up touch screen support. Is that intended only for hot-plugged devices?

**Comment by marmarek** [comment] 2018-05-03 21:41
> Evidently /usr/bin/qubes-input-trigger is not used in starting up touch screen support.

Looks like a missing part.

**Closed** 2018-05-03 22:47 UTC
Labels: C: other, P: minor, enhancement, help wanted, r3.2-buster-cur-test, r3.2-centos7-cur-test, r3.2-dom0-cur-test, r3.2-fc25-cur-test, r3.2-fc26-cur-test, r3.2-jessie-cur-test, r3.2-stretch-cur-test, r4.0-buster-cur-test, r4.0-centos7-cur-test, r4.0-dom0-cur-test, r4.0-fc26-cur-test, r4.0-jessie-cur-test, r4.0-stretch-cur-test

**Comment by v6ak** [comment] 2018-05-04 06:44
* Does not work well with screen rotation. But this is rather an issue of implementation of the screen rotation and I should probably adjust the script.
* Does not work well with multimonitor. Left monitor is external HDMI (no touchlayer), right monitor is internal (with touchlayer). The OS assumes the touch layer is over both monitors and scales touches accordingly: When I touch left half, it clicks the left monitor. When I touch the right half, it clicks the right monitor. Of course, the click happens somewhere else than my finger is, with the exception of the right edge.

Not sure if those issues are responsibility of the input proxy, but those are limitations I have found. Maybe it will be better with some other DE or with Q4 or some me newer Fedora.

**Comment by marmarek** [comment] 2018-05-04 10:54
Have you tried on non-Qubes system? I wonder if it's about some missing metadata, or that's how touchscreen in Linux in general works...

**Comment by v6ak** [comment] 2018-05-04 14:34
Not yet, I haven't had much time for that.

A bit more investigation: I've tried evdev on both dom0 and domU (without any touches) nd the only difference I see is missing INPUT_PROP_DIRECT in dom0. But a brief search does not suggest this should be crucial. Also, there is no identifier of the screen, it looks just as a flag.

Few thought on this issue:

* Configuration of the inputs seems as a responsibility of desktop environment, which is Xfce in my case.
* I believe there must be a mechanism that assigns the touchlayer to the screen. The laptop is not for Android (where OEM is expected to configure the system to work well with the hardware) and a clean Windows installation should be able to autodetect it. Maybe some records in ACPI table or some UEFI functions or so.
* AFAIK, Xfce is not known for a great support of touchscreens. So, Xfce is likely to break touchscreen-related functions.
*  The input proxy might break it by hiding some touchscreen identifier (or by prepending the VM name).

Next actions?

* I should try it with Fedora with both Gnome and Xfce in order to guess if we can have it working on Qubes. Well, it will probably take few days, I am busy/travelling now. Sorry.
* Maybe this should be considered when considering another desktop environment. At least if Qubes is intended to be touch-enabled OS.
* (Not sure if there is much to do with it withing the proxy, but we will see.)

**Comment by v6ak** [comment] 2018-05-08 18:04
So, I have tried it with Fedora 28 with Gnome Shell, Xfce spin and KDE spin. All of them were live versions without any update (I had disabled Wi-Fi and Bluetooth in BIOS for security reasons) running on the same laptop as Qubes. The external screen (non-touch) was a different one this time, but both monitors were connected by a HDMI/DVI cable.

With Xfce and KDE, it behaves the same – the touchscreen controls both screens. With Gnome Shell, I was unable to confuse it to behave incorrectly. The touchscreen controls just one screen and it is the correct one, regardless what screen is primary/secondary and if the screen is left/right. Note that it was rather a brief test, but it looks promising. Also, Gnome Shell seems to be relatively touch-ready in some other areas (swipe to scroll, virtual keyboard, hiding mouse cursor etc.). Some apps still aren't perfect (e.g., Firefox: inactive titlebar and inability to use virtual keyboard), but that probably needs to be handles case-by-case.

Short-term conclusion: So, it seems we cannot handle this in proxy at the moment. And if there is something to be handled in proxy, it would not probably bring any value at the moment. So, it is probably OK to release it with this limitation.

In long term: When considering a new desktop environment, touchscreen support might be one of the criteria. It might be an optional feature, but still worth to consider. Also, if the DE supports touchscreen with multiple screens well, it should be checked if Qubes does not break it. Is there any checklist for new desktop environments? Is there any discussion (or ongoing work) about changing desktop environment?

Workaround: In the meantime, we can use xinput map-to-output name-of-the-digitizer-as-you-see-in-xinput name-of-the-screen-as-you-see-in-xrandr.

**Comment by telepath** [comment] 2018-05-09 11:53
The touchscreen limitations are a general issue, and not related to the usb qube or usb proxy services.
Using a touchscreen without a usb qube has the same problems.

**Comment by v6ak** [comment] 2018-05-09 17:46
I agree the limitations currently come from DEs rather than input proxy. I have however created an umbrella issue for full touchscreen support, see https://github.com/QubesOS/qubes-issues/issues/3887 .

**Comment by telepath** [comment] 2018-05-10 09:29
I have Lenovo X1 Yoga with touchscreen and stylus, and can get neither to work with this update.
I installed the new qubes-input-proxy from testing in dom0 and sys-usb (qubes r4).
I suspect some further modification would be required for this to work?

**Comment by v6ak** [comment] 2018-05-10 09:38
1. Do you see the touchscreen when you run lsusb in sys-usb?
2. Do you see anything when running systemctl | grep tablet? If so, try restarting the service. It seems it does not autostart on boot (but it does when I suspend and resume my laptop), but you can start it manually. I guess it is the bug that marmarek has fixed (but the fix is not yet in current-testing).

**Comment by telepath** [comment] 2018-05-10 10:27
```
[user@sys-usb ~]$ lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 04f2:b5ce Chicony Electronics Co., Ltd 
Bus 002 Device 004: ID 8087:0a2b Intel Corp. 
Bus 002 Device 003: ID 1199:9079 Sierra Wireless, Inc. 
Bus 002 Device 002: ID 04f2:1286 Chicony Electronics Co., Ltd 
Bus 002 Device 006: ID 056a:5087 Wacom Co., Ltd 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd 
Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
[user@sys-usb ~]$ sudo systemctl | grep tablet
[user@sys-usb ~]$ sudo systemctl | grep input
qubes-input-sender-keyboard@event12.service                                        loaded active     running   Qubes input proxy sender (keyboard)                                 
qubes-input-sender-keyboard@event5.service                                         loaded active     running   Qubes input proxy sender (keyboard)                                 
qubes-input-sender-keyboard@event7.service                                         loaded active     running   Qubes input proxy sender (keyboard)                                 
qubes-input-sender-mouse@event8.service                                            loaded active     running   Qubes input proxy sender (mouse)                                    
qubes-input-sender-mouse@event9.service                                            loaded active     running   Qubes input proxy sender (mouse)                                    
system-qubes\x2dinput\x2dsender\x2dkeyboard.slice                                  loaded active     active    system-qubes\x2dinput\x2dsender\x2dkeyboard.slice                   
system-qubes\x2dinput\x2dsender\x2dmouse.slice                                     loaded active     active    system-qubes\x2dinput\x2dsender\x2dmouse.slice                      
```
There's only one USB controller, and the touchscreen is attached to the usb-qube (Wacom Co., Ltd).
But I suspect the service does not recognize it?

**Comment by v6ak** [comment] 2018-05-10 10:53
So, the touchscreen is here, but sys-usb does not try to forward its events for some reason.

1. What is the version of qubes-input-proxy-sender package in sys-usb VM?
2. Can you see any events from the touchscreen using evtest (as root)?

On May 10, 2018 12:28:01 PM GMT+02:00, Benjamin Richter <notifications@github.com> wrote:
>```
>[user@sys-usb ~]$ lsusb
>Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
>Bus 002 Device 005: ID 04f2:b5ce Chicony Electronics Co., Ltd 
>Bus 002 Device 004: ID 8087:0a2b Intel Corp. 
>Bus 002 Device 003: ID 1199:9079 Sierra Wireless, Inc. 
>Bus 002 Device 002: ID 04f2:1286 Chicony Electronics Co., Ltd 
>Bus 002 Device 006: ID 056a:5087 Wacom Co., Ltd 
>Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
>Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd 
>Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
>[user@sys-usb ~]$ sudo systemctl | grep tablet
>[user@sys-usb ~]$ sudo systemctl | grep input
>qubes-input-sender-keyboard@event12.service                            
>loaded active     running   Qubes input proxy sender (keyboard)        
>                        
>qubes-input-sender-keyboard@event5.service                             
>loaded active     running   Qubes input proxy sender (keyboard)        
>                        
>qubes-input-sender-keyboard@event7.service                             
>loaded active     running   Qubes input proxy sender (keyboard)        
>                        
>qubes-input-sender-mouse@event8.service                                
>loaded active     running   Qubes input proxy sender (mouse)           
>                        
>qubes-input-sender-mouse@event9.service                                
>loaded active     running   Qubes input proxy sender (mouse)           
>                        
>system-qubes\x2dinput\x2dsender\x2dkeyboard.slice                      
>loaded active     active   
>system-qubes\x2dinput\x2dsender\x2dkeyboard.slice                   
>system-qubes\x2dinput\x2dsender\x2dmouse.slice                         
>loaded active     active   
>system-qubes\x2dinput\x2dsender\x2dmouse.slice                      
>```
>There's only one USB controller, and the touchscreen is attached to the
>usb-qube (Wacom Co., Ltd).
>But I suspect the service does not recognize it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/2281#issuecomment-388016008

-- 
Sent from my fruity BlackBerry device with K-9 Mail. Please excuse my brevity.

**Comment by v6ak** [comment] 2018-05-10 11:32
Hmm, both look good to me, maybe marmarek will have some idea – at least about logs to look to.

**Comment by marmarek** [comment] 2018-05-14 10:42
Ckeck what udev thinks about those devices:
```
udevadm info -q all -n /dev/input/event10
udevadm info -q all -n /dev/input/event11
```

There should be `ID_INPUT_TOUCHSCREEN` or such. You can also try to manually start input proxy (in sys-usb): `systemctl start qubes-input-sender-tablet@event10.service` (and event11).

**Comment by telepath** [comment] 2018-05-14 17:26
@marmarek 
```
[user@sys-usb ~]$ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Power Button
/dev/input/event1:	Sleep Button
/dev/input/event2:	AT Translated Set 2 keyboard
/dev/input/event3:	ImExPS/2 Generic Explorer Mouse
/dev/input/event4:	PC Speaker
/dev/input/event5:	QEMU QEMU USB Tablet
/dev/input/event6:	Chicony USB Receiver
/dev/input/event7:	Chicony USB Receiver
/dev/input/event8:	Chicony USB Receiver
/dev/input/event9:	Chicony USB Receiver
/dev/input/event10:	Integrated Camera: Integrated C
/dev/input/event11:	Integrated Camera: Integrated C
/dev/input/event12:	Integrated Camera: Integrated C
/dev/input/event13:	Integrated Camera: Integrated C
/dev/input/event14:	Integrated Camera: Integrated C
/dev/input/event15:	Integrated Camera: Integrated C
/dev/input/event16:	Integrated Camera: Integrated C
/dev/input/event17:	Integrated Camera: Integrated C
/dev/input/event18:	Wacom Pen and multitouch sensor Finger
/dev/input/event19:	Wacom Pen and multitouch sensor Pen
Select the device event number [0-19]: ^C
[user@sys-usb ~]$ udevadm info -q all -n /dev/input/event18
P: /devices/pci0000:00/0000:00:06.0/usb2/2-10/2-10:1.0/0003:056A:5087.0030/input/input90/event18
N: input/event18
S: input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-event-if00
S: input/by-path/pci-0000:00:06.0-usb-0:10:1.0-event
E: DEVLINKS=/dev/input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-event-if00 /dev/input/by-path/pci-0000:00:06.0-usb-0:10:1.0-event
E: DEVNAME=/dev/input/event18
E: DEVPATH=/devices/pci0000:00/0000:00:06.0/usb2/2-10/2-10:1.0/0003:056A:5087.0030/input/input90/event18
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_HEIGHT_MM=174
E: ID_INPUT_TOUCHSCREEN=1
E: ID_INPUT_WIDTH_MM=310
E: ID_MODEL=Pen_and_multitouch_sensor
E: ID_MODEL_ENC=Pen\x20and\x20multitouch\x20sensor
E: ID_MODEL_ID=5087
E: ID_PATH=pci-0000:00:06.0-usb-0:10:1.0
E: ID_PATH_TAG=pci-0000_00_06_0-usb-0_10_1_0
E: ID_REVISION=0003
E: ID_SERIAL=Wacom_Co._Ltd._Pen_and_multitouch_sensor
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Wacom_Co._Ltd.
E: ID_VENDOR_ENC=Wacom\x20Co.\x2cLtd.
E: ID_VENDOR_ID=056a
E: LIBINPUT_DEVICE_GROUP=3/56a/5087:usb-0000:00:06.0-10
E: MAJOR=13
E: MINOR=82
E: SUBSYSTEM=input
E: USEC_INITIALIZED=104106826270

[user@sys-usb ~]$ udevadm info -q all -n /dev/input/event19
P: /devices/pci0000:00/0000:00:06.0/usb2/2-10/2-10:1.1/0003:056A:5087.0031/input/input92/event19
N: input/event19
S: input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-if01-event-mouse
S: input/by-path/pci-0000:00:06.0-usb-0:10:1.1-event-mouse
E: DEVLINKS=/dev/input/by-path/pci-0000:00:06.0-usb-0:10:1.1-event-mouse /dev/input/by-id/usb-Wacom_Co._Ltd._Pen_and_multitouch_sensor-if01-event-mouse
E: DEVNAME=/dev/input/event19
E: DEVPATH=/devices/pci0000:00/0000:00:06.0/usb2/2-10/2-10:1.1/0003:056A:5087.0031/input/input92/event19
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_HEIGHT_MM=174
E: ID_INPUT_TABLET=1
E: ID_INPUT_WIDTH_MM=310
E: ID_MODEL=Pen_and_multitouch_sensor
E: ID_MODEL_ENC=Pen\x20and\x20multitouch\x20sensor
E: ID_MODEL_ID=5087
E: ID_PATH=pci-0000:00:06.0-usb-0:10:1.1
E: ID_PATH_TAG=pci-0000_00_06_0-usb-0_10_1_1
E: ID_REVISION=0003
E: ID_SERIAL=Wacom_Co._Ltd._Pen_and_multitouch_sensor
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_VENDOR=Wacom_Co._Ltd.
E: ID_VENDOR_ENC=Wacom\x20Co.\x2cLtd.
E: ID_VENDOR_ID=056a
E: LIBINPUT_DEVICE_GROUP=3/56a/5087:usb-0000:00:06.0-10
E: MAJOR=13
E: MINOR=83
E: SUBSYSTEM=input
E: USEC_INITIALIZED=104107310426
```

**Comment by tlaurion** [comment] 2018-08-27 12:03
What is the current status on this?

**Comment by andrewdavidwong** [comment] 2018-08-28 01:06
> What is the current status on this?

The current status appears to be "closed as fixed."

**Comment by tlaurion** [comment] 2018-09-04 03:36
@andrewdavidwong [this](https://github.com/QubesOS/qubes-issues/issues/2281#issuecomment-385937994) should be part of documentation.

**Comment by andrewdavidwong** [comment] 2018-09-04 04:46
> [this](https://github.com/QubesOS/qubes-issues/issues/2281#issuecomment-385937994) should be part of documentation then. I confirm it works. :)

The documentation is a community effort. Please help us improve it by submitting a pull request:

https://www.qubes-os.org/doc/doc-guidelines/
