### ISSUE TITLE
Support for 4Kn Templates

### ISSUE THREAD

**Issue by 51lieal** [QubesOS/qubes-issues#7399] opened 2022-03-31 14:41 UTC
### The problem you're addressing (if any)

Take a look at here https://github.com/QubesOS/qubes-issues/issues/7398

### The value to a user, and who that user might be

Using 4Kn templates slightly increase vm performance.

Check this out to read full discussion https://forum.qubes-os.org/t/ssd-maximal-performance-native-sector-size-partition-alignment/10189

**Comment by marmarek** [comment] 2022-05-20 14:58
Duplicate of https://github.com/QubesOS/qubes-issues/issues/4974 ?

**Comment by DemiMarie** [comment] 2022-05-20 15:29
Yup, closing as a duplicate of #4974.

**Closed by DemiMarie** 2022-05-20 15:29 UTC
Labels: T: enhancement, C: templates, P: default, C: storage

**Comment by andrewdavidwong** [comment] 2022-05-21 10:11
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
