### ISSUE TITLE
R4.2-rc2: every domU shuts down immediately after start

### ISSUE THREAD

**Issue by csarn** [QubesOS/qubes-issues#8465] opened 2023-08-29 18:48 UTC
### Qubes OS release
R4.2-rc2

### Brief summary
all domU's (hvm, pvh, fedora and debian) cannot start.
For sys-net / sys-usb a SeaBIOS window pops up shortly, then it closes and I get the desktop notification that it has shutdown.

### Steps to reproduce
On my Thinkpad T430, after setting the BIOS to Legacy boot (see #8464 ), I installed Qubes R4.2-rc2.
No special settings were made (just keyboard layout, user password, use whole disk with automatic partitioning).
At first bootup, I can configure the templates to be created, and I selected the defaults plus auto-accept USB mouse & keyboard.

### Expected behavior
domU's can boot up completely. sys-net and sys-usb get started automatically.

### Actual behavior

When the templates were installed, already the first error message popped up about sys-net being unable to start.
After another reboot and logging in, I tried to start any domU, and all of them failed to start in the same way.
(debian, fedora, hvm, pvh)

In /var/log/libvirt/libxl/libxl-driver.log, there are error messages like this:
```
libxl_device.c:1200:device_backend_callback: Domain 19:unable to add device with path /local/domain/17/backend/vif/19/0
libxl_create.c:2000:domcreate_attach_devices: Domain 19:unable to add vif devices.
```

I found another issue with a similar message: #8292 
But that one mentioned something about SELinux fails, which I don't have. It seems my dom0 is not using SELinux.
There are some kernel messages in `dmesg` but they don't seem relevant (only informational, no errors, and unrelated to domU startup fails).

**Comment by csarn** [comment] 2023-08-29 18:59
I moved the SSD where Qubes is installed to another laptop (Thinkpad W530, so same generation and similar but not identical hardware), and the behaviour is the same. So faulty hardware is unlikely to be the culprit.

**Comment by marmarek** [comment] 2023-08-29 19:17
> `libxl_device.c:1200:device_backend_callback: Domain 19:unable to add device with path /local/domain/17/backend/vif/19/0`

This looks like an issue with netvm for that qube (sys-firewall in most cases). Is it running? Maybe you can restart it?
Does starting network-disconnected qube (like "vault" in default setup) works?

**Comment by csarn** [comment] 2023-08-30 06:28
sys-firewall cannot be running, and cannot be restarted, as it suffers from the same problem.

I tried with vault:
##  fedora-38-xfce, pvh
shuts down immediately. But no new entries in libxl-driver.log

##  debian-12-xfce, pvh
doesn't shutdown, but cannot do anything. 
can't start terminal
`qvm-run --pass-io vault ls` errors:
`qrexec-client.c:186:connect_unix_socket: connect: No such file or directory`

Running "open console in qube" in the qube manager tries to start a dispvm that then immediately shuts down, so no console for me.

Shutdown is not possible, but I can stop it via `xl destroy vault`

## fedora-38-xfce, hvm mode, fedora kernel
A window opens showing 4 lines of SeaBIOS output, nothing else. Then it closes and the VM is shutdown again

## debian-12-xfce, hvm mode, fedora kernel
Same behaviour as fedora-38-xfce in hvm mode

## debian-12-xfce, hvm mode, use qube provided kernel
A window opens, showing SeaBIOS output, then a GRUB bootloader, then some kernel messages:
```
Setting up swapspace version 1, size = <some amount of> bytes
UUID=<some uuid>
mount: mounting /dev/mapper/dmroot on /root failed: Invalid argument
Failed to mount /dev/mapper/dmroot as root file system.
```
It stays stuck at that point. I can stop it with `xl destroy vault`.

**Comment by marmarek** [comment] 2023-08-30 09:12
This looks like https://github.com/QubesOS/qubes-issues/issues/4974
Looks like your disk currently might be not compatible with qubes... I've seen a suggestion that some disks allow changing the sector size, maybe that will help?

**Comment by csarn** [comment] 2023-08-30 11:21
`fdisk -l` shows:
```
Disk model: CT500MX500SSD1
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```
So I am hit with this, right? https://github.com/QubesOS/qubes-issues/issues/4974#issuecomment-1287808999

**Comment by andrewdavidwong** [comment] 2023-08-30 20:36
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue (#4974). If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2023-08-30 20:37
Duplicate of #4974

**Closed by andrewdavidwong** 2023-08-30 20:36 UTC
Labels: T: bug, P: default, needs diagnosis, C: networking, affects-4.2

**Comment by macandchief** [comment] 2023-09-02 00:08
@csarn Where you choose the storage device to install Qubes, there is a "Custom" partitioning option. If you set that option and click "Done", there will be a further screen with different file system options. If you choose "btrfs" there and click automatically partitioning, it should work with logical/physical 512 bytes/4096 bytes sector size after install.

**Comment by csarn** [comment] 2023-09-02 16:34
Thanks, that worked!
