### ISSUE TITLE
Qubes onion mirror is late to have the latest packages

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#6352] opened 2021-01-19 16:06 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes onion mirror

**Brief summary**
Upgrades coming from clearnet mirror not presented as similar as onion mirror (or at least short time)

**How Reproducible**
once there are upgrades you can try

**To Reproduce**

1.  sudo apt update && sudo apt dist-upgrade
2. check with clearnet and onion version of qubes mirror

**Expected behavior**
Mirrors should have the latest packages in no time or at least within couple of minutes. 

**Actual behavior**
It take long time (i didnt calculate it but for surely not within couple of hours) to see it going to the onion mirror

**Comment by unman** [comment] 2021-01-19 16:21
On Tue, Jan 19, 2021 at 08:06:58AM -0800, TNT BOM BOM wrote:
> 
> 
> **Qubes OS version**
> R4.0
> 
> 
> **Affected component(s) or functionality**
> Qubes onion mirror
> 
> 
> 
> **Brief summary**
> Upgrades coming from clearnet mirror not presented as similar as onion mirror (or at least short time)
> 
> 
> 
> **How Reproducible**
> once there are upgrades you can try
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 1.  sudo apt update && sudo apt dist-upgrade
> 2. check with clearnet and onion version of qubes mirror
> 
> 
> **Expected behavior**
> Mirrors should have the latest packages in no time or at least within couple of minutes. 
> 
> 
> **Actual behavior**
> It take long time (i didnt calculate it but for surely not within couple of hours) to see it going to the onion mirror 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/QubesOS/qubes-issues/issues/6352

This is a classic "misplaced expectation" imo - the Debian mirrors update
at a minimum of 4 updates in 24 hours (gpg keyservers less frequently).
That's the schedule the onion mirror works to.
One difference is that the onion repo syncs at a random interval within
that period, so theoretically there may be a maximum gap between updates
of (I think) 10 hours.

**Comment by andrewdavidwong** [comment] 2021-01-20 22:16
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2021-01-20 22:16 UTC
Labels: P: default, T: bug

**Comment by TNTBOMBOM** [comment] 2021-01-21 19:17
not sure why its not an issue when the packages taking more than 1 hour 
to sync ? why its not an issue when the user of onion repo is hours 
outdated?

Andrew David Wong:
> Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
>

**Comment by andrewdavidwong** [comment] 2021-01-22 01:01
> not sure why its not an issue when the packages taking more than 1 hour
> to sync ? why its not an issue when the user of onion repo is hours
> outdated?

Because the infrastructure is intentionally designed for it to take that long, so it is working as intended. As @unman explained above:

> This is a classic "misplaced expectation" imo - the Debian mirrors update
> at a minimum of 4 updates in 24 hours (gpg keyservers less frequently).
> That's the schedule the onion mirror works to.
> One difference is that the onion repo syncs at a random interval within
> that period, so theoretically there may be a maximum gap between updates
> of (I think) 10 hours.

On the other hand, if you are suggesting that the infrastructure should be re-designed differently, then that's a separate question. I don't know enough to comment on that.

**Comment by TNTBOMBOM** [comment] 2021-01-23 09:40
> On the other hand, if you are suggesting that the infrastructure 
should be re-designed differently, then that's a separate question. I 
don't know enough to comment on that.

Yeah thats what im saying here, This is nonsense mechanism to have even 
10 minutes different not hours.



Andrew David Wong:
>> not sure why its not an issue when the packages taking more than 1 hour
>> to sync ? why its not an issue when the user of onion repo is hours
>> outdated?
> 
> Because the infrastructure is intentionally designed for it to take that long, so it is working as intended. As @unman explained above:
> 
>> This is a classic "misplaced expectation" imo - the Debian mirrors update
>> at a minimum of 4 updates in 24 hours (gpg keyservers less frequently).
>> That's the schedule the onion mirror works to.
>> One difference is that the onion repo syncs at a random interval within
>> that period, so theoretically there may be a maximum gap between updates
>> of (I think) 10 hours.
> 
> On the other hand, if you are suggesting that the infrastructure should be re-designed differently, then that's a separate question. I don't know enough to comment on that.
>

**Comment by unman** [comment] 2021-01-23 15:49
On Sat, Jan 23, 2021 at 01:40:12AM -0800, TNT BOM BOM wrote:
>  > On the other hand, if you are suggesting that the infrastructure 
> should be re-designed differently, then that's a separate question. I 
> don't know enough to comment on that.
> 
> Yeah thats what im saying here, This is nonsense mechanism to have even 
> 10 minutes different not hours.
> 
> 
> 

As I said, you don't seem to understand how mirrors generally work.
Since the syncing mechanism can take in excess of 10 minutes, your "even
10 minutes" is a non runner.
How much will you pay to have this level of service?

**Comment by TNTBOMBOM** [comment] 2021-01-25 21:11
Not sure whatever my answer is to how much will effect the issue im 
reporting which is the big time difference between clearnet and onion 
repos. Isnt the packages available on the clearnet server is the same 
server which is mirrored to onion?? If yes why would it take more than 1 
minute? (Also as far as im aware of qubes is hosted on fosshost so no 
charges or extra traffic or so)

unman:
> On Sat, Jan 23, 2021 at 01:40:12AM -0800, TNT BOM BOM wrote:
>>   > On the other hand, if you are suggesting that the infrastructure
>> should be re-designed differently, then that's a separate question. I
>> don't know enough to comment on that.
>>
>> Yeah thats what im saying here, This is nonsense mechanism to have even
>> 10 minutes different not hours.
>>
>>
>>
> 
> As I said, you don't seem to understand how mirrors generally work.
> Since the syncing mechanism can take in excess of 10 minutes, your "even
> 10 minutes" is a non runner.
> How much will you pay to have this level of service?
> 
>

**Comment by marmarek** [comment] 2021-01-25 23:03
The onion mirror is one of the mirrors serving the updates. We require mirrors to synchronize at least once every 24h, but most do that more often. We have a strict policy what we allow to run on the main updates server and it's basically "only simple services like basic HTTP(S) server and only only static files content". This does exclude running Tor process on the same system.
