### ISSUE TITLE
provide option in split-gpg to show exactly what task is requested

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5098] opened 2019-06-13 14:18 UTC
**The problem you're addressing (if any)**
split-gpg allows access for a defined time, and all requests in that time period are approved.

**Describe the solution you'd like**
Provide an option to set the gpg-split to approve a specific task only

Lets say I write an email to j...@email.ok. I click Send and I get a message asking me "would you like to encrypt/sign the message for j...@email.ok with your key ABC....?"
In this way I am restricting the comms in between the AppVMs for a single, specific task only.

**Where is the value to a user, and who might that user be?**
Provides greater control over precise task that gpg-split provides.

**Describe alternatives you've considered**

**Additional context**
Raised by scurge1tl on [qubes-users](https://www.mail-archive.com/qubes-users@googlegroups.com/msg28977.html)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/split-gpg

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Non duplicate:
#1835
#2443

**Comment by marmarek** [comment] 2019-06-13 14:39
The current architecture of split-gpg doesn't allow to do that reliably,
as there are many options that can influence the action. There is a
great potential of de-synchronizing such options handling that
potentially could allow bypassing the policy.

On the other hand, there is work-in-progress new implementation, based
on gpg agent protocol, that allows exactly this.
It's here:
https://github.com/hw42/qubes-app-linux-split-gpg2/
Tracking issue:
https://github.com/QubesOS/qubes-issues/issues/474

Based on the above, I think this is a duplicate of #474

BTW Encrypting message doesn't need access to private key, so it doesn't
need to even go through key-holding VM. Thus, in your example, you'll be
asked only about signing, as this is the only action there requiring
access to the private key.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment] 2019-06-14 05:32
> Based on the above, I think this is a duplicate of #474

Closing as a duplicate of #474. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-06-14 05:32 UTC
Labels: C: other, P: default, T: enhancement
