### ISSUE TITLE
IPv6 support in Qubes

### ISSUE THREAD

**Issue by tykling** [QubesOS/qubes-issues#3199] opened 2017-10-20 09:29 UTC
#### Qubes OS version:
3.2

#### Affected TemplateVMs: 
all

---

### Steps to reproduce the behavior:
try to use ipv6

### Expected behavior:
be able to use ipv6

### Actual behavior:
ipv6 is not supported in Qubes

### General notes:
Can we have ipv6 support please and thank you very much :)

---

**Comment by tykling** [comment] 2017-10-20 09:29
is there a possibility of directly funding development of this specific feature?

**Comment by marmarek** [comment] 2017-10-20 11:55
This is a duplicate of #718. There is a PoC already. I'm going to revive that code in coming weeks.

**Closed by marmarek** 2017-10-20 11:55 UTC
