### ISSUE TITLE
Windows Tools Fails to Install

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4924] opened 2019-03-28 07:44 UTC
Is it 

**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Windoze Tools

**Brief summary**
Qubes Windows tools does not install from within Windows 7 VM

**To Reproduce**
1. Install Windoze VM and Qubes Windows tools like https://www.qubes-os.org/doc/windows-tools/
2. See the iso on D:/ in Windoze
3. Click on it, start installer
4. See error:

```
Setup Failed
One or more issues caused the setup to fail.  Please fi the issues and then retry setup.  For more information see th Log file.
0x80070017 - Data error (cyclic redundancy check
```

Log file is long and there is no cut and paste from Windoze VM without Qubes Windosx tools.  

**Expected behavior**
I thought the iso would install drivers letting me make the VM fullscreen (or at least bigger)

**Actual behavior**
VM works but is small

**Screenshots**

**Additional context**
It's Windoze.

**Solutions you've tried**
If applicable, any solutions or workarounds you've already tried.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/windows-tools-3/#configuration
https://www.qubes-os.org/doc/windows-tools/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
??

**Comment by andrewdavidwong** [comment] 2019-03-29 02:10
Duplicate of #3585

**Comment by andrewdavidwong** [comment] 2019-03-29 02:10
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-03-29 02:10 UTC
Labels: P: default, T: bug
