### ISSUE TITLE
Qubes Manager Segfaulting LibQtGui

### ISSUE THREAD

**Issue by DeltaHeavy** [QubesOS/qubes-issues#1266] opened 2015-10-04 00:43 UTC
Occasionally, Qubes Manager under Dom0 segfaults and crashes. 

This happens sometimes when starting up an AppVM, especially when that AppVM reported "refused to give back requested memory."

The relevant `dmesg` output (with substitutions for the exact pointer hex values) is:
`qubes-manager[2600]: segfault at 24 ip $high_mem_hex_addr_1 sp $another_high_addr error 4 in LibQtGui.so.4.8.6[$high_mem+addr+$mem_offset]`

Qubes Release 3.0 with KDE on a Lenovo ThinkPad T440p

Let me know what further info you need. Thanks!

**Comment by marmarek** [comment] 2015-10-04 11:20
This is duplicate of #1110 , fix already in testing repository - should be in stable in about a week.

**Closed by marmarek** 2015-10-04 11:20 UTC
Labels: bug, C: qubes-manager, duplicate, P: major

**Comment by axon-qubes** [comment] 2015-10-07 07:32
@marmarek:
> This is duplicate of #1110 , fix already in testing repository - should be in stable in about a week.

Is it possible to download only this fix (and no other testing stuff)? If so, is there a `sudo qubes-dom0-update ...` command for that?

**Comment by marmarek** [comment] 2015-10-07 10:06
It is possible to download only that one package, but there are a couple
other fixes. 
`sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
qubes-core-dom0`

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
