### ISSUE TITLE
Saltstack is not pulling gpg keys in vm templates because 8082-proxy is not honored

### ISSUE THREAD

**Issue by 100111001** [QubesOS/qubes-issues#7104] opened 2021-12-05 18:21 UTC
### The problem you're addressing (if any)
After creating a repository in a vm template with saltstack, it's not usable because saltstack fails to download the gpg key. This is due to the fact that vm templates are using a proxy listening at port 8082 which is not used by saltstack for downloading keys. 

Example:

> add-repo:
>  pkgrepo.managed:
>   - name: deb http://repository.spotify.com stable non-free
>   - file: /etc/apt/sources.list.d/spotify-client.list
>   - humanname: spotify
>   - keyid: 5E3C45D7B312C643
>   - keyserver: keys.openpgpg.org
>   - gpgkey: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
>   - gpgcheck: 1

This state is supposed to create a spotify repository. Neither the parameter `gpgkey` nor `keyid/keyserver` are working.

After executing this state in a vm template, you get this error:

> ID: add-repo
> Function: pkgrepo.managed
> Name: deb http://repository.spotify.com stable non-free
> Result: False
> Comment: Failed to configure repo 'deb [trusted=yes] http://repository.spotify.com stable non-free': Error: key retrieval failed: Executing: /tmp/apt-key-gpghome.xyY44SvGz1/gpg.1.sh --batch --keyserver keys.openpgpg.org --logger-fd 1 --recv-keys 5E3C45D7B312C643
> **gpg: keyserver receive failed: Network is unreachable**

Of course there are workaround e.g. described here by @unman:
https://github.com/unman/notes/blob/master/gpg_in_templates

### The solution you'd like
Retrieving of keys should be possible by using saltstack.

### The value to a user, and who that user might be
Users don't need to use workarounds to create a fully workable template. Scripts to create a template can completely rely on saltstack.

**Comment by andrewdavidwong** [comment] 2021-12-07 20:22
Is this a duplicate of #4291, #4231, and/or #6730?

**Comment by 100111001** [comment] 2021-12-07 22:00
I agree that it's a duplicate of https://github.com/QubesOS/qubes-issues/issues/4231 (which is unfortunately closed). 
I don't agree to the comment of unman: https://github.com/QubesOS/qubes-issues/issues/4231#issuecomment-866745593 because without adding a functionality to setup a repository by salt, it requires non-saltstack "hacks" to add required gpg keys to a template. From my point of view a solution should be found to make saltstack usable, like proposed in:
https://github.com/QubesOS/qubes-issues/issues/4231#issuecomment-586695744
This solution is similar to what unman proposes and it's not saltstack based: https://github.com/QubesOS/qubes-issues/issues/6730

**Comment by andrewdavidwong** [comment] 2021-12-08 21:25
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-12-08 21:25 UTC
Labels: R: duplicate, T: enhancement, C: other, P: default

**Comment by DemiMarie** [comment] 2021-12-10 00:27
@100111001 This is a bug in GnuPG (which they marked as “won’t fix”).

**Comment by unman** [comment] 2021-12-10 11:00
On Thu, Dec 09, 2021 at 04:27:24PM -0800, Demi Marie Obenour wrote:
> @100111001 This is a bug in GnuPG (which they marked as ???won???t fix???).

I think it is actually a deficiency in salt repo state packaging - of all the
straightforward states for manipulating repositories, none allow the
user to specify options for the call to keyserver.
There is an easy 'proxy' state but that only applies to Mac and Windows.
Absent those, there are only workarounds, which can be used in salt with cmd
calls.
(It's been a while since I looked at this but I doubt position has
changed.)

**Comment by andrewdavidwong** [comment] 2021-12-11 20:15
> @andrewdavidwong from my point of view closing this issue isn't appropriate because the real duplicates are #4231 or #4291 which were closed without finding a solution.

This is just a matter of issue tracking system management. If two issues are truly duplicates, then they are, by definition, describing the same underlying thing (in this case, a bug). Since they're describing the same thing, one can't be "more of a duplicate" than the other. By default, we close the newer issue as a duplicate of the older issue, because the two issues weren't duplicates until the newer one was created. It was the creation of the newer issue that caused the two to become duplicates of each other, so it's appropriate (by default, allowing for exceptions) to close the newer issue as a duplicate. Useful content from the newer issue can simply be posted as a comment on the older issue. Otherwise, it would allow people to keep opening new duplicates in order to assert precedence over older issues, since some people care about "their" issue being the one that remains open. The exceptions in which the older issue is closed as a duplicate (rather than the newer issue) mainly come down to judgement calls about practical utility and what's more useful to the devs.

> The other issue stated by you is only a workaround: #6730
> The solution here is a command which needs to be called by salt stack as a native command instead of using the functionality of salt.

If you still feel strongly about this despite the comments from Demi and unman above, please comment on #4231, making your case for why you think it should be reopened, and we'll consider it.
