### ISSUE TITLE
Newly created HVMs not booting when NIC passtrough

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7859] opened 2022-11-04 07:55 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.1

### Brief summary
I need to attache my eth nic to Windows HVM, it working few months ago. Now when I attache my eth to new Windows HVM it won't boot.

### Steps to reproduce
1.) Create HVM not based on any template
2.) Attache eth NIC to it
3.) Start the VM from iso or installed system

### Expected behavior
VM will boot and I can use my NIC from it

### Actual behavior
VM not booting with no bootable drive error in Sea BIOS

**Comment by Szewcson** [comment] 2022-11-04 08:09
I can boot OpenBSD HVM created few months ago with attached eth, but I can't boot freshly created HVMs with installed Windows 10 or one in which I tried to install ubuntu from the ISO.

**Comment by Szewcson** [comment] 2022-11-04 11:30
Ok, found the workaround, and maybe it was not working before either. When I decrease amount of RAM from 4096 to 2048 HVM can boot with attached NIC. I think I saw some similar problem when reading about GPU pass-through so maybe my problem is a duplicate of some other issue.

**Comment by andrewdavidwong** [comment] 2022-11-05 20:39
> Ok, found the workaround, and maybe it was not working before either. When I decrease amount of RAM from 4096 to 2048 HVM can boot with attached NIC.

If I understand correctly, you have determined that there is no bug here, so I am closing this issue as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2022-11-05 20:39 UTC
Labels: T: bug, P: default

**Comment by DemiMarie** [comment] 2022-11-06 17:30
> > Ok, found the workaround, and maybe it was not working before either. When I decrease amount of RAM from 4096 to 2048 HVM can boot with attached NIC.
> 
> If I understand correctly, you have determined that there is no bug here, so I am closing this issue as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

This is a bug, but I believe it is a duplicate of #4321.

**Comment by andrewdavidwong** [comment] 2022-11-07 04:54
Thanks for the correction. Reclassified as a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If anyone would like to comment on the bug reported that was reported here, please comment on issue #4321 instead of here. On the other hand, if anyone believes that these are not really duplicate issues, then please leave a comment here briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2022-11-07 04:54
Thanks for the correction. Reclassified as a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If anyone would like to comment on the bug reported that was reported here, please comment on issue #4321 instead of here. On the other hand, if anyone believes that these are not really duplicate issues, then please leave a comment here briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
