### ISSUE TITLE
Documentation: Templates: Replace template creation guide for Ubuntu with a usable version

### ISSUE THREAD

**Issue by john-999** [QubesOS/qubes-issues#5572] opened 2020-01-11 23:15 UTC
The current guide for the creation of a Ubuntu template at https://www.qubes-os.org/doc/templates/ubuntu/ is not suited for most users of Ubuntu (it lacks details).

Replace it by the relevant part of this complete and working guide (I have successfully tested it for Ubuntu Bionic 18.04): https://denariustalk.org/index.php?/topic/305-guide-to-installing-qbuntu-ubuntu-1604-xenial-templatevm-in-qubes-402-rc1/

Given the popularity of Ubuntu, this will support wider adoption of QubesOS.

**Comment by mfp20** [comment] 2020-01-13 13:20
@john-999 write a detailed version and contribute to the project! Keep in mind that the more detail, the more effort is needed in time to refresh the docs once the project is rebased (ex: R3.2 -> R4.0). The reason why they support debian and fedora only, is that they have a person committed to keep those two updated (ie: maintainers). Have a look at the current docs: a lot of documentation is based on R3.2 and developers can't spend all their time in renovating it to move it from R3.2 to R4.0 ... if they spend time on docs, they can't update the core components... the result, in time, of detailed howtos is having the docs messed up.

I can confirm what is written now in that Ubuntu page: "The build for Ubuntu {xenial,bionic} is straightforward.". I've just built them without any struggle. The only thing I'm having issues with is Windows{7&&10}...

**Comment by brendanhoar** [comment] 2020-01-13 13:29
@mfp20 - see: https://github.com/elliotkillick/qvm-create-windows-qube

**Comment by mfp20** [comment] 2020-01-13 13:47
@brendanhoar thanks, I've already tried. The problem of that project is the lack of issue tracker and wiki. It's an headache to understand how to use it. Not the documented part! Install the tool itself and win7 install, are quick and easy: I've a windows7 VM installed smooth with all the nice goodies (disabled bloatware and spyware, added external software, QWT, seamless mode, and so on), but ... there are problems related to Qubes immaturity about running Windows, and the fact that Win7 will be EOL'ed within a few weeks (ie: no worth spending time to file the edges).
Windows10 instead is a nightmare: that tool isn't working at all. The SHA256 for win10x64.iso is wrong (because the tool can't download the ISO itself and downloading from the given MS link, makes a customized downloadable ISO, so there are multiple win10x64.iso files resulting from MS website...), and the automated install fails at first step because the answer file fails to answer the product key question... 
Manual Windows10 install is broken as well: you can install the OS, but the end result is a system without both PV drivers and ethernet connection. The only way to insert PV drivers in there is to pack the updated PV drivers in a custom ISO and boot the VM with a custom ISO cdrom emulation. To figure out the updated PV drivers (9.0.0) aren't working too: no net, no display resizing on windows resize, and so on... 

I started to write this message worry of going off-topic. 

And this is part of the (qvm-create-windows-qube) problem: it's a separate project, without it's own issue tracker and wiki. I suppose its author don't have enough time to fiddle with people, I understand, but we can't even open a dedicated issue here because an issue about that tool would be off topic here. So ... kind of stuck ... I just apologize to have gone off topic.

**Comment by brendanhoar** [comment] 2020-01-13 16:42
@mfp20 - I am going to try some experiments later this week with Elliot's script using a test laptop/test R4.0.x install. Perhaps some of the issues have been addressed.

PV storage drivers:

I've had very good stability using the now-current Xen PV storage drivers (vs. those included with QWT)...nice to attach storage to Windows by point and click or qvm-attach. 

I'll take a look to see if the most recent versions of the script to see if there's an easy change to propose which could add Xen's current PV drivers and to prevent QWT from overriding them.

**Comment by unman** [comment] 2020-01-14 02:00
On Mon, Jan 13, 2020 at 05:20:18AM -0800, mfp20 wrote:
> @john-999 write a detailed version and contribute to the project! Keep in mind that the more detail, the more effort is needed in time to refresh the docs once the project is rebased (ex: R3.2 -> R4.0). The reason why they support debian and fedora only, is that they have a person committed to keep those two updated (ie: maintainers). Have a look at the current docs: a lot of documentation is based on R3.2 and developers can't spend all their time in renovating it to move it from R3.2 to R4.0 ... if they spend time on docs, they can't update the core components... the result, in time, of detailed howtos is having the docs messed up.
> 
> I can confirm what is written now in that Ubuntu page: "The build for Ubuntu {xenial,bionic} is straightforward.". I've just built them without any struggle. The only thing I'm having issues with is Windows{7&&10}...
> 
> 

I dont think we *need* a detailed Ubuntu guide - most such guides just
duplicate the stuff that's in Qubes Builder pages.
I'd suggest making it clearer(if needed) that the base instructions are
in the Builder pages, rather than duplicate material on a specific
build. (If here, why not detailed instructions for *every* template?)

**Comment by brendanhoar** [comment] 2020-01-14 12:32
> @brendanhoar thanks, I've already tried. The problem of that project is the lack of issue tracker and wiki.

Issue tracker here: https://github.com/elliotkillick/qvm-create-windows-qube/issues

**Comment by unman** [comment] 2020-02-20 15:01
@john-999 @andrewdavidwong 
I've updated the Ubuntu instructions: I think enough to close this issue.
If the `qubes-builder` instructions need improvement, (and they may) that should be a separate task. As I said, I don't think we want, or need, detailed instructions for every individual template.
Please consider closing this issue.

**Closed** 2020-02-21 09:39 UTC
Labels: C: doc, P: default, T: enhancement, help wanted
