### ISSUE TITLE
Xfce Power Manager setting for "when laptop lid is closed" is ignored for "Plugged in".

### ISSUE THREAD

**Issue by dephekt** [QubesOS/qubes-issues#4505] opened 2018-11-14 13:35 UTC
### Qubes OS version:
Qubes release 4.0 (R4.0)

### Affected component(s): 

dom0 laptop power management

---

### Steps to reproduce the behavior:

Install Qubes 4.0-rc1 on a Librem 15v3. Open the dom0 Xfce Power Manager UI. Under the `General` tab, changed the `Plugged in` action for `When laptop lid is closed:` to `Switch off display`. Close the UI. Close the laptop lid.

### Expected behavior:

It is expected that setting the above action will cause the laptop to only switch the display off when closing the laptop lid. The system should not suspend/hibernate/lock the screen when the lid is closed. USB input devices and external displays should continue functioning.

### Actual behavior:

The system suspends when the lid is closed. USB disconnects, external display is killed.

### General notes:

The workaround is to use the same setting for "On battery:" as is used for "When plugged in:". Setting the "On battery:" action to "Switch off display" results in the system not suspending when plugged in. However, this comes at the cost of the system not suspending when it _is_ on battery.

My use case here is using a Librem 15v3 with Qubes for work, along with an HDMI KVM switch. When working from home, I use a KVM switch to share a monitor and USB input devices between my personal desktop and work laptop and the laptop is plugged in. When mobile, I would like the auto-suspend-on-lid-close functionality to work to preserve battery. Granted, I can still manually sleep the laptop before closing the lid, so this is more of a workflow annoyance.

I haven't tested this on other laptop hardware.

---

### Related issues:

This is related or similar to #2287, but it's been open for several years and is for an older release of Qubes. If this should simply have been added to that issue, then I apologize in advance. Also possibly related to #2360.

**Comment by marmarek** [comment] 2018-11-14 14:06
Does the system properly detect the power plugged in? Maybe the problem is here.

**Comment by andrewdavidwong** [comment] 2018-11-15 00:47
> This is related or similar to #2287, but it's been open for several years and is for an older release of Qubes. If this should simply have been added to that issue, then I apologize in advance.

Yes, this is a duplicate of that issue. As explained in the [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), we usually don't maintain separate issues for the same bug on different versions.

**Closed by andrewdavidwong** 2018-11-15 00:47 UTC
