### ISSUE TITLE
System instability using Ax200 wifi device, Xen reports IO_PAGE_FAULT

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#6564] opened 2021-04-27 22:03 UTC
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

Xen, dom0, sys-net, wifi

**Brief summary**

Errors repeat in _hypervisor.log_:
```
(XEN) AMD-Vi: IO_PAGE_FAULT: 0000:03:00.0 d1 addr fffffffdf8000000 flags 0x8 I
```
There is no sign of errors in the sys-net logs.

System is a Lenovo Thinkpad T14 with Ryzen Pro 4750U processor.

sys-net kernel: various versions, currently qubes-vm 5.11.15. Have tried debian-10, f32 and f33 templates.

Xen version is 4.14.1-3.

**How Reproducible**

Always recurs, but somewhat randomly in roughly a 6-48 hour range.

System is extremely stable (multi-week uptime, no forced reboots) when using sys-usb wifi adapters instead of built-in Intel Ax200.

**To Reproduce**

1. Configure sys-net to use Intel Ax200 pci device
2. Add `iwlwifi.disable_rxq=1` to sys-net `kernelopts`
3. Configure VMs to use sys-net

More intense network activity will cause error messages and system instability to occur more quickly.

**Expected behavior**

Stable operation >1 week, regardless of the amount of wifi activity.

**Actual behavior**

System becomes destabilized and crashes in various ways: Sudden reset, sudden power-off, CPU becoming bogged down and hot, qubesd not responding to qvm commands, etc. Stability rarely lasts for much more than a day.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by isodude** [comment] 2021-09-27 07:44
I see this on my system as well, got the same spec. I will give it a try to see if this is what messes with my resume/suspend issues and/or graphical bugs.

Have not seen any problems with stability though. No sudden resen/power-off/cpu bogged down/hot. Been running with it since may.

**Comment by isodude** [comment] 2021-09-27 07:49
Related? https://github.com/QubesOS/qubes-issues/issues/5615#issuecomment-774682682

**Comment by windgmbh** [comment] 2022-01-28 16:28
I can confirm that I have this issue, too; despite above mentioned `iwlwifi.disable_rxq=1' parameter set.

```
(XEN) AMD-Vi: IO_PAGE_FAULT: 0000:03:00.0 d5 addr fffffffdf8000100 flags 0x8 I
```

| | |
|:---|:---|
| CPU/ APU | AMD Ryzen Embedded V1605B (`Zen+`) |
| Network Controller | Intel Corporation Dual Band Wireless-AC 3168NGW |
| Qubes Release | R4.1.0-rc4 |
| Dom0 Kernel | `5.10.76-1.fc32.qubes.x86_64` |
| Xen | `4.14.3` |
| NetVM Distro | `fedora-34-minimal`|

I am so annoyed by this, that I have already thought about replacing the device entirely. 
Has anyone got any idea about something that could be expected to be more stable?

**Comment by isodude** [comment] 2022-01-31 07:31
Later Ax devices should be fine, from what I've heard. So, Ax210.

**Comment by brendanhoar** [comment] 2022-01-31 07:38
I'm having quite a bit of trouble with the AX210 in the GPD Pocket 3. So far all the tricks out there (renaming files, pulling newer firmware from intel, etc.) isn't working. Might be waiting on some changes in kernel 5.16 for this particular AX210 chip.

**Comment by windgmbh** [comment] 2022-01-31 21:13
I have browsed the kernel's driver documentation for a bit and found out about the driver's power management features. 

You can check, whether it is enabled and stop it with:

```bash
# iwconfig wls6 
[...]
    Power management:off
[...]

# iwconfig wls6 power off
```
As of now, I do not see any further `IO_PAGE_FAULT`s in `xl dmesg` until `sys-net` is rebooted.

**Comment by tasket** [comment] 2022-03-23 15:24
BTW it also works now without `iwlwifi.disable_rxq=1` so I don't know what effect that option has, if any.

**Comment by DemiMarie** [comment] 2022-03-23 15:26
That is definitely good news @tasket!  Looks like AX200 is submitting bogus DMA transactions.  Is there any way to report a bug with them upstream?

**Comment by windgmbh** [comment] 2022-03-23 15:33
> I have been using the AX200 extensively with the patch for about 3 weeks now with solid operation.

I do confirm that I did not have the usual stability issues for about the same time as well.

**Comment by isodude** [comment] 2022-03-23 16:21
No problems here.

**Comment by andrewdavidwong** [comment] 2022-03-23 21:40
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Closed by andrewdavidwong** 2022-03-23 21:40 UTC
Labels: T: bug, C: Xen, P: default, hardware support, C: networking
