### ISSUE TITLE
Kernel header

### ISSUE THREAD

**Issue by jdoify39fss** [QubesOS/qubes-issues#5454] opened 2019-11-08 21:43 UTC
**Qubes OS version**
R4.0.1

I don't know if I should classify it as a bug or not because I'm not sure. Below is the console output that I got after executing the apt-get upgrade command. I thinking it should be like this or is it a bug? Of course I have the latest updates at dom0.

https://0bin.net/paste/U86OSDriQ602xq6z#G1a1+Y5UcgpoIx2Mm1OpFqyck-CqWQ8KRQYEW5hjtJg

The same problem is on default debian 10 template.

In addition, I do not know why but not all emails reach the user group on Google because I wanted to send my question there but the message has not appeared there for about 8 hours (some decentralized forum would be nice). At GitHub there is a problem that everybody have to create new accounts every now and again because accounts created for temporary emails sometimes have problems and who today would give a private email to something that Microsoft bought.

**Comment by andrewdavidwong** [comment] 2019-11-09 03:21
> I don't know if I should classify it as a bug or not because I'm not sure. Below is the console output that I got after executing the apt-get upgrade command. I thinking it should be like this or is it a bug? Of course I have the latest updates at dom0.
> 
> https://0bin.net/paste/U86OSDriQ602xq6z#G1a1+Y5UcgpoIx2Mm1OpFqyck-CqWQ8KRQYEW5hjtJg

Which part? Please include the actual text here so that it will be searchable.

> In addition, I do not know why but not all emails reach the user group on Google because I wanted to send my question there but the message has not appeared there for about 8 hours

Explained here:
https://www.qubes-os.org/support/#do-not-send-duplicates

> (some decentralized forum would be nice).

Addressed here:
https://www.qubes-os.org/support/#mailing-lists-vs-forums

> At GitHub there is a problem that everybody have to create new accounts every now and again because accounts created for temporary emails sometimes have problems and who today would give a private email to something that Microsoft bought.

Partially addressed here:
https://www.qubes-os.org/faq/#why-do-you-use-github

This issue is not the appropriate place to discuss these matters. Please send an email to the appropriate mailing list if you wish to discuss them further.

**Comment by unman** [comment] 2020-02-03 10:15
@jdoify39fss Your console output has expired so I have no idea what your issue was.
Please post evidence of the problem here.
If you can no longer reproduce please close this issue.

**Comment by unman** [comment] 2020-02-15 14:23
@andrewdavidwong In absence of any idea *what* @jdoify39fss might have thought was wrong, please close.

**Comment by andrewdavidwong** [comment] 2020-02-17 10:03
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2020-02-17 10:03 UTC
Labels: C: Debian/Ubuntu, P: default, T: bug
