### ISSUE TITLE
Reboot loop or freeze on sys-usb start with newer Xen & dom0 kernels

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7637] opened 2022-07-21 14:51 UTC
### Qubes OS release

4.1

### Brief summary

With newer dom0 Linux kernels (all after 5.10.109-1 appear to be bad) and Xen 4.14.5 my Qubes OS runs into a reboot loop or freeze whenever `sys-usb` is started.

### Steps to reproduce

1. Boot Qubes OS 4.1.
2. Wait for `sys-usb` to autostart.

### Expected behavior

They boot.

### Actual behavior

The entire system reboots.

Unfortunately there are no logs in the journal and no kernel dump at `/sys/fs/pstore` (it's a non UEFI-laptop).

### Related issues

#7331 - I had the issue before, but the chances for it to occur were 50% before. Recently it hasn't happened much. Now with the newer Xen version unfortunately the chances are 100%.

### Notes

The issue started to occur after the following upgrade:

```
Packages Altered:
    Install  kernel-1000:5.15.52-1.fc32.qubes.x86_64                 @qubes-dom0-cached
    Install  kernel-latest-qubes-vm-1000:5.18.9-1.fc32.qubes.x86_64  @qubes-dom0-cached
    Install  kernel-qubes-vm-1000:5.15.52-1.fc32.qubes.x86_64        @qubes-dom0-cached
    Upgrade  linux-firmware-20220610-135.fc32.noarch                 @qubes-dom0-cached
    Upgraded linux-firmware-20211216-127.fc32.noarch                 @@System
    Upgrade  linux-firmware-whence-20220610-135.fc32.noarch          @qubes-dom0-cached
    Upgraded linux-firmware-whence-20211216-127.fc32.noarch          @@System
    Upgrade  python3-xen-2001:4.14.5-6.fc32.x86_64                   @qubes-dom0-cached
    Upgraded python3-xen-2001:4.14.5-5.fc32.x86_64                   @@System
    Upgrade  xen-2001:4.14.5-6.fc32.x86_64                           @qubes-dom0-cached
    Upgraded xen-2001:4.14.5-5.fc32.x86_64                           @@System
    Upgrade  xen-hypervisor-2001:4.14.5-6.fc32.x86_64                @qubes-dom0-cached
    Upgraded xen-hypervisor-2001:4.14.5-5.fc32.x86_64                @@System
    Upgrade  xen-libs-2001:4.14.5-6.fc32.x86_64                      @qubes-dom0-cached
    Upgraded xen-libs-2001:4.14.5-5.fc32.x86_64                      @@System
    Upgrade  xen-licenses-2001:4.14.5-6.fc32.x86_64                  @qubes-dom0-cached
    Upgraded xen-licenses-2001:4.14.5-5.fc32.x86_64                  @@System
    Upgrade  xen-runtime-2001:4.14.5-6.fc32.x86_64                   @qubes-dom0-cached
    Upgraded xen-runtime-2001:4.14.5-5.fc32.x86_64                   @@System
    Removed  kernel-1000:5.10.104-3.fc32.qubes.x86_64                @@System
    Removed  kernel-latest-qubes-vm-1000:5.15.14-1.fc32.qubes.x86_64 @@System
    Removed  kernel-qubes-vm-1000:5.10.104-3.fc32.qubes.x86_64       @@System
Scriptlet output:
   1 cat: /sys/power/resume: No such file or directory
   2 Generating grub configuration file ...
   3 Found theme: /boot/grub2/themes/qubes/theme.txt
   4 Found linux image: /boot/vmlinuz-5.15.52-1.fc32.qubes.x86_64
   5 Found linux image: /boot/vmlinuz-5.10.112-1.fc32.qubes.x86_64
   6 Found initrd image: /boot/initramfs-5.10.112-1.fc32.qubes.x86_64.img
   7 Found linux image: /boot/vmlinuz-5.10.109-1.fc32.qubes.x86_64
   8 Found initrd image: /boot/initramfs-5.10.109-1.fc32.qubes.x86_64.img
   9 Found linux image: /boot/vmlinuz-5.10.104-3.fc32.qubes.x86_64
  10 Found initrd image: /boot/initramfs-5.10.104-3.fc32.qubes.x86_64.img
  11 Found linux image: /boot/vmlinuz-5.15.52-1.fc32.qubes.x86_64
  12 Found linux image: /boot/vmlinuz-5.10.112-1.fc32.qubes.x86_64
  13 Found initrd image: /boot/initramfs-5.10.112-1.fc32.qubes.x86_64.img
  14 Found linux image: /boot/vmlinuz-5.10.109-1.fc32.qubes.x86_64
  15 Found initrd image: /boot/initramfs-5.10.109-1.fc32.qubes.x86_64.img
  16 Found linux image: /boot/vmlinuz-5.10.104-3.fc32.qubes.x86_64
  17 Found initrd image: /boot/initramfs-5.10.104-3.fc32.qubes.x86_64.img
  18 done
  19 please wait... ......................................................................................................................................................................................................................................................................................................................................................................................................................................
  20 please wait... ......................................................................................................................................................................................................................................................................................................................................................................................................................................
  21 Generating grub configuration file ...
  22 Found theme: /boot/grub2/themes/qubes/theme.txt
  23 Found linux image: /boot/vmlinuz-5.15.52-1.fc32.qubes.x86_64
  24 Found linux image: /boot/vmlinuz-5.10.112-1.fc32.qubes.x86_64
  25 Found initrd image: /boot/initramfs-5.10.112-1.fc32.qubes.x86_64.img
  26 Found linux image: /boot/vmlinuz-5.10.109-1.fc32.qubes.x86_64
  27 Found initrd image: /boot/initramfs-5.10.109-1.fc32.qubes.x86_64.img
  28 Found linux image: /boot/vmlinuz-5.15.52-1.fc32.qubes.x86_64
  29 Found linux image: /boot/vmlinuz-5.10.112-1.fc32.qubes.x86_64
  30 Found initrd image: /boot/initramfs-5.10.112-1.fc32.qubes.x86_64.img
  31 Found linux image: /boot/vmlinuz-5.10.109-1.fc32.qubes.x86_64
  32 Found initrd image: /boot/initramfs-5.10.109-1.fc32.qubes.x86_64.img
  33 done
  34 warning: file /lib/modules/5.10.104-3.fc32.qubes.x86_64/modules.softdep: remove failed: No such file or directory
  35 warning: file /lib/modules/5.10.104-3.fc32.qubes.x86_64/modules.devname: remove failed: No such file or directory
  36 warning: file /lib/modules/5.10.104-3.fc32.qubes.x86_64/modules.builtin.bin: remove failed: No such file or directory
  37 warning: file /boot/vmlinuz-5.10.104-3.fc32.qubes.x86_64: remove failed: No such file or directory
  38 warning: file /boot/config-5.10.104-3.fc32.qubes.x86_64: remove failed: No such file or directory
  39 warning: file /boot/System.map-5.10.104-3.fc32.qubes.x86_64: remove failed: No such file or directory
  40 /usr/lib/kernel/install.d/20-grub.install: line 81: grub2-get-kernel-settings: command not found
  41 cat: /sys/power/resume: No such file or directory
  42 Generating grub configuration file ...
  43 Found theme: /boot/grub2/themes/qubes/theme.txt
  44 Found linux image: /boot/vmlinuz-5.15.52-1.fc32.qubes.x86_64
  45 Found initrd image: /boot/initramfs-5.15.52-1.fc32.qubes.x86_64.img
  46 Found linux image: /boot/vmlinuz-5.10.112-1.fc32.qubes.x86_64
  47 Found initrd image: /boot/initramfs-5.10.112-1.fc32.qubes.x86_64.img
  48 Found linux image: /boot/vmlinuz-5.10.109-1.fc32.qubes.x86_64
  49 Found initrd image: /boot/initramfs-5.10.109-1.fc32.qubes.x86_64.img
  50 Found linux image: /boot/vmlinuz-5.15.52-1.fc32.qubes.x86_64
  51 Found initrd image: /boot/initramfs-5.15.52-1.fc32.qubes.x86_64.img
  52 Found linux image: /boot/vmlinuz-5.10.112-1.fc32.qubes.x86_64
  53 Found initrd image: /boot/initramfs-5.10.112-1.fc32.qubes.x86_64.img
  54 Found linux image: /boot/vmlinuz-5.10.109-1.fc32.qubes.x86_64
  55 Found initrd image: /boot/initramfs-5.10.109-1.fc32.qubes.x86_64.img
  56 done
```

I'm pretty sure I used dom0 kernel 5.10.112-1 before which is now not working anymore. So it's likely a Xen <--> Linux incompatibility introduced with `xen-2001:4.14.5-6.fc32.x86_64`.

I also tried dom0 Linux kernel 5.18.9-1 which doesn't work either.

Currently working:
dom0 kernel: 5.10.109-1
Xen: 4.14.5-6
domU kernel: 5.15.52-1
Lenovo T530 i7-3720QM iGPU, 16 GB RAM, coreboot, ME cleaned

**Comment by DemiMarie** [comment] 2022-07-21 17:57
Can you try

```
kernel.panic_on_warn=0
kernel.panic_on_oops=0
```

in `/etc/sysctl.conf`?  If the problem is “merely” an oops (as opposed to a direct call to panic()) this provides a chance of getting some error output.

**Comment by 3hhh** [comment] 2022-07-21 19:05
Good idea, but unfortunately it rebooted with that setting as well.

**Comment by 3hhh** [comment] 2022-07-22 17:35
I hit into it with `5.10.109-1` today as well, but the chances appear to be significantly lower.

**Comment by 3hhh** [comment] 2022-07-23 14:09
It's apparently caused by the following device attached to `sys-usb`:
```
01:00.0 SD Host controller: Ricoh Co Ltd PCIe SDXC/MMC Host Controller (rev 07) (prog-if 01)
        Flags: bus master, fast devsel, latency 0, IRQ 16
        Memory at 82a00000 (32-bit, non-prefetchable) [size=256]
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [78] Power Management version 3
        Capabilities: [80] Express Endpoint, MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [800] Advanced Error Reporting
        Kernel driver in use: pciback
        Kernel modules: sdhci_pci

01:00.1 System peripheral: Ricoh Co Ltd Device e232 (rev 04)
        Flags: bus master, fast devsel, latency 0, IRQ 17
        Memory at 82a01000 (32-bit, non-prefetchable) [size=256]
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [78] Power Management version 3
        Capabilities: [80] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Kernel driver in use: pciback
```

**Comment by 3hhh** [comment] 2022-07-23 14:14
Possibly related: #6824

**Comment by 3hhh** [comment] 2022-08-06 10:00
Another user reported a similar issue with a different SD card reader: https://groups.google.com/g/qubes-users/c/Nz_5Aiea1_Q

**Comment by 3hhh** [comment] 2022-08-30 14:47
5.10.128-1 with Xen 4.14.5-6 works, 5.11.4-1 does not.

Btw I double checked whether the root cause is the Ricoh SD Card reader attached to `sys-usb` with 5.11.4-1 as well and yes, it is - Qubes OS doesn't freeze when I remove it from `sys-usb` (with newer kernels it doesn't reboot anymore; it just freezes).

Debugging via `pstore_blk` did unfortunately not yield any results, not sure why (the problematic 5.15 apparently has `CONFIG_PSTORE_BLK=m` by default, other versions don't).

**Comment by 3hhh** [comment] 2022-11-13 09:10
I reproduced this again with a dom0 serial console attached and found the below log entries before the freeze. All of this happens when `sys-usb` starts up. Is there maybe a racing condition in `pciback` claiming the device and `sys-usb` starting?
Or is there some issue with SD card readers in combination with pciback? Btw I usually have a SD card in the reader whenever I boot.

6.0.2-2 kernel:
```
[   67.766112] mmc0: card e624 removed
[   67.782056] pciback 0000:01:00.0: xen_pciback: seizing device
[   67.782530] Already setup the GSI :16
[   67.808890] xhci_hcd 0000:00:14.0: remove, state 4
[   67.808917] usb usb4: USB disconnect, device number 1
[   67.808926] usb 4-3: USB disconnect, device number 2
[   67.810353] xhci_hcd 0000:00:14.0: USB bus 4 deregistered
[   67.810452] xhci_hcd 0000:00:14.0: remove, state 1
[   67.810467] usb usb3: USB disconnect, device number 1
[   67.810478] usb 3-3: USB disconnect, device number 2
[   67.810488] usb 3-3.1: USB disconnect, device number 3
[   67.810590] kauditd_printk_skb: 85 callbacks suppressed
[   67.810592] audit: type=1137 audit(1668327948.449:374): pid=1994 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb4/4-3" device_rule=616C6C6F7720696420323130393A30383133206E616D652022555342332E302048756222207669612D706F72742022342D332220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   67.810655] audit: type=1137 audit(1668327948.449:375): pid=1994 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb4" device_rule=616C6C6F7720696420316436623A30303033206E616D6520227848434920486F737420436F6E74726F6C6C657222207669612D706F72742022757362342220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D74797065202222 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   67.812041] audit: type=1137 audit(1668327948.450:376): pid=1994 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.1" device_rule=626C6F636B20696420303461393A31393061206E616D65202243616E6F5363616E22207669612D706F72742022332D332E312220776974682D696E746572666163652066663A66663A666620776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   67.813688] xhci_hcd 0000:00:14.0: Slot 1 endpoint 2 not removed from BW list!
[   67.813971] audit: type=1137 audit(1668327948.452:377): pid=1994 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb3/3-3" device_rule=616C6C6F7720696420323130393A32383133206E616D652022555342322E302048756222207669612D706F72742022332D332220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   67.815611] audit: type=1137 audit(1668327948.454:3[    0.04 (mockbuild@f6ba253475a3.1-1), GNU ld vers 10 05:23:27 CEST
```

5.18.9-1 kernel:
```
[   67.681667] mmc0: card e624 removed
[   67.702930] pciback 0000:01:00.0: xen_pciback: seizing device
[   67.703373] Already setup the GSI :16
[   67.731499] xhci_hcd 0000:00:14.0: remove, state 4
[   67.731533] usb usb4: USB disconnect, device number 1
[   67.731546] usb 4-3: USB disconnect, device number 2
[   67.734313] kauditd_printk_skb: 85 callbacks suppressed
[   67.734317] audit: type=1137 audit(1668328206.305:374): pid=1952 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb4/4-3" device_rule=616C6C6F7720696420323130393A30383133206E616D652022555342332E302048756222207669612D706F72742022342D332220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
```

Working boot in comparison on a 5.10.148-1 kernel:
```
[   69.833980] usb usb2: USB disconnect, device number 1
[   69.833995] usb 2-3: USB disconnect, device number 2
[   69.834007] usb 2-3.1: USB disconnect, device number 3
[   69.835943] kauditd_printk_skb: 93 callbacks suppressed
[   69.835946] audit: type=1137 audit(1668158065.788:385): pid=1926 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb4/4-3" device_rule=616C6C6F7720696420323130393A30383133206E616D652022555342332E302048756222207669612D706F72742022342D332220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   69.836020] audit: type=1137 audit(1668158065.788:386): pid=1926 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb4" device_rule=616C6C6F7720696420316436623A30303033206E616D6520227848434920486F737420436F6E74726F6C6C657222207669612D706F72742022757362342220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D74797065202222 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   69.836080] audit: type=1137 audit(1668158065.788:387): pid=1926 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3.1" device_rule=626C6F636B20696420303461393A31393061206E616D65202243616E6F5363616E22207669612D706F72742022322D332E312220776974682D696E746572666163652066663A66663A666620776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   69.838248] audit: type=1137 audit(1668158065.790:388): pid=1926 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb2/2-3" device_rule=616C6C6F7720696420323130393A32383133206E616D652022555342322E302048756222207669612D706F72742022322D332220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D747970652022756E6B6E6F776E22 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   69.838340] xhci_hcd 0000:00:14.0: Slot 1 endpoint 2 not removed from BW list!
[   69.840024] xhci_hcd 0000:00:14.0: USB bus 2 deregistered
[   69.840414] audit: type=1137 audit(1668158065.793:389): pid=1926 uid=0 auid=4294967295 ses=4294967295 msg='op="removed-device" device="/devices/pci0000:00/0000:00:14.0/usb2" device_rule=616C6C6F7720696420316436623A30303032206E616D6520227848434920486F737420436F6E74726F6C6C657222207669612D706F72742022757362322220776974682D696E746572666163652030393A30303A303020776974682D636F6E6E6563742D74797065202222 exe="/usr/sbin/usbguard-daemon" hostname=? addr=? terminal=? res=success'
[   69.840851] pciback 0000:00:14.0: xen_pciback: seizing device
[   69.841200] Already setup the GSI :17
[   69.844242] mmc0: card e624 removed
[   69.851550] pciback 0000:01:00.0: xen_pciback: seizing device
[   69.851932] Already setup the GSI :16
[   73.1[   73.547586] loop: module loaded
[   75.881507] pciback 0000:01:00.0: xen_pciback: vpci: assign to virtual slot 0
[   75.883734] pciback 0000:01:00.0: registering for 2
[   75.884353] pciback 0000:01:00.1: xen_pciback: vpci: assign to virtual slot 0 func 1
[   75.885905] pciback 0000:01:00.1: registering for 2
[   75.886420] pciback 0000:00:14.0: xen_pciback: vpci: assign to virtual slot 1
[   75.888182] pciback 0000:00:14.0: registering for 2
[   76.314440] xen-blkback: backend/vbd/2/51712: using 1 queues, protocol 1 (x86_64-abi) persistent grants
[   76.321898] Already setup the GSI :16
[   76.322846] Already setup the GSI :16
[   76.323768] Already setup the GSI :16
[   76.324517] Already setup the GSI :16
[   76.325279] Already setup the GSI :16
```

5.10.148-1 also freezes sometimes, but more at a 20-30% rate.

**Comment by logoerthiner1** [comment] 2022-11-13 11:24
The dom0 console does not write soft lockup watchdog messages (in my case `watchdog: BUG: soft lockup - CPU#3 stuck for 402s! [dmesg:7645]` with a kernel stack backtrace). This may indicate that something deeper is confused at least.

If problem is in xen, xen log should say something. If you can get xen console, triple ctrl-a and using xen debug keys can be more helpful. When computer is in freezing state, xen may provide better idea about who is culprit and maybe what is the calling stack.

Also, debug utilities may not live with sys-usb well - in my experience, when I am using USB 3.0 debug cable, I cannot start sys-usb(partly because I did not enable `share=yes`? anyway such should be considered). And make sure your debug utility does not accidentally changed the PCI device number (#7792) .

**Comment by marmarek** [comment] 2022-11-13 19:51
> [   67.813688] xhci_hcd 0000:00:14.0: Slot 1 endpoint 2 not removed from BW list!

This hints at issue fixed in https://github.com/QubesOS/qubes-linux-kernel/commit/cb287b9d5a5797e3f287b79dcc07df7ccbd0ccac (included in 6.0.2-2). 6.0.7 has the final upstream fix included, so may be worth checking that too.

**Comment by DemiMarie** [comment] 2022-11-14 09:05
> I'll try 6.0.7 once I see it available.

It’s available in the testing repository, which you can enable via Qubes Global Settings.

**Comment by 3hhh** [comment] 2022-11-14 16:26
Ouch.

So if I understand [this line](https://github.com/QubesOS/qubes-core-admin-linux/blob/master/dracut/modules.d/90qubes-pciback/qubes-pciback.sh#L13) correctly, SD cards are simply not filtered out (mine has type `08`) and I need to do it manually via `rd.qubes.hide_pci`.

For some reason I had always thought this would all happen automatically once I assign a device to `sys-usb`. I'll file a feature request for that...

**Comment by 3hhh** [comment] 2022-11-14 16:59
With `rd.qubes.hide_pci` I could just successfully boot 6.0.2 two times in a row even with the SD card inserted.

This doesn't fix this bug, but is a good workaround.

**Comment by 3hhh** [comment] 2023-05-08 16:22
Other user with the same issue and workaround: https://forum.qubes-os.org/t/qubes-crashes-starting-sys-usb/18288

**Closed** 2024-12-07 14:02 UTC
Labels: T: bug, C: kernel, P: default, hardware support, affects-4.1, eol-4.1
