### ISSUE TITLE
LUKSerror: luks device has no key/passphrase

### ISSUE THREAD

**Issue by Schopenberg** [QubesOS/qubes-issues#1161] opened 2015-09-03 02:08 UTC
This is my first issue submission, so please bear with me.

I'm attempting to install Qubes OS R3 (rc2) on a late 2008 Macbook Pro. None of the three kernels under "Troubleshooting" would work (graphics issues, it would seem), so I went into "basic graphics mode." I went through all the steps (time zone, installation source, yadda yadda yadda), and then ran into some errors. These errors popped up whether I chose LVM, BTRFS, or the other option whose name slips my mind (I mention this because I understand that LVM doesn't work well with Macs oftentimes, though I've managed to get it to work before). 

I've included pictures of the output to save me the time of typing them all out (apologies if these are out of order).
![img_1880](https://cloud.githubusercontent.com/assets/14102299/9649152/826a581c-51b6-11e5-86c1-1137e2ff431c.jpg)
![img_1881](https://cloud.githubusercontent.com/assets/14102299/9649153/851bbd8a-51b6-11e5-9487-1b4a3b61fadf.jpg)
![img_1876](https://cloud.githubusercontent.com/assets/14102299/9649161/92b67db8-51b6-11e5-988c-c0686d582aa4.jpg)
![img_1873](https://cloud.githubusercontent.com/assets/14102299/9649162/99c56b3c-51b6-11e5-87ad-7ae022b4fca2.jpg)
![img_1877](https://cloud.githubusercontent.com/assets/14102299/9649165/9d4594bc-51b6-11e5-9ef6-ace9bda013c2.jpg)
![img_1878](https://cloud.githubusercontent.com/assets/14102299/9649166/a148e884-51b6-11e5-8025-19b5773cbf0e.jpg)
![img_1874](https://cloud.githubusercontent.com/assets/14102299/9649167/a1a160b8-51b6-11e5-9378-e45a4ffbffb6.jpg)
![img_1875](https://cloud.githubusercontent.com/assets/14102299/9649169/a1aa4fc0-51b6-11e5-8044-6d6b213b6cc5.jpg)
![img_1879](https://cloud.githubusercontent.com/assets/14102299/9649168/a1a4da04-51b6-11e5-9aa4-f1a08d53236b.jpg)

**Comment by Piirtaa** [comment] 2015-11-14 12:24
I get exactly the same error on a panasonic toughbook cf 19, mk 3.   I've tried the same steps as well.  Qubes 2 installed fine and didn't have this problem.

**Comment by SentinelX101** [comment] 2015-11-14 12:43
I also have the same problem when attempting to install Qubes OS Release 3.0 on a computer with an Nvidia graphics card that does not support anything other than basic graphics mode for installation.

Presumably the text only installer just forgets to ask for an encryption passphrase to set.

**Comment by marmarek** [comment] 2015-11-14 15:55
> Presumably the text only installer just forgets to ask for an encryption passphrase to set.

Yes. Even worse - [text installed doesn't support password prompt](https://bugzilla.redhat.com/show_bug.cgi?id=1020345).

The only way to feed LUKS password is to use kickstart file (unattended installation). Take a look at this thread: https://groups.google.com/d/msgid/qubes-users/54DA1BA0.6010305%40t-t-l.co.uk

**Comment by egberts** [comment] 2016-09-29 23:25
Looks like I got a VirtualBox video driver error, which prompted me to go into Anaconda text-mode.
<img width="956" alt="qube" src="https://cloud.githubusercontent.com/assets/10352354/18975755/68492270-867a-11e6-9e53-6fc159b03f3c.png">

Would this be a new issue?

**Comment by gjhami** [comment] 2017-02-05 02:30
Excuse me if there's an obvious answer to this question, but why can't we just edit the code to use a hard coded password for encryption and then delete the password from that file later?

**Comment by g60ocR** [comment] 2017-05-01 08:54
This is still an issue unfortunately.

**Comment by mikeshultz** [comment] 2017-10-09 05:18
If the problem is indeed upstream, perhaps a maintainer could open a ticket, since [the one submitted by a user](https://bugzilla.redhat.com/show_bug.cgi?id=1020345) was closed as Won't Fix.

**Comment by andrewdavidwong** [comment] 2021-05-08 08:00
This bug report has seen no activity in a very long time, and it is not assigned to any current release milestone. It looks like it was left open by mistake, so I'm closing it now. However, if anyone is still affected by this bug on a currently-supported release, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2021-05-08 08:00 UTC
Labels: C: installer, P: major, T: bug, help wanted
