### ISSUE TITLE
Display a "last modified" date on website / documentation pages?

### ISSUE THREAD

**Issue by vincentadultman** [QubesOS/qubes-issues#3786] opened 2018-04-04 15:10 UTC
This question comes up occasionally, most recently: https://groups.google.com/forum/#!topic/qubes-users/2MKKopsFYUw so opening this issue for discussion (apologies if it has been dealt with elsewhere).

Would it be possible / desirable for the sidebar that already shows "view page source / edit page / how to contribute" to show the date of the last commit? Yes, the user can click "view page source" to get onto github and look at the commit history, but this assumes a basic understanding of what will be found under "view page source" / github interface.

While showing such a date would not be as useful as on say medical websites where "article written" and "last reviewed" dates are often provided (as a commit may only very minimally change a page) it would give the user some idea as to the "freshness" of the content. I would see the displayed date most usefully being a hyperlink to the list of commits for that page.

Unsure of whether this is feasible with jekkyl / github pages, length of issue at https://github.com/jekyll/jekyll/issues/2260 does not give off good vibes in terms of quick and easy...

**Comment by andrewdavidwong** [comment] 2018-04-05 00:05
Duplicate of #2169

**Comment by andrewdavidwong** [comment] 2018-04-05 00:05
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-04-05 00:05 UTC
