### ISSUE TITLE
Does Whonix-Qubes Gateway Comply with Tor Entry Guards Policies?

### ISSUE THREAD

**Issue by eubxawoh** [QubesOS/qubes-issues#1145] opened 2015-08-21 15:21 UTC
According to Tor documents (e.g. https://www.torproject.org/docs/faq.html.en#EntryGuards), a Tor client should maintain the same entry guards for a certain time. To my experience, this doesn't happen in Whonix-Qubes Gateway, because at each boot it seems to use a different one. Am I wrong?

Maybe this is due to the fact that Qubes discards all root changes in its AppVMs.

Regards.

**Comment by adrelanos** [comment] 2015-08-21 15:24
Duplicate of https://github.com/QubesOS/qubes-issues/issues/1137.

**Closed** 2015-08-25 23:53 UTC
Labels: R: duplicate
