### ISSUE TITLE
Screen locks randomly on its own

### ISSUE THREAD

**Issue by aXZhbg** [QubesOS/qubes-issues#6435] opened 2021-03-02 20:34 UTC
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Screen locking component/Screensaver.

**Brief summary**
Screen locks at seemingly randoms times, even while mouse is being moved or typing at keyboard.
Happens very rare - sometimes once or twice a day, sometimes doesn't happen all day. 

I'd like to stress out that this isn't a human error in any shape or form.

**How Reproducible**
Seems to happen at random, didn't notice anything correlated to it.

**To Reproduce**

**Expected behavior**
Screen not locking at random

**Actual behavior**
Screen locks at random

**Screenshots**

**Additional context**
Was in Firefox in a StandaloneVM when it happened last time.
Using a HP Zbook G1 with a dock.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment] 2021-03-03 03:51
Same here, although for me it only happens when using the mouse, not when typing.

**Comment by andrewdavidwong** [comment] 2021-03-03 07:45
Duplicate of #3727

**Comment by andrewdavidwong** [comment] 2021-03-03 07:45
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2021-03-03 07:45 UTC
Labels: P: default, T: bug
