### ISSUE TITLE
Firewall rules do not apply to sys-whonix traffic?

### ISSUE THREAD

**Issue by ubestemt** [QubesOS/qubes-issues#2774] opened 2017-04-24 19:11 UTC
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-testing, anon-whonix

---

### Expected behavior:

Firewall rules in VM Settings also apply when sys-whonix is used as NetVM

### Actual behavior:

They do not. And unlike for sys-net, no warning is shown ("...is not connected to a FirewallVM!").

### Steps to reproduce the behavior:

While using sys-whonix as NetVM try to deny Network access in the Firewall rules tab of the VM Settings. Then check the network connection of that VM.

**Comment by rustybird** [comment] 2017-04-26 15:28
Duplicate of https://github.com/QubesOS/qubes-issues/issues/1815#issuecomment-220253105

**Closed** 2017-04-26 17:25 UTC
Labels: duplicate
