### ISSUE TITLE
Firefox icon (also chromium) gets "lost" on Debian AppVMs (unpredictably, hard to reproduce)

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2586] opened 2017-01-16 17:42 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Debian-8

---

### Expected behavior:
after all appmenus are synced and stuff the icons on app name will "stay put"  which is normal behavior since long ago https://groups.google.com/forum/#!topic/qubes-users/FnY8lGFWi1E and is observed most of the time

### Actual behavior:
If a debian-8 appvm runs long enough (like, 12 hours or so) it will suddenly and inexplicably "loose" some of its icons (they'll get replaced by a generic "lock" one.

Firefox is particularly prone to this if just left to linger for 12 hours.

### Steps to reproduce the behavior:

Make a debian-8 appvm
make sure firefox (and maybe chromium) are installed, run, and show icons "as expected"
Let the VM just stay up with firefox and/or chromium running.
At some point, firefox and/or chromium will loose their icon and have it replaced with a lock.

### General notes:
Restarting the VM usually helps get the icons back...for a while.

ADDITIONAL INFORMATION: 
Just noticed the following:
making firefox spawn new windows makes new window have a "lock" instead of firefox icon rather often. Seems related and is perhaps the easiest way of "getting" this behavior (I usually coax firefox into having a "lock" instead of normal icon after 2-3 rapidly opened new windows, which is much easier than having to wait for hours and hours)

EDIT: ADDITIONAL INFORMATION - partial workaround.
Enabling windows-style application stacking (panel preferences -> Items -> window button preferences -> window groupings, set it to always) allows to at least be aware what each window is (it will have "mozilla firefox" or something like that written on it), but it only works when there's >1 window for a given application (which is ... typical with browsers)

---

**Comment by JimmyAx** [comment] 2017-01-16 21:32
Can confirm this as I've been noticing from time to time that the window icon suddenly has turned into a generic lock icon. It's not limited to Debian and Firefox though. I can create a brand new Fedora 24 AppVM, open a terminal and create new windows by rapidly hitting `Ctrl + Alt + N`around 10-20 times to reproduce it. A few of them end up with the generic lock icon.

**Comment by tonsimple** [comment] 2017-01-17 09:14
Well, I tend to do about 70% of my stuff in Debian app-VMs (I only use fedora for firewallvm and netvm, and the latter is because compiling network card drivers for Debian-8 is a bit of a fuss right now).
Just tried in fedora 24, can confirm with terminal and firefox.

Also, if site has a favicon and redirects to another site with a favicon, firefox in fedora can lose its icon (replaced with "generic qubes lock")

**Comment by jpouellet** [comment] 2017-02-24 18:45
Duplicate of: https://github.com/QubesOS/qubes-issues/issues/1495
Possibly related to: https://github.com/QubesOS/qubes-issues/issues/2536

**Comment by andrewdavidwong** [comment] 2017-02-25 03:28
@jpouellet: Yep. Thanks. Missed that the first time around.

**Closed by andrewdavidwong** 2017-02-25 03:28 UTC
Labels: bug, C: Debian, C: gui-virtualization
