### ISSUE TITLE
HVMs with Certain Memory Values and USB Devices attached cause Unexpected Behavior

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6121] opened 2020-10-15 04:25 UTC
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
HVMs with USB controllers attached.

**Brief summary**
When USB controllers are attached in the Devices tab, setting memory values to 3857MB or greater cause HVM to hang, crash, fail to boot, or not see disks.

**To Reproduce**

1.) Allocate 3857MB or more memory to a HVM
2.) Attach USB controllers in the Device Tab with Strict PCI reset to same HVM.
3.) Start HVM via ISO, preinstalled OS, or physical USB stick

**Expected behavior**
HVM boots normally with given memory and USB devices.

**Actual behavior**
Depending on the OS, HVM may fail to boot, crashes, hangs, or is unable to see disks. 

**Additional context**
If USB devices are NOT attached to the HVM in the Device Tab, there doesn't seem to be an issue. 

Results from some testing before realizing it was due to having USB devices attached: 

All tests booted to initial Grub or similar selection menus without issue but failures occurred after choosing an option.

TailsOS v3.0.1live USB stick 
3857MB or greater, failed to boot successfully with about 5 variations in errors ranging from hangs to immediate rash/shutdowns.
3856MB or less booted normal, in about 1m8s (1m24s with memory down to 512MB)

Preinstalled windows7: 
3857MB or greater, Bluescreen with a MEMORY_MANAGEMENT fault
3556MB to 3523MB, Bluescreen, but NOT memorymanagement, just "problem with your computer"
3522MB or less boots normal, no problems. 

Win7 Installer ISO
3857MB or greater, Bluescreen with MEMORY_MANAGEMENT fault.
3856MB-3515MB, Installer boots, but disks section is blank, cannot install.
3514MB or less, boots normal, shows all available disks.

Kali Live ISO 2020.3
3587MB Loader crashes, HVM halts on its own.
3586MB Boots in to live kali normal.

Kali Installer ISO 2020.3
3587MB Loader crashes, HVM halts on its own.
3586MB Boots to installer

TailsOS v4.11 ISO
3857MB crashes, halts.

Qubes R4.0.3 ISO
3857MB halts after a few minutes
3856MB boots normal

SystemRescueCD ISO
3857MB halts
3856MB boots normal

**Solutions you've tried**
Detaching USB devices

**Comment by icequbes1** [comment] 2020-10-16 05:23
Potentially related to #4321?

**Comment by andrewdavidwong** [comment] 2020-10-16 09:20
> Potentially related to #4321?

This looks like a probable [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #4321, though I'm not certain. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2020-10-16 09:20
Duplicate of #4321

**Closed by andrewdavidwong** 2020-10-16 09:20 UTC
Labels: P: default, T: bug
