### ISSUE TITLE
Need to retry login several times (caps-lock + 3 keyboard layouts)

### ISSUE THREAD

**Issue by niccokunzmann** [QubesOS/qubes-issues#4182] opened 2018-08-04 06:08 UTC
### Qubes OS version:

R3.2

### Affected component(s): 

Login Screen after locking: XScreenSaver 5.36

---

### Steps to reproduce the behavior:

1. Add a keyboard layout which is different from EN-US i.e. Russian, German
2. Switch the layout while working (Sometimes I can  notice that VMs and dom0 can differ in layout)
3. Lock the screen
4. Try to log in. It may or may not work if you type the correct password because either caps-lock or the keyboard layout is different.

I have English, German and Russian activated. I do not see if caps-lock is activated. Thus, given I mis-spell my password sometimes, I expect 1 to 7 login attempts.

### Expected behavior:

When I am at the log-in screen after locking the screen
I would know either:
- Which keyboard locale I use and if caps-lock is activated when typing
  - It can be either shown
  - Or I can type something somewhere.

### Actual behavior:

When I am at the log-in after locking the screen screen
I can type and do not know  what I type.

### General notes:

---

### Related issues:

- A discussion about the log-in screen https://github.com/QubesOS/qubes-issues/issues/1917

**Comment by andrewdavidwong** [comment] 2018-08-04 22:17
This is either an upstream feature request for XScreenSaver or a duplicate of #1917 (i.e., another reason to switch from XScreenSaver). It's very unlikely that the Qubes OS project would maintain an XScreenSaver fork for non-Qubes-specific functionality.

**Closed by andrewdavidwong** 2018-08-04 22:17 UTC

**Comment by im7mortal** [comment] 2023-04-12 00:40
@andrewdavidwong Will we reopen it?

Do we have now fork of the screensaver from 4.1.2? I didn't find screensaver repository in the QubesOS organization. 

If there is the warning about the CapsLock then definitely there should be a warning about non **en-US** layout.

**Comment by andrewdavidwong** [comment] 2023-04-12 23:24
> @andrewdavidwong Will we reopen it?

If there is a good reason to do so, yes. If not, no.

> Do we have now fork of the screensaver from 4.1.2?

I don't believe so. I think we merely replaced the logo (#6425).

> If there is the warning about the CapsLock then definitely there should be a warning about non **en-US** layout.

That sounds like it should be an upstream feature request to the appropriate upstream project (e.g., XScreenSaver, Xfce, Fedora).

> So I see from #1917 for some reason it was hot topic for some users. So the conversation was locked (?) .

Looks like the conversation was locked because some people starting using the issue comments as a place to bicker with each other and call each other names.




> My argument is that we can easily implement a feature similar to the existing CapsLock indicator to show the current keyboard layout. This would be a practical solution for the time being, as it would help users to quickly identify which layout they are using at any given moment.

I guess I don't see why you'd ask the Qubes OS Project to do this when we neither created nor maintain XScreenSaver, Xfce, or Fedora. None of these things is specific to Qubes OS, nor is switching between keyboard layouts in Linux. I think you're simply asking for this in the wrong project's issue tracker.
