### ISSUE TITLE
Error when attempting to install Mirage template with disk size smaller than the default

### ISSUE THREAD

**Issue by palainp** [QubesOS/qubes-issues#7426] opened 2022-04-06 11:31 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

When trying to install in qubes 4.1 a TemplateVM created with qubes-builder-mirage (default `TEMPLATE_ROOT_SIZE ?= 50MiB` which suits well for unikernels) the root.img disk is smaller than default (10G) and installation fails with error "not enough data" and leads to an uninstalled template.

The installation script fails with the following logs and the template is not installed.
```
...
mirage-firewall: Importing data
Traceback (most recent call last):
  File "/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 431, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 297, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 107, in import_root_img
    vm.volumes['root'].import_data(stream=tar.stdout)
  File "/usr/lib/python3.8/site-packages/qubesadmin/storage.py", line 270, in import_data
    self._qubesd_call('Import', payload_stream=stream)
  File "/usr/lib/python3.8/site-packages/qubesadmin/storage.py", line 76, in _qubesd_call
    return self.app.qubesd_call(
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 730, in qubesd_call
    return self._parse_qubesd_response(stdout)
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 109, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesException: Data import failed: not enough data (copied 52428800 bytes, expected 10737418240 bytes)
warning: %post(qubes-template-mirage-firewall-4.0.6-202204051348.noarch) scriptlet failed, exit status 1
...
```

### The solution you'd like

I get over this error by modiying `qvm_template_postprocess.py` at lines https://github.com/QubesOS/qubes-core-admin-client/blob/400ea49e84bfba30f50b658ca0b23e4bb18c52f2/qubesadmin/tools/qvm_template_postprocess.py#L109 and https://github.com/QubesOS/qubes-core-admin-client/blob/400ea49e84bfba30f50b658ca0b23e4bb18c52f2/qubesadmin/tools/qvm_template_postprocess.py#L119:
```
-         vm.volumes['root'].import_data(stream=tar.stdout)
+         vm.volumes['root'].import_data_with_size(stream=tar.stdout, size=root_size)
```

Although it seems to be related on the surface, I cannot use the same solution for https://github.com/QubesOS/qubes-issues/issues/7176, but both issues may have a common root?

Anyway an error message still remains:
```
mirage-firewall: Failed to resize root volume of mirage-firewall from 54525952 to 52428800 after import: For your own safety, shrinking of root is disabled (52428800 < 54525952). If you really know what you are doing, use `lvresize` on qubes_dom0/vm-mirage-firewall-root manually.
```

And my unikernels is still not booting, showing the following in the logs and then it hangs:
```
[2022-04-06 07:27:02] Logfile Opened
[2022-04-06 07:27:02] .[30m.[47mWelcome to GRUB!
[2022-04-06 07:27:02] 
[2022-04-06 07:27:02] .[37m.[40m.[37m.[40m.[37m.[40m.[3;35H      [ grub-xen.cfg  424B  100%  630.95B/s ].[3;1Herror: no such device: /boot/xen/pvboot-x86_64.elf.
[2022-04-06 07:27:02] Reading (xen/xvda/boot/grub/grub.cfg
[2022-04-06 07:27:02] .[H.[J.[1;1H.[1;41H      [ grub.cfg  81B  100%  85.44B/s ].[1;1H
```

The grub.cfg have the right size (81B): https://github.com/marmarek/qubes-builder-mirage/blob/master/template_scripts/grub.cfg

### The value to a user, and who that user might be

It will be possible to install mirage unikernels templates into dom0.

**Comment by andrewdavidwong** [comment] 2022-04-13 07:38
Looks like closure via commit was intended but failed for some reason. Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Closed** 2022-04-13 09:11 UTC
Labels: T: bug, C: core, C: templates, r4.1-buster-cur-test, r4.1-dom0-cur-test, P: default, r4.1-bullseye-cur-test, diagnosed, C: storage, r4.1-centos-stream8-cur-test, r4.1-fc34-cur-test, r4.1-fc35-cur-test, r4.1-bookworm-cur-test, r4.1-fc36-cur-test
