### ISSUE TITLE
VM clocks fall out of sync after sleep

### ISSUE THREAD

**Issue by beanjo55** [QubesOS/qubes-issues#4793] opened 2019-02-06 15:18 UTC
### Qubes OS version:
R4.0.1

### Affected component(s):
All default VMs's and VM's created from templateVM's

---

### Steps to reproduce the behavior:
Have VM's running.
Put system to sleep.
After resuming from sleep, all the clocks on the system may still have the value from when the system went to sleep. Occasionally, it correctly updates the time, but in most cases it fails to do so.

### Expected behavior:
VM's sync from the designated clockVM or from the hardware clock automatically after resuming from sleep

### Actual behavior:

VM's retain the last known time rather than updating after resume

### General notes:
The clocks resync after a system reboot, but will fall it of sync again after the system is in sleep
They also resync after manually running `sudo qvm-sync-clock` in each VM

Occasionally, the systemd-timesyncd service in sys-net will fail, causing any manual syncs to get incorrect time until it is restarted

In case it matters, the install is mostly stock and up to date, with the biggest change being installing and running KDE rather than XFCE. The install is running on a Gigabyte Aero 15 v8, and sleep is triggered by closing the lid.

The sync issue causes problems relating to internet security, particularly that certificates can not be validated if the clock is too far out of sync and other site will refuse to connect altogether

---

### Related issues:
#3489

**Comment by andrewdavidwong** [comment] 2019-02-07 02:34
How is this different from #3489?

**Comment by andrewdavidwong** [comment] 2019-02-07 02:35
Duplicate of #3489

**Comment by andrewdavidwong** [comment] 2019-02-07 02:36
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-02-07 02:36 UTC
Labels: C: core, bug

**Comment by beanjo55** [comment] 2019-02-07 16:43
Apologies, I opened a new issue as the old one was marked as resolved. I will keep this in mind if I have to report other issues and will post additional info in the appropriate issue. No need to reopen, thank you.
