### ISSUE TITLE
qubes-dom0-update not working

### ISSUE THREAD

**Issue by zS3mNH2** [QubesOS/qubes-issues#5107] opened 2019-06-19 04:06 UTC
4.0

**Brief summary**
It lists updates as the following but never updates:

Installing:
 kernel          x86_64 1000:4.14.119-2.pvops.qubes    qubes-dom0-current  46 M
 kernel-qubes-vm x86_64 1000:4.14.119-2.pvops.qubes    qubes-dom0-current  64 M
Removing:
 kernel          x86_64 1000:4.14.103-1.pvops.qubes    @System            239 M
 kernel-qubes-vm x86_64 1000:4.14.103-1.pvops.qubes    @System            272 M

**To Reproduce**
Just run qubes-dom0-update

**Expected behavior**
It should remove those kernels and install other kernesl

**Actual behavior**
Instead it does nothing and says the following:

> The downloaded packages were saved in cache until the next successful transaction. You can remove cached packages by executing 'dnf clean packages'.

**Comment by andrewdavidwong** [comment] 2019-06-19 04:33
Duplicate of 4792

**Comment by andrewdavidwong** [comment] 2019-06-19 04:33
Duplicate of #4792

**Comment by andrewdavidwong** [comment] 2019-06-19 04:33
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. In particular, see https://github.com/QubesOS/qubes-issues/issues/4792#issuecomment-502472832. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-06-19 04:33 UTC
Labels: P: default, T: bug
