### ISSUE TITLE
Decrypting file woudl take too much CPU time

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5249] opened 2019-08-16 10:51 UTC
**Qubes OS version**

4.0.1
**Affected component(s) or functionality**

Qubes Restore

**Brief summary**

Restoring backup fails in "Restore qubes" dialog.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Backup qubes in encrypted file
_2. Use Qubes Manager to restore.
_3. Select all qubes to restore
_4. Begin process, see it look good for some time.
_5. See error:

```
ERROR: unable to extract files for /var/temp/restore....../vm16/private.img.007.tar.output: Error extracting data: failed to decrypt /var/tmp/restore...../private.img.000.enc: b'scrypt: Decrypting file woudl take too much CPU time\n'
```

**Expected behavior**
I expected all qubes to restore 

**Actual behavior**
I see "Finished successfully" and I have many qubes listed but they do not contain the correct data inside them.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

I backed up only a few qubes and restored them and this worked.  Could the problem be the size of the backup file?  (320GB)

**Solutions you've tried**
Rebooting
Reinstall Qubes

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

https://github.com/QubesOS/qubes-issues/issues/4683 but this looks like it is for 4.0 but I use 4.0.1 so I should have this update.  (It is not easy to update dom0 until after I restore qubes because my VPN information is in there but I will try to find a way after I reinstall Qubes again)
**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment] 2019-08-16 22:08
It is a duplicate of #4683. The update fixing it was released in March, while 4.0.1 was released in January, so 4.0.1 doesn't have it. Updating dom0 should help.

**Closed by marmarek** 2019-08-16 22:08 UTC
Labels: P: default, T: bug
