### ISSUE TITLE
menu drawing broken

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1061] opened 2015-07-14 14:08 UTC
Please have a look at this screenshot.

![20150714_160203](https://cloud.githubusercontent.com/assets/1985040/8675075/1d3742a2-2a42-11e5-82ba-bfaac7dd71b0.jpg)

Qubes Q3 RC1
kernel 3.19
nvidia
nouveau

Known issue? Want more info?

**Comment by adrelanos** [comment] 2015-07-14 14:52
Happening in a Debian based AppVM. Maybe duplicate of #1051?

**Comment by marmarek** [comment] 2015-07-14 15:35
Yes, duplicate of #1051

**Closed by marmarek** 2015-07-14 15:35 UTC
Labels: duplicate
