### ISSUE TITLE
Ubuntu Jammy template needs pulseaudio 15.99.1 headers

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7537] opened 2022-06-01 14:40 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title
Build fails as pulse headers for 15.99.1 are not included

### Steps to reproduce
Attempt to build jammy (2204 LTS) packages - specifically gui-agent-linux-vm

### Expected behavior
Build completes

### Actual behavior
PA build fails as PA_VER_FULL is 15.99.1
Only headers for 15.0 are included.

**Comment by lubellier** [comment] 2022-06-01 19:46
@unman: is it a duplicate of #7531 ? Or is it really specific to 15.99.1 as it seems?

**Comment by unman** [comment] 2022-06-05 12:49
On Wed, Jun 01, 2022 at 12:46:45PM -0700, Ludovic Bellier wrote:
> @unman: is it a duplicate of #7531 ? Or is it really specific to 15.99.1 as it seems?
> 

It is specific to 15.99.1

**Closed as completed** 2023-04-26 12:46 UTC
Labels: C: builder, C: Debian/Ubuntu, P: default, diagnosed, r4.2-host-cur-test, r4.2-vm-centos-stream8-stable, r4.2-vm-bullseye-stable, r4.2-vm-fc36-stable, r4.2-vm-fc37-stable, r4.2-vm-bookworm-stable, r4.2-vm-fc38-cur-test, affects-4.1
