### ISSUE TITLE
specifically sys-whonix fails to establish circuit

### ISSUE THREAD

**Issue by hyperfekt** [QubesOS/qubes-issues#3511] opened 2018-01-31 20:27 UTC
#### Qubes OS version:

R4.0rc3

#### Affected TemplateVMs: 
whonix-gw

---

### Steps to reproduce the behavior:

perform the following steps in sys-whonix:
1. run whonixsetup
2. select 'ready to enable'
3. wait for whonixcheck to start

### Expected behavior:

Tor Bootstrap completes successfully, a circuit is established.

### Actual behavior:

Whonixcheck aborts with the following message:
> [ERROR] [whonixcheck] Tor Bootstrap Result:
> Whonixcheck gave up waiting.
> Tor Circuit: not established
> Bootstrapping 90 % done. Tor reports: NOTICE BOOTSTRAP PROGRESS=90 TAG=circuit_create SUMMARY="Establishing a Tor circuit"

### General notes:

In an AppVM with the same whonix-gw template and the same settings, a circuit is successfully established. The same failure occurs with a clone of sys-whonix.
Nothing was changed, this is a fresh install.
The testing repository as of 22:15 UTC+1, 31-01-18 does not include a fix for this issue.

---

**Comment by adrelanos** [comment] 2018-01-31 21:50
Rerun whonixcheck on sys-whonix. Showing alright?

**Comment by hyperfekt** [comment] 2018-01-31 23:02
It failed every time I reran whonixcheck or whonixsetup. However it seems fixed with the just released rc4. I guess we can close this.

**Comment by andrewdavidwong** [comment] 2018-02-01 02:59
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-02-01 02:59 UTC
Labels: C: Whonix
