### ISSUE TITLE
archlinux template : installing python (3.11.3-1) breaks dependency required by qubes-* specific packages

### ISSUE THREAD

**Issue by toothlesslizard** [QubesOS/qubes-issues#8183] opened 2023-05-07 11:31 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.2

```
[user@archlinux ~]$ sudo pacman -Suuy
:: Synchronizing package databases...
 qubes-r4.1-current is up to date
 qubes-r4.1-current-testing is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing python (3.11.3-1) breaks dependency 'python<3.11' required by qubes-db-vm
:: installing python (3.11.3-1) breaks dependency 'python<3.11' required by qubes-vm-core
[user@archlinux ~]$ 
```

**Comment by unman** [comment] 2023-05-07 11:44
Duplicate of #8170

Any rolling distro, as with testing, will hit these issues. I dont think
there is generic solution.

**Comment by andrewdavidwong** [comment] 2023-05-07 22:47
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-05-07 22:47 UTC
Labels: T: bug, P: default
