### ISSUE TITLE
Debian Buster template has two identical application entries for "Xfce Terminal"

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#4993] opened 2019-04-23 00:10 UTC
**Qubes OS version**

r4.0

**Affected component(s) or functionality**

Debian Buster/Whonix 15 templates

**Brief summary**

There are two items in Qubes-Settings > Applications for “Xfce Terminal” for the Whonix 15 gateway and workstation. One is the actual terminal and the other is the terminal preferences. They even have the same icon.

**To Reproduce**

Follow Whonix instruction to upgrade from version 14 to 15: http://whonix.org/wiki/Upgrading_Whonix_14_to_Whonix_15.

**Expected behavior**

A single item and icon for the terminal and possibly a second for the preferences, or none at all for the preferences.

**Actual behavior**

Two identical entries for "Xfce Terminal".

**Issue**

The problem is due to the fact that `/usr/share/applications/xfce4-terminal{,-settings}.desktop` both have these same entries: `Name=Xfce4 Terminal`, `Icon=utilities-terminal`.

**Related**

Reported to Whonix here: https://forums.whonix.org/t/qubes-whonix-version-14-debian-stretch-based-can-be-upgraded-to-version-15-debian-buster-based-testers-wanted/7143/15

**Comment by unman** [comment] 2019-04-23 11:30
This may be Whonix specific, since I dont see it in Debian templates - albeit they dont have xfce4-terminal installed by default.

> The problem is due to the fact that /usr/share/applications/xfce4-terminal{,-settings}.desktop both have these same entries: Name=Xfce4 Terminal, Icon=utilities-terminal.

No - this is expected and present in native Buster.

@qubenix - Can you check the "Categories" section?

**Comment by adrelanos** [comment] 2019-04-23 15:28
I can also reproduce this in my Qubes Debian buster (release upgraded)
templates. No Whonix inside there. Two identical application entries for
"Xfce Terminal".

**Comment by qubenix** [comment] 2019-04-23 21:43
@unman

```
user@host:~$ grep Categories /usr/share/applications/xfce4-terminal{,-settings}.desktop
/usr/share/applications/xfce4-terminal.desktop:Categories=GTK;System;TerminalEmulator;
/usr/share/applications/xfce4-terminal-settings.desktop:Categories=XFCE;GTK;Settings;DesktopSettings;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;
```

**Comment by unman** [comment] 2019-04-24 23:40
So it's a function of how the Qubes menu items are processed. Indeed, not Whonix specific. Nor Debian either.
Any ideas? We clearly dont want to exclude *all* Settings .desktop files

**Comment by marmarek** [comment] 2019-06-27 14:00
I confirm those two desktop entries differs _only_ in `Exec` and `Categories` fields. Not even `Comment` or `GenericName`. Native XFCE menu probably distinguish based on `Categories`, but we flatten menu for VM.
May be mitigated by adding tooltip with desktop file name in VM settings (where you choose applications). Not ideal, but at least something.
Anyway, I think it is an upstream issue - even if those two "Xfce Terminal" entries are in different submenus ("Utilities" and "Settings") it is still confusing.

**Comment by andrewdavidwong** [comment] 2019-06-28 01:44
> Anyway, I think it is an upstream issue - even if those two "Xfce Terminal" entries are in different submenus ("Utilities" and "Settings") it is still confusing.

Closing as "not our bug." Please consider reporting this to the appropriate upstream project instead. If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2019-06-28 01:44 UTC
Labels: C: desktop-linux, P: default, T: bug
