### ISSUE TITLE
Cannot launch applications in a disposable VM from the Applications menu (silent failure)

### ISSUE THREAD

**Issue by tutaleedoo** [QubesOS/qubes-issues#3368] opened 2017-12-07 05:42 UTC
#### Qubes OS version:

Qubes release 4.0 (R4.0)

#### Affected TemplateVMs: 

fedora-25-dvm

---

### Steps to reproduce the behaviour:

1. Open the `Applications` menu
2. Mouse over `Disposable: fedora-25-dvm`
3. Select an application from the menu (for example, `fedora-25-dvm: XTerm`)

### Expected behaviour:

- A notification appears saying `Domain disp[0-9]+ is starting`
- A notification appears saying `Domain disp[0-9]+ is started`
- The application opens

### Actual behaviour:

- A notification appears saying `Domain disp[0-9]+ is starting`
- A notification appears saying `Domain disp[0-9]+ is started`
- The application does not open, and the disposable VM automatically shuts down

### General notes:

- No errors appear (silent failure)
- The application can successfully open in a disposable VM from the command line: `qvm-run --dispvm fedora-25-dvm xterm`
- Applications were installed in the fedora-25 template VM

---

**Comment by andrewdavidwong** [comment] 2017-12-07 06:36
This appears to be a duplicate of #3213. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2017-12-07 06:36 UTC

**Comment by jpouellet** [comment] 2017-12-12 23:18
May also be duplicate of https://github.com/QubesOS/qubes-issues/issues/3012 instead.
