### ISSUE TITLE
ubuntu templates build failure due to missing release file

### ISSUE THREAD

**Issue by ashadulhoque** [QubesOS/qubes-issues#5209] opened 2019-07-31 10:00 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Xenial, Bionic template build

**To Reproduce**
follow https://www.qubes-os.org/doc/templates/ubuntu/ and select xenial or bionic templates

**Expected behavior**
template RPMs are created and ready to be installed

**Actual behavior**
fails on 'make template'
```
W: The repository 'https://deb.qubes-os.org/r4.0/vm xenial Release' does not have a Release file.
E: Failed to fetch https://deb.qubes-os.org/r4.0/vm/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100
```

**Additional context**
xenail & bionic release file doesn't exit in https://deb.qubes-os.org/r4.0/

**Comment by marmarek** [comment] 2019-07-31 12:57
Duplicate of #4907

**Closed by marmarek** 2019-07-31 12:57 UTC
Labels: P: default, T: bug
