### ISSUE TITLE
USB ethernet adapter is not visible in "qvm-device usb list" when connected to dom0

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7873] opened 2022-11-11 17:06 UTC
### Qubes OS release
R4.1.1 and R4.0.

### Brief summary
Cannot see and use a USB ethernet adapter that is supported by kernel and plugged in dom0.

### Steps to reproduce
* Insert general USB-ethernet adapter.
* In dom0 `dmesg` shows it being recognized properly.
* In dom0 `ip link` shows it as `enp0s20u2`. So it kind of works in dom0.

### Expected behavior
The device `dom0:enp0s20u2` is present in the `qvm-device usb list`.

### Actual behavior
The device `dom0:enp0s20u2` is not in the list of `qvm-device usb list` nor in the Qubes Devices widget.

### Additional information
* I have only one USB controller, it's a laptop, not a standalone PC with extra PCI slots on motherboard, so the installer did not create sys-usb or something to manage USB outside of dom0.
* On other PC with R4.0 and a special qube for USB (manually created with one of PCI controller delegated to) I can use it alright, it's shown in Qubes Devices widget as `my-usb:3-2.3 ASIX_Elec.Corp....`, the same way as any block device.
* Use of block devices and usb hubs via dom0 works fine for me (`qvm-device block list` shows it). So, I expected USB adapter should work the same way if it works in separate net qube).

**Comment by jamke** [comment] 2022-11-11 18:06
I tried 2 USB-Wifi dongles and both were recognized in dom0 (as valid `ip link` wifi cards) but were not available in `qvm-devices`.
But if I use those dongles on other R4.0 PC with an AppVM for USB - both work fine and are visible in `qvm-devices` and Qubes Devices widget. So, it's some kind of bug or maybe limitation that I can somehow lift, can't I?

**Comment by marmarek** [comment] 2022-11-11 18:10
`qvm-usb` (`qvm-devices usb`) requires sys-usb VM, see https://www.qubes-os.org/doc/how-to-use-usb-devices/

**Comment by andrewdavidwong** [comment] 2022-11-12 01:36
> `qvm-usb` (`qvm-devices usb`) requires sys-usb VM, see https://www.qubes-os.org/doc/how-to-use-usb-devices/

Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2022-11-12 01:36 UTC
Labels: T: bug, P: default

**Comment by jamke** [comment] 2022-11-13 05:25
I see, so block devices from dom0 are exposed, but usb are not, right? OK, than I agree, it's not a bug.

**Is there any way to workaround it and allow usb devices being shown from dom0?** Maybe some hack or option, I understand the reasoning and security concerns. 
I have only one USB controller and I'm not sure it's possible to pass it to some AppVM (like sys-usb) and keep everything working.

**Comment by DemiMarie** [comment] 2022-11-13 06:45
@jamke do you use USB input devices?

**Comment by jamke** [comment] 2022-11-13 12:44
Yes, in this case it's a Macbook Pro and providing the only USB controller to any AppVM makes both keyboard and mouse unusable.
I cannot even connect to the internet - wifi requires broadcom proprietary drivers that I cannot download with all deps, and externel USB-Ethernet device, that is a great help in usual GNU/Linux, does not work because of this issue.

I can try to install sys-net even for single USB controller (it's possible, right?) but if there was some config option to lift the limitation of exposing dom0:usbs to other VMs, it would be a good start.
