### ISSUE TITLE
qvm-run doesn't work on systemd system-sleep scripts

### ISSUE THREAD

**Issue by gasull** [QubesOS/qubes-issues#4131] opened 2018-07-23 05:10 UTC
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

---

### Steps to reproduce the behavior:

In dom0:

```
$ sudoedit /usr/lib/systemd/system-sleep/suspend-resume.sh
$ chmod 755 /usr/lib/systemd/system-sleep/suspend-resume.sh
$ cat /usr/lib/systemd/system-sleep/suspend-resume.sh
#!/usr/bin/env bash
qvm-run --pass-io --verbose my-qube "echo hi" 2>&1 | systemd-cat -t suspend-resume
$ /usr/lib/systemd/system-sleep/suspend-resume.sh
$ journalctl --identifier=suspend-resume
-- Logs begin at (...) --
Jul 23 2:41:47 dom0 suspend-resume[7846]: Running 'echo hi' on my-qube
Jul 23 2:41:47 dom0 suspend-resume[7846]: hi
```
Close laptop, wait for it to suspend, open it again, then, in dom0:
```
$ journalctl --identifier=suspend-resume
-- Logs begin at (...) --
Jul 23 2:41:47 dom0 suspend-resume[7846]: Running 'echo hi' on my-qube
Jul 23 2:41:47 dom0 suspend-resume[7846]: hi
Jul 23 2:43:16 dom0 suspend-resume[7897]: Running 'echo hi' on my-qube
Jul 23 2:43:21 dom0 suspend-resume[7897]: vchan connection timeout
Jul 23 2:43:34 dom0 suspend-resume[7932]: Running 'echo hi' on my-qube
Jul 23 2:43:39 dom0 suspend-resume[7932]: vchan connection timeout
```

### Expected behavior:

The command `echo hi` should execute in `my-qube` and therefore `journalctl` on dom0 should return this instead:
```
Jul 23 2:43:16 dom0 suspend-resume[7897]: Running 'echo hi' on my-qube
Jul 23 2:43:21 dom0 suspend-resume[7897]: hi
Jul 23 2:43:34 dom0 suspend-resume[7932]: Running 'echo hi' on my-qube
Jul 23 2:43:39 dom0 suspend-resume[7932]: hi
```

### Actual behavior:

As said, `journalctl` on dom0 shows `echo hi` wasn't executed:
```
Jul 23 2:43:16 dom0 suspend-resume[7897]: Running 'echo hi' on my-qube
Jul 23 2:43:21 dom0 suspend-resume[7897]: vchan connection timeout
Jul 23 2:43:34 dom0 suspend-resume[7932]: Running 'echo hi' on my-qube
Jul 23 2:43:39 dom0 suspend-resume[7932]: vchan connection timeout
```

### General notes:

I tried other commands, like writing on the `journalctl` of  `my-qube` or writing a file in `my-qube`.  They work from the comand line in dom0, but not in the script for system-sleep.

---

### Related issues:

Possibly #2335

**Comment by Aekez** [comment] 2018-07-23 17:08
Isn't the detachment to the --pass-io feature after a suspend an intended security mechanism though? I mean, if it could be hijacked for example by substituting a similar signal, then maybe dom0 could be compromised if it wasn't blocking after having been temporarily cut-off by i.e. suspend? Way out of my league though, so I won't pretend to know the details, however I don't think this is a bug, but maybe a design (security) limitation? 
- For example, when re-attaching communication with dom0, how can dom0 be sure it is the same old signal from the VM as before, and not a compromised one trying to trick dom0?

Below quote is from https://www.qubes-os.org/doc/qrexec3/
> inter-VM communication must be tightly controlled to prevent one VM from taking control over other, possibly more privileged, VM. Therefore the design decision was made to pass all control communication via dom0, that can enforce proper authorization. Then, it is natural to reuse the already-existing qrexec framework.

> Also, note that bare qrexec provides VM <-> dom0 connectivity, but the command execution is always initiated by dom0. There are cases when VM needs to invoke and send data to a command in dom0 (e.g. to pass information on newly installed .desktop files). Thus, the framework allows dom0 to be the rpc target as well.

> Thanks to the framework, RPC programs are very simple – both rpc client and server just use their stdin/stdout to pass data. The framework does all the inner work to connect these processes to each other via qrexec-daemon and qrexec-agent.

Especially pay attention to this line from above, which might be missed if not carefully read.

> Therefore the design decision was made to pass all control communication via dom0, that can enforce proper authorization. Then, it is natural to reuse the already-existing qrexec framework.

The above might make more sense if reading up more on the Qubes RPC in general, and the differences between qrexec and qvm-run.

As I understand it, qvm-run is based on the qrexec framework, but the qrexec framework allows too extensive inter-VM communication, and qvm-run is therefore made to be a more secure version of qrexec framework. Using qvm-run --pass-io then gets you closer to the abilities of full fledged qrexec functionality (two-way signal) unlike only using qvm-run (one-way signal), but it looks like even if using qvm-run --pass-io it still won't allow reattaching old signals after having been cut-off (i.e. when suspended). 

An alternative, could maybe be to make a dom0 script that re-initiate a new qvm-run --pass-io job after suspending, rather than trying to regain the old VM-job, or run your service with qrexec framework instead of qvm-run? Each of those have other limitations though, like loosing existing app memory in VM, or wider security surface attack surface, respectively.

If you really, really need it, maybe you could make a different VM to control your other VM, rather than using dom0 as control VM, and then allow greater interVM communication (normally limited by qvm-run as a security feature) between these two VM's? You could give that a run with adjusting Qubes RPC inter-VM permissions.

As far as I can see the only way this can be implemented and allow reattachment of old VM jobs, wouldn't that be to have something akin to encryption hash key handshakes between dom0 and domU, or between domU's? This way it can establish some sort of trust, I guess. But is that feasible, maybe doing that has limitations on its own?

Reminder, details here is out of my league and I don't have a full understanding, but it sort of looks like this is a design (security) limitation, and not a bug.

**Comment by marmarek** [comment] 2018-07-23 17:33
> Jul 23 2:43:16 dom0 suspend-resume[7897]: Running 'echo hi' on my-qube Jul 23 2:43:21 dom0 suspend-resume[7897]: vchan connection timeout

All qubes are suspended/paused for the host suspend time, so at this point it is impossible to interact with them. You can work around this by creating new service ordered _before_ `qubes-suspend.service`. See `systemctl cat qubes-suspend.service` for example settings.

**Comment by andrewdavidwong** [comment] 2018-07-24 01:18
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2018-07-24 01:18 UTC
Labels: C: core, notanissue
