### ISSUE TITLE
Qubes VM Manager:  Qubes dom0 updates available: appears so often. Suspicious ?

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2510] opened 2016-12-10 16:41 UTC
#### Qubes OS version (e.g., `R3.2`):
R3.2

I noticed, that the message is coming up so many times a day. 

Are there really so many and so often updates becoming available ? It puzzles me, and perhaps you can find a better way to signal and inform about updates.

**Comment by andrewdavidwong** [comment] 2016-12-10 17:04
Duplicate of #2086.

**Closed by andrewdavidwong** 2016-12-10 17:04 UTC

**Comment by Wikinaut** [comment] 2016-12-10 17:10
@andrewdavidwong I saw the #2086 but my report is related to *real* updates (when there is really something to be updated). It appears so often.

**Comment by andrewdavidwong** [comment] 2016-12-11 04:04
Those updates are from Fedora. We're getting them because dom0 is based on a currently-supported Fedora version (for the moment), namely Fedora 23 in Qubes 3.2. This is in contrast to much of 3.1's lifespan, in which dom0 was based on an EOL Fedora version, namely Fedora 20.

https://www.qubes-os.org/doc/supported-versions/
