### ISSUE TITLE
Networking issues with fedora-25, debian-9 as NetVM template in 4.0rc1

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#2964] opened 2017-08-04 06:13 UTC
#### Qubes OS version (e.g., `R3.2`):
4.0rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-25, debian-9
---

### Expected behavior:
can use either or both of the templates for sys-net, sys-firewall.
### Actual behavior:
(on 2 computers): fedora-25 *almost never* works as sys-net, but does sometimes (so I don't get it).

Debian-8 as netVM works flawlessly, but when I updated that (fresh) template to debian-9, it also stopped forwarding to sys-firewall. 
Connectivity inside sys-net is fine, and/so connecting dom0 updater to the netVM directly does work.

**Comment by marmarek** [comment] 2017-08-06 21:50
Can you be more specific than "fedora-25 almost never works as sys-net"? What exactly happen?

**Comment by andrewdavidwong** [comment] 2017-08-06 23:22
I can confirm this on R3.2. When I try to use `fedora-25` or `fedora-25-minimal` as the TemplateVM for `sys-net`, I can connect to Wi-Fi networks as normal, but AppVMs have no internet connection. Switching `sys-net` back to `fedora-24*` immediately fixes it.

**Comment by 0spinboson** [comment] 2017-08-07 05:08
no packets are forwarded to sys-firewall or beyond. Compare these three logs of 'iptables -L -vn' run in sys-net, which are hopefully more informative. No rules added or changed by me, this is the out of the box configuration

[iptablesfc25.txt](https://github.com/QubesOS/qubes-issues/files/1203904/iptablesfc25.txt)
[iptablesd9.txt](https://github.com/QubesOS/qubes-issues/files/1203905/iptablesd9.txt)
[iptablesd8.txt](https://github.com/QubesOS/qubes-issues/files/1203906/iptablesd8.txt)

**Comment by marmarek** [comment] 2017-08-07 21:09
Can you include the same with `-t nat` option?

**Comment by 0spinboson** [comment] 2017-08-07 21:40
Of course:
[iptablesf25nat.txt](https://github.com/QubesOS/qubes-issues/files/1206250/iptablesf25nat.txt)
[iptablesd9nat.txt](https://github.com/QubesOS/qubes-issues/files/1206252/iptablesd9nat.txt)
[iptablesd8nat.txt](https://github.com/QubesOS/qubes-issues/files/1206251/iptablesd8nat.txt)

**Comment by marmarek** [comment] 2017-08-07 21:44
Looks ok... What is value of `/proc/sys/net/ipv4/ip_forward`?

**Comment by marmarek** [comment] 2017-08-07 21:45
(just one of broken cases is enough)

**Comment by 0spinboson** [comment] 2017-08-07 21:48
1

**Comment by tlaurion** [comment] 2017-09-07 05:33
Also have the bug. Any other troubleshooting paths to suggest? Other output that would help in troubleshooting this issue?

**Comment by andrewdavidwong** [comment] 2017-09-08 01:42
@tlaurion: In my case, it turned out that #3008 was the real problem. Blacklisting `iwlmvm` fixed it. (See the comments on that issue.)

**Comment by 0spinboson** [comment] 2017-09-08 08:41
Glad your issue was resolved, but I never use sleep/standby, and I also don't use wifi.

**Comment by marmarek** [comment] 2017-09-11 00:13
Maybe you can track with tcpdump where exactly the packets are lost?

**Comment by 0spinboson** [comment] 2017-10-25 16:06
I have no idea why, but for me the issue with fc25 and fc26 not being usable as the sys-net template has disappeared with rc2.

**Comment by andrewdavidwong** [comment] 2017-10-26 03:26
Closing this as "resolved" for now. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2017-10-26 03:26 UTC
Labels: bug, C: Debian, C: Fedora
