### ISSUE TITLE
R4.1 All non-dom0 qubes are failing in qubes-update-gui

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6284] opened 2020-12-14 08:12 UTC
Error on updating debian-11: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=debian-11', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.

<details>
<summary>qubes-updater log</summary>

```
Updating debian-11

Error on updating debian-11: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=debian-11', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
debian-11:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:

Updating fedora-32

Error on updating fedora-32: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=fedora-32', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
fedora-32:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:

Updating personal

Error on updating personal: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=personal', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
personal:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:

Updating whonix-gw-15

Error on updating whonix-gw-15: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=whonix-gw-15', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
whonix-gw-15:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:

Updating whonix-ws-15

Error on updating whonix-ws-15: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=whonix-ws-15', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
whonix-ws-15:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:

```

</details>

## Steps to reproduce
0. Get Qubes R4.1
1. Run `qubes-update-gui` and expect failure while trying to update any non-dom0 VM

---

May be related to https://github.com/QubesOS/qubes-issues/issues/6283

**Comment by marmarek** [comment] 2020-12-14 13:00
Duplicate of https://github.com/QubesOS/qubes-issues/issues/6188

**Closed by marmarek** 2020-12-14 13:00 UTC
Labels: P: default, T: bug
