### ISSUE TITLE
[R3.2] Installer fails becuase 'chrony' is missing

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2147] opened 2016-07-03 09:26 UTC
#### Qubes OS version (e.g., `R3.1`):
R3.2 RC 1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
N/A

---

### Expected behavior:
Installer successfully installs Qubes R3.2.

### Actual behavior:
During the installation after all the installation options is set a windows pop-ups and that says:

> You have specified that the package 'chrony' should be installed. This package does not exist. Would you like to ignore this package and continue with installation?

### Steps to reproduce the behavior:
I don't that if some specific setting is causing this. I only set

* Time zone
* Install both KDE and XFCE
* Automatically partition the SSD.
* Add local keyboard layout

### General notes:
* The Qubes ISO file was verified by the SHA512 sum (that in itself had been verified against Qubes' 3 release key).
* Tested three times, with rewriting the ISO file to the USB drive between the second and third attempt.
* On every test I used the "test this medium and install Qubes R3.2 RC-1" option.

**Comment by andrewdavidwong** [comment] 2016-07-03 15:14
Possible duplicate of #2110.

As described in that issue, several users have reported that the installer proceeds after the `chrony` warning. Please describe what you mean when you say that the installer "fails."

**Comment by marmarek** [comment] 2016-07-12 21:16
Yes, duplicate.

**Closed by marmarek** 2016-07-12 21:16 UTC
Labels: duplicate
