### ISSUE TITLE
Unable to create Kali HVM - Libvirt.error

### ISSUE THREAD

**Issue by PjMpire** [QubesOS/qubes-issues#2784] opened 2017-04-30 03:33 UTC
QubesOS version R3.2

### Expected behaviour:

HVM loads ISO for install

### Actual behaviour:

"Libvirt.error" libxenlight failed to create new domain"

### Step to reproduce behaviour:

`qvm-start KaliRolling --cdrom=personal:/home/user/Dowloads/kali-linux-2016.2-amd64.iso`

Whilst attempting to install Kali in HVM an error occurs:

```
[Anon@dom0:~]qvm-start KaliRolling --cdrom=personal:/home/user/Dowloads/kali-linux-2016.2-amd64.iso
--> Loading the VM (type = HVM)...
Traceback (most recent call last):
  File "/usr/bin/qvm-start", line 136, in <module>
    main()
  File "/usr/bin/qvm-start", line 120, in main
    xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
    return super(QubesHVm, self).start(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1972, in start
    self.libvirt_domain.createWithFlags(libvirt.VIR_DOMAIN_START_PAUSED)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1059, in createWithFlags
    if ret == -1: raise libvirtError ('virDomainCreateWithFlags() failed', dom=self)
libvirt.libvirtError: internal error: libxenlight failed to create new domain 'KaliRolling'
```

### General notes:

Libxl-driver.log

```
Anon@dom0 ~]$ sudo cat /var/log/libvirt/libxl/libxl-driver.log

2017-04-29 07:29:35 BST libxl: error: libxl_dm.c:1689:stubdom_xswait_cb: Stubdom 25 for 24 startup: startup timed out
2017-04-29 07:29:35 BST libxl: error: libxl_create.c:1342:domcreate_devmodel_started: device model did not start: -9
2017-04-29 07:29:35 BST libxl: error: libxl_device.c:1006:device_backend_callback: unable to remove device with path /local/domain/5/backend/vbd/25/51760
2017-04-29 07:29:35 BST libxl: error: libxl_device.c:1006:device_backend_callback: unable to remove device with path /local/domain/5/backend/vbd/24/51760
2017-04-29 07:29:35 BST libxl: error: libxl.c:1699:devices_destroy_cb: libxl__devices_destroy failed for 25
2017-04-29 07:29:35 BST libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/block remove [16949] exited with error status 1
2017-04-29 07:29:35 BST libxl: error: libxl_device.c:1138:device_hotplug_child_death_cb: script: /etc/xen/scripts/block failed; error detected.
2017-04-29 07:29:35 BST libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/block remove [16934] exited with error status 1
2017-04-29 07:29:35 BST libxl: error: libxl_device.c:1138:device_hotplug_child_death_cb: script: /etc/xen/scripts/block failed; error detected.
2017-04-29 07:29:35 BST libxl: error: libxl.c:1699:devices_destroy_cb: libxl__devices_destroy failed for 24
```

**Comment by andrewdavidwong** [comment] 2017-04-30 16:28
Possible duplicate of #2753.

**Comment by HellboundTKR** [comment] 2017-04-30 20:02
lsmod in personal appVM shows 'xen_blkback' loaded. Used '0'

**Comment by andrewdavidwong** [comment] 2019-04-01 04:08
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Closed by andrewdavidwong** 2019-04-01 04:08 UTC
Labels: C: core, T: bug
