### ISSUE TITLE
PV-mode VM fails to start with kernel 5.x

### ISSUE THREAD

**Issue by tabbyrobin** [QubesOS/qubes-issues#7560] opened 2022-06-12 22:39 UTC
### Qubes OS release

4.0

### Brief summary

PV-mode VM fails to start with kernels 5.4, 5.18. 
A VM set to PV mode will boot with kernel 4.19.125-1, but fails to boot with some other kernel versions, including: 5.4.x, 5.18.x. 

I have reproduced the errors with 5.4 on my machine. Someone else on the qubes IRC reproduced the issue with 5.18.

### Steps to reproduce

Have several kernel versions installed, including for example 4.19.125 and 5.4.x.
Set a VM (for example sys-usb or sys-net) to PV mode.
Try to boot VM on 4.19. (Succeeds)
Try to boot VM on 5.4. (Fails: "Connection to the VM failed")

### Expected behavior

VM should boot with both kernel versions.

### Actual behavior

VM only boots with 4.19, fails with 5.4. (etc)

### Other info

Note: My device requires PV mode for sys-usb and sys-net because it does not support IOMMU.

Possibly related documents: 

issue #1354

https://www.qubes-os.org/news/2022/03/10/qsb-078/

https://www.qubes-os.org/doc/managing-vm-kernels/  "If you require PV mode, install grub2-xen in dom0 and change the template’s kernel to pvgrub2."  But this doesnt have much context on *why* to use grub2-xen / pvgrub2 (presumably, other than if the desire is to use a custom kernel from inside the template).

**Comment by xaki23** [comment] 2022-06-12 22:46
can repro this straight away on 4.1.
* took one of my aux USB VMs, 
* switched it from hvm to pv, 
* tried to start with 5.18.3: doesnt start
* switched to 4.19: works

```
[2022-06-13 00:08:21] [    0.526799] #PF: supervisor read access in kernel mode
[2022-06-13 00:08:21] [    0.526802] #PF: error_code(0x0000) - not-present page
[2022-06-13 00:08:21] [    0.526805] PGD 3d5f9067 P4D 3d5f9067 PUD 3dea067 PMD 3deb067 PTE 0
[2022-06-13 00:08:21] [    0.526810] Oops: 0000 [#1] PREEMPT SMP NOPTI
[2022-06-13 00:08:21] [    0.526814] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.18.3-1.fc32.qubes.x86_64 #1
[2022-06-13 00:08:21] [    0.526818] RIP: e030:pmc_core_probe+0x136/0x210
[2022-06-13 00:08:21] [    0.526824] Code: eb a4 e8 bd df 2c 00 48 8d 7d 28 48 c7 c2 10 53 6f 83 48 c7 c6 29 8c 71 82 e8 96 89 66 ff 48 8b 45 10 48 63 40 50 48 03 45 08 <8b> 00 48 8b 55 10 4c 89 e7 8b 4a 54 ba 01 00 00 00 48 d3 e2 21 d0
[2022-06-13 00:08:21] [    0.526831] RSP: e02b:ffffc9004000bc48 EFLAGS: 00010286
[2022-06-13 00:08:21] [    0.526835] RAX: ffffc900401bb818 RBX: ffffffff82b01fa8 RCX: 0000000000000000
[2022-06-13 00:08:21] [    0.526838] RDX: ffffffff836f5310 RSI: ffffffff82718c29 RDI: ffff888007cd6350
[2022-06-13 00:08:21] [    0.526842] RBP: ffff888007cd6328 R08: 0000000000000000 R09: 00000000fe001fff
[2022-06-13 00:08:21] [    0.526845] R10: 0000000000007ff0 R11: ffffc900401ba000 R12: ffff8880060a7800
[2022-06-13 00:08:21] [    0.526849] R13: ffff8880060a7810 R14: 0000000000000006 R15: c37ff82c474e6301
[2022-06-13 00:08:21] [    0.526856] FS:  0000000000000000(0000) GS:ffff88803d000000(0000) knlGS:0000000000000000
[2022-06-13 00:08:21] [    0.526860] CS:  e030 DS: 0000 ES: 0000 CR0: 0000000080050033
[2022-06-13 00:08:21] [    0.526863] CR2: ffffc900401bb818 CR3: 0000000002810000 CR4: 0000000000050660
[2022-06-13 00:08:21] [    0.526868] Call Trace:
[2022-06-13 00:08:21] [    0.526871]  <TASK>
[2022-06-13 00:08:21] [    0.527701]  platform_probe+0x3f/0x90
[2022-06-13 00:08:21] [    0.527701]  call_driver_probe+0x24/0xc0
[2022-06-13 00:08:21] [    0.527701]  really_probe+0x18e/0x2a0
[2022-06-13 00:08:21] [    0.527701]  __driver_probe_device+0xfe/0x180
[2022-06-13 00:08:21] [    0.527701]  driver_probe_device+0x1e/0x90
[2022-06-13 00:08:21] [    0.527701]  __device_attach_driver+0x72/0xe0
[2022-06-13 00:08:21] [    0.527701]  ? driver_allows_async_probing+0x50/0x50
[2022-06-13 00:08:21] [    0.527701]  ? driver_allows_async_probing+0x50/0x50
[2022-06-13 00:08:21] [    0.527701]  bus_for_each_drv+0x8f/0xd0
[2022-06-13 00:08:21] [    0.527701]  __device_attach+0xe9/0x1f0
[2022-06-13 00:08:21] [    0.527701]  bus_probe_device+0x8e/0xa0
[2022-06-13 00:08:21] [    0.527701]  device_add+0x3fa/0x630
[2022-06-13 00:08:21] [    0.527701]  ? complete_all+0x20/0x90
[2022-06-13 00:08:21] [    0.527701]  platform_device_add+0x102/0x230
[2022-06-13 00:08:21] [    0.527701]  pmc_core_platform_init+0xe4/0x130
[2022-06-13 00:08:21] [    0.527701]  ? pmc_core_driver_init+0x40/0x40
[2022-06-13 00:08:21] [    0.527701]  do_one_initcall+0x57/0x230
[2022-06-13 00:08:21] [    0.527701]  do_initcalls+0x109/0x166
[2022-06-13 00:08:21] [    0.527701]  kernel_init_freeable+0x1ac/0x216
[2022-06-13 00:08:21] [    0.527701]  ? rest_init+0xd0/0xd0
[2022-06-13 00:08:21] [    0.527701]  kernel_init+0x16/0x130
[2022-06-13 00:08:21] [    0.527701]  ret_from_fork+0x22/0x30
[2022-06-13 00:08:21] [    0.527701]  </TASK>
[2022-06-13 00:08:21] [    0.527701] Modules linked in:
[2022-06-13 00:08:21] [    0.527701] CR2: ffffc900401bb818
[2022-06-13 00:08:21] [    0.527701] ---[ end trace 0000000000000000 ]---
[2022-06-13 00:08:21] [    0.527701] RIP: e030:pmc_core_probe+0x136/0x210
[2022-06-13 00:08:21] [    0.527701] Code: eb a4 e8 bd df 2c 00 48 8d 7d 28 48 c7 c2 10 53 6f 83 48 c7 c6 29 8c 71 82 e8 96 89 66 ff 48 8b 45 10 48 63 40 50 48 03 45 08 <8b> 00 48 8b 55 10 4c 89 e7 8b 4a 54 ba 01 00 00 00 48 d3 e2 21 d0
[2022-06-13 00:08:21] [    0.527701] RSP: e02b:ffffc9004000bc48 EFLAGS: 00010286
[2022-06-13 00:08:21] [    0.527701] RAX: ffffc900401bb818 RBX: ffffffff82b01fa8 RCX: 0000000000000000
[2022-06-13 00:08:21] [    0.527701] RDX: ffffffff836f5310 RSI: ffffffff82718c29 RDI: ffff888007cd6350
[2022-06-13 00:08:21] [    0.527701] RBP: ffff888007cd6328 R08: 0000000000000000 R09: 00000000fe001fff
[2022-06-13 00:08:21] [    0.527701] R10: 0000000000007ff0 R11: ffffc900401ba000 R12: ffff8880060a7800
[2022-06-13 00:08:21] [    0.527701] R13: ffff8880060a7810 R14: 0000000000000006 R15: c37ff82c474e6301
[2022-06-13 00:08:21] [    0.527701] FS:  0000000000000000(0000) GS:ffff88803d000000(0000) knlGS:0000000000000000
[2022-06-13 00:08:21] [    0.527701] CS:  e030 DS: 0000 ES: 0000 CR0: 0000000080050033
[2022-06-13 00:08:21] [    0.527701] CR2: ffffc900401bb818 CR3: 0000000002810000 CR4: 0000000000050660
[2022-06-13 00:08:21] [    0.527701] Kernel panic - not syncing: Fatal exception
[2022-06-13 00:08:21] [    0.527701] Kernel Offset: disabled
```

**Comment by marmarek** [comment] 2022-06-12 22:51
Duplicate of #6052

**Comment by xaki23** [comment] 2022-06-12 22:52
(ffs. i _was_ looking for duplicates, but didnt go back to 2020...)

**Closed by marmarek** 2022-06-12 22:51 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2022-06-13 02:41
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
