### ISSUE TITLE
VM window content stops updating

### ISSUE THREAD

**Issue by gangamstyle** [QubesOS/qubes-issues#7934] opened 2022-12-06 16:11 UTC
### Qubes OS release
4.1.1

### Brief summary
I started to see this bug ~1 month ago.
VM - debian 11 PVH
Everything works fine and suddenly content of a windows stops updating (for example scrolling Firefox website does not change the content of the window, window image is "freezed").
If I minimize-maximize affected window - it refreshes it's content, so application is working fine.
The only way to fix it is to restart affected application.
This bug is linked to application, if I start other application inside this VM it works fine.

**Comment by marmarek** [comment] 2022-12-06 16:14
Duplicate of #7695

**Comment by andrewdavidwong** [comment] 2022-12-06 17:45
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed as not planned by andrewdavidwong** 2022-12-06 17:45 UTC
Labels: R: duplicate, P: default
