### ISSUE TITLE
qubes-gui-agent broken after updating debian buster due to uninstallable dependencies

### ISSUE THREAD

**Issue by larsthegeek** [QubesOS/qubes-issues#4144] opened 2018-07-25 17:01 UTC
### Qubes OS version:

4.0

### Affected component(s): 
breaks all apps using template that require gui

---

### Steps to reproduce the behavior:

Run **sudo apt-get update** on debian buster template vm

During update process, qubes-gui-agent is broken, connection to template vm is lost, and access to template vm can only happen via **sudo xl console debian-10**

### Expected behavior:

apps will update, nothing will  be broken

### Actual behavior:

qubes-gui-agent ends up with broken dependency for **xserver-xorg-video-dummyqbs**, which itself is broken because of uninstallable dependency on **xorg-video-abi-23**

### General notes:

---

**Comment by marmarek** [comment] 2018-07-26 00:17
Duplicate of #4140

**Closed by marmarek** 2018-07-26 00:17 UTC
