### ISSUE TITLE
Shortcut to switch between windows of current application doesn't work across VMs

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2002] opened 2016-05-18 19:14 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

All

---
### Expected behavior:

Another window with the same application comes into focus, even if the other window is run by another VM.
### Actual behavior:

Nothing happens.
### Steps to reproduce the behavior:
1. Start [application] in [AppVM_1]
2. Start [application] in [AppVM_2]
3. Set focus on [application] in either [AppVM_1] or [AppVM_2]
4. Press `Alt+`` or `Alt+~` (the default key bindings in KDE)
### General notes:

---
#### Relevant labels:
- Bug
- UX
- P: minor

**Comment by andrewdavidwong** [comment] 2016-05-18 19:58
Generally, window classes in Qubes work differently than in standard KDE. Currently, by default, the window class is the domain. From that perspective, it makes sense that windows from the "same" application in two different VMs will not be treated as two windows from the same application. Arguably, they're not *really* (i.e., not *merely*) two windows from the same application. Rather, they're two windows from *two instances of one application running in separate VMs*. That's why I'm reticent to call this a bug. Depending on the UX approach, this may be a feature, not a bug. It may just be "the Qubes way."

**Comment by unman** [comment] 2016-05-19 00:37
The statement of  "expected behaviour" shows confusion.
If it is "Another window with the same application comes into focus", then the actual behaviour matches this.

As @andrewdavidwong says, following the steps given, they are two instances. I would say of *different* applications. 
Insert Step 1a: Wait 10 minutes. 
Then ask if these are the *same* application - When was app1 started? When app2?

**Comment by ttasket** [comment] 2016-06-14 21:08
This is less a bug than an idiosyncrasy of Qubes. The window manager examines each app as object references in its environment, so in dom0 the WM sees vms as the separate apps. If I run 2 firefox windows and a tbird window all in the same vm, then Alt-tilde switches between all of them.

IOW, the app 'name' isn't used and even if it were, you would get names like "personal" and "untrusted"; just vm names. The rest of the titlebar contents you see will often change depending on the document or address being used at the moment.

There is also a question of whether a window manager in Qubes *should* try to associate UI elements by app name. This can affect a user's view and workflow on their desktop depending on a *claim* by a domU app.

**Comment by andrewdavidwong** [comment] 2016-12-24 06:41
Closing as `notanissue`.

**Closed by andrewdavidwong** 2016-12-24 06:41 UTC
Labels: C: desktop-linux, P: minor, UX
