### ISSUE TITLE
systray app not opening as systray icon but big window

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2268] opened 2016-08-25 20:29 UTC
#### Qubes OS version (e.g., `R3.1`):

R3.2 with testing repository

(KDE)
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-8 (others untested)

---
### Steps to reproduce the behavior:

Start a Debian 8 based VM.

`sudo apt-get install klipper`

Then start from command line, run `klipper`.
### Actual behavior:

The systray app does not open as a small systray icon in the systray, but that small symbol will be zoomed up and be place at the top left as a window without borders that takes approximately one quarter of the screen.

The right click menu of that "systray" is fully functional. The window does not appear in the real systray.

This also happens when starting klipper from Qubes start menu.
### Related:

Different from #2264.

**Comment by adrelanos** [comment] 2016-08-25 20:40
This issue is gone for now after reboot. Happened after not having reboot my computer for several days.

**Comment by andrewdavidwong** [comment] 2016-08-25 20:40
Similar to/duplicate of #2216?

**Comment by adrelanos** [comment] 2016-08-25 21:49
Thanks for cross referencing them! Really helps avoiding duplicates and eases contributing information to existing issues.

@andrewdavidwong 
> Similar to/duplicate of #2216?

No.

(#2216 is about transparency, this is not happening here at all. This ticket is about a big sized window appearing rather than a systray appearing.)

**Comment by andrewdavidwong** [comment] 2019-04-01 03:58
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Closed by andrewdavidwong** 2019-04-01 03:58 UTC
Labels: C: desktop-linux, C: gui-virtualization, T: bug
