### ISSUE TITLE
Qube Manager: Disk Usage does not match `df -hs /rw`

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8870] opened 2024-01-15 11:30 UTC
### Qubes OS release

4.1.2
4.2.0

### Brief summary

Qube Manager: Disk Usage does not match `df -hs /rw`

### Steps to reproduce

Check "Disk Usage" for a qube in Qube Manager.
Compare it to `df -hs /rw` in the qube.

### Expected behavior

The two should match (or at least be close).

### Actual behavior

The differ, often significantly (e.g. 2x).

Note: I understand this is based on private volume usage, however it doesn't give good idea of actual storage usage which is what matters to the user. In case this is assumed to work as expected, please consider this an enhancement request.

**Comment by marmarta** [comment] 2024-01-15 11:59
looks like duplicate of https://github.com/QubesOS/qubes-issues/issues/7535

**Closed by marmarta** 2024-01-15 11:59 UTC
Labels: T: bug, P: default
