### ISSUE TITLE
allow setting Template to none in Qubes VM Manager (QVMM)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4437] opened 2018-10-26 08:23 UTC
feature request:

QVMM -> Template -> `(None)`

Similar to how networking can be set to `(None)`.

use case:

https://www.qubes-os.org/doc/reinstall-template/ quote:

```
Create a temporary dummy template:

 mkdir /var/lib/qubes/vm-templates/dummy
 touch /var/lib/qubes/vm-templates/dummy/{root.img,private.img}
 qvm-add-template dummy
```

This could be simplified by `QVMM -> Template -> (None)`.

This would prevent users from forgetting to change back the setting from an unrelated template. In case of Whonix reinstallation it would be very bad to accidentally start a supposedly Whonix AppVM using a lets say Fedora TemplateVM.

**Comment by marmarek** [comment] 2018-10-26 11:17
You mean allow setting to none and error on starting such VM, until template is set back to some actual template?
I'm pretty sure this was discussed before, but can't find it now.

**Comment by adrelanos** [comment] 2018-10-26 12:15
Marek Marczykowski-Górecki:
> You mean allow setting to none and error on starting such VM, until template is set back to some actual template?

Yes.

> but can't find it now.

Me neither. The only thing I can remember is me asking on the mailing
list and then being explained how to create a dummy template.

**Comment by andrewdavidwong** [comment] 2018-10-26 12:16
Duplicate of #2062

**Closed** 2018-10-26 12:17 UTC

**Comment by adrelanos** [comment] 2018-10-26 13:10
https://github.com/QubesOS/qubes-issues/issues/2062 was `Please have an option for qvm-prefs as well as in QVMM to allow setting the template to none.`

* First part `qvm-create --class TemplateVM --label red dummy` was implemented
* but second part `implement QVMM template (None) setting` was not implemented.

I don't think `implement QVMM template (None) setting` was rejected as a bad idea or so.

Could you please reopen https://github.com/QubesOS/qubes-issues/issues/2062 (maybe strictly correct) or re-open this one (perhaps more concise was's missing) so this serves its purpose as `implement QVMM template (None) setting` ticket?
