### ISSUE TITLE
Qubes disk free space not available

### ISSUE THREAD

**Issue by leonardo-dc** [QubesOS/qubes-issues#3907] opened 2018-05-18 16:51 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

dom0 (qubes_dom0/pool00)

---

### Steps to reproduce the behavior:

Free disk space does not increase/available (after files removal).

### Expected behavior:

I must be able to use the free disk space again after deleting my files.

### Actual behavior:

I just remove about 100GB of files from the Dom0.

But even after that, for example, in one of my VM I continue have a problem with an early filling of free space:

```
user@host:~$ df -h | egrep "/rw|Used"
Filesystem          Size  Used Avail Use% Mounted on
/dev/xvdb           260G  228G   33G  88% /rw


user@host:~$ sudo fallocate -l 9G /test
fallocate: fallocate failed: No space left on device


user@host:~$ sudo du -sh /test
6.7G	/test


user@host:~$ df -h | egrep "/rw|Used"
Filesystem          Size  Used Avail Use% Mounted on
/dev/xvdb           260G  228G   33G  88% /rw
```

These values are constant (free space decreases but does not increase [after removal files or VMs]):
```
user@dom0 ~ % sudo lvs qubes_dom0/pool00                  
  LV     VG         Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  pool00 qubes_dom0 twi-aotz-- 453.17g             91.85  41.55                           
```

### General notes:

I have about 282GB date on my 453GB pool00 and the strange `No space left on device` error.

I ran a disk check with `sudo fsck -f /dev/mapper/qubes_dom0-vm--my--vm--private`
And also ran `sudo pvck -v /dev/mapper/luks-efirowmc-ei3o-9381-9d93-d8209d0j3ice`

Any help is appreciated. How-to free disk space for use?

---

**Comment by marmarek** [comment] 2018-05-18 17:49
`/test` is not in `/rw`, so the above test isn't accurate.
Anyway, make sure you have 'discard` option enabled for `/` in dom0 and template(s) (/etc/fstab). It should be there for fresh 4.0 install, but if you've update from earlier release candidates it might be missing. Alternatively run `fstrim` manually after removing files.

**Comment by leonardo-dc** [comment] 2018-05-19 03:35
You are right. The `fstrim` at dom0 helps me. Thank you!

```
user@dom0 ~ % sudo lvs qubes_dom0/pool00                  
  LV     VG         Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  pool00 qubes_dom0 twi-aotz-- 453.17g             66.43  31.15                           
```

**Comment by andrewdavidwong** [comment] 2018-05-19 06:00
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-05-19 06:00 UTC
Labels: C: other
