### ISSUE TITLE
Qubes Manager - does not reflect changes in qube properties

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3675] opened 2018-03-08 16:56 UTC
#### Qubes OS version:

4.0rc5

#### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

Change label , netvm or other properties.

### Expected behavior:

Manager will reflect change

### Actual behavior:

No change

### General notes:

I understand the reason for this, (no longer synchronous change to minimise problems that 3.2 version had), but want to capture this. 

---

#### Related issues:

#3572

**Comment by u2482** [comment] 2018-03-11 01:28
I came here to mention this too.
More significantly, State doesn't change; whether it is running or updates are available.
The fields get updated if you select a qube and move off it.

**Comment by andrewdavidwong** [comment] 2018-12-17 01:08
Reopening due to apparent regression reported in #4622.

**Comment by andrewdavidwong** [comment] 2020-01-19 22:21
Reopening due to apparent regression reported in #5587.

**Comment by marmarta** [comment] 2020-03-26 15:03
I'm unable to reproduce. Updating label was fixed in https://github.com/QubesOS/qubes-manager/commit/3cf9ff3ee2b2c3336e186d697b2fc81e200a460b and VM class cannot be changed.

**Closed by marmarta** 2020-03-26 15:03 UTC
Labels: C: manager/widget, P: major, T: bug, r4.0-dom0-stable, ux
