### ISSUE TITLE
Error refreshing AppMenus for Windows AppVM

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#4863] opened 2019-03-07 15:16 UTC
### Qubes OS version:

Qubes R 4.01

### Affected component(s) or functionality:

Using a relatively fresh install of Qubes 4.01 on which a fresh Windows 7 AppVm has been installed, with QWT installed.

Trying to refresh the Applications Menus (in VM Properties) fails with a message :+1: 

« Command '['qvm-sync-appmenus','vmname'] returned non-zero exit status 1. »

Typing said command in a dom0 terminal results in an error that boils down to : 
 
« FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qubes-appmenus/qubes-start.desktop' »

---

### Steps to reproduce the behavior:

Install a Windows VM, try to update its AppMenu.

### Expected or desired behavior:

It should work ;)

### Actual behavior:

It fails :(

### General notes:

The Windows VM also lacks a proper « Start » entry in its menu after creation, so it has to be started from Qube Manager.

---

**Comment by andrewdavidwong** [comment] 2019-03-08 02:00
Duplicate of #4684

**Comment by andrewdavidwong** [comment] 2019-03-08 02:00
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-03-08 02:00 UTC
