### ISSUE TITLE
Some manpages aren't rendered correctly

### ISSUE THREAD

**Issue by meithecatte** [QubesOS/qubes-issues#7978] opened 2023-01-08 19:38 UTC
### Qubes OS release

Qubes R4.1

### Brief summary

`man qrexec-client-vm` shows HTML for some reason.

### Steps to reproduce

Run `man qrexec-client-vm` on either a Fedora or Debian template (others untested). The relevant package is `qubes-core-qrexec` version `4.1.20-1+deb11u1` on Debian (couldn't be bothered to look up how to check this on Fedora :upside_down_face:).

### Expected behavior

A human-readable manpage.

### Actual behavior

This, technically also human-readable, eyesore:

```
<h1        id="qrexec‐client‐vm">qrexec‐client‐vm</h1>        <h2
id="name">NAME</h2> <p>qrexec‐client‐vm ‐  call  Qubes  RPC  ser‐
vice</p>   <h2   id="synopsis">SYNOPSIS</h2>   <div  class="line‐
block">qrexec‐client‐vm  [‐‐buffer‐size=*BUFFER_SIZE*]   <em>tar‐
get_vmname</em> <em>service</em> [<em>local_program</em> [<em>lo‐
cal program arguments</em>]]</div> <h2  id="description">DESCRIP‐
TION</h2>  <p>Call  Qubes RPC (aka qrexec) service to a different
```

**Comment by marmarek** [comment] 2023-01-09 00:11
Duplicate of https://github.com/QubesOS/qubes-issues/issues/7041

**Closed by marmarek** 2023-01-09 00:11 UTC
Labels: T: bug, P: default

**Comment by andrewdavidwong** [comment] 2023-01-09 15:39
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
