### ISSUE TITLE
qubes-global-config crashes due to empty response from qubesd

### ISSUE THREAD

**Issue by feskehau** [QubesOS/qubes-issues#8550] opened 2023-09-27 08:58 UTC
### Qubes OS release
Qubes 4.2.0-rc3

### Brief summary
Launching Qubes Global Config after a fresh install of 4.2-rc3 crashes due to empty response from qubesd.

### Steps to reproduce
* Download Qubes R4.2.0-rc3 ISO
```
wget https://ftp.qubes-os.org/iso/Qubes-R4.2.0-rc3-x86_64.iso
```
* Install the system as normal and launch qubes-global-config

### Expected behavior
Qubes Global Config tool launches as normal.

### Actual behavior
Tool crashes when starting up.

```
$ qubes-global-config 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/global_config.py", line 207, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/global_config.py", line 285, in perform_setup
    self.handlers['usb'] = DevicesHandler(
                           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/usb_devices.py", line 634, in __init__
    for device in vm.devices['pci'].attached():
  File "/usr/lib/python3.11/site-packages/qubesadmin/devices.py", line 222, in attached
    yield assignment.device
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/devices.py", line 74, in device
    return self.backend_domain.devices[self.devclass][self.ident]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/devices.py", line 282, in __getitem__
    for dev in self.available():
  File "/usr/lib/python3.11/site-packages/qubesadmin/devices.py", line 235, in available
    self._vm.qubesd_call(None,
  File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 770, in qubesd_call
    return self._parse_qubesd_response(return_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 89, in _parse_qubesd_response
    raise qubesadmin.exc.QubesDaemonAccessError(
qubesadmin.exc.QubesDaemonAccessError: Got empty response from qubesd. See journalctl in dom0 for details.
```

```
journalctl -u qubesd.service:

Sep 27 10:27:47 dom0 qubesd[2387]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.pci.Available' dest=b'dom0' arg=b'' len(untrusted_payload)=0
Sep 27 10:27:47 dom0 qubesd[2387]: Traceback (most recent call last):
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/api/__init__.py", line 297, in respond
Sep 27 10:27:47 dom0 qubesd[2387]:     response = await self.mgmt.execute(
Sep 27 10:27:47 dom0 qubesd[2387]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/api/admin.py", line 1195, in vm_device_available
Sep 27 10:27:47 dom0 qubesd[2387]:     devices = self.dest.devices[devclass].available()
Sep 27 10:27:47 dom0 qubesd[2387]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 376, in available
Sep 27 10:27:47 dom0 qubesd[2387]:     devices = self._vm.fire_event('device-list:' + self._bus)
Sep 27 10:27:47 dom0 qubesd[2387]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 195, in fire_event
Sep 27 10:27:47 dom0 qubesd[2387]:     sync_effects, async_effects = self._fire_event(event, kwargs,
Sep 27 10:27:47 dom0 qubesd[2387]:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 168, in _fire_event
Sep 27 10:27:47 dom0 qubesd[2387]:     effects.extend(effect)
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/ext/pci.py", line 192, in on_device_list_pci
Sep 27 10:27:47 dom0 qubesd[2387]:     yield PCIDevice(vm, None, libvirt_name=libvirt_name)
Sep 27 10:27:47 dom0 qubesd[2387]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 27 10:27:47 dom0 qubesd[2387]:   File "/usr/lib/python3.11/site-packages/qubes/ext/pci.py", line 141, in __init__
Sep 27 10:27:47 dom0 qubesd[2387]:     assert dev_match
Sep 27 10:27:47 dom0 qubesd[2387]: AssertionError
```

**Comment by marmarek** [comment] 2023-09-27 14:42
This looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/6932, I've added info that it affects R4.2 too.

**Comment by feskehau** [comment] 2023-09-27 16:09
Thanks, had a look at the refrence. Disabled Intel raid on in bios and this resolved itself after a reinstall.On 27 Sep 2023, at 16:42, Marek Marczykowski-Górecki ***@***.***> wrote:﻿
This looks like a duplicate of #6932, I've added info that it affects R4.2 too.

**Comment by andrewdavidwong** [comment] 2023-09-27 21:03
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2023-09-27 21:03 UTC
Labels: T: bug, P: default
