### ISSUE TITLE
Change default locker from xfce4-screensaver to lightdm greeter

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8432] opened 2023-08-18 10:23 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

I propose this change because the default xfce4 locker is very difficult to customize. I didn’t have any bugs with him for the entire time of use.

### The value to a user, and who that user might be
They will be able to better diversify the look of the lock screen

**Comment by andrewdavidwong** [comment] 2023-08-18 12:35
Duplicate of #1917

**Closed** 2023-08-18 12:35 UTC
Labels: T: enhancement, P: default

**Comment by Middenvaus** [comment] 2023-08-18 17:27
No, I meant to include locker lightdm greeter instead of xscreensaver in the qubes os installer. Is it possible?

**Comment by andrewdavidwong** [comment] 2023-08-19 01:52
> No, I meant to include locker lightdm greeter instead of xscreensaver in the qubes os installer.

Isn't that exactly what #1917 is about?

> Is it possible?

I don't know, but please note that the issue tracker (qubes-issues) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by Middenvaus** [comment] 2023-08-19 11:19
> Isn't that exactly what #1917 is about?
That discussion is very big and I very quickly lost its essence while reading. It is similar to my problem. I will then close the current one due to a duplicate, and that discussion should be reopened

**Comment by andrewdavidwong** [comment] 2023-08-19 13:39
> That discussion needs to be reopened.

Unlocked.
