### ISSUE TITLE
sys-whonix launch error

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#3469] opened 2018-01-16 23:13 UTC
#### Qubes OS version:

R4.0_rc3

#### Affected TemplateVMs: 

whonix-gw

---

### Steps to reproduce the behavior:

launch sys-whonix

### Expected behavior:

sys-whonix should start without errors

### Actual behavior:

whonix seems to be working normally, but gives a popup error:
```
ERROR: Systemd Clock Check Result: 
Unexpected results by timedatectl. 
timedatectl_output_pretty: 
Local time: Fri 2018-01-12 14:04:59 UTC
Universal time: Fri 2018-01-12 14:04:59 UTC
RTC time: Fri 2018-01-12 14:04:06
Time zone: Etc/UTC (UTC, +0000)
NTP enabled: yes 
NTP synchronized: no
RTC in local TZ: no
DST active: n/a
It is generally recommended to keep the default as per Whonix Design. [1] If you did not change timezone related settings, please report this Whonix bug. If you know what you are doing and changed this on purpose, feel free to disable this check. [2] 

[1] https://www.whonix.org/wiki/Dev/Design-Shared#timezone 
[2] Create a file /etc/whonix.d/50_whonixcheck_user and add: 
whonixcheck_skip_functions+=" check_systemd_clock " 
```

### General notes:

apologies if this is a bug that should be reported directly to Whonix devs instead of QubesOS

---

**Comment by marmarek** [comment] 2018-01-16 23:20
@adrelanos which part of this output is unexpected?

**Comment by adrelanos** [comment] 2018-01-16 23:56
> `NTP enabled: yes`

Should be disabled by:

https://github.com/Whonix/sdwdate/blob/master/debian/sdwdate.postinst

```
## Deletes /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service.
## Otherwise timedatectl still thinks systemd-timesyncd is enabled.
timedatectl set-ntp false >/dev/null 2>&1 || true
## Make sure it gets really deleted even if timedatectl does not work.
rm --force /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service
```

The question is what re-enabled it?

**Comment by marmarek** [comment] 2018-01-17 00:05
I guess here: https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/75-qubes-vm.preset#L97
| enable systemd-timesyncd.service
together with `systemctl preset-all` at the end of installation

But there is also https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/systemd-timesyncd.service.d/30_qubes.conf, which should prevent starting the service everywhere but sys-net.

@mossy-nw can you check if the service is really running? `systemctl status systemd-timesyncd.service`

**Comment by mossy-nw** [comment] 2018-01-17 06:56
Sure.  In sys-whonix, correct?
```
user@host:~$ systemctl status systemd-timesyncd.service 
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled)
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
           └─30_qubes.conf, 40_sdwdate.conf
   Active: inactive (dead)
     Docs: man:systemd-timesyncd.service(8)
```
So it's loaded (enabled) but inactive (dead)?  I'm not sure if this means it's really running or no.  Thanks!

**Comment by mossy-nw** [comment] 2018-01-17 07:01
FWIW it's running identically in sys-net:
```
[user@sys-net ~]$ systemctl status systemd-timesyncd.service 
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; v
  Drop-In: /usr/lib/systemd/system/systemd-timesyncd.service.d
           └─30_qubes.conf
   Active: inactive (dead)
     Docs: man:systemd-timesyncd.service(8)
```
also running in sys-usb:
```
[user@sys-usb ~]$ systemctl status systemd-timesyncd.service 
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; v
  Drop-In: /usr/lib/systemd/system/systemd-timesyncd.service.d
           └─30_qubes.conf
   Active: inactive (dead)
Condition: start condition failed at Tue 2018-01-16 22:18:41 PST; 40min ago
           └─ ConditionPathExists=/var/run/qubes-service/clocksync was not met
     Docs: man:systemd-timesyncd.service(8)
```
and in an offline (via `qvm-prefs offlineVM netvm ""`) appVM:
```
[user@offlineVM ~]$ systemctl status systemd-timesyncd.service 
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; v
  Drop-In: /usr/lib/systemd/system/systemd-timesyncd.service.d
           └─30_qubes.conf
   Active: inactive (dead)
     Docs: man:systemd-timesyncd.service(8)
```
so looks like the service is starting everywhere.

**Comment by adrelanos** [comment] 2018-01-29 16:03
`timedatectl: caches NTP enablement state, better shouldn't`:
https://github.com/systemd/systemd/issues/1329

**Comment by marmarek** [comment] 2018-01-29 16:33
According to https://github.com/systemd/systemd/issues/1329#issuecomment-142260897, `sdwdate.service` should have `Conflicts=systemd-timesyncd.service`

**Comment by adrelanos** [comment] 2018-01-31 22:48
Marek Marczykowski-Górecki:
> According to https://github.com/systemd/systemd/issues/1329#issuecomment-142260897, `sdwdate.service` should have `Conflicts=systemd-timesyncd.service`
> 

It has.

https://github.com/Whonix/sdwdate/blob/master/lib/systemd/system/sdwdate.service#L17

Conflicts=systemd-timesyncd.service

**Comment by marmarek** [comment] 2018-02-01 08:15
> FWIW it's running identically in sys-net:

Should be really running there... As you can see, there is no "start condition failed", so it was prevented by something else. Can't find anything related in logs.

**Comment by mossy-nw** [comment] 2018-02-06 06:12
I don't see this issue anymore in R4.0_rc4, so is it OK to close this issue?  Don't want to close it if you all are still wanting to follow up on this or related things.  Thanks!

**Comment by mossy-nw** [comment] 2018-02-08 05:27
Ack, sorry you all @marmarek @andrewdavidwong @adrelanos it looks like on a fresh R4.0_rc4 install the original `Unexpected results by timedatectl` error message is back.  Apologies for not waiting to do more thorough testing before reporting it resolved.

**Comment by adrelanos** [comment] 2018-02-09 12:47
There was no update. Will be fixed in Whonix 14.

**Comment by mossy-nw** [comment] 2018-02-14 06:56
Wonderful.  Thank you for all the work and care you take on this project!

**Comment by vladionescu** [comment] 2018-06-27 00:23
What is the workaround here? I updated earlier today and now I can't start VMs, breaking my workflow.

**Comment by marmarek** [comment] 2018-06-27 00:55
Just to clarify - is it sys-whonix not starting at all, or displaying "Unexpected results by timedatectl" error message after the startup? The latter looks scary, but is a false positive (see discussion above) and in fact shouldn't break anything.
Do you see any other problem?

**Comment by vladionescu** [comment] 2018-06-27 01:34
It's displaying the error message and the VM starts, but connectivity in that VM appears to be broken:

- DispVMs based on whonix-ws-dvm have no outbound connectivity using Tor Browser
- Can't update whonix-gw template
- Can't update whonix-ws template

There's a chance this is a coincidence (saying this because I haven't had time to do a root cause and figure out whether the issues are related), but the issues started happening at the same time and I never had connectivity issues with whonix VMs prior. My other VMs/templates are unaffected.

**Comment by adrelanos** [comment] 2018-06-27 01:41
This very issue #3469 certainly (and I say that seldom) is only a false positive graphical user interface message warning.

For everything else, please create new issues.

**Comment by adrelanos** [comment] 2018-06-27 01:43
[status of Whonix 14 development](https://forums.whonix.org/t/whonix-14-release-blockers-status-of-whonix-14-development):

> Besides the known bugs on the Whonix and Qubes issue trackers, Whonix 14 should be ready as stable Whonix 14 release. Only waiting for new Qubes templates to be built and tested before the Whonix 14 release will be made. (#4016)

https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14

**Comment by adrelanos** [comment] 2018-08-07 17:15
Fixed in Whonix 14.

Close please.

**Closed** 2018-08-08 00:38 UTC
Labels: C: Whonix, P: major, bug
