### ISSUE TITLE
"Open in DisposableVM": Popup to enable insecure settings, like networking

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4006] opened 2018-06-15 05:52 UTC
Was Duplicate of #1118 (sorry), renamed.

An alternative implementation (which may be more secure):
- Select "Open in DisposableVM"
- Dom0 opens a popup asking if you want to enable insecure settings:

[Dom0] Open in DisposableVM
```
<filename>
[ ] Enable editing file on qube: <vm-name> (If unchecked, do not send back changes to original file & cloned file needs Read-only attribute set before opening in DispVM)
[ ] Enable networking (So malware can't phone home by default)
[Cancel] (encase malware triggered the open).
```

Original implementation for this issue:

### Qubes OS version:

R4.0

### Affected component(s): 

File Manager's right click menu option to "Open in DisposableVM".

---

### Steps to reproduce the behavior:

Create a file in `<vmname>`.
Use File Manager's right click menu option "Open in DisposableVM".
In DispVM, change file and save changes.
Reopen the file in `<vmname>`, and see if the changes were saved.

### Expected behavior:

If a file has malware, I do not want it to be able to change itself, like how some delete/corrupt their own file contents, store telemetry, or store stolen authentications. It is more secure to have the file be read-only when edits are not needed.

The File Manager's right click menu should have these two options:
1. "Open & Edit in DisposableVM" or just "Edit in DisposableVM"
2. "Read-only in DisposableVM" or just "View in DisposableVM"
- This never brings any changes back to the original VM.
- The copy of the file in the DisposableVM has its access reduced to read-only before it is opened.
- Note: You can't just get the "Copy To Other AppVM" to work easily on a DispVM to view a file.

### Actual behavior:

File Manager's right click menu option to "Open in DisposableVM" allows editing the file.

**Comment by RefinedSoftwareLLC** [comment] 2018-06-16 22:19
An alternative implementation:
- Select "Open in DisposableVM"
- Dom0 opens a popup asking if you would like Read-Write, Read-only, or Cancel (encase malware triggered the open).

**Comment by airelemental** [comment] 2018-06-17 15:34
Duplicate of https://github.com/QubesOS/qubes-issues/issues/1118 ?

Right now in current-testing, you can do this:
$ qvm-open-in-vm --viewonly
or right-click
Edit in DispVM
View in DispVM

**Comment by RefinedSoftwareLLC** [comment] 2018-06-17 16:38
Okay I am going to change the title, to incorporate the second idea. Sorry for duplicate of #1118 .

**Comment by RefinedSoftwareLLC** [comment] 2018-06-17 16:46
The popup idea, would be future compatible. Instead of adding every possible combination of security, for Opening in a DispVM, in the right click menu. Instead new security features can be added to the popup, defaulted to the secure option as an unchecked checkbox.

The popup could have a dropdown of DispVMs, like the "[Dom0] Operation execution", but with the system defaults "Default DispVM" already selected.

**Comment by airelemental** [comment] 2018-06-17 17:18
You can modify the NetVM (as well as a few other settings) of a running dispvm even after you've opened it.
$ qubes-vm-settings disp1831
brings up the settings window.

With some scripting you can bind a keyboard shortcut that opens a settings window for the foremost VM,

**Comment by marmarek** [comment] 2018-06-17 19:12
Lets not introduce additional popup, making the system more usable is about reducing them, not multiplying. But if you want, it is already possible to assign different DispVMs for different actions, or even - as you propose - choose them each time (which IMO is a bad idea). If you consider a case where some VM (normally network disconnected?) could use "Open in DisposableVM" action to phone home, better set network-disconnected DispVM there (without any prompts), instead of relying on the user to carefully choose the right thing each time. Remember, if you consider such a case, you should not trust that the file sent to view/edit is the one you've really wanted.
You can do this by setting "default_dispvm" property for such VM (for example have fedora-28-dvm-offline for that purpose). Or even per-action, using [qrexec policy](https://www.qubes-os.org/doc/qrexec3/#extra-keywords-available-in-qubes-40-and-later), like this:
```
$ cat /etc/qubes-rpc/policy/qubes.OpenInVM
# source          target                         action
some-offline-vm   $dispvm                        allow,target=$dispvm:fedora-28-dvm-offline
another-vm        $dispvm                        allow,target=$dispvm:fedora-28-dvm

# or have 'ask', with a list of available options defined by other 'ask' actions:
some-vm           $dispvm                        ask,default_target=$dispvm:fedora-28-dvm-offline
some-vm           $dispvm:fedora-28-dvm-offline  ask
some-vm           $dispvm:fedora-28-dvm          ask
```

**Comment by andrewdavidwong** [comment] 2018-06-20 01:06
Closing as "won't do." If anyone has a new argument for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2018-06-20 01:06 UTC
Labels: C: core, enhancement
