### ISSUE TITLE
sys-usb, sysfirewall and others stay 'yellow' after bootup and manual startup

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#2128] opened 2016-06-29 17:17 UTC
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): Debian-8

---

### General notes: In a fashion very similar to a 6 month closed issue #1250, with
virtually every bootup, either sys-usb and occasionally sys-firewall, a 'yellow' state
persists which only converts to 'green' upon a terminal run command. Similarly, VM
manager startup of sys-whonix has frequently entered a yellow state but functional,
entering green with terminal command. Additionally, the same process has occurred
with a menu terminal startup of debian-8 template, requiring a run terminal cmd producing two terminal windows with conversion to green. This issue has not occurred
with any previous qubes version on my system.

---

**Comment by marmarek** [comment] 2016-06-29 20:09
Looks like a duplicate of #2085. But to be sure: install updates from testing repository (instructions in that ticket). And let us know whether it helps.

**Comment by pugege** [comment] 2016-06-30 03:05
marmarek: Thank you kindly for your response. Your update has fixed the issue.
Congratulations to you and the project for an excellent upgrade.
Best Regards

**Closed** 2016-06-30 03:15 UTC
Labels: duplicate
