### ISSUE TITLE
"Request refused" on every qvm-* command in VMs since 4.0-RC4

### ISSUE THREAD

**Issue by arjan-s** [QubesOS/qubes-issues#3632] opened 2018-02-26 12:48 UTC
#### Qubes OS version:

R4.0 (RC4)

#### Affected component(s): 

Qubes RPC policy

---

### Steps to reproduce the behavior:

Run `qvm-copy filename` or `qvm-sync-clock` from a VM.

### Expected behavior:

Qubes should ask where to copy the file, or sync the clock.

### Actual behavior:

The command outputs "Request refused", and dom0 logs these kind of lines:

> qubes.Filecopy: testvm -> _default: denied: no matching rule found
> qubes.GetDate: personal -> _default: denied: no matching rule found

### General notes:

Looking at the files in /etc/qubes-rpc/policy, it seems like everything is in order. For instance, the file qubes.Filecopy correctly contains the default line `$anyvm  $anyvm  ask`.

---

**Comment by marmarek** [comment] 2018-02-26 13:25
Have you updated templates, as in https://www.qubes-os.org/news/2018/02/20/qsb-38/

**Comment by arjan-s** [comment] 2018-02-26 13:35
Oops, my bad! I thought I updated everything, but I now see that my Arch Linux template (which I use the most) didn't receive new Qubes packages. There are no updates available there, so I will look into updating them manually.
The qvm-* commands work just fine from AppVM's based on Fedora.
Thanks for pointing me in the right direction!

**Comment by andrewdavidwong** [comment] 2018-02-26 17:53
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-02-26 17:53 UTC

**Comment by marmarek** [comment] 2018-03-22 21:50
[qrexec-client-vm](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qrexec/qrexec-client-vm.c#L76-L87) should convert '$' to '@'. Make sure you really use this version.

**Comment by Nexolight** [comment] 2018-03-22 21:56
v4.0.24 contains that code and it probably does work. The problem is just that when I write:
`/usr/lib/qubes/qrexec-client-vm '@default' qubes.Filecopy /usr/lib/qubes/qfile-agent somefile`

then this appears still in the log of dom0: ...`_default: denied`...
for a.e. @@default this happens `__default: denied`

seems like @ is also replaced.

**Comment by marmarek** [comment] 2018-03-22 22:04
Looks like you haven't updated dom0 packages.

**Comment by Nexolight** [comment] 2018-03-22 22:21
Indeed that was the case. After updating it works and the other vms have the problem. After updating them it should be fine. thanks :)
