### ISSUE TITLE
Document change in TemplateVM home directory inheritance behavior

### ISSUE THREAD

**Issue by pietrushnic** [QubesOS/qubes-issues#3196] opened 2017-10-19 23:22 UTC
#### Qubes OS version:

`R4.0`

#### Affected TemplateVMs: 

`fedora-25`

---

### Steps to reproduce the behavior:

1. `qvm-start fedora-25 && qvm-run fedora-25 gnome-terminal`
2. In fedora-25 `touch ${HOME}/foobar`
3. `qvm-shutdown fedora-25`
4. `qvm-start fedora-25 && qvm-shutdown fedora-25` because of other bug
5. `qvm-create --template fedora-25 test`
6. Check if `${HOME}/foobar` exist

### Expected behavior:

`foobar` should exist

### Actual behavior:

`foobar` does not exist

### General notes:

Even hardware reboot doesn't help in that case.

---

**Comment by andrewdavidwong** [comment] 2017-10-19 23:40
@marmarek: Did this behavior change in 4.0? If so, then we can use this issue to track updating the documentation [here](https://www.qubes-os.org/doc/templates/#important-notes). If not, then this seems like a bug. Assuming the latter for initial classification.

**Comment by andrewdavidwong** [comment] 2017-10-19 23:41
@pietrushnic: Does work as expected on templates other than `fedora-25`?

**Comment by marmarek** [comment] 2017-10-19 23:56
Yes, the behavior have changed, see #1335 for some discussion (slightly outdated...).
The correct place for default home directory for new VMs is `/etc/skel`.

**Comment by andrewdavidwong** [comment] 2017-10-20 00:01
Ok, changing this to a documentation issue.

**Comment by pietrushnic** [comment] 2017-10-20 00:31
@andrewdavidwong I'm playing with `/etc/skel` and it also doesn't seem to work.

Template:

```
[2:27:08] user:~ $ ls -al /etc/skel 
total 44
drwxr-xr-x   6 root root  4096 Oct 20 02:24 .
drwxr-xr-x 121 root root 12288 Oct 20 02:27 ..
-rw-r--r--   1 root root    18 Sep 30  2016 .bash_logout
-rw-r--r--   1 root root   193 Sep 30  2016 .bash_profile
-rw-r--r--   1 root root   231 Sep 30  2016 .bashrc
lrwxrwxrwx   1 user user    33 Oct 20 02:10 .gitconfig -> /home/user/src/dotfiles/gitconfig
drwxr-xr-x   4 root root  4096 Jul 29 11:46 .mozilla
lrwxrwxrwx   1 user user    24 Oct 20 02:12 .oh-my-zsh -> /home/user/src/oh-my-zsh
lrwxrwxrwx   1 user user    24 Oct 20 02:10 .spf13-vim-3 -> /home/user/src/spf13-vim
drwxrwxr-x   2 user user  4096 Oct 20 02:09 .ssh
lrwxrwxrwx   1 user user    33 Oct 20 02:10 .tmux.conf -> /home/user/src/dotfiles/tmux.conf
drwxrwxr-x   3 user user  4096 Oct 20 02:10 .vim
lrwxrwxrwx   1 user user    37 Oct 20 02:10 .vimrc.before -> /home/user/.spf13-vim-3/.vimrc.before
lrwxrwxrwx   1 user user    44 Oct 20 02:10 .vimrc.before.local -> /home/user/src/spf13-vim/.vimrc.before.local
lrwxrwxrwx   1 user user    38 Oct 20 02:10 .vimrc.bundles -> /home/user/.spf13-vim-3/.vimrc.bundles
lrwxrwxrwx   1 user user    45 Oct 20 02:10 .vimrc.bundles.local -> /home/user/src/spf13-vim/.vimrc.bundles.local
lrwxrwxrwx   1 user user    37 Oct 20 02:10 .vimrc.local -> /home/user/src/spf13-vim/.vimrc.local
lrwxrwxrwx   1 user user    30 Oct 20 02:12 .zshrc -> /home/user/src/oh-my-zsh/zshrc
drwxr-xr-x   5 root root  4096 Oct 20 02:21 src
```

AppVM based on above template:

```
[user@coreboot-dev-f25]~% ls -al $HOME
total 80
drwx------ 14 user user 4096 Oct 20 02:26 .
drwxr-xr-x  3 root root 4096 Oct 20 02:26 ..
-rw-r--r--  1 user user   18 Sep 30  2016 .bash_logout
-rw-r--r--  1 user user  193 Sep 30  2016 .bash_profile
-rw-r--r--  1 user user  231 Sep 30  2016 .bashrc
drwxrwxr-x  3 user user 4096 Oct 20 02:26 .cache
drwx------  8 user user 4096 Oct 20 02:26 .config
-rw-------  1 user user   16 Oct 20 02:26 .esd_auth
drwxr-xr-x  3 user user 4096 Oct 20 02:26 .local
drwxr-xr-x  4 user user 4096 Jul 29 11:46 .mozilla
-rw-rw-r--  1 user user 8143 Oct 20 02:26 .xsession-errors
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Desktop
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Documents
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Downloads
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Music
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Pictures
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Public
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Templates
drwxr-xr-x  2 user user 4096 Oct 20 02:26 Videos
```

In `/etc/skel` of app vm contain all necessary.
```

**Comment by marmarek** [comment] 2017-10-20 00:36
Have you created that AppVM after template's modifications? Have you powered off the template for this?

**Comment by andrewdavidwong** [comment] 2019-01-20 00:36
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2019-01-20 00:36 UTC
Labels: C: doc
