### ISSUE TITLE
Qubes Update GUI window empty

### ISSUE THREAD

**Issue by 1cho1ce** [QubesOS/qubes-issues#8246] opened 2023-06-06 14:21 UTC
### Qubes OS release
R4.2

### Brief summary
When I start Qubes Update GUI tool it'll open empty window:

![qubes-update-gui](https://github.com/QubesOS/qubes-issues/assets/134313178/64053d1c-5fb1-42e3-a850-4b105a83c7a0)

Updates using salt work.

I don't see anything related in dom0 logs.
I don't plan to restart the system in the next few days so tell me if there's something I can check or test to find the problem.

### Steps to reproduce
Start Qubes Update GUI tool using any method.

### Expected behavior
Qubes Update GUI tool window will open and it'll be usable.

### Actual behavior
Qubes Update GUI tool window will open but it'll be empty and unusable.

**Comment by 1cho1ce** [comment] 2023-06-06 15:06
Maybe it was caused by the lack of memory in dom0. I had a problem right now because of the lack of RAM in dom0 so I've added swap to dom0. But this didn't fix the problem with Qubes Updater GUI tool. Maybe something was broken because of the lack of memory but it didn't recover when more memory was available.

**Comment by 1cho1ce** [comment] 2023-06-06 16:19
Yes, qmemman is running. I didn't have any swap enabled in dom0 and just had 4 GB of RAM. I've added 4 GB of swap for dom0 to work again.
Just for reference:
<details>
  <summary>[user@dom0 ~]$ sudo systemctl --no-pager --full status qubes-qmemman.service</summary>

```
● qubes-qmemman.service - Qubes memory management daemon
     Loaded: loaded (/usr/lib/systemd/system/qubes-qmemman.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-06-06 14:15:26 UTC; 1h 55min ago
   Main PID: 498601 (qmemmand)
      Tasks: 3 (limit: 4586)
     Memory: 9.7M
        CPU: 1min 3.132s
     CGroup: /system.slice/qubes-qmemman.service
             └─498601 /usr/bin/python3 /usr/bin/qmemmand

Jun 06 14:57:57 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3726217216 > 3537537742)
Jun 06 14:58:02 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3656724480 > 3576673901)
Jun 06 14:58:32 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3624935424 > 3467916001)
Jun 06 14:58:38 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3595816960 > 3507756626)
Jun 06 14:58:45 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3573469184 > 3393754434)
Jun 06 14:58:47 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3567984640 > 3432838982)
Jun 06 14:58:57 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3526553600 > 3394048896)
Jun 06 14:59:18 dom0 qmemman.systemstate[498601]: dom '0' still hold more memory than have assigned (3505573888 > 3433225447)
Jun 06 15:17:41 dom0 qmemman.systemstate[498601]: Xen free = 752566487 too small for satisfy assignments! assigned_but_unused=728446691, domdict={'0': {'memory_current': 3752816640, 'memory_actual': 3769594502, 'memory_maximum': 4294967296, 'mem_used': 2621722624, 'id': '0', 'last_target': 3769594502, 'no_progress': False, 'slow_memset_react': False}, '1': {'memory_current': 402698240, 'memory_actual': 402698240, 'memory_maximum': 419430400, 'mem_used': None, 'id': '1', 'last_target': 402653184, 'no_progress': False, 'slow_memset_react': False}, '2': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '2', 'last_target': 150994944, 'no_progress': False, 'slow_memset_react': False}, '13': {'memory_current': 834519040, 'memory_actual': 851234018, 'memory_maximum': 4194304000, 'mem_used': 651685888, 'id': '13', 'last_target': 851234018, 'no_progress': False, 'slow_memset_react': False}, '28': {'memory_current': 402698240, 'memory_actual': 402698240, 'memory_maximum': 419430400, 'mem_used': None, 'id': '28', 'last_target': 402653184, 'no_progress': False, 'slow_memset_react': False}, '29': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '29', 'last_target': 150994944, 'no_progress': False, 'slow_memset_react': False}, '30': {'memory_current': 564531200, 'memory_actual': 581243372, 'memory_maximum': 4194304000, 'mem_used': 444579840, 'id': '30', 'last_target': 581243372, 'no_progress': False, 'slow_memset_react': False}, '31': {'memory_current': 595316736, 'memory_actual': 612032013, 'memory_maximum': 4194304000, 'mem_used': 468197376, 'id': '31', 'last_target': 612032013, 'no_progress': False, 'slow_memset_react': False}, '32': {'memory_current': 567144448, 'memory_actual': 583859819, 'memory_maximum': 4194304000, 'mem_used': 446586880, 'id': '32', 'last_target': 583859819, 'no_progress': False, 'slow_memset_react': False}, '33': {'memory_current': 581513216, 'memory_actual': 598228920, 'memory_maximum': 4194304000, 'mem_used': 457609216, 'id': '33', 'last_target': 598228920, 'no_progress': False, 'slow_memset_react': False}, '34': {'memory_current': 553066496, 'memory_actual': 569779062, 'memory_maximum': 4194304000, 'mem_used': 435785728, 'id': '34', 'last_target': 569779062, 'no_progress': False, 'slow_memset_react': False}, '35': {'memory_current': 3943976960, 'memory_actual': 3960689203, 'memory_maximum': 4194304000, 'mem_used': 3036905472, 'id': '35', 'last_target': 3960689203, 'no_progress': False, 'slow_memset_react': False}, '37': {'memory_current': 603680768, 'memory_actual': 620393965, 'memory_maximum': 4194304000, 'mem_used': 474611712, 'id': '37', 'last_target': 620393965, 'no_progress': False, 'slow_memset_react': False}, '41': {'memory_current': 3623124992, 'memory_actual': 3639838029, 'memory_maximum': 4194304000, 'mem_used': 2790785024, 'id': '41', 'last_target': 3639838029, 'no_progress': False, 'slow_memset_react': False}, '91': {'memory_current': 1983352832, 'memory_actual': 2000067895, 'memory_maximum': 4194304000, 'mem_used': 1532940288, 'id': '91', 'last_target': 2000067895, 'no_progress': False, 'slow_memset_react': False}, '92': {'memory_current': 720838656, 'memory_actual': 737552060, 'memory_maximum': 4194304000, 'mem_used': 564482048, 'id': '92', 'last_target': 737552060, 'no_progress': False, 'slow_memset_react': False}, '94': {'memory_current': 634089472, 'memory_actual': 650803488, 'memory_maximum': 4194304000, 'mem_used': 497938432, 'id': '94', 'last_target': 650803488, 'no_progress': False, 'slow_memset_react': False}, '125': {'memory_current': 572362752, 'memory_actual': 589076695, 'memory_maximum': 4194304000, 'mem_used': 450588672, 'id': '125', 'last_target': 589076695, 'no_progress': False, 'slow_memset_react': False}, '132': {'memory_current': 623222784, 'memory_actual': 639937223, 'memory_maximum': 4194304000, 'mem_used': 489603072, 'id': '132', 'last_target': 639937223, 'no_progress': False, 'slow_memset_react': False}, '148': {'memory_current': 2237497344, 'memory_actual': 2254210347, 'memory_maximum': 4194304000, 'mem_used': 1727889408, 'id': '148', 'last_target': 2254210347, 'no_progress': False, 'slow_memset_react': False}, '164': {'memory_current': 2393772032, 'memory_actual': 2410486996, 'memory_maximum': 4194304000, 'mem_used': 1847767040, 'id': '164', 'last_target': 2410486996, 'no_progress': False, 'slow_memset_react': False}, '179': {'memory_current': 1289072640, 'memory_actual': 1305785640, 'memory_maximum': 4194304000, 'mem_used': 1000366080, 'id': '179', 'last_target': 1305785640, 'no_progress': False, 'slow_memset_react': False}, '187': {'memory_current': 595431424, 'memory_actual': 612144147, 'memory_maximum': 4194304000, 'mem_used': 468283392, 'id': '187', 'last_target': 612144147, 'no_progress': False, 'slow_memset_react': False}, '197': {'memory_current': 1951379456, 'memory_actual': 1968312771, 'memory_maximum': 4194304000, 'mem_used': 1508581376, 'id': '197', 'last_target': 1968312771, 'no_progress': False, 'slow_memset_react': False}, '208': {'memory_current': 564166656, 'memory_actual': 580880274, 'memory_maximum': 4194304000, 'mem_used': 444301312, 'id': '208', 'last_target': 580880274, 'no_progress': False, 'slow_memset_react': False}, '209': {'memory_current': 337707008, 'memory_actual': 337707008, 'memory_maximum': 337641472, 'mem_used': None, 'id': '209', 'last_target': 337641472, 'no_progress': False, 'slow_memset_react': False}, '241': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3814604800, 'id': '241', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '253': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3430952960, 'id': '253', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '259': {'memory_current': 3160915968, 'memory_actual': 3178814705, 'memory_maximum': 4194304000, 'mem_used': 2437140480, 'id': '259', 'last_target': 3178814705, 'no_progress': False, 'slow_memset_react': False}, '269': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3610931200, 'id': '269', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '270': {'memory_current': 3039055872, 'memory_actual': 3057833394, 'memory_maximum': 4194304000, 'mem_used': 2344337408, 'id': '270', 'last_target': 3057833394, 'no_progress': False, 'slow_memset_react': False}, '271': {'memory_current': 3959799808, 'memory_actual': 3980424690, 'memory_maximum': 4194304000, 'mem_used': 3052044288, 'id': '271', 'last_target': 3980424690, 'no_progress': False, 'slow_memset_react': False}, '272': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3622199296, 'id': '272', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '273': {'memory_current': 3912622080, 'memory_actual': 3930338417, 'memory_maximum': 4194304000, 'mem_used': 3013623808, 'id': '273', 'last_target': 3930338417, 'no_progress': False, 'slow_memset_react': False}, '274': {'memory_current': 1828036608, 'memory_actual': 1847593104, 'memory_maximum': 4194304000, 'mem_used': 1415979008, 'id': '274', 'last_target': 1847593104, 'no_progress': False, 'slow_memset_react': False}, '275': {'memory_current': 924229632, 'memory_actual': 942761610, 'memory_maximum': 4194304000, 'mem_used': 721895424, 'id': '275', 'last_target': 942761610, 'no_progress': False, 'slow_memset_react': False}, '278': {'memory_current': 1632169984, 'memory_actual': 1829390108, 'memory_maximum': 4194304000, 'mem_used': 1402015744, 'id': '278', 'last_target': 1829390108, 'no_progress': False, 'slow_memset_react': False}}
Jun 06 15:17:41 dom0 qmemman.systemstate[498601]: Xen free = 748315273 too small for satisfy assignments! assigned_but_unused=728446691, domdict={'0': {'memory_current': 3752816640, 'memory_actual': 3769594502, 'memory_maximum': 4294967296, 'mem_used': 2621722624, 'id': '0', 'last_target': 3769594502, 'no_progress': False, 'slow_memset_react': False}, '1': {'memory_current': 402698240, 'memory_actual': 402698240, 'memory_maximum': 419430400, 'mem_used': None, 'id': '1', 'last_target': 402653184, 'no_progress': False, 'slow_memset_react': False}, '2': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '2', 'last_target': 150994944, 'no_progress': False, 'slow_memset_react': False}, '13': {'memory_current': 834519040, 'memory_actual': 851234018, 'memory_maximum': 4194304000, 'mem_used': 651685888, 'id': '13', 'last_target': 851234018, 'no_progress': False, 'slow_memset_react': False}, '28': {'memory_current': 402698240, 'memory_actual': 402698240, 'memory_maximum': 419430400, 'mem_used': None, 'id': '28', 'last_target': 402653184, 'no_progress': False, 'slow_memset_react': False}, '29': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '29', 'last_target': 150994944, 'no_progress': False, 'slow_memset_react': False}, '30': {'memory_current': 564531200, 'memory_actual': 581243372, 'memory_maximum': 4194304000, 'mem_used': 444579840, 'id': '30', 'last_target': 581243372, 'no_progress': False, 'slow_memset_react': False}, '31': {'memory_current': 595316736, 'memory_actual': 612032013, 'memory_maximum': 4194304000, 'mem_used': 468197376, 'id': '31', 'last_target': 612032013, 'no_progress': False, 'slow_memset_react': False}, '32': {'memory_current': 567144448, 'memory_actual': 583859819, 'memory_maximum': 4194304000, 'mem_used': 446586880, 'id': '32', 'last_target': 583859819, 'no_progress': False, 'slow_memset_react': False}, '33': {'memory_current': 581513216, 'memory_actual': 598228920, 'memory_maximum': 4194304000, 'mem_used': 457609216, 'id': '33', 'last_target': 598228920, 'no_progress': False, 'slow_memset_react': False}, '34': {'memory_current': 553066496, 'memory_actual': 569779062, 'memory_maximum': 4194304000, 'mem_used': 435785728, 'id': '34', 'last_target': 569779062, 'no_progress': False, 'slow_memset_react': False}, '35': {'memory_current': 3943976960, 'memory_actual': 3960689203, 'memory_maximum': 4194304000, 'mem_used': 3036905472, 'id': '35', 'last_target': 3960689203, 'no_progress': False, 'slow_memset_react': False}, '37': {'memory_current': 603680768, 'memory_actual': 620393965, 'memory_maximum': 4194304000, 'mem_used': 474611712, 'id': '37', 'last_target': 620393965, 'no_progress': False, 'slow_memset_react': False}, '41': {'memory_current': 3623124992, 'memory_actual': 3639838029, 'memory_maximum': 4194304000, 'mem_used': 2790785024, 'id': '41', 'last_target': 3639838029, 'no_progress': False, 'slow_memset_react': False}, '91': {'memory_current': 1983352832, 'memory_actual': 2000067895, 'memory_maximum': 4194304000, 'mem_used': 1532940288, 'id': '91', 'last_target': 2000067895, 'no_progress': False, 'slow_memset_react': False}, '92': {'memory_current': 720838656, 'memory_actual': 737552060, 'memory_maximum': 4194304000, 'mem_used': 564482048, 'id': '92', 'last_target': 737552060, 'no_progress': False, 'slow_memset_react': False}, '94': {'memory_current': 634089472, 'memory_actual': 650803488, 'memory_maximum': 4194304000, 'mem_used': 497938432, 'id': '94', 'last_target': 650803488, 'no_progress': False, 'slow_memset_react': False}, '125': {'memory_current': 572362752, 'memory_actual': 589076695, 'memory_maximum': 4194304000, 'mem_used': 450588672, 'id': '125', 'last_target': 589076695, 'no_progress': False, 'slow_memset_react': False}, '132': {'memory_current': 623222784, 'memory_actual': 639937223, 'memory_maximum': 4194304000, 'mem_used': 489603072, 'id': '132', 'last_target': 639937223, 'no_progress': False, 'slow_memset_react': False}, '148': {'memory_current': 2237497344, 'memory_actual': 2254210347, 'memory_maximum': 4194304000, 'mem_used': 1727889408, 'id': '148', 'last_target': 2254210347, 'no_progress': False, 'slow_memset_react': False}, '164': {'memory_current': 2393772032, 'memory_actual': 2410486996, 'memory_maximum': 4194304000, 'mem_used': 1847767040, 'id': '164', 'last_target': 2410486996, 'no_progress': False, 'slow_memset_react': False}, '179': {'memory_current': 1289072640, 'memory_actual': 1305785640, 'memory_maximum': 4194304000, 'mem_used': 1000366080, 'id': '179', 'last_target': 1305785640, 'no_progress': False, 'slow_memset_react': False}, '187': {'memory_current': 595431424, 'memory_actual': 612144147, 'memory_maximum': 4194304000, 'mem_used': 468283392, 'id': '187', 'last_target': 612144147, 'no_progress': False, 'slow_memset_react': False}, '197': {'memory_current': 1951379456, 'memory_actual': 1968312771, 'memory_maximum': 4194304000, 'mem_used': 1508581376, 'id': '197', 'last_target': 1968312771, 'no_progress': False, 'slow_memset_react': False}, '208': {'memory_current': 564166656, 'memory_actual': 580880274, 'memory_maximum': 4194304000, 'mem_used': 444301312, 'id': '208', 'last_target': 580880274, 'no_progress': False, 'slow_memset_react': False}, '209': {'memory_current': 337707008, 'memory_actual': 337707008, 'memory_maximum': 337641472, 'mem_used': None, 'id': '209', 'last_target': 337641472, 'no_progress': False, 'slow_memset_react': False}, '241': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3814604800, 'id': '241', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '253': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3430952960, 'id': '253', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '259': {'memory_current': 3160915968, 'memory_actual': 3178814705, 'memory_maximum': 4194304000, 'mem_used': 2437140480, 'id': '259', 'last_target': 3178814705, 'no_progress': False, 'slow_memset_react': False}, '269': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3610931200, 'id': '269', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '270': {'memory_current': 3039055872, 'memory_actual': 3057833394, 'memory_maximum': 4194304000, 'mem_used': 2344337408, 'id': '270', 'last_target': 3057833394, 'no_progress': False, 'slow_memset_react': False}, '271': {'memory_current': 3959799808, 'memory_actual': 3980424690, 'memory_maximum': 4194304000, 'mem_used': 3052044288, 'id': '271', 'last_target': 3980424690, 'no_progress': False, 'slow_memset_react': False}, '272': {'memory_current': 4177592320, 'memory_actual': 4194304000, 'memory_maximum': 4194304000, 'mem_used': 3622199296, 'id': '272', 'last_target': 4194304000, 'no_progress': False, 'slow_memset_react': False}, '273': {'memory_current': 3912622080, 'memory_actual': 3930338417, 'memory_maximum': 4194304000, 'mem_used': 3013623808, 'id': '273', 'last_target': 3930338417, 'no_progress': False, 'slow_memset_react': False}, '274': {'memory_current': 1828036608, 'memory_actual': 1847593104, 'memory_maximum': 4194304000, 'mem_used': 1415979008, 'id': '274', 'last_target': 1847593104, 'no_progress': False, 'slow_memset_react': False}, '275': {'memory_current': 924229632, 'memory_actual': 942761610, 'memory_maximum': 4194304000, 'mem_used': 721895424, 'id': '275', 'last_target': 942761610, 'no_progress': False, 'slow_memset_react': False}, '278': {'memory_current': 1632169984, 'memory_actual': 1829390108, 'memory_maximum': 4194304000, 'mem_used': 1402015744, 'id': '278', 'last_target': 1829390108, 'no_progress': False, 'slow_memset_react': False}}
```

</details>

**Comment by andrewdavidwong** [comment] 2023-06-06 16:51
Since Qubes OS is intended to run with some swap space in dom0, and since it sounds like you're not able to reproduce this after adding the swap space back, this issue should probably be closed as either "not a bug" (or maybe "unable to reproduce," depending on your perspective). Of course, if the problem were to recur even with normal swap space, we'd want to reopen this issue and try to diagnose the real cause.

If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed by andrewdavidwong** 2023-06-06 16:51 UTC
Labels: T: bug, P: default

**Comment by 1cho1ce** [comment] 2023-06-06 17:10
> since it sounds like you're not able to reproduce this after adding the swap space back

I'm still affected by this issue with Qubes Updater GUI even after I've added swap.
But I didn't yet reboot the Qubes OS so maybe the issue will go away after the reboot.
