### ISSUE TITLE
Video/Audio Choppiness Every 4-6 Minutes When Playing High-Definition Video & Using USB Audio

### ISSUE THREAD

**Issue by aQubesUser** [QubesOS/qubes-issues#2630] opened 2017-02-14 00:41 UTC
#### Qubes OS version (e.g., `R3.2`):

`R.3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

StandaloneVM, `fedora-24` upgraded from `fedora-23` from base install

---

### Expected behavior:

Hi-definition video (720p & above; encoded using h264 standard) should play smoothly throughout duration of video. Video may be online (e.g. YouTube.com) or stored locally (e.g. *.mkv file). Audio is sent over a USB device that is connected to the `sys-usb` VM and attached to the StandaloneVM with `qvm-usb -a ...`

### Actual behavior:

Video plays smoothly for 4 to 6 minutes, audio & video are in-sync. For a few seconds, video will be choppy as well as audio before returning to smooth playback. Issue repeats every 4-6 minutes. I have checked `/etc/crontab` for `dom0` and the StandaloneVM in case there was a cronjob running that would cause load on the system, both are empty.

### Steps to reproduce the behavior:

1. Create a StandaloneVM from `fedora-23` template
1. Upgrade StandaloneVM to `fedora-24`
   1. Add, enable `rpmfusion` sources & install `ffmpeg-libs` to allow playback of h264 videos in Firefox
   1. Install mpv/vlc/etc for playback of video files
1. Play a high-definition video from YouTube.com or locally
1. Allow playback to conitinue for 4-6 minutes

### General notes:

Some messages seen in `dmesg`:

```
[ 4667.143981] vhci_hcd: dequeue a urb ffff8800788b5200
[ 4667.144012] vhci_hcd: device ffff880078fd8298 seems to be still connected
[ 4667.144042] vhci_hcd: dequeue a urb ffff8800788b5600
[ 4667.144056] vhci_hcd: device ffff880078fd8298 seems to be still connected
[ 4667.144070] vhci_hcd: dequeue a urb ffff8800788b4a00
[ 4667.144083] vhci_hcd: device ffff880078fd8298 seems to be still connected
[ 4667.147250] vhci_hcd: unlink->seqnum 434847
[ 4667.147274] vhci_hcd: unlink->seqnum 434848
[ 4667.147290] vhci_hcd: urb->status -104
[ 4667.153414] vhci_hcd: unlink->seqnum 434847
[ 4667.153437] vhci_hcd: unlink->seqnum 434849
[ 4667.153453] vhci_hcd: urb->status -104
[ 4667.159357] vhci_hcd: unlink->seqnum 434847
[ 4667.159385] vhci_hcd: urb->status -104
```

Relevant video hardware:

```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)
```

---

**Comment by aQubesUser** [comment] 2017-02-14 00:42
I just wanted to add that playing similar videos in Firefox or mpv worked without any issues when this system was running Debian.

**Comment by marmarek** [comment] 2017-02-14 01:08
Actually, there is a dom0 cron job running every 6 minutes -
/etc/cron.d/qubes-sync-clock.cron

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by aQubesUser** [comment] 2017-02-14 01:16
@marmarek 

Ah. I hadn't looked in the directories, thanks for pointing this out.
Do you recommend making the following change?

```
*/6 * * * * root /usr/bin/nice 19 /usr/bin/qvm-sync-clock > /dev/null 2>&1 || true
```

**Comment by marmarek** [comment] 2017-02-14 01:39
I'd first comment it out completely to check if that's the cause.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by aQubesUser** [comment] 2017-02-14 02:27
I made that change and played a video to test before seeing your response. The change seems to have fixed the periodic choppiness, but I will continue to test this. 

`mpv` falls back to using the `x11` video output driver, playback with `opengl` results in choppy audio even though video playback is fine (not sure about this either). 
`x11` makes sense given the description of the GUI on this page: https://www.qubes-os.org/doc/gui/

**Comment by aQubesUser** [comment] 2017-02-14 02:27
Description of video drivers for `mpv`: https://mpv.io/manual/master/#video-output-drivers

**Comment by andrewdavidwong** [comment] 2017-02-15 05:06
> I made that change and played a video to test before seeing your response. The change seems to have fixed the periodic choppiness, but I will continue to test this.

Closing as `notanissue` based on this comment. If the problem recurs, or if you think that this merits further action (e.g., disabling that cron job by default, which would cause other problems), let us know.

**Closed by andrewdavidwong** 2017-02-15 05:06 UTC
Labels: C: other, notanissue
