### ISSUE TITLE
Create New Qube GUI assigns network by default to templates

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#9487] opened 2024-10-01 16:57 UTC
### Qubes OS release

4.2.3

### Brief summary

creating a new qube template from an existing template using the new GUI sets networking by default

### Steps to reproduce

- run "Create New Qube"
- Click on "Template"

### Expected behavior

- Network connection is set to "No network connection"

or in case of a clone, the network connection of the source qube should be reused

### Actual behavior

- Network connection is set to "default" (which is sys-firewall)

**Comment by alimirjamali** [comment] 2024-10-03 13:08
Possibly related: #9174

**Comment by DemiMarie** [comment] 2024-10-03 19:11
I think this is a duplicate of #9174.

**Closed** 2024-10-04 09:18 UTC
Labels: T: bug, R: duplicate, C: manager/widget, P: major, affects-4.2
