### ISSUE TITLE
Salt-based install of Whonix 14 does not install debian template

### ISSUE THREAD

**Issue by jrsmiley** [QubesOS/qubes-issues#4628] opened 2018-12-17 01:27 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

sys-whonix

---

### Steps to reproduce the behavior:

See uploaded detailed notes.

### Expected behavior:

Run from dom0 as described here: https://www.whonix.org/wiki/Qubes/Install
sudo qubesctl state.sls qvm.whonix-ws-dvm
All dependencies are resolved, including installing debian templatevm if necessary
Whonix 14 ws and gw are installed and running 

### Actual behavior:

sys-whonix fails to start
debian template is not installed

### General notes:

[Qubes4IinstallNotes.txt](https://github.com/QubesOS/qubes-issues/files/2684165/Qubes4IinstallNotes.txt)

---

**Comment by marmarek** [comment] 2018-12-17 01:43
> debian template is not installed

This is expected. Whonix is installed independently of Debian template. See https://www.qubes-os.org/doc/templates/ and documentation about specific templates.

> whonixcheck | Whonix-Gateway | Unknown Qubes VM type
> Body of pop up shows that whonix-firewall.service failed to start
> This isn't surprising since I haven't told it how to connect to Tor yet.

This looks like #4603 

> First failure was "qubesdb-daemon[229]: segfault at xxx ip xxx sp xxx error 6 in ld-2.24.so[xxx]
> Failed to start Qubes DB Agent

This looks like #4349 (which is also consistent with #4603).

Can you verify what version of `libxen-4.8` package you have installed there? Should be 4.8.4-8+deb9u1 or 4.8.4-7+deb9u1.

**Comment by marmarek** [comment] 2018-12-17 01:47
Also, to verify if that's really about #4349, you can try workaround named there:  add `noxsave` to kernelopts of whonix-gw-14 (and verify if sys-whonix also got it). Use `qvm-prefs` tool.

**Comment by jrsmiley** [comment] 2018-12-17 01:49
That was the quickest response to a support issue that I think I've ever seen.  However, as I noted at the ends of my notes, I'm punting to a reinstall, this time selecting debian and repeating the steps I followed last time.  I've already begun, so there's nothing for me to poke at for you.  I'll have a look at #4369

**Comment by jrsmiley** [comment] 2018-12-17 01:54
If I'd had any idea you would respond that fast, I would have postponed the reinstall.  Really appreciate you're jumping on these issues I raise.

**Comment by jrsmiley** [comment] 2018-12-17 01:59
I should probably finish reading the salt docs.  I understand that templates are stand alone, but I had the impression salt sort of sits above the templates and resolves dependencies for you.

**Comment by marmarek** [comment] 2018-12-17 02:07
Salt allows to perform multiple actions with a single command. This is especially useful for Whonix, where you need to install two templates, create various VMs etc. Theoretically you could use salt for other templates too, but since installing them is just one command, we don't have up to date salt configuration for them.

**Comment by jrsmiley** [comment] 2018-12-17 02:10
From what I got out of #4369, the patch has been pushed to stable, so I *should* have gotten it with the qubes-dom0-update.  I'll check the version as I proceed with the reinstall.  I'll also check the version used by the Debian template after I've updated it.

**Comment by jrsmiley** [comment] 2018-12-17 03:07
Something went very wrong during the re-install.  I used the same steps as before.  The only difference was that I only de-selected Whonix during installation and left the debian template selected.  When the install was complete, I had a debian template, but it had the same issues as I noted earlier: Apps no installed, can't run a terminal, segfault during startup that looks like #4369.  

I checked for the version of libxen in dom0 and found that the package is not installed.  
sudo rpm -qa | grep libxen
returns nothing
sudo yum list installed
visual scan confirms package libxen is not installed.
sudo yum search libxen
gets redirected to dnf search libxen
returns no match found

I thought this was in the stable repository.  What am i missing

**Comment by marmarek** [comment] 2018-12-17 03:10
That package is in Debian/Whonix template.
You can try running terminal in debian-9 with `qvm-run debian-9 xterm`. If that fails, you can access its console with `sudo xl console debian-9` (start the qube first).

**Comment by jrsmiley** [comment] 2018-12-17 03:17
I had already tried qvm-run debian-9 gnome-terminal and got nothing, so I'll give the console a try.  First I have to re-install the template because I removed it (qube template vm and dom0 package) and was about to try re-installing it when I saw your reply.  I'm installing using
sudo qubes-dom0-update qubes-template-debian-9
is that correct?  When you say Debian/Whonix template, is that the same thing or something different?

**Comment by marmarek** [comment] 2018-12-17 03:19
>  I'm installing using
> sudo qubes-dom0-update qubes-template-debian-9
> is that correct?

Yes.



> When you say Debian/Whonix template, is that the same thing or something different?

The same package should be in both of them.

**Comment by jrsmiley** [comment] 2018-12-17 03:19
"Both of them"?  Is there another debian-9 template?

**Comment by jrsmiley** [comment] 2018-12-17 03:20
I'm not installing Whonix until I have a working and up-to-date debian-9 template.  when you say "both", you mean the Whonix ws/gw pair or something else?

**Comment by jrsmiley** [comment] 2018-12-17 03:30
So it looks like 4.8.4 did *not* make it to stable.

**Comment by marmarek** [comment] 2018-12-17 03:31
>  libxen-4.8.3-4+deb9u1 installed

Ok, so this package does _not_ contains the fix yet. So, I'm pretty sure it's #4349 now.
What version of the template you've got (you should see it during install)?

**Comment by jrsmiley** [comment] 2018-12-17 03:33
4.0.0-201803270258

**Comment by marmarek** [comment] 2018-12-17 03:37
Ok, so this definitely does not contain the fix (it's half a year too old for that). Oh, and this is also the newest template in stable, all the latest are still in templates-itl-testing. 
Lets see with https://github.com/QubesOS/updates-status/issues/829 - should be in stable in few minutes.

**Comment by marmarek** [comment] 2018-12-17 03:50
Ok, should be there. Use `qubes-dom0-update --clean qubes-template-debian-9` to make sure it picks up new version.

**Comment by jrsmiley** [comment] 2018-12-17 03:50
Here we go

**Comment by jrsmiley** [comment] 2018-12-17 03:56
"No match for argument: qubes-template-debian-9"
This is right after the "last metadata expiration check"

**Comment by jrsmiley** [comment] 2018-12-17 03:56
Does need some time to percolate?

**Comment by marmarek** [comment] 2018-12-17 03:58
Ah, you need to remove the old one first. Or add `--action=upgrade`.

**Comment by jrsmiley** [comment] 2018-12-17 03:58
I did a sudo yum remove on the old one.  The new one is installing now.

**Comment by jrsmiley** [comment] 2018-12-17 04:03
Wow, we moved forward nearly 9 months in time with that one.  From March 27 doe Dec 9.

**Comment by jrsmiley** [comment] 2018-12-17 04:10
Noooooo..  It's still craping out.  First failure is "Failed to start Load Kernel Modules" followed a few steps later by a segfault on the qubesdb-daemon "Failed to start Qubes DB agent"

**Comment by marmarek** [comment] 2018-12-17 04:12
Check libxen-4.8 package version...

**Comment by jrsmiley** [comment] 2018-12-17 04:12
I'm going to have to hang it up for tonight.  Time to start the bedtime process and head to work in the morning.  I'll check back after work tomorrow.

Because I know you'll ask this, yes indeed, the installed version is:
qubes-template-debian-9.noarch 4.0.1-201812091508

**Comment by jrsmiley** [comment] 2018-12-17 04:15
Still no apps installed except start, so no term, but the console works and the libxen version shows
4.8.4-8+deb9u1

**Comment by jrsmiley** [comment] 2018-12-17 04:16
Good night and good working with you.

**Comment by jrsmiley** [comment] 2018-12-17 04:53
Coming to you live from within my Personal Qubue:

There were a few packages in dom0 that were available to update after you pushed the 4.0.1.xxx version of the debian-9 template, so I applied them and rebooted, removed the debian-9 template, reinstalled it.  No change.  However, I was able to get you a complete log from the console.  See attached.

[debian-9.log](https://github.com/QubesOS/qubes-issues/files/2684510/debian-9.log)

**Comment by unman** [comment] 2018-12-17 11:30
I'm always reluctant to dive in to this sort of issue, because invariably I do not encounter the problem.
I have a clean install of 4.0 and 4.1rc1 - in both the Debian templates work as expected.
Also, installing the latest template on all the systems I have access to produces a working Debian template, with menus and all. 

I'll run a comparison against the posted log, although the segfault in qrexec-agent after Raise network interfaces stands out.
@jrsmiley Can you confirm that this is a log from the template please?

**Comment by jrsmiley** [comment] 2018-12-17 16:50
Yes the console log I posted came directly from the new Debian-9 template
pushed to stable tonight 201812.. time stamp. The version prior to last
nights update was from March.  It had similar problems. You should be Able
to find all of the details and timeline in the issue tracker

**Comment by jrsmiley** [comment] 2018-12-18 04:42
Tried to generate an HCL for debian-9 template.  Here's the result:
This is what was displayed in my dom0 terminal window
[hcl-debian-9.log](https://github.com/QubesOS/qubes-issues/files/2688918/hcl-debian-9.log)

This is the output file it generated

[Qubes-HCL-Gigabyte_Technology_Co___Ltd_-X299_AORUS_Gaming_3-20181217-203034.zip](https://github.com/QubesOS/qubes-issues/files/2688922/Qubes-HCL-Gigabyte_Technology_Co___Ltd_-X299_AORUS_Gaming_3-20181217-203034.zip)

Doesn't look like it got very much since we can't start a terminal in that template.  Is there a way to get what we need via the Qube's console?

**Comment by marmarek** [comment] 2018-12-18 04:54
Try this:
https://github.com/QubesOS/qubes-issues/issues/4628#issuecomment-447698851
I'm pretty sure the cause of the issue is the same as in #4349, maybe there is slightly different variant. The key point about the hardware matches:
> [    0.000000] x86/fpu: Enabled xstate features 0xff, context size is 2560 bytes, using 'compacted' format.

The `noxsave` option is a workaround, so you get it working until proper solution.

**Comment by jrsmiley** [comment] 2018-12-18 05:03
That allowed the template to boot and I was able to run an update.

**Comment by jrsmiley** [comment] 2018-12-18 05:07
I re-ran the HCL.  Here's the new output.
[Qubes-HCL-Gigabyte_Technology_Co___Ltd_-X299_AORUS_Gaming_3-20181217-210438.zip](https://github.com/QubesOS/qubes-issues/files/2688960/Qubes-HCL-Gigabyte_Technology_Co___Ltd_-X299_AORUS_Gaming_3-20181217-210438.zip)

**Comment by unman** [comment] 2019-02-21 13:11
@jrsmiley Are you able to close this issue? The original problem stemmed from a misunderstanding of the salt Whonix install,combined with issues that arose from hardware problems - you seem to have a workround for those and have been able to boot the template.
The hardware incompatibility seems a duplicate of #4349(?)
Is there a reason to keep this open?

**Closed** 2019-02-25 03:19 UTC
Labels: C: Debian/Ubuntu, C: Whonix, C: mgmt, bug
