### ISSUE TITLE
qvm-open-in-vm doesn't fill Target with vmname

### ISSUE THREAD

**Issue by constantoverride** [QubesOS/qubes-issues#4207] opened 2018-08-12 09:00 UTC
### Qubes OS version:

R4.0

### Affected component(s): 

qvm-open-in-vm ?

---

### Steps to reproduce the behavior:

* In a `vm1` terminal type: `qvm-open-in-vm vm2 https://duckduckgo.com` (works the same for files too, eg. replace the url with `1.png`)
Note: `vm2` must exist, or else you immediately get `Request refused` on console.

### Actual behavior:

![qvm-open-in-vm_screenshot_2018-08-12_10-45-02](https://user-images.githubusercontent.com/40925413/44000280-521cfa14-9e1d-11e8-959c-b896c7d20e06.png)
(`vm1` is `work` in this screenshot)

A dialog appears with title `[Dom0] Operation execution` with two fields: first is an uneditable `Source: vm1` and the second is an editable `Target:`  which is empty. In other words, the `vmname` arg for `qvm-open-in-vm` is not in the `Target:` field.

### Expected behavior:

dialog's `Target:` field should contain the text: `vm2`

### General notes:

`vm1` is a fedora 28 vm
I'm pretty sure that I'm using the testing repositories...

Bonus question: has anyone patched firefox to add a menu entry, near `Open Link in New Tab` for example, to open that link in a different VM ? (even if the VM names aren't included in a submenu, for security reasons?, but rather just like this issue, you're expected to fill in the Target VM name yourself in the dialog that opens)

---

### Related issues:

Related comment: https://github.com/QubesOS/qubes-issues/issues/2436#issuecomment-260727458

**Comment by constantoverride** [comment] 2018-08-12 18:10
I just noticed that the above is true for `qvm-copy` (from within a `vm1`) too, like `$ qvm-copy vm2 file.jpg` will have `Target:` be empty in the dialog. I'm assuming the root cause will fix both of these issues.

However it's interesting that `qvm-copy-to-vm` says:
```
qvm-copy-to-vm/qvm-move-to-vm tools are deprecated,
use qvm-copy/qvm-move to avoid typing target qube name twice
```

$ qvm-copy
usage: /usr/bin/qvm-copy-to-vm [--without-progress] dest_vmname file [file]+
$ qvm-copy-to-vm
usage: /usr/bin/qvm-copy-to-vm [--without-progress] dest_vmname file [file]+

Hmm... however, in practice looks-like, `qvm-copy` expects all its args to be files(because it's equivalent to `qvm-copy-to-vm '$default'`), then you select the Target vm in the dialog. Whilst `qvm-copy-to-vm` actually expects the first arg to be the dest_vm_name and it looks like it's known that you have to type the dest_vmname twice(once as arg and once in the Target field of the dialog), according to the above message that says: `use qvm-copy/qvm-move to avoid typing target qube name twice`.

This leads me to believe the original issue is actually a feature: expecting to type vmname twice(as arg and as dialog).

**Comment by andrewdavidwong** [comment] 2018-08-12 20:40
Duplicate of #3251

**Comment by andrewdavidwong** [comment] 2018-08-12 20:40
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-08-12 20:40 UTC
