### ISSUE TITLE
Building Arch template fails due to outdated dependencies

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7569] opened 2022-06-15 19:14 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Can't build Arch template 

### Steps to reproduce
Build Arch according to https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md

### Expected behavior
Build finished with sucess

### Actual behavior
Dependency error: 
```
==> Making package: qubes-vm-gui 4.1.25-10 (Wed Jun 15 21:06:52 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
error: target not found: pulseaudio<=15.0
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> pulseaudio<=15.0
  -> xorg-server-devel
  -> xorg-util-macros
  -> libxcomposite
  -> libxt
  -> qubes-vm-gui-common
==> ERROR: Could not resolve all dependencies.
Container chroot-vm-archlinux failed with error code 8.
```

**Comment by lubellier** [comment] 2022-06-15 22:29
This is a duplicate of https://github.com/QubesOS/qubes-issues/issues/7531.

**Comment by andrewdavidwong** [comment] 2022-06-16 02:21
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed** 2022-06-16 02:21 UTC
Labels: T: bug, P: default
