### ISSUE TITLE
XScreenSaver randomly locking up

### ISSUE THREAD

**Issue by pure007** [QubesOS/qubes-issues#4678] opened 2019-01-03 09:02 UTC
### Qubes OS version:

R4.0.1-rc2

### Affected component(s): 

XScreenSaver

---

### Steps to reproduce the behavior:

Use the system like normal.

### Expected behavior:

The screen would lock after a period of no activity.

### Actual behavior:

The system locks while actively using it.

### General notes:

The version of XScreenSaver is 5.37 and on the lock screen it is showing "This version of XScreenSaver is very old! Please upgrade!".

---

**Comment by andrewdavidwong** [comment] 2019-01-04 01:59
Duplicate of #3727

**Comment by andrewdavidwong** [comment] 2019-01-04 02:00
> The version of XScreenSaver is 5.37 and on the lock screen it is showing "This version of XScreenSaver is very old! Please upgrade!".

This is covered by #3652.

**Comment by andrewdavidwong** [comment] 2019-01-04 02:00
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-01-04 02:00 UTC
