### ISSUE TITLE
Running qubes are sometimes missing from Qubes widgets

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#8373] opened 2023-07-28 23:54 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.2

### Brief summary
The Qubes Domain widget is missing at least one of my running AppVM.

### Steps to reproduce

1. Boot Qubes
2. start some AppVM
3. right-click on Qubes Domain Widget
4. Verify that all running AppVm are present in the list: bug if not

### Expected behavior

I expect all running AppVM to be present in the list.
This also affects the ability to assign USB devices to AppVM.  The first time I noticed this I was trying to assign a YubiKey to a running AppVM and it was not present in the list.

### Actual behavior

One or more AppVM are missing.  In screenshot, the AppVM "beto" is missing, but it can be seen to be running from the `Qubes Manager`.  It really is running.

I note that this was identified previously, and closed as a dup of another bug which was also closed as fixed back in 2022.
This is a newly installed system (with old 4.1.2 system backup re-installed).  Just ran `qubes-dom0-update` and nothing updated, so I am reasonably sure I have the fixes from 2022 applied.

![Screenshot_2023-07-29_09-33-32](https://github.com/QubesOS/qubes-issues/assets/2313876/adbf1dbd-8e42-49a4-ac89-556a6c1b3cec)

**Comment by andrewdavidwong** [comment] 2023-07-29 23:24
> I note that this was identified previously, and closed as a dup of another bug which was also closed as fixed back in 2022.

Sounds like a possible duplicate of #7362.

> This is a newly installed system (with old 4.1.2 system backup re-installed). Just ran qubes-dom0-update and nothing updated, so I am reasonably sure I have the fixes from 2022 applied.

Even so, if this is the same bug, then we should reopen that issue.

But there still isn't enough information to tell whether it's the same bug, as far as I can tell.

Please read through #7362 and see whether that matches your situation. In particular, please specify whether happens only when starting things concurrently or whether it also happens when the missing VM is the only thing recently started.

**Comment by permezel** [comment] 2023-07-31 01:01
I looked at #7326.  Does not appear to match my situation.  I do not start Qubes Manager.  I do not have any auto-start things.
```
[nimda@dom0 ~]$ find ~/.config/ | grep start
[nimda@dom0 ~]$ 
```

Just powered on my system.  I have 12 qubes which do start automatically due to "start qube automatically on boot" being set.  I verified that all were present in the Qubes-Domain menu.
I then opened a terminal on dom0, and ran `qvm-start passwords`.  After `passwords` started, I found that the `beto-email` vm has been lost from the list.  See the screen scrapes.
The `passwords` VM was the one I first observed this problem on, as that was the one I was wanting to assign the Yubikey to, but at that time, it was missing from the menu list.

![Screenshot_2023-07-31_10-40-00](https://github.com/QubesOS/qubes-issues/assets/2313876/ce1e4176-e5b9-41fd-b4a1-dabc22e3e3a5)
![Screenshot_2023-07-31_10-41-31](https://github.com/QubesOS/qubes-issues/assets/2313876/6c97ab8f-a16d-4992-8eca-62844a26a596)

**Comment by permezel** [comment] 2023-07-31 01:33
I just remove the "start qube automatically on boot" setting on the `sys-firewall-02-mgmt` as I no longer use it.
Rebooted.
All qubes are in the list.
![Screenshot_2023-07-31_11-27-08](https://github.com/QubesOS/qubes-issues/assets/2313876/c432c5f8-a642-4a25-8ab5-729cf1d48e54)

Unsure what this implies, but another data point.

**Comment by permezel** [comment] 2023-08-01 08:04
Another data point.  Just rebooted, with the same 11 AppVM as above, and `admin-aws` is missing.
![Screenshot_2023-08-01_17-57-33](https://github.com/QubesOS/qubes-issues/assets/2313876/344d3a03-e7ad-4fbc-976d-aaff9a4f411c)

**Comment by marmarta** [comment] 2023-08-01 12:25
I think this means some events get lost. Theoretically, we do a complete refresh of the menu once connection to the event dispatcher is established, but this looks like it doesn't really work and some events are lost.
Or it's a cache problem...

**Comment by marmarta** [comment] 2023-08-01 12:30
I pushed a putative fix; can't really reproduce this directly (I'm running out of RAM before I get to a problematic amount fo qubes), but I thiiiiiink this might help?

**Closed** 2023-08-05 13:48 UTC
Labels: T: bug, C: manager/widget, P: default, diagnosed, pr submitted
