### ISSUE TITLE
Backing up a qube does not save its registered u2f keys

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8344] opened 2023-07-09 15:10 UTC
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Backing up a qube does not save its registered u2f keys.

### Steps to reproduce

Back up a qube and then restore it on a different Qubes installation.

### Expected behavior

The list of registered u2f keys is restored.

### Actual behavior

The list of registred u2f keys is not restored.

**Comment by marmarek** [comment] 2023-07-09 15:27
Duplicate of https://github.com/QubesOS/qubes-issues/issues/3550

**Closed by marmarek** 2023-07-09 15:27 UTC
Labels: T: bug, P: default

**Comment by DemiMarie** [comment] 2023-07-09 16:37
> Duplicate of #3550

This issue is a duplicate of #3550 inasmuch as set of registered u2f keys is stored in qrexec policy, but that’s an implementation detail of the current code.  In particular, #3550 seems to be incompatible with paranoid backup & restore mode, whereas this is not.

**Comment by marmarek** [comment] 2023-07-09 16:50
> whereas this is not.

I don't agree. Gaining access to arbitrary U2F key is not something that a VM restored from a compromised system (via paranoid restore) should be able to get.
This is really a duplicate.

**Comment by andrewdavidwong** [comment] 2023-07-10 11:05
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
