### ISSUE TITLE
LVM Pool metadata default size is too small

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5054] opened 2019-05-28 11:54 UTC
**Qubes OS version**
R4.01 current testing

**Affected component(s) or functionality**
System stability - filesystems

**Brief summary**
It is possible for the LVM Thin Pool to approach/reach a full state on a running system without a method to resolve, leading to catastrophic results

**To Reproduce**
Unclear but several R4.0x users, including @tasket have run into the issue (thread: https://groups.google.com/forum/#!topic/qubes-users/qq_ElNPdx-g )

**Expected behavior**
1. Installation of a non-server OS should be configured with somewhat more user-oriented (e.g. non-sysadmin) default values such that system usage doesn't unexpectedly produce catastrophic results

2 Warning to be emitted when approaching potentially unrecoverable storage situations and user guided to 

**Actual behavior**
System stops responding. On reboot VMs cannot start up or even boot up. Typical user actions to resolve may may situation worse.

**Solutions you've tried**
N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I did not see anything addressing the issue on https://www.qubes-os.org

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5053

**Comment by andrewdavidwong** [comment] 2019-05-29 02:10
Duplicate of #3243

**Comment by andrewdavidwong** [comment] 2019-05-29 02:10
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2019-05-29 02:10 UTC
Labels: P: default, T: bug
