### ISSUE TITLE
R4.1(x86_64) qubes-updater fails for qubes-template-debian-11

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6251] opened 2020-12-03 00:51 UTC
This issue affects Qubes Updater on R4.1(x86_64).

```
Updating debian-11

Error on updating debian-11: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=debian-11', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
debian-11:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:
```

### Steps to reproduce
1. Install the template in dom0 e.g. `qubes-dom0-update qubes-template-debian-11` 
2. Try to update it through `Qubes Updater` and expect failure

### Hypothesis
Debian-11 doesn't provide access point for qubes-updater through SSH?

### Additional info
qubes-template-debian-11 is by default creating a disposable VM that opens `/bin/sh` to run `xterm`, unknown why.

**Comment by andrewdavidwong** [comment] 2020-12-04 06:12
Duplicate of #6188

**Comment by andrewdavidwong** [comment] 2020-12-04 06:12
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-12-04 06:12 UTC
Labels: P: default, T: bug
