### ISSUE TITLE
Firewall: Adding unresolvable domain name breaks connectivity in AppVM

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#5711] opened 2020-03-07 20:51 UTC
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
AppVM Firewall

**Brief summary**
Using the _Limit outgoing internet connections to..._ function I configured the firewall of my AppVM to only allow connections to certain domains. This worked for some time but at some point (while adding more and more domains) my AppVM lost connectivity to **every** domain, even whitelisted ones. Setting the Firewall back to _Allow all outgoing internet connections_ did not help either.

It turned out I added one domain that could not be resolved to an IP address. This breaks connectivity immediately, no domains can be reached anymore. Removing the invalid domain re-establishes connectivity.

**To Reproduce**
1. Open an AppVMs _Qube Settings_
2. Select the _Firewall rules_ tab
3. Select _Limit outgoing internet connections to..._
4. Add the unresolvable domain _invalidhost_, with default settings
5. Add the resolvable domain _www.qubes-os.org_, with default settings
6. Open Firefox, enter _www.qubes-os.org_ in the address bar and hit Return
7. It will timeout

Note: Connectivity won't return even when disabling the domain filter by setting _Allow all outgoing internet connections_ as long as the invalid domain is in the list.

Note: when testing remember to close the browser/clear history/etc. between tests because there seems to be caching involved which makes sites appear loading when in fact they wouldn't be when opening them for the first time.

**Expected behavior**
I expect unresolvable domains not to break connectivity.

**Actual behavior**
Unresolvable domains break connectivity.

**Comment by heinrich-ulbricht** [comment] 2020-03-07 20:57
Narf. After writing this I knew what to search for in the list of open tickets. This seems to be a duplicate of #5269.

**Comment by andrewdavidwong** [comment] 2020-03-09 12:52
> Narf. After writing this I knew what to search for in the list of open tickets. This seems to be a duplicate of #5269.

Could you elaborate on why you think this is a duplicate of #5269? It is not obvious to me.

**Comment by heinrich-ulbricht** [comment] 2020-03-09 16:33
@andrewdavidwong #5269 describes that adding a "nonsensical domain" like _nonexistent.foobar_ causes all traffic to be filtered. And in [one of his comments](https://github.com/QubesOS/qubes-issues/issues/5269#issuecomment-524542524) Marek says that this is working as intended. This seems to describe what I am observing.

**Comment by andrewdavidwong** [comment] 2020-03-12 13:14
> @andrewdavidwong #5269 describes that adding a "nonsensical domain" like _nonexistent.foobar_ causes all traffic to be filtered. And in [one of his comments](https://github.com/QubesOS/qubes-issues/issues/5269#issuecomment-524542524) Marek says that this is working as intended. This seems to describe what I am observing.

Ah, but #5269 is primarily about a different topic, so I think it's more appropriate to close this as `not an issue` because, as you pointed out, it's working as intended.

**Closed by andrewdavidwong** 2020-03-12 13:14 UTC
Labels: C: core, P: default, T: bug

**Comment by heinrich-ulbricht** [comment] 2020-03-17 21:07
Yes and a change of this behavior would be much appreciated. But that is already being discussed over at the other ticket.
