### ISSUE TITLE
Error Message when Updating Whonix Templates over sys-whonix

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6983] opened 2021-10-18 04:20 UTC
### Qubes OS release
R4.1

### Brief summary
After updating either whonix template over tor using sys-whonix, an error message popups when template is shutting down:
"Denied: whonix.NewStatus Denied whonix.NewStatus+whonix-gw-16_shutdown from whonix-gw-16 to sys-whonix"
"Denied: whonix.NewStatus Denied whonix.NewStatus+whonix-ws-16_shutdown from whonix-ws-16 to sys-whonix"

### Steps to reproduce
Update a whonix template over tor using the qubes updater.  Either the gateway or workstation.

### Expected behavior
No error popup.

### Actual behavior
Error message popup when attempting shutdown.

![2021-10-17_22-56-52](https://user-images.githubusercontent.com/38737447/137667537-84af0e32-ae54-4b5c-8bc8-32cd21b3f04d.jpg)
![2021-10-17_23-08-31](https://user-images.githubusercontent.com/38737447/137667988-f1e27d8b-8154-4d67-868e-9e7accff8585.jpg)

### Additional Information
This doesn't seem to affect anything negatively, just the red error popup shows up.  The template still shuts down automatically.

**Comment by adrelanos** [comment] 2021-10-20 16:08
How was Qubes-Whonix 16 initially installed? Did you install using https://www.whonix.org/wiki/Qubes/Install / using `qubesctl` (Qubes salt) or using Qubes installer during Qubes operating system installation?

related:
https://github.com/QubesOS/qubes-issues/issues/6890

**Comment by zellchristensen** [comment] 2021-10-21 00:40
Via the Installer by clicking the checkbox when configuring Qubes for its first boot.  It seems to happen any time a whonix template is started and shut down.

**Comment by marmarek** [comment] 2021-11-07 13:21
The [policy](https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubes-rpc-policy/whonix.NewStatus.policy) allows the call only to qubes with `anon-vm` tag, but I think nothing adds this tag to the Whonix templates themselves (only to qubes based on those templates). 
@adrelanos what is the intended situation here? I see those options:
1. Templates should not make that call at all (they don't have netvm connected, only updates proxy access, so I think time sync would fail anyway)
2. (Whonix) templates should be allowed by having `anon-vm` tag too.
3. (Whonix) templates should be allowed by explicitly naming them in the policy (and should not have the `anon-vm` tag).

**Comment by adrelanos** [comment] 2021-11-10 10:11
Will get back to this shortly.

**Comment by adrelanos** [comment] 2021-11-10 10:19
Good question... Looking up development notes...

https://www.whonix.org/wiki/Dev/Qubes#qvm-tags

I think the name of the tag `anon-vm` implies that it's for anonymous VMs only. VMs here implying App Qubes and not "technically any VM (including Templates)". While Whonix Templates updates are routed over Tor, these VMs itself shouldn't be used for as anonymous activities. Only App Qubes based on these Templates should.

By overloading the meaning of `anon-vm` nowadays, it could become confusing in the future what permissions go with it and which permissions shouldn't go with it. Otherwise, I think we would have called that tag simply `anon` perhaps (more generic, avoid saying `whonix` in case ever similar templates are maintained in Qubes).

So if in the future we needed a tag for Whonix Templates, we should probably call it `anon-template`. At the time of writing, by design, sdwdate doesn't run inside Whonix Templates anyhow.

```
user@host:~$ sudo systemctl status sdwdate
● sdwdate.service - Secure Distributed Web Date
     Loaded: loaded (/lib/systemd/system/sdwdate.service; enabled; vendor preset: enabled)
    Drop-In: /usr/lib/systemd/system/sdwdate.service.d
             └─20_arch_syscall_whitelist.conf, 40_qubes.conf
     Active: inactive (dead)
  Condition: start condition failed at Wed 2021-11-10 10:16:01 UTC; 11s ago
             └─ ConditionPathExists=!/run/qubes/this-is-templatevm was not met
       Docs: https://www.whonix.org/wiki/sdwdate

Nov 10 10:16:01 host systemd[1]: Condition check resulted in Secure Distributed Web Date being skipped.
```

If that ever gets a more clever implementation (asking time from sys-whonix perhaps without running their own instance of sdwdate), all of this could be re-considered, re-designed.

Therefore...

@marmarek 
> I see those options:
> 1. Templates should not make that call at all (they don't have netvm connected, only updates proxy access, so I think time sync would fail anyway)

That seems best. Will work on it.

**Comment by adrelanos** [comment] 2021-11-10 10:32
The question is, why isn't this happening in Qubes R4 but in Qubes R4.1?

sdwdate-gui shouldn't be running inside Templates. Can you confirm it is running in Template?

    ps aux | grep sdwdate-gui

If running, then we get closer to diagnose this issue. Running on the assumption...

Related source code files:

* [`/etc/xdg/autostart/sdwdate-gui.desktop`](https://github.com/Whonix/sdwdate-gui/blob/master/etc/xdg/autostart/sdwdate-gui.desktop)
* [`/usr/libexec/sdwdate-gui/start-maybe`](https://github.com/Whonix/sdwdate-gui/blob/master/usr/libexec/sdwdate-gui/start-maybe)

I suspect `/usr/libexec/sdwdate-gui/start-maybe` starts sdwdate-gui even though it should not. Did the output of

    qubesdb-read /qubes-vm-type

change? Could someone run this in Template please?

Expected output:

> TemplateVM

----

related:
https://github.com/QubesOS/qubes-issues/issues/6890

**Comment by marmarek** [comment] 2021-11-10 14:17
> The question is, why isn't this happening in Qubes R4 but in Qubes R4.1?

It is happening in both, it's simply easier to miss in R4.0, because we didn't have policy deny notification there (but you can find the message in dom0's journalctl).

What's interesting, this seems to happen only during the very first template start only (the one during template installation), but not later. I'm not sure what could be different at that stage...

**Comment by andrewdavidwong** [comment] 2021-11-11 04:27
> > The question is, why isn't this happening in Qubes R4 but in Qubes R4.1?
> 
> It is happening in both, it's simply easier to miss in R4.0, because we didn't have policy deny notification there (but you can find the message in dom0's journalctl).

Updated milestone to earliest affected release (4.0).

**Comment by adrelanos** [comment] 2021-11-11 20:59
Excellent. Fixed in git and uploaded to testers and stable-proposed-updates just now.

**Comment by marmarek** [comment] 2021-11-13 21:51
I can confirm with sdwdate-gui 7.3 the `sdwdate-gui-shutdown-notify.service` is properly disabled in templates and the spurious policy deny is gone.

**Closed by marmarek** 2021-11-13 21:51 UTC
Labels: T: bug, C: Whonix, P: default, diagnosed

**Comment by adrelanos** [comment] 2021-11-14 08:42
Great. This fix is now in all Whonix repositories.

**Comment by Minimalist73** [comment] 2021-11-15 12:41
![2021-11-15-131633](https://user-images.githubusercontent.com/51658826/141780953-aee0c807-fc53-4eba-8ad3-5c1206d20101.png)

Different error message but it seems related to this issue.
This error appears everytime I close a dispvm using the ws-dvm
Running Qubes 4.1 and Whonix 16 downloaded with `qvm-template-gui` & `qubesctl` (salt)
Both WS et GW templates are updated.

**Comment by DemiMarie** [comment] 2021-11-15 14:30
@Minimalist73 A qrexec call can fail because the destination VM does not exist, which is happening in this case.  This is a race condition that should really be fixed.

**Comment by Minimalist73** [comment] 2021-11-15 15:17
> @Minimalist73 A qrexec call can fail because the destination VM does not exist, which is happening in this case. This is a race condition that should really be fixed.

Should I make a new issue regarding this error or is this one enough?

**Comment by DemiMarie** [comment] 2021-11-15 16:39
> > @Minimalist73 A qrexec call can fail because the destination VM does not exist, which is happening in this case. This is a race condition that should really be fixed.
> 
> Should I make a new issue regarding this error or is this one enough?

Please make a new issue.
