### ISSUE TITLE
Performance regression in Qubes R4.0

### ISSUE THREAD

**Issue by archfan** [QubesOS/qubes-issues#3867] opened 2018-04-29 12:25 UTC
### Qubes OS version:
R4.0
[dmesg.txt](https://github.com/QubesOS/qubes-issues/files/1958711/dmesg.txt)

### Affected component(s): 

?
[logs.zip](https://github.com/QubesOS/qubes-issues/files/1958710/logs.zip)

---

### Steps to reproduce the behavior:

Install Qubes R4.0 on
Asrock H170M Pro4 (VT-D is enabled, ME has been disabled w/ me-cleaner)
i7-6700
16 GB RAM

### Expected behavior:

Performance should be acceptable.

### Actual behavior:

Performance is slow. 

### General notes:

There is a serious regression in Qubes R4.0. The first time setup (where it creates the templates) after the Qubes OS installation took around 2 hours. The personal VM doesn't start or takes an unreasonable amount of time to load up. The whole system feels sluggish and unresponsive. I've installed all dom0 updates as well and restarted. It did not solve the problem.

Qubes R3.2 runs fine in comparision. I've had no performance problems with it.

---

**Comment by JPL1** [comment] 2018-04-29 13:14
For what it's worth I haven't experienced any slowdown between running and installing r4.0 and r3.2. 

i7 4th gen HP EliteDesk PC, Qubes mounted on USB 3 stick.

**Comment by archfan** [comment] 2018-04-29 14:41
Yes, I'm also running it on a Thinkpad T440s. It runs flawlessly on there but not on my main desktop. 

Could it be a kernel or xen regression? Perhaps it might have something to do with the newly introduced PVH mode.

**Comment by andrewdavidwong** [comment] 2018-04-29 18:37
Duplicate of #3639

**Comment by andrewdavidwong** [comment] 2018-04-29 18:37
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2018-04-29 18:37 UTC
