### ISSUE TITLE
qubes-dom0-update error on anaconda-core or kernel-qubes-vm

### ISSUE THREAD

**Issue by adubois** [QubesOS/qubes-issues#3694] opened 2018-03-13 06:35 UTC
### Qubes OS version:
Qubes release 4.0 (R4.0)

### Affected component(s): 

qubes-dom0-update
anaconda-core-1000:25.20.9-10.fc25.x86_64
   -> anaconda-core-1000:25.20.9-11.fc25.x86_64
kernel-qubes-vm-1000:4.9.56-21.pvops.qubes.x86_64
   -> kernel-qubes-vm-1000:4.14.18-1.pvops.qubes.x86_64

---

### Steps to reproduce the behavior:

on up to date R4.0rc4 system (rc5?) on 13th of March:
~~~
sudo qubes-dom0-update
~~~

### Expected behavior:

~~~
  Cleanup     : anaconda-core-1000:25.20.9-10.fc25.x86_64                 45/75 
  Erasing     : kernel-qubes-vm-1000:4.9.56-21.pvops.qubes.x86_64         46/75 
  Cleanup     : qubes-core-dom0-linux-4.0.10-1.fc25.x86_64                47/75 
~~~

### Actual behavior:

~~~
  Cleanup     : anaconda-core-1000:25.20.9-10.fc25.x86_64                 45/75 
usage: qvm-ls [-h] [--verbose] [--quiet] [--all] [--exclude EXCLUDE]
              [--help-columns] [--help-formats]
              [--format FORMAT | --fields FIELD,...] [--raw-data] [--spinner]
              [--no-spinner] [--raw-list] [--disk] [--network]
              [VMNAME [VMNAME ...]]
qvm-ls: error: unrecognized arguments: --kernel
  Erasing     : kernel-qubes-vm-1000:4.9.56-21.pvops.qubes.x86_64         46/75 
  Cleanup     : qubes-core-dom0-linux-4.0.10-1.fc25.x86_64                47/75 
~~~

### General notes:

Note sure of the impact at this stage. I have not rebooted. Going to do a backup before restarting...

---

**Comment by adubois** [comment] 2018-03-13 08:00
No issue after 1st reboot. From user point of view, it can probably be closed. Possible some clean-up did not happen.

**Comment by SaswatPadhi** [comment] 2018-03-13 08:12
I didn't install rc5 fresh, but I have upgraded from rc4 to rc5, and I don't notice this behavior ...

**Comment by unman** [comment] 2018-03-14 16:34
I dont see this on a clean install rc5.
@adubois - I think you can close this issue

**Comment by andrewdavidwong** [comment] 2018-03-15 05:17
Closing this for now as "cannot reproduce." If you believe this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Closed by andrewdavidwong** 2018-03-15 05:17 UTC
Labels: C: core, bug
