### ISSUE TITLE
Arch Linux template build missing pulseaudio version 13.99.3

### ISSUE THREAD

**Issue by huertanix** [QubesOS/qubes-issues#6219] opened 2020-11-21 03:50 UTC
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Arch Linux template build

**Brief summary**

When attempting to build an Arch Linux template, `make qubes-vm` fails due to the prerequisite pulseaudio-13.99.3 directory missing from `qubes-src/gui-agent-linux/pulse`. This is similar in nature to #4109.

**How Reproducible**

Predictably reproducible.

**To Reproduce**

1. Follow the steps in the [Archlinux template building instructions](https://www.qubes-os.org/doc/building-archlinux-template/) up to the `make qubes-vm` command.
2. Run the `make qubes-vm` command.
3. Observe error

**Expected behavior**

`make qubes-vm` should build as expected in the aforementioned guide.

**Actual behavior**

`make qubes-vm` attempts to create a symlink to a `qubes-src/gui-agent-linux/pulse/pulsecore-13.99.3` directory which does not exist, leading to this error:

> ...
> rm -f pulse/pulsecore
> ln -s pulsecore-13.99.3 pulse/pulsecore
> make -C pulse module-vchan-sink.so
> make[1]: Entering directory '/home/user/qubes-src/gui-agent-linux/pulse'
> gcc -Wall -Wextra -Werror -O2 -g -c `pkg-config --cflags vchan-xen` -fPIC module-vchan-sink.c  -DHAVE_CONFIG_H -I.
> module-vchan-sink.c:64:10: fatal error: pulsecore/core-error.h: No such file or directory
>    64 | #include <pulsecore/core-error.h>
>   |          ^~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[1]: *** [Makefile:12: module-vchan-sink.o] Error 1
> make[1]: Leaving directory '/home/user/qubes-src/gui-agent-linux/pulse'
> make: *** [Makefile:66: pulse/module-vchan-sink.so] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
> make[2]: *** [/home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:134: dist-package] Error 4
> make[1]: *** [Makefile.generic:191: packages] Error 1
> make: *** [Makefile:246: gui-agent-linux-vm] Error 1 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/building-archlinux-template/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#4109

**Comment by RaphaelBalthazar** [comment] 2020-11-21 06:50
Looks like a duplicate of #6172

**Comment by andrewdavidwong** [comment] 2020-11-21 15:17
Duplicate of #6172

**Comment by andrewdavidwong** [comment] 2020-11-21 15:17
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Closed by andrewdavidwong** 2020-11-21 15:17 UTC
Labels: P: default, T: bug
