### ISSUE TITLE
Whonix WS 16 sometimes fails to install, sometimes with full system freeze

### ISSUE THREAD

**Issue by CrsiX** [QubesOS/qubes-issues#6930] opened 2021-10-03 14:59 UTC
_**UPDATE:** Just re-attempting the installation worked. After four or five failed installations (during the one installation that should give me the exact error message), it just completed successfully. However, I still decided to open the issue. Maybe someone else has that problem too._

### Qubes OS release

R4.0.4

### Brief summary

Installing Whonix Workstation 16 fails (the gateway template just installed fine!). Some of the attempts even resulted in a full system freeze.

At first, [the Whonix wiki](https://www.whonix.org/wiki/Qubes/Install) only contained the step `sudo qubesctl state.sls qvm.anon-whonix` to update to version 16, without installing the template package as manual step. This command alone froze my system multiple times without any specific logs, warning, returns etc. However, the wiki was updated to do `sudo qubes-dom0-update qubes-template-whonix-gw-16 qubes-template-whonix-ws-16` beforehand. This way, the gateway template installed fine, but the workstation template didn't.

I have the following error message:

```
whonix-ws-16: Importing data

Traceback (most recent call last):
  File "/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 235, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 98, in import_root_img
    raise qubesadmin.exc.QubesException('root.img extraction failed')
qubesadmin.exc.QubesException: root.img extraction failed
Warning: %post(qubes-template-whonix-ws-16-4.0.6-202109211111.noarch) scriptlet failure, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package qubes-template-whonix-ws-16
Non-fatal POSTIN scriptlet failure in rpm package qubes-template-whonix-ws-16
```

Note: Removing the package and re-installing it (`sudo dnf remove qubes-template-whonix-ws-16`) only worked after manually creating a template qube named `whonix-ws-16` (which was just the clone of some random template) and forcefully removing the directory `/var/lib/qubes/vm-templates/tmp-whonix-ws-16/`, so that the uninstall procedure doesn't fail to remove a non-existing template qube.

Regarding the system freeze: During almost any dom0 package installation, I have intense lags where even moving the mouse coursor has a delay of some seconds (!) - but that's fine as long as it works.

### Steps to reproduce

1. Enable the `qubes-templates-community` yum repository
2. `sudo qubes-dom0-update`
3. `sudo qubes-dom0-update qubes-template-whonix-gw-16 qubes-template-whonix-ws-16`

### Expected behavior

Installation of the two templates completes successfully.

### Actual behavior

One template installs fine, the other one fails (sometimes with the shown error, sometimes with a full system freeze).

**Comment by brendanhoar** [comment] 2021-10-03 15:24
Possibly default-sized sys-firewall space issue downloading two templates in one run triggers other issues?

**Comment by CrsiX** [comment] 2021-10-03 17:45
I had >6GiB free, usable disk space in sys-firewall. Additionally, the download of the files took place _before_ that error happened, i.e. the relevant rpm files were already loaded into dom0, since the red color of the sys-firewall output had already ended.

**Comment by adrelanos** [comment] 2022-02-10 20:55
Closable?

> > The root issue however might be that Xen doesn't properly moderate the dom0 disk i/o, giving it maximum priority while disregarding anything else? Could that be a configuration that Qubes might add by default?
> 
> All disk I/O goes through dom0 by default, so it is not at all surprising that dom0 gives its own I/O priority. That said, deliberately throttling it during template installation is definitely a good idea.

Separate ticket for this?

Because I don't suggest re-purposing this ticket for that purpose. Seems hard to get from reading `Whonix WS 16 sometimes fails to install, sometimes with full system freeze` the idea to implement "throttle disk usage I/O during template installation".

**Comment by andrewdavidwong** [comment] 2022-02-11 01:05
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Closed** 2022-02-11 01:06 UTC
Labels: T: bug, C: other, R: not an issue, P: default

**Comment by adrelanos** [comment] 2022-02-14 13:09
Created https://github.com/QubesOS/qubes-issues/issues/7268 for it.
