### ISSUE TITLE
Template Update Notification

### ISSUE THREAD

**Issue by cmschube** [QubesOS/qubes-issues#3746] opened 2018-03-26 14:47 UTC
### Affected component(s): 

Qube-Manager

---

### Steps to reproduce the behavior:

1.  Update a Template VM
2.  Check for restart icon on Child Template VM

### Expected behavior:

Child VMs created from that Template should show the "Restart" icon to inform the user that there are pending changes to the underlying template. 

### Actual behavior:

No notification given

### General notes:

---

### Related issues:

Don't know if this is related to #3745 or not..

**Comment by marmarta** [comment] 2018-03-30 16:28
Have you refreshed the VM list after updating template?

**Comment by marmarta** [comment] 2018-07-15 22:54
I cannot reproduce it with the current, dbus-based version of Qube Manager. I'll close this issue, but please do not hesitate to reopen it if the problem persists.

**Closed by marmarta** 2018-07-15 22:54 UTC
Labels: C: qubes-manager, bug
