### ISSUE TITLE
Windows do not display for sys-whonix and other whonix-gw-15 based VMs in Qubes 4.1.

### ISSUE THREAD

**Issue by Timothy-S-P-Capehart** [QubesOS/qubes-issues#6545] opened 2021-04-20 23:32 UTC
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

Any Qube based on whonix-gw-15 template.

**Brief summary**

When attempting to use sys-whonix or any VM based on the whonix-gw-15, no graphics from the VM are displayed. Text output can be seen if using `qvm --pass-io sys-whonix (command)` or if using the "open console in qube" option in Qube Manager.

When an affected VM is shutdown, a notification is displayed which reads:
`Denied: whonix.NewStatus+sys-whonix_shudtown from sys-whonix to sys-whonix` or something similar.

Oddly the template itself does not have the same problem.

The guid.sys-whonix.log reads:

Icon size: 128x128
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x1c00007
                 Failed serial number:  1140
                 Current serial number: 1141
XShmAttach failed for window 0x4a001d5(remote 0xe00006)
ErrorHandler: BadValue (integer parameter out of range for operation)
                 Major opcode: 12 (X_ConfigureWindow)
                 Value:        0x0
                 Failed serial number:  1162
                 Current serial number: 1165

**How Reproducible**

Every attempt to run GUI programs has failed.

**To Reproduce**

Start any GUI program in a Qube based on whonix-gw-15.

**Expected behavior**

The window from the program opens.

**Actual behavior**

No window is displayed. 

**Screenshots**

Not sure how to add any, but I would be happy to post some if needed.

**Additional context**

Qubes based on all other templates work as expected, including those based on whonix-ws-15.

**Solutions you've tried**

Starting programs using `qvm --pass-io sys-whonix (command)`
Making new qubes based on the whonix-gw-15 template.
Reinstalling the template.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

I have not found anything that seems relevant.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by adrelanos** [comment] 2022-02-10 20:48
I never experienced this issue and I cannot reproduce this at this time.

Is this issue still reproducible?

> When attempting to use sys-whonix or any VM based on the whonix-gw-15, no graphics from the VM are displayed.

> The guid.sys-whonix.log reads:
> 
> Icon size: 128x128 ErrorHandler: BadAccess (attempt to access private resource denied) Major opcode: 130 (MIT-SHM) Minor opcode: 1 (X_ShmAttach) ResourceID: 0x1c00007 Failed serial number: 1140 Current serial number: 1141 XShmAttach failed for window 0x4a001d5(remote 0xe00006) ErrorHandler: BadValue (integer parameter out of range for operation) Major opcode: 12 (X_ConfigureWindow) Value: 0x0 Failed serial number: 1162 Current serial number: 1165

This does not seem like a bug that Qubes-Whonix would introduce. Seems more like a Qubes GUI implementation bug.

Not sure the `C: Whonix` is appropriate here. Not sure something I would be able to help with.

----

> When an affected VM is shutdown, a notification is displayed which reads: `Denied: whonix.NewStatus+sys-whonix_shudtown from sys-whonix to sys-whonix` or something similar.

Separate issue, see:

* https://github.com/QubesOS/qubes-issues/issues/7013

**Comment by DemiMarie** [comment] 2022-02-10 23:36
Closing as “cannot reproduce”.  @Timothy-S-P-Capehart feel free to reopen if it still happens, though Whonix 15 is end of life.

**Closed by DemiMarie** 2022-02-10 23:36 UTC
Labels: T: bug, C: gui-virtualization, P: default, needs diagnosis

**Comment by Timothy-S-P-Capehart** [comment] 2022-04-04 22:17
Sorry for the delayed reply. I returned the machine since I didn't have much use for it if I couldn't use it for Qubes reliably, so I'm not sure if it is still reproducible. 

I've reverted to using Qubes-OS 4.0 on a different machine.
Thanks for trying to help though. Sorry I couldn't provide better information.
