### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4621] opened 2018-12-16 14:19 UTC
### Qubes OS version:

`R4.0`

### Affected component(s): 

Qubes update system

---

### Steps to reproduce the behavior:

Wait for updates to be available for any Qubes template, or for dom0

### Expected behavior:

Qubes pops up an alert with options like

* Update this VM, and prompt in the future when updates are available.
* Update this VM, and automatically apply updates in the future.  You may change this by &lt;insert instructions&gt;.
* Do not update this VM (NOT RECOMMENDED).

### Actual behavior:

No pop-up, and no way to enable automatic installation of updates when they become available.

### General notes:

Qubes should handle updates at least as well as Windows.

---

**Comment by DemiMarie** [comment] 2018-12-16 14:33
@unman I absolutely agree with the clear visual indicator.

**Comment by andrewdavidwong** [comment] 2018-12-17 00:58
Duplicate of #2718

**Comment by andrewdavidwong** [comment] 2018-12-17 00:58
@DemiMarie, FYI, you previously filed a very a similar: #4282.

Like that one, this is a duplicate of #2718.

**Comment by andrewdavidwong** [comment] 2018-12-17 00:59
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment] 2018-12-17 01:06
Reopening as a feature request for a GUI frontend for the cron functionality described in

> We have a CLI way to update VMs (which can be added to cron)

**Comment by andrewdavidwong** [comment] 2021-05-22 19:36
Actually, I no longer believe that this is a duplicate of #2718, since automatic updates are not the same as a tool for performing multiple updates at the same time. Moreover, a GUI frontend for cron functionality is also not the same as automatic updates.

Instead, I now think this is a duplicate of #4282, which I no longer believe to be a duplicate of #2718.

**Closed by andrewdavidwong** 2021-05-22 19:36 UTC
Labels: C: updates, P: major, T: enhancement, ux
