### ISSUE TITLE
Installer for Qubes-4.1-rc1 can not be started on a device protected by secure boot

### ISSUE THREAD

**Issue by grince** [QubesOS/qubes-issues#7034] opened 2021-11-04 09:22 UTC
### Qubes OS release

4.1-rc1

### Brief summary
when I try to start the Qubes-OS Installer via USB on a secure-boot-secured device, the installer doesn't start. since I am able to start the debian-installer with a signed kernel, I think that the installer doesn't use a kernel which is signed from a device-trusted CA and is therefore not able to start.

### Steps to reproduce
I tried starting the installer on a Microsoft Surface Pro 8. just create an usb-stick with the installer and try to boot from usb.

### Expected behavior
start of the installer to install Qubes-OS on the device (or at least check the requirements cpu-wise ;)

### Actual behavior
doesn't boot from usb

**Comment by marmarek** [comment] 2021-11-04 10:04
Duplicate of #4371

**Closed by marmarek** 2021-11-04 10:04 UTC
Labels: T: bug, P: default
